### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by Scott-Fischer** [mjmlio/mjml#10]
After installing MJML globally via npm, I get the following error message when running any command in the cli:

$ mjml -r input.mjml
ReferenceError: engine is not defined
    at /usr/local/lib/node_modules/mjml/lib/cli.js:86:12

I do not get any sort of error messages while installing. I also tried running the installer with sudo and the cli commands with sudo and both situations reproduced the error above.

**Comment by arnaudbreton** [comment]
Hi @Scott-Fischer,

Thanks for reaching out and sorry your first experience with MJML was not a successful one. There was a typo in a code we merged before the release that we just managed to identify. The fix is almost ready and will be released shortly.

Keep you posted.
Thanks for your patience.

**Comment by Scott-Fischer** [comment]
Thanks man! I'm actually just glad it wasn't an issue with my local node/npm installation.

As a full time email developer, you have no idea how excited I am to get this up and running!

**Comment by arnaudbreton** [comment]
Haha, can feel some bad past experience here.

I'm glad to read that you're at least as excited as we are to have released MJML :)!

**Comment by arnaudbreton** [comment]
@Scott-Fischer, there it is https://github.com/mjmlio/mjml/tree/v1.0.2

Hope it works for you and apologies for the false start..

**Comment by Scott-Fischer** [comment]
This resolved the issue. Thanks for the quick response!

**Comment by arnaudbreton** [comment]
@Scott-Fischer glad to hear. Can you please close this issue? Happy MJML-ing!
