### ISSUE TITLE
<Section> not applying padding attribute

### ISSUE THREAD

**Issue by Geczy** [mjmlio/mjml#1003]
I just want to render mjml via react by creating components using `mjml-section` etc

```js
import React from 'react'
import { convertRGBA } from '../../containers/Mjml'
import Section from 'mjml-section'
import Column from 'mjml-column'
import Text from 'mjml-text'

const Html = ({ options: { html, backgroundColor }, raw }) => (
  <Section padding="30" background-color={convertRGBA(backgroundColor.attributes.value)}>
    <Column>
      <Text font-size={30}>
        { raw || html.attributes.value }
      </Text>
    </Column>
  </Section>
)

export default Html
```
![image](https://user-images.githubusercontent.com/1036968/36562329-b0370398-17e4-11e8-9352-81accd990965.png)

![image](https://user-images.githubusercontent.com/1036968/36562289-851093be-17e4-11e8-9f93-c687466dcb5a.png)

Why is it ignoring all attributes I add? But attributes on `Text` working correctly, as you can see the font size is 30

**Comment by Geczy** [comment]
Adding padding-left works, but padding by itself does not

**Comment by Geczy** [comment]
I also can't seem to use react to dynamically update any of the settings, like `background-color` doesn't update after I change a variable. is this because of `postRender` being used in `Section`?

**Comment by iRyusa** [comment]
Hi @Geczy 
Well MJML component in v1/2/3 are React component but that doesn't mean you can use them inside a React context because of many fixes that are applied in pre/post-render.

Now in MJML4 we've dropped totally react from the stack anyway.
