### ISSUE TITLE
srcset is invalid

### ISSUE THREAD

**Issue by sallf** [mjmlio/mjml#1004]
Trying to use `srcset` in `<mj-image>` and am getting a 'srcset is invalid' error when I go to compile. Looks like it's no longer in `allowedAttributes`. Was this removed on purpose? Code below for reference:
```
<mj-column>
  <mj-image
    padding="0"
    src="image1.jpg"
    srcset="image1.jpg 900w, image2.jpg 1200w"
    alt=""
    href="https://example.com"
  />
</mj-column>
```
Thanks!

**Comment by kmcb777** [comment]
The fix has been merge we can close this one 👍
