### ISSUE TITLE
All text are not displayed

### ISSUE THREAD

**Issue by igorissen** [mjmlio/mjml#1009]
All text are not displayed.

**Reproduction Steps:**

1. Use the generated JSON : [mjml.json](https://gist.github.com/igorissen/b78b499dc27a1a0a719fae17ffac22f2#file-mjml-json)
2. Call the method `mjml.mjml2html(json, options)` with the JSON content and the options `{minify: true}`
3. Get the generated HTML : [mjml.html](https://gist.github.com/igorissen/b78b499dc27a1a0a719fae17ffac22f2#file-mjml-html)
4. Paste the result in a HTML file
5. Open the file in you favourite browser

**Expected behavior:**

This is the expected result with some text.

<img src="https://image.ibb.co/hmRg8H/Screen_Shot_2018_02_27_at_11_17_00.png" width="200px">

**Observed behavior:**

Only images are displayed.

<img src="https://image.ibb.co/crzq2c/Screen_Shot_2018_02_27_at_11_16_27.png" width="200px">

**Screenshots and GIFs**

As you can see, the text is in the html but not displayed.

<img src="https://image.ibb.co/iw2chc/Screen_Shot_2018_02_27_at_11_17_48.png" width="500px">

**MJML version:**

3.3.5

**Email clients the bug is seen on:**

I'm testing first in a browser by opening the HTML file before sending it.

**Comment by iRyusa** [comment]
Hi @igorissen 

This is an issue with quoted font name, remove quote in font-family and it will display fine (they are not needed most of the time) I think this has been fixed in MJML4 too ( might need to test it )

**Comment by igorissen** [comment]
Hi @iRyusa 

Thank you for the tip. It works now.
