### ISSUE TITLE
how to change brakepoint?

### ISSUE THREAD

**Issue by wireinet** [mjmlio/mjml#1012]
![how](https://user-images.githubusercontent.com/23517333/36781226-54f8f9b8-1c86-11e8-9824-1bc13bbe23d4.gif)
Hello! I have two pictures - in separate mj-columns and this brakes very early! Can i customize a brake point in this way

**Comment by ngarnier** [comment]
hey @wireinet, in MJML 4 you can customize the breakpoint with the `mj-breakpoint` component: https://github.com/mjmlio/mjml/blob/master/packages/mjml-head-breakpoint/README.md

Not sure to understand what you mean though about "breaks very clearly".

**Comment by wireinet** [comment]
ngarnier  - thank you! Dont knowed about new version!

**Comment by wireinet** [comment]
but...as i can see app is not a new - in offecial site - download for windows 2.6.0
Can you tell me how to get version MJML 4 ?

**Comment by ngarnier** [comment]
No worries! For now the only way is using MJML locally and installing with npm: https://github.com/mjmlio/mjml#installation

If you're not familiar with it, the best is to wait that we update the MJML App.

**Comment by wireinet** [comment]
Thank you! i use npm, but love app - its great! Thank you again for answers
