### ISSUE TITLE
mjml-core miss babel-runtime dep

### ISSUE THREAD

**Issue by natesilva** [mjmlio/mjml#1016]
The `mjml-core` module doesn’t work as a standalone module. It errors on import.

**Use case:** The main `mjml` module brings in a ton of dependencies that we don’t want (including `mjml-cli` which brings in the somewhat problematic `fsevents` via `chokidar`). We just need the `mjml2html()` function so I hoped to get that from `mjml-core`.

**Reproduction Steps:**

```shell
$ npm i mjml-core
   [ …usual install output… ]
$ node
> var mjmlCore = require('mjml-core');
Error: Cannot find module 'babel-runtime/helpers/toConsumableArray'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

**MJML version:**

4.0.0
Node: 8.9.4
NPM: 5.6.0

**Comment by matass** [comment]
hi @iRyusa 

I have added `babel-runtime (6.26.0)`, now I'm getting this error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Error in file /xxx/xxx.mjml: Cannot read property 'mj-container' of undefined
```

**Comment by iRyusa** [comment]
Really weird error considering that `mj-container` doesn't exist anymore, can you try to reinstall or provide the template to reproduce?

**Comment by matass** [comment]
I'm using `mjml-core` in my own package (https://github.com/matass/swu-mjml). so I'll try to make fresh mjml app and compile some templates

**Comment by iRyusa** [comment]
Looks like a dep issue in your project, you're using `mjml-core` 4.0 + gulp-mjml (MJML3.0 dep).

Note that gulp-mjml isn't up to date with MJML4

**Comment by matass** [comment]
Ok, thanks. I think I have to rollback to previous mjml-core version. Do You have any plans to make mjml-4 compatible with gulp-mjml?

**Comment by iRyusa** [comment]
Here https://github.com/mjmlio/gulp-mjml/issues/34 but we're focusing on MJML4 fixes before.

**Comment by kmcb777** [comment]
Hi @natesilva this has been fixed in the new release mjml4.2-beta, which you can install with npm install mjml, you can check if it solves the problem

**Comment by natesilva** [comment]
Thank you. It works.
