### ISSUE TITLE
Social Icons. Different Icon sizes

### ISSUE THREAD

**Issue by ebiasini** [mjmlio/mjml#1018]
I'm well aware of icon-size attribute but it applies to the whole set of icons.
Is it possible to serve for instance 4 icons sized 40x40 and 1 icon sized 120x40?

Thank you

**Comment by iRyusa** [comment]
Hi @ebiasini 

In mjml4, `mj-social-element` now support an `icon-size` attribute per social network it should do the trick ?

**Comment by hansnolte** [comment]
iRyusa was faster.

https://github.com/mjmlio/mjml/tree/master/packages/mjml-social


`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-social font-size="15px" icon-size="30px" mode="horizontal">
          <mj-social-element name="facebook" href="https://mjml.io/" icon-color="#4d4d4d">
            Facebook
          </mj-social-element>
          <mj-social-element name="google" href="https://mjml.io/" icon-color="#4d4d4d">
            Google
          </mj-social-element>
          <mj-social-element icon-size="120"  name="instagram" href="https://mjml.io/" icon-color="#4d4d4d">
            Instagram
          </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

**Comment by ebiasini** [comment]
Thanks. But this doesn't solve the rectangular size icon. Since there is only one icon-size I cant use a 120x40 social network logo.

**Comment by hansnolte** [comment]
Then make your own icon

<mj-social-element href="url" background-color="#FF00FF" src="path-to-your-icon">
      Optional label
    </mj-social-element>
