### ISSUE TITLE
"!" ending mj-text 

### ISSUE THREAD

**Issue by kaoze** [mjmlio/mjml#102]
Bonjour !
First, thanks so much for this awesome piece of code... 
Second, I second the request for the editor ;)
Then... a small bug compiling the following code 

      
	<mj-section background-color="#fafafa">
		<mj-text color="#fafafa" font-size="20" font-family="Ubuntu, Helvetica, Arial, sans-serif" color="#626262">Des didacticiels pour aller plus vite !</mj-text>
		<mj-column>
			<mj-button background-color="#4a8a77" font-family="Ubuntu, Helvetica, Arial, sans-serif" href="{SERVER}/didacticiels/">Consultez nos vidéos !</mj-button>
		</mj-column>
	</mj-section>

which returns :
`mjml -r crm-standard.mjml -o crm-standard-new.html
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <td>. See Section > td > MJMLElement > MJMLColumnElement > tr.`

removing the ending " ! " from the mj-text html solves this issue. ("Des didacticiels pour aller plus vite...")

**Comment by hikouki** [comment]
Try this code :sushi: 

```html
<mj-section background-color="#fafafa">
    <mj-column width="100%">
        <mj-text color="#fafafa" font-size="20" font-family="Ubuntu, Helvetica, Arial, sans-serif" color="#626262">Des didacticiels pour aller plus vite !</mj-text>
    </mj-column>
    <mj-column>
        <mj-button background-color="#4a8a77" font-family="Ubuntu, Helvetica, Arial, sans-serif" href="{SERVER}/didacticiels/">Consultez nos vidéos !</mj-button>
    </mj-column>
</mj-section>
```

**Comment by kaoze** [comment]
merci !
