### ISSUE TITLE
mj-group background-color doesn't work anymore

### ISSUE THREAD

**Issue by fmauNeko** [mjmlio/mjml#1022]
Hello,

It seems that mj-group background-color attribute isn't working anymore in MJML 4.

**Reproduction Steps:**

1. Specify background-color on a mj-group

**Expected behavior:**

Colored background with MJML 4.0.0 as it was with MJML 3.3.5

**Observed behavior:**

Background is white after migrating to MJML 4.0.0

**Screenshots and GIFs**
*MJML 3.3.5*
![MJML 3.3.5](https://user-images.githubusercontent.com/46060/37038589-7fe4da42-2155-11e8-8601-a8fff5642fcb.png)
*MJML 4.0.0*
![MJML 4.0.0](https://user-images.githubusercontent.com/46060/37038591-80033a64-2155-11e8-9f25-b07edba8a74c.png)

Those tables were generated by the following code (Handlebars template)
```handlebars
{{#each table}}
  <mj-section>
    <mj-group width="90%" background-color="#feeeef">
      <mj-column border-left="8px solid #fd5c63" vertical-align="middle">
        <mj-text align="center" font-weight="700" padding="15px" color="#000000">
          {{name}}
        </mj-text>
      </mj-column>
      <mj-column vertical-align="middle">
        <mj-text align="center" font-weight="400" padding="15px" color="#000000">
          {{value}}
        </mj-text>
      </mj-column>
    </mj-group>
  </mj-section>
  {{#unless @last}}
  <mj-divider width="90%" border-color="#fd5c63" border-width="2px"/>
  {{/unless}}
{{/each}}
```

**MJML version:**

3.3.5 and 4.0.0

**Email clients the bug is seen on:**

All clients.

**Comment by iRyusa** [comment]
Hi @fmauNeko 

Nice catch, looks like component definition in `4.0.0` doesn't match `3.3.X` branch, we'll fix it ASAP

**Comment by fmauNeko** [comment]
I have tried the above fix, can confirm it is working fine ! Thanks :+1:

**Comment by iRyusa** [comment]
Thanks for the follow up ! ❤️ We'll try to release it this week on NPM
