### ISSUE TITLE
mj-social inner-padding not inheriting to mj-social-elements

### ISSUE THREAD

**Issue by timschaaf** [mjmlio/mjml#1024]
mj-social inner-padding not inheriting to mj-social-elements

**Reproduction Steps:**

In MJML App 2.8

`    <mj-section>
      <mj-column>
      	<mj-social align="right" font-size="12px" icon-size="28px" mode="horizontal" inner-padding="20px" >
          <mj-social-element href="#" icon-color="#4d4d4d" name="twitter" />
          <mj-social-element href="#" icon-color="#4d4d4d" name="facebook" />
          <mj-social-element href="#" icon-color="#4d4d4d" name ="linkedin" />
        </mj-social>
      </mj-column>
    </mj-section>`

**Expected behavior:**

Expected padding to reflect in each mj-social-element

**Observed behavior:**

No change in padding.

**MJML version:**

MJML app 2.8 on MJML v4

**Comment by kmcb777** [comment]
Thanks for reporting this !

This is fixed by 0a99539

**Comment by ngarnier** [comment]
Fixed in 4.0.2
