### ISSUE TITLE
Two (or more) colums section no longer working with 2.8.0 (#222)

### ISSUE THREAD

**Issue by evforija** [mjmlio/mjml#1025]
Hi there, just updated to the new MJML version and all my emails broke. I frequently use the two column layout from here: https://mjml.io/documentation/#2-columns-section

`
  <mj-section background-color="#fafafa" padding-bottom="20" padding-top="0">
    
    <mj-column>
      <mj-image width="50" src="https://autobooks.co/images/icons/invoice_envelope_acme.png" />

      <mj-text font-size="20" font-family="Helvetica Neue" font-weight="400" color="#626262" align="center">
        Online Invoices </mj-text>

      <mj-text color="#525252" font-family="Helvetica Neue" font-weight="300" font-size="12pt" align="center">
        Create and send invoices to your customers online. It's easy to view and manage their invoice history.
      </mj-text>
    </mj-column>

    
    <mj-column>
      <mj-image width="50" src="https://autobooks.co/images/icons/payment-options-acme.png" />
      <mj-text font-size="20" font-family="Helvetica Neue" color="#626262" font-weight="400" align="center">
        Payment Notifications </mj-text>

      <mj-text color="#525252" font-family="Helvetica Neue" font-size="12pt" font-weight="300" align="center">
        You can receive email notifications when your customers view and pay your invoices, instantly.

      </mj-text>

    </mj-column>
  </mj-section>`

**Screenshots and GIFs**

![4front march 1-desktop](https://user-images.githubusercontent.com/32684477/37107214-c6530aba-2201-11e8-89c2-ee15243a8178.png)

**MJML version:**

2.8.0

**Email clients the bug is seen on:**

All

**Comment by iRyusa** [comment]
Hi @evforija

Can you give us some info about how you're sending your email ?

**Comment by evforija** [comment]
Hi there, I am using Active Campaign, but the screenshot is actually from the MJML desktop app itself!

**Comment by iRyusa** [comment]
Ok we found it, it looks that now we're outputing comments in an mj-raw so the section behave like if it has 3 columns instead of 2. 
2 solution here, either you remove the comments, and then you will have your 2 column with 50% width again, or just define the width in the column manually

**Comment by evforija** [comment]
Ah ok, thank you! Should I avoid comments going forward then?

**Comment by iRyusa** [comment]
Well to avoid any issue just keep comments or put them outisde the section and define the width manually on the column in % or pixels

**Comment by evforija** [comment]
AH gotcha gotcha - because the comments are IN the section. Der. Thank you!!!
