### ISSUE TITLE
MJML 4.0 — Setting mj-body attributes in mj-head renders an empty div

### ISSUE THREAD

**Issue by Razinsky** [mjmlio/mjml#1027]
Here's the code:
```
<mj-head>
    <mj-title>Title</mj-title>
    <mj-attributes>
        <mj-body background-color="#ffffff" />
    </mj-attributes>
 </mj-head>
```

Tested in the MJML macOS app and with the `mjml-core` package.

The error occurs the minute you put `<mj-body />` in `<mj-attributes />`. No need to add any attributes to the tag.

**Comment by iRyusa** [comment]
Hi @Razinsky 

Thanks for finding this 👍
