### ISSUE TITLE
[Feature Request]: AMPHTML

### ISSUE THREAD

**Issue by asyi** [mjmlio/mjml#1029]
Hey all! I'm not sure how this would work, but I was reading about AMPHTML by Google today and thought it would be cool to make use of it with MJML. Just a thought!

https://www.blog.google/products/g-suite/bringing-power-amp-gmail/
https://gsuite-developers.googleblog.com/2018/02/AMP-for-email-developer-preview.html
https://github.com/ampproject/amphtml/issues/13457

**Comment by ngarnier** [comment]
Hey @asyi, thanks for the suggestion!

AMP is kind of a MJML for Gmail only, so the markup is quite simple already. In my opinion, there isn't much we can do to abstract it more.

When it comes to using AMP with MJML, you can already do so simply by putting your AMP tags inside a `mj-text` or `mj-raw` component. 

The only thing I can think of that we could do to make it easier to use AMP with MJML, is to simplify how to add the necessary `script` tags in the head (possible today with this [workaround](https://github.com/mjmlio/mjml/issues/82#issuecomment-291408987) but not optimal).

What do you think?

**Comment by asyi** [comment]
@ngarnier I'm open to anything! I literally just heard about it yesterday, and thought it looked interesting, bu the meta definition in the head idea sounds decent. I'm pretty new to emails, so I'm not shying away from anything. 

Thanks for the quick answer!

**Comment by ngarnier** [comment]
Alright, I'll close because it seems there isn't much we can do regarding AMPHTML.
