### ISSUE TITLE
<mj-inline-links> and <mj-link> no longer render after upgrading to 4.0.0

### ISSUE THREAD

**Issue by jamespwaters** [mjmlio/mjml#1031]
I have been using VS Code to set up emails using MJML and  I have just updated my MJML plugin in VS Code to 4.0.0.

I am now finding that the <mj-inline-links> and <mj-link> tags no longer render.  If It try to produce links using these tags, the links will be completely absent in the exported HTML email and are also not showing up in the MJML Preview pane.

Additionally, these tags are underlined with red in the code pane and when I hover over them to see what the error is, I get the message that these elements '_do not exist or are not registered_'.

The<mj-inline-links> and <mj-link> tags are still listed on the MJML documentation page and I have not been able to find out whether or not they have been replaced with something else.

Have mj-inline-links and mj-links actually been scrapped from 4.0.0?  Have they been replaced with a similar tag or will I need to start using standard HTML <a href=""> tags for creating links from now on?

**Comment by iRyusa** [comment]
Hi @jamespwaters 

Both `mj-inline-link` and `mj-link` were only created for `mj-navbar`, those 2 components have been renamed to `mj-navbar` and `mj-navbar-link` to avoid any confusion. 

So yes, when you have to do a link : just use a mj-text and a regular html anchor tag `<a>` (in both version 3.3.X & 4.X).

As you can see on the bottom left, documentation in mjml.io is still about MJML 3.3.5 and will be updated soon.

**Comment by jamespwaters** [comment]
Great... thanks a lot @iRyusa
