### ISSUE TITLE
Set <mj-body /> width to a percentage value render images with a fixed width of 20px

### ISSUE THREAD

**Issue by Razinsky** [mjmlio/mjml#1036]
It would be very useful for "text-like" emails to be able to set the `<mj-body />` width to a percentage value. Currently, setting `<mj-body width="100%" />` makes all the images to have a fixed width of 20px.

**Comment by iRyusa** [comment]
Hi,

You can only define the width in pixel for mj-body. This is a limitation of our approach, if you have only text inside your email then MJML isn't really suited for that and will bloat the final output for nothing.

**Comment by Razinsky** [comment]
Yeah I understand that. My templates are meant to be very subtle with just a logo at the top, nice font and a footer with links. So I still need HTML.

Right now I simply override `max-width: 600px` in media queries and it works in most of Mac clients. It doesn't work on Gmail though and I'm not sure I understand why...

Anyway thanks for your prompt reply @iRyusa!

**Comment by Renjaminino** [comment]
@Razinsky - it's because Gmail does have certain limitations for css. - https://developers.google.com/gmail/design/reference/supported_css#supported_media_queries
