### ISSUE TITLE
Gmail/gmail app

### ISSUE THREAD

**Issue by SxPolice** [mjmlio/mjml#1043]
Hello
I have a problem with gmail(not sure that only gmail).
[MJML live](https://mjml.io/try-it-live/HkoQ1W4FM)
Its looks great. And its looks great when i opening this html-code in browser:

> <img src='https://i.imgur.com/Raorx1D.jpg' />

But when its sends by PHP scrip its make me cry:

> <img src='https://i.imgur.com/vK7gxEJ.jpg' />

ps. Sorry for the big pictures. Cant do this smaller

**Comment by ngarnier** [comment]
Hey, probably due to how you send. Can you please try to send with https://putsmail.com/?

**Comment by SxPolice** [comment]
Nope. I just found my mistake. If u work at live u can use url like this: /../image 1.png. But in mails its doesnt work. You should write like this: /../image_1.png(or image1.png) - without spaces. Look at this please

**Comment by ngarnier** [comment]
Ah, indeed the image paths need to be valid.
