### ISSUE TITLE
mj-image width doesn't work anymore Bug MJML 4

### ISSUE THREAD

**Issue by vsiv** [mjmlio/mjml#1044]
Have to use height to control width for mj-image.

**Reproduction Steps:**

`<mj-image width="100%" padding="0" src="http://.." />`
**Expected behavior:**

full width image is shown

**Observed behavior:**

normal width image is shown

**Comment by iRyusa** [comment]
Hi @vsiv 

We never supported width in `%` in any version of MJML for `mj-image`.

There's still an open issue about fluid image for mobile but we didn't found any compromise yet #263

Closing because of duplicate

**Comment by vsiv** [comment]
In the [doc](https://github.com/mjmlio/mjml/tree/master/packages/mjml-image), default value is set to `100%`, which got me confused.

**Comment by iRyusa** [comment]
Yep sorry about that, it means 100% of the column minus it's padding 👍We'll update the readme

**Comment by vsiv** [comment]
👍

**Comment by komali2** [comment]
FYI the readme remains with default as a %
![Screenshot from 2021-12-10 12-27-12](https://user-images.githubusercontent.com/8533113/145517238-568432d0-3e24-4ab6-ae29-461fdd2b0e1c.png)

**Comment by iRyusa** [comment]
You can’t set the width in percent, the default value is just poorly written as it’s 100% of parent width but defined in px.
