### ISSUE TITLE
URIError: URI malformed due to %> character

### ISSUE THREAD

**Issue by batman774** [mjmlio/mjml#1055]
Hello
I have updated my version of mjml to 4.0.1. After this update, mjml watch on my mjml template doesn't work.

The mjml file respond the error > URIError: URI malformed
After some investigation, I found as the character %> generate the error message.
Maybe other character generate this issue.. 

Version used
mjml : 4.0.1
npm : 5.7.1

Thanks for your help

**Comment by iRyusa** [comment]
Hi

We're aware of it, and a fix is in progress see #1055 for more information

**Comment by batman774** [comment]
Ok thanks
