### ISSUE TITLE
text not render

### ISSUE THREAD

**Issue by wireinet** [mjmlio/mjml#1056]
Hello! strange things is see. Some text not rednder in new mjml 4
![2018-03-16_10-47-25](https://user-images.githubusercontent.com/23517333/37509748-a71b978e-2909-11e8-85a4-5a09cc708924.png)

**Comment by iRyusa** [comment]
Hi

This is because you have no unit in your `font-size` just put a `px` and the text will show up

**Comment by wireinet** [comment]
oh...realy/ Thank you!
