### ISSUE TITLE
Image Carousel is not working.

### ISSUE THREAD

**Issue by KhushbuAjmera** [mjmlio/mjml#1057]
I used same HTML as given in this link https://mjml.io/documentation/#mjml-carousel. I send Minify HTML in my gmail account of https://mjml.io/try-it-live/components/carousel, But slider is not working in Gmail.
Even I tried to implement mjml-accordion  https://mjml.io/documentation/#mjml-accordion, It is not working in Thunderbird and gmail.  

I am using latest version of MJML.

Can you please explain me in which mailbox this will be supported, and why it is not working in Gmail.

**Comment by iRyusa** [comment]
Hi  

Gmail/Thunderbird doesn't support any click interaction so arrow are hidden.
However you should be able to hover the thumbnails to display other images.

Here's a list of client that support accordion https://mjml.io/compatibility/mj-accordion

**Comment by KhushbuAjmera** [comment]
Please provide me list of mailbox in which Carousel and accordion is supported.

**Comment by iRyusa** [comment]
> Here's a list of client that support accordion https://mjml.io/compatibility/mj-accordion
...

We doesn't have an as detailed list for mj-carousel but at least the fallback should be decent enough
