### ISSUE TITLE
Columns that don't stack up on mobile?

### ISSUE THREAD

**Issue by epayet** [mjmlio/mjml#106]
I have a case where I have 2 smalls columns and I don't want them to stack up on mobile because they look nice on mobile next to each other.

I know that the default behaviour of columns are that they stack up on mobile, but I would like to be able to specify that I don't want the columns to stack for a certain section.

Maybe an attribute for the section that change the default behaviour? Any ideas/thoughts? Thanks

**Comment by iRyusa** [comment]
See #41 There's some ideas on how to implement it :+1: I close this one
