### ISSUE TITLE
background for container in mjml 4

### ISSUE THREAD

**Issue by wireinet** [mjmlio/mjml#1062]
hello! Please tell me - how i can now set background color for body? In previous mjml is set be default in attributes...

**Comment by ngarnier** [comment]
@wireinet all `mj-container` attributes now belong to `mj-body`. The list of changes introduced in MJML v4 is available here: https://github.com/mjmlio/mjml/releases/tag/v4.0.0

**Comment by wireinet** [comment]
Thank you!
