### ISSUE TITLE
Add better logging to CLI

### ISSUE THREAD

**Issue by 10kc-zack** [mjmlio/mjml#1065]
### Issue
When running the new v4 CLI, I found that the messages being shown when using the CLI (or lack thereof) made it difficult to understand what what happening. For example:

This works as expected and creates an HTML version of my template:
```bash
mjml ./src/templates/my-template.mjml -o my-template.html
```

while this doesn't work:
```bash
mjml ./src/templates/my-template.mjml -o ./dist/my-template.html
```
When running both of these commands, neither one showed any sort of logging. After looking at #1014, I saw @iRyusa state that the CLI **does not** create the `dist` folder to avoid issues, but anyone else running this command would be unable to determine why both commands aren't working. I think it's important to follow the example set by large CLIs like [create-react-app (CRA)](https://github.com/facebook/create-react-app) that show progress of the CLI operations, or at the very least a meaningful error or success message. For example, CRA uses the following success and fail messages when trying to create a new project (which could be analogous to transpiling from MJML to HTML):

**Success Case**
<img width="382" alt="screen shot 2018-03-20 at 5 28 36 pm" src="https://user-images.githubusercontent.com/28154501/37684031-f9b19616-2c64-11e8-8b21-e6a826244f65.png">

**Fail Case**
<img width="513" alt="screen shot 2018-03-20 at 5 28 51 pm" src="https://user-images.githubusercontent.com/28154501/37684047-01d87c88-2c65-11e8-938f-6b1d284418aa.png">

In the scenario I described above for the MJML CLI, I think messages like this should be included (at the very least):

**Success Case**
> Compiled MJML template to `/path/to/my-template.html`

**Fail Case**
> Error! Failed to compile MJML template. Directory `/path/to/dist` does not exist.

### MJML version:

`v4.0.2`

**Comment by iRyusa** [comment]
Hi @10kc-zack 

On this particular case, we've added a message in cli to warn you that output directory doesn't exist.
I'm not against a  "verbose" mode/option for the cli, but default output should stick to the strict minimum, because some existing connectors in MJML ecosystem (ex: some ruby gems) interact directly with `stdout`.

**Comment by 10kc-zack** [comment]
Thanks for your reply @iRyusa. That makes perfect sense why you would want to keep logging to a minimum.

Is the message you mentioned adding in `v4.0.2`? I was not seeing a message when using the command `mjml ./src/templates/my-template.mjml -o ./dist/my-template.html` when `./dist` did not exist, which prompted me to post the issue.

**Comment by iRyusa** [comment]
It might only works when output multiple files inside a non-existing directory 🤔 

We'll check about that in the `4.1.0` version
