### ISSUE TITLE
MJML 4, issuing `yarn` on fresh repo clone causes failure

### ISSUE THREAD

**Issue by arvilmena** [mjmlio/mjml#1069]
MJML 4, just following the [Development section](https://github.com/mjmlio/mjml#development), issuing `yarn` on fresh repo clone causes failure.

**Reproduction Steps:**

1. as a Windows 10 user
2. `git clone https://github.com/mjmlio/mjml.git mjml-dev && cd mjml-dev`
3. `yarn`

**Expected behavior:**

should build as intended.

**Observed behavior:**

[Here is the actual CLI response](https://pastebin.com/raw/TqRE3Y3n)
[Screenshot](http://prntscr.com/iu7ek4)

**Screenshots and GIFs**

Here is my [yarn-error.log](https://pastebin.com/raw/Sr1v7UV6)

**MJML version:**

4.0.2

**Comment by iRyusa** [comment]
Can you try to do a `yarn build` and start `lerna bootstrap` again ?

**Comment by arvilmena** [comment]
Failed still. I got this now: [Pastebin](https://pastebin.com/raw/UreJ4bQh)

**Comment by iRyusa** [comment]
I think it's related to #944

**Comment by arvilmena** [comment]
yup, that allows me to run the yarn build, cool thanks
