### ISSUE TITLE
mj-button does not render well without href attribute on outlook.com

### ISSUE THREAD

**Issue by epayet** [mjmlio/mjml#107]
This is related to [#73](https://github.com/mjmlio/mjml/issues/73). Forgetting to put the href attribute on a mj-button changes everything on outlook.com. I usually put the href attribute at the end, and I forget to add it for testing purposes.

Is there a way to render the button nicely even without href? If not, maybe just add a warning on the documentation that says the href attribute is mandatory to render nicely.

**Comment by iRyusa** [comment]
I think we can change `<a>` element by something else if there's no `href`

**Comment by iRyusa** [comment]
In 2.3, `a` tag is now being replaced by a `p` tag if there's no `href`
