### ISSUE TITLE
Unable to change Image Width from 100%

### ISSUE THREAD

**Issue by arockiya** [mjmlio/mjml#1071]
Hi @iRyusa,

I am unable to change image width from 100%. I am using below code for image.

      <mj-section>
        <mj-column>
          <mj-image width="700" height="400" src="Template/chart.png" alt="Full Activation" />
        </mj-column>
      </mj-section>

In the preview  panel, it is displaying fine. But i when i try view the same in Outlook 2013, the image is showing with width 1920.

          <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
            <tbody>
                <tr>
                    <td style="width:550px;">

                        <img height="400px" width="1920" src="cid:9cb34a5a-3e9d-4a4e-b2cc-11b78d5df6c8" style="border:0;display:block;outline:none;text-decoration:none;width:100%;">

                    </td>
                </tr>
            </tbody>
        </table>

Sample screen shot of the problem:
![mjml issue](https://user-images.githubusercontent.com/7664960/37711475-49fa0f84-2d2a-11e8-9ee1-75a37de48fef.png)

expected result: start from green marked border
Actual Result: start from red border

Please correct if i am doing anything wrong.

**Comment by iRyusa** [comment]
Can you provide the MJML version you're using please ? Can't reproduce your issue here on MJML4 & 3.3.5

**Comment by arockiya** [comment]
I am using below version.

![image](https://user-images.githubusercontent.com/7664960/37711848-8b60a798-2d2b-11e8-87df-fca625f39d4d.png)

**Comment by iRyusa** [comment]
Can you provide the full template so we can investigate, I really can't reproduce your issue with the snippet you provide ? Did you modify the width of `mj-body` ?
