### ISSUE TITLE
mjml.mjml2html is not a function in nodejs 

### ISSUE THREAD

**Issue by aatishkori1412** [mjmlio/mjml#1075]
**When trying out MJML in JSON example into the nodejs:**

` var mjml = require('mjml') `
`console.log(mjml.mjml2html({tagName: 'mjml',
  attributes: {},
  children: [{
    tagName: 'mj-body',
    attributes: {},
    children: [{
      tagName: 'mj-container',
      attributes: {},
      children: [{
        tagName: 'mj-section',
        attributes: {},
        children: [{
          tagName: 'mj-column',
          attributes: {},
          children: [{
              tagName: 'mj-image',
              attributes: {
              'width': '100px',
              'src': '/assets/img/logo-small.png'
              }
            },
            {
              tagName: 'mj-divider',
              attributes: {
                'border-color' : '#F46E43'
              }
            }, 
            {
            tagName: 'mj-text',
            attributes: {
              'font-size': '20px',
              'color': '#F45E43',
              'font-family': 'Helvetica'
            },
            content: 'Hello World'
          }]
        }]
      }]
    }]
  }]
}))`

**Screenshots and GIFs**
I get the following error:

![error](https://user-images.githubusercontent.com/31002993/37819146-7efc7e1e-2ea2-11e8-9fd7-9cc9487e7520.JPG)

**MJML version:**

[4.0.2]

Am I missing something here ?

**Comment by ngarnier** [comment]
hey @aatishkori1412, `mjml2html` is now the default function exported: https://github.com/mjmlio/mjml#inside-nodejs

so:
```
var mjml2html = require('mjml')
console.log(mjml2html{})
```

**Comment by aatishkori1412** [comment]
thanks
