### ISSUE TITLE
MJML 4 renders font-size attribute without px

### ISSUE THREAD

**Issue by rcscott** [mjmlio/mjml#1080]
In MJML 3.x, the `font-size` attribute on the `mj-text` had `px` automatically added to the end of the value if it was missing. On MJML 4.x, the `px` is not automatically added. I'm not sure if this is a bug or intentional change, but it broke the rendering of the text content for me in Outlook and Gmail. Thunderbird handled it just fine however and interpreted the value as pixels with or without the `px`.

I can work around this easily by adding `px` to the values in my templates, but figured I'd report it in case it is an actual bug.

**Reproduction Steps:**

Render the following with MJML 3 and 4, compare the results.

```html
<mj-text font-size="14">Body text</mj-text>
```

In MJML 3, this renders as:

```html
<div style="...font-size:14px;..."> Body text </div>
```

In MJML 4, this renders as:

```html
<div style="...font-size:14;..."> Body text </div>
```

**MJML version:**

4.0.2

**Email clients the bug is seen on:**

Outlook for Mac 16.11, Gmail web client

**Comment by iRyusa** [comment]
HI @rcscott 

This is a intended changes to avoid adding some unit on some attributes that support unitless values

If you migrate an old template with mjml-migrate tool, it will add `px` automatically for you.

**Comment by rcscott** [comment]
Ah, got it. Thanks!
