### ISSUE TITLE
MJML ouput for mj-divider incorrect syntax for MSO conditional

### ISSUE THREAD

**Issue by timschaaf** [mjmlio/mjml#1084]
When using mj-divider, the mso-conditional code has the incorrect width specifications./

**Reproduction Steps:**

MJML code:

`<mj-divider width="20px" 
                    border-width="1px"
                    border-color="#000000"
                    padding="20px 0px 10px 0px" />`

Compiled HTML:

``

Necessary correction in compiled code to make it work: **(note: in our MJML code example, the width is set to 20px. So we need to change the full width to 20px in the mso conditional code).**

``

**Comment by iRyusa** [comment]
Thanks @timschaaf ! 

We'll try to fix it for next version too
