### ISSUE TITLE
Specifying height on mj-text with units results in double px in ms conditional compiled code

### ISSUE THREAD

**Issue by timschaaf** [mjmlio/mjml#1085]
Specifying height on mj-text with units results in double px in ms conditional compiled code

**Reproduction Steps:**

```
<mj-text align="left"
                 color="#6a737b"
                 font-size="16px"
                 line-height="24px"
                 padding-top="10px"
                 height="140px"
                 padding-right="20px">
        	   sample text
        </mj-text>
```
**Expected behavior:**

`<table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td height="140px" style="vertical-align:top;height:140px;">`

**Observed behavior:** Note the double pxpx on the height.

`<table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td height="140px" style="vertical-align:top;height:140pxpx;">`

**Comment by iRyusa** [comment]
Hi @timschaaf 

It's now fixed in MJML `4.0.3`, so I'm closing it
