### ISSUE TITLE
Using "mj-table" results in non-standard attributes on table element with value of "[object Object]".

### ISSUE THREAD

**Issue by warrickbayman** [mjmlio/mjml#1086]
Hi.

I'm using the mj-table component like this:

```html
<mj-table color="#888888">
```

And I'm getting this result:

```html
<table 0="[object Object]" 1="[object Object]" 2="[object Object]" border="0" style="cellspacing:0;color:#888888;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;">
```

Without the "color" attribute on the `mj-table` element, the `0`, `1` and `2` attributes on the resulting "table" disappear.

**Reproduction Steps:**

1. Use "mj-table" element with any attribute
2. compile HTML: `mjml input.mjml -o output.html`

**Expected behavior:**

Expected correct HTML `table` element

**Observed behavior:**

Resulting HTML `table` element is mostly correct, but includes three additional attributes named `0`, `1` and `2` each with the value `[object Object]`.

**MJML version:**

4.0.3

**Comment by kmcb777** [comment]
Hi @warrickbayman, thanks for reporting this, some of the attributes were indeed not passed correctly. The fix will be included in one of the next releases.
