### ISSUE TITLE
Left align Text & Button don't align

### ISSUE THREAD

**Issue by lajlev** [mjmlio/mjml#109]
![screenshot](https://i.imgur.com/bMmplSp.png)

**Comment by lajlev** [comment]
Button wrapping td is 30px ![screenshot](https://i.imgur.com/n9iGBIy.png)
While other elements are 25px ![screenshot](https://i.imgur.com/GnZRGks.png)
??

**Comment by iRyusa** [comment]
Yes, default padding on button is higher than other mjColumnElement. I guess we can standardize that..

**Comment by lajlev** [comment]
Awesome. Thanks for fast response :muscle:

**Comment by iRyusa** [comment]
It will be good in the next `1.3` release !

**Comment by iRyusa** [comment]
`1.3` is now available on npm !
