### ISSUE TITLE
Trying to override default styles within the Head

### ISSUE THREAD

**Issue by djarosz319** [mjmlio/mjml#1090]
Trying to set default global attributes using "mj-all" and "mj-text" inside the mj-attributes container with in the Head. Seems not to be working on my output file.  I'm on version 4.0.3.

Also, it seems that heading tags have margin added by default, unable to remove the margin.

===First Step===
<mj-attributes>
        <mj-all font-family="Arial, Helvetica, sans-serif" padding="0" />
        <mj-text padding="0" font-family="Arial, Helvetica, sans-serif" margin="0" />
</mj-attributes>

It seems whatever I do inside the mj-attribute, does not render out in my output file.

I'm trying to avoid having to add the font-family and padding individually to every mj-text syntax.

![screen-shot-2018-03-26-at-2 56 07-pm- 2](https://user-images.githubusercontent.com/8809384/37929650-28116220-3106-11e8-9a52-3c0430c16dd2.jpg)

The screen shot above shows the output.html file and how it renders incorrectly.

The expected behavior/result should remove the default padding, margin and add in the font-family.

Secondly, all heading tags h1, h2, h3... have a margin that cannot be removed.

Please let me know if something changed from version 3 to 4.

Im currently using mjml 4.0.3

Thank you!

**Comment by iRyusa** [comment]
Can you share the MJML so we can debug it? 

For h1/2/3/3, margin are applied by the browser so there’s nothing we can do about it. You can use mj-style to reset it if you want so, as regular html/css.

**Comment by djarosz319** [comment]
Do you wan the actual mjml file?

**Comment by iRyusa** [comment]
At least the bare minimum to reproduce your issue

**Comment by djarosz319** [comment]
`
  <mj-head>
    
    <mj-title>Sensient Insights</mj-title>
      <mj-attributes>
        <mj-all font-family="Arial, Helvetica, sans-serif" padding="0" />
        <mj-text padding="0" font-family="Arial, Helvetica, sans-serif" />
      </mj-attributes>
    <mj-style inline="inline">
    </mj-style>
    <mj-style>
    </mj-style>
  </mj-head>

<mjml>
    <mj-body background-color="#d8d8d8">

        <mj-section padding="0 0 0 0" background-color="#d8d8d8">
            <mj-column>
                <mj-spacer height="8px" />
                <mj-text padding="0 0 0 0" align="center" font-size="10px" line-height="20px">
                    Aenean blandit, ligula eu convallis malesua
                </mj-text>
                <mj-spacer height="5px" />
                <mj-text padding="0 0 0 0" align="center" font-size="10px" line-height="20px">
                    <a href="" style="text-decoration: underline; color: #000000;">View in Browser</a>
                </mj-text>
                <mj-spacer height="5px" />
            </mj-column>
        </mj-section>

        
        <mj-section padding="0 0 0 0" background-color="#ce0058">
            <mj-column>
                <mj-image padding="0 0 0 0" src="http://via.placeholder.com/600x150" alt="" />
            </mj-column>
        </mj-section>

        
        <mj-section padding="0px 15px 0 15px" background-color="#ffffff">
            <mj-column width="400">
                <mj-spacer height="40px" />
                <mj-text mj-class="test" align="center" font-size="20px"  color="#294787" text-transform="uppercase">
                    <h1>Insights</h1>
                </mj-text>
                <mj-spacer height="25px" />
                <mj-text padding="0 0 0 0" align="center" font-size="24px" line-height="28px" font-family="Arial, Helvetica, sans-serif" color="#000000">
                    Mauris faucibus leo sed dolor convallis, vitae ullamcorper nulla
                </mj-text>
                <mj-spacer height="10px" />
                <mj-divider border-width="4px" border-style="dotted" border-color="#ffcf2e" width="47px" />
                <mj-spacer height="5px" />
                <mj-text padding="0 0 0 0" color="#000000" align="left" font-size="16px" line-height="22px">
                    <p>Aenean blandit, ligula eu convallis malesuada, magna metus dapibus lacus, ac aliquet velit lacus vitae elit. Donec elementum enim eu odio eleifend aliquam.</p>
                </mj-text>
                <mj-spacer height="30px" />
            </mj-column>
        </mj-section>

        <mj-section padding="0 5%" background-color="#f8f8f8">
        <mj-column width="47%" background-color="#ffffff">
          <mj-image padding="0 0 0 0" src="http://via.placeholder.com/500x268" alt="" />
          <mj-spacer height="25px" />
          <mj-text padding="0 30px" align="left" font-size="11px" line-height="15px">
            <h3>Trends</h3>
          </mj-text>
          <mj-text padding="0 45px 0 30px" align="left" font-size="16px" line-height="22px" font-weight="bold">
            <p>Sensient Flavors' Urban Foraging Trip Inspires Trends to Taste Predictions</p>
          </mj-text>
          <mj-spacer height="5px" />
          <mj-text padding="0 30px" align="left" font-size="13px" line-height="19px">
            <a href="" style="text-decoration: underline; color: #294787; text-transform: uppercase; font-weight: bold;">Read More</a>
          </mj-text>
          <mj-spacer height="30px" />
        </mj-column>

        <mj-column width="5%" background-color="#f5f6f8">
          <mj-text font-size="0" line-height="0" padding="0">
            &nbsp;
          </mj-text>
        </mj-column>
      
        <mj-column width="47%" background-color="#ffffff">
          <mj-image padding="0 0 0 0" src="http://via.placeholder.com/500x268" alt="" />
          <mj-spacer height="25px" />
          <mj-text padding="0 30px" align="left" font-size="11px" line-height="15px">
            <h3>Trends</h3>
          </mj-text>
          <mj-text padding="0 45px 0 30px" align="left" font-size="16px" line-height="22px" font-weight="bold">
            <p>Sensient Flavors' Urban Foraging Trip Inspires Trends to Taste Predictions</p>
          </mj-text>
          <mj-spacer height="5px" />
          <mj-text padding="0 30px" align="left" font-size="13px" line-height="19px">
            <a href="" style="text-decoration: underline; color: #294787; text-transform: uppercase; font-weight: bold;">Read More</a>
          </mj-text>
          <mj-spacer height="30px" />
        </mj-column>
      </mj-section>




    </mj-body>
</mjml>
  `

**Comment by djarosz319** [comment]
For some reason the head didn't show up in the above post.
`<mj-head>
    
    <mj-title>Sensient Insights</mj-title>
      <mj-attributes>
        <mj-all font-family="Arial, Helvetica, sans-serif" padding="0" />
        <mj-text padding="0" font-family="Arial, Helvetica, sans-serif" />
      </mj-attributes>
    <mj-style inline="inline">
    </mj-style>
    <mj-style>
    </mj-style>
  </mj-head>`

**Comment by djarosz319** [comment]
Figured it out. The Standard Head components were outside of the opening <mjml> tag.  Sorry to take up your time. Everything seems to be working now.

Thanks!
