### ISSUE TITLE
Request: explanation in docs as to what component can be in another

### ISSUE THREAD

**Issue by matthewbryancurtis** [mjmlio/mjml#1095]
Thanks for the project - it looks really promising.

I'm just getting started but finding it tough to figure out what component can be nested in another. I imagine the strict hierarchy has to do with many components being abstractions of various table elements and it would be really helpful to `mjml` beginners to outline these restrictions.

I noticed that this is actually done for `mj-section` but not for many others.

Thanks again.

**Comment by ngarnier** [comment]
Hey @matthewbryancurtis, have a look at this part: https://mjml.io/documentation/#nesting. 

Basically, a MJML layout is: 
```
<mjml>
  <mj-head>
    <!-- Standard head elements -->
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <!-- Standard body elements -->

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

When in doubt, you can check the docs for each component, they include an example so you can see where it's supposed to be. Example with v3 for `mj-navbar` (which we updated and now belongs to `mj-column` in MJML 4, for more consistency): https://mjml.io/documentation/#mjml-navbar

We'll see what we can do to illustrate this better, but feel free to also make a pull request with a new section in the doc (you can create a `.md` file if you think it's necessary): https://github.com/mjmlio/mjml/tree/master/doc.
