### ISSUE TITLE
mjml.io/documentation/ is hosting outdated v3.x docs

### ISSUE THREAD

**Issue by knksmith57** [mjmlio/mjml#1097]
MJML Documentation site hosted @ https://mjml.io/documentation/ hasn't been updated for `v4.x` and is currently tagged as `v3.3.5`.

Additionally, it's not immediately clear where to find rendered `v4.x` developer docs (or how _to_ render `v4.x` developer docs) .

relates to #1082

**Reproduction Steps:**
1. visit  https://mjml.io/documentation/

**Expected behavior:**
Rendered documentation tracks the current stable release of MJML (at this moment, that's `v4.0.3`).

**Observed behavior:**
Rendered documentation reflects the latest `v3.x` release (at this moment, that's `v3.3.5`).

**MJML version:**
n/a

**Email clients the bug is seen on:**
n/a

**Comment by ngarnier** [comment]
Hey @knksmith57, thanks. We're aware and working on updating the website, lots to do with the release of MJML 4 and update all the ecosystem.

**Comment by ngarnier** [comment]
The doc on mjml.io is generated from the different READMEs referenced here: https://github.com/mjmlio/mjml/blob/master/doc/config.json, using https://github.com/lord/slate.

Feel free to help by contributing to the READMEs yes!
