### ISSUE TITLE
Adding overall border to email

### ISSUE THREAD

**Issue by nickngqs** [mjmlio/mjml#1098]
With the removal of mj-container. What's the best way to wrap only the max-width of the email with borders? Adding class on mj-body affects the whole page instead of the contained width

On Outlook, using my own wrapper, it breaks all versions of Outlook.

And i can't use mj-wrapper since I'm using them for nesting certain sections. And the cli throws an error when that's a wrapper inside a wrapper.

**MJML version:**
MJML v4

**Comment by ngarnier** [comment]
The removal of `mj-container` doesn't change anything, the container didn't take a border attribute (or I am missing how you used to do). You can simply use mj-wrapper.

If you want to use your own CSS selector, you simply need to target the child div of the body:
```
.body > div {}
```

Example of both solutions:
```
<mjml>
  <mj-head>
    <mj-style>
      .body > div {
        background-color:red;
      }
    </mj-style>
  </mj-head>
  <mj-body css-class="body">
    <mj-wrapper border="1px solid black">
      <mj-section>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-wrapper>

  </mj-body>
</mjml>
```

**Comment by nickngqs** [comment]
Hi, I unable to use a mj-wrapper, because there're other mj-wrappers inside to nest certain sections.

**Comment by ngarnier** [comment]
Ok so the CSS selector seems the best solution. You might need to use a `mj-raw` with an opening div and Outlook conditional before the sections you want to wrap, and close them in another `mj-raw` after the sections.
