### ISSUE TITLE
Missing css-class on mj-carousel-image

### ISSUE THREAD

**Issue by janishorsts** [mjmlio/mjml#1099]
Value of 'css-class' attribute on mj-carousel-image is not present in rendered html.

**Expected behavior:**

Provided css-class should be present in rendered html.

**Observed behavior:**

Provided css-class is not present in rendered html.

**MJML version:**

4.0.3

**Comment by heyflo** [comment]
After re-checking the doc, I've found that they are not using `css-class` to call a class defined in your header but `mj-class` instead. 

Take a look here : https://mjml.io/documentation/#mjml-attributes

Yet when you go to the component section, if you call a class with a `css-class` attribute it won't work. I think the doc is not correct on this part.

✌️

**Comment by heyflo** [comment]
@iRyusa yeah thanks I realized my mistake 'cause I am using it differently 😅
`css-class` isn't working on `mj-button` aswell, I tried it on `mj-text` it appears to be working fine.

**Comment by iRyusa** [comment]
It does work fine, it's inherited by `mj-column` https://mjml.io/try-it-live/S1GGDiojz
