### ISSUE TITLE
Border-radius not working with mj-column

### ISSUE THREAD

**Issue by piotrkulpinski** [mjmlio/mjml#1104]
Hi guys,

Looks like the border-radius is not working on mj-column at all.

![image](https://user-images.githubusercontent.com/358412/38093043-15c5b434-336a-11e8-9614-7cd3beabd41c.png)

```
<mj-column width="30" border="2px solid #222222" border-radius="5px">
   (...)
</mj-column>
```

Am I doing something wrong?
Thanks

**Comment by iRyusa** [comment]
Hi @piotrkulpinski 

Well the issue is because we're using a `border-collapse: collapse` on the table that handle the column. So border-radius doesn't work with it, what you can do is using a css-class on your column and remove it but it can lead to inconsistency on some clients.

**Comment by ngarnier** [comment]
HA! @iRyusa got faster while I was typing.

You can also fake it is by using the background-color on the wrapping element: https://mjml.io/try-it-live/SyU_bO55f

**Comment by panayotoff** [comment]
I was able to fake it with box-shadow:

```
<mj-style inline="inline"> .bordered-col{ box-shadow: 0 0 0 1px #E4EBF2; border-radius: 4px; }</mj-style>
...
<mj-column width="100%" css-class="bordered-col">
...
</mj-column>
```

**Comment by sidhantsuvagiya** [comment]
Just want to add another solution: using `css-class` on your `mj-column` and applying custom style.

https://mjml.io/try-it-live/4YVOVgLazf

```
<mjml>
  <mj-head>

    <mj-style>
      .br_20{
      border: 1px solid red !important;
      border-radius: 20px !important;
      }
    </mj-style>

  </mj-head>

  <mj-body>

    <mj-section>
      <mj-column css-class="br_20">

        <mj-text>
          Hi There!
        </mj-text>

      </mj-column>
    </mj-section>

  </mj-body>
</mjml>
```

**Comment by mikk-parg** [comment]
> Just want to add another solution: using `css-class` on your `mj-column` and applying custom style.
> 
> https://mjml.io/try-it-live/4YVOVgLazf
> 
> ```
> <mjml>
>   <mj-head>
> 
>     <mj-style>
>       .br_20{
>       border: 1px solid red !important;
>       border-radius: 20px !important;
>       }
>     </mj-style>
> 
>   </mj-head>
> 
>   <mj-body>
> 
>     <mj-section>
>       <mj-column css-class="br_20">
> 
>         <mj-text>
>           Hi There!
>         </mj-text>
> 
>       </mj-column>
>     </mj-section>
> 
>   </mj-body>
> </mjml>
> ```

Excellent! There is a problem where the outlook fall-back would clip the right side of the border in Outlooks. 
To fix this I found that MJML automatically generates a "br_20-outlook" so we just have to define it and remove the border-radius to clean up. 

```
 .br_20{
border: 1px solid red !important;
 border-radius: 20px !important;
 }

 .br_20-outlook{
border: 1px solid red !important;
 }
```

Now the whole border shows up in Outlooks.
