### ISSUE TITLE
mj-social-element href's not working

### ISSUE THREAD

**Issue by pvlachou** [mjmlio/mjml#1107]
Pretty self-explanatory > [Link](https://mjml.io/try-it-live/SyaOJrs5G)

**Comment by ngarnier** [comment]
hey @pvlachou, the try it live is still running on v3.3.5, so mj-social is using the old syntax: https://mjml.io/documentation/#mjml-social. We're doing our best to update the website asap, likely next week.

**Comment by pvlachou** [comment]
Thanks for the update @ngarnier. I'm getting the same issue with the latest version of the mjml app too. Unfortunately, I've never been able to get the custom mjml engine option to work with the app, in order to use the absolute latest version of mjml.
