### ISSUE TITLE
Body tag only contain a empty div

### ISSUE THREAD

**Issue by son-link** [mjmlio/mjml#1109]
I, firts, sorry for my english.
I update mjml to 4.0.3 an execute njml -m fot migrate, but to regen my html file the body is empty, only contain a &lt;div>

I create a new document for test, but i have the same issue. This is the code of test:

```mjml
<mjml>
	<mj-body>
		<!-- Company Header -->
		<mj-section background-color="#f0f0f0">
			<mj-column>
				<mj-text>
					My Company
				</mj-text>
			</mj-column>
		</mj-section>
	</mj-body>
</mjml>
```

and this is te result under body in both documents:

```html
<body>
  <div> </div>
</body>
```

**MJML version:**

mjml-core: 4.0.1
mjml-cli: 4.0.3
node: 9.9.0
npm: 5.7.1

**Comment by son-link** [comment]
I tested with `-o` and `-w` but the result is the same, and i don't used `-m` for my test file

**Comment by iRyusa** [comment]
Can you try to reinstall completely the package, it looks like a version conflict to me

**Comment by son-link** [comment]
Ok, i reinstall all node modules and works again. Thanks a lot :+1:
