### ISSUE TITLE
How to add translate to the template

### ISSUE THREAD

**Issue by StepanNaryshkov** [mjmlio/mjml#1112]
Hi everyone, sorry, if i did not see an answer, I use mjml the second day, but I don't find any examples, how to add {`% load dbi18n %} {% load static %}` in the mjml temlate? i use django and mjml

**Comment by ngarnier** [comment]
hey @StepanNaryshkov, welcome to the community of MJML users 😉! 

I have no idea about the templating language you're using here, but there is no native template language support in MJML. 

To achieve that, you need to use the template language of your choice within your MJML templates (it's up to you to import it and render it).
