### ISSUE TITLE
v4.0.1 inline body style missing

### ISSUE THREAD

**Issue by antonyoneill** [mjmlio/mjml#1113]
I'm trying to style the body of the email (background colour) through CSS instead of through MJML so that our clients can easily change the background colour through our platform so that I can keep the MJML template fairly generic.

This was working with 3.3.5.

**Reproduction Steps:**

1. Create an v4 MJML file containing:
```xml
<mjml>
  <mj-head>
    <mj-style inline="inline">
      body {
        background-color: blue;
        font-weight: bold;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          Hello world
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
1. Run that file through the processor
```
./node_modules/.bin/mjml -r ./body_test.v4.mjml -o ./body_test.v4.mjml.html
```

**Expected behavior:**
`body` tag in output should contain the inlined css (as it does in 3.3.5)
```html
<body style="background-color: blue; font-weight: bold;">
```

**Observed behavior:**
`body` tag in output does not contain the css
```html
<body>
```

**MJML version:**

```
➜  ./node_modules/.bin/mjml -V
mjml-core: 4.0.1
mjml-cli: 4.0.3
```

Juice version (if it helps)
```
➜  ./node_modules/.bin/juice -V
4.2.3
```

**Comment by antonyoneill** [comment]
Perhaps this is expected behaviour based on [mjml-core/src/helpers/skeleton.js#L82 ](https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/skeleton.js#L82)

How much effort would it take to refactor this so that the entire body element is passed through juice?

A workaround is to put the body css inside a non-inlined `mj-style` tag.

**Comment by kmcb777** [comment]
@iRyusa 's idea was right, jucing after creating the skeleton fixes the problem 👍
