### ISSUE TITLE
No option to disable sharing in mj-social-element in v.4 (+ text mode does nothing)

### ISSUE THREAD

**Issue by ChrisPlaneta** [mjmlio/mjml#1115]
I'm using windows app v 2.8.0

I've noticed that mj-social-element creates a share link. I cannot find an option in your documentation (https://github.com/mjmlio/mjml/tree/master/packages/mjml-social) that disables it (I need to show the link to our profile page and not a link to share email). 

Another thing is that the only way to disable social network's name is to remove the text in html (and thus it's not produced in export, and so it's not accessible) because the text-mode setting doesn't work.

**MJML version:**

4

**Comment by iRyusa** [comment]
Hi @ChrisPlaneta 

We made a decision on MJML4 to force users to do a custom `mj-social-element` while keeping the old behavior without the  `:url` thingy. You can just re-use the img `src` and `background-color` to get back this behavior.
