### ISSUE TITLE
White space when images are blocked larger than the image container

### ISSUE THREAD

**Issue by Generian** [mjmlio/mjml#1117]
Hi, I'm dealing with the following problem:
When images are blocked by the email client, sometimes the white space created instead is significantly larger than the original image size, resulting in the rest of the content to be pushed down further than intended.

Encountered in: Mostly browser-based clients in the Explorer, but sometimes also Firefox and Chrome. Only desktop client with this problem is Outlook 2003.

**Reproduction Steps:**

1. Create an email with a full-width (600px) image
2. Check email in one of the above mentioned email clients with the image blocking feature turned on

**Expected behavior:**

Image should not be shown and the space in which the image would be shown should either be collapsed (not visible) or show a white background (or image blocked indicator) that's the same size as the original image.

**Observed behavior:**

Height of the image space is about 2-3x the original image height

**Screenshots and GIFs**

image rendered: https://ibb.co/dGMoHH
image blocked: https://ibb.co/fimzPx

**MJML version:**

4.0.0

**Email clients the bug is seen on:**

Gmail (Explorer)
G Suite (Explorer)
Yahoo (Explorer)
Web.de (Explorer)
GMX.de (Explorer)
freenet.de (Firefox)
freenet.de (Explorer)
freenet.de (Chrome)
T-online.de (Firefox)
T-online.de (Exlorer)
Outlook.com (Explorer)
Office 365 (Explorer)
Comcast (Explorer)
Outlook 2003 (Win 7)

**Comment by Generian** [comment]
Hi @iRyusa,

Tried to set a height. No difference unfortunately.

**Comment by iRyusa** [comment]
Well I don't really know if we can do something about this, it differs from the engine + clients I think ?

**Comment by mdogan1** [comment]
Did you try to create custom image tag instead?

**Comment by kmcb777** [comment]
Hi @Generian mj-image height wasn't correctly handled but this has been fixed in 4.1 beta, which you can install with `npm install mjml@next`, feel free to give it a try, this should solve this issue.
I don't think it's possible to handle this image blocked thing without setting the height manually.
