### ISSUE TITLE
mj-social-element[href] documented as defaulting to [[SHORT_PERMALINK]] but renders undefined

### ISSUE THREAD

**Issue by themightychris** [mjmlio/mjml#1118]
The readme for V4 indicates that the href for social links will default to `[[SHORT_PERMALINK]]` is it did it previous versions, but currently it renders as `undefined`

**Comment by kmcb777** [comment]
Hi @themightychris thanks for reporting this, this defaultAttribute was indeed missing.
This will be fixed in one of the next releases
