### ISSUE TITLE
mj-all is not working in online editor

### ISSUE THREAD

**Issue by cytsunny** [mjmlio/mjml#1119]
`mj-all` is not working on the online editor (i.e. the one you see in https://mjml.io/try-it-live/) 

**Reproduction Steps:**

1. Got to the online editor by the link:  https://mjml.io/try-it-live/
2. Change the code to use mj-all. For example, you may see this: https://mjml.io/try-it-live/rJwiocuoM 
or copy the following code to the online editor:
```
<mjml>
  <mj-head>
    <mj-all color="red"/>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Expected behavior:**

The text "Hello World" in the output should be red

**Observed behavior:**

The text "Hello World" in the output is black instead

**Screenshots and GIFs**

![image](https://user-images.githubusercontent.com/3927120/38486334-4849cbc2-3c0f-11e8-8667-18218b5ea784.png)

**MJML version:**

Unknown. Version number not shown in online editor

**Browser the bug is seen on:**

Chrome 65.0.3325.181
Firefox 57.0.4
Internet Explorer 11.309.16299.0

All of them under Windows 10

**Comment by iRyusa** [comment]
Hi @cytsunny 

You're missing the `<mj-attributes>` that's why
