### ISSUE TITLE
Outlook bugs

### ISSUE THREAD

**Issue by francoistibo** [mjmlio/mjml#112]
After emailonacid tests, I've seen some bugs on Outlook 2007, 2010, 2013 et 2016. Curiously, everything's ok on Outlook 2003, 2011 and 2016 mac.

- MJ-DIVIDER = margins appear under divider element, which has however been forced to have no padding (`<mj-divider padding="0" height="2"></mj-divider>`)
- MJ-IMAGE = image which are originally not fullwidth are resized to the parent container width. The original size is not preserved
- MJ-COLUMN = there's vertical unequal gaps (alignment) between column elements on the same raw.

**Comment by techdragon** [comment]
These have been biting me a LOT.

**Comment by iRyusa** [comment]
Hi @techdragon & @francoistibo 

Can you give an example for each of your concerns with actual/expected render for a given MJML, it would help us a lot.

**Comment by iRyusa** [comment]
I think your concern with divider is now ok in `1.3` release. 
As described it's the expected behavior from MJ-Image, but you can set a `width` attribute.
And for MJ-column, with no step te reproduce i'm closing the issue, feel free to reopen with step to reproduce + screenshot
