### ISSUE TITLE
Column not working as expected on iPad mini

### ISSUE THREAD

**Issue by StudioVDS** [mjmlio/mjml#1120]
Hi,

there I'm working on an e-mail signature  with a section with three columns around 30% each. They shwo okay on desktop, and on mobile, but on iPad the columns are centered where I expect them to stay aligned to the left.

[Desktop version](https://studiovds.nl/mimaki/desktop.png)
[Mobile version](https://studiovds.nl/mimaki/mobile.png)

[fault iPad version](https://studiovds.nl/mimaki/ipad.jpeg)

How can I solve this?

This is the section I have:
`
<mj-section padding="20px 20px 0 20px">

      <mj-column width="33%" vertical-align="top" padding-bottom="20px">
        <mj-image href="https://www.mimaki.com" align="left" width="168" src="https://studiovds.nl/mimaki/mimaki-logo-small.png" />
        </mj-image>
      </mj-column>

      <mj-column width="40%" vertical-align="top" padding-bottom="20px">
        <mj-table>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">Phone</td>
            <td style="padding: 0 15px 0 0; color:#636363;"></td>
          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">General:
            </td>
            <td class='tel' style="padding: 0 15px 0 0; color:#636363;">+31 (0)20 462 7642
            </td>
          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">Direct:</td>
            <td class='tel' style="padding: 0 15px 0 0; color:#636363;">+31 (0)20 462 7641
            </td>
          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">Mobile:</td>
            <td class='tel' style="padding: 0 15px 0 0; color:#636363;">+31 (0)6 1136 9464
            </td>
          </tr>
        </mj-table>
        <mj-table padding-top="25px">
          <tr>
            <td width="21px" style="padding: 0 0 0 0; color:#636363; line-height:1;"><a href="https://www.facebook.com"><img src="https://studiovds.nl/mimaki/facebook-small-small.png" width="21px" height="35px"/></a></td>
            <td width="35px" style="padding: 0 0 0 0; color:#636363; line-height:1;"><a href="https://www.twitter.com"><img src="https://studiovds.nl/mimaki/twitter-small.png" width="35px" height="35px"/></a></td>
            <td width="35px" style="padding: 0 0 0 0; color:#636363; line-height:1;"><a href="https://www.linkedin.com"><img src="https://studiovds.nl/mimaki/linkedin-small.png" width="35px" height="35px"/></a></td>
            <td width="35px" style="padding: 0 0 0 0; color:#636363; line-height:1;"><a href="https://www.instagram.com"><img src="https://studiovds.nl/mimaki/instagram-small.png" width="35px" height="35px"/></a></td>
            <td width="35px" style="padding: 0 30px 0 0; color:#636363; line-height:1;"><a href="https://www.youtube.com"><img src="https://studiovds.nl/mimaki/youtube-small.png" width="35px" height="35px"/></a></td>
            <td></td>
          </tr>
        </mj-table>
      </mj-column>

      <mj-column width="27%" vertical-align="top" padding-bottom="20px">
        <mj-table>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">Mimaki Europe B.V.</td>
          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">Stammerdijk 7E
            </td>
          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">1112 AA Diemen
            </td>
          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">The Netherlands</td>

          </tr>
          <tr>
            <td style="padding: 15px 15px 0 0; color:#636363;">VAT: NL813051411B01</td>

          </tr>
          <tr>
            <td style="padding: 0 15px 0 0; color:#636363;">COC: 24357886</td>

          </tr>

        </mj-table>
      </mj-column>

    </mj-section>`

**Comment by iRyusa** [comment]
Hi @StudioVDS 
Did you tried to minify the output it renders fine here : 
![image](https://user-images.githubusercontent.com/570317/38604443-ac718470-3d70-11e8-87a3-6347688cfa39.png)

**Comment by iRyusa** [comment]
Note that you can control the breakpoint with `mj-breakpoint` if you want so.
