### ISSUE TITLE
The migration of mj-link to mj-navbar-link isn't working

### ISSUE THREAD

**Issue by Marenek** [mjmlio/mjml#1124]
The [migration of mj-link to mj-navbar-link](https://github.com/mjmlio/mjml/issues/1031) isn't working neither in an online editor nor in command `mjml -m`.

**Comment by iRyusa** [comment]
Can you share your markup please ?

**Comment by iRyusa** [comment]
We did migrate it with the provided migration tool so that's why we need a bare MJML template to reproduce.

**Comment by Marenek** [comment]
Migrated version ![racoon3_migrated_to_4](https://user-images.githubusercontent.com/24964784/38564436-6f4c447c-3cdf-11e8-933a-1644b0573a4f.png)
Old version ![racoon3_old](https://user-images.githubusercontent.com/24964784/38564437-6f6e7eb6-3cdf-11e8-90b1-bc810ab189c2.png)
Actual version ![racoon4_ok](https://user-images.githubusercontent.com/24964784/38564438-6f8e5cfe-3cdf-11e8-88c4-a2adf8a2a175.png)

**Comment by iRyusa** [comment]
Looks like we didn't pushed the fix here then ! Thanks for finding this
