### ISSUE TITLE
mj-image alt on MJML app 2.8.0 with MJML engine v^4.0.0

### ISSUE THREAD

**Issue by pbsmultimedia** [mjmlio/mjml#1125]
Using the MJML app 2.8.0 with MJML engine v^4.0.0 having the following code:

`<mjml> <mj-body> <mj-container> <mj-section> <mj-column> <mj-image width="300" src="http://www.online-image-editor.com//styles/2014/images/example_image.png" alt="soft kitty"/> </mj-column> </mj-section> </mj-container> </mj-body> </mjml>`

I get the following HTML output:
...
`<img height="auto" src="http://www.online-image-editor.com//styles/2014/images/example_image.png" style="border:0;display:block;outline:none;text-decoration:none;width:100%;" width="300" />`
...

The ALT attribute is erased, on another example, the src attribute gets placed on the alt.

Any idea?

Thanks!

**Comment by ngarnier** [comment]
Hey, this was fixed in the MJML 4.0.3 (and MJML app v2.9.0), please upgrade. Feel free to reopen if you still see the issue happening.
