### ISSUE TITLE
Usage of word-break is breaking the layout

### ISSUE THREAD

**Issue by heyflo** [mjmlio/mjml#1127]
Usage of `word-wrap: break-word;` for the sake of consistency across all the major browsers & email clients instead of `word-break: break-word` which isn't supported by all browsers : https://developer.mozilla.org/fr/docs/Web/CSS/word-break

**Reproduction Steps:**
Use a big title with long words, open it on Firefox (for instance) or Firefox Mobile... See the word going outside of the viewport.

**Expected behavior:**
Long words should break into multiple lines if they cannot fit in the viewport.

**Observed behavior:**

Big words aren't broke on multiple line to not expand outside the window.

**Screenshots and GIFs**

![Screenshot](https://i.imgur.com/NdfJNBl.png)

**MJML version:** 4.0.3

Thanks guys ✌️

**Comment by iRyusa** [comment]
Hi @heyflo 

Well it's more a css than mjml issue, both doesn't behave exactly the same and we had issue with this in the past.

If you want to use `word-break: break-word` feel free to use it with inline style  / mj-style / mj-style inline.
