### ISSUE TITLE
Feature for mj-social href atribute

### ISSUE THREAD

**Issue by milos5593** [mjmlio/mjml#1130]
I need a way to make links in `mj-social` to be just regular URL links and not shareable links.

**Reproduction Steps:**

When I enter the code as bellow:

```
<mj-social-element name="facebook" href="https://www.facebook.com/Ariel.Property.Advisors" background-color="#343b3f">
```

**Expected behavior:**

```
<a  href="https://www.facebook.com/Ariel.Property.Advisors" target="_blank">
```

**Observed behavior:**

```
<a  href="https://www.facebook.com/sharer/sharer.php?u=https://www.facebook.com/Ariel.Property.Advisors" target="_blank">
```

**MJML version:**

4.0.3

**Comment by kmcb777** [comment]
Hi @milos5593 i'll see with the others if we implement an option, it can be useful indeed
For now you could define your own mj-social-element, using src and color from the default social networks values (their default values can be found at the top of this file : https://github.com/mjmlio/mjml/blob/master/packages/mjml-social/src/SocialElement.js)

i.e. a twitter social-element with a custom link would be like this :
```
<mj-social-element src="https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter.png" href="https://my-unchanged-url" background-color="#55acee">
  Twitter
</mj-social-element>
```

**Comment by milos5593** [comment]
@kmcb777 This works as a workaround. Thanks

**Comment by maherelaridi** [comment]
@kmcb777 It's not working for me. 

`
      <mj-social font-size="15px" icon-size="40px" mode="horizontal">
        <mj-social-element src="https://bit.ly/2Hbm8FY" href="https://www.facebook.com/" background-color="white"></mj-social-element>
        <mj-social-element src="https://bit.ly/2HaqDRl" href="https://twitter.com/" background-color="white"></mj-social-element>
        <mj-social-element src="https://bit.ly/2JSomI5" href="https://www.linkedin.com/" background-color="white"></mj-social-element>
        <mj-social-element src="https://bit.ly/2qIHT55" href="https://www.youtube.com/" background-color="white"></mj-social-element>
      </mj-social>`

Although, the custome icons show up in the footer template, it shows the default icons when I get back to the main page.

Footer.mjml 
![screenshot 2018-04-18 15 03 34](https://user-images.githubusercontent.com/2089136/38955333-f991d706-4319-11e8-93df-0ed3d36505a6.png)

Main-template.mjml 
![screenshot 2018-04-18 15 06 21](https://user-images.githubusercontent.com/2089136/38955367-133e66a6-431a-11e8-9e22-5089915f590a.png)

**MJMLApp v2.8.0
MJML v^4.0.0**


Thanks!

**Comment by ngarnier** [comment]
From what I can see, you're using the v4 syntax (`mj-social-element`) in your footer while you're using the v3 sytnax (`mj-container`) in your main-template. Can you try to remove the `mj-container` tags in your main-template?

**Comment by maherelaridi** [comment]
Thanks @ngarnier! Works like a charm now by removing the `mj-container`

**Comment by splitt3r** [comment]
The following code:

```
<mj-social>
    <mj-social-element src="https://www.mailjet.com/images/theme/v1/icons/ico-social/facebook.png" href="https://facebook.com/" background-color="#8c8c8c">Facebook</mj-social-element>
    <mj-social-element src="https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter.png" href="https://twitter.com/" background-color="#8c8c8c">Twitter</mj-social-element>
</mj-social>
```

Throws: `TypeError: Cannot read property 'icon-height' of undefined` in version 4.0.4. But it works in 4.0.1.

**Comment by kmcb777** [comment]
@splitt3r Hi, thanks for reporting this. A bug was indeed introduced in 4.0.4, the fix is already done and we will release a 4.0.5 very soon to fix this

**Comment by splitt3r** [comment]
4.0.5 did the job 👍

**Comment by yrammos** [comment]
This site is relevant to the discussion: [http://www.socicon.com/generator.php](http://www.socicon.com/generator.php) (disclaimer: I'm entirely unaffiliated with it).

**Comment by kmcb777** [comment]
Hi @milos5593 in the new release mjml4.2-beta you can now use `name="[network-name]-noshare"` to avoid the url from being inserted in the share url , you can check it with `npm install mjml`

**Comment by yrammos** [comment]
Excellent! Many thanks.
