### ISSUE TITLE
mjml.io 503 service unavailable

### ISSUE THREAD

**Issue by rosskevin** [mjmlio/mjml#1144]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
Website is down

**Reproduction Steps:**

1. Navigate to https://mjml.io

**Expected behavior:**

Website is up

**Screenshots and GIFs**

![mjml](https://user-images.githubusercontent.com/136564/38877285-f77dbc74-4223-11e8-8f17-5792885a9820.png)

**Comment by iRyusa** [comment]
Hi,

We're aware of that, and working on it. No need to open an issue for each downtime 👍
