### ISSUE TITLE
MJML version of API service

### ISSUE THREAD

**Issue by theVannu** [mjmlio/mjml#1147]
Hi all,
I use MJML through API service for render HTML email from mjml syntax but the version of API is 3.3.3 instead 4.03

**Expected behavior:**
I expect the mjml_version field of the API response to be 4.03

**Observed behavior:**
I observe that mjml_version field of the API response is 3.3.3

Are you planning to update mjml API service to 4.03 version?
Thank for support

**Comment by ngarnier** [comment]
Hey @theVannu, 

Indeed we plan to update the MJML version used in the API, likely after we have released MJML v4.1.0. We'll send an email to users of the API to let you know in advance, so you can plan accordingly.

I'll close this issue as it's not related to the MJML lib directly.

**Comment by nkCreation** [comment]
hi @ngarnier does the api service have been updated to v4 ?

**Comment by ngarnier** [comment]
hey @nkCreation, now that MJML 4 is stable we're in the process of upgrading Passport (Mailjet's drag and drop template builder) to the latest version. The API is next!
