### ISSUE TITLE
How to style links with hover effect

### ISSUE THREAD

**Issue by salpulse** [mjmlio/mjml#1153]
I'm trying to get link hover effects working in MJML. I've tried:
```
    <mj-style inline="inline">
      .link-style { color: #0478bf; text-decoration: none }
      .link-style:hover { color: #8eb3d1 !important; text-decoration: underline !important }
    </mj-style>

   <a class="link-style" href="#">my link</a>
```
The primary style works, but nothing changes on hover (testing in outlook).

**Comment by iRyusa** [comment]
Well hover effect can't be inlined, so it will be lost with your current
implem, a regular mj-style should fix it.

Note that some client just don't support head style and hover effect so it
will depends on clients.
