### ISSUE TITLE
mj-group is ignored on iphone 5 Gmail app

### ISSUE THREAD

**Issue by haxic** [mjmlio/mjml#1157]
\<mj-group> does not work as intended on iphone 5 Gmail app. The grouped columns stacks vertically instead of horizontally.

**Reproduction Steps:**

1. Copy the [sample code](https://mjml.io/documentation/#mjml-group) for the group tag in the documentation.
2. Paste the sample code into MJML App (v2.9.0).
3. Send email from the app through Mailjet API.
4. Check email on:
 - PC-Windows-Chrome-Gmail
 - PC-Windows-Chrome-Gmail (responsive) -> inspect page -> toggle device toolbar -> select a device with a small screen e.g., iphone 5. (May require to refresh the page after selecting device.)
 - iphone_5-GmailApp
 - huawei_p10_lite-GmailApp

**Expected behavior:**

On both desktop view (large screen) and mobile view (small screen) the two columns should stack horizontally.

**Observed behavior:**

 - On desktop and mobile view using PC-Windows-Chrome-Gmail (normal and responsive) the columns are stacked horizontally as expected.
 - On mobile view using huawei_p10_lite-GmailApp the columns are stacked horizontally as expected.
 - On mobile view using iphone5-GmailApp the columns are stacked vertically.

**Screenshots and GIFs**

 - Working as intended on PC-Windows-Chrome-Gmail:
![PC-Windows-Chrome-Gmail](https://user-images.githubusercontent.com/11627116/39184846-573b0468-47c5-11e8-9a04-a0244e7bdcd2.png)

 - Not working as intended on iphone5-GmailApp:
![iphone5-GmailApp](https://user-images.githubusercontent.com/11627116/39185173-95caf246-47c6-11e8-867d-bfbe280ed182.JPG)

**MJML version:**

MJML v^4.0.3

**Email clients the bug is seen on:**

iphone5 Gmail v5.0.180408

**NOTE**

I did further testing, which I did not include above. I reduced the width of the images and all wrappers (columns, group, body, etc.). After doing that the columns stacked as intended on iphone5-GmailApp as well, but this doesn't seem like an optimal solution.

Is this a bug or are grouped columns just forced to stack vertically when the screen is too small? (Is the iphone 5 screen considered too small / out of date?)

**Comment by ngarnier** [comment]
Did you try minifying the output as suggested in the documentation?

>  iOS 9 Issue: If you use a HTML beautifier for MJML output, iOS9 will render your columns inside a mj-group as stacked. On the output HTML, remove the blank space between the two columns inside a mj-group

**Comment by haxic** [comment]
Good point. It was checked off. I'll test it quickly.

**Comment by haxic** [comment]
Ah. That solved it. I missed that particular warning... Thanks for the quick response!

**Comment by ngarnier** [comment]
No worries, glad it solved your issue! 

It's true the message isn't that clear, PR appreciated to make it easier to understand!

**Comment by haxic** [comment]
Funny 😀

**Comment by ngarnier** [comment]
Like mentioned [here](https://github.com/mjmlio/mjml/issues/1157#issuecomment-383914340), minifying the whole HTML will solve the issue. 

There's an issue with minifying on 4.0.5 that will be fixed in 4.1.0, but you can use http://kangax.github.io/html-minifier/ (it's the one we're using) and uncheck "Minify CSS" to minify your HTML.

**Comment by AtoianAvetik** [comment]
Thanks for the quick response! I will try it.

**Comment by halws** [comment]
for anybody whom minifying didn't help 

there is another fix - set last column width  `width - 1%` or experiment what would work to you eg  `width - 0.5%` etc

for example:

```html

<mjml>
  <mj-body>
    <mj-wrapper background-color="white" padding="0 32px 0 32px">
      <mj-section>
        <mj-group>
          <mj-column width="40%" border="1px solid red">
            <mj-image width="137px" height="185px" padding="0" src="https://mjml.io/assets/img/easy-and-quick.png" />
            <mj-text align="center">
              <h2>Easy and quick</h2>
              <p>Write less code, save time and code more efficiently with MJML’s semantic syntax.</p>
            </mj-text>
          </mj-column>
          <mj-column width="59%" border="1px solid blue">
            <mj-image width="166px" height="185px" padding="0" src="https://mjml.io/assets/img/responsive.png" />
            <mj-text align="center">
              <h2>Responsive</h2>
              <p>MJML is responsive by design on most-popular email clients, even Outlook.</p>
            </mj-text>
          </mj-column>
        </mj-group>
      </mj-section>
    </mj-wrapper>

  </mj-body>
</mjml>

```

https://mjml.io/try-it-live/h0vcqNO99u

**Comment by orlin7** [comment]
Thanks that solved the issue for me, but that causes issues with the Outlook 2016 and Outlook 2019 versions
![Outlook issue](https://github.com/user-attachments/assets/bafe8f52-65d7-42cb-acd1-7ede5b1ee4b0)

Any ideas.
