### ISSUE TITLE
4.0.4 mjml-cli assumes file path without extension is a directory

### ISSUE THREAD

**Issue by antonyoneill** [mjmlio/mjml#1158]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
I have a compilation process that generates a temporary file using `tempnam` in PHP which creates a file for my pleasure, this file does not have an extension (example: `/private/var/tmp/mjmloutputdmCS2N`)
I use this file as an output destination for the HTML compiled by the `mjml` command.

This worked in 4.0.3, but now in 4.0.4 I get an error stating that the given path is not a directory.

If the node already exists, and is a file then it should output the HTML to the file, if it's a directory then it should output input.html - I guess. And if the node doesn't exist at all, then it should create the directory? 

**Reproduction Steps:**

1. Install `mjml@4.0.4`
2. Create a token MJML file `./input.mjml`
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
3. Create a file without an extension `./output`
4. Run `mjml -r ./input.mjml -o ./output`

**Expected behavior:**

The file `./output` contains the compiled HTML

**Observed behavior:**

A command line error occurs
```
Command line error:
Output directory doesn’t exist for path : ./output
```

**Screenshots and GIFs**

Probably overkill for this...

**MJML version:**

4.0.4

**Comment by kmcb777** [comment]
Hi @antonyoneill we chose not to create directories, only non-existing files, but this check was wrong indeed, it should just check the parent directory. The fix should be released soon
