### ISSUE TITLE
mj-social-element src attribute doesn't work

### ISSUE THREAD

**Issue by ganlanyuan** [mjmlio/mjml#1159]
`<mj-social-element>` src attribute doesn't work.

**Reproduction Steps:**
Check out this demo: https://mjml.io/try-it-live/ByClvhn2f

I also tested on local which has the same issue.
I used JavaScript API on local.
index.js
```javascript
const mjml2html = require('mjml'),
      fs = require('fs'),
      path = require('path');

function run () {
  fs.readFile('index.mjml', {encoding: 'utf-8'}, (err, data) => {
    if (err) { return console.log(err); }
    let htmlOutput = mjml2html(data, {
      minify: true
      // beautify: true
    });
    // console.log(htmlOutput)
    fs.writeFile('index.html', htmlOutput.html, err => {
      if (err) { return console.log(err); }
      console.log('index.html saved');
    });
  });
}

run();
```
And do `node .`

**Expected behavior:**
Expect MJML uses my customized images.

**Observed behavior:**
But it uses the default images.

**MJML version:**
v4.0.3

Npm: v5.6.0
Node: v8.11.1

**Email clients the bug is seen on:**
All

**Comment by iRyusa** [comment]
Hi,

This is because you're using the `name` attribute that doesn't allow any override. Just remove them, apply your bakcground color and you're good cf : https://mjml.io/try-it-live/SJXucnh2G

**Comment by ganlanyuan** [comment]
I see, thanks
