### ISSUE TITLE
Outlook 2013 crops/stretches background image

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml#116]
Setting a background image will be ignored by Outlook 2013.

Furthermore, I wonder if it was the intention to let "background-url" replace background-color?

E.g. when using a transparent png, the transparent part will show the color of the body, and not the one that was defined in the section. (Directly in the Live Editor)

**Comment by janus-reith** [comment]
Altough this is not completetly related to this issue, could someone here tell me how to implement something more complex, like a shadow around my 600px newsletter?

Using repeating images --> Not working in Outlook
Using nested 1px tables with different color --> Can not be implemented using MJML

**Comment by iRyusa** [comment]
Hi @janus-reith ,

There's a VML fallback for background image, is this not working for you ?
We'll add support for background color with a background url shortly !

**Comment by janus-reith** [comment]
Seems like it isn't, the sections have no bg image.
I am using the live editor, Is it up to date?

**Comment by iRyusa** [comment]
Yes it should be, can you give me your MJML ?

**Comment by janus-reith** [comment]
This is a small excerpt of my code, however it works to reproduce the issue.

[http://pastebin.com/ywm3KFja](url)

It works as intended in gmail, in all browsers I tested.
The Mailclient on iOS, and most i tested on Android will not show it, as intended to make best use of the available space.

Outlook 2013 ignores them.

**Comment by janus-reith** [comment]
I just tried replacing the background image in the code above, and it is shown.(In the example above: Replaced shadow_repeat_600_white.jpg with shadow.jpg)

Therefore I assume that the background image gets stretched somehow in outlook, and therefore I could see the white part of it , but not the left and right 40px of the 600px image that create the  shadow.
I will investigate this further to determine the actual width outlook is showing.

**Comment by janus-reith** [comment]
Interesting. I just created [this](http://www.cds-service.com/newsletter/images/Image/2016/NN/colormeter.jpg) 600px mutlicolored image and used it with my code above. While most clients show it as expected, Outlook will only show green and white.

My conclusion is, that Outlook will only show an area of something between 440-460px of my 600px background image.

**Comment by janus-reith** [comment]
Just tested the AMARIO template in Outlook 2013.
The background image with the boats also has a width of 600px, but outlook doesn't cut of any width. 

Instead it repeats in height, but this is probably a design issue, as it happens in Outlook 2013, Chrome, Iphone 6s and even in the try-it-live mobile view.

**Comment by janus-reith** [comment]
I just tested again, in outlook 2013 my 600*1px bg image is cropped at 450px and then stretched back to fit the 600px. My workaround atm is to do the same in reverse:

I take my bg image, shrink it to 450px leaving 75px white on each side.
Then I take my finished MJML HTML code and replace every <v:fill> with the extra outlook version.

**Comment by iRyusa** [comment]
It might be an issue with the generated vml then. Big :+1: for your investigations

**Comment by janus-reith** [comment]
Well, I nearly can't believe that it took me so long to find the solution:

<v:fill>'s type has to be changed from type="tile" to type="frame".

I would prepare a PR for this, but it is a bit complicated:
Im unsure if type="tile" could also be needed by some users, so I can not just replace it with fill.

On the other hand it also seems a bit hacky to add an additional parameter for mj-section to select which one to use, as this is an Outlook-specific thing.

**Comment by m2ses** [comment]
v:fill type"frame" not stretching nor resizing images in outlook.com, any alternatives?

**Comment by iRyusa** [comment]
@m2ses It's the 3rd times we're telling you that VML won't do anything for outlook.com and is only used in desktop Outlook application 

Outlook.com doesn't support any background related property so there's no fix for that...

https://github.com/mjmlio/mjml/pull/165#issuecomment-325333291
https://github.com/mjmlio/mjml/pull/165#issuecomment-325298659

**Comment by m2ses** [comment]
Sorry, Thank you for the info

**Comment by m2ses** [comment]
I have a meeting with Microsoft tomorrow if they provide a solution I will let you know.

**Comment by iRyusa** [comment]
Well I think we can close that now, current implementation of VML doesn't look to be an issue for people using MJML now. 
We'll reopen if the community needs a switch from `tile/frame` behavior
