### ISSUE TITLE
Since mjml 4.0.5 watch does not work

### ISSUE THREAD

**Issue by vielhuber** [mjmlio/mjml#1171]
![index](https://user-images.githubusercontent.com/3183737/39306110-7c37cbb6-495f-11e8-8ae0-ac5fb97e9aaa.png)

**Comment by kmcb777** [comment]
Hi @vielhuber thanks for reporting this

**Comment by mohsentaleb** [comment]
I just tried 4.0.3 and 4.0.4 and they wont work either. Didn't have time to test previous versions. 
@vielhuber @kmcb777

**Comment by kmcb777** [comment]
Yes i saw that, but we hadn't noticed yet, anyway there's a pr for the fix now, should be included in 4.1 :)

**Comment by michelgotta** [comment]
For everyone struggling with this and waiting for 4.1 to release. Here is a hotfix for 4.0.5 for usage like `mjml --watch input.mjml --output index.html` running it from node_modules and use a prebuild version:

In file `node_modules/mjml-cli/lib/client.js` find 

```
if (inputs.length) {
    _context.next = 31;
    break;
}

error('No input files found');
return _context.abrupt('return');
```

replace line 192–195 with:

```
if (true) {
    _context.next = 31;
    break;
}
```

or remove the if statement to pipe the code to the next step (31). 

@kukac7 @mohsentaleb @vielhuber

**Comment by kmcb777** [comment]
Hi @michelgotta @kukac7 @mohsentaleb @vielhuber we released a new beta for mjml 4.1, which you can install with `npm install mjml@next`. This watch problem is now solved, feel free to try !

**Comment by pierresis** [comment]
> Hi @michelgotta @kukac7 @mohsentaleb @vielhuber we released a new beta for mjml 4.1, which you can install with `npm install mjml@next`. This watch problem is now solved, feel free to try !

It does not change anything for me :(

**Comment by kmcb777** [comment]
Hi @pierresis this bug is solved but maybe you have an other one, could you describe your problem a bit more ?
Which mjml version are you using ?
What command are you using ?
If you add `--config.stack=true` at the end of the command, do you get an error message ?

**Comment by pierresis** [comment]
Hi @kmcb777 this is ok, it was my bad. Dunno why i the version i had was before 4.0.
It's ok now :)

Thank you and have a good evening.
