### ISSUE TITLE
mjml-column: Background property on table is invalid, should have been css style or bgcolor instead

### ISSUE THREAD

**Issue by tkafka** [mjmlio/mjml#1174]
MJML generates `<table background="#f2f2f2" ...>` which is [not valid](https://developer.mozilla.org/cs/docs/Web/HTML/Element/table).

What happens in `email.seznam.cz` webmail is that they parse this as an unknown property, find a `#f2f2f2` value which is a valid url (unexpectedly and really :) ), assume that it is an url of a background image, and display a warning about email containing external images.

**Reproduction Steps:**

1. Use `<mj-column background-color="#f2f2f2">` in an email template
2. `<table background="#f2f2f2" ...` is generated in the output
3. Email HTML becomes invalid, and some clients understand this construction as providing external image as background, and display warning about external images.

**Expected behavior:**

We use (deprecated) `<table bgcolor="#f2f2f2" ...` instead, or, even better we listen to the advice in [table spec](https://developer.mozilla.org/cs/docs/Web/HTML/Element/table):

> The `<table>` element should be styled using CSS. Use the background-color property in CSS to create an effect that is similar to the bgcolor attribute.

**Observed behavior:**

`email.seznam.cz` webmail displays warning about external images when a `mj-column` with `background-color` is used.

**MJML version:**

4.0.5

**Email clients the bug is seen on:**

email.seznam.cz (webmail)

**Comment by kmcb777** [comment]
Hi @tkafka this has been fixed in the new release mjml4.2-beta, which you can install with `npm install mjml`, you can check if it solves the problem
