### ISSUE TITLE
mjml-4 winmail 10 rendering problems

### ISSUE THREAD

**Issue by wireinet** [mjmlio/mjml#1178]
Hello! i use mjml 4! Its great! problems with outloook 2007 now in solved - all rendering is fine!
BUT... 
in win 10 i have problem with rendering hero image! See the attachment:
![win10 mail](https://user-images.githubusercontent.com/23517333/39405848-e0146402-4bb5-11e8-8126-61e68493fb6b.png)
Early i have same issues with same - you recomend me to use fluid-height - now it it - but...again - not right rendering...

**Comment by iRyusa** [comment]
Hi,

I don't really understand the issue, the background should be under the button too ?
We still need more information like MJML version, and a MJML to reproduce.

**Comment by wireinet** [comment]
Hello!
Yes, you right! Look at the picture: left-is ok - right - win10mail client:
![error](https://user-images.githubusercontent.com/23517333/39418904-bdd091b2-4c65-11e8-8b75-67d2c00723b1.jpg)

**Comment by iRyusa** [comment]
> We still need more information like MJML version, and a MJML to reproduce.

Again...

**Comment by wireinet** [comment]
![2018-04-30_08-03-11](https://user-images.githubusercontent.com/23517333/39418990-32cf39a0-4c66-11e8-8fe3-246c82a26503.png)
[index.zip](https://github.com/mjmlio/mjml/files/1959845/index.zip)

**Comment by iRyusa** [comment]
Well your background image looks really small (515x314) getting a bigger image should fix it.

**Comment by wireinet** [comment]
ok. i Understand. thank you.
