### ISSUE TITLE
Inserting as text in Outlook results in distorted images

### ISSUE THREAD

**Issue by barkan** [mjmlio/mjml#1179]
When taking a rendered HTML file and using "Insert as text" in Outlook, the horizontal sizes of columns and items is reduced, resulting in distorted images

**Reproduction Steps:**

1. Go to https://mjml.io/try-it-live/templates/basic and view HTML
2. Save the HTML to a file
3. In Outlook, create a new email and use "Insert as text" to create the email. (instructions for doing this can be found at https://www.linkedin.com/pulse/how-insert-html-source-code-outlook-emails-maurizio-la-cava )

**Expected behavior:**

Circles and other images should maintain proportional width and height.

**Observed behavior:**

Images and dimensions are squeezed and distorted.

**Screenshots and GIFs**

<kbd>![image](https://user-images.githubusercontent.com/974668/39548085-795f87c2-4e27-11e8-9b96-ec87a26f1abb.png)</kbd>

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

Outlook 2016 on Windows 10 Enterprise

**Comment by iRyusa** [comment]
We can’t do anything on this one as Outlook clearly mess with html. Please use an esp or a site like putsmail to sens test email instead of this.
