### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [mjmlio/mjml#118]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because I want to give some of money to mjml, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like mjml.
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work mate!

**Comment by ngarnier** [comment]
hey @Francolpm, 

Really sorry about the late answer, this issue definitely slipped through. 

We won't take payments but feel free to share about MJML on Twitter or wherever you can and it'll make us happy! Thanks for the kind words.
