### ISSUE TITLE
mj-accordion only contain mj-accordion-text?

### ISSUE THREAD

**Issue by edwh** [mjmlio/mjml#1183]
This is a question more than a bug report.  Looks to me from the docs and experimentation like the accordion can only contain mj-text, which means that I can't put rich content in there.  Have I understood correctly?

**Comment by iRyusa** [comment]
Nope as mentioned in the doc mj-accordion-text receive plain HTML so you can write anything you want inside it ( I think in demo we did put a span to showcase it )

**Comment by edwh** [comment]
Thanks for your reply.

If I use this on try it live, I don't see the image.  What am I doing wrong?

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-accordion>
          <mj-accordion-element>
            <mj-accordion-title>Why use an accordion?</mj-accordion-title>
            <mj-accordion-text>
              <mj-image src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png" />
              <span style="line-height:20px">
                Should see an image.
              </span>
            </mj-accordion-text>
          </mj-accordion-element>
        </mj-accordion>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
You have to use regular HTML not mjml

**Comment by edwh** [comment]
Ah, I see.  That is a shame - doesn't it mean you can still only put pretty simple stuff inside the accordion, otherwise you'll have to figure out all the stuff that MJML normally does for you?

(Not complaining much, MJML is amazing.)

**Comment by iRyusa** [comment]
Well at this point everything is kinda safe. Section/column already do the hardest job for you.

**Comment by ngarnier** [comment]
As @iRyusa said, you're pretty safe to put HTML inside the accordion as it's contained inside responsive containers (sections, columns, and the accordion-text tag).

**Comment by edwh** [comment]
OK. But it still seems a shame to me. It means that, for example, if I want a button inside there then I have to code the button manually inside an accordion, and try to make it consistent with an mjml button outside the accordion.

**Comment by ngarnier** [comment]
Agreed it would be better to be able to render MJML. 

It used to be impossible in MJML 3 to render MJML inside a custom component but as it's possible now in MJML v4, this feature should be doable. It's not something we'll be able to work on in a near future, but if you're interested in working on a fork (and better yet, a PR), you can check how to render MJML inside a component here: https://github.com/mjmlio/mjml-component-boilerplate/blob/master/components/MjLayout.js#L84-L98.

Not sure how being able to render both HTML & MJML should be handled though.

**Comment by edwh** [comment]
Thanks. I understand that the right answer for an open source project is to help improve it :).
