### ISSUE TITLE
Anchor links within emails

### ISSUE THREAD

**Issue by edwh** [mjmlio/mjml#1184]
Can we insert links to other parts of the email, so that you can have a table of contents effect?

Apologies if this is somewhere obvious in the docs that I've missed.

**Comment by iRyusa** [comment]
You can use anchor tag like in HTML, but supports depends on clients

**Comment by edwh** [comment]
I remember (years ago) doing this, but I'm not up to date on which 
clients support it.  Do happen you know whether this will break badly in 
any clients?  It's fine if clicking just doesn't work, but I have a 
vague memory of it causing issues, so I haven't used it recently.

------ Original Message ------

**Comment by iRyusa** [comment]
I don’t use them personally so idk. Best way to figure it out is to look on litmus forum or any blog post about the support
