### ISSUE TITLE
Specify extension for output files on batch compile

### ISSUE THREAD

**Issue by samatcd** [mjmlio/mjml#1185]
There doesn't seem to be any way to set the extension on batch template compiles. E.g., `mjml -w src/*.mjml -o dist/` will always output the file with `.html` extension.

**Feature request:**

I'd like to be able to tell the `mjml` command what extension to use, e.g., `mjml -w src/*.mjml -o dist/ --extension php`.

**MJML version:**

4.0.5

**Comment by samatcd** [comment]
Ok, thanks - will sort something out. Was hoping for a simple solution, but understand that position if it's not straight-forward.

**Comment by Calinou** [comment]
If anyone is wondering how to do this without external tools, see https://github.com/mjmlio/mjml/issues/866 :smiley:

Those issues ask similar questions, so I thought it would be helpful to link here.

**Comment by timack** [comment]
@Calinou Thanks a bunch, worked like a charm.
