### ISSUE TITLE
mj-navbar can work on Android

### ISSUE THREAD

**Issue by dcg-git** [mjmlio/mjml#1187]
**You can remove this. It seems my "fix" breaks the hamburger menu in IOS.** 
      
I found that while using the Live Editor the HTML generated symbols for the hamburger menu instead of the ASCII codes. See Screenshots. By Manually editing the output I got the hamburger to work on Android 7.

**Reproduction Steps:**

1. Use the Live Editor on the website.

**Expected behavior:**

Hamburger Menu should not work on Android Mail.

**Observed behavior:**

Hamburger menu does work on Android 7 with proper ASCII &#9776 and &#8855.

**Screenshots and GIFs**

![encoding](https://user-images.githubusercontent.com/25446608/39771934-d13b1d32-52c1-11e8-91a3-79af5cb435bc.PNG)
![encoding2](https://user-images.githubusercontent.com/25446608/39772219-a22c6fd6-52c2-11e8-91ea-c05d6a150458.PNG)

**MJML version:**

Live Editor on website

**Email clients the bug is seen on:**

Android Mail, BlueMail on Android 7.

**Comment by iRyusa** [comment]
Hi 

Is this only an issue on the try it live ? We're using a different parser for security reasons on the website, if it's not the case with the cli version I will close this issue then

**Comment by iRyusa** [comment]
Maybe we can fix this for 4.2 @kmcb777 it's just removing those `String.fromCharCode`
