### ISSUE TITLE
Windows 10 Mail: Background Color Missing

### ISSUE THREAD

**Issue by jmfisherr** [mjmlio/mjml#1191]
When testing via Litmus the background color for Windows 10 Mail is being displayed as white.

**Expected behavior (Viewing Outlook 2016 on Windows 7):**
https://snag.gy/gLkq5f.jpg

**Observed behavior (Viewing Windows 10 Mail on Windows 7):**
https://snag.gy/A1gkm4.jpg

Applied background color to email by using `background-color="#eaeaea"` on the `<mj-body>` tag.

**MJML version:**
4.0.3

**Comment by callaginn** [comment]
Haven't used MJML yet, but I solved a similar issue on a Foundation email yesterday with some conditional code. I believe I placed this in my body tag.

````html
<!--[if mso 16]>
	<style type="text/css">
		html, body, .bgtable .bgcell {background: #eaeaea;}
	</style>
<![endif]-->
````

That snippet of code adds back the background for Windows 10 Mail. However, it will also disable looping background patterns in Outlook 2016. (I was using solid colors as a fallback in that particular template).

**Comment by kmcb777** [comment]
Hi @jmfisherr @callaginn , thanks for reporting this.
There is already an issue concerning this : #572 so i'll close this one.
We found another workaround (see my last message on this issue), please let us know if this works for you :)

**Comment by kmcb777** [comment]
Hi @callaginn , i was trying your snippet but it doesn't seem to work. Is there a `table.bgtable` in your elements ? It doesn't seem to work on `body` and `html` so i think it's the one on `table` that made it work. 
Therefore using a `<mj-wrapper background-color="color">` is a good workaround, it will wrap its content in a table, whose background will work in win10 mail.
