### ISSUE TITLE
mj-image breaks when mj-column width is set

### ISSUE THREAD

**Issue by eatplaysleep** [mjmlio/mjml#1193]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
When adding a width to <mj-column>, if there is an mj-image in the column, the image disappears. 

The following will show the image:
```
<mjml>
   <mj-body>
      <mj-section background-color="black">
         <mj-column>
            <mj-image width="11px" src="https://assets.influential.co/dashboard/email-templates/icon-facebook_2x.png" />
         </mj-column>
      </mj-section>
   </mj-body>
</mjml>
```
<img width="1459" alt="screen shot 2018-05-10 at 6 55 20 pm" src="https://user-images.githubusercontent.com/37595884/39902599-bb6f91cc-5483-11e8-8507-582e689556a2.png">

The following, with the addition of `width="20"` to mj-column, will **not**:
```
<mjml>
   <mj-body>
      <mj-section background-color="black">
         <mj-column width="20">
            <mj-image width="11px" src="https://assets.influential.co/dashboard/email-templates/icon-facebook_2x.png" />
         </mj-column>
      </mj-section>
   </mj-body>
</mjml>
```
<img width="1452" alt="screen shot 2018-05-10 at 6 55 55 pm" src="https://user-images.githubusercontent.com/37595884/39902611-ccf8ed8a-5483-11e8-91fe-2cea023b63bb.png">

**Comment by iRyusa** [comment]
Hi,

It’s behaving as expected. On the computed Width it will remove padding left and right. Reset the padding to 0 on mj-image and it should work fine. Don’t forget to add unit on mj-column width

**Comment by eatplaysleep** [comment]
Solved it! I would not have expected that. Appreciate the help.
