### ISSUE TITLE
Terminal can't run --watch (but compiles successfully)

### ISSUE THREAD

**Issue by robincollin** [mjmlio/mjml#1195]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
Hello everyone!
I'm trying to use MJML. But my workflow is totally stuck due to a problem with the --watch option. I can compile mjml to html normally by using

`mjml index.mjml -o index.html`

but unfortunately `mjml -w index.mjml -o -index.html` the same with `--watch` returns

```
Command line error:
No input files found
```

I already un- and reinstalled mjml. I tried to install mjml globally, but this disn't help either. Does someone has an idea how to fix this? Thanks in advance.

Versions:
mjml-core: 4.0.5
mjml-cli: 4.0.5

**Comment by iRyusa** [comment]
Hi,

There's already an open issue on that here #1171 it will be fixed in 4.1, in the meantime you can use gulp plugin to have a working `watch`
