### ISSUE TITLE
[Help wanted] Text disappears in <mj-column> tag

### ISSUE THREAD

**Issue by Premitium** [mjmlio/mjml#1204]
I  have this markup:
  <mj-section>
     <my-column>
        <mj-text color="#938d93" font-size="20px" font-family="Montserrat">
          <a href="#"> Privacy Policy </a>
          <mj-text color="#938d93">
            |
          </mj-text>
        </mj-text>
      </my-column>
</mj-section>

If the text is outside of the <my-column> tag it renders. 
Trying it with an image is the same.

What am I missing here?

**Comment by iRyusa** [comment]
You can't use `mj-text` inside an `mj-text`, you can use only plain HTML inside it.

**Comment by Premitium** [comment]
I had a typo    </my-column>. But the nested text works.

**Comment by iRyusa** [comment]
`mj-text` won't be replaced by an actual HTML tag, so even if browser display the content ( it will behave like a div ) it will produce invalid HTML. Attributes on `mj-text` won't even work. So no, it doesn't.
