### ISSUE TITLE
MJML watch not working

### ISSUE THREAD

**Issue by ktrantm** [mjmlio/mjml#1209]
When running **mjml --watch index.mjml -o index.html** or **mjml -v**, I'm getting the command line error **No input files found**.

I find this odd since I can run **mjml -r index.mjml -o index.html** just fine.

![mjml_watch_error](https://user-images.githubusercontent.com/39101201/40323951-dab754e6-5ceb-11e8-9761-554fd8d35c31.png)

**MJML version:**
Version 4.0.5

**Comment by kmcb777** [comment]
Hi @ktrantm , thanks for reporting this. There is already an issue about this : #1171, so i'll close this one.
This will definitely be fixed in the next release 👍
