### ISSUE TITLE
Using custom component?

### ISSUE THREAD

**Issue by peckrob** [mjmlio/mjml#121]
Maybe I'm missing something, but there seems to be a pretty big hole in the documentation between creating a custom component ... and actually using it.

https://mjml.io/documentation/#create-a-component

I ran:

`mjml --init-component header`

and it created a Header.js file in the current directory. And then what? How do I use the custom component I just created? Simply running `mjml` throws an error when I try to use `mj-header`

`Error: [MJMLError] UnknownMJMLElement: Could not find element for : mj-header`

But I can't see anything in the docs or the CLI tool that shows how to actually use the component.

**Comment by GuillaumeBadi** [comment]
Hey @peckrob !

You are quite right, the CLI cannot handle imports yet as mentionned here https://github.com/mjmlio/mjml/issues/120 .

To use custom components at the moment, you have to create a JS file, and `require` every custom components before calling the mjml2html function

**Comment by epayet** [comment]
The documentation is not really clear about how to import custom components... I created a starter-kit for this purpose, where you can put your custom components on the `components` folder and then start the dev mode (file watching) or just build it manually. Have a look ;) 

https://github.com/epayet/mjml-starter-kit

**Comment by arnaudbreton** [comment]
Thanks @epayet for sharing! @peckrob did it makes thing easier to you?

As @GuillaumeBadi said, the import tag will be the solution we would like to implement to solve this issue. Feel free to participate in the discussions there!

**Comment by kila03** [comment]
@epayet first of all thank you for the starter kit - it rocks! Will it be upgraded to show how it works with v2 of mjml?

**Comment by epayet** [comment]
@kila03 Thanks! It will be upgraded, I'll do it as soon as I can :)
