### ISSUE TITLE
mj-table compiles to table with incorrect styling / attributes

### ISSUE THREAD

**Issue by devonJS** [mjmlio/mjml#1210]
`mj-table` compiles into a HTML `table` with incorrect attributes and styling, also unable to set cellpadding and cellspacing for the table.

**Reproduction Steps:**

1. ./node_modules/.bin/mjml -w ./mjml/example.mjml --config.beautify -o ./html
2. Open html file and compare the HTML `table` created from `mj-table`

**Expected behavior:**

`mj-table` should convert to a `table` with valid attributes and styling

**Observed behavior:**

`<mj-table></mj-table>`

compiles to

`<table 0="[object Object]" 1="[object Object]" 2="[object Object]" border="0" style="cellspacing:0;color:#000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;"> </table>`

and

`<mj-table cellspacing="0" cellpadding="0"></mj-table>`

compiles to

`<table 0="[object Object]" 1="[object Object]" 2="[object Object]" border="0" style="cellspacing:0;color:#000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;"> </table>`

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

All

**Comment by iRyusa** [comment]
Hi @devonJS 

It already has been fixed in 4.0.4/5, so I'm closing the issue

**Comment by devonJS** [comment]
thanks looks good, though there's a style="cellspacing:0;" still being created for the table.
