### ISSUE TITLE
Bordered section wraps all following sections in Outlook

### ISSUE THREAD

**Issue by trentclowater** [mjmlio/mjml#1219]
Using MJML 4.0.5, when trying to create a bordered box using the code below, the section containing the border wraps the content of all the following sections. The wrapping issue happens on the email clients listed below. It is fine on Mac OS versions of Outlook 2011 and 2016, and the other 73 email clients tested. 

**Reproduction Steps:**
1. Use the following MJML code to compile an HTML email.

```
<mjml>
  <mj-body background-color="#ffffff">
    <mj-section css-class="body-section">
      <mj-column>
        <mj-text>
          Preceding section 1
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#dddddd" border-top="20px solid #000000" border-left="2px solid #000000" border-right="2px solid #000000">
      <mj-column>
        <mj-text>
          Box top section.
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#dddddd" border-bottom="2px solid #000000" border-left="2px solid #000000" border-right="2px solid #000000">
      <mj-column>
        <mj-text>
          Box bottom section.
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section>
      <mj-column>
        <mj-text>
          Following section 1
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section>
      <mj-column>
        <mj-text>
          Following section 2
        </mj-text>
      </mj-column>  
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior:**

![normal](https://user-images.githubusercontent.com/51736/40527269-0b19f8de-601e-11e8-9cc1-378a8ec40d63.png)

**Observed behavior:**

![issue](https://user-images.githubusercontent.com/51736/40527317-412ef97e-601e-11e8-9fdf-a0d6416ab3f6.png)

**MJML version:**

4.0.5

**Email clients the bug is seen on:**

Windows Mail 10
Outlook 2017 (Windows 7)
Outlook 2016 (Windows 7)
Outlook 2013 (Windows 7)
Outlook 2010 (Windows 7)
Outlook 2007 (Windows 7)
Outlook 2003 (Windows 7)
Outlook 2002 (Windows 7)
Outlook 2000 (Windows 7)
IBM Notes 9 (Windows 7)
Lotus Notes 8.5 (Windows 7)
Lotus Notes 8.0 (Windows 7)

**Comment by trentclowater** [comment]
Actually, this may be related to #1201. I just tried turning minifying off, and the issue didn't happen.

**Comment by ngarnier** [comment]
Yep, indeed the same issue as #1201. It will be fixed in the next release.

I'm closing to the benefit of #1201.
