### ISSUE TITLE
Split a column into two sections?

### ISSUE THREAD

**Issue by Narey** [mjmlio/mjml#1228]
I have an email template that I'm having problems with. What I'm trying to do is essentially split a column into 2 sections, if this is even possible. I've attached the full MJML code and a diagram of what I'm actually wanting, fingers crossed someone knows a better way around it as I'm stuck for ideas.

[
![image](https://user-images.githubusercontent.com/11885821/40843584-5a719564-65a9-11e8-93ee-927fbe8fe39b.png)
](url)

Here is the code: https://pastebin.com/Akx9xViD (it bugged out when I just added the code quotes so I just pasted it into PasteBin! BTW I'm just using the try-it-live site, so I'm not sure on the version, I believe it's v4.

Thanks in advanced!

**Comment by iRyusa** [comment]
Hi! 
I'm really sorry but i'm not really sure what you want to achieve here 🤔 

`column` cannot be split into sections because a section of an email is basically a "row" of your email.

You should be really careful when creating an email as a website because it doesn't behave like you would expect in email clients.

**Comment by Narey** [comment]
> I'm really sorry but I'm not really sure what you want to achieve here 🤔
So the black boxes are 2/3 columns that are in a section, I'd like to essentially have the 2 columns that are there and half them, so they act independently from the top half. I can't add another section (which would be nice and easy) as it would be placed below **Got a gift card?**. Ideally, I would love to make a new section, trim it down to say 70% and slot it in the gap under the existing options, if that way of putting it makes sense for what I'm trying to achieve?

**Comment by iRyusa** [comment]
Mh, so what won't you just use regular table with 2 td instead of a section ?

**Comment by iRyusa** [comment]
I'm closing it, because I think the solution is to have a table width 2 td here if you need to split it.

Feel free to reopen if needed
