### ISSUE TITLE
Cloud9 integration

### ISSUE THREAD

**Issue by jarodium** [mjmlio/mjml#123]
Hello there

I would like to suggest Cloud9 integration :)

**Comment by arnaudbreton** [comment]
@jarodium thanks for sharing! Any idea how we could help things move forward here?

**Comment by jarodium** [comment]
The integration could be as the code coloring on the cloud9.
Parsing and previewing I think it be be achieved by developing a plugin for them.

My knowlegde of the Cloud9 plugin system is very rudimentary, as I am developing a MySQL plugin ( at this time work is pretty much stalled due to lack of time ) for interfacing with a MySQL server.

**Comment by ngarnier** [comment]
hey @jarodium, did you finish developing your MySQL plugin? If this is still a thing, we could use your experience to see how to develop a MJML plugin for Cloud9 :-)

**Comment by jarodium** [comment]
Hello @ngarnier 
Unfortunately I had to put that on hold, because of professional reasons ( not related to the plugin ).
You can base your plugin on mine, but keep in mind that work may already be behind the newest changes of c9's sdk, since the project is in alpha and the API still is unstable...
If there is something I can help with, please let me know. I will try to take a short time to help out...

**Comment by ngarnier** [comment]
Hello, same thing as for an IntelliJ plugin (https://github.com/mjmlio/mjml/issues/53), it's really interesting but we won't be able to develop and maintain one ourselves for now so I'm closing. Obviously, we'll welcome and gladly feature any contribution for this!
