### ISSUE TITLE
Problem with Office and Outlook

### ISSUE THREAD

**Issue by Krulzor** [mjmlio/mjml#1230]
Hello, we were having problems with Office /Outlook but saw that can be fixed with:

`<mjml></mjml>
<mjml owa="desktop">
....
</mjml>`

And indeed it fixed it but at the same time we manage to break **Gmail with iPhone** .

Desktop Gmail(iPhone) version looks good but Gmail Mobile(iPhone) doesn't make the pictures to fit the full width.(100%)

Any other workaround to this?=)

Thank you!

**Comment by iRyusa** [comment]
Hi

The fix for MJML App has nothing to do with full width image. It's a known issue here #263 and we're trying to add a new fuild on mobile attribute on 4.1.

I'm closing the issue in favor of 263

**Comment by Krulzor** [comment]
You are right, sorry, the developer told me so, my apologies. **It has nothing to do**. Will check #263 thank you!.
