### ISSUE TITLE
mj-text href

### ISSUE THREAD

**Issue by bkonia** [mjmlio/mjml#1235]
It seems strange that mj-text does not have an href attribute. It would be convenient and consistent to be able to add links to mj-text elements the same way we do for mj-image, etc... 

I understand we can add <a> tags inside mj-text, but I think a goal of this project should be to minimize the amount of HTML that has to be added, as it makes for ugly, less readable, less elegant code. It's kind of like adding HTML tags in a Markdown document. You can do it, but then you're defeating the purpose of using Markdown.

**Comment by ngarnier** [comment]
Many users add links inside of `mj-text` tags and not for the whole text inside, like that:

```
<mj-text>
    This is a <a href="mjml.io">link</a>
</mj-text>
```

If we allowed what you're saying, it would be possible to have a link on the `mj-text` tag and then a link inside the `mj-text`, therefore an `a` tag nested inside another `a` tag, which is invalid in HTML.

Therefore, using `a` inside of `mj-text` remains the safest and most flexible solution. And you can still do that for your purpose, which doesn't bloat up your code:

```
<mj-text>
    <a href="mjml.io">This is a paragraph linked</a>
</mj-text>
```

**Comment by alexshi0000** [comment]
This creates problems because if the href contains for example an ampersand `&` it will get sanitized to something HTML safe like &amp; which is totally unusable for a URL. What is the conventional workaround for this?
