### ISSUE TITLE
Highlight Blocks in Preview Window on Mouseover Code

### ISSUE THREAD

**Issue by bkonia** [mjmlio/mjml#1236]
It would be great if the MJML app worked like how Developer Tools works in any modern browser. When you mouseover or click on a code block, it would highlight the corresponding section in the preview window. This would make it much easier to find the code you need to edit for a particular section.

**Comment by iRyusa** [comment]
Hi,

Sorry this is not the right repo to post suggestion to MJML-APP, please check https://github.com/mjmlio/mjml-app . I think it has been already suggested.
