### ISSUE TITLE
mj-button: pointer cursor appears only when hovering the label

### ISSUE THREAD

**Issue by nuthinking** [mjmlio/mjml#1238]
The pointer cursor hovering a mj-button with href set only appears when hovering the label.

**Reproduction Steps:**
Adding a button with href: https://mjml.io/try-it-live/rJe9dZ_xX

**Expected behavior:**

pointer appears over all the surface

**Observed behavior:**

appears only hover the label

**Screenshots and GIFs**

![mj-button](https://user-images.githubusercontent.com/163635/41161642-d63ca64a-6b33-11e8-863d-05a7f84f9337.gif)

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

Web preview and App preview.

**Comment by iRyusa** [comment]
Hi 

We're unable to provide any full-width button that behave/works nicely across every clients yet, you can read more on this issue here #359 . I'm closing this one in favor of the old one

**Comment by BillAbramovitz** [comment]
Hi, I'm not sure if this is totally safe across all email clients, but I've been getting around it by adding "display:block" to <mj-button>
