### ISSUE TITLE
mj-button padding

### ISSUE THREAD

**Issue by nuthinking** [mjmlio/mjml#1239]
setting a padding to **mj-button** seems ignored. As a matter of fact the inline padding is applied to the **TD** containing the button **TABLE**, but the **TD** inside just outside the **A** keeps "padding:10px 25px;".

**Comment by iRyusa** [comment]
You can find in the documentation the `inner-padding` here : https://mjml.io/documentation/#mjml-button that will handle the padding inside the button.

**Comment by nuthinking** [comment]
Thank you so much!
