### ISSUE TITLE
Mobile version showing on Google Inbox

### ISSUE THREAD

**Issue by kevin-wolf** [mjmlio/mjml#124]
Anyone was having this issue? My email it's showing nice on each view but on http://inbox.google.com it's displaying the mobile one.

Any thoughts or neat solution?

**Comment by arnaudbreton** [comment]
@kevin-wolf thanks for reporting.

Could you please share the MJML code, the engine version you're using to render and a screenshot of the result?

Thanks!

**Comment by epayet** [comment]
This is the same issue than [40](https://github.com/mjmlio/mjml/issues/40). Google Inbox is another client that shows mobile version.

**Comment by iRyusa** [comment]
Dup of #40 adding Google Inbox into the list
