### ISSUE TITLE
Proposal: <mj-include> should allow custom props

### ISSUE THREAD

**Issue by jdotjdot** [mjmlio/mjml#1240]
We'd like to be able to create reusable MJML components that we include using `<mj-include>` just from the standard stock MJML components _without_ having to write any Javascript, use gulp, or generally go through the custom component creation process.  

The primary use case for this is that while `<mj-include>` works fine for partial templates that are always identical, the second anything needs to change from usage to usage (for example, if you have a `_header.mjml` where you want to change the title text for each email), you need to instead create a fully custom component.  This means downloading the component boilerplate, writing Javascript, running the build process, and registering your custom components every time.

For extremely simple components that just require props to be passed down into the component and use nothing truly custom, it should be possible to do that via `<mj-include>`.

**Comment by jdotjdot** [comment]
I wouldn't call this a templating thing&mdash;this isn't any different than the current custom component creation that is offered, it just lets you do it without Javascript.

That said, I _do_ wish there were a few more templating options availble.  Some of the key issues our team keeps running into over and over again are that when we try to create components, they're not truly modular or reusable, and that we also nearly always have to use another template language on top of MJML, which means that we're going through multiple rendering processes and we have to pre-process before we can even use MJML previewers. It makes what would otherwise be a seamless development experience much harder.

**Comment by iRyusa** [comment]
Custom component allow you to enhance the lang, it’s clearly not the same as templating variable support in include.

What you need is either setting a proper gulp workflow or a small webserver that does the same. It needs a one time effort and there’s already a lot of repo with a proper gulp workflow.

**Comment by codenamezjames** [comment]
Hey friends. I just ran in to this issue and i found a solution that i thing works pretty well. 
I use Vue to render variables and components. 
This bit of code runs in `feathersjs` so thats where the context variable comes from.

```
const vue = require('vue')
const renderer = require('vue-server-renderer').createRenderer()
const { resolve } = require('path')
const fs = require('fs')
const mjml2html = require('mjml')

module.exports = () => async (context) => {
  let { from, to, subject, file, data, layout } = context.data
  data = data || {}
  const template = fs.readFileSync(resolve(__dirname, '../../emails', file), 'utf8')
  const layoutTemplate = fs.readFileSync(resolve(__dirname, '../../emails/layouts', layout || 'default.mjml'), 'utf8')

  vue.component('layout', {
    props: { title: { type: String, default: () => '' } },
    template: layoutTemplate
  })
  
  var app = new vue({
    data,
    template
  })

  const mjml = await renderer.renderToString(app)
  const html = mjml2html(mjml).html;
  
  context.data = { from, to, subject, html }
  return context
}

```

example layout
```
<mjml>
  <mj-head>
    <mj-title>Welcome to Accelerate</mj-title>
  </mj-head>
  <mj-body background-color="#E7E7E7" width="600px" padding="10px">
    <mj-wrapper >
      <slot name="header"> HEADER CONTENT </slot>
    </mj-wrapper>
    <mj-wrapper>
      <slot />
    </mj-wrapper>
    <mj-wrapper full-width="full-width">
      <slot name="footer"> FOOTER CONTENT </slot>
    </mj-wrapper>
  </mj-body>
</mjml>
```

example body
```
<layout>
  <template #header>
    OVERWRITE DEFAULT HEADER
  </template>
  <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px">
    <mj-column width="100%">
      <mj-text color="#212b35" font-weight="bold" font-size="20px" v-if="user.displayName || user.firstName">
        Welcome to example.com
      </mj-text>
      <mj-text color="#212b35" font-weight="bold" font-size="20px" v-else>
        Verify {{user.email}}
      </mj-text>
      <mj-text color="#FF7201" font-size="16px">
        <a :href="tokenLink">{{tokenLink}}</a>
      </mj-text>
    </mj-column>
  </mj-section>
  <template #footer>
    OVERWRITE DEFAULT FOOTER
  </template>
</layout>
```
