### ISSUE TITLE
mj-wrapper and mj-section outlook desktop padding problem

### ISSUE THREAD

**Issue by gorkemturhal** [mjmlio/mjml#1242]
Hi, i got some mj-wrapper and mj-section padding issue only in outlook desktop, in other clients (including outlook web) paddings are applying. And some image inside table td cutting in half.
my code below. (I could not insert here don't know reason).

https://paste.ubuntu.com/p/Wk64KjCfsk/

Expected behavior(i.e:gmail):
<img width="1001" alt="screen shot 2018-06-12 at 11 45 32" src="https://user-images.githubusercontent.com/30040453/41279827-27080e98-6e36-11e8-8e4c-3568424b6686.png">

padding in mj-wrapper content and mj-section (inside bordered content)

Observed behavior(in outlook desktop):
<img width="1051" alt="screen shot 2018-06-12 at 11 48 05" src="https://user-images.githubusercontent.com/30040453/41279994-90d17eea-6e36-11e8-8914-a0c10a1cc550.png">

no padding in mj-wrapper content and mj-section (inside bordered content) and icon image cutting.

MJML version : 4.0.3

outlook desktop

**Comment by iRyusa** [comment]
Hi @gorkemturhal 
This is sadly a known issue on Outlook with VML (for background image), the padding are totally mis-applied (https://github.com/hteumeuleu/email-bugs/issues/32). 

For your image being cutted, reset the `line-height` to `1` on the `td` will fix this.
