### ISSUE TITLE
Command line error: No input files found

### ISSUE THREAD

**Issue by lefuturiste** [mjmlio/mjml#1246]
Hello!
The compilation work but the watch no.

![Screenshot](https://i.imgur.com/avE6QAR.png)

My version : 
`"mjml": "^4.0.5"`

I'm on windows with Git Bash.

**Comment by ngarnier** [comment]
hey @lefuturiste, thanks for reporting. It's a known issue, we're going to fix it very soon in v4.1.0. 

I'm closing this one to the benefit of the already-opened issue: https://github.com/mjmlio/mjml/issues/1171

**Comment by klimov-rv** [comment]
Oh, now i know that i must have file "index.mjml" in directory before this entering this command?
