### ISSUE TITLE
How to add conditional to html header?

### ISSUE THREAD

**Issue by nickngqs** [mjmlio/mjml#1254]
How would you add a conditional statement inside the header

for example
```
<!--[if gte mso 15]>
<style type="text/css">
    table { word-break:break-all }
</style>
<![endif]-->
```

**Comment by iRyusa** [comment]
Hi @nickngqs 

`mj-raw` will be supported in `head` for 4.2 release. For now you can use this dirty hack https://mjml.io/try-it-live/Hy5PG7CZQ
