### ISSUE TITLE
The API should indicate the MJML version in URL

### ISSUE THREAD

**Issue by atrujillofalcon** [mjmlio/mjml#1255]
The API should indicate the MJML version in the endpoint URL. This would maintain backward compatibility in future API MJML major version upgrades.

For Example:

Before upgrade: https://api.mjml.io/v1/mjml-3

After upgrade: https://api.mjml.io/v1/mjml-4

**Comment by ngarnier** [comment]
Hey @atrujillofalcon, we're already providing a MJML API for free, we won't maintain several versions of the API (especially as MJML v3 is deprecated anyway).

The version is already provided in the response payload of the API, so you can use this to know which version is used.

We'll communicate appropriately before upgrading the MJML API to MJML 4 so you are aware of the change.

**Comment by Xplouder** [comment]
@ngarnier do you plan to release the API source code? I wish I could run your API under my control (e.g. locally).

**Comment by ngarnier** [comment]
@Xplouder no, it would require quite some work as we have additional layers for example for user authentication and account creation. 

However, it's pretty simple to build your own local API, or you can browse Github for existing repos such as https://github.com/chronotruck/mjml2html.

**Comment by atrujillofalcon** [comment]
@ngarnier I think that a open source API would be a good idea and I'm sure that community would help to get done the extra work that you comment. In my opinion a good product should ever have a good API as centerpiece.

If the API takes so long to upgrade, it is not a viable option for creating products that consume MJML :(

**Comment by iRyusa** [comment]
But what's the point, you don't need the overhead of having user account + auth ? 
If you're hosting your own API at this point it's like 20 line of express...

**Comment by atrujillofalcon** [comment]
The point is that an API must be language agnostic. Potencial projects or clients maybe only wants consume the API. Does that make sense, no?

**Comment by ngarnier** [comment]
Because of the points I mentioned, our API has a complex architecture using both NodeJS and Go and dependencies the community is not interested in, such as Cassandra. Like @iRyusa said, it is much simpler for you to create a simple Node API from scratch than try to remove our extra layers from our API (and that's why I'm confident no one from the community would work on that because it just doesn't make sense).

I think it's pretty nice that we already provide an API for free :-).

**Comment by iRyusa** [comment]
> The point is that an API must be language agnostic. Potencial projects or clients maybe only wants consume the API. Does that make sense, no?

At the end you will expose your API, so no matter what's the lang behind it ? Having node, ruby, python or whatever exposing a REST API will at the end still be a REST API.
