### ISSUE TITLE
Social component not displaying correctly using MJML editor software

### ISSUE THREAD

**Issue by Nantiee** [mjmlio/mjml#1257]
[Social component not displaying correctly using MJML editor software]

**Reproduction Steps:**

I just use the component given by the documentation.

**Expected behavior:**

Should be an inline display.

**Observed behavior:**

First element is alone, second is on second line, the next elements are correct.

**Screenshots and GIFs**

![image](https://user-images.githubusercontent.com/2286536/41922580-bb62b978-7965-11e8-87bd-0814f67cad27.png)

**MJML version:**

MJML APP 2.8.0
MJML v^4.0.3

**Comment by iRyusa** [comment]
Hi,

MJML App 2.8.0 isn't using 4.0.3 by default, can you try to update to MJML App 2.9 ? I think this was fixed in a minor release after the 4.0.0.

**Comment by Nantiee** [comment]
Hi,

I installed the app today and downloaded from [this link](https://mjmlio.github.io/mjml-app/) (2.9 for mac), but when I install the App, in "about" this is 2.8...

![image](https://user-images.githubusercontent.com/2286536/41924635-d6cdbff0-796a-11e8-9632-09affcbe0116.png)

**Comment by iRyusa** [comment]
Can you share the code here then, we'll check what happens. It seems to work fine with the try it live version https://mjml.io/try-it-live/BkSK7kxM7 ?

**Comment by Nantiee** [comment]
Hi,

thanks for replying.

Here is the code. Doesn't work in the live preview neither.
I tried with the basic one given in the documentation mais I have the same bug.
But if I compile with command line this is working.

`
    // Social banner
    <mj-section background-color="#F5F5F5" padding="30px 20px 0">
      <mj-column>
        <mj-text mj-class="sectionTitle" padding-bottom="15px" align="center">Follow us</mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#F5F5F5" padding="0px 20px 30px">
      <mj-column>
        <mj-social font-size="15px" icon-size="30px" mode="horizontal">
          <mj-social-element name="facebook" href="https://mjml.io/" border-radius="0" background-color="#3b5998">
            Facebook
          </mj-social-element>
          <mj-social-element name="twitter" href="https://mjml.io/" border-radius="0" background-color="#00aced">
            Twitter
          </mj-social-element>
          <mj-social-element name="Youtube" src="img/social-youtube.png" href="https://mjml.io/" border-radius="0" background-color="#4d4d4d">
            Youtube
          </mj-social-element>
          <mj-social-element name="Flickr" src="img/social-flickr.png" href="https://mjml.io/" border-radius="0" background-color="#4d4d4d">
            Flickr
          </mj-social-element>

        </mj-social>
      </mj-column>
    </mj-section>`

**Comment by iRyusa** [comment]
I think this bug has been fixed in 4.0.5/4.1, can you check that it works with it ?
We can close this issue because it's fixed, you should wait for a new release of the APP with MJML 4.1 to fix this

**Comment by Nantiee** [comment]
I confirm this is working online now ! Thank you very much :)
