### ISSUE TITLE
Sidebar ?

### ISSUE THREAD

**Issue by Nantiee** [mjmlio/mjml#1259]
Hi,

My client absolutely wants a sidebar in his new newsletter because they had one before (see here : [europa old newsletter](http://ec.europa.eu/employment_social/epic/newsletter/201804/EPIC_Newsletter_April_2018.html) ) .

I can't find a way to do this because it's not possible to put section in an parent container and give it a width, or something like this.

I check the template mais there is no sidebar.

I could put everything in mj-raw, but put all the code in a mj-raw remove the interest of using mjml...

I like mjml but I can't find any solution for this problem.

Something link this would be wonderful, it's possible to do this with multiple table in basic html, why not in mjml ?

![image](https://user-images.githubusercontent.com/2286536/42031710-85c0c616-7ad7-11e8-98c1-eb40f66c7196.png)

Thank you :)

**Comment by ngarnier** [comment]
A simple 2-column layout should fix that, why don't you do that? See this example: https://mjml.io/try-it-live/HyYhtSzzQ

Note that unlike your old newsletter example, this will automatically be responsive as columns naturally stack.

**Comment by Nantiee** [comment]
Thank for replying, but the left column has to be divided in subcolumns. That's the problem...

**Comment by ngarnier** [comment]
In your example there is only one column in the left column. Is what you're trying to achieve different? In that case you can use mj-table in the left column.
