### ISSUE TITLE
Incorrect unit, description, and default value for filePath in Node.js options documentation

### ISSUE THREAD

**Issue by eclopez** [mjmlio/mjml#1260]
It looks like the _unit_, _description_, and _default value_ for the **filePath** option is incorrect and duplicates the values from **beautify** option.

![screen shot 2018-06-28 at 12 47 39 pm](https://user-images.githubusercontent.com/1847929/42057575-a6263788-7ad2-11e8-9530-c4f592861385.png)

[https://mjml.io/documentation/#inside-node-js](https://mjml.io/documentation/#inside-node-js)

**Comment by iRyusa** [comment]
Hi

This has been fixed in the doc on github but not yet released on the website. Doc should be updated with MJML 4.1 update soon. Thanks for reporting
