### ISSUE TITLE
<mj-button> align="right" not working on Outlook for Windows

### ISSUE THREAD

**Issue by qunvar-arora** [mjmlio/mjml#1261]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
[Short description of problem here]
I created a basic email in MJML in which I have a hero image with text and a button used as an overlay. I am trying to right align both the text and the button. When I render test with Email on Acid the text stays right aligned perfectly but the button does not stay right aligned for any combination of Outlook on Windows. In this version of the render test the button for some reason moves all the way to the left side of the email *Email on Acid Link 1 Below*. When I removed the align="right" from my <mj-button> and then re-tested on Email on Acid the button is now positioned in the center of my mj-column/mj-section *Email on Acid Link 2 Below*. This means the button alignment centered is being taken into consideration by the Windows/Outlook rendering but why is the align="right" not working??

**Reproduction Steps:**

1. [First Step]

In hero image section 

<mj-section background-url="http://info.flex.com/l/279492/2018-06-29/336gl/279492/65679/Email_1_Feature_button_light_HeroImage.jpg" background-repeat="no-repeat" background-size="cover" text-align="right">

add align="right" attribute to 

<mj-button background-color="#009ADD" border="1px solid #009ADD" border-radius="50px" color="#ffffff" font-family="Arial" font-size="14px" href="https://intelechygroup.com/" padding-top="0px" target="_blank">Read the case study</mj-button>. 

Then test on email on acid and you will receive these results: https://app.emailonacid.com/app/acidtest/PHT99PTaXVYG6riSkIQuidMImVUXOuCehHTzWhzl3BamF/list

The results show the button all the way to the left of the email (for Windows/Outlook renderings only) which is incorrect! The button is supposed to be aligned to the right under the overlay text.

2. [Second Step]

In hero image section 

<mj-section background-url="http://info.flex.com/l/279492/2018-06-29/336gl/279492/65679/Email_1_Feature_button_light_HeroImage.jpg" background-repeat="no-repeat" background-size="cover" text-align="right">
 
remove align="right" attribute from 

<mj-button align="right" background-color="#009ADD" border="1px solid #009ADD" border-radius="50px" color="#ffffff" font-family="Arial" font-size="14px" href="https://intelechygroup.com/" padding-top="0px" target="_blank">Read the case study</mj-button>. 

Then test on email on acid and you will receive these results: https://app.emailonacid.com/app/acidtest/rgDSYzK4KKXa1qF3T62qBNml6sYmLHn5WvGibLTi9wUwl/list

The results show that Windows/Outlook combinations are taking into consideration the default center alignment attribute of the button so there is no reason why it should not be acknowledging the align="right" from the step above!

3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]
On Windows/Outlook combinations the button should be aligning to the right of the email directly underneath the hero image overlay text!

**Observed behavior:**

[Describe observed behavior here]
On Windows/Outlook combinations the button is aligning to the left of the email even though I have explicitly specified align="right" in the <mj-button> mjml code.

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

Here is the live MJML editor with the align="right" attribute added to the <mj-button>: https://mjml.io/try-it-live/BJBMAgNG7

Here is the live MJML editor with the align="right" removed from the <mj-button>: https://mjml.io/try-it-live/rkXb1bVfX

**MJML version:**

[Enter MJML version here]
Using "MJML App v2.8.0" which is using "MJML v^4.0.3" https://ibb.co/dEHK3y

**Email clients the bug is seen on:**

[Enter email clients names and versions here]
All versions of Windows/Outlook combinations as rendered by Email on Acid.

**Comment by kmcb777** [comment]
Hi @qunvar-arora thanks for reporting this
Its seems like the `align="right"` property on table prevents it from aligning on the right on outlook
We'll fix this, for now as a workaround you can delete it in the generated html. Your button is wrapped in:
```
<td align="right" vertical-align="middle" style="font-size:0px;padding:10px 25px;padding-top:0px;word-break:break-word;">
    <table align="right" border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;">
        <tr>
```
just remove the `align="right"` on the table and it should align properly

**Comment by qunvar-arora** [comment]
@kmcb777 thank you so much that fixed it!!
