### ISSUE TITLE
Mjml If condition is not working in version 4.1.0.

### ISSUE THREAD

**Issue by desaimansi** [mjmlio/mjml#1265]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.

Here is below demo code for if condition , which is not working.
<mjml>
  
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
        
      </mj-column>
    </mj-section>
    <mj-raw>{% if "a" == "a" %}</mj-raw>
            {{ data  }}
    <mj-raw>{% endif %}</mj-raw>
  </mj-body>
</mjml>

**MJML version:**

4.1.0

**Comment by iRyusa** [comment]
Hi @desaimansi 

Can you explain a bit because MJML doesn't have any templating language ?

**Comment by ngarnier** [comment]
More details would be helpful, but I suppose you're using Mailjet templating language?

It's normal that "it's not working" as your `{{data}}` is not inside a `mj-raw` and is not inside any MJML tag (content outside of a content tag is stripped out). You can fix it by placing your content inside a `mj-raw` too: https://mjml.io/try-it-live/rkiGUi_GX

```
<mjml>
  <mj-body>
    
    <!-- inside a raw directly --> 
    <mj-raw>
      {% if "a" == "a" %}
        {{ data  }}
      {% endif %}</mj-raw>
      
      
    <!-- inside a section -->
    <mj-raw>{% if "a" == "a" %}</mj-raw>
    <mj-section>
      <mj-column>
        <mj-text>{{data}}</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>{% endif %}</mj-raw>
  </mj-body>
</mjml>
```
