### ISSUE TITLE
mj-wrapper and background-position?

### ISSUE THREAD

**Issue by baba43** [mjmlio/mjml#1266]
Hey,

I'm trying to create a layout with a skyscraper (image) on the right side.

My first attempt was to create a two-column layout, but then I had problems with nested columns since there seems to be no functionality for nesting columns/sections, right?

So my second attempt is to use the `mj-wrapper` and provide the skyscraper as an background-image while pushing the content to the left with a `padding-left`. However, the only reason this doesn't seem to work is because I can't set `background-position` for `mj-wrapper`.

My question is, how to come around this problem?

And by the way: Thank you for this great project and your efforts.

**Comment by iRyusa** [comment]
Hi @baba43 

It's really hard to understand the issue without any code could you share a link here https://mjml.io/try-it-live ?

Background-position isn't well supported across email clients (outlook.com/yahoo& outlook desktop does totally ignore it) so that's why we don't expose this attribute.

If you really want to use it you can create a css-class and use it in mj-style

**Comment by baba43** [comment]
Hi @iRyusa,

sure. I've already done what you have suggested but I'm not sure if this is working fine cross-brother. 

Here is my current version which also shows how the template should look like:
https://mjml.io/try-it-live/rkrevT_zm

**Comment by iRyusa** [comment]
Well as you can see the responsive mode is totally broken and won't be readable at all on mobile because of the high amount of padding-right. 

I think you can do a section with 2 columns, and use a mj-table when you need to have a 2 column setup inside the first column.

**Comment by baba43** [comment]
Yes, you are right, but can't this be fixed by Media Queries?
https://mjml.io/try-it-live/Byiy96_G7

**Comment by iRyusa** [comment]
As MJML is Mobile First, I highly suggest to use mobile first media queries instead of desktop first.

I thinks this approach : https://mjml.io/try-it-live/Hyxjia_fQ is way better and is fairly easier to maintain. And the right image can be clickable in this approach too :)

**Comment by baba43** [comment]
Okay, you got me. I will go for your approach then.

Thank you very much for the help!
