### ISSUE TITLE
Amazon SES statements get removed upon parsing

### ISSUE THREAD

**Issue by Kretolus** [mjmlio/mjml#1268]
I've been using mjml to create email templates for use in Amazon's SES service. SES offers some additional statements (iteration, conditions) but they get removed while parsing into html.

**Example:**

```
<mj-column>
    {{#if exampleVar }}
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">{{exampleVar}}</mj-text>
     {{/if}}
</mj-column>
```

**Observed behavior:**

The SES `if` tags disappear in the parsed `html`.

**Workaround**

If you just want to check whether text should be displayed an easy workaround is simply including the tags within the `mj-text` tag:

```
<mj-column>
    <mj-text font-size="20px" color="#F45E43" font-family="helvetica">{{#if exampleVar }}{{exampleVar}}{{/if}}</mj-text>
</mj-column>
```

However any more complex conditional changes could either be made impossible by this, or require complex, unintuitive workarounds.

Is it possible to add support to the

**MJML version:**

This was checked with `try-it-live`, and the `mjml` package version `4.0.5`

**Comment by iRyusa** [comment]
Hi 

You need to add them inside an `mj-raw` if you want to keep them after compilation: 

```xml
<mj-column>
   <mj-raw>{{#if exampleVar }}</mj-raw>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">{{exampleVar}}</mj-text>
     <mj-raw>{{/if}}</mj-raw>
</mj-column>
```
