### ISSUE TITLE
please add supported programs/email servers in Reedme or wiki

### ISSUE THREAD

**Issue by vitvad** [mjmlio/mjml#127]
Awesome idea, thx for this tool.
Could you update description with:
- compatibility ? 
- maybe you know any alternative tools that suggest similar?

**Comment by arnaudbreton** [comment]
About email clients supported, it's all here https://mjml.io/faq#email-clients

The closest tool we've found to MJML is http://foundation.zurb.com/emails.html but it is still close to regular HTML and requires to with it (less than plain HTML though).

Hope it helps!

**Comment by vitvad** [comment]
@arnaudbreton thx, somehow miss that section

is there any plans to support blackberry ?
