### ISSUE TITLE
MJML 4.1.0 watch command not continuously running 

### ISSUE THREAD

**Issue by kellyannmcnamara01** [mjmlio/mjml#1271]
After I have installed MJML I confirm what version I am using (4.1.0) then run the --watch command on my file. Before it would watch continuously, and recompile each time I saved. Now it will run the watch command once and not recompile on save. I have seen the closed issues/1171 and I am aware that 4.1.0 came out with a --watch fix, but I would like to know if you killed the continuous watch or if it really is still a bug. 

<img width="570" alt="screen shot 2018-07-06 at 2 30 40 pm" src="https://user-images.githubusercontent.com/24300129/42394735-2e3d5ae6-8129-11e8-8817-378ce5fc809f.png">

**Comment by kmcb777** [comment]
Hi @kellyannmcnamara01 I couldn't reproduce the issue, watch is working fine for me. Maybe there is something that make the compilation crash, could you plz provide the mjml file you used, or try to run it with `--config.stack=true` ?

**Comment by kmcb777** [comment]
Hi @kellyannmcnamara01 , actually i could reproduce the issue, it only happens when no output is specified. Thanks for reporting this, i'll check why this happens. For now you can specify the output file with `-o outputfilename.html` and it should work

**Comment by kellyannmcnamara01** [comment]
Hey,

I rolled back to 3.3.5 and it is working smoothly.

I love using mjml, but I still couldn't get 4.1.0 to work.
The mjml file I was using was used on another email and works fine, and I
am getting no errors.

Thanks to responding so quickly and creating such an awesome product.

Cheers,
km

**Comment by kellyannmcnamara01** [comment]
Sorry, I mean to write "I was able to get it working" the compiled file
trick worked!

Cheers,
km

**Comment by kmcb777** [comment]
@kellyannmcnamara01 Actually it turns out it's the normal behavior. For regular compilation, if you don't specify the output it will log in the console. With the `watch` option, it would just completely flood the console, so the output is needed. But thanks for reporting this, we'll add this to the documentation.

**Comment by kellyannmcnamara01** [comment]
Thanks! That’s good to know
