### ISSUE TITLE
mjml-text align="justify" : Attribute align has invalid value

### ISSUE THREAD

**Issue by jmbarbier** [mjmlio/mjml#1272]
Docs (from mjml.io, and the README.md from mjml-text package) says that allowed attributes for align are "left, right, center, justify". The arguments listed in attributes checking enum from `packages/mjml-text/src/index.js`are only left, right and center.  So when using `align="justify"` the compiler raises an error/warning.

Using 4.1.0 nodejs mjml2html with no option :

```
[
  {
    "line": 55,
    "message": "Attribute align has invalid value: justify for type Enum, only accepts left, right, center",
    "tagName": "mj-text",
    "formattedMessage": "Line 55 of /api (mj-text) — Attribute align has invalid value: justify for type Enum, only accepts left, right, center"
  },
```

I couldn't find a word on align="justify" being deprecated, so the error should be in enum : https://github.com/mjmlio/mjml/blob/f7051e5054aa88da489a5fa5f16a81176c56b435/packages/mjml-text/src/index.js#L9

**Comment by iRyusa** [comment]
Hi @jmbarbier 
Yep, you're right, `align` on this one doesn't use old html attribute `align` but `text-align` so we should update the enum for this one

**Comment by pawl-bb** [comment]
I'm seeing a similar error on mj-table's `table-layout`.

```
Attribute table-layout has invalid value: fixed for type Enum, only accepts auto/fixed/initial/inherit
```

I'm using it like:
```
<mj-table table-layout="fixed">
```

**Comment by iRyusa** [comment]
🤔 @kmcb777 can you take a look ?

**Comment by kmcb777** [comment]
hi @pawl-bb thanks for reporting this, it will be fixed in the next version

**Comment by AJ-Whalley** [comment]
Hi @kmcb777 - I'm using version "^4.2.0-beta.3" and I still get the same error - "Attribute align has invalid value: justify for type Enum, only accepts left, right, center"
