### ISSUE TITLE
Hide illegal Attributes

### ISSUE THREAD

**Issue by theVannu** [mjmlio/mjml#1276]
Hi all guys,
When you try convert mjml-markup template to html (using soft validator) you can obtain some errors if you use some illegal attributes, is it possible to return the mjml-markup without the illegal attributes?

**Reproduction Steps:**
Considering this component:

        <mj-button align="center" background-color="#f45342" uniqueID="jjfh7vuggjx1i0zvdhn">
          Button
        </mj-button>
      
if you convert it to html using validation soft the result is an object with correct html and the list of errors, in this case illegal Attributes uniqueID

**Expected behavior:**
Is it possible to return also the mjml-markup without the illegal Attributes: 

        <mj-button align="center" background-color="#f45342">
          Button
        </mj-button>

**Comment by iRyusa** [comment]
Hi @theVannu 

Can you explain a bit the need behind it ? I don't really find any useful use case for this ?

**Comment by theVannu** [comment]
Hi @iRyusa 
I have a json structure that describe the mjml template. I want convert the json to mjml-markup and finally to html.
My json structure is created using [Normalizing State Shape](https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape) concept so, when I get the de-normalize json structure, I have additional field into my json (like primary_key and foreign_key of a relational database).
For example:

`{           
           "tagName":"mjml",
           "children":{
              "uniqueID":"iduniquebody",
              "descr":null,
              "attributes":{
                "uniqueID":"idbodyatt",
                "body_id":"iduniquebody",
                "background-color":""
              },
              "tagName":"mj-body"
           }
        }`

This is the json for render an mj-body component without children, as you can see the body's attributes has 2 illegal fields: uniqueID and body_id. When I convert it to mjml-markup (using json2mjml) the result is:
`<mjml>
  <mj-body background-color="" body_id="iduniquebody" uniqueID="idbodyatt">
</mj-body>
</mjml>`

When convert the mjml-markup to html the result is an object with the correct html and some errors ( Attributes body_id, uniqueID are illegal).

I would like to get the correct mjml-markup that describe the html:

`<mjml>
  <mj-body background-color="">
</mj-body>
</mjml>`

**Comment by iRyusa** [comment]
MJML Validation is just here to validate the structure of the object/xml string you're passing to the core. It's not really his job to sanitize the output. 

List of accepted fields are available in each `component` class, so it's easy to write a small filter to check & remove those non valid attributes.

**Comment by theVannu** [comment]
@iRyusa thank you for support, I will try to code my own filter

**Comment by iRyusa** [comment]
👍
