### ISSUE TITLE
Color validation raises errors on valid combinations

### ISSUE THREAD

**Issue by rosskevin** [mjmlio/mjml#1277]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
The following color is deemed invalid but is acceptable color code:
```
rgba(0, 0, 0, 0.54) // spaces
rgba(0,0,0,0.54)    // specificity
```
disallowed by:

```
/rgba\(\d{1,3},\d{1,3},\d{1,3},\d(\.\d)?\)/gi,
```

https://github.com/mjmlio/mjml/blob/master/packages/mjml-validator/src/types/color.js#L12

**Reproduction Steps:**

1. `mjml2html('<mj-text color="rgba(0, 0, 0, 0.54)">foo</mj-text')`

**Expected behavior:**
Accepts all valid color codes

**Observed behavior:**
Rejects valid color codes

**Screenshots and GIFs**
```
{"line":7,"message":"Attribute color has invalid value: rgba(0,0,0,0.87) for type Color ","tagName":"mj-text","formattedMessage":"Line 7 of /Users/kross/projects/archetype/packages/renderNotification (mj-text) — Attribute color has invalid value: rgba(0,0,0,0.87) for type Color "}
```

**MJML version:**
mjml@4.1.0

## Rationale
Value is provided by external library as a theme, so changing the source value is not practical.

## Solution
Improved regex:
https://regex101.com/r/K9GgbV/1

```
/rgba\(\d{1,3},\s?\d{1,3},\s?\d{1,3},\s?\d(\.\d{1,3})?\)/gi
```

**Comment by iRyusa** [comment]
Thanks for finding that, you're right we'll merge your PR with the regexp enhancement ! 👍 for making a PR about it
