### ISSUE TITLE
Custom code outside the <mjml> wrapper?

### ISSUE THREAD

**Issue by holmesadrianh** [mjmlio/mjml#1279]
Firstly, such an awesome framework, however, I cannot seem to create the workflow with the current project I am working with. The email templates that I create all need to have some custom code/script at the top of the file. It seems that I am unable to add code to the top of the mjml file which is untouched by mjml.

If there perhaps a way to do it?

For example, this would be ideal:

```
// custom code goes here and un affected by mjml.
<mjml>
// MJML markup
</mjml>
```

Any feedback would be much appreciated.

**Comment by ngarnier** [comment]
Hello, thanks for the kind feedback! 

No indeed, everything outside of the `mjml` tag is ignored. The best is probably to create your own workflow, it should be fairly easy using a task manager like [gulp](https://gulpjs.com/) (there is also a [gulp-mjml](https://github.com/mjmlio/gulp-mjml) package).

**Comment by holmesadrianh** [comment]
@ngarnier , is there a solution for grunt? We are currently forced to use grunt and I am not sure of a solution to do this.

#1404

**Comment by holmesadrianh** [comment]
It does not need to specifically be outside of the main <mjml> tag, but if there was a place we could put a raw tag that gets placed at the top of the compiled file that would be a huge help.
