### ISSUE TITLE
Adding background image messes with padding in Outlook 2013

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml#128]
[This is an example with two sections.](http://pastebin.com/SY7e3YVd)

The first of them looks as it is supposed to including in Outlook, as it does not have a background.

The second one only has the difference that background-url is set.
In Outlook 2013 it is shifted to the left.

![ol2013](https://cloud.githubusercontent.com/assets/1831220/13637864/df7748de-e609-11e5-8acd-343db4325c12.png)

I also tried to remove the section padding left and right and gave every item a seperate padding, but this looked even more confusing in Outlook.

This is what it should look like:

![mitschatten](https://cloud.githubusercontent.com/assets/1831220/13638039/bba49ce4-e60a-11e5-812d-da04077b729d.png)

I'd really appreciate help how to solve this,
splitting it into 6 images instead of image + text did not help, same issue in Outlook.
Using one big image instead would stop it from being responsive.

[**Another example:**](http://pastebin.com/CJ8Vq94e)

Outlook without background-url set:
![outlook_withoutbg](https://cloud.githubusercontent.com/assets/1831220/13638566/1eac2fee-e60d-11e5-851a-047f513f1e63.jpg)

With background-url set:
![ooutlook](https://cloud.githubusercontent.com/assets/1831220/13638577/3081776a-e60d-11e5-8bea-09938875912b.jpg)
~~I found no way to get rid of the white line that appears under the text...~~
I found a workaround for the second issue: By taking the `<mj-text>` out of its own section and putting it in the next section below the additional line was gone. Though this would not have worked if the next section had more than one column.

**Comment by iRyusa** [comment]
May be related to #116 

I don't know if vml might cause some weird things on a section...

**Comment by janus-reith** [comment]
Just as an update, this is still an issue with 1.3.3.
The use of background-images still results in weird/unwanted paddings.

[cropped/stretched background](https://github.com/mjmlio/mjml/issues/116) in Outlook is also still a thing.

**Comment by br4nnigan** [comment]
can confirm:

    <mj-section
        background-url="http://test.bayerundpreuss.com/spockstar/bottom-shadow-1300x90.png"
        background-repeat="no-repeat"
        background-color="#ffffff"
        background-size="100%"
        padding="0px 10% 50px 10%"
    >

this causes the padding to be ignored. Which is especially a problem since a bg image can only be used on a section, so i can't use a wrapper as workaround.

**Comment by Renjamin** [comment]
I'm also experiencing this the exact same issue as @br4nnigan.

**Comment by iRyusa** [comment]
Hi @br4nnigan & @Renjamin  

I don't think padding in `%` are supported in Outlook

**Comment by Renjamin** [comment]
Hey iRyusa,

Thanks for getting back so quick.  👍 

You're right, % do not render properly in outlook.  I should have been more specific with what I was saying.

`<mj-section background-url="http://storage.pardot.com/131451/33585/cio_mailer_bg.png" background-size="cover" background-repeat="no-repeat" text-align="left" padding-top="25px" padding-right="22px" padding-bottom="35px" padding-left="45px">
				<mj-column border-left="4px solid #4a96ae" width="600">

					<mj-text align="left" padding-top="0" padding-bottom="0" padding-left="15px" font-size="20px" font-weight="800" color="#ffffff" font-family="Montserrat, Arial Black, Arial, Helvetica, sans-serif">
						CIO Innovation and Strategy
					</mj-text>

					<mj-text align="left" padding-top="0" padding-bottom="0" padding-left="15px" font-size="20px" color="#ffffff" font-family="Montserrat, Arial, Arial Black, Helvetica, sans-serif">
						Tech Flash
					</mj-text>

				</mj-column>
			</mj-section>`

That specific snippet renders without padding in outlook 2013 and 2016.

2007-2010 are fine, at least according to the pardot litmus test.

**Comment by Renjamin** [comment]
I just wanted to bump for suggestions or ideas on this.  Has anyone found a good workaround for this padding issue in Outlook 2013 and 2016?

**Comment by iRyusa** [comment]
Not yet @Renjamin 

We didn't find where does the ghost padding come from

**Comment by iRyusa** [comment]
Just found out that padding left is applied to the right so right padding = left + right within a VML section... dunno if it's something related to MJML's HTML structure or purely VML

**Comment by katart** [comment]
I also would like to know if there is a fix for this. I'm removing background image support for Outlook until there's a solution for this.

**Comment by iRyusa** [comment]
It's a bug on outlook side, when having more than one table nested inside a vml bloc.

For now we have no idea how to fix this and if it's fixable :/

**Comment by iRyusa** [comment]
I'm closing this issue because it's a bug inside the VML/Word engine so there's nothing we can do on our side to prevent this.

**Comment by sidhantsuvagiya** [comment]
> Just found out that padding left is applied to the right so right padding = left + right within a VML section... dunno if it's something related to MJML's HTML structure or purely VML

Hi @iRyusa I have the same problem. Have you found any fixes for this?

Outlook 2019 Win10

![Outlokk 2019 Win10](https://user-images.githubusercontent.com/66551578/175815979-b284641a-ce78-42fe-8ba3-995c4b965d35.png)

Other Email Clients (should be like this)

![Other Email Clients (should be like this)](https://user-images.githubusercontent.com/66551578/175815974-9f34ec6e-14fd-41f9-a64f-3047b410599a.png)

**Comment by sidhantsuvagiya** [comment]
✅ Just want to add a solution here that I found through the discussion on the MJML slack channel.
Margin is supported on Outlook, so we can add a particular style for Outlook.
So here is the code:
https://mjml.io/try-it-live/ppTToW2_pv

  ```
<mjml>
   <mj-head>

     <mj-preview>Test</mj-preview>
     <mj-title>Test</mj-title>

     <mj-attributes>
       <mj-all padding="0px" font-family="Arial,sans-serif" />
     </mj-attributes>

     <mj-html-attributes>
       <mj-selector path=".outlook_fix > table > tbody > tr > td">
         <mj-html-attribute name="class">outlook_padding</mj-html-attribute>
       </mj-selector>
     </mj-html-attributes>


     <mj-raw>
       <!--[if gte mso 13]>
        <style type="text/css">
          .outlook_padding {
              margin-left: 40px !important;
              padding-left: 0 !important;
              padding-right: 0 !important;
           }
        </style>
      <![endif]-->
     </mj-raw>


   </mj-head>

   <mj-body background-color="#eaeaea">

     <mj-wrapper background-url="https://manix.dev/img/test/background_3.jpg" background-repeat="repeat" background-size="contain" background-position="top" background-color="#ffffff">

       <mj-section css-class="outlook_fix" padding="40px">
         <mj-column background-color="#FFFFFF">
           <mj-text padding="40px" font-size="20px" font-weight="bold">
             Let's Make a great emails using MJML!
           </mj-text>
         </mj-column>
       </mj-section>

     </mj-wrapper>

   </mj-body>
 </mjml>
```

**Comment by noushift** [comment]
Since none of the suggested solutions worked for me, I tried various other workarounds. Finally, I found one that really worked: 

**Add an empty column taking up the padding space!**

Below, an example of left-padding taking up 10% space. For some reason, only % units work for me. Also make sure that you wrap up the columns in an <mj-group> to keep everything in one row.
```mjml
<mj-section background-url="https://placehold.co/600x180">
  <mj-group background-color="#2D2D2D">
    <mj-column width="10%"></mj-column>
    <mj-column width="90%" background-color="#2D2D2D" padding-top="20px" padding-bottom="20px">
      <mj-text color="#000" padding-bottom="10px">
        Outlook Padding Workaround
      </mj-text>
    </mj-column>
  </mj-group>
</mj-section>
```
