### ISSUE TITLE
MJML-Validator crashes when receiving an attribute with a number-value

### ISSUE THREAD

**Issue by Michael-wm** [mjmlio/mjml#1287]
I generate mjml-templates by creating my own object in javascript (so I'm bypassing the whole MJML-Parser stuff). The mjml-conversion will crash during validation, if one of my attributes has a number as value. The error is caused by the isValid-method, which is expecting a string.

The Error-Message is: 
`this.value.match is not a function`

It can be reproduced by using this object:
`{
                tagName: 'mjml',
                children: [{
                    tagName: 'mj-body',
                    attributes: {},
                    children: [{
                        tagName: 'mj-column',
                        attributes: {},
                        children: [{
                            tagName: 'mj-text',
                            attributes: {
                                'font-weight': 300
                            },
                            children: [],
                        }]
                    }]
                }]
            }`

And this is the code-location:
https://github.com/mjmlio/mjml/blob/f7051e5054aa88da489a5fa5f16a81176c56b435/packages/mjml-validator/src/types/type.js#L31

Exclusively using strings solves this issue for me. Additional error-handling would be nice though, in case someone else encounters this problem.

This occured in MJML 4.1.0

**Comment by kmcb777** [comment]
Hi @Michael-wm thanks for reporting this, the validator was indeed expecting strings only. This will be fixed in version 4.2
