### ISSUE TITLE
What about non-responsive mail?

### ISSUE THREAD

**Issue by jt3k** [mjmlio/mjml#129]
how to make mail-layout ceased to be responsive?

**Comment by epayet** [comment]
From my point of view, non responsive emails could be non-stacking columns. It will look the same on mobile and desktop. See issue [#41](https://github.com/mjmlio/mjml/issues/41) and the work in progress [PR115](https://github.com/mjmlio/mjml/pull/115)

**Comment by jt3k** [comment]
it looks like the solution to this problem with the use of crutches.

is it possible to completely disable rules media query such as the addition of attribute no-responsive="true" to mj-body tag?
```xml
<mj-body no-responsive="true">
   <!-- no responsive layouting in this email-->
</mj-body>
```

_Sorry if my English sounds rude_

**Comment by jt3k** [comment]
bump up

**Comment by iRyusa** [comment]
To be honest, MJML is designed with a mobile first approach. So having a non-responsive mode would be tricky

**Comment by jt3k** [comment]
OK, then I will remove the block with a media-query in the output files :(

**Comment by arnaudbreton** [comment]
Hi @jt3k, sorry we can't help more for now. As @iRyusa, we've designed MJML with responsive in mind because we believe email must be look great everywhere these days. 

I'm closing the issue for now. Let us know if you're experiencing any issues or if you find an alternative solution for your use-case, we would love to review a contribution from you.

Happy emailing with MJML!

**Comment by jt3k** [comment]
I typeset the mail with a width of 400 px and I want to have a table here. but I can not do it because you think that the letters in the modern world must look good everywhere ...

please correct this problem. it prevents to achieve my goal.

**Comment by osbre** [comment]
You can use `<mj-group>` if you want to disable the responsivity feature.

https://mjml.io/documentation/#mj-group

**Comment by jt3k** [comment]
> You can use `<mj-group>` if you want to not make the columns responsive.
> 
> https://mjml.io/documentation/#mj-group

thanks, it looks like this should help :) (after 5 years)
