### ISSUE TITLE
How can i change font-size in mobile with media query?

### ISSUE THREAD

**Issue by cihanzengin** [mjmlio/mjml#1297]
Hello, i have a text like 

```
<mj-text align="left" font-family="Arial, Helvetica" font-size="36px" color="#000000" font-weight="normal" padding-bottom="0" css-class="title">SAMPLE TEXT</sup>.
  </mj-text>
```

i want to display font-size in mobile just 15px how can i do that? 

i tried to 

```
<mj-style>
      @media (max-width:480px) { 
        .title {
          font-size:15px !important
        }
      }
    </mj-style>
```

but nothing happened because inline style which i write to **mj-text** element is dominate to css.

if i delete the inline style from mj-text and make it like that; 
interesting but title class font-size:36px not working mjml add automatically inline style to element with 16px font-size 

```
<mj-style>
     .title {
font-size:36px
}
      @media (max-width:480px) { 
        .title {
          font-size:15px
        }
      }
    </mj-style>
```

**Comment by iRyusa** [comment]
Hey ! 

You can inspect the given HTML code by MJML to see that the `.title` is applied to the `td` and not the `div` the easy fix is to change your selector to `.title div` and then it will work fine. Keep the important because of how inline style works here :)
