### ISSUE TITLE
ENHANCEMENT: I would like the `mj-carousel` fallback (for Outlook and Gmail) to include thumbnails for all images.

### ISSUE THREAD

**Issue by eatplaysleep** [mjmlio/mjml#1298]
*I would like the `mj-carousel` fallback (for Outlook and Gmail) to include thumbnails for all images so that users can see all images and access any applicable links.*

**Reproduction Steps:**

1. Implement `<mj-carousel>`.
2. Attach `href` attributes to each image.
3. View in Outlook or Gmail.

**Desired behavior:**

1. Small thumbnails of *each* image are rendered so users can still see all the content.

    <img width="304" alt="screen shot 2018-07-31 at 11 00 32 am" src="https://user-images.githubusercontent.com/37595884/43477860-254707a2-94b1-11e8-854c-ee6d5ad3cc0f.png">

2. Clickable links are provided in instances where the image cannot be clicked. (?)

**Observed behavior:**

1. Only the initial image is rendered.

   <img width="579" alt="screen shot 2018-07-31 at 10 58 43 am" src="https://user-images.githubusercontent.com/37595884/43477709-bf8b80b4-94b0-11e8-9135-5b7052b2a7d9.png">

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

OWA, Gmail

**Comment by iRyusa** [comment]
Hi,

I know that current fallback can't suit for everyone, but this was the best compromise for now. It's pretty hard to have both behavior set (+ handling carousel in a Email).

I think here I would advise to either tweak the current solution with `mj-style` or fork `mj-carousel` to suits your need.
