### ISSUE TITLE
Outlook Render can't render text-alignment well

### ISSUE THREAD

**Issue by jeeshenlee** [mjmlio/mjml#130]
Text alignment of text that is nested in mjcolumn does not render correctly on Outlook 2013.

How do i get it to render correctly? Thanks.

![mjml-01](https://cloud.githubusercontent.com/assets/1011777/13668934/ffdef468-e6fa-11e5-8498-f76b7eabfe58.png)

**Comment by iRyusa** [comment]
Hi @jeeshenlee 

Can you provide a sample MJML, i'll take a look at it

**Comment by jeeshenlee** [comment]
@iRyusa here's my MJML. Thanks for taking your time to help.

[MJML-BookingEmail.txt](https://github.com/mjmlio/mjml/files/168330/MJML-BookingEmail.txt)

**Comment by jeeshenlee** [comment]
I believe i have found where the code is causing this problem.

The generated 

`                            `

where the mso specific should be
`                            `

Can someone update this into the code generator? Thanks!

**Comment by iRyusa** [comment]
I think this could be already fixed in 1.3, I'll check it.. 

But you're right the generated TD misinterpret width's unit

**Comment by iRyusa** [comment]
Appears to be fixed in 1.3 ! :tada:

**Comment by iRyusa** [comment]
And now released ! :+1:
