### ISSUE TITLE
mj-column width not working on outlook

### ISSUE THREAD

**Issue by gorkemturhal** [mjmlio/mjml#1300]
Hi guys, In my previous mjml usage there was no problem but now mj-column width not working in outlook in example: im giving a column width="25%" it still behave like 100% i have to add " [owa] .mj-column-per-25 { width: 25% !important; } " code on the top of html manually everytime. Even columns of mjml site template mails not working properly on outlook. 

MJML version 4.0.3

Outlook web and Outlook Desktop

**Comment by iRyusa** [comment]
Hi

This has been discussed multiple time. As you mention the `[owa]` fix it, you can enable this behavior with `<mjml owa="desktop">` in MJML4.

In MJML App there's an issue with the fix, you have to do `<mjml></mjml><mjml owa="desktop">` to fix it. I think the app will be updated soon to avoid to do this dirty hack.
