### ISSUE TITLE
MJ-TEXT Component missing 'text-transform' attribute!?

### ISSUE THREAD

**Issue by SkylerRogers** [mjmlio/mjml#131]
Was this by design (i.e. is there something I am overlooking where you can pass arbitrary "overrides" to the style attribute prior to HTML generation) or was this particular attribute just overlooked?

All the best,
-Skyler

**Comment by SkylerRogers** [comment]
Update: I was able to find a work around via https://github.com/mjmlio/mjml/issues/66. It looks like you can just add native HTML tags within MJ-TEXT like so...
     
    <mj-text>
      <h1>text</h1>
    </mj-text>

I'm curious if the arbitrary style tag is currently possible but this should do trick for now.

Thanks again,
-Skyler

**Comment by arnaudbreton** [comment]
Glad you've found a workaround for now. I believe this is something we can add in a future release. Keeping it open for now, will keep you posted! 

Happy coding with MJML!
