### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by KnightYoshi** [mjmlio/mjml#1310]
Under the usage section for Node both the beautify and filePath have the same information

option | unit | description | default value
-- | -- | -- | --
fonts | object | Default fonts imported in the HTML rendered by HTML | See in index.js
keepComments | boolean | Option to keep comments in the HTML output | true
beautify | boolean | Option to beautify the HTML output | false
minify | boolean | Option to minify the HTML output | false
validationLevel | string | Available values for the validator: 'strict', 'soft', 'skip' | 'soft'
filePath | boolean | Option to beautify the HTML output | false

**Comment by iRyusa** [comment]
This has been fixed on Master : https://github.com/mjmlio/mjml/blob/master/doc/install.md
