### ISSUE TITLE
Background with wide image

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#1311]
Hi, is it possible to build this type of email using MJML? I have a problem with the first section, it is bigger than the others. And there is no way to decrease the width of the others sections.

![zapytanie](https://user-images.githubusercontent.com/528501/44036575-666c4d08-9f12-11e8-88a3-a672d9ba3af6.JPG)

**Comment by iRyusa** [comment]
Hi @ProdigyMaster 

Using a full-width wrapper should do the trick here : https://mjml.io/try-it-live/HyApMfyLQ
