### ISSUE TITLE
mj-spacer default height not working

### ISSUE THREAD

**Issue by mbaumbach** [mjmlio/mjml#1312]
In the MJML [documentation for mj-spacer](https://mjml.io/documentation/#mjml-spacer), the `height` default value says it is `20px`. Omitting the height attribute results in a 0 height spacer.

**Reproduction Steps:**

1. Insert a `<mj-spacer />` into your template somewhere between two elements.
2. Inspect the output HTML for the height and note there are `NaN` and `undefined` values set for the spacer.

**Expected behavior:**

Using a no-attribute `<mj-spacer />` should result in a space with 20px between.

**Observed behavior:**

Without a `height` attribute defined, there is no space. Looking at the output HTML, this is what happens when the attribute is omitted:

```
<!--[if mso | IE]>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td height="NaN" style="vertical-align:top;height:undefined;">  
<![endif]-->
                <div>
                    &nbsp;
                </div>
<!--[if mso | IE]>
            </td>
        </tr>
    </table>  
<![endif]-->
```

Notice the `td` `height` is `NaN`, `height` `style` property is `undefined`, and there's no height style property set on the inner div. When specifying a height, such as `20px`, the following HTML is produced and renders the space correctly:

```
<!--[if mso | IE]>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0">
        <tr>
            <td height="20" style="vertical-align:top;height:20px;">
<![endif]-->
                <div style="height:20px;">
                    &nbsp;
                </div>
<!--[if mso | IE]>
            </td>
        </tr>
    </table>      
<![endif]-->
```

**MJML version:**

Whatever is live on https://mjml.io/try-it-live/components/spacer and also reproduced on at least `4.1.0`.

**Email clients the bug is seen on:**

All

**Comment by kmcb777** [comment]
Hi @mbaumbach, thanks for reporting this, this will be fixed in the next version

**Comment by kmcb777** [comment]
Hi @mbaumbach this has been fixed in the new release mjml4.2-beta, which you can install with `npm install mjml`, you can check if it solves your problem
