### ISSUE TITLE
Error rendering columns in gmail

### ISSUE THREAD

**Issue by Simon-BonneGueule** [mjmlio/mjml#1314]
Hello, 

I seem to have a column problem in Gmail. I've seen similar issue tickets in here but they're all closed. 

I send an email with the same template for a few month now created in atom then copied from the mjml app to mailchimp. 
Everything was fine till 2 weeks ago. 

I have a two columns design that breaks into a single column only in gmail (I've tested the others with litmus). I'v tryed everything from removing everything not necessary to resending old generated email they all breaks. 

**Reproduction Steps:**

1. Create mjml in atom with two columns One image, one text (every email I've tried breaks) 
2. Copy and paste to MJML app (2.8.0 MJML v^4.0.3) (macos high sierra)
3. Copy Html to Mailchimp
4. Send test email to gmail
5. Email renders on a single column 

**Screenshots and GIFs**

Expected render :
<img width="600" alt="screen shot 2018-08-14 at 20 31 54" src="https://user-images.githubusercontent.com/26002601/44110893-3db0b724-a001-11e8-8542-1692ba36926e.png">

Actual render : 
<img width="601" alt="screen shot 2018-08-14 at 20 30 21" src="https://user-images.githubusercontent.com/26002601/44110786-ecec71b6-a000-11e8-95c7-97ff7553b10b.png">

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

GMAIL (old and new interface) 

Thanks in advance for you answer

**Comment by iRyusa** [comment]
Hi

I think this has been reported multiple time that mailchimp alter the HTML,
can you confirm by using a clean service like putsmail.com to see if it
works fine ?

**Comment by Simon-BonneGueule** [comment]
Hi, 

I Just found the problem. The update from MJML 3 to 4 broke my code silently (I didn't had any error so I didn't) I've rollback to the 3 and evereything is fine again. 
Now I just have to figure what's breaking my code. 

Sorry for the inconvenience.
