### ISSUE TITLE
OutlookColumnsProblem

### ISSUE THREAD

**Issue by sanazmemar** [mjmlio/mjml#1319]
Hi,

I have a problem with outlook.live.com : I have several columns in my Mjml, and instead of appearing side by side, they appear one below the other.
I read in the other posts that we had to add the prefix [owa] in the media queries, I did, but that does not solve my problem.
also I read #837 issue but it's not working in outlook.love.com.
I think it's not outlook problem with media query because I've tested other email framwork and they were correct!
but I coded my some templates with mjml and they are correct in other email engine(gmail, yahoo), what should I do for outlook?

![outlookproblem](https://user-images.githubusercontent.com/32170493/44342961-5d4da800-a441-11e8-8340-1d9c301a354e.PNG)

**Comment by iRyusa** [comment]
Hi,

In MJML4, you have a special attributes `<mjml owa="desktop">` if you want to have the desktop version in desktop (beware that the mobile version of outlook.com will receive the desktop version too instead of the mobile).

**Comment by sanazmemar** [comment]
Yes I read it. I've use this code:

`<mjml owa="desktop">
  <mj-head>
    <mj-style>
      [owa] .mj-column-per-100 {
        width: 100%!important;
      }
      [owa] .mj-column-per-50 {
        width: 50%!important;
      }
      [owa] .mj-column-per-33 {
        width: 33.333333333333336%!important;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

but I have that problem yet, in desktop version show like as mobile!

**Comment by iRyusa** [comment]
It seems that you still use MJML3 (because of the container) can you please try with latest version it shows up fine on litmus / eoa.

Did you tried with putsmail.com too ?
