### ISSUE TITLE
Images stack in Gmail app

### ISSUE THREAD

**Issue by neuhaus3000** [mjmlio/mjml#1321]
Hey guys, 

I have a simple 3 columns with images in them.  
The problem is that on Gmail App (mobile), the images in desktop stacks up.

We are suppose to see 3 images one beside the other ones.
On mobile, the two images at each end display:none.

But on Gmail app (mobile) the images stack up.

**What we are suppose to see** 
<img width="642" alt="screen shot 2018-08-20 at 1 04 01 pm" src="https://user-images.githubusercontent.com/42549942/44355160-d537c480-a479-11e8-99b8-fca56d03233b.png">

**What we see** 
<img width="460" alt="screen shot 2018-08-20 at 1 04 34 pm" src="https://user-images.githubusercontent.com/42549942/44355168-dc5ed280-a479-11e8-8385-417efea30454.png">

**MJML version:**

<mjml>
  <mj-head>
    <mj-style>
      .width-24, .mj-column-per-24 td {
        width: 24% !important;
      }
      .width-52-100, .mj-column-per-52 td {
        width: 52% !important;
      }
      @media all and (max-width: 480px) {
        .hide {
          display: none !important;
        }
        .width-24, .mj-column-per-24 td {
          width: 24% !important;
        }
        .width-52-100, .mj-column-per-52 td {
          width: 100% !important;
        }
      }
      @media screen yahoo {
        * {
          overflow: visible!important
        }
        .y-overflow-hidden {
          overflow: hidden!important
        }
      }
    </mj-style>
  </mj-head>
  
  <mj-body>
        
    
    <mj-section padding="0">
      <mj-column width="24%" css-class="width-24 hide">
        <mj-image src="http://via.placeholder.com/600x2400/aaaaaa?text=J1" href="https://www.reitmans.com/" padding="0" />
      </mj-column>
      <mj-column width="52%" css-class="width-52-100">
        <mj-image src="http://via.placeholder.com/600x1108/666666?text=J2" href="https://www.reitmans.com/" padding="0" />
      </mj-column>
      <mj-column width="24%" css-class="width-24 hide">
        <mj-image src="http://via.placeholder.com/600x2400/333333?text=J3" href="https://www.reitmans.com/" padding="0" />
      </mj-column>
    </mj-section>    
    
    
    
  </mj-body>
</mjml>

**Email clients the bug is seen on:**
Gmail App (mobile)

Any idea will be appreciated.

Thanks!!!

neuhaus3000

**Comment by ngarnier** [comment]
Well it's the normal behaviour for the images to stack up on mobile. You can force them to stay side by side with `mj-group`: https://mjml.io/try-it-live/rJCNw_dUX

Is that what you want?

**Comment by neuhaus3000** [comment]
Hey Nicolas!  I added a <mj-group> as suggested.  I think it will solve the issue... One moment please.  Thanks!

**Comment by neuhaus3000** [comment]
Hey Nicolas... Indeed, it worked.   Thanks a bunch! :)
