### ISSUE TITLE
Two columns images won't expand at 100% in mobile.

### ISSUE THREAD

**Issue by neuhaus3000** [mjmlio/mjml#1323]
Hey guys, 

I have a simple 2 columns with images.  On desktop, no problem.  On mobile, the images won't expand at 320px.  They expand at 300px.  Any idea why?

**MJML version:**

<mj-section padding="0">
      
      <mj-column padding="0">
        <mj-image src="http://via.placeholder.com/1200x1200/aaaaaa?text=C1" href="#" padding="0" />
      </mj-column>
      
      <mj-column padding="0">
        <mj-image src="http://via.placeholder.com/1200x1200/666666?text=C2" href="#" padding="0" />
      </mj-column>
      
    </mj-section>

**Email clients the bug is seen on:**

Gmail app android and iPhones.

**Comment by iRyusa** [comment]
Hi,

In MJML 4.1.X, you have a new attributes for that `https://github.com/mjmlio/mjml/blob/master/packages/mjml-image/README.md fluid-on-mobile that rely on a media query to work

**Comment by neuhaus3000** [comment]
Example ?  I don't quite understand how to add the fluid-on-mobile in the MQ.

**Comment by iRyusa** [comment]
`<mj-image fluid-on-mobile="true">` as mentioned in the link

**Comment by neuhaus3000** [comment]
Yes... I tried... Doesn't work.  It's the MQ that I'm not quite certain.

<mj-section padding="0">
      
      <mj-column padding="0">
        <mj-image fluid-on-mobile="true" src="http://via.placeholder.com/1200x1200/aaaaaa?text=C1" href="https://www.reitmans.com/" padding="0" />
      </mj-column>
      
      <mj-column padding="0">
        <mj-image fluid-on-mobile="true" src="http://via.placeholder.com/1200x1200/666666?text=C2" href="https://www.reitmans.com/" padding="0" />
      </mj-column>
      
    </mj-section>

**Comment by ngarnier** [comment]
there's no media query needed, it's handled by MJML. Check this link, you can see that the image is expanding to the whole viewport: https://mjml.io/try-it-live/BJpoyYFUQ

**Comment by neuhaus3000** [comment]
Hey Nicolas... It's expanding at 300px.  It's not suppose to expand at 320px ?

**Comment by ngarnier** [comment]
Sorry the try it live is actually not up to date, try with a local version of MJML and it'll work.

**Comment by neuhaus3000** [comment]
Hummm... Still doesn't work.  The fluid attribute is giving me an error.

<img width="2559" alt="screen shot 2018-08-21 at 8 09 16 am" src="https://user-images.githubusercontent.com/42549942/44400611-cc96cb00-a519-11e8-91d4-ecdd6ffe483a.png">

**Comment by neuhaus3000** [comment]
Doh !   Ok... I'll try to figure out something.  Thanks a lot for your help!
