### ISSUE TITLE
mjml-table - table-layout attribute validation fails

### ISSUE THREAD

**Issue by thommeo** [mjmlio/mjml#1324]
Source code:

```
<mj-table table-layout="auto">
```

Validation error message:

```
Module build failed: Error: ValidationError: 
 Line 55 of ... (mj-table) — Attribute table-layout has invalid value: auto for type Enum, only accepts auto/fixed/initial/inherit
```

Here seems to be an error: https://github.com/mjmlio/mjml/blob/v4.1.2/packages/mjml-table/src/index.js#L24

```diff
    padding: 'unit(px,%){1,4}',
-    'table-layout': 'enum(auto/fixed/initial/inherit)',
+    'table-layout': 'enum(auto,fixed,initial,inherit)',
    'vertical-align': 'enum(top,bottom,middle)',
```

This code actually passes the validation

```
<mj-table table-layout="auto/fixed/initial/inherit">
```

**MJML version:**

4.1.2

**Comment by iRyusa** [comment]
Hi @thommeo 

This has been already merged in `next` branch and will be pushed in 4.2.0 https://github.com/mjmlio/mjml/blob/next/packages/mjml-table/src/index.js#L24
