### ISSUE TITLE
mj-navbar-link issues in Outlook clients

### ISSUE THREAD

**Issue by kpratt2** [mjmlio/mjml#1329]
When using the mj-navbar, there is a rendering issue in the Outlook client 2003-2019.

The links look like this in every other client: 
![image](https://user-images.githubusercontent.com/29489435/44545489-34e4d880-a6e3-11e8-8e80-22aad92e6cbe.png)

The links instead look like this: 
![image](https://user-images.githubusercontent.com/29489435/44545413-fea75900-a6e2-11e8-8d8a-ad2fcfae5476.png)

Nothing particularly fancy is being done with the mj-navbar but this issue persists. What can be done to correct this?

Markup:
```
<mj-navbar>
   <mj-navbar-link href="http://www.emory.edu/">
      Emory Home&#160;|&#160;
   </mj-navbar-link>
   <mj-navbar-link href="http://news.emory.edu/">
      Emory News Center&#160;|&#160;
   </mj-navbar-link>
   <mj-navbar-link href="http://www.emory.edu/home/giving/index.html">
      Give to Emory&#160;|&#160;
   </mj-navbar-link>
   <mj-navbar-link href="http://www.emory.edu/home/contact-emory/index.html">
      Contact Emory&#160;|&#160;
   </mj-navbar-link>
   <mj-navbar-link href="http://news.emory.edu/press/contact.html">
      Contact Emory University Media Relations
   </mj-navbar-link>
</mj-navbar>
```

**Comment by iRyusa** [comment]
Well as the fallback for Outlook is to wrap everything into a table, I
don't think there's any solution for you here. The last text is too long to
be displayed for outlook (no line break for a table)
