### ISSUE TITLE
error after npm install

### ISSUE THREAD

**Issue by justinchristensen66** [mjmlio/mjml#133]
I am running node 5.1.1 I installed mjml globally through npm and now when I run "mjml -r index.mjml" and  also input.mjml I get a message "Error: ENOENT: no such file or directory, access 'index.mjml'
    at Error (native)"     Is this something on my end? What do you think went wrong?

**Comment by arnaudbreton** [comment]
Hi @justinchristensen66, sorry to read that you're experiencing an issue here. Thanks for sharing here.

Are you sure the file is accessible in current directory?

**Comment by justinchristensen66** [comment]
i was running in a empty directory.  Not sure if that was the issue, so I created a index.mjml file and ran "mjml -r index.mjml" in the directory and got "Error: [MJMLError] EmptyMJMLError: Null element found in mjmlElementParser
    at MJMLError.Error (native)
    at new MJMLError (/Users/justinchristensen66/.nvm/v5.1.1/lib/node_modules/mjml/lib/Error.js:24:85)
    at Object.mjmlElementParser (/Users/justinchristensen66/.nvm/v5.1.1/lib/node_modules/mjml/lib/documentParser.js:24:13)
    at documentParser (/Users/justinchristensen66/.nvm/v5.1.1/lib/node_modules/mjml/lib/documentParser.js:64:22)
    at mjml2html (/Users/justinchristensen66/.nvm/v5.1.1/lib/node_modules/mjml/lib/mjml2html.js:49:52)
    at /Users/justinchristensen66/.nvm/v5.1.1/lib/node_modules/mjml/lib/cli.js:81:12"      

I am not sure if this problem is due to something on my end, it usually is, but I would like to figure out what I am doing wrong. Thanks for any help!

**Comment by epayet** [comment]
I think this is because your `index.mjml` is empty. You should use a basic layout to start with like:

```html
<mj-body>
  <mj-section>
    <mj-column>
      <mj-text>Hello World</mj-text>
    </mj-column>
  </mj-section>
</mj-body>
```

I agree that the error message may not be clear enough here.... Suggestion, maybe we should check that the file is not empty or that it is starting by `mj-body` and if not, show the error `File is not valid / empty`.

**Comment by justinchristensen66** [comment]
Thanks @epayet ! Once I added the above to my empty file the command "mjml -r index.mjml" generated the "a.html" file.  So I guess everything is going good again.  Thanks to @arnaudbreton for the help as well.

**Comment by arnaudbreton** [comment]
@justinchristensen66 welcome! glad to hear it works now. I'm closing the issue. Thanks @epayet for figuring this out.
