### ISSUE TITLE
Outlook adding padding to right side of images

### ISSUE THREAD

**Issue by Hookeo** [mjmlio/mjml#1330]
So somehow, Outlook 2013, 2016 and 2019 are adding about 20 px of space to the right of center aligned images.

**Reproduction Steps:**

1. Creation section with smaller than full width image and align center
2. Test in litmus for the above versions

**Expected behavior:**

Images to be aligned in the center

**Observed behavior:**

Images off center by about 20 px

**Screenshots and GIFs**

https://imgur.com/a/xV4eJ4x

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

Outlook 2013, 2016 and 2019

**MJML Section Code**
```<mj-section> text-align="center">
      	<mj-column>
        	<mj-image src="http://cenergy.stellarblast.com/brookwood/09-006-214/workshopText.png" padding-top="0" padding-bottom="30px"></mj-image>
          <mj-image src="http://cenergy.stellarblast.com/brookwood/09-006-214/brookwoodVideo.png" padding="0" href="http://brookwoodfarms.com/workshop/index.html#workshop"></mj-image>
          <mj-image src="http://cenergy.stellarblast.com/brookwood/09-006-214/invited.png" width="243px" padding-top="50px;"></mj-image>
          <mj-text padding="10px 70px" css-class="mobile-padding">
          	Join us September 26-27th, in Lawrenceville, GA for a free, one-on-one workshop. We’ll review your menu, share new, craveable dishes that are packed with profit, and give you information to craft a menu your customers will love.
<br /><br />This session can help you grow your sales by incorporating barbeque in new, exciting ways. Don’t miss this free opportunity to grow your business. Reserve your time NOW!
          </mj-text>
          <mj-image href="http://brookwoodfarms.com/workshop/rsvp.html" src="http://cenergy.stellarblast.com/brookwood/09-006-214/rsvpNow.png" align="center" padding-bottom="20px" width="104px"></mj-image>
        </mj-column>
      </mj-section>```

**Comment by iRyusa** [comment]
This is a known bug when you have a background image in your section. Padding is applied twice inside a VML section, resetting it to 0 should fix it

**Comment by Hookeo** [comment]
@iRyusa Thanks for that.  What padding should I set to 0?

**Comment by iRyusa** [comment]
Every padding left & right inside your section (column/text/image) should be set to 0, this is a known issue with vml but we didn't find any fix for this particular case

**Comment by Hookeo** [comment]
Cool.  Thank you for the help!
