### ISSUE TITLE
I want to pass the tags along with the string.

### ISSUE THREAD

**Issue by laddered** [mjmlio/mjml#1332]
1. In ruby:
`@body = "<p>Anything <p>Anything else"`
2. To mjml:
`<mj-text> <%= @body %> </mj-text>`

**Expected behavior:**

```
  Anything
  Anything else

```
**Observed behavior:**

```
<p>Anything <p>Anything else

```

**MJML version:**
mjml app v 2.9.0    
mjml v^4.0.3

**Comment by iRyusa** [comment]
This should work fine in MJML 4.1.x
