### ISSUE TITLE
having problem with column stacking on outlook and hotmail.

### ISSUE THREAD

**Issue by viniciusvinicius** [mjmlio/mjml#1333]
Is It possible to fix this?

Expected result in Gmail Desktop: 
https://www.aguiabranca.com.br/Files/SiteImages/587-screencapture-mail-google-mail-u-0-2018-08-28-10_45_09.png

In webmail clients on the desktop the columns are stacked: 
https://www.aguiabranca.com.br/Files/SiteImages/603-screencapture-outlook-live-mail-inbox-id-AQQkADAwATNiZmYAZC0xNjEyLTdjOWEtMDACLTAwCgAQAO7-r-bnQjFHqFRCcxau39I-2018-08-28-10_39_14.png

Code:

    <mj-section padding="0px">
      
      <mj-column padding="4px 4px">
        <mj-image src="https://goo.gl/XWfMMH" href="https://goo.gl/x46WUY" padding="0px"></mj-image>
      </mj-column>
      
      <mj-column padding="4px 4px">
        <mj-image src="https://goo.gl/cuYr8g" href="https://goo.gl/KZJS1h" padding="0px"></mj-image>
      </mj-column>
      
    </mj-section>
    
    
    
    
    <mj-section padding="0px">
      
      <mj-column padding="4px 4px">
        <mj-image src="https://goo.gl/M3Mf9H" padding="0px" href="https://goo.gl/thdV5N"></mj-image>
      </mj-column>
      
      <mj-column padding="4px 4px">
        <mj-image src="https://goo.gl/nnTYFC" padding="0px" href="https://goo.gl/PBjfgd"></mj-image>
      </mj-column>
      
    </mj-section>

**Comment by iRyusa** [comment]
`mjml` root tag supports  `owa="desktop"` if you want to force it as desktop, you can read more about this here : https://medium.com/mjml-making-responsive-email-easy/mjml-turns-2-and-levels-up-with-a-new-version-mjml-v4-d3f59b752ae6#f702

**Comment by viniciusvinicius** [comment]
iRyusa, can you share any documentation about how to use the owa for outlook in code examples?

**Comment by iRyusa** [comment]
It's just written in the medium link : `<mjml owa="desktop">` I know there's some issue on MJML App for now with this I think the fix is to add a empty mjml tag at the beginning : 

```
<mjml></mjml>
<mjml owa="desktop">
 <!--  ....My Document -->
</mjml>
```

**Comment by viniciusvinicius** [comment]
Thanks! It fixed now, works fine here!

**Comment by EdPS** [comment]
I have been checking this issue and the owa tag fixed the problem only for owa, which is the online version of outlook. For the desktop client of outlook and the windows 10 email app the columns are stacking up. Has someone checked this? any fix?

**Comment by ngarnier** [comment]
@EdPS in that case and as stated in other issues, the issue is likely with the ESP/method of sending you are using rather than MJML. Try sending with https://putsmail.com/ to confirm. If it persists, please open an issue.

**Comment by EdPS** [comment]
You are right @ngarnier. It works on putsmail. Thanks for guiding me!
