### ISSUE TITLE
Mising `alt` attribute in social button `<img>` tags increases spam score.

### ISSUE THREAD

**Issue by yrammos** [mjmlio/mjml#1334]
According to mail-tester.com, among other similar tools, HTML email with images that lack an `alt` value is penalized with a higher spam likelihood.

Unfortunately the `<mj-social-element>` does not accept an `alt` attribute. Could this be amended?

Thanks.

**Comment by iRyusa** [comment]
Hi,

In fact this is supported but not listed as a valid attribute maybe @kmcb777 can fix it for the next release ?

**Comment by kmcb777** [comment]
the fix has been merged and included in the 4.2-beta so i'll close this one
