### ISSUE TITLE
<mj-raw> in <mj-head> doesn't work (content of mj-raw doesn't appear in rendered <head>)

### ISSUE THREAD

**Issue by tkafka** [mjmlio/mjml#1338]
**Reproduction Steps:**

I put a following block in `<mj-head>`, expecting the meta tag to appear in rendered html.

```
<!-- shis should work but it doesn't -->
<mj-raw>
	<meta name="format-detection" content="telephone=no, address=no, email=no, date=no" />
</mj-raw>
```

**Expected behavior:**

`<meta>` shows up in `<head>` section of rendered html.

**Observed behavior:**

`<meta>` tag is not there.

However, this hack works:

```
<!-- this hack works -->
<mj-style>
	</style>
	<meta name="format-detection" content="telephone=no, address=no, email=no, date=no" />
	<style>
</mj-style>
```

**MJML version:**

4.0.3

**Comment by iRyusa** [comment]
Hi,
It's WIP addition for 4.2.X see #82 (some of tickets of 4.2 has been closed but not pushed yet, a beta should be released this week)

**Comment by tkafka** [comment]
Thanks! Looking forward to 4.2!

**Comment by tkafka** [comment]
@donni106 That would be a regression then - I can confirm this works (writes a meta tag into html header) in 4.2.0:

```
<mj-head>
<mj-raw>
	<meta name="format-detection" content="telephone=no, address=no, email=no, date=no" />
</mj-raw>
...
</mj-head>
```

Just an idea - did you check if you call this inside mj-head?

**Comment by ngarnier** [comment]
No regression, more likely a version conflict on @donni106 side. Let's keep the conversation in https://github.com/mjmlio/mjml/issues/82#issuecomment-451934759 to avoid spreading it across multiple issues.
