### ISSUE TITLE
Try it live in website: Object in code

### ISSUE THREAD

**Issue by Triloworld** [mjmlio/mjml#1339]
Pleas go to example where bug occur: https://mjml.io/try-it-live/Bk8iWtqP7

Go to "View in html" and check line 906
This is wrong:

`<table 0="[object Object]" 1="[object Object]" 2="[object Object]" border="0" style="cellspacing:0;color:#000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;table-layout:fixed;width:auto;">`

Is this from React Framework / MJML Framework?

Add info to readme and documentation where issues about website can be send :)

**Comment by iRyusa** [comment]
Hi,

Try it live isn't up to date, it has been fixed in 4.0.5 I think.
