### ISSUE TITLE
mjml#next - add package version

### ISSUE THREAD

**Issue by tkafka** [mjmlio/mjml#1340]
As mjml#next fixes a lot of bugs I encountered, I would like to use it. However, currently I can't run `npm install mjmlio/mjml#next --save` because `package.json` doesn't have version:

> npm install mjmlio/mjml#next --save 
> Can't install github:mjmlio/mjml#e3adb25b1368e8eab6a69f8f7ad5b0e356fd0d88: Missing package version

Can we add some preliminary version to #next? Like `4.2.0-alpha`?

**Comment by iRyusa** [comment]
As releasing on npm isn't as trivial as pushing a button, we want to minimize the number of NPM release as we can. A `beta` for 4.2.0 should be available soon, but there's no ETA yet.

You can still install the repo locally.

**Comment by tkafka** [comment]
@iRyusa I wouldn't need to have it added to npm, I would be ok with just installing it from github branch (this would also signify better 'you are doing this on your won risk' :)).

**Comment by iRyusa** [comment]
The main issue is how the repo is split today, that's why you can't install it like that.
We have the "dev package" that contains all package of MJML in a sub folders `packages` `mjml-core/mjml-text/...`.

**Comment by ngarnier** [comment]
you can already install it from Github @tkafka, here are the instructions (don't forget to switch to the right branch) https://github.com/mjmlio/mjml#development. 

Then you can render your files with the local version (`./packages/mjml/bin/mjml` instead of just `mjml`).

**Comment by tkafka** [comment]
@ngarnier I know, I just wanted a way to specify it as npm dependency so that teammates could just oull the code and `yarn` and it would work :).
