### ISSUE TITLE
Mjml-cli prints errors to a stdout, and they mix with rendered html code

### ISSUE THREAD

**Issue by tkafka** [mjmlio/mjml#1342]
Mjml-cli currently prints warnings to a stdout, same as the rendered html template. This is a problem because when I compile templates like this `mjml index.mjml > index.html`, I don't see any problems, and I risk accidentally sending an email that begins with mjml error messages.

**Reproduction Steps:**

Create a template with warning, for example by using a mj component in a scope where it doesn't belong.

**Expected behavior:**

Errors are sent to stderr (`console.error()`) while the output appears on stdout (`console.log()`).

**Observed behavior:**

Both errors and output is sent to stdout, and errors appear at the beginning of compiled template.

**MJML version:**

4.1.2

**Comment by kmcb777** [comment]
Hi @tkafka it's true that errors could be sent to stderr, we'll see for changing that in 4.3
Meanwhile, if you compile with `mjml index.mjml -o index.html` you have no risk to have errors in the output

**Comment by tkafka** [comment]
@kmcb777 Awesome, thank you! And thanks for the advice, I'll change my build scripts.

**Comment by iRyusa** [comment]
Fixed in 4.2.1 👍

**Comment by ngarnier** [comment]
Update: we're going to revert this change. stderr should be used only for an actual failure in the MJML compilation, not syntax warnings. See https://github.com/mjmlio/mjml/issues/1439

**Comment by tkafka** [comment]
I disagree with this - `stdout` should only be used for the actual output (so that you can redirect it to a file, and be sure you aren't sending your users an email with validation messages).

All diagnostic output should go to `stderr`, and I propose to add setting to select verbosity (warnings and errors, or errors only).

**Comment by noguespi** [comment]
I think the warnings/errors should go through stderr not stdout. 

Stdout can't be used anymore for outputing template because we can't distinguish what is the the template and what is an error/warning message in the output. At least disable it when using the `-s` option.

Using `-o` with a temporary file as a hotfix.

**Comment by iRyusa** [comment]
It should be fixed now warnings & errors are all in stderr ?

**Comment by noguespi** [comment]
Only the errors, not the warning.

```
$ mjml/bin/mjml --version

mjml-core: 4.5.1
mjml-cli: 4.5.1
```

```
$ echo "<mjml><mj-container>c</mj-container></mjml>" | mjml/bin/mjml -i 2> /dev/null  | head

MJML v3 syntax detected, migrating to MJML v4 syntax. Use mjml -m to get the migrated MJML.
<!-- FILE: undefined -->
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
  <title>
  </title>
  <!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
```

**Comment by iRyusa** [comment]
Well https://github.com/mjmlio/mjml/blob/master/packages/mjml-migrate/src/migrate.js#L204 

This has been here to ensure everyone is using mjml4 syntax now, please remove mj-container and you should be fine ?

**Comment by noguespi** [comment]
Sure, but what if later mjml add another kind of warning ?

**Comment by iRyusa** [comment]
This is the only console.log in actual MJML code (not counting in cli & test files) and auto-migrate will probably be removed at some point (or hidden behind a flag).
