### ISSUE TITLE
Monaco Editor package providing syntax support for MJML

### ISSUE THREAD

**Issue by ganapativs** [mjmlio/mjml#1344]
Is there any package to support mjml syntax highlight and suggestion for [monaco editor](https://github.com/Microsoft/monaco-editor)?

I see there is [atom editor](https://github.com/mjmlio/language-mjml) support, but any plan to support for monaco editor which uses [Monarch tokenizer](https://microsoft.github.io/monaco-editor/monarch.html)?

**Comment by iRyusa** [comment]
Hi,

Well we try to support most of major editors here, but it would be hard to support everything. Like the VSCode plugin is totally done by the community https://github.com/attilabuti/vscode-mjml

As a fallback you can use HTML/XML syntax it would do the job perfectly 👍

**Comment by ganapativs** [comment]
No problem, currently I'm using HTML syntax, was curious if anyone already worked on monaco support. Thanks anyways 👍
