### ISSUE TITLE
mjml-cli watch live changes?

### ISSUE THREAD

**Issue by stephenrust** [mjmlio/mjml#1347]
I'm Running mjml core 4.2.0-beta.2 and mjml-cli 4.2.0-beta.2 locally, and have a question. 

Perhaps I've misunderstood the documentation, but while running `mjml watch` should I be able to view changes to the compiled file as I save the source?

I'm able to see changes if I launch the compiled file with live-server, but only after saving multiple times. 

Apologies for the basic question, but I'd like to understand how to best use the cli and watch command.

**Comment by iRyusa** [comment]
Hi,

I don't see this behavior on my end, can you do a clean install of the beta first ? What's the `cmd` you're using ?

**Comment by stephenrust** [comment]
Hi @iRyusa, thanks for the response. 

I did a fresh install for this project. The command I'm using is `mjml --watch index.mjml -o index-compiled.html`

Just so I understand correctly, what exactly should happen when I run the command, and how should I be monitoring changes to the compiled file? Should a browser serving the compiled file launch when I run the command, or should I launch one manually with live-server to monitor the compiled file?

**Comment by iRyusa** [comment]
It will only compiles the index.mjml on chance, it won't reload your browser in any way. You'll have to use something to reload the file if you want this behavior

**Comment by stephenrust** [comment]
Ah, ok. So by default, I would have to manually reload the compiled file in the browser if I want to see re-compiled version?

**Comment by iRyusa** [comment]
Yep, you'll have to use a liver reload tool for that.

**Comment by stephenrust** [comment]
Understood, thanks for clearing that up!
