### ISSUE TITLE
Gmail webpage display is not normal

### ISSUE THREAD

**Issue by numr** [mjmlio/mjml#1350]
To help us help you, provide as much information as you can. You'll find below a template you can use to submit your issue, but feel free to remove any part that wouldn't be relevant here.
      
[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**MJML version:**

[Enter MJML version here]

**Email clients the bug is seen on:**

[Enter email clients names and versions here]

**Comment by iRyusa** [comment]
Well at least provide a description... I'm closing feel free to open/re-open with some details
