### ISSUE TITLE
Outlook 600px width

### ISSUE THREAD

**Issue by jacobroberts6** [mjmlio/mjml#1352]
Apologies if this has already been answered. 

I'm building a template with full width background colours, looks great on most email clients but on Outlook, the background colour is being limited to 600px width becuse of this code:

`<table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;">`

Is there something I can add in to force it to use 100% width on outlook? 

**OUTLOOK SCREENSHOT**     
![outlook](https://user-images.githubusercontent.com/29915532/45626033-5177f480-ba86-11e8-8d29-e782f1ca100c.png)

**GMAIL SCREENSHOT**
![gmail](https://user-images.githubusercontent.com/29915532/45626055-605ea700-ba86-11e8-84d1-99de268e7c63.png)

`
  <mj-body>
    <mj-container>

      <mj-section full-width="full-width" padding="10px" background-color="#ed520f">
        <mj-column>
          <mj-text padding="0px" align="center" font-size="10px">
            <a style="color:#ffffff; text-decoration:none" href="http://$CANTREAD$">View Email Online
          </a>
          </mj-text>
        </mj-column>
      </mj-section>

      <mj-wrapper padding="10px 10px 0px 10px" full-width="full-width" background-color="#ed520f">

        <mj-section full-width="full-width" padding="0px 20px 0px 20px" border-radius="10px 10px 0px 0px" background-color="#ffffff">
          <mj-group>
            <mj-column vertical-align="middle">
              <mj-table>
                <tr>
                  <td style="width: 60;">
                    <img width="50" src="https://www.brookson.co.uk/globalassets/documents/emails/calendar.jpg" />
                  </td>
                  <td>
                    <b id="mobile-hide" style="font-size:15px">WEBINAR INVITATION</b>
                  </td>
                </tr>
              </mj-table>
            </mj-column>
            <mj-column vertical-align="middle">
              <mj-image padding="30px" align="right" width="100" src="https://www.brookson.co.uk/globalassets/documents/emails/brookson-one/brookson-one-logo.png">
              </mj-image>
            </mj-column>
          </mj-group>
        </mj-section>

        <mj-section full-width="full-width" padding="0px 20px 0px 20px" background-color="#ffffff">
          <mj-column vertical-align="middle">
            <mj-image padding="30px" align="center" width="300" src="https://www.brookson.co.uk/globalassets/documents/emails/presenters.jpg">
            </mj-image>
          </mj-column>
        </mj-section>
      </mj-wrapper>`

**Comment by iRyusa** [comment]
HI,

What version of MJML ?
There's a lot of type missing in your MJML too.

And which version of Outlook ?

**Comment by jacobroberts6** [comment]
Hi, 

Thanks, I think it's v3.3.3 and Office 365. 

What type am I missing? 

Thanks,

**Comment by iRyusa** [comment]
`<td style="width: 60;">` miss a px, every mj-image width too.

Full-width wrapper & outlook has been only available on MJML4, so that's why it doesn't work here. Please try on MJML 4.1.2, but it should work properly

**Comment by jacobroberts6** [comment]
Thanks @iRyusa! 

I'm using the desktop app, do I just need to update that to get the lastest version of MJML?

**Comment by iRyusa** [comment]
Yep, note that there's some little adjustments to do on MJML4 detailed here : https://medium.com/mjml-making-responsive-email-easy/mjml-turns-2-and-levels-up-with-a-new-version-mjml-v4-d3f59b752ae6

**Comment by kmcb777** [comment]
@jacobroberts6 yes the lastest app version (2.10) is using mjml 4.1.2

**Comment by jacobroberts6** [comment]
@iRyusa @kmcb777 Thanks Both! I will brush up on MJML 4 and the update has worked! 

Thanks for the help!
