### ISSUE TITLE
Width attribute values missing "px" in compiled HTML

### ISSUE THREAD

**Issue by daGUY** [mjmlio/mjml#1355]
When I export my MJML source to HTML, I've noticed that it generates code like this:

```
<!--[if mso | IE]>
      <table
         align="center" border="0" cellpadding="0" cellspacing="0" style="width:650;" width="650"
      >
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
      <![endif]-->
    
      
      <div  style="background:#6db3d7;background-color:#6db3d7;Margin:0px auto;max-width:650;">
      ...
```

Note the `style="width:650;"` and `style="max-width:650;"` – this is incorrect because the `px` suffix is missing from the values, which causes Outlook to ignore them and display the tables at 100% width instead.

For now, I'm working around this by doing a find/replace in my compiled HTML (`width:650;` -> `width:650px;` – that catches both the `width` and `max-width` attributes), but this is annoying and MJML clearly seems to be in the wrong here, no?

I'm using version 2.8.0 of the MJML app on macOS, and MJML 4.0.3.

**Comment by kmcb777** [comment]
Hi @daGUY could you provide your mjml ? You need to specify the unit manually, in your mjml did you specify the `px` or just `width="650"` ?

**Comment by daGUY** [comment]
Ah! You're right, I had `<mj-body width="650">` instead of `<mj-body width="650px">`. I think because the syntax looks like regular HTML, I was thinking it wasn't supposed to have the `px` suffix. Thanks!
