### ISSUE TITLE
mj-wrapper should be available inside mj-hero

### ISSUE THREAD

**Issue by gabiudrescu** [mjmlio/mjml#1359]
I'm trying to achieve this output with mjml:
![screen shot 2018-09-24 at 5 03 04 pm](https://user-images.githubusercontent.com/5156054/46012389-bc05e180-c0d1-11e8-8530-a559435c7278.png)

**Reproduction Steps:**

The markup below: 
```
<mjml>
  <mj-body>
    <mj-hero mj-class="hero-banner">

      <mj-spacer height="30px" />
      
      <mj-text mj-class="hero-banner-subtitle">
        H1 GHOTAM MAXIM MAXIMORUM
      </mj-text>

      <mj-text mj-class="hero-banner-title">
        H2 CHRONICLE DISPLAY ALL CAPS
      </mj-text>

      <mj-text mj-class="hero-banner-text">
        h3 Subtitlu pentru Corina, maxim 2 randuri in care se descrie super succind mecanismul campaniei
      </mj-text>

      <mj-spacer height="350px" />
      
      <mj-wrapper mj-class="hero-banner-text-background-white-wrapper">
        <mj-text mj-class="hero-banner-text-background-white">
          <span class="hero-white-subtitle">P1 Foloseste codul promotional:</span>
          <br/>
          <br/>
          <span class="hero-white-title">H4 GOTHAM SPATIAT</span>
          <br/>
          <br/>
          <span class="hero-white-paragraph">P2 valabil pana la 31 septembrie inclusiv, se aplica doar pe produsele care nu se afla deja in promotii.</span>
        </mj-text>
      </mj-wrapper>

      <mj-spacer height="20px" />

      <mj-button mj-class="hero-button-outline-black"  href="#">
      discover
      </mj-button>
      <mj-button mj-class="hero-button-black" href="#">
      discover
      </mj-button>
      <mj-button mj-class="hero-button-link" href="#">
      discover &#9658;
      </mj-button>
    </mj-hero>

    <mj-section>
      <mj-column>
        <mj-spacer height="20px" />
      </mj-column>
    </mj-section>
  <mj-body>
<mjml>
```

renders a validation error:
```
(mj-wrapper) — mj-wrapper cannot be used inside mj-hero, only inside: mj-attributes, mj-body
(mj-text) — mj-text cannot be used inside mj-wrapper, only inside: mj-attributes, mj-column, mj-hero
```

**Expected behavior:**

Compile from MJML to HTML without errors. 

**Observed behavior:**

Although the compiler complaints, if I send the output as is via email, it is rendered correctly. In Gmail at least. I'm planning to test it with Litmus on other platforms as well. When I will have the conclusions, I'll comeback to this issue and update it.

**Screenshots and GIFs**

Here's a screenshot on how it looks rendered in Gmail:
![image](https://user-images.githubusercontent.com/5156054/46012701-b78df880-c0d2-11e8-99e0-1970bdc11398.png)

**MJML version:**

4.1.2 (latest)

**Email clients the _bug_ is seen on:**

Works good on Gmail (desktop).

**Comment by iRyusa** [comment]
Mj-hero is meant to be a single column element with extended background support. So I don't really understand the issue here, as you have no background-url,  you can just use regular wrapper+section+column for you layout here

And, wrapper isn't meant to receive direct content node as mj-text without section/column inside it.
