### ISSUE TITLE
mj-group not working with outlook.com or outlook.for Mac

### ISSUE THREAD

**Issue by Kitcat711** [mjmlio/mjml#1361]
<mj-group> not working properly

**Reproduction Steps:**
Copy/paste of the document.
Email sent using CAKEPHP 3.6

**Expected behavior:**
Exactly what is described here:
https://mjml.io/documentation/#mjml-group

**Observed behavior:**
The 2 columns are seen one under the other.
<img width="498" alt="image" src="https://user-images.githubusercontent.com/13149618/46205644-b272b880-c321-11e8-8657-d306f677ee23.png">
... so it is not working with "even Outlook" on this ;) 
Thanks for your answer 
-- I search in the previous issue before posting, but found no one still open on this

**MJML version:**
Online miml tool 
npm installation one Mac : 
mjml-core: 4.2.0-beta.2
mjml-cli: 4.2.0-beta.2

**Email clients the bug is seen on:**
Mail is read with both outlook.com webmail and outlook v16.17 on Mac.
Works fine on gmail account.

**Comment by ngarnier** [comment]
It does work with "even Outlook" ;). 

Outlook.com doesn't allow the distinction between the mobile or desktop clients (there are a lot of closed issues about this already if you want to do a search on the repo), so you can use the `owa` attribute on the `mjml` tag.

As for Outlook on Mac, it should work fine so if it doesn't it might come from your way of sending, try with https://putsmail.com/ to be sure (it's free, no sign up needed, and doesn't alter your HTML).
