### ISSUE TITLE
Media queries are working fine in preview but not in email clients

### ISSUE THREAD

**Issue by akhilmantha** [mjmlio/mjml#1362]
Hi team, I am new to mjml and was going through media queries and implemented them accordingly. The issue I am facing is that it looks good when I test it in the editor's preview but when I send out a test email both of the images supporting desktop and mobile are in it. 

**Testing Methods**
1. Used Media queries to check it on the editor preview
2. Used sendy to test on desktop and mobile email clients
3. checked on outlook and gmail desktop clients and they have two images showing. 

**Expected behavior:**
Should work independent of desktop and mobile 

**Observed behavior:**
Both the images of the respective platforms appear in the email client 

**Screenshots and GIFs**
![image](https://user-images.githubusercontent.com/11584708/46278709-91f66880-c584-11e8-8c5e-13483a23ffc8.png)
<img width="1680" alt="screenshot 2018-10-01 at 3 02 55 pm" src="https://user-images.githubusercontent.com/11584708/46281019-1e0b8e80-c58b-11e8-9caf-54fbe75b762b.png">

**MJML version:**
MJML- APP : 2.10.0
MJML-VERSION : 4.1.2

**Email clients the bug is seen on:**

outlook and gmail desktop version

**Comment by ngarnier** [comment]
Hi @akhilmantha, please provide:

- MJML used
- Method of testing/sending used

Also note that media queries are poorly supported across email clients, so it might be expected to not see them working in some of those clients.

**Comment by akhilmantha** [comment]
Sorry, I'll edit it right away and is there any workaround for this apart from using media queries?

**Comment by akhilmantha** [comment]
`<mjml>
  <mj-head>
    <mj-style>
      @media all and (max-width: 480px) { img[src="https://beebom.com/wp-content/uploads/2016/01/Reverse-Image-Search-Engines-Apps-And-Its-Uses-2016.jpg"] { display: none!important; } } 
      img[src="http://www.jqueryscript.net/images/Simplest-Responsive-jQuery-Image-Lightbox-Plugin-simple-lightbox.jpg"]
      { display: none!important; }
      @media all and (max-width: 480px) { img[src="http://www.jqueryscript.net/images/Simplest-Responsive-jQuery-Image-Lightbox-Plugin-simple-lightbox.jpg"]
      { display: block!important; } }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-image src="http://www.jqueryscript.net/images/Simplest-Responsive-jQuery-Image-Lightbox-Plugin-simple-lightbox.jpg"></mj-image>
          <mj-image src="https://beebom.com/wp-content/uploads/2016/01/Reverse-Image-Search-Engines-Apps-And-Its-Uses-2016.jpg"></mj-image>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

**Comment by akhilmantha** [comment]
I have attached the image of reference code that I am using.

**Comment by iRyusa** [comment]
Attribute selector aren't available in gmail, so please use a css-class on your mj-image component.

Note that some clients just don't support any media queries so you're own with the fallback.

**Comment by ngarnier** [comment]
But then, even without the attribute selector, Outlook has no support for media queries at all so they will be totally ignored. You can start with an image that's shown and one that's hidden by default (without media queries so that there is no dependency on them), and then use media queries to change that, but be prepared for this to not work in some clients. 

PS: sharing an image of code is not ideal, especially on a coding platform. Are we supposed to rewrite all of the code in the image to test it?
