### ISSUE TITLE
Possibility to remove commented mjml code from output?

### ISSUE THREAD

**Issue by tkafka** [mjmlio/mjml#1364]
Currently, if I put something in html comment in mjml template (`<!-- like this -->`), it gets written into resulting html.

I'd love to be able to tell mjml to throw away these comments, as I use them for storing alternatives (eg. different copy text) or todo notes.

It isn't enough to just remove the comments from a rendered html, because comments are used there for conditional formatting as well, and any cleanup script would accidentally remove those tags as well.

**Reproduction Steps:**

1. Add commented code to mjml template.
2. Compile with some '--remove-comments' flag

**Expected behavior:**

Resulting html doesn't have my comments.

**Observed behavior:**

My comments are in rendered html.

**MJML version:**

[Enter MJML version here]

**Email clients the bug is seen on:**

[Enter email clients names and versions here]

**Comment by iRyusa** [comment]
On cli, you can just do `mjml file.mjml --config.keepComments=0` and those comments won't be rendered. 
In a side note, any `options` passed in `mjml2html` can be passed through `--config` option

**Comment by tkafka** [comment]
Hi @iRyusa, thanks - this is what I needed! :)

I looked into these two places, and didn't find a mention about this, it would be great if the options were documented here:
- https://www.npmjs.com/package/mjml-cli
- https://mjml.io/documentation/#command-line-interface

**Comment by iRyusa** [comment]
Yeah, feel free to open a PR on the doc to mention it 👌
