### ISSUE TITLE
Ability to add custom head elements

### ISSUE THREAD

**Issue by mastertheblaster** [mjmlio/mjml#1369]
Inside email body we are allowed to use/add `<mj-raw>...</mj-raw>` element.
However it's not possible to modify the head part.

Is this by design, or just a missing feature.
Cause it would be very useful to add custom meta tags, or links.

For example, adding ability to disable format detection for decent devices:

```html
<meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no"/>
```

Ability to specify favicon, if email would be viewed inside a browser:
```
<link rel="icon" href="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
```

**Comment by iRyusa** [comment]
It's already done in MJML 4.2 beta, you have access to `mj-raw` in head

**Comment by mastertheblaster** [comment]
@iRyusa great, thanks for the update, what's the timeline for beta becoming not beta?
