### ISSUE TITLE
Error generating .mjml

### ISSUE THREAD

**Issue by kelvinaero** [mjmlio/mjml#138]
mjml -r test.mjml on mac command-line returns this error

Error: ENOENT, access 'test.mjml'
    at Error (native)

mjml v. 1.2.1

**Comment by GuillaumeBadi** [comment]
Hey @kelvinaero !

can you paste the output of `ls -l` ?

**Comment by kelvinaero** [comment]
-rw-r--r--  1 kelvinaero  staff    8271 Mar 16 11:32 body_promo.html
-rw-r--r--  1 kelvinaero  staff    2130 Mar 16 11:32 body_promo.mjml
-rw-r--r--@ 1 kelvinaero  staff    3697 Mar 15 15:24 btn-approved.jpg
-rw-r--r--@ 1 kelvinaero  staff    6606 Mar 15 15:23 btn-fb.jpg
-rw-r--r--@ 1 kelvinaero  staff   98319 Mar 15 16:19 contest-rules.jpg
-rw-r--r--@ 1 kelvinaero  staff  234177 Mar 15 16:19 enter-simple.jpg
-rw-r--r--  1 kelvinaero  staff     239 Mar 15 13:32 gulpfile.js
-rw-r--r--@ 1 kelvinaero  staff  164682 Mar 15 16:18 hero.jpg
-rw-r--r--@ 1 kelvinaero  staff   28388 Mar 15 16:18 img-logo.jpg
-rw-r--r--@ 1 kelvinaero  staff   79080 Mar 15 16:19 img-people.jpg
-rw-r--r--  1 kelvinaero  staff  599504 Mar 15 16:33 mar-1406-fb-promo.zip
drwxr-xr-x  5 kelvinaero  staff     170 Mar 15 10:34 node_modules

well I already created an .mjml file manually and copied some of the markup from one of your templates, just wanted to know why I cant generate a basic .mjml

**Comment by GuillaumeBadi** [comment]
You need to replace `input.mjml` by an `mjml` file in you case, I assume it would be
```$ mjml -r body_promo.mjml```

**Comment by kelvinaero** [comment]
Well, I just parked inside this folder, but no matter how try it returns an error. Lets say I want to create version 2, I would use 

$ mjml -r body_promo2.mjml

I still get: 

Error: ENOENT, access 'body_promo2.mjml'
    at Error (native)

**Comment by GuillaumeBadi** [comment]
`mjml -r` won't create the file, you need to 1) Create the file with your favorite Code Editor, then compile the file with `mjml -r`

**Comment by kelvinaero** [comment]
Ok it looks like a documentation issue, in the end we ended up creating the file manually, but wanted to ask you.  just in case it was an error. It would be nice to be able to generate a skeleton file, but that is just a suggestion. Thank you.
