### ISSUE TITLE
Ability to replace named html entities to hex representation

### ISSUE THREAD

**Issue by mastertheblaster** [mjmlio/mjml#1380]
Some email clients (outlooks) (based per Litmus tests), don't always correctly render named hml entities. For example:

`&apos;` -> `&#39;`
`&copy;` -> `&#169;`
...

Maybe it's possible to pass some post processing parameters to mjml function?

```js
mjml('<mjml>...</mjml>', { postProcessing: { replaceHtmlEntities: true } });
```

**Comment by iRyusa** [comment]
Well, I don't think this is really something we should do, we don't want modify the user input. We had some issue in the past in MJML3 and it could lead to potential issue for some users.

You should wrap mjml2html to your own implem to replace those chars for you.

**Comment by mastertheblaster** [comment]
Ok, gotcha, thanks.
