### ISSUE TITLE
Ability to automatically shorten classnames used inside emails

### ISSUE THREAD

**Issue by mastertheblaster** [mjmlio/mjml#1381]
Currently we do declare readable and usually long classnames for the MJML components.
This is very good for development phase, however this increases the final HTML size (making gmail client cut the emails).

Maybe it's possible to add a post processing step to shorten them?

```js
mjml('<mjml>...</mjml', {postProcessing: {shortenClassNames: true}});
```

So in development mode we would use `false` and for production one it would be `true`.

What do you think?

**Comment by iRyusa** [comment]
I think that's not the job of MJML to provide this. The minify tool that we use should do the trick to avoid any client clipping issue for like 99% of projects.

I think here, you want to do a "deep" optimization and that would require to have an external deps like [clean-css](https://github.com/jakubpawlowicz/clean-css) to do that for you.
