### ISSUE TITLE
Ability to set margins on mj-social or mj-social-element

### ISSUE THREAD

**Issue by sinklair** [mjmlio/mjml#1384]
As an email designer, I would like to be able to change the size of the social sharing elements without changing the image size so that the images can stand out better on the page.

The social sharing elements support making the buttons entirely round by setting the border-radius="30px". The result looks a bit crowded and I would like to set an additional margin around the sharing icon such that the icon has padding to separate it from the surrounding share icons.

What I am able to do with the current version is this:
<img width="118" alt="screen shot 2018-10-11 at 4 36 07 pm" src="https://user-images.githubusercontent.com/2170324/46832377-ddbec400-cd73-11e8-83e6-954a6558e8d2.png">

What I'd like to be able to accomplish is something more akin to this example:
<img width="194" alt="screen shot 2018-10-11 at 4 36 30 pm" src="https://user-images.githubusercontent.com/2170324/46832402-eadbb300-cd73-11e8-9432-14b8a5244c41.png">

**Comment by iRyusa** [comment]
Hi @sinklair and thanks for your suggestion
Well it's really easy to do, I think we should add a `icon-padding` and `text-padding` ?

**Comment by iRyusa** [comment]
It's now available in 4.2.1 👍
