### ISSUE TITLE
Incorrect Table Widths for Outlook With Divider Inside Bordered Section

### ISSUE THREAD

**Issue by katart** [mjmlio/mjml#1389]
**Describe the bug**
I noticed a bug in the table width calculations for Outlook specific tables when placing a `mj-divider` element within a `mj-section` that has a bordered applied.

You can view the mjml markup here: https://mjml.io/try-it-live/BkXwF3Vjm
You can view the Email on Acid testing here: https://app.emailonacid.com/app/acidtest/MKftcM4RBiDPSeOat4CpiJpnByiMZ3js05onCcfnuLYbw/list

**To Reproduce**
1. Create a file with this MJML code: https://mjml.io/try-it-live/BkXwF3Vjm

**Expected behavior**
Proper table width calculations to prevent expanded table widths

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.1.2
 - MJML tool used: Online Editor

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [Putsmail](https://putsmail.com/)] 

**Affected email clients (for rendering issues):**
 - Email Client: Outlook
 - OS: Windows
 - Browser: N/A

**Screenshots**
https://app.emailonacid.com/app/acidtest/MKftcM4RBiDPSeOat4CpiJpnByiMZ3js05onCcfnuLYbw/list

**Comment by iRyusa** [comment]
Hi @katart thanks for adding so much details for this issue  🙌 and even a EOA link 👍 

I think we did update the way we handle border in 4.2.0, can you give it a try ?

**Comment by katart** [comment]
Yep. Fixed in 4.2.0

https://app.emailonacid.com/app/acidtest/27b5GrZyMiPeEky9NwPRElcRGGVUgcXhoLV0kX6wRG9Qw/list

Thanks for the quick reply
