### ISSUE TITLE
Wrong Version of MJML app - Link says 2.10, file is 2.9.0

### ISSUE THREAD

**Issue by Brandonw365** [mjmlio/mjml#1390]
Hello, 

The link on this page https://mjmlio.github.io/mjml-app/ says that version 2.10 is available for download, however the file downloaded is version 2.9.

CTA on github
![image](https://user-images.githubusercontent.com/10367769/47231490-e1f56d80-d381-11e8-88ac-f9cbb626fa97.png)

File Downloaded
![image](https://user-images.githubusercontent.com/10367769/47231549-094c3a80-d382-11e8-98f7-0b17a47e7a21.png)

**Comment by iRyusa** [comment]
Hi,

Sorry MJML App support is not done here, please use this repo instead https://github.com/mjmlio/mjml-app
