### ISSUE TITLE
Setting width  explicitly in mj-image tag still returns the default 100% width

### ISSUE THREAD

**Issue by cbtposborne** [mjmlio/mjml#1392]
**Describe the bug**
I am trying to set the width of an image to 30px, but it still returns as 100% so doesn't contain a width. 

**To Reproduce**
1. Create a file with this MJML code: 
<mjml>
<mj-body>

      <mj-section full-width="full-width">
        <mj-column width="50px" padding="0 10px">
            <mj-image 
                padding-top="0" 
                padding-bottom="0"
                height="30px"
                width="30px"
                src="https://perfectpets.com.au/images/images/ginger_kitten.gif" 
            />
        </mj-column>
        <mj-column width="50px" padding="0 10px">
            <mj-image 
                padding-top="0" 
                padding-bottom="0"
                height="30px"
                width="30px"
                src="https://perfectpets.com.au/images/images/ginger_kitten.gif" 
            />
        </mj-column>
        <mj-column width="50px" padding="0 10px">
            <mj-image 
                padding-top="0" 
                padding-bottom="0"
                height="30px"
                width="30px"
                src="https://perfectpets.com.au/images/images/ginger_kitten.gif" 
            />
        </mj-column>
        <mj-column width="50px" padding="0 10px">
            <mj-image 
                padding-top="0" 
                padding-bottom="0"
                height="30px"
                width="30px"
                src="https://perfectpets.com.au/images/images/ginger_kitten.gif" 
            />
        </mj-column>
        <mj-column width="50px" padding="0 10px">
            <mj-image 
                padding-top="0" 
                padding-bottom="0"
                height="30px"
                width="30px"
                src="https://perfectpets.com.au/images/images/ginger_kitten.gif" 
            />
        </mj-column>
      </mj-section>
</mj-body>
</mjml>

2. Render it to HTML by running: mju --build -i ./path-to-template -o ./path-to-build-file
3. View source from any browser window

**Expected behavior**
I am expecting the image to be 30px wide by 30px tall, but instead I am getting 100% wide by 30px tall

**MJML environment (please complete the following information):**
 - OS: 
  "dependencies": {
    "mjml": "^4.2.0-beta.2",
    "mjml-cli": "^4.2.0-beta.2",
    "npm-run-all": "^4.1.3"
  }

  "devDependencies": {
    "mjml-utils": "^2.2.1"
  }

**Additional context**
This happens any time I use the image size option.

**Comment by iRyusa** [comment]
Well this look like to misbehave because mj-image has a default padding left/right of 25px on mj-image. So your image is 0 px wide.

Resetting the padding to 0 on `mj-image` should display your cats : https://mjml.io/try-it-live/BkS7zL2oQ
