### ISSUE TITLE
Interaction between mj-all border attribute and mj-accordian border attribute

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1394]
**Is your feature request related to a problem? Please describe.**
Demo at [https://mjml.io/try-it-live/Sy2gzO5jQ](https://mjml.io/try-it-live/Sy2gzO5jQ)

Also (because it's short and we might be changing the code as we work):

    <mjml>
      <mj-head>
        <mj-attributes>
          <mj-all border="none" />
        </mj-attributes>
      </mj-head>
    
      <mj-body width="690px" >
        <mj-wrapper padding="20px" >
          <mj-section padding="20px 0 0 0" >
            <mj-column>
              <mj-accordion border="solid blue 1px" >
                <mj-accordion-element>
    
                  <mj-accordion-title>
                    accordion title
                  </mj-accordion-title>
              
                  <mj-accordion-text>
                    accordion text
                  </mj-accordion-text>
    
                </mj-accordion-element>
              </mj-accordion>
            </mj-column>
          </mj-section>
        </mj-wrapper>
      </mj-body>
    </mjml>

Note the attribute and property on `mj-accordion`: `border="solid blue 1px"`.

With the three lines in `<mj-head>` either

    <mj-attributes>
      <mj-all border="none" />
    </mj-attributes>

or

    <mj-attributes>
      <mj-all border="0" />
    </mj-attributes>

the output for the accordion closed is
![image](https://user-images.githubusercontent.com/14095071/47274583-26446180-d56c-11e8-9764-0fb1fe8c424d.png)

and the output for the accordion open is
![image](https://user-images.githubusercontent.com/14095071/47275681-ff3f5d00-d576-11e8-84c6-3f9279a592d1.png)

Note the absence of the bottom border(s).

**Describe the solution you'd like**

Bottom border(s).

**Additional info**

Without the three lines in `mj-head` described above (that is, with nothing between the `mj-head` and `/mj-head` tags), the output for the accordion closed is
![image](https://user-images.githubusercontent.com/14095071/47274841-52151680-d56f-11e8-84be-316f76ebd5ca.png)

and the output for the accordion open is
![image](https://user-images.githubusercontent.com/14095071/47275724-57765f00-d577-11e8-91b7-51cbb8f20a88.png)

There are no other changes to the source. Note the presence of bottom border(s).

**Additional behaviors of `mj-accordion` demonstrated**

* Notes about icons and defaults:
  * None of the three variants of code mentioned above included use of mj-accordion attributes `icon-unwrapped-alt`, `icon-unwrapped-url`, `icon-wrapped-alt`, or `icon-wrapped-url`.
  * All four of the mentioned attributes have defaults (the plus and minus characters for two of them; imgur URLs for the other two).
  * Neither result includes either an imgur icon or alternate text.
  * I would not have been surprised to see either an imgur icon or a character backup.

* Notes about text color:
  * None of the code specified a color for text.
  * For MJML color attributes (`color`, `background-color`, `border-color`, etc.), all defaults are either white, greys, or black.
  * The text in both results is blue.
  * Perhaps there's an undocumented blue default somewhere?
    * I can't suspect the text color is following the border color. I changed the border color to red and got a red border around blue text.

**Describe alternatives you've considered**

For the first report, there is the option to not use `mj-all`.

For the second and third reports, there is the option to always specify the four subject attributes (report 2) and any color attributes (report 3).

In any of those cases, perhaps we'll consider change to MJML documentation.

**HTML differences**

There are five differences between HTML generated by code `mj-all` and other code:
* Three differences are in `style` attributes. In each case, code using `mj-all` includes a property "border:none;" that is absent in the other code.
* Two differences are in properties on the `<table>` tags holding, respectively, the "accordion title" and "accordion text" strings.
  * For the code using `mj-all`, both tables include the property "border-bottom:none;".
  * For the other code, those two tables include instead, "border-bottom:solid blue 1px;".

**HTML observations**

I find many references `mj-accordion-checkbox` in several forms. Many have `display:none` associated. Similarly, I find references to the imgur URLs, both with attribute `style="display:none;"` among other properties.

**Comment by iRyusa** [comment]
It looks like some of the internal border logic shouldn't be affected by `mj-all`, cc @kmcb777 accordion-element should only listen to `mj-accordion` border and ignore local border attribute

It should be easy to fix in 4.3

**Comment by kmcb777** [comment]
@GarryFlemings Hi, thanks for reporting this but this is actually already fixed in 4.2
Attributes transmitted by the parent element now have priority over those transmitted by mj-all
