### ISSUE TITLE
accordion android border

### ISSUE THREAD

**Issue by abovelaika** [mjmlio/mjml#1395]
Hello!

I just was testing the accordion and I can't get rid of these small borders on gmail app in mobile devices.
I tried adding border: none, border-collapse: collapse; as inline style in the rendered html but nothing.
I even tried to apply a black border on a black background to hide it.

I am not the best with those tables, sorry if I missing something obvious 
 
This is the mjml code (I used try it live to render the html): 

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-accordion border="none" style="border:none;" padding="0"/>
      <mj-accordion-element icon-wrapped-url="https://www.iconsdb.com/icons/preview/white/arrow-199-xxl.png" icon-unwrapped-url="https://www.iconsdb.com/icons/preview/white/arrow-137-xxl.png" icon-height="24px" icon-width="24px" />
      <mj-accordion-title font-family="Roboto, Open Sans, Helvetica, Arial, sans-serif" background-color="#000000" color="#ffffff" padding="15px" font-size="18px" />
      <mj-accordion-text font-family="Open Sans, Helvetica, Arial, sans-serif" background-color="#000000" padding="15px" color="#acacac" font-size="14px" />
    </mj-attributes>
  </mj-head>

  <mj-body>
    <mj-section padding="20px" background-color="#ffffff">
      <mj-column background-color="#dededd">
        <mj-accordion>
          <mj-accordion-element>
            <mj-accordion-title>Title for collapsable element</mj-accordion-title>
            <mj-accordion-text>
              <span style="line-height:20px">
                Our beatiful collapsable element done to deliver a lot of information in a concise way.
                Too often emails with a lot of content are a very bad experience on mobile. We can also use it if we do not want to highlight something.
              </span>
            </mj-accordion-text>
          </mj-accordion-element>
          <mj-accordion-element>
            <mj-accordion-title>Fully Supported</mj-accordion-title>
            <mj-accordion-text>
              <span style="line-height:20px">
                Content is stacked into tabs and users can expand them at click.
              </span>
            </mj-accordion-text>
          </mj-accordion-element>
        </mj-accordion>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

very basic, almost identical to the one in your documentation.

The email was sent with Litmus/send test.

This is a screenshot from an asus nexus android:
![image](https://user-images.githubusercontent.com/35969802/47418253-0bdfd300-d77a-11e8-8857-16423f375895.png)

Thanks so much for MJML, you made the emailing experience....less painful 🥇

**Comment by iRyusa** [comment]
We did see those line in some templates but never understand where they come from. We'll see what we can do about this one. But it might be an weird Webkit/Blink bug that couldn't be fixed from us :/

**Comment by kmcb777** [comment]
Hi @abovelaika, as iryusa said, we sometimes saw these kind of lines on android. They're not really borders, they seem to be more like empty spaces, revealing the parent element underneath - and their color seem to be a blend of the child and the parent background-colors.

Thus your best shot is to give the parent elements the same background-color.
(One time i even had to wrap my section in a black mj-wrapper to make those disappear.)

You'll probably want to change your column color anyway, because with the mjml you posted this is what i get on emailonacid for android 5 : 
![image](https://user-images.githubusercontent.com/8144509/47685304-490eef80-dbd6-11e8-81e5-84a8bd05226c.png)
