### ISSUE TITLE
install guilde does not work on windows

### ISSUE THREAD

**Issue by pbuzdin** [mjmlio/mjml#1396]
**Describe the bug**
install guide from https://mjml.io/download does not work on windows 7 (possibly 10 too)

**To Reproduce**
Run powershell
npm init -y
npm install mjml

`npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "mjml" under a package
npm ERR! also called "mjml". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-10-24T09_38_37_171Z-debug.log`

To run MJML, type
$ ./node_modules/.bin/mjml index.mjml

**Expected behavior**
it works

**MJML environment (please complete the following information):**
 - OS: Windows 7 x64

**Comment by ngarnier** [comment]
The answer is in your question: 
```
npm ERR! Refusing to install package with name "mjml" under a package
npm ERR! also called "mjml". Did you name your project the same
npm ERR! as the dependency you're installing?
```

You're trying to install a package in a folder bearing the same name as the package. Install it in a folder with a different name (for example: "my-mjml-project").
