### ISSUE TITLE
Fixed width of mj-image not respected on mobile Android email clients

### ISSUE THREAD

**Issue by urbgimtam** [mjmlio/mjml#1397]
Fixed-width in mj-image is not respected on mobile Android email client.

__Steps to reproduce the behavior:__

1. Create a file with this MJML code: 
```
<mjml>
  <mj-body background-color="#555" width="680px">
    <mj-section>
      <mj-column>
        <mj-image 
                width="100px"
                src="https://mjml.io/assets/img/logo-white-small.png"
                alt="MJML logo" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
2. Render normally
3. Send html email
4. Open in an mobile Android native email client (not Gmail).

**Expected behavior**
Rendered HTML should respect the fixed width.

It's currently rendering.:
```
<td style="width:100px;">
<img alt="MJML logo" height="auto" src="https://mjml.io/assets/img/logo-white-small.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;" width="100">
</td>
```

The culprit seems to be the inlined style **"width: 100%;"**. I believe this  is here because of centering the image inside the cell.

I'm able to solve it manually by replacing **width: 100%;** with **margin: auto;**.
This will still center the icon onto its space, but preserve the image width established on the <img> width attribute.

**MJML environment (please complete the following information):**
 - OS: Windows10
 - MJML Version: 4.2
 - MJML tool used: vscode-mjml

**Affected email clients (for rendering issues):**
 - Email Client: Native Android email client 

**Screenshots**
**Observed problem on native Android mobile email client:**
![mjml-icon-problem-screen_pub](https://user-images.githubusercontent.com/1061965/47498637-c09af280-d855-11e8-85c3-ec3a00466fb7.png)

**Expected (screenshot after manual correction in html):**
![mjml-icon-problem_corrected-screen_pub](https://user-images.githubusercontent.com/1061965/47498836-52a2fb00-d856-11e8-869d-bcd641645307.png)

**Comment by urbgimtam** [comment]
Thanks!

About 7% of my user base uses Android native email client, so that is
something for me.

I've made some tests. In outlook 2007 (it's what I have...) the correction
didn't create problems.

Gmail and Gmail for Android didn't display any problems either.
Haven't tested other browsers yet.



A Qui, 25 de out de 2018, 13:26, Maxime Brazeilles <notifications@github.com>
escreveu:

**Comment by kmcb777** [comment]
Hi @urbgimtam your fix doesn't seem to break anything, however i can't reproduce the issue. The image respect the fixed width on all clients on emailonacid, also tested on a real android device.
Which way do you send the email ?

**Comment by iRyusa** [comment]
Well it's not really a client in our test scope, so we would be happy to merge a fix about this email client. 

For now there's not much we can do about this ( it's not a listed client in Litmus & EOA ) so testing a proper fix would be hard.

> I'm able to solve it manually by replacing width: 100%; with margin: auto;.
> This will still center the icon onto its space, but preserve the image width established on the  width attribute.

Here we have to keep the `width: 100%` to have a proper display & avoid overflow in some clients, so it's not really a valid fix.

Would be happy to re-open if you found out why it ignores the parent `td` width.
