### ISSUE TITLE
Social noshare doesn't display icons

### ISSUE THREAD

**Issue by dsampaolo** [mjmlio/mjml#1398]
When adding "noshare" to a mj-social-element, the icon disappears.

ex : 

`<mj-social-element name="twitter" href="https://twitter.com/seonews_fr">Twitter</mj-social-element>`
Share link, icon is displayed

 `<mj-social-element name="twitter-noshare" href="https://twitter.com/seonews_fr">Twitter</mj-social-element>`
Unchanged URL, no icon displayed.

**Comment by iRyusa** [comment]
Hi,

There's a template for issue, that require basic stuff like MJML versions to help us investigate what's going on. `noshare` has been introduced in 4.2, so it looks like you're using an older version of MJML.

**Comment by dylan-13** [comment]
I have the same problem now, and i cant find any solutions..

When i use -noshare, the icon is not display

Someone know what I can do ? Thanks

**Comment by iRyusa** [comment]
Can you share you code please ?

**Comment by dylan-13** [comment]
It's not working on infomaniac mail box (my working adress) but it works on Gmail so it's ok ! Thanks for your fast reaction !

**Comment by iRyusa** [comment]
I don't know about this mail client, so it's probably not supported.
