### ISSUE TITLE
Mj-social in mj-container problem

### ISSUE THREAD

**Issue by sameshako** [mjmlio/mjml#1399]
Hello,
I found something and got no clue how to fix it.
Something happens and the page doesn't render anything custom if the mj-social tag is nested in the mj-container, if the mj-container tag, is removed, it works as it should.

https://mjml.io/try-it-live/SyDt3Hy2m

Any clue on how to approach this problem?

Thank you in advance!

**Comment by ngarnier** [comment]
`mj-container` is deprecated in MJML 4, just remove it. If you leave it, your template is considered to be MJML 3 so the syntax you are using for `mj-social` is invalid (as it changed between MJML v3 and MJML v4).

**Comment by sameshako** [comment]
Thank you for the clarification!
