### ISSUE TITLE
Strange border added around pictures in Gmail Android

### ISSUE THREAD

**Issue by fraincs** [mjmlio/mjml#140]
Here's an example : https://litmus.com/builder/267a3b9 using the demo code on the website
direct link to the bug: https://androidgmailapp.capture.litmuscdn.com/25a39761-d7f7-4a46-b045-92df370a2dcb/results/androidgmailapp-vertical-allowed-1366.png

**Comment by arnaudbreton** [comment]
@fraincs sorry for the slow answer. It seems the link are now expired so we can't really see what is going on. Would be awesome if you could repost them. Apologies for the inconvenience

**Comment by iRyusa** [comment]
Well feel free to reopen if you can provide the step to reproduce ! Thanks
