### ISSUE TITLE
Problem with mj-wrapper

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#1400]
Hi, I have got problem with mj-wrapper on Outlook 2016 and Outlook 2013 120 DPI whole email content is on the left site. On other clients it works fine. When i delete mj-wrapper email backs to normal (center).

It looks like this: https://ibb.co/e0ehVq

**Comment by ngarnier** [comment]
There is an issue template (where we ask for a number of things like the MJML to reproduce) for a reason :). If you don't follow it, we can't help you.
