### ISSUE TITLE
mjml-raw outside body

### ISSUE THREAD

**Issue by jimblue** [mjmlio/mjml#1404]
### Problem

Sometimes a **front matter** is needed. (for almost all flat files systems)
But it's actually impossible to use `<mjml-raw>` outside  `<mjml>`.

### Solution

Enable `<mjml-raw>` outside `<mjml>` tag to be able to add `front matter`.

##### MJML input:
```mjml
<mj-raw>
front matter datas

---

</mj-raw>

<mjml>
  <mj-body>
    </mj-section>
        <mj-text>Hello World!</mj-text>
    </mj-section>
  </mj-body>
</mjml>
```

##### HTML output:
```html
front matter datas

---

<!doctype html>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
      <head>

[ ... rest of the html ... ]
```

**Comment by ngarnier** [comment]
The parser is reading and parsing what's inside `<mjml>` to render it into responsive HTML/CSS. If you need to prepend/append stuff to the generated HTML, that should be pretty easy to do outside of MJML (and it's not the role of MJML to do that). 

Just do it directly in your code where you're rendering MJML into HTML or with a Gulp task.

**Comment by jimblue** [comment]
Hey, thanks for your fast answer!

I'm using gulp to and it's pretty hard to extract the front matter from mjml, save it to a variable to latter prepend it to the html output of mjml. I didn't found how to do that.

Also it makes more sens imo to keep all necessary data for each email in each mjml file. So why not make `mjml-raw` tag work outside? I will not break anything. It'll only give more flexibility to developer using mjml. There is so many differents user cases...

**Comment by jimblue** [comment]
Hey @ngarnier,

What do you think about my last words, you didn't answer.

I would be so nice if you could add this feature.

**Comment by jimblue** [comment]
Hey @ngarnier,

Do you think you could consider this?

Thank you

**Comment by jimblue** [comment]
I mean, I've try so hard to handle that with gulp, outside of mjml, it's pretty hard... I didn't found any solution... I should be much more easier to extend `mjml-raw` to all `mjml` file content, not only whats between mjml tags...

**Comment by iRyusa** [comment]
https://www.npmjs.com/package/gulp-append-prepend it does the job for you already. We don’t want to complexify the parser for a thing that can be done post compile easily

**Comment by jimblue** [comment]
ok @iRyusa tks for your answer

**Comment by holmesadrianh** [comment]
Hi guys, I am running into the same issue. However, I am limited to using grunt. The project that I am working on needs to add custom code to the very top of the compiled email template or it does not work. So I need to be able to add raw code to the MJML but it needs to remain right at the top of the document. I am not sure how to do this. Is it possible for me to create a custom component that works outside of the main <mjml> tag? or maybe at the top of the MJML tag?

Or maybe it can be passed as an attribute to a tag? And maybe the custom tag can be stored as a variable e.g.:
<mjml-variable name="customVariableName">...</mjml-variable>

Then passing it to the main MJML tag to be used at the top. Just some ideas as I have no idea how to solve this problem.

And I was the one who convinced the team on using MJML in the workflow for obvious reasons, but this is proving to be a deal breaker.

**Comment by iRyusa** [comment]
Skeleton can be modified in MJML4 but I'm not convinced that's a proper solution. You can use just another grunt plugin to append to final result ? Like grunt-file-append https://www.npmjs.com/package/grunt-file-append

**Comment by holmesadrianh** [comment]
@iRyusa , thanks for the reply. The thing is, for the Devs who will be working on many of these MJML templates, they need a place to put it in the MJML file directly to then be compiled. Do you have a suggestion for this?

An idea that comes to mind is a custom tag at the top of the page like <top-code></top-code> which a dev can put whatever they want which is automatically placed at the top of the compiled document. I am just not sure how to achieve this with grunt.

**Comment by iRyusa** [comment]
Why would it matters if at the end it's append by grunt workflow after MJML compilation ? For the skeleton part it can be an option

```js
import skeleton from 'mjml-core/src/helpers/skeleton.js'

mjml2html(input, { 
  skeleton: (options) => `<!-- Whatever you want here will be at beginning of the document, and you can pass custom options here -->
${skeleton(options)` 
})
```

You can even do a regexp that split the file until `<mjml>` starting tag and add it to what `mjml2html`  function returns.

With a workflow tool like grunt/gulp/... you can just do this as you want.
