### ISSUE TITLE
Minify html should minify css

### ISSUE THREAD

**Issue by jimblue** [mjmlio/mjml#1405]
### Problem
CSS is not minified with minify option enabled.

### Solution
Change `html-minifier` option to minify CSS by default

https://github.com/mjmlio/mjml/blob/dad233f7c8dc6ce92845eb048ef743e38e66ce52/packages/mjml-core/src/index.js#L283

### Alternatives
Add an option to toggle CSS minification.

**Comment by ngarnier** [comment]
Have you tried toggling it? I believe minifying the CSS will break the responsiveness in email clients.

**Comment by jimblue** [comment]
Yep, I did directly in node_modules and it works.
All CSS code in the head is minified between `<style>` tag.

**Comment by ngarnier** [comment]
Yep, but have you tested the results across email clients?

**Comment by jimblue** [comment]
Sorry, I can only test it on mail ios and mail mac os. But I didn't see any issues on both of them.

**Comment by iRyusa** [comment]
I think we should just expose an object to pass extra options to minifier instead of mapping them.

cc @kmcb777

**Comment by iRyusa** [comment]
You can now pass any option to html-minifier through the cli/options arguments 👍 So I'm closing this.
