### ISSUE TITLE
Multi column of mj-image is displayed as one column when forwarded in gmail

### ISSUE THREAD

**Issue by timenz** [mjmlio/mjml#1406]
**Describe the bug**
Multi column of mj-image is displayed as one column when forwarded in gmail

**To Reproduce**
1. Create a file with this MJML code: 

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image src="http://placehold.it/600x469/000/fff?width=600"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image src="http://placehold.it/600x469/000/fff?width=600"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

2. Render normally
3. Send the HTML to an gmail email address
4. From gmail email client forward the email to another address
5. In the gmail email forward compose, the image is stacked in one column

**Expected behavior**
In gmail forward compose email should has 2 column like the original email, not stacked in one column

**MJML environment:**
 - OS: linux
 - MJML Version: 4.1.2
 - MJML tool used: [MJML Email Editor](https://mjml.io/try-it-live/)

**Email sending environment**:
 - Platform used to send the email [Putsmail](https://putsmail.com/)

**Affected email clients (for rendering issues):**
 - Email Client: Gmail 
 - OS: Linux
 - Browser: Opera

**Screenshots**
Expected display in gmail inbox
![in inbox](https://user-images.githubusercontent.com/3658979/47631702-a2950100-db79-11e8-88b9-98ec905e19e4.png)
Column stacked when forwarded
![forwarded](https://user-images.githubusercontent.com/3658979/47631701-a2950100-db79-11e8-86fb-d2ab0ab27b50.png)

**Comment by ngarnier** [comment]
Unfortunately, we can't do anything about that. 

When Gmail (or most email clients for the matter) receives an email, it is processed and the markup is altered. When you transfer it, it is altered again and the responsive styles are broken, so the default version (without responsive styles) is shown. As MJML happens to be mobile-first, the default version is the mobile version. 

Transferring emails is notorious for breaking their layout too.
