### ISSUE TITLE
Error during the installation (No input files found)

### ISSUE THREAD

**Issue by matisback** [mjmlio/mjml#1407]
Hey,

I just installed Nodejs and Npm.
Installed Mjml via this page : https://mjml.io/download
After the first installation, I had : 

$ ./node_modules/.bin/mjml index.mjml
Command line error:
No input files found

As a result, I tried to change to Path to see if any changes may happen, so I typed 
$ export PATH="$PATH:./node_modules/.bin".
And when typing $ mjml index.mjml , I still had : 
Command line error:
No input files found

I don't know if this can help, but when typing:
$ ./node_modules/.bin/mjml -V, 
I got : 
mjml-core: 4.2.0
mjml-cli: 4.2.0

I have absolutely no idea why it doesn't work.
I wish I could know what's wrong with the installation. Any help is welcome.
Thanks for your input.

**Comment by ngarnier** [comment]
Hey @matisback, as `./node_modules/.bin/mjml -V` works, the installation was successful. 

`No input files found` means that the file you specified as an input wasn't found. Create the file `index.mjml` with some MJML inside before running the command.

**Comment by matisback** [comment]
Alright, cheers mate !
