### ISSUE TITLE
Apply css-class to sub-elements of generated HTML

### ISSUE THREAD

**Issue by roja** [mjmlio/mjml#1409]
**Is your feature request related to a problem? Please describe.**
Most components allow for a css-class attribute to be used which attaches the passed class name to the root generated html element. I have a case where I would like this class name to attached to a sub-element of the generated html.

**Describe the solution you'd like**
Ideally, I would like a solution which allowed me to add the element to arbitrary sub-elements probably using a css selector syntax. Something like:

<mj-image css-classes="img=classname1, div.something=classname2" src="..." />

This would apply the class name "classname1" to all img elements within the generated output and "classname2" to all the div elements which already had the class name "something"

**Describe alternatives you've considered**
I can manually add these classes to the sub-elements however it is not an ideal process as the details are lost during every export.

**Additional context**
Trying to make templates for use in vero such that the content is editable. This requires the addition of a class name to the editable html element. Further details at https://help.getvero.com/articles/using-html-templates-in-vero.html

**Comment by iRyusa** [comment]
I don't think we'll have a dedicated solution within MJML for that.

It's too hard to do (and find a proper syntax about it), and have a really
low benefit. What I suggest, you should take a look at
https://github.com/cheeriojs/cheerio and do a custom script that does that
after the MJML compilation.

**Comment by matthewahillman** [comment]
Sounds like what your describing is a script to insert css classes for you, this isn't something emails are capaable of as it would require Javascript/JQuery.

Are you not using css-class or mj-class already?
