### ISSUE TITLE
How can I use it with Laravel?

### ISSUE THREAD

**Issue by yammadev** [mjmlio/mjml#141]
I've been reading that you have to install dependencies trough command line (I mean npm), but in the laravel structure there are many folders, so, where exactly do I have to install it?

**Comment by yammadev** [comment]
I was thinking that it was necessary to save all `mjml` files in some folders and import them, but, reading with calm the documentation I realize that use this framework is a breeze. Just install it globally in the machine using `npm` and the just copy and paste the rendered file to destination path. Nice!

**Comment by fsasvari** [comment]
@yammadev can you please provide some info or quick help/tutorial about using Laravel with MJML ?

**Comment by asahasrabuddhe** [comment]
@fsasvari I am working on creating a package to support MJML in Laravel similar to how we currently use Markdown. I will probably release a beta tomorrow. You're welcome to test and share feedback :)

**Comment by fsasvari** [comment]
@asahasrabuddhe Great news :) Will test it in the following few days.

**Comment by yammadev** [comment]
@asahasrabuddhe sure, in that moment it was a good solution for me, because I just wanted to compile just 1 to 2 emails at most, but in the long term, the best solution should be compiling automatically and in real time, which is what your package aims to do.

**Comment by asahasrabuddhe** [comment]
@yammadev If you can spare time, please give it a try and share your valuable feedback. Thank you!
