### ISSUE TITLE
Support new styles on mj-social

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml#1412]
`mj-social` should support:

- `font-weight`: if not set to a different value on `mj-social-element`, all `mj-social-element`s should inherit from this style
- `font-style`: if not set to a different value on `mj-social-element`, all `mj-social-element`s should inherit from this style

In addition, this style should be fixed:
- `text-decoration`: currently, `mj-social-element` doesn't inherit from the value set on `text-decoration`.

**Comment by matthewahillman** [comment]
I'd like to see a width added, mainly for when the social is inside of a column there is no way to force it to a certain width to make sure that Outlook  < 2003 doesn't center and make it 100% width when you only want it at a certain size.

**Comment by iRyusa** [comment]
Do you have any example of this use case ?
I'm pretty sure that playing with column size should have already decent results

**Comment by matthewahillman** [comment]
> Do you have any example of this use case ?
> I'm pretty sure that playing with column size should have already decent results

If you make a standard 2 column with no set widths, image on  right for example and text on the left, place the social element under a few lines of text within the left column and then test it in Litmus. the social element will center and stretch out inside the column. It only happens in Outlook 2003 to 2000.

![new project](https://user-images.githubusercontent.com/3380011/48912756-57b39400-ee6e-11e8-8c64-785d55061b50.jpg)

Where as everything else pretty much looks like

![new project](https://user-images.githubusercontent.com/3380011/48912788-65691980-ee6e-11e8-8298-caf943a47be4.png)

**Comment by iRyusa** [comment]
Weird I don't have the same behavior than you on my side with EOA : 

![image](https://user-images.githubusercontent.com/570317/48913077-aade1480-ee77-11e8-953c-2fe9c9c6bc21.png)
https://mjml.io/try-it-live/S1DUZINR7

Can you share the code ?

**Comment by ngarnier** [comment]
Your code is invalid by the way @matthewahillman, nesting `wrapper`, `section` and `column` inside another set of `section` and `column` is not supported.

```mjml
   <mj-section>
      <mj-column>
      <!-- this below is invalid -->
        <mj-wrapper mj-class="whitebg">
          <mj-section>
            <mj-column>
```

As stated in the doc: 
> Columns cannot be nested into columns, and sections cannot be nested into columns as well.
