### ISSUE TITLE
Can I create a carousel that scrolls automatically?

### ISSUE THREAD

**Issue by DanyeWest** [mjmlio/mjml#1414]
I'd like to know if I can make my carousel automatically go through the photos. 

Here is my carousel code:

<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-carousel thumbnails="hidden">
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-03.png?17792505984384578237" />
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-04.png?17792505984384578237" />
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-06.png?17792505984384578237" />
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-05.png?17792505984384578237" />
        </mj-carousel>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by DanyeWest** [comment]
I do not see the code pasted in that so I'm pasting again

<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-carousel thumbnails="hidden">
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-03.png?17792505984384578237" />
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-04.png?17792505984384578237" />
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-06.png?17792505984384578237" />
          <mj-carousel-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Why_to_Customize-05.png?17792505984384578237" />
        </mj-carousel>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by matthewahillman** [comment]
A sliding carousel would require javascript which isn't supported in emails.
