### ISSUE TITLE
Mj-raw {input boxes} glitch

### ISSUE THREAD

**Issue by anarey3117** [mjmlio/mjml#1418]
I'm currently using MJML to make phishing templates which will be imported into GoPhish. Our client wants credential harvesting and have done some Googling to find out how I can marry the two together. After lots of testing, my code does actually work however, it doesn't work when the code is inside an <mj-column>. If I put the code into a <mj-section> for example, the button directs me to the page as linked inside GoPhish, and the resulting Username and Password displays. But if I just directly paste the code into a <mj-column>, the button click does nothing.

This one does work when the HTML is imported into GoPhish: https://mjml.io/try-it-live/S1Ia7m1p7
This one does not work when the HTML is imported into GoPhish: https://mjml.io/try-it-live/rJFiJX1TX

**MJML environment (please complete the following information):**
 - OS: Windows 10 Pro x64
 - MJML Version 4.1.2
 - MJML tool used mjml.io

I'm sorry for the lack of information, if you need anything like videos or screenshots, please do let me know. All I know is that the exact same code works inside a section, but not in a column (columns used to space things out and make it look pretty). 

Thanks

**Comment by iRyusa** [comment]
Well, many things are wrong in your template:

 - Outputting in mj-column would produce non-valid HTML just check the output HTML, so it might be misinterpreted by the browser

```html
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="" width="100%">
                          <style>
                            input {
                              border: 1px solid #ccc;
                              width: 320px;
                              height: 23px;
                            }

                            input[type=button],
                            input[type=submit],
                            input[type=reset] {
                              background-color: #069685;
                              border: none;
                              color: #fff;
                              text-decoration: none;
                              cursor: pointer;
                              height: 25px;
                              width: 60px;
                            }
                          </style>
                          <form action="" method="post" name="form"> <input type="text" name="username"></input> <br></br> <input type="password" name="password"></input> <br></br> <input type="submit" value="Log In" style="float:right"></input>
                          </form>
                        </table>
```
- form simply doesn't work in email clients
- `mj-body` with a `100%` width is invalid, you can only have a pixel based body in MJML
- `mj-spacer` used outside of a column
- you're using style like `float` that are not really well supported

I don't think we can do anything about this.

**Comment by anarey3117** [comment]
If you're just going to slate what I've done, not taking into consideration why spacers are outside of columns (to achieve the design that they want), or why I've used floats, please don't comment and then instantly close the threat. You've helped me exactly 0%, and I'm back to where I started off.

In the future, actually offer help and constructive criticism, oh and suggestions can also be a good thing.

Thanks for nothing :)
