### ISSUE TITLE
Remove NavBarLink default text decoration

### ISSUE THREAD

**Issue by pxwee5** [mjmlio/mjml#1420]
**Is your feature request related to a problem? Please describe.**
NavbarLink's shouldn't have default text-decoration set. The default inline `text-decoration: none` is not necessary by default and will mess up if there's a need to add hover effect on nav links.

It's impossible to overwrite it via mj-style or etc.

**Comment by iRyusa** [comment]
Here's a small example here : https://mjml.io/try-it-live/Bka3Ukm6m

**Comment by pxwee5** [comment]
Well, I'm trying to add hover effect via the `<style>` tag to do underline on hover. But because inlined css has more specificity than the `<style>` tag, none of the styles in the tag will work.

Example style tag
```
a { text-decoration: none}
a:hover { text-decoration: underline }
```
Both of which has less specificity than the inline css.

Is there a specific use case for adding the default `text-decoration: none` on `mj-navbar-link`?

**Comment by iRyusa** [comment]
It was the most common use-case when we used it.

You just have to use `!important` to bypass inline style as standard css https://mjml.io/try-it-live/B1PU8e7a7

But I would recommend the `mj-attributes` way instead of using `mj-style` for that

**Comment by pxwee5** [comment]
Both the methods you suggested does not solve the required outcome. 
Can you create an example on `try-it-live` that will create a `mj-navbar-link` that have links that only underlines during hover?

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/HJit9x7T7

**Comment by pxwee5** [comment]
That's ugly, double `!important`. But it does the job. Thanks.
