### ISSUE TITLE
Images ignoring width and going 100% in Android Mail App on Huawei

### ISSUE THREAD

**Issue by nevnein** [mjmlio/mjml#1422]
**Describe the bug**
Fixed width mj-image ignores `width` value and goes 100%. 

**To Reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image
          src=any
          width=any fixed width, eg. 40px
        />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
2. Render it to HTML
3. Send the HTML to an email address

**Expected behavior**
The image should be centered, and with the set (eg. 40px) width.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.2.0
 - MJML tool used: MJML for VsCode

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: [Putsmail](https://putsmail.com/)

**Affected email clients (for rendering issues):**
 - Email Client: Mail App
 - OS: Android 8.0.0

**Additional context**
Haven't tested in any other Android base mail apps than Mail on Huawei P10 and Huawei P8 plus. The problem disappears when removing the inline `width: 100%`from the compiled HTML `img` tag, but I'm afraid this could cause issues with other clients/browsers.

**Comment by iRyusa** [comment]
👋 
This has been reported here already : https://github.com/mjmlio/mjml/issues/1397#issuecomment-436259623

But, I'm not really sure how we can really fix it, as it's not a widely used client and we have no really way to test this one. It looks like to use another custom render engine than default Android client so it's even harder to debug :/

**Comment by nevnein** [comment]
Oh sorry, I tried to search for open issues before posting but I guess the keywords were too vague. I'm closing this one, if I find a fix that doesn't break the current code I will post it there.
