### ISSUE TITLE
Some containers don't respect the size on mobile Huawei Android Email clients

### ISSUE THREAD

**Issue by urbgimtam** [mjmlio/mjml#1428]
_Sorry if this has been posted before. I've searched through and haven't found anything related.
I also understand the Huawei Android Email client is not a tested email client. However, this is a real problem that will become more pronounced as the market share increases._ 

**The Bug**
On some Huawei Android mobile email clients, containers seem to have some extra space. Most of the times the 'spill' seems to be on the right (also saw some to the left, although usually half the size of the right ones).
The bottom also appears affected, mainly by mj-body.

This is happening, so far, in sections, columns and images. Because images live inside columns that live inside sections, the result is more pronounced in images.

Even if you can minizime the problem by selecting a background color similar to the image in the mj-section, the size of it is never really correct. Even mj-text displays some extra space to the right.

**To Reproduce**
1. Create a file with this MJML code: 

```
<mjml>
  <mj-body background-color="red">
    <mj-section 
         padding="0" 
         background-color="pink">
      <mj-column background-color="orange">
        <mj-image 
           fluid-on-mobile="true" 
           padding="0" 
           src="http://5vph.mj.am/img/5vph/b/1g86w/0696u.jpeg" 
           />
      </mj-column>
    </mj-section>
    <mj-section background-color="#f0f0f0">
      <mj-column>
        <mj-text>
           This is some sample text. This is some sample text. 
           This is some sample text. This is some sample text. 
           This is some sample text. This is some sample text.  
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

2. Render it to HTML by doing `mjml -r test.mjml -o test.html`
3. Send the HTML to an email address with any system

**Expected behavior**
'Spills' from parent containers should not be present. Container sizes should be correctly maintained.

**MJML environment (please complete the following information):**
 - OS: Android
 - MJML Version 4.2.0
 - MJML tool used [MJML cli, MJML vscode extension]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [[Guestfolio](https://guestfolio.net/)] (doesn't change the html output) 

**Affected email clients (for rendering issues):**
 - Email Client: Huawei Android Email client
 - OS: Android
Note: Could not test on other Android devices so far.
Gmail, Outlook and Apple products are ok (to the best of their own capabilities; example: Outlook has some flaws with padding).

**Screenshots**
Actual device display:
![mjml-android-spill](https://user-images.githubusercontent.com/1061965/48622524-f89ddd00-e99e-11e8-89a7-0cf249069c85.png)

The desired result shoud be (photoshoped):
![mjml-android-expected-result](https://user-images.githubusercontent.com/1061965/48622718-8b3e7c00-e99f-11e8-8dda-ba12a1645cc1.png)

**Additional context**

**Comment by iRyusa** [comment]
Sorry about the generic answer here, but it will be the same as previous issue on this client. 

As it's not a major client and not available in litmus/eoa we have no real way to try identify what's happening.

We would be happy to merge any PR, but it looks like the engine behind this email client is doing a lot of non-standard things with the HTML.

**Comment by urbgimtam** [comment]
I understand completely. 

But at least these issues become identified. So if someone searches for them they'll find some details.

Meanwhile I'll be trying to figure what underlying code is making the unexpected issues.

**Comment by iRyusa** [comment]
Feel free to re-open if someone willing to work on this
