### ISSUE TITLE
Mobile gmail client content on left

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#1431]
**Describe the bug**
I would like the table to be centered in the mobile view. In Outlook and the browser, everything looks fine, but in the Gmail client for mobile, the table is shifted to the left.

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`

```
<mjml>

  <mj-head>
  <mj-style>
    @media only screen and (max-width:400px) {
        table[class=container], table[class=respTable] {width: 100% !important;}
      }
    
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section background-color="black">
      <mj-column>
        <mj-raw>
      <table class="container" border="0" cellspacing="0" cellpadding="0" width="365" align="center">
      <tr align="center">
        <td>
          <table class="respTable" border="0" cellspacing="0" cellpadding="0" width="50%" align="left">
            <tr>
              <td align="center"><p style="line-height: 36px; margin: 0px 0; text-align: center;font-size:34px;color:#ffffff;font-weight:700;font-family:'Roboto',Helvetica,Arial,sans-serif">UNDERLINE</p></td>
            </tr>
            <tr >
              <td align="center"><image width="160px" src="https://cdn2.hubspot.net/hubfs/3297259/Emails/Black_Friday_November_2018/500_Discounts_CountDown/czerwona_kreska.png"  padding-top="0px" padding-left="0px"/></td>
            </tr>
          </table>
          <table class="respTable" border="0" cellspacing="0" cellpadding="0" width="50%" align="left">
            <tr>
              <td  align="center"><p style="line-height: 36px; margin: 0px 0; text-align: center;font-size:34px;color:#ffffff;font-weight:700;font-family:'Roboto',Helvetica,Arial,sans-serif">TEXT</p></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
     
      </mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml> 
```

**Expected behavior**
Centered table in gmail mobile view.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.1.2
 - MJML App 2.10.0

**Affected email clients (for rendering issues):**
 - Email Client Gmail
 - OS: Android

**Screenshots**
https://ibb.co/nkVtS0

**Comment by iRyusa** [comment]
Hi,

The HTML produced by this MJML is invalid: mj-column open a `table` and you have directly a table inside as a child. 
Please add at least a `tr/td` to have valid HTML.

For your media query, just use regular `class` selector instead of attribute selector, it's generally a bad idea and it's not that well supported `.container, . respTable` should be enough.

**Comment by ProdigyMaster** [comment]
Hey, problem was in my table I solved it by using mj-columns. And now it works fine. Thanks

**Comment by kmcb777** [comment]
Great, i'm closing then
