### ISSUE TITLE
configPath optiion to set custom path for .mjmlconfig does not work

### ISSUE THREAD

**Issue by godmuahaha** [mjmlio/mjml#1432]
**Describe the bug**
It's described in docs that you have an option to specify an alternative path to .mjmlconfig
But neither command line way, no mjml2html + parseOptions way doesn't work

**To Reproduce**
1. Create a custom MJML component in 'components' folder
2. Add .mjmlconfig file with this component link to components folder
3. Parse your template with custom component, using
` mjml2html(template, {
    configPath: 'components',
  })` (I tried different variations of how to specify the path - no success)
4. Template is rendered, but custom component is not.

**Expected behavior**
The component is rendered.
Currently it works only if I put .mjmlconfig to the root folder. Which does not suit my needs

**MJML environment (please complete the following information):**
 - OS: [MacOS]
 - MJML Version [4.2.0]
 - MJML tool used [script with mjml2html(). In MJML App specifying config path in dev version also does not work]

**Comment by kmcb777** [comment]
Hi @godmuahaha , thanks for reporting this, i see there was indeed a confusion in the docs, the option name is actually `mjmlConfigPath` instead of `configPath`

**Comment by godmuahaha** [comment]
Thanks! Works with `mjmlConfigPath`!
