### ISSUE TITLE
Problems Outlook mj-carousel  and gmail

### ISSUE THREAD

**Issue by rodrigoBruno1986** [mjmlio/mjml#1437]
Hello, I tell you my problem. I have a mj-carousel that does not play in any way in outloock and in gmail. I'm going to leave my mjml code and the screenshots of the errors. So these components can not be used in larger emails like gmail and outloock?
I hope you help me thanks!

http://work.rappargentina.com.ar/drinks/mjml-slider/img/outlook.jpg

http://work.rappargentina.com.ar/drinks/mjml-slider/img/gmail.jpg

**CODE MJML**

-------------------------------------------
<mjml>
  <mj-head>
     <mj-title></mj-title>
      <mj-attributes>
        <mj-image alt="" padding="0px"></mj-image>
        <mj-section padding="0px"></mj-section>
        <mj-class name="titulo" font-family="Times New Roman" color="#111111" font-size="35px" line-height="14px"></mj-class>
        <mj-class name="copy" font-family="Verdana" color="#4a4a4a" font-size="16px" line-height="26px" align="center"></mj-class>
          <mj-class name="boton" font-family="Verdana" color="white" font-size="16px" line-height="26px" align="center"></mj-class>
        <mj-class name="headline-text" font-family="Times New Roman" color="#111111" font-size="35px" line-height="36px" align="center" text-transform="uppercase"></mj-class>
    </mj-attributes>
      <mj-style>
         @media only screen and (max-width: 480px){
           .titulo-mobile{
          
             font-size:26px;
         
           }
           
           .boton-mobile{
              color:red;
           }
           .texto-selecciona{
             font-size:15px;
           }
           .cta{
            font-size:16px;
            
           }
         }
      </mj-style>
  </mj-head>
  <mj-body>
     <mj-section padding="20px 10px">
             <mj-text
                color="black"
                align="center"
                 href="https://www.google.com"
                >
                <a style="color:black; text-decoration:none;"
                href="http://work.rappargentina.com.ar/drinks/mjml-slider/index.html">¿No podés visualizar este mail? Miralo online </a>
             </mj-text>
          </mj-section>
          <mj-wrapper
              background-color="#f9f9f9" 
              padding="0px">
            
            <mj-section
              padding="0px">
                 <mj-column>
                     <mj-image 
                          width="600px" 
                          src="http://work.rappargentina.com.ar/drinks/mjml-slider/images/imagen_01.jpg" />
                  </mj-column>
            </mj-section>
            <mj-section
              padding="0px">
                  <mj-column>
                    <mj-image alt="BLACK FRIDAY" href="" width="600px" src="http://work.rappargentina.com.ar/drinks/mjml-slider/images/imagen_02.png">
                  </mj-image>
                  </mj-column>
            </mj-section>
            <mj-section 
                padding="20px 0 0px">
                <mj-column>
                  <mj-text 
                  
                    mj-class="headline-text">
                    <span class="titulo-mobile" >
                       Grandes descuentos
Para grandes momentos.
                    </span>
                   
                    <br> </mj-text>
                </mj-column>
            </mj-section>
            <mj-section 
                padding="5px 0 0px">
                <mj-column>
                  <mj-text 
                      mj-class="copy">Este Black Friday es la excusa perfecta para compartir con quien quieras. ¿Qué esperás para aprovecharlo?
                   </mj-text>
                </mj-column>
            </mj-section>
            <mj-raw>&lt;!--[if !mso]&gt;&lt;\!--&gt;</mj-raw>
             <mj-section>
        <mj-column width="450px">
          <mj-carousel tb-border-radius="0px" tb-hover-border-color="red" tb-width="60px" tb-border="0px" left-icon="http://work.rappargentina.com.ar/drinks/mjml-slider/images/flecha.png" right-icon="http://work.rappargentina.com.ar/drinks/mjml-slider/images/flecha.png"
            icon-width="20px">
            
         
            <mj-carousel-image href="" thumbnails-src="http://work.rappargentina.com.ar/drinks/mjml-slider/images/ballantines.jpg" alt="" src="http://work.rappargentina.com.ar/drinks/mjml-slider/images/ballantines.jpg"></mj-carousel-image>
            
               <mj-carousel-image href="" thumbnails-src="http://work.rappargentina.com.ar/drinks/mjml2/img/4.png" alt="" src="http://work.rappargentina.com.ar/drinks/mjml2/img/4.png"></mj-carousel-image>
                  <mj-carousel-image href="" thumbnails-src="http://work.rappargentina.com.ar/drinks/mjml-slider/images/ballantines.jpg" alt="" src="http://work.rappargentina.com.ar/drinks/mjml-slider/images/ballantines.jpg"></mj-carousel-image>
                     <mj-carousel-image href="" thumbnails-src="http://work.rappargentina.com.ar/drinks/mjml2/img/2.png" alt="" src="http://work.rappargentina.com.ar/drinks/mjml2/img/2.png"></mj-carousel-image>
            
         
             
           
          </mj-carousel>
      
      </mj-section>
      
      <mj-section>
        <mj-column width="480px">
          <mj-text font-family="Open Sans, Arial, sans-serif" font-size="18px" line-height="26px" color="#bcbec0" text-transform="uppercase" align="center"><span class="texto-selecciona">Hacé click en el producto que quieras ver
</span> </mj-text>
        </mj-column>
      </mj-section>

      
      <mj-section padding="10px 0px 0px">
      <mj-column>
        <mj-button 
              padding="15px 2px" 
              mj-class="boton" 
              border-radius="0px" 
              href="https://www.drinksandcommunity.com.ar/blackfriday.html" 
              background-color="#65a3d1"
              height="40px"
              width="60%">
              <span class="cta">¡MIRÁ TODAS LAS OFERTAS!</span></mj-button>
      </mj-column>
     
    </mj-section>

   <mj-section
             background-color="white">
             <mj-text
                padding-top="25px"
                color="#ffffff"
                font-family="arial"
                font-size="12px"
                align="center"
                line-height="30px"
                font-weight="200"
                >
              <a style="color:black; text-decoration:none;" href="https://www.drinksandcommunity.com.ar/termos-e-condicoes">• Términos y Condiciones</a>  <a style="color:black; text-decoration:none;" href="https://www.drinksandcommunity.com.ar/politica-de-privacidad">• Política de privacidad</a> <a style="color:black; text-decoration:none;" href="https://www.pernod-ricard.com/es/nuestros-compromisos/nuestro-modelo-nuestros-4-compromisos/">• Declaración de responsabilidad </a> </br>
                <a style="color:black; text-decoration:none;" href="http://click.news-campaigns.pernod-ricard.com/unsub_center.aspx?qs=781b9675966c2d485f5704202d062f7f725aaeaa3065e9d689e7b9bcb5a47633d7ed799a479c4543a2011f548c1cffa37b1e1118d0120b9ab982cc5c935dcbeb946f5afd265322ad">Cancelar Suscripción</a>
             </mj-text>
          </mj-section>
          
    
    <mj-section
       padding="15px ">
      <mj-column>
        <mj-button 
              padding="15px 2px" 
              mj-class="boton" 
              border-radius="0px" 
              href="https://www.drinksandcommunity.com.ar/" 
              background-color="black"
              height="40px"
              width="100%">
              <span>BEBIDAS</span>
      </mj-button>
      
      </mj-column>
      <mj-column>
        <mj-button 
              padding="15px 2px" 
              mj-class="boton" 
              border-radius="0px" 
              href="https://www.drinksandcommunity.com.ar/brands.html" 
              background-color="black"
              height="40px"
              width="100%">
              <span>MARCAS</span>
      </mj-button>
      
      </mj-column>
     
    </mj-section>
    
    <mj-section
        padding="20px "
        >
             <mj-text
                color="#717275"
                font-family="arial"
                font-size="14px"
                align="justify"
                line-height="20px"
                font-weight="200"
                background-color="white"
                
                >
                 <strong>BEBER CON MODERACIÓN. PROHIBIDA SU VENTA A MENORES DE 18 AÑOS SI VAS A CONDUCIR, NO TOMES ALCOHOL. </strong>
                </br></br>
                El presente correo electrónico fue enviado por reply@email.pernod-ricard-argentina.com. Si desea no recibir estos correos electrónicos por favor responda a dicha casilla solicitando la baja. El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326. La DIRECCION NACIONAL DE PROTECCIÓN DE DATOS PERSONALES, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales.- Art. 27, Inc. 3 de la Ley 25.326: "El titular podrá en cualquier momento solicitar el retiro o bloqueo de su nombre de los bancos de datos a los que se refiere el presente artículo".- Art. 27, 3er párrafo del Decreto 1558/0: "En toda comunicación con fines de publicidad que se realice por correo, teléfono, correo electrónico, Internet u otro medio a distancia a conocer, se deberá indicar, en fxrma  solicitar el retiro o bloqueo, total o parcial, de su nombre de la base de datos. A pedido del interesado, se deberá informar el nombre del responsable o usuario del banco de datos que proveyó la información".
             </mj-text>
    
          </mj-section>
            
            

          </mj-wrapper>
  </mj-body>
</mjml>

**Comment by iRyusa** [comment]
Hi,

Both client doesn't support any click interaction so we hide arrows when it's not supported.

That's why it doesn't display anything here.

**Comment by kmcb777** [comment]
Hi @rodrigoBruno1986 to be more precise, Outlook doesn't support any pointer interaction, and gmail doesn't support click, only hover.
So the best workaround we found is :
- for Outlook, only display the first image
- for Gmail, hide the arrows and only show the thumbnails, so the other images can be displayed when the user hover the thumbnails
It doesn't seem possible to do much better unfortunately
