### ISSUE TITLE
Bug in mj-image width?

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#144]
There is strange behaviour now in mj-image, when you use and set image width to 350

`<mj-image src="assets/img/logo-small.png" width="350"></mj-image>`

you get

`<img alt="" src="assets/img/logo-small.png" style="border:none;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="350" height="auto">`

So, image is 100% width, not 350. Something to do with @lohek commit https://github.com/mjmlio/mjml/commit/b499396117255be7591af2fe33c9180c540bed3c?

**Comment by Tlapi** [comment]
I see, that there is now default width css style set to 100% by default, but not being recalculated never. I will try to fix this.

**Comment by Tlapi** [comment]
I have just removed default 100% width style as it seems it was added by mistake. See PR https://github.com/mjmlio/mjml/pull/145

**Comment by janus-reith** [comment]
Yes, this broke my design, commented on your pull request...

**Comment by arnaudbreton** [comment]
Hi, sorry about the issue. We'll have a look at it today.

Keep you posted on our progress.

**Comment by Tlapi** [comment]
Hey @arnaudbreton, this should have been already solved by https://github.com/mjmlio/mjml/pull/146

**Comment by arnaudbreton** [comment]
@Tlapi correct, I missed this one sorry. We're currently reviewing it and should merge/release soon. Keep you posted

**Comment by iRyusa** [comment]
@Tlapi 1.3.3 has been released can you test that your MJML work now ? :+1:

**Comment by Tlapi** [comment]
@iRyusa I will.

**Comment by leshayface** [comment]
Hi I have the same problem. Can't override the default 100% of an image

**Comment by iRyusa** [comment]
hi @leshayface the width attribute is applied on `td` that surround the image

**Comment by raderj89** [comment]
i just experienced this issue today. is there a way to set the width on the surrounding `td`? just doing `<mj-image width="300" />` doesn't work for me - it's always set to 100.

**Comment by iRyusa** [comment]
Hey @raderj89 

Maybe because your column is 100px in desktop ?
Can you share some code so I can take a look ?

**Comment by manu2195** [comment]
Hi, I am experiencing the same problem now. 
Setting the width of mj-image in pixels, it is putting 100% width on the surrounding td and the image tag, which leads to the scaling of image with respect to column.

**Comment by komali2** [comment]
I'm having this issue today. Version 4.9.3 as I'm using the editor. 

`<mj-image width="32px" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiI+CiAgICA8ZGVmcz4KICAgICAgICA8bGluZWFyR3JhZGllbnQgaWQ9ImEiIHgxPSI1MCUiIHgyPSI1MCUiIHkxPSIwJSIgeTI9IjEwMCUiPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjAlIiBzdG9wLWNvbG9yPSIjMDhCMUZBIi8+CiAgICAgICAgICAgIDxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzRGOEVGRiIvPgogICAgICAgIDwvbGluZWFyR3JhZGllbnQ+CiAgICAgICAgPGxpbmVhckdyYWRpZW50IGlkPSJjIiB4MT0iNTAlIiB4Mj0iNTAlIiB5MT0iMCUiIHkyPSIxMDAlIj4KICAgICAgICAgICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzAwOTBGRiIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMwMDU5RkYiLz4KICAgICAgICA8L2xpbmVhckdyYWRpZW50PgogICAgICAgIDxwYXRoIGlkPSJiIiBkPSJNMCAwbDI2IDI2SDB6Ii8+CiAgICAgICAgPGxpbmVhckdyYWRpZW50IGlkPSJkIiB4MT0iNTAlIiB4Mj0iNTAlIiB5MT0iMCUiIHkyPSIxMDAlIj4KICAgICAgICAgICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI0ZGM0E1MCIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNFRDMwNkIiLz4KICAgICAgICA8L2xpbmVhckdyYWRpZW50PgogICAgPC9kZWZzPgogICAgPGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8cGF0aCBkPSJNMCAwaDMydjMySDB6Ii8+CiAgICAgICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMyA0KSI+CiAgICAgICAgICAgIDxwYXRoIGZpbGw9InVybCgjYSkiIGQ9Ik0xNi4zMzIuMDA1QTcuNjYyIDcuNjYyIDAgMCAwIDE2IDIuMjZDMTYgNS44NjYgMTkuMTM0IDkgMjMuMjYgOWE2LjQ3NiA2LjQ3NiAwIDAgMCAyLjk5OS0uNzVjLjE1OC43MjUuMjQxIDEuNDc4LjI0MSAyLjI1QzI2LjUgMTYuMjk5IDIxLjc5OSAyMSAxNiAyMXY1SDBWMGgxNmMuMTExIDAgLjIyMi4wMDIuMzMyLjAwNXoiLz4KICAgICAgICAgICAgPHVzZSBmaWxsPSJ1cmwoI2MpIiB4bGluazpocmVmPSIjYiIvPgogICAgICAgIDwvZz4KICAgICAgICA8Y2lyY2xlIGN4PSIyNiIgY3k9IjYiIHI9IjQiIGZpbGw9InVybCgjZCkiLz4KICAgIDwvZz4KPC9zdmc+Cg==" />`

resolves to

```
 <tbody>
                                    <tr>
                                      <td style="width:32px;">
                                        <img height="auto" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiI+CiAgICA8ZGVmcz4KICAgICAgICA8bGluZWFyR3JhZGllbnQgaWQ9ImEiIHgxPSI1MCUiIHgyPSI1MCUiIHkxPSIwJSIgeTI9IjEwMCUiPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjAlIiBzdG9wLWNvbG9yPSIjMDhCMUZBIi8+CiAgICAgICAgICAgIDxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzRGOEVGRiIvPgogICAgICAgIDwvbGluZWFyR3JhZGllbnQ+CiAgICAgICAgPGxpbmVhckdyYWRpZW50IGlkPSJjIiB4MT0iNTAlIiB4Mj0iNTAlIiB5MT0iMCUiIHkyPSIxMDAlIj4KICAgICAgICAgICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzAwOTBGRiIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMwMDU5RkYiLz4KICAgICAgICA8L2xpbmVhckdyYWRpZW50PgogICAgICAgIDxwYXRoIGlkPSJiIiBkPSJNMCAwbDI2IDI2SDB6Ii8+CiAgICAgICAgPGxpbmVhckdyYWRpZW50IGlkPSJkIiB4MT0iNTAlIiB4Mj0iNTAlIiB5MT0iMCUiIHkyPSIxMDAlIj4KICAgICAgICAgICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI0ZGM0E1MCIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNFRDMwNkIiLz4KICAgICAgICA8L2xpbmVhckdyYWRpZW50PgogICAgPC9kZWZzPgogICAgPGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8cGF0aCBkPSJNMCAwaDMydjMySDB6Ii8+CiAgICAgICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMyA0KSI+CiAgICAgICAgICAgIDxwYXRoIGZpbGw9InVybCgjYSkiIGQ9Ik0xNi4zMzIuMDA1QTcuNjYyIDcuNjYyIDAgMCAwIDE2IDIuMjZDMTYgNS44NjYgMTkuMTM0IDkgMjMuMjYgOWE2LjQ3NiA2LjQ3NiAwIDAgMCAyLjk5OS0uNzVjLjE1OC43MjUuMjQxIDEuNDc4LjI0MSAyLjI1QzI2LjUgMTYuMjk5IDIxLjc5OSAyMSAxNiAyMXY1SDBWMGgxNmMuMTExIDAgLjIyMi4wMDIuMzMyLjAwNXoiLz4KICAgICAgICAgICAgPHVzZSBmaWxsPSJ1cmwoI2MpIiB4bGluazpocmVmPSIjYiIvPgogICAgICAgIDwvZz4KICAgICAgICA8Y2lyY2xlIGN4PSIyNiIgY3k9IjYiIHI9IjQiIGZpbGw9InVybCgjZCkiLz4KICAgIDwvZz4KPC9zdmc+Cg==" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:18px;" width="32" />
                                      </td>
                                    </tr>
                                  </tbody>
```

**Comment by Tanmayshetty** [comment]
I am experiencing the same issue.

```
<mjml>
  <mj-body background-color="white">
    <mj-wrapper padding-bottom="5px" background-color="white" background-size="auto" background-repeat="no-repeat" background-position="right top">
      <mj-section padding-bottom="0" padding-top="0" background-color="transparent" css-class="backgroundFilter">
        <mj-column width="3%" padding="0"></mj-column>
        <mj-column width="90%" padding="0">
          <mj-text align="center" font-size="22px" color="#2E2E2E" font-weight="bold" font-style="normal" line-height="31.2px"> What&prime;s new </mj-text>
        </mj-column>
      </mj-section>
      <mj-section padding-bottom="0" padding-top="0" background-color="transparent">
        <mj-column padding="0" width="60px">
          <mj-image height="60px" width="60px" src="https://assets.room3d.com/triple-star-feature.png" />
        </mj-column>
        <mj-column width="80%" padding="0">
          <mj-text align="center" font-size="16px" color="#676767" font-weight="300" font-style="normal" line-height="25.6px"> Thank you for beeing part of our ROOM Community. <br />Our open beta with new, extensive and powerful capabilities launches now! 🎉 </mj-text>
        </mj-column>
      </mj-section>
      </mj-container>
  </mj-body>
</mjml>
```
The HTML code that is generated 

``` 
<div class="mj-column-px-60 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
   <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
      <tbody>
         <tr>
            <td style="vertical-align:top;padding:0;">
               <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="" width="100%">
                  <tbody>
                     <tr>
                        <td align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                           <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
                              <tbody>
                                 <tr>
                                    <td style="width:10px;">
                                       <img height="60" src="https://assets.room3d.com/triple-star-feature.png" style="border:0;display:block;outline:none;text-decoration:none;height:60px;width:100%;font-size:13px;" width="10">
                                    </td>
                                 </tr>
                              </tbody>
                           </table>
                        </td>
                     </tr>
                  </tbody>
               </table>
            </td>
         </tr>
      </tbody>
   </table>
</div>
```
I am using MJML v4.12.0
