### ISSUE TITLE
Add title attribute for mj-social-element

### ISSUE THREAD

**Issue by fac42** [mjmlio/mjml#1447]
**Is your feature request related to a problem? Please describe.**
Currently I have to open the compiled HTML and manually add title attributes to social icons.

**Describe the solution you'd like**
If this attribute could be added to the next version of MJML that would be great 👍.

**Describe alternatives you've considered**
Currently only a manually adding the title attribute is possible.

**Additional context**
N/A

**Comment by fac42** [comment]
Just noticed that PR #1446 will fix this issue, please close this issue if the PR is accepted!

**Comment by kmcb777** [comment]
Hi @fac42 yes i remembered you asked for this on slack, and there was no reason not to allow it, now i have an issue number to put on that pr 👍

**Comment by kmcb777** [comment]
Hi @fac42 , this feature has been included in the new 4.3 release, feel free to try it out !
