### ISSUE TITLE
Inlining styles makes all elements inside mj-raw tags lowercase

### ISSUE THREAD

**Issue by wdonnell** [mjmlio/mjml#1450]
**Describe the bug**
When using `<mj-style inline="inline">` all html elements inside `<mj-raw>` and `<mj-table>` have their tag names and parameters set to lowercase, even if they aren't related to the css selectors. 

My intended workflow is using MJML to render a freemarker template, which our application can process to dynamically generate unique emails.  The freemarker tags include references to variables, so casing is important.

**To Reproduce**
1. Render the following MJML using the cli application, or the try-it-live editor:
```
<mjml>
   <mj-head>
    <mj-style inline="inline">
      .myClass{
        background: red;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-raw>
      <#if someCheckHere()>
        <p class="myClass">${someValueHere}</p>
      </#if>
    </mj-raw>
  </mj-body>
</mjml>
```

**Expected behavior**
Body output is:
```
<body>
  <div style="">
    <#if someCheckHere()>
      <p class="myClass" style="background: red;>${someValueHere}</p>
    </#if>
  </div>
</body>
```
Ideally, the styles would be inlined with the `<p>` tag and the unrelated `<#if>` would remain unchanged.  Or, since it's inside an  mj-raw tag, everything including the `<p>` would remain untouched.

**Actual behavior**
Body output is:
```
<body>
  <div style="">
    <#if somecheckhere()="">
      <p class="myClass" style="background: red;">${someValueHere}</p>
    </#if>
  </div>
</body>
```
The style is applied, but the `<#if>` tag's attribute `somecheckhere` is lowercased

**MJML environment (please complete the following information):**
- MacOS Mojave
- mjml-core: 4.2.1
- mjml-cli: 4.2.1

**Comment by iRyusa** [comment]
Might be related to `juice` rather than mjml here, @kmcb777 can you check there's an option on `juice` side ?

**Comment by iRyusa** [comment]
And I haven't seen that it has been converted to `<#if somecheckhere()="">`. There's a really low change that we'll be able to do anything on that part (even juice)  because it's a parser issue with htmlparser :/

Thanks for reporting this @wdonnell with an example 👍

**Comment by wdonnell** [comment]
Your comments set me on the right track.  `juice` has a configuration option called [codeBlocks](https://github.com/Automattic/juice#juicecodeblocks) that let you specify which tags you want ignored when inlining css.  It includes a couple defaults.  I was able to get this working by editing the source in `juice/lib/cheerio.js` and adding in the freemarker tags:

```
module.exports.codeBlocks = {
  EJS: { start: "<%", end: "%>" },
  HBS: { start: "{{", end: "}}" },
  freeMarker: { start: "<#", end: "</#" }
};
```

Exposing this configuration as a parameter would be a more permanent solution.

**Comment by iRyusa** [comment]
Maybe open a PR on juice side so we can update juice version for the next release ?
