### ISSUE TITLE
config.minify does not minify css inside the style tag

### ISSUE THREAD

**Issue by muuvmuuv** [mjmlio/mjml#1459]
**Describe the bug**

When I run `node_modules/.bin/mjml -i -s --config.minify true --config.minifyOptions='{"minifyCSS": true, "removeEmptyAttributes": true }' --config.beautify false` everything is minified except the CSS inside the style tags. Is this the correct behaviour?

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a file with this MJML code: https://hastebin.com/yiqajojasu.xml
2. Render it to HTML by doing `node_modules/.bin/mjml -i -s --config.minify true --config.minifyOptions='{"minifyCSS": true, "removeEmptyAttributes": true }' --config.beautify false`

**Expected behavior**

Everything is minified.

**MJML environment (please complete the following information):**
 - OS: macOS 10.14.1
 - mjml-core: 4.2.1
 - mjml-cli: 4.2.1

**Comment by iRyusa** [comment]
Hi,

As mentioned here : https://github.com/mjmlio/mjml/issues/1405 it was intended, and we're now providing an option for those who wants to enhance minifier options https://github.com/mjmlio/mjml/tree/master/packages/mjml-cli#change-minify-options

**Comment by muuvmuuv** [comment]
Ah yeah I was not aware of this thread. I found it by myself I got a error `Failed to decode JSON for config.minifyOptions argument` because I passed the object to the CLI wrong (I'm working with python)
