### ISSUE TITLE
Typo in `addHeadStyle`

### ISSUE THREAD

**Issue by malonehedges** [mjmlio/mjml#1466]
See https://github.com/mjmlio/mjml/blob/804760ad2ff9afcb14e903404900671b6978e3b9/packages/mjml-core/src/index.js#L208-L212

**Comment by kmcb777** [comment]
Hi @malonehedges thanks for noticing this, for now it's used with the same typo so it's ok but we should change that to prevent any mistake in the future 👍

**Comment by iRyusa** [comment]
cc @kmcb777 can we fix this in 4.4 it's a bit annoying to have this typo in our current component API

**Comment by kmcb777** [comment]
Actually the fix had been merged in 4.4beta, so i'll close this one 👍
