### ISSUE TITLE
Fallback Font on Outlook 2010 - 2013 doesn't work

### ISSUE THREAD

**Issue by user-12** [mjmlio/mjml#1467]
**Describe the bug**
Through Outlook 2010 & 2013, default fallback fonts like Arial or Verdana aren’t taking into account. Instead, Times New Roman is used.

**Initial State**
```
<mj-head>
    <mj-font name="Montserrat" href="https://fonts.googleapis.com/css?family=Montserrat" />
    <mj-attributes>
      <mj-all font-family="Montserrat,Verdana" font-size="14px" color="#000" align="justify" `/>`
</mj-attributes>
```

**Outcome**
OUTLOOK 2010 : Times New Roman
![image](https://user-images.githubusercontent.com/6585723/50451127-6f30e180-0932-11e9-8d4a-e9bd6e2c0f27.png)

GMAIL WEBMAIL : Verdana
![image](https://user-images.githubusercontent.com/6585723/50451141-7fe15780-0932-11e9-9078-9803d3a9d48d.png)

**Expected behavior**
Verdana to be used through Outlook.

**MJML environment:**
 - OS: Window
 - MJML Version  : v4.2.1
 - MJML tool used : MJML For Visual Studio Code https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml 

**Email sending environment(for rendering issues)**:
 - Platform used to send the email:  DOLIST

**attempts & workarounds**
I tried several actions 
 Create a dedicated CSS class
 `   <mj-class name="test" font-familly="Montserrat,Verdana"/>`
or adding conditional comments like that 
``
but it seems that it’s not OK

Thanks for all of the help.

**Comment by iRyusa** [comment]
Hi,

It works just fine for me on EOA for any Outlook with this MJML : https://mjml.io/try-it-live/ByNg62hZ4 

![image](https://user-images.githubusercontent.com/570317/50685310-f9570500-1018-11e9-8d9c-3ad52148bef0.png)

So I think your ESP is altering the HTML and there's not much we can do about it

**Comment by user-12** [comment]
Hello iRyusa,

Thank you very much for your feedback. In this case, does it mean that I cannot use Google Font for major modern webmails and use default fallback fonts like Arial or Verdana for Outlook ? 

Is your solution https://mjml.io/try-it-live/ByNg62hZ4 rendering Monteserrat on GMAIL app mobile for example and Verdana through Outlook?

**Comment by user-12** [comment]
OK. But is it possible to make a MJML code that allows Google font for modern Webmail or App and default fallback like Arial for Outlook ?

For example, this code : https://mjml.io/try-it-live/r13haxTbE is displaying Arial both on OUTLOOK and GMAIL Mobile App.

OUTLOOK 2010
![image](https://user-images.githubusercontent.com/6585723/50696286-536ac100-103f-11e9-8a18-ba05b85bc7a3.png)

GMAIL mobile APP :+1: 
![image](https://user-images.githubusercontent.com/6585723/50696353-7ac18e00-103f-11e9-9b1b-8b56eec78607.png)

**Comment by iRyusa** [comment]
> Gmail (web) doesn't support external font, so does Gmail App I think.

So basically there's no way to import any font inside gmail app. Most of webmail doesn't support external font, you can try this example on iOS it should work just fine
