### ISSUE TITLE
CLI watch option not working

### ISSUE THREAD

**Issue by andreavaghi** [mjmlio/mjml#147]
Hi,
i've just installed mjml and trying to build my first email template.
using the CLI with -r option is working fine, but when i try to use the -w option this is the error that i get

mac osx 10.11.3
mjml 1.3.1
node 5.8.0
npm 3.7.3

![screen shot 2016-03-22 at 12 09 36](https://cloud.githubusercontent.com/assets/639934/13949740/02575cfa-f027-11e5-94d2-4cda2c656ddd.png)

**Comment by janus-reith** [comment]
Maybe you miss some dependency?
You could installing with npm

**Comment by andreavaghi** [comment]
doesn't `npm -g` already install all package dependencies?

**Comment by sergiubutnarasu** [comment]
Same problem

**Comment by dominiquedutra** [comment]
Same problem here.

Windows
nodejs v5.9.0
npm 3.7.3
mjml 1.3.1

**Comment by GuillaumeBadi** [comment]
Sorry guys, refactoring issue, should be fixed with this: https://github.com/mjmlio/mjml/pull/148

I am updating the package in a minute

**Comment by dominiquedutra** [comment]
@GuillaumeBadi Not a problem. Thanks for the team's efforts and  congrats for  MJML. Mailjet is a great product and so is MJML.

**Comment by GuillaumeBadi** [comment]
Thanks for the comment :+1: 

Can you make sure it works on your side ? https://www.npmjs.com/package/mjml ?
mjml 1.3.2 is now published! 

Guillaume

**Comment by sergiubutnarasu** [comment]
@GuillaumeBadi I just tested and works. Thank you!

**Comment by dominiquedutra** [comment]
@GuillaumeBadi It works. Thanks.

**Comment by andreavaghi** [comment]
It works! 
Thanks
