### ISSUE TITLE
style tag breaks convertkit

### ISSUE THREAD

**Issue by geddski** [mjmlio/mjml#1473]
**Describe the bug**
The default MJML output creates a style tag in the head. This creates a problem for anyone like me who uses Convertkit to send emails. Like many email sending platforms, they don't support style tags, only inline styles.

**To Reproduce**
1. Create a file with this MJML code:

 ```<mjml>
  <mj-body background-color="#ffffff" width="100%">
    <mj-section>
      <mj-column>

        <mj-text>
          testing MJML output
        </mj-text>

      </mj-column>
    </mj-section>

  </mj-body>
</mjml>
```

2. Render it to HTML by using the Copy HTML command in VS Code
3. Save the HTML output in Convertkit
4. See style tag as text

**Expected behavior**
No styles at all in the head. 

**MJML environment (please complete the following information):**
 - OS: macOS
 - MJML Version 4.2.0
 - MJML tool used: VS Code plugin (https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml)

**Email sending environment(for rendering issues)**:
[Convertkit](https://convertkit.com)  

**Affected email clients (for rendering issues):**
all

**Screenshots**
MJML's styles get rendered in the email:
![image](https://user-images.githubusercontent.com/515722/50661949-f947fe00-0f61-11e9-88a0-d2ebe1d49e27.png)

**Comment by iRyusa** [comment]
Hi

Head styles are widely supported across email clients. If your esp doesn’t support it, it’s not our fault.

I suggest you to contact them instead.

**Comment by geddski** [comment]
Dang, I have :( They said pretty much the same thing, pointing me here. 

What if we added an option to the compilation step, to optionally remove the external styles?

**Comment by iRyusa** [comment]
You will have only a mobile version then, so no real point of using mjml.

**Comment by ngarnier** [comment]
That statement is actually not a fact as most sending platforms don't alter their customers' HTML (fortunately).
> Like many email sending platforms, they don't support style tags, only inline styles.

It's pretty wrong for an ESP to break their customers' HTML and definitely something they should stop doing. One MJML user [got Intercom to stop doing that](https://github.com/mjmlio/mjml/issues/702#issuecomment-403798823), so maybe you'll get lucky too if you insist.

As @iRyusa said, we can't do much about the bad practices of some third-party platform so I'll close that issue.

**Comment by geddski** [comment]
It sounds like ConvertKit has a separate place for CSS. So my question: are the MJML styles in the head the exact same every time? If so I could put that in their template spot once and just strip it out in my build.

**Comment by kmcb777** [comment]
@geddski no it's not always the same, depending on the components you're using. Some components will add style to the head if they're used in the template.

**Comment by geddski** [comment]
ConvertKit has given me access to their new editor beta, and so far it seems compatible with MJML. I'll keep anyone here interested up to date.

**Comment by geddski** [comment]
Also it turns out the source of the problem is the editor library they were using: https://imperavi.com/redactor/

**Comment by harrydry2** [comment]
Hi @geddski did you ever fix this? I can't seem to get MJML working with Convert Kit atm

**Comment by geddski** [comment]
@harrydry2 yes it works now with Convertkit's new editor, currently in beta.
