### ISSUE TITLE
Landing Page - Entire Background

### ISSUE THREAD

**Issue by FasterThanGoogle** [mjmlio/mjml#1474]
**Describe the bug**
I'm creating a landing page and have a CSS gradient that I would like to use for the background. However, I would like it to fill the entire size of the web browser, not just what is defined as a section (or body) so that it fills the entire background regardless of the resolution, is this possible right now?

**MJML environment (please complete the following information):**
 - OS: Windows 10 Pro
 - MJML Version - 4.1.2
 - MJML tool used - Website

**Comment by iRyusa** [comment]
Well first, MJML is not suited to build a webpage. You can use a full-size mj-wrapper to achieve that with a background.

But, please, don't use MJML for building a webpage, the HTML will be bloated with non necessary stuff required for email clients.
