### ISSUE TITLE
Preserve newlines in generated HTML

### ISSUE THREAD

**Issue by RobWalker** [mjmlio/mjml#1478]
**Is your feature request related to a problem? Please describe.**
I have an mj-text element I want to apply a class with "white-space: preserve" to, but the generated html does not preserve whitespace present in the input mjml

```
<mj-text>hello
world</mj-text>
```

Produces
```
<div>hello world</div>
```

**Describe the solution you'd like**
Ideally all white space in the input should be preserved ... is there a downside to this?

Or an attribute on mj-text to enable this behaviour.

**Describe alternatives you've considered**
Can't find a way to achieve this currently

**Comment by iRyusa** [comment]
Might be a parser issue 🤔 

Can you look a bit on this @kmcb777 if we still have the whitespace in the json ?

**Comment by tkafka** [comment]
It seems that 4.3.0 is a first version that preserves whitespace - I save rendered templates in versioning system and with mjml upgrade I saw all the newlines in resulting html.

**Comment by RobWalker** [comment]
Thanks, I upgraded to 4.3.1 but didn't see a change, but on digging further found that the test code was passing { beautify: true } into mjml2html

Removing this attribute fixed the desired output and all looks good now!
