### ISSUE TITLE
Alt text hidden in most email clients

### ISSUE THREAD

**Issue by Zelltron** [mjmlio/mjml#1479]
**Describe the bug**
Mj-image is inheriting a parent font-size of 0 from mj-section by default. This reduces the font-size of alt text in unloaded/broken images. Alt text is hidden in most email clients. 

**To Reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="center" color="#555" />
      <mj-section background-color="#fff" />
    </mj-attributes>
  </mj-head>
  <mj-body background-color="#eee">
    <mj-section>
    <mj-column>
        <mj-image width="200px" src="http://placehold" alt="testing"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
2. Render it to HTML by doing either...
- ` $ mjml --watch input.mjml --output index.html`
- Generate the HTML through a native app 
- The MJML online editor

3. Send the HTML to an email address with gmail, apple mail, or yahoo mail

**Expected behavior**
The image alternate text displays over blocked image.

**MJML environment (please complete the following information):**
 - OS: Sierra 10.12.6 
 - MJML Version 4.3.0
 - MJML Node Module

**Email sending environment(for rendering issues)**:
 - Litmus

**Affected email clients (for rendering issues):**
 - Emails: Client Gmail, Yahoo, Apple Mail
 - OS: Windows/Apple
 - Browsers: Chrome & Firefox

**Comment by iRyusa** [comment]
Well it can be styled through mj-style inline & some css selector, but you're right we should expose mj attributes like font-size/color on mj-image

**Comment by Zelltron** [comment]
This worked, but I had to use `!important` on font-size to view the alt text.

**Comment by iRyusa** [comment]
This has been merged for a while now :D
