### ISSUE TITLE
MJ-Group not working outlook desktop

### ISSUE THREAD

**Issue by K05M0NAUT** [mjmlio/mjml#1481]
Hello, I hope this is the proper place to put this. I may be misunderstanding the way the groups work or maybe it isn't fully supported in Outlook. I have created in my footer of my email a pair of social media icons. In order to make them close in proximity I have made two columns, one with an image aligned to the left and another with the image aligned to the right. I then have nested them within a group so that they do not stack. They work well except in Outlook's desktop application where they stack and then my left and right aligned images end up on opposite ends of the pages. If this is the expected behavior can someone recommend a solution other than this to getting two objects side by side in the center of the email?

I have attached the MJML link here.
https://mjml.io/try-it-live/HykzQfbGE

**Comment by iRyusa** [comment]
Hi,

It should works fine, can you tell us a bit how did you send your email to
test ? And which outlook version, mjml version, and a screenshot ? It seems
that both of your images are broken too.

**Comment by K05M0NAUT** [comment]
I have attatched some screenshots of what I am running into.

https://imgur.com/a/Nrvnpyb

**Comment by K05M0NAUT** [comment]
I am using the web based editor which it says is  using MJML 4.2.1. Also I have tried just restarting from scratch and trying a slightly different layout but I still get the same issue. Here is my second attempt here.

https://mjml.io/try-it-live/HyC2ccXfN

**Comment by ngarnier** [comment]
Most importantly:
> how did you send your email to test

**Comment by K05M0NAUT** [comment]
I used Agile CRM which has the option to paste HTML into the email. I sent it to someone I work with who has a windows machine. I would be happy to send you an email from the CRM if you would like.

**Comment by ngarnier** [comment]
That's likely the issue then, Agile CRM must alter the HTML and break it. Try sending with https://putsmail.com/.

PS: like @iRyusa said, both your images inside the group are broken/unaccessible.

**Comment by ngarnier** [comment]
Seems putsmail has some issues lately, try with https://sendtest.email/. 

As a matter of fact, they are.
> Also for the time being I have put the two social icons as random icons from google so there shouldn't be any issues with them being unaccessible.

**Comment by K05M0NAUT** [comment]
I sent the email though sendtest.email and it works much better. I guess it is a problem with our CRM and I will have to see if there is any way they can fix it. Thank you so much for your help! I think what you are doing is really helpful and I plan to use MJML as much as I can.
