### ISSUE TITLE
<mj-raw> left in output

### ISSUE THREAD

**Issue by dschach1** [mjmlio/mjml#1482]
**Describe the bug**
Using <mj-raw> to wrap handlebars expressions,  the <mj:raw> elements are sometimes left in the output.

**To Reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-body>
    <mj-section>
        <mj-column>
          <mj-text>
            <mj-raw>{{Test}}</mj-raw>
          </mj-text>
        </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
2. Render it to HTML using https://mjml.io/try-it-live
3. Examine the rendered html.  The <mj:raw>{{Test}}</mj:raw> is in the output html.

**Expected behavior**
{{Test}} should not be wrapped.

**MJML environment (please complete the following information):**
 - MJML Version 4.1.2
 - MJML tool used [e.g MJML App] try-it-live

**Comment by ngarnier** [comment]
That's because you placed it inside `mj-text` while it's not needed (`mj-text` just prints your content without parsing it).

Remove the unneeded `mj-raw`: 
```
<mjml>
  <mj-body>
    <mj-section>
        <mj-column>
          <mj-text>
            {{Test}}
          </mj-text>
        </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
