### ISSUE TITLE
Display two mjml components inline

### ISSUE THREAD

**Issue by samarthmaniar** [mjmlio/mjml#1486]
I am trying to align two mjml components (e.g. a text component and a button component) inline by putting them in a group with a single column but no success yet.

Is there a way I can do this? I know this can be achieved using `mjml-table` with raw html tags for text and button but I have a system requirement to use standard components only. 

Here is an example snippet of what I tried.

```
<mjml>
  <mj-head>
    <mj-style>
      .bodyText { display: inline; width: 100%; }
      .bodyLink { display: inline-block; width: 100%; padding: 0px 0px !important; inner-padding: 0px 0px !important; }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column>
          <mj-text align="center" css-class="bodyText">
            Text
          </mj-text>
          <mj-button font-family="Helvetica" background-color="#fff" color="black" css-class="bodyLink">
            Link
          </mj-button>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by ngarnier** [comment]
You simply need to use columns to have them side by side, like in this snippet: https://mjml.io/try-it-live/H1F310YfE.

Your group is useless with one columns, the point of `mj-group` is to keep columns side by side on mobile instead of having them stack (so you need at least 2 columns).

**Comment by sapsonic** [comment]
I'm facing the same issue and did exactly what @ngarnier mentioned above. However—as you can see from @ngarnier's link (and attached screenshot)—they aren't exactly in-line: the two columns have text in them, but they are one below the other (in two separate rows).  I'm trying to get both the text (or image+text, as the case may be) into the same line next to each other.  What am I doing wrong?
![Screenshot 2019-11-07 at 10 52 19 PM](https://user-images.githubusercontent.com/43087642/68399655-b2461d00-01b1-11ea-9301-e504cd69ea00.png)

**Comment by iRyusa** [comment]
Both have simply different paddings (+ button has outer padding + inner padding). You can also use vertical-align for that https://mjml.io/try-it-live/HJDqUhWjr

**Comment by sapsonic** [comment]
Oh, yes! The vertical-align fixed that.  Thanks for the lightning-fast response!
