### ISSUE TITLE
Can't use components on MJMLApp

### ISSUE THREAD

**Issue by totanus** [mjmlio/mjml#1488]
I downloaded and built the component-boilerplate, following the tutorial instructions but, when I try to browse the index.mjml code on the MJMLApp version I get some error tooltips stating that the custom components either don't exist or aren't registered.

<img width="1662" alt="schermata 2019-01-15 alle 15 23 23" src="https://user-images.githubusercontent.com/57438/51186300-9cd9cc80-18d9-11e9-8a69-dd1ee634bda8.png">

Is there something I'm missing?
Thank you in advance for helping me.

Matteo

**Comment by kmcb777** [comment]
Hi @totanus indeed the custom components can't be used on the app yet, there is an open PR on the app to allow them but we need to rework it accordingly to the latest mjml changes

**Comment by dschach1** [comment]
There is a work around.  Custom components load in mjmlapp if you start the mjmlapp from the folder that defines the components.

**Comment by iRyusa** [comment]
Hi, closing because it's the wrong repo 👌
