### ISSUE TITLE
Set different paddings to mj-section for mobile

### ISSUE THREAD

**Issue by totanus** [mjmlio/mjml#1489]
Is it possible to target `mj-section` in order to change the padding size depending on the breakpoint?
I'm thinking to use a mediaquery inside a `mj-style` block but I'm not sure how to target the proper element.
Thank you in advance.
Matteo

**Comment by dalefish** [comment]
Use dev tool to determine the selector.

To apply the class to target you can use css-class on the section(s)
required.

There is no built-in method.
