### ISSUE TITLE
Overriding the default fonts so that Ubuntu is never rendered

### ISSUE THREAD

**Issue by muxica** [mjmlio/mjml#149]
Hi, I'm most likely missing something but I was wondering how to override the default fonts so that I am not stuck with Ubuntu. I'm hoping to use Roboto.

**Comment by arnaudbreton** [comment]
Hi @muxica, thanks for sharing!

We made a design proposition in #80 about this use-case. Please have a look at it and feel free to comment with your feedback there.

**Comment by arnaudbreton** [comment]
@muxica actually, you can already use Roboto, using the `font-family` attribute [see the doc](https://mjml.io/documentation/#mj-text). Based on that #80 will be useful for you only if you need non supported fonts.
