### ISSUE TITLE
mj-button ignores align attribute

### ISSUE THREAD

**Issue by dschach1** [mjmlio/mjml#1490]
The code for mj-button always generates a td with align='center'

See https://github.com/mjmlio/mjml/blob/master/packages/mjml-button/src/index.js#L110

The button defines an align attribute at https://github.com/mjmlio/mjml/blob/master/packages/mjml-button/src/index.js#L7

but it is never used.

**To Reproduce**
1. Create a file with this MJML code: 
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-button align="left" text-align="left" padding="0px 0px 0px 0px">hello</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
2. Render it to HTML using https://mjml.io/try-it-live
3. Inspect the code

**Expected behavior**
Setting align to left would override the align="center"

**Comment by iRyusa** [comment]
`align` is used on column's renderChildren see : https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L235

So, it is used at the wrapper level, not directly. But there's no way in the current component api to add a set of attributes to it's children (padding works the same basically)

**Comment by dschach1** [comment]
OK. I see it's used at the column level.  My concern is having any attributes in mjml components that can't be overridden. Just as there is inner-padding maybe there should be an inner-align.

**Comment by iRyusa** [comment]
There’s text-align for that already

**Comment by caseyjhol** [comment]
@iRyusa Setting `text-align` on an `mj-button` element doesn't appear to actually do anything. Looking at the source for the mjml-button component, there is no reference to `text-align`.

**Comment by caseyjhol** [comment]
Ah - sorry about that. I was using mjml-component-boilerplate and didn't realize it comes with a very outdated version of MJML.
