### ISSUE TITLE
ico-align doesnt work

### ISSUE THREAD

**Issue by Alainvdz99** [mjmlio/mjml#1495]
Hi,

I am trying to make a hamburger navbar but it seems like the ico-align doesnt work. I am trying to get the hamburger icon to the right op the email while the text keep staying in the middle of the email. Is this a bug or am i doing something wrong? 
``` <mj-section full-width="full-width" css-class="header-background">
    <mj-column>
        <mj-navbar hamburger="hamburger" ico-align="right">
          <mj-navbar-link text-transform="none" padding="10px 20px" color="#8b9091" font-size="14px" href="">Zwembaden</mj-navbar-link>
          <mj-navbar-link text-transform="none" padding="10px 20px" color="#8b9091" font-size="14px" href="">Vijvers</mj-navbar-link>
          <mj-navbar-link text-transform="none" padding="10px 20px" color="#8b9091" font-size="14px" href="">Tuinrobots</mj-navbar-link>
          <mj-navbar-link text-transform="none" padding="10px 20px" color="#8b9091" font-size="14px" href="">Actie!</mj-navbar-link>
        </mj-navbar>
    </mj-column>
</mj-section>

**Comment by kmcb777** [comment]
Hi @Alainvdz99, thanks for reporting this, it's seems like there is indeed an issue, align is passed as style attribute instead of html attribute.
We'll fix this in the next release, for now the only workaround would be to edit the generated html, and add the `align="right"` attribute instead of the `align:right;` in the style attribute

**Comment by Alainvdz99** [comment]
Thank you for your fast response @kmcb777 ! We are also trying to get some text in the center next to the hamburger icon. I have tried to do this with `<mj-text>` in the same section as the navbar but this will make the text above the icon.  Here is an example on what we trying to get:
<img width="523" alt="schermafbeelding 2019-01-21 om 10 45 26" src="https://user-images.githubusercontent.com/37347746/51483113-95626980-1d98-11e9-8089-5ceb9d50d384.png">
Any idea on how to get the text next to the hamburger icon?

**Comment by kmcb777** [comment]
@Alainvdz99 yes, you can actually replace the hamburger icon with some html, using the attributes `ico-open` and `ico-close`. So if you want to add 'My title', you can do something like this :
```
<mj-navbar 
    ico-open='<span style="margin-right:20px;">My title</span><span>&#9776;</span>'
    ico-close='<span style="margin-right:20px;">My title</span><span>&#8855;</span>' >```
Note that in will only work in recent mjml versions, until recently this html was altered, so it won't work on the try-it-live.

**Comment by Alainvdz99** [comment]
@kmcb777 Thanks a lot! it works perfectly fine right now :)
