### ISSUE TITLE
Full-width row

### ISSUE THREAD

**Issue by selrond** [mjmlio/mjml#150]
I suggest adding a full-width row, so we'll be able to align text e.g. to the left edge of the viewport. Usage example - responsive e-mail signature

**Comment by Tlapi** [comment]
Hi @selrond You can use `full-width` on `mj-section`

**Comment by selrond** [comment]
Yeah I see, but I need the text to be aligned to the left of the viewport, now it is still centered.  Basically - I need to be able to align the columns (or the the centered container that contains them) to the left

**Comment by arnaudbreton** [comment]
@selrond sorry for the slow answer here. If I understand well, you don't want the main container to be centered, is that right? If yes, I'm afraid it's not possible at the moment with our current HTML layout.

What are you trying to achieve here?

Thanks for the feedback

**Comment by selrond** [comment]
To use it for email signature for instance - where you need to have everything left-aligned maybe in some full-width container

**Comment by mattpirelli** [comment]
@selrond did you manage to solve this?
I'm in the same exact situation right now and it's driving me mad

**Comment by selrond** [comment]
@mattpirelli I kinda did — I hand–coded it 😛  
I used this https://html-online.com/editor/ + stackexchange

**Comment by mattpirelli** [comment]
@selrond same here.

Thinking about it, it's understandable that this is not a "feature", since ours is a bit of a fringe case.

I may or may not end up coding a custom component for that.

**Comment by iRyusa** [comment]
I believe you'll need to write your own custom component for that, I think this is out of the spec from what MJML try to achieve. 
Here's how to start : https://mjml.io/documentation/#create-a-component Feel free to share it with us, we may add it to the main README !

**Comment by selrond** [comment]
@mattpirelli Oh and I forgot one great tool: Premailer: http://premailer.dialect.ca/ which is a great tool! Definitely check that out
