### ISSUE TITLE
Columns not stacked in older outlook versions

### ISSUE THREAD

**Issue by marcel-devdude** [mjmlio/mjml#1503]
Columns in older Outlook versions are not staked:

![cleanshot 2019-01-30 at 10 52 03](https://user-images.githubusercontent.com/1384371/51975861-9e7fc480-2483-11e9-862e-9e7cd6b74ca8.png)

In newer versions and other clients all columns are stacked:

![cleanshot 2019-01-30 at 10 51 41](https://user-images.githubusercontent.com/1384371/51975845-91fb6c00-2483-11e9-8593-28a240d0f90c.png)

We have a template with multiple `mj-column`s with 100% width:

```
<mjml>
  <mj-body>
     <mj-container>
       <mj-wrapper>
         <mj-section>
            <mj-column width="100%">
              ...
            </mj-column>
            <mj-column width="100%">
              ...
            </mj-column>
         </mj-section>
       </mj-wrapper>
     </mj-container>
  </mj-body>
</mjml>
```
The `mj-column` add some conditional comments for outlook (IE). 

![cleanshot 2019-01-30 at 11 33 06](https://user-images.githubusercontent.com/1384371/51975831-87d96d80-2483-11e9-94f2-f485fe67f3c2.png)

Every `mj-column` is wrapped in an additional `td` with `witdh=660px` (dont know where the 660px comes from). I think if there were a closing `tr` after each `mj-column` in the conditional comment, we get the expected behaviour. Is it possible to add the closing `tr`?

 - OS: MacOS
 - MJML Version: 4.3.1

**Comment by iRyusa** [comment]
Hi,

You can't have more than 100% of content in a section, that's why it behave like that.
