### ISSUE TITLE
Email header text

### ISSUE THREAD

**Issue by slavino** [mjmlio/mjml#1504]
**Is your feature request related to a problem? Please describe.**
Email preview in Inbox might benefit from an information available in a invisible section. Inspiration from here: https://raw.githubusercontent.com/TedGoas/Cerberus/master/cerberus-responsive.html

        <div style="display: none; font-size: 1px; line-height: 1px; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;">
            (Optional) This text will appear in the inbox preview, but not the email body. It can be used to supplement the email subject line or even summarize the email's contents. Extended text preheaders (~490 characters) seems like a better UX for anyone using a screenreader or voice-command apps like Siri to dictate the contents of an email. If this text is not included, email clients will automatically populate it using the text (including image alt text) at the start of the email's body.
        </div>

**Describe the solution you'd like**
tag for hidden text & support for UX

**Comment by ngarnier** [comment]
Hey @slavino, if I understood your need correctly, it's already available here: https://mjml.io/documentation/#mjml-preview
