### ISSUE TITLE
Not able to set border-radius together with border

### ISSUE THREAD

**Issue by apfelbox** [mjmlio/mjml#1510]
**Describe the bug**
As `border-radius` and `border` are set on different elements, there are rendering issues.

**To Reproduce**
1. Go to https://mjml.io/try-it-live
2. Paste the code below

```mjml
<mjml>
  <mj-body>
    <mj-section background-color="#0F0" border="1px solid black" border-radius="20px">
      <mj-column>
        <mj-text>Ohai</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
The border should follow the border-radius and not produce a box around it.

**MJML environment (please complete the following information):**
 - OS: macOS 10.14.2
 - MJML Version: npm mjml@4.3.1 + web REPL
 - MJML tool used: both npm package + web REPL

**Email sending environment(for rendering issues)**:
doesn't apply

**Affected email clients (for rendering issues):**
doesn't apply

**Screenshots**

![2019-02-11 at 09 59](https://user-images.githubusercontent.com/1032411/52553411-ac1e3e00-2de3-11e9-934f-9db1e1b2707c.png)

**Additional context**
—

**Comment by apfelbox** [comment]
Please note: this issue appears if you set it on `mj-section` or `mj-column`, it doesn't make a difference.

**Comment by kmcb777** [comment]
Hi @apfelbox it's actually intended, because of some email clients ignoring border/border-radius on some tags, we have to set the border and the border-radius on two different elements.
You can try removing the `border-collapse: collapse` as said here https://github.com/mjmlio/mjml/issues/1104 but there will be inconsistencies between clients

**Comment by ikotun-dev** [comment]
@kmcb777 , Im having this issue right now. 
```
 <mj-column width="100" border="1px solid black" border-radius="10px" padding="">
              <mj-image src="https://res.cloudinary.com/..................url"></mj-image>

            </mj-column>
```

What do you mean by getting rid of the border-collapse?
