### ISSUE TITLE
Global font settings don't seem to work

### ISSUE THREAD

**Issue by apfelbox** [mjmlio/mjml#1511]
**Describe the bug**
I try to globally set the font + the font-size of my mail but it doesn't seem to work.

**To Reproduce**
1. Open the web REPL
2. Paste the following code snippet
3. Inspect the text "Hello World2"

```mjml
<mjml>
    <mj-attributes>
        <mj-text font-family="Arial" color="#3A4759" font-size="22px" />
        <mj-section padding="0" />
        <mj-all font-family="Arial" color="#3A4759" font-size="22px" />
    </mj-attributes>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text color="#F45E43">Hello World2</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
I expected that all texts that have no explicit override would have these settings.
(But maybe I am just using the wrong configuration?)

**MJML environment (please complete the following information):**
 - OS: macOS 10.14.2
 - MJML Version: npm mjml@4.3.1 + web REPL
 - MJML tool used: both npm package + web REPL

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]: local SMTP

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail]: I guess all of them? I tested it in the browser, but as the wrong values are set inline, it should be wrong in all of them

**Screenshots**
![2019-02-11 at 10 24](https://user-images.githubusercontent.com/1032411/52554506-56e42b80-2de7-11e9-8287-665e33102afb.png)

**Additional context**
Maybe I just use the wrong setting here. Would be happy if somebody could confirm whether this is an actual bug or if I am just doing something wrong.

**Comment by iRyusa** [comment]
Hi,

You forgot `mj-head` in your snippet, that's why it doesn't work.

**Comment by apfelbox** [comment]
@iRyusa 

🤦‍♂️ of course.
Thank you!
