### ISSUE TITLE
Gifs in the new Outlook updates don't support the 'auto' height anymore.

### ISSUE THREAD

**Issue by CreativeZombie** [mjmlio/mjml#1513]
So Outlook rolled it's latest update, that included having animated gifs! This is awesome however, now gifs don't respect 'height="auto"' as they once did (side note: I'm using x2 scale images for retina screens).  :/

I've also gone through all my previous MJML based email tests in Outlook and they have all been affected. 

Has anyone else noticed this? I would assume the fix would be just set an exact height but surely that would then mess up the gif across the board? 

Cheers,

**Comment by iRyusa** [comment]
Hi @CreativeZombie 
New Outlook new bugs 😢 We'll check if there's anything we can do about this one

**Comment by CreativeZombie** [comment]
@iRyusa Oh don't we love 'em.  Thank you and I fully appreciate the help! 😄

**Comment by maxbln** [comment]
any updates here? :(  @iRyusa

**Comment by iRyusa** [comment]
Didn't find anything on why it happens.

**Comment by iRyusa** [comment]
Never found out a fix about this, if someone has potential fix for height = auto support feel free to post here i'll re-open
