### ISSUE TITLE
Background url image on column?

### ISSUE THREAD

**Issue by puyanwei** [mjmlio/mjml#1515]
Hi,

I would like to add a buttons to the middle of a row of images but having background-url and background-cover attributes are not allowed on mj-columns. Is this possible?

```
    <mj-section>
      <mj-column >
        <mj-image src="https://unsplash.it/300/300"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image src="https://unsplash.it/300/300"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image src="https://unsplash.it/300/300"></mj-image>
      </mj-column>
    </mj-section>
```

**Comment by iRyusa** [comment]
Hi,

As background image isn't really well supported, we limit it to the section & wrapper element only. If you want you can use mj-style to apply one, but a lot of client won't see it
