### ISSUE TITLE
Not rendering correctly on outlook anymore.

### ISSUE THREAD

**Issue by lRlevolution** [mjmlio/mjml#152]
I just recently updated to v1.3.3 and now the code doesn't render correctly for outlook on any browser. I tried using an old mjml code I used when it was rendering correctly but when I output the code it still doesnt show correctly. See new output ( http://awesomescreenshot.com/0f25qh5w6f ) and the old view for 2 days ago. ( http://awesomescreenshot.com/0905qh62fb ).

**Comment by lRlevolution** [comment]
`<mj-body background-color="#FFFFFF" width="600px">
 
  <mj-section padding-bottom="9" padding-top="9" background-color="#2092D6" color="white">
      <mj-column width="100%" vertical-align="middle">
          <mj-text align="center" color="white" font-family="Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="18" padding-left="25" padding-right="25" padding-bottom="0" padding-top="0">
            <span style="font-size: 18px; font-weight:700;">FREE SHIPPING</span><span style="font-size: 18px; font-weight:400;"> ON ALL ORDERS OVER $25</span>
          </mj-text>
      </mj-column>
  </mj-section>

 
  <mj-section background-color="#FFFFFF" >

 
    <mj-column width="180px" vertical-align="middle">
      <mj-image width="137px" src="https://d1s4gadwegul2m.cloudfront.net/pipeline/production/logo-hollar-6cb62359db5f61ba219b79425d932ce6abe1fb918e74ac8f7b2adbc1c01f4405.png" href="www.Hollar.com" alt="hollar logo"></mj-image>
    </mj-column>

 
    <mj-column width="70%" vertical-align="middle">
      <mj-text align="center" link-color="#595959" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" padding-bottom="0" padding-top="7" padding-left="0" padding-right="0" font-size="12px">
        <a href="https://www.hollar.com/t/category" style="text-decoration: none; color: #595959;">SHOP BY CATEGORY</a>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<a href="https://www.hollar.com/t/party" style="text-decoration: none; color: #595959;">SHOP BY PARTY</a>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<a href="https://www.hollar.com/t/gifts" style="text-decoration: none; color: #595959;">SHOP GIFTS</a>
      </mj-text>
    </mj-column>

  </mj-section>


<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

  
    <mj-image  padding-bottom="0px" padding-top="0px"  padding-left="0px" padding-right="0px"  src="http://hosting.fyleio.com/35647/public/newsletters/2016/2016-03-16_Melissa%20%26%20Doug/melissa_douglas.jpg" href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px" padding-left="25" padding-right="25" padding-bottom="10" padding-top="20">
        <p style="margin:3px 0 5px !important;">Remember your New Year’s fitness resolutions? Yeah, we thought so. Get moving with our stylish athleisure wear, resistance bands, and more fitness gear.</p>
      </mj-text>
      <mj-button background-color="#FF2509" color="white" font-size="16px" align="center" vertical-align="middle" border="none" padding="15px 30px" border-radius="3px" font-family="Helvetica, Arial, sans-serif" href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10" padding-top="10">
        SHOP NOW
      </mj-button>
    </mj-column>
  </mj-section>

  
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

    
    <mj-image  padding-bottom="0px" padding-top="30px"  padding-left="0px" padding-right="0px"  src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_19_Women%27s_Active/160316_Girls_Electro-Pod.jpg" href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#ce2576" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="27" line-height="30px" padding-left="25" padding-right="25" padding-bottom="0" padding-top="20">
        <p><span style="font-weight: normal;">Geek Chic</span></p>
      </mj-text>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px" padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p style="margin:3px 0 5px !important;">Tech Accessories with a Feminine Edge<br>
        <span style="font-weight:bold;">Starting at $2</span></p>
      </mj-text>
      <mj-button background-color="#ce2576" color="white" font-size="16px" align="center" vertical-align="middle" border="none" padding="15px 30px" border-radius="3px" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10" padding-top="10">
        SHOP NOW
      </mj-button>
    </mj-column>
  </mj-section>

  
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

    
    <mj-image  padding-bottom="0px" padding-top="30px"  padding-left="0px" padding-right="0px"  src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_19_Women%27s_Active/RAF_Sweep.jpg" href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#ee3129" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="27" line-height="30px" padding-left="25" padding-right="25" padding-bottom="0" padding-top="20">
        <p><span style="font-weight: normal;">Win a $100 Hollar Shopping Spree!</span></p>
      </mj-text>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px" padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p style="margin:3px 0 5px !important;">For a limited time only, share Hollar with friends for a chance to win a $100 shopping spree to Hollar*.<br>
Each invite = 1 entry.</p>
      </mj-text>
      <mj-button background-color="#ee3129" color="white" font-size="16px" align="center" vertical-align="middle" border="none" padding="15px 30px" border-radius="3px" font-family="Helvetica, Arial, sans-serif" href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10" padding-top="10">
        START SHARING
      </mj-button>
    </mj-column>
  </mj-section>

    
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

    
    <mj-image  padding-bottom="0px" padding-top="30px"  padding-left="0px" padding-right="0px"  src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_19_Women%27s_Active/journey2.gif" href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#2092D6" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="27" line-height="30px" padding-left="25" padding-right="25" padding-bottom="0" padding-top="20">
        <p><span style="font-weight: normal;">Press Play!</span></p>
      </mj-text>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px" padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p style="margin:3px 0 5px !important;">Get the inside look at our shipment process on our all-new blog.</p>
      </mj-text>
      <mj-button background-color="#2092D6" color="white" font-size="16px" align="center" vertical-align="middle" border="none" padding="15px 30px" border-radius="3px" font-family="Helvetica, Arial, sans-serif" href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10" padding-top="10">
        CHECK IT OUT
      </mj-button>
    </mj-column>
  </mj-section>

  
  <mj-section>
  <mj-column background-color="#FFFFFF">
 <mj-divider border-color="#cccccc" border-style="solid" border-width="1px" padding-bottom="0" padding-top="0"></mj-divider>
  </mj-column>
  </mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">
      <mj-text align="center" color="#000000" font-family="Helvetica, Arial, sans-serif" font-size="13" padding-left="25" padding-right="25" padding-bottom="0" padding-top="0">
        Download Our App
      </mj-text>
  </mj-column>
</mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF" width="107px">
      <mj-image  padding="7px" width="98px" src="http://hosting.fyleio.com/35647/public/newsletters/2016/2016_02_02_Emojis/email_emojis_160202_r1_21.png" href="www.#.com" alt=""></mj-image>
  </mj-column>
  <mj-column background-color="#FFFFFF" width="107px">
      <mj-image  padding="7px" width="98px" src="http://hosting.fyleio.com/35647/public/newsletters/2016/2016_02_02_Emojis/email_emojis_160202_r1_22.png" href="www.#.com" alt=""></mj-image>
  </mj-column>
</mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">
      <mj-text align="center" color="#000000" font-family="Helvetica, Arial, sans-serif" font-size="13" padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p>Join the Party on Social</p>
        <table width="185" cellspacing="0" cellpadding="0" border="0" align="center">

                              <tbody><tr>

                                <td width="37" align="center"><a target="_blank" href="http://facebook.com/shophollar"><img width="37" border="0" style="display:block;" alt="facebook.com/shophollar" src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-facebook.png" mc:edit="fac"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a target="_blank" href="http://instagram.com/hollar"><img width="37" border="0" style="display:block;" alt="Instagram: @hollar" src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-instagram.png" mc:edit="twit"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37"><a target="_blank" href="http://pinterest.com/hollar"><img width="37" border="0" style="display:block;" alt="pinterest.com/hollar" src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-pinterest.png" mc:edit="link"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a target="_blank" href="http://twitter.com/hollar"><img width="37" border="0" style="display:block;" alt="Twitter: @hollar" src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-twitter.png" mc:edit="pint"></a></td>
                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><img width="37" border="0" style="display:block;" alt="Snapchat: @hollarsnaps" src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-snapchat.png" mc:edit="pint"></td>

                              </tr>

                            </tbody></table>
      </mj-text>
  </mj-column>
</mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">
      <mj-text align="center" color="#808080" font-family="Helvetica, Arial, sans-serif" font-size="11" line-height="22px"padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p>*Limited time only. Invitations must be sent by March 20, 2016. Prize will be awarded as Hollar credit for the $100. No purchase or payment necessary to enter or to win. Odds depend on the number of eligible entries received. Must be U.S. resident, 18 years or older to enter. Qualifying invitations must be sent. See official rules for complete terms and conditions. </p>    
        <p>Free shipping offer is automatically applied at checkout on all first-time orders over $10. For subsequent orders over $25 pre-tax, free shipping will be applied at checkout. Offers valid on U.S. orders only.</p>
        <p>If you'd like to unsubscribe, click <a href="%%!unsubscribe_url%%" style="color:#808080; text-decoration:none;">here</a><br />
                        Copyright &copy; 2016 %%!account_organization%%. All rights reserved. <br>
                        %%!account_address1%% %%!account_address2%%, %%!account_city%%, %%!account_state%% %%!account_zip%%</p>
      </mj-text>
  </mj-column>
</mj-section>
  
</mj-body>`

**Comment by iRyusa** [comment]
Hi @lRlevolution !
Sorry to hear about that, can you show us a sample of your MJML ?

**Comment by lRlevolution** [comment]
Hi,

Code goes as followed:

<mj-body background-color="#FFFFFF" width="600px">
 
  <mj-section padding-bottom="9" padding-top="9" background-color="#00b259"
color="white">
      <mj-column width="100%" vertical-align="middle">
          <mj-text align="center" color="white" font-family="Gotham,
'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="18"
padding-left="25" padding-right="25" padding-bottom="0" padding-top="0">
            <span style="font-size: 18px; font-weight:700;">FREE
SHIPPING</span><span style="font-size: 18px; font-weight:400;"> ON ALL
ORDERS OVER $25</span>
          </mj-text>
      </mj-column>
  </mj-section>

 
  <mj-section background-color="#FFFFFF" >

 
    <mj-column width="180px" vertical-align="middle">
      <mj-image width="137px" src="
https://d1s4gadwegul2m.cloudfront.net/pipeline/production/logo-hollar-6cb62359db5f61ba219b79425d932ce6abe1fb918e74ac8f7b2adbc1c01f4405.png"
href="www.Hollar.com" alt="hollar"></mj-image>
    </mj-column>


    <mj-column width="70%" vertical-align="middle">
      <mj-text align="center" link-color="#595959" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" padding-bottom="0" padding-top="7"
padding-left="0" padding-right="0" font-size="12px">
        <a href="https://www.hollar.com/t/category" style="text-decoration:
none; color: #595959;">SHOP BY
CATEGORY</a>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<a href="
https://www.hollar.com/t/party" style="text-decoration: none; color:
#595959;">SHOP BY PARTY</a>&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;&#xA0;<a
href="https://www.hollar.com/t/gifts" style="text-decoration: none; color:
#595959;">SHOP GIFTS</a>
      </mj-text>
    </mj-column>

  </mj-section>


<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

  
    <mj-image  padding-bottom="0px" padding-top="0px"  padding-left="0px"
padding-right="0px"  src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_21_Shopkins/shopkins_featured.jpg"
href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px"
padding-left="25" padding-right="25" padding-bottom="10" padding-top="20">
        <p style="margin:3px 0 5px !important;">More must-have toys. More
party-perfect picks. More to love! </p>
      </mj-text>
      <mj-button background-color="#D1268C" color="white" font-size="16px"
align="center" vertical-align="middle" border="none" padding="15px 30px"
border-radius="3px" font-family="Helvetica, Arial, sans-serif"
href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10"
padding-top="10">
        SHOP NOW
      </mj-button>
    </mj-column>
  </mj-section>


  
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

    
    <mj-image  padding-bottom="0px" padding-top="30px"  padding-left="0px"
padding-right="0px"  src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_21_Shopkins/160318_Women_Active-email-pod.jpg"
href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#ee3129" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="27" line-height="30px"
padding-left="25" padding-right="25" padding-bottom="0" padding-top="20">
        <p><span style="font-weight: normal;">Get Movin'</span></p>
      </mj-text>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px"
padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p style="margin:3px 0 5px !important;">Fitness Gear Starting at
$2</p>
      </mj-text>
      <mj-button background-color="#ee3129" color="white" font-size="16px"
align="center" vertical-align="middle" border="none" padding="15px 30px"
border-radius="3px" font-family="Helvetica, Arial, sans-serif"
href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10"
padding-top="10">
        START SHARING
      </mj-button>
    </mj-column>
  </mj-section>

    
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

    
    <mj-image  padding-bottom="0px" padding-top="30px"  padding-left="0px"
padding-right="0px"  src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_21_Shopkins/160316_Girls_Electro-Pod.jpg"
href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#FB2757" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="27" line-height="30px"
padding-left="25" padding-right="25" padding-bottom="0" padding-top="20">
        <p><span style="font-weight: normal;">Geek? More Like
Chic.</span></p>
      </mj-text>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px"
padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p style="margin:3px 0 5px !important;">Tech Accessories with a
Feminine Edge<br>
        <span style="font-weight:bold;">Starting at $2</span></p>
      </mj-text>
      <mj-button background-color="#FB2757" color="white" font-size="16px"
align="center" vertical-align="middle" border="none" padding="15px 30px"
border-radius="3px" font-family="'Helvetica Neue', Helvetica, Arial,
sans-serif" href="www.#.com" padding-left="25" padding-right="25"
padding-bottom="10" padding-top="10">
        SHOP NOW
      </mj-button>
    </mj-column>
  </mj-section>

    
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">

    
    <mj-image  padding-bottom="0px" padding-top="30px"  padding-left="0px"
padding-right="0px"  src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_03_21_Shopkins/BLOG.jpg"
href="www.#.com" alt=""></mj-image>

      
      <mj-text align="center" color="#00b259" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="27" line-height="30px"
padding-left="25" padding-right="25" padding-bottom="0" padding-top="20">
        <p><span style="font-weight: normal;">The Hollar Blog</span></p>
      </mj-text>

      
      <mj-text align="center" color="#333333" font-family="'Helvetica
Neue', Helvetica, Arial, sans-serif" font-size="17" line-height="25px"
padding-left="25" padding-right="25" padding-bottom="10" padding-top="0">
        <p style="margin:3px 0 5px !important;">Fun stuff. Cool stuff. So
much good stuff.</p>
      </mj-text>
      <mj-button background-color="#00b259" color="white" font-size="16px"
align="center" vertical-align="middle" border="none" padding="15px 30px"
border-radius="3px" font-family="Helvetica, Arial, sans-serif"
href="www.#.com" padding-left="25" padding-right="25" padding-bottom="10"
padding-top="10">
        CHECK IT OUT
      </mj-button>
    </mj-column>
  </mj-section>

  
  <mj-section>
  <mj-column background-color="#FFFFFF">
 <mj-divider border-color="#cccccc" border-style="solid" border-width="1px"
padding-bottom="0" padding-top="0"></mj-divider>
  </mj-column>
  </mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">
      <mj-text align="center" color="#000000" font-family="Helvetica,
Arial, sans-serif" font-size="13" padding-left="25" padding-right="25"
padding-bottom="0" padding-top="0">
        Download Our App
      </mj-text>
  </mj-column>
</mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF" width="107px">
      <mj-image  padding="7px" width="98px" src="
http://hosting.fyleio.com/35647/public/newsletters/2016/2016_02_02_Emojis/email_emojis_160202_r1_21.png"
href="www.#.com" alt=""></mj-image>
  </mj-column>
  <mj-column background-color="#FFFFFF" width="107px">
      <mj-image  padding="7px" width="98px" src="
http://hosting.fyleio.com/35647/public/newsletters/2016/2016_02_02_Emojis/email_emojis_160202_r1_22.png"
href="www.#.com" alt=""></mj-image>
  </mj-column>
</mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">
      <mj-text align="center" color="#000000" font-family="Helvetica,
Arial, sans-serif" font-size="13" padding-left="25" padding-right="25"
padding-bottom="10" padding-top="0">
        <p>Join the Party on Social</p>
        <table width="185" cellspacing="0" cellpadding="0" border="0"
align="center">

                              <tbody><tr>

                                <td width="37" align="center"><a
target="_blank" href="http://facebook.com/shophollar"><img width="37"
border="0" style="display:block;" alt="facebook.com/shophollar" src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-facebook.png"
mc:edit="fac"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a
target="_blank" href="http://instagram.com/hollar"><img width="37"
border="0" style="display:block;" alt="Instagram: @hollar" src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-instagram.png"
mc:edit="twit"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37"><a target="_blank" href="
http://pinterest.com/hollar"><img width="37" border="0"
style="display:block;" alt="pinterest.com/hollar" src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-pinterest.png"
mc:edit="link"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a
target="_blank" href="http://twitter.com/hollar"><img width="37" border="0"
style="display:block;" alt="Twitter: @hollar" src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-twitter.png"
mc:edit="pint"></a></td>
                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><img
width="37" border="0" style="display:block;" alt="Snapchat: @hollarsnaps"
src="
http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_02_03_App/social-snapchat.png"
mc:edit="pint"></td>

                              </tr>

                            </tbody></table>
      </mj-text>
  </mj-column>
</mj-section>

   
<mj-section padding="0">
  <mj-column background-color="#FFFFFF">
      <mj-text align="center" color="#808080" font-family="Helvetica,
Arial, sans-serif" font-size="11" line-height="22px"padding-left="25"
padding-right="25" padding-bottom="10" padding-top="0">
        <p>*Limited time only. Invitations must be sent by March 20, 2016.
Prize will be awarded as Hollar credit for the $100. No purchase or payment
necessary to enter or to win. Odds depend on the number of eligible entries
received. Must be U.S. resident, 18 years or older to enter. Qualifying
invitations must be sent. See official rules for complete terms and
conditions. </p>
        <p>Free shipping offer is automatically applied at checkout on all
first-time orders over $10. For subsequent orders over $25 pre-tax, free
shipping will be applied at checkout. Offers valid on U.S. orders only.</p>
        <p>If you'd like to unsubscribe, click <a
href="%%!unsubscribe_url%%" style="color:#808080;
text-decoration:none;">here</a><br />
                        Copyright &copy; 2016 %%!account_organization%%.
All rights reserved. <br>
                        %%!account_address1%% %%!account_address2%%,
%%!account_city%%, %%!account_state%% %%!account_zip%%</p>
      </mj-text>
  </mj-column>
</mj-section>

</mj-body>

On Thu, Mar 24, 2016 at 2:13 AM, Maxime Brazeilles <notifications@github.com

**Comment by iRyusa** [comment]
Hi @lRlevolution !

Everything looks ok on my side, can you provide the full mjml template to help us investigate ?

**Comment by lRlevolution** [comment]
I had empty span classes which didn't render the styles.
