### ISSUE TITLE
Keep row of columns on mobile

### ISSUE THREAD

**Issue by puyanwei** [mjmlio/mjml#1520]
Hi,

I want to have a row of columns and maintain it on mobile. Right now it just stacks into a column of 3 rows on mobile by default

Note my images are 52px squared, and src address is probably wrong but i've changed what I really have for this example

```
      <mj-section>
        <mj-column width="52px">
          <mj-image src="image1.png">
          </mj-image>
        </mj-column>
        <mj-column width="52px">
          <mj-image src="image2.png">
          </mj-image>
        </mj-column>
        <mj-column width="52px">
          <mj-image src="image3.png">
          </mj-image>
        </mj-column>
      </mj-section>
```

**Comment by iRyusa** [comment]
Hi,

`mj-group` is what you're looking for. https://mjml.io/documentation/#mjml-group
