### ISSUE TITLE
MJML 4.3.0 Align Not Working

### ISSUE THREAD

**Issue by FasterThanGoogle** [mjmlio/mjml#1522]
Hi, 

Recently, the Try It Live version has been updated to 4.3.0 and all of my existing templates seem to be broken in some way (most likely bad coding, but it worked before).

For some reason, the align= attribute that I added to buttons, image and tables etc.. are no longer working and feels like they're being ignored. Is there another way I should be aligning objects and images now?

Thanks,

**Comment by iRyusa** [comment]
Well it works fine here https://mjml.io/try-it-live/SyXXf3cHE can you share some code ?

**Comment by FasterThanGoogle** [comment]
Sure, please see below:

https://mjml.io/try-it-live/S1tWrnqHE

The button, regardless of how I try to align doesn't work, I've also tried popping in a few images and they aren't affected by the align tag either.

**Comment by iRyusa** [comment]
You have no column in your section that’s why
