### ISSUE TITLE
charset=UTF-8 after title

### ISSUE THREAD

**Issue by minamoto19** [mjmlio/mjml#1524]
Hello.

It seems that the title tag `<title></title>` is generated before setting the charset.

So if the title is containing other than ASCII characters its decoding wrong and weird symbols displayed.

`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">` should be the first meta in head.

Kind Regards

**Comment by iRyusa** [comment]
Hi,

Well I don't really mind to move it, but as the HTML spec says :
https://www.w3.org/TR/html5/semantics.html#charset it must be declared in
the first 1024 bytes, so it's safe to assume that there's no real issue here

**Comment by minamoto19** [comment]
Hi.

I guess you are right then.

Sorry about that.

**Comment by iRyusa** [comment]
If you want to move the meta up, feel free to make a PR we'll merge it anyway 👍
