### ISSUE TITLE
Need a function to define a shared layout

### ISSUE THREAD

**Issue by ChristophKind** [mjmlio/mjml#1529]
Hi there,

I realy need a function or a statement to include an outer layout. I have defined a general outer layout with several inner contents (text, images, ...). My current workflow is to replace the inner conent every time in my outer layout. Thats costs me a lot of time. 

Is there any feature planned to define a layout like i mentioned?

Regards
Chris

**Comment by marciotoledo** [comment]
Hi @ChristophKind 

MJML have the 'mj-include' component.
https://mjml.io/documentation/#mj-include

You could have a gulp/grunt workflow that process all main templates including your inner content.
So you can change your inner content and run the workflow to generate the HTMLs.

Cheers,
MT

**Comment by ChristophKind** [comment]
Hmm,

mj-include is not what i am searching for.
Yes, I can use 3rd party tool to reach what i need, but it would be very nice to have it in native mjml.

It could be so easy: 
<mj-body layout='MyLayout.mjml'>
.....
</mj-body>

I am very surprised that this basic function does not exist...

**Comment by iRyusa** [comment]
Well it’s not really the job of MJML to do that. It’s more a templating feature. Feel free to use mjml with something like pug or any templating language that offer a layout support. As said, mj include is the closest feature that the lang will support

**Comment by iRyusa** [comment]
I'm closing because that was already discussed ( #987 ) and I don't think there's much more to add to this subject
