### ISSUE TITLE
Outlook Windows Desktop is rendering like mobile width

### ISSUE THREAD

**Issue by marciotoledo** [mjmlio/mjml#1530]
**Describe the bug**
I have a simple template, but on Outlook Windows Desktop is rendering like mobile width.

**To Reproduce**
1. MJML: https://mjml.io/try-it-live/SktcGIzLN
2. I'm just copying the rendered HTML
3. And sending by sendy.co instance
4. The error: https://d.pr/free/i/8fgLqP

**Expected behavior**
In preview and Gmail, are ok.
Preview: https://d.pr/free/i/niS1kn
Gmail: https://d.pr/free/i/wLph4i

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.1.2
 - MJML tool used: MJML App

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [Sendy](https://sendy.co/?ref=Q3yhn)

**Affected email clients (for rendering issues):**
 - Email Client: Outlook
 - OS: Windows
 - Browser: No issues

**Screenshots**
Links are above.

**Additional context**
No additional.

**Comment by iRyusa** [comment]
Your body width is in percent, it supports only px. That’s should be the lssue

**Comment by marciotoledo** [comment]
@iRyusa my bad! =/
But if I'd like template seams a common email (100% / full width). Not 600px centered?

**Comment by iRyusa** [comment]
Well, the technique we're using doesn't allow that so there's no real solution here to provide. If you only have a 'simple' text email like that you should be able to code it in HTML pretty easily as MJML won't really provide any help toward those single column + full text email.
