### ISSUE TITLE
Broken Links Mail Tester mj-navbar-link href

### ISSUE THREAD

**Issue by angelitodiaz1** [mjmlio/mjml#1535]
**Describe the bug**
Broken Links Mail Tester in Standard Body components mj-navbar-link  attributte href.

**To Reproduce**
1. Create a file with this MJML code:   <mj-navbar-link href="https://dominio.com/contacto/" color="#572A00" font-size="10px">
            CONTACTO
          </mj-navbar-link>
2. Render it to HTML by doing '.: In Mail Tester respond with...

[408 - Request timed out] https://dominio.com/contacto/

3. Send the HTML to an email address with '...'

**Expected behavior**
Not broken links in Email Tester https://www.mail-tester.com

**MJML environment (please complete the following information):**
 - Web Tool MJML Version 4.3.0

**Comment by iRyusa** [comment]
I'm sorry but can you share the whole MJML document ? I feel like you're not using mj-navbar as you should here, cf : https://mjml.io/documentation/#mjml-navbar

**Comment by iRyusa** [comment]
Closing, feel free te ropen with details
