### ISSUE TITLE
Line-height should support unitless

### ISSUE THREAD

**Issue by TheWebTech** [mjmlio/mjml#1536]
**Is your feature request related to a problem? Please describe.**
The line-height property supports using it unitless, and this is most often the most reliable way of using it. As far as I'm aware there are no issues with using unitless in any email clients.

https://www.campaignmonitor.com/css/text-fonts/line-height/

**Describe the solution you'd like**
allow unitless line-height attribute in mjml markup

**Comment by kmcb777** [comment]
Hi @TheWebTech, thanks for reporting this, however it has already been fixed in the latest version (4.4.0)
Which version are you using ?

**Comment by TheWebTech** [comment]
I guess I was using the MJML app (had some errors when trying to use the cli) 

MJML app must be running an older version of MJML

**Comment by kmcb777** [comment]
The app has been released with mjml4.4 so we can close this one
