### ISSUE TITLE
mj-image should support height="auto"

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml#1538]

**Comment by joerstom** [comment]
I'm using this commit and with height auto, Outlook 2010-2016 are cropping images around 20px. 

Code example, output from mjml:
`  <img alt height="auto" src="..." style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="337">`

Image reference attached.
![image002](https://user-images.githubusercontent.com/15024517/55723806-8b332d00-59cf-11e9-984f-74273e763f0a.png)

This didn't used to be an issue with mjml prior to this commit.

**Comment by iRyusa** [comment]
cc @kmcb777 it might now need a line-height reset to  `1` on mj-image ?

**Comment by kmcb777** [comment]
Yes i'll test with the line-height reset
@joerstom Do you mean you didn't have this behaviour with the same mjml before this commit ? Was it already height=auto in your previous test, or fixed height ?
It's strange because this commit only prevents the validator from triggering a warning when setting height to "auto". There hasn't been any actual change on mj-image for months.

**Comment by iRyusa** [comment]
I think this come from the font size that is now set for alt text

**Comment by joerstom** [comment]
@kmcb777 that's correct - I have not seen this issue with mj-image before. 
@iRyusa - I will manually add the line-height in both the MSO conditional comment and the universal html and report back. 

I'm not sure why it even puts font size into the style tag. Is that automatic as well?

**Comment by iRyusa** [comment]
If no font size is set, the alt tag won't be displayed in case of broken
link / accessiblity etc

**Comment by joerstom** [comment]
Line-height isn't fixing it. removing height auto doesn't fix it. setting a height to the table cell, or image doesn't fix it. I'm going to continue looking elsewhere but wanted to circle back. 

If I set the height to the image and table cell, it still crops it at about 16px and then moves it to the center of the tabe cell vertically. It's the strangest thing.

**Comment by iRyusa** [comment]
Can you share the template to allow us to investigate ?

**Comment by maxx0r** [comment]
mso-line-height-rule: at-least

have you tried that?
