### ISSUE TITLE
Can not get correct content when using https://mjml.io/api

### ISSUE THREAD

**Issue by luannguyengo1** [mjmlio/mjml#1539]
**Describe the bug**
Can not get correct content when using https://mjml.io/api

**To Reproduce**
- Call this script
`curl -X POST \
  https://api.mjml.io/v1/render \
  -H 'Authorization: Basic ZDFkZWEyODUtM2U0NC00ZjNjLTg1ZTgtNTUwNTVlZjhhMWM4OjAxZDc2ZDg4LTg1NjktNDdjOS1hNGZmLTRkY2U3Njg2ZTMxMg==' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: e150c1ef-7687-4280-a4b7-01faf4a9dc67' \
  -H 'cache-control: no-cache' \
  -d '{"mjml":"<mjml>\n  <mj-head>\n    <mj-title>Discount Light<\/mj-title>\n    <mj-preview>Pre-header Text<\/mj-preview>\n    <mj-font name=\"Muli\" href=\"https:\/\/fonts.googleapis.com\/css?family=Muli:400,400i,600,700\" \/>\n    <mj-attributes>\n      <mj-all padding=\"0\"><\/mj-all>\n      <mj-text font-style=\"normal\" font-weight=\"500\" font-size=\"16px\" color=\"#374B50\" line-height=\"22px\" font-family=\"Muli, -apple-system, system-ui, helvetica, '\''helvetica neue'\'', ubuntu, roboto, noto, '\''segoe ui'\'', arial, sans-serif\"><\/mj-text>\n    <\/mj-attributes>\n    <mj-style inline=\"inline\">\n      .body-section {\n        -webkit-box-shadow: 0px 1px 3px rgba(18, 31, 34, 0.06), 0px 4px 6px rgba(18, 31, 34, 0.08);\n        -moz-box-shadow: 0px 1px 3px rgba(18, 31, 34, 0.06), 0px 4px 6px rgba(18, 31, 34, 0.08);\n        box-shadow: 0px 1px 3px rgba(18, 31, 34, 0.06), 0px 4px 6px rgba(18, 31, 34, 0.08);\n      }\n    <\/mj-style>\n    <mj-style inline=\"inline\">\n      .text-link {\n        color: #5e6ebf\n      }\n    <\/mj-style>\n    <mj-style inline=\"inline\">\n      .footer-link {\n        color: #888888\n      }\n    <\/mj-style>\n  <\/mj-head>\n  <mj-body background-color=\"#ffffff\" width=\"536px\">\n    <mj-section full-width=\"full-width\" background-color=\"#374B50\" padding-bottom=\"48px\" padding-top=\"48px\" padding-left=\"38px\" padding-right=\"38px\">\n      <mj-column width=\"100%\">\n        <mj-image href=\"https:\/\/go1.com\" src=\"https:\/\/res.cloudinary.com\/go1vn\/image\/upload\/v1542352740\/ck9u0yqyojcdkjrv5xac.png\" alt=\"\" align=\"center\" width=\"150px\" \/>\n        <mj-text font-style=\"normal\" color=\"#C0D4D9\" font-weight=\"600\" align=\"center\" font-size=\"20px\" letter-spacing=\"1px\" padding-top=\"16px\" line-height=\"27px\">\n          GO1 learning recommendations\n        <\/mj-text>\n        <mj-text color=\"#81A2AB\" align=\"center\" font-size=\"16px\" padding-top=\"0\" font-weight=\"normal\" letter-spacing=\"1px\" line-height=\"22px\">\n          Our top picks for you this week\n        <\/mj-text>\n      <\/mj-column>\n    <\/mj-section>\n    <mj-section padding-top=\"32px\">\n      <mj-column><\/mj-column>\n    <\/mj-section>\n    <mj-wrapper border-radius=\"4px\" padding-top=\"32px\" padding-bottom=\"32px\" css-class=\"body-section\">\n      <mj-section>\n        <mj-column padding-left=\"24px\" padding-bottom=\"24px\">\n          <mj-text font-size=\"25px\" line-height=\"34px\" font-weight=\"600\">\n            Recommended for you\n          <\/mj-text>\n        <\/mj-column>\n      <\/mj-section>\n              <mj-section background-color=\"#ffffff\" padding-left=\"24px\" padding-bottom=\"24px\">\n          <mj-group>\n            <mj-column width=\"40%\">\n              <mj-image border-radius=\"4px\" href=\"https:\/\/dev.go1.com\/p\/#\/app\/course-view\/808339\/overview\" src=\"https:\/\/res.cloudinary.com\/go1vn\/image\/upload\/v1546483054\/weyceybyszrahqpilksx.png\" \/>\n            <\/mj-column>\n            <mj-column padding-left=\"16px\" width=\"60%\">\n              <mj-text color=\"#374B50\" font-weight=\"600\" font-size=\"20px\" line-height=\"27px\">\n                <a href=\"https:\/\/dev.go1.com\/p\/#\/app\/course-view\/808339\/overview\" style=\"text-decoration: none; color: inherit;\">Course 1.30<\/a>\n              <\/mj-text>\n              <mj-text color=\"#6B868C\" font-weight=\"normal\">\n                by Other Name \/ Vu Nguyen\n              <\/mj-text>\n              <mj-text color=\"#6B868C\" font-weight=\"normal\">\n                2h 30m\n              <\/mj-text>\n            <\/mj-column>\n          <\/mj-group>\n        <\/mj-section>\n              <mj-section background-color=\"#ffffff\" padding-left=\"24px\" padding-bottom=\"24px\">\n          <mj-group>\n            <mj-column width=\"40%\">\n              <mj-image border-radius=\"4px\" href=\"https:\/\/dev.go1.com\/p\/#\/app\/course-view\/808339\/overview\" src=\"https:\/\/res.cloudinary.com\/go1vn\/image\/upload\/v1546483054\/weyceybyszrahqpilksx.png\" \/>\n            <\/mj-column>\n            <mj-column padding-left=\"16px\" width=\"60%\">\n              <mj-text color=\"#374B50\" font-weight=\"600\" font-size=\"20px\" line-height=\"27px\">\n                <a href=\"https:\/\/dev.go1.com\/p\/#\/app\/course-view\/808339\/overview\" style=\"text-decoration: none; color: inherit;\">Course 1.30<\/a>\n              <\/mj-text>\n              <mj-text color=\"#6B868C\" font-weight=\"normal\">\n                by Other Name \/ Vu Nguyen\n              <\/mj-text>\n              <mj-text color=\"#6B868C\" font-weight=\"normal\">\n                2h 30m\n              <\/mj-text>\n            <\/mj-column>\n          <\/mj-group>\n        <\/mj-section>\n            <mj-section padding-top=\"6px\">\n        <mj-column>\n          <mj-button href=\"https:\/\/mygo1.com\/p\/\" width=\"100%\" height=\"48px\" align=\"center\" background-color=\"#31B8DA\" border-radius=\"4px\" color=\"#ffffff\" font-size=\"20px\" font-weight=\"bold\" inner-padding=\"0\" padding=\"10px 25px\" text-decoration=\"none\" text-transform=\"none\" vertical-align=\"middle\" line-height=\"20px\">\n            Go to dashboard\n          <\/mj-button>\n        <\/mj-column>\n      <\/mj-section>\n    <\/mj-wrapper>\n    <mj-section padding-bottom=\"100px\" padding-top=\"40px\">\n      <mj-column>\n        <mj-text letter-spacing=\"0.5px\" text-transform=\"uppercase\" text-decoration=\"none\" align=\"center\" color=\"#6B868C\" font-size=\"13px\" line-height=\"19px\" padding-bottom=\"0px\" padding-top=\"0px\" padding=\"10px 25px\">\n          <a href=\"https:\/\/go1.com\" style=\"text-decoration: none; color: inherit;\">\n            VISIt GO1.COM\n          <\/a>\n          |\n          <a href=\"https:\/\/go1.com\" style=\"text-decoration: none; color: inherit;\">\n            View email in browser\n          <\/a>\n          |\n          <a href=\"https:\/\/go1.com\" style=\"text-decoration: none; color: inherit;\">\n            Unsubscribe\n          <\/a>\n        <\/mj-text>\n      <\/mj-column>\n    <\/mj-section>\n  <\/mj-body>\n<\/mjml>\n"}'`

**Expected behavior**
Work same with result from https://mjml.io/try-it-live

**Screenshots**
http://prntscr.com/mw6mpx

**Comment by ngarnier** [comment]
As returned by the API, the API is using the MJML v3 version, so your markup (using v4 syntax) is invalid (as for example `mj-container` is deprecated in v3 but mandatory in v4). We're working to update the API to use v4.

Also, please *do not share your API credentials* in a public issue visible to everyone... I'm deleting your issue so that they don't remain visible to anyone.
