### ISSUE TITLE
Issue rendering in outlook

### ISSUE THREAD

**Issue by EduCaballero** [mjmlio/mjml#1541]
Hi there, 

I would like to know if someone has the same problem as me with Outlook. [Here's my code and how it should look](https://mjml.io/try-it-live/rkJOcKPDE)
<a href="http://es.tinypic.com?ref=25in3o5" target="_blank"><img src="http://i68.tinypic.com/25in3o5.png" border="0" alt="Image and video hosting by TinyPic"></a>

And here is how it looks on Outlook, sent using LitmusPutmail and in-app mjml desktop software (with mailjet has minor differences):
<a href="http://es.tinypic.com?ref=23likhe" target="_blank"><img src="http://i64.tinypic.com/23likhe.png" border="0" alt="Image and video hosting by TinyPic"></a>
<a href="http://es.tinypic.com?ref=ibmaki" target="_blank"><img src="http://i67.tinypic.com/ibmaki.png" border="0" alt="Image and video hosting by TinyPic"></a>

Very thankful

**Comment by ngarnier** [comment]
Hey @EduCaballero, the issue is that your markup is invalid: you have sections where the sum of the columns is more than 100%. Example you should rather split the section line 24 into 2 sections with each a 100% column inside.
