### ISSUE TITLE
MJML Navbar hamburger not working 

### ISSUE THREAD

**Issue by waqasalimeer** [mjmlio/mjml#1545]
**Navbar hamburger is not working even in IOS**
I create a menubar with mjml-navbar and using hamburger for mobile devices. The humburger is not working even in ios which it is supported. I am using mailchimp to send emails. 

The icons-align option also not work in any mjml editor. 

 `<mj-navbar text-align="right" base-url="https://mjml.io" hamburger="hamburger" ico-color="#ffffff">
          <mj-navbar-link href="#" color="#ffffff">Getting started</mj-navbar-link>
          <mj-navbar-link href="#" color="#ffffff">Try it live</mj-navbar-link>
          <mj-navbar-link href="#" color="#ffffff">Templates</mj-navbar-link>
          <mj-navbar-link href=#" color="#ffffff">Components</mj-navbar-link>
        </mj-navbar>`

**Comment by iRyusa** [comment]
Can you give it a try with https://putsmail.com/ to send your email? It's
working fine for me, might be mailchimp messing with the media queries.
icon-align has been fixed in 4.4.0 beta cf
https://github.com/mjmlio/mjml/releases/tag/v4.4.0-beta.1

**Comment by iRyusa** [comment]
I'm closing for now, feel free to test with putsmail if it still doesn't work for you we'll investigate a bit more

**Comment by waqasalimeer** [comment]
Hi

I test it with litimus. I removed the hamburger and use its default behaviour.

I think its issue with MailChimp.  Because I notice one more issue. On Gmail web version. It will display a mobile version instead of desktop version.

In litimus it will display good.

thanks
