### ISSUE TITLE
mj-include - allow absolute paths 

### ISSUE THREAD

**Issue by araphiel** [mjmlio/mjml#1546]
### Ideal behavior

**File:** archive/index.mjml 

- `<mj-include root="true" path="/partials/footer.mjml" />`

**Command**:  `npx mjml ./archive/**/*.mjml -o ./dist` 

- ✅ All files in located in a the archive will compile into the /dist folder 
- 🚫 mj-include partials are referenced from _project root_ directory, instead of _file_ directory. 

---

**Why?**: This would allow larger teams to provide a consistent workspace + archive

```
├── index.mjml // working file (untracked)
├── partials // template partials
|    ├── header.mjml
|    └── footer.mjml
└── archive // repo of old work
    └── events
    |   └── event-email-96.mjml
    └── newletters
        ├── newsletter-55.mjml
        └── random-campaign
            └── campaign-newsletter.mjml
```

**Comment by araphiel** [comment]
As it turns out - this functionality does exist via [`mjml2html`](https://mjml.io/documentation/#inside-node-js) options.

**Comment by kmcb777** [comment]
@araphiel actually all the mjml2html options can be used with the cli with `--config`, so you can already do `--config.filepath ./includes`
We'll add this one to the cli documentation 👍

**Comment by araphiel** [comment]
Thanks for reaching out @kmcb777 

Just tested it out (using the command below) & the mj-include partials didn't compile.

`npx mjml archive/general/webinar_thank-you.mjml --config.filePath ./partials -o index.html`

Maybe `filePath` needs to be explictly exposed via the CLI?

https://github.com/mjmlio/mjml/blob/da9825c1628aa4259feddb4bf5ccbcb5fa338b10/packages/mjml-cli/src/client.js#L100

https://github.com/mjmlio/mjml/blob/da9825c1628aa4259feddb4bf5ccbcb5fa338b10/packages/mjml-cli/src/client.js#L175

**Comment by iRyusa** [comment]
You have to use relative path no absolute
