### ISSUE TITLE
MJML email sent from Oulook 2016 not rendering correctly in Apple Mail

### ISSUE THREAD

**Issue by hollygodarkly** [mjmlio/mjml#1547]
Hi all,

I'm new to MJML, and working on my first project. It's a simple template, but I'm finding that it's not rendering as expected in the Apple Mail app.

Our team uses Outlook as our email platform (my only choice), and a majority of our users check email on iOS mobile devices using the Apple Mail app.

I’ve searched out and tried some fixes I’ve found online (for example, [these tips](https://emails.hteumeuleu.com/what-you-need-to-know-about-apple-mail-in-ios-10-c7031f6d704d) and others), but to no avail.

When I try to use <pre>&lt;meta name="x-apple-disable-message-reformatting" /&gt;</pre> specifically, it's in the code when I put it in Outlook, but it looks like it's stripped out when it's sent. It's no longer there when I check the HTML after I receive the test email.
 
Is there a workaround for email rendering in Apple Mail when the email is sent from Outlook?

Thanks.

**To Reproduce**
1. MJML:

`<mjml>
  <mj-head>
    <mj-attributes></mj-attributes>
    <mj-style></mj-style>
    <mj-raw>
      <meta name="x-apple-disable-message-reformatting" /> </mj-raw>
  </mj-head>
  <mj-body background-color="#fff">
    <mj-section>
      <mj-column>
        <mj-text align="center">This is a header</mj-text>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-text>
          <p>Hello,
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dui lectus, rhoncus et fringilla id, tempor quis massa.</p>
            <p>Nullam leo erat, porta vel ante id, maximus ultrices nisi.</p>
            <p>Donec quis semper tellus. Phasellus vitae lacus quis neque auctor mollis at eget ex. Vivamus in convallis quam. Ut malesuada velit nisi, sit amet rutrum leo condimentum non.</p>
            <p>Ut volutpat vehicula nulla, vel auctor ipsum luctus non. Integer posuere ante augue, vitae egestas turpis lacinia id.</p>
            <p>Thank you,</p>
            <p>Good night.</p>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-text align="center">
          <p>This is a footer.</p>
        </mj-text>
      </mj-column>
    </mj-section>
</mjml>`

2. HTML:

`<!doctype html>
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
      <head>
        <title>
          
        </title>
        
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style type="text/css">
          #outlook a { padding:0; }
          .ReadMsgBody { width:100%; }
          .ExternalClass { width:100%; }
          .ExternalClass * { line-height:100%; }
          body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
          table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
          img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
          p { display:block;margin:13px 0; }
        </style>
        
        <style type="text/css">
          @media only screen and (max-width:480px) {
            @-ms-viewport { width:320px; }
            @viewport { width:320px; }
          }
        </style>
        
        
        
        
      
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css">
        <style type="text/css">
          @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);
        </style>
      

    
        
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }
    </style>
    
  
        <style type="text/css">
        
        
        </style>
        <style type="text/css"></style>
        <meta name="x-apple-disable-message-reformatting" />
      </head>
      <body style="background-color:#ffffff;">
        
        
      <div
         style="background-color:#ffffff;"
      >
        
      
      
    
      
      <div  style="Margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;"
              >
                
            
      <div
         class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        
            <tr>
              <td
                 align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
              >
                
      <div
         style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:center;color:#000000;"
      >
        This is a header
      </div>
    
              </td>
            </tr>
          
      </table>
    
      </div>
    
          
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      
    
      
      <div  style="Margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;"
              >
                
            
      <div
         class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        
            <tr>
              <td
                 align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
              >
                
      <div
         style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;"
      >
        <p>Hello,
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dui lectus, rhoncus et fringilla id, tempor quis massa.</p>
            <p>Nullam leo erat, porta vel ante id, maximus ultrices nisi.</p>
            <p>Donec quis semper tellus. Phasellus vitae lacus quis neque auctor mollis at eget ex. Vivamus in convallis quam. Ut malesuada velit nisi, sit amet rutrum leo condimentum non.</p>
            <p>Ut volutpat vehicula nulla, vel auctor ipsum luctus non. Integer posuere ante augue, vitae egestas turpis lacinia id.</p>
            <p>Thank you,</p>
            <p>Good night.</p>
      </div>
    
              </td>
            </tr>
          
      </table>
    
      </div>
    
          
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      
    
      
      <div  style="Margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;"
              >
                
            
      <div
         class="mj-column-per-100 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        
            <tr>
              <td
                 align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
              >
                
      <div
         style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:center;color:#000000;"
      >
        <p>This is a footer.</p>
      </div>
    
              </td>
            </tr>
          
      </table>
    
      </div>
    
          
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      
    
    
      </div>
    
      </body>
    </html>`
3. Send the HTML from Outlook 2016 and check in Apple Mail.

**Expected behavior**
Email to display in Apple Mail app the same as (or close to) the display in the Outlook for iOS app.
 
**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: 4.3.1
 - MJML tool used: MJML App 2.11.0

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Outlook 2016 

**Affected email clients (for rendering issues):**
 - Email Client: Apple Mail, Outlook for iOS app
 - OS: iOS 12
 - Browser: None

**Screenshots**
The images are screenshots of the email rendered in Outlook 2016 on Windows 10 desktop, the Outlook iOS mobile app on iOS 12.1.4 (full width of the screen), and in Apple Mail on iOS 12.1.4 (half the width and aligned to the left).

**Additional context**

![AppleMail](https://user-images.githubusercontent.com/48868355/54883012-d3721d00-4e1d-11e9-8611-5be08d382bf8.png)
![OutlookOnDesktop](https://user-images.githubusercontent.com/48868355/54883013-d40ab380-4e1d-11e9-9873-a7d502421fb0.png)
![OutlookOnMobile](https://user-images.githubusercontent.com/48868355/54883014-d40ab380-4e1d-11e9-93b8-db03863772fe.png)

**Comment by iRyusa** [comment]
You won't be able to get nice result when sending from Outlook. It mess
with the HTML you should send from an esp or if it's for testing use
something like https://putsmail.com/

**Comment by hollygodarkly** [comment]
Unfortunately, that's not an option for me at work. Outlook is my only choice. At least I know that what I have is as good as it gets.

Thanks.

**Comment by iRyusa** [comment]
Then yes, there's no way to fix that, and you won't be able to have any
responsive behavior in top of that so MJML is useless in your case.
