### ISSUE TITLE
Display issue on Apple Mail on Iphone 5S

### ISSUE THREAD

**Issue by Pookiz** [mjmlio/mjml#155]
Hello,

When I tried the compatibility between clients/devices with Email On Acid, I found this issue :

![screen issue](https://cloud.githubusercontent.com/assets/9559832/14016921/9c228196-f1c3-11e5-9801-2009279ec159.png)

I have researched how to fix this and there is the solution : 
http://stackoverflow.com/questions/9493272/iphone-mail-table-doesnt-stretch-to-100-because-of-an-anchor-tag
http://stackoverflow.com/questions/10398227/link-in-100-width-table-results-in-90-width-table/10711039#10711039

How can we fix that ? Because I can not do this with the mjml file...

Thank you very much for your answers :)

**Comment by arnaudbreton** [comment]
Hi @Pookiz, sorry to hear you're experiencing issue with your layout.

Could you please share the MJML code used here, so we can provide you with better support?

**Comment by Pookiz** [comment]
Hi @arnaudbreton, thank your for your answer
The example is from the basic layout : company header

Here the section with the image :+1: 
`<mj-body background-color="#e8e8e8">

<mj-section background-color="#f0f0f0">
  <mj-column>
    <mj-text  
              font-style="italic"
              align="center"
              font-size="20"
              color="#626262">
      My Company
    </mj-text>
  </mj-column>
</mj-section>
  
  
  
  <mj-section background-url="https://pixabay.com/static/uploads/photo/2015/08/08/20/18/paris-880754_960_720.jpg"
              background-size="cover"
              padding="10">

    <mj-column>

          <mj-text  align="center"
                   	line-height="1"
                    color="#fff"
                    font-size="40"
                    font-family="Helvetica Neue"
                    padding="80">Slogan here</mj-text>

      <mj-button background-color="#F63A4D"
                 href="#">
        Promotion
      </mj-button>

    </mj-column>

  </mj-section>
</mj-body> `

**Comment by Pookiz** [comment]
Hi MJML team!

Have any news from this issue ? :( 

Thank you!

**Comment by isnifer** [comment]
Hey, guys! There is a problem with that demo on desktop too:
## Tablet
![image](https://cloud.githubusercontent.com/assets/1788245/14918818/8848114a-0e2e-11e6-9b71-49ed0e60c3a8.png)

## Mobile 
![image](https://cloud.githubusercontent.com/assets/1788245/14918825/8dc87164-0e2e-11e6-8e51-376292cd82d1.png)

**Comment by iRyusa** [comment]
Hi, i've just checked.

@isnifer On the mjml there's a `line-height="1" on `mj-text` that break the design.
The issue described here is solved by mjml 2.0, I close it.

@GuillaumeBadi can you update it to remove `line-height` on the try it live example?
