### ISSUE TITLE
Gmail on iOS not respecting button width

### ISSUE THREAD

**Issue by pdugan20** [mjmlio/mjml#1556]
Gmail's newest release on iOS collapses buttons and doesn't respect manual widths.

**Comment by iRyusa** [comment]
Can you share a bit of details ? Markup, mjml version, screenshots ? Really
hard to see what's going on with this little informations

**Comment by iRyusa** [comment]
@pdugan20 any news on that ?

**Comment by kmcb777** [comment]
@pdugan20 I couldn't reproduce on emailonacid, if you still have this problem please provide your mjml code so that we can test
