### ISSUE TITLE
Border overflow inside column

### ISSUE THREAD

**Issue by osajunior** [mjmlio/mjml#1557]
example: https://mjml.io/try-it-live/HJIcpwv_E

```
<mjml>
  <mj-head></mj-head>
  <mj-body width="600px">
    <mj-section border="0 solid #000000" background-repeat="repeat" background-size="auto" vertical-align="top" text-align="left" padding="0" direction="ltr" background-color="#FFFFFF">
      <mj-column border="none" vertical-align="top" padding="0" width="100%">
        <mj-text color="#000000" container-background-color="#FFD32A" font-family="Ubuntu, Helvetica, Arial, sans-serif" font-size="13px" line-height="19px" align="left" padding="5px">
          <p style="font-family:Arial;font-size:14px;margin-top:0px;margin-bottom:0px;font-weight:normal;color:#000000;"><strong>Test message</strong></p>          
        </mj-text>
        <mj-image src="https://picsum.photos/600/300" href="" width="600px" align="right" alt="" style="text-align: center"padding="0" border-radius="0" border="20px solid #000000"></mj-image>
      </mj-column>
    </mj-section>
    <mj-section border="0 solid #000000" background-repeat="repeat" background-size="auto" vertical-align="top" text-align="center" padding="5px" direction="ltr">
      <mj-column border="none" vertical-align="top" padding="0" width="25%"></mj-column>
      <mj-column border="none" vertical-align="top" padding="0" width="25%"></mj-column>
      <mj-column border="none" vertical-align="top" padding="0" width="25%"></mj-column>
      <mj-column border="none" vertical-align="top" padding="0" width="25%"></mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

you should add: 'box-sizing': 'border-box' to the getStyles () method in mjml-image  to fix this

**Comment by ngarnier** [comment]
Issue is not linked to align but really just how the border calculation works with mj-image, thanks for reporting. 

Simplified snippet to reproduce with just what is needed: https://mjml.io/try-it-live/Hy5toUsOV

```mjml
<mjml>
  <mj-body>
    <mj-section background-color="red" padding="0">
      <mj-column>
        <mj-text container-background-color="#FFD32A">
          Test message
        </mj-text>
        <mj-image src="https://picsum.photos/600/300" padding="0" border="20px solid #000000"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
` 'box-sizing': 'border-box' ` would just add some inconsistencies as most of Desktop clients doesn't support it.

It seems that using an align left would fix it because of how width are handled inside `mj-image` html

I don't know if we can do anything on that it might just be a gotcha when working with high border value :(

**Comment by kmcb777** [comment]
After further experimentation, it seems impossible to properly handle horizontal alignment when there is a border on mj-image, only align:left works properly. It would indeed require to use border-box but it's still not supported on some mainstream email clients

**Comment by thefubon** [comment]
<mjml>
  <mj-body>
    <mj-section background-color="red" padding="0">
      <mj-column>
        <mj-text container-background-color="#FFD32A">
          Test message
        </mj-text>
        <mj-image src="https://picsum.photos/600/300" padding="20px"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
