### ISSUE TITLE
feature request: support more positioning for mj-divider

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1558]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Support positioning the divider horizontally. Within `mj-divider`, `width="50%"` centers the divider at half the width of the box it's in. It'd be nice to be able to justify the divider left or right. Or center it on other points in the width.

**Describe alternatives you've considered**
As to left and right justification:
- Add a new attribute `align, left/right/center, default center`, similar to `mj-text`.
- Support percentages on the existing attribute `padding`, so that `width="25%" padding-right="75%"` would cause left justification at all screen widths.

As to centering on other points in the width: Support percentages on the existing `padding` attribute, so that `width="33%" padding-left="17%"` would (approximately) center a divider with length one-third of the box, centered at one third across the box.
- If we support right-to-left languages downstream, include this in the effects? 

As to existing support of percentage values in padding: See [example](https://mjml.io/try-it-live/H1inubs_E). The MJML 4.3.0 `mj-divider` component responds unpredictably to percentage values in padding. `width="25%" padding-left="75%"` (an attempt at right justification) results in a divider smaller than `width="25%"` and though positioned in the right quarter of the line, is not centered on the right quarter in the example shown. The component would do better to respond predictably, perhaps ignoring percentages (since they're not supported).

**Additional context**
Urgency: Low. It's an idea.

**Comment by iRyusa** [comment]
Closing because of duplicate : #407 
It would be nice to have but as today it's done with margin, it would require to tweak a bit the divider code

**Comment by GarryFlemings** [comment]
All good. Lots of good information in #407. Thanks.
