### ISSUE TITLE
Anchor tag for components 

### ISSUE THREAD

**Issue by g0ddish** [mjmlio/mjml#156]
Maybe I'm blind but I can't find in the docs how to use links other than hrefs in image and button. I was wrapping an anchor tag in mj-text and it required you to inline remove text-decoration and color inherit to match the mj-text.

- Would it make more sense for it to take on the styling of its parent?
- What if I want to link a component that doesn't have href?
- Would an mj-a tag would be a good addition?

**Comment by arnaudbreton** [comment]
@g0ddish thanks for sharing.

Please provide MJML code showing what you're trying to achieve and/or [try it live](https://mjml.io/try-it-live) URL (or screenshots) of the result, to be sure I get everything.

Thanks!

**Comment by g0ddish** [comment]
This is for my first bullet, an example use case would also be legal text links matching their mj-text parent.
https://mjml.io/try-it-live/8b865458e9b573574322

My second bullet won't compile into HTML; I hope this illustrates what I'n trying to accomplish.

```
<mj-body>
    <mj-section>
    <mj-column width="100%">
     <a href="http://www.google.ca"><mj-location address="37 bis, rue du Sentier – 75002 Paris" /></a> 
    </mj-column>
  </mj-section>
</mj-body>

```

**Comment by arnaudbreton** [comment]
I see, in that case it is an update on the component itself, which definitely lacks an `href` property. Thanks for reporting!

We'll look into that shortly. Meanwhile, we would love to review a contribution from you.

Keep you posted

**Comment by iRyusa** [comment]
Hello

`href` is available for `mj-location`, we'll update the documentation with 2.3.3.
