### ISSUE TITLE
Combining separate <mj-style> elements, expected behavior?

### ISSUE THREAD

**Issue by viktorix** [mjmlio/mjml#1562]
**Describe the bug**
When you create several <mj-style> sections, when HTML is rendered they are all combined into one <style> section.

**To Reproduce**
1. Add several <mj-style> sections.
2. Check HTML.
3. They will be combined into one <style>

**Expected behavior**
If we choose to separate CSS with <mj-style> they should be rendered as individual <style> sections.

**MJML environment (please complete the following information):**
 - OS:  Win 10
 - MJML Version 4.3.1
 - MJML app 2.11.0 and visual studio code.

**Additional context**
This is somewhat related to my [feature suggestion](https://github.com/mjmlio/mjml/issues/1561) about conditional attribute. I was trying to add conditional statements with mj-raw (see below) and I did not notice styles were combined, and my conditional statements were left empty:

```
<mj-raw><!--[if mso]><!-- --></mj-raw>
  <mj-style>
    .mso-hide{ display: block !important; }
  </mj-style>
<mj-raw><!--<![endif]--></mj-raw>
```
and when HTML is rendered:
```
<style type="text/css">
        .mso-hide {
            display: none;
        }

        [class*="mso-hide"] {
            display: none;
        }

        .mso-hide {
            display: block !important;
        }
    </style>
    <!--[if mso]><!-- -->
    <!--<![endif]-->
```

**Comment by iRyusa** [comment]
Well this is expected as you want to save as many space as you can inside an email. I don't think "as it's own" it would add any value, as in 99.99% of case you want to minify your file before sending it

**Comment by kmcb777** [comment]
@viktorix  right now mj-styles are all grouped together, and mj-raws in mj-head are also grouped together and inserted at the end of the head, it would require a lot of changes.
For now you can just use a mj-raw, and inside it you put your conditional and a regular `style` tag
