### ISSUE TITLE
Padding between Sections and Word Breaks

### ISSUE THREAD

**Issue by epeck-graphicproducts** [mjmlio/mjml#1564]
Hey there,

So I'm working on creating some transaction emails and I'm new to mjml and struggling with some basics.  I can't seem to figure out how to get rid of all of the extra space in between my sections.

**Example:**
![image](https://user-images.githubusercontent.com/49292317/55633764-e1a33000-5771-11e9-9343-6d18f3fd720b.png)

I also need help figuring out how to remove the word break or at least get it so the abbreviation on the text 'QTY' isn't breaking.  I've put larger words in that same spot and it breaks way later in the text.

Here's my code:
```mjml
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          <mj-style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    html,
    body,
    table,
    tbody,
    tr,
    td,
    div,
    p,
    ul,
    ol,
    li,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      margin: 0;
      padding: 0;
    }
    body {
      margin: 0;
      padding: 0;
      font-size: 0;
      line-height: 0;
      -ms-text-size-adjust: 100%;
      -webkit-text-size-adjust: 100%;
    }
    table {
      border-spacing: 0;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }
    table td {
      border-collapse: collapse;
    }
    .ExternalClass {
      width: 100%;
    }
    .ExternalClass,
    .ExternalClass p,
    .ExternalClass span,
    .ExternalClass font,
    .ExternalClass td,
    .ExternalClass div {
      line-height: 100%;
    }
    /* Outermost container in Outlook.com */
    .ReadMsgBody {
      width: 100%;
    }
    img {
      -ms-interpolation-mode: bicubic;
    }
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: Arial;
    }
    h1 {
      font-size: 28px;
      line-height: 32px;
      padding-top: 10px;
      padding-bottom: 24px;
    }
    h2 {
      font-size: 24px;
      line-height: 28px;
      padding-top: 10px;
      padding-bottom: 20px;
    }
    h3 {
      font-size: 20px;
      line-height: 24px;
      padding-top: 10px;
      padding-bottom: 16px;
    }
    p {
      font-size: 16px;
      line-height: 20px;
      font-family: Georgia, Arial, sans-serif;
    }
    </style>

    <style>
      .container600 {
        width: 600px;
        max-width: 100%;
      }
    @media all and (max-width: 599px) {
      .container600 {
        width: 100% !important;
      }
      
    
      .smarttable {
        border: 0;
      }
      .smarttable thead {
        display:none;
        border: none;
        clip: rect(0 0 0 0);
        height: 0px;
        margin: 0px;
        overflow: hidden;
        padding: 0;
        max-width:0px;
        max-height:0px;
      }
      .smarttable tr {
        display: block;
        width:90%;
        margin:20px auto;
      }
      .smarttable td {
        border-bottom: 1px solid #000;
        display: block;
        font-size: 14px;
        text-align: right;
      }
      .smarttable td:before {
        content: attr(data-label);
        float: left;
        font-weight: bold;
        text-transform: uppercase;
      }
    }
  </style>
</mj-style>
   <!--[if gte mso 9]>
        <style>
            .ol {
              width: 100%;
            }
        </style>
    <![endif]-->

</head>
    <center>

        <!--[if gte mso 9]><table width="600" cellpadding="0" cellspacing="0"><tr><td>
                    <![endif]-->

                <table width="100%" cellpadding="0" cellspacing="0" style="min-width:100%;">
 
                  <tr>
                    <td style="padding:5px;">

                        <table class="smarttable" width="100%" cellpadding="0" cellspacing="0" style="min-width:100%;">
                          <thead>
                            <tr>
                              <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">QTY</th>
                              <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">UM</th>
                              <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">ITEM #</th>
                                   <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:20px;line-height:30px;color:#033047;text-align:left;background-color:#eee">DESCRIPTION</th>
                                   <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">UNIT PRICE</th>
                                   <th scope="col" style="padding:5px; font-family: Arial,sans-serif; font-size: 14px; line-height:10px;line-height:15px;color:#033047;text-align:left;background-color:#eee">EXTENDED PRICE</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td data-label="QTY" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">12</td>
                              <td data-label="UM" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">200R</td>
                              <td data-label="ITEM #" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">T0406-70</td>
                              <td data-label="DESCRIPTION" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">	DLT 4x6 WARNING AF OUTDOOR</td>
                              <td data-label="UNIT PRICE" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">$214.99</td>
                              <td data-label="EXTENDED PRICE" valign="top" style="padding:5px; font-family: Arial,sans-serif; font-size: 12px; line-height:20px;">$2,579.88</td>
                            </tr>

             
                          </tbody>
                        </table>

                    </td>
                  </tr>
                </table>

              </td>
        </tr>
    </table>

  <!--[if gte mso 9]></td></tr></table>
                    <![endif]-->
    </center>

        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by ngarnier** [comment]
Your code looks completely invalid, you have a `style` inside a `mj-style` inside a `mj-text`, then a closing `head` tag...?

**Comment by epeck-graphicproducts** [comment]
Like I said, I am new to this platform and I’m by no means a master coder.

**Comment by ngarnier** [comment]
That's totally fine, but you still need to refer to the documentation. You can clearly see here that `mj-style` should be inside `mj-head`, and that no `style` tag needs to be added inside: https://mjml.io/documentation/#mjml-style

**Comment by epeck-graphicproducts** [comment]
Well this is just the code for the data table I have addition code for the rest of my email.  When I remove the regular style tag the design disappears in the view.  I was wondering if I just used the raw code tag for this section.  I’m basically trying to implement a workaround to having my data table look all squished when it’s on mobile by using card stacking instead of word-breaks.

**Comment by ngarnier** [comment]
It's impossible to help you without valid code to reproduce and understand your problem. 

I did the work for you and here is a link with your code cleaned: https://mjml.io/try-it-live/Bk8L3yBFV. I don't see any specific issue there?

**Comment by epeck-graphicproducts** [comment]
Okay, thank you for providing that for me.  As I said before it now has broken the other half of my code, the index.

See below:
[cid:image002.jpg@01D4EB85.97BE35F0]

**Comment by ngarnier** [comment]
If you're referring to image in your first comment (as in your latest comment there is no image, just `[cid:image002.jpg@01D4EB85.97BE35F0]`), you didn't provide the section above the table, so we can't help.

**Comment by epeck-graphicproducts** [comment]
![image](https://user-images.githubusercontent.com/49292317/55637270-7eb59700-5779-11e9-8a4b-c28f9215a9a1.png)

Here is the image.  Is there something I can do to make you less cranky?

**Comment by epeck-graphicproducts** [comment]
Here is the index code:

<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="left" font-family="sans-serif" color="#000" font-size="16px" line-height="24px" />
      <mj-section background-color="#fff" />
      <mj-button background-color="#F45E43" color="#fff" font-size="14px" /> </mj-attributes>
  </mj-head>
  <mj-body background-color="#eee">
    <mj-section>
      <mj-column>
        <mj-text>
          <h1 style="color:#033047;font-size:18px;">ORDER CONFIRMATION</h1>
          <mj-text>Customer #:<br> Order #: ((OrderNbr))<br> Order Status: ((poorderslist.Status))<br> Ship-to Name: ((poreceiptslist.ShipToLocationID.DefContactID.FirstName)) ((poreceiptslist.ShipToLocationID.DefContactID.LastName)) <br> Ship-to Company: ((poreceiptslist.ShipToLocationID.Descr))<br>            Shipping Location: ((poreceiptslist.ShipToLocationID))<br> Order Date: ((poorderslist.CreatedDateTime))<br> Customer PO#: <br> Terms: ((poorderslist.TermsID))<br> Ship Via:<br> FOB: ((poorderslist.FOBPoint.FOBPointID))<br> Purchaser:<br>            Comment:<br> Territory: </mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-include path="./test.mjml" /> </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-text> Payment Type:<br> Ship Weight:<br> Freight Amount:<br> Order Total (USD): ((poorderslist.OrderTotal))<br></br> Date and time of this email: 01/11/2019 11:01:07 AM Pacific<br> </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by epeck-graphicproducts** [comment]
I also appears as though my the changes you made to my code made it stack in mobile very strangely

![image](https://user-images.githubusercontent.com/49292317/55637413-d81dc600-5779-11e9-9ed8-e3f22a15020e.png)

**Comment by ngarnier** [comment]
"less cranky", really? I'm just trying to help you, and you're making it very difficult by providing only chunks of information. The responsive is looking good for me on the example I created:

![Screenshot 2019-04-05 at 5 09 34 PM](https://user-images.githubusercontent.com/4700883/55637564-adf1f580-57c5-11e9-8248-66fb18dab85a.png)

Please provide your final code, compiled inside a single MJML file (not with an include separated) on https://mjml.io/try-it-live if you want us to help.

**Comment by epeck-graphicproducts** [comment]
Will do, I’ll send it over after I figure out how to combine everything you made without it messing up the entire design ☺

**Comment by epeck-graphicproducts** [comment]
Here you go: https://mjml.io/try-it-live/Bk1NTlBYN

**Comment by ngarnier** [comment]
Thanks. So now, the only issue is the vertical padding between the sections? If so, you just need to reset the default padding by applying `padding="0"` on your `mj-section`s. You can do it on each section or use `mj-section` inside `mj-attributes` to make it default (works for all other components too such as `mj-text`).

**Comment by epeck-graphicproducts** [comment]
Thanks. I was able to figure that part out on Friday, I'm still not sure how to remove the random line breaks in the data table, if you would like to address that.

**Comment by epeck-graphicproducts** [comment]
I’ve been able to plug in larger words and they word break later on in the word, is there not a way to tell it when to word break?

**Comment by iRyusa** [comment]
Well MJML doesn't provide any magic stuff, it's basic html table that
behave like that so no.

**Comment by epeck-graphicproducts** [comment]
Oh well. Thanks.
