### ISSUE TITLE
<!--[if mso]> conditional comment breaks mj-raw

### ISSUE THREAD

**Issue by WilsonBrett** [mjmlio/mjml#1565]
**Describe the bug**
When using an [if mso] conditional inside an mj-raw tag (mjml 4.3) the first closing mj-raw tag, mjml element that follows, and subsequent opening mj-raw tag (needed to hold the closing mso conditional tag) is treated as one comment. The mj-element doesn't render as expected.

Problematic snippet (large red square in screenshot):

```
<mj-raw><!--[if mso]></mj-raw>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
<mj-raw><![endif]--></mj-raw>
```

My try-it live:
https://mjml.io/try-it-live/BkLgDMSYN

**Screenshots**
![mj-raw_with_mso](https://user-images.githubusercontent.com/13980960/55650540-f99ba380-57b3-11e9-823e-809115566a66.png)

**Expected behavior**
Something similar to the [if !mso] conditional comment where the opening comment allows the mj-text element to render. Mj-raw tags are also parsed correctly by the mjml engine leaving only the contents of the mj-raw tags outputted into the html.

```
<mj-raw><!--[if !mso]><!-- --></mj-raw>
<mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
<mj-raw><!--<![endif]--></mj-raw>
```

**Additional context**
Related issue 1561 I think:
https://github.com/mjmlio/mjml/issues/1561

**Comment by iRyusa** [comment]
I'm not sure if i understood completely but this might be fixed in 4.4.

**Comment by WilsonBrett** [comment]
Thanks, some of my original post wasn't rendering correctly but I think I fixed everything.

**Comment by iRyusa** [comment]
Well I think this is not fixed at all in MJML4.4 the fix on ending tag has
been shipped in MJML4.3. That's a bit annoying and I honestly don't have
any idea on how to handle that properly might to check if we're able
somehow to hack htmlparser for that :(

**Comment by kmcb777** [comment]
@WilsonBrett  After further examination, it turns out that even if we do hacky stuff to parse conditional comments in a different way than regular comments, the mjml components you'll put between them probably won't work.
Most mjml components use conditional comments when rendering, and i suppose nesting conditionals wouldn't work well.
If you want a mj-text that only displays on outlook (or the opposite), the best way would be to create a custom component that extends MjText, and override the render function so that the whole output is in one single conditional

**Comment by WilsonBrett** [comment]
Ok thanks @kmcb777 for looking into and for the suggestion.

**Comment by kmcb777** [comment]
There is no real solution for this problem, it would require tricky hand-made parsing and the result still wouldn't work properly as it is. The best solution is a custom component, so i think we can close this
