### ISSUE TITLE
MJ-Group with 2 columns fails on iOS Gmail

### ISSUE THREAD

**Issue by voermansm** [mjmlio/mjml#1568]
**Describe the bug**
MJ-Group doesn't keep columns side by side in Gmail.

If you place HTML comments around the MSO code to remove whitespace between tags it works. However its odd that the font-size:0 isn't fixing that.

**To Reproduce**
https://mjml.io/try-it-live/ByFluGLFV - MJML code
https://litmus.com/builder/7b8154f - Litmus test
https://litmus.com/checklist/emails/public/e176f1c#gmailios iOS Gmail specific

**Expected behavior**
The columns should remain side by side as grouped columns do.

**MJML environment (please complete the following information):**
- MJML: Try it live: 4.3.0

**Email sending environment(for rendering issues)**:
 - Pasted output HTML into Litmus

**Affected email clients (for rendering issues):**
- iOS Gmail (note, not affecting Android Gmail)

**Comment by iRyusa** [comment]
Did you minified your code as stated in the documentation ?

**Comment by voermansm** [comment]
Thanks for the quick response. I didn't realize that was required. I thought I ran into this issue before, so I quit minifying: https://www.emailonacid.com/blog/article/email-development/line-length-in-html-email/ Sorry I don't have tests to prove that at the moment. Perhaps you know off hand if your minifier is starting new lines before 998 though.

**Comment by iRyusa** [comment]
Well we send a lot of mjml emails daily minified and never encounter any issue with our minifier config. As the bug is in webkit there’s other way around ( or remove spaces manually... )
