### ISSUE TITLE
Social icon background size

### ISSUE THREAD

**Issue by jsphkm** [mjmlio/mjml#1571]
**Is your feature request related to a problem? Please describe.**
I'm unable to change the size of the background of the social elements with my custom icons

<img width="35" alt="Screen Shot 2019-04-09 at 4 27 27 PM" src="https://user-images.githubusercontent.com/28643797/55841623-c7a47d00-5ae4-11e9-8172-77224ca8353e.png">

<img width="42" alt="Screen Shot 2019-04-09 at 4 31 13 PM" src="https://user-images.githubusercontent.com/28643797/55841666-ee62b380-5ae4-11e9-8d3e-beb2adbab435.png">

icon-size only adjusts the transparent icon, I need to adjust the size of the background-color element.

**Describe the solution you'd like**
I would like to be able to change the size of the color element

**Describe alternatives you've considered**
Not willing to create a colored circle icon

**Additional context**

**Comment by iRyusa** [comment]
Did you tried inner padding on social element ?

**Comment by jsphkm** [comment]
Ah, I got it with icon-padding on `mj-social`, thanks for the clue

**Comment by jsphkm** [comment]
I just noticed that the icon has the border-radius applied

<img width="41" alt="Screen Shot 2019-04-09 at 5 20 58 PM" src="https://user-images.githubusercontent.com/28643797/55843208-ef4b1380-5aeb-11e9-97ee-53208e6d2d9d.png">

This is the original
<img width="56" alt="Screen Shot 2019-04-09 at 5 22 32 PM" src="https://user-images.githubusercontent.com/28643797/55843237-173a7700-5aec-11e9-941b-ac4b42448d48.png">

The result looks the same when `border-radius` is applied to either `mj-social` or `mj-social-element`

**Comment by jsphkm** [comment]
I was able to manually turn it off using css-class:

```
<mj-style>
      .social-element img {
        border-radius: 0 !important;
      }
</mj-style>

...
<mj-social icon-size="20px" icon-padding="5px" mode="horizontal" border-radius="20px" >
    <mj-social-element css-class="social-element" href="url" background-color="#79b" src="img/external-facebookBoxed.png">
    </mj-social-element>
</mj-social>
```

It seems like the border-radius gets applied to both the `table` and the `img`.  For a second I thought I applied the padding incorrectly.
