### ISSUE TITLE
Why is cross-env a runtime dependency?

### ISSUE THREAD

**Issue by nexdrew** [mjmlio/mjml#1572]
Particularly when it comes to the `mjml-core` package, `cross-env` appears to be used at build-time only (via `npm run build` or `npm run clean`) - there are no references to `cross-env` in production code distributed in the published package.

As an application developer using mjml, I'm looking for ways to keep our dependency footprint (and thus, our security audit reports) as small as possible.

Are you open to moving `cross-env` to be a dev dependency instead?

**Comment by iRyusa** [comment]
You're right, it's only use in `package.json`. I think we didn't realized that when merging this PR #1091 ... Can you do a PR to fix this ?

**Comment by nexdrew** [comment]
> Can you do a PR to fix this ?

Yes, but it might take a day or two. I'm not super familiar with using lerna or yarn, so I'll probably have to experiment a bit to make sure I'm updating parent package.json and all the yarn.lock files appropriately, but I'll carve some time out to make this happen soon-ish. Thanks.
