### ISSUE TITLE
document additional support for css-class

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1574]
**Describe the bug**
Documentation discrepancy. Reported by `@Thor Haakon Thor Brunstad` at https://mjml.slack.com/archives/C12HESC2G/p1554981547035600.

On one hand, the documentation says, under `mj-style`, "Here is an example showing the use in combination with the `css-class` attribute, _which is supported by all body components_." (emphasis added)

On the other hand, the lists of attributes supported for `mj-navbar`, `mj-navbar-link`, `mj-raw`, `mj-social`, `mj-social-element`, and `mj-table` don't include `css-class`.

Except for `mj-raw`, there are references below to demonstrations that all those _do_ support `css-class`. 

**To Demonstrate Support for `css-class`**
For each Try-It-Live below, misspell a class name in the `mj-style` (add or delete one character, for example). Observe that the result matches the documentation. Restore the spelling. Observe that the result is consistent with the attributes in the class.

MJML element                                 | Try-It-Live
---------------------------------------|----------------------
`mj-navbar` and `mj-navbar-link`    | [for `mj-navbar` and `mj-navbar-link`](https://mjml.io/try-it-live/BJiXIOaKN)
`mj-social` and `mj-social-element` | [for `mj-social` and `mj-social-element`]()
`mj-table`                                         | [for `mj-table`](https://mjml.io/try-it-live/Sykg5KTYV)

**Expected behavior**
`css-class` should be in supported attribute lists for `mj-navbar`,`mj-navbar-link`,  `mj-social`, `mj-social-element`, and `mj-table`.

**MJML environment (please complete the following information):**
 - OS: Win10
 - MJML Version [e.g. 4.2.0]: 4.3.0
 - MJML tool used [e.g MJML App]: Try-It-Live

**Email sending environment(for rendering issues)**:
 Doesn't apply.

**Affected email clients (for rendering issues):**
 Doesn't apply.

**Screenshots**
See Try-It-Live.

**Additional context**
No further.

**Comment by kmcb777** [comment]
@GarryFlemings Thanks for pointing that out, all mj-column direct children indeed support css-class, it's handled by the mj-column component
