### ISSUE TITLE
MJML HERO is not taken account within Laposte’s webmail 

### ISSUE THREAD

**Issue by user-12** [mjmlio/mjml#1575]
**Describe the bug**
Through https://webmail.laposte.net/, the background image of the MJML hero component is not displayed: the fallback background color is visible instead.
![render](https://user-images.githubusercontent.com/6585723/56045659-ee132400-5d41-11e9-973b-9c29b83489e9.jpg)

Apparently, this webmail is overwritten the default background property (see screenshot).

![css-classe](https://user-images.githubusercontent.com/6585723/56045524-b2785a00-5d41-11e9-91c3-574f1da4f80d.PNG)

Is a hack possible to avoid this?

**To Reproduce**
1. Create or use a French La Poste’s account here: https://www.laposte.net/accueil
4. Send an HTML with the hero component

**MJML environment :**
 - OS: Window
 - MJML Version 4.2.0
 - MJML tool used : MJML visual Studio Plugin

**Affected email clients :**
 - Email Client : https://webmail.laposte.net/,  
 - OS:. Windows
 - Browser : Google Chrome

**Comment by iRyusa** [comment]
Well as laposte clearly mess with background property I don't think we can support it :/
