### ISSUE TITLE
Want to change the way the columns stack

### ISSUE THREAD

**Issue by jsphkm** [mjmlio/mjml#1577]
**Is your feature request related to a problem? Please describe.**
I would like to distribute columns horizontally on small screen and vertically on big screen, the opposite of the default behavior

This is the same effect as what I see on a yelp email

Small Screen:
<img width="470" alt="Screen Shot 2019-04-12 at 7 47 47 PM" src="https://user-images.githubusercontent.com/28643797/56073766-e6fa0f00-5d5d-11e9-9a6c-8bcfccfb4807.png">

Large Screen:
<img width="768" alt="Screen Shot 2019-04-12 at 7 48 05 PM" src="https://user-images.githubusercontent.com/28643797/56073774-f9744880-5d5d-11e9-92af-3569b9637ed4.png">

The photo and the business details are horizontally aligned on a small screen, and is vertically aligned on a large screen.

**Describe the solution you'd like**
I would also like to be able to define the breakpoint of this if possible.

**Comment by iRyusa** [comment]
Hi,

As pointed on Slack the best direction would be to play with `mj-style` and media queries.
This won't be available "out-of-the-box" on MJML. Don't forget to use and... abuse of `!important` and feel free to share the result here 👍

**Comment by tpetry** [comment]
@jsphkm We currently do this by adding both variants to our mails and selectively display one of them based on media queries: https://github.com/mjmlio/mjml/issues/1182
