### ISSUE TITLE
How to place images in lines with small intervals?

### ISSUE THREAD

**Issue by StanZhuravlev** [mjmlio/mjml#1578]
I need to place the icons of social networks in a letter in one row. I did this as follows.

> <mj-section background-color="#ddc7f6">
    <mj-group>
        <mj-column>
            <mj-image mj-class="social" href="https://link......." src="mails/social/twitter.png"/>
        </mj-column>
        <mj-column>
            <mj-image mj-class="social" href="https://link......." src="mails/social/twitter.png"/>
        </mj-column>
        <mj-column>
            <mj-image mj-class="social" href="https://link......." src="mails/social/twitter.png"/>
        </mj-column>
        <mj-column>
            <mj-image mj-class="social" href="https://link......." src="mails/social/twitter.png"/>
        </mj-column>
        <mj-column>
            <mj-image mj-class="social" href="https://link......." src="mails/social/twitter.png"/>
        </mj-column>
        <mj-column>
            <mj-image mj-class="social" href="https://link......." src="mails/social/twitter.png"/>
        </mj-column>
    </mj-group>
</mj-section>

With this code, the pictures are stretched in width and look ugly (the upper picture in the image below, marked as "NOW"). And I need to make them more concise (need make a small interval), as shown in the picture at the bottom (marked as "I WANT").

![mjml-social-icons](https://user-images.githubusercontent.com/2879873/56097725-f36a9d00-5f00-11e9-8cba-9468e5c9fee8.jpg)

How can I do it right?

**Comment by iRyusa** [comment]
You should use mj-social instead, it should be way easier.

**Comment by StanZhuravlev** [comment]
@iRyusa, yes, thank you very much! :)
