### ISSUE TITLE
support images

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1579]
**Is your feature request related to a problem? Please describe.**
No problem.
Candidate for the roadmap, maybe.
Candidate for "help needed", maybe.
Motivation: _Using images and graphics in HTML markup often pays off in easier reading and more user acceptance._

It'd be great to support images in MJML components where they can't currently go. I'll make a case here for `mj-accordion`.

[Outside of scope for this issue; only a side comment: Probably there's a case to make for `mj-button` and maybe for `mj-navbar`. I'll leave those issues to others or get back to these components later.]

**Describe the solution you'd like**
I'd like MJML users to have an easy way of including and positioning images inside `mj-accordion-text` and `mj-accordion-title` elements, and between `mj-accordion-title` elements. To the extent that sentence is three suggestions, it reflects my priority, too:  `mj-accordion-text`, then `mj-accordion-title`, and then between `mj-accordion-title` elements.

A possibility for `mj-accordion-text`: Give `mj-accordion-text` elements the ability `mj-text` already has, that (from the documentation) " `MjText` can contain any HTML tag with any attributes. Don't forget to encode special characters to avoid unexpected behaviour from MJML's parser".

Another: Support `mj-image` within `mj-accordion-text`.

Another: Support `img` enclosed within `mj-raw`.

A possibility for `mj-accordion-title`: Support pictures either left or right. They'll always be visible with the title. Perhaps the implementation will limit their height to that of the title element.

Perhaps the title text becomes optional, in which case there'd be no need to restrict the width of the image. In this case, the accordion appearance moves a little closer to the carousel; the function remains distinct---to expose and hide text, rather than to jump elsewhere.

A possibility for putting images between `mj-accordion-title` elements: Images would always be visible and positioned between `mj-accordion-title` elements. Perhaps the accordion would flow around the image. Perhaps MJML would support left and right positions only.
Maybe this design is unacceptable: Images might be perceived as interrupting the cohesion of the accordion .

**Describe alternatives you've considered**
1. I placed `mj-image` within `mj-accordion-text` (https://mjml.io/try-it-live/S1Qdq7g5E). It got no warning and didn't render.

2. I placed `mj-raw` and `img` within `mj-accordion-text` (https://mjml.io/try-it-live/HydJMVxcV). It always rendered (`mj-accordion-text` either open and closed).

**Additional context**
None.

**Comment by iRyusa** [comment]
Well, those tag already support plain html so you can just use the `img` tag instead of mj-image.

I'm closing this.
