### ISSUE TITLE
Mailchimp is clearing/removing styles in head

### ISSUE THREAD

**Issue by mio31337** [mjmlio/mjml#1581]
My built HTML email templates were just another ones that I did for my client. Everything was smooth and perfect with the emails in all email clients (dekstop and mobile), until the client decided to switch to Mailchimp. The main issues was on Gmail App (iOS and Android). Everywhere else worked just fine as expected.

After a couple of hours scratching my head around, I finally found a bug that was causing Mailchimp to "strip" and in my opinion "comment out" all my styles and media queries from head. This caused the problem only for Gmail App.

I basically went on test-grinding and tested part by part of the source code from head until I finally came to a little piece of code "<!-->" that shouldn't even be there.

After I removed this opening HTML comment (usually on 2 spots after mjml generated my HTML file), I finally got it working in Mailchimp as expected. My styles in head were still there, mobile responsive layout was 100% there!

The code that MJML automatically adds and it should be removed manually:

![image](https://user-images.githubusercontent.com/722467/56363815-4c7e4d80-61ed-11e9-8cf3-9d5084e11233.png)

![image](https://user-images.githubusercontent.com/722467/56363855-6c157600-61ed-11e9-88af-9d81577e4dda.png)

Hopefully you get this fixed quickly.

**Comment by iRyusa** [comment]
Well they shouldn't alter the HTML at all to be fair.

We use this solution as stated in this litmus topic, https://litmus.com/community/discussions/982-outlook-overrides-font-to-times-new-roman , so I believe this extra `<!-->` is needed ?

I don't know,  can you test a bit with litmus/eoa if it doesn't transform every text to Times when removing it ?

**Comment by mio31337** [comment]
> Well they shouldn't alter the HTML at all to be fair.
> 
> We use this solution as stated in this litmus topic, https://litmus.com/community/discussions/982-outlook-overrides-font-to-times-new-roman , so I believe this extra `<!-->` is needed ?
> 
> I don't know, can you test a bit with litmus/eoa if it doesn't transform every text to Times when removing it ?

Yeah, I know. They shouldnt...

Since my post, I've been testing on all kinds of service providers - all looks perfectly fine without `<!-->`

**Comment by Skjolbir** [comment]
> > Well they shouldn't alter the HTML at all to be fair.
> > We use this solution as stated in this litmus topic, https://litmus.com/community/discussions/982-outlook-overrides-font-to-times-new-roman , so I believe this extra `<!-->` is needed ?
> > I don't know, can you test a bit with litmus/eoa if it doesn't transform every text to Times when removing it ?
> 
> Yeah, I know. They shouldnt...
> 
> Since my post, I've been testing on all kinds of service providers - all looks perfectly fine without `<!-->`

I've switched from mailchimp to campaign monitor. Couldnt stand that you had to manually enter image dimensions everytime you change an editable image. Fine for me, but my clients... they want more one-two click solutions without having to think about stuff like image scaling.
