### ISSUE TITLE
Break after <mj-section> Outlook for Mac

### ISSUE THREAD

**Issue by jarrodwhitley** [mjmlio/mjml#1583]
In Outlook for Mac v16.24 there are gaps (possibly margins I can't tell) after each <mj-section>

This is how it should appear:
<img width="988" alt="Screen Shot 2019-04-22 at 9 23 47 AM" src="https://user-images.githubusercontent.com/11711674/56505896-7e8bfa00-64e2-11e9-8150-a575baed9040.png">

This is how is appears in Outlook:
![Screen Shot 2019-04-22 at 9 23 31 AM](https://user-images.githubusercontent.com/11711674/56505903-82b81780-64e2-11e9-9f8a-a6781c67c745.png)

<mjml>
  <mj-body background-color="#d7dde5">
    <mj-section background-color="#ffffff">
      <mj-column width="100%" vertical-align="middle">
        <mj-image src="https://boomerbenefits.com/wp-content/uploads/2019/04/bb-logo-email@2x.png" alt="Boomer Benefits" padding-bottom="0px" padding-top="10px" width="300px"></mj-image>
      </mj-column>
    </mj-section>
    
    <mj-section background-color="#2780bc">
      <mj-column width="50%" vertical-align="middle">
        <mj-image width="150px" src="https://boomerbenefits.com/wp-content/uploads/2019/04/danielle-circle.png"></mj-image>
      </mj-column>
      <mj-column width="50%" vertical-align="middle">
        <mj-text css-class="hero-text" font-family="Helvetica, Arial, sans-serif"  font-size="14px" font-weight="600" color="#fff" padding-left="0" padding-right="0" vertical-align="middle"><span style="font-size: 40px; line-height: 50px;">Medicare<br/>Mini-Course</span></mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#ffffff" vertical-align="top">
      <mj-column vertical-align="top" width="100%">
        <mj-text font-family="Helvetica, Arial, sans-serif" align="left" color="#555" font-size="16px" padding-bottom="30px" padding-top="3px"><span style="font-size: 16px; color: #555; line-height: 20px;">Let's dive right in with <b>Email Lesson 1 - Medicare Starts with the Parts</b></span><br/><br/>I created a checklist that will help you through this course. Each lesson corresponds
          to one step on the checklist; making it easy to track your progress. You can download it by clicking here!
          <br/><br/> Put all that away! Don't put the cart before the horse, and let's be honest, most of it is trash. For today, I want you to forget all that mail about Medigap plans. Just focus on learning about the Parts of Original Medicare. Understanding
          what each part covers will give you a foundation for all the other decisions ahead of you.
          <br/><br/> I've also included the video that goes along with this lesson at the bottom, watch it to get a summary!</mj-text>
      </mj-column>
    </mj-section>

    <mj-section vertical-align="middle" background-color="#ffffff" padding="0">
      <mj-column width="100%" vertical-align="middle" padding="0">
        <mj-text font-family="Helvetica, Arial, sans-serif" align="center" padding="0" color="#555" font-size="25px">Medicare Starts with the Parts</mj-text>
      </mj-column>
    </mj-section>

    <mj-section vertical-align="middle" background-color="#ffffff">
      <mj-column width="50%" vertical-align="middle">
        <mj-image src="https://boomerbenefits.com/wp-content/uploads/2019/04/hospital.png" alt="" padding-bottom="20px" padding-top="20px" width="150px"></mj-image>
        <mj-text font-family="Helvetica, Arial, sans-serif" align="center" color="#555" font-weight="600" font-size="20px">Part A</mj-text>
      </mj-column>
      <mj-column width="50%" vertical-align="middle">
        <mj-image src="https://boomerbenefits.com/wp-content/uploads/2019/04/medical-kit.png" alt="" padding-bottom="20px" padding-top="20px" width="150px"></mj-image>
        <mj-text font-family="Helvetica, Arial, sans-serif" align="center" color="#555" font-weight="600" font-size="20px">Part B</mj-text>
      </mj-column>
    </mj-section>

    <mj-section vertical-align="middle" background-color="#ffffff" padding="0">
      <mj-column width="100%" vertical-align="middle" padding="0">
        <mj-text font-family="Helvetica, Arial, sans-serif" align="left" color="#555" font-size="16px" padding-bottom="30px" padding-top="3px"><span style="font-size: 18px; color: #555; line-height: 20px;"><b>Original Medicare is made up of 2 parts:</b></span><br/><br/>Part A Hospital Insurance &amp; Part B Outpatient Insurance. (Part C &amp; D came later - and we'll address those further
          in the course)
          <br/><br/> As part of today's lesson, you'll want to read about the Parts of Medicare and what each covers here.
          <br/><br/> Tomorrow, we'll be delving into determining YOUR ANTICIPATED COSTS FOR MEDICARE. And if you're ahead of the curve and want to get started on finding your coverage, feel free to email me to request personal help.<br/><br/>Oh - I almost
          forgot! Stay tuned for a link to our next free New to Medicare Webinar. (I'll give you details in tomorrow's email.)
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#ffffff" >
      <mj-column width="100%" vertical-align="middle">
        <mj-image href="https://www.youtube.com/watch?v=VtSGMsZCO38&feature=youtu.be" src="https://boomerbenefits.com/wp-content/uploads/2019/04/watch-video.png" alt="Boomer Benefits" padding-bottom="0px" padding-top="10px"></mj-image>
      </mj-column>
    </mj-section>

    <mj-section>
      <mj-column width="100%" padding="0">
        <mj-social font-size="15px" icon-size="30px" mode="horizontal" padding="0" align="center">
          <mj-social-element name="facebook" href="https://mjml.io/" background-color="#A1A0A0">
          </mj-social-element>
          <mj-social-element name="twitter" href="https://mjml.io/" background-color="#A1A0A0">
          </mj-social-element>
          <mj-social-element name="pinterest" href="https://mjml.io/" background-color="#A1A0A0">
          </mj-social-element>
          <mj-social-element name="instagram" href="https://mjml.io/" background-color="#A1A0A0">
          </mj-social-element>
          <mj-social-element name="linkedin" href="https://mjml.io/" background-color="#A1A0A0">
          </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>

    <mj-section>
      <mj-column width="100%" vertical-align="middle">
        <mj-text align="center" font-size="11px" padding-bottom="0px" padding-top="0px">
          <p style="font-size: 11px">[[DELIVERY_INFO]]</p>
        </mj-text>
        <mj-text align="center" font-size="11px" padding-bottom="0px" padding-top="0px">
          <p style="font-size: 11px">[[POSTAL_ADDRESS]]</p>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by kmcb777** [comment]
@jarrodwhitley I just tested on emailonacid and it renders fine on all outlooks
Outlook for mac is less likely to have issues than on windows, it could be your email provider altering the html, how did you send the email ?

**Comment by jarrodwhitley** [comment]
@kmcb777 I'm using Drip and sending myself a test email. Since the email spoofs the domain the email automatically goes to my boss, who forwards it to me. He's using a PC. He said that the email looks like that in his inbox.

**Comment by kmcb777** [comment]
@jarrodwhitley it can be Drip altering the html when you send it, sadly many providers seem to do this.
Can you try to send it with https://putsmail.com/tests/new (don't check the "Move my css inline")
If it works with putsmail, then it is definitely Drip altering the html

**Comment by ngarnier** [comment]
Also note that forwarding an email breaks the layout because receiving servers alter the HTML when they render it, it's a well-known problem with email.

**Comment by jarrodwhitley** [comment]
@kmcb777 I'll give that a try and see how it works. Thanks for the tip @ngarnier

**Comment by jarrodwhitley** [comment]
@kmcb777 You were correct. When went with putsmail the email looks correct on Outlook. Thanks for help fellas.
