### ISSUE TITLE
Add support to set body margin/padding using mj-attributes

### ISSUE THREAD

**Issue by robertgaal** [mjmlio/mjml#1586]
**Is your feature request related to a problem? Please describe.**
I'm currently creating a campaign where there is no real body container, and it resembles a normal plain-text email closely. This means I'd like clients to decide on their own what the padding or margin for the email should be. This means removing the "margin/padding: 0" CSS from the generated HTML source by MJML.

**Describe the solution you'd like**
It would be great if mj-attributes would allow me to set `<mj-body margin="initial" padding="initial" />'.

**Describe alternatives you've considered**
Any inline CSS can't seem to fix these issues.

Thanks for considering! Love what you've built.

**Comment by kmcb777** [comment]
Hi @robertgaal the problem is that mj-body is not really a mj-component, it's handled completely differently.
Since the body style is in the head, not inlined, if you use a mj-style, it should be ok ?
```
  <mj-head>
    <mj-style>
    	body {
      	  margin: initial;
      	  padding: initial;
        }
    </mj-style>
  </mj-head>
```

**Comment by handhikadj** [comment]
@kmcb777 
what is the workaround for this?
this is not working on gmail app:
```
body {
  padding: 20px;
}
```

**Comment by mihanizm56** [comment]
> @kmcb777 what is the workaround for this? this is not working on gmail app:
> 
> ```
> body {
>   padding: 20px;
> }
> ```

same situation, gmail can not add paddings to body

**Comment by eranbetzalel** [comment]
If you aim to achieve full width, you can use a width of ```4096px``` on ```mj-body```.

Worked for me.

**Comment by iRyusa** [comment]
Just dont do that.
