### ISSUE TITLE
Make it possible to disable the auto webfont injection

### ISSUE THREAD

**Issue by Windvis** [mjmlio/mjml#1588]
**Is your feature request related to a problem? Please describe.**
I'm using the following code to apply a "system-ui" font stack to the email template:
```html      
<mj-all font-family="-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen-Sans,Ubuntu,Cantarell,'Helvetica Neue',sans-serif" />
```
I noticed mjml automatically adds links to Google fonts, when they are included in a font-family attribute. So this results in the following code:

```html
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css">
<style type="text/css">
  @import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);
  @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);
</style>
```

Is it possible to disable that behaviour? I'm using that system font stack to make sure clients use the native fonts, but adding the webfonts might "force" them to use a different font.

**Describe the solution you'd like**
Add an extra flag to the cli which disables this auto font injection logic.

**Describe alternatives you've considered**
Add properties to certain mjml components (mj-head?) to disable this behaviour

**Comment by iRyusa** [comment]
I think we did something not so long ago like --config.fonts={} to override
default font can you give it a try ?

**Comment by Windvis** [comment]
@iRyusa Yup, that seems to work. Thanks!

I checked the CLI documentation but didn't find anything relevant.
