### ISSUE TITLE
Support background on mj-text

### ISSUE THREAD

**Issue by EmmanuelBeziat** [mjmlio/mjml#159]
Hi there,

I'm in need of using a background on mj-text component right now. I'm not able to find a good workaround with this (outlook don't allow padding certain tags)…

This would be a good feature to add, imo.

Thanks!

**Comment by arnaudbreton** [comment]
Thanks @EmmanuelBeziat for sharing! We'll look into it and come back to you shortly.

**Comment by iRyusa** [comment]
Hello !

Now in MJML 2 you can add a `container-background-color` on any column-element https://mjml.io/documentation/#mj-text

**Comment by EmmanuelBeziat** [comment]
Cool, thanks ;)
