### ISSUE TITLE
Content inside mj-column is not fully expanded for Outlook 2016 & 2019

### ISSUE THREAD

**Issue by vai0** [mjmlio/mjml#1593]
**Describe the bug**
Content inside an mj-column is not being properly rendered in Outlook 2016 and Outlook 2019. The content inside seems to not expand to 100% of the width of it's parent, as a result, the content edges towards the left of the screen.

**To Reproduce**

Demo: https://mjml.io/try-it-live/SyrdmNIo4

In Litmus (testing tool),
Outlook 2019 (Windows 10)
![image](https://user-images.githubusercontent.com/1195698/56992724-89ccce80-6b4f-11e9-94c5-408735393994.png)

Outlook 2016 (Windows 7)
![image](https://user-images.githubusercontent.com/1195698/56992672-73267780-6b4f-11e9-8c52-1c8b0716b599.png)

**Expected behavior**
Content should be centered, and not edge towards the left.

It looks fine across all other email clients tested.
![image](https://user-images.githubusercontent.com/1195698/56992855-d6b0a500-6b4f-11e9-963e-29675c7c51f5.png)

**MJML environment (please complete the following information):**
 - OS: Linux
 - MJML tool used: MJML Live, VScode MJML extension.

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Litmus

**Affected email clients (for rendering issues):**
 - Email Client: Outlook
 - OS: Windows
 - Browser: Unknown

**Additional context**
Keep up the good work :) Absolutely love MJML

**Comment by iRyusa** [comment]
Well that's an issue on Outlook applying all left & right padding on...
right side. For some reasons (you can find more on this one on #128), it
doesn't like nested table inside a VML block, just remove the padding
left/right inside it and it will be fine.

Note that those client doesn't support cover & no repeat so you most likely
still have an issue on how the background is displayed. if you want a
better effect just reduce the size of the background to match your mj body
width

**Comment by vai0** [comment]
Understood, thank you! Closing
