### ISSUE TITLE
Docs: Code block in community components section isn't rendering correctly.

### ISSUE THREAD

**Issue by bradtgmurray** [mjmlio/mjml#1594]
https://mjml.io/documentation/#community-components is missing the sample content of a .mjmlconfig file.

Compare:
![image](https://user-images.githubusercontent.com/33967/57018084-f1d2f180-6bef-11e9-952e-1ad51fa19801.png)

With: https://github.com/mjmlio/mjml/blob/dad233f7c8dc6ce92845eb048ef743e38e66ce52/doc/community-components.md

The markdown file has the code block, but the generated docs do not

**Comment by ngarnier** [comment]
hey @bradtgmurray, maybe I misunderstood, but the code block is visible in the docs for me: 

![](https://puu.sh/DmLZr/2cf40f26c6.png)

Or did I get you wrong?

**Comment by bradtgmurray** [comment]
Whoops, right you are. The colon at the end of the sentence made me look inline and not to the left.
