### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by JustMeCodex** [mjmlio/mjml#1595]
Hi,

Is there a detailed documentation of V3 that contains attributes support for each component?

This would be V4 https://mjml.io/documentation/#mjml-guides We are currently using v3.

Thanks

**Comment by iRyusa** [comment]
Hi

Everything is still in the repo here:  https://github.com/mjmlio/mjml/tree/3.3.x , every package has a README.md that contains every attributes and examples.
