### ISSUE TITLE
Center mj-table

### ISSUE THREAD

**Issue by Isabellle** [mjmlio/mjml#1598]
**Is your feature request related to a problem? Please describe.**
Ability to center a table 

**Describe the solution you'd like**
margin="auto" or that the text-align="center" on the section also applies on tables

**Describe alternatives you've considered**
Putting left and right padding, but tricky

**Comment by iRyusa** [comment]
Hi,

`mj-table` already support `align` attribute. It does work only when the `width` is set, by default mj-table width match the column width. Here's an example https://mjml.io/try-it-live/Hkq8SyQhV
