### ISSUE TITLE
Background-repeat error

### ISSUE THREAD

**Issue by victordarras** [mjmlio/mjml#16]
When I'm using a __<mj-section>__ with a background-url and a repeat rule, the rendered CSS is broken.

source :
```
<mj-section 
  background-repeat="repeat-x" 
  background-url="http://www.synbioz.com/images/articles/background_bleu.gif">
```

styles rendered :
```
width:100%;
font-size:0px;
background:url(http://www.synbioz.com/images/articles/background_bleu.gif) top center / repeat-x;
```

See the "/" caraxtere has nothing to do here and break the rule .

**Comment by iRyusa** [comment]
Hello @victordarras , 

I'm sorry this is an unexpected behaviour from MJML, `mj-section` expect to have a `background-size` attribute to generate a proper css rule. You can add `background-size="auto"`to fix it temporarily, I'll open a PR to set it by default.

Keep in mind that at the moment we didn’t find any way to support `background-repeat` in VML for outlook 2007/2010/2013

**Comment by victordarras** [comment]
Thank you for your answer, if I find a better solution for background-repeat I'll fork the repo ;)
