### ISSUE TITLE
mj-button is not full clickable in the new release

### ISSUE THREAD

**Issue by raphaelfabeni** [mjmlio/mjml#1600]
**Describe the bug**
`mj-button` is not full clickable.

**To Reproduce**
I've created a simple `mjml` file to test:
```
<mjml>
	<mj-head></mj-head>
	<mj-body>
		<mj-section>
			<mj-column>
				<mj-button href="https://www.globo.com">Test</mj-button>
			</mj-column>
		</mj-section>
	</mj-body>
</mjml>
```
**Expected behavior**
I think as I'm using the new version the `mj-button` component should be clickable.

**MJML environment (please complete the following information):**
 - OS: v10.14.4 Mojave
 - MJML 4.4.0-beta.1

**Email sending environment(for rendering issues)**:
 - I've done some tests using _email on acid_ but even testing in a simple HTML file we can see the bug.

**Affected email clients (for rendering issues):**
- All of them ( I know it won't work in Outlook).

**Screenshots**
![May-13-2019 18-21-28](https://user-images.githubusercontent.com/1345662/57655213-7a686f00-75ac-11e9-898b-486d0df88232.gif)

**Comment by iRyusa** [comment]
Can you just follow the main thread instead of opening a new one with
absolutely no details  ?  https://github.com/mjmlio/mjml/issues/359

**Comment by raphaelfabeni** [comment]
Sure! Thanks!

**Comment by raphaelfabeni** [comment]
Hey @iRyusa .. my bad!
Just fixed some stuff locally here and it worked!
Thanks! :)

**Comment by orliesaurus** [comment]
Hey @raphaelfabeni how did you fix it? Would be nice to know how you did it so I can do it myself! Ty
