### ISSUE TITLE
mj-style removes !important

### ISSUE THREAD

**Issue by nnDjeff** [mjmlio/mjml#1602]
**Describe the bug**
As stated in the title, if you use !important for a specific value, it isn't added to the generated HTML.

**To Reproduce**
Inspect any text on this generated file https://mjml.io/try-it-live/components/head-style

**Expected behavior**
!important should be added to the inline styles.

**MJML environment (please complete the following information):**
 - OS: MacOS (Chrome)
 - MJML Version 4.3.0
 - MJML tool used MJML Live editor and MJML Node locally

**Email sending environment(for rendering issues)**:
 - Tested on Emailonacid. Issue presents itself on the web versions of Outlook / Office 365.

**Affected email clients (for rendering issues):**
 - Same as above.

**Comment by iRyusa** [comment]
Hi,

cc @kmcb777 we should just add an option to extend juice config as we do on minify.
