### ISSUE TITLE
Ignore "compileFiles errors"

### ISSUE THREAD

**Issue by daraclare** [mjmlio/mjml#1606]
**Describe the bug**
We are using MJML ( using Java for templating) Currently on v.4.0.3, compiling and email sending works fine. However, when I update to v4.3.x or anything higher than 4.0, I get errors when compiling as MJML does not recognise our templating language (Java), and the compiling fails, eg:

```
 { line: 23,
    message:
     'Attribute background-color has invalid value: ${agentBackgroundColor} for type Color ',
    tagName: 'mj-column',
    formattedMessage:
     'Line 23 of /Users/username/Code/my-emails/projects/xxx/templates/\', \'*.mjml (mj-column) — Attribute background-color has invalid value: ${agentBackgroundColor} for type Color ' }

compileFiles error: Error: Issue Compiling
  
```

Is there anything I can do to ignore errors when they relate to templating so I can update my version of MJML? 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a file with this MJML code: 

```
<mjml>
<mj-head>
    <mj-title>${subject}</mj-title>
    <mj-include path="../common/head-defaults.mjml" />
  </mj-head>
 <mj-body>
 <mj-wrapper padding="0 4px" background-color="#f1f1f1" full-width="full-width">
 <mj-section padding="30px 0 0 0">
        <mj-raw>
          <#if developmentBrandColor?has_content>
            <#assign developerBackgroundColor=developmentBrandColor>
              <#else>
                <#assign developerBackgroundColor='#f1f1f1'>
          </#if>
        </mj-raw>
        <mj-column background-color="${developerBackgroundColor}" width="100%">
          <mj-raw>
            <#if developmentLogo?has_content>
              <div style="text-align: center; padding: 4px 0;">

                <img src="${developmentLogo}" alt style="width: auto; max-width: 252px; max-height: 54px; height: auto; vertical-align: middle" />
              </div>
            </#if>
          </mj-raw>
          <mj-image src="${photoUrl}" alt padding="0" href="${ctaUrl}" />
        </mj-column>
      </mj-section>
 </mj-wrapper>
</mj-body>
</mjml>
```

2. try to compile it using node in terminal
3. See error

**Expected behavior**
When using the version 4.0.x I could compile without errors, would like to be able to do the same.

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS] MacOS
 - MJML Version [e.g. 4.2.0] 4.0.3
 - MJML tool used [e.g MJML App] Building in VSCode, compiling with node in terminal with Sending with our own email tool

**Email sending environment(for rendering issues)**:
 Not relevant as issue is with compiling only.

**Affected email clients (for rendering issues):**
Not relevant as issue is with compiling only.

**Screenshots**
Not relevant as issue is with compiling only.

**Comment by iRyusa** [comment]
Hello ! 

Well, two way to fix that : 

- either apply your variable before compiling MJML
- or you just ignore the file validation by setting `validationLevel` to `skip`, if you're using the terminal then `--config.validationLevel=skip` should do the trick, but then it won't raise any error (like not using the proper tag in another).

Maybe we should add a flag to ignore typecheck rules for people using template attribute heavily cc @kmcb777 or just extend the typechecker to find most common var pattern and ignore errors ?

**Comment by daraclare** [comment]
Thanks @iRyusa we can't go with the first option, so I reckon the second is what we need, thanks. It would be great if we could turn off the check for one line only, and keep it for everywhere else, similar to `/*eslint-disable-next-line*/` or allow disabling of a certain rule maybe, similar to `/* eslint-disable no-alert, no-console */` 🤔 Just a thought, thanks again!!

**Comment by kmcb777** [comment]
yes, extend the typechecker to find most common var pattern and ignore errors would be absolutely possible
or we could expose an option to accept a specific pattern for all types

allow disabling for a specific line would be much heavier to handle unfortunately

**Comment by daraclare** [comment]
Sorry, I wasn't clear about how we are compiling, we are using Node, I was just running a command on the terminal to run the Node script. Unfortunately, using `{ validationLevel: 'skip' })` only removed some of the errors, the templates did not compile so I can't upgrade at the moment 😞Any workaround would be much appreciated.

**Comment by iRyusa** [comment]
You don't have any exception triggered ? Can you add `stack: true` to your config object if you're using the cli to have a bit more information about the issue ?

**Comment by kmcb777** [comment]
Hi @daraclare, using `validationLevel: 'skip'` should remove the error you reported (`Attribute background-color has invalid value`), do you have other errors then ?
Validation errors should never prevent a template from compiling.

**Comment by daraclare** [comment]
@kmcb777 @iRyusa Thanks, it is working now, I'm not sure why it didn't work before, I was trying a lot things, so maybe I changed something I shouldn't have 😬 Thanks for your help!
