### ISSUE TITLE
Documentation contains incorrect default value for mjml-carousel attributes left-icon and right-icon

### ISSUE THREAD

**Issue by NiklasSch** [mjmlio/mjml#1609]
The documentation contains incorrect default values for the mjml-carousel ([https://mjml.io/documentation/#mjml-carousel](https://mjml.io/documentation/#mjml-carousel)) attributes left-icon and right-icon.

**Comment by iRyusa** [comment]
👋 can you open a PR to fix this ?

**Comment by MaiJianxiang** [comment]
What does PR mean?

**Comment by iRyusa** [comment]
Pull Request
