### ISSUE TITLE
Text wrapping issue with Outlook 2016 when using mj-table component

### ISSUE THREAD

**Issue by sobolawdev** [mjmlio/mjml#1610]
**Describe the bug**
I'm running into the text-wrap issue in Outlook 2016 when using the `<mj-table>` component. Normally, it can be fixed using `mso-table-rspace` and `mso-table-lspace` but for some reason, it's not working. I need to figure out if it's an Outlook 2016 issue or an MJML issue.

**To Reproduce**

Code used: 
```               
<mj-table align="left">
                    <tr style="padding: 10px 0px">
                        <td valign="middle" style="color: #ed5432; font-size: 24px; font-family: Open Sans, Arial Semibold, Helvetica, sans-serif; vertical-align: middle; padding: 10px;">
                            <em>Lorem ipsum dolor sit amet, consectetur adipiscing elit</em>
                        </td>
                    </tr>
                    <tr style="background-color:#f2f2f2; line-height: 5px; height: 5px; font-size: 5px;">
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>
                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                <tbody>
                                    <tr>
                                        <td width="20">&nbsp;</td>
                                        <td style="vertical-align:top; padding:0px; margin:0px;">
                                            <table width="50" align="left" border="0" cellpadding="0" cellspacing="0" style="margin-right:5px;">
                                                <tbody>
                                                    <tr>
                                                        <td width="50">
                                                            <table align="left" border="0" cellpadding="1" cellspacing="1" style="margin-right:5px;">
                                                                <tbody>
                                                                    <tr>
                                                                        <td><img width="50" height="100" align="left" alt="placeholder image" src="https://placehold.it/50x100"></td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <span style="vertical-align:top; padding:0;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br>
                                            </span>
                                            <span style="vertical-align:top; padding:0;">
                                                <a href="http://duckduckgo.com" target="_blank" rel="noopener" style="color: #ed5432;">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a>
                                            </span>
                                        </td>
                                        <td width="20">&nbsp;</td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </mj-table>
```

**Expected behavior**
Tables shouldn't have a border covering text.

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: 4
 - MJML tool used: NPM CLI via WSL (Ubuntu 18.04)

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Constant Contact

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2016 
 - OS: Windows 10
 - Browser: N/A

**Screenshots**
Text wrapping issue using mj-tables:
![Annotation 2019-06-06 090411](https://user-images.githubusercontent.com/50915259/59036368-219f9580-883d-11e9-8bcb-6fd44d41e55d.png)

Desired outcome (sent on Outlook without mj-tables):
![Annotation 2019-06-06 090544](https://user-images.githubusercontent.com/50915259/59036449-54498e00-883d-11e9-8658-5ca8be9f390b.png)

**Comment by iRyusa** [comment]
I think it's more an issue from your HTML code inside `mj-table` the structure is rather complex to read, but it can be due to the margin, or even the span just mis-behaving when used right after a table.

**Comment by sobolawdev** [comment]
I looked at the raw HTML, and it seems like the align attribute isn't carrying over on `<mj-table>`. Manually adding it to the raw HTML file seems to alleviate the issue. Does `<mj-table>` support the align attribute?

**Comment by iRyusa** [comment]
Well the align will be applied to the table that wrap mj-table as any element in mj-column, it's weird that it comes only from that 🤔

Maybe we can add it here : https://github.com/mjmlio/mjml/blob/master/packages/mjml-table/src/index.js#L66

**Comment by kmcb777** [comment]
Hi @sobolawdev from what i see the problem seems more like outlook is ignoring the `style="margin-right:5px;"` on the tables.
On emailonacid i don't get the same result as yours for Outlook2016 on Win10. There is not margin between the text and the column, but the text is not cropped : 
<img width="617" alt="Screen Shot 2019-10-01 at 17 13 09" src="https://user-images.githubusercontent.com/8144509/65975397-d3a74100-e46e-11e9-885f-0d62d63927ca.png">
Is there anything else that could influence this bloc, maybe a mj-style ?
Btw if i remove `align="left"` on your mj-table i don't see any change so i don't think it's related to this
