### ISSUE TITLE
mj-social-element appending unnecessary text to href

### ISSUE THREAD

**Issue by calmworm** [mjmlio/mjml#1611]
**Describe the bug**
For Twitter, Facebook, and LinkedIn some unncessary text from each, is appended to the href. 
Twitter: "https://twitter.com/home?status="
Facebook: "https://www.facebook.com/sharer/sharer.php?u="
LinkedIn: "https://www.linkedin.com/shareArticle?mini=true&url="

These are the only 3 I am using in this situation, so other social-element's may have them too.

They appear as though they are set to "share" somehow, but I would like to just add an href url of my own choosing, which makes more sense.

**To Reproduce**
1. Use 'mj-social-element' 
2. Render to HTML
3. See links for social-elements

**Expected behavior**
href should be the URL I enter, and not append another URL

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version 4.2.0 (4.3.0)
 - MJML tool used VS Code extension and online editor

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by iRyusa** [comment]
It's the intended behavior 👍 

Cf the documentation : 

```
Supported networks with a share url:
- facebook
- twitter
- google
- pinterest
- linkedin
- tumblr
- xing

Without a share url:
- github
- instagram
- web
- snapchat
- youtube
- vimeo
- medium
- soundcloud
- dribbble

When using a network with share url, the href attribute will be inserted in the share url (i.e. https://www.facebook.com/sharer/sharer.php?u=[[URL]]). To keep your href unchanged, add -noshare to the network name. Example :

<mj-social-element name="twitter-noshare" href="my-unchanged-url">Twitter</mj-social-element>
```

**Comment by calmworm** [comment]
@iRyusa Apologies for not seeing this in the docs! Thank you so much for taking the time to answer. I am loving MJML, btw!
