### ISSUE TITLE
IOS Gmail app Roboto font problem

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#1612]
**Describe the bug**
I used Roboto font in my email. In Gmail App on Android Roboto works perfectly fine but on Gmail App on IOS Roboto font doesn't work and it is replaced by other font. 
1) Why is that? 
2) Is it possible to have Roboto font also in Outlook?

**To Reproduce**
I use mj-font to import Roboto from Google Fonts:
`<mj-font name="Roboto" href="https://fonts.googleapis.com/css?family=Roboto" />`

and for Outlook fallback font:
 `<mj-all font-family="Montserrat,Verdana" font-size="14px" color="#000" align="justify" />`

**Expected behavior**
I want Roboto works on IOS Gmail App.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version: 4.4.0-beta.2
 

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Hubspot

**Affected email clients (for rendering issues):**
 - Email Client: Gmail
 - OS: IOS

**Comment by iRyusa** [comment]
Well It's weird that it evens work on gmail android because gmail web
doesn't support any external font, nothing we can do on that part.

**Comment by ProdigyMaster** [comment]
https://twitter.com/kevinmandeville/status/989511569175384065?lang=en

It seems that Roboto is supported by GMail. Is it possible that `<mj-all>` overwrites it?

**Comment by iRyusa** [comment]
He might be referring to gmail web. Mjml isn’t related to anything here. You would see the same behavior with a small html template.

**Comment by BusinessInsiderMarketing** [comment]
I'm running into this issue as well. iOS Gmail alone swaps Roboto to another font.

Otherwise it shows up correctly on:
- Apple Mail
- Gmail (Android 13)
- Gmail (Chrome Desktop Mac OS/Windows)
- Outlook (Android)

Not sure what's causing the issue. I've tried putting in several fallback fonts close to Roboto, but they always default to another font on iOS Gmail alone.
