### ISSUE TITLE
Remove `.ExternalClass` rules in reset styles

### ISSUE THREAD

**Issue by hteumeuleu** [mjmlio/mjml#1614]
In the HTML code generated by MJML, the first `<style>` tag contains the following rules :

```
.ExternalClass {
   width: 100%;
}

.ExternalClass * {
    line-height: 100%;
}
```

This was useful for Outlook.com up to circa 2016. The new versions of Outlook.com since 2016 no longer use the `.ExternalClass` prefix.

These styles should be safely removed from the generated HTML.

**Comment by iRyusa** [comment]
Hey !

Let's add that change for the next 4.4 beta then. 👍  

Thanks !

**Comment by hteumeuleu** [comment]
After a bit more research, looks like the `.ReadMsgBody` selector in the reset styles also relate to older Outlook.com versions and no longer apply. So this can be safely removed as well:

```
.ReadMsgBody {
   width: 100%;
}
```

(See also [this thread](https://litmus.com/community/discussions/18-externalclass-and-readmsgbody-still-necessary-in-live-com-outlook-com) for a discussion on these selectors.)
