### ISSUE TITLE
<mj-soclial> Outlook problems

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#1617]
**Describe the bug**
Hey, I've got probelm with mj-social. It breaks on Outlook 2019, 2010, 2016 ... 
![mjml-issue](https://user-images.githubusercontent.com/528501/59591438-483bb700-90ee-11e9-9725-9f38a7c49460.PNG)

I should look like this:
![mjml-issue2](https://user-images.githubusercontent.com/528501/59591501-686b7600-90ee-11e9-909b-45a3ed20f796.PNG)

Outlook doesn't respect padding between elements, and vertical align of text.

**To Reproduce**

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="center" color="#555" />
      <mj-section background-color="#fff" /> </mj-attributes>
    <mj-style> @media screen and (min-width: 595px) { .paddingRight{ padding-right:24px } } </mj-style>
  </mj-head>
  <mj-body background-color="#eee">
    <mj-section padding-top="12px" padding-bottom="10px">
      <mj-column>
        <mj-social font-size="14px" line-height="15px" icon-size="24px" mode="horizontal" color="#080f1a" inner-padding="10px" vertical-align="middle">
          <mj-social-element href="www.wp.pl" src="https://cdn2.hubspot.net/hubfs/3297259/Emails/2019%20May%2016th%20-%20Onboarding%203.0%20-%20Email/fb.png?noresize" align="center">
            <p style="font-family:Roboto,Arial,sans-serif;vertical-align:middlevertical-align:middle" class="paddingRight">Join Community</p>
          </mj-social-element>
          <mj-social-element src="https://cdn2.hubspot.net/hubfs/3297259/Emails/2019%20May%2016th%20-%20Onboarding%203.0%20-%20Email/yt.png?noresize" href="www.wp.pl" align="center">
            <p style="font-family:Roboto,Arial,sans-serif;vertical-align:middle">Subscribe to our channel</p>
          </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>
    <mj-section padding-top="0px" padding-bottom="0px" padding-right="0px" text-align="left" background-color="#F3F5F8" full-width="full-width" css-class="borderGrey">
      <mj-column background-color="#F3F5F8">
        <mj-spacer height="27px"></mj-spacer>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
![mjml-issue2](https://user-images.githubusercontent.com/528501/59591594-92bd3380-90ee-11e9-87e6-4949d4a91fed.PNG)

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.3.1
 - MJML tool used MJML App

**Email sending environment(for rendering issues)**:
 - Hubspot

**Affected email clients (for rendering issues):**
 - Email Client Outlook 2019, 2010, 2016 ... 
 - OS: Windows

**Comment by iRyusa** [comment]
Hi,

Outlook desktop doesn't support media queries, so it's not related to MJML here.

You might be able to define a style block inside a head `mj-raw` with an outlook conditionnal comment to target only desktop outlook.
