### ISSUE TITLE
Remove `@viewport` declaration in viewport styles

### ISSUE THREAD

**Issue by hteumeuleu** [mjmlio/mjml#1618]
In the default styles generated by MJML, we have the following block:

```html
<!--[if !mso]><!-->
  <style type="text/css">
    @media only screen and (max-width:480px) {
      @-ms-viewport {
        width: 320px;
      }
      @viewport {
        width: 320px;
      }
    }
  </style>
  <!--<![endif]-->
```

This was useful to trigger a mobile viewport width on the default email client in Windows Phone 8. This was never used in any other email client as far as I know. Considering Windows Phone 8 is dead, it probably should be a good idea to remove this. Or maybe if some people are still finding this useful, have this only generated when using a special "_legacy_" option to generate HTML?

Here's [an article (in french)](https://remi-grumeau.com/blog/2495-emails-responsive-viewport-ya-du-nouveau/) about Windows Phone 8 and `@viewport` declaration.

**Comment by steveocarr** [comment]
This would resolve #844 as well

**Comment by Pharmasolin** [comment]
@hteumeuleu is right, I also remove this part from output file. It would be great to have at least CLI option something like --no-windows-phone-support which will remove this part.
