### ISSUE TITLE
Write `margin` in lowercase in styles

### ISSUE THREAD

**Issue by hteumeuleu** [mjmlio/mjml#1619]
Certain components (like [mjml-section](https://github.com/mjmlio/mjml/blob/dad233f7c8dc6ce92845eb048ef743e38e66ce52/packages/mjml-section/src/index.js) or [mjml-button](https://github.com/mjmlio/mjml/blob/dad233f7c8dc6ce92845eb048ef743e38e66ce52/packages/mjml-button/src/index.js)) generate `Margin` styles with an uppercase `M`.

This was useful historically for Outlook.com where CSS support depended on case. So `margin:0` would get stripped by Outlook.com, but not `Margin:0;`. This is no longer the case (no pun intended) since the last versions of Outlook.com so it can be safely changed back to lowercase `margin` everywhere. This might be a small thing but it can be one less quirk to figure out for newcomers and make MJML look more up to date towards modern best practices.

See [this bug report](https://github.com/hteumeuleu/email-bugs/issues/6) for more details.

**Comment by Ryan-Zell** [comment]
Some companies have clients working on older systems. Having backwards compatibility is a good thing in my opinion. Outlook has the capability to parse between the two.

**Comment by hteumeuleu** [comment]
Are you sure about that? My understanding was that every Outlook.com accounts were migrated to the new Office 365 type of accounts. Also there’s been two successive versions of Outlook.com where this bug has no longer been there.
