### ISSUE TITLE
Prefix CSS classes by `mj-`

### ISSUE THREAD

**Issue by hteumeuleu** [mjmlio/mjml#1620]
Certain classes generated by MJML are prefixed by `mj-` (like `.mj-column-per-100`, `.mj-menu-checkbox`, …). But some others are not:

* `table.full-width-mobile`
* `td.full-width-mobile`
* `.outlook-group-fix`

There's probably more, but these are the few I found inspecting the code generated by the [Black Friday template](https://mjml.io/try-it-live/templates/black-friday). Using `mj-` prefix everywhere would help make the generated code more clear towards the purpose of these class. (For example, to differentiate between a class generated by MJML for its own purpose versus a class used to target an email client.) So ideally, the previous classes should read:

* `table.mj-full-width-mobile`
* `td.mj-full-width-mobile`
* `.mj-outlook-group-fix`

**Comment by kmcb777** [comment]
@iRyusa for this one, should we wait for next major version ? 4.5 ?
can be breaking changes if someone used these classes in their css selector

**Comment by iRyusa** [comment]
We might need to check on mj-style content if we find those classes and add a warning ?

But yep, I agree that we should wait for 4.5 before changing this. 👍 for consistency
