### ISSUE TITLE
Documentation (default padding for mj-column and default padding for mj-social-element)

### ISSUE THREAD

**Issue by kevingermain** [mjmlio/mjml#1622]
Both default padding in the documentation are wrong (should be n/a for column and 4px for mj-social-element)

**Comment by iRyusa** [comment]
Can you open a PR on that please ? So we could fix it for 4.4 ? thanks

**Comment by iRyusa** [comment]
Ofc yep

**Comment by iRyusa** [comment]
Website is still updated manually, it's holiday season dunno when they will have time to update the doc to 4.4.1 release. I'm closing then
