### ISSUE TITLE
Directory watching doesn't work

### ISSUE THREAD

**Issue by sephii** [mjmlio/mjml#1623]
**Describe the bug**
Using the command `mjml -w emails/` (`emails` being a directory with `.mjml` files) outputs "Now watching: emails/" but then doesn't seem to do anything when a file is modified (chokidar seems to trigger change events though).

I didn't find anything in the docs regarding watching multiple files (apart from the section [command line interface](https://mjml.io/documentation/#command-line-interface) which contains a broken link in the text "Watches the changes made to input") so I'm not sure that's the proper way to do it. I also tried the command `mjml -w emails/welcome_active.mjml emails/welcome_passive.mjml` but this gives an error "Need an output option when watching files". Adding an output option didn't help though: `mjml -w emails/email1.mjml emails/email2.mjml -o emails/dist` also gives "Need an output option when watching files".

**To Reproduce**
1. Create an `emails` directory with 2 `.mjml` files in it, no matter the contents
2. Render it to HTML by doing `mjml -w emails`
3. Change the contents of one of the mjml files
4. See that nothing happens

**Expected behavior**
The modified file gets compiled when changed. Or there's a documented solution that shows how to watch multiple files.

**MJML environment (please complete the following information):**
 - OS: Linux
 - MJML Version: 4.4.0-beta.2
 - MJML tool used: mjml-cli

**Comment by iRyusa** [comment]
You have to add a wildcard pattern : `mjml -w emails/*.mjml -o dist` or `mjml -w emails/* -o dist`

Note that the `output` dir should already exist when given.

**Comment by sephii** [comment]
Thanks, the error indeed goes away when the destination directory exists. I still think this could be improved though, either by outputting a specific error message (eg. "Output directory xxx doesn't exist"), or specifying something in the docs (I would love to see more command-line usage examples).

If you think that makes sense, I'd be happy to submit a PR.

**Comment by iRyusa** [comment]
There's still some obscure case in the current cli, feel free to open a PR about documentation & cli error messages. Help is always appreciated 👍
