### ISSUE TITLE
CLI Issue: --config.filePath does not work as expected

### ISSUE THREAD

**Issue by araphiel** [mjmlio/mjml#1628]
## Describe the bug

Using the CLI, using `--config.filePath` flag that dictates where `mj-includes` are referenced from, meaning you can use partials in a separate directory.

However, the flag currently expects a **single file**, not a **directory**

### Expected behavior: 

`mjml --c.filePath includes -w src/emails/transactional/test-2.mjml -o`

Should generate an email using the `/includes/` directory. **This currently fails.**

### What does work:

`mjml --c.filePath includes/header.mjml -w src/emails/transactional/test-2.mjml -o`

While this works, it's **not clear** that this works for **multiple partials**. (however, it's also error prone when working with many emails)

### To Reproduce

Test Repo: https://github.com/araphiel/mjml-filePath-issue

You can clone this repo and run the following commands to see odd but working implementations.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.4.0-beta.2

Related:
https://github.com/mjmlio/mjml/issues/1546
https://github.com/mjmlio/mjml/issues/842

**Comment by iRyusa** [comment]
Well I think this options for `watch` won't work anyway, if you need to do such a complex build, I'm not sure the cli is ideal here. However adding a check if given filePath is a directory should be easy to do.
