### ISSUE TITLE
Create public Gitter chat room for support

### ISSUE THREAD

**Issue by gonchs** [mjmlio/mjml#163]
Would be nice to have a chat room where people can help each other: https://gitter.im

**Comment by ngarnier** [comment]
Hey @gonchs, thanks for your message, we totally agree!

We're working on it and you'll have a place to chat with fellow MJMLers in the coming weeks, keep you posted!

**Comment by ngarnier** [comment]
Hello @gonchs, I have some good news for you! We've opened a public MJML slack so everyone can chat and share about MJML: https://mjml.io/slack

It will be officially launched next tuesday but as you requested something similar, we thought you should be one of the first to join ;-p. 

See you on Slack!

**Comment by ngarnier** [comment]
Hey @gonchs, 

As the MJML slack is now released, I'm closing this issue. See you on Slack!
