### ISSUE TITLE
background-size="contain" not working in Outlook 2016

### ISSUE THREAD

**Issue by raeann312** [mjmlio/mjml#1633]
**Describe the bug**
background-size="contain" not working in Outlook 2016. It works fine on every other email client, including in the browser.

**To Reproduce**
Here is my mjml code:
`<mjml owa="desktop">
  <mj-head>
  </mj-head>
  <mj-body>

    <mj-section full-width="full-width">
      <mj-group width="80%">

        <mj-column vertical-align="middle">
          <mj-image align="left" width="150px" src="https://dhilton.s3.amazonaws.com/uploads/2018/03/Corporate-One-logo.png">
          </mj-image>
        </mj-column>

        <mj-column vertical-align="middle">
          <mj-text font-size="12px" color="grey" font-weight="bold" align="right" padding-bottom="0">Email Here</mj-text>
          <mj-text font-size="12px" color="grey" align="right" padding-top="5px">Phone Here</mj-text>
        </mj-column>
      </mj-group>

    </mj-section>

    <mj-section full-width="full-width" background-color="#d4dcdf" background-url="http://pi.corporateone.coop/l/147401/2019-06-26/5kxcz8/147401/131327/AdobeStock_207312686__Converted_.jpg" background-size="contain" background-repeat="no-repeat">

      <mj-group width="80%">
        <mj-column>
          <mj-text align="left" font-size="20px" font-family="Verdana">Make your money work harder for you with new member specials from Corporate One.</mj-text>
        </mj-column>

        <mj-column>
          //blank just for layout purposes
        </mj-column>
      </mj-group>

    </mj-section>

    <mj-section>
      <mj-column width="80%" border-left="15px solid red">
        <mj-text font-size="20px" font-family="Arial black" color="#003768">EARN UP TO 20 BASIS POINTS OVER THE FED'S RATE ON EXCESS RESERVES</mj-text>
      </mj-column>
    </mj-section>

    <mj-section padding-top="10px">
      <mj-column width="80%">
        <mj-text color="grey">
          Corporate One’s strong financial position allows us to be a premier provider of short-term cash management solutions. With a $1 million initial investment of new money deposited into a 90-day notice account at Corporate One, new members can earn up to
          20 basis points over the IOER (Interest Rate on Excess Reserves).
        </mj-text>
        <mj-text color="grey">
          In addition to the 90-day notice account we are also making available an Overnight Market Account where your credit union can earn up to 10 basis points over the IOER rate.
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section>
      <mj-column width="80%" border-left="15px solid red">
        <mj-text padding-bottom="0" font-size="20px" font-family="Helvetica Neue" color="#626262">Get started today.</mj-text>
        <mj-text padding-bottom="0" padding-top="0" font-size="20px" font-family="Helvetica Neue" color="#626262">Call [phone here] or</mj-text>
        <mj-text font-size="20px" padding-top="0" font-family="Helvetica Neue" color="#626262">e-mail [email here]</mj-text>
      </mj-column>
    </mj-section>

    <mj-section padding-top="0">
      <mj-column width="80%">
        <mj-text font-size="9px" font-style="italic" color="grey">Earn up to 20 basis points over the rate the Federal Reserve pays on excess reserves (IOER). Subject to $5 Associate membership fee. *Rate subject to change.</mj-text>
      </mj-column>
    </mj-section>

    <mj-section background-color="#617382" full-width="full-width">
      <mj-column>
        <mj-image align="center" src="http://pi.corporateone.coop/l/147401/2017-01-26/21vfjx/147401/37343/C1_Logo_Footer_0117v1.png"></mj-image>
      </mj-column>

      <mj-column>
        <mj-spacer height="15px" />
        <mj-text padding="0" color="#a2adb7" align="center">Corporate One FCU</mj-text>
        <mj-text padding="0" color="#a2adb7" align="center">8700 Orion Place</mj-text>
        <mj-text padding="0" color="#a2adb7" align="center">Columbus, OH 43240</mj-text>
      </mj-column>
      <mj-column>
        <mj-spacer height="15px" />
        <mj-text padding="0" color="#a2adb7" align="center">866/MyCorp1</mj-text>
        <mj-text padding="0" color="#a2adb7" align="center">614/825-9200</mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="rgb(90, 107, 121)" full-width="full-width">
      <mj-column width="500px">
        <mj-text font-size="9px" color="#a2adb7" align="center">View as a webpage</mj-text>
        <mj-text font-size="9px" color="#a2adb7" align="center">You are receiving this email from Corporate One Federal Credit Union because either you have opted-in to receive MemberMail email communications in the past, or because of your financial institution's relationship with Corporate One FCU. If you
          no longer wish to receive these emails, please use the link below to unsubscribe or manage your email preferences.</mj-text>
        <mj-text font-size="9px" color="#a2adb7" align="center">
          <a class="link-grey" href="%%email_preference_center%%" style="color:#a2adb7 !important;color:#a2adb7;" target="_blank">
            <font color="#a2adb7">Unsubscribe or manage your email preferences</font>
          </a>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: 4.3.0
 - MJML tool used: Email Editor

**Email sending environment(for rendering issues)**:
 - Pardot

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2016

**Screenshots**
The email in Gmail (how it's supposed to look):
![gmail](https://user-images.githubusercontent.com/28910169/60541367-71a83580-9cdf-11e9-988a-90bfbcd32ba4.png)

The email in Outlook (looks more like cover than contain):
![outlook](https://user-images.githubusercontent.com/28910169/60541382-7ff65180-9cdf-11e9-9384-544be3012065.png)

**Additional context**
N/A

**Comment by iRyusa** [comment]
There’s no way to support this behavior in desktop Outlook sadly.

**Comment by raeann312** [comment]
Ok. That should probably be noted in the documentation.
