### ISSUE TITLE
Create button with icon as standard body component 

### ISSUE THREAD

**Issue by user-12** [mjmlio/mjml#1634]
I often use buttons with icons into my emails. Here the outcome:

![image](https://user-images.githubusercontent.com/6585723/60814761-892b6680-a196-11e9-9df4-a108da3137fd.png)

Right now, I am creating basic table to achieve it. An example of the code:

```
<mj-column width="270px" background-color="#78B927">
        <mj-table>
          <tr style="background-color=#78B927">
            <td style="width:20px">
              <img src="img/left-corner.png" style="display:block;">
            </td>
            <td style="width:23px">
              <img src="img/email-icon.png" style="display:block;width:23px">
            </td>
            <td bgcolor="#78B927" style="font-family:Verdana, Geneva, sans-serif; color:#FFFFFF; font-size:16px; text-align:center; vertical-align:middle;width:207px">
              <strong>
                <a style="text-decoration:none; color:#FFFFFF;" href="#" target="_blank">
                  Contact
                </a>
              </strong>
            </td>
            <td style="width:20px">
              <img src=" img/right-corner.png" style="display:block;" border="0" align="right">
            </td>
          </tr>
        </mj-table>
      </mj-column>
```

Do you think you can create a standard body component to make it smoother?

**Comment by iRyusa** [comment]
You can already embed an img inside mj-button as you can paste any HTML inside `mj-button`. ex : https://mjml.io/try-it-live/HJ98AlUMS

For a left/right icon inside the button I think you should do a custom component for that.

**Comment by nicmare** [comment]
FYI won't work in many clients. icon has offset or text is missing. tested it with litmus.

**Comment by iRyusa** [comment]
Just tested and it works fine, the logo overflow in Outlook but this can be solved by adjusting the natural width of the image tho. You can still wrap the content in a table with 2 td one for the image one for the text it would work just fines

**Comment by nicmare** [comment]
some proofs.

code:
`<mj-button padding="0 10px 10px" css-class="region region-link" align="left" href="#" inner-padding="10px 0" background-color="#efefef" mj-class="webfont-sm" color="#af3393"><img src="https://pardot.salanje.de/l/894941/2021-06-08/2g2fs/894941/1623144870zV6yv9Cs/arrow_right_primary.png
" style="width:20px; vertical-align:middle;" /> &nbsp; Button Link</mj-button>`

outlook2019:
![image](https://user-images.githubusercontent.com/898582/121198211-4090f200-c872-11eb-90ee-4f00654cafeb.png)

office 365 windows:
![image](https://user-images.githubusercontent.com/898582/121198311-53a3c200-c872-11eb-8cf4-781d3986ae74.png)

office 365 chrome:
![image](https://user-images.githubusercontent.com/898582/121198413-66b69200-c872-11eb-8f56-33b02b2eaab5.png)

**Comment by iRyusa** [comment]
Text could disappear because of non valid href for some clients try to remove `href="#"` or use a valid temporary like `href="https://google.com"`

**Comment by nicmare** [comment]
veritcal-align:middle is already aligned. see code above will text the href attribute. thank you ryusa!

**Comment by nicmare** [comment]
> Text could disappear because of non valid href for some clients try to remove `href="#"` or use a valid temporary like `href="https://google.com"`
> 
> For the vertical align issue you can just try to apply veritcal-align:middle on img tag that should work

did not know that makes the difference. thank you!! label is there now. but vertical offset remains

**Comment by BaptisteGillard** [comment]
You can use table inside your button. I tried it and it seems working on main clients like gmail / outlook/ apple.
https://mjml.io/try-it-live/tedYB7ZfKwh

**Comment by iRyusa** [comment]
If you should avoid putting a table inside mj-button as some client doesn't support `<a>` with `<table>`, making the link not clickable even it renders fine.

**Comment by BaptisteGillard** [comment]
> If you should avoid putting a table inside mj-button as some client doesn't support `<a>` with `<table>`, making the link not clickable even it renders fine.

Oh my bad, So do you recommend anything else in particular to solve this problem?

**Comment by iRyusa** [comment]
> You can already embed an img inside `mj-button` as you can paste any HTML inside it. ex : https://mjml.io/try-it-live/HJ98AlUMS
> 
> For a left/right icon inside the button I think you should do a custom component for that.

This 😄

**Comment by BaptisteGillard** [comment]
> some proofs.
> 
> code:
> `<mj-button padding="0 10px 10px" css-class="region region-link" align="left" href="#" inner-padding="10px 0" background-color="#efefef" mj-class="webfont-sm" color="#af3393"><img src="https://pardot.salanje.de/l/894941/2021-06-08/2g2fs/894941/1623144870zV6yv9Cs/arrow_right_primary.png " style="width:20px; vertical-align:middle;" /> &nbsp; Button Link</mj-button>`
> 
> outlook2019:
> ![image](https://user-images.githubusercontent.com/898582/121198211-4090f200-c872-11eb-90ee-4f00654cafeb.png)
> 
> office 365 windows:
> ![image](https://user-images.githubusercontent.com/898582/121198311-53a3c200-c872-11eb-8cf4-781d3986ae74.png)
> 
> office 365 chrome:
> ![image](https://user-images.githubusercontent.com/898582/121198413-66b69200-c872-11eb-8f56-33b02b2eaab5.png)

Yes, I was talking about this issue

**Comment by nicmare** [comment]
i can confirm that too. putting the img tag inside a button is not sufficient. where need a component here for sure :-D

**Comment by iRyusa** [comment]
There's not so much that can be done here as vertical-align on older outlook clients isn't supported without a wrapping table, and adding a table inside an anchor would degrade the clickability of the button.

**Comment by sidhantsuvagiya** [comment]
**i have better solution**

https://mjml.io/try-it-live/u9caI30uD

Preview: - [https://mcusercontent.com/58cc6fdf204aea6e7442682a9/images/1699d488-aca4-5862-7003-7da2ed012961.jpeg](url)

`<mj-section padding="24px 0px" background-color="#FFFFFF">
        <mj-column>
        <mj-social align="left" padding="0px 35px 35px 35px" mode="horizontal">
          <mj-social-element font-size="14px" line-height="17px" icon-size="1px" icon-height="1px" color="#292D34" 
                  align="left" font-weight="700" padding="0px" href="www.example.com" 
                  src="https://mcusercontent.com/58cc6fdf204aea6e7442682a9/images/ff91363e-68a6-b542-160e- 
                  e2def8f82726.png"> Find out more &nbsp; 
          </mj-social-element>
          <mj-social-element icon-size="16px" icon-height="17px" padding="0px" 
                  src="https://mcusercontent.com/58cc6fdf204aea6e7442682a9/images/a90930c2-5ec4-e8ba-d1a3- 
                  101687fa8914.png">
         </mj-social-element>
       </mj-social>
        </mj-column>
    </mj-section>`

**Comment by nicmare** [comment]
> **i have better solution**
> 
> https://mjml.io/try-it-live/u9caI30uD
> 
> ![Web capture_23-9-2022_175030_mjml io](https://user-images.githubusercontent.com/66551578/191960564-3599d87a-a8d0-482d-b73f-116c87678bd3.jpeg)
> 
> `<mj-section padding="24px 0px" background-color="#FFFFFF"> <mj-column> <mj-social align="left" padding="0px 35px 35px 35px" mode="horizontal"> <mj-social-element font-size="14px" line-height="17px" icon-size="1px" icon-height="1px" color="#292D34" align="left" font-weight="700" padding="0px" href="www.example.com" src="https://mcusercontent.com/58cc6fdf204aea6e7442682a9/images/ff91363e-68a6-b542-160e- e2def8f82726.png"> Find out more &nbsp; </mj-social-element> <mj-social-element icon-size="16px" icon-height="17px" padding="0px" src="https://mcusercontent.com/58cc6fdf204aea6e7442682a9/images/a90930c2-5ec4-e8ba-d1a3- 101687fa8914.png"> </mj-social-element> </mj-social> </mj-column> </mj-section>`

very creative! does it look good across mail clients?

**Comment by sidhantsuvagiya** [comment]
@nicmare yes, it looks good. I have tested on email on acid
