### ISSUE TITLE
text decoration none not respected on Outlook for mac or Outlook for Android

### ISSUE THREAD

**Issue by vcorvid** [mjmlio/mjml#1635]
**Describe the bug**
Text decoration none is not respected on Outlook for Mac (I'm running Version 16.26 on Mojave) or on the Outlook app for Android (I'm running Outlook version 3.0.92 on Android 8.0.0 on an LG G6). The underline also does not match the link color and displays in a default blue.

**To Reproduce**
1. Send the Arturia iSpark template through email. Note the mint green links at the bottom with no underline.
2. View the received email in Outlook for Mac or Outlook App for Android. The links show blue underlines with mint green text.

**Expected behavior**
Links with text decoration none should have no underlines.

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version4.3.1
 - MJML App 2.11.0

**Email sending environment(for rendering issues)**:
 Tried pasting html into outlook
Also tried sending from Visual Studio code from Gmail

**Affected email clients (for rendering issues):**
Outlook for Mac
(I'm running Version 16.26 on Mojave)

Outlook App for Android
(I'm running Outlook App version 3.0.92 on Android 8.0.0 on an LG G6).

**Additional Info**
I looked on the compatibility chart, and it looks like it hasn't been updated since 2017 but that Outlook for iOS is expected to support text decoration. There isn't an entry for Outlook App for Android though so I don' know if that is supported. 
https://mjml.io/compatibility/mj-text

**Comment by pierresis** [comment]
Did you try to add a css class ?

`css-class="link-no-decoration`

`<mj-style inline="inline">
      .link-no-decoration { text-decoration: none }
    </mj-style>`

**Comment by iRyusa** [comment]
I think there's no really solution here as it s a known bug on Outlook Mac, what you can do, as suggested by @pierresis, try to remove the text-decoration and "maybe" try with a border-bottom but i'm not sure about the support too.
