### ISSUE TITLE
Allow scripts in header of mail - Google Email Markup

### ISSUE THREAD

**Issue by patrickbussmann** [mjmlio/mjml#1638]
I need to place the example script of google to my head of the mjml template.
https://developers.google.com/gmail/markup/

For example this:

```
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "EmailMessage",
    "potentialAction": {
      "@type": "ConfirmAction",
      "name": "Approve Expense",
      "handler": {
        "@type": "HttpActionHandler",
        "url": "https://myexpenses.com/approve?expenseId=abc123"
      }
    },
    "description": "Approval request for John's $10.13 expense for office supplies"
  }
</script>
```

This should go to `<head />` or at least to `<body />`.

But then I get compiler errors.

Or is there another way to implement Google Email Markup with MJML? 😇

**Comment by iRyusa** [comment]
You can use mj-raw in mj-head for that
