### ISSUE TITLE
Accessing helpers from custom components

### ISSUE THREAD

**Issue by cyberwombat** [mjmlio/mjml#164]
How would one use:

    import  { widthParser } from '../helpers/mjAttribute'

In a custom component?  Is there a way to access the helpers in another way?

**Comment by lohek** [comment]
Hi !

Maybe, you can try `import  { widthParser } from 'mjml/lib/helpers/mjAttribute'`

**Comment by epayet** [comment]
Hi, I just checked. This works, but I don't find that very intuitive?
Maybe we should have an alternative like

```javascript
import { helpers } from 'mjml'
// And then one can use helpers.mjAttribute.widthParser
// Or even shorter helper.widthParser?
```

Or something close to this?
I guess we should expose the helpers on [src/index.js](https://github.com/mjmlio/mjml/blob/master/src/index.js)

**Comment by iRyusa** [comment]
Hello ! 
As @epayet mention you can use them through ` import { helpers } from 'mjml'` in MJML 2.X
