### ISSUE TITLE
Move BorderRadius on mj-section on same level as mj-column & add warning in documentation about it

### ISSUE THREAD

**Issue by PMunch** [mjmlio/mjml#1641]
Currently the documentation makes it seem like border-radius should work for `mj-section` and `mj-column`, but according to the issues #1104 and #1510 this is known not to work. I propose removing these attributes for these elements if there is no way to fix this.

**Comment by iRyusa** [comment]
It still works for background color, and there’s a way to get around it within the first issue. So I don’t see why we should remove it.

**Comment by PMunch** [comment]
Maybe rename it to `background-radius` then? I just spent a lot of unnecessary time trying to figure out why this didn't work. At the very least leave a note on this in the documentation..

**Comment by iRyusa** [comment]
A warning can be added in the doc, yup. Renaming an attribute will break a lot of templates, so this is not a good solution.

**Comment by PMunch** [comment]
That's a fair point, but as it stands now it's mis-named. It doesn't change the border radius, so naming it `border-radius` isn't very intuitive. Especially as it shares the same name as the CSS property that _does_ change the border radius. Does mjml support deprecation?

**Comment by PMunch** [comment]
Oh and by the way, the workaround in #1104 doesn't work for multiple columns with borders.

**Comment by iRyusa** [comment]
It would need to release a major version only for that...

 I don’t really think the name is an issue as it‘s applied as a css border-radius in the final output. It’s not like mjml introduce this behavior, this is how the CSS properties works.

A small warning on the doc will be enough.

**Comment by iRyusa** [comment]
Changing the title
