### ISSUE TITLE
mjml2html is not a function

### ISSUE THREAD

**Issue by Uysim** [mjmlio/mjml#1643]
I did
```
import { mjml2html } from 'mjml'

mjml2html(...);
```

I have tried 
```
import mjml2html from 'mjml'
const mjml2html = require('mjml')
```

but nothing work

**Comment by kmcb777** [comment]
Hi @Uysim, mjml2html is the default export, so these should work :
```import mjml2html from 'mjml'
const mjml2html = require('mjml')```
You get `mjml2html is not a function` with these ones ?
Are you using the latest version ?

**Comment by Uysim** [comment]
@kmcb777 Yes, I used the latest version. But do you think because I use it for front-end is the problem? seem like mjml only support for back-end.

**Comment by kmcb777** [comment]
@Uysim yes indeed, it uses node libraries like `fs`
We'll try to make it browser compatible someday - PRs are welcome for this !
