### ISSUE TITLE
[BUG] impossible to install MJML 4.4.0

### ISSUE THREAD

**Issue by jimblue** [mjmlio/mjml#1644]
I've just try to install the new release of MJML version 4.4.0 but NPM return me the following error:

```bash
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mjml-section@4.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mjml'
npm ERR! notarget 
```

**Comment by iRyusa** [comment]
Looks like a cache issue from npm, it listed as released on website https://www.npmjs.com/package/mjml-section

**Comment by jimblue** [comment]
Ok, so just need to wait... tks

**Comment by jimblue** [comment]
@iRyusa, if you look at the registry it, latest version is still **4.4.0-beta.2**: https://registry.npmjs.org/mjml-section

**Comment by iRyusa** [comment]
Looks like it's now ok :)

**Comment by jimblue** [comment]
Indeed it is 🎉🎉🎉
