### ISSUE TITLE
Center logos on mobile

### ISSUE THREAD

**Issue by SoyDiego** [mjmlio/mjml#1645]
Hi people, I have a problem with my two logos. In desktop all works fine, but I don't know how can I do for center my logos on mobile.
I think the problem is because have the logos with align left (logo1) and align right (logo 2)
How can I remove the attribute ALIGN in responsive and center the logos?

Here my code:
https://mjml.io/try-it-live/r1sXRAhZH

Sorry for my english, is not good. I hope to explained myself well.

**Comment by iRyusa** [comment]
Well best way to do this is to add an align `center`, then expand image to column's width and it should be fine.

Ex here : https://mjml.io/try-it-live/HkeRrkTWH just tweak the number and you'll be fine

**Comment by SoyDiego** [comment]
> Well best way to do this is to add an align `center`, then expand image to column's width and it should be fine.
> 
> Ex here : https://mjml.io/try-it-live/HkeRrkTWH just tweak the number and you'll be fine

Thanks for your fast reply @iRyusa. I did your way before, but the problem is that the logos is not align to the banner and i need aligned in DESKTOP . Here an screenshot:

![imagen](https://user-images.githubusercontent.com/19764334/61401069-eaa7af80-a8d1-11e9-8c01-e93dcf39c6df.png)
The logos aligned with the banner (red line).

Thanks again for help me :)

**Comment by kmcb777** [comment]
iryusa meant you could ajust with the width of the column in the middle, like this : https://mjml.io/try-it-live/SJMf3y6bS

**Comment by SoyDiego** [comment]
> iryusa meant you could ajust with the width of the column in the middle, like this : https://mjml.io/try-it-live/SJMf3y6bS

Thanks @kmcb777 now i understood. But i have a little question more, (i think is the last, sorry haha).
Its possible remove the column with the empty space on mobile? Because I need remove the space between the logos. I tried with:

`				 @media (max-width:480px) {
        .hidden {
          display: none !important;
        }
      }`

and i put css-class="hidden" in the column but is not working... :(

Thanks again...

**Comment by iRyusa** [comment]
Adding a font size to 0 should do the trick

**Comment by SoyDiego** [comment]
> Adding a font size to 0 should do the trick
> […](#)
> On 17 Jul 2019, at 21:09, Diego ***@***.***> wrote: iryusa meant you could ajust with the width of the column in the middle, like this : https://mjml.io/try-it-live/SJMf3y6bS Thanks @kmcb777 now i understood. But i have a little question more, (i think is the last, sorry haha). Its possible remove the column with the empty space on mobile? Because I need remove the space between the logos. I tried with: @media (max-width:480px) { .hidden { display: none !important; } } and i put css-class="hidden" in the column but is not working... :( Thanks again... — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Excellent @iRyusa, works perfectly!!!
I think need learn some tricks like this...
Thanks for your help!!
