### ISSUE TITLE
Button href is always #, in 4.4.0

### ISSUE THREAD

**Issue by paulisloud** [mjmlio/mjml#1646]
# The bug

Using this template:

```mjml
<mj-button background-color="transparent" border="1px solid #1e8044" align="right" color="#1e8044" font-weight="bold" href="#" font-size="16px" href="${link}">Read this article</mj-button>
```

I get this output:

```html
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:separate;line-height:100%;">
        <tr>
          <td align="center" bgcolor="transparent" role="presentation" style="border: 1px solid #1e8044; border-radius: 3px; cursor: auto; mso-padding-alt: 10px 25px; background: transparent; padding-left: 14px; padding-right: 14px;" valign="middle">
            <a href="#" style="display:inline-block;background:transparent;color:#1e8044;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;" target="_blank">
              Read this article
            </a>
          </td>
        </tr>
      </table>
```

The same `link` value is used in an adjacent mjml element (_twice_), and works fine.

Rendered using 
```js
mjml2html(stuff)
``` 
from [mjml](https://github.com/mjmlio/mjml)
# Expected behavior
Button should render with proper link value.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.4.0 (just installed the latest 5 minutes prior to posting)
 - Node.js 11.0.0

**Email sending environment(for rendering issues)**:
MailChimp

**Affected email clients (for rendering issues):**
Everything, it shows up in the MailChimp render

**Comment by iRyusa** [comment]
You have two href attribute on your button, is it intended ?

**Comment by paulisloud** [comment]
Ug, nope. 🤦‍♂  Thanks!
