### ISSUE TITLE
Marketo Implementation?

### ISSUE THREAD

**Issue by layonthebeech** [mjmlio/mjml#1648]
I am trying to use mjml over foundation, due to it's ease of use. I need to integrate my emails into a template in marketo. Some of the stipulations of that are things like editable text need a unique ID and name. For example: 

` <tr>
                                                    <td style="font-size:16px;font-family:'Open Sans',Arial,Sans-serif;color:#989898;line-height:24px;">
                                                    <div class="mktoText" id="mkto-article-description" mktoName="Article Description">
                                                    Consectetur adipiscing elit. Aenean mollis diam
                                                    sit amet leo lacinia aliquet. Duis lacinia placerat dignissim. Aenean vel interdum ligula. Etiam tempus risus vel condimentum lacinia. Sed viverra
                                                    suscipit orci non ornare. Maecenas arcu massa, porta et eros ac, vehicula sodales mi.
                                                    </div>
                                                    </td>
                                                </tr>`

I'm not sure if that's going to be possible with MJML before rendering it out to html. I would assume the only way to do this would be with mj-raw, but then I couldn't have anything within that element that needs to be rendered. 

Another gotcha is you can define "modules" in your html. Marketo treats these as unique elements that will be the building blocks of your template. They are defined like this:

`<tr class="mktoModule" id="mkto-article" mktoName="Article">`

Same issue. Anyone have experience with marketo and mjml?

**Comment by probablyabear** [comment]
Before the team has a chance to comment on the feasibility of adding those IDs and custom attributes to the MJML markup, I'd suggest implementing those attributes/IDs in the compiled HTML so you'll have direct access to those elements.

**Comment by layonthebeech** [comment]
I would do that but I basically have like 30 components, so it's not super feasible. That's alright though, if it's not already possible in mjml, I will look into it with foundation. Let me know though!

Thanks for the quick response and let me know if i can provide any more info.

Pat

**Comment by iRyusa** [comment]
ID aren't supported in mjml but `css-class` can be used to applied css class at a top level.

 I think what you would like is #200 but there's too many usecase and no solution has been found yet. 

In mj-text you can also use plain HTML but dunno if it will be enough for your need.

**Comment by probablyabear** [comment]
@iRyusa, would creating a custom component allow for one to set allowable attributes as needed?

**Comment by iRyusa** [comment]
Well you can do whatever you want with component even non valid html so yep

**Comment by araphiel** [comment]
https://www.npmjs.com/package/mjml-marketo 

I released a custom wrapper that can be used to create editable sections for your Marketo templates.
Combine this with the recently added `<mj-html-attributes>` tags for images to take it a step further.

**Comment by nicmare** [comment]
> https://www.npmjs.com/package/mjml-marketo
> 
> I released a custom wrapper that can be used to create editable sections for your Marketo templates.
> Combine this with the recently added `<mj-html-attributes>` tags for images to take it a step further.

any chance to use the custom wrapper in the mjml-app?

**Comment by nicmare** [comment]
fyi afaik this should work:
`<mj-raw>
      <table class="mktoModule text-item" id="text-item" mktoName="Text Item" mktoAddByDefault="true" border="0" cellpadding="0" cellspacing="0" style="width:100%;padding:0;margin:0;">
      <tr style="padding:0;margin:0;width:100%;"><td style="padding:0;margin:0;width:100%;">
</mj-raw>
      <mj-section padding="0">
        <mj-column>
          <mj-text css-class="text-item_text">
        	  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
          </mj-text>
        </mj-column>
      </mj-section>
<mj-raw>
      </td></tr></table>
</mj-raw>`

because marketo expects modules to be a table. so simply wrap an outer table around everything which should become a module. 
then with the new html attribute function add editable text area like this in <mj-head>:
```
<mj-html-attributes>
  <mj-selector path=".text-item_text > div">
        <mj-html-attribute name="class">mktoText text-item</mj-html-attribute>
        <mj-html-attribute name="id">text-item_text</mj-html-attribute>
        <mj-html-attribute name="mktoName">Text-Item</mj-html-attribute>
  </mj-selector>
</mj-html-attributes>
```
