### ISSUE TITLE
2 problems: Padding and blue line in links

### ISSUE THREAD

**Issue by SoyDiego** [mjmlio/mjml#1650]
Hi people, i have the next code:
https://mjml.io/try-it-live/SkMPA74zS

All is perfect, but in Outlook the padding-right in bullets not working, i don't know how can i fix this.

In the link, a blue line is under the text, I wrote color property but the problem continue. 

Here I attach an image. Can you help me?

Thanks again for all

HERE MY RESULTS :S

![Captura de pantalla 2019-07-23 a las 8 59 24](https://user-images.githubusercontent.com/19764334/61689812-36ba8000-ad28-11e9-8af7-393535868076.png)

![Captura de pantalla 2019-07-23 a las 8 57 20](https://user-images.githubusercontent.com/19764334/61689732-05da4b00-ad28-11e9-9242-ecd25defd78d.png)

**Comment by iRyusa** [comment]
Well about the padding, it's not supported in Outlook so there no solution for it, you can throw a `&nbsp` here to add a visible space between your bullet & text.

What version of outlook you're using and on what OS ?

**Comment by SoyDiego** [comment]
> Well about the padding, it's not supported in Outlook so there no solution for it, you can throw a `&nbsp` here to add a visible space between your bullet & text.
> 
> What version of outlook you're using and on what OS ?

Hi @iRyusa thanks again. You always reply me, thanks for that.
I used Litmus for check and all versions in Outlook have the PADDING problem.

Regarding the blue line in the link, or sometimes blue links in address, numbers, etc... do you have any idea?
I tried also inserting inline style `style=”color: red; text-decoration: none;”`but continue blue. 
This problem ocurrs in Outlook and iOS. Firefox and Chrome is perfect.

Thanks again for your "solution" with `&nbsp`. it serves me and I will use it :)

**Comment by kmcb777** [comment]
Hi @SoyDiego, about the blue line, i don't get this result on emailonacid, on which outlook version are you testing and how do you send the email exactly ?

Also you can try to put the related css in a `<mj-style inline="inline">`

**Comment by SoyDiego** [comment]
> Hi @SoyDiego, about the blue line, i don't get this result on emailonacid, on which outlook version are you testing and how do you send the email exactly ?
> 
> Also you can try to put the related css in a `<mj-style inline="inline">`

thanks for your reply and sorry for the delay @kmcb777.
I tested all in litmus, all versions in Outlook. But i think the problem was in Litmus because then i send my newsletter to my Outlook and the problem wasn´t show.

Thanks again and close this topic =)
