### ISSUE TITLE
ghost button styles

### ISSUE THREAD

**Issue by Coobaha** [mjmlio/mjml#166]
Hi! First of all, thanks for this awesome tool!

I cant figure out the way to render ghost button (button with border only without background, like download button on your site)

I tried this:
```
<mj-button             
  container-background-color="white"
  border="1px solid blue"
  background-color="white" 
  border-radius="10px" 
  color="blue"
>
READ MORE
</mj-button>
```
but this produce squared button, ignores border-radius..

If I remove border attribute from `table`, and apply it to `a` styles - all works as expected in chrome preview.
```
  getStyles () {
    const { mjAttribute } = this.props

    return _.merge({}, this.constructor.baseStyles, {
      table: {
        borderRadius: mjAttribute('border-radius')
      },
      a: {
        border: `${mjAttribute('border')}`,
      }
    })
  }
```

**Comment by janus-reith** [comment]
I also tried that without success.
For now I stick with with an image as button.

**Comment by jvhellemond** [comment]
It looks like the `border` property is applied to the parent of the button (a `<td>` element) and the `border-radius` is applied to the the parent and the button itself (an `<a>` element). But `border-radius` has no effect on `<td>` elements.

This issue, for this particular case at least, could be fixed by applying the `border` property to the button itself, rather than its parent.

**Comment by jitendravyas** [comment]
I also need to make ghost button with <mj-text>, don't know how to do it

**Comment by lohek** [comment]
If you want simple ghost button, you can try this
```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-button background-color="#fff" color="#000" border="1px solid #000">
            My button
          </mj-button>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
But no border-radius for the moment.

**Comment by jitendravyas** [comment]
thanks. i want to make it visually look like button but i dont want to make it actual button because this block will have a coupon code which people can copy.

**Comment by lohek** [comment]
And this ?
```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-table>
            <tr>
              <td width="30%">&nbsp;</td>
              <td width="40%" align="center" style="border: 1px solid #000; padding: 10px 25px;">
                My coupon code
              </td>
              <td width="30%">&nbsp;</td>
            </tr>
          </mj-table>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
![](http://puu.sh/oOXKj/015df2d967.png)

**Comment by jitendravyas** [comment]
Nice but it can't have radius

**Comment by zrb0529** [comment]
Is border radius well supported? I thought it was unsupported by Gmail which (for us at least) is a huge part of our audience.

**Comment by iRyusa** [comment]
You can now create ghost buttons within MJML 2.3 !
