### ISSUE TITLE
Blue dates, schedule and address on iOS

### ISSUE THREAD

**Issue by SoyDiego** [mjmlio/mjml#1660]
Hi people, again me! (sorry haha)
I have a problem with blue colors in dates, schedule and address. 
The problem is in some Iphone and Outlook Mac.

How can i solve the problem?
I tried with `<span style="text-decoration: none; color: red;">` but not working.

![Captura de pantalla 2019-07-31 a las 8 50 07](https://user-images.githubusercontent.com/19764334/62191109-267f5200-b373-11e9-9fa1-284fee9b4650.png)

Thanks again!!

**Comment by iRyusa** [comment]
Hi ! 

You can use the solution mentioned here : https://github.com/mjmlio/mjml/pull/511#issue-102894396

**Comment by SoyDiego** [comment]
@iRyusa thanks!! you always save me! works perfectly.
I searched in google but nothing works but i have read your post, and it works!!.  In all my litmus test disappear the blue color :) :).
THANKS!
