### ISSUE TITLE
Hairline appear in Outlook 2016/2019 Windows

### ISSUE THREAD

**Issue by alfredtan** [mjmlio/mjml#1661]
**Describe the bug**
On Outlook 2016/2019 **Windows**, a hairline appears that is showing the background color of the <body> element. The issue appears consistently on Outlook 2016, but appears to be random on Outlook 2019. 

We are aware that this is an longstanding issue, and we have tried the numerous workarounds offered by the community, but none of it works. We now look to the experts here for any reliable solution you might have. 

**To Reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-body background-color="#ffffff" width="640px">
    

<mj-wrapper background-color="#f0f0f0" padding="10px 20px">
  <mj-section padding="0px" background-color="#ffffff">
    <mj-column width="50%">
      <mj-image fluid-on-mobile="true" padding="0px" src="https://via.placeholder.com/290x210" />
    </mj-column>
    <mj-column width="50%" background-color="#ffffff" vertical-align="middle">
      <mj-text align="center" font-family="Arial, sans-serif" color="#231f20" padding="20px">
        <span style="font-size: 14px; line-height: 18px;">
          <strong>For a seamless web experience, we recommend using these browsers:</strong> <br /><br />
          Chrome v63, Safari v10, FireFox v57, Internet Explorer v11 or their latest versions.
        </span><br /><br />
        <span style="font-size: 16px; line-height: 20px;">
          Click <a href="https://www.google.com" target="_blank" style="text-decoration: underline; color: #009fd4;">here</a> for updates.
        </span>
      </mj-text>
    </mj-column>
  </mj-section>
</mj-wrapper>
    
<mj-wrapper background-color="#f0f0f0" padding="10px 20px">
  <mj-section padding="0px" background-color="#ffffff">
    <mj-column width="50%">
      <mj-image fluid-on-mobile="true" padding="0px" src="https://via.placeholder.com/290x210" />
    </mj-column>

    <mj-column width="50%" background-color="#ffffff" vertical-align="middle">
      <mj-text align="center" font-family="Arial, sans-serif" color="#231f20" padding="20px">
        <span style="font-size: 14px; line-height: 18px;">
          <strong>For a seamless web experience, we recommend using these browsers:</strong> <br /><br />
          Chrome v63, Safari v10, FireFox v57, Internet Explorer v11 or their latest versions.
        </span><br /><br />
        <span style="font-size: 16px; line-height: 20px;">
          Click <a href="https://www.google.com" target="_blank" style="text-decoration: underline; color: #009fd4;">here</a> for updates.
        </span>
      </mj-text>
    </mj-column>
  </mj-section>
</mj-wrapper>
<mj-wrapper background-color="#f0f0f0" padding="10px 20px">

  <mj-section background-color="#ffffff">
    <mj-column width="100%" background-color="#ffffff">
      <mj-text align="center" font-family="Arial, sans-serif" color="#231f20">
        <span style="font-size: 28px; line-height: 30px;">
          1 Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
        </span>
      </mj-text>
    </mj-column>
  </mj-section>
</mj-wrapper>    
  </mj-body>
</mjml>
```
2. Copy the HTML code and run it in Litmus, selecting Outlook 2016/2019 (Windows variant), or go here: https://litmus.com/checklist/emails/public/a751173
3. See image attached for the issue

**Expected behavior**
Hairline should not appear.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: v4.3.1
 - MJML tool used: MJML App v2.11.0

**Email sending environment(for rendering issues)**:
 - None. Currently being tested on Litmus

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2016 & 2019 (random)
 - OS: Windows 7/10
 - Browser [e.g. Google Chrome]

**Screenshots**
See attached
![hairline-outlook-2016-windows](https://user-images.githubusercontent.com/374446/62280405-6ed76680-b47e-11e9-95bd-b53a227f9a42.png)

**Comment by iRyusa** [comment]
Well this is a bug in the outlook engine, and no one yet found a proper fix https://mosaico.io/email-client-tricks/outlook-2016-weird-1px-horizontal-lines/ 

It appears that sometime tweaking random stuff (as padding..., align attribute, adding a `dir="ltr"`)  is fixing it for some people.

**Comment by alfredtan** [comment]
Right... so it's really a trial and error thing?

**Comment by iRyusa** [comment]
And nothing we can do on MJML to prevent that :/

**Comment by alfredtan** [comment]
Thank you :(

**Comment by pmioni** [comment]
This issue happened to me on Outlook Office 365.
I managed to fix this on MJML, after numerous tries, with:

`
            <mj-class name="office365fix" height="10px"  />`

applied like this:

`<mj-text css-class="highlightText" mj-class="office365fix highlightText textLineHeight textPadding">`
