### ISSUE TITLE
Adding contenteditable="true" on mj-button

### ISSUE THREAD

**Issue by danfraticiu** [mjmlio/mjml#1662]
**Is your feature request related to a problem? Please describe.**
We need a way to add a contenteditable="true" attribute on the <a> tag generated but the <mj-button>. 

**Describe the solution you'd like**
Add an allowed attribute `contenteditable` on mj-button.

**Describe alternatives you've considered**
I tried adding a <span contenteditable="true"> inside the <mj-button> but even with that the browser will handle the click event on the <a> instead of placing the cursor on the <span>

**Additional context**
I could create a PR for this feature, I'm not familiar with the MJML code base, but after a quick look around I think it should be relatively simple. Question is if this is a feature that the team would consider adding.

**Comment by iRyusa** [comment]
Hi,

You can just use a regular span inside mj button for that like this : https://mjml.io/try-it-live/ry9r4h-XH

**Comment by danfraticiu** [comment]
Hi @iRyusa unfortunately that doesn't work (see here https://mjml.io/try-it-live/HyYP5_B7r) if you have a `href` on the `<mj-button>` (ex: https://mjml.io/try-it-live/HyYP5_B7r)

The contenteditable needs to be on the actual `<a>` for this to work.

**Comment by iRyusa** [comment]
Well "it works" kinda, it opens the link and you can also edit the content after closing the tab. The behavior isn't really the best for sure. You can also add an `onClick="javascript:return false;"` on the span but you need to remove it afterward :/ 

 It's a very specific use case and related to #200 but for now we don't have any proper solution to tackle this.

**Comment by danfraticiu** [comment]
But is this is a feature that would be considered? I could jump in and try to implement it.

**Comment by iRyusa** [comment]
As it's really specific, so I don't think we want to have this on "release". But you can just fork  components, add it and use it as a custom component.

**Comment by danfraticiu** [comment]
I understand, I'll probably go the custom component route. Thank you for your feedback.
