### ISSUE TITLE
Node >=8 is now mandatory to install MJML

### ISSUE THREAD

**Issue by snapeuh** [mjmlio/mjml#1665]
Hello,

We started using MJML for our project recently. We started with the very common `npm install mjml --save` and ended up with `v4.4.0-beta.2` which worked as expected on our dev, testing and prod environments.

However today, after a deployment we noticed an error installing the MJML package. The MJML package now require at least Node 8 to install.

This is due to this commit : https://github.com/mjmlio/mjml/commit/6dded94e36b661cfab2e0e2a6d3d77f8b90804b8#diff-8ee6c05367b124c491fc1f1d14203f47

This commit bumps the `chokidar` version to `3.0.0` and this version now needs Node 8 to install.

It's quite a big change between `v4.4.0-beta.2` and `v4.4.0-beta.3` (and next) and could break installs for other users aswell.

I'm posting this because it's not clearly advertised on the documentation nor on the package.json that MJML now needs Node 8 to install on a server.

Regards,

Romain.

**Comment by iRyusa** [comment]
Well Node 8 is in EOL this year and it's not really safe to use anymore cf https://github.com/nodejs/Release#release-schedule. The beta was mistakenly push on the wrong tag on npm so it never was a release candidate or anything (and you can't unpublish package after 72 hours on npm).

Feel free to open a PR on this (package.json and/or readme).

**Comment by snapeuh** [comment]
Hello,

Thanks for your answer. I know it’s EOL this year but as I said it wasn’t obvious that a minor update that is done automatically (because of the caret in the package.json) would result in an error when upgrading to the newest version.

My coworker submited a PR to explicitly tell that MJML is needing Node 8 as a minimum.

**Comment by iRyusa** [comment]
> The beta was mistakenly push on the wrong npm tag

As said, so the real upgrade is from 4.3.1 to 4.4.0, the beta isn't an RC. We can still make breaking change on it if we want so, plus the dep update was for a security issue.
