### ISSUE TITLE
Mjml navbar - outlook 2016 

### ISSUE THREAD

**Issue by Calfreider** [mjmlio/mjml#1668]
I'm building a template email with a navbar, but when I show it in Outlook 2016 the menu does go outside. I use MJML version 4.3.1

That the code I write:
`    
    <mj-section background-color="#6c675b">
      <mj-column>
        <mj-navbar base-url="#" hamburger="hamburger" ico-color="#d8d1ce">
          <mj-navbar-link href="#" color="#ffffff">Zimmer</mj-navbar-link>
          <mj-navbar-link href="#" color="#ffffff">Wellnessbereich</mj-navbar-link>
          <mj-navbar-link href="#" color="#ffffff">Test</mj-navbar-link>
          <mj-navbar-link href="#" color="#ffffff">Urlaubspauschalen</mj-navbar-link>
        </mj-navbar>
      </mj-column>
    </mj-section>
    `
    
Can you help me?

![images](https://user-images.githubusercontent.com/53857685/62611084-39f76380-b905-11e9-8b87-3144ed88bd0f.png)

**Comment by iRyusa** [comment]
Hi,

How did you send your email ? Can you try with putsmail.com

**Comment by kmcb777** [comment]
Hi @Calfreider , i tested with your mjml on emailonacid and i don't have this result, it renders fine.
How do you test exactly ? How do you send the email ?

**Comment by Calfreider** [comment]
Hi, 
I see this problem in outlook 2016.
I send the test mail with mjml.

**Comment by Calfreider** [comment]
Hi, the email rendering problem in Outlook 2016 is when I send the test email through the MJML Windows desktop App. When I send the html code through putsmail.com or mjml code through mailjet.com the problem doesn't exist.

**Comment by iRyusa** [comment]
Looks like it's an issue with Mailjet then, you should open a support ticket instead of here.

I'm closing then
