### ISSUE TITLE
mj-column how to set flexible width

### ISSUE THREAD

**Issue by mingthegit** [mjmlio/mjml#1669]
Is it possible to make `mj-column` fill up all available space of the parent section?
Basically something like `flex-grow: 1` in `flexbox`.

I want image and button to have fixed width and the text section to be flexible.
I had to workaround this by wrapping under `mj-group` and setting custom css using 
```
  width: calc(100% - 260px) !important;
  max-width: calc(100% - 260px) !important;
```

https://mjml.io/try-it-live/SJQ-KB_mS
```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-column border="1px solid black" />
      <mj-section border="1px solid black" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-section full-width="full-width">
      <mj-column width="100px">
        <mj-image src="/assets/img/logo-small.png"></mj-image>
      </mj-column>

			<mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
      </mj-column>
      
      <mj-column width="160px">
        <mj-button>Try it now</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Well the CSS support is too limited in clients to have something like that. There's no way to find the column width for Outlook conditional comments.

**Comment by mingthegit** [comment]
@iRyusa What I asked was not related to CSS at all.

I just wanted to check if there is an option to set flex width to `mj-column` component. I was not able find in the docs, since it says only percentage/px is allowed.

Can I take you as it's impossible? In that case, do you have any other suggestions to achieve similar?

**Comment by iRyusa** [comment]
> @iRyusa What I asked was not related to CSS at all.

It is, be cause it's a way to mimic a `flex:1` here. 

As stated in the previous comment, Outlook Desktop comments require a **fixed width**, so there's no reliable way to do that.

**Comment by mingthegit** [comment]
Okay, thanks for your clarification.
