### ISSUE TITLE
Hero background image is under wrapper background in Outlook

### ISSUE THREAD

**Issue by krystof-k** [mjmlio/mjml#1671]
When using _mj-hero_ inside _mj-wrapper_, which has a background color, the hero background (image) is hidden below the wrapper background color in Outlook because of `z-index: -3;`:

https://github.com/mjmlio/mjml/blob/11c88d13e827301fed34c446283f7aff6d867a83/packages/mjml-hero/src/index.js#L129

**To Reproduce**
1. Create a file with this MJML code:

   ```mjml
   <mjml>
     <mj-body>
       <mj-wrapper background-color="pink">
         <mj-hero
           mode="fixed-height"
           height="300px"
           background-width="600px"
           background-height="300px"
           background-url="https://placekitten.com/600/300"
           background-color="red"
         >
           <mj-text
             color="#ffffff"
             align="center"
             font-size="45px"
             line-height="45px"
             font-weight="900">
             MEOW
           </mj-text>
         </mj-hero>
       </mj-wrapper>
     </mj-body>
   </mjml>
   ```

2. Render it to HTML in version 4.4.1
3. Send the HTML to Outlook (I used Outlook 2007 on Windows 7)
4. You see pink background (of the wrapper) instead of a kitten

   ![image](https://user-images.githubusercontent.com/11633481/62639881-b52a3b00-b940-11e9-9bfd-be4e97d94676.png)

5. Delete the _z-index_ from compiled HTML code:
   
   ```html
   <!--[if mso | IE]><table role="presentation" border="0" cellpadding="0" cellspacing="0"> <tr><td class="" width="600px" ><table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:600px;" width="600" ><tr><td style="line-height:0;font-size:0;mso-line-height-rule:exactly;"><v:image style="border:0;height:300px;mso-position-horizontal:center;position:absolute;top:0;width:600px;z-index:-3;" src="https://placekitten.com/600/300" xmlns:v="urn:schemas-microsoft-com:vml" /><![endif]-->
   ```

6. And it renders the kitten:

   ![image](https://user-images.githubusercontent.com/11633481/62640130-2964de80-b941-11e9-94b3-8e96065ce91b.png)

**MJML environment (please complete the following information):**
- OS: macOS
- MJML Version: 4.4.1
- MJML tool used: NodeJS
- Email sending environment: [Putsmail](https://putsmail.com/)

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2007
 - OS: Windows 7

**Comment by krystof-k** [comment]
I know removing the z-index isn't a solution – it then overlays even the content (notice missing _MEOW_ on the image). _Which didn't matter for our campaign because we used transparent PNG._

**Comment by kmcb777** [comment]
Yes it can be a workaround for your use cas.
I remember trying to change this z-index for another background issue, and outlook was ignoring z-indexes on the hero content, so setting it negative on the hero container is the only way to see the content unfortunately.
We can keep this open for further testing

**Comment by krystof-k** [comment]
What about giving the wrapper even lower z-index? Could it work?

**Comment by iRyusa** [comment]
We need a bit of testing for that, but I don't think we'll be able to provide a fix on this one :(

**Comment by kmcb777** [comment]
We can't do anything indeed, i just made a few more tests to be sure, but i remember trying multiple combination, and z-index are ignored on most tags. If we set a z-index on the wrapper, it creates a new stacking context and the z-index:-3 on the vml inside it will still be underneath.
We'll precise this in mj-wrapper documentation

**Comment by kleimaj-dms** [comment]
The quickest solution I found was to remove the `<mj-hero>` from `<mj-wrapper>` like so:
html```
<mj-wrapper>
...
</mj-wrapper>
<mj-hero>
...
</mj-hero>
<mj-wrapper>

</mj-wrapper>
```
I was under a deadline so this was the quickest solution I can find to successfully rendering the background image behind the call to action text. With this solution I don't even have to touch the `z-index` in the html. I'm sure there are better solutions out there.
