### ISSUE TITLE
Outlook not rendering button correctly in 4.4.1 when sent from Intercom

### ISSUE THREAD

**Issue by krystof-k** [mjmlio/mjml#1672]
Button is not rendered with paddings in 4.4.1 when sent from Intercom. 4.3.1 works fine.

Intercom alters the HTML with unwanted whitespace, so that may be the case.

**To Reproduce**
1. Create a file with this MJML code:

   ```mjml
   <mjml>
   <mj-body>
      <mj-section>
         <mj-column>
         <mj-button font-family="Helvetica" background-color="#f45e43" color="white">
            Don't click me!
            </mj-button>
         </mj-column>
      </mj-section>
   </mj-body>
   </mjml>
   ```

2. Render it to HTML in version 4.4.1
3. Send the HTML to Outlook (I used Outlook 2007 on Windows 7)
4. Renders like this:

   ![image](https://user-images.githubusercontent.com/11633481/62642116-5adfa900-b945-11e9-9828-b2b530dc6ebc.png)
5. Render it in version 4.3.1:
   ![image](https://user-images.githubusercontent.com/11633481/62642167-6df27900-b945-11e9-983d-19cb3c04d43e.png)

**MJML environment (please complete the following information):**
- OS: macOS
- MJML Version: 4.4.1 / 4.3.1
- MJML tool used: NodeJS
- Email sending environment: Intercom.io

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2007
 - OS: Windows 7

Here is the diff of the rendered files:

```diff
16a17,28
>     .ReadMsgBody {
>       width: 100%;
>     }
> 
>     .ExternalClass {
>       width: 100%;
>     }
> 
>     .ExternalClass * {
>       line-height: 100%;
>     }
> 
44a57,69
>   <!--[if !mso]><!-->
>   <style type="text/css">
>     @media only screen and (max-width:480px) {
>       @-ms-viewport {
>         width: 320px;
>       }
> 
>       @viewport {
>         width: 320px;
>       }
>     }
>   </style>
>   <!--<![endif]-->
72c97
<     <div style="margin:0px auto;max-width:600px;">
---
>     <div style="Margin:0px auto;max-width:600px;">
76c101
<             <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;">
---
>             <td style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;">
79c104
<                 style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
---
>                 style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
89c114
<                             style="border:none;border-radius:3px;cursor:auto;mso-padding-alt:10px 25px;background:#f45e43;"
---
>                             style="border:none;border-radius:3px;cursor:auto;padding:10px 25px;background:#f45e43;"
92c117
<                               style="display:inline-block;background:#f45e43;color:white;font-family:Helvetica;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;">
---
>                               style="background:#f45e43;color:white;font-family:Helvetica;font-size:13px;font-weight:normal;line-height:120%;Margin:0;text-decoration:none;text-transform:none;">
```

**Comment by iRyusa** [comment]
Can you check with putsmail.com & 4.4.1 if it does the same, I can't seem to reproduce ?

**Comment by krystof-k** [comment]
Sorry, I misedited the post above. Putsmail works OK, problem is just with the Intercom, however the previous version works even there, so there may be some way to edit it.

I will try to post diff from the sent emails.

**Comment by iRyusa** [comment]
We use a new technique to enhance clickability on mj-button. I think they might remove mso-alt-padding for some obscure reasons ?

Anyway, nothing we can do on MJML side. We had some reply from Intercom support last time on #702 maybe you can ping them to see if they can find the solution.

**Comment by krystof-k** [comment]
Yeah, I'm already in touch with them, I'll keep you posted.
