### ISSUE TITLE
Outlook issues with hero component

### ISSUE THREAD

**Issue by nizz0k** [mjmlio/mjml#1674]
**Describe the bug**
I am attempting to use the hero component with a background image behind some centered text but I am having problems with the rendering in Outlook 365. The issue seems to be that the image isn't displayed, covers a portion of the top element in the email body, and then pushes down into the section below. Editing the raw html to change the z-index value of the image solves part of the problem, but the next section down is still covered by the image. I assume this is operator error. My image was edited in gimp and should be 600 x 300px.

**To Reproduce**
The code was generated and tested in the mjml.io in browser editor, VS code with the MJML extension, and in the MJML app. It was rendered to HTML and then pasted into a Mailchimp template and send using the Mailchimp Platform.

here is the code:
```xml 
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-accordion border="none" padding="1px" />
      <mj-accordion-element icon-wrapped-url="https://drive.google.com/uc?id=17Pj5TncdqBWdANJeMfzzYs7FPDl1dP0L" icon-unwrapped-url="https://drive.google.com/uc?id=1xs9dMhLofRoHVe9BkhhtFELnQOqizmBm" icon-height="24px" icon-width="24px" />
      <mj-accordion-title font-family="Roboto, Open Sans, Helvetica, Arial, sans-serif" background-color="#fff" color="#031017" padding="15px" font-size="18px" />
      <mj-accordion-text font-family="Open Sans, Helvetica, Arial, sans-serif" background-color="#fafafa" padding="15px" color="#505050" font-size="14px" />
    </mj-attributes>
  </mj-head>
  <mj-body background-color="#d7dde5">
    <mj-section full-width="full-width">
      <mj-column width="66.66666666666666%" >
        <mj-text align="left" font-size="11px" padding-bottom="0px" padding-top="0"><span style="font-size: 11px">[[HEADLINE]]</span></mj-text>
      </mj-column>
      <mj-column width="33.33333333333333%" >
        <mj-text align="right" font-size="11px" padding-bottom="0px" padding-top="0"><span style="font-size: 11px"><a href="https://mjml.io" style="text-decoration: none; color: inherit;">[[PERMALINK_LABEL]]</a></span></mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff" full-width="full-width">
      <mj-column width="33.33333333333333%" >
        <mj-image src="https://drive.google.com/uc?id=1oACJyNhnHMAqDTNlQCne1-Y4feLhCwZi" alt="GreenTec Capital Logo" padding-bottom="0px" padding-top="10px" width="125px"></mj-image>
      </mj-column>
      <mj-column width="66.66666666666666%">
        <mj-text align="center" padding-bottom="0px" padding-top="10px"><a href="#portfolio" style="text-decoration: none; color: inherit;">Portfolio Updates</a>
          <a href="#opportunities" style="text-decoration: none; color: inherit;">Investment Opportunities</a>
        </mj-text>
      </mj-column>
    </mj-section>
<mj-include path="./header.mjml"/>
```

and here is the header snippet 

``` xml
<mj-hero mode="fixed-height" height="300px" background-width="600px" background-height="300px" background-url="https://drive.google.com/uc?id=1aQ2X43Qm0RqYJMGQfpOgUKXYGcIEe8pu">
 <mj-text align="center" font-size="14px" color="#fff" padding-bottom="10px" padding-top="125px"><span style="font-size: 30px; line-height: 30px;">GreenTec Capital Partners</span><br/><br/>Investor Newsletter </mj-text>
</mj-hero>
```

**Expected behavior**
For the hero image to render within its container with the text above and no impact on the section below it.
**MJML environment (please complete the following information):**
 - OS: Windowns
 - MJML Version  4.3.0
 - MJML tool used MJML.io browser, VS Code and extension, tested in MJML desktop app.

**Email sending environment(for rendering issues)**:
Mailchimp

**Affected email clients (for rendering issues):**
 - Email Client Outlook 
 - OS: Windows

**Screenshots**
Outlook (with image missing)
![image](https://user-images.githubusercontent.com/23455125/62788694-b9349500-bac7-11e9-8aa0-02780ce1aacf.png)
Outlook (image present, but no text) 
![image](https://user-images.githubusercontent.com/23455125/62788832-09135c00-bac8-11e9-8d93-298a5460c769.png)
Expected Rendering:
![image](https://user-images.githubusercontent.com/23455125/62788861-14668780-bac8-11e9-8ffe-5f3efbf760b5.png)

**Additional context**

**Comment by iRyusa** [comment]
Can you test with putsmail.com instead of mailchimp to see if it's an issue from mjml or HTML being altered in any way ?

**Comment by iRyusa** [comment]
Yep so nothing we can do here, mailchimp just alter the HTML.
