### ISSUE TITLE
[v4.4.1] Version issue

### ISSUE THREAD

**Issue by bertho-zero** [mjmlio/mjml#1675]
**Describe the bug**
`mjml-validator` throw errors after a simple update of version 4.4.0.

**MJML environment (please complete the following information):**
 - MJML Version 4.4.1

**Additional context**
The problem comes from this commit (https://github.com/mjmlio/mjml/commit/72aae004f42f1ae4d939d2f3cf29539ddab41505), the version of `mjml-validator` has been updated in the package.json after the NPM release.

I have a monorepo with `packages/A` that has a dependency on `mjml@^4.4.0`, and a `package/B` that has a dependency on `mjml-validator@^4.4.1`.

The problem is that `mjml@4.4.1` requires `mjml-validator@4.4.0` (without `^`), so I have 2 versions of `mjml-validator` and the dependencies are not saved in the right place when I use `registerDependencies` (https://github.com/mjmlio/mjml/blob/master/packages/mjml-validator/src/dependencies.js#L10).

It can be seen in version 4.4.1 released here (line 49): https://unpkg.com/browse/mjml@4.4.1/package.json#L49

**Comment by bertho-zero** [comment]
A workaround to fix a problem with your publish, works only with yarn:
```
  "resolutions": {
    "mjml-validator": "4.4.0"
  }
```

4.4.0 works fine, 4.4.1 is broken.

**Comment by bertho-zero** [comment]
"I do not have the mistake so no one else can have it..."

I will wait for the next version!

**Comment by iRyusa** [comment]
We'll see if we can get a release next week, let's keep that open for now.

**Comment by kmcb777** [comment]
4.5 release don't have this problem so we can close this one
