### ISSUE TITLE
Unorganized view in email

### ISSUE THREAD

**Issue by imanubhardwaj** [mjmlio/mjml#1676]
**Describe the bug**
When I copy paste the mjml in live mjml editor, it works fine. https://mjml.io/try-it-live/By7xntAmH

But when I use google api's to send the email, the columns are unorganized, I mean they don't stack side by side but they rather position themselves one beneath the other. https://drive.google.com/file/d/1Zkv7VgbG53wu9anU6Q7GaWwB9Qdnak7U/view?usp=sharing

Any help on this would be appreciated.

**Comment by iRyusa** [comment]
Hi, 

They most likely alter the HTML when sent, to confirm try to test with https://putsmail.com to confirm

**Comment by imanubhardwaj** [comment]
> Hi,
> 
> They most likely alter the HTML when sent, to confirm try to test with https://putsmail.com to confirm

Hey @iRyusa you were spot on with this, can you please suggest me how to overcome this issue since I'm bound to use Google APIs.

**Comment by iRyusa** [comment]
There's nothing we can do on MJML side to prevent this, you should open a ticket on google support if they have a way to send raw HTML.
