### ISSUE TITLE
Austin template: Unnecessary effect that looks like solid 1px "border-right" after mj-section elements and after mj-text

### ISSUE THREAD

**Issue by nfedyashev** [mjmlio/mjml#1677]
**Describe the bug**

Unnecessary effect that looks like solid 1px "border-right" after mj-section elements and after mj-text that is only reproducible in desktop Outlook client

**To Reproduce**
1. Create a file with this MJML code from https://mjml.io/try-it-live/templates/austin
2. Render it to HTML by doing -config.minify=false --config.beautify=true
3. Send the HTML to an email address and open it using desktop Outlook

**Expected behavior**

**MJML environment:**
 - OS: Linux
 - MJML Version: 4.3.0
 - MJML tool used: https://github.com/sighmon/mjml-rails

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: https://postmarkapp.com  

**Affected email clients (for rendering issues):**
 - Email Client: "Microsoft Outlook for Office 365 MSO(16.0.11328.20362)
 - OS: Windows

**Screenshots**

![2019-08-12_849x498_scrot](https://user-images.githubusercontent.com/61983/62881944-990c0c80-bd39-11e9-9bb5-21827675cc8c.png)

![2019-08-12_844x496_scrot](https://user-images.githubusercontent.com/61983/62881993-a75a2880-bd39-11e9-95fc-1a240ca9d06b.png)

![2019-08-12_843x503_scrot](https://user-images.githubusercontent.com/61983/62882006-aa551900-bd39-11e9-86f2-084913cd3798.png)

![2019-08-12_842x502_scrot](https://user-images.githubusercontent.com/61983/62882011-ad500980-bd39-11e9-8946-ac4d2060d758.png)

![2019-08-12_841x495_scrot](https://user-images.githubusercontent.com/61983/62882018-afb26380-bd39-11e9-8dfe-927b3598102a.png)

![2019-08-12_600x395_scrot](https://user-images.githubusercontent.com/61983/62882095-d2dd1300-bd39-11e9-8fb8-6742edffe8cc.png)

**Additional context**

I really liked the original Austin template https://mjml.io/try-it-live/templates/austin  which worked great for all the emails that I send until we had a report that it renders completely different in desktop Outlook.

I've tried some other templates(https://mjml.io/try-it-live/templates/card for example), and it didn't have such this issue.

**Comment by iRyusa** [comment]
Well this is an weird outlook bug that we can't really solve where background email is "leaking" into content. Most likely a rounding issue inside Outlook... Sometimes there's some weird horizontal/vertical line appearing. Note that minify "sometimes" fix this, but there's no real solution and it's not really related to MJML

**Comment by probablyabear** [comment]
@nfedyashev I made the template. Can you be more specific on the error you're seeing? Is it that purple vertical line in the last picture you attached?

I'd be happy to look into the template and see if there's anything that can be done to fix.

**Comment by nfedyashev** [comment]
@iRyusa 
Thanks for the explanation and for the tips! I'll give it a try.

@probablyabear 
By the way thanks for your template! It looks great. I was trying find the original author but I couldn't until now.

> Is it that purple vertical line in the last picture you attached?
Yes!

https://stackoverflow.com/questions/57463664/mjml-unnecessary-right-border-between-elements-in-desktop-outlook this might be helpful for localizing the issue.

In the attachment I'll add what it looks like in my production emails(which are based on the Austin template).

![2019-08-14_470x384_scrot](https://user-images.githubusercontent.com/61983/63029339-0b572b00-beb9-11e9-8b65-0cd08b8db03c.png)

FYI: this issue could not be reproduced in the native Windows desktop "Mail" app, screenshots were made in "Microsoft Outlook for Office 365 MSO(16.0.11328.20362)".
