### ISSUE TITLE
problem rendering in outlook 2016 : css code visible

### ISSUE THREAD

**Issue by svenMOrd** [mjmlio/mjml#1678]
**Describe the bug**
I get the error trying to get the sample to work, 

**To Reproduce**
1. Create a file with this MJML code: https://mjml.io/try-it-live/templates/arturia
2. Render it to HTML by using the visual studio extension 1.6 or the latest npm version
3. Send the HTML to an email address with 'Sendgrid'
4. Gmail renders the file correct (although with a large whitespace before the mail), outlook shows the css text

**Expected behavior**
Shows the email

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version : latest
 - MJML tool used : Visual studio code / npm

**Email sending environment(for rendering issues)**:
 - sendgrid

**Affected email clients (for rendering issues):**
 - Outlook 2016
- Gmail
**Screenshots**
Outlook : 
![image](https://user-images.githubusercontent.com/24450744/62892456-9b299780-bd48-11e9-8156-d63c2850e098.png)
Gmail: 
![image](https://user-images.githubusercontent.com/24450744/62892602-f5c2f380-bd48-11e9-8d4c-b7ae44e1dfe4.png)

Rendering output html: 
[templateoutput.txt](https://github.com/mjmlio/mjml/files/3494033/templateoutput.txt)

**Additional context**
I tried the templates and my own simple attempts, all have the problem.

**Comment by iRyusa** [comment]
It seems that sendgrid just mess with your HTML nothing we can do on MJML to prevent that. You can still test your mail with https://putsmail.com
