### ISSUE TITLE
Add <modules></modules> to Template

### ISSUE THREAD

**Issue by A-D-E** [mjmlio/mjml#1679]
I use mjml with MyMail plugin (Wordpress). This <module> is being used for interactive editing in the WYSAWIG editor. I have to laboriously enter these modules by hand. Is there a possibility to include this option in the template?

**Comment by iRyusa** [comment]
Can you please show an example of what you want at least ?

**Comment by A-D-E** [comment]
of course! 
directly after <body> tag, comes <modules> and is logically closed before the </ body>, so </ modules>.
each module gets <module label = "some module label">
<Mj-section>
       <Mj-column>
         <! - Your first column ->
       </ Mj-column>
       <Mj-column>
         <! - Your second column ->
       </ Mj-column>
     </ Mj-section>
</ Module>
a single line, e.g. h1, h2 etc. always gets <single label = "some label">
<h1> <single label = "some label"> Title </ h1>

Paragraf always gets the <multi label = "some label">
<multi label = "some label"> <p> <multi label = "some multi label"> lorem ipsum <multi>

all other elements such as e.g. images, buttons etc. must contain this in their HTML structure:
editable = "" label = "some image"

here is the documentation: https://docs.mailster.co/?_ga=2.53288104.1216420370.1565642445-1812555056.1565642445#/templates-custom

best regards
from Potsdam, Germany

**Comment by iRyusa** [comment]
So you can already do this with mj-raw today, ex: https://mjml.io/try-it-live/HyoaZ81VH

Any final tag like mj-text,button,... can receive plain html so you should be able to do what you want
