### ISSUE TITLE
<mj-raw></mj-raw>

### ISSUE THREAD

**Issue by dominikzogg** [mjmlio/mjml#1682]
**Describe the bug**

All `<mj-raw>` tags get rendered within the html output.

**To Reproduce**

Create a mjml template and render it with:

```
mjml('some mjml', {
    filePath: 'path/to/index.html'
  });
```

**Expected behavior**

No <mj-*> tags are in the output

**MJML environment (please complete the following information):**
 - OS: Ubuntu 19.04 / OSX 
 - MJML Version 4.4.1

**Comment by philippjauss** [comment]
It's more specific, as it looks like to me. I recognized that behavior if I use <mj-raw> inside a <mj-text> for example. Reproduced with the  try live feature of the documentation (https://mjml.io/try-it-live/components/text)  with the following example:

`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          <mj-raw>{% if title %}</mj-raw>
          <h1>
            Hey Title!
          </h1>
          <mj-raw>{% else %}</mj-raw>
          <h2>
            Hey Subtitle
          </h2>
          <mj-raw>{% endif %}</mj-raw>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

Also reproduced if <mj-raw> used inside the following mjml tags. 
- <mj-table>
- <mj-accordion-title>
- <mj-accordion-text>
- <mj-button>
- <mj-navbar-link>
- <mj-social-element>

Maybe I've missed something in the documentation.

**Comment by dalefish** [comment]
There's no need for mj-raw within mj-text, you can just use the {% %} tags
directly in mj-text

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
Final tag that can contain html doesn't need `mj-raw`

**Comment by jrkd** [comment]
Hey @iRyusa is it possible to add the list of 'content' tags that dont parse (the mj-raw tag) to the docs @ https://mjml.io/documentation/#mj-raw? 

Cause it seems like there's a few of us trying to use mjml in conjunction with template languages and expecting mj-raw to work globally.

Also see #1482 #1626

**Comment by iRyusa** [comment]
Common rules is any tag that receive anything other than MJML behave as a content tag
