### ISSUE TITLE
Button hover not working

### ISSUE THREAD

**Issue by m-gleeson** [mjmlio/mjml#1683]
Having a hard time doing something seemingly very simple.... can't seem to get button hover styles working at all. Works fine with other elements, but not this. Best I can do is get the background table to adopt the bg color i'd like, but not the button proper.

Code goes like this:

`<mjml>
  <mj-head>
    <mj-style>
      .hover:hover > * { background-color: blue!important; }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-button css-class="hover" font-family="Helvetica" color="white" border-radius="12px" background-color="red">
          Don't click me!
        </mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

and then looks like this on hover:

![Capture](https://user-images.githubusercontent.com/46072622/63290795-37472780-c290-11e9-80a8-a94c6366cc3d.JPG)

any ideas?

**Comment by iRyusa** [comment]
You have to be a bit more specific about your css selector here : https://mjml.io/try-it-live/Hk_5ldOVr `.hover:hover > *` is not enough

**Comment by m-gleeson** [comment]
Thanks!

**Comment by dylanmrowe** [comment]
@iRyusa In the example you posted the button highlights when your mouse is anywhere on the row. 

I've tried multiple ways to make it only highlight when on the button, but can't get it to work. 

Any insight?

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/Hk_5ldOVr You only need to tweak the css selector.

**Comment by dylanmrowe** [comment]
@iRyusa I've tried many different selectors on the example button. Even with a selector such as

`<mj-style> .hover:hover p { background-color: blue !important; } </mj-style>`

The <p> tag (the button) highlights when hovering outside of the <p> tag. 

I've also tried `td > p`, `td p` and it always happens. 

Am I missing something basic about CSS, or is this a result of how the classnames are applied by MJML?

**Comment by ajaygharge-ds** [comment]
`<mj-button css-class="hover-blue" border-top="1px solid #000000" background-color="whitesmoke" color="black" mj-class="btn-10" align="center" href="https://www.apple.com">
        Click Me!
      </mj-button>`

if you have href attr in the button you can do hover by targeting "a"
```
.hover-blue:hover a {
        background-color: blue !important;
      }
```

**Comment by nuthinking** [comment]
> https://mjml.io/try-it-live/Hk_5ldOVr You only need to tweak the css selector.

Yeah, as soon as you put an href it breaks for me.
