### ISSUE TITLE
Background repeat outlook

### ISSUE THREAD

**Issue by AdamGodfrey93** [mjmlio/mjml#1685]
Hi guys,

I'm having an issue with the "background-url" within  "mj-section".

The problem that the background repeats in Outlook, while Gmail etc is fine.

I've tried background-repeat: no-repeat, but nothing seems to work.

 - Email Client: Outlook
 - OS: Windows
 - Browser: N/A

Thanks

Adam :)

**Comment by iRyusa** [comment]
Background image are handled by VML, so sadly there's no way to support no-repeat on background for section. There's a small hack to play with vml background size/height but the results aren't that great (it distort the background image).

**Comment by AdamGodfrey93** [comment]
Agh!!

I'll try and find a way around it myself too!

Thanks for the quick reply man!


Adam :)

**Comment by AdamGodfrey93** [comment]
I appear to have fixed the issue, well on my email anyway.

I've been sizing the image to 600px, to fit the width of the email.

But after trying a 1920x1080 the image sizes itself to fit the container!!


Adam :)
