### ISSUE TITLE
font-color in mj-table does not take action

### ISSUE THREAD

**Issue by barisdemiray** [mjmlio/mjml#1687]
**Describe the bug**
When I add an `mj-text` with `font-color` inside `mj-table`, color doesn't take effect.
 
**To Reproduce**
1. Create a file with this MJML code:

<mjml>
  <mj-body>

    <mj-section>
      <mj-column background-color="white">
        <mj-text color="#ff0000" font-size="25px">&#10004;</mj-text>
      </mj-column>
    </mj-section>

    <mj-section>
      <mj-column background-color="white">
        <mj-table>
          <tr>
            <td>
   	          <mj-text color="#ff0000" font-size="25px">&#10004;</mj-text>
            </td>
            <td>
   	          <mj-text color="#ff0000" font-size="25px">&#10004;</mj-text>
            </td>
          </tr>
        </mj-table>
      </mj-column>
    </mj-section>

  </mj-body>
</mjml>

2. Render it to HTML by doing
3. See error. `mj-text` outside the table is red while other is not.

**Expected behavior**
Having tick signs in red inside table.

**MJML environment (please complete the following information):**
 - OS: 18.04.3 LTS
- MJML App 2.12.0
- MJML v^4.4.1

**Screenshots**

![Screenshot from 2019-08-24 20-41-21](https://user-images.githubusercontent.com/2464842/63641490-c6e53f80-c6af-11e9-9e02-45383afb3736.png)

**Comment by iRyusa** [comment]
Mj table receive plain HTML only. So you don’t need any mj-text here.

**Comment by barisdemiray** [comment]
My bad, thanks a lot @iRyusa !
