### ISSUE TITLE
Spaces between rows on Outlook

### ISSUE THREAD

**Issue by byDaCz** [mjmlio/mjml#1688]
**Describe the bug**
There are some Spaces between rows on Outlook. It doesn't happen on Gmail or Apple Mail.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new project on Mailjet.
2. Create 2 rows with background colours.
3. Send the mail using the black button. "Send a test mail"

**Expected behaviour**
You can see a white spacing between the rows. Like 1 or 2 pixels.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version: 4.3.0
 - MJML tool used: Mailjet

**Email sending environment(for rendering issues)**:
 - The platform used to send the email: Mailjet

**Affected email clients (for rendering issues):**
 - Email Client: Outlook
 - OS: Windows
 - Browser: -

**Screenshots**

Between 2 grey areas:
![image-1](https://user-images.githubusercontent.com/25955389/63675710-b76a1180-c7e9-11e9-9552-f241dfa3b588.png)

Between Red and grey area:
![image-2](https://user-images.githubusercontent.com/25955389/63675716-bb962f00-c7e9-11e9-9e23-3edb0de5703f.png)

MJML + HTML files:
[Archivo comprimido.zip](https://github.com/mjmlio/mjml/files/3540106/Archivo.comprimido.zip)

**Comment by iRyusa** [comment]
Hi,

There's multiple random reasons where this can happen (you can search about outlook white line on google you'll find a lot of resource on this : https://mosaico.io/email-client-tricks/outlook-2016-weird-1px-horizontal-lines/ ) but there's no real fix about this one.

I'm closing because it's a bug within Outlook engine and there's nothing we can do to prevent this behavior

**Comment by byDaCz** [comment]
It doesn't happen when we do the same layout manually so I must say that Outlook is not the problem there...

**Comment by iRyusa** [comment]
<img width="643" alt="Capture d’écran 2019-08-26 à 12 39 10" src="https://user-images.githubusercontent.com/570317/63684980-88aa6600-c7fe-11e9-8edc-b7d74a952a4c.png">
Clearly not.
