### ISSUE TITLE
Bad path in mj-include does not make a validation error

### ISSUE THREAD

**Issue by mikob** [mjmlio/mjml#1689]
**Describe the bug**
If you use mj-include, when you call eg.
```
    const mostlyRenderedHTML = mjml2html(mjmlTemplate);
```

you might get errors with not being able to find the includes as comments in the html, but they should be validation errors IMO as they represent a serious ommission with the rendered html.

**To Reproduce**
Have mj-includes in a subdirectory.

**Expected behavior**
`mostlyRenderedHTML.errors` should not be `[]`, or strict validation should throw an error.

**MJML environment (please complete the following information):**
 - OS: Linux
 - MJML Version 4.2
 - MJML tool used node package

**Comment by iRyusa** [comment]
I really like this idea cc @kmcb777

**Comment by kmcb777** [comment]
Yes it would be quite logical indeed.
The only problem is that mj-includes are completely handled by the parser, and the parser only returns the JSON mjml, we'll have to modify the structure of the parser's output to be able to handle this.
This would break projects that use the parser directly, like passport :/

**Comment by iRyusa** [comment]
Mhhh right, but when parsing it, we replace non valid include by an mj-raw comment. Can we just maybe add an extra "hidden" params to this node and just read it on mjml-validator ?

**Comment by kmcb777** [comment]
Yup good idea 👍
Right now i think mj-raws are ignored by the validator, but this shouldn't be a real problem
