### ISSUE TITLE
Random `carouselId` breaks Jest-Snapshot tests

### ISSUE THREAD

**Issue by 12finger** [mjmlio/mjml#1690]
Concerns [mjml-carousel](https://github.com/mjmlio/mjml/tree/master/packages/mjml-carousel) only.

This line](https://github.com/mjmlio/mjml/blob/master/packages/mjml-carousel/src/Carousel.js#L45) generates a fully random id which is used on many css-classes and elements. On each render run it is different, so all snapshot tests involving a file that renders a carousel, brake.

<img width="1792" alt="notification-service-template-engine 2019-08-26 23-49-10" src="https://user-images.githubusercontent.com/1730022/63725980-39931e00-c85c-11e9-85be-2c1ae962257d.png">

Would be nice to have a static version for testing ?!
Or actually why use that random id in the firstplace ?

**Comment by iRyusa** [comment]
Well the id is needed to ensure that you can use multiple carousel in a single email. You can just stub the crypto package for that https://github.com/mjmlio/mjml/blob/master/packages/mjml-carousel/src/Carousel.js#L45

**Comment by 12finger** [comment]
@iRyusa  thanks so much for the super quick reply. 
and: True! 🤦‍♂ stubbing is the way to go ..
