### ISSUE TITLE
mj-image src validation

### ISSUE THREAD

**Issue by jnoga** [mjmlio/mjml#1691]
**Is your feature request related to a problem? Please describe.**
There are some email clients (Gmail for example) that do not support base64 image loading and they just show the alt value.

**Describe the solution you'd like**
In my opinion the best solution would be to validate (or show a warning?) de src content and check that starts with 'http(s)' string.

**Describe alternatives you've considered**
Another way to validate the src content would be to check that it does not start with 'data:' string.

**Comment by iRyusa** [comment]
Hi,

I don't think we'll do that because some people are using templating in `href` so it would trigger validation issue for nothing.

**Comment by jnoga** [comment]
Ok, got it

What about the alternative of not allowing  src content starting with 'data:'?

**Comment by iRyusa** [comment]
You can still add your own validation rules, with https://github.com/mjmlio/mjml/blob/master/packages/mjml-validator/src/index.js#L10 

I don't think we should have an opinion about this, as it's a user preference (you don't accidentally put a base 64 image inside your mjml document)
