### ISSUE TITLE
mjml-cli: add sanitize-html option

### ISSUE THREAD

**Issue by jnoga** [mjmlio/mjml#1692]
**Is your feature request related to a problem? Please describe.**
There are some email services that do not sanitize the html content and Gmail adds the "clipped" message if there are unescaped characters.

**Describe the solution you'd like**
Add a sanitize option to mjml-cli commands.

**Comment by iRyusa** [comment]
Don't know if we should add that, it will need again to add an external dep that could potentially alter the output file.

Keeping that open for now
