### ISSUE TITLE
Bulk process multiple MJML templates?

### ISSUE THREAD

**Issue by davidchameleon** [mjmlio/mjml#1694]
Hello,
We are developing Email Templates for a large organisation and so far we've found MJML to be a great framework!

We are developing a large volume of templates (120+)  - many of which are similar, with minor adjustments to header and footer.

So each time a client makes a change to one of the templates, I need to manually go through and enter the commands to compile the MJML into HTML.

Is there a way this process could be made faster - an option or workflow that would allow for the bulk processing of these templates?

I have begun looking into developing shell scripts for this purpose but I wondered if there was a native method that I am missing?

Many thanks.

**Comment by kmcb777** [comment]
Hello @davidchameleon you could use a gulp task that compiles all your templates, there is a boilerplate here : https://github.com/mjmlio/gulp-mjml

**Comment by iRyusa** [comment]
Default cli has a `watch` mode that looks into nested mj-include too. But it will output every template in a single directory.

Looks like a task runner like gulp would do the job for you as @kmcb777 said

**Comment by davidchameleon** [comment]
Great, I will take a look into using Gulp to compile the templates and speed up the workflow. 
Thanks for your help guys.

**Comment by matepaiva** [comment]
I had the same issue and didn't want to add gulp to my stack, so I made a script with Node.

I will leave the script in a gist just in case someone is looking for a quick solution.

https://gist.github.com/matepaiva/de1c8c6a1d827c462b4e17e2839fbc83

**Comment by wottpal** [comment]
@matepaiva just want to let you know that you are my hero today!!

**Comment by matepaiva** [comment]
Wow! I didn't even remember that I did it last year, lol! I am glad to help :)

**Comment by clementducerf** [comment]
@matepaiva Thanks for the script !
