### ISSUE TITLE
Border-Radius with Mj-Column?

### ISSUE THREAD

**Issue by Narey** [mjmlio/mjml#1695]
**Describe the bug**
Hi, is it possible to use the border-radius attribute to a column that has a border defined? As it doesn't seem to work for me :(

**To Reproduce**
Steps to reproduce the behaviour:
Head over here: https://mjml.io/try-it-live/HyYggDSHr 

**Expected behavior**
To have borders on the columns, it only seems to work for sections at the moment?

**MJML environment (please complete the following information):**
 - Latest MJML Online Try-It-Live

Any help or advice would be greatly appreciated :)

Thanks,

**Comment by iRyusa** [comment]
This is a known issue due to `border-collapse`, the border-radius only work on background color, not border. Overriding the default value could work https://mjml.io/try-it-live/SklHbPBrr but it could lead to inconsistency over Outlook desktop & old desktop clients.

**Comment by Narey** [comment]
So for now, you'd recommend just using the section as the border/radius for the best compatibility?

**Comment by iRyusa** [comment]
I think it's even worse on mj-section as the radius is applied on table and the border on the `td`, we need to move them on the same element cc @kmcb777

**Comment by kmcb777** [comment]
@iRyusa  i think this was intentional because border-radius is ignored on the td on some clients, or something like this ?

**Comment by iRyusa** [comment]
I don't think so, the column has everything applied on the table
