### ISSUE TITLE
[mj-font]Implement our own hosted fonts

### ISSUE THREAD

**Issue by yosh970** [mjmlio/mjml#1697]
Hello there, I'm desperately trying every possible ways to use my own hosted fonts.

Setting a googleapi font through the tag bellow works perfectly
`<mj-font name="Raleway" href="https://fonts.googleapis.com/css?family=Raleway" />`

How ever if I try with my own URL such as below it does not work
`<mj-font name="MyFont" href="https://path/to/font/Averta-Semibold.woff2" />`

I also tried using `@fontface{}` in head mj-style tag such as bellow, but again, not successful

`<mj-style>`
 `@font-face {`
 `font-family: 'AvertaSemibold';`
`font-style: normal;`
`font-weight: 600;`
`src: local('AvertaSemibold'), local('AvertaSemibold'), url(https://path/to/font/Averta-Semibold.woff2") format('woff2');`
`unicode-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF;
  }`
`</mj-style>`

Is there any way to use fonts hosted on our own server ?

Regards
Keep up the good work ❤️

**Comment by iRyusa** [comment]
Sorry about the late reply, you have multiple solution:

Either you require an hosted css file that work as google font and use mj-font (ex : https://fonts.googleapis.com/css?family=Roboto&display=swap ). Or you do this manually with an mj-style, but some client like Outlook desktop will fallback all the font to Times

**Comment by abdul-Tz-prog** [comment]
@iRyusa Is there any solution now available where I can include my local fonts in MJML ?
I know that google fonts works fine but can you guide me for solution about local fonts that works also for outlook and gmail ?
Thanks in advance.

**Comment by iRyusa** [comment]
The sameway as you would google do: host it on a server and host the stylesheet that imports it.

**Comment by abdul-Tz-prog** [comment]
@iRyusa  It will be really helpful. If you suggest me any article or tutorial about this, where I can look and understand it.

**Comment by spencerr-carimus** [comment]
@abdul-Tz-prog e.g. click here: https://fonts.googleapis.com/css?family=Montserrat

copy the CSS

Put it in `<mj-style>` in your `<mj-head>`

The problem however is this won't get your font to show up in most email clients since they do not support the `@font-face` rule.  So unless you pre-render your custom font as an image or something crazy like that, you're basically out of luck.

**Comment by iRyusa** [comment]
Do not paste font face into mj style or outlook will fallback every text to Times. Just use mj-font.

**Comment by spencerr-carimus** [comment]
> Do not paste font face into mj style or outlook will fallback every text to Times. Just use mj-font.

Won't make a difference in Gmail

**Comment by iRyusa** [comment]
But a huge one in Outlook :)

**Comment by spencerr-carimus** [comment]
And for that reason I'm pretty sure you could do _both_ (font faces and import with `mj-font`).  Using font faces won't help in Gmail or Outlook but it will in Apple Mail for example.  Abdul was asking for something that works for both Outlook and Gmail.  At least for Gmail, you really can't do much at all except fallback to a font that Gmail natively has (e.g. Roboto, Tahoma, Verdana, etc)

**Comment by iRyusa** [comment]
As soon as Outlook encounter a single font-face declaration/stylesheet import it will set all font as Times. So the only way to prevent Outlook do so is surround font import via outlook conditionnal. That's what `mj-font` does, so no you can't do both.

**Comment by spencerr-carimus** [comment]
Leave it to Microsoft to have the weirdest behavior of all in their email client 🙄
