### ISSUE TITLE
MJ Table image is full size?

### ISSUE THREAD

**Issue by Narey** [mjmlio/mjml#1702]
Hi!

I have a quick demo email that puts an image and text within a table, you can see this here:

https://mjml.io/try-it-live/r1FTTq7Ur

During the preview, it looks how I want it to look. However, when sending out, the icon is HUGE and I don't know why?

![image](https://user-images.githubusercontent.com/11885821/64522988-32a3eb00-d2f3-11e9-8948-2e49ae9fdeb9.png)

This is what it looks like when send to an Outlook client however, on Outlook mobile, it's fine.

Can someone advise me on what's the best way to get this layout? Or how to fix this issue?

Thanks,

**Comment by iRyusa** [comment]
Hi,

Just add a regular style="width:20px;" on the `img`, and remove `px` in `width` attribute it's unitless. It should works like that

**Comment by Narey** [comment]
Do you mean like this?

https://mjml.io/try-it-live/rJhpCjQUB

If so, it still generates the overly large image as before.

**Comment by iRyusa** [comment]
Maybe copy the code of mj-image then `<td style="width:20px;"> <img height="auto" src="https://cdn4.iconfinder.com/data/icons/free-colorful-icons/360/google_docs.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;" width="20" /> </td>`

I know that outlook doesn't like any of retina image, resizing it down to the actual size might just be the way to go if it doesn't work.
