### ISSUE TITLE
Allow CLI options to be set in mjmlconfig as well

### ISSUE THREAD

**Issue by muuvmuuv** [mjmlio/mjml#1709]
**Is your feature request related to a problem? Please describe.**

I parse a lot of files and appending `--config.minify=true` to every file seems odd. It would be great if I could just add it to the `.mjmlconfig`.

**Describe the solution you'd like**

In `.mjmlconfig`:

```json
{
  "config": {
    "minify": {
      "enabled": true,
      "option": {
        "minifyCSS": true
      }
    }
  },
  "packages": []
}
```

**Describe alternatives you've considered**

Another solution would be to allow wildcards. So I could do this: `mjml email/*.mjml -o email/[filename].html`.

**Additional context**

I guess both of my solution would be great. So mjml can compile multiple files at once and also takes options from a file instead of creating a long CLI command.

**Comment by muuvmuuv** [comment]
@iRyusa nice, haven't found any documentation about that :), worth adding I guess.

**Comment by csojinb** [comment]
+💯 for this suggestion. We have gotten around this by wrapping the mjml commands in various scripts for devs to use, but sometimes you do still have to run `mjml` directly, and it would be really nice to have our preferred CLI options set without having to think about it. Much easier for someone new to this area of the codebase to use.

**Comment by iRyusa** [comment]
We'll try to push this asap 👍
