### ISSUE TITLE
mjml-core 4.5.0 not released properly

### ISSUE THREAD

**Issue by avif** [mjmlio/mjml#1715]
Version 4.5.0 was released a few hours ago, mjml was updated but mjml-core was not (never released to npm).

**To Reproduce**
1. `npm i mjml-core@4.5.0` or visit https://www.npmjs.com/package/mjml-core

**Expected behavior**
All mjml packages are released with latest version.

**MJML environment (please complete the following information):**
Not relevant.

**Email sending environment(for rendering issues)**:
Not relevant.

**Affected email clients (for rendering issues):**
Not relevant.

**Screenshots**
Not relevant.

**Additional context**
Not relevant.

**Comment by paleite** [comment]
Also: https://www.npmjs.com/package/mjml

**Comment by Manoz** [comment]
Same issue with our CI builds:

```sh
npm ERR! notarget No matching version found for mjml-core@4.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mjml'
npm ERR! notarget 
```

**Comment by rvanzon** [comment]
any workaround?

**Comment by gasperecf** [comment]
> any workaround?

same as last time on same issue with 4.4.1 release, use lower version, until its somehow starts working

**Comment by iRyusa** [comment]
We're working on it, we have a silent failing when publishing some packages with Lerna.

**Comment by iRyusa** [comment]
It should be fine now, mjml-core has been (re?)released !

You might have some cache issue still on NPM side, just wait few minutes and everything will be good :)
