### ISSUE TITLE
MJML Location element stopped working

### ISSUE THREAD

**Issue by WebmasterClickPanda** [mjmlio/mjml#1717]
Hello!

Today the API stopped rendering our templates, it looks like the line-height css property is not accepting "normal" nor floating numbers or int numbers.

We could fix this and most of our mjml templates are rendering correctly. However the element <mj-location/> causes errors during rendering.

We have even tried the "try-it-live" option rendering the following basic element:

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-location address="37 bis, rue du Sentier 75002 Paris" />
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

However , the reply is "MJML badly formatted", it used to be working a few days ago.

Was this element removed or the syntax changed? Thanks for your help.

Best regards

**Comment by ngarnier** [comment]
Hello, 

We updated the API to MJML 4 last week, several notices and reminders were sent (see [this example](http://go.mailjet.com/nl2/618y/5n6vg.html?hl=en)). It is now running on the v4 syntax while you are using the v3 syntax which explains the issues you're encountering (you can find more info in the email link I shared).

Best

**Comment by WebmasterClickPanda** [comment]
Thanks for your reply, however none of the v4 articles mentions anything about the ml-location element, and the syntax of my example is correct for v4, I will keep looking and trying, but even the mj-location element does not work on the mjml website and the migration tool just deletes the element. Does this simply mean this element does not exist anymore?

**Comment by WebmasterClickPanda** [comment]
I have even looked at your official documentation: https://mjml.io/documentation/#standard-body-components

The element mj location does not appear anymore, looks like it was deleted

**Comment by ngarnier** [comment]
Yes, it was deprecated as well as `mj-container` in [MJML v4.0](https://github.com/mjmlio/mjml/releases/tag/v4.0.0), which explains why it doesn't dispaly on the try it live.
