### ISSUE TITLE
Add letter-spacing attribute to mjml-button

### ISSUE THREAD

**Issue by bvonhalle** [mjmlio/mjml#1724]
**Is your feature request related to a problem? Please describe.**
Our button styles require letter-spacing (they are all caps and it looks much better with the letter-spacing). This seems like a relatively simple, straightforward addition.

**Describe the solution you'd like**
Just add `letter-spacing` as an attribute.

**Describe alternatives you've considered**
Allow for mjml-text or a span inside a button as a hack.

**Additional context**

**Comment by HenriqueFadoni** [comment]
Is this issue still open? I want to solve it

**Comment by ngarnier** [comment]
Hi @HenriqueFadoni, thanks but you can see above that a PR was submitted and merged, so it'll be closed in the next release.

**Comment by bvonhalle** [comment]
Thank you all, this was my first open-source issue and it was solved within 10 days, so cool!

This community gives me faith in humanity.
