### ISSUE TITLE
Column widths are not inlined

### ISSUE THREAD

**Issue by brafkind** [mjmlio/mjml#1729]
When specifying a column width, the css for it is written inside a <style> tag rather than being inlined. First, why? Second, this causes problems for applications that strip/sanitize <style>. The workaround is to use a custom css class that does the same thing.

For example,
```
<mj-style inline="inline">
  .column-per-16 {
    width: 16% !important;
    max-width: 16%;
  }
</mj-style>
...
<mj-column css-class="column-per-16">
```

**Comment by kmcb777** [comment]
Hi @brafkind, there is already a width of 100% set in an inline style attributes, for mobile.
This one in the head is intended for desktop.
With your workaround the columns will no longer be responsive.
