### ISSUE TITLE
Allow mj-include to include other templates in online editor

### ISSUE THREAD

**Issue by crnastena** [mjmlio/mjml#1733]
I could not find any documentation on how to use mj-include with Online Editor. If such feature exists please point me in the right direction.

For example, I would like to include template like this:

`<mj-include template-id="1092334"></mj-include>`

Or if this is something that will not be implemented for online editor, at least add some documentation about it, so if anyone wants to use mj-include they would get an error other than what is shown in the screenshot.

<img width="719" alt="Screenshot 2019-10-14 at 11 09 16" src="https://user-images.githubusercontent.com/1594571/66744042-523eae00-ee73-11e9-814b-57bceb49ccc2.png">

**Comment by kmcb777** [comment]
Hi @crnastena actually with mj-include the path needs to target another mjml file. So it won't work with a template id indeed. I don't think it's planned to implement template inclusion on Passport.
I'll see if there is a documentation specific to this editor because this is not directly related to mjml.

**Comment by crnastena** [comment]
It seems that online editor HTML templates have "Saved sections" which can be linked inside of templates. But no such feature exists for MJML. 

Maybe in MJML online editor you can have <mj-saved-section></mj-saved-section> or <mj-link></mj-link> that links to MJML Saved sections. 

Anyway, as you said this is not related to MJML but online editors. I will close the issue at the end of the day.

**Comment by zingix** [comment]
This would be a very helpful extension. At the moment with the section the editor capabilities are limited. It should be possible to switch to MJML for sections 👍
