### ISSUE TITLE
Include paths seem to be treated differently depending on build process

### ISSUE THREAD

**Issue by anothersailor** [mjmlio/mjml#1734]
**Describe the bug**
Depending on whether I compile the mjml files from vs-code's mjml extension, or from npm installed mjml & mjml-utils (using "npm run email-build" script as per mjml-utils instructions), the compiler will, or will not find the includes.

Is there a way to set a path that is understood by all tools?

**To Reproduce**

The file hierarchy is:

- /web-project/subdirectory/mails/
    - templates/
    - source/
         - shared/

The mjml partials to include are in /shared/
The mjml template including the partials is in /source/
The html output goes in /templates/

With vs-code's "export html" or preview, the following include statement is understood and the build succeeds:
```
<mj-include path="./shared/header.mjml"
```

When running the build with npm, the same include produces an html with, instead of the partial's code: 
`<!-- mj-include: file not found /Users/Me/Documents/web-project/shared/header_french.mjml -->`, or nothing at all. (the path not found is missing /subdirectory/mail/ to be valid).

Seems that the mjml desktop application parses the includes paths the same way than vs-code.

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: MacOS 10.14
 - MJML Version: mjml 4.5.1, installed in the project with npm
 - MJML tool used: mjml-utils 2.2.1; vs-code with extension mjml 1.6.0 from Attila Buti.
- npm is installed globally

Many thanks,
E.

**Comment by ngarnier** [comment]
What do you mean with this? 
> When running the build with npm

Are you referring to MJML built-in CLI? mjml-utils CLI?

**Comment by anothersailor** [comment]
Yes, good question.

I run njml-utils CLI from npm, (installed it with npm in the project).
(cf. https://www.npmjs.com/package/mjml-utils).

Here are the scripts, as defined in package.json:
`
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "email-build": "mju --build -i ./v6_admin/v6_admin_templates_html/mails/source -o ./v6_admin/v6_admin_templates_html/mails/templates",
    "email-watch": "mju --watch -i ./v6_admin/v6_admin_templates_html/mails/source -o ./v6_admin/v6_admin_templates_html/mails/templates",
    "email-send": "mju --send -o ./v6_admin/v6_admin_templates_html/mails/templates"
  },
`
You are right, I coud probably have used the njml CLI directly, as I am adding a layer of complexity. For some reason though, the njml command is not recognised from my project directory, so would have to add it to my PATH.

As a side note, it also seems that the "includes" are not managed the same way. I have 3 in my current templates: a "styles paragraph" for the HEAD, a header and a footer. When I use vs-code to compile (or rather "export html"), with the relative included paths originating in my mail template directory, all three includes are included. When I use npm scripts with "longer" include paths originating in my web-project root, the first two are included, but not the third (footer). Currently trying syntax options to understand the difference.

The only difference I see is the content of the includes. The footer contains the following:
`
<mj-spacer height="50px"/>
<mj-text mj-class="text_centered">
    <a href="https://mysite.com">www.mysite.com</a>
</mj-text>
<mj-text mj-class="text_centered">
    Tel: +33 6 80 94 14 45
</mj-text>
<mj-social mj-class="text_centered">
    <mj-social-element href="url" href="https://www.facebook.com/pages/mypageID" src="https://mylinkto/facebook-b&w.png">
        Facebook
    </mj-social-element>
    <mj-social-element href="url" href="https://www.instagram.com/mypageID" src="https://mylinkto/instagram-b&w.png">
        Instagram
    </mj-social-element>
    <mj-social-element href="url" href="https://www.pinterest.fr/mypageID/" src="https://mylinkto/pinterest-b&w.png">
        Pinterest
    </mj-social-element>
</mj-social>
`
E.

**Comment by ngarnier** [comment]
The [mjml-utils](https://github.com/justinsisley/mjml-utils) package which is a community library hasn't been updated in 2 years and runs on MJML v3 so it's not surprising you're seeing differences. I suggest to either stop using it, do a PR to update it or create an issue on that package. 

As for the mjml command not being recognized, like you said it's expected if installed locally and not added to your path.

**Comment by anothersailor** [comment]
OK. Will try to use mjml direct! Thanks, E.

**Comment by anothersailor** [comment]
Excellent advice. Confirming that the problem was mjml-utils...
Many thanks again.
E.
