### ISSUE TITLE
API sometimes returns invalid JSON

### ISSUE THREAD

**Issue by intelliweb** [mjmlio/mjml#1736]
**Describe the bug**
The MJML API sometimes returns invalid JSON when attempting to render MJML as HTML.

**To Reproduce**
1. Render MJML to HTML via the API.
2. Decode returned JSON (containing HTML) via PHP json_decode.
3. Receive PHP error: Control character error, possibly incorrectly encoded.
I'm happy to share an example of invalid JSON response privately. Just let me know the best way to get it to you.

**Expected behavior**
Valid JSON should have been returned.

**MJML environment (please complete the following information):**
API

**Additional context**
The invalid JSON is not returned with every API call. Rendering some emails works fine while others consistently return invalid JSON.

**Comment by kmcb777** [comment]
Hi @intelliweb thanks for reporting this, could you please provide an example of an email that return invalid Json ?

**Comment by ngarnier** [comment]
By the way I would suspect this is not random, but rather depending on the payload you actually send. 
> Rendering some emails works fine while others consistently return invalid JSON.

I suppose you're sending some content that varies from one time to the other, maybe user-generated emails? I'd start there and see if that could be where the invalid characters are coming from. This is the first time this is raised in years and there's absolutely no reason for the API to randomly return wrong characters.

**Comment by iRyusa** [comment]
This has been reported here too #1637

**Comment by ngarnier** [comment]
Alright, never got an answer on this one so I still suspect it's due to the input sent but let's see :-)

**Comment by intelliweb** [comment]
@kmcb777 Please find the request and response JSON here:
https://gist.github.com/intelliweb/c9a14f61cf2bd16b8d5e31b587b80de7

@ngarnier Yes, it is probably related to the content. Some of the content does vary with each email. I just can't figure out what in the email would cause the issue. The request is valid JSON according to jsonlint.com

Let me know if I can do anything else to help.

**Comment by iRyusa** [comment]
@intelliweb Does the provided json will 100% output a invalid json ?

**Comment by intelliweb** [comment]
@iRyusa - Sorry, I don't understand the question.

**Comment by iRyusa** [comment]
With this JSON here: https://gist.github.com/intelliweb/c9a14f61cf2bd16b8d5e31b587b80de7#file-request-json does the api will always return an invalid JSON?

**Comment by intelliweb** [comment]
@iRyusa Yes. Every time I have tried with the API it has returned invalid JSON.

**Comment by intelliweb** [comment]
@iRyusa After running several times without issue, this has happened again with a different email. Same overall template but different content within the template. I've included the request and response JSON in the Gist as request2.json and response2.json

https://gist.github.com/intelliweb/c9a14f61cf2bd16b8d5e31b587b80de7

Any ideas?

**Comment by iRyusa** [comment]
Both responses have exactly the same length, that's interesting... we'll check that, it might be an issue between go & node

**Comment by intelliweb** [comment]
Awesome. Thank you @Tommy-42 !

**Comment by Tommy-42** [comment]
sorry for the delay @intelliweb, the fix has been released, you should now be able to send your payload without any problem !

**Comment by intelliweb** [comment]
Thanks so much @Tommy-42 
Sounds like we should be all good now. Since this was a sporadic issue that we only saw once a month or less with certain emails, you may want to just close it out now. I'll reach back out if we encounter any other errors.
