### ISSUE TITLE
Outlook not rendering the email template as the other clients

### ISSUE THREAD

**Issue by Janchey** [mjmlio/mjml#1738]
**Describe the bug**
I have a problem with the Outlook rendering on Windows. OSX works good, but Windows Outlook renders all columns in one row. 

**To Reproduce**
1. Create a file with this MJML code: https://mjml.io/try-it-live/Sy7wWO3tH
I use MJML sublime extension and the code is bigger but the problem is the same with all my sections. Also i use <mj-include> for templating. Output.html is good on all other email clients.
2. Render it to HTML by doing: mjml quote.mjml -o output.html
3. Send the HTML to an email address with: https://litmus.com
4. See error: I have no errors

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version not surre... I get the "error: no input argument received" in the cmd
 - MJML tool used MJML Sublime extension

**Email sending environment(for rendering issues)**:
 - Platform used to send the email. NONE - just testing on https://litmus.com

**Affected email clients (for rendering issues):**
 - Email Client Outlook
 - OS: Windows
 - Browser Google Chrome

**Screenshots**
http://prntscr.com/pmouvi You should be able to see the problem on that link.

**Comment by iRyusa** [comment]
Hi,

You have more than 100% of content in sections, just split your email into multiple sections

**Comment by Janchey** [comment]
> Hi,
> 
> You have more than 100% of content in sections, just split your email into multiple sections

So every column with width 100% should be in its own section?

**Comment by iRyusa** [comment]
You can't have more than 600px or 100% of content in a section. In bowser it works fine, but this is because CSS support is actually not an issue

**Comment by Janchey** [comment]
> You can't have more than 600px or 100% of content in a section. In bowser it works fine, but this is because CSS support is actually not an issue

Thanks for the info. I will change styles for all my sections. 

Now I get another problem. 
One section should has 3 columns in a row and below another row with 2 columns. So its 5 columns 3+2. All of this should be in one section. Is it possible?

Again only Outlook renders it like 5 columns in a row. Other clients render it correctly.

**Comment by kmcb777** [comment]
No, a section is meant to be a row (in desktop, and in mobile each column becomes a row).
Why do you need them to be in one section ?
