### ISSUE TITLE
Rendering issue with inline style in combination with mj-raw

### ISSUE THREAD

**Issue by kventil** [mjmlio/mjml#1739]
**Describe the bug**
When using `<mj-style inline="inline">` in combination with `<mj-raw>` strange replacement patterns occur.

**To Reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-head>
  <mj-style inline="inline">
    h1 {}
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-raw>
    <#if test=="condition">
    </mj-raw>
  </mj-body>
</mjml>
```
(included live sample: [https://mjml.io/try-it-live/Hkt_PtTYB](https://mjml.io/try-it-live/Hkt_PtTYB)) 
2. Render it to HTML
3. Result: 

```
<body>
  <div style="">
    <#if test="=" condition "">
    </#if>
  </div>
</body>
```

**Expected behavior**
```
<body>
  <div style="">
    <#if test=="condition">
  </div>
</body>
```

**MJML environment (please complete the following information):**
 - OS: Windows, Osx, Docker
 - MJML Version 4.3.0
 - MJML tool used: Visual Studio Plugin, Live Editor, API

**Screenshots**
Result: ![grafik](https://user-images.githubusercontent.com/111546/67372297-f9130080-f57d-11e9-8122-bc47fad80504.png)

**Additional context**
This occurs only if I use the the `inline="inline"` paramter. As soon as I change `inline` to something elese it works. e.g.: `inline="whatever"`. (See [https://mjml.io/try-it-live/H1gLTFptr](https://mjml.io/try-it-live/H1gLTFptr))

**Comment by iRyusa** [comment]
Can you try with latest version instead 4.3 ?

**Comment by iRyusa** [comment]
Yep you have an option for that in cli now : https://github.com/mjmlio/mjml/commit/20c39e8508dbb235abf9304e9468a353cc60a646

**Comment by kventil** [comment]
@iRyusa Got the same error with the 4.5.1.
Thanks for the super fast reply <3

**Comment by kventil** [comment]
Not sure if it helps, but I tried it with the following snippet and was not able to preseve the tags.

```
var opts = {
    keepComments: ('true')
    minify: ('false'),
    validationLevel: ('skip')
    juicePreserveTags: ('{"freemarker": { "start": "<#if", "end": "</#if" }}')
};
  var result = mjml2html(input || '', opts);
```

**Comment by iRyusa** [comment]
Well as we use juice you should open an issue with a reproductible snippet on https://github.com/Automattic/juice they might be able to find this out for you.

**Comment by kmcb777** [comment]
@kventil if you're not using the cli, the juicePreserveTags option should be an object, not a string, so just `juicePreserveTags: {"freemarker": { "start": "<#if", "end": "</#if" }}`

**Comment by kventil** [comment]
@kmcb777 Thanks. That solved my problem. @iRyusa for me this would make this ticket obsolete. If you're ok with it i'd close this ticket. :)

**Comment by Micah-S** [comment]
I'm unable to preserve tags (in 4.5.1) while launching with the following:
`mjml DefaultPdf.mjml -o ../Transactions/DefaultPdf.html --config.juicePreserveTags='{"freemarker": { "freemarker": "<#", "end": ">" }}'`

Given the example in the initial post, `<#if test=="condition">` continues to become `<#if test="="condition""> </#if>`

The main issue for me is the automatic closing tag. It isn't a problem for _if_ tags, however a closed _include_ tag will error when processed through FreeMarker.
