### ISSUE TITLE
Are we able to add classes to a mj-button? 

### ISSUE THREAD

**Issue by bradybunchxx** [mjmlio/mjml#1740]
I have been trying to build an email template that reduces the size of my button on smaller screens however when using css-class it does not work and I cannot find another way of making it responsive.

I would like to be able to add css-class on to any of the standard body components, is there a reason why it is restricted?

I have added my mjml code just incase anybody knows a fix for my issue, thanks in advance

`<mj-section background-url="https://contour.redeye.com/Image/fileLibrary/getImageByFileName/libraryType=Images&parentId=-205&fileName=191028_block1.jpg&_dc=191023135742" height="100%" padding-bottom="100%"  vertical-align="middle" background-size="100%"  background-repeat="no-repeat">
      
  
  
  <mj-column width="100%" vertical-align="middle">
        
        
        <mj-text css-class="font-size" align="center" color="#000"  letter-spacing="2px;">
          <span  style=" font-family: 'Montserrat'; line-height: 30px;">20% OFF EXCLUSIVE WALLPAPER</span>
        </mj-text>
        
        
        <mj-button css-class="testing" align="center" background-color="#041239" color="#fff" border-radius="0" font-size="16px" font-family="Montserrat" inner-padding="15px 40px" href="https://www.grahambrown.com/uk/wallpaper/g-and-b-exclusive-wallpaper/">SHOP NOW</mj-button>
      </mj-column>
  
</mj-section>`

**Comment by iRyusa** [comment]
css-class will always be applied at the top level of a component. So yes, it works even on button, just check the output  HTML to tweak the selector

<img width="1537" alt="Capture d’écran 2019-10-23 à 16 52 00" src="https://user-images.githubusercontent.com/570317/67405787-858ce580-f5b5-11e9-8037-5ad18dbf7767.png">
