### ISSUE TITLE
mj-style not working as expected

### ISSUE THREAD

**Issue by grant007** [mjmlio/mjml#1741]
**Describe the bug**
given a simple example, mj-style in conjunction with css-class is working as expected.

**To Reproduce**
1. Create a file with this MJML code using mjml.io email editor: 
```
<mjml>
  <mj-head>
     <mj-style>
      .orange div {
        color: orange;
        font-size: 50px;
        border-left: 5px solid orange;
        font-style: italic;
        padding-left: 10px;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text css-class="orange">
          Title
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

```
2. Render it to HTML by doing 'View HTML'

**Expected behavior**
The resultant text content 'Title' should be color=orange and the font-size=50px. 

Examination of the resultant HTML shows that default values for color, font-size, font-family, etc. are being applied to the style of the element therefore overriding the .orange class values.

I have tried both with and without inline="inline" on the mj-style.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - MJML Version: 4.3.0

**Comment by iRyusa** [comment]
Well you have to use `!important` everywhere because those style are already inline by MJML.

You can also use mj-attribute instead of mj-style to override default mj attributes on any element
