### ISSUE TITLE
Grouped Columns (stacked) are shown as a single row (side by side) in Ms Outlook 2010

### ISSUE THREAD

**Issue by iamtahirk** [mjmlio/mjml#1742]
I have two column layout where on one side I have an image and on the other side I have two columns (grouped layout) where I have an image with text side by side.

![T9AVeXM](https://user-images.githubusercontent.com/25350745/67623288-c64a6000-f83c-11e9-8b61-1109300d0b0e.png)

Mobile:
![image](https://user-images.githubusercontent.com/25350745/67623344-630cfd80-f83d-11e9-9b4a-cb3acc4532a2.png)

Here is the code for the section:
`<mj-section padding="10px 0 24px">
      <mj-column vertical-align="middle" width="325px">
        <mj-image width="325px" padding="16px 0" src="https://via.placeholder.com/325x250" />
      </mj-column>

      <mj-group vertical-align="middle" width="325px">
        <mj-column vertical-align="middle" padding="10px" width="21%">
          <mj-image padding="0" width="48px" src="aucun-risque-indemniflight@2x.jpg" />
        </mj-column>
        
        <mj-column vertical-align="middle" width="79%">
          <mj-text padding="0 5px 3px" font-size="15px" line-height="21px" align="left" color="#434652">
            <strong>Lorem Ipsum</strong>
          </mj-text>
          <mj-text padding="0 5px 5px" font-size="14px" line-height="21px" align="left" color="#434652">Lorem Ipsum dummy text</mj-text>
        </mj-column>

        <mj-column vertical-align="middle" padding="10px" width="21%">
          <mj-image padding="0" src="gain-de-temps-indemniflight@2x.png" />
        </mj-column>

        <mj-column vertical-align="middle" width="79%">
          <mj-text padding="0 5px 3px" font-size="15px" line-height="21px" align="left" color="#434652">
            <strong>Lorem Ipsum</strong>
          </mj-text>
          <mj-text padding="0 5px 5px" font-size="14px" line-height="21px" align="left" color="#434652">Lorem Ipsum dummy text</mj-text>
        </mj-column>

        <mj-column vertical-align="middle" padding="10px" width="21%">
          <mj-image padding="0" src="experience-indemniflight@2x.png" />
        </mj-column>

        <mj-column vertical-align="middle" width="79%">
          <mj-text padding="0 5px 3px" font-size="15px" line-height="21px" align="left" color="#434652">
            <strong>Lorem Ipsum</strong>
          </mj-text>
          <mj-text padding="0 5px 24px" font-size="14px" line-height="21px" align="left" color="#434652">Lorem Ipsum dummy text</mj-text>
        </mj-column>
      </mj-group>
    </mj-section>`

This appears as following in Ms Outlook:
![image](https://user-images.githubusercontent.com/25350745/67623312-10cbdc80-f83d-11e9-893e-5177ef377322.png)

Is there any solution for above?

**Comment by iRyusa** [comment]
You have more than 100% of content inside the section/group that’s why it behave like that.

**Comment by iRyusa** [comment]
You should use a mj table for that kind of layout instead it will be way easier to do

**Comment by iamtahirk** [comment]
I have set the body width to 650px. Also removed the padding from the whole section, but still the same.  

Can I use mj-columns within the mj-table row?

**Comment by iRyusa** [comment]
No just it’s just a standard html table here
