### ISSUE TITLE
Conditionals not working for JSON objects

### ISSUE THREAD

**Issue by zingix** [mjmlio/mjml#1743]
**Describe the bug**
When using a JSON object on the input varialbes, the properties can be accessed for rendering but not for comparision. The mechanism to determine the variable value is different for conditionals.
Please see the example below.

**To Reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-body>
      <mj-section>
        <mj-column width="100%">
          <mj-hero>
            <mj-raw>
           <h1>{{var:reseller.sapid}}</h1>
              </mj-raw>
          </mj-hero>
        <mj-raw>{% if var:reseller.sapid == '123' %}</mj-raw>
        <h1>Hello world</h1>
        <mj-raw>{% endif %}</mj-raw>
      </mj-column>  
      </mj-section>
  </mj-body>
</mjml>
```
2. Render it to HTML by using the mailjet online editor.
3. Provide the following data in export mode: 
```
{
  "Data": {},
  "Variables": {
    "reseller" : {
      	"sapid": "123",
    }
  }
}
```

**Expected behavior**
The string Hello World should be displayed. But instead, an error is thrown. You can see, that the first H1 tag is rendered correctly.

**MJML environment (please complete the following information):**
 - MJML in current Mailjet environement.

**Email sending environment(for rendering issues)**:
 - Just testing in online editor.

**Affected email clients (for rendering issues):**
 - No clients affected.

**Screenshots**
See attached screenshot.
![image](https://user-images.githubusercontent.com/11198434/67760979-a3899880-fa42-11e9-921d-e9d405f72359.png)

**Comment by iRyusa** [comment]
This is not related to MJML but to Mailjet templating language

So I'm closing
