### ISSUE TITLE
Draw a horizontal line

### ISSUE THREAD

**Issue by Gangotriv** [mjmlio/mjml#1746]
I want to draw a horizontal line in second column of the row. This line should be at same base of words like usually we use for doing signature.

I tried to use <mj-divider> tag. The code is below.

`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="30px">Hello world Hello!</mj-text>
      </mj-column>
      <mj-column>
        <mj-divider border-width="1px" border-style="solid" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

Please suggest the correct way to do.

**Comment by iRyusa** [comment]
HI,

Just put it in it's own section https://mjml.io/try-it-live/S1aGmxksS

**Comment by Gangotriv** [comment]
Actually I want something like 

<img width="238" alt="signatureLine" src="https://user-images.githubusercontent.com/42729190/68273718-39e63b80-008d-11ea-9012-01462e4375e5.PNG">
