### ISSUE TITLE
Can't use custom font except google font

### ISSUE THREAD

**Issue by sanazmemar** [mjmlio/mjml#1748]
I want to use a custom font in my MJML template. It's not a google font (for example, it's bentonSans family font). I try to use it in `<mj-font>` and use font-face on `<mj-style>`, but both of them didn't work! What should I do? Was it my bad? Or in the MJML, we can't use custom fonts?

Thank you.

**Comment by iRyusa** [comment]
Well mj-font let you import an external css file that declare font face to ensure that you won't have any issue on Outlook. 
Beware, most of client ignore custom fonts https://www.caniemail.com/search/?s=font-face
