### ISSUE TITLE
mj-include inside mj-include

### ISSUE THREAD

**Issue by vielhuber** [mjmlio/mjml#1749]
mjml does not parse another include in an included file.

Is this planned to be supported?

index.mjml
```
<mj-include path="1.mjml" />
```

1.mjml
```
<mj-include path="2.mjml" />
```

2.mjml
```
<mj-text>This is a header</mj-text>
```

**Comment by iRyusa** [comment]
This is already supported, how do you compile it ?

**Comment by vielhuber** [comment]
Sorry, my fault.

I added mj-include inside a mj-text, which is dump.

Works very well!
