### ISSUE TITLE
No README on npmjs.com

### ISSUE THREAD

**Issue by bbenoist** [mjmlio/mjml#1750]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2091902/68543873-27d20900-03bd-11ea-816d-1d2912302926.png)

**To Reproduce**

Go to https://www.npmjs.com/package/mjml

**Expected behavior**

I should see the README.md of the repository on the npm package page.

**Comment by iRyusa** [comment]
Hi, thanks for reporting this, it will be fixed in next release

**Comment by iRyusa** [comment]
It's good now ! Thanks for that 👍
