### ISSUE TITLE
Problem displaying emails on Outlook

### ISSUE THREAD

**Issue by Burry439** [mjmlio/mjml#1752]
Emails aren't being displayed correctly on Outlook

On desktop 
![on-desktop](https://user-images.githubusercontent.com/30046057/68766621-e1341700-0627-11ea-95fd-c8b79b2412e0.PNG)
 
On browser 
![on-browser](https://user-images.githubusercontent.com/30046057/68766665-f1e48d00-0627-11ea-8614-a145dd775ea4.PNG)

I've tried adding` <mjml></mjml>`  before the template as was suggested here https://github.com/mjmlio/mjml-app/issues/234
and adding  owa="desktop" as was suggested here https://github.com/mjmlio/mjml/issues/1333 
but they don't seem to be doing anything,
I tested these on putsmail.com, Using version 3.3.3 and version 4.5.1
Using try it live on

MJML code 
`<mjml version="3.3.3">
  
  <mj-head>
    <mj-style inline="inline">
      a {
        color: black;
      }
    </mj-style>
  </mj-head>
  
  
  <mj-body background-color="white" color="#55575d" font-family="Roboto, sans-serif">

    //HEADER WITH LOGO
    <mj-section background-color="white" background-repeat="repeat" padding="10px 0" text-align="center" vertical-align="top">
      <mj-column>
        <mj-image align="center" padding="20px" src="https://www.jumbomail.me/Content/img/logos/logo-grey.png" width="186px"></mj-image>
      </mj-column>
    </mj-section>

    //MAIN BODY INSIDE THE BORDER
    <mj-section background-color="#ffffff" background-repeat="repeat" padding="20px 40px" text-align="center" vertical-align="top" border="1px #eee solid">

      //group of email and donwload
      <mj-column width="100%">
        <mj-text align="center" font-size="20px" padding-bottom="5px">
          Viktor@jumbomail.me
        </mj-text>
        <mj-text align="center" font-size="16px" padding-top="0">
          Sent you some files via JUMBOmail
        </mj-text>
        <mj-text align="center">
          Please note, Eran Ronen requested payment for downloading the files
        </mj-text>
        <mj-text align="center" font-size="15px">
					<b>Total amount: 
         	100.00 ILS</b>
      	</mj-text>
        <mj-text align="center">
					Your payment will be transferred on your behalf to Eran Ronen via JUMBOPay
        </mj-text>
        <mj-button background-color="#15B4D4" color="white" border-radius="25px" height="50px" width="160px" font-size="15px" padding="30px">
          Get your files
        </mj-button>
      </mj-column>

      //two columns section
      <mj-group width="100%">
        <mj-column>
          <mj-text>
            1,544 files 487MB
          </mj-text>
        </mj-column>
        <mj-column>
          <mj-text>
            Will be deleted on 15 August 2019
          </mj-text>
        </mj-column>
      </mj-group>
      
      <mj-column width="100%">
        <mj-text>
          Download link: <a href="#" style="color: #15B4D4">https://www.jumbomail.me/j/rC82q0R3dk2DgXo</a>
        </mj-text>
      </mj-column>

      // mail info section
      <mj-column width="100%">
        <mj-divider border-width="1px" border-color="#eee" />
        <mj-text padding-bottom="0" padding-top="30px" font-size="15px">
          Images form the wedding
        </mj-text>
        <mj-text padding-bottom="30px" line-height="20px">
          	Hi,
            This is a demo content for the sent mail as it will appears in the recipient's email.
            More text here as much as needed
        </mj-text>
        <mj-text padding-bottom="0">
          <b>This JUMBOmail includes:</b>
        </mj-text>
        <mj-text padding-bottom="30px">
          123123.jpg, Test.pdf, asdasd.jpg +23
        </mj-text>
      </mj-column>
      
      <mj-column width="100%">
        <mj-text padding-bottom="30px" font-size="15px">
          Private signature of sender
        </mj-text>
      </mj-column>

    </mj-section>

    <mj-section background-color="#eeeeee" background-repeat="repeat" padding="0" text-align="center" vertical-align="top" border-radius="0 0 5px 5px">
      <mj-column padding="5px 0">
        <mj-text color="#444">
          Get more out of JUMBOmail, <a href="#" style="color:#444">GO PRO</a>
        </mj-text>
      </mj-column>
    </mj-section>

    //FOOTER INFO UNDER BORDER

    <mj-section background-color="#ffffff" background-repeat="repeat" vertical-align="top" text-align="left" padding="10px 0">
      <mj-column width="100%">
        <mj-text font-size="12px" padding="5px 0" color="#444">
          To make sure our emails arrive, please add <a href="#">no-reply@jumbomail.me</a> to your contacts.
        </mj-text>
      </mj-column>
      <mj-column width="100%">
        <mj-text font-size="12px" color="#444" padding="5px 0px">
          Please do not reply to this email. This message is an automated notification from JUMBOmail.
					<br>To unsubscribe from future notifications or to update your email preferences <a href="#">click here</a>
        </mj-text>
      </mj-column>
      <mj-group width="100%">
        <mj-column width="80%">
          <mj-text font-size="12px" color="#444">
            <a href="#"> www.jumbomail.me </a>
          </mj-text>
        </mj-column>
        <mj-column width="20%">
          <mj-text font-size="12px">
            <a href="#">Terms to use</a>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>

  </mj-body>
</mjml>`

**Comment by iRyusa** [comment]
Hi,

You have more than 100% of content inside a section, that's why
