### ISSUE TITLE
Background Image in Hero Doesn't Display in Outlook 365

### ISSUE THREAD

**Issue by AlyssaGodfrey** [mjmlio/mjml#1753]
**Describe the bug**
The background image in mj-hero doesn't display in Outlook 365,the fallback color does not display, and padding is ignored.

**To Reproduce**
1. Create fluid-height hero in MJML
2. Test by sending through Putsmail 
3. Open in Outlook 365

Here is the MJML used:

` <mj-hero mode="fluid-height"
      background-width="650px"
      background-height="700px"
      background-url="https://s3.amazonaws.com/production.campaign.talemetry/uploads/emails/images/15632/content_73069_Email_Update_4.jpg"
      background-color="#771b61"
      padding="460px 20px 0px 20px"
      >
    <mj-text><h1 style="font-family: catamaran, calibri light, calibri, helvetica, sans-serif;font-size: 64px; font-weight: bold;color:#0092b3;line-height: 68px;margin-bottom:5px;">UPMC Careers <span style="font-weight: 100;">News</span></h1>
    <p style="font-family: montserrat, calibri light, calibri, helvetica, sans-serif; font-size: 18px; color: #ffffff;margin-top:0px;font-weight: 100;">Your monthly update on featured jobs, events, and other happenings in home health at UPMC.</p></mj-text>
    </mj-hero>`

**Expected behavior**
Render like this:
![image](https://user-images.githubusercontent.com/33841093/68798724-e17ee300-0624-11ea-8fd3-71b348a256d6.png)

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Email sending environment(for rendering issues)**:
 - [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Outlook 365
 - Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/33841093/68798622-b8f6e900-0624-11ea-8e0a-289f6c5df520.png)

**Comment by iRyusa** [comment]
Can you try with a png background image to see if it does anything ?

**Comment by AlyssaGodfrey** [comment]
Hi iRyusa, thanks! I tried it with the new version and the image displayed, but the padding was still ignored. 

![image](https://user-images.githubusercontent.com/33841093/68803827-76d2a500-062e-11ea-9731-c938a3963a20.png)

I haven't tried the PNG yet but I'll give it a go.

**Comment by AlyssaGodfrey** [comment]
PNG was the same result

**Comment by iRyusa** [comment]
Padding left & right are applied twice to the right: it's a bug within outlook render engine. There's no real fix for that sadly. I'm closing this then

**Comment by AlyssaGodfrey** [comment]
Actually I've got a work-around. Take the right and left padding off mj-hero and add it to the text instead. But I would still consider that an issue with MJML that needs to be addressed, right?

**Comment by iRyusa** [comment]
That something we cannot fix with vml & nested table inside it. We did tried everything, even mso-alt-padding does behave the same.
