### ISSUE TITLE
Partial rendering

### ISSUE THREAD

**Issue by cdvv7788** [mjmlio/mjml#1754]
**Is your feature request related to a problem? Please describe.**
I want to compile my templates in 2 steps: mjml -> default framework engine -> final html
This is possible at the moment, but has a big caveat: I cannot use template hierarchy using my framework of choice.

**Describe the solution you'd like**
To fully support this, I need to be able to use rendering of subelements by themselves, without generating the whole email document, and doing so only in the presence of the top level tag `mjml`.
Another useful option (that I can't find in the docs) is to pass the `.mjml` directly to the cli, instead of a file. This could allow a more flexible implementation and ease of integration with my other template engines.

**Describe alternatives you've considered**
To have mjml available at runtime. However, templates are compiled at build time, so this complicates my setup and adds a runtime dependency on my system, which I would like to avoid.

I don't know if this all makes sense or if it is even possible with `mjml`, not familiar with the implementation.

**Comment by iRyusa** [comment]
Hi,

This is not really something we can provide, mj element are not simply transpiled into body element,: sometimes it adds some extra head css, sometime parent element allow children to inherit some attributes (like padding that doesn't work for mj-text if it's not used in a column).

And I think you should try the `-s` option on mjml cli, it will write the HTML to the stdout.
