### ISSUE TITLE
mj-raw issue with elements html of freemarker when minify html

### ISSUE THREAD

**Issue by jg2dev** [mjmlio/mjml#1756]
**Describe the bug**
Im doing a html template with powerful mjml and the cobination of the engine freemarker for fill the dynamic data. The problemas occur when i try to put a syntax element of condition (freemarker) if or whatever that has a ending of a html element dont mynify the html correctly.

**To Reproduce**

1. Create a file with this MJML code: 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">
        <mj-raw>
            <#if name??>
		${name}
	     </#if> <!-- This can't be minify -->
          </mj-raw>
        </mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

See error : MJML badly formatted

https://mjml.io/try-it-live/r1lq-T6ir

**Expected behavior**
Respect the content of <mj-raw> when mynify the html

**MJML environment (please complete the following information):**
 - CHrome
 - MJML Version  4.5.1
 - MJML tool used https://mjml.io/try-it-live

**Screenshots**
![image](https://user-images.githubusercontent.com/15870655/68997630-d2a86280-08a8-11ea-8002-6b7ffb2e26da.png)

Thx !!

**Comment by iRyusa** [comment]
Hi,

This is mentioned in `mj-raw` documentation  (https://mjml.io/documentation/#mjml-raw). You have to put those templating tag between 2 html comment : https://mjml.io/try-it-live/S17N9ygnB

Note that you don't need mj-raw in mj-text as it's already escaped.

**Comment by Frisch12** [comment]
This is broken again! Open your editor and you'll see that the closing tag will be converted to a html comment! 

Please fix this

**Comment by iRyusa** [comment]
![Screenshot 2023-09-28 at 10 48 31](https://github.com/mjmlio/mjml/assets/570317/4c4d162b-e2f1-4647-84a2-d5c4947e606d)
Can't reproduce ?

**Comment by Frisch12** [comment]
@iRyusa Opening your link from 4 years ago, you'll see the issue immediately: https://mjml.io/try-it-live/S17N9ygnB

**Comment by iRyusa** [comment]
Ok you're mixing what the browser does with the HTML and what MJML will output. MJML does not alter the `<#if name??>${name}</#if>` but the browser does when parsing it resulting to put this into HTML comment. 
There's no fix needed here as it will only happens when you're trying to preview the HTML with templating stuff not replaced yet.

**Comment by Frisch12** [comment]
@iRyusa If I'm using the NPM packages the same happens. Needed to adjust the juice options to ignore/preserve these tags. The commenting like `<!-- #if -->` is not a thing the browser did but juice.

**Comment by iRyusa** [comment]
If you're using mj-style inline style then you need to pass some options to juice in order to handle those xml-like tags properly.

**Comment by Frisch12** [comment]
I'm not using mj-style. 

Here is a example:
```
<mjml>
    <mj-body>
        <mj-text>
            Hello ${world}!
            <b>${s}</b>
            <br/>
            <#if v2??>
            ${v1}
            <#elseif sp??>
            ${v1}, ${sp}
            <#else>
            ${v1}

            </#if>
            <#if v2??>
            <#if sp??>
            ${v2}, ${sp}
            <#else>
            ${v1}
            </#if>
            </#if>
        </mj-text>
    </mj-body>
</mjml>
```
And the output contains all the closing `</#if>` as comments.

**Comment by iRyusa** [comment]
![Screenshot 2023-09-28 at 16 56 57](https://github.com/mjmlio/mjml/assets/570317/b3e68af8-eec6-45b6-975f-b4ff433cd685)
Everything is fine on my end
