### ISSUE TITLE
non-existing components in the documentation

### ISSUE THREAD

**Issue by davidsneighbour** [mjmlio/mjml#1759]
Go to https://mjml.io/components and try to check out the "Try It" link in `mjml-location` or `mjml-invoice`. It will load a default template because those components don't exist.

**Comment by iRyusa** [comment]
Yup those no longer exist in MJML4, we'll remove them

**Comment by ngarnier** [comment]
We should simply remove the whole page, it's not very useful (it's already removed from the menu).
