### ISSUE TITLE
mj-raw is rendered out of order inside mj-column

### ISSUE THREAD

**Issue by jamesabell** [mjmlio/mjml#1760]
mj-raw components are moved up to the top of mj-columns on render

Example:
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>First</mj-text>
        <mj-raw>
          <div style="font-size:50px">Second</div>
        </mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
Rendered:
![image](https://user-images.githubusercontent.com/29130459/69387710-a91a7d00-0c94-11ea-8776-50a69dd85460.png)

Version 4.5.1

**Comment by jamesabell** [comment]
I've solved this issue by using the mj-text component.  Leaving this open to see if this is a known issue.

**Comment by iRyusa** [comment]
This is the expected behavior, just check generated HTML. 

`mj-raw` just output right where you write it, so you have to check surrounding HTML elements to produce valid HTML.

**Comment by jamesabell** [comment]
@iRyusa  Maybe I'm not following.  What you you mean "right where you write it"?

If I have 
`        <mj-column>
          <mj-text>
            MJ-TEXT
          </mj-text>
          <mj-raw>
            MJ-RAW
          </mj-raw>
        </mj-column>`

Right were I write it is after mj-text.

But the render is before:
![image](https://user-images.githubusercontent.com/29130459/69389873-555f6200-0c9b-11ea-82f9-a20d8ba062af.png)

**Comment by iRyusa** [comment]
Take a look at generated html, not with the inspector. As browser detects invalid html (div in table) it will renders it before / after depending on browser.

**Comment by codeflorist** [comment]
> Take a look at generated html, not with the inspector. As browser detects invalid html (div in table) it will renders it before / after depending on browser.

A div inside a td is perfectly valid HTML.

Can `mj-raw` only be used outside `mj-section/mj-column` elements?

If yes, this would strongly limit the flexibility of mjml.

If not, then this markup:
```xml
<mj-column>
  <mj-text>First</mj-text>
  <mj-raw>
    <div>Second</div>
  </mj-raw>
</mj-column>
```
... should imho render this (innermost) HTML-structure:
```html
<table>
  <tr>
    <td>
        <div>First</div>
        <div>Second</div>
    </td>
  </tr>
</table>
```
Instead mjml renders this wrong HTML-structure:
```html
<table>
  <tr>
    <td>
        <div>First</div>
    </td>
  </tr>
  <div>Second</div>
</table>
```

**Comment by iRyusa** [comment]
I said in table not td.

That’s exactly how it’s suppose to behave as it mostly use for templating stuff.
 It only tell the transpiler to put exactly this string as is in the output html
