### ISSUE TITLE
mj-include not including files without .mjml in the config string

### ISSUE THREAD

**Issue by davidsneighbour** [mjmlio/mjml#1763]
**Describe the bug**

MJML documentation states, that the mj-include tag can contain in the path without the .mjml extension (in the code sample) at https://mjml.io/documentation/#mj-include

![Screenshot from 2019-11-19 20-27-54](https://user-images.githubusercontent.com/83281/69150353-1e5a4680-0b0b-11ea-8cbe-06303a7e094b.png)

Doing that in the app results in silently not showing the included part. 

**To Reproduce**

1. create a template with some code
2. create a second file named `footer.mjml` in the same directory
3. add `<mj-include path="./footer" />` to the first template

**Expected behavior**

`footer.mjml` exists but is not loaded. Changing the inlude path attribute to `./footer.mjml` loads the footer file. 

**Environment (please complete the following information):**

 - OS: Ubuntu 19.10
 - App Version mjml-app-2.12.0-linux-x64

**Additional context**

I am not sure if it's a bug in the app, or wrong documentation on behalf of the MJML team... please move this issue if needed.

**Comment by jzaefferer** [comment]
I can confirm this behaviour. Changing the `path` to include the extension fixes the issue, so an updated in the documentation would be good enough.
