### ISSUE TITLE
Separate borders on columns

### ISSUE THREAD

**Issue by KillianTaieb** [mjmlio/mjml#1770]
Hello ! Thanks for you help.

So, I have two columns and wish to put borders on them. The problem is they look like that and I can't manage to find a clean workaround to put a gutter between them.

![image](https://user-images.githubusercontent.com/14974184/70444306-f91d8000-1a99-11ea-9b77-5ace829eca31.png)

If I add another mj-column it's broken on mobile.

Is there a feature that prevents borders to be glued together ?

Thanks !

**Comment by iRyusa** [comment]
You should be able to target the inner table with padding on column https://mjml.io/try-it-live/HkH2I13pS

We need to do some tweak on that @kmcb777 with inner-background-color & inner-border 🤔

**Comment by KillianTaieb** [comment]
Clever solution, works like a charm, thanks !
