### ISSUE TITLE
Unable to do registerDependencies inside custom component

### ISSUE THREAD

**Issue by tume** [mjmlio/mjml#1771]
**Describe the bug**
Trying to follow https://medium.com/mjml-making-responsive-email-easy/tutorial-creating-your-own-component-with-mjml-4-1c0e84e97b36 and https://github.com/mjmlio/mjml-component-boilerplate where each custom component have their on registerDependencies call but trying myself it always complains `'mj-foobar cannot be used inside mj-column, only inside: mj-attributes'`.

**To Reproduce**
1. Follow tutorial and create simple custom component
2. Import & registerComponent
3. Try to render
4. Get error ''mj-foobar cannot be used inside mj-column, only inside: mj-attributes'

**Expected behavior**
Would expect mjml to registerDependencies in the custom component that I specidied.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.5.1
 - MJML tool used - 

**Additional context**
I can make it work by moving the registerDependencies call to file where I import my custom component but feels a bit wrong place for it.

**Comment by iRyusa** [comment]
Can you share your component code ?

**Comment by tume** [comment]
Work in progress repo: https://github.com/tume/mjml-i18n and actual component code: https://github.com/tume/mjml-i18n/blob/master/src/mjmlNumber.js

**Comment by iRyusa** [comment]
It should works just fine like that. Maybe the imported `mjml-core` version differs from the boilerplate, try to list mjml-core & mjml-validator as peerDep instead of dep.

As it works on the boilerplate https://github.com/mjmlio/mjml-component-boilerplate/blob/master/components/MjBasicComponent.js#L4 I suspect it's more likely an issue from your setup.

**Comment by tume** [comment]
Ah stupid me. Exactly that... thanks 👍
