### ISSUE TITLE
Getting API doesn't work

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#1772]
Hi everyone!
I went to https://mjml.io/api and tried to fill in form to get API keys. I tried twice and haven't received any emails.
Please, provide me API keys, as I want to add supporting your API service for `django-mjml` library (https://github.com/liminspace/django-mjml).
Thanks.

**Comment by ngarnier** [comment]
Just replied to the email you just sent me, let's keep it there. 

PS: you don't receive them because you've already created an account with this email back in 2017.
