### ISSUE TITLE
Cannot set background-color directly on mj-text inner element

### ISSUE THREAD

**Issue by jfcere** [mjmlio/mjml#1773]
### Bug Description

Using the `mj-text` component creates an inner `div` on which we cannot directly set style properties such as `background-color`.

The [documentation](https://mjml.io/documentation/#mjml-text) for `mj-text` points torward using `container-background-color` to apply background color on the _inner_ element. 

Unfortunately, using `container-background-color` only applies the background-color to the parent element (container), in occurrence the `td` element and not the inner `div` (see image below).

![image](https://user-images.githubusercontent.com/6987084/70531862-d637ae00-1b23-11ea-89cf-f547c7cd6c63.png)

Although the code example above renders correctly from a visual point of view, this will be flagged by SpamAssassin with `HTML_FONT_LOW_CONTRAST` and impact spam score (which will eventually lead emails to the _Junk Mail_ folder).

I found out from that [Stackoverflow answer](https://stackoverflow.com/a/50896705/5583283) that the `HTML_FONT_LOW_CONTRAST` requires that the element itself must have both `background-color` set with the `color` properties otherwise it will evaluate the font contrast using default `#ffffff` as background.

Note that using CSS selector such as `td > div` to apply background color on the inner element doesn't fix the `HTML_FONT_LOW_CONTRAST` issue, it must be applied by `style` attribute.

### Steps To Reproduce

Live example available here: https://mjml.io/try-it-live/Hy1HIGaaB

### Expected behavior

**Correct `container-background-color` documentation for `mj-text`**
Using `container-background-color` should continue to be used to add background color on the `div` parent created using `mj-text` component and documentation should be adjusted not to be missleading by saying `inner element background color` but instead `container element background color`.

**Add `inner-background-color` property on `mj-text`**
There should be another property such as `inner-background-color` to set the background color on the _real_ inner element to avoid `HTML_FONT_LOW_CONTRAST` to be raised by spam filters.

### MJML environment (please complete the following information):

 - OS: Windows 10
 - MJML Version: 4.5.1
 - MJML tool used: Live App + local environment

### Email sending environment(for rendering issues):

 - Smtp Server: Hosted Exchange
 - Spam filter: SpamAssassin

### Affected email clients (for rendering issues):

 - Email Client: All
 - OS: Windows 10
 - Browser: All

### Screenshots

See the screenshot in bug description.

### Additional context

I can't think of anything that hasn't been said yet.

**Comment by iRyusa** [comment]
Well this can be simply fixed with an inline style. ex: https://mjml.io/try-it-live/r1Z4X7p6B

Having multiple attribute for this with close name would be really confusing at this point. We never had any issue about deliverability with this behavior for years now.

And I'm not 100% sure that every client will behave the same on the `background-color` on div

**Comment by jfcere** [comment]
Hi @iRyusa,

Thanks for the quick response but unfortunately like I said in the bug ... this won't work for anti spam.

> Note that using CSS selector such as `td > div` to apply background color on the inner element doesn't fix the `HTML_FONT_LOW_CONTRAST` issue, it must be applied by `style` attribute.

**Comment by iRyusa** [comment]
Had a typo in previous snippet : https://mjml.io/try-it-live/B1-cImaar
inline="inline" will output everything in style attribute.

**Comment by jfcere** [comment]
Awesome, I wasn't aware of the `inline` property for `mj-style` ... I've tested it against the anti-spam and it works! 

Thanks a bunch, you saved my day 😄
