### ISSUE TITLE
Feature request: Avoid overwriting the input file via the -o option

### ISSUE THREAD

**Issue by AndrassGray** [mjmlio/mjml#1775]
Please help a fool to harm himself ;)

I launch mjml on the command-line and it happened for the second time: using file-completion without changing the extension, and I overwrote the mjml input file using the -o option. Obviously, this is my fault, but I would love to see this :

Check if the output-file is the same as (any of) the input-file(s). And abort if so.

**Comment by iRyusa** [comment]
Mhh I'm not sure about this one, this can lead to some weird stuff to do in the cli just for an edge case
