### ISSUE TITLE
[Arch Linux] mjml does not support relative path, what gave "Command line error: No input files found"

### ISSUE THREAD

**Issue by gusbemacbe** [mjmlio/mjml#1777]
**Describe the bug**

Before, I tried https://github.com/mjmlio/mjml/issues/1246, https://github.com/mjmlio/mjml/issues/1407, https://github.com/mjmlio/mjml/issues/1209, https://github.com/mjmlio/mjml/issues/885 and https://github.com/mjmlio/mjml/issues/1171, but no luck. 

I suspect that `mjml` does not support relative path. It works only with the absolute path.

**To Reproduce**
1. I have already created a file `index.mjml`;
2. I ran `mjml -r index.mjl`;
3. I received:

```
Command line error:
No input files found
```

**Expected behavior**

I tested to run `mjml -r /home/gusbeme/GitLab/go-to/templates/E-mails/index.mjml` and it worked. 

As mjml does not support relative path, MJML plugin on VSCode and other text editor does not work. 

**MJML environment (please complete the following information):**
 - OS: Arch Linux
 - MJML Version 4.5.1

```
$ which {electron,mjml,node,npm}
/home/gusbemacbe/node_modules/.bin/electron
/home/gusbemacbe/node_modules/.bin/mjml
/home/gusbemacbe/.nvm/versions/node/v12.10.0/bin/node
/home/gusbemacbe/.nvm/versions/node/v12.10.0/bin/npm

$ electron --version
v7.1.6

$ node --version
v12.10.0

$ npm --version
6.11.3

$ neofetch
                   -`
                  .o+`
                 `ooo/
                `+oooo:
               `+oooooo:
               -+oooooo+:
             `/:-:++oooo+:               
            `/++++/+++++++:              --------------------- 
           `/++++++++++++++:             OS: Arch Linux 
          `/+++ooooooooooooo/`           Kernel: 5.4.3-arch1-1 
         ./ooosssso++osssssso+`          Uptime: 6 hours, 13 mins 
        .oossssso-````/ossssss+`         Packages: 1410 (pacman), 19 (flatpak) 
       -osssssso.      :ssssssso.        Shell: zsh 5.7.1 
      :osssssss/        osssso+++.       Resolution: 2560x1080 
     /ossssssss/        +ssssooo/-       DE: Plasma 
   `/ossssso+/:-        -:/+osssso+-     WM: KWin 
  `+sso+:-`                 `.-/+oso:    WM Theme: Materia-Manjaro-Rounded 
 `++:.                           `-/+/   Theme: Breeze-Dark [GTK2/3] 
 .`                                 `/   Icons: breeze-dark [GTK2/3] 
                                         Terminal: tilix 
                                         CPU: AMD Ryzen 7 2700X (16) @ 3.700GHz 
                                         GPU: NVIDIA GeForce GTX 1660 
                                         Memory: 5157MiB / 16028MiB 

```

**Screenshots**

![image](https://user-images.githubusercontent.com/2257024/71067920-3fd34000-2154-11ea-9d75-b8affdbfab63.png)

![image](https://user-images.githubusercontent.com/2257024/71068298-326a8580-2155-11ea-9bf3-132f2ed89afc.png)

![image](https://user-images.githubusercontent.com/2257024/71068327-3e564780-2155-11ea-928c-b939dbc927e1.png)

**Comment by iRyusa** [comment]
Does `./index.mjml` works?

**Comment by gusbemacbe** [comment]
> Edit: in your screenshot templates are located in `templates/E-mails/index.mjml` and your cwd looks to be the root of `portallacrei`. Are you sure you're currently in the right directory ? As it works fine on OSX, it weird that it wouldn't work on another UNIX system

You are right. I have tested it and it worked. I took hours to fix the mjml's executable path to make VSCode's preview working. Sorry!

**Comment by iRyusa** [comment]
Totally unrelated but can you tell me what theme you're using on VScode ? I didn't find it ?

**Comment by gusbemacbe** [comment]
> Totally unrelated but can you tell me what theme you're using on VScode ? I didn't find it ?

```json
{
   "workbench.colorCustomizations": 
    {
        "activityBarBadge.background": "#C6FF00",
        "activityBar.border": "#C6FF00",
        "activityBar.foreground": "#A9B8BA",
        "breadcrumb.activeSelectionForeground": "#C6FF00",
        "editorSuggestWidget.highlightForeground": "#C6FF00",
        "editorWidget.border": "#C6FF00",
        "editorWidget.resizeBorder": "#C6FF00",
        "list.activeSelectionForeground": "#C6FF00",
        "list.highlightForeground": "#C6FF00",
        "list.inactiveSelectionForeground": "#C6FF00",
        "menu.selectionForeground": "#C6FF00",
        "menubar.selectionForeground": "#C6FF00",
        "notificationLink.foreground": "#C6FF00",
        "panelTitle.activeBorder": "#C6FF00",
        "pickerGroup.foreground": "#C6FF00",
        "progressBar.background": "#C6FF00",
        "scrollbarSlider.activeBackground": "#C6FF0050",
        "scrollbarSlider.background": "#C6FF00",
        "scrollbarSlider.hoverBackground": "#C6FF0050",
        "settings.headerForeground": "#C6FF00",
        "settings.modifiedItemForeground": "#C6FF00",
        "settings.modifiedItemIndicator": "#C6FF00",
        "tab.activeBorder": "#C6FF00",
        "textLink.foreground": "#C6FF00"
    },
    "workbench.colorTheme": "Material Theme Darker",
    "workbench.iconTheme": "material-icon-theme"
}
```

**Comment by iRyusa** [comment]
👍 thanks you
