### ISSUE TITLE
mj-column doesn't work on Comcast (web), GMX (web) & Telstra/Bigpond (web)

### ISSUE THREAD

**Issue by maxjonas13** [mjmlio/mjml#1778]
**Describe the bug**
Comcast (web), GMX (web) & Telstra/Bigpond (web) don't render mj-column correctly. instead they stack it.

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`

`<mj-section background-color="{{ color }}" padding="0" direction="rtl">
    <mj-column>
        <mj-image src="{{ imagePath }}/{{ img.file }}" href="{{ block.uri }}" alt="{{ block.img.alt }}" padding="0" fluid-on-mobile="true" />
    </mj-column>
    <mj-column padding="0 0 15px 0" vertical-align="top">
        <mj-text font-size="17px" font-weight="600" line-height="22px" color="#000" padding="15px">
            {{ block.title | safe }}
        </mj-text>
        <mj-text font-size="14px" line-height="22px" color="#000" padding="15px">
         {{ block.texts | safe }}
        </mj-text>
    </mj-column>
</mj-section>`

2. Render it to HTML
3. Send the HTML to an email address with '...'
We tested it in https://www.emailonacid.com/

Render Error:
![render-error](https://user-images.githubusercontent.com/8791380/71103308-2fee4700-21ba-11ea-8938-389f929110f2.png)

**Expected behavior**
Render expected behaviour:
![render-expected](https://user-images.githubusercontent.com/8791380/71103311-2fee4700-21ba-11ea-8503-cfc9ec23b03d.png)

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS] : macOS Catalina v 10.15.1
 - MJML Version [e.g. 4.2.0]: mjml@4.3.1

**Email sending environment(for rendering issues)**:
Tested in: https://www.emailonacid.com/
Sent from: Acoustic https://www.ibm.com/customer-engagement/marketing/launch/
&
Rendered code pasted from build.
Both gave same results.

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] : Comcast (web), GMX (web) & Telstra/Bigpond (web)
 - OS: [e.g. Windows] : macOS Catalina v 10.15.1 & windows 7
 - Browser [e.g. Google Chrome] : ie11, chrome, firefox

**Screenshots**
(see renders above.)

**Additional context**
We tried to find out what is wrong. We found out that the system creates a style tag:
`<style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
.mj-column-per-50 { width:50% !important; max-width: 50%; }
.mj-column-per-32 { width:32% !important; max-width: 32%; }
.mj-column-per-2 { width:2% !important; max-width: 2%; }
.mj-column-per-49 { width:49% !important; max-width: 49%; }
.mj-column-per-37 { width:37% !important; max-width: 37%; }
.mj-column-per-63 { width:63% !important; max-width: 63%; }
.mj-column-per-33 { width:33.333333333333336% !important; max-width: 33.333333333333336%; }
      }
    </style>`
This is ignored in Comcast (web), GMX (web) & Telstra/Bigpond (web)

**Comment by iRyusa** [comment]
Mjml is mobile first so if a mail client doesn’t support media queries, it will fallback to mobile version.

**Comment by mikeveeckmans** [comment]
Thanks @iRyusa for the feedback. 
Although i do understand the fallback, is there a workaround you can suggest for this specific mail clients?

**Comment by ngarnier** [comment]
The issue is not with MJML or those clients, you can see in this test it's working fine on all 3 clients you mentioned: https://app.emailonacid.com/app/acidtest/8zceYrJEUjDWHCceB5UWzn2HQAOqCofEvsNN6D2uQbuAe/list. 

The issue is either with your code (it's hard to tell as you didn't provide the whole code to reproduce), or your method of sending (IBM Acoustic).

**Comment by maxjonas13** [comment]
@iRyusa agreed. this should be the case when media queries aren't supported.
But should the content not also grow with the column?
I made it so the image is always 100% the width of the column. 
But the generated width on the image, td and table Is half the width of the mail itself. This width is generated by the parent column.
When the column doesn't work and the fallback is shown, doesn't that mean that the column with a width of 50% should become one of 100%?

In my generated code I have this in my head:

```
<style type="text/css">
    @media only screen and (max-width:480px) {
      table.full-width-mobile { width: 100% !important; }
      td.full-width-mobile { width: auto !important; }
    }  
</style> 
```

It is also present as a class on the column.
So a media query for mobile, that isn't supported on a mail client, isn't used in a framework that works with mobile first? Shouldn't this "full width" be present by default and overwritten by a media query on desktop?

Just to be sure.

**Comment by iRyusa** [comment]
Column expand to 100% width and content too, but image "full width" is handled by a media query as you pointed out so it won't work if there's no MQ supported too.
Images are a special case because width are defined in px, not in % (mostly to ensure outlook doesn't explode on large image).

> Shouldn't this "full width" be present by default and overwritten by a media query on desktop?

We've tried, and everytime Outlook desktop just break the layout. This is far from the best solution, but in common cases it works fine.

**Comment by maxjonas13** [comment]
@iRyusa Ok, thank you for the feedback!
