### ISSUE TITLE
Hero Background Image missing all versions outlook PC

### ISSUE THREAD

**Issue by 2dareis2do** [mjmlio/mjml#1779]
Outlook tests PC all versions - background-position/size feature on the hero that does not seem to be available on the section.

I like the background-position/size feature on the hero that does not seem to be available on the section.

AFAICT the hero is missing the VML mark-up on background issues that is responsible for rendering the background image in outlook.

https://litmus.com/community/discussions/6766-background-image-not-loading-in-outlook-2013

However elements that can be placed in a hero seem to be somewhat limited? It seems to me that the features of the section and the hero seem to overlap here. If we could implement the background position features on the section it would probably make the hero redundant, although maybe I am missing something here? 

Also with regards the hero if you omit the width or set it to 0 it will try generate markup that include NaN and infinite as css parameters, so it would seem a little buggy as well.

I am disappointed that when using the hero the images do not render in the background in outlook. Given the widespread use of Outlook on Windows It would therefore appear to be unfinished and I do not know why this forms part of MJML if it is not recommended to use?

**Comment by iRyusa** [comment]
> Outlook tests PC all versions - background-position/size feature on the hero that does not seem to be available on the section.

Well this is a bit more complex we're not using the same "technique" of VML for hero & section, both have some limitation.

> AFAICT the hero is missing the VML mark-up on background issues that is responsible for rendering the background image in outlook.

? Mj hero does actually use VML and v:image with an absolute position to renders. 

> Also with regards the hero if you omit the width or set it to 0 it will try generate markup that include NaN and infinite as css parameters, so it would seem a little buggy as well.

I'm not  sure about this one ? width is inherited by mj body so omitting it should be 600px by default ? Do you have a mjml to reproduce here ?

Well mj-hero started as an "experimental" component at the beginning where we tried to be as close as what you can find on some website.

**Comment by 2dareis2do** [comment]
Mark up is very similar to this.

`    <mj-hero mode="fluid-height" background-height="0" background-width="600px" background-url="https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/79938caf-f474-4bb5-95c1-a4abb2cad80c2.jpg" background-color="#ffffff" padding="1px 1px">
      <mj-image src="https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/09b1e98f-36e8-4fb5-93ff-902c4cdcfa3c.png" align="left" width="80px" padding-right="0px" padding-bottom="0px" />
      <mj-text color="#000" font-family="Roboto, Helvetica" align="center" font-size="45px" line-height="45px" font-weight="900" padding="70px 0px">
        Backing <span style="color:#31BCF2;font-family:Satisfy,Times New Roman,Times,Serif;font-style:italic">ambition</span>
      </mj-text>
    </mj-hero>`

**Comment by iRyusa** [comment]
Well I can't access to any image you've provided: https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/09b1e98f-36e8-4fb5-93ff-902c4cdcfa3c2.png give me an 403 forbidden so this is most likely why you don't see any image on outlook.

**Comment by 2dareis2do** [comment]
take the 2 off

**Comment by 2dareis2do** [comment]
the last one

**Comment by 2dareis2do** [comment]
Ok, maybe my tests are coming back false negative. I guess the image might just be taking too long. So as far as you can see there is no reason why this shouldn't work in Outlook email client on Windows only. Ok I will try optimising the image and see if that helps with the test. 

As per usual it appears I am jumping to conclusions. Thank you for your support. I will let you know how I get on with the tests.

**Comment by 2dareis2do** [comment]
Here is the NaN issue I was referring too.

`    <mj-hero mode="fluid-height" background-width="0"  background-width="0" background-url="https://cloud.githubusercontent.com/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg" background-color="#ffffff" padding="0">
      <mj-image src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fa%2Fa0%2FAcme-auto_1906_logo.jpg&f=1&nofb=1" align="left" width="80px" padding-right="0px" padding-bottom="0px" />
      <mj-text color="#000" font-family="Roboto, Helvetica" align="center" font-size="45px" line-height="45px" font-weight="900" padding="100px 0px">
        Tracking <span style="color:#31BCF2;font-family:Satisfy,Times New Roman,Times,Serif;font-style:italic">internet</span>
      </mj-text>
    </mj-hero>`

**Comment by iRyusa** [comment]
background width 0 will lead to a division by 0 so yeah the NaN is quite expected here.

**Comment by 2dareis2do** [comment]
0 / 0 is 1 I think

**Comment by iRyusa** [comment]
https://en.wikipedia.org/wiki/Division_by_zero well it's not 1, and it doesn't really have anything to do with JS

**Comment by 2dareis2do** [comment]
Any number divided by it self is 1

**Comment by iRyusa** [comment]
Nope, sorry that's not how it works, read a bit about wikipedia. You just can't divide by 0 that's a math fact

**Comment by 2dareis2do** [comment]
Ok I tried optimising the image and unfortunately I am getting fairly consistent results against all versions of outlook running on a PC. As I mentioned before this could be something with the test suite set up and the amount of time it takes for an image to load but it does seem strange. I have done teh same with the background image on the section and these seem to work fine.

Here is screenshot 

https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/7f685443-a0fc-41a5-88b9-7c4e09627138.png

Will have a look

**Comment by 2dareis2do** [comment]
Looks like 0/0 is either undefined, indeterminate or possibly 1. No one can agree and certainly 

1 * 0 = 0 so it also follows that 1 = 0/0

which seems odd as 1/infinitely small number approaching 0 is a number approaching infinity.

Either way we will probably never know what 0/0 or any number divided by 0 actually is.

**Comment by iRyusa** [comment]
> Looks like 0/0 is either undefined, indeterminate or possibly 1. No one can agree and certainly
> 1 * 0 = 0 so it also follows that 1 = 0/0

Please stop ... It's proven https://en.wikipedia.org/wiki/Division_by_zero#Fallacies and it's common sense that dividing by zero isn't a thing.

If you use `fluid-height` do not set `background-height` or `background-width` to 0 but to the actual background size to ensure that it will render fine.

**Comment by 2dareis2do** [comment]
OK I have had a chance to diagnose this problem. In ie/outlook background image is not supported on the table element so it turns out that it renders the style tag on the table element instead. However it does not seem to be able to handle both colour and background image.

My mark up is as follows:

`    <mj-section background-url="https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/ef5e163f-c5ea-4b28-be58-b926b0c0984e.jpg" background-color="#ffffff" padding="1px 1px" background-repeat="no-repeat">`


This ends up rendering something quite complicated like this:

  ```
   <!--[if mso | IE]>
      <table
         align="center" border="0" cellpadding="0" cellspacing="0" class="" style="width:600px;" width="600"
      >
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
      
        <v:rect  style="width:600px;" xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false">
        <v:fill  origin="0.5, 0" position="0.5, 0" src="https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/ef5e163f-c5ea-4b28-be58-b926b0c0984e.jpg" color="#ffffff" type="tile" />
        <v:textbox style="mso-fit-shape-to-text:true" inset="0,0,0,0">
      <![endif]-->
    <div style="background:#ffffff url(https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/ef5e163f-c5ea-4b28-be58-b926b0c0984e.jpg) top center / auto no-repeat;margin:0px auto;max-width:600px;">
      <div style="line-height:0;font-size:0;">
        <table align="center" background="https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/ef5e163f-c5ea-4b28-be58-b926b0c0984e.jpg" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff url(https://gallery.mailchimp.com/a27ecf3dbe7fdfb3670b945c4/images/ef5e163f-c5ea-4b28-be58-b926b0c0984e.jpg) top center / auto no-repeat;width:100%;">
          <tbody>
            <tr>
```

So AFACT in all versions of Oulook on PC the the background colour seems to take precedence. Therefore it would seem that this does not support both background image and colour.
