### ISSUE TITLE
100% Full Width image

### ISSUE THREAD

**Issue by willryanuk** [mjmlio/mjml#1782]
I've been reading the documentation, the issues on Github, and trying a whole heap of things with the different components, but it seems i can't have a full width image in an email. I want it to break outside the bounds of the body, and go from edge to edge of the email viewport (remaining full width if the viewport were resized).

I ended up doing, the following, but I think this might break in some email clients:

```
<mj-raw>
            <table cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td>
                        <img width="700" alt="" src="images/leading-newsletter-image.jpg" style="display:block; width:100%" />
                    </td>
                </tr>
            </table>
        </mj-raw>
```

Would there be a possibility of having a component that did this, with graceful degradation for Outlook, if this is what won't support it?

**Comment by iRyusa** [comment]
Well it's far from perfect but i would suggest to go that way https://mjml.io/try-it-live/SJeOljqCr

You wont have a full width image but you can make it larger than the container.

Another way to do so is having a background image and a full-width section.

**Comment by willryanuk** [comment]
The example you sent isn't edge to edge though... from what i can see, it is just the width of the section, which is set at 700px... 

I want an image at the top of the email which goes from edge to edge (e.g. if the email viewport was 1000px width, the image would be 1000px). Is that possible or no?

**Comment by iRyusa** [comment]
The text would still be in the container but the you should use a full width section with background image as mentioned.

**Comment by willryanuk** [comment]
@iRyusa but with the full width section and background image, it seems I must set an explicit height for the section, whereis in reality, I want the image to resize with the width of the email client. e.g. I want the entirety of the image to show.

But perhaps this simply isn't possible?

**Comment by iRyusa** [comment]
Well in email world, you're very limited in what you can do. So yes, what you want to do is just not possible

**Comment by willryanuk** [comment]
@iRyusa thanks very much for your patience helping me out with this. I thought that might be the case. Merry Christmas :)
