### ISSUE TITLE
Button href and images

### ISSUE THREAD

**Issue by oron11** [mjmlio/mjml#1784]
Hello,
I just started to use `mjml`  (Latest version), and I'll be happy to get any help in the following matters:

- I'm adding button with href in it like below:
  `<mj-button background-color="#Fbfbfb" color="black" href="https://...">Learn more</mj- 
  button>`

  And somehow the href is found in the attachments (I'm using Gmail).
  Can it be removed from the attachments?

-  I cannot add images with local source. 
   Is It possible? Or the only choice is to provide a URL?

Thank you!

**Comment by iRyusa** [comment]
> And somehow the href is found in the attachments (I'm using Gmail).
 Not really sure about this one, can you provide a screenshot ?

>I cannot add images with local source.
> Is It possible? Or the only choice is to provide a URL?

Well local image will works only locally, it's not really related to MJML here.

**Comment by oron11** [comment]
> > And somehow the href is found in the attachments (I'm using Gmail).
> > Not really sure about this one, can you provide a screenshot ?
> 
> > I cannot add images with local source.
> > Is It possible? Or the only choice is to provide a URL?
> 
> Well local image will works only locally, it's not really related to MJML here.

I used CLT but it appears also in the attachments

**Comment by iRyusa** [comment]
You mean CID ?

**Comment by oron11** [comment]
Yes CID

**Comment by iRyusa** [comment]
Then it’s normal there’s no way to prevent that
