### ISSUE TITLE
outlook 16 | 19 - unwanted gaps between tables

### ISSUE THREAD

**Issue by am-34000** [mjmlio/mjml#1787]
Hi, 
i found a problem on Outlook 16 windows 7/10 & Outlook 19 windows 10. On each main tables,  a gap displays. It works well on other platform.

How can i fix it ?

 - MJML tool used : Email editor on Mailjet website

 - Platform used to test the email: EOA

**Screenshots**

<img width="614" alt="test" src="https://user-images.githubusercontent.com/59564781/71819034-0030b180-308b-11ea-8445-017fde5bf4ee.png">

Thanks,

**Comment by iRyusa** [comment]
This is a known issue in Outlook and no one really found out why & how to fix it.

Some reading about this : https://mosaico.io/email-client-tricks/outlook-2016-weird-1px-horizontal-lines/
https://litmus.com/community/discussions/4990-outlook-2016-1px-horizontal-lines-showing-up-in-the-body
https://litmus.com/community/discussions/5286-mysterious-white-line-in-outlook

**Comment by am-34000** [comment]
Thanks for your reply and links.

@iRyusa, @MJML Team, have you got some feedback about this problem and fix ? I can read many "fix" on Litmus... 

I tested an old template (Template built with Email editor MJML), this old template works well. 
The 1px line does not appear.

**Comment by mjml** [comment]
Hello, I am not actually involved with this project but have a similar name so please try to avoid tagging me with @mjml instead of @mjmlio. Thanks!

**Comment by iRyusa** [comment]
@am-34000 there's multiple "fix" that works sometimes but it's not magic. You can try to change  line-height/font-size/width/ adding/removing some content/ adding a `br`/ `&nbsp;`. But there's no silverbullet for this.
