### ISSUE TITLE
Using padding in <tr> show different results in browser/program/outlook

### ISSUE THREAD

**Issue by qarmin** [mjmlio/mjml#1789]
**Describe the bug**
Sometimes when i use in <tr> padding and background-color, then table will broke(look at screenshoots)

**To Reproduce**
1. Create a file with MJML code from bottom of page
2. Render it to HTML with web or desktop app
3. Send the HTML from Thunderbird to an Outlook account

**Expected behavior**
Email in Outlook should look like in preview in app or browser

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.4.1
 - MJML tool used  MJML App - 2.12

**Email sending environment(for rendering issues)**:
 - Thunderbird 68.3.1
 - OS: Windows 

**Affected email clients (for rendering issues):**
 - Email Client Outlook 2016
 - OS: Windows

**Screenshots**
In mjlm app
![Q1](https://user-images.githubusercontent.com/41945903/71899208-80bee300-315b-11ea-885f-e4578592ac5f.png)
In web 
![Q2](https://user-images.githubusercontent.com/41945903/71899354-cc718c80-315b-11ea-9d56-b9ff205cf2ab.png)
And broken table in Outlook 2016
![Q3](https://user-images.githubusercontent.com/41945903/71899376-d98e7b80-315b-11ea-81a1-73dff97f4697.png)

**Additional context**
Code
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-table>
          <tr style="background-color:#f7f7f7;">
            <td> SSSSSSSSSSSSSSSSSSSSSSSSS </td>
            <td> <img align="right" width="140" src="https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Sterling_Warriors_Logo.png/180px-Sterling_Warriors_Logo.png" /> </td>
            <td style="padding:25 25 25 25;color:white;background-color:#c90000;width:20%;min-width:90px;line-height:1.2;">
            SSSSSSSSSSSSSSSSSSSSSSSSSSFASFASFASFASFFFASFASF </td>
            <td style="padding:0 5 0 5;color:white;background-color:#c90000;min-width:101px"> GASFSAFASFASFSAFSAFSAFSAFSAFFSFSFAFSSAFASFsafSAF </td>
          </tr>
        </mj-table>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
> Send the HTML from Thunderbird to an Outlook account
Just use putsmail.com instead for test email, as thunderbird alter the html.

Some properties like min-width doesn't work in outlook, and you need to set the unit on your padding.
