### ISSUE TITLE
Request: Allow `width` parameter on `mj-button`

### ISSUE THREAD

**Issue by markbloomfield** [mjmlio/mjml#179]
Scenario:

![buttons](https://cloud.githubusercontent.com/assets/936966/14275877/0f7710ca-fb1b-11e5-9a0f-676d16c455a0.jpg)

Can't duplicate this layout with padding only... Would be great to be able to set a width on buttons?

**Comment by ugogo** [comment]
+1

**Comment by groomain** [comment]
+1 

Also needed to make full width buttons

**Comment by iRyusa** [comment]
Any idea on how `width` will be applied on older outlook ?

**Comment by Tlapi** [comment]
Seems ok for me.

Full width button 100%:
https://www.emailonacid.com/app/acidtest/display/summary/CuQfi4QnwaQvvkZLO3zcar7uvSaLLMXiPtHkthdRj1YgR/shared

Width set to 300px:
https://www.emailonacid.com/app/acidtest/display/summary/FREgjX72eUVf69xg8d8Tl4ZQ29uvTN4i1A2qx7BXnS5jN/shared

But there are some problems with outlook.com, or is this Email on acid bug?

**Comment by iRyusa** [comment]
Hello, that's look good ! 

Did you set a valid `href` on your `mj-button` ? That can break outlook.com if not set properly

**Comment by Tlapi** [comment]
Ah ok, no i did not, i will and test again.

**Comment by Tlapi** [comment]
Working good: https://www.emailonacid.com/app/acidtest/display/summary/fBHd1TuKNW4s06biz1SR5BtH1QXUXKUTUM4bbF8aHgcYI/shared

Just an alignment issue in Yahoo. But full-width button is without any problems.

**Comment by iRyusa** [comment]
Looks good to me !
We have "center" issue on Yahoo see #231

**Comment by iRyusa** [comment]
Hi @Tlapi did you only add width on table to achieve this result ? Because when I add it on the table it doesn't work :/

**Comment by iRyusa** [comment]
Hi there !

`Width` is now available in MJML3 !
