### ISSUE TITLE
create list 

### ISSUE THREAD

**Issue by sanazmemar** [mjmlio/mjml#1792]
I need create a list on my template, So I used below code! It works but I need change `list-style-type` of that and it doesn't work on it. How can I create a list after `mj-list` deprecated?

```
<mj-text>
    <ul>
         <li>
             Element #1
          </li>
          <li>
             Element #2
          </li>
     </ul>
 </mj-text>
```

**Comment by iRyusa** [comment]
You can just use inline style for that or class + mj-style. ul/ol can misbehave in outlook so you should avoid it if you can.
