### ISSUE TITLE
Issue with Outlook 2019 and direction="ltr"

### ISSUE THREAD

**Issue by nvassos** [mjmlio/mjml#1793]
Hey guys, I have made this on MJML

https://pastebin.com/EubbtFaE

It's meant to be a signature and it works fine everywhere, and outlook 2019 supports full html signatures, however, for some reason, the entire signature's text, goes right align, and I think it has to do with rtl. Has anyone experienced that before? Or have some input on what I could be doing differently?

**Comment by nvassos** [comment]
Apparently it's a known issue, where you have to use ltr on the inside tables, is that something that can be fixed on MJML?

https://litmus.com/community/discussions/5568-dir-rtl-in-table-causes-problems-with-text

**Comment by iRyusa** [comment]
As suggested surrounding your mj text with direction ltr should fix it don't know if it's really something we have to do on mjml side here 🤔 ( multiple choice here, adding a css class might do the trick)

This attribute could be used legitimately to have text goes rtl.

**Comment by nvassos** [comment]
css class would work, but I am not able to add direction on the mj-text doesn't seem to allow me.

**Comment by iRyusa** [comment]
Yes it's not in the supported list of attributes :) just a  `.ltr { direction: ltr; }`  class & inline it and you should be fine ?

**Comment by nvassos** [comment]
Adding it now, thank you.

**Comment by nvassos** [comment]
<mj-style>
      .ltr {
        direction: ltr; 
      }
    </mj-style>
    <mj-style inline="inline">
      .ltr {
        direction: ltr; 
      }
    </mj-style>

this should be fine?

**Comment by iRyusa** [comment]
the last one is enough then `mj-text css-class="ltr"`

**Comment by nvassos** [comment]
Okay. thank you
