### ISSUE TITLE
CSS background-color on <mj-section> without full-width property does not work in Outlook

### ISSUE THREAD

**Issue by krikienoid** [mjmlio/mjml#1796]
When using CSS to apply a `background-color` to an `<mj-section>` or `<mj-wrapper>` element, and the element does not have the `full-width` property set, the background color does not display in Windows Outlook.

The problem does not occur when a `background-color` property is added directly to an MJML element. The problem also does not occur on MJML elements that have `full-width` set.

**To Reproduce**
Below is an MJML email code snippet which will reproduce the issue. The first `<mj-section>` in the example does not display correctly in Outlook.

```html
<mjml lang="en">
  <mj-head>
    <mj-title>
      Test emails
    </mj-title>

    <mj-style>
      .bg-blue {
        background-color: blue;
      }
    </mj-style>
  </mj-head>

  <mj-body>
    <mj-section css-class="bg-blue" padding="20px">
      <mj-column>
        <mj-text>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.</p>
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section css-class="bg-blue" padding="20px" full-width="full-width">
      <mj-column>
        <mj-text>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.</p>
        </mj-text>
      </mj-column>
    </mj-section>

    <mj-section padding="20px" background-color="green">
      <mj-column>
        <mj-text>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.</p>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
Expected behavior is that the first two sections will have a blue background and the third section will have a green background. In Outlook, the first section does not display a background color.

**MJML environment:**
 - OS: MacOS 10.14.5
 - MJML Version: 4.3.1

**Affected email clients (for rendering issues):**
 - Email Client: Microsoft Outlook, all versions
 - OS: Windows

**Screenshots**
How it looks in everything but Windows Microsoft Outlook
![Screen Shot 2020-01-14 at 12 44 08 PM](https://user-images.githubusercontent.com/8528227/72368204-97b98400-36cb-11ea-9f2e-1a62dad5b098.png)

How it looks in Windows Microsoft Outlook
![Screen Shot 2020-01-14 at 12 32 06 PM](https://user-images.githubusercontent.com/8528227/72368205-97b98400-36cb-11ea-9b6f-6d4c99eb0dc9.png)

**Comment by iRyusa** [comment]
Just use the given mj attribute instead of CSS? In your example you’re using a class rather than the background-color attribute on mj section

**Comment by krikienoid** [comment]
Yes that is what I am doing now. I didn't see anything in the documentation to indicate why the CSS class should not work. Seems weird to me that it works fine if `full-width` is set but breaks if it is not.

**Comment by iRyusa** [comment]
Well we can’t really document every hack we use in mjml. Full width section might start with a table, and non full width start with a div so that should be why

**Comment by krikienoid** [comment]
I am okay with not using CSS classes in this instance. I still feel it's worth bringing up though since this behavior was so unexpected.

**Comment by iRyusa** [comment]
Well that's a too wide subject here. It would be hard to provide documentation for every component, every clients & every css attributes. Let's just say that it is safer to use mj-attributes than custom css as a generality here :)
