### ISSUE TITLE
Incorrectly placed background-color on mj-column when using border with padding

### ISSUE THREAD

**Issue by CodeSkills** [mjmlio/mjml#1797]
**Describe the bug**
When using the `mj-column` with border type other than solid, like `dashed` or `dotted`, together with padding and background-color, the renderer places the styles incorrectly.

**To Reproduce**
1. Insert this MJML to Try live editor
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column border="10px dashed #000000" background-color="red" padding="0">

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
Preview:
![image](https://user-images.githubusercontent.com/3975293/72438139-81cbc200-37a4-11ea-8a0c-090d9c65e925.png)

**Expected behavior**
When you insert the same but without `padding` attribute, it works correctly:
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column border="10px dashed #000000" background-color="red">

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
(the background color is placed correctly now, but the dashed border seems also bugged, but thats another issue I guess)

![image](https://user-images.githubusercontent.com/3975293/72438440-1d5d3280-37a5-11ea-997f-975bf2188532.png)

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version Latest
 - MJML tool used Local and Try it live editor

**Affected email clients (for rendering issues):**
 - Browser Google Chrome (tested in chrome but it will show the same everywhere)

**Comment by iRyusa** [comment]
Both of the issue are related to `border-collapse` property that make sure there's no gap between table in Outlook. You can just override it locally with a css class.
