### ISSUE TITLE
Add social text tag only when necessary

### ISSUE THREAD

**Issue by aurmil** [mjmlio/mjml#180]
hello,

when using the social component, I wanted to display only icon, without any text so I set xyz-content=""
as expected, there's no text displayed but the td>a tags still exist in HTML code, with a padding-right so this element has a width

these tags should be added only if text is not empty

**Comment by g0ddish** [comment]
Have you tried with text-mode = false?
Example:
https://mjml.io/try-it-live/b665980d71b571adeace00e283ded09e

**Comment by aurmil** [comment]
exactly what I needed so I think documentation should be improved on this particular point as it is written:

attribute | unit | description | default value
---------- | ----- | -------------- | -----------------
text-mode | string | vertical/horizontal | true

I didn't understand why true was the default value if authorized values were vertical and horizontal
now I get it...
thanks
