### ISSUE TITLE
(mj-hero) — Attribute width is illegal

### ISSUE THREAD

**Issue by chrislow** [mjmlio/mjml#1800]
**Describe the bug**
When trying to set the `width` attribute on the `<mj-hero>` element, the compiler throws the following error:  
```
➜ mjml email_activation.mjml -o email_activation.html --config.minify=false --config.beatuify=true
Line 39 of /emails/templates/email_activation/email_activation.mjml (mj-hero) — Attribute width is illegal
```

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
```html
<mj-hero mode="fixed-height" height="300px" width="100%" background-width="600px" background-height="300px" background-url="https://someimage.url/public/assets/img/background-banner.png" background-color="#2a3448" padding="30px">
      <mj-image src="https://someimage.url/public/assets/img/logo.png" width="200px" align="left" />
      <mj-text color="#ffffff" align="left" font-size="48px" line-height="51px" font-weight="bold">
        HERZLICH<br> WILLKOMMEN
      </mj-text>
    </mj-hero>
```
2. Render it to HTML by doing `mjml email_activation.mjml -o email_activation.html --config.minify=false --config.beatuify=true`

**Expected behavior**
It should compile with no errors, because the documentation clearly states, that the element can have the `width`-attribute.

https://mjml.io/documentation/#mjml-hero

**MJML environment (please complete the following information):**
 - OS: MacOS
```
➜ mjml --version
mjml-core: 4.5.1
mjml-cli: 4.5.1
```

**Comment by iRyusa** [comment]
Well the doc is a bit outdated here this was removed for a while now. 

It just follows mj-body as it should

**Comment by chrislow** [comment]
Okay, thats bad. We should update the docs then. But how can i make my code run? I need to set the width attribute to give my `<mj-image>`-tag a small width. If you don't add `width="100%"` to the `<mj-hero>`-element, the width on the image tag does not work.

**Comment by iRyusa** [comment]
It does work perfectly fine ? https://mjml.io/try-it-live/ryt8xFvbU

**Comment by GarryFlemings** [comment]
@chrislow I happen to be working now on the document update for `mj-hero`. The `width` attribute will not appear in the next version.

While my work isn't done, I expect it to be complete before the next release.

Thanks for that report.
