### ISSUE TITLE
mj-navbar and mj-navbarlink href handling with handlebars variable

### ISSUE THREAD

**Issue by iamjoeker** [mjmlio/mjml#1801]
**Describe the bug**
When providing a handlebars expression as the be `base-url` attribute of `mj-navbar`, it is not included in the generated urls of the `mj-navbarlink` elements. When I try to include the handlebars expression in the href attribute of the `mj-navbarlink` it is URL encoded. I've not yet been able to find a way to get a generated navbar link which includes the handlebars expression.

This is inconsistent with other elements which correctly pass through `{{var}}` to the src or href attributes.

**To Reproduce**
1. Create MJML file with code below
1. Render to HTML using CLI or JS
1. Note that
   1. In the case of example 1, the generated links do not include the `base-url`
   1. In the case of example 2, the generated links have the handlebars tag URL encoded. 

** Code example 1**
```mjml
<mjml>
  <mj-body width="800px">
    <mj-section background-color="#161616">
      <mj-column>
        <mj-navbar base-url="{{baseUrl}}" hamburger="hamburger" ico-color="white">
          <mj-navbar-link mj-class="navbar-link" href="/dashboard">Dashboard</mj-navbar-link>
          <mj-navbar-link mj-class="navbar-link" href="/profile">Profile</mj-navbar-link>
        </mj-navbar>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

** Code example 2**
```mjml
<mjml>
  <mj-body width="800px">
    <mj-section background-color="#161616">
      <mj-column>
        <mj-navbar hamburger="hamburger" ico-color="white">
          <mj-navbar-link mj-class="navbar-link" href="{{baseUrl}}/dashboard">Dashboard</mj-navbar-link>
          <mj-navbar-link mj-class="navbar-link" href="{{baseUrl}}/profile">Profile</mj-navbar-link>
        </mj-navbar>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
In the case of example 1, I expect `{{baseUrl}}` to be prepended to the `href` attribute of the `mj-navbar-link` elements.

In the case of example 2, I expect that (like other elements), the handlebars expression is not URL encoded.

**MJML environment (please complete the following information):**
 - OS: macOS 10.15.2
 - MJML Version: 4.5.1
 - MJML tool used: CLI and `mjml2html` is a test node app

**Email sending environment(for rendering issues)**:
 - N/A

**Affected email clients (for rendering issues):**
- N/A

**Screenshots**
N/A

**Comment by iRyusa** [comment]
Yup we should remove the `url.resolve` and just append both base url & href instead.
