### ISSUE TITLE
[FR] customize default style

### ISSUE THREAD

**Issue by jimblue** [mjmlio/mjml#1802]
**Is your feature request related to a problem? Please describe.**
I need all `<p>` tag to have a different style from the MJML default defined here:
https://github.com/mjmlio/mjml/blob/f0e32bb88a8f5cdf076a31da9702afdef282a8d3/packages/mjml-core/src/helpers/skeleton.js#L43

**Describe the solution you'd like**
It could be nice to have a something like a `<mj-style default>` tag to overide the default MJML style.

**Describe alternatives you've considered**
I'm actually overide the default in a  `mj-style` like so:
```css
p {
    margin: 0 !important;
}
```
But I'm affraid some emails clients will not follow this rule and break my templates.

**Comment by iRyusa** [comment]
Well if head styles are supported in the first place then there's no real need to have such feature because of how cascading works in CSS ( and here, the important is totally not needed ). 

Those small overrides ensure that everything will be displayed as it should everywhere.
