### ISSUE TITLE
Support HTML "font-size" attribute in mj-text css-class

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1803]
**Motivation for this issue**

@RussellSinclair reported issues with `font-size` in `mj-class`es in our Slack channel, https://mjml.slack.com/archives/C12HESC2G/p1580157591039400. The subject code is very similar to his, with minor modifications and augmentation for this purpose.

**Is your feature request related to a problem? Please describe.**

https://mjml.io/try-it-live/HJ0uiMfMU demonstrates that in this code, the HTML attribute `small` does not work in the MJML `css-class`. It further demonstrates that in this code, the MJML attribute `small` works in the MJML `mj-class`.

Our documentation says, under `mjml-style`,

> This tag allows you to set CSS styles that will be applied to the __HTML__ in your MJML document as well as the HTML outputted. The CSS styles will be added to the head of the rendered HTML by default, but can also be inlined by using the inline="inline" attribute.

**Analysis**

I see no indication of an inlined `font-size:12px` prior to the `css-class="small"` string in the resulting HTML (either "to the head of the rendered HTML" or otherwise).

**Describe the solution you'd like**

Maybe
(1) Support HTML `font-size` in MJML `css-class` attributes, or
(2) Add more information to our documentation about which of the many HTML attributes we support. Maybe different attributes for each MJML component?

Implicitly, (1) above might be a call for supporting a great many other "commonly used" HTML attributes. Maybe it's unreasonable to support a great many.

**Describe alternatives you've considered**

I don't claim adequate expertise here. Above, I've listed support and change to documentation. There's lots of detail to fill in.

**Additional context**

For any impact on documentation, I'm happy to facilitate coordination among team members to achieve consensus on appropriate documentation changes for this issue. My background is twenty years as a software project manager, credentialed for the large majority of that time as a Project Management Professional (PMP), similar to the PRINCE2 certification which I understand to be better known in Europe.

**Comment by iRyusa** [comment]
Well it's supported but as usual you have to tweak the CSS selector
 `.small { font-size: 12px; }` should become: `.small div { font-size: 12px !important; }` and then it works.

Note that the `!important` is required as font-size is already inlined by mj-text, so you should stick to a `mj-class` here instead.
