### ISSUE TITLE
Inline media queries with <mj-style>

### ISSUE THREAD

**Issue by ctinnita** [mjmlio/mjml#1805]
Hello,

First to mention, I am using mjml 3.3.3.

**Is your feature request related to a problem? Please describe.**
I am trying to inline all the styling by using <mj-style inline="inline"> tags but the media queries do not get inlined.

**Describe the solution you'd like**
Is there a way to inline the media queries using <mj-style inline="inline">?

**Comment by iRyusa** [comment]
Nope, you can't add media queries on `style` HTML attribute so there's no way to do so.
