### ISSUE TITLE
Inline automatically generated column width styles

### ISSUE THREAD

**Issue by ctinnita** [mjmlio/mjml#1806]
Hello,

First to mention, I am using mjml 3.3.3.

**Is your feature request related to a problem? Please describe.**
In the mjml built HTML document there is an automatically generated <style> section like 
```
<style type="text/css">
  @media only screen and (min-width:480px) {
    .mj-column-per-50 { width:50%!important; }
.mj-column-per-100 { width:100%!important; }
.mj-column-per-20 { width:20%!important; }
.mj-column-per-80 { width:80%!important; }
.mj-column-per-65 { width:65%!important; }
.mj-column-per-35 { width:35%!important; }
  }
</style>
```
which includes styling for all the used column widths.
What I am trying to do is to inline all of the styling in the template.

**Describe the solution you'd like**
Is there a way to inline these column styles too?

**Comment by iRyusa** [comment]
Well this is "almost" the same issue as #1805 so, ... no
