### ISSUE TITLE
Avoid styling in <style> sections to be truncated/dropped in mail clients

### ISSUE THREAD

**Issue by ctinnita** [mjmlio/mjml#1807]
**Is your feature request related to a problem? Please describe.**
Related to #1805 and #1806,
what we are trying to do is to inline all the styling because of concern that <style> sections might be truncated or dropped by email clients.

**Describe the solution you'd like**
In that context, what is your recommended solution with mjml to make sure that styling in <style> sections is not truncated or dropped?

**Comment by iRyusa** [comment]
Well, MJML is built mobile first, so if you client doesn't support head style, it will display the mobile version instead. There's no magic, if clients doesn't support head style then there's no way to have a responsive email.

**Comment by ctinnita** [comment]
I understand, thank you for your reply.
From your experience with MJML, would there be a recommended max <style> section length and/or max number of <style> sections, in order to increase the chances of successful acceptance by mail clients?

**Comment by iRyusa** [comment]
Well if they support it one time they will support it everytime. Gmail tends to remove any style block that contains invalid css for instance.
