### ISSUE TITLE
[mj-divider] Double padding bug

### ISSUE THREAD

**Issue by CodeSkills** [mjmlio/mjml#1808]
**Describe the bug**
When using `padding-top,padding-bottom,padding-left,padding-right` attributes, the `mj-divider` still persist its default `padding` attribute, so the rendered result has both, which breaks is some browsers.

**To Reproduce**
Go to https://mjml.io/try-it-live/ryCVSx_zL
Show HTML code
Rendered HTML of divider:
```html
<td style="font-size:0px;padding:10px 25px;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;word-break:break-word;">
```

**Expected behavior**
```html
<td style="font-size:0px;padding-top:10px;padding-right:10px;padding-bottom:10px;padding-left:10px;word-break:break-word;">
```

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version Latest
 - MJML tool used MJML Online tool and local js app

**Comment by iRyusa** [comment]
I highly doubt that padding will be applied twice as `padding` is a [shorthand property](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties). Can you show an example where it breaks ?

**Comment by CodeSkills** [comment]
Just had a few reports from clients that use unknows browsers/older email client version, where it messes up the render a bit) I will try to get you a concrete example until I get that you can close this (if you need that). I thought that this was unintentionally applied double padding.

**Comment by iRyusa** [comment]
Padding can be applied twice within a vml block (eg: background image on a section) because of an old obscure Outlook bug. You can mitigate this by relying on align attribute & column size instead of padding.
