### ISSUE TITLE
Button letter-spacing never made it to production?

### ISSUE THREAD

**Issue by rfoel** [mjmlio/mjml#1809]
**Is your feature request related to a problem? Please describe.**
While working on a button, I wanted to add letter-spacing to it. As a developer I checked GitHub first and I saw that had a PR for it already merged. When I tried to use it is not there yet, but looking at the commits it is right after the v4.5.1 release. So wasn't it deployed after all?

**Describe the solution you'd like**
A new release would be nice.

**Describe alternatives you've considered**
Forking everything and make it my own.

**Additional context**

![image](https://user-images.githubusercontent.com/19496473/73940024-6ea2a280-48c9-11ea-966a-8aa915c0e39e.png)

**Comment by iRyusa** [comment]
Looks like we had it merge on master and push `next` branch instead 🤔 
We have a small update on column gutter that should be pushed soon to npm so it should come with it

**Comment by rfoel** [comment]
@iRyusa close this issue when this is release, will ya?

**Comment by dagadbm** [comment]
hummm i still cant use letter spacing...

what happened?

**Comment by dagadbm** [comment]
any work arounds for this?

**Comment by dagadbm** [comment]
seems that it works lol.. only the try-it-live page complains about it

**Comment by iRyusa** [comment]
You can check the try it live version right after the logo :) it's still not updated yet

**Comment by donni106** [comment]
It is also not listed in the docs yet: https://mjml.io/documentation/#mjml-button

**Comment by iRyusa** [comment]
Try it live isn't yet updated to 4.6, so as the doc we'll try to update it soon

**Comment by Antimated** [comment]
Any updates on this? I got the same issue

**Comment by iRyusa** [comment]
It works just fine https://mjml.io/try-it-live/BJRPJGfLP  ¯\\_(ツ)_/¯

**Comment by Antimated** [comment]
> It works just fine https://mjml.io/try-it-live/BJRPJGfLP ¯\_(ツ)_/¯

Damn I’m stupid, I was using an older version of the mjml vscode plugin that was still running on mjml 4.2 🤦‍♂️
