### ISSUE TITLE
Further documentation at docs > Standard Head components > mj-attributes?

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1811]
**Is your feature request related to a problem? Please describe.**

In [our Slack](https://mjml.slack.com/archives/C12HESC2G/p1581102500132500), @dillon wrote

>Can I have a css-class be part of mj-class? I don't see anything about that in documentation

**Describe the solution you'd like**

Our documentation would be better if it listed all the MJML tags eligible to include as children of `mj-attributes` and how developers can use each of those tags.

- The text says any other MJML tag can go there and why, and indicates css-class can go there.
- An &lt;aside> indicates `mj-all` can go there and why. It does not mention css-class.
- The accompanying code demonstrates `mj-class`. The text does not mention mj-class.
- If there are any more tags usable here, our documentation would improve with mention of them. If no other tags are usable, that statement would be useful.

Additionally, this location in the documentation is great for a discussion of the similarities and differences of HTML and MJML elements, and HTML and MJML attributes. Perhaps there is lots of confusion on related issues.

**Additional context**

I already worked a bit on a draft for fixing parts of this; I haven't pushed it to the repository. If the team provides me information not in the existing documentation, I'll be happy to include it, either before or after I push my initial version.

**Comment by iRyusa** [comment]
It's a bit "weird" for me because it feels like the current definition doesn't need to mention this.

Doc says that mj-attributes will override any default attributes, so every "supported" attributes for a given tag, as css-class is supported everywhere I don't understand why it should be a special case.
