### ISSUE TITLE
'juicePreserveTags' not applied in Watch mode

### ISSUE THREAD

**Issue by Micah-S** [mjmlio/mjml#1812]
Given the following code:
```
<mjml>
  <mj-head>
    <mj-style inline="inline">
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-raw>
          <!-- htmlmin:ignore -->
          <#include "7476468">
            <!-- htmlmin:ignore -->
        </mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

I was running into an issue where my `<#include>` tag was being auto closed with `</#include>`, which errors when processed by FreeMarker.

I tried to utilize the `juicePreserveTags` config to prevent this but there was no difference in the output.
ex:
```
mjml -w ./index.mjml -o ./result.html --config.juicePreserveTags='{"myTag": { "start": "<#", "end": ">" }}'
```

Eventually I ran the above command without `-w` and sure enough the closing tag was not added. Watch mode must not be applying `juicePreserveTags` when processing.

**Comment by iRyusa** [comment]
Did you try to put the config option first ?

**Comment by Micah-S** [comment]
Yes it didn't make a difference doing the following:
```
mjml --config.juicePreserveTags='{"myTag": { "start": "<#", "end": ">" }}' -w ./index.mjml -o ./output.html
```
At the same time, `--config.minify true` works correctly:
```
mjml --config.juicePreserveTags='{"myTag": { "start": "<#", "end": ">" }}' -w ./index.mjml -o ./output.html --config.minify true
```

**Comment by iRyusa** [comment]
🤔 We'll take a look then it's really weird

**Comment by kmcb777** [comment]
Hi again Micah, thanks for noticing this, PR opened 👍

**Comment by iRyusa** [comment]
This should be good now! I'm closing
