### ISSUE TITLE
I got background-position and background-size working for Outlook for desktop 2007+

### ISSUE THREAD

**Issue by Alexnortung** [mjmlio/mjml#1814]
# Is your feature request related to a problem? Please describe.
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

When adding a background image to a section there is currently no way to change the background position straight from MJML to work for all clients. I get frustrated thjat I need to make this work by manipulating the HTML and VML.

**I am only describing how to do this with VML objects as it is trivial to make it work with a simple css property**

# Describe the solution you'd like
*A clear and concise description of what you want to happen.*

I would like to be able to add the background-position attribute to the `mj-section` element like this

 ```html
<mj-section 
    background-url="https://placehold.it/900" 
    background-size="cover" 
    background-position="center">
    <!-- content -->
</mj-section>
```

To make the background-position work for Outlook desktop clients the VML should be changed, more specifically, the `<v:fill>` element

## HTML and VML for center background image

To make the image stay in the center the `origin` and `position` attributes needs to be changed to `0.5, 0.5` 
for example

```html
<v:fill  origin="0.5, 0.5" position="0.5, 0.5" src="http://placehold.it/1800x1800" type="tile" />
```

## making cover work

cover will work by adding two more attributes to the `<v:fill>` element: `size="1,1"` and `aspect="atleast"`.
For an example we can use the above example where both cover and position center will work

```html
<v:fill  origin="0.5, 0.5" position="0.5, 0.5" src="http://placehold.it/1800x1800" type="tile" size="1,1" aspect="atleast" />
```

## making contain work 

This one is a little different, there are a few things that should be changed here. The first things that should be changed is `type="frame` this will also make the background non-repeating (which might be a plus 🤠). you also want to add `aspect="atmost"` and `size="1,1"`. 
The `origin` and `position` attributes also needs to be changed to `0,0` to center the image.

For example

```html
<v:fill  origin="0, 0" position="0, 0" src="http://placehold.it/1800x1800" type="frame" aspect="atmost" size="1,1" />
```

# Additional context
*Add any other context or screenshots about the feature request here.*

All of the above examples has been tested in litmus for Outlook versions 2007, 2010, 2013, 2016 and 2019 for windows desktop.

**Comment by iRyusa** [comment]
This could be great to implement, last client to not support something similar would be outlook.com

Can you provide a litmus link for the test for all values ?

**Comment by Alexnortung** [comment]
@iRyusa Yes, here they are, it's not perfect because I was playing around with alot of the HTML. But I think you'll get the point https://litmus.com/builder/ecec985

**Comment by Alexnortung** [comment]
@iRyusa you mentioned outlook.com, but I just tested outlook.com and it seems to work fine with the css property `background-position: center`. The only other problem I ran into was that Yahoo mail doesn't seem to support shorthand `background` property, which means I also had to apply `background-size: cover` in my css.

**Comment by iRyusa** [comment]
Well they might have updated it then ! Good to know :D 

Can you work a bit on that ? (opening a PR) 

If you need some help we're available on Slack !
