### ISSUE TITLE
css-class ignored in Outlook and Windows Mail alone

### ISSUE THREAD

**Issue by sobolawdev** [mjmlio/mjml#1816]
**Describe the bug**

**To Reproduce**
1. Create a file with this MJML code: ` 

--mj-section---

mj-section css-class="top_header"

and
--mj-style--
            *[class~=top_header] {
                border: 5px solid #f6d372 !important;
            }
            *[class~=top_header] td {
                background-color: #124b80 !important;
            }
            *[class~=top_header] td p, *[class~=top_header] td strong {
                color: #ffffff !important;
                font-size: 1.25em;
            }
</mj-style>
`
2. Render it to HTML by doing 'mjml -w template.mjml -o template.html'
3. Send the HTML to an email address with 'Constant Contact'

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: Windows 10 1909 / WSL - Ubuntu 18.04
 - MJML Version: 4.4.0-beta.2
 - MJML tool used: MJML CLI

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Constant Contact

**Affected email clients (for rendering issues):**
 - Email Client: Outlook/Windows Mail
 - OS: Windows 7+
 - Browser: N/A

**Screenshots**

**Additional context**
A style that shows up in every mail client is not showing up on Outlook or Windows Mail. I'm using the css-class method to attach the class to mj-section. It looks fine in browser and all emails except the Microsoft clients.

**Comment by iRyusa** [comment]
You shouldn't use `*[class~=top_header`  those selector just use the simpler one: `.top_header` instead.

If css class are not supported then there's nothing we can do, just inline the style to be safe
