### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by dstrawhand88** [mjmlio/mjml#1817]
Any chance this will be updated to work with the latest version of mjml? The includes won't render and produce an error:

[MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" doesn't contain a child element.

**Comment by iRyusa** [comment]
Well without any code it's hard to help you here. mj-include works just fine in latest release. 
Please provide more details so we can help you here..

**Comment by dstrawhand88** [comment]
It does out of the box, but when using the builder I get this error:

> mju --build -i ./in -o ./out

Unable to render my-company.html
[MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" doesn't contain a child element.

**Comment by iRyusa** [comment]
Again... that's so little information...
What's this `mju` alias ? Node version ? Mjml version ? What's your file content ? Your OS ? ...

**Comment by iRyusa** [comment]
Ok after digging a bit it looks like you're on the wrong repo as you're talking about https://github.com/justinsisley/mjml-utils

It looks like they're still on MJML 3.x branch so you should either fork/open an issue on mjml-utils repo instead of here
