### ISSUE TITLE
documentation: closing the HTML <img> tag; documentation only

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1819]
**Background**

[Mozilla's documentation on `<img>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img) includes,

> Must have a start tag and must not have an end tag.

**Describe the bug**

My IDE nagged me about closing tags when I used the HTML `<img />` construct. When it did, I was incorrectly closing (says the above) the HTML &lt;img> tag.

I found only one use of the `<img />` construct in MJML documentation. _Docs > Standard Body components > mj-image_ includes, 

> It is similar to the HTML &lt;img /&gt; tag.

My IDE found many instances of terminating `<img>` tags in our code.

I didn't find instances of terminating `<img>` tags in demo code visible in our documentation.

**To Observe**

Docs > Standard Body components > mj-image

A code example: The previous version of _packages/mjml-button/README.md_, the first code in the section.

**Comment by iRyusa** [comment]
As both are valid let's close that
