### ISSUE TITLE
mj-image and width=auto support

### ISSUE THREAD

**Issue by aurmil** [mjmlio/mjml#182]
I want to display an image resized on height, not on width, and with width: auto
but

``` xml
<mj-image width="auto" height="500" padding="0 0" src="..." href="..."></mj-image>
```

becomes

``` html
<img alt="" src="..." style="border:none;display:block;outline:none;text-decoration:none;width:100%;height:500px;" width="700" height="500">
```

note: 700px is my email width

so width auto is not considered or considered as an invalid value and fallbacks to default width 100% behavior

**Comment by arnaudbreton** [comment]
@aurmil thanks for reporting, we'll have a better look and come back to your shortly on it.

**Comment by zrb0529** [comment]
image doesn't support width, correct? so you would have to give a width to the column I think...or the section?

**Comment by blaugueux** [comment]
👍  I'm having exactly the same problem

**Comment by MarionLivet** [comment]
Hi,
I'm having the same issue, I don't want to set a fixed height and width for an image so I set both to "auto" but it's ignored and the image takes 100% of the parent cell.
Is there a work around or am I forced to set their sizes in pixels? If so this is going to be painful as I actually would like to display the image depending on a variable ("http://domain.com/{{variable}}.jpg") and the images corresponding to the variable values don't have the same size.

**Comment by ngarnier** [comment]
hey @MarionLivet, is it a ratio issue? If so, you can either just set the `width` of the image and the height will adapt depending on the image, or just not set it and it will take the width of the column. 

If you want the image to be displayed in its actual width, then it's indeed not possible and would probably break the layout if the image is wider than the container or column it's contained in.

**Comment by dalefish** [comment]
There is a way to achieve 100% width on mobile using media queries. Add
css-class and force 100% on the child table below the class applied to the
contains tr. Only works where media queries are supported obviously.

**Comment by MarionLivet** [comment]
@ngarnier oh too bad, I want the image to be displayed in its actual width, but I'll find another way, thanks!!

**Comment by billscheidel** [comment]
I'm running into the same problem.  Did you ever find a solution @MarionLivet?

**Comment by iRyusa** [comment]
Well `auto` image are supported if you're using them inside a `mj-table` / `table`. I think current `mj-image` goal allow a bulletproof enough approach to add image in an email with consistency for every clients.

`mj-image` require a static width as of today to works properly and could lead to inconsistency across clients. I would recommend as said earlier to do it manually in HTML if `width:auto` is needed.

Note that you can also rewrite image css with `css-class` and `mj-style inline="inline"` too.
