### ISSUE TITLE
Gradients within mj-button; error/false-positive

### ISSUE THREAD

**Issue by zslabs** [mjmlio/mjml#1826]
**Describe the bug**

**To Reproduce**
1. Attempt to use `background-image` within `<mj-button />`
    1. Not supported and does not show in render
1. Attempt to use `background-color="linear-gradient(to right, blue, green)"` as value for `background-color` (I know that's invalid CSS, but for the sake of example)
    1. Throws console error, but renders as `background` in browser.

**Expected behavior**
Should not throw error, or -- if this is invalid for a stylistic reason, potentially provide clearer message on why it's not supported. Not sure if this is similar to https://github.com/mjmlio/mjml/issues/1809 where the error shouldn't be there, or if there's a specific reason behind it.

Can we have fallback values for this, `background="blue linear-gradient(to right, blue, green)"`? The following does work since it's compiled to `background: ...` but the editor is showing an error:

`background-color="blue linear-gradient(to right, blue, green)"`

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.5.1
 - MJML tool used MJML npm package

**Comment by iRyusa** [comment]
MJML linter will only output warning/errors (depending on the validationLevel) when the  attribute doesn't match given regexp.

We don't reject non-valid values in non-strict mode because you can also use some variables in your build system so you can use background-color="{{ my var }}", where it will be flag as invalid.

For unsupported attributes, linter will say that the attribute is illegal, so I don't think we can do much more here ?

**Comment by zslabs** [comment]
@iRyusa Thanks for the quick response. Could you clarify on what you mean by "unsupported attributes"? Is `background` not supported as part of `<mj-button />` because of an email rendering issue, or could I just submit a PR to https://github.com/mjmlio/mjml/blob/master/packages/mjml-button/src/index.js#L10 that would add in that functionality with the `string` attribute? It is a bit odd that when `background-color` is used as part of the component, it gets translated to `background` in the browser; any reason for that?

**Comment by iRyusa** [comment]
Email client quirks, some attributes are supported, some aren't. So sometime we have to use some tricks to have a proper support everywhere

Ex: Desktop outlook doesn't support background image without VML, but nesting VML block just break the email so we "remove" it from any other attribute than section to avoid any issue. You can still mess around with css-class + mj-style and pass some custom css.

**Comment by zslabs** [comment]
Gotcha, thanks for the explanation and I hope you have a great day!
