### ISSUE TITLE
Resend emails in gmail/outlook

### ISSUE THREAD

**Issue by ManuelOG** [mjmlio/mjml#1828]
Hello, first, thank you for mjml, is awesome.

The problem: when you send the email from a web app or an email marketing app everything goes fine, But when you try to use gmail to send the email,  or resend from gmail or outlook then weird things happens.

I think that gmail delete all html comments so if you send from gmail and open in outlook youll have problems. Maybe add a "secure" option that make all the code for outlook obligatory (not in comments) so gmail dont delete it could be a solution.

In outlook i detected that when you try to resend a mail it add a space under every section.

Than you very much.

Sorry if my english is bad.

**Comment by iRyusa** [comment]
Well there's no way to prevent that. Email clients alter the HTML when transferred so we can't do anything about this.
