### ISSUE TITLE
Outlook oft format support

### ISSUE THREAD

**Issue by rsumeetprdxn** [mjmlio/mjml#1830]
Does the framework also supports the .oft format, i have tested it and it doesn't. It adds extra spacing, removes responsive code, requires a single column flow. could all this be fixed.

**Comment by iRyusa** [comment]
We don't want to support such thing as it's specific to outlook and won't really output responsive email as outlook will alter the HTML at the end.

**Comment by adhamaa** [comment]
> Does the framework also supports the .oft format, i have tested it and it doesn't. It adds extra spacing, removes responsive code, requires a single column flow. could all this be fixed.

you can export using the mjml app(engine v^4.8.1) rather than 'mjml index.mjml -o index.html' in terminal, and try insert the file to outlook to convert to OFT format yourself, it's actually work for me...

**Comment by GarryFlemings** [comment]
If you follow this process, the MJML team would recommend that you test thoroughly. I know of no instance of someone saying on the MJML Slack channel that any email client (Gmail and competitors) preserves the HTML we build before sending. Quite the contrary, the consensus seems to be that all (or nearly all) change that HTML. Testing would prove that. It's probably well worth your time!
