### ISSUE TITLE
Optional image (that doesn't take space if not loaded)

### ISSUE THREAD

**Issue by tkafka** [mjmlio/mjml#1832]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to add an image banner into my email, that would show up if client loads the image, but wouldn't take space if images are disabled.

I am struggling to do this in mjml:
- the only way to have an image like this in a browser/email client is to have no width or height attribute set
- basically mjml forces me to set the width and height attribute - if I omit height, it will be set to auto, which is equal to width (= huge square image)
- and for width I either have to put the size in px/%, or if I omit the width, it will be computed to equal 100 %

So, currently I can only have huge square placeholder (width: 100%, height: auto = 100 % of width), or I put in the real size, and risk having a huge empty space at the top of the email.

**Describe the solution you'd like**
I would like some way to add 'optional' images, that take zero or almost zero space until loaded. I think in most clients, you can combine omitting width and height attributes, and using the `max-width: 100%` to limit the image overflowing the container.

**Current workaround**

I now use this:

	<mj-text align="center">
		<a href="{{{agentResultLink}}}" style="border:none;font-size:0;line-height:0;"><img alt="" src="my-url" style="max-width:100%;border:none;" /></a>
	</mj-text>

**The problem right now:**
<img width="588" alt="Screenshot 2020-02-20 at 15 34 06" src="https://user-images.githubusercontent.com/876717/74944524-7a788380-53f6-11ea-8f8f-98e21b97def7.png">

**Comment by iRyusa** [comment]
Well as we try to avoid image overflow in Outlook desktop I can't really think of a way to make that happen without breaking some clients. You can still override any inlined css attribute with mj-style inline & css-class ?

**Comment by tkafka** [comment]
@iRyusa I can override style, I think, but the current mj-image implementation just never leaves the `width` attribute blank, and the attribute imo wins.

But never mind, if this is not doable while supporting most clients, then I can continue using my workaround (that still renders as a small approx 20x20 square with question mark even when I add `alt=""` to image and `font-size:0;line-height:0;` to wrapping link).

<img width="778" alt="Screenshot 2020-02-20 at 16 26 07" src="https://user-images.githubusercontent.com/876717/74949210-b95e0780-53fd-11ea-978b-7ea1b69cba94.png">

**Comment by iRyusa** [comment]
By default mj-image will take parent width (minus left & right padding) so yup, there's no way to provide an empty width

**Comment by tkafka** [comment]
Okay, thanks!
