### ISSUE TITLE
Emails showing up in blank in Outlook on InfusionSoft by Keap

### ISSUE THREAD

**Issue by Creativenauts** [mjmlio/mjml#1836]
**Describe the bug**
The emails are showing up blank in Outlook desktop client. InfusionSoft Keap advanced support basically says the HTML is not valid, see below:

After reviewing this with the development team they recommended we removed the commented out ms/outlook comments and now the email shows in outlook.

Some of the examples that were removed are:

```
<!--[if !mso]><!== -->
        <!--[if mso]>
<![endif]-->
```

If these can be removed please remove them from your template as outlook doesn't like those. 

Please let us know if there is anything else we can assist with.

Thanks, Nosko

**To Reproduce**
Simply create an email from within MJML desktop app. Copy the HTML and paste it into InfusionSoft's email editor. Save the template and then send the email, it shows up blank in outlook every time after saving.

**Screenshots**
![blank-email](https://user-images.githubusercontent.com/4481041/75067727-b0cc0680-54bb-11ea-82b3-785eb7074d05.png)

**Additional context**
I do not believe this is an issue with MJML at all. I've tested this on other ESP's without issue and also tested on Putsmail without any issues whatsoever. InfusionSoft Keap insists that this is an issue with the HTML as you will read above. But perhaps someone here has had a similar issue with other Email Service Platforms and knows of an easy fix. 

I can provide the template as well if anyone would like to test.

**Comment by iRyusa** [comment]
If they alter output HTML then we can't do anything as you stated.

Outlook comments are mandatory (and quite commons in email world) to ensure email will be responsive & displayed properly for Outlook desktop (lol at their response on that).

**Comment by Creativenauts** [comment]
@iRyusa thanks for the response! I will be passing this onto their support team. LOL!!
