### ISSUE TITLE
Removing default fonts is unclear

### ISSUE THREAD

**Issue by zslabs** [mjmlio/mjml#1847]
**Describe the bug**
I'm attempting to use the bundled MJML file inside of providers like PostMark, but they do not allow `<link />` tags, which is inserted by default with the core fonts; such as `<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" type="text/css">`. Using the CLI, I've tried:

* `mjml --config.fonts {} ./src/*.mjml -o ./build/`
* `mjml --config.fonts null ./src/*.mjml -o ./build/`
* `mjml --config.fonts false ./src/*.mjml -o ./build/`

With all 3 resulting in things like:

```
<link href="{" rel="stylesheet" type="text/css">
<link href="}" rel="stylesheet" type="text/css">
```

What's odd is that it doesn't ALWAYS do this with the empty object, but it does sometimes... a bit stumped here on how to remove those defaults. Is there a reason to keep them by the way? Shouldn't we default to a more standard system-stack, like `-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji`?

**To Reproduce**
1. ☝️ 

**Expected behavior**
No custom fonts should be rendered.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.5.1
 - MJML tool used cli

**Email sending environment(for rendering issues)**:
 - Platform used to send the email PostMark

**Comment by iRyusa** [comment]
Can you try with `mjml --config.fonts={} ./src/*.mjml -o ./build/` ?

**Comment by zslabs** [comment]
👋 When running `mjml --config.fonts={} ./src/*.mjml -o ./build/` that seemed to work fine, but when using the `-w` command, it does not `mjml --config.fonts={} -w ./src/*.mjml -o ./build` and adds those brackets inline:

```
      <!--[if !mso]><!-->
        <link href="{" rel="stylesheet" type="text/css">
<link href="}" rel="stylesheet" type="text/css">
        <style type="text/css">
          @import url({);
@import url(});
        </style>
      <!--<![endif]-->
```

**Comment by iRyusa** [comment]
Yup the watch command doesn't pass options correctly it should be fixed in the next release

**Comment by zslabs** [comment]
Ah gotcha! Any pending work to be done before the next version is released?

**Comment by iRyusa** [comment]
A few merge, but it should be out monday

**Comment by zslabs** [comment]
Sounds great, appreciate the quick replies as always. Happy to close this one, unless you think it's a good idea to keep open until this issue is resolved in `master` to help anyone else that comes across this issue.

**Comment by iRyusa** [comment]
Sure ! We'll close it when it's released

**Comment by iRyusa** [comment]
It should be good now ! I'm closing :)

**Comment by zslabs** [comment]
Thanks works perfectly!
