### ISSUE TITLE
-V no longer works to show the version in 4.5.x

### ISSUE THREAD

**Issue by DexterTheDragon** [mjmlio/mjml#1848]
**Describe the bug**
Using the `-V` flag used to show the version number. 

**To Reproduce**
```
% npm install -g 'mjml@4.4.x'
% mjml -V
mjml-core: 4.4.1
mjml-cli: 4.4.1

% npm install -g 'mjml@4.5.x'
% mjml -V
Command line error:
No input argument received
```

**Expected behavior**
Expected `mjml -V` to print the version info.

**MJML environment (please complete the following information):**
 - OS: macOS 10.15.3
 - MJML Version 4.5.1
 - MJML tool used: cli

**Comment by iRyusa** [comment]
That's a weird one 🤔  @kmcb777 do you have some time to investigate this before release 4.6 ?
