### ISSUE TITLE
mjmlConfigOptions in output with version 4.6.1

### ISSUE THREAD

**Issue by notFloran** [mjmlio/mjml#1856]
At the beginning of CLI output the following lines are displayed : 

```
mjmlConfigOptions ------------------------------------------>
{}
```

![Capture d’écran 2020-03-04 à 10 16 22](https://user-images.githubusercontent.com/523981/75863788-55760e80-5e01-11ea-8ab0-e00e2cbc5f13.png)
![Capture d’écran 2020-03-04 à 10 16 30](https://user-images.githubusercontent.com/523981/75863791-560ea500-5e01-11ea-83d8-31bcb1d5e912.png)

**To Reproduce**
1. Create a file `test.mjml` with this MJML code: 

```
  <mjml>
    <mj-body>
      <mj-section>
        <mj-column>
          <mj-text>
            Hello World!
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-body>
  </mjml>
```

2. Render it to HTML by doing `npx mjml -r test.mjml`
4. See output

**Expected behavior**

Output without:

```
mjmlConfigOptions ------------------------------------------>
{}
```

**MJML environment :**
MacOS

Node v12.16.0

```
mjml-core: 4.6.1
mjml-cli: 4.6.1
```

**Comment by iRyusa** [comment]
@kmcb777 4.6.2 then 😄

**Comment by kmcb777** [comment]
aw i guess i didn't yarn build again after last clean up :/ 
4.6.2 is released, thanks for reporting that
