### ISSUE TITLE
MJML API still uses v4.3.1

### ISSUE THREAD

**Issue by brunocfalcao** [mjmlio/mjml#1858]
Hi,

The MJML API from my understanding still uses the version 4.3.1.

Any plans to make to 4.6.1?

Thanks in advance for the feedback.

**Comment by iRyusa** [comment]
cc @ngarnier :)

**Comment by malanga31** [comment]
Any news?

**Comment by ngarnier** [comment]
We'll try to release a new version of the API next week

**Comment by malanga31** [comment]
thanks @ngarnier

**Comment by ngarnier** [comment]
I didn't update the issue right away but the MJML API is now running on v4.6.1.
