### ISSUE TITLE
How do i remove all the comments when converting MJML to HTML, specially the IE support comments.

### ISSUE THREAD

**Issue by umanga907** [mjmlio/mjml#1859]
I have been using MJML through out the years now and really like it. I have used mjml only for making email templates but now i am using it to make PDF templates which gets printed afterwards. 
The developer who is working on it always ask me to remove the comments because it giving a parse error when he is making it dynamic. I have been removing the comments manually now and there are a lot of comments, those comments are all over the code. 
Like these comments, 
` <![endif]--><!--[if !mso]><!-->`

It would be better if there would be an option to remove the comments when compiling from MJML to HTML.

**Comment by iRyusa** [comment]
That's not really an use case for emails. You can just ask him to sanitize the content with a simple regexp replace. That would require to bloat MJML code base for no real reason.
