### ISSUE TITLE
[BUG] mj-font not working with Twig

### ISSUE THREAD

**Issue by jimblue** [mjmlio/mjml#1860]
If using Twig to define the font href like so:

```html
<mj-font name="Pensum Display" href="{{ asset_url_static('css/newsletter-font.min.css') }}" />
```

The output is broken:

```twig
<style type="text/css">
    @import url({{ asset_url_static('css/newsletter-font.min.css')
    }
    }

    );
  </style>
```

**Comment by iRyusa** [comment]
Yeah not so much we can do about this, try to add a beautify=false to the cli / config, beautifier believe that `{{}}` is a css block declaration

**Comment by jimblue** [comment]
OKay no pb disabling beautifier fix it.
Tks :smile:
