### ISSUE TITLE
Accordion compatibility issues

### ISSUE THREAD

**Issue by Mlangdon22** [mjmlio/mjml#1862]
Hey all, 

Trying to use an accordion tag to contain a large amount of information within an email. However, when I plug in the HTML, the drop down no longer shows and each tab stays open. I did see that this will happen if there are compatibility issues, but I was wondering if there is an HTML fix I could do instead or some other workaround?

Thank you so much for your help. 

Here's what the list looks like in MJML: 
https://imgur.com/a/uLp1yrd

**Boilerplate Accordion HTML taken from MJML**
<!doctype html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><title></title><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style type="text/css">#outlook a { padding:0; }
          body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
          table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
          img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
          p { display:block;margin:13px 0; }</style><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700" rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css"><style type="text/css">@import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700);
@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);
@import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);</style><style type="text/css">@media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
      }</style><style type="text/css">noinput.mj-accordion-checkbox { display:block!important; }

      @media yahoo, only screen and (min-width:0) {
        .mj-accordion-element { display:block; }
        input.mj-accordion-checkbox, .mj-accordion-less { display:none!important; }
        input.mj-accordion-checkbox + * .mj-accordion-title { cursor:pointer; touch-action:manipulation; -webkit-user-select:none; -moz-user-select:none; user-select:none; }
        input.mj-accordion-checkbox + * .mj-accordion-content { overflow:hidden; display:none; }
        input.mj-accordion-checkbox + * .mj-accordion-more { display:block!important; }
        input.mj-accordion-checkbox:checked + * .mj-accordion-content { display:block; }
        input.mj-accordion-checkbox:checked + * .mj-accordion-more { display:none!important; }
        input.mj-accordion-checkbox:checked + * .mj-accordion-less { display:block!important; }
      }

      @goodbye { @gmail }</style></head><body><div><div style="background:#ffffff;background-color:#ffffff;margin:0px auto;max-width:600px;"><table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff;background-color:#ffffff;width:100%;"><tbody><tr><td style="direction:ltr;font-size:0px;padding:20px;text-align:center;"><div class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"><table border="0" cellpadding="0" cellspacing="0" role="presentation" style="background-color:#dededd;vertical-align:top;" width="100%"><tr><td style="font-size:0px;padding:1px;word-break:break-word;"><table cell-spacing="0" cell-padding="0" class="mj-accordion" style="width:100%;border-collapse:collapse;border:none;border-bottom:none;font-family:Ubuntu, Helvetica, Arial, sans-serif;"><tbody><tr><td style="padding:0px;"><label class="mj-accordion-element" style="font-size:13px;"><input class="mj-accordion-checkbox" type="checkbox" style="display:none;"><div><div class="mj-accordion-title"><table cell-spacing="0" cell-padding="0" style="width:100%;border-bottom:none;"><tbody><tr><td style="width:100%;background-color:#ffffff;color:#031017;font-size:18px;font-family:Roboto, Open Sans, Helvetica, Arial, sans-serif;padding:15px;">Why use an accordion?</td><td class="mj-accordion-ico" style="padding:16px;background:#ffffff;vertical-align:middle;"><img src="http://i.imgur.com/Xvw0vjq.png" alt="+" class="mj-accordion-more" style="display:none;width:24px;height:24px;"><img src="http://i.imgur.com/KKHenWa.png" alt="-" class="mj-accordion-less" style="display:none;width:24px;height:24px;"></td></tr></tbody></table></div><div class="mj-accordion-content"><table cell-spacing="0" cell-padding="0" style="width:100%;border-bottom:none;"><tbody><tr><td style="background:#fafafa;font-size:14px;font-family:Open Sans, Helvetica, Arial, sans-serif;color:#505050;padding:15px;"><span style="line-height:20px">Because emails with a lot of content are most of the time a very bad experience on mobile, mj-accordion comes handy when you want to deliver a lot of information in a concise way.</span></td></tr></tbody></table></div></div></label></td></tr><tr><td style="padding:0px;"><label class="mj-accordion-element" style="font-size:13px;"><input class="mj-accordion-checkbox" type="checkbox" style="display:none;"><div><div class="mj-accordion-title"><table cell-spacing="0" cell-padding="0" style="width:100%;border-bottom:none;"><tbody><tr><td style="width:100%;background-color:#ffffff;color:#031017;font-size:18px;font-family:Roboto, Open Sans, Helvetica, Arial, sans-serif;padding:15px;">How it works</td><td class="mj-accordion-ico" style="padding:16px;background:#ffffff;vertical-align:middle;"><img src="http://i.imgur.com/Xvw0vjq.png" alt="+" class="mj-accordion-more" style="display:none;width:24px;height:24px;"><img src="http://i.imgur.com/KKHenWa.png" alt="-" class="mj-accordion-less" style="display:none;width:24px;height:24px;"></td></tr></tbody></table></div><div class="mj-accordion-content"><table cell-spacing="0" cell-padding="0" style="width:100%;border-bottom:none;"><tbody><tr><td style="background:#fafafa;font-size:14px;font-family:Open Sans, Helvetica, Arial, sans-serif;color:#505050;padding:15px;"><span style="line-height:20px">Content is stacked into tabs and users can expand them at will. If responsive styles are not supported (mostly on desktop clients), tabs are then expanded and your content is readable at once.</span></td></tr></tbody></table></div></div></label></td></tr></tbody></table></td></tr></table></div></td></tr></tbody></table></div></div></body></html>

**Comment by kmcb777** [comment]
Hi @Mlangdon22 i'm not sure i understand how you did proceed here.
It's quite hard to read the generated html, could you provide your mjml code instead ?
Or did you use the generated html from the accordion, then added html inside ?

**Comment by Mlangdon22** [comment]
Apologies, I've linked my MJML code below. 
This result is coming from Outlook 

<mj-wrapper padding-top="0" padding-bottom="0" css-class="body-section">
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px">
        <mj-column width="100%">
          <mj-text color="#637381" font-size="18px" padding-top="0px" align="center">
            There are plenty of well-kept secrets for buying a home, but you don’t have to be an expert homebuyer to take advantage of them!
          </mj-text>
          <mj-text color="#2198C0" font-size="22px" padding-top="30px" align="center">
            Here are a few of the best-kept secrets out there that many new homebuyers don’t know about:</mj-text>
          <mj-divider border-color="#F45E43"></mj-divider>
        </mj-column>
      </mj-section>
      <mj-section padding="0px" background-color="#ffffff">
        <mj-column background-color="#dededd">
          <mj-accordion>
            <mj-accordion-element>
              <mj-accordion-title>1: Don’t try to time the market to your advantage</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
                The housing market can be fickle, and even industry experts often can’t predict what it will do next. If you find a home you love but start waiting for prices to drop, you might end up missing out on an already good deal. <br></br>When you find something that’s affordable and meets your needs, snatch it up and don’t think about what things might be like in a few months.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>2: Scope out the neighborhood</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
              You may have found the perfect home, but how is the neighborhood? Start dropping by at different times of the day and consider what is important to you for your daily life. Where is the nearest grocery store? How is the traffic? <br></br>Test your commute to work or school and see how you handle the drive. Even if you don’t have children, the quality of school districts in the area play an important role in the future value of your home, so consider carefully.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>3: Don’t make any large purchases</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
                As soon as you start thinking about purchasing a home, you should keep your money exactly where it is for approximately 3 to 6 months before buying. Your credit profile is important when it comes to your mortgage, so avoid large purchases like a car or high-end furniture to keep your credit score and debt-to-income ratio in tact until closing time.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>4: Get preapproved before home shopping or making an offer</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
                Aside from finding out for yourself exactly what kind of home you can afford, getting preapproved puts you at a great advantage in a bidding war with another potential buyer. <br></br>When you are preapproved and the other bidder either hasn’t spoken to a mortgage company at all or is only prequalified, chances are a seller and listing agent are going to take your bid much more seriously.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>5: Don’t let your emotions get the best of you</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
                It’s easy to let our emotions overwhelm our instincts from time to time, especially when making such a big decision. You might fall in love with one aspect of a house and ignore all other factors, which may lead to some unwise financial decisions. <br></br> While a home is vastly important to your family and personal life, treating it like the investment that it is will allow you to make sound financial decisions. Don’t get wrapped up in the little details, but instead think more of the value of the home and what kind of deal you are getting.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>6: Call the inspector</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
                Most people don’t even buy a carton of eggs without checking each one for cracks, so why would you buy a home without letting a professional give it a good once over? Hiring a home inspector will cost you a few hundred bucks, but it can save you thousands in the long run by providing you with the information you need to decide whether or not to buy. Furthermore, any issues found can be used as a bargaining chip for negotiation.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>7: Never turn down help</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
                If two heads are better than one, than it never hurts to add more professionals and help into the mix. Ask family, friends, real estate agents, and mortgage professionals all the questions you can and educate yourself properly.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>
            <mj-accordion-element>
              <mj-accordion-title>8: Take your time.</mj-accordion-title>
              <mj-accordion-text>
                <span style="line-height:20px">
               There is often a lot of pressure placed on homebuyers to push through a deal as quickly as possible. Don’t feel like you have to give in to that pressure. Buying a home is a major step, and since you’re probably going to spend at least 5 years living and investing in it, you should feel comfortable taking all the time you need. <br></br>You don’t want to get locked into rates and terms that are not in your best interest, so take advantage of any opportunities to speak with professionals in the industry.
              </span>
              </mj-accordion-text>
            </mj-accordion-element>

          </mj-accordion>
        </mj-column>
      </mj-section>
    </mj-wrapper>

**Comment by iRyusa** [comment]
> However, when I plug in the HTML, the drop down no longer shows and each tab stays open. I did see that this will happen if there are compatibility issues, but I was wondering if there is an HTML fix I could do instead or some other workaround?

If client doesn't support click interaction, then there's no way to have an working accordion. That's why you have the accordion open in most of cases
