### ISSUE TITLE
Wrong button color with href

### ISSUE THREAD

**Issue by hackolein** [mjmlio/mjml#1865]
If I create a button with an href the defined color is not used.

1. Create a file with this MJML code: `<mj-button href="https://mjml.io" background-color="#fff" color="red"  font-family="Arial, sans-serif" padding="20px 0 0 0" font-weight="bold" font-size="16px" >Text</mj-button>`
2. Render it to HTML `<a href="https://mjml.io" style="display: inline-block; background: #ffffff; font-family: Arial, sans-serif; font-size: 16px; font-weight: bold; line-height: 120%; margin: 0; text-transform: none; padding: 10px 25px; mso-padding-alt: 0px; border-radius: 3px; text-decoration: none; color: inherit;" target="_blank">
              test
            </a>`

The color should red and not inherit. 

 - OS: MacOS 10.15.3 
 - MJML Version  4.4.1 and 4.6.2
 - MJML tool used MJML App 2.12.0 and  3.0.0-Alpha.1

**Comment by kmcb777** [comment]
Hi @hackolein i can't reproduce the issue, i used your mjml code with the latest app version and with an older version of mjml, and i get the `color:red;` in the inline-style of the `<a>` as expected.
Maybe you have a mj-attribute that overrides it ?

**Comment by hackolein** [comment]
Yes, i  don't see the inline style  🤦‍♂️, Sorry!
` <mj-style inline="inline">a { text-decoration: none!important; color: inherit!important; }</mj-style>`
