### ISSUE TITLE
Attribute vertical-align is illegal via API

### ISSUE THREAD

**Issue by WebmasterClickPanda** [mjmlio/mjml#1866]
Hello!

Starting today, everytime I try to render HTML elements with the CSS attribute vertical align using the API at the endpoint https://api.mjml.io/v1/render I am getting the following error:

Attribute vertical-align is illegal via API

A few months ago it happened that certain css values were not accepted anymore, and I could correct them in all my HTML templates, however, it is a big issue because I cannot replace this attribute in all my 10 thousand templates, was there any change made in the API accepted attributes?

**Comment by WebmasterClickPanda** [comment]
This is the full error but the line number might be related to my specific template
Line 72 of /home/ndjs/mjmlapi-3270a319-418 (mj-section) — Attribute vertical-align is illegal

**Comment by iRyusa** [comment]
Well `vertical-align` was never supported on `mj-section` (but it's fine on mj-column see https://mjml.io/try-it-live/rknm3CyU8).

 It was just listed as supported in component code but never used.
