### ISSUE TITLE
mj-button does not align in the center where is a background image

### ISSUE THREAD

**Issue by malanga31** [mjmlio/mjml#1867]
Hi Team,
I was trying to add a mj-button in a section with a background image and the mj-button does not align well on outlook.

code:
`<mj-section background-url="http://placehold.it/650x100" background-size="100%" background-color="#ececec" background-repeat="no-repeat">
      <mj-column>
        <mj-button font-size="14px" padding-top="0px" padding-bottom="0px" border-radius="0px" background-color="#002a54" href="https://www.google.com/" align="center"><strong>CTA</strong></mj-button></mj-image>
      </mj-column>
    </mj-section>`
Is there a fix for this?
I tried to search and didn't find anything.
Thanks

**Comment by iRyusa** [comment]
Remove left & right padding on mj-button. 

In a section with background image, padding left & right are applied both the left for some reasons.

**Comment by malanga31** [comment]
Thanks @iRyusa worked fine
