### ISSUE TITLE
Background image on a mj-section does not work on Mail Win10

### ISSUE THREAD

**Issue by malanga31** [mjmlio/mjml#1868]
Hi Team,
I was trying to to build a section with a background image and add a mj-image on top.
For some reason in Mail win10 does not work (Works with a mj-hero), the problem is that I need to add 2 columns on the section (mj-hero does not support 2 columns).
code:
`<mj-section background-url="http://placehold.it/650x400" background-repeat="no-repeat" background-size="100%" background-color="#ececec">
      <mj-column vertical-align="middle">
        <mj-image src="https://via.placeholder.com/300x220/FFFF00/000000" width="300px" alt="some text" padding-bottom="52px" padding-top="52px" align="center"></mj-image>
        </mj-column>
    </mj-section>`

Is there a way to fix it?
Sorry if this was already closed, did not find anything related.

**Comment by iRyusa** [comment]
`mj-hero` doesn't use the same technique (for vml) as `mj-section`, so nope, no way to have it working on win10 mail.
