### ISSUE TITLE
Curly braces inside css values get clobbered

### ISSUE THREAD

**Issue by michelwilson** [mjmlio/mjml#1869]
**Describe the bug**
I want to try and make a template with customizable colors for branding purposes. To that end, I want to use `{{ primary-color }}`, `{{ secondary-color }}` etc in various places in the CSS. Instead of having to inline it, I'd like to just have this in the CSS in the header, but this doesn't work

**To Reproduce**
Minimal template:
```
<mjml>
  <mj-head>
    <mj-style inline="inline">
      .background{
        background-color: {{ primary-color }}
      }
    </mj-style>
  </mj-head>
  <mj-body css-class="">
    <mj-section >
      <mj-column>
       <mj-text css-class="background">
         This is a example
       </mj-text>
      </mj-column>
    </mj-section>
</mjml>
```

**Expected behavior**
```
<td align="left" class="background" style="background-color: {{  primary-color }}; font-size: 0px; padding: 10px 25px; word-break: break-word;" bgcolor="{{ primary-color }}">
```

**Actual output**
```
<td align="left" class="background" style="background-color: { primary-color; font-size: 0px; padding: 10px 25px; word-break: break-word;" bgcolor="{ primary-color">
```

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version: 4.6.2
 - MJML tool used: npm package

**Comment by iRyusa** [comment]
There's some closed issue about this: just disable the beautifier (or use the built-in minifier) as it thinks those curly braces are a css block.

**Comment by michelwilson** [comment]
Ah, will give that a try and will close the issue when that solves it, thanks!!

**Comment by probablyabear** [comment]
@michelwilson, Are you using a templating engine for the color variables?

**Comment by michelwilson** [comment]
Yes, I'm using the output as a template in Sendgrid, so I need the color variables to be substituted _after_ mjml is done :) otherwise it would be simple, first do the color thing and then run mjml...

**Comment by michelwilson** [comment]
@iRyusa I tried the following:
```
`npm bin`/mjml --config.beautify false --config.minify false --config.juicePreserveTags='{"nunjucks": {"start": "{{", "end": "}}"}}' input.html -o output.html`
```
My understanding is that this should disable both the minifier as well as the beautifier and preserve the `{{` and `}}` tags. But, unfortunately, I still get a `background-color: { primary-color;` in the output... Using, for example `<%` and `%>` it does work. One way would be to use those tags, and then to use `sed` to rewrite the output, but ideally mjml should be able to handle this transparently.

**Comment by iRyusa** [comment]
Well I didn't see that you're using juice here to inline it... 

Sadly there's not much we can do here as juice doesn't seems to respect the config. They might interpret it as a CSS block rather than templating block.  Maybe you should try to reproduce it with juice only to see if it's something on MJML or Juice side.

**Comment by michelwilson** [comment]
Clear :) will have a look at that part of the "pipeline". I'm also considering to just use `[[` and `]]`, and then replace it using another tool. Would make some other things easier as well. Thanks for thinking along!

**Comment by iRyusa** [comment]
Closing this for now, feel free to ping us if you're opening an issue on juice side

**Comment by georgeevans1995** [comment]
@michelwilson Did you find a solution for this, I am running into the same problem.
