### ISSUE TITLE
Including a css file

### ISSUE THREAD

**Issue by hardysabs2** [mjmlio/mjml#1872]
mjml@4.6.2
node -v  v10.15.3
I am previewing my mjml file.

I have a number of 
    <mj-style>
.myclassname ....
    </mj-style>

with unique class names that are definitely formatting my content as expected.

Some content is going to be semantic ui so I add above that mj-style element

    <mj-style>
    <mj-include path="./semantic.css"/>
    </mj-style>

Just to preview.

1) The content of semantic.css does not seem to impact on my semantic ui content, but when I take bits from in the file and add them to an mj-style element manually they appear to have an effect.
2) As soon as I add this include (though it's content in no way duplicates class names I have already added, my current styling is dropped.

I cannot seem to find from the docs what I am doing wrong or if this is  a bug.

**Comment by iRyusa** [comment]
Well "content" (mj-text/style/table/...) tags doesn't support mj-include. 

You'll need to `mj-include` inside `mj-head`, and surround your css file content with `<mj-style>`

**Comment by hardysabs2** [comment]
Sorry to trouble you again.  In a regular html file 

<head>
  <link rel="stylesheet" type="text/css" href="./semantic-ui/semantic.css">  
</head>
...
<i aria-hidden="true" class="orange exclamation triangle large icon"></i>
...

presents as expected

but 

  <mj-head>
    <mj-attributes>
...
    </mj-attributes>

    <mj-include path="./semantic-ui/semantic.css"/>

    <mj-style>
...
    </mj-style>

  </mj-head>

with semantic.css

<mj-style>
...
</mj-style>

does not seem to correctly access the fonts.  Should I expect it to?

Is this most likely a limitation of the mjml inclusion mechanism or 
perhaps a limitation of the VS Code previewer?

Or something else.

**Comment by iRyusa** [comment]
It's really hard to help you without the full project, but in the output HTML you should find the style block with semantic css content if the include does work, you should check that first.
