### ISSUE TITLE
How to include LinkedIn company in social media

### ISSUE THREAD

**Issue by hardysabs2** [mjmlio/mjml#1873]
```
          </mj-social-element>
          <mj-social-element name="linkedin" href="https://www.linkedin.com/company/mycompany/">
            LinkedIn
          </mj-social-element>

```
This seems to treat the link as a document and embed it in a linked in login url.  This format with twitter seems to work as a company twitter link.  Do you know how I do the same for LinkedIn?

Thanks

**Comment by iRyusa** [comment]
Well it's written in the documentation https://mjml.io/documentation/#mjml-social

> When using a network with share url, the href attribute will be inserted in the share url (i.e. https://www.facebook.com/sharer/sharer.php?u=[[URL]]). To keep your href unchanged, add -noshare to the network name. Example :
> `<mj-social-element name="twitter-noshare" href="my-unchanged-url">Twitter</mj-social-element>`

**Comment by hardysabs2** [comment]
Sorry.  Thank you.
