### ISSUE TITLE
`mj-body` naming looks wrong in docs

### ISSUE THREAD

**Issue by iamandrewluca** [mjmlio/mjml#1875]
As I see from all examples there is no `mjml-body`, correct it is `mj-body`.  
But when navigating the docs you can see, that is named `mjml-body`

https://mjml.io/documentation/#mjml-body

**Comment by iRyusa** [comment]
The title refers to the package name instead of the tag name (#1480), this will be changed in the next release of the doc as it seems to confuse people.
