### ISSUE TITLE
Adding support for Direction attribute

### ISSUE THREAD

**Issue by mamos98** [mjmlio/mjml#188]
Hi, Thanks for the great work of you guys on mjml.
It's literally the best solution I've ever seen to email design problems.

I'm using mjml for both Persian and English languages and it would be great if you could add support for "direction" attribute in all components like `<mj-text>` , `<mj-button>` , etc. or simply you could help me how to do that.

Currently, I have some issues in Persian and I have to manually edit the html file after building to make texts and buttons to show correctly.

Thanks

**Comment by lRlevolution** [comment]
This would be extremely helpful!

**Comment by iRyusa** [comment]
Hello @mamos98 !

Any idea on how it works on Outlook ?

**Comment by ngarnier** [comment]
Hey @mamos98, I think we might not have understood your request initially. 

I think you're looking for RTL support, isn't it? I'll close this issue to follow the discussion on https://github.com/mjmlio/mjml/issues/230. 

If I misunderstood the purpose of your issue, feel free to reopen!
