### ISSUE TITLE
Color attribute for wrapper components

### ISSUE THREAD

**Issue by adekbadek** [mjmlio/mjml#1881]
**Is your feature request related to a problem? Please describe.**

When using `mj-wrapper` and `mj-column`, user can set the background color, but not the text color.

**Describe the solution you'd like**

A `color` attribute on `mj-wrapper` and `mj-column` components, so that the text in the component can be colored.

**Comment by iRyusa** [comment]
You can already do something like that with `mj-class` https://mjml.io/try-it-live/SJSdUI3_I

I don't think we should add another attribute that interacts with children attributes like that, as it could lead to potential issue of inheritance (ex: I have a default mj-text color set with mj-attributes, and a color on mj-section/column/wrapper and no color attribute on mj-text, who takes the priority and why)
