### ISSUE TITLE
Link to the selector with Mj-navbar-link  crash Thunderbird

### ISSUE THREAD

**Issue by dariuszpaluch** [mjmlio/mjml#1882]
**Describe the bug**
When I click in link with selector to id in mail, Thunderbird will crash.

**To Reproduce**
1. Create a file with this MJML code: 
```html
<mjml>
  <mj-body>
    <mj-section background-color="#ef6451">
      <mj-column>
        <mj-navbar hamburger="hamburger" ico-color="#ffffff">
          <mj-navbar-link href="#test" color="#ffffff">GO_TO_TEST</mj-navbar-link>
        </mj-navbar>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-raw>
        	<a href="#" id="test" style="font-size:12px;color:black">TEST</a>
      	</mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

2. Render it to HTML
3. Send the HTML to an email address
4. Open email in Thunderbird

**MJML environment:**
 - Windows
 - MJML Version 4.5.1

**Email sending environment**:
 - Nodemailer or Gmail by Chrome browser

**Affected email clients:**
 - Thunderbird 68.7.00
 - Windows

**Screenshots**
![crash-thunderbird](https://user-images.githubusercontent.com/15227876/79974180-23943680-8499-11ea-8249-bd2b4c109e60.gif)

**Comment by dariuszpaluch** [comment]
When i replace `<mj-navbar-link>` to `<a>` it works normally

**Comment by iRyusa** [comment]
Link insde `navbar-link` is a standard anchor tag too, so I don't know if this is really related to MJML here. Maybe because links reference to the anchor`#test` that doesn't exist in the document ?

**Comment by iRyusa** [comment]
Ok so after a bit of investigation it looks like it's a bug within thunderbird when you have an anchor with `target="_blank"`. You should open a ticket on thunderbird bug tracker as it's not related to MJML.

**Comment by dariuszpaluch** [comment]
@iRyusa  Yes you are right, thanks a lot 👍
