### ISSUE TITLE
Fully clickable button with changing width

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#1885]
**Describe the bug**
Hi, I want to change the width of the button on the mobile. But when I change the width of the button from CSS it becomes not fully clickable. Is there a way to have the fully-clickable button with charged width on mobile (100% would be great)?

**To Reproduce**
The close I can get: [https://mjml.io/try-it-live/SyBAYeyKL](https://mjml.io/try-it-live/SyBAYeyKL)

**Expected behavior**
Fully clickable button on mobile and desktop version.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.5.1
 - MJML tool used [e.g MJML App]

**Affected email clients (for rendering issues):**
 ALL

**Comment by iRyusa** [comment]
The first version you had was a bit better, target the `td` instead of table and applying background to both `td` & `a` https://mjml.io/try-it-live/HJZZWZJtI any clients that doesn't support media queries won't expand the button, so it's probably the best compromise you can get
