### ISSUE TITLE
Support borderTop, borderBottom, etc... on mjml-image

### ISSUE THREAD

**Issue by osdiab** [mjmlio/mjml#1891]
**Is your feature request related to a problem? Please describe.**
You can set the `border` attribute on `mjml-image`s but you can't set specific ones like `border-top` or `border-bottom`. 

**Describe the solution you'd like**
Add those props to `mjml-image` and probably other elements that also have border support

**Describe alternatives you've considered**
In my case using `mjml-style` is not convenient since I'm making templates that can be used on multiple emails.

**Additional context**
I am using `mjml-react` with TypeScript, so if this gets implemented, that library, plus typings for `mjml` and `mjml-react`, will need to be updated too

**Comment by iRyusa** [comment]
We're not maintainer of typescript definition so you'll have to check with them for that (probably using the allowedattribute so it should be fine)

cc @kmcb777 we should be able to add it for next release

**Comment by osdiab** [comment]
@iRyusa i can add it there, no worries. will do whenever this gets resolved!

**Comment by iRyusa** [comment]
👍 Done and released in 4.8
