### ISSUE TITLE
How to add a circle element with an inner icon image.

### ISSUE THREAD

**Issue by sean-hill** [mjmlio/mjml#1892]
**Is your feature request related to a problem? Please describe.**
I'd like to build an element like this:

![image](https://user-images.githubusercontent.com/1205866/80816138-d3e1f900-8b83-11ea-8294-469dd8e7a80e.png)

**Describe the solution you'd like**
To be able to build an element as seen above.

**Describe alternatives you've considered**
Maybe using the social icon component? But I need a custom icon like a check.

**Comment by ngarnier** [comment]
I suppose that because we're missing the full design you're trying to achive, I've trouble understanding the problem with using a simple image and text like this: https://mjml.io/try-it-live/HJIlR2tF8.

**Comment by iRyusa** [comment]
Border-radius won't work in most old desktop clients, so using an image seems more appropriate here
