### ISSUE TITLE
Error: Cannot find module 'lodash.map' from Cheerio

### ISSUE THREAD

**Issue by hmelenok** [mjmlio/mjml#1895]
**Describe the bug**
Cli and library from npm fails to compile templates from `.mjml` to `.html`
Cannot find module 'lodash.map'

**To Reproduce**
1. `npx mjml ./any-template.mjml -o ./templates/` or `ts-node ./src/email-templates/templates/user-reset-password.ts` or `mjml ./any-template.mjml -o ./templates/`
2. See error

**Expected behavior**
Mjml templates should be converted to html

**MJML environment (please complete the following information):**
 - OS: MacOS 10.15.4
 - MJML Version [e.g. 4.6.2]
 - MJML tool used cli, nodeJS interface from library

**Screenshots**
<img width="796" alt="Screenshot 2020-05-05 at 18 32 41" src="https://user-images.githubusercontent.com/2149114/81084670-dd11f380-8efe-11ea-8caf-1e711798e056.png">
<img width="768" alt="Screenshot 2020-05-05 at 18 32 49" src="https://user-images.githubusercontent.com/2149114/81084668-daaf9980-8efe-11ea-89b7-0330e05f46e2.png">

**Comment by hmelenok** [comment]
Template code: 
```
<mjml>
  <mj-head>
    <mj-font name="Open Sans" href="https://fonts.googleapis.com/css?family=Open+Sans" />
  </mj-head>
  <mj-body background-color="#fafafa">
    <mj-section full-width="full-width" padding-top="30px" padding-bottom="30px">
      <mj-column background-color="#ffffff" width="600px" border-radius="5px" padding-left="7px" padding-right="7px" padding-bottom="55px">
        <!-- Here goes Email body -->
        <mj-image width="120px" src="https://static.shelf.io/images/logo/logo-200-100-3.png" padding-bottom="0" />
        <mj-divider border-width="1px" border-style="solid" border-color="#efefef"  padding-bottom="10px" />
        <!-- Here goes message after logo -->
        <mj-text font-family="Open Sans, Arial" line-height="1.55" >Hello {{user}},<br><br>Someone requested a password change for your account. If it was you, click below to set a new password.</mj-text>
        <mj-button href="{{resetURL}}" target="_blank" background-color="#fa6b30" text-transform="uppercase" font-weight="500" border-radius="0px" height="40px" padding-bottom="24px" padding-top="20px">Reset password</mj-button>
        <mj-text font-family="Open Sans, Arial"> If for some reason the button above doesn't open Shelf, please copy and paste the following link into your browser: {{resetURL}}
        </mj-text>
          <mj-text font-family="Open Sans, Arial">
          If you don’t want to change your password or didn’t request this, just ignore or delete this message.
          </mj-text>
        <!-- Here goes end of Email body -->
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

```

**Comment by iRyusa** [comment]
Can't reproduce on a fresh install, try clear your node modules & reinstall ?

**Comment by hmelenok** [comment]
Reinstall not helped but with mandatory version in npx cmd it's works fine
`npx mjml@4.6.3 ./src/email-templates/templates/user-reset-password.mjml`. Seems something with my dependency folder, probably close it. Sorry for inconvenience.

**Comment by iRyusa** [comment]
Try to remove npm cache then, corrupted install probably 👍
