### ISSUE TITLE
Adding extras fonts and extra styles

### ISSUE THREAD

**Issue by peterfox** [mjmlio/mjml#19]
Doesn't seem to be anything on linking to different styles or how to change any head values in the documentation?

**Comment by iRyusa** [comment]
Hi there !
We didn't provide anything to add some stuff on `head`. Do you have any idea how do you want to

**Comment by iRyusa** [comment]
Hi there !

We didn't provide anything to add some stuff on `head`. Do you have any idea on how it should be written ?

```xml
<mj-head>
  ...
</mj-head>
<mj-body>
  ...
</mj-body>
``` 

Something like this ?

**Comment by iRyusa** [comment]
To go further, why not implement `<mj-font>` and `<mj-style>` what do you think guys ? @arnaudbreton @robink @lohek  @hteumeuleu

**Comment by peterfox** [comment]
Yes, makes sense to me to have both a head <mj-font> component. Doesn't necessarily have to be a head as a lot of email clients actually ignore head regions all together and only use the body portion of a HTML email.

**Comment by robink** [comment]
@iRyusa `mj-head`, `mj-style` and `mj-font` are all making sense to me

**Comment by jsit** [comment]
How would `<mj-font>` work? What's inside that element?

**Comment by peterfox** [comment]
The main concept would be you could provide URLs to import a font easily. But there might be a wider discussion of what else might be needed to be altered to a head element?

**Comment by Chrisedmo** [comment]
Maybe even some kind of default override would be good? Like this: https://github.com/mjmlio/mjml/issues/49#issuecomment-184227380

**Comment by arnaudbreton** [comment]
Hi everyone,

I've described in better details what we could do for fonts (#80), global CSS styling (#81) and head level definition (#82). Closing this issue now. Let's move each discussion in the now dedicated thread.

Thanks everyone for your input to come up with a clean solution!
