### ISSUE TITLE
Create a own component

### ISSUE THREAD

**Issue by tinohager** [mjmlio/mjml#190]
I have try to create a own component after instructions of the documentation. If a example available?

```
mjml --init-component title
```
What then to do with the .js file?

Thanks

**Comment by GuillaumeBadi** [comment]
Hey!

You mean, how to use the component once done, or how to actually write the component ?

**Comment by tinohager** [comment]
It want to know how to use it. What am I supposed to do with the .js file, do i have to copy it in a specified folder or do i have to add an entry in another file to use it?
In short, I need the way from "--init-component title" to "<mj-title>"

**Comment by GuillaumeBadi** [comment]
So, right now you have to create a js file that will `import` your component, then compile your mjml:

``` javascript

import { mjml2html } from 'mjml'
import './MyComponent'
import './MyOtherComponent'

console.log(mjml2html(`
<mj-body>
  <mj-section>
    <mj-column>
      <mj-my-component />
    </mj-column>
  </mj-section>
</mj-body>
`))

```

**Comment by GuillaumeBadi** [comment]
I am closing this one. Feel free to reopen it if it doesn't answer your question
