### ISSUE TITLE
Image container width is wrong when we set body width to 100%

### ISSUE THREAD

**Issue by AGachet** [mjmlio/mjml#1901]
Hi guys, thanks for this amazing lib :)

I found a bug which is blocker for me, I've a template with 100% width (on body), but in this case when I have an image inside, it looks to set the image width to 100px.

You can take a look here: https://mjml.io/try-it-live/rkObzWPqU

I've an issue displaying "Attribute width has invalid value: '100%' for type Unit, only accepts (px, %) units and 1 value(s)" 

Does it mean that we can't use % with a typo inside the error message ? In this case, how could I have a body taking 100% of the width ?

Thanks guys

**Comment by iRyusa** [comment]
You can't set width in percent for mj-body, only px is supported. Dunno why we didn't fix the allowed attributes yet in mj-body to throw a validation error cc @kmcb777
