### ISSUE TITLE
not able to see images in outlook at reciving side

### ISSUE THREAD

**Issue by Vickykumarsingh** [mjmlio/mjml#1906]
I have created one email responsive template using mjml but when i send that template using outlook in a text form then all images part are coming in red cross sign at receiving side in outlook.

I am using url for images but then also they are not visible.

Please can anyone guide on this issue and help me to resolve this issue.

This is code part:
<mj-hero mode="fixed-height" height="334px" background-width="600px" background-url="https://pl8u8gzwojwu79sjassets.blob.core.windows.net/fpwt9kv0c5ge/Hero%20Image/EVA%20Hero%20Image.jpg?sv=2019-02-02&sr=c&sig=jt%2F6hh%2BJv1uXVajLmbeT5hQspwd%2Bd%2B7M2IL3Kg8gZOo%3D&se=2029-11-21T17%3A10%3A12Z&sp=r" padding="0px 0px">

**Comment by iRyusa** [comment]
Which version of Outlook ? Desktop (2003, 2016, ...) , Mobile App, Outlook.Com ? 
It's hard to tell with that few informations. Can you try with a 'dumb' url like `https://via.placeholder.com/300/09f/fff.png` or a template from https://mjml.io/templates to see if it works ? How did you send your email ?

**Comment by iRyusa** [comment]
I'm closing it for now, feel free to reopen
