### ISSUE TITLE
Nested Columns

### ISSUE THREAD

**Issue by JoshuaMapley** [mjmlio/mjml#191]
I'm having a bit of trouble with making sub columns, I'm not sure if this is a feature or not but what i'm trying to do is this:

![demo](https://cloud.githubusercontent.com/assets/17286486/14551613/c4f03e7c-0318-11e6-9306-1b961ac2bff5.jpg)

but when ever i nest a column it deletes it completely, any recommendations of how this should be done or clarification about what's going on would be great, thanks

**Comment by ngarnier** [comment]
Hey @JoshuaMapley, can you please share the mjml code you're using to achieve this?

From what I see you're just trying to have a section with 2 columns, which can be achieved like this: 

```
<mj-section>

  <mj-column>
    <!-- First/Left Column -->
  </mj-column>

  <mj-column>
    <!-- Second/Right Column -->
  </mj-column>

</mj-section>
```

**Comment by ngarnier** [comment]
hey @JoshuaMapley, did it solve your issue? 

I'll suppose it did and will close your issue if I don't have any news by next week.

Cheers!

**Comment by lrae24** [comment]
@ngarnier 

I wanted to know can you have  2 nested columns and use 1 just to act as a border and the other for the content ? 

I have already managed to achieve this but saw that  you document specifies not to use nested columns is there another way around this ??

The aim is similar to the above image in this issue .  
 below is my code:




<mj-column background-color="#f3f6f9" border="1px solid #c3c6c9" width="49%">

  <mj-column  border="10px solid #f3f6f9">

    <mj-table>
      <tr>
        <td></td>
        <td></td>
      </tr>
    </mj-table>

    <mj-text ></mj-text>
    <mj-text ></mj-text>
    <mj-text ></mj-text>
    <mj-text ></mj-text>

  </mj-column>

</mj-column>

**Comment by ngarnier** [comment]
Hi @lrae24, instead of using the column for the border, it's better to use a `wrapper` or a `section`, example here: https://mjml.io/try-it-live/HyJrtjqqg

**Comment by lrae24** [comment]
@ngarnier  ok so currently what you suggested is what i had  but my issue is then that the content i am placing in the column just fits  its almost as if i need inner padding to have the content aligned correctly . Hence i then added the second column to give it that so is there no way to add inner padding or anything ?
![screen shot 2017-03-06 at 12 04 37 pm](https://cloud.githubusercontent.com/assets/25219824/23605462/7f48e2e6-0265-11e7-9134-89e59598a13e.png)

**Comment by ngarnier** [comment]
Why don't you add the padding on the children elements? Like this: https://mjml.io/try-it-live/HyjtHnc9x
