### ISSUE TITLE
border-radius does not apply to mj-column or mj-section border

### ISSUE THREAD

**Issue by zarikadzer** [mjmlio/mjml#1910]
**Bug description**
mj-column and mj-section are not enabled to setup border-radius correctly due to default border-collapse style. 

**How to reproduce**
1. Create a file with this MJML code: 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column background-color="red" border="3px solid black" border-radius="50px">
        <mj-text>Hello world</mj-text>
        <mj-text>Hello world</mj-text>
        <mj-text>Hello world</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
2. Render it to HTML or just open live demo: https://mjml.io/try-it-live/S1qUzaRcU
3. Background has rounded, but border has not.

**Expected behavior**
mj-column/mj-section should be able to have rounded border.

**MJML environment:**
 - MJML Version [any]

**Screenshots**
![image](https://user-images.githubusercontent.com/9337044/82152639-5b5d8680-986b-11ea-8621-484ef4842e44.png)

**Additional**
I guess that the best solution is to allow users decide if they want to use border-collapse attribute for column/section or not.

**Comment by iRyusa** [comment]
`border-collapse` does fix some weird behavior in Outlook so it's here to stay by default. You should use a css-class+inline if you want to override that behavior.

**Comment by zarikadzer** [comment]
@iRyusa, I've tried, but it does not work. 
https://mjml.io/try-it-live/HyRhDjysI
Please, show me an example of how I can set up border radius.

**Comment by iRyusa** [comment]
`mj-class` only target mj-attribute and there's no `style` attribute on mj-column so there's no way it could work like that.
ex: https://mjml.io/try-it-live/H18Og0kj8
