### ISSUE TITLE
<!-- 96 is added before message text

### ISSUE THREAD

**Issue by vladshcherbin** [mjmlio/mjml#1913]
**Describe the bug**
After sending a simple message with 1 word using mjml try it live generated html I received a message starting with `<!-- 96`.

**To Reproduce**
1. Take html output from https://mjml.io/try-it-live/SktrgZeoU
3. Send the HTML to an email address with [Bitrix24 CRM](https://www.bitrix24.eu) (only for crm customers)

**Expected behavior**
The message should not have `<!-- 96`.

**MJML environment (please complete the following information):**
 - OS: macOS
 - MJML Version: 4.5.1
 - MJML tool used: Mjml Try it live

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: [Bitrix24 CRM](https://www.bitrix24.eu)

**Affected email clients (for rendering issues):**
 - Email Client: Gmail
 - OS: macOS
 - Browser: Chrome
 - Email App: AirMail

**Screenshots**

![image](https://user-images.githubusercontent.com/6711845/82218667-ec446880-9924-11ea-9a15-c44bfafec2ec.png)

**Additional context**

Issue exists when using gmail in browser and in AirMail app. I was able to remove `<!--` part by removing `<!-- -->` from `<!--[if !mso]><!-- -->` and below.

Probably related: https://github.com/mjmlio/mjml/issues/1581, https://github.com/mjmlio/mjml/issues/1894

**Comment by vladshcherbin** [comment]
Also happens with latest mjml version (4.6.3) and using generated html from cli.

**Comment by iRyusa** [comment]
Well if your CRM is altering the HTML there's not much we can do about this one, so I'm closing. 
As said in both issues, those are required for to fix some email clients.

**Comment by vladshcherbin** [comment]
@iRyusa maybe you know any hacks to prevent CRM from doing this, like using `\` dash before this section or smth?

**Comment by iRyusa** [comment]
I don't know what they're doing to have something like that, you should reach them first to see why they alter it.

**Comment by vladshcherbin** [comment]
@iRyusa from received email source code I see they change `<!--[if !mso]>` to `&lt;!--` so I believe they encode it, parts between this blocks are partly (but not completely) removed.
