### ISSUE TITLE
Embed Video

### ISSUE THREAD

**Issue by sanazmemar** [mjmlio/mjml#1920]
Hi,
Great work!
Do you have any plan for embed video or music player ?  I can't find anythings about that in your documentation. 
Some brand campaign use that now on their emails. Is it possible you have it too? 
Thank you

**Comment by iRyusa** [comment]
Hi,
As there's no real fallback to embed a video, there's not so much we can do about this : https://www.caniemail.com/features/html-video/

**Comment by emilsedgh** [comment]
Have we considered `<mj-video src="file.mp4" fallback="file.gif" />` ? 

Gif's are super popular in emails.

**Comment by iRyusa** [comment]
I mean there's no real benefit to this as there's no real support for video
tag in email. Just use a mj-image with gif instead and a link to the video
