### ISSUE TITLE
Margin cannot be overwritten

### ISSUE THREAD

**Issue by youjinp** [mjmlio/mjml#1921]
**Describe the bug**
`margin` in `mj-style` is not respected, output html uses `0 auto` regardless.

**To Reproduce**
Simple example:
```html
<mjml>
  <mj-head>
    <mj-style inline="inline">
      .margin { margin: 40px auto; }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-wrapper css-class="margin" background-color="cyan" border="2px solid #000">
      <mj-section>
        <mj-column>
          <mj-text>Hello world</mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

**Actual behavior**
- margin defaults to `0px auto`
```html
<div class="margin" style="background: cyan; background-color: cyan; margin: 0px auto; max-width: 600px;"</div>
```

**Expected behavior**
- margin respects overwrite, `40px auto`
```html
<div class="margin" style="background: cyan; background-color: cyan; margin: 40px auto; max-width: 600px;"</div>
```
**MJML environment (please complete the following information):**
 - OS -- MacOS
 - MJML Version -- 4.6.3
 - MJML tool used -- MJML Live editor, cli

**Comment by iRyusa** [comment]
Add `!important` on properties to override already inlined styles.
