### ISSUE TITLE
Variable issue permalink not enable

### ISSUE THREAD

**Issue by alexiathouvenin** [mjmlio/mjml#1926]
A have a variable which is a Dynamic permalink.
The template is good but when received there is no link, only text : the permalink is disabled :

![image (10)](https://user-images.githubusercontent.com/61704140/83245913-b2cff080-a1a1-11ea-8285-f6f62db088c0.png)

Can you tell me what is wrong in the code or How to activate the permalink ? 
Windows
 - MJML V3

 - Laurent@teeps.co and Alexia@teeps.co
 - OS: Windows]
 - Browser  Chrome]

**Comment by iRyusa** [comment]
Please reach Mailjet support for that. That's not related at all to MJML repository.
