### ISSUE TITLE
Application OUTLOOK 2013 and Other Versions

### ISSUE THREAD

**Issue by RicardoMassocato** [mjmlio/mjml#1927]
At first the error as mentioned in the image below is appearing in the Office Outlook 2013 application and other versions where I was informed. have any solution to solve this "break".

Image attached:
***ERRORS** APP OUTLOOK FOR WINDOWS:
![Capturar01](https://user-images.githubusercontent.com/28220581/83261185-5664d500-a191-11ea-9e7c-8333431e15b5.PNG)
![Capturar02](https://user-images.githubusercontent.com/28220581/83261191-57960200-a191-11ea-9651-12be27e72905.PNG)

***CORRECT** BROWSERS:
![Capturar03](https://user-images.githubusercontent.com/28220581/83261192-582e9880-a191-11ea-8fea-1437c103e4cf.PNG)
![Capturar04](https://user-images.githubusercontent.com/28220581/83261196-58c72f00-a191-11ea-95e8-18943277262d.PNG)

**Code attached MJML / HTML:**
*Campanhas.zip
[Campanhas.zip](https://github.com/mjmlio/mjml/files/4701817/Campanhas.zip)

**Comment by iRyusa** [comment]
Well it's known issue with large image on outlook, just resize them to the desired width and it shouldn't overflow anymore

**Comment by iRyusa** [comment]
Feel free to reopen if it doesn't fix your issue
