### ISSUE TITLE
Columns are always in one line in Outlook

### ISSUE THREAD

**Issue by fantkolja** [mjmlio/mjml#1928]
**Describe the bug**
When I create the following template, where total columns widths exceed the section with (https://mjml.io/try-it-live/Sk54GFCsL) the columns are wraped in the mjml viewer and some enail clients, but in the Outlook they are displayed all in one line (nowrap)

**To Reproduce**
1. Create a file with this MJML code: https://mjml.io/try-it-live/Sk54GFCsL
2. Send the compiled template.
3. Open it in Outlook

**Expected behavior**
The columns should wrap like in the viewer

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.5.1
 - MJML tool used (MJML App)

**Email sending environment(for rendering issues)**:
 - Platform used to send the email (https://putsmail.com/)

**Affected email clients (for rendering issues):**
 - Outlook

**Screenshots**
https://prnt.sc/sq2wje
https://prnt.sc/sq2wq1

**Comment by iRyusa** [comment]
Well you can't have more than 100% of content (body's width / 600px by default) into a section, so that's the intended behavior here. Just wrap your columns into a new section.

**Comment by rlemasquerier** [comment]
I could workaround this by using a `mj-wrapper` instead of `mj-section` to embbed my different `mj-column`

**Comment by iRyusa** [comment]
Mj-wrapper is already a mj-section, it just override how children are wrapped to allow multiple section @rlemasquerier that has nothing to do with the original issue ?

**Comment by rlemasquerier** [comment]
Hello @iRyusa , thanks for your feedback :)

Maybe I misunderstood the original issue... 

But I had the exact same problem on outlook windows client only (on other clients, my 3 columns were wrapped correctly), and using a wrapper instead of a section fixed that behaviour on outlook while keeping other clients working the same way. Do you have any idea why?

I'd be glad to give more details and code snippets if you are interested?

**Comment by iRyusa** [comment]
Yup without code snippets it's hard to see what could go wrong, but it's most likely the same issue sum of columns width exceed section size
