### ISSUE TITLE
Ability to add raw HTML to head from BodyComponent

### ISSUE THREAD

**Issue by verbeeksteven** [mjmlio/mjml#1929]
**Is your feature request related to a problem? Please describe.**

I have a custom package https://github.com/HAWK-Marketing/mjml-image-hover that needs to add styles and an mso conditional style to the head. I do not seem to be able to from a BodyComponent, only from a HeadComponent.

**Describe the solution you'd like**

A render function or something that would allow me to add raw styles and html to the head from a BodyComponent.

**Describe alternatives you've considered**

At the moment I use two components, one to add the mso/styles and one to add the actual body html.

**Additional context**

If I am missing something do let me know, I took a look around and could not find anything that would work.

**Comment by iRyusa** [comment]
Well, you can push headStyle directly from component directly ex: https://github.com/mjmlio/mjml/blob/454584ac7bdd555d07a9ee68eac514067e585368/packages/mjml-accordion/src/Accordion.js#L37 but you can't push "raw" block into head. 

Let's just add an helper to push raw stuff @kmcb777 as we've done for head style ?

**Comment by verbeeksteven** [comment]
Ya I was able to successfully push all the styles I needed. But sadly I also need a mso wrapped <style></style> added. And I didn't see anyway of doing that.

**Comment by iRyusa** [comment]
A bad hack would be to close and open a new style block 
```js  
headStyle = () => {
  return `
    </style>
     <!-- mso conditionnal -->
     <style>...</style>
     <!-- end mso -->
     <style type="text/css">
  `
}
```

That would work until a `headRaw` helper exists

**Comment by iRyusa** [comment]
This has been released for a while now I'm closing
