### ISSUE TITLE
Add vk to mj-social

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#193]
Please, add vk to `mj-social`. VK.COM is very popular social media and many people will be use it.
You can use this icon https://www.iconfinder.com/icons/386743/kontakt_v_kontakte_vk_vkontakte_icon#size=128

**Comment by iRyusa** [comment]
Hi ! 
Just for a follow up @liminspace , i've added a way to add custom social network on mj-social : 

```
<mj-social display="facebook awesome-network"
    awesome-network-content="Share on a awesome network"
    awesome-network-href="http://awesome-network.com/my-company"
    awesome-network-icon-color="#FF00FF"
    awesome-network-icon="http://myicon.png" />
```
So when #222 will be merged you will be able to add vk.com to your emails !
