### ISSUE TITLE
Alignment for mj-group

### ISSUE THREAD

**Issue by emilsedgh** [mjmlio/mjml#1936]
**Is your feature request related to a problem? Please describe.**
It's impossible to align columns (and their content) inside a `mj-group`

**Describe the solution you'd like**
Implementing `align` on `mj-group` would allow it

**Describe alternatives you've considered**
You can workaround this using css.

**Additional context**
Here is an example:

![Screenshot_20200606_212250](https://user-images.githubusercontent.com/120439/83960275-e4992500-a83b-11ea-9764-c1cd41bb3399.png)

The red area is a `mj-group` which is always set to `text-align: left`.
Each button in here is a `mj-column`.
I would like to be able to change `mj-group`'s `text-align`.

If you guys are OK with this I can provide a MR.

**Comment by iRyusa** [comment]
I think you just have to align it's content here. As column take full group size anyway there's no need to align anything ? Just add an align right to your second mj button and you should be fine
