### ISSUE TITLE
html empty-element tags show error in UI

### ISSUE THREAD

**Issue by wparad** [mjmlio/mjml#1945]
**Describe the bug**
Editor incorrectly doesn't understand tags that don't require to be closed.

`<link>` `<meta> `\<hr>` `\<br>`

all suggest that there need to be a `</>` somewhere.

**To Reproduce**
[Example here](https://mjml.io/try-it-live/HJiMDC_6I)

```html
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-raw><br></mj-raw>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

![image](https://user-images.githubusercontent.com/5056218/85017531-e8964280-b16b-11ea-8d70-83ca8659beca.png)

**Expected behavior**
No error to be seen here

**Comment by iRyusa** [comment]
Well that's because Codemirror as XML to highlight the syntax, and as input aren't really valid XML input it highlights as a syntax error, but there's not so much we can do about this.

**Comment by wparad** [comment]
@iRyusa that's probably the worst support I have every seen anyone give. There is lots that you can do, you are do choosing to do nothing. Blaming it on a implementation detail of the project that assumes dependencies doesn't translate for users.

The same problem exists in the HTML section:

![image](https://user-images.githubusercontent.com/5056218/85021188-cdc6cc80-b171-11ea-902c-9cd8ee44ead5.png)

**Comment by iRyusa** [comment]
> @iRyusa that's probably the worst support I have every seen anyone give.

🤷 

Well there's not so much we can do about this, and it's only a "try it live" not an every-day tool that you should use. `vscode` extension have better highlight support & features.
