### ISSUE TITLE
Create webstorm plugin

### ISSUE THREAD

**Issue by AdityaAnand1** [mjmlio/mjml#1951]
🤓 ❤️

**Comment by iRyusa** [comment]
That's not really into our scope as said here #53 it takes a lot of bandwith to maintain such plugin. 

So I'm closing it like

**Comment by AdityaAnand1** [comment]
It's unfortunate to see that in 4 years since that issue, a tiny bit of bandwidth couldn't be found :( Though I doubt it'd be that much different than maintaining VS code/Atom etc. plugins, hell it'd probably just be a small weekend project to get up and running.

I hope mailjet can reconsider because this would be amazingly useful to the Jetbrains community 😁 

Any thoughts?  @kmcb777 @loeck @ngarnier

**Comment by iRyusa** [comment]
We're not really focusing much on Atom (broken for now), only VScode plugin has been forked from community one to update MJML version.

> hell it'd probably just be a small weekend project to get up and running.

Then feel free to start it as an open source project, people would contribute.

It's not really Mailjet call at this point, we'd rather finish 4.7 & other features than adding another plugin that we need to find time to support.

**Comment by IanEdington** [comment]
@AdityaAnand1 have you figured out any ways to set up Intellij with mjml? I've figured out a few things but I'm interested in your solutions

https://github.com/mjmlio/mjml/issues/53#issuecomment-687646528
