### ISSUE TITLE
Outlook-Styles do not work

### ISSUE THREAD

**Issue by lepako** [mjmlio/mjml#1954]
Hi everyone :)
Right now I try to build an E-Mail Template with MJML.
When using the following Code:

`<mjml>
 
    <mj-head>
            <mj-style inline="inline">
                .section {
                      background-color: #FFFFFF;
                }
             </mj-style>
    </mj-head>
 
    <mj-body background-color="#000000">
      
         <mj-section css-class="section">
            <mj-column>
              <mj-text>test</mj-text>
             </mj-column>       
          </mj-section>
 
 
    </mj-body>
 
</mjml>`

I'm facing the issue that the styling is working except in Outlook.
Are there known issues using <mj-styles> with outlook?
It works with mj-class. But I would preffer css-class.

**Comment by iRyusa** [comment]
You shouldn't use a css class for that as `mj-section` does support `background-color` here. `background-color`  is applied on `div` here, as Outlook doesn't support `background-color` on `div` it won't show up.
