### ISSUE TITLE
Allow not defaulting MjmlText color

### ISSUE THREAD

**Issue by osdiab** [mjmlio/mjml#1955]
**Is your feature request related to a problem? Please describe.**
I have two "themes" in my emails, which I want to toggle on and off based on the presence of a CSS class - a dark and a light theme.

In the dark theme, all text should be light. In the light theme, all the text should be dark.

But `MjmlText` defaults the `color` CSS rule to `#000000`. Unfortunately since it uses the `color` type from `mjml-core` which uses regexes to detect hex codes and such, it also disables the potential for passing `inherit` as the value. so, I cant disable this functionality.

**Describe the solution you'd like**
Either a) allow passing `inherit` as the value to `MjmlText` assuming that's well supported or b) allow disabling the setting of `color` altogether, neither of which would be backwards-incompatible

**Comment by iRyusa** [comment]
You can just ignore the validating message here ?

**Comment by osdiab** [comment]
I'm preferring to use strict mode as part of my testing, I don't want to have to give up validation of my entire project just so that I can deal with one missing part of this library. I'd be happy to add a PR, but which of my suggestions if either would you like?

**Comment by iRyusa** [comment]
Then you can open a PR here : https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/types/helpers/colors.js adding inherit.

mj-all doesn't validate the attribute type, so if you pass color on it it won't be listed as an error for now.

For compatibility issue you should still use inline styles over class to maximize support.

**Comment by iRyusa** [comment]
Inherti is now supported for every color attribute since 4.10.2 !
