### ISSUE TITLE
Switch Image for different viewports

### ISSUE THREAD

**Issue by TaRudeOne** [mjmlio/mjml#1956]
Hi, 
is there meanwhile a solution for switching images in different viewports?

**Comment by iRyusa** [comment]
Current beta should support https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images srcset + sizes, even if the support isn't really great that could be a start. You can still hide/display image with media queries & add a special outlook style block to handle that particular case
