### ISSUE TITLE
Generated HTML tags sometimes being split over multiple lines by email clients

### ISSUE THREAD

**Issue by chrisbeldam** [mjmlio/mjml#1959]
I currently have a the following gulp task to turn MJML into HTML.

```
gulp.task('emails', function () {
    return gulp.src(['./scion/templates/email/mjml/**/*.mjml', '!./scion/templates/email/mjml/components/*.mjml'])
        .pipe(mjml(mjmlEngine, {beautify: true, minify: true}))
        .on('error', handleMJMLErrors)
        .pipe(gulp.dest("./scion/templates/email/mjml"));
});
```

It returns me the expected HTML and everything is condensed into 1 line 
![image](https://user-images.githubusercontent.com/22501792/86222172-c9d97800-bb7d-11ea-9e72-d5439079222f.png)

However, this seems to cause issues with email clients. If a line of HTML reaches a certain length (can't determine exactly what the exact length is), Gmail attempts to split the HTML onto a new line.

![image](https://user-images.githubusercontent.com/22501792/86222269-ebd2fa80-bb7d-11ea-9875-17de64237492.png)

If this happens, you can issues like the following where the closing strong tag seems to escaped or incorrectly rendered due to the split occurring inside a HTML tag:

![image](https://user-images.githubusercontent.com/22501792/86222310-f7bebc80-bb7d-11ea-8b8c-4a9ecccf20a2.png)

Is there any easy fix to this from the MJML side? e.g. drop minfiy? 

The MJML for the broken strong tag is as follows: (expiry_date being a variable passed by Jinja2 and trans tags being part of our i18n markup )

```
            <mj-text align="center">
              {% trans trimmed expiry_date = select_link.expires_at | format_date %} Your credit will expire on <strong>{{ expiry_date }}.</strong> {% endtrans %}
            </mj-text>
```

Currently this issue with gmail and other email clients seems to break my strong tag and therefore breaks the email! Any advice on this would be appreciated

**Comment by iRyusa** [comment]
Never saw that behavior but you can pass some extra config to minifier (minifyOptions on mjml2html) we use this one : https://github.com/kangax/html-minifier `maxLineLength`

**Comment by chrisbeldam** [comment]
Thanks, will give this a go!

**Comment by chrisbeldam** [comment]
Removing Minify and or adding the maxLineLength works fine and stops this being cut. As per my comment on https://github.com/mjmlio/mjml/issues/1960, it may well be worth adding a warning to the docs about minify and the possibility of this happening.
