### ISSUE TITLE
allow mjml-section to have a width

### ISSUE THREAD

**Issue by osdiab** [mjmlio/mjml#1962]
**Is your feature request related to a problem? Please describe.**
mjml-group, mjml-column and so on can have explicit widths provided, but mjml-section cannot. This is frustrating since I made a layout that looks like a "card" using mjml-section and mjml-wrapper, but don't have a way to constrain how wide that card will go. coupled with #1961 , I'm having a lot of trouble achieving the design I'd like.

**Describe the solution you'd like**
I want to be able to make a section have a max width and be centered if it would grow bigger than that. I have a standardized padding that this card-looking section applies to all content, and i don't particularly want to have to duplicate and synchronize those paddings onto all of the mjml-group and mjml-column instances inside of the section.

**Comment by iRyusa** [comment]
Column support padding and inner background now that should be enough to do what you want ? Can you share a screenshot of what you want to do ?

Section are just "line of content" inside the email, if we support width then the ghost table for outlook might mis-align comparing to the browser / phone version

**Comment by iRyusa** [comment]
Feel free to reopen with more details, i'm closing for now
