### ISSUE TITLE
Background images working with mj-wrapper, but not with mj-hero on Outlook 2007 - 2016, 365

### ISSUE THREAD

**Issue by pmartiner** [mjmlio/mjml#1963]
**Describe the bug**
While testing my template on Litmus, I couldn't make the `mj-hero` component with background images work in Outlook 2007, 2010, 2013, 2016 and 365 on Windows. The image doesn't show. 

![imagen](https://user-images.githubusercontent.com/25936810/86387893-776d8980-bc59-11ea-92cc-74dc6cfd9a7d.png)

Yet, while testing the background images with the `mj-wrapper` component, it did work.

![imagen](https://user-images.githubusercontent.com/25936810/86388025-a7b52800-bc59-11ea-9094-e0b1bdaaf0a0.png)
(neither of those worked on the new Win 10 app)

Here's the code I used for both cases:
Hero component:
```html
<mjml>
  <mj-head>
    <mj-breakpoint width='530px' />
    <mj-attributes>
      ...
      <mj-class
        name='hero-background-image'
        background-url='https://cloud.githubusercontent.com/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg'
        background-size='cover'
        background-repeat='no-repeat'
        background-color='#6d9ebf'
        border-bottom='solid 5px #22B14C'
        padding='20px'
        mode='fixed-height'
        background-height='120px'
        height='120px'
      />
      ...
    </mj-attributes> 
  </mj-head>
  <mj-body>
    ...
    <mj-raw>
      <!-- Hero Image -->
    </mj-raw>
    <mj-hero mj-class='hero-background-image'>
          <mj-text mj-class='hero-text hero-header'>
            Welcome to <strong>ACME Next</strong>
          </mj-text>
          <mj-text mj-class='hero-text'>
            The easiest way to get a mortgage.
          </mj-text>
    </mj-hero>
    ...
</mj-body>
</mjml>
```

Wrapper component: 
```html
<mjml>
  <mj-head>
    <mj-breakpoint width='530px' />
    <mj-attributes>
      ...
      <mj-class
        name='hero-background-image'
        background-url='https://cloud.githubusercontent.com/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg'
        background-size='cover'
        background-repeat='repeat-y no-repeat'
        background-color='#6d9ebf'
        border-bottom='solid 5px #22B14C'
        padding='20px'
        mode='fixed-height'
        background-height='120px'
        height='110px'
      />
      ...
    </mj-attributes> 
  </mj-head>
  <mj-body>
    ...
    <mj-raw>
      <!-- Hero Image -->
    </mj-raw>
    <mj-wrapper mj-class='hero-background-image'>
      <mj-section>
        <mj-column>
          <mj-text mj-class='hero-text hero-header'>
            Welcome to <strong>ACME Next</strong>
          </mj-text>
          <mj-text mj-class='hero-text'>
            The easiest way to get a mortgage.
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
 ...
</mj-body>
</mjml>
```

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2. Render it to HTML by doing '...'
3. Send the HTML to an email address with '...'

**Expected behavior**
Both background images should render on Outlook clients.

**MJML environment (please complete the following information):**
 - OS: Win10
 - MJML Version: 4.6.4
 - MJML tool used: VS Code

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Gmail through mailjet.com 

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2007, 2010, 2013, 2016 and 365
 - OS: Windows 10

**Comment by iRyusa** [comment]
I think you're just missing `background-width` here can you try it again with it ?

**Comment by pmartiner** [comment]
Thank you very much 💯 ! It worked perfectly (even on the Win10 app).
![image](https://user-images.githubusercontent.com/25936810/86489106-e1a12f80-bd28-11ea-82f9-0311c56380ec.png)

I don't if I missed it, but maybe a warning regarding the background-width could be added to the docs? :)
So people like I don't miss it. Thank you again!
