### ISSUE TITLE
background image no-repeat not working in outlook

### ISSUE THREAD

**Issue by vaishnavi-accountbox** [mjmlio/mjml#1964]
Hi MjMl Team,

Facing issue with section background images in outlook. background image with no-repeat is not working as expected in outlook, but works fine with other clients.

ref: https://snipboard.io/mqFyaR.jpg  -gmail client, https://snipboard.io/YLckgm.jpg - outlook client

**Comment by iRyusa** [comment]
It's not supported in Outlook so there's nothing we can do about this. You can still use background hero with a fixed background width/height
