### ISSUE TITLE
mj-social shows default icons inside mj-container, ignores mj-social-elements

### ISSUE THREAD

**Issue by jHards** [mjmlio/mjml#1965]
**Describe the bug**
mj-social shows default icons inside mj-container, ignores mj-social-elements. Remove mj-container and mj-social-elements are recognisied. Behaviour same on [web editor](https://mjml.io/try-it-live) and VS Code plugin

**To Reproduce**
1. Create a file with this MJML code: `<mjml><mj-body><mj-container><mj-section><mj-column><mj-social><mj-social-element name="twitter" href="https://twitter.com" /></mj-social></mj-column></mj-section></mj-container></mj-body></mjml>`
2. Render it to HTML by using the [web editor](https://mjml.io/try-it-live)
3. See the 3 

**Expected behavior**
I would expect that the inclusion of container tags would not affect this?

**MJML environment (please complete the following information):**
 - OS: [e.g. Windows Version 10.0.18362 Build 18362]
 - MJML Version [e.g. 4.6.3]
 - [MJML web editor](https://mjml.io/try-it-live)

**Comment by iRyusa** [comment]
`mj-container` doesn't exist anymore if you add a `mj-container` it will think that you have a mjml v3 input so it will convert it as v4 (so social-element didn't exist back then they are not ported back)

**Comment by jHards** [comment]
Thanks for the prompt response!

**Comment by jHards** [comment]
> `mj-container` doesn't exist anymore if you add a `mj-container` it will think that you have a mjml v3 input so it will convert it as v4 (so social-element didn't exist back then they are not ported back)

Thanks for the prompt response!
