### ISSUE TITLE
zsh: command not found: mjml

### ISSUE THREAD

**Issue by drewbaker** [mjmlio/mjml#1966]
**Describe the bug**
I created an empty directory. Added a `package.json` file with contents of `{}`. Then I installed mjml using: 
```
npm install mjml
```

That made my `package.json` file look like this:

```
{
  "dependencies": {
    "mjml": "^4.6.3"
  }
}
```

I then made a basic test template, that looks fine in Atom Preview, then I run: 

```
mjml templates/invite.mjml -o
```

But I get this error:
```
zsh: command not found: mjml
```

**MJML environment (please complete the following information):**

I'm on Mac OSX `10.15.3 (19D76)` and I'm pretty sure the problem is that with this version of OSX (Catalina) they don't use bash by default, the use zsh.

The contents of my `.zshrc` file is:

```
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```

**Comment by iRyusa** [comment]
That's nothing to do with zsh it's just that local binary aren't in your path. Npm ships with npx now, so `npx mjml` will works as expected

**Comment by drewbaker** [comment]
Yes! `npx mjml templates/invite.mjml -o` worked great! Thank you. Might be worth adding that to documentation.

**Comment by drewbaker** [comment]
BTW, thanks so much for MJML. Super good idea and I've been loving using it. Way better than the alternatives. 

You should include a basic webserver in it so you can just preview it in a browser with hot reloaded. Also, would be great if you could enable it to work with handlebars.js and associated data in someway.

**Comment by iRyusa** [comment]
That can be done using other OSS software like gulp so that's why we don't include all of those feature in MJML. We already have a lot to do in current scope :)
