### ISSUE TITLE
improve some language in mj-hero docs

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1967]
**Describe the bug**

File mjml-hero/README.md opens text with four `<aside>` tags, the third of which reads,

>For better result we encourage you to use a background image width equal to the hero container width and always specify a fallback background color, in case the user email client does not support background images.

**To Reproduce**
Read documentation > Standard Body components > mj-hero > third `<aside>`

**Expected behavior**

The sentence could better read,

>For all uses of "mj-hero", it's best to set attribute "background-width" to the "mj-hero" container width and to specify a "background-color" (for use only on the few clients that don't support "background-url").

**Additional context**

Documentation only. No changes to any JavaScript file.

**Comment by iRyusa** [comment]
I think both have a different purpose here, we recommend the image width to have the same width as body's width, but both background height & width attributes are mandatory

**Comment by GarryFlemings** [comment]
True. Maybe ...

>For all uses of "mj-hero", it's best to (1) set attribute "background-width" to the "mj-hero" container width and (2) specify a "background-color" (for use only on the few clients that don't support "background-url").

**Comment by GarryFlemings** [comment]
True. How about additional change the first aside from,

> The height attribute is required only for the fixed-height mode

to

> For "mode="fixed-height", both "background-height" and "background-width" are necessary.

**Comment by iRyusa** [comment]
background width & height aren't really tied to mode, it's required everytime. `fixed-height` mode need an height to be working or there's no point to have a fixed ... height 😄

**Comment by HansUXdev** [comment]
I'm trying to get more involved with this awesome community so if anyone wants to assign this to me or the other documentation issues feel free. I plan to submit a PR this weekend for some of the other documentation issues and maybe mention that it takes a mobile-first approach and is built on top of react components.

**Comment by GarryFlemings** [comment]
@HansUXdev : You're right about the awesome community part. Friendly. Patient. Expert. The team is skilled at creating code that "does one thing and does it well". And with few resources and lots of community support. Their scope (my opinion only, this isn't formal) is the MJML language, transpilation to HTML, and the current (and changing) state of email clients. Not adding support for dynamic content (say, Handlebars and its competitors), though making it easy for them to interface with MJML is important. They keep their documentation sparse; they don't have the resources to support yet-another-explanation-of-CSS, for example. Wise.

To contribute, maybe wait for the inevitable suggestions in the Slack community about additions and changes to documentation.  Or recognize on your own which problems people have there are affected by documentation or could be. Before you put the time into preparing a formal PR, maybe DM iRyusa (maybe both of us). The feedback will help both you and me. Then, you can confidently do the PR.

Glad to see your offer of help! I look forward to working with you. Best of luck. 🍀
