### ISSUE TITLE
Full width mj-button

### ISSUE THREAD

**Issue by SimonFricker** [mjmlio/mjml#1968]
Is it possible to make the `mj-button` take up  the full width of the `mj-column`?

**Comment by kmcb777** [comment]
Yes you can set its width to `100%`
Note that when the width is set in percent, only the inner-padding will be clickable

**Comment by SimonFricker** [comment]
@kmcb777 thanks for the comment. 

I used the following solution to make the entire div/link clickable. 

```

<mj-style>
    .btn-block a {
        display: block !important;
    }
</mj-style>

<mj-section background-color="#ffffff" padding-top="36px" padding-bottom="0">
    <mj-column width="100%">
        <mj-button href="www.google.com" css-class="btn-block" padding="0" line-height="32px" border-radius="0" width="100%" background-color="red" color="white">
            Button text
        </mj-button>
    </mj-column>
</mj-section>

```

Although I understand and accept that there are some compatibility issues.

**Comment by maximbashevoy** [comment]
@SimonFricker thank you for the solution, works great! For me the clickable area does not extend all the way to the div borders, just inside the link area itself (blue rectangle below), which is still better than before: 

![Screenshot 2021-06-24 at 10 36 11](https://user-images.githubusercontent.com/1901826/123240272-14af7680-d4d8-11eb-9a08-ccff837b69c5.png)

```

Is it different for you? I also can't adjust the padding on the mj-column.

Full code:
<mjml>
  <mj-head>
    <mj-style> .btn-block a { display: block !important; } </mj-style>
  </mj-head>
  <mj-body>
    <mj-section background-color="#ffffff" padding-top="36px" padding-bottom="0">
      <mj-column width="100%">
        <mj-button href="www.google.com" css-class="btn-block" padding="0" line-height="32px" border-radius="0" width="100%" background-color="red" color="white"> Button text </mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
