### ISSUE TITLE
word-break declaration breaking table layouts on mobile

### ISSUE THREAD

**Issue by gad2103** [mjmlio/mjml#197]
`<td style="word-break:break-word;font-size:0;padding:10px 25px;" align="left">`

this seems to cause the table headers to pile up at small resolutions and removing it fixes the problem. however, its generated by default when the template is compiled. please consider making it optional.

here is an image of the problem

![img_0323](https://cloud.githubusercontent.com/assets/1045265/14748584/711127ec-0888-11e6-93aa-a6cd5b564e17.jpg)

**Comment by Kerumen** [comment]
Hello, I just stumbled upon this issue today. Is there a particular reason to include `word-break: break-word` in the rendered HTML?

**Comment by iRyusa** [comment]
Hi there, 

If we remove it, table will expand and email will have horizontal scrolling. `MJ-table` should be used wisely if you want a good results on mobile

**Comment by Kerumen** [comment]
@iRyusa Even if the container width is fixed? (600px)

**Comment by iRyusa** [comment]
`mj-container`'s width is only used for the desktop version

**Comment by iRyusa** [comment]
I'm closing this because it's more a regular CSS/HTML behavior than a bug.

Feel free to reopen if needed
