### ISSUE TITLE
<mj-spacer> rendering issues on Outlook

### ISSUE THREAD

**Issue by przemas666** [mjmlio/mjml#1971]
I've found issue with mj-spacer element - it looks much bigger on Outlook email clients than has been set in code.
For example - i set up spacer to 3 px height, Outlook has rendered it as twice bigger or more.

Affects Outlook 2007 Win, 2010 Win, 2013 Win, 2016 Win, Outlook 2019 Win, Outlook Office 365 Win.

Please find attached screens.
![outlook](https://user-images.githubusercontent.com/51823576/86932490-bc059300-c139-11ea-9bb3-976e193e15e2.jpg)
![mjml-live](https://user-images.githubusercontent.com/51823576/86932507-c162dd80-c139-11ea-89c9-962597ce5f42.png)

Is there any way to to get this working properly on Outlook clients?

**Comment by iRyusa** [comment]
Most likely an issue where the line-height of nbsp is still set somehow can you try add a line-height 0 & font-size 0 to the div ?

We've never really tested such low value for spacer, imo it's a non-sense to use it for such low value as any element in column would support padding anyway

**Comment by Pharmasolin** [comment]
@iRyusa it can be that outlook started multiplying spacer in conditional tag + in div? Because of this bug I don't use mjml-spacer too, I use this for spacing: https://www.goodemailcode.com/email-code/spacing

**Comment by iRyusa** [comment]
When you apply a css reset on that particular tag it works as intended, but I don't think you should really use spacer for that purpose for such a low value, padding is way more reliable

**Comment by Pharmasolin** [comment]
@iRyusa I made some tests in PR #2123 it clearly was broken (same might be with mjml-divider, will check later, and I see there is pending PR with alignment enhancement for mjml-divider).
