### ISSUE TITLE
mj-body background-color not applied in ms mail app

### ISSUE THREAD

**Issue by unktomi** [mjmlio/mjml#1973]
**Describe the bug**
mj-body background-color attribute is assigned. The message has the color in clients except for ms mail app which is white.

**To Reproduce**
See above
**Expected behavior**
The background-color instead of white

**MJML environment (please complete the following information):**
MacOS

**Email sending environment(for rendering issues)**:
Mailjet passport

**Affected email clients (for rendering issues):**
MS Mail
Windows

**Screenshots**
Surely not necessary in this case

**Additional context**

**Comment by iRyusa** [comment]
Well that client isn't really in our test scope it might just not support background color on div/body and there's not so much we can do about this. 

What you can try is using a mj-wrapper and add background color on this one to see if it renders it.

**Comment by MaxMediaPictures** [comment]
Hi, I am actually struggling with the same issue :)

The mj-wrapper workaround actually helps to solve the background color issue, however, then I can't use wrappers elsewhere in the template. In my case I would like to have a dark background with a white centered wrapper where content (sections) is placed. 

It would be great if you could nest wrappers. Could this be possible?

**Comment by iRyusa** [comment]
If you really need to target this specific client you can just surround it with a table (with mj-raw) see more here : https://github.com/mjmlio/mjml/issues/572#issuecomment-283968017

Windows Live Mail is worst than outlook in CSS support so either you mj-raw the solution given in the comment or just ignore this background for this client
