### ISSUE TITLE
Show the html converted code from mjml in outlook

### ISSUE THREAD

**Issue by oHappy** [mjmlio/mjml#1974]
Hello everybody,

i have a problem. I used the a template for testing
https://mjml.io/try-it-live/templates/happy-new-year

There I changed the code and viewed the code in html. By the way, whats minify html?
So i took the html code an posted it in outlook as txt. I've got my goal, but without actions in outlook.
See the attachment. The pictures should be changed by itself and I insert a carousel effect. In Outlook there only show up one picture without the option to change the picture by arrows. 

What did I wrong.
Sorry, I'm new at this and hope you can help me out.

Thank you and best regards,
oHappy
![HMLT1](https://user-images.githubusercontent.com/68100179/87126175-0c8d0580-c28c-11ea-95d5-d7eda36397d9.png)

**Comment by iRyusa** [comment]
Outlook doesn't support click interaction so it will fallback to a simple image. You should use https://putsmail.com/ to send test email instead of outlook.
