### ISSUE TITLE
<mj-image> width is not respected in mobile web view of Outlook.com

### ISSUE THREAD

**Issue by muratari** [mjmlio/mjml#1975]
\<mj-image\> width is not respected in mobile web view of Outlook.com. It might be related to #1422 , but I'm not sure if it is the same problem.

  **Reproduction Steps:**

1. Go to https://mjml.io/try-it-live
2. Paste mjml below: 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="https://mjml.io/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
  
3. Select "Minify Html" and send it to outlook.com-domained email.
4. Open Chrome on Android phone
5. Go to Outlook.com, login and open that e-mail.

  **Expected behavior:**

Image should be in given width, like this (gmail mobile web view):

![Screenshot_20200710-153235_Chrome](https://user-images.githubusercontent.com/4509001/87155667-061a8000-c2c4-11ea-9d55-d7690413f587.jpg)

  **Observed behavior:**

Image has 100% width.

![Screenshot_20200710-153027_Chrome](https://user-images.githubusercontent.com/4509001/87155684-12064200-c2c4-11ea-990f-f5aa0fe343d9.jpg)

  **MJML version:**

I am guessing it is the latest, because we are using https://mjml.io/try-it-live

  **Email clients the bug is seen on:**

Samsung S9 Plus phone + Chrome browser + Outlook.com webpage. I didn't try any other phone.

**Comment by iRyusa** [comment]
I'm not really sure how we could fix it, and mobile version of Outlook.com isn't in our test scope. It clearly doesn't respect any width defined in 2 places (width html attributes, td width). I've tried to add a max-width to the image and it does the same.

Feel free to open a PR if you find a successful fix, but I'm guessing it would be hard without breaking other clients.

New Outlook.com has some shady media queries with `!important` so it's really hard to override some of their behavior

**Comment by muratari** [comment]
Okay, thanks. 

We kind of have a workaround, but it is not generic-enough for mj-image, so I'm guessing it doesn't have PR-grade quality. But it might be enough for other people, so I'm posting it below. Height must be given for this to work.

```
<mjml>
  <mj-head>
    <mj-style inline="inline">
      .of-contain img {
        object-fit: contain;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" height="32px" src="https://mjml.io/assets/img/logo-small.png" css-class="of-contain"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
👍  I'm closing then
