### ISSUE TITLE
How can I add gutters between two columns with a shadow

### ISSUE THREAD

**Issue by melchiorEcotree** [mjmlio/mjml#1976]
Hi, I'm trying to add a gutter between the two cards, any idea on how to do it ?
https://mjml.io/try-it-live/BkHxSzckw

**Comment by iRyusa** [comment]
mj-column supports padding, if you tweak a bit the selector it behave as you want https://mjml.io/try-it-live/SJBO_zcyD

**Comment by melchiorEcotree** [comment]
Thanks a lot Maxime, it works perfectly
--

Melchior Quennec
*Marketing Digital*
m: +33 6 81 13 92 79
w: ecotree.green  e:  melchior@ecotree.fr
<https://www.facebook.com/EcoTree/>
<https://twitter.com/ecotree_contact>
<https://www.linkedin.com/company/ecotree/>
<https://www.instagram.com/ecotree.fr/>
