### ISSUE TITLE
Is there a repository for templates in https://mjml.io/templates ?

### ISSUE THREAD

**Issue by willhertz** [mjmlio/mjml#1979]
Many if not all templates in https://mjml.io/templates
are made for probably an older version of MJML and are

1) Throwing invalid attribute errors every 3 or 4th line of markup (at least on desktop app (Windows/ MJML App 3.0.2/MJML V^4.6.2) , in VSCode no errors are shown.

2) Using in-line styles for each and every element. 
That clutters the markup and doesn't take advantage from classes and attributes.  Making them hard to read and edit, and IMHO might scare away potential new users. Because visually are great, but the code doesn't make justice to the advantages of MJML and are less appealing.

I would like to know if there's a repository where community can refactor them (I'have already tried a couple with very good results)

I don't know how "kosher" might be to upload the refactored ones directly from the submit option in the page. 
Might create confussion? because visually will be duplicates  Some copyright (or copyleft) issues?

**Comment by iRyusa** [comment]
We have a repo for those, but I don't know if the site has a mechanism to pull them directly from it, I believe they are hard coded in a db somewhere.

Idk how we should handle this @ngarnier

**Comment by ngarnier** [comment]
Definitely, appreciate the help @willhertz! Here's the repo: https://github.com/mjmlio/email-templates. It's not automated at this time but once the changes are merged we can just reimport the fixed templates in the website.

**Comment by willhertz** [comment]
Thanks for your answer. 
I already made a pull request for one of the templates.
Don't know if now this issue might be closed, now that the seed is planted in https://github.com/mjmlio/email-templates
and everything related to templates be issued and managed over there.

**Comment by ngarnier** [comment]
Yes indeed, let's keep the conversation in that other repo. Thanks for your contribution!
