### ISSUE TITLE
Is there any way to validate the MJML content before converting to HTML?

### ISSUE THREAD

**Issue by nick13jaremek** [mjmlio/mjml#198]
Hi there!

We are using the `mjml` library in a NodeJS project to convert MJML emails to HTML. For this purpose, we are using the `mjml2html` function you provide.

However, we noticed that this function is synchronous, and therefore error handling needs to be done using a try-catch clause.

Is there is any other function or sister-library of yours that may be used to validate an MJML structure before attempting the actual convertion? Or perhaps an asynchronous equivalent to handle the errors due to invalid MJML structures?

Thanks in advance!

**Comment by pixelize** [comment]
Hi @nick13jaremek, I don't think it exists yet but I agree a kind of "mjml lint" would be awesome !

**Comment by nick13jaremek** [comment]
Hi @pixelize!

Indeed, an `mjml lint` function would be awesome. In the meantime, we wrapped the synchronous `mjml2html` function in a Promise, which suits our needs for the moment.

**Comment by iRyusa** [comment]
Hello, 

Quick update here, we will support an `xsd` like layer of validation that provide meaningful errors such as "mj-column should be in a mj-section/mj-group" or "attribute X doesn't exist on mj-column"

**Comment by iRyusa** [comment]
Hi there,

Long awaited feature is now available ! Use `mjml --validate file.mjml` to validate a file or just compile it and it will output to stdout the errors. In javascript, `mjml2html` or `MJMLRenderer` now output an `Object` with `html` and `errors` properties !

**Comment by gabiudrescu** [comment]
@iRyusa the `mjml --validate file.mjml` detects errors like the one below:

 `<mj-image width="x" src="image.jpg" align="center" padding="0" />`

but stuff like the one below are reported as OK - while they should raise an error:

`<mj-image blablabla="totallyinvalidoption" src="images/actionable-notification.jpg" align="center" padding="0" />`

`</mj-section`

any clues on how can I set the validator to raise an error when finding something like this?

**Comment by kmcb777** [comment]
@gabiudrescu which mjml version are you using ? With 4.1.2 i get the validation warning saying 'blablabla' is not a valid attribute

**Comment by gabiudrescu** [comment]
well, @iRyusa I would highly appreciate any help on setting up `mjml` as the binary used as a linter. as you can see in my examples above, the output is not what I'm expecting.

**Comment by iRyusa** [comment]
> when you use mjml-cli on it's own, no component are registered by default.

**Comment by iRyusa** [comment]
> when you use mjml-cli on it's own, no component are registered by default.
Just use the regular binary of the `mjml` package, it will just work fine.

**Comment by gabiudrescu** [comment]
I think I have managed to find a bug. I'm opening another issue.

**Comment by gabiudrescu** [comment]
@iRyusa let's move our discussion over #1356 as I have posted there the *exact* steps I am doing in order to reproduce the error. Now I'm able to reproduce it consistently.
