### ISSUE TITLE
Button inner padding 100%

### ISSUE THREAD

**Issue by pavlito** [mjmlio/mjml#1980]
**Currently only inner button padding is clickable even if the width is set 100%**
Users expecting that whole button is clickable - instead, they don't know that they need to click only on the button content in case of btn 100% width.

**Rework or introduce new button <mj-button-100>**

![Button 100%](https://i.snipboard.io/NrVwUm.jpg)

**Comment by iRyusa** [comment]
This has been discussed already, and this is the best compromise we could get.
