### ISSUE TITLE
Outline buttons possible?

### ISSUE THREAD

**Issue by pavlito** [mjmlio/mjml#1982]
Is it possible to have outline buttons with only border and text color?

**Comment by iRyusa** [comment]
Yes, use background-color transparent

**Comment by pavlito** [comment]
> Yes, use background-color transparent
> […](#)
> On 22 Jul 2020, at 20:05, pavlito ***@***.***> wrote: ﻿ Is it possible to have outline buttons with only border and text color? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Is it possible to have custom component like <mj-button-outline> as an idea for future upgrade

**Comment by iRyusa** [comment]
Just do a mj-class for that kind of work no need to create a specific component just for few arguments on current mj button
