### ISSUE TITLE
mj-raw preventing valid table code output of mj-column

### ISSUE THREAD

**Issue by lvl99** [mjmlio/mjml#1985]
**Describe the bug**
When I use a `mj-raw` block inside a `mj-column` block, the `mj-column` block doesn't output all the necessary table code to be valid.

**To Reproduce**
1. Create a file with this MJML code:

```
<mjml>
  <mj-body>
    <mj-wrapper>
      <mj-section>
        <mj-column>
          <mj-image
            src="https://via.placeholder.com/600x150"
            width="600px"
            height="150px"
            alt=" "
            align="center"
          ></mj-image>
        </mj-column>
      </mj-section>
    </mj-wrapper>

    <mj-wrapper>
      <mj-section>
        <mj-column>
          <mj-raw>
            Here's some code
          </mj-raw>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```
2. Compile MJML to HTML
3. Search for "Here's some code" in the compiled HTML
4. You can see that the code surrounding the content of the `mj-raw` block is malformed -- there's a `table` block but no other table elements:

```html
      <div
         class="mj-column-per-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        Here's some code
      </table>
    
      </div>
```

**Expected behavior**
I expected the full and valid `table` code structure that would then wrap the `mj-raw` contents, similar to what is visible for the output of the `mj-image` block in the provided code example.

**MJML environment (please complete the following information):**
 - OS: macOS 10.14.6
 - MJML Version: 4.6.3
 - MJML tool used: Node.js `mjml` package

**Comment by lvl99** [comment]
I did another experiment with the following MJML code:

```
<mjml>
  <mj-body>
    <mj-wrapper>
      <mj-section>
        <mj-column>
          <mj-image src="https://via.placeholder.com/600x150" width="600px" height="150px" alt=" " align="center"></mj-image>
        </mj-column>
      </mj-section>
    </mj-wrapper>

    <mj-wrapper>
      <mj-section>
        <mj-column>
          <mj-raw>
            mj-raw inside mj-column
          </mj-raw>
        </mj-column>
      </mj-section>
    </mj-wrapper>

    <mj-wrapper>
      <mj-section>
        <mj-raw>
          mj-raw inside mj-section
        </mj-raw>
      </mj-section>
    </mj-wrapper>

    <mj-wrapper>
      <mj-raw>
        mj-raw inside mj-wrapper
      </mj-raw>
    </mj-wrapper>
  </mj-body>
</mjml>
```

For the `mj-raw inside mj-column` example it is directly wrapped with a `table` that has no necessary child elements, whereas all the others (`mj-section` and `mj-wrapper`) seem to have no issues.

**Comment by iRyusa** [comment]
You need to use mj text if you want so. Mj-raw will output directly into the HTML code as you would expect for templating language to surround your tr/td elements

**Comment by lvl99** [comment]
Hi @iRyusa,

The plain text I put in was just to reduce the size of the example. If I put in any other HTML the result would be the same.

`mj-wrapper` and `mj-section` work fine with `mj-raw` as a child and output the correct table structure — `mj-column` doesn’t.

**Comment by iRyusa** [comment]
Mj raw is for RAW output nothing else. mj-column will wrap child only for non raw element. Use mj text you’ll have td and tr generated by column and you can put HTML in it too.

**Comment by lvl99** [comment]
Ok, so it’s expected behaviour? Seems a little weird and inconsistent to me. The fix I made to my templates was to remove the `mj-column` node.

**Comment by iRyusa** [comment]
This is the intended use of mj raw you don’t want templating stuff to be surround by a tr td or HTML comments.

**Comment by lvl99** [comment]
@iRyusa isn’t this what we get with `mj-wrapper` and `mj-section` anyway? If I wanted to put some raw HTML within a column, I would have to write the extra `tr` and `td` elements and miss all the automated mso conditionals and CSS classes that MJML generates for other child elements of the `mj-column` element.

**Comment by iRyusa** [comment]
No, it’s just that the final output tag from section & wrapper have no need to wrap children.

You misunderstand the use of mj-raw here, it’s mostly useful for templating language. If you need a valid children with HTML / raw support just use mj-text as said before.

**Comment by lvl99** [comment]
@iRyusa yeah, I think I’ve misunderstood the usage of it in this particular context. I am using `mj-raw` to insert HTML and other templating languages (I have a project where I manage email templates for three different email template systems — mjml with handlebars is one of them). My workaround works, I think it was just my expectations were wrong. Still seems strange that if I use `mj-raw` within `mj-column` that I have to put in the supporting `tr`, `td` code, whereas I don’t have to with `mj-wrapper` and `mj-section`.

**Comment by iRyusa** [comment]
Again.... use mj-text for that. Raw is only for raw content.

**Comment by lvl99** [comment]
Just to clarify: are you saying to wrap the `mj-raw` element with an `mj-text` element if I need to place it within an `mj-column`?

**Comment by iRyusa** [comment]
No, use mj text instead of mj raw

**Comment by iRyusa** [comment]
Closing this one has it not the purpose of mj-raw.

If you want to produce valid HTML code, just use a component like `mj-text` as stated, mj-raw allow you to surrend any children properly:

```xml
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-raw>
          <% if something %>
        </mj-raw>
        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
        <mj-raw>
          <% endif %>
        </mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
``` 

Would produce :

```html
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%">
                  <% if something %>
                  <tr>
                    <td align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                      <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
                        <tbody>
                          <tr>
                            <td style="width:100px;"> <img height="auto" src="/assets/img/logo-small.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" width="100" /> </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td style="font-size:0px;padding:10px 25px;word-break:break-word;">
                      <p style="border-top:solid 4px #F45E43;font-size:1px;margin:0px auto;width:100%;"> </p>
                      <!--[if mso | IE]>
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" style="border-top:solid 4px #F45E43;font-size:1px;margin:0px auto;width:550px;" role="presentation" width="550px"
        >
          <tr>
            <td style="height:0;line-height:0;">
              &nbsp;
            </td>
          </tr>
        </table>
      <![endif]-->
                    </td>
                  </tr>
                  <tr>
                    <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                      <div style="font-family:helvetica;font-size:20px;line-height:1;text-align:left;color:#F45E43;">Hello World</div>
                    </td>
                  </tr>
                  <% endif %>
  
                </table>
```

**Comment by lvl99** [comment]
@iRyusa I've tried your suggestion of `mj-text`, but it is definitely not sufficient for my use case, considering I'm inserting HTML code generated by another templating language.

Given this MJML template:

```
<mjml>
  <mj-body>
    <mj-wrapper>
      <mj-section>
        <mj-column>
          <mj-text>
            <mj-raw>
              <!-- HTML code generated by another templating language -->
            </mj-raw>
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

I got an output where the `mj-raw` block was treated as text (here's an excerpt):

```html
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        
            <tr>
              <td
                 align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;"
              >
                
      <div
         style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;"
      ><mj-raw>
              <!-- HTML code generated by another templating language -->
            </mj-raw></div>
    
              </td>
            </tr>
          
      </table>
```

If I'm trying to add HTML generated by another templating language within a `mj-column`, it doesn't look good to me using either `mj-raw` as the first child within the `mj-column`, nor when wrapped in a `mj-text` element as you suggested.

It seems that the only reliable way I can do it is like this:

```
<mj-column>
  <mj-raw>
    <tr>
      <td>
        <!-- HTML code generated by another templating language -->
      </td>
    </tr>
  </mj-raw>
</mj-column>
```

**Comment by iRyusa** [comment]
I don't know how many times I have to say, just use mj-text instead of mj-raw https://mjml.io/try-it-live/rkaFOSnlv.

There's no need to use mj-raw inside mj-text as mj-text children isn't parsed (exactly as mj-raw).

Mj-text does support **anything** as children. 

Both tag have different purpose, mj-raw suits for templating, comments, non MJML dependent code. mj-raw is needed only when you know what you're doing at this point of the generated HTML from MJML. Here you simply want a "div"-like element and that's exactly the purpose of mj-text here.

**Comment by lvl99** [comment]
@iRyusa I guess I feel the same equal frustration -- it's obviously a communication issue.

For me `mj-text` is for adding a block of text -- being able to support HTML code seems semantically outside its named premise, and I'm lead to using `mj-raw` due to using other HTML in other blocks having processing rejections due to MJML not processing HTML code. I don't have much experience with MJML aside from trying to wangle it into my existing templating project due to another service's usage of MJML.

In my case I am trying to add a block of HTML that has been generated by a templating language. I see now what you're saying is "if you're inserting HTML, use ONLY `mj-text` (because it allows HTML) and NOT `mj-raw`".

**Comment by iRyusa** [comment]
It's even stated in the doc as a warning : 

 > MjText` can contain any HTML tag with any attributes. 

And the exemple of mj-text shows it : 

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          <h1>
            Hey Title!
          </h1>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

And multiple templates here https://mjml.io/templates show HTML inside `mj-text`.
