### ISSUE TITLE
MJML Copy to html emojis are converted to symbols

### ISSUE THREAD

**Issue by ScottAgirs** [mjmlio/mjml#1989]
**Describe the bug**
When creating a .mjml template in VSCode and using the MJML: Copy HTML, the HTML string that's copied to clipboard turns emojis to symbols.

For example: `👋`  will be turned into `üëã`

**To Reproduce**
1. Create an MJML file with emoji in it
2. Use Copy HTML
3. Paste into editor

**MJML environment (please complete the following information):**
 - OS: macOS 10.15.4
 - MJML VSCode Extension 1.6.0

PS.
This is also true for some characters: 
` · ` will be decoded into ` ¬∑ `

**Comment by kmcb777** [comment]
Hi, this shouldn't happen anymore, this is likely due to the fact that the mjml version in vscode extension 1.6.0 by attilabuti is quite old. It's no longer maintained so we forked it to update mjml version.
You need to use the mjml extension by "mjmlio" instead.

**Comment by ScottAgirs** [comment]
> Hi, this shouldn't happen anymore, this is likely due to the fact that the mjml version in vscode extension 1.6.0 by attilabuti is quite old. It's no longer maintained so we forked it to update mjml version.
> You need to use the mjml extension by "mjmlio" instead.

ahh, okay, so I should only have this (https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml) installed and uninstall the @attilabuti one?

**Comment by kmcb777** [comment]
Yes exactly, the mjml version will be much more recent
It just checked the code and the "copy to clipboard" functionality uses the `copy-paste` npm library. The problem may also come from there. We updated some dependencies when forking the extension, so it may be solved, but if you still have this problem i'm afraid we can't do anything about it.

**Comment by ScottAgirs** [comment]
Okay, i'll test it with that, if you don't see this re-opened in few days, then your proposed solution will be the fix. : )
