### ISSUE TITLE
mjml2txt

### ISSUE THREAD

**Issue by ppawlak** [mjmlio/mjml#199]
When writing a newsletter one often embed both HTML and text format in the email.
It would be great if _mjml_ could also generate the plain text part from the same markup using a _mjml2txt()_ function

**Comment by dominiquedutra** [comment]
I would also like a feature like you described.

What i've tried so far:

```npm install -g html-to-text```
then bash
```cat emailmarketing.html | html-to-text > emailmarketing.txt```

Does funny things with image src links and line breaks on a mjml generated template.

Thanks

**Comment by ngarnier** [comment]
The only immediate solution we can see is indeed to rely on html-to-text, which as @dominiquedutra said does funny things from a HTML template so is not an ideal solution.

It's also probably not the role of MJML to generate the text from a HTML template as there are libs for that. If you see an efficient way to do it though, feel free to reopen!
