### ISSUE TITLE
White Space between three columns

### ISSUE THREAD

**Issue by dion96** [mjmlio/mjml#1990]
**Describe the bug**

When using three columns next to each other MJML produces a white line between one of the columns as seen in the attached screenshot below.

**To Reproduce**

1. Use this MJML code: 

`<mjml>
<mj-head>
<mj-font href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500" name="Roboto">
</mj-font>
</mj-head>
<mj-body>
<mj-section background-repeat="repeat" background-size="auto" css-class="mj-section-22970776" padding-bottom="50px" padding-left="50px" padding-right="50px" padding-top="50px">
<mj-column background-color="#B29BFD" css-class="mj-column-09042109" padding-bottom="50px" padding-left="30px" padding-right="30px" padding-top="50px">
</mj-column>
<mj-column background-color="#B29BFD" css-class="mj-column-77012792" padding-bottom="50px" padding-left="30px" padding-right="30px" padding-top="50px">
</mj-column>
<mj-column background-color="#B29BFD" css-class="mj-column-88774928" padding-bottom="50px" padding-left="30px" padding-right="30px" padding-top="50px">
</mj-column>
</mj-section>
</mj-body>
</mjml>`

2. Try it out in the live editor

**Expected behavior**

No white spaces between columns

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML API and Live Editor

**Screenshots**

<img width="1591" alt="Schermafbeelding 2020-07-29 om 15 02 25 1" src="https://user-images.githubusercontent.com/9917616/88803915-71fa5500-d1ad-11ea-8ff9-7db6157c4328.png">

**Comment by iRyusa** [comment]
It's a rounding (missing pixel) issue where MJML can't guess properly column's width with auto column-sizing (as size is declared in pixel both column have a 33,333333333...% width). 

2 solutions : 
- define width manually to `34%/33%/33%` or `200px` for each one
- add a background color to the section with the same column background to hide the missing pixel.
