### ISSUE TITLE
Does the latest MJML support running in the Java Nashorn engine?

### ISSUE THREAD

**Issue by skingsland** [mjmlio/mjml#1992]
I want to call out to the mjml.js [Nashorn](using https://www.oracle.com/technical-resources/articles/java/jf14-nashorn.html) from a Java server, because I need to convert from MJML -> HTML on the fly in Java. Is that supported in the latest version of MJML?

**Comment by DRoet** [comment]
Mjml depends on commonjs modules and nodejs builtins (fs/path) and as far as I'm aware Nashorn does not support these, but I could be wrong.

**Comment by skingsland** [comment]
OK yeah it looks like you're right, thanks for confirming!
