### ISSUE TITLE
Background-url doesn't work as expected

### ISSUE THREAD

**Issue by oron11** [mjmlio/mjml#1993]
I have added local file path to my mj-section as described in the tutorial:
https://mjml.io/getting-started/2
From what I'm seeing, the picture does not show up in the email, it also doesn't work with regular src of mjml-image.

`<mj-section background-url="LOCAL_FILE_PATH">
..
</mj-section>`

I tried in a different method with the "cid" as an attachment and for a regular image, it's working but for background-url, it doesn't.

MacOS 10.15.5
mjml 4.6.3
node.js 14.3.0

**Comment by GarryFlemings** [comment]
@oron11 : Thanks for writing. Welcome to MJML. I can help.

There are many things that can cause this. It'd be speculation to propose one without seeing your code.

Care to share? Maybe, on https://mjml.io/try-it-live? It's free and easy.

It's best to tell us your URL after you put your code in.

Glad to help. 🍀

**Comment by oron11** [comment]
@GarryFlemings thank you for your help.
I tried exactly like in the try-it-live with my own local source.
```
<mjml>
<mj-body>
  <mj-section>
    <mj-column>

      <mj-image width="100px" src="/img/logo.png"></mj-image>

      <mj-divider border-color="#F45E43"></mj-divider>

      <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

    </mj-column>
  </mj-section>
</mj-body>
</mjml>
```
The path should work, I used other variation like building the path with: `path.normalize`

I think if this problem will solve it should work also for the background-url.

**Comment by GarryFlemings** [comment]
https://mjml.io/try-it-live/ryjzvjN-P

The above is your code, except that I've substituted the URL of an image in our documentation. It looks like your code is fine.

Is your string "/img/logo.png" a relative path?

A problem you'll find in email HTML (it's bigger than MJML) is that many email clients require a fully qualified path to a server on the Internet or on your reader's computer (yeah, good luck with that one! 😄)

Seems like you're doing okay. Hang in. 🍀

**Comment by GarryFlemings** [comment]
@oron11: Maybe you have the answers you need. I'll close this now.

Feel free to reopen it. Or open another.

Again: Welcome to MJML! Good luck. 🍀

**Comment by oron11** [comment]
I tried also with the full path, building it with `path.normalize`.
So relative and full path didn't work for me, unfortunately.

**Comment by iRyusa** [comment]
We need a bit more context for this one I think to help you.

What are you using to render the MJML file, what's the file structure you have ?

**Comment by oron11** [comment]
I'm using nodemailer 6.4.6.
mjml2html from the mjml library.
All the rest of the configuration that I wrote in the first comment.

**Comment by iRyusa** [comment]
You need to host images if you're sending it through nodemailer. There's no magic that does that stuff for you. Try to open the local HTML, it should work locally.
