### ISSUE TITLE
Lines in the color of body element in the Outlook 2016

### ISSUE THREAD

**Issue by creationell** [mjmlio/mjml#1994]
**Describe the bug**
I get strange lines in the color of the body element in the Outlook 2016 (windows) at places where they should not appear (1 horizontall after the word Subline and second vertically close to the text in the block left text right picture ). There are  no such lines in the try it live preview or outlook or on https://outlook.office365.com/ 

**To Reproduce**
1. Create a file with this MJML code: https://mjml.io/try-it-live/HkzuPLHbD
2. Render it to HTML by doing 'node ./node_modules/mjml/bin/mjml -w index.mjml -o index.html'`or copy paste from try-it-live
3. Send the HTML to an email address with 'https://www.putsmail.com/ or cleverreach'

**Expected behavior**
There should be no grey lines visible on the 

**MJML environment (please complete the following information):**
 - OS: Windows10
 - MJML Version 4.6.3
 - MJML tool used: npm + nodeJS 

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [Putsmail](https://putsmail.com/] and [CleverReach](https://www.cleverreach.com/)  

**Affected email clients (for rendering issues):**
 - Email Client Outlook 2016
 - OS: Windows 10

**Screenshots**
![1](https://user-images.githubusercontent.com/31882731/89169542-a9d31500-d57e-11ea-9bbd-0aae25df43f2.png)
![2](https://user-images.githubusercontent.com/31882731/89169555-ab9cd880-d57e-11ea-8628-d44707986428.png)

**Comment by iRyusa** [comment]
That's not really related to MJML, this weird behavior in Outlook where sometimes horizontal/vertical-lines appears randomly. It can be fix by playing with various stuff such as line-height, font-size, column width... https://mosaico.io/email-client-tricks/outlook-2016-weird-1px-horizontal-lines/
There's various blog post about this. Hope you'll find the culprit value here
