### ISSUE TITLE
add info from dependencies.js to the documentation pipeline

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1997]
**Is your feature request related to a problem? Please describe.**

There are three relevant conditions:

1. Our documentation could do a better job of communicating what MJML components are legal children in others.
2. The information needed in the documentation is in _MJML/packages/mjml/src/dependencies.js_.
3. If we decide to add this information to the documentation, we want it to be compact.

There is opportunity to remedy all three conditions.

**Describe the solution you'd like**

The goal of the changes: Add a component inclusion rule at the start of documentation for each MJML component. The effect of this rule shall be to start an automated routine
1. to collect an accurate list of MJML components allowed as children of the component for the current documentation,
2. format that list into a consistent format across all MJML components and appropriate for MJML documentation, and
3. include that information in the documentation.

By way of example and not direction: The documentation pipeline will at some point process _MJML/packages/mjml-accordion/README.md_ into the documentation. The sections there for MJML components mj-accordion, mj-accordion-element, mj-accordion-title, and mj-accordion-text could each include a component inclusion rule.

Each rule would cause a routine to look in _MJML/packages/mjml/src/dependencies.js_ for information on the respective component. 

For _mj-accordion_ (the first component in the subject file). the relevant information in _dependencies.js_ is
> 'mj-accordion': ['mj-accordion-element', 'mj-raw'],

Perhaps the project will decide it wants one-line documentation of the form (for the example of mj-accordion),
> Accepted children of mj-accordion: mj-accordion-element and mj-raw

The routine could create that output.

The second component inclusion rule--for MJML component mj-accordion-element--could result in this line for mj-accordion-element:
> Accepted children of mj-accordion-element: mj-accordion-title, mj-accordion-text, and mj-raw

The third component inclusion rule--for MJML component mj-accordion-title--would detect that in contrast with the first two examples, the mj-accordion-title component allows no children.

Perhaps the project will decide for this case it wants a line like,
> Accepted children of mj-accordion-title: none

On the other hand, the project might decide it prefers no line in the documentation. Readers will come to connect the line's absence with the appropriate information.

The documentation is more precise with the first of those. It is more streamlined with the second.

**Describe alternatives you've considered**

We could continue a largely manual process for including all information in the documentation.

Not recommended, because in this case, automated information collection can be expected to
1. have fewer errors, and
2. insulate the project from potential variation in volunteer availability.

**Comment by iRyusa** [comment]
Closing this for #2316 this should be easier to in the new doc
