### ISSUE TITLE
images get scaled when setting mj-column width

### ISSUE THREAD

**Issue by ludobrands** [mjmlio/mjml#2]
try following code and look at the image size:
```
<mj-body>
  <mj-section>
    <mj-column width="20%">
      <mj-image src="/assets/img/logo-small.png"></mj-image>
      <mj-divider border-color="#F45E43"></mj-divider>
      <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
    </mj-column>
     <mj-column width="60%">
      <mj-image src="/assets/img/logo-small.png"></mj-image>
      <mj-divider border-color="#F45E43"></mj-divider>
      <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World2</mj-text>
    </mj-column>
  </mj-section>
</mj-body>
```

Try `<mj-column width="400">` to see the image blow up

**Comment by arnaudbreton** [comment]
Adding `width="100%"` attribute on the first image fixes it, preventing the image to scale up more than its own max size.

For the second image, it's the processed `max-width: 10px` CSS rule which constraints it.

**Comment by iRyusa** [comment]
Images scale with column width now, if you want to have a fixed width you have to add `width="20px"` on your `mjImage`
