### ISSUE TITLE
mj-column > vertical-alignment: "middle" renders like "top"

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2007]
**Describe the bug**
In https://mjml.io/try-it-live/H1R4GjEzw, `vertical-alignment: "middle"` renders the same as `vertical-alignment: "top"`.
![image](https://user-images.githubusercontent.com/14095071/90430447-0eb56180-e08d-11ea-83be-0adeb145a56b.png)

**Expected behavior**
The "middle" column would vertically render between the "top" and the "bottom".

**Comment by iRyusa** [comment]
`vertical-align` is an old css attributes with non intuitive behavior. Setting the first column as `vertical-align="middle"` make it works as expected https://mjml.io/try-it-live/BJQLCBdGD
