### ISSUE TITLE
mj-divider with a static width (40px or 400px) doesn't adapt on mobile

### ISSUE THREAD

**Issue by dubcanada** [mjmlio/mjml#2014]
**Describe the bug**
A mj-divider with a set width in pixels (such as 400px) will not change the width on mobile.

**To Reproduce**

```
<mj-divider width="400px" />
```

Check width of divider on a mobile, you'll see the p tag has a width of 400px

**Expected behavior**

Ideally it would allow either a desktop & mobile width or set it to 100% if width is greater then the mobile breakpoint.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.6.3
 - MJML tool used: MJML App

**Email sending environment(for rendering issues)**:

Not applicable

**Affected email clients (for rendering issues):**

All mobile clients

**Comment by iRyusa** [comment]
I don't think we'll be able to do much here as it will rely on media queries and i'm not sure we'll have proper result for outlook. You can either fork mj-divider or just rely on width in percent which will works just fine.

**Comment by dubcanada** [comment]
Alright I'll play around with it and see what's possible.
