### ISSUE TITLE
Make entire button clickable

### ISSUE THREAD

**Issue by mdmoura** [mjmlio/mjml#2017]
I created a button but in some cases only the text is clickable. For example in Apple Mail:

```
<mjml>
  <mj-head>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
         <mj-button css-class="button" href="http://www.google.com" align="center" background-color="#00C7B1" color="#FFFFFF" border-radius="3px" font-size="20px" font-weight="bold" inner-padding="12px 18px" padding="12px 18px" target="_blank" text-transform="uppercase">Button</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Then I added the following styles which, at least in Safari, makes all the button clickable:

(Example: https://mjml.io/try-it-live/HkQdM-VmP)

```
    <mj-style>  
      td.button td { border-radius: 3px !important; padding: 0 !important; }
      td.button td a { display: block; border-radius: 3px !important; padding: 12px 18px !important; }
      td.button td:hover, td.button td:hover a { background-color: #007864 !important; }
    </mj-style>   
```
Should I do this? Why isn't the default button clickable in the entire button area?

**MJML environment:**
 - OS: MacOS
 - MJML Version: 4.2.0
 - MJML tool used: ([Mjml Visual Studio Code Extension](https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml))

**Affected email clients:**
 - Email Client Apple Email and Gmail
 - OS:MacOS

**Comment by iRyusa** [comment]
This is because some clients as outlook doesn’t support fully clickable button see https://github.com/mjmlio/mjml/issues/359

**Comment by mdmoura** [comment]
I understand but if in Apple Mail the button is not fully clickable using:

```
    <mj-button 
        css-class="button" 
        href="http://www.google.com" 
        align="center" 
        background-color="#00C7B1" 
        color="#FFFFFF" 
        border-radius="3px" 
        font-size="20px" 
        font-weight="bold" 
        inner-padding="12px 18px" 
        padding="12px 18px" 
        target="_blank" 
        text-transform="uppercase">Button
    </mj-button>
```

But it becomes fully clickable adding:

```
    <mj-style>  
      td.button td { border-radius: 3px !important; padding: 0 !important; }
      td.button td a { display: block; border-radius: 3px !important; padding: 12px 18px !important; }
      td.button td:hover, td.button td:hover a { background-color: #007864 !important; }
    </mj-style>   
```

Shouldn't theses styles being added by default to <mj-button> implementation since at least in Apple Mail solves the problem (not sure about the other ones)?

Or am I missing something?

**Comment by iRyusa** [comment]
Fixing a client doesn’t mean it will render fine in other. Actually mj button is the best compromise in clickability and how It renders across all email clients
