### ISSUE TITLE
allow cellpadding and cellspacing parameters on `<mj-table>`

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml#202]
Just because sometimes we need them.

Currently, `<table style="border-spacing: 10px; border-collapse: separate;"></table>` returns `Cannot read property 'defaultMJMLDefinition' of undefined`.

`<mj-table  cellspacing="10">` would be good.

**Comment by iRyusa** [comment]
Hey there ! `mj-table` now supports `cellpadding` and `cellspacing` in 2.3 !
