### ISSUE TITLE
mj-spacer. Vertical align attribute is unnecessary

### ISSUE THREAD

**Issue by OReshetnikov** [mjmlio/mjml#2021]
**Describe the bug**
When I try to add vertical-align to spacer, it is not working. Is it incorrect in documentation or? Looks like this attribute is redundant

**To Reproduce**
Steps to reproduce the behavior: https://mjml.io/try-it-live/SyUocToXv
Try to change vertical-align from top to middle or bottom.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.3.0

**Comment by iRyusa** [comment]
`width` & `vertical-align` have no real purpose on this tag anyway, they just need to be removed.

**Comment by OReshetnikov** [comment]
Hi @iRyusa , can I create PR for documentation update or will you update it yourself?

**Comment by iRyusa** [comment]
You can update the doc and allowed attributes in the component https://github.com/mjmlio/mjml/blob/master/packages/mjml-spacer/src/index.js#L18-L19
