### ISSUE TITLE
Importing regular CSS files without the mj-style tag

### ISSUE THREAD

**Issue by AdrianFahrbach** [mjmlio/mjml#2026]
**Is your feature request related to a problem? Please describe.**
The problem is that you can't include regular css files without wrapping it with an `<mj-style>`. Related issues that I found are #1872 and #1049
Whenever you're working with some kind of build automation, you'll always get a regular CSS file. Adding the `<mj-style>` Tag is an unnecessary step that basically everyone with style generation has to do.

**Describe the solution you'd like**
I would like to import regular CSS. It could be done in a similar way to this:
```
<mj-style>
  <mj-include path="./semantic.css"/>
</mj-style>
```
```
<mj-style path="./semantic.css"/></mj-style>
```

**Comment by iRyusa** [comment]
I'm not really against this, but it means `mj-style` will be dependent to filesystem and making browser build tedious again. 

But again this need a lot of work on parser side, because relative path still need to be relative of the included file not the root file

**Comment by niksauer** [comment]
With the current setup, i.e.:

```
# base.mjml
<mj-head>
  <mj-include path="./onboarding.mjml.css" />
</mj-head>


# onboarding.mjml.css
<mj-style>
body {
  background-color: #f2f2f2;
}
</mj-style>
```

I get the following linting error:

```
$ mjml -l strict -v src/*.mjml
Line 47 of .../emails (mj-raw) — mj-include fails to read file : ./onboarding.mjml.css at ../emails/onboarding.mjml.css
```

Is that expected?

**Comment by iRyusa** [comment]
You might be able to modify current mj include implem to have something like that, I'm not sure what's the impact would be on current mj-include implementation (with nested include)

**Comment by samvanfleteren** [comment]
I'm sort of having the same problem. In an ideal world I want my css-file to be added inline on output, not included as a seperate file.

**For example:**

**test.css** could look like this:
`.test {color: #FF0000;}`

**test.mjml** could look like this:
`<mjml>
    <mj-head>
        <mj-style inline="inline">
            <mj-include path="test.css" />
        </mj-style>
    </mj-head>
    <mj-body>
        <mj-section>
            <mj-column>
                <mj-text css-class="test">Some text</mj-text>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
`
And my **desired output** would be something like this:
`<td style="color: #FF0000;">Some text</td>`

Is this possible?

**Comment by iRyusa** [comment]
We're looking to support multiple extension on mj-include in a next update. But mj-include won't work in content tag like mj-style.
