### ISSUE TITLE
Twitter share URL has changed.

### ISSUE THREAD

**Issue by astanar01** [mjmlio/mjml#2027]
Old sharing URL is not working anymore
`https://twitter.com/home?status=https://mjml.io/`

New code to be used:
`https://twitter.com/intent/tweet?text=hello`

**Comment by GarryFlemings** [comment]
Related: PR#1914 merged May 26.

**Comment by ngarnier** [comment]
As pointed out by Garry this was already merged and released in v4.7.0. We'll update plugins and the online editor to use the latest version as always.
