### ISSUE TITLE
mj-button click works only for text not entire button Windows outlook issue

### ISSUE THREAD

**Issue by shiv15ani** [mjmlio/mjml#2028]
`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-button href="https://www.google.com/" width="230px">Click</mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

does for work all the email clients, but  for windows outlook, only text inside button is clickable, but entire button is not clickable,

Is there any fix for this, or it is still an issue

**Comment by iRyusa** [comment]
That's the most we can do about thi, please check #359
