### ISSUE TITLE
mj-section background-position not working

### ISSUE THREAD

**Issue by jayhybrid** [mjmlio/mjml#2031]
**Describe the bug**
mj-section background-position does not seem to work.

**To Reproduce**
1. Create a file with this MJML code:
```mjml
<mjml>
  <mj-body>
    <mj-section background-url="https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569_960_720.jpg" background-color="#fff" background-size="contain" background-repeat="no-repeat" background-position="top left">
      Why is the background not aligned?

      <mj-spacer height="128px" />
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
The Background image is not centred but positioned at the top left corner of the container.

**Screenshots**
![image](https://user-images.githubusercontent.com/44577029/93208845-84305280-f75d-11ea-8f70-8b978ba6b68a.png)

**Additional context**

**Comment by iRyusa** [comment]
`background-position` on `mj-section` is only supported on MJML 4.7

**Comment by jayhybrid** [comment]
It seems to still be mentioned in the docs or am I missing something? https://mjml.io/documentation/#mj-section

**Comment by jayhybrid** [comment]
I started using the API. Does it automatically use the most recent MJML version? Can I expect this issue to resolve itself?
