### ISSUE TITLE
<a href> tags

### ISSUE THREAD

**Issue by ducktheworld** [mjmlio/mjml#2037]
I noticed there's no documentation about <a href> tags. Yes, you can do <mjml-text><a href=""> but you can't prevent the text link from being underlined and blue. You can create a style but Outlook disregards it. 

Anyone have a fix? 

<img width="679" alt="Screen Shot 2020-09-18 at 4 27 39 PM" src="https://user-images.githubusercontent.com/20198907/93646479-ea221180-f9cb-11ea-8151-f6c3883be5fc.png">

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/rys-GMESD both works fine.

Please before opening an issue post your actual code and try it yourself first.
