### ISSUE TITLE
Japanese translation of the README.md

### ISSUE THREAD

**Issue by hikiroom** [mjmlio/mjml#2038]
I'd like to translate README.md for Japanese developers.
I would like to know if there are any existing translation rules.

**Comment by iRyusa** [comment]
Hi ! 

There's no real guideline about that because there's no translation yet available, but you can just post a readme-{lang}.md and add a link to it into the main readme ?

**Comment by hikiroom** [comment]
Hi! @iRyusa 
Thanks for letting me know :D
I'll try to submit a pull request using the method you gave me.
