### ISSUE TITLE
Question: Remove top comment on mjml-cli usage (rendering a file)

### ISSUE THREAD

**Issue by Kwaadpepper** [mjmlio/mjml#2039]
Is it possible to prevent mjml from adding a top comment when rendering a file ?
eg : `<!-- FILE: resources/views/mails/level/test2.mjml -->` ?

I tried `--config.keepComments=0` without success.

Thank you.

**Comment by iRyusa** [comment]
Nope there's no option to disable it as it's specific to the cli not `mjml-core`. Maybe we can add a small flag to remove it @kmcb777 

Note that it's not output when you output into a file

**Comment by iRyusa** [comment]
You have a new option in mjml-cli to remove the extra file name !

**Comment by Kwaadpepper** [comment]
Thank you sir :D
