### ISSUE TITLE
How do you set document/mj-body gutter ?

### ISSUE THREAD

**Issue by pixelize** [mjmlio/mjml#204]
Hey guys,

Just started my first email with MJML which looks a good framework.
Otherwise, I'd like to set a left and right gutter outside my general template. In fact, i'd like to add a padding-left and padding-right to the body so my container has spaces on the sides.

![group 3](https://cloud.githubusercontent.com/assets/2931627/14857458/a433d76a-0c9c-11e6-8bde-3baad0525fe3.png)

I tried several things like putting in additional mj-column, settings padding on mj-body or wrapping with a mj-section but nothing works. Any help would be very appreciated ;)

Keep up the good work.

Here is my code : [http://codepen.io/Pixelize/pen/qZJWyd](http://codepen.io/Pixelize/pen/qZJWyd)

(sorry but github code tag is totally bugging)

**Comment by iRyusa** [comment]
Dup of 160 closing this one

**Comment by jitendravyas** [comment]
Is the solution for this available now?

**Comment by handhikadj** [comment]
@iRyusa what is the workaround for this?

**Comment by iRyusa** [comment]
You can use a mj-wrapper to add left/right padding
