### ISSUE TITLE
Attribute font-size has invalid value: 20pxpx for type Unit, only accepts (px) units and 1 value(s)

### ISSUE THREAD

**Issue by EECOLOR** [mjmlio/mjml#2040]
```js
const test = `<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text font-size="20px">Text</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

const mjml2html = require('mjml')

const { errors } = mjml2html(test)

console.log(errors)
```

Version `4.7.0`

**Comment by iRyusa** [comment]
Just remove mj container, it must be a small issue with mjml 3 migration tool.

**Comment by EECOLOR** [comment]
Version `4.6.3` does not have this issue. Since this is a minor version step it will cause problems in production systems as soon as they run a `yarn/npm install`.

**Comment by iRyusa** [comment]
Yes, it shouldn't happen I don't know why yet we'll investigate (mjml migrate should be removed soon). 

But the simple fix is just to remove `mj-container` as MJML 3 syntax is deprecated for almost **3 years**.

**Comment by EECOLOR** [comment]
Most of our applications live longer than 3 years and we spend effort on these things when it is needed. We however need to plan it in advance (the example is simplified, and in reality it's multiple templates in multiple projects). That said, I understand your stance on the matter.

**Comment by iRyusa** [comment]
https://github.com/mjmlio/mjml/commit/34488432b482b1d552decfd65d444ac405a579ae#diff-68b2b292976d69a635de462e6fedb491L28-R28 this is the culprit cc @DRoet can you revert this line ?

**Comment by DRoet** [comment]
@iRyusa sure, https://github.com/mjmlio/mjml/pull/2041

**Comment by EECOLOR** [comment]
Awesome support! Puts a smile on my face, thank you very much!
