### ISSUE TITLE
Update try-it-live editor to 4.7

### ISSUE THREAD

**Issue by jayhybrid** [mjmlio/mjml#2043]
I'm not familiar with the general workflow of software releases so please do not take my question wrong but the [try-it-live editor](https://mjml.io/try-it-live/) still seems to be running 4.6.3 can it be updated to 4.7?

**Comment by iRyusa** [comment]
It should be done soon, we're just checking that the new "auto" generated doc works properly first

**Comment by jayhybrid** [comment]
Great, thanks! I look forward to it!
