### ISSUE TITLE
Text not rendering / invisible but copy&pasteable (using mailjet's API?)

### ISSUE THREAD

**Issue by Syncriix** [mjmlio/mjml#2045]
**Describe the bug**
Text is not rendered (Either Invisible or maybe rendered behind the background?)

**To Reproduce**
1. Create a file with this MJML code: 
[Main.zip](https://github.com/mjmlio/mjml/files/5295510/Main.zip)
2. Copy HTML to Clipboad / Export to HTML
3. Use Mailjet's API to send the email trough python
[digest_creator - Copy.zip](https://github.com/mjmlio/mjml/files/5295527/digest_creator.-.Copy.zip)
(CRTL+F(ind all the 4 "##" and enter your keys + emails))
The MJML code above is already copied in to the python file - no need to do that again
4. See the error

**Expected behavior**
Text to be visible?

**MJML environment (please complete the following information):**
 - OS: Win10 latest
 - MJML Version 4.6.2
 - MJML App 3.0.2

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: MailJet

**Affected email clients (for rendering issues):**
All tested: Mozilla, SOGo, Roundcube

**Screenshots**
How it looks on the two Editors:
[Imgur](https://i.imgur.com/EfydWie.png)
How it looks once it's in the client's inbox
[Imgur](https://i.imgur.com/aLSQaGo.png)

**Additional context**
I might be totally wrong to post this here -  I don't know if the issues comes from mailjet, MJML or the loop. Probably it's just me in the end. Oh yeah, you can copy paste the invisible text so it is there - just not rendered.
I can not reproduce the invisible text by sending the copy+pasted html directly, it only happens after using the for lop from mailgun (at least I guess that is what could be the cultpit)

**Comment by iRyusa** [comment]
Zip are corrupted on my machine can't you just paste the mjml on try it live please `https://mjml.io/try-it-live` 

It might be a `font-size` / `line-height` missing somewhere ? Can you check the email on gmail to see if it's related to the client you're using (roundcube and SOGO aren't tested, and for mozilla i guess you're talking about thunderbird) ?

**Comment by Syncriix** [comment]
@iRyusa
The Zip's work fine for me, just download WinRar to unpack them.

I have defined font size and line height in a mj-class and there is text that displays well with that class inherrited - so I'd take a wild guess and say that that isn't the problem.

**Comment by iRyusa** [comment]
Can you just upload them to the try it live please : )

**Comment by Syncriix** [comment]
You might have missed the edit, already done

**Comment by Syncriix** [comment]
I have uploaded the pythonscript to 0bin for you: https://0bin.net/paste/mwS0AvET#N6I6YST3L5ogsGWVfyxyiesescNEhpHIgdzb3yE-1O/
Expires in 1 day

**Comment by iRyusa** [comment]
You have a lot of font-size without unit, that's why it doesn't works. Just add `px` to most of them and the text will appears
