### ISSUE TITLE
Option to export HTML as "fragment" rather than a full E-Mail

### ISSUE THREAD

**Issue by My1** [mjmlio/mjml#2048]
**Is your feature request related to a problem? Please describe.**

When creating an MJML it is always in the context of being an entire e-Mail. when crafting using MJML for a signature/mail footer or similar cases this might get a little problematic as when pasting the exported HTML at the end of an existing email there would be multiple html/head/body elements.

**Describe the solution you'd like**
a way to convert not to a "full" e-mail, but rather just some code you can throw into an existing email (basically no html, body or head, elements).

**Describe alternatives you've considered**

honestly not sure of what better alternatives there may be.

**Comment by ngarnier** [comment]
This is not possible as some responsive styles have to be added to the head of the email.

Furthermore, MJML's approach isn't really compatible with email signatures as it uses a fixed-width centered container on desktop.
