### ISSUE TITLE
No work grid - <mj-column>

### ISSUE THREAD

**Issue by thefubon** [mjmlio/mjml#2050]
Hey. <mj-column> doesn't work for me. I do everything as indicated in the documentation. Pointed in the screenshots.

<img width="2560" alt="Снимок экрана 2020-10-05 в 12 54 55" src="https://user-images.githubusercontent.com/43171309/95065672-0d59fa00-070a-11eb-9755-2a581cf81cf2.png">
<img width="2323" alt="Снимок экрана 2020-10-05 в 12 54 46" src="https://user-images.githubusercontent.com/43171309/95065679-0f23bd80-070a-11eb-8f94-e230e02c9243.png">

**Comment by iRyusa** [comment]
I don't think Yandex does support media queries so it display the mobile version instead as MJML is mobile first.

Nothing we can really do about this
