### ISSUE TITLE
c.isRawElement is not a function

### ISSUE THREAD

**Issue by frontendwizard** [mjmlio/mjml#2052]
**Describe the bug**
I'm trying to create a component but after I register the basic component example, I get this error message when trying to generate the HTML:
`c.isRawElement is not a function`

**To Reproduce**
1. register the MjBasicComponent from the example
1. Render a mjml template to HTML
1. See error

**Expected behavior**
Component registered and html being generated.

**MJML environment:**
 - OS: macOS
 - MJML Version 4.7.1
 - MJML cli

**Comment by iRyusa** [comment]
Well the issue isn't in the right repository as it seems to be with the boilerplate.

I've just cloned it and everything works fine for me ? Did you clean your `node_modules` first ?

**Comment by frontendwizard** [comment]
I believe I'm missing the piping through babel step, I'm gonna try that.

**Comment by frontendwizard** [comment]
It most likely was a problem of how I transpiled the component.
