### ISSUE TITLE
Does the API always use the newest MJML Version?

### ISSUE THREAD

**Issue by grandeljay** [mjmlio/mjml#2053]
I've never really worked with an API before, so please excuse if I'm missing something obvious but is there a way to determine which MJML version the API is currently referring to?

**Comment by iRyusa** [comment]
Just check the payloard returned by the api you have a `mjml_version` returned https://mjml.io/api/documentation/

**Comment by grandeljay** [comment]
I checked it and it returned `4.6.1` can this be changed?

**Comment by marcbelletre** [comment]
I'm using the API and I get different results using the Try it live editor which is 4.7.0 and the API which is 4.6.1. Actually the columns layout breaks in the Gmail web app when I render from the API so I can't use it anymore.  

Is there any plan to update the API version?

Thanks for the great work ;)

**Comment by iRyusa** [comment]
There's no structural change inbetween 4.6 & 4.7 so I highly doubt it's a version issue here. But yes, API is upated when we think that the version is stable enough.

**Comment by marcbelletre** [comment]
You're right. I spent the morning trying to figure out why I had differences between the two versions and I found out right after posting here. I messed up with the head tag. Anyway sorry for the mistake and thank you for the quick answer!
