### ISSUE TITLE
Width percentage on mj-image

### ISSUE THREAD

**Issue by stefandevo** [mjmlio/mjml#2054]
**Describe the bug**
If setting width percentage like 50% in mj-image, it takes 50px

**To Reproduce**
```
 <mj-image width="100%" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" />
```

**Expected behavior**
Percentage is used instead of px.

Default setting for image is 100% like docs says:
https://mjml.io/documentation/#mj-image

**Comment by iRyusa** [comment]
Linter does warn you that image should be defined in px and not in percent (px is the only unit listed on mj-image doc too)

**Comment by stefandevo** [comment]
Ok, but
<img width="741" alt="Screenshot 2020-10-07 at 18 49 24" src="https://user-images.githubusercontent.com/1656051/95362083-dd5b5400-08cd-11eb-90bc-9bd1a3d4e333.png">
Says default: 100%

**Comment by iRyusa** [comment]
It’s 100% of it’s container by default cf https://mjml.io/try-it-live/rys-f_sLv

**Comment by stefandevo** [comment]
Understand that; but how to set the image for example to 50% off the container centered?

**Comment by iRyusa** [comment]
Relative size doesn’t behave properly in some clients just set it as px and it will be fine if your column does 300px then 150px & align center ?

**Comment by iRyusa** [comment]
Feel free to open a PR if you find the doc confusing but I'm closing as stated by the linter and the doc image in percent aren't supported.
