### ISSUE TITLE
support partial like structures

### ISSUE THREAD

**Issue by st-h** [mjmlio/mjml#2055]
**Is your feature request related to a problem? Please describe.**
We are using a generic footer for our emails. However this footer contains one line of text, that changes depending on the mjml file where it is used: "You are receiving this email because.... "

**Please note**: This is not a request to reinvent the templating wheel. We are using handlebars to personalise our emails. However, this is not about personalisation, as the same mjml file will always contain the exact same footer. But multiple templates share a common subset of the footer (essentially the whole footer, excluding that one sentence)

**Describe the solution you'd like**
I would like to see a way where we could include an mjml file while being able to specify some content. For instance:
```
<mj-include path="footer.mjml">You are receiving this email because you opened a GitHub issue</mj-include>
```
`footer.mjml:`
```
<mj-section>
  <mj-column>
    <mj-text color="#e0dcdc" font-size="12px">
      <mj-yield />
    </mj-text>
    <mj-text color="#e0dcdc" font-size="12px">
      company info stuff
    </mj-text>
  </mj-column>
</mj-section>
```

The `<mj-yield/>` tag would specify where to insert the content specified in the `<mj-include> </mj-include>` tag.

**Describe alternatives you've considered**

**copy and paste**: always works, always a hassle to maintain
**custom components**: Looks way overkill for such a simple issue
**move this to the templating stage**: This will inevitably make our business logic responsibility for choosing the right text to insert, which is just unnecessarily error prone
**zurb foundation for emails**: Been there, they have good support for such things, but too many rendering issues (probably due to the lack of development within the last years) and a few other issues - don't want to go back

**Comment by IanEdington** [comment]
A custom component would work for this situation, although they are fairly verbose.

I like the idea of a mj-yield component but I don't know how useful a single yield would be.

The custom components are very powerful but not easy to use. I wonder if investing in making custom components easier to use would be a better use of time than building another way of doing the same thing

ref custom components: https://mjml.io/documentation/#creating-a-component

**Comment by st-h** [comment]
> I like the idea of a mj-yield component but I don't know how useful a single yield would be.
 
Yes, this is a valid concern. For simple cases like mine, this would be really helpful. But for complex things using a custom component probably is more appropriate, because allowing multiple yields always gets more complex. But, if the input is not limited to simple strings and one could insert a whole block like:

```
<mj-include path="footer.mjml">
   <mj-section>
      ... now there is a way to insert complex stuff
   </mj-section>
</mj-include>
```

this would allow for a lot of things - except specifying two totally independent locations (like insert this block at the top, and that at the bottom)

Making custom components easier to use would be totally awesome. But then, If I would put that into a component, I would pretty much just try to create something, which would allow me to yield a string to the component - which I think could be solved in a more reusable way.

**Comment by iRyusa** [comment]
With current `mj-include` implementation there's no way it could receive something like that, I'm not even sure that we would be able to keep existing feature of mj-include with a "yield" feature. 

Component like mj-text are considered as ending tag, so even if `yield` would exist it won't be replaced too.

**Comment by st-h** [comment]
@iRyusa thanks for chiming in. I haven't had a chance to look at the source yet, but I suspected it would likely be more complex than it looked. Seemed simple: At an early stage it would just need to take the stuff inside the block and replace the `<mj-yield>` tag with that. But that involves a lot of assumptions about how things currently work. Is there any chance this can be easily added by providing a new tag other than `<mj-include>`?

**Comment by iRyusa** [comment]
You can still do a custom component that does exactly what you want here. But I doubt it would come as a "standard" component as we want to avoid accessing file system in component.

**Comment by st-h** [comment]
@iRyusa please feel free to close this issue if this is not feasible as a standard component. I am just a little surprised that something similar isn’t more often needed. Having a customizable footer seems a pretty common case - but maybe it is more common to implement custom components than I assumed.

**Comment by IanEdington** [comment]
```
import { BodyComponent } from 'mjml-core';

const dependencies = require('mjml/lib/dependencies');

export default class CompanyFooter extends BodyComponent {
  static dependencies = {
    'mj-body': ['company-footer'],
    'mj-wrapper': ['company-footer'],
	// tells mjml-verify that the company-footer can take any elements mj-text can take
    'company-footer': dependencies['mj-text'],
  };

  render() {
	// renderMJML allows rendering mj components rather than dom elements
    return this.renderMJML(this.renderContent());
  }

  private renderContent() {
    return `
      <mj-section>
        <mj-column>
          <mj-text color="#e0dcdc" font-size="12px">
			<!-- not sure why you need rawXML but we found it doesn't work without it -->
            ${this.renderChildren(this.props.children, { rawXML: true })}
          </mj-text>
          <mj-text color="#e0dcdc" font-size="12px">
            company info stuff
          </mj-text>
        </mj-column>
      </mj-section>
    `;
  }
}
```

**Comment by iRyusa** [comment]
I'm closing because I think there won't be anything standard in MJML for that, if you don't need a browser build you can just require file on the fly in a custom component too
