### ISSUE TITLE
MJML Syntax Highlighting In JavaScript?

### ISSUE THREAD

**Issue by mikefisher84** [mjmlio/mjml#2057]
When building an email template with an MJML template string I'd like to use dynamic data from other javascript files. I can do this fine but its difficult to edit the mjml template with no syntax highlighting

**Describe the solution you'd like**
I would like MJML syntax highlighting for template strings in VSCode

**Describe alternatives you've considered**
Use .mjml files with handlebars but have a reduced developer experience. 

**Additional context**
Other languages seem to be able to automatically turn on syntax highlighting when using a function to parse its template string. 

Example:
This template string prefixed with `gql` would get syntax highlighting in vscode

```js
import gql from 'graphql';

const query = gql`
  query {
    getUsers();
  }
`;
```

**Comment by iRyusa** [comment]
This is not the proper repository for that. Please open an issue here https://github.com/mjmlio/vscode-mjml
