### ISSUE TITLE
Text-background inside a button is slightly different from button background

### ISSUE THREAD

**Issue by DanielO1403** [mjmlio/mjml#2064]
Hey everyone, (First Post, sorry in advance for all my blog-ettiquette/wrong-info related mistakes)

I wanted to know if there's a way to remove the little text-background present on a button if one introduces alpha value to an rgb background color, for a button specifically. I'd like to know if it's posible to disable that text-specific background and work with the button-background color only.

Here's my code:

```
<mjml>
  <mj-head>       
    <mj-attributes>     
      <mj-class name="cta2" align="left" padding="10px 0px" background-color="rgba(0, 0, 0, 0)" border-radius="25px" font-weight="bold" inner-padding="10px 30px" color="#ffffff" border="2px solid #ffffff"/>
      
      <mj-all font-family="Montserrat, Verdana, Sans-Serif"/>            
      <mj-font name="Montserrat" href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" />   
      </mj-head>
  
  
  <mj-body>
   <mj-hero>      
    <mj-button mj-class="cta2" padding="50px 0" href="#" align="center" font-size="24px" background-color="rgba(0, 0, 0, 0.6)">CONOCE SKANDIA</mj-button>  
   </mj-hero>
  </mj-body>
 </mjml>
```

and also here are some reference screen-shots

<img width="231" alt="Captura de Pantalla 2020-10-20 a la(s) 11 31 05 a  m" src="https://user-images.githubusercontent.com/73188617/96616737-598b6980-12c8-11eb-8f5f-d1b72fd4e2db.png">
<img width="361" alt="Captura de Pantalla 2020-10-20 a la(s) 11 34 14 a  m" src="https://user-images.githubusercontent.com/73188617/96616743-5abc9680-12c8-11eb-8616-bcc10535241f.png">

Thanks in advance for any help :) !

**Comment by iRyusa** [comment]
`mj-button` doesn't support rgba colors as the color is applied multiple times to ensure it renders/fallback properly.

If you really want to keep it like that you can do a small css rule that override the background color on the `a`

```xml
<mj-style inline="inline">a { background: none !important;}</mj-style>
```

**Comment by DanielO1403** [comment]
Thanks Maxime!

Works perfectly.
