### ISSUE TITLE
Border-radius (mj-section, mj-button)

### ISSUE THREAD

**Issue by OReshetnikov** [mjmlio/mjml#2065]
**Describe the bug**
Border-radius works incorrect in <mj-section> and <mj-button> tags in the MS Outlook

**To Reproduce**
Steps to reproduce the behaviour:
https://mjml.io/try-it-live/ryhGvDTPw
Send the rendered HTML and open it in the MS Outlook

**Expected behaviour**
The border-radius should work the same as on other email clients

**MJML environment:**
OS: Windows
MJML Version 4.6.3

**Affected email clients (for rendering issues):**
 - MS Outlook desktop version

**Comment by iRyusa** [comment]
Outlook doesn't support border-radius, you can do something like that with VML but it can't be nested and add a whole new level of complexity.
