### ISSUE TITLE
Thunderbird removes columns

### ISSUE THREAD

**Issue by m-kaddatz** [mjmlio/mjml#2068]
**Describe the bug:**
Thunderbird removes columns since the newest update. (78.4)

**To Reproduce**
Just create a template with columns and send it to a Thunderbird client.

**MJML environment**

OS: [Windows]
MJML Version [4.2.0]
MJML tool used [VSC Extension / 1.6.0]
send via Litmus / Mailchimp

**Comment by iRyusa** [comment]
Well, thunderbird adds a new "security" feature that strip media queries, as for now you can disable it locally but there's nothing  we can do to prevent that behavior.
https://bugzilla.mozilla.org/show_bug.cgi?id=1530106

I know that's not the reply you're hoping for, but you should fill a ticket on thunderbird side so they maybe looks a bit closer at this.

**Comment by m-kaddatz** [comment]
Thanks for respond. So, is there a reason why the "desktop-width" is defined in the media-query instead of inline?

**Comment by ngarnier** [comment]
@m-kaddatz MJML is mobile-first as it's the best approach to ensure responsive support across the widest range of email clients. This article is quite outdated but the description about responsiveness in "The Approach" section still stands, if you're curious: https://www.smashingmagazine.com/2017/01/making-responsive-html-email-coding-easy-with-mjml/

**Comment by ngarnier** [comment]
I'm reopening as even if it's not a bug related to MJML but Thunderbird, it's good to track. 

Though I don't really like the idea of adding this to MJML and rather hope Thunderbird will fix this, @M-J-Robbins shared a potential workaround on Twitter: https://twitter.com/M_J_Robbins/status/1334091297435639808.

**Comment by Pharmasolin** [comment]
There are few examples how thunderbird can be targeted https://howtotarget.email/ may be it worth replace owa feature with fix for thunderbird in mjml v5 if thunderbird wouldn't revert their change?

**Comment by iRyusa** [comment]
This has been released I think !

**Comment by starchild** [comment]
> This has been released I think !

What has been released - still an issue as far as I can see?  Crazy to think that thunderbird would link this a feature and not a fault.

**Comment by iRyusa** [comment]
We did add a special style block targetting only thunderbird to apply the desktop version

**Comment by hayden-t** [comment]
Is this still broken or fixed ? As im using the builder at https://mjml.io/try-it-live and my columns are still stacking in thunderbird. thanks.

**Comment by hayden-t** [comment]
actually it came good, so must be fixed
