### ISSUE TITLE
Responsive problems facing mail gmail

### ISSUE THREAD

**Issue by akacha** [mjmlio/mjml#207]
Good afternoon, I am creating a responsive email with mjml which works perfect, but when viewed on the app gmail, it is not seen in the respective columns for which it was designed, the query is to see how I fix that is displayed correctly in both native mobile application and the app offers gmail

Thanks for the help

**Comment by erochersimplicite** [comment]
Hello @akacha maybe you have the same problem as some people with "App for work" if you want more details  watch for this issue --> https://github.com/mjmlio/mjml/issues/24 <--

**Comment by akacha** [comment]
Thank you! and I will review :)

**Comment by akacha** [comment]
That solution is to gmail desktop, but my problem is with the mobile app for both Android and iPhone that does not take 2-column layout, but shown in 1, any idea how to fix it?

**Comment by ngarnier** [comment]
Hey @akacha, can you please provide us with your `mjml` code and screenshots of the issue? 

Cheers!

**Comment by akacha** [comment]
Sure! 


In cases of a single column fits perfect in the cell but where two-column text apology to send you the code in a zip overflows but at this point the machine from where I am working is blocked ports for shipping information github


[respaldo.responsive-v2.mjml.zip](https://github.com/mjmlio/mjml/files/242648/respaldo.responsive-v2.mjml.zip)
![img_6250](https://cloud.githubusercontent.com/assets/15241296/14919612/6a55602e-0df3-11e6-977b-9641aa9ca502.jpg)
![img_6251](https://cloud.githubusercontent.com/assets/15241296/14919613/6a6356b6-0df3-11e6-8aeb-869bef665c46.jpg)
![img_6252](https://cloud.githubusercontent.com/assets/15241296/14919614/6a70a870-0df3-11e6-81e1-e03eaf1b45e0.jpg)

**Comment by iRyusa** [comment]
@akacha MJML columns are mean to be stacked on mobile, that's why you can't have 2 columns on mobile yet. 

There's a proposal of `mj-group` in this issue https://github.com/mjmlio/mjml/issues/41 , so closing this one
