### ISSUE TITLE
Outlook 365 - Images Cutted

### ISSUE THREAD

**Issue by baltazaroliveira** [mjmlio/mjml#2074]
**Describe the bug**
Images are cutted. Outlook 365.

**To Reproduce**

MJML CODE

`

    <mj-section padding="0px 100px 0px 100px">
      <mj-column>
      
        <mj-image width="32px" height="32px" src="https://www.heliotextil.com/pac_si/imgs/instagram.png" href="https://instagram.com/heliotextil"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image width="32px" height="32px" src="https://www.heliotextil.com/pac_si/imgs/facebook.png" href="https://facebook.com/heliotextil"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image width="32px" height="32px"  src="https://www.heliotextil.com/pac_si/imgs/twitter.png" href="https://twitter.com/heliotextil"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image width="32px" height="32px" src="https://www.heliotextil.com/pac_si/imgs/linkedin.png" href="https://linkedin.com/company/heliotextil"></mj-image>
      </mj-column>
      <mj-column>
        <mj-image width="32px" height="32px" src="https://www.heliotextil.com/pac_si/imgs/youtube.png" href="https://www.youtube.com/HeliotextilPortugal"></mj-image>
      </mj-column>
    </mj-section>
`

2. Render it to HTML by doing

![image](https://user-images.githubusercontent.com/953742/97964861-5b1d5d00-1db1-11eb-8dc8-625bf782e893.png)

![image](https://user-images.githubusercontent.com/953742/97964482-bef35600-1db0-11eb-9f05-bddcd220f900.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/953742/97964531-d3cfe980-1db0-11eb-98f8-23c303b6d865.png)

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]

Windows

 - MJML Version [e.g. 4.2.0]

Latest

 - MJML tool used [e.g MJML App]

MJML App

**Comment by iRyusa** [comment]
`mj-image` does have a default padding that "squish" your image to 30px, on dekstop it looks almost fine (the ratio isn't respected as you've defined `height`.

Either remove completely  padding left & right on `mj-image`, use `mj-social`, or use `mj-social` instead.

(You should update your MJML App, you're missing a lot of fixes)

**Comment by baltazaroliveira** [comment]
Sorry for late reply.

I have the same problem (tested also with mj-social)

![image](https://user-images.githubusercontent.com/953742/105518331-11695200-5cd0-11eb-84d2-4cf7cdc3aba5.png)

Can you help?

If I don't define height stays like that

![image](https://user-images.githubusercontent.com/953742/105518530-4f667600-5cd0-11eb-80cc-2f180cbb4cd8.png)

Now with this engine

![image](https://user-images.githubusercontent.com/953742/105518574-5ee5bf00-5cd0-11eb-83fb-2068749dad23.png)

**Comment by iRyusa** [comment]
I think height=auto doesn't work in Outlook 365, it's a bit weird because I can't recall having any issue with any template on this.

Mj-social has a `icon-size` attribute that ensure square icon have both width and height set.

**Comment by baltazaroliveira** [comment]
I have discovered setting cellpadding solves the problem, but having difficulty to set that option in MJML.
