### ISSUE TITLE
Add attribute to disable vml background image with mj-section

### ISSUE THREAD

**Issue by singdavid** [mjmlio/mjml#2075]
**Is your feature request related to a problem? Please describe.**
Using background image in mj-section is causing other mj-section to move on outlook

**Describe the solution you'd like**
Possibility to have an attribute to disable vml for background image

**Describe alternatives you've considered**
I removed the vml nodes using some regex in my code

**Additional context**
We prefere to not show any background instead of having vml images issue on some email

**Comment by iRyusa** [comment]
> Using background image in mj-section is causing other mj-section to move on outlook

Can you show that issue ? Because I never saw that behavior on EOA with background image?

As we want to avoid client-specific attributes as much as we can, I'm not really fan of this.

**Comment by chasegiunta** [comment]
@iRyusa I'm currently experiencing a similar issue with using a background-url on `mj-wrapper` (I assume it's a similar issue as `mj-section`) where having a background-url added is causing padding problems solely on Outlook for Windows. Seemingly, there's no way to get left-padding to work. It's wrapping everything in `</v:textbox> </v:rect>`. If I had the option disable background-url on Outlook for Windows, that would help tremendously.

**Comment by iRyusa** [comment]
VML does apply both padding left and right to the right for some unknown reason when nesting more than 1 table. 

I'm not really a big fan of adding another level of complexity where you have to decide if you want to have X or Y thing in Z client.

You can most likely avoid this by restrict column size by the amount of the padding and it would work fine in desktop i guess ?

**Comment by chasegiunta** [comment]
@iRyusa I mean, there's 18 columns within various sections throughout the wrapper on this email. The proposed solution is to do the math for each of these respective columns to figure out how to get left & right padding on the entire wrapper?

Respectfully, not only is that adding way more complexity for the developer in template code (and I'm still having to decide if I want to do this column math, X Y in Z client, if I want to use a background image) there's already Outlook specific attributes, like `owa`, and isn't Outlook the _main_ caveat with email building anyways, given it's complex table layout requirements?

I understand the hesitation to add exceptions for _every_ client, but there's already several noted caveats regarding Outlook in the documentation already, and the main draw for MJML (in my naive opinion) is that it tackles email design in Outlook almost perfectly.

**Comment by iRyusa** [comment]
> The proposed solution is to do the math for each of these respective columns to figure out how to get left & right padding on the entire wrapper?

You could add ghost columns to the size of your padding too, it's not that big of an effort too here.. You could also just inline a background-image, then the VML won't be generated and most of clients would renders it fine. 

OWA was the only "client" specific attribute and will be deprecated as it's no longer needed (and imo it wasn't the best solution). If we start to add client specific attribute then it will be a mess to maintain AND document.

**Comment by chasegiunta** [comment]
@iRyusa Ghost columns may work, but _woof_ lol, talk about complexity (sorry to be so blunt about this). Inlining the background image won't work because the child table inherits, and explicitly sets, the background color from the wrapper, thus blocking the background image.

**Comment by iRyusa** [comment]
It's not like you'll have to edit manually HTML here. 

When you inline background image you can just specify a proper css selector that will target the node :  https://mjml.io/try-it-live/rJDQNldiP

**Comment by chasegiunta** [comment]
Thanks @iRyusa setting the background image on the table, rather than the containing div looks like it's going to work. Appreciate your help.
