### ISSUE TITLE
Email appears good in gmail, web outlook, but not in desktop outlook

### ISSUE THREAD

**Issue by georgesbc** [mjmlio/mjml#2078]
Hello,

I am new to mjml, using it to prepare a newsletter campaign in mailjet.

The email appears right in gmail and web outlook, however in desktop outlook, it takes the full screen width, and the photos at the bottom of the email aren't one next to the other, but above (eventhough I use GROUP).

In the code below I removed the photos and the weblinks

MJML code Used
https://mjml.io/try-it-live/HkPmkpMFD

MJML version:
mailjet version - 4.6.3

Email clients the bug is seen on:
Outlook - office 365 ProPlus - version 1902

Thank you for the help

**Comment by iRyusa** [comment]
How did you send your test email, can you share some screenshot of the issue ? As it looks fine on Email On Acid and with default templates : 
 
![image](https://user-images.githubusercontent.com/570317/98366912-0722aa80-2035-11eb-92e6-2da36f0aebb0.png)

**Comment by georgesbc** [comment]
Thanks for the reply.

The email was sent using the TEST email in mailjet campaign (envoyer un email de test)

below screenshot1 of the bottom of the email in outlook. (screenshot2 is gmail)
As you can see the wrapper borders have the same width as the screen
and the social media icons aren't aligned

![Capture1](https://user-images.githubusercontent.com/10071784/98368318-713c4f00-2037-11eb-82df-b73476c711c3.JPG)


GMAIL
![Capture2](https://user-images.githubusercontent.com/10071784/98368327-74cfd600-2037-11eb-90af-d2f12c90f817.JPG)

**Comment by iRyusa** [comment]
It's weird that your container goes to full width here, can you try with a minimal template like https://mjml.io/try-it-live/templates/racoon, I doubt Mailjet is altering the HTML here ?

**Comment by georgesbc** [comment]
same result with Raccon mail.
I copied the model in my mailjet and sent a test mail to outlook.

the email has the screen width, and all the photos are one above the other

**Comment by iRyusa** [comment]
Can you try with https://putsmail.com/ to send the racoon mail ?

**Comment by georgesbc** [comment]
UPDATE

indeed, my email code is good.

The issue is with my outlook.

My mailjet emails go to a folder named "Newsletter".

When they go to the inbox, the format is good.

I guess that outlook messes with the format when moving the email from inbox to newsletter.

Sorry for the inconvenience and that you for the support.

**Comment by ngarnier** [comment]
Ugh, the fact that Outlook would mess with the HTML of the email when placing it into a folder really mesmerizes me (luckily it's nothing new from Outlook). Thanks for sharing @georgesbc.
