### ISSUE TITLE
Comments at the top of a .MJML file don't get compiled in the .HTML

### ISSUE THREAD

**Issue by emilianog94** [mjmlio/mjml#2079]
**Describe the bug**
If you write comments at the top of the file, the comments don't show in the final compiled HTML file.

**To Reproduce**
1. Create a file with this MJML code: 

```
<!-- This is a test comment -->

<mjml>
 <mj-body>
        <mj-section>
            <mj-column> 
                <mj-text>
                        Lorem Ipsum
                </mj-text>
            </mj-column>
        </mj-section>
</mj-body>
</mjml>

```
2. Render it to HTML
3. The rendered file doesn't keep the comments at the top

**Expected behavior**
Comments should be kept in the .HTML file?

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML tool used: MJML VSCode Official Extension (https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml)

**Screenshots**
.MJML file: https://i.imgur.com/GttiULc.png
.HTML file: https://i.imgur.com/jY1fJEi.png

**Additional context**
CMS's like Magento need to have html comments before any sort of code in its email templates in order to both work properly and store variables. At this moment i am manually copying the comments in the final HTML file.

**Comment by iRyusa** [comment]
Yeah this is by design I doubt we'll be able to do something about this as everything outside MJML isn't parsed as we use XML mode...

**Comment by kmcb777** [comment]
Indeed, even if there was a solution to have this parsed, the root of the mjml parsed as json is supposed to always be a single tag, it's not an array, and changing this would require a lot of changes

**Comment by steepho** [comment]
Put the comment in a `<mj-raw> ` element.
