### ISSUE TITLE
Include documentation/examples for subclassing base components

### ISSUE THREAD

**Issue by joeyfigaro** [mjmlio/mjml#208]
I was looking to throw this into a project at work and had about a 30 minute window to get up and running. Unfortunately, I wasn't able to subclass the base components to add the project-specific inline styles within that time, so I had to abandon it for the time being. 

Would be fantastic if there were examples that showed how to subclass something like the `MJ-SECTION` component to add css properties/values. The example should walk through the whole process, and ideally include steps to have mjml use the subclassed `MJ-SECTION` over the default one that it ships with.

In case it helps, this is where I was when the 30 minute window was up...you can see a few of the places that could use DRYing up:
```html 
<mj-body width="415px" background-color="#FCF9F6">
    <mj-section>
        <mj-column>
            <mj-divider border-width="1px" border-style="dashed" border-color="#979797"></mj-divider>
            <mj-text font-size="20px" font-weight="bold">Ordering Is Open!</mj-text>
            <mj-divider border-width="1px" border-style="dashed" border-color="#979797"></mj-divider>
        </mj-column>
    </mj-section>

    <mj-section>
        <mj-column>
            <mj-text>Hi, <%= @user.name %></mj-text>
            <mj-text>The market just opened for the week, and we wanted to show you a little of what you’ll be getting! Remember that <strong>ordering closes at 12 AM this Sunday.</strong></mj-text>
            <mj-divider border-width="1px" border-style="dashed" border-color="#979797"></mj-divider>
        </mj-column>
    </mj-section>

    <mj-section>
        <mj-column>
            <mj-text><img src="<%= image_url('email/top-zigzag-border@2x.png') %>" width="100%"></mj-text>
            <mj-table>
                <tr></tr>
            </mj-table>
        </mj-column>
    </mj-section>
</mj-body>
```

Also, `MJ-BODY` is a potential candidate for subclassing to include that width and background-color, as well. We've got tons of templates and all of their `MJ-BODY` components use the same styles.

**Comment by ngarnier** [comment]
Hey @joeyfigaro, I believe https://github.com/mjmlio/mjml/pull/249 solves your issue by allowing you to set default styling in the head?

**Comment by iRyusa** [comment]
I think `mj-attributes`is what you were looking for. So I'm closing this one
