### ISSUE TITLE
Center alignment not applying to Gmail iOS (2-col section)

### ISSUE THREAD

**Issue by james1-qa** [mjmlio/mjml#2080]
Hopefully someone can help me with this 😀

I've got a 2 column section with images 50% width each on desktop, on mobile they stack vertically. Testing on a range of clients and it's just the Gmail app for iOS that doesn't seem to be working correctly (see image below)

This is how I want it to look https://mjml.io/try-it-live/SkJf3ZmYv and how it looks on other devices including the Gmail android app 

Can anyone help? Tried a few things with alignment and minifying the code but it doesn't seem to help

![image](https://user-images.githubusercontent.com/43765601/98398533-069c0b00-2059-11eb-8bff-4d3d1c4d9c21.png)

`<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="center" color="#2B2B2B" />
      <mj-section background-color="#fff" />
    </mj-attributes>
  </mj-head>
  <mj-body background-color="#fff">
    <mj-section>
      <mj-column padding-left="15px" padding-right="15px">
        <mj-text align="left" font-size="36px" font-weight="bold">Lorem ipsum dolor sit amet</mj-text>
        <mj-image href="https://placeholder.com" src="https://via.placeholder.com/150x75"></mj-image>
        <mj-text align="left" font-size="20px" font-weight="1">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat</mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#990033">
      <mj-column padding-left="25px" padding-right="25px">
        <mj-text color="white" font-size="15px">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</mj-text>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-text font-size="36px" font-weight="bold" padding-bottom=0>test test test</mj-text>
      </mj-column>
    </mj-section>
    <mj-section padding-left="80px" padding-right="80px" padding-top="0">
      <mj-column width="50%" padding-top="10px">
        <mj-image src="https://via.placeholder.com/150x75" padding="5px"></mj-image>
        <mj-social font-size="14px" icon-size="20px" mode="horizontal" align="left" padding="0">
          <mj-social-element src="http://link.lg.com/custloads/765000807/md_1003489.jpg"> @testtest </mj-social-element>
        </mj-social>
      </mj-column>
      <mj-column width="50%" padding-top="10px">
        <mj-image src="https://via.placeholder.com/150x75" padding="5px"></mj-image>
        <mj-social font-size="14px" icon-size="20px" mode="horizontal" align="left" padding="0">
          <mj-social-element src="http://link.lg.com/custloads/765000807/md_1003489.jpg"> @testtest </mj-social-element>
        </mj-social>
      </mj-column>
      <mj-column width="50%" padding-top="10px">
        <mj-image src="https://via.placeholder.com/150x75" padding="5px"></mj-image>
        <mj-social font-size="14px" icon-size="20px" mode="horizontal" align="left" padding="0">
          <mj-social-element src="http://link.lg.com/custloads/765000807/md_1003489.jpg"> @testtest </mj-social-element>
        </mj-social>
      </mj-column>
      <mj-column width="50%" padding-top="10px">
        <mj-image src="https://via.placeholder.com/150x75" padding="5px"></mj-image>
        <mj-social font-size="14px" icon-size="20px" mode="horizontal" align="left" padding="0">
          <mj-social-element src="http://link.lg.com/custloads/765000807/md_1003489.jpg"> @testtest </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

**Comment by iRyusa** [comment]
You have 200% of content inside your section Split the last 4 column into 2x2.

It looks like something alter the body width here, but I can't reproduce with the given exemple. Everything looks fine on Email On Acid and on device. How did you send your test email ?

**Comment by james1-qa** [comment]
Ah yeah I see the 200% content now,

Thanks for checking, we are using Emarsys so the email is integrated with it, must be an issue with that.

Thank you for your help!
