### ISSUE TITLE
Mjml + Less + BrowserSync

### ISSUE THREAD

**Issue by GurovDmitriy** [mjmlio/mjml#2081]
Hello. Can I set up a co-build Mjml + Less + BrowserSync?
```
build/           => min html

src/
    less/        => less block
    mjml/        => mjml
    index.html   => compil mjml no minify
```

**Comment by iRyusa** [comment]
There's no support for less/sass built in MJML. However this can be added with custom head component. You can just watch your files with mjml-cli and watch the output folder with browser sync.
