### ISSUE TITLE
Documentation Guide

### ISSUE THREAD

**Issue by GurovDmitriy** [mjmlio/mjml#2082]
![Screenshot_1](https://user-images.githubusercontent.com/26795848/98441519-f004bb00-210f-11eb-847f-f82459a8d06d.png)
![Screenshot_2](https://user-images.githubusercontent.com/26795848/98441520-f135e800-210f-11eb-9115-8a5ce87be338.png)
![Screenshot_3](https://user-images.githubusercontent.com/26795848/98441522-f135e800-210f-11eb-92c4-12f093cfec61.png)

On page:
[mjml.io/documentation/](https://mjml.io/documentation/#mjml-guides)

code:
```
<!-- Image Header -->
  <mj-section background-url="https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg"
              background-size="cover"
              background-repeat="no-repeat">

    <mj-column width="600px">

          <mj-text  align="center"
                color="#fff"
                font-size="40px"
                font-family="Helvetica Neue">Slogan here</mj-text>

      <mj-button background-color="#F63A4D"
                 href="#">
        Promotion
      </mj-button>

    </mj-column>

  </mj-section>
```

bug section:
```
<mj-column width="600px">
```

when resizing the block falls out. Width 600 needs to be removed.

**Comment by iRyusa** [comment]
Chrome responsive mode have some issue with this markup, if you just reload the page with the proper resolution it won't scroll. Keep in mind those HTML are meant to be display inside an Email client, it's not as "responsive" as a traditionnal website.
