### ISSUE TITLE
&nbsp; is changed to Â in thunderbird

### ISSUE THREAD

**Issue by ProdigyMaster** [mjmlio/mjml#2084]
**Describe the bug**
Hey 👋 In Thunderbird on Windows & nbsp; is changed to Â in my email. Is there a way to change it? 
In HTML output, the charset is set to UTF-8. 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

**To Reproduce**
https://mjml.io/try-it-live/B1B_nOUYw

**Expected behavior**
Not display Â.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client Thunderbird
 - OS: Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/528501/98514697-2d7d5b80-226a-11eb-870e-1167079f3d85.png)

**Comment by iRyusa** [comment]
Hi,

It's not really related to MJML here so we won't be able to help you on that, sorry.
