### ISSUE TITLE
Addin css-class with border on the mj-column changes layout

### ISSUE THREAD

**Issue by creationell** [mjmlio/mjml#2085]
**Describe the bug**
I am not sure if it is a bug or desired behavior, but when I put a css class that puts border on the element on the mj-column I get only 2 columns in a row and the third one in next row in a 3 column section. 

**To Reproduce**
[try it live code](https://mjml.io/try-it-live/rkDTyRUtP)
Without that class I get 3 columns block as intended. 
[try it live code](https://mjml.io/try-it-live/SkbZmRIKw) 

**Expected behavior**
I would expect that the layout will not be broken by adding a css class that puts only border on the column.

**MJML environment (please complete the following information):**
 - MJML Version 4.7.0

**Comment by iRyusa** [comment]
Well we can't use `box-sizing:border-box;` (https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) because it's not supported everywhere. 

You should remove few px on your columns to make it works as expected
