### ISSUE TITLE
Outlook 2007 + Win 7 does not respect text-align="center"

### ISSUE THREAD

**Issue by symeonreichenberg** [mjmlio/mjml#2086]
I can see strange behaviour of Outlook 2007 (only on the Compatibility test provided by an external company):
![outlook-2007-not-centered](https://user-images.githubusercontent.com/29659643/98683095-ef189700-2364-11eb-9c3c-2ef578537591.png)

As you can see, all Outlooks use this value well, expect of this one. 
text-align="center" attr is used on <mj-wrapper> and on <mj-section>, <mj-text> has an attr align="center". It works on every device. But I can still see the same error only one this one stupid combination Outlook 2007 + Windows 7. I have inspected the code a thousand times and tried everything...

Does anyone know why? Thanks a lot.

**Comment by iRyusa** [comment]
Can you provide the code here https://mjml.io/try-it-live please ?
