### ISSUE TITLE
Wrap images

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml#2089]
Hi!

**Is your feature request related to a problem? Please describe.**
The closing of issue #200 bring us close to cool possibilities, but... There's something still missing. Some email template engines require wrappers. Mautic wants images to be wrapped in a `div`.

**Describe the solution you'd like**
Maybe a `wrap` or `parent` parameter?

**Describe alternatives you've considered**
Use `mj-raw` to create the `div`.

```
         <mj-raw>
          <!-- htmlmin:ignore --><div data-slot="image"><!-- htmlmin:ignore -->
        </mj-raw>
```

**Additional context**
Is that a bad idea?

**Comment by iRyusa** [comment]
`mj-raw` would produce invalid html here. I don't think there's any way to do so without forking the component here. 

It's a really weird very specific issue here :(

**Comment by robsonsobral** [comment]
Yeah... I spent more time looking at Mautic code. It requires almost all of its components to be wrapped in `div`s.

Maybe a super-hyper-power RegEx can do that. Thank you!
