### ISSUE TITLE
problem to install mjml in ubuntu machine

### ISSUE THREAD

**Issue by olebrussels** [mjmlio/mjml#2090]
**Describe the bug**
Hey
I dont manage to install mjml in my ubuntu machine.
npm install mjml does not work

**To Reproduce**
I input "npm install mjml" and i get this error

WARN engine fsevents@2.1.3: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} (c/home/manuel
├── markdown-to-mailchimp@0.5.0 
└── mjml@4.7.1 

**MJML environment (please complete the following information):**
 - OS: [Ubuntu 18.04]

Any ideas of whqat can be the problem? thank you !

**Comment by IanEdington** [comment]
It looks like this is your first issue! Welcome to the MJML community!

It looks like this is an issue with `fsevents` which I thought was a MacOS only optional dependency.

What version of node are you using? I've been having issues with fsevents on node 14

You could also look into installing without optional dependencies `--no-optional`. Usually fsevents is an optional dependency

**Comment by iRyusa** [comment]
If you've installed nodejs through apt then it might be an old version of node. Can you do a `node --version` and try to upgrade to latest node version ?

**Comment by olebrussels** [comment]
@IanEdington  and @iRyusa thanks a lot! my node version is currently v8.10.0.  

A while ago I tried to install this https://github.com/MarcL/markdown-to-mailchimp but i dont know if this is related

**Comment by olebrussels** [comment]
npm install mjml --no-optional
/home/manuel
├── markdown-to-mailchimp@0.5.0 
└── mjml@4.7.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/manuel/package.json'
npm WARN manuel No description
npm WARN manuel No repository field.
npm WARN manuel No README data
npm WARN manuel No license field.

**Comment by IanEdington** [comment]
hmm. You'll probably need to update your version of node. https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by iRyusa** [comment]
The error message quite self explain here. Just create a new folder, do a npm init, and then you can npm install mjml inside it. Note that node 8 is really old you should update your node version because MJML isn't tested anymore with node 8

**Comment by olebrussels** [comment]
Thank you so much. i did an update and now it works!

**Comment by iRyusa** [comment]
👍
