### ISSUE TITLE
Thank you (also email address)

### ISSUE THREAD

**Issue by aredridel** [mjmlio/mjml#2091]
Thank you so much for making MJML. The amount of real world knowledge encoded into this project is amazing. You've saved me such a huge amount of time!

Also, just so you know, the email address on this github profile doesn't work — I'd have sent this as private email if that had worked.

**Comment by ngarnier** [comment]
Thanks for the kind words and support @aredridel. We'll look in the email address but ironically, we don't really use email as a communication channel for email. Slack or Github is preferred.

**Comment by aredridel** [comment]
Makes sense! Anyway, thanks for the fantastic tool!
