### ISSUE TITLE
mj-section padding issue in MS Outlook 2016

### ISSUE THREAD

**Issue by OReshetnikov** [mjmlio/mjml#2092]
**Describe the bug**
Incorrect padding-right behaviour in mj-section for the MS Outlook desktop client

**To Reproduce**
Steps to reproduce the behaviour:
https://mjml.io/try-it-live/H1nKX8N5w
Send the rendered HTML and open it in the MS Outlook

**Expected behaviour**
The padding should be the same as in the test sandbox

**MJML environment:**
OS: Windows
MJML Version 4.6.3

**Affected email clients (for rendering issues):**
MS Outlook 2016 desktop version
![msOutlook](https://user-images.githubusercontent.com/20542098/99723938-8e533200-2abb-11eb-99d4-98c0b90e08f7.png)
In the web clients, such as Web Outlook and Gmail it looks correctly
![webClients](https://user-images.githubusercontent.com/20542098/99724045-b5116880-2abb-11eb-9877-9882744ff24a.png)

**Comment by iRyusa** [comment]
Outlook is using ghost table to mimic an "inline-block"-div. Browser and "modern" email client are smart enough to handle properly inline-block with overflow, but there's no way to have this behavior in a table.

There's really no applicable use of this in a design, i'm closing it
