### ISSUE TITLE
Stack Images won't work in Google Mail App

### ISSUE THREAD

**Issue by BestLice** [mjmlio/mjml#2094]
**Describe the bug**
The GMail App on Android will ignore any try to stack the Images.
Using the "fluid-on-mobile" Tag is ignored as using a defined width which corresponds to the display width.
Everything is just displayed smaller.

**To Reproduce**
Using tag:
```
<mjml>
    <mj-body background-color="#FFFFFF" >
        <mj-section direction="rtl">
            <mj-column>
                <mj-image width="250px" fluid-on-mobile="true" src="{{IMG_LINK}}"></mj-image>
            </mj-column>
            <mj-column>
                <mj-text font-size="18px" font-weight="bold" font-family="Roboto" align="center">
                    Test-Text
                </mj-text>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

Using width:
```
<mjml>
    <mj-body background-color="#FFFFFF" >
        <mj-section>
            <mj-column>
                <mj-image
                    src="{{LINK}}"
                    alt="Alt-Text"
                    width="134px" 
                    align="center"/>
            </mj-column>
            <mj-column>
                <mj-image
                    src="{{LINK}}"
                    alt="Alt-Text"
                    width="230px" 
                    align="center"/>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

**Expected behavior**
I expected, that the images in the Mail will stack.
Like they do in the preview, but they don't.

**MJML environment:**
 - OS: Debian
 - MJML Version 4.6.2
 - MJML App for Windows

**Email sending environment(for rendering issues)**:
JavaMailer, Exim4

**Affected email clients (for rendering issues):**
 - Email Client Gmail (there could be more, it's the one I found the Bug)

**Comment by iRyusa** [comment]
Can you provide a screenshot of the issue ? Are you sure you have nothing altering the email ? Can you try with https://putsmail.com/ ?

**Comment by BestLice** [comment]
Hi iRyusa,

thank you for your quick answer and sorry I took so long.
I tried it with putsmail and it worked. I guess it's a problem with the Java-Mailer then. I'll take a look at that next.
Thank you agin, we can close that issue then.
