### ISSUE TITLE
Background-image for Yahoo mail

### ISSUE THREAD

**Issue by GurovDmitriy** [mjmlio/mjml#2098]
When compiling, the background is set without quotes. Such background rejects Yahoo mail. How to get single quotes during compilation. Or how to display a background for Yahoo.
Thanks!
![Screenshot_1](https://user-images.githubusercontent.com/26795848/100063747-b4bdf800-2e42-11eb-9dcd-37da493ed5d0.jpg)

should be:

```
style="background: url('https//.....')..."
```

**Comment by Kassiwin** [comment]
Hi.
You may add a css class in  `<mj-head>` as
`<mj-style>
      .my-class {
        background-image: url('https://i.postimg.cc/VNZJGLB6/img-tech-bg-4.jpg');//This will be use as a fallback on Yahoo and Aol.
      }
    </mj-style>`
then on you section
`<mj-section css-class="my-class">`

**Comment by GurovDmitriy** [comment]
Thanks!

**Comment by GurovDmitriy** [comment]
problem solved! When specifying a background image, you do not need to specify a background color, otherwise it overlaps the background image. The background color should be set to the parent

**Comment by kmcb777** [comment]
Hi @GurovDmitriy on which device/browser did you test ? Could you please provide your mjml for this section ?
I made a few tests on emailonacid and the background-image seems to display on AOL and Yahoo, even when a background-color is set as fallback.

**Comment by GurovDmitriy** [comment]
Hi @kmcb777 . 
Sorry, but I can't reproduce the problem now. But it appeared several times and I removed the background color from my projects. In the process, I will try to reproduce the problem and give an example. Now with tests in good.

**Comment by Pharmasolin** [comment]
@kmcb777 https://github.com/hteumeuleu/email-bugs/issues/79 here is explanation, if string in url() is inside quotes it should work.
