### ISSUE TITLE
Passing bindings as values

### ISSUE THREAD

**Issue by kplates** [mjmlio/mjml#2102]
**Describe the bug**
Cannot seem to pass handlebars binding for width values. 

Can seem to pass values for other properties such as border color etc

Is there a workaround for this?

**To Reproduce**
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column width="{{colWidth}}">	
        <mj-image width="{{imgWidth}}" src="/assets/img/logo-small.png"></mj-image>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
Expected to pass bindings in compiled template

**Comment by iRyusa** [comment]
Some attributes like width are mandatory at transpilation to generate properly media query or compute ghost tables for Outlook.

There's no way to do so here, you should apply handlebars first and then pass the result to MJML.
