### ISSUE TITLE
Support typescript import

### ISSUE THREAD

**Issue by vh13294** [mjmlio/mjml#2105]
<img width="1018" alt="Screen Shot 2020-12-02 at 5 02 32 PM" src="https://user-images.githubusercontent.com/17086745/100858358-723e9000-34c0-11eb-85de-75c597c0e99a.png">

At the moment to use with typescript we have to do a work around esModuleInterop.

**Comment by TrySound** [comment]
You can hack ts and use `import * as mjml2html from 'mjml'` or just enable esModuleInterop and solve all problems. Default typescript behaviour is compatibility legacy.
