### ISSUE TITLE
MJML mj-class till inserts px on font size

### ISSUE THREAD

**Issue by edwh** [mjmlio/mjml#2106]
**Describe the bug**

#1080 explains that the font-size attribute no longer adds px automatically if not present.  But when expanding mj-class styles, px is still added (at least sometimes).

**To Reproduce**

Use this MJML on Try It Live:

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-class name="primary"  background-color="darkgreen" color="white" font-size="20px" inline="inline"/>
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container>
        <mj-section padding="10">
          <mj-column width="185">
            <mj-button align="center" href="#" mj-class="primary">
              Test
            </mj-button>
          </mj-column>
        </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Inspect the button, and you can see that the font-size attribute contains 'pxpx'.

**Expected behavior**

Font size should contain just 'px'.

**Comment by iRyusa** [comment]
You're still using MJML3 syntax on MJML4, as unit were optional in MJML3, the migrate script adds px by default to it.

Remove mj-container and adds unit to your padding/width, then it should be ok. Migration script will be deprecated really soon and won't be patch as MJML4.
