### ISSUE TITLE
Responsivity in Gmail after message clipped

### ISSUE THREAD

**Issue by lsegeta** [mjmlio/mjml#2109]
Hello, here is my template https://mjml.io/try-it-live/B1sqSNcjw 

After clicking view entire message https://prnt.sc/vwsftb resposivity doesnt work https://prnt.sc/vwsg3a Original https://prnt.sc/vwsgdg

Here is bug https://prnt.sc/vwskea

What can I do to fix it? I have tried templates from https://mjml.io/templates and there is still same bug so it isnt only for my template.

**Comment by iRyusa** [comment]
There's no way to prevent that, gmail just does strip head style when blocking image/clipping the email. Try to send the minified version, if it doesn't work then you'll have to manually optimise your MJML to be under 102KB
