### ISSUE TITLE
Allow custom component to adjust allowed children

### ISSUE THREAD

**Issue by verbeeksteven** [mjmlio/mjml#2110]
Hello,

In the linter it loops over each component (such as `mj-column`) and confirms that the component is allowed to be there.

But from what I can see there doesn't seem to be a way to say `mj-custom-component` is allowed to be placed inside a `mj-column`.

It would be nice if there was a way to this child could be part of what parents, rather then what children a parent can have.

Thanks,

**Comment by iRyusa** [comment]
It would be a bit confusing API wise to support both way IMO ?

**Comment by verbeeksteven** [comment]
Is there anyway to edit the existing components? Like can I add components to mj-column "registry"?

**Comment by iRyusa** [comment]
When you call the function it will append it to currently registered dependencies

**Comment by verbeeksteven** [comment]
@iRyusa which function are you referring to?

    registerComponent(MjImageHover)

That one?

**Comment by iRyusa** [comment]
You have an exemple in component boilerplate here : https://github.com/mjmlio/mjml-component-boilerplate/blob/master/components/MjImageText.js#L5-L9

**Comment by verbeeksteven** [comment]
Well shut the front door. Let's call this solved, my apologies I did not see this before. I think this method is perfectly fine.
