### ISSUE TITLE
Relative Paths not working on MJML with mjml-react

### ISSUE THREAD

**Issue by alioshr** [mjmlio/mjml#2112]
**Describe the bug**
- The use of relative paths render broken links on the email recipient
- The use of links from images on the web generate broken links on the email, except for the case that these links have a termination which explicitly names an image, with its type (jpg, etc), e.g ```src="http:://somelink....jpg"```

**To Reproduce**

Relative path does not work: 
```
       <MjmlImage
              width="400px"
              src="./public/Book/Book.png"
            ></MjmlImage>
```

Only this kind of link that works:

```
<MjmlImage
              width="400px"
              src="https://image.shutterstock.com/image-photo/bright-spring-view-cameo-island-260nw-1048185397.jpg"
            ></MjmlImage>
```

**Expected behavior**
The image should show on the email of the recipient. 

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.7.1
 - MJML tool used: mjml-react 1.0.61

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Gmail

**Affected email clients (for rendering issues):**
 - Email Client: Gmail
 - OS: Windows
 - Browser: Google Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/54821977/102109017-5fa64e00-3e12-11eb-9d15-5248e83d5b3f.png)

**Additional context**
I tried using [this package](https://developer.aliyun.com/mirror/npm/package/mjml-with-images-loader) and followed the steps for ```webpack``` on my ```next.config.js``` file (I am using NextJs) but it did not work also.

**Comment by kmcb777** [comment]
Hi, we don't maintain mjml-react so you should open your issue on their repo instead.
But if i understand your issue correctly, there is no way that a relative link would work for the recipient, how would they have access to the image file ? You need to host the image somewhere.
