### ISSUE TITLE
local issuer certificate error when using mjml api

### ISSUE THREAD

**Issue by landoephan** [mjmlio/mjml#2114]
I use the API since a few weeks and everything worked fine, but today I suddenly ran into this error when trying to send mails:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.mjml.io', port=443): Max retries exceeded with url: /v1/render (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```

I didn't change my config or anything. I also tried to retrieve new API Credentials, but I didn't receive a new email so far.

**Comment by aureliusm** [comment]
Having the exact same issue.

**Comment by CMorrier** [comment]
Same here, there seems to be a certificate problem on MJML end

**Comment by jeffersonrabb** [comment]
Having the same issue in https://github.com/Automattic/newspack-newsletters. As of a few hours ago the MJML API started returning `{"errors":{"http_request_failed":["cURL error 60: SSL certificate problem: unable to get local issuer certificate"]},"error_data":[]}`

**Comment by ngarnier** [comment]
Hi everyone, sorry about that. We've identified the issue and working on a fix. There is a valid certificate on mjml.io but the issue is related to the intermediate chain.

**Comment by landoephan** [comment]
issue seems solved

**Comment by ngarnier** [comment]
Yes, we just put a fix in place. Sorry for the issue and feel free to report if you see anything else.

**Comment by landoephan** [comment]
thanks

**Comment by CMorrier** [comment]
Hi,

The problem seems to be back :(

`SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Thank you

**Comment by yucomds** [comment]
The issue is back .. Any suggestion?

**Comment by landoephan** [comment]
how should one use mjml in production if it's not reliable?

**Comment by yucomds** [comment]
For people using the API in PHP software you could "solve" by installing mjml cli.

Run this :

`npm install -g mjml`

Then in your code you can make something like this :


        $input_file     = "/tmp/".time()."_input.mjml";
        $output_file    = "/tmp/".time()."_output.mjml";

        file_put_contents($input_file, $mjml);

        $res = exec("mjml {$input_file} -o {$output_file}", $error, $return_var);

        // print_r($res);
        // print_r($error);
        // print_r($return_var);

        $html = file_get_contents($output_file);   
        
        unlink($input_file);
        unlink($output_file);

**Comment by carlosfcol** [comment]
since last past 2  weeks im receiving same error from one of our networks... seems like for us this issue is back

**Comment by carlosfcol** [comment]
We appreciate any suggestion , we are gonna try to install it locally,
if you guys have any code to share we appreciate it

**Comment by carlosfcol** [comment]
this is part of our code, builder.js 
![image](https://user-images.githubusercontent.com/96447210/146835289-d917706e-cf61-4888-9293-9be0efd02e9d.png)
