### ISSUE TITLE
Target="_blank" rel="norefer" ?

### ISSUE THREAD

**Issue by GurovDmitriy** [mjmlio/mjml#2115]
Shouldn't we use y links Target="_blank" rel="norefer" ?

**Comment by iRyusa** [comment]
Can you add more details here ? Most component have target blank already, and  button does support the `rel` attributes

**Comment by GurovDmitriy** [comment]
By default, target blank is set for all email links. Google's safety recommendations say that for such a case, rel nooper noreffer should be added by default. Is this an obligation to apply to letters as well?

**Comment by IanEdington** [comment]
@GurovDmitriy Could you link to those recommendation?

**Comment by GurovDmitriy** [comment]
https://web.dev/external-anchors-use-rel-noopener/

**Comment by iRyusa** [comment]
You can still provide default value to any `rel` attribute with `mj-all`. I'm closing it
