### ISSUE TITLE
Provide official Docker image

### ISSUE THREAD

**Issue by pennal** [mjmlio/mjml#2117]
**Is your feature request related to a problem? Please describe.**
After the problem with the certificates (See #2114), it has become clear that many people rely on the service in prod environments. Personally I believe this is due to the simplicity of the service (send the markup, get the perfect HTML back), but the impact that such an outage can have is quite large. 

Currently, there are a couple of images out there (See [this](https://github.com/MarcoMedrano/docker-mjml), [this](https://hub.docker.com/r/adrianrudnik/mjml-server), and a Google search produces a lot more), but none are 100% compatible with the API, and some of them require special payloads or setting to make it work.

**Describe the solution you'd like**
An official Docker image, which bundles the API to be 100% compliant with the currently hosted version. This would allow developers to self host the service on their own machine, and not rely on the external service. 

**Describe alternatives you've considered**
I have built the image myself, but this means that I need to keep up with possible updates, changes, etc. Also, I have made a very simple MVP so there are a lot of features I am missing (errors, correct version, etc). See the first paragraph for other alternatives.

**Additional context**
__None__

**Comment by ngarnier** [comment]
Thanks for the feedback @pennal, there is no plan for us to provide an official Docker image at the time. 

Feel free to create a repo to act as the community Docker image. There are example of community packages that we took over as the main maintainers as the adoption justified it (example: https://github.com/mjmlio/vscode-mjml).
