### ISSUE TITLE
MSO VML bg and links inside...

### ISSUE THREAD

**Issue by GurovDmitriy** [mjmlio/mjml#2118]
when the links are inside the vml background in the mso they are shifted to the left. How can this be avoided?
1 photo mso desktop
2 photo  browser and other email clients

![Screenshot_1](https://user-images.githubusercontent.com/26795848/102691514-2741ae00-421e-11eb-83a7-74909d9113cf.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/26795848/102691517-290b7180-421e-11eb-823c-c281fadccade.jpg)

**Comment by iRyusa** [comment]
Padding left and right are applied both on right on Outlook withink a section with background image, you should remove it if you can.

There's not so much we ca do about this
