### ISSUE TITLE
mj-text does not inherit font-size from mj-container

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#212]
```
<mjml>
  <mj-body>
    <mj-container font-size="32">
      <mj-section>
        <mj-column>
          <mj-text>Hello world!</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Why font-size in mj-container does not affect to mj-text?

**Comment by jarsbe** [comment]
@liminspace I think you're missing the px. `<mj-container font-size="32px">`

**Comment by liminspace** [comment]
it not helps

**Comment by pixelize** [comment]
@liminspace it's always better to specify properties on each elements when coding a mail ! A bunch of desktop and web email clients need css on every single elements to render the whole thing good ;)

**Comment by liminspace** [comment]
I think MJML can make layout more easy and DRY principe is possible.

**Comment by iRyusa** [comment]
Well I think we'll remove it in a near future, #79 will easily fix this behaviour and is more flexible
