### ISSUE TITLE
mj-social icons arn't displayed with Outlook

### ISSUE THREAD

**Issue by Mijer** [mjmlio/mjml#2120]
Hello,

I've got an issue with mj-social in Outlook, blocs are displayed with the matching color & label, but the icons are missing. Everything is ok with Gmail, or android email app, same for MacOs mail app.

[Here is my MJML](https://mjml.io/try-it-live/rJe4LY1pP)

**MJML environment (please complete the following information):**
 - OS: MacOs Catalina 10.15.7
 - MJML Version : 4.4.1
 - MJML tool used : MJML App v2.12.0

**Email sending environment(for rendering issues)**:
 - Platform used to send the email : Mailjet

**Affected email clients (for rendering issues):**
 - Email Client : Outlook 
 - OS: Android/MacOS (probably others too)
 - Browser : Chrome / Firefox (probably others too)

**Screenshots (Outlook)**
![image](https://user-images.githubusercontent.com/8359906/102904736-6e27e180-4472-11eb-8b41-98e85aeb5226.png)
**Screenshots (Gmail)**
![image](https://user-images.githubusercontent.com/8359906/102903838-2bb1d500-4471-11eb-81ca-e3f0121334ae.png)

**Comment by iRyusa** [comment]
Hi,

Do you have other images in your email ? Are they displayed ?

**Comment by Mijer** [comment]
Hello @iRyusa,
Yes, I do. Other images are displayed.

Here is a screenshot of the DOM of a social icons. The SRC is set with a 1x1 px image, while the "originalsrc" have the real image.
![image](https://user-images.githubusercontent.com/8359906/102904087-864b3100-4471-11eb-883d-cdc31c43db6f.png)

**Comment by iRyusa** [comment]
Really weird here if I send with putsmail there's no issue here. Might be related to Mailjet here so you should open a ticket on their side.
