### ISSUE TITLE
catch circular includes

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2121]
**Is your feature request related to a problem? Please describe.**

Condition: When users create circular references to include files, MJML generates
a syntax warning, "mjml fails to read file: ..."
It creates no HTML.
It provides neither indication it didn't generate HTML nor why.
These syntax warnings are easy to miss (and indeed reasonable to ignore in some cases).

MJML displays this same syntax warning when the include file doesn't exist. The wording fits that condition well. It's sufficient for that condition because MJML still creates HTML, though without any content from the intended file (as expected).

For this condition, the wording of this syntax warning is marginally suggestive of the problem and not useful. It confuses users when they find that the file exists.

**Describe the solution you'd like**

(1) MJML identify this condition and issue a new syntax warning reporting a presently called include file that is already being processed (circular reference). (2) Also, use a stronger level of warning to indicate this problem.

One way to do it:

For (1) above: MJML to keep a list of include files it is currently processing. Before each call to a new include file, check whether that file is already in processing. If it is, issue a warning like, "MJML doesn't allow circular relationships among include files. File: ..." This warning will be a new entry in the existing list of all warnings and will get the existing icon display response in editors.

For (2) above: Additionally, report the condition to the author in HTML. The current response produces no HTML; this is better. This creates no harm different than creating no HTML. A starting draft for the message in the HTML file is:

> File xxx at line yyy calls file zzz as an include file. File zzz is already in processing, creating a circular reference. MJML doesn't produce HTML in this condition. The condition does not affect the presence of your MJML files.

Providing a warning via HTML would equally apply to all email author use cases for MJML.

**Describe alternatives you've considered**

As to (1, Identifying this condition and issuing a warning with new wording) :

Other than the proposed, I've considered only the "do nothing" option. Perhaps "do nothing" is reasonable. On the other hand, perhaps proposal (1) is a "small" and "easy" change to MJML code with low potential for introducing maintainability challenges. If that's true, the benefit of better telling users about the condition may outweigh both the time in development and testing, and the added maintainability potential.

Proposal (1 Identifying this condition and issuing a warning with new wording) is more attractive than "do nothing".

As to (2, Creating a second level of warning):

For MJML authors depending on Node.js, MJML already sends error messages to the console; this could be another. This is better than nothing. However, this solution involves widely varying chance of gaining attention among other use cases (various editors and environments). This is unattractive.

For MJML authors using the various editors we could ask editor authors to add something like a dialog box or another change to their user experience to better gain attention. Changes to the desktop app and the Visual Studio plugin might be necessary; those efforts would be within the team. Perhaps this would apply to Atom and Sublime, too. Email authors choose many other editors (bare-bones editors offered by various operating systems and many third-party editors). We can expect no interest in changing many of those products. This is unattractive.

There's the "do nothing" option. Using the HTML file is better.

Proposal (2, Creating a second level of warning) is more attractive than these alternatives.

**Comment by iRyusa** [comment]
It already throw an error, but message might give a bit more context


```sh
➜  sandboxu cat test.mjml
<mjml>
  <mj-body>
    <mj-include path="a.mjml" />
  </mj-body>
</mjml>

➜  sandboxu cat a.mjml
<mj-text>Hello</mj-text>
<mj-include path="b.mjml" />
➜  sandboxu cat b.mjml
<mj-text>Hello from B</mj-text>
<mj-include path="a.mjml" />
➜  sandboxu yarn mjml test.mjml
yarn run v1.22.4
$ /Users/maximebrazeilles/Workspace/sandboxu/node_modules/.bin/mjml test.mjml
File: test.mjml
Error: Circular inclusion detected on file : /Users/maximebrazeilles/Workspace/sandboxu/a.mjml

Command line error:
Input file(s) failed to render
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by GarryFlemings** [comment]
Seems like a good solution. Kinda looks like it's coded. Plans to deploy? Done?
Thanks.

**Comment by iRyusa** [comment]
This works for a while now, not so much to add here

**Comment by GarryFlemings** [comment]
Closed by accident.
