### ISSUE TITLE
Internal error(500) with error "An unknown error occurred"

### ISSUE THREAD

**Issue by vaishnavi-accountbox** [mjmlio/mjml#2128]
Hi MJML Team,

We are receiving 500 internal server error, This is happening very frequently.

Here is a sample response
{"message":"An unknown error occurred","request_id":"621c088a-d9e1-4f51-be34-96b242a5a030","started_at":"2020-12-29T15:28:46Z"}

Please help ?

**Comment by iRyusa** [comment]
... Please check for open issue instead of reopening a new one for the same problem.
