### ISSUE TITLE
Cannot find module '../lib/utils.js' in esbuild

### ISSUE THREAD

**Issue by thom801** [mjmlio/mjml#2132]
**Describe the bug**

When importing mjml into an esbuild project the build works fine, but the compiled app has this error: 

`Error: Cannot find module '../lib/utils.js'`

Full trace:

```
Error: Cannot find module '../lib/utils.js'
Require stack:
- /Users/thom/develop/laboratory/mjml-build-error/out.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:39836:13
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:11:5
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:39919:18
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:11:5
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:47259:23
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:11:5
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:51912:43
    at /Users/thom/develop/laboratory/mjml-build-error/out.js:11:5 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/thom/develop/laboratory/mjml-build-error/out.js' ]
}
```

**To Reproduce**
I've uploaded a very simple working example just follow README to run: 

https://drive.google.com/uc?id=1Xfb9d1jEJ9nIOyI8Tqnm6tuRkydRKdb3&export=download

**Expected behavior**
The app should execute without errors.

**MJML environment (please complete the following information):**
 - OS: Mac OS 11.1 Big Sur
 - MJML Version 4.8.1
 - MJML tool used: npm package

**Comment by thom801** [comment]
Looking closer at this. It seems that the issue lies somewhere in mjml-core's dependency to html-minifier which requires uglify-js which requires node 7 (?) and that is where the issue is happening. So perhaps updating the html-minifier dependency (https://github.com/mjmlio/mjml/blob/45507ebde835129ba62671d341e76bc9892552c9/packages/mjml-core/package.json#L28) is the solution?

Although mjml-core is currently using v4.0.0 which is the latest version. So I'm not sure. Maybe @alexlamsl might recognize this issue? (core contrib on html-minifier).

**Comment by iRyusa** [comment]
html-minifier won't be bundled anymore with MJML5 and onward so it might be it for you ? You can try also mjml-browser build

**Comment by thom801** [comment]
@iRyusa yeah that might be the right path then. Is MJML5 available for use right now?

**Comment by iRyusa** [comment]
Nope and there’s no ETA yet

**Comment by thom801** [comment]
@iRyusa any idea how we maybe could get this working in our environment? Would we have to fork and replace html-minifier? Would that be a lot of work?

**Comment by iRyusa** [comment]
Did you tried with https://www.npmjs.com/package/mjml-browser ?

**Comment by thom801** [comment]
@iRyusa I just got access to MJML API. I think that will solve our problem pretty well, what do you think?

**Comment by iRyusa** [comment]
It should work as a workaround but the `mjml-browser` should be fine tho

**Comment by thom801** [comment]
`mjml-browser` package failed to install on node v15.4.0 for me. The API version of MJML is working as a workaround. If anyone is curious this is what my replacement looks like:

```typescript
    const MJMLContent = getFile(`api/src/mail/mjml/${template}`)
    const postData = { mjml: MJMLContent }
    const authEncoded = Buffer.from(`${process.env.MJML_APP_ID!}:${process.env.MJML_PRIVATE_KEY!}`).toString('base64')
    const basicAuthValue = `Basic ${authEncoded}`
    const response = await fetch('https://api.mjml.io/v1/render', {
      method: 'post',
      headers: { 
        'Content-Type': 'application/json',
        'Authorization': basicAuthValue
      },
      body: JSON.stringify(postData),
    })

    const responseJSON: MJMLRenderResponse = await response.json()

    if (response.status !== 200 || responseJSON.errors.length > 0) {
      throw new Error(`Error rendering MJML template: ${responseJSON.errors.toString()}`)
    } else {
      const HTMLContent = responseJSON.html
      const renderedHTML = Mustache.render(HTMLContent, templateData)
      return renderedHTML
    }
```

@iRyusa thank you for the assistance.

**Comment by kmcb777** [comment]
Hi @thom801 what problem did you have when installing mjml-browser on node 15 ?
It's been tested on node 14 and there was no problem with install and usage

**Comment by thom801** [comment]
@kmcb777 Sorry I don't recall. I should have posted the error here. Thank you for following up. I just tried an install within our project now on v15.4.0 and seemed to work just fine.

**Comment by kmcb777** [comment]
Ok thanks for your answer, glad to hear it worked fine this time

**Comment by Gavursnake** [comment]
Hi I found a workaround inspired by https://github.com/mjmlio/mjml/issues/1365#issuecomment-555835755. Basically, i defined a plugin that would return an empty module for the uglify file:

`let emptyMjmlUglifyPlugin = {
  name: 'empty mjml uglify plugin',
  setup(build) {
    build.onLoad({ filter: /uglify-js\/tools\/node.js$/ }, () => ({
      contents: '{}',
      loader: 'js',
    }));
  },
};`

**Comment by Gavursnake** [comment]
Hi I've found a workaround inspired by https://github.com/mjmlio/mjml/issues/1365#issuecomment-555835755. Basically, i defined a plugin that would return an empty module for the uglify node file:

```
let emptyMjmlUglifyPlugin = {
  name: 'empty mjml uglify plugin',
  setup(build) {
    build.onLoad({ filter: /uglify-js\/tools\/node.js$/ }, () => ({
      contents: '{}',
      loader: 'js',
    }));
  },
};
```
tested with mjml 4.11.0

**Comment by ChristopheBougere** [comment]
For anyone trying to use MJML in AWS Lambda bundled with CDK (which uses esbuild):

@sadtomatoofjoy workaround cannot be used because CDK doesn't provide the ability to define custom esbuild plugins (it is used in CLI, not in Node).
I got it working by adding `uglify-js` in the [`nodeModules` property](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html#install-modules).

It increases the code size indeed, but it's the best I found.

**Comment by blurp1478963** [comment]
To use it with netlify (with lambda functions), add
```
[functions]
  external_node_modules = ["uglify-js"]
```
To your netlify.toml file

**Comment by wengkhing** [comment]
I was facing the same issue with monorepo setup using SST serverless stack. I have an email microservice that uses `mjml`, the above solutions doesn't seems to work in my context, what works for me is moving the installation of `mjml` package to the root project `package.json` instead of in the email microservice `package.json`.

**Comment by rogueturnip** [comment]
> I was facing the same issue with monorepo setup using SST serverless stack. I have an email microservice that uses `mjml`, the above solutions doesn't seems to work in my context, what works for me is moving the installation of `mjml` package to the root project `package.json` instead of in the email microservice `package.json`.

I'm having this issue myself.  I've tried moving into the root package.json but I'm still getting libs/utils.js not found.  did you make any other changes?

**Comment by jdrydn** [comment]
I couldn't get this to work at all, so I ended up putting `mjml` into its own Lambda layer & getting `esbuild` to exclude `mjml` completely. Some fun issues when trying to package/deploy the layer (happy to share if desired) but beyond that I've not had any further issues around `esbuild` & `mjml`!

**Comment by chrisandrewcl** [comment]
Another option is to use the package manager to override `uglify-js`:
```JSONC
// package.json
// ...
  "pnpm": {
    "overrides": {
      "uglify-js": "npm:terser"
    }
  }
}
```

\* Since it doesn´t seem to be in use, it should be fine to override it to any other package.

**Comment by andrerpena** [comment]
In my case, I was able to fix it by making `uglyfy-js` as external on `esbuild`

```
require("esbuild")
  .build({
    bundle: true,
    platform: "node",
    outdir: "./dist-cli",
    entryPoints: ["cli/index.ts"],
    tsconfig: "./tsconfig.cli.json",
    external: ["fsevents", "uglify-js"],
    sourcemap: true,
  })
  .catch(() => process.exit(1));
```

**Comment by hikeeba** [comment]
This is still an issue, and MJML 5 does not exist

**Comment by iRyusa** [comment]
https://www.npmjs.com/package/mjml/v/5.0.0-alpha.6 is available on NPM @hikeeba

**Comment by hikeeba** [comment]
Thanks. I'll try that out and see if it works for us

**Comment by hikeeba** [comment]
Well, unfortunately this still didn't work for us. Got an issue with the version of prettier being used in alpha.6.

```
node:internal/errors:496
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
at new NodeError (node:internal/errors:405:5)
at createRequire (node:internal/modules/cjs/loader:1505:11)
at node_modules/prettier/index.mjs (/usr/src/app/dist/index.js:295592:48)
at __init (/usr/src/app/dist/index.js:9:59)
at /usr/src/app/dist/index.js:310863:57
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'ERR_INVALID_ARG_VALUE'
}
```

**Comment by hikeeba** [comment]
We'll likely have to rip out MJML until there's something stable that can be used.
