### ISSUE TITLE
Why is mjml still using Cheerio?

### ISSUE THREAD

**Issue by skingsland** [mjmlio/mjml#2136]
My company is using the `mjml` Node.js module to generate emails in a batch process. As we have started to scale up to higher volumes, we've noticed some slowness with mjml. We have just started profiling its performance, but one thing I'm wondering about is the `cheerio` library. According to a [blog post](https://medium.com/mjml-making-responsive-email-easy/hey-were-entirely-rebuilding-mjml-from-scratch-announcing-mjml-v4-ae92f83b725b) from 2017, you replaced that with a different parser (`htmlparser2`) but it looks like you're still using cheerio: https://github.com/mjmlio/mjml/blob/a2e6adecef66eb027eef90d2a950559739f274a6/packages/mjml-core/src/index.js#L307

Why is that?

In case you're curious, we're passing in MJML documents with `<mj-*>` tags (_not_ JSON), embedding it in a continuously running node.js service, and we're using `strict` validation.

**Comment by TrySound** [comment]
Cheerio is anyway a part of juice. Though I agree parsing/serialisation could be done once.

**Comment by iRyusa** [comment]
Cheerio is being used for a new feature in 4.8.x (https://documentation.mjml.io/#mj-html-attributes), if you don't use this feature then it's not really an issue as cheerio is only being used here. Using htmlparser2 give us a bit more flexibility on parsing  XML-like input, but cheerio is used to apply custom attribute with css selectors.

**Comment by skingsland** [comment]
Cool, thanks for the explanation!
