### ISSUE TITLE
button with variable as "onclick"

### ISSUE THREAD

**Issue by az-z** [mjmlio/mjml#2137]
Hello,
 2 issues:
 a. is there comprehensive documentation? 
 b. for a template, how can i add a button with var URL? something lke :
 ```
<button onclick="window.location.href='VARIABLE_URL_THAT_I_CAN_PASS_WHEN_SENDING_THE_EMAIL';">
      Click Here
    </button>

```
thank you

**Comment by IanEdington** [comment]
Hi @az-z, it looks like this is your first issue with MJML. Welcome to the community 👍 

Are you using MJML to write emails?
Unfortunately, it's not possible to use javascript in email 😢 . It's actually a good thing though since it would be a huge security issue.

You probably want the `mj-button` element with an href on it: https://documentation.mjml.io/#mj-button

It might look like this:
```
<button href="VARIABLE_URL_THAT_I_CAN_PASS_WHEN_SENDING_THE_EMAIL">
   Click Here
</button>
```

**Comment by az-z** [comment]
@IanEdington , thank you for your assistance. JS in the mail is definitely a bad idea.
how do i get the MJML code from the visual template builder?
`
![image](https://user-images.githubusercontent.com/5010397/104143783-e3f6dd00-538e-11eb-8a04-a938faeeb5bb.png)
`

**Comment by IanEdington** [comment]
hmm that's a great question.

Is this with MailJet or another email service provider? If it is I think it's outside the scope of what we can help with in this community. You might want to try contacting their support of their docs. There are lots of very specific template language details that depend on how MJML is set up with the templating language.

If it's not, what is this tool?

**Comment by az-z** [comment]
Got it, i thought that MailJet created and supported the MMLIO thru github.  My apologies. I'll check with them then. Thank you for the quick reply.

**Comment by GarryFlemings** [comment]
I'll take the documentation question.

Most importantly to documentation: MJML uses HTML, so all HTML documentation is important. There's no added value in repeating HTML documentation.

The team advises email authors that many problems are best solved at HTML level. And, reading the HTML gets pretty easy after some practice. There's lots of flexibility in responding there.

The best organized of the MJML documentation is at links starting from
https://mjml.io
especially
https://documentation.mjml.io

Rich sources of MJML information are at links starting with
https://github.com/mjmlio/mjml
especially both of
https://github.com/mjmlio/mjml/issues
https://github.com/mjmlio/mjml/pulls
Obviously, you've found the first of those. A GitHub search often helps you find discussion of your exact issue (they tend to come around more than once).

I recall seeing Bill Gates say about documentation early in his career something like, "Documentation? The source code is the documentation!" And you have access to the source code. Simply pull
https://github.com/mjmlio/mjml.git
into a Git repository. Or, similarly, fork the code on GitHub. Skilled knowledge of JavaScript, CSS, and HTML is valuable.

A valuable source of further help is
https://mjml.slack.com
The MJML team is extremely helpful there.

**Comment by az-z** [comment]
Great! Thank you very much!
