### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ryanburr** [mjmlio/mjml#2141]
**Description**
When registering a custom component that does not contain a `dependencies` property, the `mjml-validator` gives a very cryptic error,
```
Error when registering custom component :  /path/to/CustomComp.js TypeError: Cannot convert undefined or null to object
```

**To Reproduce**
1. Create a custom mjml component as the default export
```js
export default CustomComp extends BaseComponent {
  // public dependencies = {}; Leave this property out
  public allowedAttributes = {
    attr1: 'string'
  };

  // ...
}
```
2. Add the component to your `.mjmlconfig`
3. Create an mjml template that uses your custom component
4. Compile the mjml with the node SDK
```js
import mjml2html from 'mjml';

const { html, errors } = mjml2html(mjmlFile);

console.log(errors);
```

**Expected behavior**
One of the following...

1. Allow a component to be defined and validated without specifying dependencies.
2. Throw a more descriptive error when registering dependencies that don't exist.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.8.1
 - MJML tool used: Node

**Additional context**
[This line of code](https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/mjmlconfig.js#L95) is where you should handle either 
1. passing an empty object if `.dependencies` is not defined
2. throwing an error telling you that `dependencies` are required.

Without this, the `sources` param of `assignDependencies` ends up being `[null]`, which throws a hard type error when trying to iterate over the items.
https://github.com/mjmlio/mjml/blob/master/packages/mjml-validator/src/dependencies.js#L1

**Comment by iRyusa** [comment]
Hey !

Thanks about this bug report, can you open a PR about this to credit your work on this ?

**Comment by ryanburr** [comment]
@iRyusa Yeah I'll put a PR together this weekend
