### ISSUE TITLE
Background image position issue

### ISSUE THREAD

**Issue by vaishnavi-accountbox** [mjmlio/mjml#2142]
Hi MJML Team,

We are facing issue with background image positions. We have tried with background-position and (background-position-x and background-position-y) both the ways we found issue.  It is always rendering as top center not considering the values which we have pass through API.

Here is the screenshot - https://snipboard.io/1TvrI5.jpg
But when I checked in mjml editor it just works fine - https://snipboard.io/dnWruI.jpg

Please Help!

**Comment by iRyusa** [comment]
Well there's not enough information to help you here. 

Can you please provide at least MJML version, the way you send the first email, MJML input string in the try-it-live https://mjml.io/try-it-live

**Comment by vaishnavi-accountbox** [comment]
Thanks and here below is the mjml object sending to https://api.mjml.io/v1/render
{
	"tagName": "mjml",
	"attributes": {},
	"children": [{
		"tagName": "mj-head",
		"children": []
	}, {
		"tagName": "mj-body",
		"attributes": {
			"background-color": "#f9f9f9",
			"width": "600px"
		},
		"children": [{
			"tagName": "mj-container",
			"attributes": {
				"background-color": "#f9f9f9",
				"width": "600"
			},
			"children": [{
				"tagName": "mj-wrapper",
				"attributes": {},
				"children": [{
					"tagName": "mj-section",
					"attributes": {
						"css-class": "eb-section eb-template-first-section eb-template-last-section",
						"background-color": "#ffffff",
						"padding": "10px 10px 10px 10px",
						"background-url": "https://s3.amazonaws.com/ebuploads2/uploads/1607156694435-avatar_new.png",
						"background-repeat": "no-repeat",
						"background-size": "auto",
						"background-position-x": "right",
						"background-position-y": "bottom"
					},
					"children": [{
						"tagName": "mj-column",
						"attributes": {
							"vertical-align": "top",
							"width": "100%",
							"background-color": "transparent",
							"border": "none"
						},
						"children": [{
							"tagName": "mj-spacer",
							"attributes": {
								"height": "400",
								"container-background-color": "transparent"
							}
						}]
					}]
				}]
			}]
		}]
	}]
}

**Comment by kmcb777** [comment]
Hi @vaishnavi-accountbox 
I could indeed reproduce the issue on the api. The api is running on mjml v4.6.1, so this must be the cause, since it works on the try-it-live which is on v4.7.1
The api releases are quite rare, but depending on your technical stack, you could maybe use `mjml-browser` instead ?

Also note that to have background-repeat to really work on outlook desktop you need mjml >= 4.7, and you need to specify the `background-size`. I tried setting "background-size="128px 128px" on your example and it renders perfectly.
