### ISSUE TITLE
Trouble centering a <mj-group> and nested columns disapearing

### ISSUE THREAD

**Issue by SStan-prog** [mjmlio/mjml#2143]
Hello, I am trying to center the group of social media icons (nested in columns) to the center of the screen. 
I've tried centering with padding but have had no luck, what is the best way to center a <mj-group>?

The images also completely disappear after the width gets to a certain point.

Any help is greatly appreciated. Loving the framework so far. 

![mj-sample](https://user-images.githubusercontent.com/63458207/104614986-c5c30280-5656-11eb-88c3-e7f6d55e703f.png)
![mjml-code-sample](https://user-images.githubusercontent.com/63458207/104615001-c8bdf300-5656-11eb-8f6d-1cd724c0826e.png)

**Comment by iRyusa** [comment]
columns within `mj-group` only support width in `%` not in `px`.

Just use regular mj-social for that.

**Comment by SStan-prog** [comment]
Thank you, the mj-social works great. 
One other thing I am trying to correct is the spacing around the top text, I would like each line to be quite a bit closer. 
I don't understand why they are still spaced so far apart when padding is set to 0.

**Comment by iRyusa** [comment]
Just inspect the element with your favorite browser, it mostlikely comes from default margin from h1/h5

**Comment by SStan-prog** [comment]
Got it, thanks!
