### ISSUE TITLE
Centering a group of dynamic width columns 

### ISSUE THREAD

**Issue by kprokopczyk** [mjmlio/mjml#2144]
Hello, i have 3 columns that i want to smash together and center horizontally _as a group_. In other words, I want the image, slash and text to appear as **one object** centered horizontally, so something like this:
![image](https://user-images.githubusercontent.com/30055821/104780374-4f053280-5746-11eb-8538-64c4e02e8471.png)

I can't figure out how to do it without a `width="auto"` option on `mj-column`. Any pointers? Is a 3 column layout the right approach or is there a better solution?
```
<mjml>
	<mj-head>
		<mj-style inline="inline">
			.slash {
				padding-right: 6px;
				font-size: 20px;
				font-style: normal;
				color: blue;
			}
			div.groupCenter {
				text-align: center !important;
			}
		</mj-style>
	</mj-head>
	<mj-body>
		<mj-section>
			<mj-group css-class="groupCenter">
				<mj-column width="120px" vertical-align="middle"  border="1px solid black">
					<mj-image padding="0" align="right" src="https://logosbynick.com/wp-content/uploads/2018/03/final-logo-example.png"/>
				</mj-column>
				<mj-column vertical-align="middle" padding="10px 0px"  border="1px solid red">
					<mj-text align="center">
						<span  class="slash">&#8725;</span>
					</mj-text>
				</mj-column>
				<mj-column vertical-align="middle" border="1px solid black">
					<mj-text align="left" padding='0' font-weight='200' font-size='16px'>
						Example
					</mj-text>
				</mj-column>
			</mj-group>
		</mj-section>
	</mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
"auto" width doesn't exist because it need to generate outlook ghost table.

Inside mj-groupe you can only define width in `%` and not in `px`, you should just do something like 40/20/40 inside this mj-groupe and it will works fine.

**Comment by kprokopczyk** [comment]
Thank you, but I left out one important element: The third column has a variable width.

**Comment by iRyusa** [comment]
There's no way to have "auto" column in MJML because of ghost table. So you should just play with width size to handle most cases.

**Comment by kprokopczyk** [comment]
Alright, thanks for the help.

**Comment by caseyjhol** [comment]
@iRyusa I modified the transpiled HTML and replace the specified widths with `width: auto` (including in the Outlook ghost table). This seems to work fine (tested in Outlook webmail, Outlook 365 for Windows, and Yahoo webmail). Do you know which email clients this isn't supported in? Supporting `width="auto"` for `mj-column` would be a major enhancement.

https://mjml.io/try-it-live/qcCkB2yO3

**Comment by iRyusa** [comment]
You need to test older client (outlook 2013/2007/…) I don’t think outlook 365 use those ghost table

**Comment by caseyjhol** [comment]
@iRyusa Maybe I'm misunderstanding what ghost tables are? I assumed they were the "mso" commented table/td surrounding each column div.

#### Outlook 365 (v2203)

With mso comments:
![image](https://user-images.githubusercontent.com/2874325/165592651-734ca872-1695-409f-83f3-ad6161dad692.png)

With mso comments removed:
![image](https://user-images.githubusercontent.com/2874325/165592743-2d9e6943-6c97-4a6e-8552-97fac39f76aa.png)

**Comment by iRyusa** [comment]
That's my bad, Outlook 365 use ghost tables too.
Here it's a bit more complexe than that as auto might be only ignore as all cell have the same value tho as it's the default behavior of html table. You should try with a fixed width column and 2 "auto" and it shouldn't render the same as you expect

**Comment by iRyusa** [comment]
Would need some testing but that’s a great news if it works 👍🏻

**Comment by caseyjhol** [comment]
@iRyusa Would you like me to open a PR?

**Comment by iRyusa** [comment]
Yup but I wonder how will this work with `mj-image` as it rely on column width to ensure there's no overflow 🤔

**Comment by iRyusa** [comment]
Well the issue is how properly document this so it's not a "new gotcha" as most user doesn't read the documentation :/
