### ISSUE TITLE
Docs: Missing "Social Icons" in "Basic layout example"

### ISSUE THREAD

**Issue by Hocdoc** [mjmlio/mjml#2148]
A minor thing: 

In the [Basic layout example](https://documentation.mjml.io/#basic-layout-example) the documentation has a section for "Social icons". But the Facebook icon is missing in the [Try-it-Live-Template](https://mjml.io/try-it-live/templates/basic). It would be nice, if the example is on the same state as the docs.

**Comment by kmcb777** [comment]
Hi, thanks for reporting this
The example template is defined at the website level, so we'll have to wait for a release of the site.
