### ISSUE TITLE
TypeError: Class constructor BodyComponent cannot be invoked without 'new'

### ISSUE THREAD

**Issue by btourman** [mjmlio/mjml#2149]
Hi everyone,

I'm developer on https://github.com/image-charts/mjml-chart 

Recently I try to bump mjml-* dependencies from 4.7.1 to 4.8.1.
But when I run our tests, `TypeError: Class constructor BodyComponent cannot be invoked without 'new'` appears.
And I don't know why I have this error

Here is the component file https://github.com/image-charts/mjml-chart/blob/master/src/index.js

**To Reproduce**
1. Clone https://github.com/image-charts/mjml-chart
2. Bump mjml-* to 4.8.1
3. Run `npm test`

**MJML environment (please complete the following information):**
 - OS: MacOS Catalina
 - MJML Version 4.8.1
 - Node Version 14.15.1
 - NPM Version 6.14.8

**Comment by TrySound** [comment]
Looks like it's because native class is trying to be extended by not native class. I guess we need to enable class transpilation back until next v5.

**Comment by iRyusa** [comment]
Do we have the same issue within the component boilerplate ?

**Comment by TrySound** [comment]
What's "component boilerplate"?

**Comment by YasiOnFire** [comment]
Component boilerplate repo:
[https://github.com/mjmlio/mjml-component-boilerplate](https://github.com/mjmlio/mjml-component-boilerplate)

Same error for me for all my custom mjml components that are based on component boilerplate.

**Comment by kmcb777** [comment]
Hi @btourman @YasiOnFire this should be fixed in the freshly released mjml 4.8.2
