### ISSUE TITLE
Question - Add CellPadding to Section

### ISSUE THREAD

**Issue by baltazaroliveira** [mjmlio/mjml#2152]
Hello,

How to set cellpadding in mj-section?

Thanks,
Baltazar

**Comment by iRyusa** [comment]
There's no `cellpadding` in MJML

section does support padding left and right, and column support padding left/right and `inner-background-color` for gutter between columns

**Comment by baltazaroliveira** [comment]
It should support, I have to change file after being saved by MJML...

Any other solution?

**Comment by iRyusa** [comment]
You can still use https://documentation.mjml.io/#mj-html-attributes to alter HTML.
