### ISSUE TITLE
`mj-spacer` component is missing `css-class` property implementation

### ISSUE THREAD

**Issue by glukki** [mjmlio/mjml#2155]
**Describe the bug**
[Documentation](https://documentation.mjml.io/#mj-spacer) states, that the `mj-spacer` component has `css-class` property.
Yet, provided class doesn't get applied to the rendered element.

**To Reproduce**
1. Open https://mjml.io/try-it-live/PQ7gXRS86OC
2. inspect rendered div properties

**Expected behavior**
Rendered `div` has a `class="test"` attribute.

**MJML environment (please complete the following information):**
 - MJML Version 4.7.1

**Screenshots**
![Screenshot 2021-01-25 at 16 13 22](https://user-images.githubusercontent.com/140462/105711006-fb0a0300-5f28-11eb-9423-f3393b9caadc.png)

**Comment by iRyusa** [comment]
`css-class` inside `mj-column` elements is applied to the top level rendered element, here the `td`

**Comment by glukki** [comment]
@iRyusa oh! sorry, didn't notice :(
