### ISSUE TITLE
"mj-accordion-element" supports "border" strangely

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2157]
**Describe the bug**

- Whether using attribute `border` directly on an `mj-accordion-element` or through `mj-attribute` (as in the example mentioned below), borders change consistent with each `mj-accordion-text` overriding its `border-top` and `border-bottom`, thus changing all horizontal lines for the `mj-accordion` component except the top line.
- `mj-accordion-element` (https://documentation.mjml.io/#mj-accordion) does not list `border` among its supported attributes.
- https://mjml.io/try-it-live/gs3v2xeDrGl includes the `border` attribute on `mj-accordion-element`. I used it accidentally and missed the notice, `attribute border is illegal`.

**To Reproduce**
1. https://mjml.io/try-it-live/gs3v2xeDrGl (version 4.7.1)
2. MJML app (version ^4.8.1)
3. Node v12.18.4 and MJML version 4.8.1.
![image](https://user-images.githubusercontent.com/14095071/106055774-77305200-60b3-11eb-8d90-6d059b1922c2.png)

**Expected behavior**
MJML would be better if either

![image](https://user-images.githubusercontent.com/14095071/106056314-25d49280-60b4-11eb-8b86-42a3ee2b962d.png)

1. The code would ignore unsupported attributes (`border` on `mj-accordion-element`, in this case), or
2. We change the documentation to indicate support for `border` on `mj-accordion-element`.

Recommended: Option 1 above and not Option 2. Ignore unsupported attributes and leave the documentation as is. It's probably a rare author that wants the existing rendering. I don't have a good proposal for this attribute here.

**MJML environment (please complete the following information):**
current Windows 10; MJML versions above

**Additional context**
If the decision is to change the documentation, I volunteer to do it.

**Comment by iRyusa** [comment]
You can just add it to the doc, as it's seems intentional from the code.

**Comment by GarryFlemings** [comment]
Didn't expect that, but I'll put in the PR.

Maybe you'll want to disarm the syntax warning "Attribute border is illegal" for `accordion-element` before merging that PR?

**Comment by iRyusa** [comment]
You're right you can also add it to supported attribute
