### ISSUE TITLE
Outlook on Windows

### ISSUE THREAD

**Issue by jkindness** [mjmlio/mjml#2158]
**Describe the bug**
When setting using `<mj-column width="100%">`, it puts multiple columns on the same row only for outlook windows 10. Works fine with several other clients.

Notice how the link and text is to the right of the image when it should be below it. Should I be re-arranging this to use mj-sections for each row?
![Outlook Win 10](https://user-images.githubusercontent.com/5871512/106067143-0ea19f00-60cc-11eb-94b0-9f7a31df6e58.png)

**To Reproduce**
`<mjml>
  <mj-body>
    <mj-wrapper background-color="#ddd">
      <mj-section>
        <mj-column width="100%">
          <mj-image src="https://cdn2.hubspot.net/hub/5700957/hubfs/Product%20Releases/newsletter-sm.png?upscale=true&width=1200&upscale=true&name=newsletter-sm.png" />
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column width="100%">
          <mj-text><a href="https://test.com">
              An Update To Our Email Integrations</a></mj-text>
          <mj-text>Our Email Integrations have received some attention this week, with updates to our Active Campaign, Campaign Monitor, and Constant Contact integrations. Plus, we've added a new widget feature!</mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>`

**Expected behavior**
This is using the same version of outlook but on mac:
![Outlook Mac](https://user-images.githubusercontent.com/5871512/106067145-0f3a3580-60cc-11eb-81b3-7b5d2446cb6f.png)

**MJML environment (please complete the following information):**
 - OS: Win 10
 - MJML Version 4.7.1
 - MJML tool used: MJML App

**Email sending environment(for rendering issues)**:
 - Litmus

**Affected email clients (for rendering issues):**
 - Outlook 2016 win 10
 - Outlook 2019 win 10
 - Outlook 365 win 10

**Comment by iRyusa** [comment]
Did you enable the minifier on Litmus side ?

**Comment by jkindness** [comment]
@iRyusa No I didn't enable the minifier. I've also had a user forward me the broken version from their outlook so it seems to be a common issue.

**Comment by iRyusa** [comment]
Can't really reproduce on Email On Acid when just copy pasting your code without any modification.

> I've also had a user forward me the broken version from their outlook 

Forwarding will mess the layout anyway because email clients will alter the output when forwarding

**Comment by jkindness** [comment]
I realize forwarding will change things, but the forward did show the same issue that I can see in litmus. I just tried it on email on acid and indeed, the issue doesn't exist there. But since it does show on litmus and I had a user complain, I do believe there is an issue.

Is it best practice to create full width columns with the goal to create content on a single row?

**Comment by jkindness** [comment]
@iRyusa I have to apologize since I just realized that the code I originally pasted to reproduce the issue was wrong! This was other code I was testing to solve the problem which it did. Here is the problematic code which doesn't render properly in email on acid:

`<mjml>
  <mj-body>
    <mj-wrapper background-color="#ddd">
      <mj-section>
        <mj-column width="100%">
          <mj-image src="https://cdn2.hubspot.net/hub/5700957/hubfs/Product%20Releases/newsletter-sm.png?upscale=true&width=1200&upscale=true&name=newsletter-sm.png" />
        </mj-column>
        <mj-column width="100%">
          <mj-text><a href="https://test.com"> An Update To Our Email Integrations</a></mj-text>
          <mj-text>Our Email Integrations have received some attention this week, with updates to our Active Campaign, Campaign Monitor, and Constant Contact integrations. Plus, we've added a new widget feature!</mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>`

Notice the difference between the two sets of code is that I am using two columns within the same section set to 100% width. Is that something I shouldn't be doing? Again, sorry for the mix up!

**Comment by iRyusa** [comment]
You can't have more than 100% of content inside a single section. You can just keep using the same column with everything then.
