### ISSUE TITLE
How to remove @import declaration for font if I don't need it 

### ISSUE THREAD

**Issue by limiterCore** [mjmlio/mjml#216]
I don't want to 
@import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700); 
to be in my compilated file.

Is this a way to solve it?

**Comment by iRyusa** [comment]
Hello @limiterCore 

There's a font importer that should doing this job for you ( see https://github.com/mjmlio/mjml/blob/ca544a4cc42a11e1d8a00d3e232f5a68bbf52406/packages/mjml-core/src/helpers/getFontsImports.js ) 

Note that `Ubuntu` is a default font for many MJML element, you may need to set a custom `font-family` without Ubuntu.

**Comment by limiterCore** [comment]
Thx for the answer, @iRyusa , but I have not understood.

I use Verdana font in my current project, I set it with font-family everywhere it needs.
And now I don't want to use and import an external font (Ubuntu in this case)

As I undersand I need to go to mjml.core files and change it? If so, can you help me to find it, if I using a gulp-mjml.

**Comment by iRyusa** [comment]
Can you provide your MJML ? It looks like you miss one of them, it's a regexp that scan the mjml, so you have nothing to do.

**Comment by limiterCore** [comment]
MJML here https://gist.github.com/limiterCore/6c5a1dc7137ea33930a90a0b213a83e5

**Comment by lohek** [comment]
Hi !

Try this : https://mjml.io/try-it-live/78d82741133bcb2b7e4c98bbfb9c5e2d, i add `font-family="Verdana, sans-serif"` on mj-text and mj-list without `font-family`

**Comment by limiterCore** [comment]
@lohek, thank you so much :) Now I'm totally understand what should I do to remove any external font imports: set font-family to all components that have it's default value as 'Ubuntu...'

**Comment by lohek** [comment]
Yup, by default `mj-text`, `mj-list` and `mj-button` have `Ubuntu, Helvetica, Arial, sans-serif` for default `font-family`, so you need change all `mj-text`, `mj-list` and `mj-button` with other font for remove Ubuntu import !

**Comment by jitendravyas** [comment]
ok though why MJML creators want to use a custom font as a default font for some component, why not system fonts?

**Comment by in-in** [comment]
For my case `mjml-table` also have Ubuntu

**Comment by tamas-marton** [comment]
You may want to go on with mj-head»mj-attributes»mj-all»font-family instead of defining all the occuring element types (;

**Comment by dezechristophe** [comment]
this should work !
```
   <mj-head>
     <mj-attributes>
       <mj-all font-family="Helvetica Neue" />
     </mj-attributes>
   </mj-head>
```

**Comment by webuxr** [comment]
FYI: Solved this issue here... https://github.com/mjmlio/mjml/issues/257 ... i.e.: if you only want Roboto, use this:
```
<mj-head>
  <mj-font name="roboto"
           href="https://fonts.googleapis.com/css?family=Roboto" />
    <mj-attributes>
      <mj-all font-family="roboto, arial, sans-serif"
          ico-font-family="roboto, arial, sans-serif" />
    </mj-attributes>
</mj-head>
```

Cheers,
_rs

**Comment by jpwdesigns** [comment]
This is really silly. Remove google font default and use system fonts.

**Comment by webuxr** [comment]
> This is really silly. Remove google font default and use system fonts.

Agreed.

**Comment by iRyusa** [comment]
You can just override the internal by using `mjml --config.fonts={}` and I even think this could be in .mjmlconfig too 🤔
