### ISSUE TITLE
Gaps between <mj-section>

### ISSUE THREAD

**Issue by FarhaanaBeato** [mjmlio/mjml#2161]
There are horizontal gaps being created on my MJML template. The gaps only show up in Outlook on a PC (not Mac). The code is run through [Luminate Online](https://secure3.convio.net/hfhi/admin/AdminLogin). Once the email is received, the `<mj-section>`’s are nested in tables with a return (¶) in between each. On sections that have background colors, it appears as thick white lines between the tables.

![screenshot-3](https://user-images.githubusercontent.com/7244695/106194375-bb3b5980-617c-11eb-9121-ec0712464b9c.png)

**Comment by iRyusa** [comment]
Hi,

There's not much we can do if your ESP alter the HTML here you should
contact them instead.

**Comment by FarhaanaBeato** [comment]
Wait what?

**Comment by iRyusa** [comment]
The service you're using sending the email is altering the HTML produced by
MJML.

You can check this by sending with a free test service like
https://putsmail.com/

**Comment by FarhaanaBeato** [comment]
@iRyusa Yes. I’m trying to figure out what I can do to prevent those gaps.

**Comment by iRyusa** [comment]
As said there's nothing we can do MJML side to help you.

You have to contact your ESP ( Luminate Online ) to see why they are
altering the HTML.

**Comment by iRyusa** [comment]
As there's nothing we can do on our side I'm closing.
