### ISSUE TITLE
Odd white block showing in empty column

### ISSUE THREAD

**Issue by gtherat** [mjmlio/mjml#2162]
Here's my MJML markup:

![mjml-markup](https://user-images.githubusercontent.com/7010034/106356745-daabc100-62f9-11eb-9806-44abdf11c240.jpg)

And here is what I'm seeing in Outlook:

![mjml-section-gap](https://user-images.githubusercontent.com/7010034/106356724-a89a5f00-62f9-11eb-9ea3-343f48424d2c.jpg)

If anyone could shed some light on why there's a white block rendering between the sections, just on the left side - that would be amazing, it has me stumped! (Ignore the fact I have 'no' and 'stamp' joined as one word, I'll fix that!

Thanks

**Comment by gtherat** [comment]
If anyone is interested, I managed to resolve this by adding a 5px red image into the otherwise empty 1st and 3rd columns.

**Comment by iRyusa** [comment]
Yep sometime Outlook does need a bit of content inside column to draw it properly. I'm closing then
