### ISSUE TITLE
MJML-columns are not working in outlook 2016/19

### ISSUE THREAD

**Issue by ThomasPof** [mjmlio/mjml#2164]
**Describe the bug**
It's a known bug : `mjml-column` is not working on Outlook 2016/19 and Office 365 : it appear stacked. In addition, width is 100% on outlook, which doesn't help to have a "not that bad" design even if it's stacked

**Expected behavior**
I'd like to make the outlook/win10 preview at least a bit better than what I have now. Any known workaround ?

**Affected email clients (for rendering issues):**
 - Outlook 2016/19 and Office 365
 - Win 10

**Screenshots**
<img width="647" alt="Capture d’écran 2021-02-01 à 17 53 42" src="https://user-images.githubusercontent.com/11079771/106467943-be08b800-64b6-11eb-8ed7-0f42387ac612.png">

**Comment by ngarnier** [comment]
@ThomasPof this is not a known bug, but very likely related to your workflow.

Please edit your issue with the things we ask for in the bug template, especially the code you're using and how you're testing (directly in Litmus or sending it as an email to Litmus, and if so, how you're sending).

**Comment by ThomasPof** [comment]
My bad : this email is built and send through php, but I re-used one of my script that clean the code before sending it, and it was removing comments...
