### ISSUE TITLE
mj-section and mj-column border-radius do not get applied to borders

### ISSUE THREAD

**Issue by mrleemurray** [mjmlio/mjml#2165]
Border-radius on mj-section and mj-column do not get applied to border.

1. Create a file with this MJML code: 
```
<mjml>
    <mj-head>
        <mj-attributes>
          </mj-all>
          <mj-all padding="0px">

          </mj-all>
</mj-attributes>

      <mj-breakpoint width="480px"/>
        <mj-preview/>
</mj-head>

  <mj-body background-color="#ffffff" width="640px">

      <mj-section padding="24px 24px 24px 24px" border-radius="0px" background-color="#ffffff">
          <mj-column padding="16px 0px 16px 0px" border="4px solid green" border-radius="50px" background-color="pink" vertical-align="top">
              <mj-text padding="0px 48px 0px 24px" color="#000000" font-family="'Segoe UI', Arial" font-size="21px" font-weight="600" font-style="normal" line-height="32px" align="left">Header

              </mj-text>
              <mj-text padding="12px 48px 0px 24px" color="#000000" font-family="'Segoe UI', Arial" font-size="17px" font-weight="400" font-style="normal" line-height="24px" align="left">Subheader

              </mj-text>
              <mj-text padding="12px 48px 12px 24px" color="#000000" font-family="'Segoe UI', Arial" font-size="14px" font-weight="400" font-style="normal" line-height="20px" align="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

              </mj-text>
              <mj-button padding="20px 0px 8px 24px" color="#ffffff" font-family="'Segoe UI', Arial" font-size="16px" font-weight="600" font-style="normal" line-height="18px" align="left" background-color="maroon" border-radius="0px" width="106px" inner-padding="7px 15px 7px 15px">Click here

              </mj-button>

          </mj-column>

      </mj-section>
  </mj-body>
</mjml>

```
2. View preview on either the MJML desktop app or online "try-it-live" tool
3. See render error

I expect when I add a border-radius to an mj-section or mj-column element with a border it will be applied to both the border and the background fill, not just the background fill.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version [e.g. ^4.3.1]
 - MJML tool used [e.g MJML App, online "try-it-live" tool]

**Email sending environment(for rendering issues)**:
 - Outlook for Mac, Outlook Web

**Screenshots**
Green border should have radius applied to it
![image](https://user-images.githubusercontent.com/25487940/106485583-aaeeeb80-64a8-11eb-87c6-7ca6b37284b3.png)

**Comment by Hideman85** [comment]
Can you add it to the [documentation](https://documentation.mjml.io/#mj-section) please?

I was actually facing the same issue and found this issue before opening a new one.
A property on the mj-section would be really appreciated :)

**Comment by ikotun-dev** [comment]
Hey @Hideman85 , Can you please give more details on how you resolved this?
