### ISSUE TITLE
Changing Body Width causes text color to change

### ISSUE THREAD

**Issue by shinyidol** [mjmlio/mjml#2166]
**Describe the bug**
setting width to anything other than default causes all text in body to be black in some email clients.
` <mj-body width="700px" background-color="#D3D3D3">`

Simply removing the `width=700px` fixes the problem

**To Reproduce**
1.  <mj-body width="700px" background-color="#D3D3D3"> with hard coded text in white.
2. Send test email and read in Spark

**Expected behavior**
Text should be white, but showing up as black

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.8.1
 - MJML tool used MJML Editor

**Email sending environment(for rendering issues)**:
 - Mailjet

**Affected email clients (for rendering issues):**
 - Spark 
 - OS: MacOS

**Comment by iRyusa** [comment]
Spark isn't in our test scope so I don't know what could happen here.

It's a bit weird as body's width is defined anyway. Can you post full MJML
here https://mjml.io/try-it-live ?

**Comment by shinyidol** [comment]
Adding another variable when having a background-image.

`<mjml>

  <mj-head>

    <mj-attributes>
      <mj-text align="center" color="#555" />
      <mj-section background-color="#fff" />
    </mj-attributes>

  </mj-head>

  <mj-body width="700px">
    <mj-section background-url="https://shinyidol.s3.us-west-2.amazonaws.com/blackbg.png" padding="30px 0 0px">
      <mj-column>
                   <mj-text color="#FFFFFF">just testing out some text here</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

**Comment by iRyusa** [comment]
It's not related to mj-body width but to background image. It seems like a bug in their HTML sanitizer because if you replace `#FFFFFF` by `#FFFFEE` text will appear properly. 

You should contact them to see what they can do about it, for now you can just use a non true white color as we can't do anything on our side
