### ISSUE TITLE
Outlook column not spanning full width

### ISSUE THREAD

**Issue by mattdriscoll** [mjmlio/mjml#2167]
**Describe the bug**
Hello, I've had an issue with Outlook respecting column widths in the last couple of templates I've created. In my most recent email, the body is rendering correctly in most email clients, but not Outlook. In the screenshot below, you can see that the footer spans the full width, but the body is only roughly 2/3 of the width. I tried explicitly setting the column width to 100%, but not luck. 

(Side note for another issue, I actually had the opposite issue in a different template where Outlook was rendering the email full width no matter what I did. I only mention it because it was also limited to Outlook only)

Is there a known issue with Outlook rendering columns incorrectly in a recent update? Or does anything look obviously incorrect below? Or any workarounds?

Thank you for your help, I really appreciate your team and this tool.

**To Reproduce**
Here is my mjml code:
```mjml
<mjml>
  <mj-head>
    <mj-title>...</mj-title>
    <mj-preview>...</mj-preview>
    <mj-font name="Open Sans" href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700" />
    <mj-font name="Source Sans Pro" href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;0,700;1,400;1,700" />

    <mj-attributes>
      <mj-all
        font-family="Open Sans, Verdana, sans-serif"
      />
      <mj-text
        color="#06415e"
        font-family="Open Sans, Verdana, sans-serif"
        font-size="14px"
        line-height="24px"
      />
    </mj-attributes>
  </mj-head>

  <mj-body>
    <mj-section
      background-color="#fff"
      padding-top="30px"
      padding-bottom="0"
    >
      <!-- 
        *************************************
        This column is not spanning the full 
        width of the section in Outlook: 
        *************************************
      -->
      <mj-column
        background-color="#ffffff"
        padding-bottom="20px"
        width="100%"
      >
        <mj-image
          src="https://github.blog/wp-content/uploads/2021/01/102393310-07478b80-3f8d-11eb-84eb-392d555ebd29.png?w=218"
          width="218px"
          align="left"
          href="#"
        />

        <mj-text>
          <div pardot-region="Email Body" pardot-region-type="pardot">
            <p> ... </p>
          </div>
        </mj-text>
      </mj-column>
      <mj-column>
    </mj-section>

    <mj-section
      mj-class="dark-blue-background"
    >
      <mj-column
        width="34.5%"
        css-class="footer-left"
      >
        <mj-image
          src="https://github.blog/wp-content/uploads/2021/01/102393310-07478b80-3f8d-11eb-84eb-392d555ebd29.png?w=200"
          width="200px"
          align="left"
        >
        </mj-image>
      </mj-column>

      <mj-column
        width="64.5%"
        css-class="footer-right"
      >
        <mj-text
          mj-class="footer-social-label"
          padding-bottom="0px"
        >
          Follow us online
        </mj-text>

        <mj-raw>
          <tr>
            <td align="left" style="font-size:0px;padding:0px 25px 10px;word-break:break-word;">
              <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
                <tbody> ... </tbody>
              </table>
            </td>
          </tr>
        </mj-raw>

        <mj-text
          css-class="footer-boilerplate"
          mj-class="footer-boilerplate"
        >
          ...
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**MJML environment (please complete the following information):**
 - **OS:** MacOS
 - **MJML Version:** 4.8.1
 - **MJML tool used:** mjml-cli

**Email sending environment(for rendering issues)**:
 - **Platform used to send the email:** Pardot

**Affected email clients (for rendering issues):**
 - **Email Client:** Outlook 
 - **OS:** Windows / Mac

**Screenshots**
![image](https://user-images.githubusercontent.com/16880374/106558954-4bb1cb00-64ea-11eb-8985-6c7769048a21.png)

**Thank you for your help!**

**Comment by iRyusa** [comment]
Can you try to send your email via https://putsmail.com/ ?

**Comment by mattdriscoll** [comment]
I did, and it renders fine when it's delivered to my gmail. But it is still not rendering properly in Outlook.

**Comment by mattdriscoll** [comment]
I don't know if this is helpful, but here is a comparison between gmail with the expected layout behavior and several versions of outlook:

![mjml-outlook-comparison](https://user-images.githubusercontent.com/16880374/106681141-86b50c80-6585-11eb-8d57-b140338216da.png)

**Comment by iRyusa** [comment]
We really need the full email to understand what could go wrong here, basic
email works fine on email on acid for me so I guess either there's
something that mess up the ghost table for Outlook or something is altering
your email in some way.

**Comment by mattdriscoll** [comment]
I really appreciate your help. Here is the [link](https://putsmail.com/tests/1e8ba947-1404-44a1-9ae3-1f0c3ea80503) to the putsmail test with the generated html. 

(I think that link should work(?) Sorry, I'm not familiar with this service)

Are there any gotchas I need to look out for that could mess up the ghost table?

**Comment by mattdriscoll** [comment]
Whoa, user error here. There's a rogue opening `<mj-column>` tag right below the column in question. I'm used to the cli yelling at me for little errors like that, not sure why/how that one slipped through 🤷‍♂️

Thank you for your help and for the great tool.
