### ISSUE TITLE
border-radius top corners and bottom corners

### ISSUE THREAD

**Issue by basickarl** [mjmlio/mjml#2168]
Is it possible to achive the following?:

https://ibb.co/v3TN7bz

Basically a border-radius only on the top two corners of the top section and the bottom two corners of the bottom section. I was reading the documentation but can't seem to find out ho to do this.

If it's not possible today, feature request! :D

**Comment by iRyusa** [comment]
You can just check `border-radius` css documentation for that https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius MJML purely rely on it.

**Comment by basickarl** [comment]
> You can just check `border-radius` css documentation for that https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius MJML purely rely on it.

You seem to have misunderstood what I want to achieve. Did you even look at the link I posted?

border-top-left-radius="20px" does not seem to work.

**Comment by iRyusa** [comment]
Just use the shorthand version https://mjml.io/try-it-live/-6NNMX-HRNL

If the attribute isn't listed then it won't work.
