### ISSUE TITLE
mjml-raw cannot be used inside of mj-social prevents use of looping in a template language

### ISSUE THREAD

**Issue by samstickland** [mjmlio/mjml#2169]
**Describe the bug**

mjml-raw cannot be used inside of mj-social prevents use of looping in a template language

**To Reproduce**

I want to have ERB (embedded Ruby) in my MJML file:

```
      <mj-social padding-bottom='0'>
         <mj-raw><% I18n.t('navigation.social_media').each do |info| %></mj-raw>
           <mj-social-element href='<%= info[:link] %>' src="<%= attached info[:email_icon] %>"/>
        <mj-raw><% end %></mj-raw>
      </mj-social>
```

Produces the error: mjml-raw cannot be used inside of mj-social

Running without wrapping the template language in mj-raw gives this error: Element % doesn't exist or is not registered

**Expected behavior**

A single rendered social media table element is produced, with the containing loop in the ERB still present, so that when the ERB is processed the loop unroles to include all the social media networks.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.7.1
 - MJML tool used : CLI

**Comment by iRyusa** [comment]
vertical mode should work fine, but horizontal would need a small tweak to make it works https://github.com/mjmlio/mjml/blob/master/packages/mjml-social/src/Social.js#L96 cc @kmcb777  we can just render the content if it's a rawElement here ?

**Comment by kmcb777** [comment]
yes indeed like it's done in mj-column and others,
i opened a PR

**Comment by samstickland** [comment]
Awesome, thanks!
