### ISSUE TITLE
mj-button is missing title

### ISSUE THREAD

**Issue by lahdekorpi** [mjmlio/mjml#2175]
There is no title attribute for mj-button. This would be helpful to have in order to show a long tooltip for users as well as for accessibility.

Is there a technical reason why this was not implemented?

**Comment by iRyusa** [comment]
image & social already have it so feel free to open a PR to add it on button too 👍

**Comment by kvedantam** [comment]
From which version is this functionality available? We are on 4.9.3 and I am facing an issue with adding the title attribute to the button. It doesn't show up. All other attributes are fine.
