### ISSUE TITLE
Mjml not found

### ISSUE THREAD

**Issue by DeusExM** [mjmlio/mjml#2182]
Hello,
We have a problem with MJML and symfony.
We are using yarn and each time we are loading a page in the website we have an error (see the linked image).
error 500
"Error Output:"
sh: 1: exec: mjml: not found.

We are using yarn and we can compile all our emails with no problem. We can send email with no problem.
If I do mjml -V in the project path I have : 
mjml-core: 4.8.1
mjml-cli: 4.8.1

I'm on Ubuntu.

Do you have any solution ?

Thank you.

![Capture d’écran de 2021-02-17 16-39-43](https://user-images.githubusercontent.com/64694675/108230810-6e2a2200-7141-11eb-897b-5a7067af4d4f.png)

**Comment by iRyusa** [comment]
MJML binary isn't available in PATH when executed from PHP. 

We can't really help you on this one as it's not related to MJML directly here, you can try to install it locally and access it with absolute path instead.

**Comment by DeusExM** [comment]
What can I do ?
my PATH is : /usr/bin/:$PATH:./node_modules/.bin

**Comment by iRyusa** [comment]
Well you can try to echo PATH inside PHP and see that it will be different, you should use absolute path for that as said in previous comment.
