### ISSUE TITLE
recursive mj-class possible ?

### ISSUE THREAD

**Issue by LGMAM** [mjmlio/mjml#2187]
I have several themes for different customers and a set `<mj-class>` tags that work semantically, so to change themes I would just need to change these tag definitions. 

For example, color "header-main-100" is used several times in the mjml file.

```
<mj-class name="header-main-100" color="#E0EBF5"/>
<mj-class name="main" background-color="{{header-main-100}}"/>
...
<mj-class name="footer-bg" background-color="{{header-main-100}}"/>
...
```

meaning

```
<mj-class name="main" background-color="#E0EBF5"/>
<mj-class name="footer-bg" background-color="#E0EBF5"/>
```

Is there a way to get this behaviour "natively" ? I am now preprocessing the mjml file to generate a themed mjml file, but would like to save this step

Thanks.

**Comment by iRyusa** [comment]
The closest solution I would think of would be to rely on css var and replace them at the end, `juice` doesn't support them yet (https://github.com/Automattic/juice/issues/312).
It's way too close to a templating feature so I don't think this will be ever implemented.

**Comment by LGMAM** [comment]
Yeap, I am actually using php blade templates to generate "themed" mjml files.

Thanks. I will keep my current solution then.
