### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by vaishnavi-accountbox** [mjmlio/mjml#2189]
Hi MJML Team,

Is there a way to add a video to an email and it can play within the email and not open in a new tab/window?
We did some test with videos suggested by email acid, Reference -> https://www.emailonacid.com/blog/article/email-development/a_how_to_guide_to_embedding_html5_video_in_email/

Is there any way to fulfill this requirement ? Please suggest.

**Comment by iRyusa** [comment]
You can just follow this guide into a mj-text and this would work fine. 

We've discussed about a potential `mj-video` but the support is not really decent enough to provide a good fallback.
