### ISSUE TITLE
issues for table view in mobile 

### ISSUE THREAD

**Issue by ysy523** [mjmlio/mjml#2191]
![image](https://user-images.githubusercontent.com/26822323/109092452-84436e00-7751-11eb-8aad-f77f57cecfdf.png)
how to adjust this table  header and column problems?

**Comment by iRyusa** [comment]
There's not so much we can do as html tables aren't really responsive by design.

You can tweak everything with media queries, or try this solution https://medium.com/@nathankeenmelb/bulletproof-responsive-datatables-in-html-emails-64248b9e18f5
