### ISSUE TITLE
Pardot + MJML App v3.0.3:  Accordion does not work

### ISSUE THREAD

**Issue by nicmare** [mjmlio/mjml#2192]
**Describe the bug**
Accordion component does not work in Pardot Templates.

**To Reproduce**
1. Insert the [Accordion-Code from Example](https://mjml.io/try-it-live/components/accordion) into your Pardot template (HTML-Tab):
![image](https://user-images.githubusercontent.com/898582/109154462-997ac580-776e-11eb-9cda-7e6ee94f18ac.png)
2. as soon as to switch to Editor-Tab, the accordion stop working because it adds closing tag to early </label> to it:
![image](https://user-images.githubusercontent.com/898582/109154560-be6f3880-776e-11eb-9c09-0301593feeec.png)
HTML-Tab:
![image](https://user-images.githubusercontent.com/898582/109154619-d5ae2600-776e-11eb-918a-e113ba3fdd35.png)

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML v^4.8.1
 - MJML App v3.0.3

**Comment by iRyusa** [comment]
Not so much we can do here as the problem is in pardot not from our code. I suggest you to open a ticket on their side.

**Comment by nicmare** [comment]
sure, pardot tries to fix open html tags and does not understand whats going on here. its just a hint from my side that this component does not work there. do what ever you want with this hint ;-)
