### ISSUE TITLE
Thank you for the great app

### ISSUE THREAD

**Issue by nicmare** [mjmlio/mjml#2193]
Did a lot of templates in the past and was always a pain in the a…
Now found MJML and was surprised how simple and clever it is built. 
i use the mac app. its sufficient for me. but api looks interesting as well.
And best of all its free?? Really? Why? I would even pay for it (one time payment of course).
found mjml today through google and now we have the best email template ever since. 
checked it in litmus – looks well everywhere. 
**THANK YOU!**

**Comment by iRyusa** [comment]
👍
