### ISSUE TITLE
Consistent rendering of attributes on mj-body

### ISSUE THREAD

**Issue by Voltra** [mjmlio/mjml#2194]
**Describe the bug**
MJML attributes are not all applied on the generated body

**To Reproduce**
1. Create a file with this MJML code:
```mjml
<mjml>
  <mj-head>
    <mj-style>
      .background--background{
        background-color: #d7dde5;
      }
    </mj-style>
  </mj-head>

  <mj-body css-class="background--background" background-color="black"></mj-body>
</mjml>
```
2. Render it to HTML (any method)
3. Inspect the generated HTML
4. Notice the `background-color` style is applied to both the body and underlying div
5. Notice the `class` is not applied to the body but only on the underlying div

**Expected behavior**
All attributes to be properly set on the HTML body (as well as the underlying div ?)

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: v4.8.1
 - MJML tool used: MJML App

**Comment by iRyusa** [comment]
There's some inconsistency with background on `body` element

So if you want so you can just use a mj-style inline for that https://mjml.io/try-it-live/KIWpFzIu6EU

**Comment by Voltra** [comment]
It may be a **workaround** but for usage with media queries (e.g. `(prefers-color-scheme: dark)`), which cannot be inlined, this will not be a solution

**Comment by iRyusa** [comment]
Media query can just target the body tag ?

**Comment by Voltra** [comment]
Directly targeting elements removes the flexibility of using classes (especially if they were intended to be more generic)

**Comment by iRyusa** [comment]
Having extra rules for the single body element you can have in a document won't be the end of the world here. Especially when most css rules are ignored on body because some webmail client removes it anyway.
