### ISSUE TITLE
media queries not work in outlook 365 desktop

### ISSUE THREAD

**Issue by RebaekSoparkKitchen** [mjmlio/mjml#2195]
**Describe the bug**
Media queries in `<mj-style>` not work on outlook 365 desktop. I design everything mainly for mobile since mjml is mobile first. When I send email to outlook 365 desktop, the columns are in the same row means it knows it is desktop, however when I use @media in `<mj-style>`, it doesn't work in this situation. From my understanding, the format should be either complete mobile or complete desktop. The format in outlook 365 desktop seems like desktop but I can not deal with desktop format specifically.

**To Reproduce**
Steps to reproduce the behavior(a small example):
1. Create a file with this MJML code: 
```
<mjml>
  <mj-head>
    <mj-style>
      @media (min-width:480px) {
        .test-text {
          text-align: center !important;
        }
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column width="50%" border="1px solid red">
          <mj-text>
            <div class="test-text">should be center in desktop</div>
          </mj-text>
        </mj-column>
        <mj-column width="50%" border="1px solid green">
          <mj-text>
            should be left in both
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
2. Render it to HTML by doing gulp-mjml 4.0.2
3. Send the HTML to an email address with putsmail
4. See error: in outlook (outlook for microsoft 365 MSO(16.0.13127.21210) 64 bits)

**Expected behavior**
the string "should be center in desktop" center in the outlook 365 desktop

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: gulp-mjml 4.0.2
 - MJML tool used: vscode

**Email sending environment(for rendering issues)**:
 - Platform used to send the email:  [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client : outlook 365 desktop
 - OS: Windows
 - Browser : Chrome

**Screenshots**
The outlook screenshot for the code above.
![2021-02-27_22-31-33](https://user-images.githubusercontent.com/49260863/109390292-bae4d880-794b-11eb-9ccb-219d7447fc48.png)

**Additional context**
Thank you in advance!

**Comment by GarryFlemings** [comment]
Outlook.com (aka Outlook 365), sadly, doesn't support media queries. Bummer, eh!
https://caniuse.email/#media-queries
https://www.campaignmonitor.com/css/media-queries/media

**Comment by RebaekSoparkKitchen** [comment]
Thank you for the website sharing, it's really helpful. I will take that into the consideration and redesign the email, thank you!
