### ISSUE TITLE
Incorrect column width

### ISSUE THREAD

**Issue by tdenvl** [mjmlio/mjml#2196]
**Describe the bug**
Hi.

I've faced the issue related to width of mj-column.

**To Reproduce**
1. Create a new mail with this MJML code (https://mjml.io/try-it-live/VaIiI6vNsID):
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column width="35%" background-color="green">
          <mj-image padding="0" src="https://mjml.io/assets/img/easy-and-quick.png" />
        </mj-column>
        <mj-column width="25%" background-color="gray">
          <mj-image padding="0" src="https://mjml.io/assets/img/responsive.png" />
        </mj-column>
        <mj-column width="72px" background-color="green">
          <mj-text padding="0" align="center">
            <h2>Some text</h2>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>
```
*There are several mj-column, wrapped into mj-group. The last mj-column's width is in pixels. Body has default width - 600px.*

2. Switch to mobile view.
3. Open developer tools and observe with of the third column.

**Expected behavior**
Width of the third column is 12%.

**Actual behavior**
Width of the third column is 0.12%.

**MJML environment (please complete the following information):**
 - MJML Version [e.g. 4.7.1]

**Affected email clients (for rendering issues):**
 - All

**Screenshots**
<img width="1164" alt="2021-03-02 в 20 25 42" src="https://user-images.githubusercontent.com/6775317/109689787-7a819680-7ba7-11eb-95d7-aa3dcffcb7c2.png">

**Additional context**
Look like there is an issue in conversion pixels to percentages. Actually width should be: `(72px (column width) / 600px (body width) * 100%) = 12%`.
I suppose the issue is on this line: https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L141 (missed multiplication by 100).
Correct is: `${(100 * parsedWidth) / parseInt(containerWidth, 10)}%`

Thank you in advance!

**Comment by iRyusa** [comment]
From the doc 

>  Column inside a group must have a width in percentage, not in pixel
