### ISSUE TITLE
Using mj-html-attributes breaks template lib variables/tags

### ISSUE THREAD

**Issue by edbentinck** [mjmlio/mjml#2197]
**Describe the bug**
When adding custom attributes to tags using `mj-html-attributes`, template tags (e.g. ERB syntax) is incorrectly modified, as if there were html attributes themselves.

**To Reproduce**
1. Create a file with the following MJML code inside `mj-head`:
```
<mj-html-attributes>
    <mj-selector path=".deep-link a">
        <mj-html-attribute name="ses:no-track"><mj-html-attribute>
    </mj-selector>
</mj-html-attributes>
```
and the following MJML code (with Ruby ERB template tags) inside `mj-body`:
```
<mj-text>Hello <%= name %></mj-text>
<mj-button css-class="deep-link" href="https://google.com/">Visit Google</mj-button>
```
2. Render the file to HTML
3. The content of `mj-text` is rendered as:
```
Hello <%= name="" %="">
```

**Expected behavior**
The button link renders with the custom attribute, and the text above is left untouched.

**MJML environment (please complete the following information):**
 - OS: MacOS 10.15.7
 - mjml-core: 4.8.2
 - mjml-cli: 4.8.2

**Comment by iRyusa** [comment]
Hi !

We're aware about this but sadly there's nothing we can do. This was a known issue on MJML3 when we were using Cheerio as the main parser it detects `<%=` as a tag element and applying everything inside as an attribute.
As there's currently no alternative for cheerio, there's no other way to avoid html-attributes with templating :/ 

Hope we'll find an alternative someday...

**Comment by edbentinck** [comment]
Oh, that's too bad 😞  but thanks for the explanation.
