### ISSUE TITLE
Template scaling on mobile screens

### ISSUE THREAD

**Issue by vrshgv** [mjmlio/mjml#2199]
Hi MJML Team,

I'm facing an issue with mobile layout. In all email clients my template always stays with the same desktop scale: all the elements work fine (such as columns which come one after another on mobile screens, images, etc.), but font is too small and generally the template looks like it came from desktop, but with some mobile rules applied. In mjml builder on mobile screens font is enlarged according to the screen size. But in my case 16px font-size looks so much smaller on mobile devices and looks like it's not responsive and not convenient to read on mobile at all. My draft template (deleted some styles and imports here also):

<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all padding="0px"></mj-all>
      <mj-text font-weight="400" font-family="Montserrat, Tahoma, sans-serif" align="left" font-size="16px" line-height="20px"></mj-text>
    </mj-attributes>
  </mj-head>
  <mj-body font-family="Montserrat, Tahoma, sans-serif" background-color="#D7EFC5">

    <mj-wrapper border-radius="10px"  padding="60px 0px 20px" background-color="#fff">
      <mj-section padding-bottom="30px">
        <mj-column>
          <mj-image width="209px" src="http://l.aviata.kz/custloads/767698131/md_890145.png" alt="aviata-logo" padding="0px"></mj-image>
        </mj-column>
      </mj-section>
      <mj-section padding-bottom="45px">
        <mj-column width="100%">
          <mj-text padding-bottom="18px" font-weight="700" font-size="28px" line-height="34px">
            Путешествуем выгодно со</br> скидкой 30%
          </mj-text>
          <mj-image src="http://l.aviata.kz/custloads/767698131/md_890157.png" alt="travel-banner" padding="0px"></mj-image>
        </mj-column>
      </mj-section>
      <mj-section padding-bottom="20px">
        <mj-column>
          <mj-text>
            Всем привет! </br>
            Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section padding-bottom="20px">
        <mj-column>
          <mj-text padding-bottom="20px" font-weight="700" font-size="22px">
            Условия
          </mj-text>
          <mj-text>
            Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.
          </mj-text>
        </mj-column>
      </mj-section>

      <mj-section>
        <mj-column padding="10px 11px">
          <mj-image 
            src="http://l.aviata.kz/custloads/767698131/md_890155.png" 
            alt="city_1"
            href="https://aviata.kz"
          ></mj-image>
        </mj-column>
        <mj-column padding="10px 11px">
          <mj-image 
            src="http://l.aviata.kz/custloads/767698131/md_890155.png" 
            alt="city_2"
            href="https://aviata.kz"
          ></mj-image>
        </mj-column>    
        </mj-column>
      </mj-section>

      <mj-section padding="20px">
        <mj-column>
          <mj-button height="60px" font-size="20px" font-weight="700" border-radius="10px" background-color="#55BB06"
            href="https://aviata.kz/"> 
            Полетели!
          </mj-button>
        </mj-column>
      </mj-section>
    </mj-wrapper>

    <mj-section>
      <mj-column>
        <mj-raw>
          <div style="height:26px; background-color:#D7EFC5">
          </div>
        </mj-raw>
      </mj-column>
    </mj-section>

    <mj-wrapper border-radius="10px" padding="20px 20px 18px 20px" background-color="#fff">
      <mj-section>
        <mj-column width="100%">
          <mj-image align="center" src="http://l.aviata.kz/custloads/767698131/md_903344.png" alt="article-banner" padding-bottom="17px"></mj-image>
          <mj-text align="left" padding-bottom="15px" padding-left="0px" font-weight="700" font-size="18px">
            Как выбрать идеальный чемодан?
          </mj-text>
           <mj-button width="122px" align="left" font-size="14px" font-weight="600" font-size="15px" font-family="Montserrat, Tahoma, sans-serif" color="white" border-radius="6px" background-color="#55BB06"
            href="https://aviata.kz/">
            Читать
          </mj-button>
        </mj-column>
      </mj-section>
    </mj-wrapper>

    <mj-section>
      <mj-column>
        <mj-raw>
          <div style="height:26px; background-color:#D7EFC5">
          </div>
        </mj-raw>
      </mj-column>
    </mj-section>

    <mj-wrapper border-radius="10px" padding="40px 25px 5px 25px" background-color="#fff">
      <mj-section>
        <mj-column padding-bottom="35px">
          <mj-text align="center" font-size="24px" font-weight="700">
            Оцените нашу рассылку
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section>
        <mj-column padding-bottom="35px" border-radius="10px">
          <mj-button align="center" width="175px" height="35px" border="2px solid #55BB06" background-color="#fff" border-radius="10px"
            href="https://aviata.kz/">
            <img align="center" src="http://l.aviata.kz/custloads/767698131/md_890153.png" alt="like"/>
          </mj-button>
        </mj-column>
        <mj-column padding-bottom="35px">
          <mj-button align="center" width="175px" height="35px" border="2px solid #F01F1F" background-color="#fff" border-radius="10px"
            href="https://aviata.kz/">
            <img align="center" src="http://l.aviata.kz/custloads/767698131/md_890152.png" alt="dislike"/>
          </mj-button>
        </mj-column>
      </mj-section>
    </mj-wrapper>

    <mj-section>
      <mj-column>
        <mj-text align="center" color="#313030" font-family="Montserrat, Tahoma, sans-serif" font-size="11px">
          Это не оферта, цены на билеты устанавливают авиакомпании.
        </mj-text>
    </mj-section>
    <mj-section>

      <mj-column>
        <mj-raw>
          <div style="height:35px; background-color:#D7EFC5">
          </div>
        </mj-raw>
      </mj-column>
    </mj-section>

    <mj-section background-color="#D7EFC5" padding-bottom="25px">
      <mj-group>
        <mj-column>
          <mj-button background-color="rgba(255, 255, 255, 0.65)" border-radius="10px" color="#807E7E" height="20px" font-size="12px"
            href="https://aviata.kz/">
            Отписаться
          </mj-button>
        </mj-column>
        <mj-column>
          <mj-button background-color="rgba(255, 255, 255, 0.65)" border-radius="10px" color="#807E7E" height="20px" font-size="12px"
            href="https://aviata.kz/">
            Веб-версия
          </mj-button>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>

Please Help!
Thanks a lot for your awesome product

**Comment by iRyusa** [comment]
Not so much we can do about this, just tweak `font-size` with media queries in `mj-style`
