### ISSUE TITLE
Mailchimp error with Google Webfont

### ISSUE THREAD

**Issue by philippebarbosa** [mjmlio/mjml#22]
Hi,

By default, Mailchimp can't support `@import` webfont directly in a `<style>` tag :
![Image](http://barbo.sa.com/1jr1n/23qAwXGD+)  
It works by doing `<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>` instead.

Default compiling from mjml need that the html files must be edited to be Mailchimp compatible :(

**Comment by g13nn** [comment]
You could have an option to compile the template with MailChimp's template language.  So it would add required tags, remove in-line styling and compile as editable CSS in your head tags.

**Comment by iRyusa** [comment]
@hteumeuleu Replace `style` and `import` with `link` can have a downside for us ?

**Comment by iRyusa** [comment]
~Related to #19
