### ISSUE TITLE
Directories in output is skipped

### ISSUE THREAD

**Issue by pixelize** [mjmlio/mjml#220]
```
$ mjml -w bar/email.mjml -o foo/email.html
```

It will render path as `email.html` instead of `foo/email.html`.
I think the problem is `path.basename()` which removes the directories, see [mjml-cli/src/client.js#L75](https://github.com/mjmlio/mjml/blob/master/packages/mjml-cli/src/client.js#L75)
A possible solution would be using `path.dirname()` before.

**Comment by ngarnier** [comment]
If I'm correct this has been fixed with https://github.com/mjmlio/mjml/pull/239. Great job @pixelize!
