### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dbasilioesp** [mjmlio/mjml#2200]
**Describe the bug**
After install the package with the command `npm install -g mjml`, and run a simple file only with `mj-section mj-column mj-text`, the following error show:

```
➜  mjml index.mjml
File: index.mjml
TypeError: Cannot read property 'replace' of undefined

Command line error:
Input file(s) failed to render
```

PS: the version of mjml 4.7.1 is working.

**To Reproduce**
1. With node version 12.19.0 and npm version 6.14.8 install globally the mjml `npm install -g mjml`.
2. Create a file with this MJML code: 

```
<mj-section>
    <mj-column>
        <mj-text> Some text </mj-text>
    </mj-column>
</mj-section>
```

3. Render it to HTML by running:  `mjml index.mjml`

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - MJML Version 4.8.2
 - MJML tool used: MJML CLI

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**

![image](https://user-images.githubusercontent.com/894329/110111702-816afd80-7d8f-11eb-91ef-947063d8b062.png)

**Additional context**

**Comment by iRyusa** [comment]
Can you try to remove every global install and use a local install instead ?

**Comment by garrettc** [comment]
I'm getting the same error when trying to compile through node. 

Strict validation and compilation works on the command line with the local install. 

This is on macOS Catalina 10.15.7

```shell
$ which mjml
mjml not found

$ ./node_modules/.bin/mjml --version
mjml-core: 4.9.0
mjml-cli: 4.9.0

$ ./node_modules/.bin/mjml -l strict -v mjml/*.mjml

$ node index.js 
/Users/garrettc/sandbox/LWE/email-templates/node_modules/mjml-core/lib/helpers/minifyOutlookConditionnals.js:9
content.replace(/(<!--\[if\s[^\]]+]>)([\s\S]*?)(<!\[endif]-->)/gm, (match, prefix, content, suffix) => {
        ^

TypeError: Cannot read property 'replace' of undefined
    at _default (/Users/garrettc/sandbox/LWE/email-templates/node_modules/mjml-core/lib/helpers/minifyOutlookConditionnals.js:9:9)
    at mjml2html (/Users/garrettc/sandbox/LWE/email-templates/node_modules/mjml-core/lib/index.js:398:53)
    at file:///Users/garrettc/sandbox/LWE/email-templates/index.js:59:24
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

```

**Comment by iRyusa** [comment]
Just tried with a fresh install and it works fine, can you try to remove your `node_modules` first ?

**Comment by iRyusa** [comment]
Just tried with node 14.9 and it works fine here :(

Try maybe to remove `node_modules`, remove your lockfile, reinstall ?

If it still doesn't work did you have any mjml installed globally previously ?

**Comment by garrettc** [comment]
I removed `node_modules` and `package-lock.json`, still no joy.

I did have a global install, but I removed it after reading your response to **dbasilioesp** above:

```
$ ls /usr/local/lib/node_modules
caniuse-cmd       gulp              keybase-installer parker
eslint            hoodie-cli        less              watchless
grunt-cli         keybase           npm
```

**Comment by iRyusa** [comment]
Wait the cli works but not your script right ? If so you might be using mjml2html from `mjml-core` directly instead from `mjml` package ?

**Comment by iRyusa** [comment]
cc @kmcb777 We might need to handle this behavior in MJML5 where rendering without any dep registered would crash because of empty content returned by `processing` method

**Comment by garrettc** [comment]
Sorry folks, looks like this was user error. After to speaking to another dev on our team we realised that I was using `fs.readFileSync` to ingest the MJML file, but I wasn't specifying an encoding, so it was returning an object, not a string. 

This was broken:
```javascript
const data = fs.readFileSync(filePath);
const HtmlBody = mjml2html(data, mjmlOptions);
```

This worked:
```javascript
const data = fs.readFileSync(filePath, { encoding: "utf8" }); // added encoding option
const HtmlBody = mjml2html(data, mjmlOptions);
```

**Comment by iRyusa** [comment]
Feel free to reopen if you can provide more info @dbasilioesp

**Comment by dbasilioesp** [comment]
> Feel free to reopen if you can provide more info @dbasilioesp

Sorry by not respond @iRyusa, I will be able to test again next week.

**Comment by jrasanen** [comment]
I have the same issue with 4.9.0.

```javascript
import mjml2html from 'mjml-core';

const mjmlContent = `<mj-section>
  <mj-column>
      <mj-text> Some text </mj-text>
  </mj-column>
  </mj-section>
  `;

mjml2html(mjmlContent, {});
```

This throws an error:

```
TypeError: Cannot read property 'replace' of undefined
    at _default (deploy/node_modules/mjml-core/lib/helpers/minifyOutlookConditionnals.js:9:9)
    at Object.mjml2html [as default] (deploy/node_modules/mjml-core/lib/index.js:398:53)

```

**Comment by iRyusa** [comment]
Change
```
import mjml2html from 'mjml-core';
```
to
```
import mjml2html from 'mjml';
```

**Comment by jrasanen** [comment]
@iRyusa hmm, I tried that too, unfortunately, it didn't resolve the issue. This repository reproduces the issue:

https://github.com/jrasanen/mjmlbug/blob/trunk/index.ts
https://github.com/jrasanen/mjmlbug/blob/trunk/package.json

**Comment by kmcb777** [comment]
Hi, i think it's related to the fact that there is no <mjml> and <mj-body> tags in your mjml

**Comment by iRyusa** [comment]
Looks like you have no mjml root tag in your input string for some reason it crash

```
<mjml>
<mj-body>
<mj-section>
  <mj-column>
      <mj-text> Some text </mj-text>
  </mj-column>
  </mj-section>
  </mj-body>
</mjml>
```
works fine in your repo

**Comment by notflip** [comment]
> Hi, i think it's related to the fact that there is no `<mjml>` and `<mj-body>` tags in your mjml


Shouldn't this throw an MJMLValidationError instead?
