### ISSUE TITLE
unable to download font for the email content. 

### ISSUE THREAD

**Issue by jpca999** [mjmlio/mjml#2203]
**Describe the bug**

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2. Render it to HTML by doing '...'
3. Send the HTML to an email address with '...'

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**

**Additional context**

**Comment by kmcb777** [comment]
Hi, could you provide more information about your problem ?

**Comment by jpca999** [comment]
I’m trying to download .ttf from my secret but it’s not working.

**Comment by iRyusa** [comment]
You really need to provide more details about your issue here. 
What would you expect from us with 0 information provided ?

**Comment by kmcb777** [comment]
We'd still need more information,
could you provide your mjml ?
how did you test it ? using the cli, the mjml-app,... ?
on which email client did you test ?
