### ISSUE TITLE
Image gets stretched on mobile

### ISSUE THREAD

**Issue by fsalerno-sdc** [mjmlio/mjml#2207]
I have the following 650px by 170px image in my template:
```
<mj-section>
            <mj-column>
              	  <mj-image width="650px" height="170px" align="center" src="https://my-image.jpg"></mj-image>
            </mj-column>
</mj-section>
```

Which displays fine on desktop, but on mobile it gets stretched. I noticed that the HTML shows the width as 550px instead of 650px, so MJML is changing its width without keeping the aspect ratio constant.

This could be solved with object-fit and object-position, but I don't think they're well-supported on mobile. I've also tried using mj-raw and a div with a background image, background-size and background-position, but I don't know how well-supported those are and then it gets hard to center and size the element correctly.

How can I tell MJML what to do when the available width is less than the image's?

**Comment by iRyusa** [comment]
You should just not specify any height and it will be fine.

MJML remove padding to image width and cannot be wider than default body of 600px so that's why you have a 550 width here.
