### ISSUE TITLE
registerComponent when using mjml-browser

### ISSUE THREAD

**Issue by danfraticiu** [mjmlio/mjml#2208]
**Describe the bug**
Trying to register a new component while using `mjml-browser` fails with warning from webpack (create-react-app more specifically):

```
./node_modules/mjml-core/lib/index.js
Critical dependency: the request of a dependency is an expression

./node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression

./node_modules/mjml-core/lib/helpers/mjmlconfig.js
Critical dependency: the request of a dependency is an expression
```

and in browser:

```
TypeError: fs.readFileSync is not a function
```

**To Reproduce**
1. call `registerComponent` in browser context.

**Expected behavior**
No warnings in console and the code to work

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.9
 - MJML tool used: n/a

**Email sending environment(for rendering issues)**:
 - N/A

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**
n/a

**Additional context**
For starters I'm trying to see figure out if this use case is supposed to work, if not: can it be made to work? 

Any info on this is greatly appreciated.

**Comment by iRyusa** [comment]
Well this is clearly stated in the README of `mjml-browser`

> Unavailable features
> mj-include tags are unavailable and will be ignored.
> features involving the .mjmlconfig file are unavailable, which means no custom components.

https://github.com/mjmlio/mjml/blob/master/packages/mjml-browser/README.md#unavailable-features

For now there's not so much we can do about this
