### ISSUE TITLE
MJML needs to be rebuilt for my current platform

### ISSUE THREAD

**Issue by NikolaNbgd** [mjmlio/mjml#2209]
**Describe the bug**
After I installed mjml in Visual Studio Code I can't have it as an extension. I keep getting this info all the time

**Screenshot**
![Screen Shot 2021-03-17 at 10 21 25](https://user-images.githubusercontent.com/18666816/111444514-bc175300-870a-11eb-8dbf-fb9234d824f1.png)

Does anyone know how to resolve this problem? Thanks

**Comment by iRyusa** [comment]
It should take time to reinstall some package on your machine, double check that you use this one : https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml

And please use the extension repo instead https://github.com/mjmlio/vscode-mjml

**Comment by ico3iain** [comment]
I am getting the message
`MJML needs to be rebuilt for your current platform. Please wait for the installation to finish...` on vscode - mac

Can run commands for MJML so that side fine, but the icon for the ext doesnt show in the side toolbar

**Comment by VeryStrongFingers** [comment]
> MJML needs to be rebuilt for your current platform. Please wait for the installation to finish...

Getting the same message using a fresh VSCode setup on an M3 (arm64) MacBook Pro, extension version v1.6.0.
Will debug properly next time I'm writing a template.

**Comment by MarcoNaik** [comment]
> I am getting the message `MJML needs to be rebuilt for your current platform. Please wait for the installation to finish...` on vscode - mac
> 
> Can run commands for MJML so that side fine, but the icon for the ext doesnt show in the side toolbar

same here, the icon appears but it doesnt render the mail ok

**Comment by HackettLai** [comment]
> I am getting the message `MJML needs to be rebuilt for your current platform. Please wait for the installation to finish...` on vscode - mac
> 
> Can run commands for MJML so that side fine, but the icon for the ext doesnt show in the side toolbar

Same, it keep showing the message while I can work with the MJML with no problem.

VSCode: Version: 1.92.0
Extension: v1.6.0
macOS: 14.5 (23F79)

**Comment by Appz-dk** [comment]
on macbook pro m1 in vscode this just stays "running" forever as soon as I have touched anything to do with MJML.

The only fix is to close vs code entirely. 

![image](https://github.com/user-attachments/assets/a0989c0b-390d-4a12-9f0a-d99be7bfd0a9)

**Comment by HackettLai** [comment]
> on macbook pro m1 in vscode this just stays "running" forever as soon as I have touched anything to do with MJML.
> 
> The only fix is to close vs code entirely.
> 
> ![image](https://private-user-images.githubusercontent.com/93446524/360839300-a0989c0b-390d-4a12-9f0a-d99be7bfd0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDAwODIsIm5iZiI6MTcyNDM5OTc4MiwicGF0aCI6Ii85MzQ0NjUyNC8zNjA4MzkzMDAtYTA5ODljMGItMzkwZC00YTEyLTlmMGEtZDk5YmU3YmZkMGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3NTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZmZiZjRmOGQwZDNiMzk1NzVlMjg1NzcyZWM2YjI0OTBiOWU5ZWNiMWIyOTA3MWFhYzkxMGIwZTZkZTBiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXs66CujcdJgVXx7qzVuIfBmr4PbDNIm33drr98CnMc)

Oh yes!! this is the one I keep seeing all the time!!!! No way to get rid of it.

**Comment by mlaass** [comment]
Same problem, on Linux, mjml works fine and the extension works fine, but I get the annoying popup, which I can't close.

**Comment by oelhammouchi** [comment]
Can confirm, same problem on Debian!

**Comment by murshex** [comment]
Me too. lol

**Comment by interaminense** [comment]
Many people getting that issue :(

**Comment by felix-berlin** [comment]
Same problem on Win11 with WSL 2 (Ubuntu LTS).

**Comment by iRyusa** [comment]
If you're still having this issue : please upgrade to the 2.0.0 version of the plugin. 
PhantomJS has been removed from it, so you should no longer see this message. If you do, it means you're using the wrong extension.

**Comment by murshex** [comment]
> If you're still having this issue : please upgrade to the 2.0.0 version of the plugin. PhantomJS has been removed from it, so you should no longer see this message. If you do, it means you're using the wrong extension.

Dear library author,

I recommend you to try it for yourself, fresh vscode installation, Windows. I promise you will be able to reproduce this problem. And make sure you use the right extension. ;)

**Comment by iRyusa** [comment]
![image](https://github.com/user-attachments/assets/79df85ec-fdd7-4a58-9139-1b39ab383184)

Just installed it without any issue.

**Comment by murshex** [comment]
![image](https://github.com/user-attachments/assets/dbca2fd9-7802-4276-851d-a85550c77bc6)

Ah ok, can confirm its working now too. I think your latest changes fixed it.

**Comment by timreach** [comment]
Am trying to install today and having this issue. I do not think this should be considered closed.

**Comment by iRyusa** [comment]
Either you've installed the old one, or not the 2.0.

**Comment by timreach** [comment]
I simply searched on the in-app VSC extension store and installed from there. I also downloaded from the browser portal for VSC extensions and dragged to my extensions and got the same thing, Certified 2.0

It's a small issue and I'm sure you have better things to be doing but just letting you know I experienced this. Thank you for your work!

**Comment by iRyusa** [comment]
Are you sure you don't have the other one installed too ? This message come from PhantomJS and is totally removed from the project, so there should be no way to get this message.

Can you do a CMD+SHIFT+P (CTRL+SHIFT+P) on Windows type "Show Running Extensions" and print screen the page ?

**Comment by timreach** [comment]
Ok, sorry, this was user error. I had confused myself with the "MJML" and "MJML Official" packages. Apologies!
