### ISSUE TITLE
Border-radius for mj-button at Outlook (Windows)

### ISSUE THREAD

**Issue by MrSerGV** [mjmlio/mjml#2212]
Hi MJML Team.
As I see at [documentation](https://mjml.io/compatibility/mj-button#attribute-border-radius) border-radius is not supported at Outlook (Windows).

Perhaps there is some way to set the border radius for the button at Outlook (Windows)?

Are you planning to make support for Outlook (Windows)?

**Comment by iRyusa** [comment]
`border-radius` can be done only with VML so there's no way to support without VML. You can use this https://buttons.cm/ but it won't work in section with background image.
