### ISSUE TITLE
Border-radius for mj-image at Outlook (Windows) 

### ISSUE THREAD

**Issue by MrSerGV** [mjmlio/mjml#2213]
Hi MJML Team.
As I see at [documentation](https://mjml.io/compatibility/mj-image) border-radius is supported at Outlook (Windows) 2013 and 2016.
But I had this [result](https://i.imgur.com/vrag04V.png).
It looks like the border radius is not working at Outlook (Windows) 2013, 2016 and also 2019.
Here code example:
`<mj-section>
      <mj-column>
        <mj-image width="300px" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" border-radius="20px" />
      </mj-column>
</mj-section>`

**Comment by iRyusa** [comment]
This was updated in 2017 and no longer really up to date, border radius won't work without VML in Windows Desktop version of Outlook
