### ISSUE TITLE
Is it possible to implement progress bar using mjml elements.

### ISSUE THREAD

**Issue by MrSerGV** [mjmlio/mjml#2214]
Hi MJML Team.
Is it possible to implement such progress bar using mjml elements?
![image.png](https://i.imgur.com/N6EYigZ.png)
We implemented using tables, but it is not displayed correctly at Outlook (Windows).

**Comment by iRyusa** [comment]
Nop there's nothing in MJML for this, you'll need to do some custom HTML here.

**Comment by GarryFlemings** [comment]
@MrSerGV One vote from the peanut gallery: If you do this custom HTML and can find a way to get it into a new community component, I think it'd be awesome! Dunno whether it would be approved, but it'd be great to see! Good luck! 🍀
