### ISSUE TITLE
Linter fails to generate an error when <mj-button> is used inside <mj-text>

### ISSUE THREAD

**Issue by jonosheehy** [mjmlio/mjml#2216]
The MJML linter fails to generate an error when an `<mj-button>` element is used inside an `<mj-text>` element.

Very basic example code is here: https://mjml.io/try-it-live/BNX2z0iVAdH (also pasted in full at the bottom of this bug report).

Tested on Windows 10 PC in:

- VS Code (running latest version), running latest version of the official MJML extension (running MJML version 4.8.0)
- https://mjml.io/try-it-live/ (on latest version of Chrome browser

Both failed to identify the error.

→ As expected, no button is generated (instead, the button text simply appears within the `<mj-text>` container, with that container's styling applied).
→ All that is missing is an error notification, so that the user realises their mistake.

***

Here is a very basic example code (same as in the 'try-it-live' link above):

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">
          Hello World
          <mj-button href="https://mjml.io/">
            CLICK HERE
          </mj-button>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Content tags aren’t parsed to ensure they’re not altered. So we can’t provide any warning about that.
