### ISSUE TITLE
Add telegram to social-element defaults

### ISSUE THREAD

**Issue by mattiaswerner** [mjmlio/mjml#2217]
**Is your feature request related to a problem? Please describe.**
I'm currently using a custom social-elements tag to get telegram (https://telegram.org) included in our social elements list. The platform is big enough now that I think inclusion into the defaults is warranted.

**Describe the solution you'd like**
I'd like telegram added as a default and usable just like facebook, twitter etc. social elements.

`<mj-social-element name="telegram" href="https://t.me/example"</mj-social-element>`

It should likely be using this icon as the default https://fontawesome.com/icons/telegram-plane?style=brands

**Describe alternatives you've considered**
The custom social element as described [here](https://mjml.io/documentation/#mj-social-element) is workable. I would still argue that telegram should be added to the defaults.

**Comment by iRyusa** [comment]
We don't want to extend this feature anymore (eg named social network) as you should use custom social element instead.
It's more flexible, portable, and not tied to MJML version.
