### ISSUE TITLE
responsive mj-group is not working in grapesjs-mjml preview

### ISSUE THREAD

**Issue by ThomasPof** [mjmlio/mjml#2220]
**Describe the bug**

**To Reproduce**
1. I've set-up a grapes-mjml builder here http://emailbuilder.thomas-dev.com
2. import a small amount of Mjml code
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column>
          <mj-image width="137px" height="185px" padding="0" src="https://mjml.io/assets/img/easy-and-quick.png">
          </mj-image>
          <mj-text align="center">
            <h2>Easy and quick
            </h2>
            <p>Write less code, save time and code more efficiently with MJML’s semantic syntax.
            </p>
          </mj-text>
        </mj-column>
        <mj-column>
          <mj-image width="166px" height="185px" padding="0" src="https://mjml.io/assets/img/responsive.png">
          </mj-image>
          <mj-text align="center">
            <h2>Responsive
            </h2>
            <p>MJML is responsive by design on most-popular email clients, even Outlook.
            </p>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>
```
3. use the responsive tool on left-top corner and inspect the preview. Try to locate the `.mj-column-per-50` element and his style

**Expected behavior**
The `mj-column-per-50` is not working as expected (keep things in two columns because inside of a mj-group)
As you can see on this image, it's wrapped into a `moz-text-html` class, and I don't know why. 
It's only in preview mode : when you generate the final html code, it works as expected.

**MJML environment**
 - MJML Version [e.g. 4.9.0]
 - MJML tool used [grapesjs-mjml]

**Screenshots**
<img width="1126" alt="Capture d’écran 2021-03-31 à 08 19 16" src="https://user-images.githubusercontent.com/11079771/113099500-56db5b80-91fa-11eb-97e8-0e350c857f2f.png">

**Comment by ThomasPof** [comment]
Hum... seems that's not on your side but more on the grapesjs-mjml config... don't really know yet, but I'm trying

**Comment by iRyusa** [comment]
> As you can see on this image, it's wrapped into a moz-text-html class, and I don't know why.

This has been added recently media queries are displayed 3 styles block before.

Doesn't seems related to MJML at all, I'm closing.
