### ISSUE TITLE
<Image /> default height of "auto" flagged as invalid by email on acid validator

### ISSUE THREAD

**Issue by pklada** [mjmlio/mjml#2224]
Image renders "auto" as default height property, which is flagged as an invalid value by some validation services. 

Not sure if this is actually a bug or if we care about it at all, but we're using MJML and currently fighting off some metrics drops. One hypothesis is email validation, specifically around email opens (i.e. less of our emails using MJML are being delivered), and whether some clients interpret the emails as having invalid markup.

Do we know if "auto" is acceptable as a default here? Thanks!

**Screenshots**
This is from email on acid: 
![image](https://user-images.githubusercontent.com/1474231/113923331-49474800-979d-11eb-8535-b6eb24ee00ac.png)

**Comment by iRyusa** [comment]
Not sure that would raise any issue,  I think it does something for Word-based Outlook but I might be wrong.

> Not sure if this is actually a bug or if we care about it at all, but we're using MJML and currently fighting off some metrics drops.

If you're talking about this email linked https://mjml.slack.com/archives/C12HESC2G/p1617919092264100 I've posted some hints about multiple issue you have in your MJML, I should be available in DM on slack if needed.

**Comment by pklada** [comment]
Thanks! Yeah we're in a better state now, will keep you updated.
