### ISSUE TITLE
add attributes to mj-carousel for positioning

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2225]
**Is your feature request related to a problem? Please describe.**
In the carousel, I wish I could position (1) the left and right icons from the sides of the top picture, (2) the three thumbnails from the bottom of the top picture, and (3) the horizontal spacing of the three thumbnails.

**Describe the solution you'd like**
(1) A solution equivalent to providing a parameter to replace "20px" in this:

```
<mj-style inline="inline" > {
	.mj-carousel-previous {
	  	  padding-right:20px !important;
	}
	.mj-carousel-next {
	  	  padding-left:20px !important;
	}
}
```

The first moves the left icon 20px to the left of its default position left of the top photo. The second similarly moves the right icon 20px to the right.

(2) A solution equivalent to providing a parameter to replace "20px" in this:

```
<mj-style inline="inline" > {
	  .mj-carousel-main {
	  	  padding-bottom: 20px !important;
	  }
}
```

This one moves the row of three thumbnails 20px lower from the top picture than their default position.

(3) A solution to widen the spacing between the three thumbnails below the top picture. 

**Describe alternatives you've considered**

(1) I foresee wanting to displace the icons about 10px to 50px from the top picture. I don't foresee wanting to displace one side by a different amount than the other, so a single parameter would satisfy my request. The team might consider whether some designers/developers would want both left and right offset parameters.

(2) I foresee wanting to use offsets of about 10px to 50px.

(3) I foresee wanting to use offsets of about 10px to 50px. The team might consider whether some designers/developers would want settings for (a) splitting available white space into four equal-sized gaps, 

![four-gaps](https://user-images.githubusercontent.com/14095071/113958656-15911000-97e7-11eb-92f1-1c1a9cc8bfb2.PNG)

and (b) splitting available white space into two equal-sized gaps.

![two-gaps](https://user-images.githubusercontent.com/14095071/113958631-07db8a80-97e7-11eb-8466-06c6e8152166.PNG)

I intend both pictures to show relative position. I didn't intend either to be in scale.

**Comment by iRyusa** [comment]
Not every element in carousel have wrapping table to support properly padding/margin everywhere.
If you find a workaround with css-class/mj-style you should better use it instead.

**Comment by GarryFlemings** [comment]
Good response. And, might we add more information?

I'm unfamiliar with the particulars of "wrapping table". Perhaps `.mj-carousel-previous`, `.mj-carousel-next`, and `.mj-carousel-main` are examples?

I'll respond in the context of all three suggestions above.

As to (1) and (2): These wrapping tables exist and are useful. Are they documented for use by our authors, other than in source code?

If they're not documented, they are available to only the small percentage of authors who are also capable of reading the source code and understanding the significance of these classes (a fairly demanding process for mere mortals; iRyusa: you're not a mere mortal in this respect!) And only to the portion of those motivated to read the source code.

In lieu of documenting the wrapping tables themselves, my suggestion is to put attributes in the language to abstract to tables from our authors. With the attributes, those tables become available for our general authors. MJML becomes more useful. Well, that's my theory.

A valuable alternative is documenting the wrapping tables and providing demo code, also making the tables more available.

As to (3): Perhaps your comment most directly applies here; perhaps there is no wrapping table for this aspect of the accordion. My suggestion is to add it. Perhaps your response is a terse way of saying that's not possible or advisable.

I consider it valuable to document more here before considering this closed.

**Comment by iRyusa** [comment]
We don't really want to document the HTML produced by MJML as it would clearly goes against abstracting component. All image lives in `label` and not `table` element, so padding can't work for clients like outlook here.

> If they're not documented, they are available to only the small percentage of authors who are also capable of reading the source code and understanding the significance of these classes

Well I don't agree with this if you use such a tool, you need to have basic knowledge of CSS, and HTML to at least know what is produced. Everyone can just inspect the DOM with any browser built-in developer tools now.

`mj-carousel` use case is really limited and it's a "hack" of css usage because we can't have any JS involved in email, so we don't want to push too much attribute on it.
