### ISSUE TITLE
Embedded image is not working -- like base64

### ISSUE THREAD

**Issue by meghal** [mjmlio/mjml#2227]
**Describe the bug**
Uploading the image and binding into base64 in src image.

**To Reproduce**
1.Upload image in editor
2. Call render API of mjml
3. Getting error in response.
![base64](https://user-images.githubusercontent.com/10130352/114258050-8dc32580-99e1-11eb-9bbb-71541e7c394b.JPG)

**Comment by iRyusa** [comment]
Well there's a limit on snippet size to avoid storage issue. You shouldn't paste base64 directly in email anyway as some client like gmail might clip it because of the HTML size.
