### ISSUE TITLE
mj-button not working as expected in outlook.

### ISSUE THREAD

**Issue by jayanthbondi** [mjmlio/mjml#2228]
This is mjml code.

`<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-button font-family="Helvetica" background-color="#f45e43" color="white" width="135px">
          Don't click me!
         </mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

This looks fine when I view it in browser.
![image](https://user-images.githubusercontent.com/35721161/114421911-6af86300-9bd3-11eb-8c64-c96b10758f8f.png)

But it's distorted when I view it in outlook.
![image](https://user-images.githubusercontent.com/35721161/114422015-85324100-9bd3-11eb-95d3-f6ae57d7e4ed.png)

Please help me out.
Thanks in advance.

**Comment by iRyusa** [comment]
Not much we can do about this, if you're using fixed width button you should check how it renders in you email clients as they might not have the same value for various thing like font-size, letter-spacing, ... and everything related to text size.

You should just switch to a fluid button instead or get some safety pixels in your desired width.

**Comment by jayanthbondi** [comment]
@iRyusa could you please show me a sample?

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/8Ndw1L8SJIU

**Comment by jayanthbondi** [comment]
This is my code snippet.

`<mjml>
  <mj-body width="750px">
    <mj-section>
       <mj-column width="10%" vertical-align="middle">
          <mj-image padding="0px" src="https://arya-react-email-editor-qa.s3.amazonaws.com/0fb45cd9-b9e3-4ed5-bbd0-b0ea3da62b2e/2b2e7d23-5be7-4ee9-b700-733fe375d75b-candidates%402x.png" width="52px" width="52" />
        </mj-column>
        <mj-column width="65%" vertical-align="middle">
          <mj-text padding="0px" color="#4C4C4C" font-family="Roboto" font-size="16px" font-weight="500" letter-spacing="0" line-height="19px">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard 
          </mj-text>
        </mj-column>
        <mj-column width="20%" vertical-align="middle" padding="0px">
          <mj-button height="24px" background-color="#13C26B" href="app-qa.goarya.com" padding="0px">
           Get Lorem Ipsum
          </mj-button>
        </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

![image](https://user-images.githubusercontent.com/35721161/114757502-91f09980-9d79-11eb-9f2c-bb7e8ab17c15.png)

Button text is breaking into 2 lines, I need it in a single line.

**Comment by iRyusa** [comment]
Try to reduce inner padding then or make the column a bit bigger.

**Comment by jayanthbondi** [comment]
@iRyusa I tried to reduce the inner padding, but it's not working in outlook.

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/6JOlJqEphHP
