### ISSUE TITLE
Columns not wrapping on Outlook Desktop

### ISSUE THREAD

**Issue by Alecell** [mjmlio/mjml#2229]
**Describe the bug**
Columns are displaying all in one roll on outlook.

**To Reproduce**
Create a section with background and some columns with width, it breaks when open on Outlook.

**Expected behavior**
The columns should break instead of clip outside of the container.

**MJML environment (please complete the following information):**
 - Linux Ubuntu 20.04 x64 / Windows 10 x64 Home Single Language version 1909
 - MJML Version: Web (probably LTS)
 - MJML tool used: MJML App

**Email sending environment(for rendering issues)**:
 - https://putsmail.com/tests/new

**Affected email clients (for rendering issues):**
 - Email Client Outlook desktop 2103
 - OS: Windows

**Snippet** 
https://mjml.io/try-it-live/i1hdrBAy10D

**Screenshots**
![01](https://user-images.githubusercontent.com/13935760/114432609-441c3b80-9b97-11eb-8c77-5ef272befeb0.JPG)
![02](https://user-images.githubusercontent.com/13935760/114432617-467e9580-9b97-11eb-8022-031b529153c1.JPG)
![03](https://user-images.githubusercontent.com/13935760/114432621-48485900-9b97-11eb-9cf4-ab08940a95dd.JPG)

**Full email**
[email.pdf](https://github.com/mjmlio/mjml/files/6298476/email.pdf)

**Other comments**
The footer is displaying wrongly, but is readable so I don't care too much.

**Comment by iRyusa** [comment]
Sum if column within a section can’e exceed 100%. Break those in multiple sections instead

**Comment by Alecell** [comment]
@iRyusa I just realise that this is write on the docs, I'm really sorry for that, but how can I keep the background image on all the three images without breaks?

**Comment by iRyusa** [comment]
You can use mj-wrapper to wrap multiple section https://documentation.mjml.io/#mj-wrapper note that you can't nest multiple background tho

**Comment by Alecell** [comment]
@iRyusa really really thank you, it worked as expected
