### ISSUE TITLE
[docs] Update "Using MJML in JSON" to show example of inline HMTL

### ISSUE THREAD

**Issue by marlonmarcello** [mjmlio/mjml#2230]
**Is your feature request related to a problem? Please describe.**
At the moment the "Using MJML in JSON" section of the docs isn't clear about what to do when you need HTML inside an element.
For example, if I wanted to have a span inside a `mj-text` would I:
1. Add the span as a children
```json
"tagName": "mj-text",
"attributes": {},
"children": [{
  "tagName": "span",
  "attributes": {
    "style": "font-size: 10px"
  },
  "content": "Text inside span"
}]
```

2. Or add the `span` inside **content** with the text
```json
"tagName": "mj-text",
"attributes": {},
"content": "A big text by default<br /><span style=\"font-size: 10px\">With a small text</span>"
```

**Describe the solution you'd like**
A note or example on the docs.

**Comment by iRyusa** [comment]
Well this is really easy to test if you're using MJML as JSON as you can just test the result of mjml2html function 😅

For the record, as `mj-text` is a "content tag" it cannot receive any children, so everything need to be in `content` like your 2nd exemple. You can simply add a PR here : https://github.com/mjmlio/mjml/blob/bd9bb7f10235ab473a0279c2768161504eace326/doc/using_mjml_in_json.md
