### ISSUE TITLE
Not able to center align the text and image inside mjml column

### ISSUE THREAD

**Issue by jayanthbondi** [mjmlio/mjml#2231]
I'm not able to center align the text and image inside mjml column

This is my code snippet.

`<mjml>
  <mj-body>
    <mj-section>
           <mj-column border="1px solid #DADBDD" border-radius="4px" vertical-align="middle" text-align="center">
         <mj-text align="left" vertical-align="middle" text-align="center" font-size="14px" color="#202830" line-height="22px">
            <img width="16"
              src="https://arya-react-email-editor-qa.s3.amazonaws.com/0fb45cd9-b9e3-4ed5-bbd0-b0ea3da62b2e/54a6458b-fea9-488c-b184-65c714d6ba03-Group%20117.png" vertical-align="middle" style="vertical-align:middle !important"/> 
            Radius 60 miles
          </mj-text>
        <mj-text font-size="12px" color="#202830" line-height="16px" padding-left="40px">
          Current: 3000 miles
        </mj-text />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

This is fine when viewed in Browser
![image](https://user-images.githubusercontent.com/35721161/114722428-6ceb2f00-9d57-11eb-8357-93ca0e634244.png)

But when viewed in outlook, the text and checkbox are not center aligned.

![image](https://user-images.githubusercontent.com/35721161/114722717-a91e8f80-9d57-11eb-81b6-6e36d6a2af53.png)

Please help me out,
Thanks in advance
.

**Comment by iRyusa** [comment]
Most likely doesn't work in outlook use a table instead of mj-text for something like this.

**Comment by jayanthbondi** [comment]
Hi @iRyusa ,

This is my code snippet
`<mjml>
  <mj-body>
    <mj-section>
      <mj-column border="1px solid #DADBDD" border-radius="4px" vertical-align="middle">
        <mj-table align="center" width="50%">
          <tr>
            <td width="10%">
              <img width="16"
                src="https://arya-react-email-editor-qa.s3.amazonaws.com/0fb45cd9-b9e3-4ed5-bbd0-b0ea3da62b2e/54a6458b-fea9-488c-b184-65c714d6ba03-Group%20117.png"
                 />
            </td>
            <td style="display: inline">
              <mj-text font-size="12px" color="#202830">
                Radius 600 miles
              </mj-text />
            </td>
          </tr>
          <tr>
        </mj-table>
        <mj-text font-size="12px" color="#202830" line-height="16px" padding-left="40px">
          Current: 3000 miles
        </mj-text />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

what can I do so that, 
1) my check box and text beside it are center aligned?
2) "Current: 3000 miles" should appear exactly below "Radius 600 miles" (aligned)
