### ISSUE TITLE
Unable to center align table elements

### ISSUE THREAD

**Issue by jayanthbondi** [mjmlio/mjml#2232]
Hi @iRyusa ,

This is my code snippet
`<mjml>
  <mj-body>
    <mj-section>
      <mj-column border="1px solid #DADBDD" border-radius="4px" vertical-align="middle">
        <mj-table align="center" width="50%">
          <tr>
            <td width="10%">
              <img width="16"
                src="https://arya-react-email-editor-qa.s3.amazonaws.com/0fb45cd9-b9e3-4ed5-bbd0-b0ea3da62b2e/54a6458b-fea9-488c-b184-65c714d6ba03-Group%20117.png"
                 />
            </td>
            <td style="display: inline">
              <mj-text font-size="12px" color="#202830">
                Radius 600 miles
              </mj-text />
            </td>
          </tr>
          <tr>
        </mj-table>
        <mj-text font-size="12px" color="#202830" line-height="16px" padding-left="40px">
          Current: 3000 miles
        </mj-text />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

what can I do so that, 
1) my check box and text beside it are center aligned?
2) "Current: 3000 miles" should appear exactly below "Radius 600 miles" (aligned)

![image](https://user-images.githubusercontent.com/35721161/114737359-8fd01000-9d64-11eb-8a90-6ea24e56a410.png)

**Comment by iRyusa** [comment]
Just use vertical align on `td` element that's how it works in HTML not anything special with MJML here.

https://mjml.io/try-it-live/FnOJRBXsL_Q

**Comment by jayanthbondi** [comment]
I tried vertical-align="middle" for td, but this is not working as expecetd
