### ISSUE TITLE
Roboto font is not working in outlook older version

### ISSUE THREAD

**Issue by jayanthbondi** [mjmlio/mjml#2233]
Roboto font is not working in outlook.

`<mjml>
  <mj-head>
    <mj-font name="Roboto" href="https://fonts.googleapis.com/css?family=Roboto" />
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-family="Roboto">
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`

![image](https://user-images.githubusercontent.com/35721161/114821872-dbbf9b00-9dde-11eb-9708-9e948d984b72.png)

**Comment by iRyusa** [comment]
Font doesn't work on most of clients check https://www.caniemail.com/features/css-at-font-face/ for client support.

**Comment by jayanthbondi** [comment]
@iRyusa is there any alternative for this?

**Comment by iRyusa** [comment]
Nop there's no way to do so.
