### ISSUE TITLE
Try it live editor never stops loading

### ISSUE THREAD

**Issue by grandeljay** [mjmlio/mjml#2235]
**Describe the bug**
The [Try it live](https://mjml.io/try-it-live/) editor never seems to finish loading.

**To Reproduce**
1. Visit https://mjml.io/try-it-live/

**Expected behavior**
The page should stop loading eventually.

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version 4.7.1
 - MJML tool used try it live editor

**Email sending environment(for rendering issues)**:
 - Platform used to send the email none

**Affected email clients (for rendering issues):**
 - Email Client None
 - OS: Windows
 - Browser Firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/45571053/114985907-a3c65f80-9e93-11eb-95c2-a2c161c08556.png)

**Additional context**
My guess is that the google tag manager script statement is at fault here, I couldn't find it in the network tab, which probably means it couldn't be loaded due to what looks like a faulty url:
```html
<script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-P62JWC6"></script>
```

**Comment by iRyusa** [comment]
`//` is a known trick to use the same protocol as current url. It loads up fine on network tab as you can see. We've never really had time to investigate on how to fix the infinite loading, but it should go back to normal when you start editing.
