### ISSUE TITLE
.mjmlconfig and options

### ISSUE THREAD

**Issue by nikolasdas** [mjmlio/mjml#2237]
Hey there!

I'm trying to call mjml (latest version, 4.9.0) from a npm script to build my mail templates. This works, but I want to use a `.mjmlconfig` file to control minification and some other config options.

This is my current setup:

_package.json:_
```json
"scripts": {
  "mjml": "mjml ./src/mails/*.mjml -o ./dist/mails --config.useMjmlConfigOptions true"
}
```

_.mjmlconfig:_
```json
{
  "packages": [],
  "options": {
    "minify": true,
    "minifyOptions": {
      "minifyCSS": true
    },
    "fonts": {},
    "keepComments": false
  }
}
```

Unfortunately, this seems to have no effect. I tried it with and without setting `--config.useMjmlConfigOptions`, as well as explicitly linking the config file with `--config.mjmlConfigPath`...

Any ideas?

**Comment by kmcb777** [comment]
Hi @nikolasdas we just released v4.9.1, this should be fixed you can try it out

**Comment by nikolasdas** [comment]
Thank you! I get a warning that "minify" option is deprecated. What is the correct way to use minification?

**Comment by GarryFlemings** [comment]
Maybe this note in December release notes helps?

> Move js-beautify and html-minifier to cli, and flag minify and beautify options as deprecated in mjml-core. They will be removed from the core and only available in cli in MJML 5.

**Comment by iRyusa** [comment]
@nikolasdas Minify will be removed in MJML 5 and we'll provide a migration guide when it happens

**Comment by kmcb777** [comment]
Seems like we can close this since the original issue has been fixed

**Comment by iRyusa** [comment]
Mostly to reduce external dependencies from `mjml-core`
