### ISSUE TITLE
[Question] Override padding, space and fontsize on mobile/desktop

### ISSUE THREAD

**Issue by weenzeel** [mjmlio/mjml#2239]
Hi!

My design spec calls for different font sizes, padding and spacing on desktop vs mobile. What’s the best way to do this with mjml while maximizing client support?

Any pointers welcome.

Thanks!

**Comment by iRyusa** [comment]
You can just use regular media queries for that

**Comment by weenzeel** [comment]
Thanks for responding @iRyusa.

> You can just use regular media queries for that

I've been experimenting with media queries. And I know that they aren't universally supported. So I think my question comes down to how to use the framework to maximize compatibility as much as possible. Should we do desktop first and override for mobile? Or should we do mobile first and override for desktop?

Consider this code that uses media queries to adjust desktop content to mobile via media queries:

```
<mjml>
  <mj-head>
    <mj-style>
      
      @media only screen and (max-width:600px) {

      	.padding-mobile > table > tbody > tr > td {
      
      		padding: 0px !important;
      
      	}      
      
      	.font-size-mobile > div {
      
      		font-size: 16px !important;
      		line-height: 24px !important;
      
      	}
      
      }
      
    </mj-style>
    <mj-attributes>
      <mj-all padding="0" />
    </mj-attributes>
  </mj-head>
  <mj-body background-color="#EEEEEE">
    <mj-section padding="32px" background-color="#FFFFFF" css-class="padding-mobile">
      <mj-column>
        <mj-text font-family="sans-serif" font-size="24px" line-height="32px" css-class="font-size-mobile">This is my content!</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

This isn't supported e.g. on Android and content is rendered to big.

If we try to do it the other way around, going from mobile layout to desktop-layout via queries I can't adjust padding in Outlook because of the hard coded guard tables for outlook that are inserted by MJML. Given the values calculated at compile-time space allocated to content will match the padding set for mobile. And the width of these tables aren't adjustable via css, right?

I'm leaning towards trying to find compromise values that will work acceptable on both mobile and desktop. Or go with the desktop first version and override as many mobile clients as are supported.

**Comment by iRyusa** [comment]
As MJML goes mobile first you should go for progressive enhancement via media queries. 

For outlook you can use mj-raw in head to wrap a style block with outlook conditionnal (when you add a css class, some ghost table will get a `-outlook` version of this class you can easily inspect it in generated html). 

For Outlook ghost table it just match column width. It only remove `mj-column`'s padding to avoid overflow when using gutter, but you should be safe with other padding

https://howtotarget.email/ has a lot of useful trick to target specific email clients

**Comment by weenzeel** [comment]
Just to make sure that I understand (thanks for taking the time) ... you suggest that I write MJML that replicates my mobile design. And then try and target different desktop clients via media-queries?

Do you have an example of what you mean with:

> use mj-raw in head to wrap a style block with outlook conditionnal

**Comment by iRyusa** [comment]
Most desktop client support media queries, if they doesn't it's better to have a mobile layout on desktop rather than desktop layout on mobile.

https://mjml.io/try-it-live/chxBt68IcDw for mj-raw in head
