### ISSUE TITLE
Warning: Please upgrade your MJML markup to add a <mjml> root tag

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#224]
Getting this error on a blank file when I run this command
`➜  mjml mjml --watch index.mjml -o index.html`

```
Warning: Please upgrade your MJML markup to add a <mjml> root tag, <mj-body> as root will no longer be supported soon, see https://github.com/mjmlio/mjml/UPGRADE.MD
TypeError: Cannot read property 'length' of undefined
    at documentParser (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:97:11)
    at MJMLRenderer.parseDocument (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:109:45)
    at new MJMLRenderer (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:76:12)
    at /usr/local/lib/node_modules/mjml/node_modules/mjml-cli/lib/client.js:107:12
```

**Comment by iRyusa** [comment]
Hello,
Can you provide your mjml version and your index.mjml ?

Thanks

**Comment by jitendravyas** [comment]
@iRyusa there is nothing inside my index.html. how to know installed mjml version?

**Comment by g0ddish** [comment]
For version use `mjml --version`.
What is the content of index.mjml **not** index.html?

**Comment by jitendravyas** [comment]
```
mjml --version
2.0.0
```

And my index.mjml has nothing. I just ran this command on blank file, is this the problem?

![index mjml nextmail mjml t8uh7](https://cloud.githubusercontent.com/assets/77309/15038165/03df7570-12bf-11e6-82ab-51468e10fa42.jpg)

**Comment by ngarnier** [comment]
Hey @jitendravyas, indeed you need some mjml in your file if you want it to be transpiled to responsive HTML :). 

You can start with this boilerplate: 
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica" align="center">Hello World</mj-text>
          <mj-divider border-color="#F45E43"></mj-divider>
          <mj-text font-size="16px" color="blue" font-family="helvetica">More text</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by jitendravyas** [comment]
@ngarnier Thanks. Though in opinion MJML should give some different message rather than this error if file is blank.

**Comment by iRyusa** [comment]
I think you have to update your MJML with npm. Because I haven't the same error than you with 2.0.2

**Comment by jitendravyas** [comment]
@iRyusa How to update to 2.0.2. I tried but it didn't work 

```
➜  mjml npm update mjml
➜  mjml npm update -g mjml
➜  mjml mjml --version
2.0.0
```

**Comment by lohek** [comment]
Maybe directly try `npm uninstall -g mjml` then `npm install -g mjml`

**Comment by jitendravyas** [comment]
@lohek I did as you said but still

```
➜  ~ mjml --version
2.0.0
➜  ~
```

**Comment by lohek** [comment]
Very weird https://www.npmjs.com/package/mjml the latest version is 2.0.2
What is your version of NodeJS ?

**Comment by dalefish** [comment]
I thought it would only report major versions... 2.0, 2.1 etc but not 2.0.2. Correct me if I'm wrong admins.

**Comment by jitendravyas** [comment]
@lohek 
```
➜  ~ node --version
v0.12.13
```

**Comment by iRyusa** [comment]
@jitendravyas Can you try to update to node > 4 please and try again ?

**Comment by jitendravyas** [comment]
it works after node upgrade though I need to run the watch command each time I want to see the result

**Comment by nnDjeff** [comment]
I'm having this issue as well on v2.3.1. 
My MJML file only contains the root and body tag.

Both -o and -w are giving the error message:
`Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file
    at MJMLError.Error (native)
    at new MJMLError (C:\Users\Jef Aerts\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-core\lib\Error.js:24:85)
    at documentParser (C:\Users\Jef Aerts\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-core\lib\parsers\document.js:140:11)
    at MJMLRenderer.parseDocument (C:\Users\Jef Aerts\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-core\lib\MJMLRenderer.js:129:22)
    at new MJMLRenderer (C:\Users\Jef Aerts\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-core\lib\MJMLRenderer.js:86:12)
    at C:\Users\Jef Aerts\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-cli\lib\client.js:107:12`

I've upgraded my Node as well, but that didn't resolve the issue.

**Comment by iRyusa** [comment]
Hello can you provide your MJML @nnDjeff ? Thanks

**Comment by nnDjeff** [comment]
Hi @iRyusa 

It's simply:
```
<mjml>
  <mj-body>
    
  </mj-body>
</mjml>
```

I added the file as well: 
[mjmlmail.zip](https://github.com/mjmlio/mjml/files/408945/mjmlmail.zip)

Hope it helps!

**Comment by iRyusa** [comment]
A MJML document with an empty `mj-body` is interpreted as if it had no `mj-body`, try to add a `mj-container` and it should be ok

**Comment by mattez** [comment]
Hi @iRyusa , @ngarnier please help, similar problem here:

for test purposes i use minimal file recommended by @ngarnier earlier in this tread.
My input.mjml file:
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica" align="center">Hello World</mj-text>
          <mj-divider border-color="#F45E43"></mj-divider>
          <mj-text font-size="16px" color="blue" font-family="helvetica">More text</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
I then run
```sh
$ mjml input.mjml -o content.html
```
works fine. Create new file _content.html_ with correct content - I'm happy. Then I try:
```sh
$ mjml -w input.mjml -o content.html
Now watching: input.mjml
```
I modify _input.mjml_ (e.g. "Hello World" to "Hello World 2") and save it:
```sh
$ mjml -w input.mjml -o content.html
Now watching: input.mjml
[16:00:07] Reloading MJML
Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" doesn't contain a child element.
    at new MJMLError (/home/mattez/.nvm/versions/node/v7.5.0/lib/node_modules/mjml/node_modules/mjml-core/lib/Error.js:26:110)
    at documentParser (/home/mattez/.nvm/versions/node/v7.5.0/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:174:11)
    at MJMLRenderer.parseDocument (/home/mattez/.nvm/versions/node/v7.5.0/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:162:45)
    at new MJMLRenderer (/home/mattez/.nvm/versions/node/v7.5.0/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:151:12)
    at mjml2html (/home/mattez/.nvm/versions/node/v7.5.0/lib/node_modules/mjml/node_modules/mjml-core/lib/index.js:66:10)
    at /home/mattez/.nvm/versions/node/v7.5.0/lib/node_modules/mjml/node_modules/mjml-cli/lib/client.js:94:36
(node:20280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" doesn't contain a child element.
(node:20280) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My setup:
- ubuntu 14.04 LTS
- node **v7.5.0**
- mjml **3.3.0**

What Im doing wrong? Thank you very much for your help.

**Comment by tvkit** [comment]
Not sure at what point this became necessary, but the container should be wrapped like this:

```
      <mjml>
        <mj-body>
          <mj-container>
             <!-- your awesome stuff here -->
          </mj-container>
        </mj-body>
      </mjml>


```
