### ISSUE TITLE
Can the OWA attribute be implemented back? 

### ISSUE THREAD

**Issue by Jax-p** [mjmlio/mjml#2241]
I know about the [new version of OWA](https://github.com/mjmlio/mjml/issues/2097) but as long as OWA can be self-hosted it doesn't have to be up-to-date. All of my clients and my company uses older versions of OWA and I had to downgrade MJML lib to 4.8.2 in all of my projects. 

Is there any possibility to bring this attribute back as long as it is optional?

**Comment by iRyusa** [comment]
Yep that should be easy to revert

**Comment by kmcb777** [comment]
Hi @Jax-p we added it back in v4.9.2, you can try it out

**Comment by Jax-p** [comment]
It works well! Thank you.

**Comment by ronaldohoch** [comment]
Hi guys, sorry for bring it back, but, for what purpose and what the difference between a non owa and a owa='desktop' in the final result of e-mails?

**Comment by iRyusa** [comment]
Outlook.com didnt support media query at that time and it allow you to display either the mobile or desktop version for that particular client
