### ISSUE TITLE
Slack link broken

### ISSUE THREAD

**Issue by JamesBelchamber** [mjmlio/mjml#2244]
Hey all. The community slack link is no longer working - it redirects to a generic Heroku page saying _"There's nothing here, yet"_: https://slack.mjml.io/

I'm guessing this coincides with the heroku billing changes for free dynos, but that was a little while back so it might be something else. Or it's possible the Slack is closed to new users :sweat_smile: in which case it probably needs removing from the readme :slightly_smiling_face:

**Comment by iRyusa** [comment]
Oh... Thanks for finding this we'll try to patch this is out asap !

**Comment by JamesBelchamber** [comment]
Could I get an invite in the mean time? I have questions :sweat_smile:

**Comment by GarryFlemings** [comment]
@JamesBelchamber Slack is working for me. If their application isn't working, please consider trying the URL. Any blocking in a firewall?

**Comment by iRyusa** [comment]
I've invited you on your email on your Github Profile.

We really need to host a new Slackin @kmcb777 😬

**Comment by iRyusa** [comment]
Well the tool we've used is now deprecated here's the link until we update the website https://join.slack.com/t/mjml/shared_invite/zt-gqmwfwmr-kPBnfuuB7wof5httaTcXxg

**Comment by iRyusa** [comment]
Hey we did it 😬 

Let's hope slack won't remove it this time 👍
