### ISSUE TITLE
Loads the version of the mobile layout when you click to reply or forward the email on the desktop.

### ISSUE THREAD

**Issue by filypeferreira** [mjmlio/mjml#2247]
**Describe the bug**
When receiving the email in the desktop version and clicking forward or reply to the email, the mobile version of the layout is applied.

**Expected behavior**
I would like when you click on the forward or reply to the email on the desktop keep the desktop version of the layout

**Email sending environment(for rendering issues)**:
 - Marketing Cloud

**Affected email clients (for rendering issues):**
 Gmail

**Comment by iRyusa** [comment]
There's nothing we can do about that as client alter the HTML when forwarding.
