### ISSUE TITLE
Responsive Image only 250px width?

### ISSUE THREAD

**Issue by nicmare** [mjmlio/mjml#2250]
**Describe the bug**
On large mobile Devices image in a two column layout is only 250px wide. i can see the 250px on the <td> in the generated html output. why is it there? why isn't it 100%? where can i change it?

**To Reproduce**
1. Create a file with this MJML code: `<mj-section padding="0">
        <mj-column>
          <mj-text mj-class="headline2" css-class="columns-two-text-image_title"> Content Bock #2 </mj-text>
          <mj-text css-class="columns-two-text-image_text"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. </mj-text>
        </mj-column>
        <mj-column>
          <mj-image src="http://go.powerschool.com/rs/861-RMI-846/images/HE Newsletter Winter Webinar v3.jpeg" alt="Peopleadmin" align="center" css-class="columns-two-text-image_image" />
        </mj-column>
      </mj-section>`
2. See error

**Expected behavior**
100% wide like on desktop view

**MJML environment (please complete the following information):**
 - OS: Big Sur
 - MJML Version 4.8.1
 - MJML App 3.0.3

**Screenshots**
![image](https://user-images.githubusercontent.com/898582/117142758-5e20f680-adb0-11eb-9ea8-100595aea78a.png)

![image](https://user-images.githubusercontent.com/898582/117142778-62e5aa80-adb0-11eb-839a-6d7c41963b23.png)

**Comment by iRyusa** [comment]
`mj-image` has a `fluid-on-mobile` attribute for this behavior. cf https://documentation.mjml.io/#mj-image it relies on a media query for this so support may vary.

**Comment by nicmare** [comment]
wow was searching for something like "250px" and found nothing.

**Comment by iRyusa** [comment]
The size will depend on the column size to avoid overflow issue in Desktop Outlook. It's a simple column width - (left+right padding) - (left+right border)
