### ISSUE TITLE
specific role="presentation" on layout tables

### ISSUE THREAD

**Issue by danfitz36** [mjmlio/mjml#2256]
**Is your feature request related to a problem? Please describe.**
for accessibility reasons, it would be nice to add `role="presentation"` to all tables that are used for layout and not content. that way screen readers know how to handle them properly.

**Describe alternatives you've considered**
I can manually add the attribute, but it would be nice to have it by default

**Comment by iRyusa** [comment]
Do you have an exemple where it's not applied because we already have it
for a while now ?
