### ISSUE TITLE
mj-section. wrong background-color

### ISSUE THREAD

**Issue by OReshetnikov** [mjmlio/mjml#2257]
**Describe the bug**
When I add two mj-sections (one of them has a full-width attribute) with an alpha background color, they have a different color.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add code: `<mjml>
    <mj-head>
    </mj-head>
    <mj-body>
        <mj-section background-color="rgba(8,20,222,0.5)">
        </mj-section>
      <mj-section full-width="full-width" background-color="rgba(8,20,222,0.5)">
    </mj-section>
    </mj-body>
</mjml>`
2. Put it to the https://mjml.io/try-it-live

4. See a differences

5. Or, just open the https://mjml.io/try-it-live/F-e5_701e2z

**Expected behaviour**
The colors should be the same in both cases

**Screenshots**

**Comment by iRyusa** [comment]
I'm not sure we can really do something about it, for compatibility we need
sometime to put the background color on multiple levels to ensure it
display on as many clients as possible.

Most desktop clients doesn't support rgb/rgba colors it should be safer to
go with hex colors everywhere

**Comment by OReshetnikov** [comment]
You're right. So, I will convert rgba to hex (6 digits) and replace it. Thanks
