### ISSUE TITLE
mjml getting flagged by npm audit due to vulnerabilities in lodash

### ISSUE THREAD

**Issue by packlam** [mjmlio/mjml#2258]
Hi,

Our CI pipeline has started flagging up issues from npm audit due to a security vulnerability in one of the dependencies of the various mjml packages - namely lodash <4.17.21 (see [here](https://www.npmjs.com/advisories/1673)).

It would be great if these could be updated sometime soon.

Thanks.

**Comment by iRyusa** [comment]
Hi,

Not really a big priority for us as `template` is not used within our codebase.

**Comment by iRyusa** [comment]
@kmcb777 did we update lodash in 4.10.1 ? If not can we do this for a .2 to close this
