### ISSUE TITLE
Border with 0px width show border on outlook 

### ISSUE THREAD

**Issue by dariuszpaluch** [mjmlio/mjml#2259]
**Describe the bug** 
When I add a border with value = `0px solid red` to `mj-column`, the border will visible on the outlook.

**To Reproduce**
1. Open [Basic layout example](https://documentation.mjml.io/#basic-layout-example)
2. Change line 8 to `<mj-column border="0px solid red">`
3. Send the HTML to an email address and open in one of `Outlook Office 365 - Windows 10`, `Outlook 2010 - Windows 7`, `Outlook 2013 - Windows 7`, `Outlook 2016 - windows 10`, `Outlook 2019 - windows 10`
4. You will see rer border around `My Company`

**Expected behavior**
I think every Mjml components should filter border value when is 0px

**MJML environment (please complete the following information):**
 - Windows 10 / Windows 7
 - MJML Version **4.7.1**
 - MJML tool used https://mjml.io/try-it-live/templates/basic

**Email sending environment(for rendering issues)**:
 - Gmail
 - Email on Acid

**Affected email clients (for rendering issues):**
 - Outlook Office 365 - Windows 10`
 - Outlook 2010 - Windows 7
 - Outlook 2013 - Windows 7`
 - Outlook 2016 - windows 10
 - Outlook 2019 - windows 10

**Screenshots**
![image](https://user-images.githubusercontent.com/15227876/118794683-1d3ddd00-b89a-11eb-8d4f-84fa2215c918.png)

**Comment by iRyusa** [comment]
Do you have a proper use case in mind ? Because I don't really think it would add anything to handle this.

**Comment by dariuszpaluch** [comment]
I use it because I added the ability to change border width in the UI editor for clients with possible values from 0 to 5 px.

Why I think it's important to fix:
 - `0px` border width is correct value for border-width
 - Bug is only on outlook, and if the programmer work on Gmail or Chrome while developing a new email template  will be ok, so very likely he not notice the problem on the outlook

**Comment by iRyusa** [comment]
I don't really like to "fix" a behavior like that in MJML as there no real user that would need to have such a fix within MJML. It would bloat a bit the way we're handling border for **every** component (meaning most likely a regexp) and come with a perf cost for large template.

I don't think this would need much change on your editor to remove completely the attribute if you have a 0px border ?
