### ISSUE TITLE
Shouldn't "--watch" inform the user when changes are detected?

### ISSUE THREAD

**Issue by tupini07** [mjmlio/mjml#226]
And also inform when 'compilation' has finished?

**Comment by arnaudbreton** [comment]
Hey @tupini07, thanks for your report and interest in MJML!

Could you please elaborate on what you mean by inform? Do you expect this "notification" to be just a display on standard output or also via a specific status/signal that another app could listen on?

Just want to clarify and be sure of what you expect here.

Thanks!

**Comment by tupini07** [comment]
Sorry, I should have elaborated more. I imagine a functionality similar to the 'grunt-contrib-watch' task where the user is informed, by means of the terminal, that:
1. A change has been detected
2. The 'compilation' task is running
3. The 'compilation' has finished
I think that for mjml's watch task it would be enough just to inform the user that a change has been detected and the HTML file is being updated.
This would be mostly so the user can receive feedback from the process

**Comment by ngarnier** [comment]
Hey @tupini07, I'm closing as this is now fixed by #234! Thanks for opening this issue and tell us what you think :-)
