### ISSUE TITLE
Can we make/use mj-social without icons?

### ISSUE THREAD

**Issue by Toumash** [mjmlio/mjml#2260]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to implement a horizontal list that will wrap on desktop, but stay stacked on mobile.

[**See the problem DEMO🔎**](https://mjml.io/try-it-live/jx_7jHFXFdS)

**Desktop**
X X X 
X
Y Y Y
**Stacked mobile**
X
X
X
X
Y
Y 
Y  

**Describe the solution you'd like**
The mj-social element has this exact behaviour, but it enforces the usage of icons. Can we make a component like this but remove the need for the icons?

**Describe alternatives you've considered**
I've tried to use media queries to use `display: inline-block;` on desktop, and `display: block;` on mobile, but Outlook Desktop always uses the media query properties, so it looks like the mobile version.

**Why not just use mj-column?** You may ask

It behaves very differently, because it wont wrap columns to the new line, but shrink then and wrap a column as a single block like that

X X X 
      X
Y Y Y
   Y

**Additional context**
The first line is the alternative behavior, but its not so useful on mobile device.
The mj-social below has a perfect behaviour for me, but i dont know how to use it without the icons.

![image](https://user-images.githubusercontent.com/9840635/118816435-7580d900-b8b2-11eb-8fe2-ba9d3eafd07b.png)

![image](https://user-images.githubusercontent.com/9840635/118816489-80d40480-b8b2-11eb-93fa-f19b87d8d67c.png)

**Comment by iRyusa** [comment]
Well you can maybe fork `mj-social-element` to remove the icon part and fit your need ? You might be able to replicate something similar with some media query with way less HTML produced at the end.
`mj-navbar` has a similar approach (if you just remove menu part).

I don't really have much time to think about a component like that, but that could be a nice thing to have. Could be hard to have a proper name for this behavior tho

**Comment by Toumash** [comment]
Ok, i'm gonna try to modify mj-social-element :)

**Comment by Toumash** [comment]
Meh, it actually renders different in the outlook - same as mj-column

mjml live editor:
![image](https://user-images.githubusercontent.com/9840635/118821114-36a15200-b8b7-11eb-9b25-cc3ebf5178a9.png)
Outlook:
![image](https://user-images.githubusercontent.com/9840635/118821070-2be6bd00-b8b7-11eb-902f-d98c782ed7e6.png)

**Comment by Toumash** [comment]
mj-navbar look below. I guess its fine, its stretching the template, but thats an alternative.
MJML live editor:

![image](https://user-images.githubusercontent.com/9840635/118821609-b2030380-b8b7-11eb-8f60-1b58b3d48ac4.png)

Outlook:

![image](https://user-images.githubusercontent.com/9840635/118821621-b4fdf400-b8b7-11eb-8ae8-6b453cbb4ed7.png)
