### ISSUE TITLE
Mjml image help

### ISSUE THREAD

**Issue by MomoOishiii** [mjmlio/mjml#2264]
Helloos! :D  

May I ask if there is a way to have an image as a floating/stand-alone within the column where it will not be affected by the other text/images? (like having it as a front layer while the text is the back layer?) 

Before: 
<img width="594" alt="Screenshot 2021-05-23 at 10 41 17 PM" src="https://user-images.githubusercontent.com/84673053/119265214-74d0a580-bc18-11eb-8974-6792958d7c31.png">

Result Looking to be Achieved: 
<img width="593" alt="Screenshot 2021-05-23 at 10 41 05 PM" src="https://user-images.githubusercontent.com/84673053/119265240-887c0c00-bc18-11eb-929a-a031aa83a03a.png">

**Comment by iRyusa** [comment]
Well "float" like image aren't supported in email. You might be able to use this tech https://www.goodemailcode.com/email-enhancements/faux-absolute-position but I'm not sure it will be enough.
You can still use a table to have text + img side by side.
