### ISSUE TITLE
MJML tags for table sub-components, including tr, th, td

### ISSUE THREAD

**Issue by d1manson** [mjmlio/mjml#2267]
**Is your feature request related to a problem? Please describe.**
I started with the table [example given in the docs](https://documentation.mjml.io/#mj-table), but I wanted my `th` tags to be the first column of cells rather than the first row of cells (as in the example). This looked like it was going to be fine in MJML itself, but when I sent the email to Gmail it was very corrupted after the second `th` (i.e. on the second row). For some reason none of the other cells in the table were displayed and the later sections outside the table were very broken. Switching to `td` rather than `th` seemed to fix it.

**Describe the solution you'd like**
I'd like to see `mj-tr`, `mj-td`, and `mj-th` tags, rather than using raw html inside a table. These tags could either compile to support both row/column forms of `th` or simply not allow you to make `th` in column form.

**Describe alternatives you've considered**
The alternative is to just use `td` as I explain above.

**Additional context**
This works:
```html
<mj-table>
  <tr>
    <th>column 1</th>
    <th>column 2</th>
  </tr>
  <tr>
     <td>value 1</td>
     <td>value 2</td>
  </tr>
</mj-table>
```

This doesn't work:
```html
<mj-table>
  <tr>
    <th>row 1</th>
    <td>value 1</th>
  </tr>
  <tr>
     <th>row 2</td>
     <td>value 2</td>
  </tr>
</mj-table>
```

Thanks!

**Comment by iRyusa** [comment]
Well if we do so then it would be really hard to use templating inside mj-table (meaning that you'll have to use mj-raw). There's no real benefit to overload HTML where it works perfectly fine.
