### ISSUE TITLE
Can we transpile MJML without <mjml>&<mjml-body> attributes ?

### ISSUE THREAD

**Issue by NicolasGiaco** [mjmlio/mjml#2269]
Hello, 

I have a small question about the use of the library

My team has a git repository of MJML templates, these templates use .mjml files which have certain characteristics, as for example below :

```
// OUR TEMPLATE
src/templates/bat.mjml

<mjml>
  <mj-head>
    <mj-title>My company BAT</mj-title>
    
    <mj-include path="./src/partials/attributes.mjml" />
  </mj-head>
   ...
```

```
// OUR CHARACTERISTIC
src/technical-blocks/attributes.mjml

<mj-attributes>
  <mj-class name="cta-yellow" background-color="#FFEA28" color="#000" border="2px solid #FFEA28" />
  <mj-class name="cta-dark-tr" background-color="transparent" color="#000" border="2px solid #000" />
  <mj-class name="title" font-size="25px" color="#262626" text-transform="uppercase" align="left" padding="20px 10px 0 20px" />
  ...
</mj-attributes>
```

We want to make our "characteristic library" available to our customers so they can use them in their templates. We therefore want to transpile our .mjml (not the templates) into .html .

But, we can't use mjml2html, because our .mjml don't have the `<mjlm>` and `<mjml-body>` tags. 

I therefore have this error:
```
node_modules/mjml-core/lib/helpers/minifyOutlookConditionnals.js:9
content.replace(/(<!--\[if\s[^\]]+]>)([\s\S]*?)(<!\[endif]-->)/gm, (match, prefix, content, suffix) => {
        ^

TypeError: Cannot read property 'replace' of undefined
```

Is there a way to transpile mjml without adding <mjml>/<mjmlbody> tags ? Is there anything I'm missing ? 

Thanks in advance !

**Comment by iRyusa** [comment]
There's no way to do so because some component like section/columns/hero ... can push some head styles and can't render only the HTML.

`mj-include` allows you to include files without MJML root tag but there's no other way.
