### ISSUE TITLE
Request: Allow and process `mj-include` as a child of `mj-preview`

### ISSUE THREAD

**Issue by rootwork** [mjmlio/mjml#2270]
As far as I can tell, you can't nest an `<mj-include>` inside an `<mj-preview>` -- the include never gets processed and the tag itself is included in the preview text.

The reason I'd like to be able to do this is to have the preview text file that I'm including have only the preview text itself in it -- not the wrapping `<mj-preview>` tags. If there's another way to do that without an include, let me know.

**Comment by iRyusa** [comment]
There's no way to do so because every ending tags aren't processed by the
parser to avoid issue we had with MJML3.

**Comment by rootwork** [comment]
Ah, OK. That's unfortunate.
