### ISSUE TITLE
Support for Passport

### ISSUE THREAD

**Issue by pcorpet** [mjmlio/mjml#2272]
**Is your feature request related to a problem? Please describe.**
All my MJML templates have been generated by Mailjet's online tool, Passport. As a result it contains some extra features that are not core to MJML4 and are ignored by the library.

**Describe the solution you'd like**
I'd like that some, if not all, Passport additions to MJML be supported by the library, or at least that I could implement them through a plugin system.

**Describe alternatives you've considered**
Stop using MJML programatically, and only rely on Passport to manipulate MJML and HTML.

**Additional context**
Here are some features that are done in MJML Passport:

`mj-section` may have an attribute (in JSON) to decide when they are shown:
```
          "attributes": {
            "padding-top": "0px",
            "passport": {
              "conditions": [
                {
                  "operator": "==",
                  "varName": "action",
                  "varValue": "converting"
                }
              ],
              "id": "oOnuhwTpP"
            },
            "text-align": "center",
            "vertical-align": "top"
          },
```
In the HTML, the corresponding section (actually `div` in HTML) is surrounded by `{% if var:action == "converting" %}` and {% endif %}

`mj-text` and probably other may have an attribute to hide them:
```
              "attributes": {
                "passport": {
                  "hidden": true,
                  "id": "GbpXTsxoBgXDz"
                }
              },
```
When `hidden` is `true`, the node is simply not rendered in HTML.

**Comment by iRyusa** [comment]
Passport features are exclusive to Mailjet ecosystem. If you need a
templating language you can pipe the result from mjml to any templating
lang.
