### ISSUE TITLE
MjImage breaks if you set width to 100% (probably all percentages)

### ISSUE THREAD

**Issue by chadfurman** [mjmlio/mjml#2274]
**Describe the bug**
https://github.com/mjmlio/mjml/blob/0fc8b3be2ab8058d3d7cc9139e743840d3215d72/packages/mjml-image/src/index.js#L77

This parsedWidth+unit doesn't work as expected.  Passing in 100% results in 100px being set on the td.

Also, note that the full-width property is undocumented: https://documentation.mjml.io/#mj-image

**To Reproduce**
1. Create a file with this MJML code: `return this.renderMJML(`
    <mj-image
      ${this.htmlAttributes<IMjImageComponent>({
        width: '100%'
      })}
    />
  `);`
2. Render it to HTML by doing 'mjml2html(mjmlHere, {
      keepComments: false,
      beautify: false,
      minify: true,
      validationLevel: 'soft',
    });'
3. display the html on the page
4. note the image is constrained

**Expected behavior**
image should be full width

**MJML environment (please complete the following information):**
 - OS: render on Linux in Node, display in Chrome on Mac
 - MJML Version 4.7.0
 - MJML tool used: npm library

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: displayed locally

**Affected email clients (for rendering issues):**
 - Google Chrome

**Screenshots**
Note here that the image is tiny

![Screen Shot 2021-05-28 at 10 06 26 AM](https://user-images.githubusercontent.com/635170/119996313-9e812800-bf9c-11eb-9715-f26fb64d8aa4.png)

Note here that I've set full-width prop on mj-image and it's fine:
![Screen Shot 2021-05-28 at 10 06 48 AM](https://user-images.githubusercontent.com/635170/119996398-b789d900-bf9c-11eb-9ef7-a54483591516.png)

**Comment by iRyusa** [comment]
If you check MJML Linter it warns you that it support only `px` values : 
<img width="747" alt="Capture d’écran 2021-05-28 à 16 13 54" src="https://user-images.githubusercontent.com/570317/119997554-1e74b580-bfd0-11eb-8edf-2e59b39c082e.png">

For that full-width attribute this seems a very old attempt to have `fluid-on-mobile`-like behavior without media query but never really worked. We should just remove this in the code.

**Comment by chadfurman** [comment]
There should be a way to make this image full-width.  I don't understand why I can't set width: 100% on the image, in general.  Something has to allow this -- if I have to set the width to a really large number I can do that, but that seems wrong.  I tried setting the width to 600px but it was set to 550px instead.  

There's definitely something that needs to be improved here.  I don't think this ticket should be closed outright

**Comment by iRyusa** [comment]
Older versions of Outlook doesn't behave so well with img in %. That's why we limit it to px only. 
As you have default padding on the mj-image you can just reset it to 0 because padding left/right are removed from the img size to avoid overflow.
