### ISSUE TITLE
is there a way to insert variable values inside the mjml file like the name of the person?

### ISSUE THREAD

**Issue by jpca999** [mjmlio/mjml#2275]
Is there a way to insert variable values inside the mjml file like the name of the person?
When I run the mjml  var_1 = "Mark Gold"  filename.mjml -o file.html   

It should replace the  var_1 inside the mjml file with "Mark Gold".

**Comment by iRyusa** [comment]
This has been replied multiple time you can find some answers here #1630 
You can plug anything to MJML with a bit of works there's few project listed in this issue but this won't be provided by MJML as it's a markup language.
