### ISSUE TITLE
Allows to minify without deprecation warning in core

### ISSUE THREAD

**Issue by adrien-zinger** [mjmlio/mjml#2277]
I'm building my project with the core by calling gulp, so using the core, with the minify option, and I receive lot of warnings. Since the project use htmlMinify in the core and in the cli, I would like to understand if this is a real feature or an omission. 

I would be interested to know the reason of this deprecation and if there is a real danger of using it in production. And furthermore, if we can allow users to minify in js.

Have a nice day !

**Comment by iRyusa** [comment]
Well it will be removed in MJML5 as a "built-in" feature, but we'll provide an easy way to add it back as a dependency.

**Comment by adrien-zinger** [comment]
Ok nice thank you !

**Comment by yvele** [comment]
> Well it will be removed in MJML5 as a "built-in" feature, but we'll provide an easy way to add it back as a dependency.

So what is the workaround to avoid the deprecation warning?

We want to make it nice and future proof in the Webpack loader:
  - https://github.com/BlitzBanana/webpack-mjml-loader/issues/26
