### ISSUE TITLE
Using the sizes attribute for <mj-image>

### ISSUE THREAD

**Issue by jonathan-wright-79** [mjmlio/mjml#2278]
**Describe the bug**
I can't get the sizes attribute to work, most likely I am doing something wrong but couldn't find an example. Was using this as my basis: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-sizes

1. Create a file with this MJML code: 

`<mjml>
  
  <mj-head>
    <mj-attributes>
      <mj-text padding="10px" />
      <mj-section padding="0px" />
      <mj-image padding="0px" />
      <mj-all font-family="Arial" font-size="12px" />
    </mj-attributes>
  </mj-head>
  <mj-body>
  
        

    <mj-section background-color="#35aade">
      
      <mj-column width="30%" padding="10px 0px 0px 0px">

        <mj-text align="left" font-size="22px" font-weight="600" color="#ffffff">
          22 - 23 September
        </mj-text>
        <mj-image align="left" src="https://info.tmforum.org/rs/021-WLD-815/images/DTWS-2021-circle_bottom-left_v2_300px.png" sizes="(max-width: 480px) 10px, 300px">

        </mj-image>

      </mj-column>
      

      <mj-group width="70%">      
      <mj-column width="80%" padding="10px 0px 10px 10px">
         <mj-text align="left" font-size="24px" font-weight="600" color="#ffffff">
          The time is now to make the vision a reality
        </mj-text>
        
        <mj-text align="left" font-size="14px" font-weight="600" color="#ffffff" line-height="18px">
          Burning questions answered:
          <ul>
          <li>Why is tech the future for telco?</li>
          <li>How can you think and operate as a techco? </li>
          <li>The search for growth: Can telecoms deliver? </li>  
          </ul>
        </mj-text>

      </mj-column>
      
      <mj-column width="20%" padding="0px 0px 0px 0px">

        <mj-image src="https://info.tmforum.org/rs/021-WLD-815/images/DTWS-2021-circle_top-right_300px.png">

        </mj-image>

      </mj-column>
     </mj-group>
    </mj-section>

    
  </mj-body>
</mjml>`

**Expected behavior**

I was wanting the left quarter circle image to appear smaller on mobile

**MJML environment (please complete the following information):**
 - MJML Version [e.g. 4.7.1]
 - MJML tool used [e.g MJML App on Chrome

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**

**Additional context**

**Comment by iRyusa** [comment]
Sizes attributes doesn't work like that. It only allow to the best image
within srcset see : https://github.com/mjmlio/mjml/issues/2278

You can use media queries to target mj-image `td` instead with a css-class

**Comment by Celsiusss** [comment]
> It only allow to the best image within srcset see : #2278 

You just linked this issue.

**Comment by mcsodn** [comment]
@iRyusa, you just linked this issue, can you show right link?

**Comment by iRyusa** [comment]
That's a good a question :D Can't remember really, you might found some answers here : #891
You should be able to find multiple discussions about srcset/size if you search in closed issues
