### ISSUE TITLE
howto scale image with different aspect ratio

### ISSUE THREAD

**Issue by giddel** [mjmlio/mjml#2280]
I want to provide images with complete different and unknown aspect ratios and sizes in Mailjet templates.
In top of the template I've got a paragraph to place the image. It should fit the place in optimal matter and keep it's aspect ratio.

Example:
https://mjml.io/try-it-live/f_KCXBYyWTz

The SWLB logo looks nice in the first version, but not acceptable in the second one.
And vice versa for the KIWIGRID logo.

It seems there is no proper solution for this?

**Comment by iRyusa** [comment]
There's no way to do so as mj-image rely on width (that need to be defined as pixel not percent as you've done) to handle older Outlook Desktop versions. 
You can try to use HTML `img` tag within `mj-text` and hope that you won't have any overflow issue in older clients.
