### ISSUE TITLE
Compatibility matrixes are out of date & missing some of the components

### ISSUE THREAD

**Issue by tuukkamustonen** [mjmlio/mjml#2281]
1. https://mjml.io/compatibility doesn't list all the `mj-*` components.
2. What it has, is quite outdated (seems like year 2016 was when it was last updated).

Is there plan to update the compatibility matrix regarding these?

**Comment by iRyusa** [comment]
Well I wish we had time and resources to update those matrices but I would highly recommend to use https://www.caniemail.com/ instead now as we try to document them when we needed.

Most component didn't change much from MJML3 so everything listed in those would still apply in MJML 4/5 for now.

**Comment by iRyusa** [comment]
Well there's way too many interaction with CSS/Attributes that it cannot be tested automatically :/
