### ISSUE TITLE
Align Body Container to left instead of center

### ISSUE THREAD

**Issue by nicmare** [mjmlio/mjml#2283]
Is there any reason why there is no option to left align the whole html code? Client ask for that but want him to tell why this is no good idea.
![image](https://user-images.githubusercontent.com/898582/121207191-6077e400-c879-11eb-99b6-b4611d1dc254.png)

**Comment by nicmare** [comment]
here is my solution:

`  <mjml>
  <mj-head>
<mj-style inline="inline">
      .body-section { text-align:left; margin:0 !important }
    </mj-style>
  </mj-head>
<mj-body background-color="#ffffff" width="600px">
    <mj-wrapper padding-top="0" padding-bottom="0" css-class="body-section"></mj-wrapper>
  </mj-body>`

seems to work

**Comment by iRyusa** [comment]
Well we've never really tested MJML to have non-centered content. 

I don't think there's technical limitations however, it might need some heavy tweaks to support background images and other things properly, so it's not really in our plan to support non-centered emails.

**Comment by matthijs-neijenhuijs** [comment]
I think it will be great to support this. For example: sometimes you want to send emails to your b2b clients. If they get a fancy centered email, they don't open it. They recognize it as a standard email. 

Sometime you only want to send a simple email:

Hi,

Hereby .....


With kind regards,
