### ISSUE TITLE
floating image? how?

### ISSUE THREAD

**Issue by kukac7** [mjmlio/mjml#2286]
hi,

sorry, i couldn't find a better forum for this. ([slack link is dead](https://slack.mjml.io/))
how can i do the layout shown in the picture?

thanks for the help!

<img width="619" alt="Screenshot 2021-06-10 at 12 51 32" src="https://user-images.githubusercontent.com/1240104/121513579-49f19a00-c9eb-11eb-8507-d1bbf50f4a42.png">

**Comment by iRyusa** [comment]
You can't really do something like that with MJML component, and you'll most likely have some compatibility issue.

You might be able to get some inspiration from https://sayo1337.medium.com/overlay-email-absolute-positioning-efd2f2f09ed4

**Comment by kukac7** [comment]
@iRyusa hm, interesting. and it doesn't look bad.

https://testi.at/proj/y91Te7PHgzLC8OvCMeNHrQzHex
