### ISSUE TITLE
Documentation: Provide examples of both singleton and regular tags on components that support both

### ISSUE THREAD

**Issue by rootwork** [mjmlio/mjml#2293]
**Is your feature request related to a problem? Please describe.**

I was trying to diagnose an issue with a parser messing up MJML's tags, and in particular the [`mj-image`](https://documentation.mjml.io/#mj-image) element. The documentation gives it this form:

`<mj-image width="300px" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" />`

But when I went to [Try It Live](https://mjml.io/try-it-live/) to experiment, I noticed the default example provided there is in this form:

`<mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>`

**Describe the solution you'd like**

It appears the `mj-image` element supports both a singleton/void form, and a regular (with-closing-tag) form.

If that's the case, could the documentation note that somehow?

And if there are other elements like this, that support both forms, could they note this as well?

It's just a small documentation thing, but for instance in my case realizing I could use the regular tag form meant I could avoid the problem I was trying to fix with the parser entirely.

Thanks!

**Comment by iRyusa** [comment]
> I was trying to diagnose an issue with a parser messing up MJML's tags
Can you provide an exemple where self-closing tag does mess up ?

I don't really know about this, there's multiple exemples of this with multiple tags. As MJML looks alike HTML, it looks explicit enough for me that it works like that (and for almost 6 years now ?).

**Comment by GarryFlemings** [comment]
Related question: Apart from the many MJML components for which self-closing tags are irrelevant (say, `mj-section` and `mj-column`), do all MJML components accept self-closing tags?

**Comment by iRyusa** [comment]
As HTML you can self close any tags it would render as if it has no children 🤷

**Comment by rootwork** [comment]
> Can you provide an exemple where self-closing tag does mess up ?

It was another library that does thing like transform apostrophes/tickmarks into curly quotes. It wasn't MJML's problem :)

If it's true (re @GarryFlemings' question) that all MJML elements that don't wrap content can use either self-closed or separate closing tags, then that's great! And I hear you @iRyusa about the structure of HTML. But I definitely didn't want to *assume* that MJML replicated all the standard forms of HTML! If so, that's great to hear.

**Comment by iRyusa** [comment]
Looks like it's mentioned in the getting started 

> This sections is made up of 2 columns. One containing an image, the other one containing a text. For the image part, note that when a tag does not have any child, you can use the XML self-closing tag syntax: <mj-image />

Not really ideal but at least it's here. We'll see when we overhaul the getting started to make it more visible.

There's already heavy sign that MJML follow XML/HTML principle in the doc, I don't think there's value here as there's enough exemples in the doc and should be implicit.

**Comment by rootwork** [comment]
You're right -- I apologize for overlooking that sentence in the getting started section.
