### ISSUE TITLE
Long url breaks layout in Outlook

### ISSUE THREAD

**Issue by philip-smr** [mjmlio/mjml#2297]
**Describe the bug**
Hi, is there any fix for long URL (of password recovery) that is generated and that breaks completely layout in MS Outlook.

** How the code looks now**
 <mj-section>
      <mj-column width="600px">
         <mj-text align="center">
            <a href="{{password_reset_url}}" >{{password_reset_url}}</a>
        </mj-text>
      </mj-column>
    </mj-section>

![Screenshot 2021-06-16 at 16 05 42](https://user-images.githubusercontent.com/82498721/122225143-7ad74080-cebd-11eb-8cd9-e171081aa3a4.png)

**MJML environment (please complete the following information):**
 - OS Big Sur
 - MJML Version 3.0.1
 - MJML tool used 4.6.2

**Email sending environment(for rendering issues)**:
 - Platform used to send the email is Sendgrid

**Affected email clients (for rendering issues):**
MS Outlook

**Screenshots**
![Screenshot 2021-06-16 at 16 06 08](https://user-images.githubusercontent.com/82498721/122224887-38adff00-cebd-11eb-98b2-f661fc62c861.png)

Please help, thank you

**Comment by iRyusa** [comment]
Did you tried to use `word-break:break-all;` on this ?

**Comment by philip-smr** [comment]
Yeah, I did, doesn't work. ` <a href="{{password_reset_url}}" style="word-break:break-all;">{{password_reset_url}}</a>` I use this construction, but the result for Outlook is the same.

**Comment by iRyusa** [comment]
Not so much we can do then if it's not supported. What version of Outlook you're trying to target ?

**Comment by philip-smr** [comment]
Microsoft® Outlook® for Microsoft 365 MSO (16.0.14026.20202) 64-bit

**Comment by probablyabear** [comment]
I solved a similar issue by adding a `css-class` that sets some text properties and, more importantly, sets an explicit width. 

```
<mj-style inline="inline">
      .wrapped-link > div, a {
      white-space: pre-wrap;      
      white-space: -moz-pre-wrap;  
      white-space: -pre-wrap;      
      white-space: -o-pre-wrap;    
      word-wrap: break-word;  
      word-break: break-all;
      width: 450px;    
      }
</mj-style>
```

**Comment by iRyusa** [comment]
Not so much we can do about this one if outlook 365 doesn't support word-break.
