### ISSUE TITLE
Better CLI debug

### ISSUE THREAD

**Issue by philippebarbosa** [mjmlio/mjml#23]
When doing a parse error, the debug does not tell which line from the mjml file is concerned :

```
➜  mjmltest  mjml -r test.mjml
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <td>. See Section > td > MJMLElement > MJMLColumnElement > tr.
```

**Comment by iRyusa** [comment]
Hello !
At this point, MJML markup doesn't have any validation.

**Comment by iRyusa** [comment]
Hello there! 

MJML doesn't provide any validation at this point. We're working to provide some on attributes & markup validation but at the moment we have nothing ready to be shown. 

The cuurrent warning you have is from React, could you provide your MJML maybe I can help with that ?

**Comment by philippebarbosa** [comment]
Hey Maxime,
in my case, i remember that i forgot to put a `mj-column` in my `mj-section`. Only that.
But i had to search few minutes before finding my error. Old school debugging :)

I'm just suggesting error as SCSS procesor do (`"at ligne XX"`… :))

**Comment by iRyusa** [comment]
Closing atm, a proper issue with validation concern will be open soon
