### ISSUE TITLE
contour

### ISSUE THREAD

**Issue by lucasabrantes1** [mjmlio/mjml#2300]
How can I define the outline in my email with predefined measurements?

![image](https://user-images.githubusercontent.com/62405928/122595636-23f97480-d03f-11eb-9bca-035b504272cd.png)

**Comment by GarryFlemings** [comment]
@lucasabrantes1 This isn't much detail. Any chance you can tell us more about what you want to accomplish by defining this outline? If you have code that demonstrates deficiencies in a prior attempt, please post it to https://mjml.io/try-it-live and send us the URL it assigns. (That way we'll see exactly what you do!) Thanks!

**Comment by iRyusa** [comment]
Feel free to reopen with more details. I think you can just use a simple section with padding for that.
