### ISSUE TITLE
Your Hero Demos: No difference fixed/fluid height

### ISSUE THREAD

**Issue by nicmare** [mjmlio/mjml#2306]
I try to understand the mode attribute. But when i open your examples they look the same?!

https://mjml.io/try-it-live/components/hero
https://mjml.io/try-it-live/components/hero/1 (even with error: attribute width is illegal)

i would expect the fluid height to adapt to its content. But it has the exact same height as the regular fixed height hero. So what is the general idea here?!

**Comment by iRyusa** [comment]
Hi

Fluid-height mostly try to keep the background aspect ratio and extends the container to display the whole background-image https://mjml.io/try-it-live/TE_04gsTBgn 
Fixed-height allow you to ensure the mj-hero will have a fixed height not related to background image https://mjml.io/try-it-live/o4T0WRuGwkT

Exemples without padding might be easier to understand ?
