### ISSUE TITLE
What are the best practices to nest elements?

### ISSUE THREAD

**Issue by floustao** [mjmlio/mjml#2307]
Looks like nesting wrappers is not an option with mjml.
In that situation, could someone guide me towards the best practices on how to build this skeleton:
![Screen Shot 2021-06-23 at 2 31 25 PM](https://user-images.githubusercontent.com/25415107/123171310-7caa8200-d430-11eb-88c7-6efae46a9349.png)

Specifically on how to build the gray block including the import summary.
In my code I already used a wrapper > section > column and I can't add a 4th level of nested mjml tag.
https://mjml.io/try-it-live/OGXOz8HdYdm

Appreciate the guidance, thank you

**Comment by iRyusa** [comment]
You should be able to play with `container-background-color` and `mj-table` for this kind of layouts https://mjml.io/try-it-live/FAoWyuPkCI5
