### ISSUE TITLE
Columns to not work when printing

### ISSUE THREAD

**Issue by jnnkB** [mjmlio/mjml#2308]
**Describe the bug**
When you print the generated newsletter HTML, columns no longer work. This happens because for the breakpoint a CSS media query is used containing `only screen`.

**To Reproduce**
1. Create a file with this MJML code:
   ```mjml
   <mjml>
     <mj-body>
       <mj-section>
         <mj-column>
           <mj-text>Hello</mj-text>
         </mj-column>
         <mj-column>
           <mj-text>World</mj-text>
         </mj-column>
       </mj-section>
     </mj-body>
   </mjml>
    ```

2. Render it to HTML e.g. by using https://mjml.io/try-it-live/. You can download the generated HTML [here](https://github.com/mjmlio/mjml/files/6711165/test.html.zip)

3. Open the HTML in a browser and try to print it

**Expected behavior**
It would look like the mail but with page breaks.

**MJML environment (please complete the following information):**
Happens in different environments, one of them being https://mjml.io/try-it-live/

**Screenshots**

How it should look
![non printend](https://user-images.githubusercontent.com/29376715/123308722-4cdca680-d524-11eb-9780-7fa301f857e4.png)

How it looks after being printed
![printed](https://user-images.githubusercontent.com/29376715/123308723-4e0dd380-d524-11eb-8260-1c88816339a1.png)

**Additional context**

**Comment by mohamedsalem401** [comment]
If you duplicate every CSS media query like `@media only screen and (min-width:480px)` and change it into `@media print and (min-width:480px)` , It will print just fine in browsers.

Maybe MJ-style should add both `only screen` and `print` to the media queries.

**Comment by iRyusa** [comment]
It won't really matter as most email client remove head style for printable version. As MJML is built mobile first there's nothing we can do about this.

**Comment by jnnkB** [comment]
> As MJML is built mobile first there's nothing we can do about this.

Why is that? Couldn't you change the media queries from
https://github.com/mjmlio/mjml/blob/bc90c8e05d59911cc6824fce23d5a8311d5c8d5f/packages/mjml-core/src/helpers/mediaQueries.js#L21
to one of these?
``` css
       @media (min-width:${breakpoint}) { 
```

``` css
       @media only screen and (min-width:${breakpoint}), print and (min-width:${breakpoint}) { 
```

The later one shouldn't affect the layout in any way when not printing.

**Comment by iRyusa** [comment]
> **as most email clients remove head style for printable version**

Test it by yourself, add it to the html and try to print it into Gmail, it will keep stacking columns.

**Comment by jnnkB** [comment]
You're right – Gmail indeed does not work. But in other mail clients like Windows Mail, Apple Mail and Geary it does. So maybe one could change it since it should not break anything and improves to experience on these clients?

**Comment by jnnkB** [comment]
What do you think @iRyusa?
