### ISSUE TITLE
Column elements are not centered on Yahoo

### ISSUE THREAD

**Issue by jeremybasolo** [mjmlio/mjml#231]
Images are not being centered properly on Yahoo Mail. Only solution I found for now is to use an mj-raw tag instead. Example:

                    <mj-raw>
                        <tr>
                            <td style="text-align:center;">
                                <img src="http://link-to-you-image.com/image.jpg" style="display:inline-block;margin: 0 auto;" />
                            </td>
                        </tr>
                    </mj-raw>

That'd be great if it could be fix natively in mj-image

**Comment by ngarnier** [comment]
hey @jeremybasolo, can you please provide screenshots of the issue with associated `mjml-code`? Also, do you know what might be causing it and / or how we could fix it?

**Comment by jeremybasolo** [comment]
Hi Nicolas,

Thanks for coming back to me!

Here's the mjml code I used:
http://digital.akauk.com/email-templates/two-columns.mjml
Which gives this html:
http://digital.akauk.com/email-templates/two-columns.html

The problem is the book tickets button image not being centered on Yahoo
mail (screenshot attached).
I think it's due to the img tag generated by mj-image, or the wrapping
table. It contains display:block in the style.

I think to fix the problem, you'd only need to apply display:inline-block
instead, and text-align:center on the wrapping element that is 100% wide.

Let me know if that helps.
Cheers




---------------------------------

JEREMY BASOLO
+44 (0) 7851 215 231
jeremy.basolo@gmail.com
http://jeremybasolo.com

**Comment by jeremybasolo** [comment]
Oh and also, noticed that the email was not centered on outlook.com, had to
fix it by wrapping everything inside mj-container
within <mj-raw><center></mj-raw> and <mj-raw></center></mj-raw>

Cheers


---------------------------------

JEREMY BASOLO
+44 (0) 7851 215 231
jeremy.basolo@gmail.com
http://jeremybasolo.com

**Comment by iRyusa** [comment]
From @aenohe investigation, it looks like `text-align:center` is in conflict with `align="center"` only on Yahoo...

**Comment by iRyusa** [comment]
I re-open until the 2.1 is released

**Comment by ngarnier** [comment]
Hey @jeremybasolo, this should be fixed with #261, feel free to reopen if it's not the case. Thanks for reporting the issue!
