### ISSUE TITLE
Dont use console.error for unknown components

### ISSUE THREAD

**Issue by timo-reymann** [mjmlio/mjml#2310]
**Is your feature request related to a problem? Please describe.**
I am the author of the mjml support for IntelliJ and integrate the mjml2html function inside a rendering function, communicating with my plugin via json on stdout. 

You can also see the very simple script here:
https://github.com/timo-reymann/intellij-mjml-support/blob/main/renderer/index.js

The problem is that when e. g. a tag is not defined the json is not parsable, because of some console outputs

**Describe the solution you'd like**
In my opinion errors should be populated in a more consistent manner. That means there should be no log output to stderr inside a general function, rather a error should be appended for it.

**Describe alternatives you've considered**
A very hacky solution would be:

```javascript
console.error = () => {};
```

But that would disable ALL error output in a node application i think this would be not optimal ...

**Additional context**
Location with the logging: https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/createComponent.js#L277

**Error message looks then sth like this**
```text
Error parsing result from stdout: No matching component for tag : mj-styl
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"No matching component for tag : mj-styl
{"html":"\n    <!doctype html>\n    <html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n      <head>\n        <title>\n          \n        </title>\n        <!--[if !mso]><!-->\n        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n        <!--<![endif]-->\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n        <meta name="[truncated 27886 chars]; line: 1, column: 3]

```

**Comment by iRyusa** [comment]
> The problem is that when e. g. a tag is not defined the json is not parsable, because of some console outputs

Console.error does write on process.stderr tho and not on stdout, you can just get the stdout output instead no ?

**Comment by timo-reymann** [comment]
Yeah this also an option. To be honest i havent thought about it that way.

In general would it make sense not to write to stdout/stderr on such a low level?

**Comment by iRyusa** [comment]
I don't know, for me stderr is the standard for a process to output runtime errors ? So I guess it's a legit use case here
Not closed about removing any interaction with std out/err in the lib itself but how as a process would it send an error signal without crashing the process ?

**Comment by timo-reymann** [comment]
Yeah i mean the function returns html and errors. So from my perspective it would make sense to have a single way to get errors.

**Comment by iRyusa** [comment]
Well the "errors" are more linter related errors, maybe we should rename this field to ensure there's no confusion 🤔 
Using a non-registered tag is way more critical than linter related, we could even throw a dedicated error for this we prefer to render the document at least.

**Comment by timo-reymann** [comment]
I created a separate ticket for fixing the problem with stderr in my project, thank you for clarification! :)

**Comment by timo-reymann** [comment]
Its also detecting the error in the errors output as far i see after first analysis. 

e. g. `Element mj-s doesn't exist or is not registered`
