### ISSUE TITLE
Rendering differences

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2313]
*Environment*
 - OS: Win10 Home 20H2 19042.1052 (current)
 - Either
    * Node.js 14.17.0 with MJML 4.10.1
    * MJML App with MJML 4.8.2
    * [Try-it-Live](https://mjml.io/try-it-live) with MJML 4.7.1
    * VS Code 1.56.1 with VS Code/MJML 1.0.4
 - Either
    * Chrome 92.0.4472.114 (current)
    * Firefox 89.0.2 (current)

*Subject code*

Either of:
 - [Try-it-Live](https://mjml.io/try-it-live/wHNtp7R7r6x)
 - [mj-include_allowed.txt](https://github.com/mjmlio/mjml/files/6730148/mj-include_allowed.txt) (Download and change extension to .mjml. Github doesn't support upload of .mjml files.)

*To Reproduce*

 - In Chrome and Firefox: Use Node.js, MJML, and the renamed file from above to create an HTML file equivalent to the above file. Point each browser to that file.
 - In VS Code: Edit the renamed file from above.

 - In the MJML App: Point the app to the renamed file from above.

 - In Try-it-Live: Click [Try-it-Live](https://mjml.io/try-it-live/wHNtp7R7r6x).

*Expected behavior*

All four renderings show only white text (#FAFAFA) on a blue background (#001FFE).

*Actual behavior*

 - Chrome, Firefox, and VS Code render as intended: The background is blue and the text is white.
![image](https://user-images.githubusercontent.com/14095071/123729213-399a4580-d85a-11eb-9e9d-0011fc1736fc.png)
    * Firefox and VS Code are effectively identical.

 - The MJML App:
![image](https://user-images.githubusercontent.com/14095071/123729295-5afb3180-d85a-11eb-8e4e-4200619e0cf0.png)
    * Text at the top left and bottom right is black, not white.
    * The background color is purple (#3700FD).

 - Try-it-Live:
![image](https://user-images.githubusercontent.com/14095071/123729352-7108f200-d85a-11eb-9f77-32d9c5b3f2de.png)
    * Text at the top left and bottom right is black, not white. (Matches the MJML App.)
    * The background color is as expected.

*Background*
The JetBrains HTML Support plugin reproduces the MJML App rendering.

**Comment by iRyusa** [comment]
For some reason re-rendering an iframe doesn't recognize the doctype of the document switching to quirks mode as it loads some weird css with a lot of overrides.

I'm closing, there's not so much we can do about this without compromising perf/adding visual glitches  when reloading the iframe entirely.

**Comment by GarryFlemings** [comment]
That happens (by this evidence) only for Try-it-Live and the MJML App (Electron)? Has anything common to them changed recently to cause this? This feels new.

**Comment by iRyusa** [comment]
Any browsers behave like this so it’s like this for a while

**Comment by GarryFlemings** [comment]
The browsers are operating correctly. The condition is only in Try-it-Live and the MJML App.

**Comment by iRyusa** [comment]
Every browsers behave like this with iframe when replacing content on the fly.

**Comment by GarryFlemings** [comment]
Here's a total surprise.

Sigh. Try-it-Live renders the same as Chrome and Firefox now.
![Screenshot 2021-07-01 145936](https://user-images.githubusercontent.com/14095071/124182923-20251380-da7d-11eb-8f84-140efe3d9e12.png)

That's different from just two days ago when I wrote this ticket.

The MJML App did not change from above.

I had another reason to put the code directly from this ticket into Try-it-Live again. Compare the above image to the third image in the original ticket. Here, all text is white.

Perhaps the Try-it-Live update from 4.7.1 to 4.9.3 was relevant? Something else?

**Comment by iRyusa** [comment]
It happens when it reload the iframe as I've said. Change a small character and it iframe goes in quirk mode from some unknown reasons.
