### ISSUE TITLE
Color Type does not support "inherit" and does not work without a value

### ISSUE THREAD

**Issue by chadfurman** [mjmlio/mjml#2315]
**Describe the bug**
Using the "colorType" validator with an optional attribute causes `cannot read property 'match' of undefined` errors.  Likely due to https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/types/color.js#L24

I don't want the color to have a default value, because there is not support for the 'inherit' color property here: https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/types/helpers/colors.js and I don't want them to have any of these matching colors or any hex color etc.

**To Reproduce**
1. Create a custom mjml component that uses the color validator on an attribute without a default value
2. Use this component in some MJML rendering code somewhere but don't give the color attribute a value
3. Render it to HTML in the normal way
4. Note the error

**Expected behavior**
There should be some way of allowing font color to be inherited while still allowing font colors to be specified and providing for validation.

**MJML environment (please complete the following information):**
Appears in latest source.   Found while using mjml 4.7.0

**Comment by iRyusa** [comment]
Yup you're right ! 
At least the fix isn't that hard, a small guard in the `getValue` function should do the trick here. Same for inherit we can safely add it to the color list and it will fix #1955 too 😄

**Comment by chadfurman** [comment]
PR open: https://github.com/mjmlio/mjml/pull/2317

Any chance we can get this back-ported as 4.7.2?

**Comment by iRyusa** [comment]
We don't update older version of MJML 4.X is the main release channel, thanks for this PR 👍

**Comment by iRyusa** [comment]
Now live in 4.10.2 thanks !
