### ISSUE TITLE
mj-column default padding can not be removed

### ISSUE THREAD

**Issue by denisaconstantinescu** [mjmlio/mjml#2320]
Hello there,

I am trying to remove the padding from button (I want the phone image to be sticked to the buttom), but as much combinations of the padding I try- I still have a padding on the buttom because of mj-column.

This is my mjml:

`<mjml>
  <mj-body width="500px">
    
    
    <mj-section padding="0" background-color="linear-gradient(90deg, #07080A 0%, #303239 49.48%, #0B0C0E 100%)" css-class="banner-container">
      <mj-column>
        <mj-table padding-top="25px">
          <tr align="right">
            <td width="250px" color="#FFFFFF" font-size="17px" font-weight="normal" font-family="normal" line-height="20px" align="center" letter-spacing="0.19px">
              <img src="https://www.dpd.co.uk/images/Group1.png?v=1"  />
              <p class="experience-the-app"> Experience the app today!</p>
              <p> <a href="{{bannerLink}}" class="link-style">GET THE APP ></a></p>
            </td>
            <td>
              <mj-all padding="0" />
              <img src="https://www.dpd.co.uk/images/app.png" width="130px" />
            </td>
          </tr>
        </mj-table>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
`
And I would like it to look like in the picture below:

<img width="388" alt="Screenshot 2021-07-01 at 20 02 16" src="https://user-images.githubusercontent.com/41586643/124162566-43fd4f00-daa7-11eb-8b94-f4f55d6c3ff1.png">

**Comment by iRyusa** [comment]
If you want to re move the bottom padding you have to reset mj-table padding and not only override `padding-top`.

Mj-column doesn't have any padding by default.
