### ISSUE TITLE
mj-include path

### ISSUE THREAD

**Issue by Cucak** [mjmlio/mjml#2321]
**Describe the bug**
Adding my-include path works in practice, but when I want to preview in extensions I cant see the included part 

**To Reproduce**
1. for example my path is <mj-include path="src/modules/templates/email/header.mjml>

**Expected behavior**
I expect to preview the whole view in Visual Studio code MJML extension

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Comment by iRyusa** [comment]
Try to add `./` before `src` and if it's only related to mjml extension please reopen with https://github.com/mjmlio/vscode-mjml and full details to reproduce (file structure or a demo repository)
