### ISSUE TITLE
MJML w/includes -> MJML, (inline the includes)

### ISSUE THREAD

**Issue by pachuka** [mjmlio/mjml#2322]
**Is your feature request related to a problem? Please describe.**
I'm working within a system where a 3rd party system is processing raw MJML files, so I need my `mj-include`'s to be inlined since that system would not have my local context, but not converted to HTML.

**Describe the solution you'd like**
Is there already a way to output a MJML string with the includes parsed?

**Describe alternatives you've considered**
There used to be this solution: https://stackoverflow.com/questions/52973121/render-multiple-mjml-files-into-one-mjml-file-string , but I don't think that's applicable today? Or at least I wasn't able to figure out how to reproduce that same behavior.

**Additional context**

**Comment by iRyusa** [comment]
Hi !

You can use the mjml parser as we use it in mjml-core here https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/index.js#L128-L135 and convert back the json to xml (we have a internal helper for that too https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/jsonToXML.js )

Don't forget to require the full `mjml` package first to load register every standard components
