### ISSUE TITLE
Responsive emails for different email-clients

### ISSUE THREAD

**Issue by MarkyGitHub** [mjmlio/mjml#2324]
**Description**
According to my understanding MJML provides a mechanism for designing and building emails. The emails are created with mjml's **wysiwyg** editor and then the html code is generated by mjml. The generated html code is responsive and is displayed evenly in different clients, such as Thunderbird, Outlook, IPhone, etc.

However, the template that I have generated and the HTML code resulting therefrom are not being displayed correctly in, for example Outlook 2019. Here the columns are displayed horizontally instead of vertically.

![image](https://user-images.githubusercontent.com/59173613/124583652-9649c180-de53-11eb-9c1e-ea180da5b945.png)

The email is displayed correctly in Thunderbird.

![image](https://user-images.githubusercontent.com/59173613/124583760-b7121700-de53-11eb-872d-4d1f282c5af2.png)

**To Reproduce**
1. Create an email template by using columns, e.g.

``<mj-column background-color="#DCDCDC" width="100%" padding="0px 40px 0px 40px" padding-top="40px" padding-bottom="40px">
  <mj-text font-family="Brandon Text" font-size="25px" text-transform="uppercase" padding="0px 0px 0px 0px" font-weight="bold" align="center"> Morgengold bringt's </mj-text>
  <mj-text font-family="Brandon Text" font-size="25px" align="center" text-transform="uppercase" padding="0px 0px 0px 0px" font-weight="bold"> Freu dich drauf </mj-text>
</mj-column>
<mj-column width="80%">
  <mj-text font-family="Arial" font-size="15px"> Falls Sie keine weiteren Produktinformationen mehr per E-Mail wünschen, teilen Sie dies bitte 
  Ihrem Morgengold Partner per E-Mail 
  an folgende Adresse mit: <a style="text-decoration: inherit; color: inherit" href="mailto:$MailFN$">$MailFN$.</a>
  </mj-text>
</mj-column>
<mj-column width="100%" vertical-align="middle">
  <mj-spacer height="32px" />
  <mj-social font-size="15px" icon-size="40px" mode="horizontal">
    <mj-social-element name="trustedshops" src="http://$Hostname$/assets/asset/nAZ1gr4IIds"  
    href="https://www.trustedshops.de/bewertung/info_XB23DF2C689CD1F51D7E00E279D369153.html">
    </mj-social-element>
    <mj-social-element name="facebook" src="http://$Hostname$/assets/asset/DW9DsuP3Js0" href="https://www.facebook.com/mein.morgengold/">
    </mj-social-element>
    <mj-social-element name="instagram" src="http://$Hostname$/assets/asset/_t7aanwcer0" href="https://www.instagram.com/mein.morgengold/">
    </mj-social-element>
  </mj-social>
  <mj-text font-family="Arial" font-size="15px" font-weight="bold" align="center" padding="0px 0px 0px 0px">
    <a target="_blank" style="text-decoration: inherit; color: inherit" href="https://www.morgengold.de/customer/login"> mein.morgengold </a>
  </mj-text>
</mj-column>``

2. Render it to HTML.
3. Send the HTML to an email address on Outllook 2019 and Thunderbird clients.
4. See rendered email in Outlook client.

**Expected behavior**
The email should be displayed in the same way in both Outlook 2019 and Thunderbird.

**MJML environment **
 - OS: Windows 10
 - MJML Version 4.8.1
 - MJML tool used: MJML App v3.0.3

**Email sending environment**:
 - The rendered HTML is used to generate an email and send via Java code to email address.

**Affected email clients (for rendering issues):**
 - Email Client: Outlook 2018, Thunderbird current version
 - OS: Windows 10

**Screenshots**
See above.

**Comment by iRyusa** [comment]
You need to split your columns into multiple sections. 
1 section = 100% of content. Here you have 280% of content inside a single section so outlook will display everything inline
