### ISSUE TITLE
Inline mobile and desktop conditional 

### ISSUE THREAD

**Issue by tabvn** [mjmlio/mjml#2329]
Dear Team,

can we have better inline condition  like

```
<mj-text font-size="{sm: "20px", "lg": "25px"}">Good job team!</mj-text>

```

or 

```
<mj-text sm-font-size="20px" lg-font-size="25px">Good job team!</mj-text>

```

Thanks team

**Comment by iRyusa** [comment]
Hi !

We don't want to do this as it would be expected to work on any tag, we prefer to let user declare their media query so they can have full control of responsivness instead of hiding it behind a non customizable attribute
