### ISSUE TITLE
Support for title property in images

### ISSUE THREAD

**Issue by NetoBraghetto** [mjmlio/mjml#233]
Is it possible to add title property in images?
Eg:
`<mj-image src="img/A.jpg" width="325" height="359" alt="A" title="A" padding="0"></mj-image>`

**Comment by jitendravyas** [comment]
I'm just curious, why you want to add title to the image?

**Comment by iRyusa** [comment]
Hello @NetoBraghetto ,

Can you provide some use case on it, and some render example ? thanks

**Comment by iRyusa** [comment]
Closing it, feel free to reopen with more details on it

**Comment by g0ddish** [comment]
Title adds a tooltip on images when you hover on them and sometimes are used in screen readers.

**Comment by iRyusa** [comment]
Re-openning !

**Comment by jitendravyas** [comment]
Images should have `alt` attribute for screen reader, not `title` I think. I'm sure if `title` is used by any screen reader.

**Comment by g0ddish** [comment]
Yes some screen readers use alt while others use title. [html4 spec](https://www.w3.org/TR/html4/struct/global.html#adef-title) actually references audio and non-visual useragents use it.

**Comment by iRyusa** [comment]
`title` is now supported on `2.3` !
