### ISSUE TITLE
MJML - href with special characters is not being rendered in the final HTML output

### ISSUE THREAD

**Issue by kvedantam** [mjmlio/mjml#2330]
**Describe the bug**
A href tag with special characters (inside a button or an image) is not getting rendered in the final HTML output.

**To Reproduce**
A href added inside an image or a button with special characters is not getting rendered in the final HTML output
If we remove special characters like **|%** it is working as expected.

Sample code:
"mjml
  mj-body
    mj-section
      mj-column
        mj-button href="https://www.google.com/?adc=sample&sample=Test1|Test2|Test3|Test4|Test5 (This is a sample text)||&parameters=%=sample%"
          Click me!
         /mj-button
      /mj-column
    /mj-section
  /mj-body
/mjml"

Removed the <> so that the code is visible properly

Rendere HTML without anchor tag and href:
![image](https://user-images.githubusercontent.com/83304302/126029449-2d96441a-508f-492b-9c8f-b0f9e5c3dc97.png)

Rendered HTML after removing the special characters **|%**:
![image](https://user-images.githubusercontent.com/83304302/126029649-ca94ef13-f268-4862-8b8d-b9a692538180.png)

The same code is working fine in https://mjml.io/try-it-live

**Additional context**
We are leveraging MJML in Adobe experience manager which is a CMS tool from Adobe. Internally the npm server converts the HMTL into MJML.

**Comment by iRyusa** [comment]
It looks to works just fine on the try it live, so I'm not sure this is related to MJML here. What version of MJML are you using on your server ?

**Comment by kvedantam** [comment]
Hi @iRyusa we are using 4.9.3 version of mjml. Can you pls help us with this as this is a blocker for our release?

Thanks,
Kiran Vedantam.

**Comment by iRyusa** [comment]
I would like to, but as the direct output of MJML doesn't alter your href here so there's no way to reproduce

**Comment by iRyusa** [comment]
Feel free to reopen with more details, it doesn't seem to be related to MJML but on your workflow instead
