### ISSUE TITLE
mj-preview does not allow html elements, failed to parse superscript in preheader

### ISSUE THREAD

**Issue by gowram** [mjmlio/mjml#2331]
**Describe the bug**
mj-preview does not allow us to use HTML code inside the context. 
**To Reproduce**
```xml
  <mj-preview>
      <div>this is pre header sd<sub>2</sub><div>
   </mj-preview>
```
JSON result as...
```json
{ "tagName": "mj-preview", "children": [ { "tagName": "div", "children": [ { "tagName": "sub", "content": "2", "attributes": {} } ], "content": "this is pre header sd", "attributes": {} } ], "attributes": {} }
```

**Expected behavior**
```json
{ "tagName": "mj-preview", "content": "<div>this is pre header sd<sub>2</sub><div>",  "attributes": {} }
```

**MJML environment (please complete the following information):**
 - OS: Ubuntu
 - MJML Version 4.8.1

**Comment by iRyusa** [comment]
It's really hard to help you without everything here. 

Can you give the whole document you're trying to parse ? Are you using the parser directly ? If so what options are you using ?

**Comment by gowram** [comment]
@iRyusa please find the below example.
I would like to have it parsed "mj-preview" content similar to "mj-text", whereas it's breaking into children array.


```xml
<mjml>
  <mj-head>
    <mj-preview>
      <div>
        this is pre header sd<sub>2</sub>
        <div>
    </mj-preview>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
I don't have any issue to parse this as a JSON. 

Can you reply to those question please ?

> Are you using the parser directly ? If so what options are you using ?

**Comment by gowram** [comment]
@iRyusa 
I am using conversion library for this, which [mjml2json@1.0.1](https://github.com/mjmlio/mjml2json)

**Comment by iRyusa** [comment]
This lib has not been updated for a while now you should just use the mjml parser instead

**Comment by gowram** [comment]
I need to parse from MJML to JSON, what API is available with MJML?

**Comment by gowram** [comment]
This is working fine, no issues.
