### ISSUE TITLE
2175 changes are missing in latest builds

### ISSUE THREAD

**Issue by kvedantam** [mjmlio/mjml#2333]
The changes of https://github.com/mjmlio/mjml/issues/2175 are missing in the latest builds. I do not see the code changes in the latest version JS file of mj-button. 

Last available version:
4.8.2

Missing from version:
4.10.0

Is this expected? How is the same functionality working live?

**Comment by iRyusa** [comment]
Seems like the tbody patch did remove title attribute on the component you're right feel free to open a pr 👍 we'll merge and deploy it back asap

**Comment by kvedantam** [comment]
I don't see the branch available for raising a PR. Can you please do it from your end? @iRyusa

**Comment by kvedantam** [comment]
@iRyusa can you let me know what's the status of this? Did you get time to raise a PR?

**Comment by iRyusa** [comment]
Nothing really moved here, I'm on holiday

**Comment by shivani15sharma** [comment]
Is there any update on adding title attribute to mj-button?

**Comment by shivani15sharma** [comment]
@iRyusa Is there any update on adding title attribute to mj-button?

**Comment by iRyusa** [comment]
Pr is open most likely come back this week

**Comment by iRyusa** [comment]
Should be good in 4.10.3
