### ISSUE TITLE
Feature Request — Allow Contribution to Social Icon Set

### ISSUE THREAD

**Issue by ethan-bc** [mjmlio/mjml#2338]
# Allow Contribution of Social Icons
I noticed a few icons were out of date and wanted to add updated versions to the code base, but alas, I cannot. It'd be great if we can contribute social icons so we don't have to make requests like this for each outdated one. 

https://github.com/mjmlio/mjml/blob/c5f74dd4bd49961132e557edd23c7ea4418f0241/packages/mjml-social/src/SocialElement.js#L4

![please sir](https://media.giphy.com/media/CHvcLFzd0OCdO/giphy.gif)

**Comment by iRyusa** [comment]
Well it would be better to deprecate those are they are just still here for retro-compatibility with MJML3 where custom social network was harder to add. Now that the syntax is really easier I guess it's better to use custom social network over those.

**Comment by ethan-bc** [comment]
@iRyusa ah okay, that makes sense. 🙂
