### ISSUE TITLE
Document how to add more components at runtime without the need to gulp-prebuild them

### ISSUE THREAD

**Issue by meglio** [mjmlio/mjml#2341]
Dear team,

I could not figure out the way to add components at runtime so that I don't have to start with a boilerplate and build the components.

I'd like to "declare" the mjml components in my Next.js application and use them straight away; however, the documentation only talks about build my custom components with gulp first.

Could you please clarify?

**Comment by iRyusa** [comment]
You should be able to register any component with MJML API already see https://github.com/mjmlio/mjml-component-boilerplate/blob/master/gulpfile.babel.js#L33 

I'm not sure if you need to transpile with babel as it use standard class. We might be able to completely remove babel from the project in MJML5 🤔

**Comment by meglio** [comment]
Thanks. I'm doing it in Next.js, which has babel. Do you happen to know if I need to configure Next.js' Babel in any specific way to make mjml components work?

**Comment by iRyusa** [comment]
Can close this for now I guess
