### ISSUE TITLE
How to prevent mjml from reading .mjmlconfig file in node.js

### ISSUE THREAD

**Issue by meglio** [mjmlio/mjml#2342]
Hi. I'd like to use `mjml` in such a way that it does absolutely no filesystem I/O.

However, I guess, at the very minimum, it will try to read the `.mjmlconfig` file. Is this true? If so, how can I disable this behaviour?

Another thing that is suspicious is the default value of `mjmlConfigPath`, which defaults to `process.cwd()` (which is, again, an attempt to get the filesystem state).

An addition to my question would be, can I use the `mjml2html()` function in browser, or does it have server-only dependencies?

Please advise. -- Many thanks, Anton

**Comment by meglio** [comment]
So, when running with `yarn` in `zero-installs` mode, mjml also tries to write something to a file, but it fails because of the yarn's virtual file system.

How do I stop mjml from trying to read/write to the filesystem altogether?

**Comment by iRyusa** [comment]
There's a mjml-browser package that mock all `fs` access to enable using it with browser. 

Maybe later we'll find some way to turn off completely mjmlconfig/mj-include so it doesn't require node `fs` but for now we don't have enough resource to work on this. 

>  mjml also tries to write something to a file,

About this I don't know what it could be, if you should open a new issue with the stacktrace to see if we can do something about  it.
