### ISSUE TITLE
Images being cutted in Outlook

### ISSUE THREAD

**Issue by vladox** [mjmlio/mjml#2347]
**Describe the bug**
When using the tag `mj-image` inside a `mj-column` tag the result image is only showing "cropped" (top part invisible). 
Changing the style `line-height` to the value of 1 apparently solves the issue but it's not possible to be set neither in the  `mj-column` tag nor in the `mj-section` tag.

**To Reproduce**
1. Create a file with this MJML code: 

```
 <mj-section padding-top="0">
    	<mj-column>
        <mj-raw>
          {% with apple_url=order.get_apple_url google_url=google_pay_url apple_button_image="webshop/buttons/apple_wallet.png" google_button_image="webshop/buttons/google_pay.png" %}
        </mj-raw>
          <mj-image width="270px" href="{{ apple_url }}" src="{% get_base_url %}{% static apple_button_image %}" alt="apple wallet" />
          <mj-image width="278px" href="{{ google_url }}" src="{% get_base_url %}{% static google_button_image %}" alt="google pay" />
        <mj-raw>
          {% endwith %}
        </mj-raw>
      </mj-column>
    </mj-section>
```

2. Render it to HTML by doing 'mjml --config.beautify false -l skip "templates/templated_email/source/*.mjml" -o templates/templated_email/compiled'
3. Send the HTML to an email address with 'Django EMAIL SEND'

**Expected behavior**
Images showing in full 

**MJML environment (please complete the following information):**
 - OS: Linux
 - MJML Version: 4.10.1
 - MJML tool used: Node.JS

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Mailgun

**Affected email clients (for rendering issues):**
 - Email Client: Outlook
 - OS: Windows
 - Browser: None

**Screenshots**

![image](https://user-images.githubusercontent.com/2648461/130767491-260ab05b-732c-4f57-9c30-827a0cb19f5c.png)

**Additional context**

**Comment by vladox** [comment]
This is the generated HTML code:

```
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse: collapse; border-spacing: 0px; font-size: 14px; line-height: 20px;">
        <tbody style="font-size: 14px; line-height: 20px;">
          <tr style="font-size: 14px; line-height: 20px;">
            <td style="padding: 5px; width: 270px; font-size: 14px; line-height: 20px;" width="270">
              
        <a href="{{ apple_url }}" target="_blank" style="font-size: 14px; line-height: 20px;">
          
      <img alt="apple wallet" height="auto" src="{% get_base_url %}{% static apple_button_image %}" style="border: 0; display: block; outline: none; text-decoration: none; height: auto; width: 100%; font-size: 14px; line-height: 20px;" width="270">
    
        </a>
      
            </td>
          </tr>
        </tbody>
      </table>
``` 

For some reason the `line-height` is set to 20px

**Comment by iRyusa** [comment]
You have an inline style in your mjml that does add it as you can’t see any line height applied here https://mjml.io/try-it-live/1rlMCUpbTNW

**Comment by vladox** [comment]
@iRyusa You were completely right, I did oversee that css rule, thanks!
