### ISSUE TITLE
Changing paddings of mj-column in mobile view

### ISSUE THREAD

**Issue by shivakantshukla55** [mjmlio/mjml#2348]
Thanks a lot for the amazing framework. This has made making html email so much easier.

- Problems I am facing:
I have made a desktop first email template in which i have used many mj-columns which is working perfectly fine in desktop view and as expected every column is taking full width in mobile view but the problem is i have given different padding to mj-column in desktop view and now it is difficult to change the padding of mj-column in mobile view using media queries.

What will be the right way to handle it?

I am still discovering mjml. please correct me if I am wrong somewhere.
Thankyou.

**Comment by GarryFlemings** [comment]
Wrong? Not the right word. Understandable.

About media queries: They're not supported well on many email clients.
https://www.caniemail.com/search/?s=%40media

In contrast, though don't have a link to prove it, we're told clients on desktop platforms support media queries better (not perfectly or always, but better).

So, the MJML team recommends coding mobile first.

For you, that'll mean writing the original code with paddings for mobile. Then, use media queries to change them for desktop.

**Comment by shivakantshukla55** [comment]
Thankyou for your response @GarryFlemings 
But my usecase is desktop first. I am working in editor kind of thing.
what will be the right way to achieve this from desktop to mobile?
once again Thank you.

**Comment by GarryFlemings** [comment]
This could go back and forth for a while. If you don't mind, could we take this discussion to Slack? The MJML Slack is https://mjml.slack.com/. If you're not signed up yet and have problems, try https://join.slack.com/t/mjml/shared_invite/zt-gqmwfwmr-kPBnfuuB7wof5httaTcXxg.

Either way, let's take the discussion to code, please. Can you send us a short snippet that demonstrates what you've tried and how it's proving difficult? The best way would be with https://mjml.io/try-it-live; once you paste code there, the URL will change and you can tell us that URL.

Seeing code might be necessary for us to be certain we answer the right question. Like you, I suspect media queries will be part of the solution. I have not tried this particular change with them; it might be ugly. Slack is better for this question; maybe someone there will have a creative solution!

As to your use case: If an overwhelming number of your users have desktop clients that don't support media queries, writing desktop first could well be your best answer; that must be your call. If you make that choice, the data I mentioned above indicates you might only be able to reach a small portion of mobile users (depending on the mix of mobile email clients in use 😀).

Many moving parts. Let's work through this a step at a time!

**Comment by shivakantshukla55** [comment]
Yes Sure. It will be very helpful for the long run.
Thanks @GarryFlemings
