### ISSUE TITLE
TypeError: _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by sbimochan** [mjmlio/mjml#2353]
Fresh clean installation
npm install mjml

Try out:
mjml --watch index.mjml index.html

Throws:
TypeError: _interopRequireDefault is not a function

**Comment by iRyusa** [comment]
What version of Node are you using ?

**Comment by sbimochan** [comment]
v14.15.1

**Comment by iRyusa** [comment]
Seems like NPM doesn't satisfies babel runtime properly as we've seen in #2299 
The release this week should fix this. Try to fix babel runtime to `7.14.6` on your package json for now it should work

**Comment by iRyusa** [comment]
Should be good now in 4.10.3 as everything has been bump. Can you confirm this ?
