### ISSUE TITLE
html generated for mj-image title attribute applies to only img tag and not to the anchor tag

### ISSUE THREAD

**Issue by shivani15sharma** [mjmlio/mjml#2354]
When using title attribute on mj-image, it gets applied only to the `<img>` tag and not to the `<a>` tag

We have an issue for T-online-de, while using **src** or **msrc** as a query param in the url image is not visible. We need to have a **title** attribute for the anchor tag to resolve that issue. However when we apply title attribute to mj-image generated html shows title attribute being applied to `<img>` tag only and not to the `<a>` tag which holds the href(i.e the url).

**To Reproduce**
1. Create a file with this MJML code: 

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image href="https://test.com/tracking?msrc=123" title= "test" width="300px" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
2. Generated html for mj-image is:
```
<tr>
  <td style="width:300px;">
    <a href="https://test.com/tracking?msrc=123" target="_blank">
      <img height="auto" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" title="test" width="300" />
    </a>
  </td>
</tr>
```

EOA link - when title is there for `img` tag only: https://app.emailonacid.com/app/acidtest/hQriROd1lbtSWCNZrbsQxM4iC4yGRcoTfoCgGkVekK8lh/list
It can be seen that image is missing for both Chrome & Firefox for T-online-de

but to resolve our issue we would need html to have title attribute applied to both `<img> & <a>` tag like below:
```
<tr>
  <td style="width:300px;">
    <a href="https://test.com/tracking?msrc=123" title="test" target="_blank">
      <img height="auto" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px;" title="test" width="300" />
    </a>
  </td>
</tr>
```

EOA link - when title is there for` img & a` tag both: https://app.emailonacid.com/app/acidtest/NrdxM0L8E10tntfzEpwsXvC7BfJUGFgf4xoOOuhiv5JPu/list
 
 It works when title attribute is present at both `<a>` and `<img>` tags

**Email sending environment(for rendering issues)**:
 - Platform used to check the email EmailOnAcid

**Affected email clients (for rendering issues):**
 -T-Online-de

Is it possible we can get title attribute for `<a>` tag for mj-image.

**Comment by iRyusa** [comment]
That's really a weird bug, I don't think this would cause any issue, feel free to open a PR for that 👍

**Comment by shivani15sharma** [comment]
@iRyusa Will you be able to merge the PR for this fix?

**Comment by shivani15sharma** [comment]
@iRyusa Can we have a new release for these fixes. Latest release doesn’t include these fixes.
