### ISSUE TITLE
Missing background-color attribute on mj-body

### ISSUE THREAD

**Issue by kila03** [mjmlio/mjml#236]
After updating from v1 to v2 it is no longer possible to put background color to mj-body - putting background-color only on mj-container only colors background equal to the height of the content instead of the full height of the window. Can we get this option back to mj-body?

**Comment by iRyusa** [comment]
Hello @kila03,

This is a bug related on the post-render of `mj-container` it will be fixed in the next release. Note that `mj-body` is just a root of a MJML document and no longer support attributes, that's why it's on `mj-container` now

**Comment by kila03** [comment]
Any idea when it will be released @iRyusa?

**Comment by iRyusa** [comment]
Hello, this is released on 2.1.X branch !
