### ISSUE TITLE
HTML minification not working

### ISSUE THREAD

**Issue by kailasnadh790** [mjmlio/mjml#2360]
Even with minify: true , the HTML output is not getting minified and is causing issue on gmail.
![image](https://user-images.githubusercontent.com/53608019/133277278-4dbc3313-747e-4d85-9dad-e513ac77c6ab.png)

**Comment by iRyusa** [comment]
I'm not really able to reproduce here can you provide more info ?

**Comment by iRyusa** [comment]
I'm closing for now because I can't reproduce.  Feel free to reopen with a repo to reproduce so we can investigate
