### ISSUE TITLE
The mj-accordion body components is displayed always expanded when sent by mandrillapp and received in gmail, fastmail, ...

### ISSUE THREAD

**Issue by adussel** [mjmlio/mjml#2368]
I tried to use an email with the mj-accordion body components.
I copied pasted the code provided in https://documentation.mjml.io/#mj-accordion and tried to send the html version of the email provided through https://mjml.io/try-it-live to a @gmail.com or @fastmail.com account, using the mandrillapp tool of mailchimp and the result is an always expanded version of the accordion

![image](https://user-images.githubusercontent.com/873031/134532267-77f092eb-b192-47f0-a976-04fc4e932ca6.png)

**Comment by iRyusa** [comment]
Gmail doesn't support click interaction so it expend the accordion by default.
