### ISSUE TITLE
add more class or id names to HTML

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2369]
**Is your feature request related to a problem? Please describe.**
Using a `class=xxx` statement only to create a start point for selecting HTML elements creates avoidable distractions in MJML code.

**Describe the solution you'd like**
Include additional id or class names in the HTML code.

**Describe alternatives you've considered**

1) The documentation says styling gets applied to the top-level element. Maybe, label those.
1) Maybe, include `mj-class` names in HTML as class names.

  - Some might argue these labels in turn add avoidable distractions to the HTML. These additions to the HTML have more value than distraction because they 1) have a valuable use case and 2) help identify parts of the HTML.

**Benefits**

1) These labels will make it easier for email authors to select HTML elements they want to style.
1) These labels could help email authors develop proficiency in identifying parent MJML of the HTML code.

**Comment by iRyusa** [comment]
Email have some constraints in HTML size, if we start to add classes everywhere it will increase to output size dramatically.
`mj-class` are meant to be used only for mj-attribute so there's no point to have this as css-class as it will confuse users and make `css-class` pointless.
