### ISSUE TITLE
build part of edm

### ISSUE THREAD

**Issue by Samaritan89** [mjmlio/mjml#237]
mjml is greate to build a full edm, in some case I need to generator just part of edm code, can we do that?

For example, just build the snippet

    <mj-text>Test</mj-text>

**Comment by ngarnier** [comment]
Hey @Samaritan89, 

I'm not sure to understand what you need. Can you please provide more details of what you want to do and what you expect from MJML in this specific scenario?

Cheers!

**Comment by Samaritan89** [comment]
We have a CMS to generate page by dragging  components in to a layout . Every component is some HTML code like 

    <button >{{text}}</button>

or

    <nav>
       ...
    </nav>

Even if you don't know HTML, you can design a page with our components

Here is my problem, I hope people can design EDM with my CMS, so I need to develop some EDM components, I don't need every component build into a whole EDM with head body, just need part of the code, I'll package all components into HTML in CMS

**Comment by ngarnier** [comment]
Thanks for detailing your need. 

For now, mjml renders the container with the html tag, head, body & etc but it could be tweaked to fit your need and render only the html of component you're interested in. 

We'll see how we could implement that. Until then, feel free to submit a pull request!

**Comment by iRyusa** [comment]
@Samaritan89 I understand what you want to do, but some component have `style` in head in order to work, how will you handle it?

With `2.3` you'll be able to generate valid html with this: 

```xml
<mjml>
  <mj-body>
    <mj-text>Hello text !</mj-text> 
  </mj-body>
</mjml>
```

But it will generate a full HTML document. You can still use jQuery or Cheerio to get only `body` content ?

**Comment by iRyusa** [comment]
I'm closing this one, feel free to comment to re-open
