### ISSUE TITLE
Is it possible to generate context for renderChildren's renderer

### ISSUE THREAD

**Issue by vidhu** [mjmlio/mjml#2371]
Using the mjml apis, you can wrap your children with a custom renderer
```js
this.renderChildren(children, {
  renderer: component => `<something>${component.render()}</something>`;
});
```

However, I have a use case where I want to do something specific for every child. 

Is there way to create a context for each child which can be accessed in the renderer. Something like this

```js
const children = children.map((child) => ({
  ...child,
  contextForRenderer: { ... }
}));

this.renderChildren(children, {
  renderer: component => `something with ${component.contextForRenderer}`
});
```

Does something like this already exist? I've gone through the source and don't really see anything like this so fully expecting this to be a feature request, in which case, happy to open a PR

The only thing I can think of is to pass context via the `child.attributes` object but that seems hacky because the context values aren't really used in the child

**Comment by iRyusa** [comment]
You can also define it simply in your renderer too :

this.renderChildren(children, {
  renderer: component => {
    const contextForRenderer = generateContextForChildren(component)
    // do something with your context ?

    return component.render()
  }
});

**Comment by iRyusa** [comment]
There no validation in the transpiling process, so it's good to go !
