### ISSUE TITLE
Handle malformed mjml templates with better error

### ISSUE THREAD

**Issue by MarkMurphy** [mjmlio/mjml#2373]
**Describe the bug**
Handle malformed mjml templates (maybe with same error you used to?)

**To Reproduce**
1. Create a file with this MJML code: `malformed`
2. Try to render it
3. See error

**Expected behavior**
The mjml library used to throw a malformed mjml error but now will choke on this internally which results in a different much less helpful error:
```
Cannot read property 'replace' of undefined

          at _default (node_modules/mjml-core/lib/helpers/minifyOutlookConditionnals.js:9:9)
          at Object.mjml2html [as default] (node_modules/mjml-core/lib/index.js:400:53)
```

The library used to handle this scenario at least in 4.6.3, the latest versions not so much.

**Comment by Sigkar** [comment]
Also ran into this error, was confused until I saw this issue. I started to look into it but got pulled away.

Looks like the test only covers a passing `minifyOutlookConditionnals` case, was going to make one that failed but I wasn't able to reproduce this `Cannot read property 'replace' of undefined` without digging deeper with some limited time.

Probably could be something as simple as 'Your MJML may be malformed' as a custom `console.error`? No idea, i just got here - just throwing out ideas

**Comment by kmcb777** [comment]
Hi @Sigkar are you using the latest version ?
Did you use mjml with the cli or as a node module ?
I just tried both ways on latest (4.11.0) and i get this error message : `Error: Parsing failed. Check your mjml.`
Maybe you have an older version of mjml installed globally ? When mjml requires mjm-core it may take an other available version

**Comment by iRyusa** [comment]
This should be good in 4.12 now 👍
