### ISSUE TITLE
support for "mjml -V"

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#2375]
**Describe the bug**

At the command line, **mjml --help** includes

`  -V, --version   Show version number                                  [boolean]`

Side issue: Is "boolean" accurate?

In contrast both **mjml -V** and **mjml --version** report (from the command line)

````
mjml-core: 4.10.1
mjml-cli: 4.10.1
````

Additionally, the **package.json** files for both the above components include

`"version": "4.10.1",`

Maybe this behavior results from change in the build process?

Maybe support for "-V" is deprecated? I do not find mention of it at
https://github.com/mjmlio/mjml/releases

Maybe the deprecation occurred in version 4.10.4? That version currently has no write-up at the above.

**To Reproduce**

Use the command line.
Read the "version" field of the two **package.json** files.
Read release notes at https://github.com/mjmlio/mjml/releases

**Expected behavior**

I hope to find the MJML version, either with **mjml -V** or a substitute.

**MJML environment (please complete the following information):**
 - OS: Win10, up-to-date
 - MJML Version: most recent 2021-10-17 (**git fetch mjml** on the command line, remote "mjml" pointing to the GitHub MJML repository). Probably version 10.4 (the highest-numbered version tag in the repository).
 - MJML tool used: node.js

**Additional context**

"-V" was helpful, AFAIK, through version 4.10.1.

As I remember it for version 4.10.3, the **mjml-core** > **package.json** > "version" field was "4.10.3"; for **mjml-cli**, the parallel field was "4.10.1".

**Comment by iRyusa** [comment]
It works fine on a fresh install :
``` 
yarn run v1.22.4
warning ../package.json: No license field
$ /Users/maximebrazeilles/Workspace/xxx/node_modules/.bin/mjml -V
mjml-core: 4.10.4
mjml-cli: 4.10.4
✨  Done in 0.84s.
```
You didn't probably bump the version in your package json or version is locked on your side.

We use a lib to handle cli documentation and argument without options shows up as `boolean`.
