### ISSUE TITLE
Inconsistent Margins on different iPhones

### ISSUE THREAD

**Issue by viking2917** [mjmlio/mjml#2380]
**Describe the bug**
The same MJML produces an email with visible margins on iPhone 13 Pro Max, whereas on iPhoneX no margin is present. 

**To Reproduce**
See mjml code below. When converted to minimized HTML and sent, and then viewed in the iPhone email client, inconsistent margins are obtained. 

See attached images, iPhoneProMax13Margin.jpg shows left and right margins in the email. iPhoneXNoMargin.jpg shows that on an iPhoneX, there is no side margin whatsoever. (For what it's worth, all my Android devices behave the same as the ProMax client, as does Gmail on my iPhone - that is, they all have margins). 

**Expected behavior**
I am a little unclear about the expected behavior to be honest. I *did* ask for no padding (` <mj-class name="embody" padding-left="0px" padding-right="0px" />` etc), but on every (mobile) email client I have access to except iPhone X, the client itself provides a margin around the emails. 

Either way would be fine (extra margins added, or not), so long as it was consistent. 

The objective is, I'm trying to remove all extraneous padding - if I do not set the padding=0, then on most email clients I get double margins, one (apparently) added by the email client, and one added by mjml. 

**MJML environment (please complete the following information):**
 - OS: [web try-it-live for conversion to HTML]
 - MJML Version [4.9.3]
 - MJML tool used [web try-it-live]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [email sent by Mailgun API]  

**Affected email clients (for rendering issues):**
 - Email Client [ios Mail client, on iPhone X] 

**Screenshots**
see Attached
![iPhoneXNoMargin](https://user-images.githubusercontent.com/7691349/139284351-868aae39-da25-4254-9de7-9a0edc004a02.jpg)
![iPhone13ProMaxMargin](https://user-images.githubusercontent.com/7691349/139284356-1a0406ca-6110-4d58-9bd6-ea556974a8ca.jpg)

**Additional context**

full MJML code below:

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all line-height="18px" />
      <mj-text font-family="Georgia"></mj-text>
      <mj-text font-size="15px"></mj-text>
      <mj-text line-height="1.4"></mj-text>
      <mj-font name="Quando" href="https://fonts.googleapis.com/css?family=Quando" />
      <mj-class name="embody" padding-left="0px" padding-right="0px" />
      <mj-class name="footerbody" padding-left="10px" padding-right="10px" />
      <mj-class name="imgHeader" padding-left="0" adding-right="0" height="300px" border-radius="10px 10px 10px 10px" />
    </mj-attributes>

  </mj-head>

  <mj-body>

    <mj-section padding-bottom="0px" padding-left="0px" padding-right="0px">
      <mj-column>
        <mj-image width="100px" src="https://images.thehawaiiproject.com/bookshiplogo.png"></mj-image>
      </mj-column>
    </mj-section>

    <mj-section padding-bottom="0px" padding-left="0px" padding-right="0px">
      <mj-column>
        <mj-text mj-class="embody" padding-top="0px" padding-bottom="0px">
          Hi %recipient.FNAME%,
        </mj-text>

        <mj-text mj-class="embody" padding-top="0px">
          %recipient.EMAILTEXT%
        </mj-text>

      </mj-column>
    </mj-section>

    <mj-section background-color="#363636">
      <mj-column>
        <mj-text mj-class="footerbody">
          <span class="footer-text" style="color: #d8d8d8"><a style="color:white;" href="http://www.bookshipapp.com">Bookship</a> is a production of <a style="color:white;" href="https://www.thehawaiiproject.com/faq">The Hawaii Project</a>.
            We believe Books Change Lives, so we donate 10% of our revenue to great literacy non-profits like
            <a class="footer-link" style="color: #d8d8d8" href="https://www.nabu.org/">Nabu.org</a>,
            <a class="footer-link" style="color: #d8d8d8" href="https://www.hawaiiliteracy.org/">Hawaii Literacy</a>, and others. Subscribe to Bookship Premium and help support literacy! 
            <a class="footer-link" style="color: #d8d8d8" href="https://links.bookshipapp.com/premium">Learn More</a>.

          </span>
        </mj-text>

        <mj-text mj-class="footerbody">
          <span class="footer-text" style="color: #d8d8d8">You are receiving this email because you use, or were invited to, the Bookship app. You can turn off emails in the Accounts page in the app if desired.</span><br />
        </mj-text>

        <!-- social media -->
        <mj-text mj-class="footerbody">
          <span class="footer-text" style="color: #d8d8d8">Email: </span><a href="mailto:info@thehawaiiproject.com" style="text-decoration: none;color: #848484;font-weight: normal;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">xxxxxxxxxxx</a>
          <br />
          <span class="footer-text" style="color: #d8d8d8">xxx<br />
            <em>Copyright © 2021 xxxxxxxxxxx, All rights reserved.</em>
          </span>
        </mj-text>

      </mj-column>
    </mj-section>


  </mj-body>
</mjml>
```

**Comment by viking2917** [comment]
I have verified that this happens on a friend's iPhone 11 as well, so it's not specific to my iPhone X. 

Any ideas what might be causing this? Or a way around it?

**Comment by iRyusa** [comment]
Really weird i'm trying in xcode simulator too and can't reproduce this behavior 🤔 
Can you try to remove manually the margin:0/padding:0 on body in head style to see if it changes anything ?

**Comment by viking2917** [comment]
OK, so I think the problem is not with MJML. (I did try removing the padding above and it does not make a difference), and I see the same issue with the MJML sample data mentioned above as well.).

However, I think the problem is related to my use of Mailgun API to send the emails. When I send the HTML as a simple cut-and-paste into gmail, and send that way, the resulting email, when viewed in the iOS email client, looks fine. So something about my use of Mailgun appears to be the problem. 

I'm going to investigate that further, and if I learning anything of general use, will post back. But in the meantime, I'm going to close this. Thank you @iRyusa for your help, and sorry I didn't figure this out before posting the issue!
