### ISSUE TITLE
Class selector not working on href

### ISSUE THREAD

**Issue by llezhava** [mjmlio/mjml#2381]
Hello!
Thanks for the great library.

I can't style href links with classes, while styles attribute is working.
When I see compiled output, it is not inlining classes on href. 
It is not only about link, if sub-element is targeted with class, it is not inlined as well.

I made links working with advanced selector though

**To Reproduce**
See demo:
https://mjml.io/try-it-live/4klHgAHW6fm

**Expected behavior**
Inline styles must be applied to href also.

**Comment by llezhava** [comment]
If I target href now with class, but with advanced css selector, it is working, examples are linked above.

**Comment by iRyusa** [comment]
Change css class to class on html element (<a>) and it will work

**Comment by llezhava** [comment]
Great, that's probably so because that everything under mj-text is treated as HTML and not compiled by MJML.

https://mjml.io/try-it-live/YVpm5mjkb-h

Thanks!
