### ISSUE TITLE
Can't override default attributes with css-class or mj-class

### ISSUE THREAD

**Issue by AveryTheDev** [mjmlio/mjml#2382]
I can't override a default value with a css-class or mj-class but I can by adding the attributes directly to the mjml tag which doesn't work for me with my use case. I need to use css-class because I want the styles to change according to the width of the screen.

What I want to do specifically is add a border to an overall column, but remove the top or bottom border if a certain width is reached.

You can replicate with this code and the [editor](https://mjml.io/try-it-live/I6H59hAJ6eM).

```mjml
<mjml>
  <mj-head>
    <mj-title> Responsive table </mj-title>
    <mj-attributes>
      <mj-class name="data-table" width="50%" />
      <mj-style inline="inline">
        .data-table { width: 50%; border-radius: 24px; border: "1px
        solid #000"}
      </mj-style>  
      <mj-style inline="inline">
        @media (max-width: 450px) {
        .data-table:first-child { border-bottom: none; }
        .data-table:nth-child(2) { border-top: none; } }
      </mj-style>
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column css-class="data-table">
        <mj-text>Key</mj-text>
      </mj-column>
      <mj-column css-class="data-table">
        <mj-text>Value</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Classes of either kind should be able to override the default styling

**Comment by iRyusa** [comment]
It's not really clear for me what you want to do here.

But both your `mj-style` are in mj-attribute so it won't be applied.

Not sure about that synthax : `border: "1px solid #000"` probably want `border: 1px solid #000;` ?
And you can't inline media query so you should remove that inline attribute on the 2nd mj-style.

**Comment by AveryTheDev** [comment]
Aside from the removal of `inline: "inline"` is there anything else I can do to ensure that the media query is applied properly? This isn't removing the borders like I'd hoped

```mjml

 <mj-style >
        @media (max-width: 450px) {
        .data-table:first-child { border-bottom: none; }
        .data-table:nth-child(2) { border-top: none; } }
</mj-style>
```

**Comment by AveryTheDev** [comment]
Interesting, so `!important` should be added to any media query ask? That worked btw, much appreciated

**Comment by iRyusa** [comment]
You should avoid !important as much as possible. But when you don't have really the choice to then you can use it. This should be explained here https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
