### ISSUE TITLE
White top and bottom margins when viewed on dark background

### ISSUE THREAD

**Issue by bbannas** [mjmlio/mjml#2383]
Hello, I hope I'm not missing anything super simple, but for some reason when I view my email on my phone, I have white margins on the top and bottom of it, which are not visible when opening the HTML file in my browser (the top of the rainbow image is directly touching the top of my browser, same with the bottom). 

Here are some screenshots of the issue: https://puu.sh/ImDGx/de6a5e8a00.jpg , https://puu.sh/ImDGJ/7eb0b3860d.jpg

**Email sending environment(for rendering issues)**:
 - gmail.com

**Here is my MJML code:**
[TWOEYES_email_MJML.zip](https://github.com/mjmlio/mjml/files/7464716/TWOEYES_email_MJML.zip)

**Here is my HTML code:**
[TWOEYES_email_HTMLfull.zip](https://github.com/mjmlio/mjml/files/7464726/TWOEYES_email_HTMLfull.zip)

I read somewhere that minifying the html can help with this issue, but unfortunately it didnt work
**Here is my HTML code minified:**
[TWOEYES_email_HTMLmini_3.zip](https://github.com/mjmlio/mjml/files/7464727/TWOEYES_email_HTMLmini_3.zip)

I tried setting all padding on the top and bottom images/sections to 0px but that didnt help either...

Anyone know what the issue could be?

Id really appreciate some advice, **thank you!**

**Comment by iRyusa** [comment]
Can you try to send with https://putsmail.com/ instead ? I can't reproduce the issue.

**Comment by bbannas** [comment]
Ah shit, so it was just a dumb mistake. 

I read online that the "right way to send HTML emails" is to just open the HTML file in your browser, hit ctrl+A and then just copy and paste into the email body, which seemed weird to me, but I went along with it. 

This apparently doesn't work.

Through litmus the email I received looks perfect.

In that case, can you recommend a way for my client to send MJML (html) emails out, ideally some open source free option, or a way to paste the html in a functional way into gmail? I tried searching for a solution, thought it would be part of the MJML guide but I couldn't find it there.

**Comment by iRyusa** [comment]
Putsmail should work for you I know that https://useparcel.com/ have a send test feature too
