### ISSUE TITLE
border radius on column doesn't work

### ISSUE THREAD

**Issue by mhamri** [mjmlio/mjml#2387]
**Describe the bug**
given code below

```
<mjml>
  <mj-body background-color="#ffffff">
    <mj-section>
      <mj-column border-radius="30px" border="2px solid black" padding-top="20px">
        <mj-text align="center" font-size="18px"> Training Dates </mj-text>
        <mj-text padding="20px"> First line of text </mj-text>
        <mj-divider border-width="1px" border-style="dashed" border-color="lightgrey" padding="0 20px" />
        <mj-text padding="20px"> Second line of text </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

https://mjml.io/try-it-live/4Vg9dIUtUXw

**Expected behavior**
I expect to see some rounded corner
![image](https://user-images.githubusercontent.com/8991783/141795060-168bc32a-f507-4356-8a1c-82afb5490c71.png).

**Comment by iRyusa** [comment]
We enforce border-collapse to `collapse` to ensure there's no whiteline in outlook. If you want you can inline a `border-collapse:separate` on some table to make border-radius work ex: https://mjml.io/try-it-live/1lr_M9syddA .
