### ISSUE TITLE
As section or group can not be nested in column, is there any way to realize this effect?

### ISSUE THREAD

**Issue by xlnhaha** [mjmlio/mjml#2389]
Hi, I'd like to make a template like this structure (in red box), but as the document say, the section or group can not be nested in a column, would you please give any suggestion? Thank you very much
![image](https://user-images.githubusercontent.com/34709921/142589453-9df0ed0c-f683-4258-aa1f-33b80295fc58.png)

**Comment by kmcb777** [comment]
Hi, it's indeed impossible to nest a section in a column, instead you'll need to use a mj-table for the "bbb"/"ccc" line.
However you can't use a mjml component in a mj-table, only html.

**Comment by xlnhaha** [comment]
@kmcb777 Thank you for your brilliant suggestion
