### ISSUE TITLE
`mj-font` not working with the JSON format of the MJML

### ISSUE THREAD

**Issue by AGachet** [mjmlio/mjml#2390]
**Describe the bug**
`mj-font` not working when MJML is used on **JSON format with** `mjml2html`

**To Reproduce**
1. Create a file with this MJML code: 
```json
{
    "tagName": "mjml",
    "attributes": {},
    "children": [
        {
            "tagName": "mj-body",
            "attributes": {
                "width": "640px",
                "background-color": "#FFFFFF"
            },
            "children": [
                {
                    "tagName": "mj-section",
                    "attributes": {},
                    "children": [
                        {
                            "tagName": "mj-column",
                            "attributes": {},
                            "children": [
                                {
                                    "tagName": "mj-text",
                                    "attributes": {
                                        "font-family": "Raleway Dots, Arial",
                                        "font-size": "50px",
                                        "align": "center"
                                    },
                                    "children": [],
                                    "content": "Lorem ipsum dolor"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "tagName": "mj-head",
            "attributes": {},
            "children": [
                {
                    "name": "Raleway Dots",
                    "tagName": "mj-font",
                    "href": "https://fonts.googleapis.com/css2?family=Raleway+Dots"
                }
            ]
        }
    ]
}
```
2. Render it to HTML by using  `mjml2html` function as mentioned in the documentation
3. See the render without any imported font

It looks like the optimization made to check if the font is used in the template (which is a condition to generate the import following [this ticket](https://github.com/mjmlio/mjml/issues/703)) doesn't work correctly when the base template is in JSON format.

4. Create file with the same code with the markup format

```html
<mjml>
  <mj-body width="640px" background-color="#FFF">
    <mj-section>
      <mj-column>
        <mj-text font-family="Raleway Dots, Arial" font-size="50px" align="center">
          Lorem ipsum dolor
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
  <mj-head>
    <mj-font name="Raleway Dots" href="https://fonts.googleapis.com/css2?family=Raleway+Dots" />
  </mj-head>
</mjml>
```

5. Render it to HTML by using  `mjml2html` function as mentioned in the documentation
6. [See the render](https://mjml.io/try-it-live/Q4NOXhTdfTO) which is working properly!

**Expected behavior**
The font should be detected as used in the JSON, so MJML should generate this part of the code in the final render

```html
  <!--[if !mso]><!-->
  <link href="https://fonts.googleapis.com/css2?family=Raleway+Dots" rel="stylesheet" type="text/css">
  <style type="text/css">
    @import url(https://fonts.googleapis.com/css2?family=Raleway+Dots);
  </style>
  <!--<![endif]-->
```

**MJML environment (please complete the following information):**
 - OS: MacOS, Linux, Windows
 - MJML Version:  4.9.6, 4.9.3 and 4.10.3 and it doesn't work on any of these versions
 - MJML tool used: [MJML API](https://mjml.io/try-it-live/Q4NOXhTdfTO) and Private MJML API using JSON format

I tried several things, simplifying the JSON, reversing the body/header order, updating the versions of MJML, none of them make this component work with the JSON format.

**Comment by iRyusa** [comment]
```json
        {
            "tagName": "mj-head",
            "attributes": {},
            "children": [
                {
                    "name": "Raleway Dots",
                    "tagName": "mj-font",
                    "attributes": {
                       "href": "https://fonts.googleapis.com/css2?family=Raleway+Dots"
                    } 
                }
            ]
        }
```

Nevermind I think you forgot to put the href into the `attributes` object of `mj-font`

**Comment by AGachet** [comment]
ah, damn it, you've found a part of the problem... I've been abused by the others header components as `mj-style` or `mj-raw` ... or again `mj-preview`... 

In this one, `href` but also `name` are attributes, I will close my ticket so :). 

Really sorry for that mistake and thanks a lots four your reactivity :)

**Comment by AGachet** [comment]
Just to be clear for others, it should be like that:

```json
        {
            "tagName": "mj-head",
            "attributes": {},
            "children": [
                {
                    "tagName": "mj-font",
                    "attributes": {
                       "name": "Raleway Dots",
                       "href": "https://fonts.googleapis.com/css2?family=Raleway+Dots"
                    } 
                }
            ]
        }
```
