### ISSUE TITLE
Clarification on how MJML supports the responsiveness of our product

### ISSUE THREAD

**Issue by jlstaffbase** [mjmlio/mjml#2391]
Hi MJML,

My name is Jon and I'm reaching out on behalf of Bananatag, a customer of MJML, about the responsiveness of our Email Designer, which MJML supports. Can you assist with the below query?

One of our clients noticed that when they view a sent email, that was built using our email designer, on Outlook, the content of the email doesn't respond well with the native Outlook zoom feature. However, when they view a sent email that was created within the native Outlook compose window, the content of the email is able to respond to the resolution of the screen and adjust accordingly.

Can you please offer some insight on why this may be the case? I've attached to this support ticket both versions of the same email as well as two screenshots. The email titled "MJML Responsive Template" was created within the native Outlook compose window and the email titled "MJML Unresponsive Template" was created with our Email Designer.

We really appreciate you looking into this and please let me know if you require any additional information from us!
![Unresponsive](https://user-images.githubusercontent.com/94860347/142907341-d850d34f-cb88-44fd-b77e-8a35390f0a03.png)
![Responsive](https://user-images.githubusercontent.com/94860347/142907343-2f4fc524-917f-49f0-8573-315f83f2c695.png)
[MJML - Unresponsive Template.txt](https://github.com/mjmlio/mjml/files/7583138/MJML.-.Unresponsive.Template.txt)
[MJML - Responsive Template.txt](https://github.com/mjmlio/mjml/files/7583139/MJML.-.Responsive.Template.txt)

*I wasn't able to attach the .msg file for both emails so please let me know if there's a better place to send this to you. I also tried sending this as an email to support@mjml.io but it couldn't be delivered.

**Comment by iRyusa** [comment]
> then they view a sent email that was created within the native Outlook compose window

You shouldn't send email via Outlook send function as it alter the HTML ( if it's only for testing purpose use somehting as https://putsmail.com/ ). 

There's no way to handle the use case of zoom level with Outlook limitation, responsive email have much more limitation than a responsive website.

**Comment by jlstaffbase** [comment]
Hi @iRyusa, thanks for getting back to me!

To confirm, the affected email (MJML - Unresponsive) that was built with the Email Designer (supported by MJML) was not sent via Outlook but from Bananatag directly. However, when viewed on Outlook, the email doesn't respond to the zoom feature, in the same way, a regular email, that was natively composed in Outlook, would.
 
Does MJML not support Outlook's zoom feature and if so, are there plans to support it in the near future?

**Comment by jlstaffbase** [comment]
Hi @iRyusa, any updates on this? Thanks

**Comment by iRyusa** [comment]
> **There's no way to handle the use case of zoom level with Outlook limitation**, responsive email have much more limitation than a responsive website.

I've already reply to this in the 1st reply, try to send it with https://putsmail.com/ to see if the HTML wasn't altered by Bananatag.
