### ISSUE TITLE
Command line error: No input argument received

### ISSUE THREAD

**Issue by shinyidol** [mjmlio/mjml#2392]
Get the following error after installing mjml via cmd

```
Command line error:
No input argument received
```

Repro:
Install nodejs
Install mjml (tried -g)
run mjml in cmd/terminal

Machine:
Windows 10 (latest)
Nodejs 16.13.0

**Comment by iRyusa** [comment]
As the error state if you dont specify an input file the command won't do anything https://github.com/mjmlio/mjml/blob/master/packages/mjml-cli/README.md#command-line-interface

**Comment by shinyidol** [comment]
doh. I spaced on that one.
thanks.
