### ISSUE TITLE
Navigation bar without an icon

### ISSUE THREAD

**Issue by alenparf** [mjmlio/mjml#2395]
Hi there! 

It's my firdt day in MJML and I'm not a profi in coding. 

but I couldn't find an answer anywhere. I'd like to make my navigation bar without an icon, like this - https://monosnap.com/file/wu5bopqITqkJofPpuMqQ1iIaiTzRdC 
but I don't see how to exclude icon from there. 
I've even found an example of email with navigation bar that I need - https://mjml.io/try-it-live/templates/worldly
But even if I copy the code and past it in my email - it doesn't work like in a template. 
It looks like this - https://monosnap.com/file/3DS9x2hVIzPpkDP5y0f4nH6kBiFpXv

Please advise what should I do or where I can find info about it.

**Comment by iRyusa** [comment]
You most likely need to play with the padding here as it just "wrap" it's content. 

Can you share the code https://mjml.io/try-it-live here so we can check ?

**Comment by alenparf** [comment]
@iRyusa Here it is - https://mjml.io/try-it-live/wSjgFdMlK4t
 Many thanks for your reply. 
 
 You mean the padding of the nav-link?

**Comment by GarryFlemings** [comment]
>if I copy the code and past it in my email

If I understand right, you describe pasting MJML or HTML code into a message you're preparing in your email client (Gmail, perhaps, or a peer). That doesn't work.

There is HTML code involved whenever an email client sends or receives email. When we put code into an email the client will send, the clients tend to change the code before sending it. Further, they tend to change the code upon receipt. Neither helps us!

The best we can do is write all the code for the email and send it to the receiver through an Email Service Provider (ESP) that doesn't change the code. (Some ESPs change the code; choose carefully.)

One such sender (for testing your competed email) is www.putsmail.com. You'll need to set up an account if you don't have one, but the whole process is free.

**Comment by alenparf** [comment]
@GarryFlemings nah, I mean if I copy the code from the template and past it in mjml live (the third screenshot from the first post). I'm working in ESP company and trying out new constructors for better work.

**Comment by iRyusa** [comment]
Yep if you just lower the padding on nav-link it does work as expected https://mjml.io/try-it-live/4nclaPOMXAD ?

**Comment by alenparf** [comment]
Thank you, yes, it works just as it should!
