### ISSUE TITLE
mjml generates invalid html comments

### ISSUE THREAD

**Issue by evilsufi** [mjmlio/mjml#2399]
**Describe the bug**
According to HTML standard, [comments](https://html.spec.whatwg.org/#comments) cannot be nested and certain string are forbidden inside comments. Mjml generates such invalid html.

**To Reproduce**
1. Create a file test.mjml with this MJML code: `<mjml><mj-body></mj-body></mjml>`
2. Render it to HTML by doing 'mjml test.mjml -o test.html'
3. The result html contains nested comments such as:
  &lt;!--[if !mso]>&lt;!-->
  &lt;meta http-equiv="X-UA-Compatible" content="IE=edge">
  &lt;!--&lt;![endif]-->

**Expected behavior**
Mjml should create valid html comments which don't contain nested comments or forbidden strings (e.g. &lt;!--, -->, --!>). The above example should probably be output like this:
  &lt;!--[if !mso]>
  &lt;meta http-equiv="X-UA-Compatible" content="IE=edge">
  &lt;![endif]-->

**MJML environment (please complete the following information):**
 - OS: Linux
 - MJML Version 4.11.0
 - MJML tool used MJML CLI

**Comment by iRyusa** [comment]
Those comments are used almost everywhere for Outlook. You can read more about this here https://en.wikipedia.org/wiki/Conditional_comment#Downlevel-revealed_conditional_comment

**Comment by evilsufi** [comment]
Thanks for the reference. As explained by the wikipedia article, there seems to be no good format for the downlevel-revealed conditional comments. The structure of 

  non-IE-stuff

would be ok by the standard, except for the fact that some IE-based browsers would also render the initial "-->". But any workaround for this like having nested " ... 
and

style conditional comments within the <head> section, but only 

style comments within the <body>? At least based on the mentioned test source document. If the idea is to work around rendering extra "-->", shouldn't the first format be used everywhere (or at least in the body)?

So, it seems that web developers are between a rock and a hard place here. It's clear that browsers and other web page renders are forced to deal with all kinds of non-standard stuff, but still think html generators should aim to produce valid html.

The reason for raising this issues was that I tried to use the html generated by mjml with one Microfocus product. It has functionality to add html email templates, but it also validates the entered html before saving it. And since the generated html isn't valid html, it failed.

**Comment by iRyusa** [comment]
We use those for negation comments as you can find here https://stackoverflow.design/email/base/mso/ 

There's no way for us to output completely valid HTML as we use sometime non-standard/obsolete attributes to have everything working fine in any Mail clients
