### ISSUE TITLE
"full-width" property not functioning as described. May need further clarity in docs as to how it functions

### ISSUE THREAD

**Issue by AveryTheDev** [mjmlio/mjml#2401]
**Bug Description**
When I applied the `full-width` property to a mj-section or mj-wrapper, I am not seeing a 100% width applied instead of a max-width as stated in the [docs](https://documentation.mjml.io/#mj-section).

![Screen Shot 2022-01-06 at 11 29 53 AM](https://user-images.githubusercontent.com/23192489/148416282-93b7bb15-ebea-4fae-bb29-7bcfe2394982.png)

What I see instead is a table with a width of 100% wrapped *around* the element that has a max-width of 600px leading to visual bugs. Its supposed to change the max-width.

**To Reproduce**
1. Within a mjml file, create a mj-section or mj-wrapper
2. Apply the `full-width` property to the element
3. Compile the html file from the code

I've attached a [sandbox](https://mjml.io/try-it-live/D5hC2zCNJ) with an example. Here is the code snippet in case the link gets lost somehow

```
<mjml>
  <mj-body>
    <mj-section full-width="full-width">
      <mj-column width="100%">
        <mj-divider border-width="1px" border-style="dashed" border-color="black" width="100%" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
What I would have expected would be the horizontal rule taking up the full width of the screen. The docs say that the max-width should be changed to 100%.

**Actual behavior**
Rather than the max-width changing, a table with a width of 100% is *wrapped around* the div that has a max-width of 600px. As a result, the section's contents remain constrained to the unchanged max-width. 

![Screen Shot 2022-01-06 at 11 36 01 AM](https://user-images.githubusercontent.com/23192489/148417403-c645845b-47e3-4a23-8abe-67fd8d804060.png)

*Above is an example of what happens after I update my html file based on my changes in my mjml file (adding the full-width property). The green highlight indicates that the change in html file has been the addition of the wrapper, rather than changing the max-width. That value has been left alone.*

As a result, the horizontal rule within the section does not take up the full width but only 600px.

![Screen Shot 2022-01-06 at 11 40 14 AM](https://user-images.githubusercontent.com/23192489/148417815-bea1caca-42af-47d9-979e-0e1ae280930a.png)

**Comment by iRyusa** [comment]
> The full-width property will be used to manage the background width.

As stated it only expend the background not the content.

**Comment by AveryTheDev** [comment]
The language is confusing because it says it changes the max-width but it doesn't, it remains at 600px

**Comment by AveryTheDev** [comment]
How would I make a full width divider if I can only adjust the background width?

**Comment by iRyusa** [comment]
There is 0 mention of a max-width in this block, it only says that it will expand the background width. If you’re not happy with the formulation, feel free to open a PR about it. 

There’s no way to have full width divider, you can just use a background image with the divider with an empty section. You can also do it as HTML within mj-raw but you’re on your own with compatibility issues on clients.
