### ISSUE TITLE
inline stylesheets remove !important declarations

### ISSUE THREAD

**Issue by LucPestille** [mjmlio/mjml#2404]
**Overview**
When using custom fonts in a font-family attribute, Outlook requires an "!important" declaration to prevent it from falling back to Times New Roman, even when a fallback is declared.

However, any css files that are included with their css-inline set to "inline" which style an element also has the undesired effect of removing any "!important" declarations from the styles. This also effects styles from any mj-attributes.

**To Reproduce**
1. Create a file with this MJML code (github doesn't like the mjml tag, apologies for unformatting):
file.html
< mjml>
    < mj-head>
        < mj-attributes>
            < mj-all font-family="sans-serif" />
            < mj-button font-family="'Titillium Web', sans-serif !important"/>
        < /mj-attributes>
        < mj-include path="test.css" type="css" css-inline="inline" />
        < mj-font name="Titillium Web" href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,400;0,700;1,400;1,700&display=swap" />
    < /mj-head>
    < mj-body>
        < mj-section>
            < mj-column>
                < mj-text>
                    < h1>p is missing !important< /h1>
                < /mj-text>
                < mj-button>Click me!< /mj-button>
            < /mj-column>
        < /mj-section>
    < /mj-body>
< /mjml>

test.css
`
p {font-weight: bold;}
`

2. Render it to HTML by doing 'mjml file.html -o file-output.html'
3. View the HTML and the paragraph tag that the mj-button generates will have no "!important" declaration in its font-family style. Remove the mj-include for the css file and run again - observe the now in-place "!important"

**Expected behavior**
"!important" should not be stripped from style declarations when css is inlined, nor overwrite mj-attributes when that targeted element has styles that need inlining.

**Comment by iRyusa** [comment]
> When using custom fonts in a font-family attribute, Outlook requires an "!important" declaration to prevent it from falling back to Times New Roman, even when a fallback is declared.

Are you sure about that one ? As far as I know it only fallback to Times when importing external css, that's why we surround font import with comments, it works just fine here : https://app.emailonacid.com/app/acidtest/puPiffzP8j6iWYjwJaGPM7j6zRhXFnhOpKXSQTPP7myzj/list

If you want to preserve important with `inline` it's a default option inside `juice` you can find them here https://github.com/Automattic/juice#options `preserveImportant` should be what you're looking for.

**Comment by LucPestille** [comment]
> ... that's why we surround font import with comments

That's what I was missing, apparently, which was causing no end of issues and rabbit holes. Thanks.
