### ISSUE TITLE
SpamAssassin: Long block of hidden text - bayes poison?

### ISSUE THREAD

**Issue by lumin888** [mjmlio/mjml#2410]
**Describe the bug**
Checking the spam headers of a MJML email, I see my email has some penalty points due to long invisible text.
`1.5 LONG_INVISIBLE_TEXT    Long block of hidden text - bayes poison?`

From an inspection of the HTML, I see there is a lot of conditional fall backs for MS Office. I'm guessing these trigger the LONG_INVISIBLE_TEXT penalty from SpamAssassin.

Not a bug per se, but maybe the rendered HTML could be improved to reduce the impact on spam scores?

**To Reproduce**
1. Create a file with this MJML code: https://pastebin.com/raw/C6J496Tq
2. Render it to HTML
3. Send the HTML to any email server that filters mail using SpamAssassin
4. Check the email header for the X-Ham-Report

**Expected behavior**
The LONG_INVISIBLE_TEXT should not appear in the report, or have a lower score.

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version: mjmlio.vscode-mjml v1.0.5

**Email receiving environment**:
 - Email server that filters mail using SpamAssassin

Thank you to the MJML team for the good work.

**Comment by iRyusa** [comment]
We're aware of that but sadly there's nothing we can do, the `font-size:0` trick is used for some old webkit based clients to ensure `inline-block` doesn't render ghost spaces. More info here : #2062

**Comment by lumin888** [comment]
Just a note for myself and others, this can be fixed by setting minify to off.
