### ISSUE TITLE
A few different styles for the same mjml file?

### ISSUE THREAD

**Issue by notflip** [mjmlio/mjml#2411]
I have an email that is sent out when a customer completes an order. The thing is I have 3 subsites with their own styling.
I'm not sure what the best way would be to accomplish this with mjml.

Let's say I have a text field like this `<mj-text font-family="Raleway" font-weight="800">`, It would not be clean to add an if statement here to check which subsite we're on. **does this mean mjml would favor me to have an mjml file for each subsite?**

I would love to have only the one file for all subsites, does anyone have an idea on how I can achieve this?

**Comment by iRyusa** [comment]
If you're using a templating language on top of MJML you could use `mj-class` to create a different style for each and apply it conditionally

**Comment by notflip** [comment]
That what I'm thinking, currently I'm going to try and have a different `mj-attributes` for each sub site, is that what you would recommend? So I can have default styles and mj-classes for each subsite

**Comment by kmcb777** [comment]
Yes, depending on the differences between your styles, you could have different sets of `mj-attributes`.
Note that you can use `mj-include` to import `mj-head` components, or even css files that will be included the same way as with a `mj-style` so you could handle the differences in partials and use a templating engine to set which files are mj-included
