### ISSUE TITLE
(Question) Equal height column (Image & Text)

### ISSUE THREAD

**Issue by zecka** [mjmlio/mjml#2412]
Is there a way to force the columns to have the same height?

I try to find a solution for layout like that:
![image](https://user-images.githubusercontent.com/18116930/150299758-8d8fa6b2-d1a2-44ae-ad2d-3672e6c7bb5d.png)

I want to have columns of equal height to give a background-color to the image column (if the text is higher).

So the expected result is
![image](https://user-images.githubusercontent.com/18116930/150300304-bb70ddb7-6b2e-4b04-9955-9f7739d658cf.png)

Here is the actual playground: https://mjml.io/try-it-live/jiLY4cWHug1

To be honest I haven't found a solution in pure html while keeping the columns responsive either

**Comment by iRyusa** [comment]
There's no way to do so because both div of column are independent. What you could do is apply the background color of the smallest column to the section. It fakes it, but it's not the best.

**Comment by zecka** [comment]
Ok understood, but the solution does not seem ideal because the smallest column can be different depending on the size of the desktop client.
 P:EX
 
![image](https://user-images.githubusercontent.com/18116930/150313518-c57d5843-07f9-4626-992b-54baa8f08a65.png)
![image](https://user-images.githubusercontent.com/18116930/150313584-4731b559-1d81-43f1-a058-593b5d0bc8b8.png)


So I think my option is:
- Tell the design team not to provide this type of layout 🤣
- Restrict the length of the content for the editorial team
- Dynamically change image ratio depending of content length
