### ISSUE TITLE
Media queries can only be applied to css, so using mj-attributes for dark-mode is impossible?

### ISSUE THREAD

**Issue by notflip** [mjmlio/mjml#2413]
There's a few issues that already discussed dark mode, I'm not here for a feature request, just to find out what is possible at this time.

I know I can add the following to achieve dark mode
```
<mj-style>
    body {
        background-color: #f8f1f2;
    }

    @media (prefers-color-scheme: dark) {
        body {
            background-color: #2a2a2a !important;
        }
    }
</mj-style>
```

However, let's say I have the following attribute (which in my case can be different depending on some variables)

```
<mj-attributes>
    <mj-text color="#511620"/>
</mj-attributes>
```
I suppose that, to achieve dark mode, I can't use the attributes but should rely on 100% css to style my mail, is that correct?

**Comment by iRyusa** [comment]
In this case the `color` attributes will be applied as inline-style on the div produced by `mj-text`. 

So you can just use css-class on `mj-text` and override it with a media query.
