### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by ronaldohoch** [mjmlio/mjml#2414]
**Describe the bug**
Documentation website is broken from mj-accordion onwards

**To Reproduce**
1. Go to https://documentation.mjml.io/#standard-body-components
2. Check the documentation page broken

**Screenshots**
![image](https://user-images.githubusercontent.com/2287371/150847023-336cfe94-9612-4d44-ac09-a0e11692691b.png)
![image](https://user-images.githubusercontent.com/2287371/150847064-63ef0e20-486c-423d-845c-0500d92129ee.png)
![image](https://user-images.githubusercontent.com/2287371/150847099-b07ff0f1-ff6e-450e-9310-cbfbdb06fc89.png)
![image](https://user-images.githubusercontent.com/2287371/150847555-ec10dd5d-9857-462c-8bbb-d50defbe98de.png)

**Correction**
Missing quotes here and other onwards..
![image](https://user-images.githubusercontent.com/2287371/150847961-81efd4a6-e209-49be-95b9-a9f2206fc6e0.png)

**Additional context**
Tested in Brave and Firefox, also in incognito mode.

**Comment by iRyusa** [comment]
Thanks for this, PR has been merged this should be resolved soon

**Comment by ronaldohoch** [comment]
Thank you!
