### ISSUE TITLE
My wishlist for mjml

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#242]
1) A way to build multilingual HTML Emails
2) inline style should be allowed on `<mj-image style="">` to style `ALT` text
3) There should be a way to control internal padding of `<mj-button>`
4) I guess currently there is not way to horizontally aligned `<mj-table>`
5) (MJML App) - Option to save gist as private gist in user's account
6) An option to control spacing between icons for` <mj-social>`
7) An option to re-use any style and content at multiple places
8) An option to inherit styling from parent element if required
9) letter-spacing is required for `<mj-text>` and `<mj-button>`
10) (MJML App) Option to save file in the using `Ctrl+S`
11) text-transform should be allowed for` <mj-text>`, `<mj-button>` and `<mj-table>`
12) An option needed to add box-shadow for `<mj-section>`, `<mj-column>`
13) An option to use `<mj-column>` like table, currently, column takes full width in mobile view
14) A component which makes possible to use this technique https://julie.io/email-layout-calculator/ to create responsive columns without media queries

**Comment by ngarnier** [comment]
Hey @jitendravyas,

Thank your for your issue, we appreciate your involvement in MJML.
​
Unfortunately, each issue must be specific to one bug or feature request or it is impossible to track, so I have to close your issue. It doesn't mean we don't take good note of your feedback which is very valuable to us.
​
Finally, if you want to see those wishes from your list granted, the best is to submit pull requests. MJML will definitely benefit from the help of contributors like you to make it even better.
