### ISSUE TITLE
<mj-raw/> with table based HTML under column with padding misaligned subsequent siblings 

### ISSUE THREAD

**Issue by hkurra** [mjmlio/mjml#2420]
**Describe the bug**
I have written a raw HTML to render image with a hyperlink and a play icon at center.
Used the `<mj-raw/>` attribute to render this custom HTML code along with the other mjml elements, if i give padding to parent `<mj-column/>` element then the element after `<mj-raw/>` element with my custom code are not getting proper padding and getting misaligned as compared to other elements.
![image](https://user-images.githubusercontent.com/6569316/151785168-19e4ca49-a04f-4177-b9d6-be9b6e88af65.png)

The good part is all email clients are rendering that HTML correctly but the preview has the alignment issue   

**To Reproduce**
I have created a sample  using mjml playground [here](https://mjml.io/try-it-live/SFpbS_-a0rv) using following  HTML code

```
       <mj-raw><table>
  <tbody><tr>
    <td></td>
    <td rowspan="2" style="padding-bottom: 10px; padding-top: 10px; padding-left: 20px; padding-right: 20px">
      <a target="_blank" class="ghl-mj-video-root" href="https://www.youtube.com/watch?v=6-xjz1xn1fI">
        <img src="https://img.youtube.com/vi/6-xjz1xn1fI/maxresdefault.jpg" style="width:auto; height:auto; max-width:100%; max-height:100%">
      </a>
    </td>
  </tr>
  <tr>
    <td colspan="2" align="center" style="padding-bottom: 10px; padding-top: 10px; padding-left: 20px; padding-right: 20px" class="ghl-mj-video-play-btn ghl-mj-video-play-btn-">
      <a target="_blank" class="ghl-mj-video-root" href="https://www.youtube.com/watch?v=6-xjz1xn1fI" style="text-decoration: none">
        <span style="background-color:rgb(255, 0, 0, 1);
                font-size: 25px;
                border-radius: 65% / 10px;
                padding:9px 18px;               
                display: inline-flex;">
                  <span style="border-style: solid;
                      box-sizing: border-box;
                      border-width: 9px 0px 9px 18px;
                      border-color: transparent transparent transparent white; 
                      display: inline-block">
                  </span>
          </span>
      </a></td>
  </tr>
</tbody></table></mj-raw>
        
```

**Expected behavior**
Subsequent siblings  should aligned like other element 

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML: Version 4.9.3
 - MJML: MJML playground

**Screenshots**
![image](https://user-images.githubusercontent.com/6569316/151785912-627affe9-d00f-4340-bf5e-23b4601693e2.png)

**Comment by iRyusa** [comment]
As you use `mj-raw` then it will directly set the content inside the node. So the produced HTML is no longer valid as you're in a `table`. You need to surround your code by a tr+td. Or just paste it inside a `mj-text` mj-raw is not really mandatory here.
