### ISSUE TITLE
Use with angular app

### ISSUE THREAD

**Issue by mohamedelmancy** [mjmlio/mjml#2424]
Hi, i am new to mjml , i am install the mjml into the my angular application, but i am block in the build time i need to convert the mjml files into the html, can you any one guide me ?How i do with this CLI build .

Thank you.

**Comment by mohamedelmancy** [comment]
closed

**Comment by iRyusa** [comment]
Can you please provide more details about this ?
If you need `mjml2html` on your front end you can use `mjml-browser` package that can be used.
If you only want to convert in cli then follow the instruction in the readme.

**Comment by iRyusa** [comment]
Closing for now feel free to reopen with more details
