### ISSUE TITLE
MIT License isn't parsed to generated HTML

### ISSUE THREAD

**Issue by artClown** [mjmlio/mjml#2425]
Hello, sorry for a newbie and stupid question. I'm planning to use MJML in a commercial context where the email design will be done using MJML and then the generated HTML will be sent to customers. 

I've checked the generated HTML (using MJML VS Code extension) and can't find MIT license being parsed. Would it cause me trouble if the license isn't there on the generated HTML?

**Comment by iRyusa** [comment]
There's no need to have the MIT license in the final output, it's fine for you 👍
