### ISSUE TITLE
Performance issues when upgrading v4.6.3

### ISSUE THREAD

**Issue by shanizlo** [mjmlio/mjml#2426]
**Describe the bug**
Hi mjml Team,
We are using mjml v4.6.3 (all mjml components v4.6.3 as well).
We tried to upgrade to v4.10.3 (the first version where nth-check vulnerability is fixed), but we experienced major performance issues: rendering emails took much longer, it created a bottleneck and an incident at our side.
We tried version 4.12.0, run load tests, and observed performance issues as well.
We can't point out which version exactly between 4.6.3 and 4.10.3 the performance change happened.
But this is blocking us from upgrading to the new versions (and especially from upgrading to the version without vulnerabilities).

**To Reproduce**
1. Run load tests using mjml 4.6.3. 
2. Observe and note the results.
3. Upgrade mjml to version 4.10.3 and higher.
4. Run load tests and observe the results.
5. Compare the results from both load tests.

**Expected behavior**
Results from the load tests shouldn't significantly differ.

**MJML environment (please complete the following information):**
 - OS: Linux (running on Docker)
 - MJML Version 4.10.3 and up
 - MJML tool used: mjml package for node

**Email sending environment(for rendering issues)**:
 - Platform used to send the email sendGrid. 
 - Rendering with mjml happens in our service.

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**

**Additional context**

**Comment by iRyusa** [comment]
Can you open a repository to reproduce the issue and provide some data too ? It's hard to guess like that as we don't have any benchmark inside the repo and as I know there's no major change between those version.

**Comment by iRyusa** [comment]
We'll probably reopen this one if anyone provide a repository to reproduce for now i'm closing
