### ISSUE TITLE
[Question] Preserve Media query on mj-style "inline"

### ISSUE THREAD

**Issue by zecka** [mjmlio/mjml#2428]
In <mj-style> tag I got a css that come from scss file. This css contain also media query. Any way to keep media query in <style> tag and inline the rest of css ? Like we can do with juice with `preserveMediaQueries` options ?

```mjml
<mjml>
  <mj-head>
    <mj-style inline="inline">
      .demo strong{
      	color: blue;
      }
      @media only screen and (max-width: 600px) {
        *[class~="hide-mobile"] {
          display: none !important;
        }
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text css-class="hide-mobile demo">
          <strong>Hide on mobile</strong>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by zecka** [comment]
My MQ and no-MQ styles are in the same scss files. So, in the output, I have one css file that contains all my css rules. I want to put the css inline for better compatibility with clients and keep the media queries for clients that support them.

But of course I can add something like [postcss-extract-media-query](https://www.npmjs.com/package/postcss-extract-media-query) in my build process.

I ask that because I know juice have an option for this behaviour.

**Comment by iRyusa** [comment]
That would be a bit hard for juice to ignore some part of our head styles I guess there's no easy solution for that :/
