### ISSUE TITLE
MJML Padding not working when image has a border

### ISSUE THREAD

**Issue by gowram** [mjmlio/mjml#2429]
**Describe the bug**
As per the given MJML,  padding on all 4 sides given as 10px, whereas right side padding not working as per the expectation.

**To Reproduce**
```xml
<mjml>
  <mj-head>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column background-color="#21eb46" border="4px solid red" padding="10px" width="100%">
        <mj-image align="center" container-background-color="grey" src="https://img.bfmtv.com/c/630/420/871/7b9f41477da5f240b24bd67216dd7.jpg" padding="10px" border="8px solid black"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
Padding should apply all the sides equally.

**MJML environment (please complete the following information):**
 -  MJML Version **4.9.3**
 - MJML tool used **https://mjml.io/try-it-live/g6fuXOkyMIq**

**Screenshots**
![screenshot-mjml io-2022 02 25-12_48_29](https://user-images.githubusercontent.com/551819/155671983-1647fe16-872b-45d6-bad5-b340cb297dac.png)

**Comment by iRyusa** [comment]
Most likely an issue where we can't use border-box as it's not supported in older outlook clients. It's weird that border left-right should be removed from the img's width to ensure it doesn't overflow tho... cf https://github.com/mjmlio/mjml/blob/f74b71880261b9550c8038323e88f0e099d598d1/packages/mjml-core/src/createComponent.js#L138-L156

Note that the try it live content has been updated can you post a new one ?

**Comment by iRyusa** [comment]
Tried to debug a bit but as we can't really support box-sizing there's no way to prevent this behavior. Border make the container even if sized properly to overflow as the image isn't sized properly by the browser.

Closing this one as there's not so much we can do here, if you need to "fix" this behavior, you can apply a box-sizing:border-box to ensure the image won't overflow but it's not supported everywhere
