### ISSUE TITLE
Background brocken in Outlook since 2.0

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml#243]
In MJML <= 1.3.4:
The full Email has the background color that was set with <mj-body background-color="#ebebeb">
`<body style="background: #ebebeb;">
  <div style="background-color:#ebebeb;"><!--[if mso]>`

Since MJML 2.0:
Everything around the 600px table is left white.
`<body>
  <div style="background-color:#ebebeb;"><!--[if mso]>`

I don't know why this was removed, but apparently Outlook needs
`<body style="background: #XXXXXX;">`

**Comment by iRyusa** [comment]
Hello @janus-reith !

Closing because related to #236 will be fixed in the next release ! Sorry about that

**Comment by janus-reith** [comment]
Sorry, just found #236 aswell and wanted to close this, you were faster :)
