### ISSUE TITLE
TypeError: (0 , mjml_1.default) is not a function

### ISSUE THREAD

**Issue by meness** [mjmlio/mjml#2430]
**Describe the bug**
```typescript
import mjml from 'mjml';

mjml(content,options); // throws an exception in TypeScript
```

> TypeError: (0 , mjml_1.default) is not a function
>     at MjmlAdapter.compile (C:\Users\Alireza\Desktop\Prestige\Backend\src\providers\mail\adapters\mjml.adapter.ts:38:31)
>     at C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\@nestjs-modules\mailer\dist\mailer.service.js:48:40
>     at processPlugins (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:283:13)
>     at C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:287:17
>     at Mail._convertDataImages (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:391:20)
>     at Mail._defaultPlugins.compile (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:31:41)
>     at processPlugins (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:283:13)
>     at Mail._processPlugins (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:291:9)
>     at Mail.sendMail (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\nodemailer\lib\mailer\index.js:168:14)
>     at MailerService.<anonymous> (C:\Users\Alireza\Desktop\Prestige\Backend\node_modules\@nestjs-modules\mailer\dist\mailer.service.js:74:51)

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS] Windows
 - MJML Version [e.g. 4.2.0] 4.12.0

**Comment by meness** [comment]
I cannot import it like this `import * as mjml from 'mjml'` because `esModuleInterop` cannot be enabled due to NestJS

**Comment by meness** [comment]
Importing like this `import mjml2html = require('mjml');` solved the problem. I think it's an issue with the `@types/mjml`

**Comment by AlexDieRobbe** [comment]
I ended up using a postinstall script in `scripts/postinstall.ts`:

```ts
import path from 'path';
import fs from 'fs';

const FILE_PATH = path.join(
  'node_modules',
  '@nestjs-modules',
  'mailer',
  'dist',
  'adapters',
  'mjml.adapter.js'
);

const fileContent = fs.readFileSync(FILE_PATH).toString();
const patch = fileContent.replace(
  'mail.data.html = (0, mjml_1.default)(mail.data.html).html;',
  'mail.data.html = (0, mjml_1)(mail.data.html).html;'
);
fs.writeFileSync(FILE_PATH, patch);
if (fileContent !== patch) {
  console.debug('postinstall: OK Fix import in mjml.adapter.js');
} else {
  console.debug('postinstall: OK');
}
```

then in my package.json
```json
"scripts": {
  "postinstall": "NODE_NO_WARNINGS=1 node --experimental-strip-types scripts/postinstall.ts"
}
```
