### ISSUE TITLE
API service not working

### ISSUE THREAD

**Issue by ryan-saffer** [mjmlio/mjml#2431]
**Describe the bug**
I am using the MJML api service, and while it works the first few times, after a number of requests I am seeing this error:
`Exception: Address unavailable: https://api.mjml.io/v1/render`

I have been using the MJML api for a long time, and never had a single issue. I have now seen this error multiple times in the past few weeks.

**To Reproduce**
1. Use the MJML render API

**Expected behavior**
The endpoint should be available

**Comment by iRyusa** [comment]
Can't seem to reproduce in my side. Can you provide more details about this ?

**Comment by iRyusa** [comment]
Closing for now, feel free to find a proper way to reproduce :/
