### ISSUE TITLE
Docs contain some assets which give a 404 error

### ISSUE THREAD

**Issue by andyfoote** [mjmlio/mjml#2433]
**Describe the bug**
In the Docs regarding the Carousel (https://documentation.mjml.io/#mj-carousel) it gives 2 URLs which are used as defaults for the left/right arrow buttons:
- https://mjml.io/assets/img/left-arrow.png
- https://mjml.io/assets/img/right-arrow.png

Going to either of these URLs gives a 404 error. 

On inspecting the demo (https://mjml.io/try-it-live/components/carousel) the actual URLs which are used are:
- https://i.imgur.com/xTh3hln.png
- https://i.imgur.com/os7o9kz.png 

**To Reproduce**
Go to the first set of URLs. See HTTP 404 error page.
Go to second set of URLs, see HTTP 200 response with correct images.

**Expected behavior**
Docs need updating to include second set of URLs

**MJML environment (please complete the following information):**
N/A. Docs related.

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
N/A

**Screenshots**
N/A

**Additional context**
None

**Comment by iRyusa** [comment]
👍  Can you open a pr about this ?

**Comment by GarryFlemings** [comment]
PR #2438 addresses this issue.
