### ISSUE TITLE
Create tag mj-json to allow for embedding of advanced json encoded mjml inside an mjml document

### ISSUE THREAD

**Issue by dariusj18** [mjmlio/mjml#2435]
**Is your feature request related to a problem? Please describe.**

I am dynamically generating mjml documents using ejs and for the most part this is easy, however I would like to use some more advanced modern style document generation techniques, ex. `Array.map` to convert an array into a series of columns, etc.  In such cases it would be easier for me to return an serialized json object rather than mjml code.

**Describe the solution you'd like**

If there was a either a new tag, ex, `<mj-json>{json goes here}</mj-json>` or an attribute added to an existing tag, ex. <mj-section children="{json goes here}"></mj-section>`

**Describe alternatives you've considered**

I could just use the older for loops with conditionals for opening and closing tags (which is what I will end up doing currently)

**Comment by iRyusa** [comment]
I don't think this would comes up into mjml-core as mixing markup is a pain to handle. However, you can just use the `jsonToXml` helper that we currently have : https://github.com/mjmlio/mjml/blob/bd9bb7f10235ab473a0279c2768161504eace326/packages/mjml-core/src/helpers/jsonToXML.js
