### ISSUE TITLE
Convert JSON MJML templates back to HTML

### ISSUE THREAD

**Issue by franfrLor** [mjmlio/mjml#2445]
I'm working with Mailjet's templates API. Templates get returned from this in [JSON format](https://documentation.mjml.io/#using-mjml-in-json).

Is there an easy way to convert from this JSON format HTML?

I tried with the official API (https://mjml.io/api/documentation/) but it doesn't work.

It's work in XML :
`{
  "mjml": "<mjml><mj-body><mj-container><mj-section><mj-column><mj-text>Hello world</mj-text></mj-column></mj-section></mj-container></mj-body></mjml>"
}`

It's not workin in JSON :
`{
  "mjml": {"tagName": "mjml","attributes": {},"children": [{"tagName": "mj-body","attributes": {},"children": [{"tagName": "mj-container","attributes": {},"children": [{"tagName": "mj-section","attributes": {},"children": [{"tagName": "mj-column","attributes": {},"children": [{"tagName": "mj-image","attributes": {"width": "100px","src": "\/assets\/img\/logo-small.png"}},{"tagName": "mj-divider","attributes": {"border-color": "#F46E43"}},{"tagName": "mj-text","attributes": {"font-size": "20px","color": "#F45E43","font-family": "Helvetica"},"content": "Hello World"}]}]}]}]}]}
}`
OR
`{
  "mjml": {
    "mj-body": {
      "mj-container": {
        "mj-section": {
          "mj-column": {
            "mj-text": "Hello world"
          }
        }
      }
    }
  }
}`

I have this error :
`{
    "message": "The request body is not JSON compliant",
    "request_id": "32e94ec4-0287-43a9-9dc6-ce97f4e9c786",
    "started_at": "2022-03-16T10:12:06Z"
}`

Thank you for your help.

**Comment by iRyusa** [comment]
You should post the json as a string and it should work fine

**Comment by franfrLor** [comment]
Oh thx I must unescape quotes
