### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by Atulin** [mjmlio/mjml#2447]
**Is your feature request related to a problem? Please describe.**
I would love to write some quick tools that use MJML under the hood, and would love to do it with Deno. Unfortunately, that's not an easy task, since Deno uses its own system for adding packages, and it requires support by the library authors.

**Describe the solution you'd like**
Deno support added to MJML

**Describe alternatives you've considered**
Creating said tool with something else than Deno, but all other Typescript-based solutions are sub-par at best, require a whole song and dance.

**Comment by iRyusa** [comment]
There's no plan to support Deno for now. I know that you could import NPM package from Deno (with a bit of work) but I have 0 idea if it works
