### ISSUE TITLE
Mj-column has "invalid" width in mj-group

### ISSUE THREAD

**Issue by SebastianStehle** [mjmlio/mjml#2449]
**Describe the bug**
When a mjml column is used inside a mj-group and has a fixed width, it gets a very small percentage width on mobile.

e.g. this gets rendered:
```
<div class="mj-column-px-100 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:0.16666666666666666%;">
```

**To Reproduce**
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column width="100px"></mj-column>
        <mj-column></mj-column>
    </mj-group>
  </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version: 4.12.0
 - MJML tool used CLI

Btw: I think the rendering is overly complicated because there is no separate measure / layout pass.

**Comment by iRyusa** [comment]
Mj column inside mj group can be only defined in percentage that’s why.

**Comment by SebastianStehle** [comment]
But why?

**Comment by iRyusa** [comment]
Because we can’t ensure any overflow/stacking issue with px based column inside mj group as the width is based of the mobile/client defined viewport
