### ISSUE TITLE
How to use custom google font?

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#245]
I want to use custom fonts from google fonts but don't know how to do it in mjml.

**Comment by ngarnier** [comment]
Hey @jitendravyas, 

This is not possible at the moment but please have a look at this issue and feel free to share your opinion: https://github.com/mjmlio/mjml/issues/80.

I can still suggest 1 workaround: loading your custom font directly in the output HTML.

I'm closing this issue to keep the discussion on #80
