### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by AlaJohnson** [mjmlio/mjml#2455]
**Is your feature request related to a problem? Please describe.**
Easy solve for dark mode vs inline css everywhere

**Describe the solution you'd like**
section in the header to set link color, button color, font color, etc for dark mode 

**Describe alternatives you've considered**
Inline css for all components, but leaves a lot of room for error

**Additional context**
likely will be continuing to grow in use. 50% of our audience currently

**Comment by iRyusa** [comment]
Duplicate of #2010
