### ISSUE TITLE
White line is appearing between the sections 

### ISSUE THREAD

**Issue by kishanindegene** [mjmlio/mjml#2456]
**Describe the bug**
When adding a section with background color a white line is shown between the sections

**To Reproduce**
`<mjml>
  <mj-body background-color="#ffffff">
    <mj-section background-color="#009FE3" padding-bottom="0px" padding-top="0">
      <mj-column vertical-align="top" width="100%">
        <mj-text align="left" color="#ffffff" font-size="45px" font-weight="bold" font-family="open Sans Helvetica, Arial, sans-serif" padding-left="25px" padding-right="25px" padding-bottom="30px" padding-top="50px">Welcome aboard</mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#009fe3" padding-bottom="20px" padding-top="20px"  padding-left="20px">
   <mj-text align="left" color="#ffffff" font-size="45px" font-weight="bold" font-family="open Sans Helvetica, Arial, sans-serif" padding-left="25px" padding-right="25px" padding-bottom="30px" padding-top="50px">Welcome aboard</mj-text>
    </mj-section>
  </mj-body>
</mjml>`

**Expected behavior**
No white should be shown between the sections.

**MJML environment (please complete the following information):**

- MJML Version 4.9.3
- https://mjml.io/try-it-live/DTx5_zwGr

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Outlook Desktop application

**Screenshots**
![image](https://user-images.githubusercontent.com/100404294/161013167-392c2cf3-e8a5-4383-b85d-a150effee6c7.png)

**Comment by GarryFlemings** [comment]
You mention Outlook. You may be experiencing the behavior described in these two articles.
![image](https://user-images.githubusercontent.com/14095071/161064438-eea6eba1-85c6-4744-99f6-555f6e6dc237.png)
![image](https://user-images.githubusercontent.com/14095071/161064483-90e5a37d-1815-4b70-a8cf-26819de07d1f.png)
You can find other articles, too.

Please try fixes there and get back to the MJML team if unable to fix the problem. An additional source of help is https://mjml.slack.com/, if you like.

**Comment by caseyjhol** [comment]
Possibly related: https://github.com/mjmlio/mjml/issues/1990

**Comment by iRyusa** [comment]
Not so much we can do about this as it's a bug within outlook. Try to change some padding/font-size/... everything in pixel as it's most likely a rounding issue within outlook render engine
