### ISSUE TITLE
Fill Variables Jason MJML

### ISSUE THREAD

**Issue by isdito** [mjmlio/mjml#2457]
Hello,

**Is your feature request related to a problem? Please describe.**
Automatically fill in variables especially so as not to be searching in the text code

**Describe the solution you'd like**
Being able to put some variables that are replaced in the email before send via interface

Any example?
reggards

![image](https://user-images.githubusercontent.com/602151/161418397-c8ee1491-c2df-4919-a108-214c4eae4f38.png)

**Comment by iRyusa** [comment]
You need to select either ERB or Handlebars template on the first select.
