### ISSUE TITLE
mj-html-attributes not set when used inside of mj-table

### ISSUE THREAD

**Issue by goellner** [mjmlio/mjml#2460]
**Describe the bug**
`mj-html-attributes` not set when used inside of `mj-table`
The docs state it is applied to every html attribute:
https://github.com/mjmlio/mjml/blob/master/packages/mjml-head-html-attributes/README.md

**To Reproduce**
https://mjml.io/try-it-live/z_8OJgEPX

1. Create a file with this MJML code: 
```
<mjml>
   <mj-head>
   <mj-html-attributes>
      <mj-selector path=".mc-repeatable">
        <mj-html-attribute name="mc:repeatable">true</mj-html-attribute>
      </mj-selector>
      <mj-selector path=".year">
        <mj-html-attribute name="mc:edit">year</mj-html-attribute>
      </mj-selector>
  </mj-html-attributes>
  </mj-head>
  <mj-body>
    <mj-section css-class="mc-repeatable">
      <mj-column>
        <mj-table>
          <tr style="border-bottom:1px solid #ecedee;text-align:left;padding:15px 0;">
            <th style="padding: 0 15px 0 0;">Year</th>
            <th style="padding: 0 15px;">Language</th>
            <th style="padding: 0 0 0 15px;">Inspired from</th>
          </tr>
          <tr css-class="mc-repeatable">
            <td style="padding: 0 15px 0 0;"><a href="https://example.com" css-class="year">2022</a></td>
            <td style="padding: 0 15px;">PHP</td>
            <td style="padding: 0 0 0 15px;">C, Shell Unix</td>
          </tr>
        </mj-table>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
3. Inside the`mj-table` it doesn't get replaced

**Expected behavior**
It should replace inside the `mj-table` component too

**MJML environment (please complete the following information):**
 - OS: MacOs
 - MJML Version 4.12.0
 - MJML tool used Live Editor and mjml node package

**Comment by iRyusa** [comment]
Replace css-class by class and it should work fine

**Comment by goellner** [comment]
Thanks, that totally makes sense! Thank you very much!
