### ISSUE TITLE
Media query doesn't work

### ISSUE THREAD

**Issue by SophieZhao5219** [mjmlio/mjml#2464]
**Describe the bug**
`<mjml>
	<mj-head>
  <mj-style>
    
    .email-wrapper-2>table>tbody>tr>td {
    	padding: 0px 70px 0 !important;
    }
    .email-wrapper-2>table>tbody>tr>td>div {
      padding: 24px 24px 0 24px !important;
      border-top: 1px solid #E8E9ED !important;
      border-left: 1px solid #E8E9ED !important;
      border-right: 1px solid #E8E9ED !important;
      border-top-left-radius: 15px !important;
      border-top-right-radius: 15px !important;
      box-shadow: 5px 10px 10px #eeeeee !important;
    }
    .email-wrapper-3>table>tbody>tr>td {
    	padding: 0px 70px 0 !important;
    }
    .email-wrapper-3>table>tbody>tr>td>div {
      padding: 0 24px !important;
			background-color: #ffffff !important;
      border-left: 1px solid #E8E9ED !important;
      border-right: 1px solid #E8E9ED !important;
      box-shadow: 5px 10px 10px #eeeeee !important;
    }
		.email-wrapper-3>table>tbody>tr>td>div:nth-last-child(1) {
    	padding-bottom: 32px;
      border-bottom: 1px solid #E8E9ED !important;
      border-bottom-left-radius: 15px !important;
      border-bottom-right-radius: 15px !important;
    	margin-bottom: 64px !important;
    }
    .email-section-3>div {
    	border: 1px solid #E8E9ED !important;
			border-radius: 15px !important;  
		}
    .email-footer a {
      color: #222222 !important;
    }
    .email-button>table>tbody>tr>td>a {
    	padding: 14px 25px !important;
    }
    
    @media only screen and (max-width: 500px) {
    	.email-wrapper-1>table>tbody>tr>td {
        padding: 0 24px !important;
      }
    	.email-image-1>table>tbody>tr>td {
    		padding-top: 40px !important;
    		padding-left: 12px !important;
    	}
    	.email-section-1>table>tbody>tr>td {
    		padding: 20px 0px 24px 0px !important;
    	}
      .email-text-1 {
        padding: 0 12px !important;
      }
    
    	.email-wrapper-2>table>tbody>tr>td {
				 padding: 0px 24px 0 !important;
    	}
    	.email-wrapper-3>table>tbody>tr>td {
        padding: 0px 24px 0 !important;
      }
    	.email-section-2>table>tbody>tr>td {
				 padding: 16px 4px 0 !important;
    	}
    	.email-text-2 {
    		padding-left: 10px !important;
    	}
    	.email-text-2>div {
    		font-size: 14px !important;
    	}
    	.email-text-3>div {
    		font-size: 12px !important;
    	}
    	.email-col-1 {
    		width: 44px !important;
    	}
    	.email-col-2 {
    		width: 200px !important;
    	}
    	.email-col-3 {
    		width: 44px !important;
    	}
    	.email-section-3>table>tbody>tr>td {
    		padding: 0 10px !important;
			}
    	.email-col-4 {
    		width: 75px !important;
    	}
    	.email-col-4>table>tbody>tr>td {
    		padding: 0 5px 0 0 !important;
    	}
    	.email-col-5 {
    		width: 75px !important;
    	}
    	.email-col-5>table>tbody>tr>td {
    		padding: 0 5px 0 !important;
    	}
    	.email-col-6 {
    		width: 75px !important;
    	}
    	.email-col-6>table>tbody>tr>td {
    		padding: 0 0 0 5px !important;
    	}
    	.email-text-4>div {
    		font-size: 13px !important;
			}
    	.email-wrapper-4>table>tbody>tr>td {
        padding: 0 12px !important;
      }
      .email-cancel-section>table>tbody>tr>td {
        padding-left: 24px !important;
        padding-right: 24px !important;
      }
    	.email-divider-1>p {
    		width: 295px !important;
    	}
    	.email-col-7>table {
    		border: none !important;
    	}
      .email-col-7>table>tbody>tr>td {
    		padding-left: 24px !important;
        padding-right: 24px !important;
    	}
      .email-section-text>table>tbody>tr>td {
        padding-left: 4px !important;
        padding-right: 4px !important;
      }
    
    }
    

    
    
  </mj-style>
</mj-head>
  <mj-body background-color="#ffffff" width="680px">

  <mj-wrapper css-class="email-wrapper-1" padding="0 70px" border-top="1px solid #E8E9ED" border-left="1px solid #E8E9ED" border-right="1px solid #E8E9ED">    
    <mj-raw>
      
    </mj-raw>
    <mj-section css-class="email-image-1" padding="64px 0 0 40px">
      <mj-column>
        <mj-image align="left" padding="0" width="107px" height="36px" src="{{renderContext.brandInfo.logo}}"></mj-image>
      </mj-column>
    </mj-section>

    <mj-section css-class="email-section-1" padding="24px 0px 32px 0px">
      <mj-column>
        <mj-text css-class="email-text-1" padding="0 40px" line-height="32px" font-family="Helvetica" font-size="24px" color="#222222" font-weight="600">Registration confirmation for</mj-text>
        <mj-text css-class="email-text-1" padding="0 40px" line-height="32px" font-family="Helvetica" font-size="24px" color="#002855" font-weight="600">{{renderContext.webinarInfo.title}}</mj-text>
        <mj-text css-class="email-text-1" padding="12px 40px 0 40px"  line-height="24px" font-family="Helvetica" font-size="16px" color="#656C80">{{formatTime renderContext.webinarInfo.scheduledStartTime}}</mj-text>
      </mj-column>
    </mj-section>
  </mj-wrapper>

  <mj-wrapper css-class="email-wrapper-2" border-left="1px solid #E8E9ED" border-right="1px solid #E8E9ED"  background-size="100%"  background-repeat="repeat">
   <mj-raw>
      
    </mj-raw>
    <mj-section padding="0px">
      <mj-column>
      </mj-column>
    </mj-section>
  </mj-wrapper>
    
  <mj-wrapper css-class="email-wrapper-3" border-left="1px solid #E8E9ED" border-right="1px solid #E8E9ED" background-color="#F7F1EC" background-size="100%" background-repeat="repeat">
    <mj-raw>
      
    </mj-raw>
    <mj-section css-class="email-section-text" padding="8px 16px 0">
      <mj-column>
        <mj-text padding="0" line-height="28px" font-family="Helvetica" font-size="16px" color="#222222">Hi <span style="font-weight:600">\\{{renderContext.registrant.firstName}}</span>, 👋</mj-text>
        <mj-text padding="0px" line-height="28px" font-family="Helvetica" font-size="16px" color="#222222">Thanks for registering for <span style="font-weight:600">{{renderContext.webinarInfo.title}}</span>. We look forward to having you.</mj-text>
      </mj-column>
    </mj-section>

    <mj-section padding="24px 0 40px">
      <mj-column>
        <mj-button css-class="email-button" padding="0" background-color="#F54C3D" border-radius="24px" height="24px" width="150px" font-size="16px" href="\\{{renderContext.registrant.joinUri}}" font-weight="500">Join Webinar</mj-button>
      </mj-column>
    </mj-section>           

    <mj-section padding="0">
      <mj-column>
        <mj-divider padding="0" border-width="1px" border-style="solid" border-color="#E8E9ED"/>
      </mj-column>
    </mj-section>
    
    <mj-raw>
      
    </mj-raw>
    <mj-section css-class="email-section-2" padding="16px 16px 0">
      <mj-column>
        <mj-text padding="0" line-height="28px" font-family="Helvetica" font-size="16px" color="#222222">You can also copy and paste this link into your browser.</mj-text>
        <mj-text padding="4px 0 0" line-height="22px" font-family="Helvetica" font-size="14px" color="#002855"><a href="\\{{renderContext.registrant.joinUri}}" style="color: #002855;text-decoration: none">\\{{renderContext.registrant.joinUri}}</a></mj-text>
        <mj-text padding="24px 0" line-height="22px" font-family="Helvetica" font-size="14px" color="#464B59">This webinar link is unique to you. Please don't share it or forward this mail.</mj-text>
      </mj-column>
    </mj-section>

    <mj-raw>
      
    </mj-raw>
    <mj-section css-class="email-section-3" padding="26px 16px" background-url="">
      <mj-column css-class="email-col-1" width="44px">
        <mj-image padding="0" border-radius="44px" width="44px" height="44px" src="{{renderContext.webinarInfo.host.avatarUrl}}"></mj-image>
      </mj-column>
      <mj-column css-class="email-col-2" width="325px">
        <mj-text css-class="email-text-2" padding="0 0 0 14px" line-height="22px" font-size="15px" font-family="Helvetica" color="#16181D" font-weight="600">{{renderContext.webinarInfo.host.firstName}} {{renderContext.webinarInfo.host.lastName}}</mj-text>
        <mj-text css-class="email-text-2" padding="0 0 0 14px" line-height="24px" font-size="16px" font-family="Helvetica" color="#16181D">{{renderContext.webinarInfo.host.jobTitle}}</mj-text>
      </mj-column>
      <mj-column css-class="email-col-3" width="85px">
        <mj-text css-class="email-text-3" align="right" padding="0" line-height="28px" font-size="14px" font-family="Helvetica" color="#464B59">Webinar Host</mj-text>
      </mj-column>
    </mj-section>
  </mj-wrapper>

  <mj-wrapper css-class="email-wrapper-4" border-left="1px solid #E8E9ED" border-right="1px solid #E8E9ED" border-bottom="1px solid #E8E9ED" padding="0px 70px">
    <mj-section css-class="email-cancel-section" padding="32px 40px 24px">
      <mj-column>
        <mj-text font-family="Helvetica" color="#464B59" line-height="22px" padding="0">You can <a href="\\{{renderContext.registrant.cancellationUri}}" style="color: #012764">cancel</a> your registration if you can’t make it. </mj-text>
      </mj-column>
    </mj-section>
    
    <mj-section padding="0">
      <mj-column>
   		 <mj-divider css-class="email-divider-1" padding="0" border-width="1px" border-style="solid" border-color="#E8E9ED" width="540px"/>
      </mj-column>
    </mj-section>

    <mj-raw>
      
    </mj-raw>
    <mj-section padding="0">
      <mj-column>
   		 <mj-divider css-class="email-divider-1" padding="0" border-width="1px" border-style="solid" border-color="#E8E9ED" width="540px"/>
      </mj-column>
    </mj-section>

    <mj-section padding="8px 0 16px">
      <mj-column>
        <mj-text css-class="email-footer" font-family="Helvetica" align="center" line-height="17px" color="#464B59" font-size="12px">{{{renderContext.brandInfo.emailFooter}}}</mj-text>
      </mj-column>
    </mj-section>
  </mj-wrapper>
  </mj-body>
</mjml>`
**To Reproduce**
1. Media query doesn't work in mobile.
2. The whole <mj-style> label doesn't work in mobile.

**Comment by iRyusa** [comment]
If it doesn't work maybe the client you target doesn't support media
queries ?

There's too few information to reproduce here... You can paste your
template here if you want https://mjml.io/try-it-live

**Comment by SophieZhao5219** [comment]
Thank you very much. I put a demo here. https://mjml.io/try-it-live/PoSYzzYXU

**Comment by iRyusa** [comment]
In what Email Client it doesn't work ? If it doesn't support media query then there's nothing MJML can do here

**Comment by SophieZhao5219** [comment]
It's working well in apple mail and outlook. It doesn't work in some Chinese email clients. We don't need to consider the second situation. Thank you! You are very responsive.^^.

**Comment by iRyusa** [comment]
👍  It probably strips out media queries, it's best to go mobile first to ensure it's applied everywhere as most emails are now seen on mobile

I'm closing then !
