### ISSUE TITLE
Support using mj-class on tags inside mj-attributes

### ISSUE THREAD

**Issue by caseyjhol** [mjmlio/mjml#2467]
**Is your feature request related to a problem? Please describe.**
It would be great if it was possible use `mj-class` on tags inside `mj-attributes`.

Example: https://mjml.io/try-it-live/HCMtg2yBq.

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-class name="green" color="green" />
      <mj-text mj-class="green" font-size="24px" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

 I would expect the "Hello world" text to be green; instead it remains black.

**Describe the solution you'd like**
Attributes defined on `mj-class` should get carried over to tags that use that `mj-class` inside `mj-attributes`.

**Comment by iRyusa** [comment]
I don't think this is something we can do now as it could break order of priority for attributes

**Comment by caseyjhol** [comment]
It seems like priority should be somewhat straightforward, no? Apply just like CSS styles. `mj-attributes` set directly on the component would get priority over `mj-attributes` set via `mj-class`.

**Comment by calebickler** [comment]
Would like to see this too
