### ISSUE TITLE
How to preserve the line breaks coming from a html <textarea>? 

### ISSUE THREAD

**Issue by yannxaver** [mjmlio/mjml#2473]
Let's assume this template: `<mj-text>{{ body }}</mj-text>`
The content for `{{ body }}` is coming from a html `<textarea>` tag and can include line breaks. 

How can I preserve the line breaks after it is passed to `{{ body }}`? 
I considered using `white-space: pre-line` but it seems to be an illegal `mjml` attribute.

**Comment by iRyusa** [comment]
This cannot be solved in MJML you need to transform `\n` into `br` tags
