### ISSUE TITLE
MJML should include the lang attribute on an element inside the body

### ISSUE THREAD

**Issue by avigoldman** [mjmlio/mjml#2475]
**Describe the bug**

Email clients will often remove the <html> element so it’s recommended for accessibility purposes to include it inside the content as well.

**To Reproduce**
```
<mjml lang="en">
  <mj-head>
    <mj-title>hello world</mj-title>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          <h1>hello world</h1>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

The output of this code only includes the `lang` attribute on the `<html>` tag

**Expected behavior**
It should probably be included on the wrapping element inside the `<body>`

**MJML environment (please complete the following information):**
 - Parcel

**Email sending environment(for rendering issues)**:
 N/A

**Affected email clients (for rendering issues):**
- Gmail

**Screenshots**
https://www.loom.com/share/8f9057aceb78408b896b5758c8de99e9

**Comment by M-J-Robbins** [comment]
Just a quick note, this also applies to the `dir` attribute.

**Comment by iRyusa** [comment]
#2476 should take care of both issue.

I'll see if I can push it to NPM monday

**Comment by iRyusa** [comment]
I can publish on npm again ... yay 2 months later 😬 

But at least it's in 4.13.0
