### ISSUE TITLE
Different results from mjml cli command and "copy HTML" GUI

### ISSUE THREAD

**Issue by ms92ita** [mjmlio/mjml#2480]
Hi to all,
I am using the mjml cli commands to export a template in an HTML file with this command:

.\mjml -m "pathtomjmlfile" -o "pathtohtmlfile"

But when I use the button "Copy HTML" from the GUI interface the result is a bit different.
In this moment I must use the GUI functionality because the template from CLI is broken (I am using dotliquid markup), but I have many templates from that I must generate html templates.

**Comment by iRyusa** [comment]
Really hard to help you with so few information.

I guess you're referring to MJML App, so both might use different version of MJML and different option to compile the template.
