### ISSUE TITLE
MJML.io API is down this morning

### ISSUE THREAD

**Issue by edwardsides** [mjmlio/mjml#2483]
**Describe the bug**
API call returns Server error: `POST https://api.mjml.io/v1/render` resulted in a `500 Internal Server Error` response: {"message":"An unknown error occurred","request_id":"81e6982c-f80c-4dd9-9b39-ce955a2191fa","started_at":"2022-06-15T15:3 (truncated...)

**To Reproduce**
Use the API as normal

**Expected behavior**
Render the MJML as HTML email

**MJML environment (please complete the following information):**
Any - Ubuntu/Windows10/PHP

**Email sending environment(for rendering issues)**:
n/a

**Affected email clients (for rendering issues):**
n/a

**Screenshots**
https://share.getcloudapp.com/YEukoORE

**Additional context**

**Comment by aabanaag** [comment]
Same issue, Tried generating a new App ID, Secret Key and Public Key but no luck.

`RuntimeError: MJML compile error (via MJML HTTP server): [code=500, request_id=6b124209-ff40-4243-8fb3-620d9afbdc56] An unknown error occurred
`

**Comment by occamssafetyrazor** [comment]
Same. I thought my API account may have been blocked and tried creating a new one, but they're not sending out new keys. Might be time to spin up our own server as a backup.

**Comment by pjohnmeyer** [comment]
I tried to email support per https://mjml.io/faq and got this:

![image](https://user-images.githubusercontent.com/122016/173878970-2aa6108a-682f-4332-939b-ce524d487c2a.png)

**Comment by WebmasterClickPanda** [comment]
Hi everyone, it looks like it is working again, however would be good to host it myself to avoid this kind of issues.

Modifying my current code to use the command line commands or the node.js library would take a long time, so what I am thinking is to create a express server using this library and expose a url so I can keep using my application without major codes. 

I am going to take the time to do this probably by next week, but if anyone already did this I would apprciate the help, it would save a lot of time, thanks everyone.

To the developers creating and maintaining this code, I am really thankful for this development, if I can pay it back somehow please let me know, thank you very much

**Comment by edwardsides** [comment]
It works nearly 50% of the time at the moment.

**Comment by codyjames** [comment]
Welp, this is a bummer. I guess I'll work on removing MJML so that my client's app can continue to send emails?

**Comment by ryan-saffer** [comment]
Also experiencing this issue... it is working on some attempts, but mostly failing.

We have a lot of our automated emails built using the API... we sent over 50 emails this morning, half of which were blank.

Anyone have any ideas on how long a fix could take, if one will even come at all?

**Comment by edwardsides** [comment]
@totocap it does seem much more reliable this morning, I tried it 5 times in succession without issue.

**Comment by edwardsides** [comment]
FYI, this was reported resolved on MJML Slack, it seems to be consistent now so I am closing the issue!
