### ISSUE TITLE
renderMJML pass through component that preserves styling

### ISSUE THREAD

**Issue by pawelzebrowski** [mjmlio/mjml#2485]
I'm trying to create a wrapper component that renders child components exactly as if the wrapper component wasn't there.  That might sound silly, but I'll use it as a jump off point for other work.

I'm most of the way there with mjml-component-boilerplate and MjLayout, but no matter what i try, MjLayout seems to be stripping the styling (especially css-class).

Template
```
<mjml>
  <mj-head>
    <mj-style inline="inline">
      .test {
        background-color: red;
        border: 6px solid green;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text css-class="test">Upper</mj-text>
        <mj-layout>
          <mj-text css-class="test">Lower</mj-text>
        </mj-layout>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

MjLayout render()
```
render() {
  return this.renderMJML(
    this.renderChildren(this.props.children, {
      rawXML: true,
      renderer: (component) => component.render,
    }),
  )
}
```

and resulting html:
```
<table border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%">
  <tr>
    <td align="left" class="test" style="background-color: red; border: 6px solid green; font-size: 0px; padding: 10px 25px; word-break: break-word;" bgcolor="red">
      <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Upper</div>
    </td>
  </tr>
    
  <tr>
    <td style="font-size:0px;word-break:break-word;">
      <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Lower</div>
    </td>
  </tr>
</table>
```

The upper `td` has the styles applied correctly, the lower one doesn't.  Is what i'm trying to do possible with MJML components?

**Comment by iRyusa** [comment]
Well most element inside column does support `padding`/`css-class` but it's applied by the column when it wraps everything inside a `tr/td`. So your `mj-layout` can receive `css-class`, but every component inside it won't.

**Comment by faridsaud** [comment]
@iRyusa care to elaborate? I'm trying to create a component that use mj-text but indeed padding and the class are missing. Other attributes seems to work.

**Comment by iRyusa** [comment]
Padding and css class are inherited from being children of mj-column element. Look at how column render children if you want more detailsOn 25 Sep 2023, at 17:47, Farid Saud ***@***.***> wrote:﻿
@iRyusa care to elaborate? I'm trying to create a component that use mj-text but indeed padding and the class are missing. Other attributes seems to work.

**Comment by faridsaud** [comment]
@iRyusa thanks. QQ, in my case I'm trying to create a basic component, but when I do:

```
  render() {
    return this.renderMJML(`
            <mj-text css-class="abc" padding-bottom="20px">
              ${this.getContent()}
            </mj-text>
        `);
  }
```
padding and css-class are ignored, is there a way to keep them?

**Comment by iRyusa** [comment]
Just pass those into your current component as attribute and you’ll be fine On 25 Sep 2023, at 17:58, Farid Saud ***@***.***> wrote:﻿
@iRyusa thanks. QQ, in my case I'm trying to create a basic component, but when I do:
  render() {
    return this.renderMJML(`
            <mj-text css-class="abc" padding-bottom="20px">
              ${this.getContent()}
            </mj-text>
        `);
  }

padding and css-class are ignored, is there a way to keep them?
