### ISSUE TITLE
when i pass a json object to the api show this error

### ISSUE THREAD

**Issue by gVelezCasas** [mjmlio/mjml#2488]
**Describe the bug**
the bug is when i pass a json object to the api it says to me that the MJML cannot be empty

**To Reproduce**
1. use postman to handle the petition
2. paste the json object 
3. send the request
4. MJML cannot be empty

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version last version of the api V1
 - MJML tool used [api]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [no plattaform used]  

**Affected email clients (for rendering issues):**
 - Email Client [none] 
 - OS: [none]
 - Browser [none]

**Screenshots**
![image](https://user-images.githubusercontent.com/94134836/175794162-9aa29e1c-d958-4b3b-92c3-9f33f13519f4.png)

**Additional context**
down below is the json that i am using 
{
	"tagName": "mjml",
	"attributes": {},
	"children": [{
		"tagName": "mj-body",
		"attributes": {},
		"children": [{
			"tagName": "mj-section",
			"attributes": {},
			"children": [{
				"tagName": "mj-column",
				"attributes": {},
				"children": [{
						"tagName": "mj-image",
						"attributes": {
							"width": "100px",
							"src": "/assets/img/logo-small.png"
						}
					},
					{
						"tagName": "mj-divider",
						"attributes": {
							"border-color": "#F46E43"
						}
					},
					{
						"tagName": "mj-text",
						"attributes": {
							"font-size": "20px",
							"color": "#F45E43",
							"font-family": "Helvetica"
						},
						"content": "Hello World"
					}
				]
			}]
		}]
	}]
}

**Comment by iRyusa** [comment]
As the doc says,  you should send a JSON object with `mjml` property and pass XML/JSON as string https://mjml.io/api/documentation/#tag-render
