### ISSUE TITLE
Missing css-class and <mj-style>  in Outlook web

### ISSUE THREAD

**Issue by SophieZhao5219** [mjmlio/mjml#2491]
**Describe the bug**
Missing css-class and <mj-style> styles in Outlook web when the emails are folded and opened again if they came from the same email address

**To Reproduce**
1. Send a email developed with MIJML with css-class attributes and <mj-style> styles. It works fine in Outlook web.
2. Send another email developed with the same MJML file. The "from" and "to" email addresses are the same with the first email. 
3. The two emails in Outlook will be folded since that they come from the same email address.
4. If you open the emails again, they will all lose the styles which are coded in css-class attributes and <mj-style> tag. They look buggy.

**Expected behavior**
All the emails can have show the <mj-style> styles.

**Affected email clients (for rendering issues):**
 - Email Client:  Outlook web
 - OS: MacOS
 - Browser:  Google Chrome

**The demo code link:**
https://mjml.io/try-it-live/PoSYzzYXU

Please help check. I'm confused and have no idea about the root cause. Missing styles issue also appears when I forward the emails and preview them in Outlook web.

**Screenshots**
<img width="473" alt="Screen Shot 2022-06-30 at 3 16 35 PM" src="https://user-images.githubusercontent.com/104306468/176623752-c684425b-b658-4076-b7f7-37e3d5f940a7.png">
<img width="986" alt="Screen Shot 2022-06-30 at 3 17 39 PM" src="https://user-images.githubusercontent.com/104306468/176623776-706ba9a2-6435-420b-a95f-1ccc2f0a4eb9.png">
<img width="467" alt="Screen Shot 2022-06-30 at 3 17 57 PM" src="https://user-images.githubusercontent.com/104306468/176623787-de5a05cb-3360-414b-8707-fb6c68f9c72b.png">

**Comment by iRyusa** [comment]
Forwarding the email will remove headstyle so resulting email to be shown as on mobile.

For this specific issue I guess it's an issue within outlook itself and there's no way to prevent this behavior as it might alter the HTML.

I'm closing as there's not so much that can be done on this.
