### ISSUE TITLE
Attribute "position" is illegal: position="file-start"

### ISSUE THREAD

**Issue by 334rashad** [mjmlio/mjml#2495]
Hello, according to the documentation when trying to add raw text before <!doctype html> we should use attribute position="file-start. The following part is from the documentation:
"One more possible use of mj-raw is to add text at the beginning of the generated html, before the <!doctype html> line. For this you need to : - put the mj-raw inside the <mjml> tag, outside of mj-head and mj-body - add this attribute on this mj-raw : position="file-start"."

But when trying to use "position="file-start" in mj-raw tag like this it gives mistake: Attribute "position" is illegal:
<mj-raw position="file-start">This will be added at the beginning of the file</mj-raw> 

![Screenshot from 2022-07-01 17-47-03](https://user-images.githubusercontent.com/32520427/176928879-8229e29a-504a-4de5-b276-73154ce0196a.png)

![Screenshot from 2022-07-01 17-47-19](https://user-images.githubusercontent.com/32520427/176928928-efc976b1-c4eb-40ae-9972-70e406bd7b32.png)

I was reading similar similar issue topic which was closed and seems that this issue was solved in that topic, but attribute "position" doesn't work:  Output raw text before <!doctype> #2146  -> https://github.com/mjmlio/mjml/issues/2146

**Comment by iRyusa** [comment]
If you're using the MJML app I'm not sure it's on latest version so that's why

**Comment by 334rashad** [comment]
Yes, I was using the MJML online editor. The installation of the latest version solved the problem. Thank you.
