### ISSUE TITLE
Background Image not shown in Outlook

### ISSUE THREAD

**Issue by codyng** [mjmlio/mjml#2497]
Hello,

I found that the background is not shown in Outlook.

I've found this article but I don't know anything about "Vector Markup Language":
https://www.emailonacid.com/blog/article/email-development/emailology_vector_markup_language_and_backgrounds/

Will the future version of Mjml solve this issue??

**Comment by iRyusa** [comment]
We already use VML for background image.

Can you add some details : how did you send your email, which version of MJML you're using and a screenshot of the issue?
