### ISSUE TITLE
Raw rendering not working on some JS code or tags

### ISSUE THREAD

**Issue by stepanh** [mjmlio/mjml#25]
We'd like to integrate MJML with EJS. It seems more efficient to generate HTML from MJML only once and then let EJS put in any dynamic text - rather than generating HTML from MJML for every single email.

I thought that using mj-raw component should let us embed EJS code - but it doesn't get rendered properly, i.e.:
`<mj-raw><% if (undefined) {} %></mj-raw>`
renders as
```
<!--[if mso]>
                <table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;"><tr><td>
                <![endif]--><% if="" (undefined)="" {}="" %=""></%><!--[if mso]>
                </td></tr></table>
                <![endif]-->
```

Two issues here:
1. The input renders corrupted (using `&lt; &gt;` etc. doesn't help)
2. It is wrapped in the 'mso' table - maybe this could be optional?

**Comment by iRyusa** [comment]
Hello,

This is a bug, `mj-raw`, shouldn't parse anything in it's node. I'm looking into it,  i'll keep you updated.

The mso table ensure that outlook will have a centered 600px table rendered from `mj-body` so it's not really optional

**Comment by iRyusa** [comment]
I'm sorry @stepanh I don't think i'll have a fix for today. 

We have an issue with a dependencies lib called cheerio that rely on htmlparser2. Htmlparser2 is parsing your `mj-raw`'s content as a tag so that's why you get that weird render.

I try to play with htmlparser2 to seed if I can find a quick workaround

**Comment by stepanh** [comment]
Thanks, @iRyusa !

**Comment by iRyusa** [comment]
@stepanh sorry for the delay, this was harder than I thought.

Next version of MJML will now correctly render `<mj-raw><% if (undefined) {} %></mj-raw>` ! I'll keep you updated tomorrow.

**Comment by techdragon** [comment]
I just ran into this issue trying to render handlebars template markup into some mjml output.

**Comment by iRyusa** [comment]
@techdragon it's merged on master, will be released it asap sorry for the  delay

**Comment by jmpp** [comment]
Having the same problem with <mj-raw> and PHP tags, I silentely followed this issue.

Recent merge solved the problem for me, my PHP tags are now well-preserved inside a <mj-raw>

A big thank you for this fix @iRyusa ! Also for making email development fun again ;)

**Comment by techdragon** [comment]
We still have incorrect rendering problems for mj-raw in beta8... I'm tempted to say they are worse now, since its generating asymmetrical tags that will really screw up rendering in IE. It looks like the end table tag is actually slipping down to before the next raw element. 

```html
<mj-raw>
{{#if advert_1}}
{{#with advert_1}}
</mj-raw>
<mj-section padding-bottom="5" padding-top="5px">
	<mj-column><mj-image href='{{link_url}}' src='{{image_url}}'></mj-image></mj-column>
</mj-section>
<mj-raw>
{{/with}}
{{/if}}
</mj-raw>
```

Turns into 
```html
<!--[if mso]>
<table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;"><tr><td>
  <![endif]-->
  {{#if advert_1}}
  {{#with advert_1}}
  <div style="margin:0 auto;max-width:600px;"><table cellpadding="0" cellspacing="0" style="font-size:0;width:100%;" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;font-size:0;padding:20px 0;padding-bottom:5px;padding-top:5px;"><!--[if mso]>
    <table border="0" cellpadding="0" cellspacing="0"><tr><td style="vertical-align:top;width:600px;">
      <![endif]--><div aria-labelledby="mj-column-per-100" class="mj-column-per-100" style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;width:100%;"><table cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="font-size:0;padding:10px 25px;" align="center"><table cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px;" align="center" border="0"><tbody><tr><td><a href="{{link_url}}" target="_blank"><img alt="" src="{{image_url}}" style="border:none;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="550" height="auto"></a></td></tr></tbody></table></td></tr></tbody></table></div><!--[if mso]>
    </td></tr></table>
  <![endif]--></td></tr></tbody></table></div><!--[if mso]>
</td></tr></table>
<![endif]-->
<!--[if mso]>
<table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;"><tr><td>
  <![endif]-->
  {{/with}}
  {{/if}}
```

**Comment by iRyusa** [comment]
@techdragon that looks good to me on branch 1.3-beta : 

![capture d ecran 2016-03-14 a 10 50 27](https://cloud.githubusercontent.com/assets/570317/13740742/9806dcae-e9d2-11e5-9a0d-4ea2cd824842.png)

In red body table
In orange raw tags that wrap a section
In blue section + column 
In green mj-image

**Comment by techdragon** [comment]
Then I may have misread the logic that constructed the table. It seemed that the opening and closing `[if-mso]` comment/tags were generated 'around content', not 'inside containers'. So, using your colours for reference, the orange portion, would belong 'outside' the `[if-mso]` segments that are in red.

I could be wrong about the order of nesting however, since all the convoluted table nesting that goes on in an email can make it extremely hard to keep track. Hopefully this comment clears up the question of what I think may still be broken.

**Comment by iRyusa** [comment]
Problem is there's many case and we have to deal with :
```
<mj-body>
 <mj-raw>if test</mj-raw>
    <mj-section ...Content />
 <mj-raw>end iff</mj-raw>
    <mj-section ...Content />
</mj-body>
```

Imagine this scenario, if mso's conditional tags was after the `if test` from `mj-raw`, the mso structure will not be applied and will completely fail on outlook.

MJML is a markup langage with no logic, you should use a preprocessor before using MJML for this kind of case.

`Mj-raw` is a workaround for some cases but it's not here to fulfill a preprocessor role

**Comment by iRyusa** [comment]
Closing this, now behave as expected on 1.3.
