### ISSUE TITLE
Aligning issues on multiple mail clients

### ISSUE THREAD

**Issue by lRlevolution** [mjmlio/mjml#250]
Hi everyone. I'm having issues with elements aligning to the left instead of center since updating MJML. So far the issue is happening on Yahoo, iOS Safari Gmail and gmail app android. 

This is my MJML Code that before updating has worked with no issues but now displays incorrectly:
```
<mjml>
 <mj-body>

<!-- NEWSLETTER BODY -->
   <mj-container background-color="white" width="600px">

   <!-- FEATURED PRODUCT -->
       <mj-section padding-bottom="15px" padding-top="0px" padding-left="0px" padding-right="0px" background-color="#ffffff "  vertical-align="middle" text-align="center">
           <mj-column background-color="#FFFFFF " width="100%">

           <!-- FEATURED PRODUCT IMAGE -->
               <mj-image align="center" padding-bottom="0px" padding-top="0px"  padding-left="0px" padding-right="0px"  
               src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_05_12_good_dinosaur/Featured.jpg" href="https://www.#.com" alt="New Release! The Good Dinosaur $5 Digital Movie Download">
               </mj-image>

           <!-- FEATURED PRODUCT DESCRIPTION -->
               <mj-text align="center" color="#666666 " font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="17px" font-weight="400" line-height="23px" padding-left="25px" padding-right="25px" padding-bottom="20px" padding-top="20px">
                 <p style="margin:0px auto 5px !important; color:#666666 !important; font-weight:400; letter-spacing:0.02em !important; font-size:17px; max-width:450px;">Arlo and Spot are here! Join them in a thrilling adventure filled with major dino attitude. Grab your download now and watch it wherever and whenever—it’s yours forever!</p>
               </mj-text>

           <!-- FEATURED BUTTON -->
               <mj-button background-color="#4ca23a " color="#FFFFFF " font-size="16px" align="center" vertical-align="middle" border="none" padding="15px 30px" border-radius="0px" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" href="https://www.#.com" padding-left="25" padding-right="25" padding-bottom="0" padding-top="10">
               SHOP NOW
               </mj-button>
           </mj-column>
       </mj-section>
       
   </mj-container>
 </mj-body>
</mjml>
```

If it helps this is the outputted HTML of the old **WORKING** version to compare to the top version (once outputted)

`<div style="margin:0 auto;max-width:600px;background:#ffffff;"><table cellpadding="0" cellspacing="0" style="font-size:1px;width:100%;background:#ffffff;" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:middle;font-size:1px;padding:20px 0px;padding-bottom:15px;padding-left:0px;padding-right:0px;padding-top:0px;"><div aria-labelledby="mj-column-per-100" class="mj-column-per-100" style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;width:100%;"><table cellpadding="0" cellspacing="0" style="background:#FFFFFF;" width="100%" border="0"><tbody><tr><td style="word-break:break-word;font-size:1px;padding:10px 25px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;text-align:center;"><table cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px;" align="center" border="0"><tbody><tr><td style="width:600px;"><a href="https://www.#.com" target="_blank"><img alt="New Release! The Good Dinosaur $5 Digital Movie Download" height="auto" src="http://hosting-source.bm23.com/35647/public/newsletters/2016/2016_05_12_good_dinosaur/Featured.jpg" style="border:none;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="600"></a></td></tr></tbody></table></td></tr><tr><td style="word-break:break-word;font-size:1px;padding:10px 25px;padding-top:20px;padding-bottom:20px;padding-right:25px;padding-left:25px;text-align:center;"><div style="cursor:auto;color:#666666;font-family:&#x27;Helvetica Neue&#x27;, Helvetica, Arial, sans-serif;font-size:17px;font-weight:400;line-height:23px;">
                  <p style="margin:0px auto 5px !important; color:#666666 !important; font-weight:400; letter-spacing:0.02em !important; font-size:17px; max-width:450px;">Arlo and Spot are here! Join them in a thrilling adventure filled with major dino attitude. Grab your download now and watch it wherever and whenever—it’s yours forever!</p>
                </div></td></tr><tr><td style="word-break:break-word;font-size:1px;padding:15px 30px;padding-top:10px;padding-bottom:0px;padding-right:25px;padding-left:25px;text-align:center;"><table cellpadding="0" cellspacing="0" style="border:none;border-radius:0px;" align="center" border="0"><tbody><tr><td style="background:#4ca23a;border-radius:0px;color:#FFFFFF;cursor:auto;" align="center" valign="middle" bgcolor="#4ca23a"><a href="https://www.#.com" style="display:inline-block;text-decoration:none;background:#4ca23a;border:1px solid #4ca23a;border-radius:0px;color:#FFFFFF;font-family:&#x27;Helvetica Neue&#x27;, Helvetica, Arial, sans-serif;font-size:16px;font-weight:normal;padding:15px 30px;" target="_blank">
                SHOP NOW
                </a></td></tr></tbody></table></td></tr></tbody></table></div></td></tr></tbody></table></div>`

**Comment by iRyusa** [comment]
Hi @lRlevolution 

Everything looks good on Android Gmail on Litmus. Safari Gmail isn't really tested on MJML so I don't know if it's the same issue with Yahoo.

However alignement in Yahoo is broken, can you check #231 ?

**Comment by iRyusa** [comment]
Closing this one, @lRlevolution I think this is solved, feel free to reopen if it's not
