### ISSUE TITLE
Litmus fallback font issue

### ISSUE THREAD

**Issue by DanaIntouch** [mjmlio/mjml#2501]
I've read through the old issues. It led me to try my test in EOA.

And, no, this does not happen in EOA.

Can we get confirmation that this is a Litmus issue and not mjml issue?

I don't understand why it would happen but here we are.

**Comment by iRyusa** [comment]
Can relate this doesn't happen on EOA but on Litmus yep. Can't reproduce on a real client. Might be Litmus injecting something that break our code.
