### ISSUE TITLE
mj-column is showing in a row on Yahoo

### ISSUE THREAD

**Issue by jonystn** [mjmlio/mjml#2503]
Hello, I just start to use MJML for mailings and I came across an issue when I test the HTML auto-generated and test on Litmus it shows the <mj-column> for some desktop clients like Yahoo and AOL in a row. 
Below you can see the code and the screenshot. Is there any way to fix it? 

[https://mjml.io/try-it-live/AFdZoYgKF](https://mjml.io/try-it-live/AFdZoYgKF)

![image](https://user-images.githubusercontent.com/42983825/179784877-2be0cf65-3a13-455b-aa1e-9e8cc3202956.png)
![image](https://user-images.githubusercontent.com/42983825/179785004-0f5af92e-ae55-4c07-a7d0-01c810917283.png)

Thank you.

**Comment by sinh117801** [comment]
@jonystn - how about add `width="100%"` on each `mj-column`.

**Comment by iRyusa** [comment]
If I remember correctly it does shows up as mobile on firefox for Yahoo but not on Chrome. I don't know if it's only an issue in  Litmus or a real issue

**Comment by iRyusa** [comment]
Can't really reproduce on EmailOnAcid that might be only an issue with Firefox on Yahoo with Litmus, i'm closing
