### ISSUE TITLE
Changing column alignment on mobile

### ISSUE THREAD

**Issue by bronze** [mjmlio/mjml#2506]
**Describe the bug**
I cant seem to change the text alignment on resizing.
My exports all contain an `align="center"` and firefox inspector just warns me thats an invalid property name.
Trying to change the alignment through `text-align` also puts everything on left alignment.

**To Reproduce**
https://mjml.io/try-it-live/BFc-xK0Br

**Expected behavior**
To change the alignment on mobile

any tips?

**Comment by iRyusa** [comment]
You need to use a deeper css selector here as it won't be inherited like that.

**Comment by bronze** [comment]
@iRyusa you are right. i was messing up. This works: https://mjml.io/try-it-live/ycpPi9AOc
