### ISSUE TITLE
mj-button going left aligned in Yahoo mail

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#251]
This is the code I'm using

```
            <mj-section background-color="#ffffff" padding-top="0">
                <mj-column>
                   <mj-button align="center" line-height="18" font-size="14" font-family="AvenirNext-DemiBold,sans-serif;" border-radius="4" color="#ffffff" background-color="#72ba8a">
                    <span style="letter-spacing: 0.8px;">
                    My button</span>
                    </mj-button>
                </mj-column>
            </mj-section>
```

**Comment by iRyusa** [comment]
Hi,

Related to #231 closing this one

**Comment by jitendravyas** [comment]
The related issue is related to an image. I'm not sure if solution for both could be the exact same/

**Comment by iRyusa** [comment]
`image/button/...` are column element, I'm updating the issue's title to reflect this

**Comment by trisrael** [comment]
This is still happening to me using MJML 4.
Does not seem to matter whether I add `text-align: center` on `mj-section` 
OR
add `align="center"` to `mj-button`

In both cases, the button continues to be left aligned.

Example:
```
<mj-section mj-class="section-content" padding="15px 0 0 0">
  <mj-column mj-class="column-content">
    <mj-button align="center" mj-class="button-primary" href="{{links.aLink}}">
       An employee needs to be be excluded
    </mj-button>
  </mj-column>
</mj-section>
```

**Comment by ngarnier** [comment]
@trisrael, how do you send your emails? 

This is very likely an issue with your sending platform altering the HTML. Please try sending with https://putsmail.com/ and see if the problem persits.

Email on Acid test of your snippet: https://www.emailonacid.com/app/acidtest/JsuaE9apvIltQtWidGSYrPHTpDRtuuBdQyD9HpTRPUPL7/list
