### ISSUE TITLE
Uncaught Exception: Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by brianfidler** [mjmlio/mjml#2515]
**Describe the bug**
When launching the MJML app on OS X, I get the following error:

> **A JavaScript error occurred in the main process**
> 
> Uncaught Exception:
> Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE

**To Reproduce**
1. This occurs every time I launch MJML on MacBook Pro (16-inch, 2019) running Catalina (10.15.7)

**Expected behavior**
I expect the application to launch with any errors. To be clear, if I hit the OK button when the launch prompts me with that error, I can still use the application, but the error does cause me to lose confidence in the app.

**MJML environment (please complete the following information):**
 - OS: Catalina (10.15.7)
 - MJML Version: 4.8.1
 - MJML tool used: MJML App v3.0.3

**Screenshots**
<img width="448" alt="image" src="https://user-images.githubusercontent.com/77189/182970859-7c332c50-ca59-4321-a2db-ddcee1f98f6f.png">

**Comment by iRyusa** [comment]
Please post this in https://github.com/mjmlio/mjml-app instead. If you have a firewall it might be the auto-update feature blocked on your side
