### ISSUE TITLE
Config to opt-out specific email client support to reduce HTML output size.

### ISSUE THREAD

**Issue by balatvm** [mjmlio/mjml#2516]
MJML is a nice library.

But, It would be great if MJML compiler improves in below areas.

 1) Compilation time
 2) HTML Output size

This request is specific to HTML output size. 
 Is it possible to provide a configurable option to opt-out specific email clients support?  
 So that MJML compiler won't inject those email client related poly-fills/ css. 
 Or any other size improvement can be done in HTML size if we can optionally opt-out specific email client support?  say IE support.

**Comment by iRyusa** [comment]
Compilation time a reasonable if you're using a watch mode, if you spawn a node process for each render then it will be slow for sure but there's not so much that can be done here.

For HTML Output size, if you find some optimization feel free to post them as we can try to implement them. We already merge outlook comment, inline as much as we can.

> Is it possible to provide a configurable option to opt-out specific email clients support?

Way too hard to do and maintain
