### ISSUE TITLE
mjml 4.13.0 doesn't appear on the release page

### ISSUE THREAD

**Issue by tdelmas** [mjmlio/mjml#2521]
The 4.13.0 release has a tag and is visible on https://www.npmjs.com/package/mjml but doesn't appear on the https://github.com/mjmlio/mjml/releases page (last one to appear is 4.12.00)

![image](https://user-images.githubusercontent.com/1955774/185570532-9f417c0c-4c6d-4b4a-bd6b-2872ea430ddf.png)

**Comment by iRyusa** [comment]
Fixed 👍

**Comment by tdelmas** [comment]
Perfect :tada:
