### ISSUE TITLE
ESLint or something similar when building email templates with MJML

### ISSUE THREAD

**Issue by dominicarrojado** [mjmlio/mjml#2523]
**Is your feature request related to a problem? Please describe.**
It would be good to have an ESLint or equivalent when building email templates with MJML. Sometimes I have a styles or classes that's not being used in the code, if there is then I get rid of them in the code. Also if there's a violation where I accidentally use an mjml component inside another component where not allowed, then we can throw an error in the build script or as a part of a PR check.

**Describe the solution you'd like**
It there's an ESLint or equivalent, then we should get some inline errors if there's unused style or class within the code. Or it will throw an error on the mjml build node script.

**Comment by iRyusa** [comment]
We already have a linter that check few things but we can't go as far as dead css code. Most code editor extension will output those errors.

**Comment by dominicarrojado** [comment]
Dead css aside, can we the `mjml` node script throw an error if say we use `mjml-button` inside the `mjml-text` or other similar violation?

**Comment by iRyusa** [comment]
it works for few tags, but not for ending tags (ex: mj-text) as the parser let you put anything you want in ending tags. You have a `validationLevel` option you can set to `strict` to throw error.

**Comment by dominicarrojado** [comment]
@iRyusa I tried that but that doesn't seem to throw an error:

```json\
    "start": "mjml --watch \"src/index.mjml\" --output \"src/index.html\" --validationLevel=strict"
```

![image](https://user-images.githubusercontent.com/6789191/186069702-8dbaf211-3e15-4e12-9a7b-502a14a9d886.png)

No error on the terminal.

**Comment by iRyusa** [comment]
I think it's `config.validationLevel` instead to pass down  config into mjml2html function from the cli
