### ISSUE TITLE
Border of mj-section doesn't use the border-radius

### ISSUE THREAD

**Issue by toto1384** [mjmlio/mjml#2529]
**Describe the bug**
If you set the border radius in mj-section and then a border of 1 px, the background color is rounded, but not the border

**To Reproduce**
\<mj-section backgroundColor='#C8C9CA' border='solid 1px' borderRadius={10}\>

**Expected behavior**
The border should use the border radius

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.13.0
 - MJML tool used Mjml React

**Email sending environment(for rendering issues)**:
<div dangerouslySetHtml={{__html: mjmlStringCode}}>

**Screenshots**
<img width="57" alt="Screenshot 2022-08-26 at 16 04 02" src="https://user-images.githubusercontent.com/35605914/186909772-ffb92b16-e9c0-4e34-92e8-a28579e96f96.png">

**Comment by iRyusa** [comment]
This is a limitation because of the use of border-collapse as it's incompatible with border-radius.

What you can do is target the table to set border-collapse to separate and apply the radius on the `td` with a css-class.

**Comment by toto1384** [comment]
Thanks for the response but can you share a response with code?

**Comment by iRyusa** [comment]
Here https://mjml.io/try-it-live/x4mYo2A57

**Comment by felipe-muner** [comment]
I followed it and thanks for that.
