### ISSUE TITLE
[Solved] Add <tr>, <td> inside <mj-raw> if you keep a <table> inside it

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#253]
Just documenting here so other people can know about it.

I was facing this problem of getting some `<mj-section>` outiside the main container in **HTML** output
![image](https://cloud.githubusercontent.com/assets/77309/15267124/8a34213e-19d6-11e6-91e0-37750c8f58a5.png)

And because of that this white (left and right) space was coming in some email clients.
![image](https://cloud.githubusercontent.com/assets/77309/15267149/f96b27c8-19d6-11e6-95b7-24f9a600e1b4.png)

Thanks to @iRyusa who helped me to solve this problem on slack. 

I was using a `<table>` inside `<mj-raw>` which was causing the problem.

I had to add `tr>td` inside `<mj-raw>` to solve this issue

```
<mj-raw>
    <tr>
        <td>
            <table align="center" width="240" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td align="left" width="80"> <a href="#">Our blog</a></td>
                </tr>
            </table>
        </td>
    </tr>
</mj-raw>

```

**Comment by iRyusa** [comment]
So I'm closing it if it's solved

**Comment by KeironLowe92** [comment]
Maybe this could be mentioned within the documentation for mj-raw? There's no mention of it and i've just spent the past half hour trying to figure out what's going on before I saw this.

**Comment by iRyusa** [comment]
It's really up to you to check what the generated HTML will be when using
mj-raw, I don't think the name is ambiguous.

I don't really know what would you add to the doc.
