### ISSUE TITLE
Windows Defender flags skeleton.js as a Trojan

### ISSUE THREAD

**Issue by GhostPirateBob** [mjmlio/mjml#2531]
**Describe the bug**
Not your fault or anything but just thought you should know Windows Defender seems to flag ```packages/mjml-core/src/helpers/skeleton.js``` as a Trojan.

**To Reproduce**

1. Attempt to download ```https://codeload.github.com/mjmlio/mjml/zip/refs/heads/master``` on Windows 10 with Defender active
2. See image

**Screenshots**
![2022-08-29 10_20_21-Windows Security](https://user-images.githubusercontent.com/37704390/187113719-97e646ea-26e8-4578-ab9f-a11e26d28674.png)

**Comment by iRyusa** [comment]
Not so much we can do about this, unlucky 🤷
