### ISSUE TITLE
Columns are not mobile responsive

### ISSUE THREAD

**Issue by shubham-budhiraja-30075199** [mjmlio/mjml#2532]
Hi,
I am trying to create an email template. And in that, I have to create a two column design with one column having 70% width and the other 30%. It works fine in desktop and tablet view but the second column goes down in mobile view. Please refer the screenshots.
Thanks
![issue 1-2](https://user-images.githubusercontent.com/109502391/187409540-30abc931-ea7c-48cf-902e-155cb248b939.PNG)
![issue 1-1](https://user-images.githubusercontent.com/109502391/187409549-d97fac39-d285-489c-858d-5174b852d9b0.PNG)

**Comment by iRyusa** [comment]
This is the default behavior of mj-column. If you don't want them to stack just use mj-group.
