### ISSUE TITLE
Image.full-width does not pass validation

### ISSUE THREAD

**Issue by skybber** [mjmlio/mjml#2533]
Image.full-width does not pass validation even though the `mj-image` code uses the attribute

Reproducer:

```
<mjml>
	<mj-body>
    <mj-hero>
	    <mj-image full-width="true"></mj-image>
    </mj-hero>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
`full-width` was a tentative of having full width image in mobile in MJML4. That didn't worked as expected so it's not really a usable attribute. We need to remove it in the code as fluid-on-mobile is available
