### ISSUE TITLE
Wrong carousel.border-radius datatype

### ISSUE THREAD

**Issue by skybber** [mjmlio/mjml#2534]
It seems that

https://github.com/mjmlio/mjml/blob/master/packages/mjml-carousel/src/Carousel.js#L12

should be (as is in other components):

    borser-radius: 'unit(px,%){1,4}',

**Comment by iRyusa** [comment]
Yup feel free to open a pr about it.

**Comment by iRyusa** [comment]
👍 thanks about the PR it should be available in next version of MJML
