### ISSUE TITLE
Zimbra email showing conditional comments for if !mso

### ISSUE THREAD

**Issue by acetinick** [mjmlio/mjml#2537]
**Describe the bug**
All emails send using MJML show the conditional tags within Zimbra webclient.

**To Reproduce**
1. Sign up for free trial of Zimbra
2. Send any email using Zimbra
3. Conditional comments are showing at the top of every email

**Expected behavior**
Should not be rendered

**Affected email clients (for rendering issues):**
 - Zimbra email

**Screenshots**
![image](https://user-images.githubusercontent.com/571649/188329698-092bc8fa-cc3b-4e8c-b7b0-c7d75a70fbbb.png)

**Comment by iRyusa** [comment]
Zimbra is not in our test scope. However as you send email with it try to send it with putsmail.com instead to ensure it doesn't alter the HTML generated by MJML.
