### ISSUE TITLE
`background-url` breaks layout in Windows Mail

### ISSUE THREAD

**Issue by helios1138** [mjmlio/mjml#2539]
**Describe the bug**
When using `background-url` on an `mj-section` or `mj-wrapper`, in Windows Mail the email looks broken (collapsed to the left, no readable text)

**To Reproduce**
```mjml
<mjml>
  <mj-body>
    <mj-section full-width="full-width"
                background-url="https://i.gyazo.com/b48b12795432d97952f7dc48788c1724.png"
                background-color="blue">
      <mj-column background-color="red">
        <mj-text font-size="40px">
          This is the text
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
Background image might not be visible (I think Winodws Mail does not support them), but the layout should be preserved

**MJML environment (please complete the following information):**
 - OS: Windows 11
 - MJML Version 4.13.0

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Windows Mail

**Screenshots**
<img width="544" alt="Screenshot 2022-09-06 144009" src="https://user-images.githubusercontent.com/7106681/188626555-ac12453c-9835-4fc1-b919-0411058378d6.png">

**Comment by iRyusa** [comment]
It seems like a regression at some point as I'm sure it was just displaying the section and not the background.

We need to investigate about this 😥

**Comment by iRyusa** [comment]
This so weird as it looks to happens only with a single section in the MJML 🤔 Can you confirm ?

**Comment by helios1138** [comment]
> This so weird as it looks to happens only with a single section in the MJML 🤔 Can you confirm ?

Do you mean that if I add a second empty section it's gonna fix it? I don't have a windows machine to test it right now, I can do it a bit later

**Comment by sbjdesigns** [comment]
Did anyone find an answer to this one? I'm experiencing the same thing. Thanks!

**Comment by iRyusa** [comment]
Yup it seems if you have another section with content it will display everything properly

**Comment by iRyusa** [comment]
Can't reproduce with another section on my end, feel free to reopen if its 'not the case for you
