### ISSUE TITLE
[Feature request] Border-radius on <mj-section>

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#254]
There should be an option to add  `border-radius` to `mj-section` so we have design like this if we want

![user interface sketch fady7](https://cloud.githubusercontent.com/assets/77309/15267441/cfab6fca-19df-11e6-8e2e-a7f9600df181.jpg)

In my current project, I need to do this. Currently I need to edit html out and add this manually

`border-bottom-right-radius: 4px;border-bottom-left-radius: 4px;`

**Comment by jitendravyas** [comment]
Has anybody started working on it?

**Comment by iRyusa** [comment]
Closing this one, dup of #92

**Comment by joelaguero** [comment]
@iRyusa I think this was wrongly closed. #92 seems to be about adding borders, regardless of border-radius.

This issue, however, is exactly the thread I was hoping to find.

**Comment by iRyusa** [comment]
@joelaguero section supports border-radius & border now, please check  [https://mjml.io/documentation/#mjml-section](the documentation). 
But you cannot use them both at the same time, due to how border-collapse is working.

**Comment by joelaguero** [comment]
@iRyusa thanks for explaining that (this is why I thought it was broken, despite the documentation). That information would be really helpful to add in the documentation; it's caused me a significant amount of confusion!
