### ISSUE TITLE
Width is not rendered properly in pdf

### ISSUE THREAD

**Issue by ariefsn** [mjmlio/mjml#2540]
**Describe the bug**
Hi, I have a problem when parse the html to pdf file, its fine when I open the html in the browser.

**To Reproduce**
1. Create a file with this MJML code: https://mjml.io/try-it-live/1AQPNeJQ9
2. Render it to HTML by doing: Hit the mjml api and get the html string
3. Send the HTML to an email address with: not sending to email, but build to pdf file using python weasyprint https://weasyprint.org/
4. See error: the error is width is not rendered properly

**Expected behavior**
It can full width in pdf version.

**MJML environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - MJML Version 4.6.1
 - MJML tool used: MJML Api

**Screenshots**
- browser version
![image](https://user-images.githubusercontent.com/33569737/188820848-e4878ef2-2534-43ae-8dbd-fa4cc240e409.png)
- pdf version
![image](https://user-images.githubusercontent.com/33569737/188821144-9bf8291b-d54f-4390-a8b3-da877a43e778.png)

**Comment by iRyusa** [comment]
Email clients are already hard to handle let's not take PDF into account.
