### ISSUE TITLE
The default font-size attribute in the MJML export HTML TD tag is 0px

### ISSUE THREAD

**Issue by yizhipiju** [mjmlio/mjml#2542]
**Describe the bug**
The default font-size attribute in the MJML export HTML TD tag is 0px
![image](https://user-images.githubusercontent.com/69177163/189257316-f182ce00-3914-4600-ad6c-883c169775ec.png)

**Comment by yizhipiju** [comment]
As a result, the exported HTML becomes problematic for converting to PDF.  Do you have other ways to convert HTML to PDF?  thank you

**Comment by iRyusa** [comment]
It's a fix for some webkit-based email clients that render empty space between inline blocks. Size is reseted in the next div.
