### ISSUE TITLE
Is "full-width" never "full"?

### ISSUE THREAD

**Issue by luison** [mjmlio/mjml#2544]
Trying to create a base layout with MJML with full-width background, but I don't seem to completely understand it, or I am missing as I always get a padding what ever I do.

I would understand this code should produce a full width sections with no padding.
```
<mjml>
  <mj-body width="3000px" padding-left="0">
    <mj-section full-width="full-width" background-color="green" padding-left="0">
      <!-- Your columns go here -->
    </mj-section>

    <mj-section full-width="full-width" background-color="red" padding-left="0">
      <!-- Your columns go here -->
    </mj-section>
  </mj-body>
</mjml>
```
I've tried with a mj-wrapper but it all gets messed up when nesting sections.
Have not found any working samples of a proper "stripped" full width.

**MJML environment (please complete the following information):**
 - MJML Version 4.2.9
 - MJML App and jetBrains plugin

![Screenshot_20](https://user-images.githubusercontent.com/745632/189739589-72a90abe-a016-47a7-91ee-022255f0c23c.png)

**Comment by DanaIntouch** [comment]
Try putting padding="0px". I believe the px is required.

**Comment by iRyusa** [comment]
As your body is 3000px wide you won’t see the difference in the preview between a full width and non full width section. Try open the HTML in the browser instead as the preview iframe has some limitations.

**Comment by luison** [comment]
Thanks for prompt reply. 
This was a preview of more complex layout. I am testing it as the block content gets previewed/edited before it is sent, in case that is what is causing the additional padding.  
The code is based on this other issue that I've created separately in order not to mix subjects as that issue is image size related. https://github.com/mjmlio/mjml/issues/2545

**Comment by luison** [comment]
Part of the padding problem was truly caused by my editor prior to email delivery and viewed on the browser seems ok, sorry, but I am still stuck in how does one suppose to correctly produce a full-width email (including text body)  considering that  "full-width" is only compatible with mj-section and mj-wrapper and mj-body can't be set to 100%. 
How am I supposed to set a fluid full-width email, including the body?

**Comment by iRyusa** [comment]
Full width only affect the background not the content. Mjml only support for centered mail with a max width on the body

**Comment by luison** [comment]
> Full width only affect the background not the content. Mjml only support for centered mail with a max width on the body

I want to think that it is due to some complicated limitation of making it responsive on that situation and not only for not being the "usual". 
In my case, I was hoping for a fluid layout with a full-width bottom section on a different colour and a responsive signature/footer with two columns.  Have not found any hacks so far.

**Comment by marcin-dwornikowski** [comment]
MJML supports it, no problem:
Just add this [mj-style](https://documentation.mjml.io/#mj-style) head component into your head:
```html
    <mj-style inline="inline">
      .use-full-width {
        width: 100%;
        max-width: 100% !important;
      }
    </mj-style>
```
And then use it in combination with the css-class attribute on your mj-section component:
```html
    <mj-section css-class="use-full-width">
      <mj-column width="100%">
        <mj-text> Regards, </mj-text>
        <mj-text> Marcin Dwornikowski </mj-text>
        <mj-text> Bubble Wrap - bubblewrap.dev </mj-text>
      </mj-column>
    </mj-section>
```

Here's a ready to use footer.mjml block for you (it's a recreation of Apple Mail's footer, but with a clickable link):
```html
<mjml lang="en">
  <mj-head>
    <mj-attributes>
      <mj-text
        font-size="12px"
        font-weight="400"
        font-style="normal"
        line-height="1.2"
        color="inherit"
        align="left"
      />
      <mj-all padding="0" margin="0" font-family="Helvetica" />
    </mj-attributes>
    <mj-style inline="inline">
      .use-full-width {
        width: 100%;
        max-width: 100% !important;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section css-class="use-full-width">
      <mj-column width="100%">
        <mj-text> Regards, </mj-text>
        <mj-text> Marcin Dwornikowski </mj-text>
        <mj-text
          ><a
            href="https://bubblewrap.dev"
            style="
              color: rgb(218, 72, 223);
              font-weight: 600;
              text-decoration: none;
            "
            >Bubble Wrap</a
          ></mj-text
        >
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

```
**Important note:** after you build the file, it's worth looking into the output .html file (particularly ctrl/cmnd + F for '600' as there will be some conditional comments, primarily for Microsoft Outlook / Internet Explorer rendering engines - that will be conditionally enabled in those). For max consistency, those should be manually edited as well - swapping width values from '600px' to '100%'.

You can check this snippet [live](https://mjml.io/try-it-live/y5CQTCIM5) if you want to inspect the output html right now. One thing is that it will look like it does not work - but it does - it's just wrapped into an <iframe> element with width of 800px - you can inspect the source and edit it out to be 100% to see it working.
