### ISSUE TITLE
Can't change image size

### ISSUE THREAD

**Issue by luison** [mjmlio/mjml#2545]
My images within the code remain at a certain width (max 80px) whatever size I use.

This is the code but please note that I've also attached it as it breaks on the code preview

`<mjml owa="desktop">
  <mj-head>
    <mj-breakpoint width="600px"/>

    <mj-attributes>
      <mj-wrapper
              padding="0"
              background-color="#fff"
              border-radius="6px"/>
      <mj-section
              padding="20px 10px"/>
      <mj-text
              font-size="12px"
              line-height="17px"
              font-family="Fira Sans, Arial, Helvetica, sans-serif"
              align="left"
              color="#5e6977"
              padding="0"/>
      <mj-divider
              border-color="#E6E6E6"
              border-style="solid"
              border-width="2px"
              width="100%"
              padding="5px 0"
              padding-top="5px"
              padding-bottom="5px"/>
      <mj-button
              align="left"
              background-color="#457a1c"
              border-radius="4px"
              border="none"
              color="#ffffff"
              font-family="Arial, sans-serif"
              font-size="14px"
              font-weight="normal"
              inner-padding="10px 15px 10px 15px"
              padding-left="0px"
              padding-right="0px"
              padding="10px 0px 10px 0px"
              text-decoration="none"
              text-transform="none"
              vertical-align="middle"/>
      <mj-image
              padding="0px 0px 0px 0px"
      />

      
      <mj-class name="font2" font-family="Fira Sans, Arial, Helvetica, sans-serif"/>
      <mj-class name="text-body"/>
      <mj-class name="text-uppercase" text-transform="uppercase"/>
      <mj-class name="color-gray" color="#5c5e5a"/>
      <mj-class name="color-light-gray" color="#8e8e8e"/>
      <mj-class name="bg-gray" background-color="#f9f9f9"/>
      <mj-class name="legal-text" font-size="11px" padding="20px 15px" color="#8e8e8e"/>
      <mj-class name="headline"
                font-size="16px"
                font-weight="bold"
                color="#457a1c"
                line-height="24px"
                padding-bottom="0px"
      />
      <mj-class name="subheadline"
                font-size="13px"
                color="#8e8e8e"
                padding-top="0"
                line-height="24px"/>
      <mj-class name="small" font-size="10px" color="#8e8e8e" padding-top="0" line-height="24px"/>
      
      <mj-class name="text-uppercase" text-transform="uppercase"/>
      <mj-class name="border-radius" border-radius="5px"/>

    </mj-attributes>

    <mj-font href="https://fonts.googleapis.com/css?family=Fira+Sans:300,500" name="Fira Sans" />

    <mj-raw>
      block for php template system
    </mj-raw>
  </mj-head>
  <mj-body background-color="#EEE8BC" width="100%">
    <mj-section background-color="#ffffff" full-width="full-width" border-bottom="8px solid #457a1c" width="100%">
      <mj-column width="100%">
        <mj-text font-family="Fira Sans, Arial, Helvetica, sans-serif">
          CONTENT BLOCK
        </mj-text>
        <mj-image width="600px" align="left" alt="" href="https://elsurexiste.es" src="https://www.fillmurray.com/400/100" title="test" />
      </mj-column>
    </mj-section>

    <mj-section full-width="full-width" padding-bottom="5px">
      <mj-column mj-class="footer" width="100%">
        <mj-text color="#000000" font-size="15px" padding-bottom="10px">
          Enviado por <b>{{$remitente}}</b>
        </mj-text>
        <mj-text color="#000000" font-size="11px" padding-bottom="40px" padding="0px 0px 10px 0px">
          Consultas o dudas a <a style="color:inherit;" href="mailto:test@test.com">
            <u>test@email.com</u>
          </a>
        </mj-text>

        <mj-image width="300px" align="left" alt="" href="https://elsurexiste.es" src="https://www.fillmurray.com/400/100" title="test" />
      </mj-column>
    </mj-section>
    
    <mj-section css-class="section-with-padding">
      <mj-column>
        <mj-text color="#5e6977" font-size="10px">
          {{$legal_text}}
        </mj-text>
        <mj-spacer height="50px"></mj-spacer>
      </mj-column>
    </mj-section>

  </mj-body>
</mjml>`

The preview breaks at:
`</mj-head>
  <mj-body background-color="#EEE8BC" width="100%">
    <mj-section background-color="#ffffff" full-width="full-width" border-bottom="8px solid #457a1c" width="100%">
      <mj-column width="100%">
        <mj-text font-family="Fira Sans, Arial, Helvetica, sans-serif">`

When generated  I get an approx 80px width image
![image](https://user-images.githubusercontent.com/745632/189855394-60df5ede-4de3-4e98-8bd0-5d88745eccee.png)

[test.zip](https://github.com/mjmlio/mjml/files/9555159/test.zip)

**Comment by iRyusa** [comment]
`mj-body` only accept px values that's why. Note that MJML App should warn you about this :
![Capture d’écran 2022-09-13 à 11 08 08](https://user-images.githubusercontent.com/570317/189861024-def97e5f-1b37-45ac-a4b4-3d59ebc8a150.png)

**Comment by luison** [comment]
Correct, thanks. I noticed about it on another question, but never expected it would affect image sizes.  Jetbrains editor plugin does not alert. Thanks.
