### ISSUE TITLE
TypeError: this.context.processing is not a function -- when using custom HeadComponent inside mj-head

### ISSUE THREAD

**Issue by matzeso** [mjmlio/mjml#2546]
**Describe the bug**
I am trying to build a custom component to reuse my `mj-head` part.
To get a minimum version working I created a very simple `HeadComponent`:

```
export default class PmHead extends HeadComponent {
  constructor(initialDatas = {}) {
    super(initialDatas);
  }

  render() {
    return this.renderMJML(`
    <mj-title>Test Title</mj-title>
		`);
  }
}
```

I register the component and try to use it in a `.mjml` file like this:
```
<mjml>
  <mj-head>
    <pm-head></pm-head>
  </mj-head>
</mjml>
```

And it gives the following error:
```
/Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/createComponent.js:122
        return partialMjml.children.map(child => this.context.processing(child, this.context)).join('');
                                                              ^

TypeError: this.context.processing is not a function
    at /Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/createComponent.js:122:63
    at Array.map (<anonymous>)
    at PmHead.renderMJML (/Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/createComponent.js:122:37)
    at PmHead.render (/Users/matzeso/code/packmatic/app/packages/mails/components/PmHead.ts:35:17)
    at /Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/createComponent.js:318:28
    at Array.map (<anonymous>)
    at MjHead.handlerChildren (/Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/createComponent.js:299:23)
    at MjHead.handler (/Users/matzeso/code/packmatic/app/node_modules/mjml-head/lib/index.js:35:19)
    at processing (/Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/index.js:307:26)
    at mjml2html (/Users/matzeso/code/packmatic/app/node_modules/mjml-core/lib/index.js:409:24)
```

If I change the component render content to `mj-text` instead and wrap it inside `mj-body` instead of `mj-head` it works nicely and I can convert to HTML without issues.

**Expected behavior**
I would expect to be able to create a custom head component that I can use inside `mj-head`.

**MJML environment (please complete the following information):**
 - OS: MacOS 12.4 on M1
 - MJML Version: 4.13.0
 - Node Version: v16.15.0

**Additional context**
I am running a simple JS script in node that first registers the custom component, then reads the mjml file and passes it to `mjml2html`.
```
mjml2html(mjml, { validationLevel: "strict" });
```

**Comment by iRyusa** [comment]
Well as mj-head component use a `handler` instead of `render` that's why it doesn't work in this context (renderMjml expect to be used in a body component context).

I don't have a real solution for you, you should be able to instanciate any mj-head component and call the handler function if you pass down current context or you can just use a mj-include.

**Comment by matzeso** [comment]
Can the `handler` return MJML?
The documentation is unfortunately a bit scarce on custom components, although I think they could be a great asset (especially if the vscode extension would support them).

I would have liked to be able to pass props to my head component and then generate e.g. title and preview based on them. And yeah now I am using `mj-include` for the shared head part, thank you for mentioning that option :-)

**Comment by iRyusa** [comment]
Nop head component are function that alter "global" data available for mj-body element. You can use the internal API to alter those maybe instead of relying on MJML here https://github.com/mjmlio/mjml/blob/master/packages/mjml-head-title/src/index.js ?

For the documentation, we're aware ... but sadly time is the issue :(
