### ISSUE TITLE
mj-social-element contains icons from mailjet.com that no longer exist

### ISSUE THREAD

**Issue by stefanisak** [mjmlio/mjml#2551]
**Describe the bug**
 `<mj-social-element />` includes broken images from mailjet.com
 

**To Reproduce**

Just use the example from the docs:
 ```
 <mj-social>
    <mj-social-element name="facebook">Share</mj-social-element>
</mj-social>
```

renders

```
[...]
<img height="20" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/facebook.png" style="border-radius:3px;display:block;" width="20">
[...]
```

And https://www.mailjet.com/images/theme/v1/icons/ico-social/facebook.png does not exists => 404

[try online ](https://mjml.io/try-it-live/9_QrY55o3)

**Expected behavior**
Should use icons that exists.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.13.0

**Comment by TingWeiKe** [comment]
same here.

**Comment by iRyusa** [comment]
This is fixed 👍
