### ISSUE TITLE
The online tool is ignoring the first style when using `prettier-ignore`

### ISSUE THREAD

**Issue by nbouvrette** [mjmlio/mjml#2557]
**Describe the bug**
Because there is no way to get correct [Prettier formatting](https://github.com/prettier/prettier/issues/9191) right now, we have to use `<!-- prettier-ignore -->` before the style contained in `<mj-style inline="inline">` to avoid having "unmaintinable block of CSS" 

When doing so, in fact when adding any HTML comments in that block, the first style is being ignored by the [online tool](https://mjml.io/try-it-live).

**To Reproduce**

https://mjml.io/try-it-live/m3hICkZBA

```html
<mjml>
  <mj-head>
    <mj-style inline="inline">
      <!-- prettier-ignore -->
      .heading > * {
        color: red !important;
        font-size: 60px !important;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-wrapper>
      <mj-section>
        <mj-column>
          <mj-text css-class="heading">heading</mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

Remove the `<!-- prettier-ignore -->` line and the CSS will be applied in the preview.

As a workaround I can add this style at the top of `<mj-style>`:

```css
.not-used {}
```

**Expected behavior**
I would expect the CSS to work right away.

**MJML environment (please complete the following information):**
N/A

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
N/A

**Screenshots**

**Additional context**

**Comment by iRyusa** [comment]
Those are not valid css comment that's why. Add extra /* */ around it.

**Comment by nbouvrette** [comment]
When I use `/* prettier-ignore */`, VSCode doesn't recognize the the previous tag `<mj-style inline="inline">` and thinks the following content is HTML markup... meaning it "minify" the CSS under the same line.

I did another test using an `.html` file and reproduce the issue when I put CSS inside a `<div>` for example... the only way to prevent formatting is to use `<!-- prettier-ignore -->`

**Comment by iRyusa** [comment]
Not so much we can do here. We rely on juice to inline the css. This is
invalid css so it will be parsed as so.

**Comment by iRyusa** [comment]
And I meant to try with /*  */

**Comment by nbouvrette** [comment]
Wow yeah it works and reformats the comments as

```html
      /*
      <!-- prettier-ignore -->
      */
```

Nice hack but yeah, it would be nice if someone finishes the proper integration here: https://github.com/prettier/prettier/issues/9191

It feels like `mjml` is partially supported because I'm having other issues when trying to include CSS files which is why I am going back to inline like this...

My setup is pretty common, Node.js, TypeScript, Prettier, VSCode as well.

**Comment by iRyusa** [comment]
There's no plugin for MJML on Prettier so yeah that's expected.

**Comment by nbouvrette** [comment]
It looks to me like they did only part of the work but I might be missing something? https://github.com/prettier/prettier/issues/5471

**Comment by iRyusa** [comment]
It's not a real lang in prettier as it handles it as an HTML document. So
no MJML tag are handled by prettier

**Comment by nbouvrette** [comment]
FYI I found a better way, using `<!-- prettier-ignore -->` before `<mj-style inline="inline">` - otherwise the IDE's CSS auto-complete no longer works.
