### ISSUE TITLE
MJML Can't render column in Outlook Desktop

### ISSUE THREAD

**Issue by namnhfreelancer** [mjmlio/mjml#2559]
https://mjml.io/try-it-live/N5hP9pa4I

I can't show my html email in desktop mode. It alway auto forge to mobile versions even i had been used owa desktop and mj-group. Any solutions ? Thanks you.

![image](https://user-images.githubusercontent.com/12831283/195351889-61859125-e5f4-4cf4-a3e3-6389f9bebe65.png)
Outlook App
![image](https://user-images.githubusercontent.com/12831283/195351932-9483c096-df0a-40f4-9f64-37f7aa74a5bb.png)
In Browser
![image](https://user-images.githubusercontent.com/12831283/195351918-405ca64e-d74c-4b8b-b6fd-5362b47c4985.png)
Use owa desktop
![image](https://user-images.githubusercontent.com/12831283/195351952-08532e4e-0bc1-48ae-9d8a-626eaa875a5d.png)
Use mj-group

**Comment by iRyusa** [comment]
How did you send your test email ?
Can you try with https://putsmail.com/

**Comment by iRyusa** [comment]
Feel free to reopen with more details
