### ISSUE TITLE
Issue rendering on last version of Outlook with simple example

### ISSUE THREAD

**Issue by RoXuS** [mjmlio/mjml#2561]
**Describe the bug**
Hi team,

We use MJML for all our emails.
We have an issue with large email.

**To Reproduce**
Use this simple example:
```
<mjml>
  <mj-body width="1920px" background-color="red">
    <mj-wrapper padding="0 16px">
      <mj-section background-color="blue">
        <mj-column>
          <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>
        </mj-column>
        <mj-column>
          <mj-text  font-size="20px" color="white">
            Hello World
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

**Expected behavior**
Left and right padding are present and the email is responsive.

**MJML environment (please complete the following information):**
 - MJML Version 4.13.0

**Email sending environment(for rendering issues)**:
- We use litmus to test rendering but we get the same issue on a "real" office 365.

**Affected email clients (for rendering issues):**
 - Outlook 365 - Windows
 - Outlook 2021 - Windows

**Screenshots**
Browser (expected rendering):
<img width="711" alt="image" src="https://user-images.githubusercontent.com/3296671/197394072-c60b9b8d-5b07-4f44-afcb-7aaa68492da0.png">

Litmus rendering:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/3296671/197394155-5d3ab7e0-fd7d-4a5a-8f1d-ee3893c5f26e.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/3296671/197394162-622893ad-3f1e-46cd-900f-c34b33d1cb55.png">

**Additional context**
Outlook 2016 MAC the rendering is ok but on Outlook 2021/365 Windows the email is set to a static width (1920px).

If you want additional information, we are available.

**Comment by iRyusa** [comment]
The padding works but your container extend the window width that's why. 
There's no way to prevent this to happens here.

**Comment by RoXuS** [comment]
Thx for your response!

Yes, but why the container take a static 1920px as width instead of max-width ? So even if the user resize the window of outlook, the email stay stuck to 1920px?

**Comment by iRyusa** [comment]
Outlook use "ghost table" to ensure it displays the content properly. There's no responsive in Outlook windows clients.

**Comment by RoXuS** [comment]
If we use only mj-table for example:
```
  <mjml>
    <mj-body width="1920px">
      <mj-table border="1px solid #aaaaaa">
        <tr>
          <td style="padding: 16px">
          <img width="60" src="https://www.doubletrade.com/wp-content/uploads/2019/12/logo_DoubleTrade.png" />
        </td>
        <td>
          <mj-text>Test</mj-text>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          Name
        </td>
      </tr>
      </mj-table>
    </mj-body>
  </mjml>
```

The email is ok and responsive:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/3296671/197499578-3f776462-db9a-4880-bdf7-926f949ec9ee.png">


What is the difference with mj-wrapper or mj-section/column?

Thx for your help!

**Comment by iRyusa** [comment]
As in table you're inside a ghost table for outlook it "might" not behave the same as a top level table.

MJML is not suited for full-width email.

**Comment by RoXuS** [comment]
Ok thx, for your help!
