### ISSUE TITLE
Error: malformed MJML error from mjml-core for valid templates (mjml-cli validates/renders fine)

### ISSUE THREAD

**Issue by matmar10** [mjmlio/mjml#2563]
**Describe the bug**
Valid templates produce error: `Error: Malformed MJML. Check that your structure is correct and enclosed in <mjml> tags. at mjml2html`

**To Reproduce**

[NOTE: full repo with three examples available here](https://github.com/matmar10/mjml-example)

Using Typescript:

```Typescript
// example sourced from README.md
import mjml2html from 'mjml-core';

const htmlOutput = mjml2html(`
  <mjml>
    <mj-body>
      <mj-section>
        <mj-column>
          <mj-text>
            Hello World!
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-body>
  </mjml>
`, {});
console.log(htmlOutput)
```

Using plain Node.js
```Node
const mjml2html = require('mjml-core').default;
const htmlOutput = mjml2html(`
  <mjml>
    <mj-body>
      <mj-section>
        <mj-column>
          <mj-text>
            Hello World!
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-body>
  </mjml>
`, {});
console.log(htmlOutput);
```

**Expected behavior**
Programmatic usage via top-level method mjml2html (which is documented to accept a string) should render a valid template.

**MJML environment (please complete the following information):**
 - OS: MacOS 12.4
 - MJML Version: 4.13.0
 - MJML tool used: npm package (via TypeScript)

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
M/A

**Screenshots**
N/A

**Additional context**
The CLI validates & renders the sample template totally fine but the JS API barfs.

This is not a typescript issue - I've included a non-ts example in the reproduction repo I created as well that has identical behavior.

I dug up some [example code from issue #2556 issue and using this](https://github.com/mjmlio/mjml/issues/2556)

```Typescript
import * as Parser from 'mjml-parser-xml'
import * as jsonToXML from 'mjml-core/lib/helpers/jsonToXML.js';

const xml = `
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
`

const mjml = Parser(xml);
console.log(jsonToXML(mjml))
```

And this method works. But these aren't even top-level exported interfaces. 

The examples and usage that don't work are directly from the documentation. 

Has the top-level `mjml2html` method broken for string usage?

**Comment by matmar10** [comment]
Thanks @iRyusa! Now I understand what's going on. There is even a comment inside the definitions file hinting at this. 

The reason I was led astray is that the `mjml` library is because:
```
This module is declared with 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

I'll close this issue and hopefully raise a new issue (with PR) that provides a more helpful error message something like: 
`No components loaded: cannot parse MJML as no components have been loaded.`

And also update that helpful comment in the definitions file to be even more explicit. 

Thanks so much for your (amazingly) fast and helpful response!

**Comment by iRyusa** [comment]
Yeah this error is used when no content is output from a MJML (instead of rendering a blank skeleton). Might need to add some warnings if there's no component registered tho.
