### ISSUE TITLE
Keyboard shortcuts not working in MJML on Chrome/Edge

### ISSUE THREAD

**Issue by jonathan-wright-79** [mjmlio/mjml#2564]
**Describe the bug**
I cannot seem to use keyboard shortcuts such as CTRL + C, CTRL + V when using the online MJML editor in Chrome/Edge. 
Firefox seems to work fine. 
Seems to be just the editor pane that is affected, I can for example use CTRL + C on the version text above the editor pane.

**To Reproduce**
1. Go here in Chrome or Edge: https://mjml.io/try-it-live
2. Try to copy code from left hand editor pane using keyboard CTRL + C, try to paste code in left hand editor pane using CTRL + V

**Expected behavior**
The code to be copied, and then pasted within the editor

**MJML environment (please complete the following information):**
 - OS: Chrome: Version 106.0.5249.119 (Official Build) (64-bit)
 - MJML Version [version 4.9.3]
 - MJML tool used: Online editor: https://mjml.io/try-it-live/pv0ECBWUV

**Comment by iRyusa** [comment]
Can't reproduce the issue on Chrome with OSX and Windows 🤔
