### ISSUE TITLE
It is possible to add embedded image ?

### ISSUE THREAD

**Issue by maximsymfony** [mjmlio/mjml#2569]
I do not have a problem with image linked
MJML
`    <mj-section background-url="https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg" background-size="cover" background-repeat="no-repeat">`
in HTML looks like
`    <div style="background:url(https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;margin:0px auto;max-width:600px;">
      <div style="line-height:0;font-size:0;">
        <table align="center" background="https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:url(https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;width:100%;">
          <tbody>`

But i want to add embedded image via Symfony Twig - 
`<div style="background:url({{ email.image('@images/email/email_header.svg') }}) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;margin:0px auto;max-width:600px;">
        <div style="line-height:0;font-size:0;">
            <table align="center" background="{{ email.image('@images/email/email_header.svg') }}" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:url({{ email.image('@images/email/email_header.svg') }}) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;width:100%;">
                <tbody>`

Rendered result is ok but not working
`109    <div style="background:url(cid:f89dbc9132fffa2302e27f47f2c09116@symfony) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;margin:0px auto;max-width:600px;">
110        <div style="line-height:0;font-size:0;">
111            <table align="center" background="cid:f89dbc9132fffa2302e27f47f2c09116@symfony" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:url(cid:f89dbc9132fffa2302e27f47f2c09116@symfony) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;width:100%;">
112                <tbody>`

**Comment by iRyusa** [comment]
This is not an issue with mjml here. We can’t help you with this.On 1 Nov 2022, at 10:32, maximsymfony ***@***.***> wrote:﻿
I do not have a problem with image linked
MJML
    <mj-section background-url="https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg" background-size="cover" background-repeat="no-repeat">
in HTML looks like
    <div style="background:url(https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;margin:0px auto;max-width:600px;"> <div style="line-height:0;font-size:0;"> <table align="center" background="https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:url(https://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;width:100%;"> <tbody>
But i want to add embedded image via Symfony Twig -
<div style="background:url({{ ***@***.***/email/email_header.svg') }}) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;margin:0px auto;max-width:600px;"> <div style="line-height:0;font-size:0;"> <table align="center" background="{{ ***@***.***/email/email_header.svg') }}" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:url({{ ***@***.***/email/email_header.svg') }}) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;width:100%;"> <tbody>
Rendered result is ok but not working
109    <div ***@***.***) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;margin:0px auto;max-width:600px;"> 110        <div style="line-height:0;font-size:0;"> 111            <table align="center" ***@***.***" border="0" cellpadding="0" cellspacing="0" role="presentation" ***@***.***) center top / cover no-repeat;background-position:center top;background-repeat:no-repeat;background-size:cover;width:100%;"> 112                <tbody>

**Comment by maximsymfony** [comment]
@iRyusa that mean - embedded images is not in best practices and blocked by many email ? Correct?
