### ISSUE TITLE
How to disable Ubuntu font and it's references in email?

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#257]
For now, I'm deleting it's all references manually from HTML output, I think making a custom font as part of MJML by default is not a good idea. There should be an option to enable/disable it, it should be optional.

**Comment by lohek** [comment]
Hey !

See https://github.com/mjmlio/mjml/issues/216, you need change all `mj-text`, `mj-list` and `mj-button` with other font-family for remove Ubuntu import.

**Comment by ngarnier** [comment]
To follow-up on what @lohek said, also note that https://github.com/mjmlio/mjml/pull/249 will make it easier to override the default font with your favorite one.

**Comment by oliviertassinari** [comment]
Will end-up using the same solution as @jitendravyas to remove the generated:
```html
<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css">
```

**Comment by iRyusa** [comment]
Hi @oliviertassinari 

You can just override every `font-family` in `mj-attributes` with `mj-all` it will disable the import. 
Ex: https://mjml.io/try-it-live/r1eZJxNNb

**Comment by oliviertassinari** [comment]
My bad, I was trying to load two fonts at once with `https://fonts.googleapis.com/`. Needs to split them. Thanks.

**Comment by webuxr** [comment]
Hello,
First time caller, long-time listener...
I need to re-open this ticket. I'm using a fresh install of mjml, set me own webfonts to use, yet I still see the Ubuntu font being output in my final HTML. Also, for reference, tagging the related issue https://github.com/mjmlio/mjml/issues/216 here too.

Here's my local stack:
- Mac OS Catalina v10.15.7
- Chrome v92.0.4515.15
- Node: v14.17.5
- NPM: v7.20.6
- mjml-core: 4.10.2
- mjml-cli: 4.10.2

I have the following code in my `basic.mjml` file:

```
<mjml lang="en">
  <mj-head>
    <mj-title>Foo</mj-title>
    <mj-preview>Foo</mj-preview>
    <mj-font name="roboto" 
             href="https://fonts.googleapis.com/css?family=Roboto" />
    <mj-attributes>
      <mj-button font-family="roboto, arial, sans-serif" />
      <mj-list font-family="roboto, arial, sans-serif" />
      <mj-all font-family="roboto, arial, sans-serif" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-text>Hello world!</mj-text>
  </mj-body>
</mjml>
```

...and after running the command:  
```
mjml -l strict -w basic.mjml -o ./output
```
...I get the following in the resulting HTML output:
```
<head>
   ...
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"
        rel="stylesheet"
        type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700"
        rel="stylesheet"
        type="text/css"><!-- <= NOT COOL -->
  <link href="https://fonts.googleapis.com/css?family=Roboto"
        rel="stylesheet"
        type="text/css">
  <style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700);
    @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700); /* <= NOT COOL */
    @import url(https://fonts.googleapis.com/css?family=Roboto);
  </style>
  ...
</head>
<body>
  ...
  <div style="font-family:roboto, arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Hello world!</div>
  ...
</body>
```

Note: I also have the mjml app installed and see the same results regardless (also posted this issue there: https://github.com/mjmlio/mjml-app/issues/58#issuecomment-904070559).

My only caveat from the origin Op is that my "Hello world!" text is styled in Roboto. While this is what I intended, I don't want the extra HTTP request for Ubuntu. PLUS, I have added the line `<mj-all font-family="roboto, arial, sans-serif" />` to my `<mj-attributes>` and yet I still get Ubuntu in my final HTML.

How do I prevent mjml from using Ubuntu in my final HTML (besides manually deleting the `<link>` and `@import` lines for Ubuntu)?

In addition, and perhaps an issue for a separate ticket, what's up with the double references to Roboto?

Thanks,
_rs

**Comment by iRyusa** [comment]
Hi,
Can't reproduce on try it live here https://mjml.io/try-it-live/jcNVkItAp2s are you sure you're sharing the full template here ?
Ubuntu is only added when there's at least 1 reference to it

**Comment by webuxr** [comment]
@iRyusa Thanks for the quick response. No, that was not my full template. Here's a link to the full template on mjml Try-It: https://mjml.io/try-it-live/4lyPTIi6Yo0 and Ubuntu is still in there.

Perhaps it's something simple, something missing or otherwise. Thoughts?

**Comment by webuxr** [comment]
@iRyusa That Try-It is a super-nifty tool! I went through my template, section by section, and discovered my use of `<mj-nav>` is what's causing Ubuntu to be added to the HTML output. So, something in this code is not working:

```
<mj-section background-color="#6f2a8e"
            border-bottom="1px solid #ffffff"
            padding="10px 0">
  <mj-column padding="0">
    <mj-navbar align="center"
               base-url="https://www.google.com"
               hamburger="hamburger"
               ico-color="#ffffff"
               padding="0">
      <mj-navbar-link href="/foo"
                      color="#ffffff"
                      font-family="roboto, sans-serif"
                      font-size="12px"
                      font-weight="700"
                      padding="0 5px 0 0"
                      target="_blank"
                      text-decoration="none"
                      text-transform="capitalize">Foo</mj-navbar-link>
      <mj-navbar-link href="#"
                      color="#ffffff"
                      font-family="roboto, sans-serif"
                      font-size="12px"
                      font-weight="700"
                      padding="0 5px 0 0"
                      text-decoration="none">|</mj-navbar-link>
      <mj-navbar-link href="/bar"
                      color="#ffffff"
                      font-family="roboto, sans-serif"
                      font-size="12px"
                      font-weight="700"
                      padding="0 5px 0 0"
                      target="_blank"
                      text-transform="capitalize"
                      text-decoration="none">Bar</mj-navbar-link>
    </mj-navbar>
  </mj-column>
</mj-section>
```

Should I create a new ticket with my finding?

**Comment by iRyusa** [comment]
There's no real issue here it works as intended. Add ico-font-family to your mj-all and you'll be fine

**Comment by webuxr** [comment]
@iRyusa Yep, that fixed the issue.

For others to reference later... use the following snippet to prevent mjml from rendering the default Ubuntu font in the output HTML:

```
<mj-font name="roboto"
         href="https://fonts.googleapis.com/css?family=Roboto" />
<mj-attributes>
    <mj-all font-family="roboto, arial, sans-serif"
        ico-font-family="roboto, arial, sans-serif" />
</mj-attributes>
```

It would be super-helpful if the above snippet could be included in the docs? Perhaps here (https://documentation.mjml.io/#mj-font)?

Thank you again!
