### ISSUE TITLE
Social element: Padding-top/right/bottom/left not working 

### ISSUE THREAD

**Issue by JBassleer** [mjmlio/mjml#2570]
**Describe the bug**
Padding-top/right/bottom/left not working on a single social element. Normal padding and giving 4 values does work.

**To Reproduce**
Provided MJML:

`<mj-social-element name="instagram-noshare" href="https://www.instagram.com/" padding-bottom="10px" background-color="#A1AEE0" border-radius="20px">`

Received HTML:
````
<table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="float:none;display:inline-table;">
                          <tbody><tr>
                            <td style="padding:4px;vertical-align:middle;">
                              <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#A1AEE0;border-radius:20px;width:35px;">
                                <tbody><tr>
                                  <td style="font-size:0;height:35px;vertical-align:middle;width:35px;">
                                    <a href="https://www.instagram.com/" target="_blank">
                                      <img height="35" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/instagram.png" style="border-radius:20px;display:block;" width="35">
                                    </a>
                                  </td>
                                </tr>
                              </tbody></table>
                            </td>
                          </tr>
                        </tbody></table>
````

**Expected behavior**
Not entirely sure where I should expect the padding-bottom (for example) to be.

**MJML environment (please complete the following information):**
- I was testing this on the live Email Editor [https://mjml.io/try-it-live/](https://mjml.io/try-it-live/)

Let me know if I need to provide more information for this but it should be easily reproduced in the live editor.

NOTE: `padding="20px 20px 20px 20px"` does work but not `padding-top="20px" padding-right="20px" padding-bottom="20px" padding-left="20px"`

**Comment by iRyusa** [comment]
It seems that they're not bound to the `td` that's why it doesn't work 😄 https://github.com/mjmlio/mjml/blob/master/packages/mjml-social/src/SocialElement.js#L150 feel free to open a PR about it 👍

**Comment by iRyusa** [comment]
Should be good in last version !
