### ISSUE TITLE
Left indentation of MJML Email

### ISSUE THREAD

**Issue by dawoodaijaz97** [mjmlio/mjml#2574]
**Describe the bug**
I am trying to create a simple HTML email using MJML 4.12.0. The emails have an unnecessary left indentation.

![image](https://user-images.githubusercontent.com/41577025/201912971-1786a9c7-6766-4899-a005-a4c45a69ad4c.png)

In the image(from Gmail), you can see the default left indentation. The question is how can I remove this

**To Reproduce**
1. Create a file with this MJML code: `<mjml>
            <mj-head><mj-preview>Email Preview</mj-preview>
            </mj-head>
            <mj-body>
                <mj-container>
                    <mj-column>
                        <mj-text>Body</mj-text>
                    </mj-column>
                    <mj-column>
                        <mj-text>Signature</mj-text>
                        <mj-image src="" alt="organization logo" align="left" width="120px" />
                    </mj-column>
                </mj-container>
            </mj-body>
        </mjml>`
2. Render it to HTML.
3. Send the HTML to an email address.
4. See the error

**Expected behavior**
In the sent message you will see the left indentation.

**MJML environment (please complete the following information):**
 - OS: Linux Ubuntu
 - MJML Version 4.12.0

**Email sending environment(for rendering issues)**:
 - I am using Microsoft graph API to send these emails.

**Comment by iRyusa** [comment]
mj-container doesn't exist anymore, and you don't have a single section in
your body.

MJML isn't suited for signature to be honest, you can try to send with
https://putsmail.com/ instead but I don't think there's any fix for you
here.

**Comment by iRyusa** [comment]
Please check the documentation about section/column and how it's supposed
to work https://documentation.mjml.io/#getting-started

This is completely normal as MJML email are in a centered container by
default.

I don't think MJML will be any help in what you want to do here.
