### ISSUE TITLE
mj-image and mj-social-element being cutted in outlook

### ISSUE THREAD

**Issue by kylawamg** [mjmlio/mjml#2577]
**Describe the bug**
Im using mj-image and mj-social-element with src attribute and in outlook (desktop) all the images are cutted by the right side.

**To Reproduce**
1. Create a file with this MJML code:

```
<mjml><mj-head>
  </mj-head>
<mj-body>
<mj-section background-color="white" css-class="footer" padding-left="12px" padding-right="12px" padding-top="8px">
<mj-column padding-top="24px" width="33%" vertical-align="middle" ${this.htmlAttributes({ style: 'social-icons-colum' })}>
      <mj-social icon-size="26px" mode="horizontal" align="center">
        <mj-social-element src="https://www.images.com/img/icons/rrss_linkedin.png" href="https://es.linkedin.com/" alt="Our Linkedin"  css-class="social-icon" />
        <mj-social-element src="https://www.images.com/img/icons/rrss_facebook.png" href="https://es-la.facebook.com/" alt="Our Facebook"  css-class="social-icon" />
        <mj-social-element src="https://www.images.com/img/icons/rrss_youtube.png" href="https://www.youtube.com/" alt="Our Youtube" css-class="social-icon" />
        <mj-social-element src="https://www.images.com/img/icons/rrss_IG.png" href="https://www.instagram.com/" alt="Instagram" css-class="social-icon" />
        <mj-social-element src="https://www.iahorro.com/img/icons/rrss_twitter.png" href="https://twitter.com" alt="Our Twitter"css-class="social-icon" />
      </mj-social>
    </mj-column>
</mj-section>
</mj-body>
</mjml>
```

The example has only the mj-social-element case, but this happens with mj-image too.

As you can see below, in Outlook images are cut off on the right by approximately 1px:

![image](https://user-images.githubusercontent.com/18372506/202407682-003cfa4e-20a6-4deb-b474-ed5b6d1ec51b.png)
![image](https://user-images.githubusercontent.com/18372506/202408397-e3483cfd-73e4-473c-887e-8f83f8aead0e.png)

While in other email clients the images are perfect: 
![image](https://user-images.githubusercontent.com/18372506/202408183-7d2f0d36-4967-4bd7-b923-eaa4c03d62ce.png)
![image](https://user-images.githubusercontent.com/18372506/202408279-8874278f-216b-4c3f-8784-1f6238e88ad2.png)

**Expected behavior**
See the images rendered like in any other email clients. (not cutted by the right)

**MJML environment (please complete the following information):**
 - MJML Version: 4.13.0

**Affected email clients (for rendering issues):**
 - Email Client: Outlook Desktop
 - OS: Windows

**Additional context**
I have tried to reproduce use cases using the necessary mjml elements ir order to reduce possible problems with other styles/markup but the problem still.

Do you have any idea why this happend and how to fix it?

Thanks in advance

**Comment by iRyusa** [comment]
Hi,

Can you try to set `icon-height` to `27px` as it looks like your icon are non-square ?

**Comment by kylawamg** [comment]
Thanks for your quick response. I tried it but the problem still. 

I create this example with a similar image and deleting all the styles: https://mjml.io/try-it-live/lU7thjbFj

And when I sent the output html to outlook client, the problem still there. The images cut of a little bit (1px?) by the right side.

**Comment by iRyusa** [comment]
How did you send your test email ?

This is what I get on Emailonacid for outlook: 

![image](https://user-images.githubusercontent.com/570317/202453419-84574a37-26d6-4d25-9fa3-a583fbcece9d.png)

Everything looks good to me

**Comment by iRyusa** [comment]
Can you try with https://putsmail.com to see if it does the same

**Comment by kylawamg** [comment]
Thanks, I tried sending the email from putsmail but the result still the same :(

**Comment by iRyusa** [comment]
🤔 what version of outlook you're using to reproduce ?
