### ISSUE TITLE
@import link missing single quotes

### ISSUE THREAD

**Issue by DanaIntouch** [mjmlio/mjml#2579]
I am using the terminal function to compile mjml to html. (mjml -w file.mjml -o file.html)

The @import link that is created for fonts is missing the single (or double) quotes. This has caused an issue for several of our vendors. 

This also happens (I just discovered) when I use the shift+cmd+P export html method.

Anyone else have this problem?

I simply remove the @import and all is well.

**Comment by iRyusa** [comment]
Quote are optional in @import so that's why there's no quote.

This is valid css and shouldn't be an issue.
