### ISSUE TITLE
text-align on mj-section not aligning text

### ISSUE THREAD

**Issue by mamartins** [mjmlio/mjml#258]
No matter what I insert in the text-align property in a mj-section the text don't follow, I need to add the style directly on mj-text

**Comment by jitendravyas** [comment]
Can you share your MJML code?

**Comment by mamartins** [comment]
simple as this:
````
 <mj-section text-align="center">
                <mj-text>test</mj-text>
 </mj-section>
````

**Comment by mamartins** [comment]
also if you set font size in the mj-container it is not added to any inherit sections, etc.

**Comment by obeces** [comment]
Have you tried with this:
` <mj-section>
   <mj-column>
      <mj-text align="center">test</mj-text>
    </mj-column>
 </mj-section`

Read the documentation:

https://mjml.io/documentation/#sections

> Remember everything has to be contained in one column.
