### ISSUE TITLE
Override default margin for paragraphs

### ISSUE THREAD

**Issue by kiranvedantam1992** [mjmlio/mjml#2581]
In mjml-lib.js, the margin is set to 13px for all p tags. How do we override it? If any code examples are available, please share.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/52167315/203163077-42bf338a-6d43-4a4f-af65-45dd9284e2a1.png">

**Comment by iRyusa** [comment]
Any mj-style in mj-head should override this
https://mjml.io/try-it-live/QYd9gCeLe

**Comment by kiranvedantam1992** [comment]
For some reason, it's not working. FYI: We have integrated MJML with AEM
<img width="1635" alt="image" src="https://user-images.githubusercontent.com/52167315/203168980-0ff7d261-303c-4afe-934a-57e07131c36a.png">

**Comment by iRyusa** [comment]
As it works in the try it live, the issue is on your side. Can't really
help you more here.

**Comment by kiranvedantam1992** [comment]
We manged to fix this by adding the style tag after the head tag
