### ISSUE TITLE
GMAIL columns not working - fixed by display and vertical align

### ISSUE THREAD

**Issue by Inf166** [mjmlio/mjml#2586]
So I was debugging various email clients, and found that gmail takes the first class of a dom element and renders a class itself that should do what other classes are doing. But through this, a bugfix I made trough an self created class to that dom element, I discovered that my class is ignored. I guess classes like mj-column-per-50 should only do one thing.

But I also think that usually we are adding columns and the content inside should align top. So maybe, to support more email clients you could add to: 
```
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
        .mj-column-per-50 { width:50% !important; max-width: 50%;}
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
      .moz-text-html .mj-column-per-50 { width:50% !important; max-width: 50%;}
    </style>
```
this: 
```
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-100 { width:100% !important; max-width: 100%; }
        .mj-column-per-50 { width:50% !important; max-width: 50%; display: inline-block; vertical-align: top; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }
      .moz-text-html .mj-column-per-50 { width:50% !important; max-width: 50%; display: inline-block; vertical-align: top; }
    </style>
```
Broken:
![image](https://user-images.githubusercontent.com/38419872/203845448-f283d8cc-abc7-4930-8e75-18a004fdba54.png)
![image](https://user-images.githubusercontent.com/38419872/203840559-1501e47b-443d-4998-9651-611078a003d7.png)

Fixed:
![image](https://user-images.githubusercontent.com/38419872/203845582-df68a572-8a9f-4f4e-80b9-67f087a33f32.png)
![image](https://user-images.githubusercontent.com/38419872/203840634-11a2b8be-a2a3-453a-a020-2ca8f710dc29.png)

**Comment by iRyusa** [comment]
Can you share you MJML code ?

**Comment by Inf166** [comment]
I can paste the code for the two-cols
```
<mj-section>
<mj-group>
  <mj-column>
        <mj-table>
               [Custum Stuff I head to do because of client requirements]
        </mj-table>
  </mj-column>
  <mj-column>
        <mj-table>
               [Custum Stuff I head to do because of client requirements]
        </mj-table>
  </mj-column>
</mj-group>
</mj-section>
```

**Comment by iRyusa** [comment]
We clearly need the MJML to reproduce. A simple 2 column layout works fine in gmail, so I don’t see why it won’t works for you.On 24 Nov 2022, at 19:00, Joel Maximilian Mai ***@***.***> wrote:﻿
Its the default out put above.
I have modified the default output like I described above... so no I can only paste the code I already pasted above...
But what else can I do to help?

**Comment by Inf166** [comment]
No need to test - It was the mj-group

I didn't realized until I wrote the code above.
It was remaining there during debugging.

Sorry for the unneeded comment
