### ISSUE TITLE
Override meta tags

### ISSUE THREAD

**Issue by kiranvedantam1992** [mjmlio/mjml#2587]
MJML by default creates <meta> tags inside its email head. Here are my queries

1. What is the list of default <meta> tags that would be added?
2. Can we override the default <meta> tags? if yes, can you please suggest the way to do it - which is upgrade compatible?
3. If not (for option 2) Can we add the same meta tags again with different values? would there be an issue in the email or SEO then?

Thanks,
Kiran Vedantam

**Comment by iRyusa** [comment]
Some of tags in the `head` are available to "custom" with mj-head component.
Everything in the head does something so don't remove anything unless you know what you're doing.
