### ISSUE TITLE
overriding default value doesn't remove default value from output.

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#259]
MJML code

```
<mj-text container-background-color="brown" padding-left="10" padding-right="10">
              Column 1
            </mj-text>
```

Output 

`<td style="word-break:break-word;background:brown;font-size:1px;padding:10px 25px;padding-right:10px;padding-left:10px;text-align:left;" background="brown">`

Before I noticed it today I used to think it replaces it, so I'm just sharing it here. https://mjml.io/try-it-live/ae116e3dc2df0b4af5b9f81e897e944b

**Comment by ngarnier** [comment]
Hey @jitendravyas, I'm sorry but I can't quite understand what you mean? 

It seems all good to me as your 1st column is brown, 2nd is yellow and 3rd is green.

The `<mj-text>` background-color obviously doesn't override the whole column because you might want to have more things in your column, see the example [here](https://mjml.io/try-it-live/a957bddb378f98a9679b285fcab0d412).

**Comment by jitendravyas** [comment]
i was talking about this duplication 

`padding:10px 25px;padding-right:10px;padding-left:10px;`

**Comment by iRyusa** [comment]
I'm closing this one. `padding-left` `padding-right` will not override default padding on a element.

**Comment by jitendravyas** [comment]
I'm not talking about override. I'm talking about code duplication

Output of this
`<mj-text container-background-color="brown" padding-left="10" padding-right="10">`

ideally should be this
`padding:10px 25px`

not this
`padding:10px 25px;padding-right:10px;padding-left:10px;`

**Comment by iRyusa** [comment]
It's on purpose, padding-left/right/top/bottom should remain as their css equivalent

**Comment by AKASH-ODEDARA** [comment]
> MJML code
> 
> ```
> <mj-text container-background-color="brown" padding-left="10" padding-right="10">
>               Column 1
>             </mj-text>
> ```
> 
> Output
> 
> `<td style="word-break:break-word;background:brown;font-size:1px;padding:10px 25px;padding-right:10px;padding-left:10px;text-align:left;" background="brown">`
> 
> Before I noticed it today I used to think it replaces it, so I'm just sharing it here. https://mjml.io/try-it-live/ae116e3dc2df0b4af5b9f81e897e944b

I Understand your query...

in mjml <mj-button> there's an attribute called **inner-padding** and it's default value is 10px 25px. So you just have to remove it by **writing inner-padding="0px" inside your mj-button tag.**
