### ISSUE TITLE
watch won't work

### ISSUE THREAD

**Issue by kentoo** [mjmlio/mjml#26]
Pulsar:mjml-demo andrea$ mjml --watch index.mjml -o index.html

/Users/andrea/.npm-packages/lib/node_modules/mjml/lib/cli.js:42
    return new Promise(function (resolve, reject) {
               ^
ReferenceError: Promise is not defined
    at /Users/andrea/.npm-packages/lib/node_modules/mjml/lib/cli.js:42:16
    at render (/Users/andrea/.npm-packages/lib/node_modules/mjml/lib/cli.js:85:3)
    at FSWatcher.<anonymous> (/Users/andrea/.npm-packages/lib/node_modules/mjml/lib/cli.js:101:12)
    at FSWatcher.EventEmitter.emit (events.js:98:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1039:12)

**Comment by GuillaumeBadi** [comment]
Hey @kentoo !

What is your Node version ?
`node -v`

**Comment by kentoo** [comment]
It's a stable and legacy version: 0.10.25

**Comment by GuillaumeBadi** [comment]
Ok, yeah the Promise API is not supported by node 0.10.
I encourage you to update your Node version. 4.2.x would work perfectly ! :+1:

**Comment by iRyusa** [comment]
@kentoo is this ok for you ? Can we close it :)

**Comment by kentoo** [comment]
Yeah, of course! Thanks a lot ;)
