### ISSUE TITLE
`mj-raw` in`mj-head` fails

### ISSUE THREAD

**Issue by jdrouet** [mjmlio/mjml#2605]
**Describe the bug**
I'm just trying to put a `mj-raw` in `mj-head` and it fails with the error `Error: Malformed MJML. Check that your structure is correct and enclosed in <mjml> tags.`

**To Reproduce**
1. Create a file with this MJML code:
```
<mjml>
  <mj-head>
    <mj-raw>
      <meta name="description" content="This should stay." />
    </mj-raw>
  </mj-head>
</mjml>
```
2. Render it to HTML
3. You get the error `Error: Malformed MJML. Check that your structure is correct and enclosed in <mjml> tags.`

**Expected behavior**
Just render with meta well placed

**MJML environment (please complete the following information):**
 - OS: Debian
 - Node: 19.1.0
 - MJML Version 4.13.0

**Comment by iRyusa** [comment]
Just add an mj-body and it should work fine.
