### ISSUE TITLE
Expecting Liquid js Short Code Supports

### ISSUE THREAD

**Issue by AgnRakul** [mjmlio/mjml#2608]
While Converting from MJML to HTML if there are any short codes like
```
{%- for person in people %}
<mj-text>Hello</mj-text>
{%- endfor%}
```

```
<body style="word-spacing:normal;">
  <div style="">
    <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Hello</div>
  </div>
</body>
```

But i am expecting like this
```
<body style="word-spacing:normal;">
  <div style="">
{%- for person in people %}
    <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Hello</div>
{%- endfor%}
  </div>
</body>
```

The Above Liquidjs For Loop as been removed while converting from mjml to html.
Is there any Option Available already ?

**Comment by iRyusa** [comment]
Yes, use Lu-rawOn 17 Dec 2022, at 09:44, AgnRakul ***@***.***> wrote:﻿
While Converting from MJML to HTML if there are any short codes like
{%- for person in people %}
<mj-text>Hello</mj-text>
{%- endfor%}

<body style="word-spacing:normal;">
  <div style="">
    <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Hello</div>
  </div>
</body>

But i am expecting like this
<body style="word-spacing:normal;">
  <div style="">
{%- for person in people %}
    <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;">Hello</div>
{%- endfor%}
  </div>
</body>

The Above Liquidjs For Loop as been removed while converting from mjml to html.
Is there any Option Available already ?

**Comment by AgnRakul** [comment]
What Happen ?

**Comment by AgnRakul** [comment]
Hey, Are you there ?

**Comment by iRyusa** [comment]
Auto-correct in email : )

Use mj-raw to wrap it. https://documentation.mjml.io/#mj-raw

**Comment by AgnRakul** [comment]
Yeah I Just Now Saw That But it won't convert MJML to HTML  whatever inside in ```<mj-raw>``` tag. It will make any issues ? like without converting to html and sending email templates to the mail

**Comment by iRyusa** [comment]
Just wrap your templating inside mj-raw not the full code. 

```
<mj-raw>if ...</mj-raw>
<mj-text>inside if</mj-text>
<mj-raw>endif</mj-raw>
```

**Comment by AgnRakul** [comment]
Got it Thanks
