### ISSUE TITLE
Some questions about using mj-column under mj-section

### ISSUE THREAD

**Issue by zh1314** [mjmlio/mjml#2609]
HI, I would like to ask a question.

I saw the official recommendation that even if there is only one column, mj-column should be added under mj-section. I think that mj-column should not be added when there is only one column, but I am not sure if it will cause any unexpected. s consequence。

like this,There is only one column, if I remove this mj-colum, what are the consequences
`<mj-section>
      <mj-column>
        <mj-image width="300px" src="https://images.pexels.com/photos/40815/test.jpeg" />
      </mj-column>
    </mj-section>`

These questions are raised because there are too many nested tables, gmail will be folded and cannot be displayed in full, and I am trying to reduce the dom structure.

**Comment by iRyusa** [comment]
Even if it's a single column you need to have it because of ghost table for Outlook.

If you have size output issue : try to minimize the number of section in your code, and don't forget to minify the HTML before sending.
