### ISSUE TITLE
Title Tag on mj-button is being stripped away

### ISSUE THREAD

**Issue by JakeLeffler-eversana** [mjmlio/mjml#2610]
`<mj-button css-class="centerText mAuto padT10" align="right" href="https://www.google.com" title="MOTE_SAMPLE" target="_blank" background-color="#34A293" border-radius="10px" color="#ffffff" font-size="16px" font-weight="bold" inner-padding="10px 18px 10px 18px">
                   Request Samples
                </mj-button>`
                
Here is the output HTML
                
`<td align="center" bgcolor="#34A293" role="presentation" style="border:none;border-radius:10px;cursor:auto;mso-padding-alt:10px 18px 10px 18px;background:#34A293;" valign="middle"><a href="https://www.google.com" style="display:inline-block;background:#34A293;color:#ffffff;font-family:Arial, Helvetica, sans-serif;font-size:16px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 18px 10px 18px;mso-padding-alt:0px;border-radius:10px;" target="_blank">Request Samples</a></td>`

**Comment by iRyusa** [comment]
Email Editormjml.io Can’t seem to reproduce here ? Message ID: ***@***.***>
