### ISSUE TITLE
Mjml If condition is not working

### ISSUE THREAD

**Issue by Daniel-wethenew** [mjmlio/mjml#2611]
**Describe the bug**
Hello there, conditional statement just doest not work or I'm really missing something. I've spent the afternoon trying to figure it out

**Additional context**
this issue https://github.com/mjmlio/mjml/issues/1265 have been closed and I dont know why because the given doesn't even work on the online editor. here is the link given has a solution https://mjml.io/try-it-live/rkiGUi_GX you can try changing the condition as you want the block is still rendering...

**Comment by iRyusa** [comment]
Mjml simply doesn’t have any templating language built in that’s why

**Comment by Daniel-wethenew** [comment]
> Mjml simply doesn’t have any templating language built in that’s why

thank you for the quick reply ! The answer given in the issue linked is missleading...
