### ISSUE TITLE
MJML Breakpoint - Media Query

### ISSUE THREAD

**Issue by renchris** [mjmlio/mjml#2614]
**Describe the bug**
The design changes from mobile to desktop upon the default breakpoint of 540px or otherwise manually set a breakpoint with the `<mjml-breakpoint width="{customBreakpointValue}px"/>` component.

However, the breakpoint happens based on a @media query of `@media only screen and (min-width:580px)` which is dependent on the screen/viewport size rather than the email body size.

In email clients such as outlook, there are navigation sidebars that take up a portion of the viewport and screen, so the email design does not invoke the breakpoint on the expected email width

Is there a way to have the breakpoint dependent on the container size rather than the screen size?

**Comment by iRyusa** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries are way too recent to be used in emails so there's not so much you can do about this.

**Comment by renchris** [comment]
> https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries are way too recent to be used in emails so there's not so much you can do about this.

@iRyusa , is there then a way to have two `<mj-column/>` components be in-line next to each other if they fit the container width (ie. desktop), and stack on top if they don't (ie. mobile)?

Elements in the same `<mj-text/>` does this as it word wraps the inner component to a new line

Currently when the contents inside the `<mj-column/>` components are larger than the width, they just overlap instead of wrapping to a new line

The actual result, overlapping: 
<img width="302" alt="image" src="https://user-images.githubusercontent.com/57972348/211284478-007a7286-3164-4db2-aa41-6db16a58805c.png">

The desired result, stacking:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/57972348/211284587-165ba535-befb-4e88-80df-bcf2b3216ca7.png">
and in-line when fits within container width:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/57972348/211284669-22c3924b-c351-48e2-8a3f-bac4418f48af.png">
