### ISSUE TITLE
mj-wrapper inside mj-column

### ISSUE THREAD

**Issue by OReshetnikov** [mjmlio/mjml#2616]
I'm not sure that it is a bug but... I need to use a wrapper in a column. When I try to do this in a sandbox, the validator says that mj-wrapper cannot be used inside mj-column but the compiler handles this nesting. Is it legal to use this structure?

Link to reproduce:  https://mjml.io/try-it-live/4f9yT4V7j

**Comment by iRyusa** [comment]
MJML isn't in strict mode in try it live, so it will transpile to something even if it's not something supported.
