### ISSUE TITLE
-o myfile.php appends .html to the output file

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [mjmlio/mjml#262]
Hi there!

I'm using mjml to output files with .blade.php extension, to be read by laravel php framework.

After updating to v2, my files are now outputing with .html at the end, not following what I specified in the "-o" command.

For example:

`mjml -r retorno.blade.mjml -o retorno.blade.php`

This generate a file named `retorno.blade.php.html`, but I wanted to output `retorno.blade.php`.

What command do I use to not append .html to my output file?

Thanks!

**Comment by eughenio** [comment]
+1

**Comment by dominiquedutra** [comment]
I've been using MJML with laravel blade for a while now. They go pretty well together.
Updated mjml to latest version and it now appends a .html to my -o file.blade.php files.

Thanks! mjml is great.

**Comment by iRyusa** [comment]
Hi there, 

It will be fix on next release. When no extension is provided it will append `.html`, if an extension is detected it will keep it
