### ISSUE TITLE
when use html-attribute, <br> in <mjml-text> render error

### ISSUE THREAD

**Issue by xlnhaha** [mjmlio/mjml#2623]
Hi, like the image below show, in the green block, when i use html-attribute, the tag br in mjml-text will render several times, please help to solve it, thank you very much.

The correct render result should have no br tag after text 'aaa' in the blue block, but it has two extra br tag after text 'aaa'
![image](https://user-images.githubusercontent.com/34709921/213390814-33376c71-8070-4221-bc69-3f1a6f66387b.png)

**Comment by iRyusa** [comment]
It's  just a visual issue with codemirror and html. Just ignore it
