### ISSUE TITLE
How to get overlapping sections effect?

### ISSUE THREAD

**Issue by soulayka8** [mjmlio/mjml#2626]
Hey everyone, I'm trying to achieve this design (the overlapped sections), since there's no margin supported, I'm stuck.

![mjml issue](https://user-images.githubusercontent.com/95493735/214514338-ab746fb2-34bc-44fb-8ac2-5c9d5365608a.jpg)

**Comment by nooonde2** [comment]
![threeimages](https://user-images.githubusercontent.com/32708543/217592676-1a95f541-5e31-45a8-bdee-093ebc3fba3f.png)
Just three images.

btw.. this is not stackoverflow

**Comment by iRyusa** [comment]
Idk why you need to add this : 

> btw.. this is not stackoverflow

It's a totally legit use of issue here.


To answer your issue, overlapping is not supported due to issue with some client. You can use a background image to fake it, with mj-wrapper, here. It's not perfect but at least you'll have the desired effect.
