### ISSUE TITLE
I have problem with placing a button in an email list (Go-To Actions - Microdata)

### ISSUE THREAD

**Issue by dawidglk** [mjmlio/mjml#2627]
I put mircrodata according to the documentation but unfortunately on gmail I don't see the button am I doing something wrong from the mjml site ? 

**My mjml code**
`
<mjml>
    <mj-raw>
      <div itemscope itemtype="http://schema.org/EmailMessage">
        <div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction">
          <link itemprop="target" href="https://xx.io"/>
          <meta itemprop="name" content="Verify "/>
        </div>
      </div>
    </mj-raw>
  <mj-body >
    <mj-include path="header.mjml" />
    </mj-body>
    </mjml>
`

**Comment by iRyusa** [comment]
Most likely come from the way you're sending the email MJML generated proper HTML at the end so that's not an issue from our side
