### ISSUE TITLE
Mobile breakpoint doesn't work in gmail

### ISSUE THREAD

**Issue by simon-abbott** [mjmlio/mjml#2629]
**Describe the bug**
I created a multi-column email in mjml and carefully tuned the `mj-breakpoint` to ensure it switches to the mobile layout at the correct width. I tested it locally, and in my native mail program (I use Spark v2), and everything worked just fine. However, as soon as I tried to view the email in the gmail web client I noticed a problem. The email was compressing far more than it should before switching to the mobile version. After looking into the inspector in my web browser I discovered that gmail is not embedding the emails in `<iframe>`s. Instead, it is just dumping the (sanitized) html directly into the rest of the page. This means that the `@media` queries are based on the _browser_ width, not the _email_ width. This is a problem because the gmail webapp has a a lot of horizontal space on both sides of the email (especially on the left though). What can be done about this?

**To Reproduce**
1. Create a multi-column email
2. Set the `mj-breakpoint` relatively high
3. View the email in the gmail web app

**Expected behavior**
The email should switch to the "mobile" version when it reaches the correct width.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.13.0
 - MJML tool used: the npm package

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: Courier

**Affected email clients (for rendering issues):**
 - Email Client: Gmail
 - OS: MacOS
 - Browser: All (only Chrome and Firefox tested)

**Screenshots**

**Additional context**

**Comment by iRyusa** [comment]
It's not really related to MJML because this is how media queries work. Containers queries are relatively new and I don't think its yet supported by gmail https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries
