### ISSUE TITLE
Background image doesn't fill container in Outlook

### ISSUE THREAD

**Issue by lorenzwoehr** [mjmlio/mjml#2632]
**Describe the bug**
In Outlook Microsoft 365 MSO, the background image doesn't cover the whole section. Seems like `backgroundUrl` creates a second column. 

```
<MjmlWrapper paddingBottom={space.xxl}>
  <MjmlSection
    backgroundUrl={backgroundUrl}
    backgroundSize="cover"
    backgroundColor={colors.grey[500]}
    paddingTop={space.md}
    paddingBottom={breakpoints.maxWidth - space.xl}
  >
    <MjmlColumn>
      <Text size="body" align="center">
        Logo
      </Text>
    </MjmlColumn>
  </MjmlSection>
  <Header />
</MjmlWrapper>
```

**Expected behavior**
The background image should fill the whole container. 

**MJML environment (please complete the following information):**
 - MacOS
 - MJML Version 4.13.0

**Email sending environment(for rendering issues)**:
 - Klaviyo 

**Affected email clients (for rendering issues):**
- Microsoft® Outlook® Microsoft 365 MSO (Version 2301 Build 16.0.16026.20002) 64 Bit 

**Screenshots**
<img width="827" alt="image" src="https://user-images.githubusercontent.com/5892374/218498910-101fb990-746a-42c5-bf52-3a4b00d35e16.png">

Expected behaviour:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/5892374/218499196-ef53f73a-a1fa-4fa0-b917-ab4ede13d58e.png">

**Comment by iRyusa** [comment]
Hi can you give a proper MJML to reproduce here ?

I know that Klaviyo alter the HTML, can you try with https://putsmail.com/ ? (make sure to NOT check the "inline CSS")

**Comment by lorenzwoehr** [comment]
Klaviyo indeed altered the html. Looks correct in putsemail.com 

Thank you!
