### ISSUE TITLE
How to achieved 4 hero in the same line

### ISSUE THREAD

**Issue by lechuhuuha** [mjmlio/mjml#2633]
Hi im new to mjml and using grapesjs-mjml to build email template

Was wondering how i can achieved this html using mjml
![image](https://user-images.githubusercontent.com/59781669/218984012-8bd3c5ef-afe6-4eca-b675-44e1e314a1fb.png)

By using mjml,  I dont see any option to do 4 columns with background-image or 4 hero in the same line

Thanks

**Comment by iRyusa** [comment]
Well background image in columns is not supported because we're not confident about the compatibility on this one.

You can do a 4 column layout with a fallback `background-color` and apply the `background-image` with `mj-style` + `css-class`

**Comment by lechuhuuha** [comment]
> Well background image in columns is not supported because we're not confident about the compatibility on this one.
> 
> You can do a 4 column layout with a fallback `background-color` and apply the `background-image` with `mj-style` + `css-class`

thanks i will stick with the options you provided
