### ISSUE TITLE
need to disable responsiveness. 

### ISSUE THREAD

**Issue by draglabs** [mjmlio/mjml#2634]
**Responsiveness on desktop breaks my layouts**
This is driving me crazy! if you look in the image below, you will see a section to an email with two columns which CANNOT go out. And thinking more critically when would a user ever look at an email on a desktop computer or any machine with more than 450 px available and not be able to expand to 600px? Also what displays legitimately only have 550 px available to view an email?

**I would like to disable desktop responsiveness at the mj-body tag**
*** so we still want break points, and mobile responsiveness, just NO fluid responsiveness before the break.***
We accept that email is not meant to be fully responsive and want the desktop version of the email to be 600 px wide, and we want the mobile (only) to be responsive. 

**Describe alternatives you've considered**
We have considered using images instead of letters on the left column. (but that makes it uneditable)
We have considered using media calls to break at anything under 600px wide, (that makes a big ugly image, or the same problem)
We have considered hacking mjml to stop it from resizing using min-width or <mj-column css-class:"min-width:300px" but that either does not work, or starts breaking mjml. 
We have considered going back to Iterable drag and drop and forgetting about MJML
We have tried extensively to get chat gpt to answer this one... 
We have tried making an array of media calls to adaptively change the font size at every screen size interval. 

**Additional context**
The email should look like this... 
<img width="950" alt="Screenshot 2023-02-19 at 7 27 36 PM" src="https://user-images.githubusercontent.com/17034358/219984841-c409848a-f6e5-473a-a989-e55b9b2e49c6.png">

Not like this...
<img width="812" alt="Screenshot 2023-02-19 at 7 16 14 PM" src="https://user-images.githubusercontent.com/17034358/219984346-d75e3e98-86b6-4431-abb6-79cd70fe2bb3.png">

**Comment by iRyusa** [comment]
> And thinking more critically when would a user ever look at an email on a desktop computer or any machine with more than 450 px available and not be able to expand to 600px? Also what displays legitimately only have 550 px available to view an email?
Then why you bother check how it render if you don't think this is important.

This is how Fluid Hybrid technique works, if it doesn't fit with your need just switch to another framework that doesn't follow this principle. Just write some media queries that override `padding` / `font-size` and you should be fine.
