### ISSUE TITLE
Improve documentation around `<mj-preview>`

### ISSUE THREAD

**Issue by nbouvrette** [mjmlio/mjml#2635]
**Is your feature request related to a problem? Please describe.**
I have been investigating deliverability issues for a while now. Most emails would work but in some case they would be flagged as spam. After further investigation I found this article:

https://support.google.com/mail/answer/81126

> Don’t use HTML and CSS to hide content in your messages. Hiding content might cause messages to be marked as spam.

**Describe the solution you'd like**
To avoid misguiding users, there should be a clear warning in the documentation about the risk behind using `<mj-preview>`.

**Describe alternatives you've considered**
I am no longer using `<mj-preview>` (I wish I would have known about the risk earlier)

**Additional context**
N/A

**Comment by nbouvrette** [comment]
Of course but for those who are using an MJML template for transactional emails, I think it's worth highlighting the risks. Especially that this is coming directly from one of the largest email providers's documentation

**Comment by iRyusa** [comment]
Mailjet does send millions of transactional email with MJML without any issue with text preview enabled for most of them. 

It's more likely an issue with your ESP reputation than content of the email here.

**Comment by iRyusa** [comment]
I really doubt you would use Gmail as an ESP for transactionnal email as
the limit is really low
https://support.google.com/mail/thread/47871468?hl=en ? Or am I missing
somthing

**Comment by nbouvrette** [comment]
Seems like this thread is a bit out of date. When you use Gmail's SMTP relay service you have a 10,000 daily limit for Gsuite accounts. More details here: https://www.gmass.co/blog/you-can-now-send-10000-emails-with-gmass-and-gmail/

Anyhow, I think this is going a bit above my intent when creating this issue. As you said there are many factors that impact deliverability. One of them is using hidden content.

I think for most people sending transactional emails such as account creation and password reset, if they have to pick between an email preview or 1% (just using a random number) deliverability increase, they would not use `<mj-preview>`

I think it would be fair to add extra clarity there based on my personal experience

**Comment by iRyusa** [comment]
We don’t observe any impact on using mj-preview on our end. So we won’t add anything about this. If it’s the only reason for you that trigger spam filter then just remove it and people might find your issue by looking for a similar behavior. But again i highly doubt this is the reason that your emails are flagged as spam.On 21 Feb 2023, at 18:45, Nicolas Bouvrette ***@***.***> wrote:﻿
Seems like this thread is a bit out of date. When you use Gmail's SMTP relay service you have a 10,000 daily limit for Gsuite accounts. More details here: https://www.gmass.co/blog/you-can-now-send-10000-emails-with-gmass-and-gmail/
Anyhow, I think this is going a bit above my intent when creating this issue. As you said there are many factors that impact deliverability. One of them is using hidden content.
I think for most people sending transactional emails such as account creation and password reset, if they have to pick between an email preview or 1% (just using a random number) deliverability increase, they would not use <mj-preview>
I think it would be fair to add extra clarity there based on my personal experience

**Comment by nbouvrette** [comment]
Also, using a text version of the email can help with deliverability - when you have hidden content, the difference between the text and HTML content differs which makes the email more suspicious. In my case after I removed the email preview, and re-aligned both the text and HTML version, one of the cases that was detecting my email as spam stopped.

So there are in my opinion drawbacks to using preview - it might be a very small portion of emails but treating it just like this is standard practice can be misleading in my opinion.
