### ISSUE TITLE
mj-accordion and mj-carousel use cell-spacing and cell-padding instead of cellspacing and cellpadding

### ISSUE THREAD

**Issue by caseyjhol** [mjmlio/mjml#2636]
**Describe the bug**
The mj-accordion and mj-carousel components use `cell-spacing` and `cell-padding` attributes instead of `cellspacing` and `cellpadding`. This is invalid HTML (not supported in Chrome and likely other browsers) and does not align with the attributes other components use. 

![image](https://user-images.githubusercontent.com/2874325/220405414-39b4720a-0b40-4dfe-aa08-f2ee2153683b.png)

**Comment by iRyusa** [comment]
Totally a typo here, even if it's just here as a reset, let's fix that
