### ISSUE TITLE
width="600" break for large screen and Outlook

### ISSUE THREAD

**Issue by Thot80** [mjmlio/mjml#2637]
**Describe the bug**

I'm building emails with mjml and it seems that the width=600 attribute break on outlook desktop and  specifics situations.
Parts of the email take more than 600px, full width indeed.

Outlook version : 
Microsoft® Outlook® pour Microsoft 365 MSO (Version 2208 Build 16.0.15601.20446) 64 bits
Screen résolution 1920x1080
Screen size 14 inches

Most strange thing is that if i click on the mirror link of the email, gather the source  code and paste it in putsmail (https://putsmail.com/) the issue disappear. 

**PS: Sorry, i was never able to make the header parts of the code renders correctly... You will find a screenshot of it below**

**To Reproduce**
1. Create a file with this MJML code: `<mjml>

         
        <mj-section>
            <mj-column>
                <mj-raw>
                    %%=ContentBlockByKey("MIRROR_BLOCK")=%%
                </mj-raw>
                <mj-text color="#6F6E77" mj-class="textDirection" css-class="darkText">
                    %%=v(@preheader)=%%
                </mj-text>
            </mj-column>
        </mj-section>
        
        <mj-section>
            <mj-column>
                <mj-image src="%%=v(@urlLogo)=%%" alt="ALL Accor Live Limitless" width="192px" />
                <mj-spacer height="20px" />
            </mj-column>
        </mj-section>
        
        <mj-section>
            <mj-column>
                <mj-text font-size="14px" line-height="18px" css-class="darkText" mj-class="textDirection">
                    %%=v(@salutation)=%%
                </mj-text>
                <mj-text font-size="14px" line-height="18px" mj-class="textDirection" css-class="darkText">
                    %%=v(@content_text1)=%%
                </mj-text>
                <mj-text font-size="14px" line-height="18px" mj-class="textDirection" css-class="darkText">
                    %%=v(@content_text2)=%%
                </mj-text>
                <mj-text font-size="14px" line-height="18px" mj-class="textDirection" css-class="darkText">
                    %%=v(@content_text3)=%%
                </mj-text>
                <mj-text font-size="14px" line-height="18px" mj-class="textDirection" css-class="darkText">
                    %%=v(@signature)=%%
                </mj-text>
            </mj-column>
        </mj-section>
        <mj-section>
            <mj-column >
                <mj-button font-size="12px" line-height= 
                "16px" color="#6F6E77" background-color="#FFF" font-weight="400" padding-left="20px" padding-right="20px" padding-top="12px" padding-bottom="12px" border="1px solid" mj-class="textDirection" href="%%= RedirectTo(@cta_url)=%%" css-class="cta"> 
                    <font class="ctaText">%%=v(@cta_text)=%%</font> 
                </mj-button>
            </mj-column>
        </mj-section>
        <mj-section>
            <mj-column>
                <mj-spacer height="10px" />
            </mj-column>
        </mj-section>
        
        <mj-section  css-class="footer">
            <mj-column css-class="footer">
                <mj-text  color="#6F6E77" align="left" line-height="12px" padding-bottom="0" mj-class="textDirection">                
                    %%=v(@footer_ml_copyright)=%%
                </mj-text>
                <mj-raw>
                    %%[IF @footer_ml_image != '' THEN ]%%
                </mj-raw>
                <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection">
                     %%=v(@footer_ml_image)=%%
                </mj-text>
                 <mj-raw>
                    %%[ENDIF]%%
                </mj-raw>
                <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection">
                    %%=v(@footer_ml_terms_conditions)=%%
                </mj-text>
                 <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection">
                    %%=v(@footer_ml_email_registration)=%%
                </mj-text>
                 <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection">
                    %%=v(@footer_ml_data_protection)=%%
                </mj-text>
                 <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection">
                    %%=v(@footer_ml_data_privacy)=%%
                </mj-text>
                <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection"> 
                   %%=v(@footer_ml_accor)=%%
                </mj-text>
                <mj-raw>
                    %%[IF @footer_ml_points != '' THEN ]%%
                </mj-raw>
                <mj-text color="#6F6E77" align="left" line-height="14px" padding-bottom="0" mj-class="textDirection">
                     %%=v(@footer_ml_points)=%%
                </mj-text>
                 <mj-raw>
                    %%[ENDIF]%%
                </mj-raw>
            </mj-column>
        </mj-section>
        <mj-raw>
            %%= ContentBlockByKey("Email_SendLog_Custom")=%%
        </mj-raw>
    </mj-body>    
</mjml>`

3. Render it to HTML by doing 'MJML: Export HTML in VSCode'
4. Send the HTML to an email address with 'Our email are send with SFMC triggered send API'
5. See error

**Expected behavior**
I would expect email layout to be 600px large.

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version 4.2.0
 - MJML tool used : attilabuti.vscode-mjml   https://github.com/attilabuti/vscode-mjml

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [Salesforce Marketing Cloud]  

**Affected email clients (for rendering issues):**
 - Email Client Microsoft® Outlook® pour Microsoft 365 MSO (Version 2208 Build 16.0.15601.20446) 64 bits
 - OS:  Windows
 - Browser none - Desktop

**Screenshots**

headers attributes : 
![header_mjml](https://user-images.githubusercontent.com/72084982/220410036-6819783f-68f0-446e-8377-a1bbdb121c2f.jpg)

Error
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/72084982/220398246-4026be90-d440-4e12-bc09-7e2c0f83e6ec.png)

Expected : 
![error_putlook](https://user-images.githubusercontent.com/72084982/220400436-fa9ec945-d369-4bee-a9ee-5f84a3ade65b.jpg)

Code extracted from .eml file from a user seems strip of all mso specific comments whereas it has them when extracted from my own outlook desktop app.

![mso_strip](https://user-images.githubusercontent.com/72084982/220411684-d15f4b49-7c4e-4a11-bb37-f9aea91617a9.jpg)

**Additional context**

Emails are tested with litmus and the problem wasn't detectable there, this was signaled from real use case.

**Thanks !**
Thank you for having develop this tool, i'm a big fan :)
Thanks for your help regarding this.

**Comment by iRyusa** [comment]
If it works in putsmail.com then it comes from the way you send the email, not from us.

Try to remove any post-processing that you can with your ESP or contact them.
