### ISSUE TITLE
background-url breaks layout in Windows Mail

### ISSUE THREAD

**Issue by vaishnavi-accountbox** [mjmlio/mjml#2641]
Describe the bug
When using background-url on an mj-section or mj-wrapper, in Windows Mail the email looks broken (collapsed to the left, no readable text)

To Reproduce

```
 <mjml>
  <mj-body>
    <mj-section full-width="full-width"
                background-url="https://i.gyazo.com/b48b12795432d97952f7dc48788c1724.png"
                background-color="blue">
      <mj-column background-color="red">
        <mj-text font-size="40px">
          This is the text
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
 </mjml>

```
Expected behavior
Background image might not be visible (I think Winodws Mail does not support them), but the layout should be preserved

MJML environment (please complete the following information):

OS: Windows 11
MJML Version 4.13.0
Email sending environment(for rendering issues):

Windows Mail
<img width="544" alt="188626555-ac12453c-9835-4fc1-b919-0411058378d6" src="https://user-images.githubusercontent.com/24909083/221175234-17c5a1c3-240a-46e0-8037-569b892405d2.png">

**Comment by iRyusa** [comment]
Can you try with multiple section ?

**Comment by vaishnavi-accountbox** [comment]
Tried with multiple sections as well, But no luck, Please help!

**Comment by iRyusa** [comment]
I can't reproduce with multiple section in email https://mjml.io/try-it-live/0nfm6GtDX can you confirm ?
