### ISSUE TITLE
MJML Carousel Bug

### ISSUE THREAD

**Issue by rustemia98** [mjmlio/mjml#2642]
Dear MJMLIO team,

I am currently creating a new template using MJML and have incorporated the MJML carousel into it. However, I am facing an issue with the rendering of the carousel in Gmail and Outlook. The carousel appears to be working perfectly fine when I preview it in VS Code, but when I send it to either Gmail or Outlook, I notice that the side icons on the left and right are missing. Additionally, in Outlook, the thumbnails are also missing.

I have tried to troubleshoot the issue by researching online and checking the MJML documentation, but I have not been able to find a solution. Could you please suggest any workarounds that I can implement to resolve this issue and ensure that the carousel renders correctly in both Gmail and Outlook?

Thank you for your assistance.

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version v1.6.0
 - MJML VS Code, Nodemailer

**Email sending environment(for rendering issues)**:
 - Putsmail, Mautic and nodemailer 

**Affected email clients (for rendering issues):**
 - Email Client: Gmail, Outlook 
 - OS: Windows, MacOS
 - Browser Google Chrome, Edge

**Screenshots**

Is:
![Screenshot 2023-02-27 092736](https://user-images.githubusercontent.com/80360222/221512683-c0677bb9-d62f-46ec-8ba5-21cb45fac624.jpeg)

Should:
![Screenshot 2023-02-27 092919](https://user-images.githubusercontent.com/80360222/221512731-ddde456f-fd5c-4c93-86f2-fd43821ddceb.jpeg)

**Comment by iRyusa** [comment]
If email client doesnt' support click interaction it will fallback to this. Gmail is a special case, as it doesn't support click interaction but  `hover` feature works fine for thumbnails so we display them.
