### ISSUE TITLE
`mj-section` with a background image inside `mj-wrapper` is horizontally mis-aligned on Outlook for Windows

### ISSUE THREAD

**Issue by nothingnesses** [mjmlio/mjml#2646]
**Describe the bug**
`mj-section` with a background image inside `mj-wrapper` is vertically mis-aligned on Outlook for Windows.

**To Reproduce**
1. Copy the HTML [output from here](https://mjml.io/try-it-live/WrkS22dbw). Currently, the page is using MJML version 4.9.3. In case the page goes down, the original MJML code I used is [also accessible here](https://gist.github.com/nothingnesses/28deabe3d85309f580c46fd18d5603e6).
2. Send the HTML to an Outlook email address with Litmus Putsmail.
3. Notice that the grey box starts at the far left and the gradient background image is only visible to the top, right and bottom of the grey box, instead of on all sides. The image is also squished to the left and the grey box isn't visible there.

**Expected behavior**
Output is the same as the output on MJML Try it Live.

**MJML environment (please complete the following information):**
 - OS: Microsoft Windows 11 Home 10.0.22000 N/A Build 22000
 - MJML Version: 4.9.3
 - MJML tool used: Try it Live

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: [Putsmail](https://putsmail.com/)

**Affected email clients (for rendering issues):**
 - Email Client: Microsoft Outlook for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20186) 64-bit
 - OS: Windows

**Screenshots**
### Output on MJML Try it Live
![Output on MJML Try it Live](https://user-images.githubusercontent.com/18732253/224547973-ed5eb6b6-91d1-4de9-a66e-9eb4551ed84f.png)

### Output on Outlook
![Output on Outlook](https://user-images.githubusercontent.com/18732253/224547980-ca41cecd-05ee-4a94-a2d6-85e8199c3d5e.png)

**Comment by iRyusa** [comment]
That's a known issue with table and padding (padding left is applied to right instead) within a VML block, sadly not so much we can do about this..
It looks like margin is not affected by this behavior tho and might lead to a potential fix

**Comment by iRyusa** [comment]
Can't find the other issue but there's an open issue about this. Try to avoid padding left/right as much as you can inside a VML section
