### ISSUE TITLE
jsp tags in mjml

### ISSUE THREAD

**Issue by TomCatSK** [mjmlio/mjml#2648]
JSP tag is broken

I need use jsp tag in mjml file, but converted jsp tag in html is broken. Is it possible to use jsp tag in mjml or not?

mjml code:
`<mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          <%= targetData.Text03 %>
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>`

and resulted html code is:

`<div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;" data-id="42"><%= targetData.Text03="" %=""/></div>`

jsp tag <%= targetData.Text03 %> was changed to <%= targetData.Text03="" %=""/>

**Comment by iRyusa** [comment]
There's no issue here : https://mjml.io/try-it-live/5E17VpAOI

Maybe you're using mj-style inline/mj-html-attributes those doesn't behave properly with templating tag that looks like actual html tags.

**Comment by TomCatSK** [comment]
Yes, I use mj-html-attribute, is it probleme? - https://mjml.io/try-it-live/-_aUEJVlU
Is there any way to solve it?

**Comment by iRyusa** [comment]
Yup this is something that we can't fix as mj-html-attributes need to reparse the actual dom to apply attributes, and by doing so, anything that "looks" like a tag will be parsed as is.

**Comment by TomCatSK** [comment]
OK, otherwise, is there another way to get the parameter _label parameter into the <a> element when it is generated for example via mj-button or mj-social-element (don't use mj-html-attributes) ? - https://mjml.io/try-it-live/D7I56I-wf

**Comment by iRyusa** [comment]
You can wrap them into a span tag like this https://mjml.io/try-it-live/LatZvGDjb ?

**Comment by TomCatSK** [comment]
This is not possible, the _label must be directly in the element **<a href="#" _label="link_payment"....>**.  Some other solution ?

**Comment by iRyusa** [comment]
Nop nothing we can do about this particular case then
