### ISSUE TITLE
Ignore reserved words from template engines

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [mjmlio/mjml#265]
Hi there!

I'm using mjml to generate a .blade.php e-mail file, which is then send to Laravel to parse it, set some var values, and send it to the user. In other words, the generated mjml is not the final html.

The problem: mjml don't like some reserved words.

For example, in Laravel Blade we may need to change what piece of info in send in the e-mail by checking some $var, using blade syntaxe:

```
@if ($var == true)
    <some-mjml>true</some-mjml>
@else
    <another-mjml>false</another-mjml>
@endif
```

In the situation above, mjml don't like `@`, making the generate mjml broken to be read by Laravel. But in this situation, each @ statement can be nested with `<mj-raw>`. It is not pretty, but works.

The real problem comes with `href` attributes in `<mj-button>`, or any other attribute. In this situation, we usually do something like this:

`<mj-button href={{ $user->getMegaFancyUrl() }}></mj-button>`

To Laravel Blade, everything between {{ }} is echoed out, so before the e-mail is sent, the final url is returned and the user receives an e-mail with the correct url.

But, MJML don't like some chars between those {{ }}, making the generated mjml file full with escaped chars. When Laravel receives this, it tries to parse and fails.

To solve this, I have to generate the url before hand, and use in mjml in a simplier way, something like {{ $my_final_url }}. But that is not always the case...

So, since mjml may be used with lots of other frameworks and templates engines, wouldn't be better if we can set, in a prettier way, what mjml should ignore and not parse at all? Something like mj-raw, but which works everywhere, not only between elements.

Or even better, something like: `mjml -r input.mjml -o output.blade.php -laravel`

So MJML would know which reserved words should not be escaped.

Thanks :)

**Comment by rafael-renan-pacheco** [comment]
\**Marketing on*\*

If MJML could generate Laravel blade files without breaking their syntaxe, it would be a nice showcase to put it on MJML website.

MJML website with the words `E-mail`, `Responsive`, and `Laravel`? Oh my...

\**Marketing off*\*

**Comment by iRyusa** [comment]
Hello @rafael-renan-pacheco 

It would be nice, but it's not what's MJML want to achieve. My opinion is Blade template should be applied __before__ MJML and here's why:

MJML has some internal logic and conditionnal column / section can break it: MJML has no way to know if you `else/if` statement is true or not. That's why put inside `mj-raw` handlebars & other templating language is a bad idea. Example : 

```xml
<mj-section>
  <mj-raw> { if my_var == 42 } </mj-raw>
  <mj-column> ... </mj-column>
  </mj-raw> { end if } </mj-raw>
  <mj-column> ... </mj-column>
</mj-section>
```
MJML will generate media queries for 2 column here. So column will be 50% even if my condition is `true` or `false`

Here's how my flow would be if I work in a Ruby environment : 
```erb
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <% if false %>
          <mj-column>
            <mj-text> You won't see me :(</mj-text>
          </mj-column>
        <% end %>
        <mj-column>
          <mj-text> Happy face :                      ^)</mj-text>
        </mj-column>
      </mj-section>
    </mj-container
  </mj-body>
</mjml>
```

I'll let ERB generate the correct MJML for me : 
```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>

        <mj-column>
          <mj-text> Happy face :                      ^)</mj-text>
        </mj-column>
      </mj-section>
    </mj-container
  </mj-body>
</mjml>
```

Then pass it to the MJML-core to have my html file.

ERB > MJML > HTML
becomes in Laravel
Blade > MJML > HTML

I have no idea how Laravel works, but I know this is possible in a Ruby application so it should be doable in a PHP environment too. Does it makes sense to you ?

**Comment by rafael-renan-pacheco** [comment]
Hi @iRyusa!

Yes, the "Blade first" approach does make sense. But this implies that, for each e-mail that I send, I have to Blade it and MJML it every time to have the desired final HTML, right?

Since e-mails are usually processed by queue jobs, async from the main app, I guess the user won't even notice a few seconds of delay to receive the e-mail.

I'll try this approach as soon as I can, thank you for your suggestion :+1:

**Comment by crabmusket** [comment]
If anyone else is trying to do this, [here's](https://laracasts.com/discuss/channels/laravel/post-processing-email-views) roughly how I did it. Getting MJML to run on an email _after_ blade wasn't the most obvious thing.

**Comment by thetutlage** [comment]
Yes, this isn't the ideal approach, since we cannot cache the output. Have to first render using the template engine (coz data can be dynamic) and then use the output (which is MJML) and then convert it again.

**Comment by nandi95** [comment]
This also means that mjml needs to be installed where this runs. Which means npm/node has to be set up.
