### ISSUE TITLE
mj-section background-image not display and mj-image not show completely in outlook

### ISSUE THREAD

**Issue by xlnhaha** [mjmlio/mjml#2652]
Hi, there are two issues:
environment: outlook 2016(desktop)
1, background-image didn't show in outllook
2, mj-image didn't show completely

Details:

code:
`<mjml>
  <mj-body>
    <mj-section full-width="full-width" background-color="black" background-url="https://static.vecteezy.com/packs/media/vectors/term-bg-1-3d6355ab.jpg" background-size="contain">
      <mj-column width="100%">
      <mj-text align="center" color="red" font-size="40px">hhhh</mj-text>
        <mj-image align="center" width="300" src="https://documentation.mjml.io/images/logo.png"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>`
mjml preview like this:
![image](https://user-images.githubusercontent.com/34709921/226078037-576c2bfc-c00e-474a-97ab-d9650ba80dc6.png)

outlook show like this:

![image](https://user-images.githubusercontent.com/34709921/226078021-5672f846-fb37-4ee2-91f3-bebb64d021b3.png)

Thank you.

**Comment by iRyusa** [comment]
Most likely due to default line-height of mj-text can you try to reset it to `1` instead ?
