### ISSUE TITLE
Attriutes from JSON format are not escaped

### ISSUE THREAD

**Issue by 3bl3gamer** [mjmlio/mjml#2656]
**Describe the bug**
`&` and `"` are not escaped in attributes passed via JSON format.

**To Reproduce**
```js
import mjml2html from "mjml";

console.log(
  mjml2html({
    tagName: "mjml",
    children: [
      {
        tagName: "mj-body",
        children: [
          {
            tagName: "mj-section",
            children: [
              {
                tagName: "mj-column",
                children: [
                  {
                    tagName: "mj-image",
                    attributes: {
                      alt: '& and "quotes".',
                      title: '& and "quotes".',
                    },
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  }).html
);
```

It outputs a string with `<img alt="& and "quotes"." ... title="& and "quotes"." ... />` so this attributes are read by browser/client parser as `alt="&amp; and "` and `quotes"."=""`.

**Expected behavior**
`<img alt="&amp; and &quot;quotes&quot;." ... `

**MJML environment:**
 - OS: Arch Linux
 - MJML Version:  4.13.0

**Comment by iRyusa** [comment]
> MJML Version: 4.2.0

I'm pretty sure this has been fixed in later version here, 4.2 is a bit old.

**Comment by 3bl3gamer** [comment]
Oops, it was actually `mjml@4.13.0` (just forgot to change this in issue template). Updated the first message.

**Comment by iRyusa** [comment]
Ok I've misunderstood the ticket, you want attributes to be encoded automatically. We won't really do that as it could be an issue for people using templating language in attributes.
