### ISSUE TITLE
mj-spacer creates odd whitespace in email client preview

### ISSUE THREAD

**Issue by internationalmagic** [mjmlio/mjml#2659]
**Describe the bug**
The mj-spacer module produces white space on email preview on mail app (mac). Every <mj-spacer></mj-spacer> with a height or padding parameter, regardless of the position in the DOM produces a whitespace step on the message preview panel.

**Please see the screenshot below**

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2. Add some <mj-spacer height="32px"/> 
3. Send the HTML to an email address from within the mjml app

**Expected behavior**
Whitespace is prepended to the message preview.

**MJML environment:**
 - OS: MacOS
 - MJML Version v3.0.4
 - MJML App v^4.12.0

**Email sending environment**:
 - [mailjet](https://mailjet.com/)

**Affected email clients (for rendering issues):**
 - Email Client: Apple Mail
 - OS: Mac

**Screenshots**
<img width="297" alt="image" src="https://user-images.githubusercontent.com/30148191/227765311-7c65b0d2-2b6c-4ff7-9897-fdc3645f0a1f.png">

**Additional context**
The more mj-spacer you add the bigger the whitespace. Regardless of the height or padding value of the mj-spacer, the space that is prepended remains the same … it seems like an odd empty character. Also I figured that self-closing or css-class or mj-class references make no difference.

**Comment by iRyusa** [comment]
Yeah `mj-spacer` has a non visible character to ensure it get displayed on some clients. Just use `padding` if it bother you.

**Comment by StefanEndress** [comment]
I figured that mj-preview in the head handles the mail app problem!

Maybe some documentation on the mj-spacer section would do the trick.
