### ISSUE TITLE
Issue with border radius on section and column

### ISSUE THREAD

**Issue by vaishnavi-accountbox** [mjmlio/mjml#2660]
Hi MJML Team,

   Border radius is not working on section and,  as well as column. Can some please look in to this and suggest me a solution.

**Comment by iRyusa** [comment]
This is because we use border-collapse on table to ensure compatibility for Outlook. You can override this with mj-style to `separate`.

**Comment by szaleq** [comment]
@iRyusa Why apply `border` to `td` then, if both `border-radius` and `background-color` gets applied to surrounding `div`?
Here is the example MJML:
https://mjml.io/try-it-live/kx2qQEPU-S

And here is a Pen with `border` property moved from `td` to the `div`: https://codepen.io/szaleq/pen/gOJGxbJ

Why not render it this way?

**Comment by iRyusa** [comment]
Because not every email client support border on div elements
