### ISSUE TITLE
Error: Request Entity Too Large in try-it-live & rest api

### ISSUE THREAD

**Issue by aksld** [mjmlio/mjml#2663]
Hello,

I would like to reopen the issue because I have this error message in the try-it-live console.

My file is 1947 lines long. This is a lot but necessary for a business logic. Is there a limit? Thanks

**MJML environment:**
 - OS: MacOS
 - MJML Version: 4.9.3
 - MJML tool used: MJML API and try-it-live

**Comment by iRyusa** [comment]
It's not really about the line limit but the size of the payload. Keep in mind if your mjml is 1950 line there's a high chance that your email will be clipped by some email clients.

Can you share the payload you're trying to compile somewhere ?

**Comment by aksld** [comment]
Let's just say I'm aware that it might get cut off but it's really only a specific email for a few people. So I'll be able to control the display.

Can I share it privately? There's some data. 

Thanks for your help

**Comment by iRyusa** [comment]
I'm on MJML slack if you want
