### ISSUE TITLE
Formal specification

### ISSUE THREAD

**Issue by Southclaws** [mjmlio/mjml#2667]
Hey!

First of all, love this tool, thanks for building it and making email templates less painful!

So I've been wondering if there have ever been any efforts to somewhat formally specify MJML's behaviour? I ask because our stack is generally always Golang and I've been trimming down our build dependencies recently and currently, the only reason we need to install Node in our CI is to run MJML, which adds a significant amount of time onto the build. JS is great, but the runtime is quite heavy, especially for systems/dev tooling.

And with that, I played around with the idea of replicating what MJML is doing in a more lighter weight and easier to distribute language such as Go. But this would be difficult to build and validate without a formal specification to build and test against.

I'm also just curious what the rationale is behind certain transformations. It seems like MJML is a simple mapping function that can be described as transforming from one XML tree to another XML tree. Are these transformations documented anywhere?

Thanks!

**Comment by iRyusa** [comment]
Nop there's no specification of this as it's a bit hard to maintain such a thing. There's some people in the community that re-implement from scratch MJML (https://documentation.mjml.io/#ports-and-language-bindings) but still lacking some features.
