### ISSUE TITLE
Please update `cheerio` to latest

### ISSUE THREAD

**Issue by Semigradsky** [mjmlio/mjml#2668]
`mjml-core@4.14.0` uses `cheerio@1.0.0-rc.10` and `juice@9` uses `cheerio@1.0.0-rc.12` (latest). So we currently have many package duplications with different versions in node_modules:
- dom-serializer
- domhandler
- htmlparser2
- parse5
- parse5-htmlparser2-tree-adapter
- css-select
- domutils
- ...

**Comment by iRyusa** [comment]
👋 Will merge this next week and release in 4.14.1 thanks

**Comment by iRyusa** [comment]
Should be good in 4.14.1 !
