### ISSUE TITLE
Display different layout in MJML App Preview and Outlook

### ISSUE THREAD

**Issue by jefferyleo** [mjmlio/mjml#2671]
I have designed an email where you can see from [here ](https://mjml.io/try-it-live/DQKtKaUgO), the problem is happening in footer social icons and download buttons. The MJML App is displayed the design perfectly, however when I tried to send a test email and view in different email platform, I found out Outlook Desktop in Windows 11 and Outlook App in Windows 11 are showing different layout in footer compared to Outlook Web.

Does anyone know what happened? Is the problem happened in my mjml code?

  **Reproduction Steps:**

  1. View in https://mjml.io/try-it-live/DQKtKaUgO
  2. Copy over the MJML code to MJML Desktop App
  3. Send test email to your own email
  4. Open in Outlook App Desktop and Outlook Web to see the difference.

  **Expected behavior:**

  ![image](https://user-images.githubusercontent.com/6831609/231104055-4e9678fa-efc0-4201-8440-1afc65c7010b.png)

  The "Connect with us" and social icons should be up and down instead of left and right

  **Observed behavior:**

  ![image](https://user-images.githubusercontent.com/6831609/231104252-4a76916c-c03a-46c6-a122-146decf6736e.png)
 
  This is what happened in Outlook Desktop App.

  **MJML version:**

  MJML Version 4.12.0

  **Email clients the bug is seen on:**

  - Outlook Desktop in Windows 11
  - Outlook Desktop App in Windows 11

**Comment by iRyusa** [comment]
You have more than 100% of content inside your group. Browser know how to handle this but  not Outlook.

You can just do a 2 column layout with 1 mj-text + 1 mj-social for each.

**Comment by jefferyleo** [comment]
@iRyusa may be can you show me an example for this?

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/YtKHhCvnv

**Comment by jefferyleo** [comment]
@iRyusa is it possible to change the social element to my own icon in this case?

**Comment by iRyusa** [comment]
![Screenshot 2023-04-11 at 11 14 01](https://user-images.githubusercontent.com/570317/231113832-459a3900-af96-4d40-968f-4d57924d1062.png)
Yes, everything is mentioned in the doc of mj-social

**Comment by jefferyleo** [comment]
@iRyusa I tried to make the icon with rectangular size, seems like it doesn't work even I set the `icon-size`, the icon is still in square form with the empty space for top and bottom of the image, any other way to achieve this?
