### ISSUE TITLE
mj-column width is ignor on some of web client 

### ISSUE THREAD

**Issue by j87x3inq2x3w7** [mjmlio/mjml#2672]
Hi, I used this basic mjml code:

```
<mj-section padding="0 0" border="1px solid red">
      <mj-column background-color="#00cb19" width="80px" border-radius="4px 4px 0px 0px" border="1px solid black">
      	<mj-text padding="0 0" color="white" font-size="12px" font-weight="600" line-height="20px" align="center" background-color="white">Reward</mj-text>
      </mj-column>
</mj-section>
```

and testing on email on acid, and see this, mj-column width is ignor on some of web client : 
![image](https://user-images.githubusercontent.com/60732910/232029798-f50d6662-fda4-42e6-92d6-298fbfd5496d.png)

mj-column, don't hold set 80px width on desktop view, any reason ?

**Comment by iRyusa** [comment]
Some desktop clients doesn't support media queries so it will display the mobile version instead.
There's no workaround for this.
