### ISSUE TITLE
mj-button looking weird and bigger then should be [ outlook desktop windows ]

### ISSUE THREAD

**Issue by j87x3inq2x3w7** [mjmlio/mjml#2673]
Hi, i used code like this:

```
<mj-section padding-top="0" padding-bottom="0" background-color="#4188ff" border-radius="0 0 6px 6px">
        <mj-column>
            <mj-button
              css-class="btn-block"
              width="100%"
              height="46px"
            	background-color="#00cb19"
              font-size="15px"
              font-weight="600"
              padding="8px 16px 16px 16px"
              href="https://">Some text
           </mj-button>
        </mj-column>
</mj-section>
```

and css:

```
.btn-block a {
      	display: block !important;
      }
```

Everywhere buton looking good except, outlook (all version) desktop windows. Button is sos big, example from email on acid:
![image](https://user-images.githubusercontent.com/60732910/232035040-288765fa-0e3e-472a-8fc2-15392ca480e0.png)

I add how it's look on macOS on outlook:
![image](https://user-images.githubusercontent.com/60732910/232035555-abd47522-5a98-46e0-bcba-e49e8d61ff69.png)

It's exceped on outlook on windows ? Any work around this ?

**Comment by iRyusa** [comment]
If you remove that display block does it behave as expected ?

**Comment by iRyusa** [comment]
Can you try with valid href pointing at google or something ? This might
happens with non valid href sometimes but without the full code to
reproduce it's really hard to help here.

**Comment by j87x3inq2x3w7** [comment]
> Can you try with valid href pointing at google or something ? This might
happens with non valid href sometimes
- can you elaborate on the problem? This is the first time I've heard of something like this, google didn't help either. any link?

> This happened to me in the past, Use a valid href link, it should fix the bug.
- can you elaborate on the problem? This is the first time I've heard of something like this, google didn't help either. any link?

i paste example link from email: 
![image](https://user-images.githubusercontent.com/60732910/232838338-9c1c5fa8-f5be-4567-8965-634f0d1804ca.png)

**Comment by j87x3inq2x3w7** [comment]
The problem was to minify the entire code in the loop, not just selected elements from mj-group. Or at least that helped.
