### ISSUE TITLE
Vertical Divider

### ISSUE THREAD

**Issue by ritikakhuranagoel** [mjmlio/mjml#2676]
**Is your feature request related to a problem? Please describe.**
Hi Team,I am looking for a vertical divider that I can use to separate out mj-text's. I tried to search for solutions out there and found that I have 2 options -
1. use a  `<span className={classes.donationValueDivider}>|</span>` where I can add this vertical kind of divider, which doesn't meet the height and font size related stuff for me. So, I ended up deciding not to use this. But this is very close to what I need.
2. use a border-right on my column, so I can get a vertical divider kind of a thing to be displayed. In that case, I end up getting the height of the divider the same as the column to which I am trying to add the border. I actually need the height of the divider to be much smaller than the column height itself.

**dweb design :**
<img width="621" alt="image (4)" src="https://user-images.githubusercontent.com/131602145/233846747-21889ff8-bdbc-4571-b6d3-2dd6c38ff680.png">

**mweb design:**
<img width="620" alt="image (5)" src="https://user-images.githubusercontent.com/131602145/233846762-29367e60-063c-4289-aa76-27eebad5cfc4.png">

If you notice, the dweb divider is much smaller than the mweb divider. 

**Describe the solution you'd like**
Like we have an mj-divider to add a horizontal divider, can we have something similar for a vertical divider also?

**Describe alternatives you've considered**
Like I mentioned above :
1. use a  `<span className={classes.donationValueDivider}>|</span>` where I can add this vertical kind of divider, which doesn't meet the height and font size related stuff for me. So, I ended up deciding not to use this. But this is very close to what I need.
2. use a border-right on my column, so I can get a vertical divider kind of a thing to be displayed. In that case, I end up getting the height of the divider the same as the column to which I am trying to add the border. I actually need the height of the divider to be much smaller than the column height itself.

**Additional context**

**Comment by iRyusa** [comment]
I think the easiest way would be to add an `img` for this
