### ISSUE TITLE
Minor: Empty style tags in html output

### ISSUE THREAD

**Issue by bjarketrux** [mjmlio/mjml#2678]
**Describe the bug**
When converting a simple hello world the resulting html has empty style tags.

**To Reproduce**
1. Create a file with this MJML code:

```mjml
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Or go to https://mjml.io/try-it-live/c7X7qQv5P

2. Render it to HTML by doing `npx mjml hello-world.mjml -o hello-world.html`
4. Look at the resulting html file

```html
  </style>
  <style type="text/css">
  </style>
  <style type="text/css">
  </style>
```

The web version only generates one empty style tag...

**Expected behavior**
No empty style tags.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.14.1
 - MJML NPM package and web playground

**Comment by iRyusa** [comment]
Might be something empty in our skeleton 🤔 

Should be an easy first issue for anyone willing to investigate
