### ISSUE TITLE
Error while compiling file

### ISSUE THREAD

**Issue by drydenwilliams** [mjmlio/mjml#2679]
**Describe the bug**
When I run a watch (`-w`) in a new project I get a `Error while compiling file` error:

**To Reproduce**
* Copy the [basic example code](https://mjml.io/try-it-live/iVuGSaQdy)
* Add it to `package.json` in the `scripts`: 
```
"watch:emails": "mjml -w templates/test.mjml -o tmp/test.html",
```
* Run the watch `yarn watch:emails`
* See the following error: 

```
$ mjml -w templates/test.mjml -o tmp/weekly-report.html
Now watching file: /Users/<user>/projects/<blah>/packages/emails/templates/test.mjml
/Users/<user>/projects/<blah>/packages/emails/templates/test.mjml - Change detected
/Users/<user>/projects/<blah>/packages/emails/templates/test.mjml - Error while compiling file
```

Is there a way to see the error?

**Comment by iRyusa** [comment]
What version of mjml you're using ?

**Comment by iRyusa** [comment]
Hi,

Can you provide more info about your env ?
