### ISSUE TITLE
Update main container/wrapper to persist background-color

### ISSUE THREAD

**Issue by netpoe** [mjmlio/mjml#268]
I've made some tests by sending an MJML template to my inbox. Even with the latest update where the markup is now: 

```
<mjml>
  <mj-body>
    <mj-container background-color="#ededed">
    ...
```

The emails lack of full background-color: 

![email-bg](https://cloud.githubusercontent.com/assets/4053518/15363373/27fdc5d2-1cde-11e6-8297-74f31c9d35c8.png)

The second image however, is a second test where I appended this wrapper to the `<<div class="mj-body">` tag: 

```
<body id="YIELD_MJML" style="background: #ededed;">
    <div class="mj-body" style="background-color:#ededed;">
      <table width="100%" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="650" valign="top" align="center" bgcolor="#ededed">
...
          </td>
        </tr>
      </table>
    </div>
  </body>
</html>
```

I can add the fix in a pull-request if: 

- The fix is approved by the community
- If the MJML team tells me where to add it, because the code structure was very difficult for me to understand

**Comment by iRyusa** [comment]
Hello,

We'll fix it in the next release thanks for reporting. Already mentioned in #236
Closing due to duplicate !
