### ISSUE TITLE
Why my template created with mjml, seems as a spam and logo not shown

### ISSUE THREAD

**Issue by sayinmehmet47** [mjmlio/mjml#2680]
**Describe the bug**
Mail seems spams and not show the image

I have created a template in mailjet template using mjml. To use the logo, I have inserted a my logo to  image and use the url of this image. 

``` js
 <mj-image src='http://0ojxp.mjt.lu/tplimg/0ojxp/b/lqj1g/0wwo1.png' alt="" width="220px" height="24px"/>
      </mj-column>
    </mj-section>

```

But when a send a mail with this url to show the logo, it seems as spam and sometimes the logo not shown. See here how the mail shown 

![image-for-notification-mail-spam](https://user-images.githubusercontent.com/75525090/235607728-62e54b21-9f48-40db-9e28-3a7dab55a3ba.png)
![spam-2](https://user-images.githubusercontent.com/75525090/235607891-c4cb5640-101d-4386-a1cc-d03c7aa211c2.png)
![spam-3](https://user-images.githubusercontent.com/75525090/235608636-572ffc4f-11c9-4596-990b-5fc2b3ea5e32.png)

Is there any other way to insert the logo in mjml or am I doing sth wrong when using logo url

**Comment by iRyusa** [comment]
There's multiple thing that can trigger the spam filter : content of the mail, reputation of the sender, ... 

I don't think MJML is the cause here.
