### ISSUE TITLE
mj-social-element icon - vertical stretch [outlook on windows]

### ISSUE THREAD

**Issue by j87x3inq2x3w7** [mjmlio/mjml#2685]
Hi, 
I have a problem with stretch icon (using mj-social-element) on outlook client all version on windows. 

I used this code.

`
<mj-section  padding="0 0" background-color="white">
<mj-column >
<mj-social align="left" css-class="padd-desktop" padding="0 16px" font-weight="600" font-size="16px" font-family="Helvetica, sans-serif">
<mj-social-element src="https://media.freshmail.mx/i/fvxl6osus8/dinxz8qhiw/720087601_4e2f5bbc90.png.png?sum=4f58077c72b6257d7d58193b1ca6eec0" icon-size="35px" padding="0 0" alt="pointer">
            Some text
          </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>
`

screen:
![image](https://github.com/mjmlio/mjml/assets/60732910/9b9bdb2f-1fb1-445c-a202-f522d8272278)
something like this, happen only on outlook and windows combination. Any reason ?

Edit: 
It's happen in other clients too:
android, native client
![image](https://github.com/mjmlio/mjml/assets/60732910/c3f4642a-292e-40b3-a0c9-fa0266b8cdfa)
android 11, outlook
![image](https://github.com/mjmlio/mjml/assets/60732910/8a72baef-a496-4312-aef7-7bcffaa7d39b)

**Comment by iRyusa** [comment]
Can you try to set the `icon-height` too ? As your icon isn't square

**Comment by j87x3inq2x3w7** [comment]
> Can you try to set the icon-height too ? As your icon isn't square
it's don't work, btw icon-size, set width and height
