### ISSUE TITLE
Mobile view appears in Outlook instead of desktop.

### ISSUE THREAD

**Issue by gowram** [mjmlio/mjml#2686]
**Mobile View appears instead of desktop View**

I have this MJML, it's rendering  mobile mode in outlook only, whereas other clients are working fine. 

**To Reproduce**
`<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all color="#000000" font-family="Arial"></mj-all>
    </mj-attributes>
    <mj-style >
      @media (max-width:480px) {
    .section_0daag > table > tbody > tr > td {
        padding: 20px 0px 20px 0px !important
    }
    .element_3ef4i {
        padding: 0px 25px 10px 25px !important;
        text-align: center !important
    }
    .element_bvkfl {
        padding: 0px 25px 0px 25px !important;
        text-align: center !important
    }
    .element_dza8d > div {
        text-align: left !important;
        font-size: 13px !important
    }
    .element_dza8d {
        padding: 25px 25px 10px 25px !important
    }
}
    </mj-style>
  </mj-head>
  <mj-body background-color="#ffffff" width="600px">
    <mj-wrapper padding-bottom="20px" padding-left="0px" padding-right="0px" padding-top="20px">
      <mj-section css-class="section_0daag" padding-bottom="20px" padding-left="0px" padding-right="0px" padding-top="20px">
        <mj-column width="34%">
          <mj-image css-class="element_3ef4i" href="#" padding-bottom="10px" padding-left="25px" padding-right="25px" padding-top="0px" src="https://d3g3ahbfahcupy.cloudfront.net/7d1921991429f66c3a29aa0e41d0ec13fd84ecdc/a62a08224978_sample_image.jpg"></mj-image>
        </mj-column>
        <mj-column width="66%">
          <mj-text css-class="element_dza8d" font-size="13px" padding-bottom="10px" padding-left="25px" padding-right="25px" padding-top="25px">
            <div>Lorem ipsum dolor sit amet, <strong>TBTY</strong> <i>consectetur</i> adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad</div>
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>`

**Expected behavior**
Desktop mode should appear in outlook
![image](https://github.com/mjmlio/mjml/assets/551819/31d699b1-d2ae-4b18-bf4e-934c2d494557)

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version v4.13.0
 - MJML tool used (node.js)

**Affected email clients (for rendering issues):**
 - Email Client - [Outlook]
 - OS: [Windows]

**Affected Screenshots**

![image](https://github.com/mjmlio/mjml/assets/551819/71905dfb-9e47-4051-bd3e-e4926b9898ba)

**Comment by iRyusa** [comment]
Can you try to send your email with https://putsmail.com/ ?

**Comment by gowram** [comment]
Microsoft® Outlook® 2019 MSO (Version 2304 Build 16.0.16327.20200) 32-bit

**Comment by iRyusa** [comment]
![Screenshot 2023-06-09 at 13 52 49](https://github.com/mjmlio/mjml/assets/570317/7f2679c5-54b4-4aa2-acaf-06804fd9c454)
We can't reproduce on our end

**Comment by philippjenni** [comment]
@gowram I was able to reproduce your problem with your MJML markup. My problem was that the Responsive Tables Conditions were rendered incorrectly when rendering the HTML markup for Office.
The cause was not MJML but my HTML editor in which I loaded the markup.

This turned the condition `<!--[if mso | IE]></td></tr></table></td></tr></table><![endif]-->` into the condition `<!-- [if mso | IE]></td></tr></table></td></tr></table><![endif]-->`.
made. In this case, Outlook does not take the condition into account if there is a space between `<!--` and `[if mso | IE]`. If the condition is rendered correctly, the display works.
You can check the markup in Outlook yourself to see if it is correct.
