### ISSUE TITLE
Layout Help

### ISSUE THREAD

**Issue by Soniacj** [mjmlio/mjml#2687]
Firstly I should mention, I don't know how to code, I dont know Html, I taught myself MJML to create templates for work. So please beaware my understanding will be limited. I need to replicate the following layout. The trouble is, I'm finding it hard to get the grey boxes looking right given their  contents. I did manage to do it, but I think its messy, BUT I forgot that the columns will be stacked on mobile view. This breaks it up completely and I cant see how to fix it. Grouping them doesnt help, as you can probably tell if you look at how I've managed to achieve the layout look. 

Is this possible with MJML or is it too complicated to do? Any other way I could do it, that would translate to mobile view ok? Thanks for any responses. 
![Untitled](https://github.com/mjmlio/mjml/assets/63528269/856caafb-f64c-4cd9-b48a-42409fb05617)

<mjml lang="en">
  <mj-head>

    <mj-style inline="inline"> .link-nostyle { color: #448aff; text-decoration: none } </mj-style>
    <mj-attributes>
      <mj-text font-size="18px" font-family="sans-serif, Arial, Helvetica" />
    </mj-attributes>

  </mj-head>
  <mj-body>

    <mj-wrapper border-left="1px solid #000000" border-right="1px solid #000000">
      <mj-section padding-top="50px">
        <mj-column>
          <mj-text font-weight="bold" font-size="28px">Your weekly PIM digest for XYZ</mj-text>
          <mj-text>Thanks for using ABC Directory Privileged Identity Management (PIM). This <a class="link-nostyle" href="https://example.com/">weekly digest</a> shows your PIM activities over the last seven days:
          </mj-text>
        </mj-column>
      </mj-section>

      <mj-section padding-bottom="0px">
        <mj-column padding-top="20px" background-color="#e5e7eb" width="250px">
          <mj-text align="center">User Activation</mj-text>
        </mj-column>
        <mj-column width="50px"></mj-column>
        <mj-column padding-top="20px" background-color="#e5e7eb" width="250px">
          <mj-text align="center">Users made permanent</mj-text>
        </mj-column>
      </mj-section>

      <mj-section padding-top="0px">
        <mj-column padding-bottom="20px" width="125px" background-color="#e5e7eb">
          <mj-text font-size="26px" align="right"><a class="link-nostyle" href="https://example.com/">{{UserActivation}}</a></mj-text>
        </mj-column>
        <mj-column padding-bottom="26px" width="125px" background-color="#e5e7eb">
          <mj-image align="left" width="20px" src="https://cdn-icons-png.flaticon.com/128/747/747376.png"></mj-image>
        </mj-column>
        <mj-column width="50px"></mj-column>
        <mj-column padding-bottom="20px" width="125px" background-color="#e5e7eb">
          <mj-text font-size="26px" align="right"><a class="link-nostyle" href="https://example.com/">{{UsersMadePermanent}}</a></mj-text>
        </mj-column>
        <mj-column padding-bottom="26px" width="125px" background-color="#e5e7eb">
          <mj-image align="left" width="20px" src="https://cdn-icons-png.flaticon.com/128/747/747376.png"></mj-image>
        </mj-column>
      </mj-section>

      <mj-section full-width="full-width" padding-bottom="0px">
        <mj-column padding-top="20px" background-color="#e5e7eb" width="250px">
          <mj-text align="center">Assignments made inside PM</mj-text>
        </mj-column>
        <mj-column width="50px"></mj-column>
        <mj-column padding-top="20px" background-color="#e5e7eb" width="250px">
          <mj-text align="center">Assignments made outside of PIM</mj-text>
        </mj-column>
      </mj-section>

      <mj-section padding-top="0px">
        <mj-column padding-bottom="20px" width="125px" background-color="#e5e7eb">
          <mj-text font-size="26px" align="right"><a class="link-nostyle" href="https://example.com/">{{AssignmentsMadeInsidePm}}</a></mj-text>
        </mj-column>
        <mj-column padding-bottom="26px" width="125px" background-color="#e5e7eb">
          <mj-image align="left" width="20px" src="https://cdn-icons-png.flaticon.com/128/747/747376.png"></mj-image>
        </mj-column>
        <mj-column width="50px"></mj-column>
        <mj-column padding-bottom="20px" width="125px" background-color="#e5e7eb">
          <mj-text font-size="26px" align="right"><a class="link-nostyle" href="https://example.com/">{{AssignmentsMadeOutsideOfPm}}</a></mj-text>
        </mj-column>
        <mj-column padding-bottom="26px" width="125px" background-color="#e5e7eb">
          <mj-image align="left" width="20px" src="https://cdn-icons-png.flaticon.com/128/747/747376.png"></mj-image>
        </mj-column>
      </mj-section>
    </mj-wrapper>

  </mj-body>
</mjml>

**Comment by iRyusa** [comment]
Something like that should work better for you https://mjml.io/try-it-live/zZubqGqORh
As every column stack in mobile it's not designed to achieve this like that. Please note that we highly recommend to know about HTML+CSS before using MJML.
