### ISSUE TITLE
style="width:NaNInfinity;" is breaking the Outlook experience

### ISSUE THREAD

**Issue by Showcase-Joz** [mjmlio/mjml#2688]
**Describe the bug**
So I have what appears to be a _bug_, brought about via the **inner-border**, which is nested within my structure.

**To Reproduce**
1. Create a file with this MJML code: 

`<mj-wrapper css-class="horizontal-speakers-wrapper card-outlines--nactive" padding="0px">
      <mj-section padding="0px" css-class="text-block block-color--ffffff" background-color="#ffffff">
        <mj-column>
          <mj-text css-class="inner-copy reduced-padding--off text-align-headings--center">
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section padding="0px" css-class="speaker-section image-radius--square block-color--ffffff" background-color="#ffffff">

        <mj-column css-class="inner-speaker-block" inner-border="1px solid #c7c7c7" padding="5px" inner-border-radius="3px">
          <mj-image css-class="speaker-img" href="https://google.com" alt="alt-test" target="_blank" src="https://thumbs.dreamstime.com/z/speaker-head-man-image-wearing-shirt-holding-front-his-face-38259325.jpg" />

          <mj-text css-class="speaker-text links--underline links-color--blue">
            <p>heading stuff</p>
            <h4>A.Name</h4>
            <h5>B.Name</h5>
          </mj-text>
        </mj-column>

        <mj-column css-class="inner-speaker-block" inner-border="1px solid #c7c7c7" padding="5px" inner-border-radius="3px">
          <mj-image css-class="speaker-img" href="https://google.com" alt="alt-test" target="_blank" src="https://thumbs.dreamstime.com/z/speaker-head-man-image-wearing-shirt-holding-front-his-face-38259325.jpg" />

          <mj-text css-class="speaker-text links--underline links-color--blue">
            <p>heading stuff</p>
            <h4>A.Name</h4>
            <h5>B.Name</h5>
          </mj-text>
        </mj-column>

        <mj-column css-class="inner-speaker-block" inner-border="1px solid #c7c7c7" padding="5px" inner-border-radius="3px">
          <mj-image css-class="speaker-img" href="https://google.com" alt="alt-test" target="_blank" src="https://thumbs.dreamstime.com/z/speaker-head-man-image-wearing-shirt-holding-front-his-face-38259325.jpg" />

          <mj-text css-class="speaker-text links--underline links-color--blue">
            <p>heading stuff</p>
            <h4>A.Name</h4>
            <h5>B.Name</h5>
          </mj-text>
        </mj-column>

      </mj-section>

      <mj-section padding="0px" css-class="speaker-section" background-color="#ffffff">
        <mj-column width="100%">
          <mj-spacer css-class="button-spacer-top button-padding--on" />
          <mj-button align="center" mj-class="button--primary" inner-padding="18px 32px" href="https://www.google.com" css-class="button button--primary">Button
            <mj-raw css-class="svg-wrapper">
              <svg id="arrow_R" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
                <path d="M13.44,7.56l-4-4a.62.62,0,1,0-.88.88l2.93,2.93H3A.63.63,0,0,0,2.37,8,.63.63,0,0,0,3,8.62h8.49L8.56,11.56a.61.61,0,0,0,0,.88.63.63,0,0,0,.88,0l4-4A.61.61,0,0,0,13.44,7.56Z" />
              </svg>
            </mj-raw>
          </mj-button>
          <mj-spacer css-class="button-spacer-bottom button-padding--on" />
        </mj-column>
      </mj-section>
    </mj-wrapper>`

2. You can see a live example with the css here https://parcel.io/e/a3edf985-f02b-444b-b41e-9089c2574eb6?
3. For comparison there is a clone of this without the offending **inner-border** tag, here https://parcel.io/e/7b8ab4f5-0e7e-45ee-9bb8-b69af5f1f7e9?

**Expected behavior**
The three speaker blocks are meant to be stacked horizontally and contained within the bounds of a 600px wrapper as seen here <img width="617" alt="Screenshot 2023-06-07 at 15 42 30" src="https://github.com/mjmlio/mjml/assets/3405708/f6292234-947c-4613-a531-16a45b2684fb">

I believe the ```inner-border="1px solid #c7c7c7"``` code is preventing the ```css-class="speaker-img"``` from acquiring a width (displays as: ```style="width:NaNInfinity;"```) as well as the (further) nested img tag's width attribute (displaying as: ```width="Infinity"```).

**MJML environment (please complete the following information):**
 - OS: mac
 - MJML Version not sure of our internal version, though the issue persists across other systems too, see tooling.
 - MJML tool used internal parse tool. https://mjml.io/try-it-live and parcel.io

**Email sending environment(for rendering issues)**:
 - Have now sent an email, closest I have gotten is Email on Acid, where the issue is present in Outlook renders.

**Affected email clients (for rendering issues):**
All Outlook according to Email on Acid testing

**Screenshots**
![d2ViL053Sk9iT2p0QzBnbHJlTTBwWUxrNXdFZGJoUUVDTWZqUlg0NlF1d1k3Z05LRi9vdXRsb29rMTlfMTI1LmpwZw==](https://github.com/mjmlio/mjml/assets/3405708/b83926fc-7c39-42ce-866b-15ac2790839c)
this image ^^ shows the issue present in Outlook

![d2ViL053Sk9iT2p0QzBnbHJlTTBwWUxrNXdFZGJoUUVDTWZqUlg0NlF1d1k3Z05LRi9nbWFpbHcxMF9jaHIyNl93aW4ucG5n](https://github.com/mjmlio/mjml/assets/3405708/e2990ce0-d405-412f-8283-a7e8280674f5)
this image ^^ shows the desired output in Yahoo (of all choices)

**Additional context**
This is cut back code taken from a relatively large codebase that uses mustache for the logic within a framework that parses. I wasn't sure where the issue came from (ie, the framework im using) so I stripped it back to check for persistence, which is shown here.

**Comment by iRyusa** [comment]
Hi !

Might be something simple to fix, but can you provide a minimal exemple to
reproduce ? It would be easier for us to debug here !


Thanks!

**Comment by Showcase-Joz** [comment]
hey @iRyusa yeah sure, i've removed the above/below tags so it is limited to the one section now. available on the original links above still 👍

**Comment by iRyusa** [comment]
Yup I guess you can reproduce simply with this https://mjml.io/try-it-live/iNJ4rBerGG 

But I won't be able to fix for a while. You can specify a width to avoid this bug for now even if it's not ideal

**Comment by Showcase-Joz** [comment]
ok thanks for the update @iRyusa . i just wanted to understand if there was in fact an actual issue that needed addressing. 👍

**Comment by iRyusa** [comment]
I don't think this hard to fix tho, as https://github.com/mjmlio/mjml/blob/49535a073e9cd05eb26bd5291c6d9a9743e17fd1/packages/mjml-column/src/index.js#L42-L46 handles`inner-border` as a `padding` / `margin` shorthand. `borderParser` instead should do the trick
