### ISSUE TITLE
Padding broken in section with background image using Outlook

### ISSUE THREAD

**Issue by CamParry** [mjmlio/mjml#2690]
**Describe the bug**
When adding a image or text element within a section that has a background image, the horizontal padding is being ignored on windows versions of Outlook/Office 365.

**To Reproduce**
Test the below code using [testi.at](https://testi.at), it is supposed to render a section with a background image that contains an image element wrapped in 30px of padding.

```
<mjml>
  <mj-body width="600px">
    <mj-section padding="30px" background-url="https://images.unsplash.com/photo-1683481951374-1d62b42afaba?q=20" background-size="cover" background-position="center">
      <mj-column>
        <mj-image padding="0" align="left" width="100px" src="https://placehold.co/100x50/orange/white?text=LOGO" />
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

```
All windows versions of Outlook and Office 365 render without the left padding, the same happens if the logo image is swapped for a text element.

![image](https://github.com/mjmlio/mjml/assets/64690031/946274c4-daac-4288-ac6a-18d859bc1594)

**Expected behavior**
It should render with 30px of padding on the left as it does on all other clients.

![image](https://github.com/mjmlio/mjml/assets/64690031/e2a98e24-974e-48fd-b960-8c3158be0595)

**MJML environment:**
 - OS: macOS Monterey
 - MJML version: 4.12.0
 - MJML tool used: MJML App

**Email sending environment**:
 - [testi.at](https://testi.at)

**Affected email clients:**
 - All versions of Outlook and Office 365 on windows

**Comment by thommeredith** [comment]
I can also say that padding works totally fine if there is no background image, when the background image is added there is a new <div> that gets output, this might be the culprit. Why is this needed?

**Comment by iRyusa** [comment]
It's not related to the `div` but rather nesting more than 2 time table inside a VML section. 
When nesting table inside VML padding left-right are just broken
