### ISSUE TITLE
Issue: Box Model Not Respected

### ISSUE THREAD

**Issue by Sambuxc** [mjmlio/mjml#2693]
**the bug**
It looks like the box model is not respected when using a border on columns. I have added a border to each of the columns and the padding does not work as expected. Borders should sit between the margin and padding: [margin] **[border]** [padding] [content]. It looks like mjml does not respect the normal box model order and is as [margin] [padding] **[border]** [content].

**the code**
Here is an example code with it not working as expected.

```
<mjml>
    <mj-body>
        <mj-section background-color="#D5D5D5" background-repeat="no-repeat" text-align="center" vertical-align="top" padding="10px">
            <mj-column padding="10px" border="1px solid #05C3DE"> 
                <mj-image src="https://puu.sh/z9hcM/b54d0b6d6a.png" padding="0" />
            </mj-column>
            <mj-column padding="10px" border="1px solid #05C3DE"> 
                <mj-image src="https://puu.sh/z9hcM/b54d0b6d6a.png" padding="0" />
            </mj-column>
            <mj-column padding="10px" border="1px solid #05C3DE"> 
                <mj-image src="https://puu.sh/z9hcM/b54d0b6d6a.png" padding="0" />
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

**MJML environment**
 - OS: MacOS
 - MJML Version ^4.12.0
- MJML App v3.0.4

**Comment by Sambuxc** [comment]
Using `inner-border` on the columns solved this issue. For reason I had to specify a padding value on the column to get the border to show, even if the value was set to 0px. Without that, the border would not show.

**Comment by iRyusa** [comment]
Nothing more to do here, most attributes are prefixed with `inner-*` to target specific element within the generated DOM.

It's hard to find a proper naming here as : 
- It's a padding
- `border` isn't applied on the same element as the `padding` attributes
- if we decided to go with `margin` in some other cases it would be the same 
- padding term is widely use in MJML so it's more coherent
- changing the name would require to find a proper name and a major version just for this

**Comment by Sambuxc** [comment]
> Nothing more to do here, most attributes are prefixed with `inner-*` to target specific element within the generated DOM.
> 
> It's hard to find a proper naming here as :
> 
> * It's a padding
> * `border` isn't applied on the same element as the `padding` attributes
> * if we decided to go with `margin` in some other cases it would be the same
> * padding term is widely use in MJML so it's more coherent
> * changing the name would require to find a proper name and a major version just for this

I'm just glad there was a solution!

I actually have a really good experience building with MJML so thanks to the team for doing all you do! 🙏🏽🙏🏽🙏🏽🙏🏽🙏🏽

Long live MJML !
