### ISSUE TITLE
VSCode error illegal inner-background-color and no border on preview

### ISSUE THREAD

**Issue by Sambuxc** [mjmlio/mjml#2694]
**Describe the bug**
**1.**
VScode doesn't seem to recognise the inner-background-color. I have it added to an mj-column as so.
```
<mj-column inner-background-color="white">
```

**2.**
The MJML preview in vscode doesn't show borders. Also on a side note, I noticed that if I didn't explicitly set a 0px padding the border would not show.
I have defined an mj-class.
```
<mj-attributes>
<mj-class name="border-blue" inner-border="1px solid #05C3DE" />
</mj-attributes>
```
Then used it as so
```
<mj-column mj-class="border-blue" padding="0px">
```

Now both of the issues aren't a problem in the MJML application, only in VScode with the MJML extension.

**MJML environment:**
 - OS: MacOS
 - MJML Version 4
 - VSCode with MJML extension

**Screenshots**
**1.**
https://i.postimg.cc/4dYJxsPt/mjml-inner-background-color-is-illegal-in-vscode.png

**Comment by iRyusa** [comment]
Make sure you're using https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml with the latest version.

**Comment by Sambuxc** [comment]
Are there two different mjml extensions?
