### ISSUE TITLE
mj-html-attributes tag is not recognized by the API 

### ISSUE THREAD

**Issue by MehyarSawas** [mjmlio/mjml#2697]
**Describe the bug**
When I try to parse mjml to html via the mjml API https://api.mjml.io/v1/render 
The API does not recognize the mj-html-attributes tag and returns the following error: 
Line 1 of /home/ndjs (mj-html-attribute) — Element mj-html-attribute doesn't exist or is not registered
The response returns the mjml_version:  4.6.1

**To Reproduce**
1. Try to parse any mjml content that contains the mj-html-attribute tag 

**Expected behavior**
Like in the try it live renderer the API must recognize the mj-html-attribute tag 

**MJML environment (please complete the following information):**
 - API

**Comment by iRyusa** [comment]
`mj-html-attributes` was released in >4.7  that's why it doesn't work in the API

**Comment by MehyarSawas** [comment]
OK that was somehow expected, but still good to know when will the api upgrade its version?

**Comment by iRyusa** [comment]
I don't have any information on Mailjet-side as it's a non profit service
with no SLA I don't think they will update it soon.
