### ISSUE TITLE
[mj-section] background images not appearing on Outlook

### ISSUE THREAD

**Issue by ElectricPowerHouse** [mjmlio/mjml#2698]
Describe the bug:
I want to create an MJML email with sections that have a background image. The images work on Gmail and in-browser mail viewers, but not on Outlook or the Microsoft Mail application. [mj-image] DOES work on all email browsers. 

To Reproduce:
1. Create a file with this MJML code: 

`<mjml>
  <mj-body background-color="#F2F2F2" width="800px">
  
    <mj-section>
      <mj-column>
        
      </mj-column>
    </mj-section>
    <mj-section background-size="cover" background-url="https://images.squarespace-cdn.com/content/v1/56bbdac627d4bd726408b6e6/c45286cc-6503-4f92-bc63-a41219cc341a/nelson_image.jpg" background-repeat="no-repeat" full-width="false">
      <mj-column width="100%">
        <mj-text padding-top="70px" color="white" font-size="18px" align="center" line-height="1"> WHERE KIWIS LOVE TO LIVE</mj-text>
        <mj-text color="white" font-size="68px" align="center"> Nelson</mj-text>
        <mj-button padding-bottom="70px" font-family="Helvetica" background-color="rgba(0,0,0,0)" border="2px solid #fff" color="white" href="https://www.english-school.ac.nz/nelson"> FIND OUT MORE </mj-button>
      </mj-column>
    </mj-section>
 
     
  </mj-body>
</mjml>`

3. Follow your preferred method for rendering and sending the email - I have tried copy & pasting the rendered email into Gmail, as well as sending the HTML through putsmail. Both result in the same issue. 
4. Send the email 
5. Open the email with an Outlook application, or a Microsoft Mail application. 
6. The images that should be shown in the background of [mj-section] do not appear. 

Expected behavior:
The images in the background of an [mjml-section] should show on all mail browsers. 

MJML environment :
 - OS: Windows 11 Home 64-bit
 - MJML Version: 4.12.0
 - MJML tool used: MJML application

Email sending environment:
 - [Putsmail](https://putsmail.com/)]  
 - Copy / pasting rendered HTML into Gmail

Affected email clients (for rendering issues):
 - Email Client: Outlook, & Microsoft Mail applications 

Screenshots:

Expected:
<img width="677" alt="firefox_opuMJJGjfL" src="https://github.com/mjmlio/mjml/assets/20962020/4dd0f33f-a1ff-4c28-9c16-2cb4ccaaee94">

What it shows in Outlook: 
<img width="534" alt="ApplicationFrameHost_GSZX48kyVp" src="https://github.com/mjmlio/mjml/assets/20962020/04da26cf-9dc5-4c0d-8222-412049935c71">

**Comment by iRyusa** [comment]
The windows 10/11 mail client isn't in our test scope (not available in email on acid). I think there's a fallback if you put a background-color but I don't remember if it's specific to mj-hero or mj-section or both.
