### ISSUE TITLE
Broken Layout on (Windows Outlook 2019, Outlook 2016, Outlook 2016 (120dpi), 

### ISSUE THREAD

**Issue by tobyonono** [mjmlio/mjml#2699]
**White lines appearing randomly on different Outlook version, misaligned element in footer on all windows versions, broken image links on some versions**

I've tested with Litmus & Email on Acid and on different versions of Outlook, some random lines will appear between sections or under elements. The instagram logo in the footer is also misaligned  on all the windows tests we've done (it should be aligned with the other top elements)

**To Reproduce**
1. `<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text padding="0 30px" />
      <mj-all padding="0 0" margin="0 0" />
    </mj-attributes>
  </mj-head>
  <mj-body >
    <mj-section background-color="#211C46">
      <mj-column width="45%">
        <mj-image padding="30px 20px" src="https://originate.ie/wp-content/uploads/2023/06/Parkleigh-logo.png" />
      </mj-column>
    </mj-section>
    <mj-section background-color="#211C46">
      <mj-column>
        <mj-image fluid-on-mobile="true" padding="0 20px" src="https://originate.ie/wp-content/uploads/2023/06/Hero-Image_6.jpg" />
      </mj-column>
    </mj-section>
    <mj-section background-color="#211C46" border="1px solid #211C46">
      
      <mj-column vertical-align="top" mj-class="desktop-column" padding="30px 0 0px" width="100%" >
        <mj-text font-size="14px" padding="0px 0px 0px" font-family="Arial" color="#F49DAD" align="center">
          <p style="letter-spacing:3px; padding:0px 0px 0px; font-weight:700">EXCITING NEWS</p>
        </mj-text>
        <mj-text font-size="42px" padding="0px 0px 20px" font-family="Georgia" color="#F9F4F2" align="center">
          <p style="font-size: 42px; font-weight:400; padding:0px 0px 0px; margin:0px" border="1px solid white">Feel right at home </p>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#211C46" border="1px solid #211C46">
    <mj-column padding="0px 10px 20px" mj-class="desktop-column" width="60%">
        <mj-text font-size="14px" padding="0 0px 0px" font-family="Arial" color="#F9F4F2" line-height="1.4" vertical-align="middle" align="center">
          <p style="font-size:14px; font-weight:400; margin:0">Our brand new selection of spacious, energy efficient 3 and 4 bedroom homes is ready to go on sale this September.</p>
        </mj-text></mj-section>
    <mj-section>
      <mj-column>
        <mj-image padding="0 0px" src="https://originate.ie/wp-content/uploads/2023/06/Image-CGI_email-8-e1687445029564.png" />
      </mj-column>
    </mj-section>
     <mj-section background-color="#DDC1DE">
       <mj-column mj-class="desktop-column" padding="30px 0px 0px" width="100%" >
        <mj-text font-size="42px" padding="0px 0px 0px" font-family="Arial" align="center" color="#211C46">
          <p>Parkleigh is different…</p>
        </mj-text>
        
      </mj-section>
      
    <mj-section background-color="#DDC1DE" padding="20px 30px 40px">
      <mj-column width="25%">
        <mj-image width="100px" align="left" src="https://originate.ie/wp-content/uploads/2023/06/icon-3.png"></mj-image>
      </mj-column>
      <mj-column width="75%">
        <mj-text font-size="26px" align="left" padding="0px 16px 0px" color="#211C46" font-weight="400">
          <p style="margin-top: 20px; margin-bottom: 0; font-size:26px font-weight:400"> Aliquam in elementum</p>
        </mj-text>
        <mj-text color="#211C46" padding="0px 16px 0px" line-height="1.4">
          <p style="font-size: 14px;">Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis diam sit amet lacinia. Aliquam in elementum tellus.</p>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#DDC1DE" padding="0px 30px" padding-bottom="20px" border="1px solid #DDC1DE">
      <mj-column width="25%">
        <mj-image width="100px" align="left" src="https://originate.ie/wp-content/uploads/2023/06/icon-2.png"></mj-image>
      </mj-column>
      <mj-column width="75%" border="1px solid #DDC1DE">
        <mj-text font-size="26px" color="#211C46" padding="0px 16px">
          <p style="margin-top: 10px; margin-bottom: 0; font-size:26px"> Curabitur vel bibendum</p>
        </mj-text>
        <mj-text color="#211C46" padding="0px 16px 30px" line-height="1.4">
          <p style="font-size: 14px;">Donec ut rhoncus ex. Suspendisse ac rhoncus nisl, eu tempor urna. Curabitur vel bibendum lorem. Morbi convallis convallis.</p>
        </mj-text>
        <mj-button align="left" padding="0px 16px 30px" border-radius="0px" font-family="Arial" letter-spacing="1px" background-color="#DDC1DE" border="1px solid #211C46" color="#211C46" href="https://www.parkleigh.ie/" font-size="14px" text-transform="uppercase" inner-padding="10px 30px">Find out more at parkleigh.ie</mj-button>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column>
        <mj-image padding="0 0px" src="https://originate.ie/wp-content/uploads/2023/06/Car.png" />
      </mj-column>
    </mj-section>
    <mj-section background-color="#211C46" >
      
      <mj-column vertical-align="middle" mj-class="desktop-column" padding="40px 0 30px" >
        <mj-text font-size="38px" padding="0px 20px 10px" font-family="Georgia" color="#F9F4F2" vertical-align="middle" align="center">
          <p>Eligible for First Home Scheme and Help to Buy</p>
        </mj-text>
        <mj-button width="200px" padding="10px 0px 0px" border-radius="0px" font-family="Arial" font-weight="bold" letter-spacing="1px" background-color="#F49DAD" color="#211C46" href="https://www.parkleigh.ie/" font-size="14px" text-transform="uppercase" inner-padding="15px">Find Out More</mj-button>
      </mj-column>
    </mj-section>
    <mj-section background-color="#B0004D" padding="30px 30px" padding-bottom="20px" border="1px solid #B0004D">
      <mj-column width="50%">
        <mj-image padding="16px 16px 16px" width="200px" align="left" src="https://originate.ie/wp-content/uploads/2023/06/SevenMillsStacked3x.png"></mj-image>
      </mj-column>
      <mj-column width="50%">
        <mj-text padding="0px 16px 0px" font-size="28px" color="#F9F4F2" font-family="Georgia" font-weight="400">
          <p style="font-size: 28px; font-weight:400'"> About Seven Mills</p>
        </mj-text>
        <mj-text padding="20px 16px 20px" padding-top="0px" font-size="16px" color="#F9F4F2" font-family="Arial" font-weight="400" line-height="1.4" align="center">
          <p align="left" padding="0px 0px" style="font-size: 14px; font-weight:400" font-weight:"400">Nestled on the Grand Canal, between Lucan and Clondalkin, Seven Mills is focused on sustainable living and community spirit. Be part of Dublin 22's newest town.</p>
        </mj-text>
        <mj-button align="center" width="230px" padding="0px 16px 30px" inner-padding="20px" border-radius="0px" border="1px solid #F9F4F2" font-family="Arial" font-weight="bold" letter-spacing="2px" background-color="#B0004D" color="#F9F4F2" href="https://www.cairnhomes.com/about/seven-mills/" font-size="14px" text-transform="uppercase">VISIT SEVENMILLS.IE</mj-button>
      </mj-column>
    </mj-section>

    

 <mj-section background-color="#211C46" padding="30px 0px 0px" border="1px solid #211C46">
   <mj-group>
     <mj-column width="100%" >
        <mj-text color="#F9F4F2" padding="0px 20px" font-size="14px" font-family="Arial">
          <p style="margin:0; padding:0">Contact Hooke & McDonald, our selling agents, for more details.</p>
        </mj-text>
      </mj-column>
   </mj-group>
   
    </mj-section>
    <mj-section background-color="#211C46" padding="0px 10px 0px" >
      <mj-group>
        <mj-column width="33%" padding="20px 10px">
               <mj-image width="190px" href="https://www.hookemacdonald.ie/" src="https://originate.ie/wp-content/uploads/2023/06/HookeMcD3x.png"></mj-image>
      </mj-column>
        <mj-column width="50%" padding="20px 10px">
        <mj-image   width="100px" src="https://originate.ie/wp-content/uploads/2023/06/BERLogo3x.png"></mj-image>
      </mj-column>
      <mj-column width="16%" padding="24px 10px" vertical-align="middle">
        <mj-image  width="30px"  href="https://www.instagram.com/cairnhomesplc/" src="https://originate.ie/wp-content/uploads/2023/04/instagram.png"></mj-image>
      </mj-column>      
      </mj-group>    
    </mj-section>
    <mj-section background-color="#211C46" padding="20px 10px" >
      <mj-group>
        <mj-column width="33%" padding="20px 10px">
               <mj-image width="1900px" href="https://www.cairnhomes.com/" src="https://originate.ie/wp-content/uploads/2023/06/Cairn-Logo-Red-HF2.png"></mj-image>
      </mj-column>
        <mj-column width="33%" padding="20px 20px">
      </mj-column>
        
      <mj-column width="32%" padding="24px 0px" vertical-align="middle">
        <mj-image  width="144px"   src="https://originate.ie/wp-content/uploads/2023/06/BuiltForGood3x.png"></mj-image>
      </mj-column>      
      </mj-group>    
    </mj-section>
    
  </mj-body>
  <mj-style>
  </mj-style>
</mjml>`

**Expected behavior**

There should be no white lines appearing under random elements or between sections

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 3.0.4
 - MJML tool used MJML App

**Email sending environment(for rendering issues)**:
 - Litmus & Email on Acid

**Affected email clients (for rendering issues):**
 -Outlook 2019, Outlook 2016, Outlook, 2016(120dpi), Outlook Office 365
 - OS: Windows
 - Browser [e.g. Google Chrome]

**Screenshots**
![Screenshot 2023-06-28 at 11 01 29](https://github.com/mjmlio/mjml/assets/10547294/6812c8e4-6ed9-446f-b1e6-a8bc3b71ca66)
![Screenshot 2023-06-28 at 11 02 42](https://github.com/mjmlio/mjml/assets/10547294/3baf7fb7-9e61-4834-a8ac-c5c26c4efdf6)
![Screenshot 2023-06-28 at 11 18 58](https://github.com/mjmlio/mjml/assets/10547294/208c4be8-b33f-493f-95c3-fd2c22b92131)
![Screenshot 2023-06-28 at 11 18 58](https://github.com/mjmlio/mjml/assets/10547294/b033f432-6bc2-45d2-9416-060fa09b728b)
![Screenshot 2023-06-28 at 11 21 18](https://github.com/mjmlio/mjml/assets/10547294/eb42041e-0e4c-4cd5-85ca-29487d22607c)
![Screenshot 2023-06-28 at 11 22 03](https://github.com/mjmlio/mjml/assets/10547294/27010802-df03-4539-be2e-fcbb6a97e89e)

**Additional context**
Expected Behaviour
![Screenshot 2023-06-28 at 11 37 57](https://github.com/mjmlio/mjml/assets/10547294/ec9b7c07-404e-4bfa-8811-d310f277b75c)
![Screenshot 2023-06-28 at 11 38 05](https://github.com/mjmlio/mjml/assets/10547294/dfa0cc38-72c8-4c44-871a-1b08ff2787d2)
![Screenshot 2023-06-28 at 11 38 16](https://github.com/mjmlio/mjml/assets/10547294/ce03279d-95aa-4b48-8f46-4ca28a13dabf)
![Screenshot 2023-06-28 at 11 38 41](https://github.com/mjmlio/mjml/assets/10547294/a645ec25-de6c-4ac7-b23d-b70899eb0b68)

**Comment by iRyusa** [comment]
For whitelines, it's a common issue in Outlook and not really from MJML. Tweaking values of padding/font-size/... can make them disappear you can find multiples articles on that topic (https://www.actionrocket.co/email-design-review/white-lines-in-outlook ex)

For the instagram logo maybe remove the vertical-align ?

**Comment by tobyonono** [comment]
Thanks! That worked for the broken instagram logo. Any suggestions about the broken images?

I'd actually gone through that doc before and evening out the padding, line heights etc. does some weird stuff and start duplicating sections etc. I'll have a look at some of the other suggestions now

**Comment by iRyusa** [comment]
> Any suggestions about the broken images?

Which one ?
