### ISSUE TITLE
Image overlapping header when line-height set

### ISSUE THREAD

**Issue by michael-wolfenden** [mjmlio/mjml#2702]
**Describe the bug**
The header of my email contains an logo image followed by header text. When I set the `line-height` for all `mj-text` nodes, the logo image overlaps the header text

**To Reproduce**

Send the html of the following template to Outlook

[Playground link](https://mjml.io/try-it-live/rPxNpEWkF5)

```html
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text line-height="24px" font-size="16px" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="600px" src="https://placehold.co/600x150"></mj-image>
        <mj-text font-size="36px" font-weight="700">Big Header</mj-text>
        <mj-text>Lorem ipsum dolor sit amet. Nam quasi pariatur qui error quas qui vero adipisci est sint ratione rem ipsum ratione. Vel quidem rerum vel accusantium sapiente in laborum veritatis.</mj-text>
        <mj-text>Lorem ipsum dolor sit amet. Nam quasi pariatur qui error quas qui vero adipisci est sint ratione rem ipsum ratione. Vel quidem rerum vel accusantium sapiente in laborum veritatis.</mj-text>
        <mj-text>Lorem ipsum dolor sit amet. Nam quasi pariatur qui error quas qui vero adipisci est sint ratione rem ipsum ratione. Vel quidem rerum vel accusantium sapiente in laborum veritatis.</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
**Expected behavior**
The logo image to not overlap the header text

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version: 4.9.3
 - MJML tool used:  Playground

**Email sending environment(for rendering issues)**:
 - Sendgrid

**Affected email clients (for rendering issues):**
 - Email Client: Microsoft® Outlook® for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20324) 32-bit 
 - OS: Windows
 - Browser: N/A

**Screenshots**

![image](https://github.com/mjmlio/mjml/assets/780521/f94fede0-bfbd-416e-bd75-68a0bf190c22)

**Additional context**

If I remove `line-height` it renders perfectly

```diff
<mjml>
  <mj-head>
    <mj-attributes>
-      <mj-text line-height="24px" font-size="16px" />
+      <mj-text font-size="16px" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="600px" src="https://placehold.co/600x150"></mj-image>
        <mj-text font-size="36px" font-weight="700">Big Header</mj-text>
        <mj-text>Lorem ipsum dolor sit amet. Nam quasi pariatur qui error quas qui vero adipisci est sint ratione rem ipsum ratione. Vel quidem rerum vel accusantium sapiente in laborum veritatis.</mj-text>
        <mj-text>Lorem ipsum dolor sit amet. Nam quasi pariatur qui error quas qui vero adipisci est sint ratione rem ipsum ratione. Vel quidem rerum vel accusantium sapiente in laborum veritatis.</mj-text>
        <mj-text>Lorem ipsum dolor sit amet. Nam quasi pariatur qui error quas qui vero adipisci est sint ratione rem ipsum ratione. Vel quidem rerum vel accusantium sapiente in laborum veritatis.</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

![image](https://github.com/mjmlio/mjml/assets/780521/31edef0e-722c-4685-accf-b5a06288b23b)

**Comment by iRyusa** [comment]
Hi!

It's not the image that overlap the text, it's just how line-height works in outlook. You need to be at either at `1` or a value equal or greater than the font-size.
