### ISSUE TITLE
Reverse mobile stack on mobile Android broken 

### ISSUE THREAD

**Issue by allisonbardy** [mjmlio/mjml#2705]
Order of columns not reversing on mobile Gmail App Pixel 6 Android 13 using this CSS

.reverse stack {
  display: flex;
  flex-direction: column-reverse;
}

Columns should reverse like shown below, but do not on Gmail App Pixel 6 Android 13: 
<img width="802" alt="Screen Shot 2023-07-06 at 10 37 39 AM" src="https://github.com/mjmlio/mjml/assets/45407686/b32145b2-9b77-4b53-bca7-78c3febd19d3">
<img width="308" alt="Screen Shot 2023-07-06 at 10 37 49 AM" src="https://github.com/mjmlio/mjml/assets/45407686/5633c838-e193-428c-a397-a49bc0c9cd62">

OS: Android 13
MJML Version 4.2.0

Using Emailonacid to test.

**Comment by iRyusa** [comment]
Not related to MJML here as it's just clearly not supported by the email client.
You can find about css compatibility on https://www.caniemail.com/
