### ISSUE TITLE
Responsive Behavior in MJML Template: Columns Not Stacking on Mobile

### ISSUE THREAD

**Issue by AntoineDesinety** [mjmlio/mjml#2706]
**Describe the bug**
I am unable to make my template responsive. I would like to use columns for desktop display and have these columns stack into full-width on mobile (around 800px wide, for example). I'm not sure if it's possible because even the MJML demos are not responsive. The columns remain as columns.

**To Reproduce**
```
<mj-head>
        <mj-title>Experience</mj-title>
        <mj-preview>Test</mj-preview>
        <mj-attributes>
            <mj-text font-weight="400" font-size="14px" color="#000000" line-height="16px" font-family="Arial, sans-serif"></mj-text>
        </mj-attributes>
    </mj-head>
    <mj-body background-color="#ffffff">
        <mj-wrapper full-width="full-width" padding="0">
            <mj-section css-class="test" padding-top="50px" padding-bottom="0">
                <mj-column css-class="test-1" background-color="red">
                    <mj-text>Test 1</mj-text>
                </mj-column>
                <mj-column css-class="test-2" background-color="green">
                    <mj-text>Test 2</mj-text>
                </mj-column>
            </mj-section>
        </mj-wrapper>
    </mj-body>
</mjml>
```

**MJML environment (please complete the following information):**
MJML Version = 4.2.0

**Email sending environment(for rendering issues)**:
Outlook desktop

**Comment by AntoineDesinety** [comment]
Hi, 

That i have on the preview of your tools : 
![image](https://github.com/mjmlio/mjml/assets/115456684/7b7874a0-eb88-48f9-8c7c-50d5e912ef67)

And this is what i have when i send my mail : 
![Screenshot_20230711_110942](https://github.com/mjmlio/mjml/assets/115456684/a31266eb-31f1-4409-bcd5-de9064c8859f)

So there is no way to have the result of the preview  ?

**Comment by AntoineDesinety** [comment]
Hi, 

This is what i have on the preview of your tools : 
![image](https://github.com/mjmlio/mjml/assets/115456684/104f5991-4ddc-4ea9-838e-635b2d59ced0)

And this is what i have when i send my mail : 
![Screenshot_20230711_110942](https://github.com/mjmlio/mjml/assets/115456684/a31266eb-31f1-4409-bcd5-de9064c8859f)

So there is no way to have the result of the preview  ?

**Comment by iRyusa** [comment]
How did you send your email here can you try with https://putsmail.com/ ?
What email client is this ?

**Comment by AntoineDesinety** [comment]
Ok this is working with putsmail but i need to use it with Outlook :
![image](https://github.com/mjmlio/mjml/assets/115456684/a039a272-0a46-4966-85e1-d2178db50ecd)
![image](https://github.com/mjmlio/mjml/assets/115456684/742fc6ca-856e-48d9-8376-b451cd0640b3)
![image](https://github.com/mjmlio/mjml/assets/115456684/e2417191-6b8b-41c2-935e-e7e3128d8b0a)

Or something like that

**Comment by iRyusa** [comment]
Outlook does alter the HTML generated by MJML so you can't send email like that. Use a ESP on a free tier or something like that

**Comment by AntoineDesinety** [comment]
Ok thank you very much !
