### ISSUE TITLE
How to place a tracking code before </body> ?

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#271]
I need to place litmus tracking code inside my email

> Simply copy and paste the following snippet before the closing body tag of your email's HTML. Once you've inserted the snippet, you'll have a chance to ensure it's working correctly.

![summary litmus fgi3e](https://cloud.githubusercontent.com/assets/77309/15447678/a6b4d84e-1f67-11e6-9ff1-1a9bd87dd5ea.jpg)

Is there a way to keep it before </body> in MJML? I know I can do this by editing HTML but if there are lots of mail then editing will take time

In MJML it's being rendered inside div and table https://mjml.io/try-it-live/fe93125d232c4fba6de0aee0d1005e71

**Comment by jitendravyas** [comment]
No commment on this?

**Comment by ngarnier** [comment]
Hey @jitendravyas, sorry for not answering earlier, quite busy with the [2.1.0 release](https://github.com/mjmlio/mjml/releases/tag/2.1.0) :-).

You won't be able to achieve this directly, what could work is a custom component with a post render to make sure your code is included just before the `</body>` tag.

**Comment by ngarnier** [comment]
Hi, I'm closing this as there's no update and not really a better option than using a post render or adding it straight into the `HTML`.
