### ISSUE TITLE
Gmail just dropped support for background images. 

### ISSUE THREAD

**Issue by draglabs** [mjmlio/mjml#2716]
**Describe the bug**
As of Jul 15th gmail nolonger supports background images and MJML background property repeats indefinitely. 
https://www.mailix.com/gmail-drops-support-for-background-images/

**To Reproduce**
1. Create a file with this MJML code: `
```

<mj-section css-class="block-end" background-color="#DEECE5" background-url="https://remote-public-sync.s3.amazonaws.com/ethos/assets/block-end-a.png" background-size="40px" background-position-x="90%" background-position-y="0px" background-repeat="no-repeat">
      <mj-column>
        <mj-spacer height="14px" />
      </mj-column>
    </mj-section>
 
```
4. Render it to HTML 
5. Send the HTML to an email address ending in gmail.com
6. See error

**Expected behavior**
background image should be contained and non repeating. 
- This is also an issue with mj-wrapper
**MJML environment (please complete the following information):**
 - MJML Version [e.g. 4.2.0]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**
<img width="419" alt="Screenshot 2023-07-23 at 4 51 37 PM" src="https://github.com/mjmlio/mjml/assets/17034358/c84b320d-9b48-4656-8f3f-7e7b81a007cf">

**Additional context**
I have made some project toward a patch by using u + * {
background: center top / cover no-repeat;
}
But that will left align the whole email, and does not work on all background images.

**Comment by deju** [comment]
[https://issuetracker.google.com/issues/291989158](https://issuetracker.google.com/issues/291989158)  Gmail team acknowledged the issue and is rolling out a fix.

**Comment by iRyusa** [comment]
Not so much we can do on our side here. I'm closing, keep looking at the thread suggested by @deju !
