### ISSUE TITLE
Blank E-Mail with stationary Apple Mail and Google Fonts

### ISSUE THREAD

**Issue by nicmare** [mjmlio/mjml#2719]
**Describe the bug**
in Apple Mail App for MacOS the message body is blank. in case someone else is stumbling upon this, i created this ticket.

**To Reproduce**
1. Create a file in the **APP** with this MJML code: `<mjml>...</mjml>`
2. insert Google Fonts code
3. send the email to a Apple Mail Client and try to view the mail
4. See the blank body of the mail

**Expected behavior**
should render the mail

**MJML environment:**
 - Mac OS Ventura
 - MJML Version 4.12
 - MJML App 3.0.4

**Email sending environment(for rendering issues)**:
 - PHP sendmail

**Affected email clients (for rendering issues):**
 - Email Client Apple Mail V16
 - MacOS Ventura

**Screenshots**

**Additional context**
i've noticed mjml produces some weird code around the google fonts part. When i alter the code, Apple Mail renders the body of the mail properly. 
before (resulting in blank email):
<img width="199" alt="image" src="https://github.com/mjmlio/mjml/assets/898582/dec6f871-44ac-4daa-a4a0-97f361a4410a">
after (working properly):
<img width="198" alt="image" src="https://github.com/mjmlio/mjml/assets/898582/e03b94e2-03b6-4ed9-a827-f44aa7b96f56">

**Comment by iRyusa** [comment]
Can you try with https://putsmail.com/ ? You might have something altering
your HTML here.

**Comment by iRyusa** [comment]
Feel free to reopen with more details
