### ISSUE TITLE
Support including inline text during rendering

### ISSUE THREAD

**Issue by orf** [mjmlio/mjml#2721]
**Is your feature request related to a problem? Please describe.**

We would like to use MJML in combination with another templating language. The MJML templates would be rendered to HTML and then this HTML would be passed through the templating system. For example:

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
	{% if foobar %}
        <mj-text>{{ foobar }}</mj-text>
        {% endif %}
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

The problem is that the `{% if foobar %}` and `{% endif %}` text is stripped from the output.

**Describe the solution you'd like**
The ability to keep such inline text contents during rendering would be very handy, i.e treating `{%` and `%}` as ending/closing tags.

**Describe alternatives you've considered**
You can work around this by using `mj-raw`:

```
<mj-raw>{% if foobar %}</mj-raw>
<mj-text>{{ foobar }}</mj-text>
<mj-raw>{% endif %}</mj-raw>
```

However this is not fantastic and makes it quite hard to read.

**Additional context**
If used incorrectly, these templating conditionals in the rendered HTML could break the layout if wrapped around columns or other layout-specific elements. However this is an advanced feature, and if used only within specific contexts (like "include this button or text if some variable is true") then it would be safe.

**Comment by iRyusa** [comment]
As some templating language looks like XML-ish the parser goes crazy with this. 
The only solution was to wrap everything in mj-raw, or pre-process templating before render with MJML.

I'm closing because there's no real solution about this even if we would maintain a parser on our own it's just too many case to handle.
