### ISSUE TITLE
Update to Terser to Resolve ReDoS Vulnerability

### ISSUE THREAD

**Issue by Prefinem** [mjmlio/mjml#2722]
The [html-minifier package](https://www.npmjs.com/package/html-minifier) hasn't been updated for nearly 4 years and has a https://github.com/kangax/html-minifier/issues/1135. Terser has forked the repo and is actively maintaining it under [html-minifier-terser](https://www.npmjs.com/package/html-minifier-terser).

Can mjml get updated to use the maintained package from Terser?

**Comment by iRyusa** [comment]
We won’t using Terser package as it’s way too big. I’m still working on remove minify as a dependency and put it as optional : if you run mjml only locally you don’t really care about this security issue.On 8 Aug 2023, at 20:45, William ***@***.***> wrote:﻿
The html-minifier package hasn't been updated for nearly 4 years and has a kangax/html-minifier#1135. Terser has forked the repo and is actively maintaining it under html-minifier-terser.
Can mjml get updated to use the maintained package from Terser?

**Comment by Prefinem** [comment]
We have templates running on the fly as we have mustache inside of html.

Is there any help that you need with removing the minify?  Would you take a PR for this?

**Comment by iRyusa** [comment]
Just don’t rely on mjml minify then you should be fine. I have an open PR on this it just need to be tested.On 8 Aug 2023, at 20:51, William ***@***.***> wrote:﻿
We have templates running on the fly as we have mustache inside of html.
Is there any help that you need with removing the minify?  Would you take a PR for this?

**Comment by Prefinem** [comment]
We don't minify but the package is getting scanned and that's causing issues since it's in the dependencies.

No worries, I will manually build for now and upgrade later

**Comment by tschoffelen** [comment]
This is still making bundling more complicated as well - any progress in marking as optional? I'm happy to put in a PR - any guidance on if you want to do something code wise, or just move it to `optionalDeps` in package.json?

**Comment by iRyusa** [comment]
👋 @tschoffelen I think `optionalDependencies` are checked too by `npm audit` and other security check.

As we're removing both beautify + minify from the lib, the HTML output from MJML is really bad, i'm looking for a lightweight alternative to beautify-js.
I'm still working on this on my free time and miss the release date that I had in mind for last month 😢 

#2589 You can reach me on MJML slack if you want 👍

**Comment by tschoffelen** [comment]
Thanks @iRyusa! I was indeed more thinking about the problem I'm having in bundling mjml with `esbuild` at the moment.

Thanks for the work you've been doing on this so far, and I understand how hard it is to find time to do this soft of stuff!
