### ISSUE TITLE
Background img

### ISSUE THREAD

**Issue by NguyenKhanhDuy612** [mjmlio/mjml#2723]
**Describe the bug**
On the desktop, I use background img different with mobile. But I am not change. I am can support. Thanks

<mj-style>
		.container-pc{
			max-width: 800px !important;
			padding: 0 !important;
		}
		  @media only screen and (min-width: 800px){
			.test-banner{
				background: url("./images/img-newsletter/banner-desktop.png") !important;
				min-width: 800px !important;
				padding: 0 !important;
			}
		  }
	</mj-style>

  <mj-section  css-class="test-banner"  background-url="./images/img-abandoned-cart/banner-mb-cart.png" padding="153px 35px 40px 35px">

**Comment by iRyusa** [comment]
We need more information to help you here. Please provide a full snippet here https://mjml.io/try-it-live
