### ISSUE TITLE
Responsive image and text in mj-group

### ISSUE THREAD

**Issue by Apricosma** [mjmlio/mjml#2724]
Hello, I'm trying to create a layout with an image that's about 1/3th the size and text aligned to the right that fills up the rest of the 2/3rds. When squished on mobile, I just want to to simply compress the text inwards without it adding extra lines or changing the image-size

I've tried many methods for this but nothing seems to be working, it will either crush the image, blow-out the text (it needs to be on one-line), or disobeys mj-group and stacks vertically

Here is an example of what it looks like on desktop, but the moment it goes <600px it will start affecting the layout. I just want the text to slide inwards without affecting anything else 

```mjml
<mjml>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column background-color="black" width="200px">
          <mj-image src="https://cdn.shopify.com/s/files/1/1735/0525/files/BLO_logo.jpg?height=628&pad_color=fff&v=1613692796&width=1200" fluid-on-mobile="true"></mj-image>
        </mj-column>
        <mj-column background-color="yellow" width="400px">
          <mj-text color="black" align="right">lorem ipsum delorem lorem ipsum </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>
```

Anyone got any ideas? thanks

**Comment by iRyusa** [comment]
Column need to be defined in % inside mj-group. That’s why it doesn’t work here just put 33% and 67% and it should be fine On 11 Aug 2023, at 21:10, Apricosma ***@***.***> wrote:﻿
Hello, I'm trying to create a layout with an image that's about 1/4th the size and text aligned to the right that fills up the rest of the 3/4ths. When squished on mobile, I just want to to simply compress the text inwards without it adding extra lines or changing the image-size
I've tried many methods for this but nothing seems to be working, it will either crush the image, blow-out the text (it needs to be on one-line), or disobeys mj-group and stacks vertically
Here is an example of what it looks like on desktop, but the moment it goes <600px it will start affecting the layout. I just want the text to slide inwards without affecting anything else
<mjml>
  <mj-body>
    <mj-section>
      <mj-group>
        <mj-column background-color="black" width="200px">
          <mj-image src="https://cdn.shopify.com/s/files/1/1735/0525/files/BLO_logo.jpg?height=628&pad_color=fff&v=1613692796&width=1200" fluid-on-mobile="true"></mj-image>
        </mj-column>
        <mj-column background-color="yellow" width="400px">
          <mj-text color="black" align="right">lorem ipsum delorem lorem ipsum </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-body>
</mjml>
Anyone got any ideas? thanks
