### ISSUE TITLE
Mj-Group Stacking Option Support

### ISSUE THREAD

**Issue by jeissler** [mjmlio/mjml#2726]
I would like to have an option on mj-group to allowed contained columns to stack in mobile views if desired. I understand preventing stacking is the main use case for groups but we have complex use cases where we create 2x2 or similar layouts w/ common background colors/images where we need this control.

The main issue I face is not being able to reverse stacking correctly for layouts w/o using groups where we sometimes do but not always want them to stack in mobile. Essentially we need the option to do either/or inside of a group; what I do now is I alter the markup to includes mj-group as wrappers but then need to remove them when stacking is desired—this would be much easier if groups had a `mobile-stacking` attribute (default false) making containers more flexible. 

Consider the below layout which cannot be reversed correctly for both mobile and desktop even using groups:

```
<mjml>
  <mj-body>
    <mj-section direction="rtl">
      <mj-column width="50%">
        <mj-text>4</mj-text>
      </mj-column>
      <mj-column width="50%">
        <mj-text>3</mj-text>
      </mj-column>
      <mj-column width="50%">       
        <mj-text>2</mj-text>
      </mj-column>
      <mj-column width="50%">         
        <mj-text>1</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

This seems like it would be possible if groups had stacking control where each 'row' of columns (=100% width) would become a group w/ its own direction and stacking settings

**Comment by iRyusa** [comment]
Here you example won't even work because you can't have more than 100%
content inside a section.
Can you provide an exemple of what you're trying to do (mobile + desktop
version) ?

**Comment by jeissler** [comment]
Thanks for your reply! Right or wrong we've been using the above layout stacked 2x2 like this which seems to stack correctly on mobile as well: 
<img width="1785" alt="Screenshot 2023-08-15 at 4 27 22 PM" src="https://github.com/mjmlio/mjml/assets/2342824/91f68064-9af3-41ae-8688-0770dbf33eec">
but when I reverse it on desktop I get this
<img width="1714" alt="Screenshot 2023-08-15 at 4 26 48 PM" src="https://github.com/mjmlio/mjml/assets/2342824/fdcbc6c8-b404-49ce-9ecb-c37df1bb4e00">

my thought is to have a group containing each 'row' (ie 2x columns = 100%) and then I could fix the reverse problem if 'allow stacking' was a thing on `mj-group`

**Comment by jeissler** [comment]
> You can't have more than 100 % of content inside a section even if it looks to work in browser it won't in many clients

I hadn't considered that to be a problem, that said it doesn't seem like we can achieve what we're after w/o 2 separate sections. Essentially I'm just trying to create a 2x2 layout that can be reversed properly where the grey is a common parent (section)
desktop
<img width="604" alt="Screenshot 2023-08-15 at 4 49 32 PM" src="https://github.com/mjmlio/mjml/assets/2342824/15a16c0d-efb0-4425-9a41-6394d7e51722">
mobile
<img width="320" alt="Screenshot 2023-08-15 at 4 49 37 PM" src="https://github.com/mjmlio/mjml/assets/2342824/746aba61-611a-4cd5-b524-03c9fdf268c7">

**Comment by iRyusa** [comment]
Then just apply a wrapper arround both of the section
https://mjml.io/try-it-live/hnu4LY1LZm and you'll be fine ? There's no need
need to reverse anything in your screenshot here

**Comment by jeissler** [comment]
Great idea, appreciated! We just need to be more mindful of the 100% width when adding layout options; I had some suspicion that might not work well. In the above I just need the ability to reverse and prevent mobile stacking in some cases for the same layouts

**Comment by jeissler** [comment]
The only thing I'm unable to do altering that example is reverse mobile stacking and I think its not going to be possible because of how table direction property works. Unless I'm missing something it doesn't seem at all possible w/ rendered tables to get 2 sections to reverse stacking top/bottom? Essentially the same as above but reversed for mobile like:
desktop
<img width="599" alt="Screenshot 2023-08-16 at 10 06 02 AM" src="https://github.com/mjmlio/mjml/assets/2342824/cc878887-d3df-4014-9c90-c86c4865f3ce">
mobile (reversed)
<img width="320" alt="Screenshot 2023-08-16 at 10 05 42 AM" src="https://github.com/mjmlio/mjml/assets/2342824/a9abe42f-5c6a-4361-8630-4a931047c0d8">

**Comment by iRyusa** [comment]
Nop there’s no way to handle that layout in MJMLOn 16 Aug 2023, at 17:43, Jeremy Eissler ***@***.***> wrote:﻿
The only thing I'm unable to do altering that example is reverse mobile stacking and I think its not going to be possible because of how table direction property works. Unless I'm missing something it doesn't seem at all possible w/ rendered tables to get 2 sections to reverse stacking top/bottom? Essentially the same as above but reversed for mobile like:
desktop

mobile (reversed)

**Comment by jeissler** [comment]
Okay thanks for your quick replies and help troubleshooting the issues we've faced; love mjml thank you!
