### ISSUE TITLE
Mixed Shorthand & Longhand Padding Properties in Rendered Html

### ISSUE THREAD

**Issue by jeissler** [mjmlio/mjml#2727]
When setting `padding` shorthand and `padding-side` longhand both are rendered into html which we've seen cause some confusion between clients and authors. Mostly it has been the default shorthand attributes not being accounted for when setting only per side attributes explicitly where we then end up w/ styles like this `padding: 0 20px; padding-left: 10px; padding-right: 10px`. 

It seems like the most correct thing would be for the html to render only one or the other w/ priority on whatever is user defined essentially merging the values into a single set.

I would propose for html all padding just be translated to shorthand, but vice-versa would work equally as well. What I've done in our install is to set `padding="none"` where it's been problematic and strip it from the rendered html before saving/sending. This works for now and was needed as just zeroing out the default padding wasn't enough to fix all cross-client issues.

**Comment by iRyusa** [comment]
Hi !

I'm not sure what to do about this. We've discussed it in the past and we
did conclude to keep it "simple" and just let it behave as it does in CSS.
I know that it would save some few extra bytes when minified, but it could
add some unwanted side effect like override a non inlined value from css
selectors.

**Comment by jeissler** [comment]
Thanks for your reply! I understand and would agree if cross-client seemed consistent w/ mixed values. Another idea is to remove the `padding` property altogether if it doesn't contain a valid value; ex `padding="none"` on an mjml element doesn't output padding prop to html in my install

**Comment by iRyusa** [comment]
Keep in mind padding is actually used in some component to compute ghost
table values, so it might add some non desired complexity just to handle
padding. Why don't you just never rely to padding-[direction] in your MJML
? Maybe you can add a linting rules to avoid them in your MJML documents ?

**Comment by jeissler** [comment]
We could do that but would be a good refactor for our current setup; we have a lot of options that touch padding and its much easier to manage when I don't have to split the values for each side to make decisions. Border options are that way where only shorthand is allowed. Only ever setting padding shorthand is basically equal to merging the shorthand and longhand values (I think) which to me is the logical default expectation especially if only shorthand is considered for certain things

**Comment by iRyusa** [comment]
Yeah but here it's just a 1-o-1 binding to CSS behavior, changing this
would require to :
- document this properly to new user
- explain the "why" we does that
-  explain potential issue you could encounter with this

I'm not sure that the benefits from this overtake the overhead it adds

**Comment by jeissler** [comment]
I understand, I think maybe this 'ghost' behavior is actually what tripped us up and now I'm a bit weary of setting padding to invalid values if thats whats always used for them. Ie I'm not sure now what to expect for the ghost elements if I set `padding-right="10px"` while the element has a default of `padding="0 20px"` and/or if I remove the short-hand completely.

My logic is in standard css padding-right would always override padding and in this case it doesn't (always) even if only for ghost elements. In reality I'm not sure the user expectation for having mixed values between long/short hand sets since it would be counter-intuitive in css

**Comment by iRyusa** [comment]
I guess it's a dead-end here.
Only thing that might worth to be mentioned is that `padding-left="40px" padding="0"` does the same thing as `padding="0" padding-left="40px"`. In MJML as attribute order is not preserved as it would be in CSS, so padding+direction will always override the shorthand.

**Comment by jeissler** [comment]
@iRyusa thanks for your reply, that said I'm content manually stripping the shorthand property where needed. Yahoo was the culprit that didn't seem to always render this correctly `padding="20px 0" padding-bottom="12px"` (ie default + padding-direction) but I don't have a solid reproduction case to look at
