### ISSUE TITLE
Need to update twitter icon in mj-social-element

### ISSUE THREAD

**Issue by vedanttikku12** [mjmlio/mjml#2733]
**Describe the bug**
The twitter icon shown through mj-social-element still displays the old icon. Need to update it to the newer icon. We can, of course, pass src prop but this should be default behaviour ideally.

**To Reproduce**
Pls check the code: https://mjml.io/try-it-live/RiRg8c8gnw

**Expected behavior**
mj-social-element with "twitter" as name show display the newer "X" icon

**Comment by iRyusa** [comment]
Well, we kept those default value from earlier version of MJML. I would advise to use a custom social element instead to host your own icons as we had some issue in the past cf #2551 

Twitter is not even Twitter anymore and called X 😬
