### ISSUE TITLE
Button Width as Percentage

### ISSUE THREAD

**Issue by jeissler** [mjmlio/mjml#2739]
Thanks for the great support on this project! 

I am wondering why the docs don't show `%` as an option for unit on button width here?

<img width="690" alt="Screenshot 2023-09-01 at 1 23 03 PM" src="https://github.com/mjmlio/mjml/assets/2342824/608b0d52-dba2-4063-8b36-270863329d08">

Percentage width renders w/o error in the 'try it live' on buttons but suspect there is some reason for it being omitted as a valid option

**Comment by iRyusa** [comment]
Yeah button can be defined in % too, it's a typo in the doc 👍

**Comment by jeissler** [comment]
Excellent thanks for clarifying!

**Comment by tdaulbaev** [comment]
@iRyusa button is displayed in full width, but the active area of the button is limited only by its content, if you use values in px this problem does not occur.

<img width="1598" alt="Снимок экрана 2023-09-27 в 11 55 34" src="https://github.com/mjmlio/mjml/assets/170334/13e894c6-666f-4ecd-b7c1-9c3386527ae2">

**Comment by iRyusa** [comment]
Try it live is a bit out of date here I think so it might not behave like that in latest MJML version

**Comment by jeissler** [comment]
@iRyusa not sure about the try it live playground, but I'm running `mjml-browser: ^4.14.1` and see the same

**Comment by iRyusa** [comment]
Yeah it seems like in the code in px we're able to determine the width of
https://github.com/mjmlio/mjml/blob/master/packages/mjml-button/src/index.js

It seems to have side effect that if the button in px is wider that mobile
viewport it overflow...

I don't think we'll ever be satisfied with button in email :(
