### ISSUE TITLE
Border radius isn't getting applied to border style

### ISSUE THREAD

**Issue by arpitjp** [mjmlio/mjml#2741]
**Describe the bug**
For `mj-section` & `mj-column`, border radius doesn't get applied to the border style leading to peculiar behaviour.

<img width="1200" alt="image" src="https://github.com/mjmlio/mjml/assets/37728770/52736a67-4f81-414d-9933-608cc1e58677">

**To Reproduce**
```
<mjml>
  <mj-body>
    <mj-section border="2px solid red" background-color="blue" padding="8px" border-radius="80px">
      <mj-column>
        <mj-button>
          Button
        </mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Well if you inspect the HTML here you'll se that the border is not applied at the same level of the radius/background.
As we use `border-collapse: collapse;` on table to prevent issue on outlook, we can't apply it on the same element. If compatibility isn't an issue for you, you can override this behavior on the table with a `css-class` + `border-collapse: separate;` and re apply a border-radius on the `td`

**Comment by arpitjp** [comment]
Thanks for the quick reply..!! Tried doing this, but didn't help. Some example I can refer?
```
<mjml>
  <mj-body>
    <mj-section border="2px solid red" background-color="blue" padding="8px" css-class="border-fix" border-radius="80px">
      <mj-column>
        <mj-button>
          Button
        </mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

`<< css file >>`
```css
border-fix {
      border-collapse: separate;
    }
```

**Comment by iRyusa** [comment]
Ex: https://mjml.io/try-it-live/8tUiBjdfYV
