### ISSUE TITLE
Vertical line with color from background when using direction="rtl"

### ISSUE THREAD

**Issue by kentergon** [mjmlio/mjml#2745]
**Describe the bug**
You can find my HTML and MJML code attached aswell as a link to a public litmus test from that exact HTML/MJML code. As you can see there from Outlook 2013 forward I have this weird vertical line next to my article, where I use direction="rtl". Do you have any idea how to fix this issue?

Best regards

Link: https://litmus.com/pub/5WDEyUqRY74ZcXvj
[direction.zip](https://github.com/mjmlio/mjml/files/12598763/direction.zip)

**Comment by iRyusa** [comment]
It's a known issue in outlook, it can comes off with playing with odd/even values on some elements like padding/ font-size/line-height.
You can try also to set a background color section + column + mj-text sometime it fixes it.
