### ISSUE TITLE
Columns are stacking in desktop

### ISSUE THREAD

**Issue by sumsho** [mjmlio/mjml#2748]
Hi,
I'm fairly new to mjml and trying to understand why the columns are stacking in my gmail inbox on desktop. 
I have the breakpoint set to 380px, and the visual editor shows they should be side-by-side on desktop, but when I actually send myself the html it stacks on desktop. I've posted what i'm working on below. 

https://mjml.io/try-it-live/a1cnJ6m-tL

**Comment by iRyusa** [comment]
Try to send the email with putsmail.com you most likely send it via a service that alter the html code produced by mjml.On 17 Sep 2023, at 00:12, sumsho ***@***.***> wrote:﻿
Hi,
I'm fairly new to mjml and trying to understand why the columns are stacking in my gmail inbox on desktop.
I have the breakpoint set to 380px, and the visual editor shows they should be side-by-side on desktop, but when I actually send myself the html it stacks on desktop. I've posted what i'm working on below.
https://mjml.io/try-it-live/a1cnJ6m-tL
