### ISSUE TITLE
Sections using RTL combined with paddings cause line artifacts in Outlook

### ISSUE THREAD

**Issue by jackcranston** [mjmlio/mjml#2750]
**Describe the bug**

When using RTL and paddings with `mj-section` and 1 or more inner `mj-column`, Outlook renders vertical line artifact. 

**To Reproduce**
1. Create a file with this MJML code or insert into the MJML web app: 
```
<mjml>
    <mj-body background-color="#000">
          <mj-section direction="rtl" padding="16px" background-color="#fff">
              <mj-column>
                  <mj-text>
                      <h1>test</h1>
                  </mj-text>
              </mj-column>
              <mj-column>
                  <mj-text>
                      <h1>test</h1>
                  </mj-text>
              </mj-column>
          </mj-section>
    </mj-body>
</mjml>
```
2. Render it to HTML via CLI or MJML web app
3. Send the HTML to an email address with Litmus PutsMail
4. View email in Outlook
5. See error

**Expected behavior**

To render without artifacts

**MJML environment (please complete the following information):**

 - OS: Windows
 - MJML Version 4.9.3 (web app editor) and 4.14.1 (local/npm)
 - MJML tool used: Web app and npm package

**Email sending environment(for rendering issues)**:

 - Platform used to send the email: [PutsMail](https://putsmail.com/)

**Affected email clients (for rendering issues):**

 - Email Client: Outlook 365
 - OS: Windows

**Screenshots**

![image](https://github.com/mjmlio/mjml/assets/33037351/d2486a28-c556-4934-ae1a-cbc1ba98e017)

**Additional context**

Works fine if RTL or padding are omitted.

**Comment by iRyusa** [comment]
Hi,
I've closed a similar issue about this recently : https://github.com/mjmlio/mjml/issues/2745#issuecomment-1720918281

It's a bug within outlook and not really in MJML. We can't really do anything about this, try to play with font-size/line-height/padding/...

**Comment by vielhuber** [comment]
Is there a setup/configuration that anybody knows how to prevent this reliably?
