### ISSUE TITLE
Support hsl() colors 

### ISSUE THREAD

**Issue by mikaoelitiana** [mjmlio/mjml#2751]
Currently, `hsl()` colors are not supported. The following is considered invalid 

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="hsl(0, 100%, 50%)" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

and the error message is `Attribute color has invalid value: hsl(0, 100%, 50%) for type Color`

Can we add support for `hsl` color in the validation function or is there a particular reason to avoid that?

https://github.com/mjmlio/mjml/blob/50cd15b194d39eef7a3cdc399796e6618e4a9e1a/packages/mjml-core/src/types/color.js#L16-L18

**Comment by iRyusa** [comment]
If I recall those are the only format that are supported in older clients. So I’m not sure we want to allow hsl here as we can’t really guarantee it to work On 19 Sep 2023, at 15:32, Mika Andrianarijaona ***@***.***> wrote:﻿
Currently, hsl() colors are not supported. The following is considered invalid
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="hsl(0, 100%, 50%)" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

and the error message is Attribute color has invalid value: hsl(0, 100%, 50%) for type Color
Can we add support for hsl color in the validation function or is there a particular reason to avoid that?
https://github.com/mjmlio/mjml/blob/50cd15b194d39eef7a3cdc399796e6618e4a9e1a/packages/mjml-core/src/types/color.js#L16-L18

**Comment by mikaoelitiana** [comment]
> If I recall those are the only format that are supported in older clients. So I’m not sure we want to allow hsl here as we can’t really guarantee it to work On 19 Sep 2023, at 15:32, Mika Andrianarijaona ***@***.***> wrote:﻿ Currently, hsl() colors are not supported. The following is considered invalid <mjml> <mj-body> <mj-section> <mj-column> <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image> <mj-divider border-color="#F45E43"></mj-divider> <mj-text font-size="20px" color="hsl(0, 100%, 50%)" font-family="helvetica">Hello World</mj-text> </mj-column> </mj-section> </mj-body> </mjml> and the error message is Attribute color has invalid value: hsl(0, 100%, 50%) for type Color Can we add support for hsl color in the validation function or is there a particular reason to avoid that? https://github.com/mjmlio/mjml/blob/50cd15b194d39eef7a3cdc399796e6618e4a9e1a/packages/mjml-core/src/types/color.js#L16-L18 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

@iRyusa I tried to find data about that but there was no `hsl` entry on https://www.caniemail.com/features/css-rgba/. Looking at https://caniuse.com/?search=mdn-css_types_color_hsla, there is pretty good support among browsers but that may not be representative. I did some tests on OSX Mail and GMail in browser and it works fine
