### ISSUE TITLE
`vertical-align` attribute not working on mj-social-element

### ISSUE THREAD

**Issue by oli799** [mjmlio/mjml#2752]
### **Problem:**

In the following code snippet the Facebook icon size is much larger than the other ones, when I apply the vertical-align attribute on the other two elements, they remain at bottom of the Facebook social element.

###   **Reproduction Steps:**

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-social font-size="15px" mode="horizontal">
          <mj-social-element icon-size="70px" name="facebook" href="https://mjml.io/">
            Facebook
          </mj-social-element>
          <mj-social-element vertical-align="top" name="google" href="https://mjml.io/">
            Google
          </mj-social-element>
          <mj-social-element vertical-align="middle" name="twitter" href="https://mjml.io/">
            Twitter
          </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
<img width="1278" alt="vertical-align" src="https://github.com/mjmlio/mjml/assets/32271091/6d24b1d1-211d-438e-9df7-2878aceac159">

### **Expected behaviour:**

The Google and the Twitter element should vertically aligned correctly.

<img width="1278" alt="vertical-align-correct" src="https://github.com/mjmlio/mjml/assets/32271091/778c303c-5dd8-4645-8036-5fd056fe9c4e">

### **MJML environment:**

- MJML Version 4.9.3
- MJML try-it-live tool

**Comment by iRyusa** [comment]
I guess it would be hard to fix as `vertical-align` was meant to be use for the element (and it doesn't work as the text part has a fixed vertical-align middle in the code) not relative to the other.

I've played a bit with it, it does work if we set the `vertical-align` on all 3 table in the browser but I don't think it will in Outlook.
