### ISSUE TITLE
Problem: Custom component cannot be used inside mj-column, only inside: mj-attributes

### ISSUE THREAD

**Issue by m-holstein** [mjmlio/mjml#2755]
**Describe the bug**
I am unable to use my custom component inside mj-column.

**The Comnponent**
```
import { BodyComponent } from 'mjml-core'
import conditionalTag from 'mjml-core/lib/helpers/conditionalTag'


export default class MjAcmDefaultText extends BodyComponent {
    static componentName = 'mj-acm-default-text'

    static endingTag = true

    static dependencies = {
        'mj-column': ['mj-acm-default-text'],
        'mj-acm-default-text': []
    }

    getStyles() {
        return {
            text: {
                'font-family': this.getAttribute('font-family'),
                'font-size': this.getAttribute('font-size'),
                height: this.getAttribute('height'),
            },
        }
    }

    static allowedAttributes = {
        align: 'enum(left,right,center,justify)',
        'background-color': 'color',
        color: 'color',
    }

    static defaultAttributes = {
        align: 'left',
        color: '#000000',

        padding: '10px 25px',
    }
    renderContent() {
        return `
      <div
        ${this.htmlAttributes({
            style: 'text',
        })}
      >${this.getContent()}</div>
    `
    }

    render() {
        const height = this.getAttribute('height')

        return height
            ? `
        ${conditionalTag(`
          <table role="presentation" border="0" cellpadding="0" cellspacing="0"><tr><td height="${height}" style="vertical-align:top;height:${height};">
        `)}
        ${this.renderContent()}
        ${conditionalTag(`
          </td></tr></table>
        `)}
      `
            : this.renderContent()
    }
}
```

**The build is made by custom JS**

```
let fs = require('fs'),
    path = require('path'),
    i18n = require('i18n'),
    delimiters = require('handlebars-delimiters');
    hbs = require('handlebars');
    mjml = require ('mjml');

const MjAcmDefaultText = require('../lib/MjAcmDefaultText').default;
const {registerComponent} = require('mjml-core');

let templatePath = './templates';
let outputPath = '../dist'

registerComponent(MjAcmDefaultText);

```

**Expected behavior**
Component renders in mj-column

**MJML environment (please complete the following information):**
 - OS: LINUX
 - "mjml": "^4.14.1",
 - "mjml-core": "^4.14.1",
 - "mjml-validator": "^4.13.0",
 - "gulp": "^4.0.2",
 - "gulp-babel": "^8.0.0",
 - "gulp-watch": "^5.0.1",

**Additional info**
I followed this Tutorial: https://medium.com/mjml-making-responsive-email-easy/tutorial-creating-your-own-component-with-mjml-4-1c0e84e97b36

**Comment by iRyusa** [comment]
I don't think this guide is up to date, `mjml-validator` export a `[registerDependencies](https://github.com/mjmlio/mjml/blob/master/packages/mjml-validator/src/dependencies.js#L31)` that you have to call manually.

**Comment by m-holstein** [comment]
Is there a guide for the current version of MJML?

**Comment by m-holstein** [comment]
After thousands of trys, it finally works.
I've put the call on top of the class:

`
.....
import { registerDependencies } from 'mjml-validator'

registerDependencies({
    'mj-column': ['mj-acm-default-text'],
    'mj-acm-default-text': ['mj-text', 'mj-raw']
})

export default class MjAcmDefaultText extends BodyComponent {
....
`
(code tag does'nt like my code :) )

Is there a easy way to accept al components as child dependencies, or must I note every single component?
