### ISSUE TITLE
Twitter X logo update for mjml social icons

### ISSUE THREAD

**Issue by comc49** [mjmlio/mjml#2757]
**Is your feature request related to a problem? Please describe.**
Twitter X logo is not available

**Describe the solution you'd like**
Twitter X logo for the social icons component

**Describe alternatives you've considered**
Hi can we add Twitter's new logo please?

**Additional context**

**Comment by iRyusa** [comment]
Hi we’ve already replied here https://github.com/mjmlio/mjml/issues/2733 we probably won’t add it as it’s better to host your own icons On 22 Sep 2023, at 18:03, Brian Koo ***@***.***> wrote:﻿
Is your feature request related to a problem? Please describe.
Twitter X logo is not available
Describe the solution you'd like
Twitter X logo for the social icons component
Describe alternatives you've considered
Hi can we add Twitter's new logo please?
Additional context
Add any other context or screenshots about the feature request here.

**Comment by comc49** [comment]
What's the best way of hosting our own icon?
