### ISSUE TITLE
Accept mj-include template in Text

### ISSUE THREAD

**Issue by m-holstein** [mjmlio/mjml#2758]
**Is your feature request related to a problem? Please describe.**
I need to include a template in a Text like:
` {%trans "upnext.inputNeeded" '<mj-include path="./templates/includes/workflow-link" />'%}
`

The `{%trans <textKey> '<Text1>' 'Text2' '...' %}` is used by a translator function that will later use the content of the mj-include in translated string.

I have tried a custom component but this would be to complicated or nearly impossible.
I need this in many scenarios

Best solution would be that mj-text would accept mj-include like MJMLv3

**Comment by iRyusa** [comment]
We did remove that because Ending Tag can contain non parsable HTML/XML. So we won't going to revert that change.

If you're already using a templating language why would you rely on mj-include here ?

**Comment by m-holstein** [comment]
> We did remove that because Ending Tag can contain non parsable HTML/XML. So we won't going to revert that change.
> 
> If you're already using a templating language why would you rely on mj-include here ?

This is no templating language. This is only a tool to translate strings in the pre rendered MJML Template.
