### ISSUE TITLE
Apple Mail 16 empty space between sections

### ISSUE THREAD

**Issue by malanga31** [mjmlio/mjml#2761]
**Describe the bug**
Apple Mail 16 is showing an empty space between sections when these sections has paddings = 0px.

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2. Render it to HTML by doing '...'
3. Send the HTML to an email address with '...'

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [4.9.3]
 - MJML tool used [try it live]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [Litmus]  

**Affected email clients (for rendering issues):**
 - Email Client [Apple Mail 16] 
![Screenshot 2023-10-02 12 17 03 PM](https://github.com/mjmlio/mjml/assets/42441501/f62683b8-cb30-461d-bdb5-d2375dcebd31)

**Screenshots**

**Comment by iRyusa** [comment]
Hi.

Hard to say without the MJML to reproduce here. Please past it here : https://mjml.io/try-it-live
