### ISSUE TITLE
Set ses:tags to enable AWS SES tracking on mj-button

### ISSUE THREAD

**Issue by ucals** [mjmlio/mjml#2762]
**Is your feature request related to a problem? Please describe.**
To track button clicks, we need to setup `ses:tags=key1:value1;key2:value2` in the `mj-button`.

**Describe the solution you'd like**
Have `mj-button` to accept `ses:tags` as mentioned above.

**Describe alternatives you've considered**
No alternatives

**Comment by iRyusa** [comment]
Hi,

You should use https://documentation.mjml.io/#mj-html-attributes for that
