### ISSUE TITLE
Twitter icon for social component

### ISSUE THREAD

**Issue by brettandrew** [mjmlio/mjml#2763]
The current social shows the old logo for Twitter (tweety bird). Can we get this updated to the new X.

e.g.
<mj-social-element name="twitter-noshare" href="[Field2]">            
          </mj-social-element>
          
The rendered image for twitter is being retrieved from:
https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter.png

![Screenshot 2023-10-11 191410](https://github.com/mjmlio/mjml/assets/4198665/43689b22-0721-48a4-b43d-be9198b3a034)

**Comment by iRyusa** [comment]
We've already replied in multiple issues : #2733 you should add your own icons instead we won't really update it as we had multiple issue with default icons in the past

**Comment by brettandrew** [comment]
Thanks!

Was able to add my own Twitter icon using src that works fine. 

<mj-social-element name="twitter-noshare" src="[add your own URL to a 72px72px X icon here.png" href="[Field2]"  padding="8px"></mj-social-element>
