### ISSUE TITLE
mj-body doesn't support width='100%' for ms outlook

### ISSUE THREAD

**Issue by rasimsen** [mjmlio/mjml#2766]
**Describe the bug**
it is not working for ms outlook, but works fine for others when I want to give 100% width to mj-section over mj-body.

**To Reproduce**
example case: 
`
<mjml>
  <mj-body width="600px" background-color="#ffffff">
    <mj-body width="100%">
      <mj-section>
        <mj-column>
          <mj-text>hello world!</mj-text>
        </mj-column>
      </mj-section>
    </mj-body>
  </mj-body>
</mjml>
`

**output as an html**
`
...
  <body>
    <div style="background-color: #fff">
      <div>
        
        <div style="margin: 0 auto; max-width: 100%">
          <table
            align="center"
            border="0"
            cellpadding="0"
            cellspacing="0"
            role="presentation"
            style="width: 100%"
          >
...
...
`

**Expected behavior**

As you see on the HTML output, if mso, it generates a code like : style="width:100%;" **width="100"** 

In here, for outlook, it breaks the styling. When I look at the mjml-section source code, the code is as follows: 

**Source**: https://github.com/mjmlio/mjml/blob/a7847de40c42b587eab21956dfbbe455fcfbf440/packages/mjml-section/src/index.js#L196C1-L210C8

`
...
...
    return `
      <!--[if mso | IE]>
      <table
        ${this.htmlAttributes({
          align: 'center',
          border: '0',
          cellpadding: '0',
          cellspacing: '0',
          class: suffixCssClasses(this.getAttribute('css-class'), 'outlook'),
          role: 'presentation',
          style: { width: `${containerWidth}` },
          width: parseInt(containerWidth, 10),
          ...bgcolorAttr,
        })}
      >
...
`

as seen above, line number 207 breaks the styling. I think that, it needs to be fixed, otherwise, when you create a new mjml component which is extended from mj-body will have a styling problem on MS Outlook as we live right now. 

**Screenshots**

![Screenshot 2023-10-23 at 13 47 07](https://github.com/mjmlio/mjml/assets/747677/bb2003a1-f638-4166-ad65-ba174860628e)
![Screenshot 2023-10-23 at 13 47 57](https://github.com/mjmlio/mjml/assets/747677/16096e77-9a42-4552-a1af-e6430cfada92)

from the source: 
![Screenshot 2023-10-23 at 13 49 32](https://github.com/mjmlio/mjml/assets/747677/23030ec0-2a07-43de-b87b-b916286bd5cc)

**Additional context**

**Comment by iRyusa** [comment]
Width need to be defined in `px` because outlook ghost table can't be defined in percent.
![Screenshot 2023-10-23 at 15 36 08](https://github.com/mjmlio/mjml/assets/570317/d54e3286-02f5-43ae-9ea2-23d3ee9d7080)
