### ISSUE TITLE
Update Medium logo to latest version

### ISSUE THREAD

**Issue by ethan-bc** [mjmlio/mjml#2780]
The `social-element` logo for Medium.com is still using the old version. 

The new logo can be found [here](https://www.dropbox.com/s/fg1x3ekgvsn1h7q/Logo.zip?dl=0) and brand guidelines [here](https://medium.design/logos-and-brand-guidelines-f1a01a733592).

**OLD LOGO**
<img width="106" alt="image" src="https://github.com/mjmlio/mjml/assets/78871177/36dd2f1d-dc6f-4829-b07b-79095f452a3b">

**NEW LOGO**
<img width="106" alt="image" src="https://github.com/mjmlio/mjml/assets/78871177/f9b305f3-5fa6-442f-b622-318e39d82525">

**Comment by iRyusa** [comment]
👋 
It's not yet mentioned to the doc yet but we won't update the social-element "fixed" list as it relies on hosting logo somewhere we can't manage. Yet Mailjet does host them, but in the past they did removed them accidentally opening numerous issue here and on Slack. 

You should use the regular version : 
```
<mj-social-element href="url" background-color="#FF00FF" src="path-to-your-icon">
  Optional label
</mj-social-element>
```
