### ISSUE TITLE
Background Color of `mj-section` having alpha value is not rendering correct 

### ISSUE THREAD

**Issue by anasvakyathodi** [mjmlio/mjml#2781]
The `mj-section` background colour is not consistent with the provided colour.
1. If `full-width` is not applied and `background-color` has opacity, then the rendered colour is twice the opacity of the provided colour
 (cause: one extra is `div` is visible outside `table` which applies background colour again)
<img width="2007" alt="image" src="https://github.com/mjmlio/mjml/assets/44634141/6025c82a-a5ab-4910-9f3b-08a2c3a8eb45">
2. if `full-width` is applied then it is coming as expected (div is not coming as container)
<img width="1545" alt="image" src="https://github.com/mjmlio/mjml/assets/44634141/e00944dd-0264-498a-9dfd-2c50a4abec9b">

example:
https://mjml.io/try-it-live/Sp1jjApCm7

https://github.com/mjmlio/mjml/assets/44634141/263fc1c0-85c8-46e1-bd5d-70e7340cd46b

**Comment by anasvakyathodi** [comment]
Sample code:

```
<mjml>
  <mj-body>
    <mj-section background-color='rgba(76, 175, 80, 0.07)' >
      <mj-column>
        <mj-text>
          section without fullwidth - color not correct
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color='rgba(76, 175, 80, 0.07)' full-width='full-width'>
      <mj-column>
        <mj-text>
          section without fullwidth - color correct
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
You should just avoid rgba in email as there's multiple fallback for various email clients. It's just not recommended to use : you should stick to hex color.

**Comment by iRyusa** [comment]
As said opacity won't work because we need to handle fallbacks for various email clients.
