### ISSUE TITLE
Automatic component dependencies registration when dependency static key is present

### ISSUE THREAD

**Issue by Freezystem** [mjmlio/mjml#2784]
### Is your feature request related to a problem? Please describe.

I'm currently working on a custom component and I struggled a bit to understand why, despite registering my component and have the proper static `dependencies` key in my class, I was forced to manually call the `registerDependencies()` helper from `mjml-validator`.  

Is this an intended behavior ? 

I guess it is worth asking because I apparently was not the first person to encounter [this problem](https://github.com/mjmlio/mjml/issues/2755).

### Describe the solution you'd like

Is it possible to check and automatically register the dependencies if the static `dependencies` key is present in the component class when using `registerComponent()` from `mjml-core` ?

Could even be behind a flag given as a second `options` argument if we want to be sure we do not break existing code.

If you think it could be a good thing to implement I'm willing to make the corresponding PR to add this feature.

### Describe alternatives you've considered

Keep on using `registerDependencies()` or `.mjmlconfig` file to register my component.

### Additional context

The component I'm working on: https://github.com/Freezystem/mjml-bar-chart

**Comment by iRyusa** [comment]
I can't remember why, but I think at somepoint it was to make `mjml-validate` totally optional and not required in `mjml-core`.
Feel free to do a PR about this 👍
