### ISSUE TITLE
Using custom Google Fonts

### ISSUE THREAD

**Issue by brfignoni** [mjmlio/mjml#2786]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but I would like to know if it is possible to use custom fonts with gmail.

**Describe the solution you'd like**
I would like mj-font to work with gmail.

**Describe alternatives you've considered**
None. I just tried using a gustom google font with a mj-font tag, and it is displaying correctly on my local testing environment, but when I send the email using gmail to myself, the custom google font is not rendered, but Arial.

**Additional context**
I have followed/used this example: https://github.com/mjmlio/mjml/blob/master/packages/mjml-head-font/README.md

**Comment by iRyusa** [comment]
Gmail doesn’t support external font so there’s nothing you can do about this.On 4 Dec 2023, at 02:27, brfignoni ***@***.***> wrote:﻿
Is your feature request related to a problem? Please describe.
It is not a problem, but I would like if it is possible to use custom fonts with gmail.
Describe the solution you'd like
I would like mj-font to work with gmail.
Describe alternatives you've considered
None. I just tried using a gustom google font with a mj-font tag, and it is displaying correctly on my local testing environment, but when I send the email using gmail to myself, the custom google font is not rendered, but Arial.
Additional context
I have followed/used this example: https://github.com/mjmlio/mjml/blob/master/packages/mjml-head-font/README.md

**Comment by brfignoni** [comment]
@iRyusa thanks so much for such a quick reply, and for this wonderful tool.
