### ISSUE TITLE
Squared Images

### ISSUE THREAD

**Issue by brfignoni** [mjmlio/mjml#2788]
**Is your feature request related to a problem? Please describe.**
I am not sure this is a request, because may be there is already a solution, which I am not aware of.

My client needs to display a list of products. Each product displays an image and a description, and the image needs to be always the same size, and squared. The problem is that the images are provided by the users, which means that the images size and format will always be different. So I need to provide a solution.

I was thinking about setting the image as background image, with _background-size:cover_, but the background-image would be applied on a column (this is a requirement, because I need two columns: one for the image, and the other one for the product description). 

This is my actual mjml markup:

```
<!-- Order | item -->
      <mj-section mj-class="space-top">
        <mj-group>
          <mj-column
            mj-class="space-right squared-col"
            width="15%"
            vertical-align="middle"
          >
            <mj-image
              css-class="object-fit"
              align="left"
              src="../images/camera-1.jpeg"
              alt="camera"
            />
          </mj-column>
          <mj-column width="85%" vertical-align="middle">
            <mj-text> Cámara vintage tipo arte. </mj-text>
          </mj-column>
        </mj-group>
      </mj-section>
```

So, I would remove the mj-image, and apply the image as a background-image on the mj-column. The problem is that the linter tells me that background-url _is illegal_ on the mj-column.

**Describe the solution you'd like**
To be able to apply background-url on other mj-components, like the mj-column in this case.

**Describe alternatives you've considered**
Inserting a mj-section inside the mj-column, but it is ilegal as well.

**Additional context**
I would appreciate any help/suggestion on how to solve this issue.

<img width="517" alt="Screen Shot 2023-12-05 at 01 27 11" src="https://github.com/mjmlio/mjml/assets/133654146/9d3b27f0-6eff-4874-99ff-d9a8e28913bf">

**Comment by iRyusa** [comment]
👋 
You can just set `width` + `height` on `mj-image`, and rely on `object-fit` if supported ?
