### ISSUE TITLE
Set Position

### ISSUE THREAD

**Issue by LOGESHWARAN2** [mjmlio/mjml#2789]
I'm struggling to fix the design in MJML. And I'm added to here the design and I'm getting this output. 
Text-decoration not set in position when i sent a mail.

![Screenshot 2023-12-05 151028](https://github.com/mjmlio/mjml/assets/91491027/f7f3239c-5c7c-432d-ad1c-cb6b876a58c3)
![Screenshot 2023-12-05 151200](https://github.com/mjmlio/mjml/assets/91491027/b8c54ffc-d8c8-4519-bd27-f21766ff1538)

**Comment by iRyusa** [comment]
Without any MJML to reproduce and that few details it's hard to help here.
