### ISSUE TITLE
message clipper

### ISSUE THREAD

**Issue by brfignoni** [mjmlio/mjml#2790]
**Describe the bug**
Hi, 

This is not a bug related to mjml, but I think you might be aware of a solution, since this tool is all about emails. The issue I am having is that I am seeing my email clipped on gmail:

<img width="1148" alt="Screen Shot 2023-12-06 at 18 54 28" src="https://github.com/mjmlio/mjml/assets/133654146/61279fe8-2bbb-4a0e-805d-27acb62a7b42">

I sent that test with [litmus](https://putsmail.com/tests/new). 
I tried minifying the email, but the issue remains. 

**To Reproduce**
Copy [this email html](https://raw.githubusercontent.com/brfignoni/stan/main/mjml-mails/order/layouts/html/owner_new-order--new.html) and try sending to a gmail email with [litmus](https://putsmail.com/tests/new).

**Expected behavior**
The full email (not clipped).

**MJML environment (please complete the following information):**
 - OS: MacOS Monterey
 - MJML Version: 4.14.1
 - MJML tool used npm package

**Email sending environment(for rendering issues)**:
 - Platform used to send the email: [litmus](https://putsmail.com/tests/new). 

**Affected email clients (for rendering issues):**
 - Email Client: Gmail (the only one I tried)

**Screenshots**
<img width="1148" alt="Screen Shot 2023-12-06 at 18 54 28" src="https://github.com/mjmlio/mjml/assets/133654146/5a431dd7-322d-4430-8232-5dcacfa60d89">

**Additional context**
None

**Comment by iRyusa** [comment]
It only means your email HTML is too big. You most likely need to simplify
your MJML first

**Comment by iRyusa** [comment]
Yeah you're using way too many section, things can be simplified with an
html table in most of your cases.

I don't have time to do a full review tho : don't rely on mj-group just to
stick two text, use a regular table instead try to stick to single
section+column as much as you can.

**Comment by brfignoni** [comment]
@iRyusa thank you. 
I am not sure if I understand how this works. 
If I try to use a mj-text directly inside a mj-wrapper, I get told that "mj-text cannot be used inside mj-wrapper, only inside: mj-attributes, mj-column, mj-hero". So I try to use a mj-column. But then, again, If I try to use a mj-column inside a mj-wrapper, I get told that "mj-column cannot be used inside mj-wrapper, only inside: mj-attributes, mj-group, mj-section". 

So I end up using a mj-section, to be able to use a mj-column, to be able to use a mj-text.

**Comment by iRyusa** [comment]
You need to have a column inside your section, but just to explain visually this :
<img width="477" alt="Screenshot 2023-12-07 at 17 00 09" src="https://github.com/mjmlio/mjml/assets/570317/6c602f14-4299-491e-9ab8-77c26b5fb739">

Should be a single section with 1 column and you handle everything inside a single mj-text.

**Comment by brfignoni** [comment]
@iRyusa I am sorry,  but I have to ask you: You suggested me to use only one column. How is this? As you can see, I have two columns for each "row": The text on the left (red), and the text on the right (blue). I am doing this for each "row".  If I use only one column, I lose the ability to have responsive columns (left and right).

![mjml](https://github.com/mjmlio/mjml/assets/133654146/24996eee-0c8e-4a8b-805f-6e4ce84ab1d1)
