### ISSUE TITLE
Setting width in mj-column adds left and right padding

### ISSUE THREAD

**Issue by yuzhouliu9** [mjmlio/mjml#2801]
**Describe the bug**
When `mj-column`  has `width` defined it seems to add left and right padding. I would have expected it to still take up the entire body size.

Here is with `width="25%"` on first column. Notice the extra left and right white space.
![image](https://github.com/mjmlio/mjml/assets/89029096/3d227ba6-115a-49fc-98ed-ecf9527e3da8)

Without `width="25%"`. Notice less left and right white space.
![image](https://github.com/mjmlio/mjml/assets/89029096/58b4f1de-509b-4369-9884-20b558559c45)

**To Reproduce**
Use MJML app. See above for reproduction. The rendered result in email client is same.

**Expected behavior**
The full `mj-body` or outer `mj-section` is taken up by the columns regardless if `width` is set or not. With `width="25%"` set, it should still align as left as possible taking up 25% of space. While the other column takes up rest of the space. The total available space should not have shrunk.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: 4.12.0
 - MJML tool used: MJML App

**Email sending environment(for rendering issues)**:
N/A.

**Affected email clients (for rendering issues):**
N/A

**Comment by iRyusa** [comment]
This is not something we can really manage here, this behavior come from default value of `width` for column.
<img width="1127" alt="Screenshot 2024-01-09 at 13 11 02" src="https://github.com/mjmlio/mjml/assets/570317/7a952f7b-31c3-4b6a-ac5e-700612f39167">

Here you have a 25% column + a 50%, extra 25% missing is just controlled by the `text-align` on `mj-section`
