### ISSUE TITLE
Columns are aligning Vertically in desktop mode, when applying border using css class

### ISSUE THREAD

**Issue by TejasGupta31** [mjmlio/mjml#2804]
**Describe the bug**
When applying border using css-class, columns are getting aligned vertically instead of horizontally.
I am applying border using css-class because of border-radius.
<img width="1725" alt="Screenshot 2024-01-09 at 5 13 57 PM" src="https://github.com/mjmlio/mjml/assets/76782463/46ccd74e-97b3-4cd5-8fc7-d3f3a8f5be19">

**To Reproduce**
```
<mjml>
    <mj-head>
    <mj-style>
      .red-text {
      	border: 5px solid red;
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column css-class="red-text">
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

```

**Comment by iRyusa** [comment]
This is how HTML works here https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
You can subtract manually the border size to your column width and define them as `px` instead of `%`
