### ISSUE TITLE
truncated text on Outlook desktop

### ISSUE THREAD

**Issue by koutatmed** [mjmlio/mjml#2807]
Hi
When I send an email with a text font size of 20px, I receive the email with truncated text on Outlook desktop. However, on Outlook's official website, it works fine. I have attached the screenshots of the bug for reference. thanks

![Captu2e](https://github.com/mjmlio/mjml/assets/94910935/88c11b5e-6275-46c4-a6ec-da121b8ddf84)
![Capture](https://github.com/mjmlio/mjml/assets/94910935/b4aeb628-e2c6-4d99-8d6c-6691727c429d)

**Comment by iRyusa** [comment]
Reset line height to 1 it should work fine thenOn 13 Jan 2024, at 13:54, koutatmed ***@***.***> wrote:﻿
Hi
When I send an email with a text font size of 20px, I receive the email with truncated text on Outlook desktop. However, on Outlook's official website, it works fine. I have attached the screenshots of the bug for reference. thanks
Captu2e.PNG (view on web)
Capture.PNG (view on web)

**Comment by koutatmed** [comment]
> Reset line height to 1 it should work fine thenOn 13 Jan 2024, at 13:54, koutatmed ***@***.***> wrote:﻿ Hi When I send an email with a text font size of 20px, I receive the email with truncated text on Outlook desktop. However, on Outlook's official website, it works fine. I have attached the screenshots of the bug for reference. thanks Captu2e.PNG (view on web) Capture.PNG (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

how  and where ?

**Comment by iRyusa** [comment]
You can reset it with mj-all or just apply it on mj-text it should be enough
