### ISSUE TITLE
MJML Upgrade broke .NET href Url.Page() builder link.

### ISSUE THREAD

**Issue by webzest** [mjmlio/mjml#2808]
**Describe the bug**
In version 1.24, I was able to use a button to send the user the Email confirmation code with all related returned URL variables.  Upgrading to a newer version, starting with 2.0 broke the URL and eliminates the ability to sent the Email Confirmation link.

**To Reproduce**
1. Create a file with this MJML code: 
```
 var callbackUrl = Url.Page("/Account/ConfirmEmail", pageHandler: null, values: new { area = "Identity", userId = userNew.Id, code = code, returnUrl = returnUrl }, protocol: Request.Scheme);

string prehtml = $@"
                                    <mj-button background-color='#D04139' border-radius='3px' font-size='18px' font-weight='normal'
                                        inner-padding='10px 25px' padding-bottom='30px' padding='10px 25px'><a
                                            href='{HtmlEncoder.Default.Encode(callbackUrl)}'
                                            style='color:#FFFFFF; text-decoration:none;'>Click to Verify</a>
                                    </mj-button>
";
```
2. Render it to HTML by doing:
```
                            var mjmlRenderer = new MjmlRenderer();
                            var options = new MjmlOptions
                            {
                                Beautify = false
                            };
                            var xml = mjmlRenderer.FixXML(prehtml, options);
                            var (RenderedgBody, error) = mjmlRenderer.Render(xml, options);
```
3. Inspect the Rendered HTML by debug mode : mjmlRenderer 

On version 1.24, the URL is available to send as an Email.  In any other version greater than 1.24, the URL is not present, in fact, there is no HTML to review at all.

**MJML environment (please complete the following information):**
 - OS: [e.g. Windows 11]
 - MJML Version [e.g. 1.24 && versions 2.0 - 3.5]
 - MJML tool used MJML App]  && copy mjml code to .NET Core app.

At this point, it does not matter what Email client is used, for the HTML is not available to generate the link or a button.

**Comment by iRyusa** [comment]
I don't think you've posted on the right repository as we're not
maintaining any .net port here.
