### ISSUE TITLE
MJML not working in Cloudflare Worker

### ISSUE THREAD

**Issue by pauldemarco** [mjmlio/mjml#2812]
**Is your feature request related to a problem? Please describe.**
I am unable to use MJML on the edge in a Cloudflare Worker.

**Describe the solution you'd like**
The library to work on Cloudflare Worker.

**Describe alternatives you've considered**
I have tried mjml-browser but there seems to be a dependency on `window`, as I get `window is not defined` errors.

**Comment by iRyusa** [comment]
Any error to share on the main mjml package instead ?

**Comment by pauldemarco** [comment]
It's just typical error messages that you see when trying to include a nodejs library on Cloudflare Worker. Lot's of missing things:
```
X [ERROR] Could not resolve "path"

    node_modules/mjml-core/lib/index.js:100:43:
      100 │ var _path = _interopRequireDefault(require("path"));
          ╵                                            ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "path"

    node_modules/mjml-core/lib/helpers/mjmlconfig.js:14:43:
      14 │ var _path = _interopRequireDefault(require("path"));
         ╵                                            ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "fs"

    node_modules/mjml-core/lib/helpers/mjmlconfig.js:16:41:
      16 │ var _fs = _interopRequireDefault(require("fs"));
         ╵                                          ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "fs"

    node_modules/uglify-js/tools/node.js:1:17:
      1 │ var fs = require("fs");
        ╵                  ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "path"

    node_modules/mjml-parser-xml/lib/index.js:24:43:
      24 │ var _path = _interopRequireDefault(require("path"));
         ╵                                            ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

X [ERROR] Could not resolve "fs"
```

**Comment by iRyusa** [comment]
Can you check
https://developers.cloudflare.com/workers/configuration/compatibility-dates/#nodejs-compatibility-flag
maybe ?

**Comment by pauldemarco** [comment]
This is not working for me. Perhaps it's because the internal imports need to be pointing to the prefixed libs?
https://developers.cloudflare.com/workers/runtime-apis/nodejs/

**Comment by pauldemarco** [comment]
Here is some relevant discussion from Cloudflare Worker thread:
<img width="902" alt="image" src="https://github.com/mjmlio/mjml/assets/16725750/64c25563-a726-4cbe-9911-7a14ebbaa449">

**Comment by pauldemarco** [comment]
<img width="396" alt="image" src="https://github.com/mjmlio/mjml/assets/16725750/78392c32-6647-4b19-89ee-0493cea5e2e3">

Any ideas what this modification might be ?

**Comment by iRyusa** [comment]
I guess as it targets a browser webpack "inject" window even if it's not
used at all.

MJML really need an overhaul (removing babel and webpack, and rely on
either bun or w/e to build) :(

**Comment by pauldemarco** [comment]
I'm a bit new to the web space, is there any quick fix to remove this dependency?

**Comment by iRyusa** [comment]
Not really from our side just keep the polyfill and you'll be fine
