### ISSUE TITLE
Upgrade js-beautifier dependency

### ISSUE THREAD

**Issue by FedoraTipper** [mjmlio/mjml#2816]
There are currently a few criticial vulnerabilities picked up in yarn's dependency audit, some of which are pointing to `js-beautifier` and `juice` in each mjml component's package.

An upgrade to each package.json to bump up the required version of `js-beautifier` should resolve of a set of them. If this approach is ok, I can stage a PR with these changes. On the `juice` vulnerability, this will require further upstream package updates before being resolved in mjml (which looks like a nightmare).

**Screenshots**
![image](https://github.com/mjmlio/mjml/assets/19745176/32455a84-19b3-44a6-b0e8-5bed11bf0c70)

![image](https://github.com/mjmlio/mjml/assets/19745176/6f565a1d-06c9-473d-8b02-6ebec0e6dbc1)

**Comment by iRyusa** [comment]
Should be good in 4.15.0 I've updated most of non dev-dep
