### ISSUE TITLE
Align images without skretcking images

### ISSUE THREAD

**Issue by multivoltage** [mjmlio/mjml#2817]
**Describe the bug**
Cannot put N images in same line without skretch

**To Reproduce**
I triesdbefore a solution to nested columns but without succes.
Then I tried
```
<mj-section css-class="footer">
  <mj-column width="50%" vertical-align="middle">
    <mj-image
      src="https://placehold.co/400"
      alt="logo company"
      align="center"
      width="117px"
    />
  </mj-column>
  <mj-column width="32px" vertical-align="middle" css-class="ciccio">
    <mj-image
      src="https://placehold.co/400"
      alt="logo company"
      align="center"
      width="32px"
      height="32px"
    />
  </mj-column>
  <mj-column width="32px" vertical-align="middle" css-class="ciccio">
    <mj-image
      src="https://placehold.co/400"
      alt="logo company"
      align="center"
      width="32px"
      height="32px"
    />
  </mj-column>
</mj-section>
```

**Expected behavior**
from 2nd to last column images render 30px instead 0px

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version: Latest
 - MJML tool used: Node js API

**Screenshots**
<img width="659" alt="Screenshot 2024-01-24 alle 10 47 28" src="https://github.com/mjmlio/mjml/assets/14030341/a83fe95c-ecaf-4b9b-9f92-d55a27c838b9">

**Comment by iRyusa** [comment]
Reset padding to `0` on mj-image and you'll be fine.
