### ISSUE TITLE
Unable to use watch option

### ISSUE THREAD

**Issue by Russellmd** [mjmlio/mjml#2821]
Using watch option generate an error. e.g. for my package.json script

`mjml -w templates/emails/*.mjml -o templates/emails/output/`

I see the error:

`/home/node/app/node_modules/mjml-cli/lib/commands/watchFiles.js:94
    const matchInputOption = input.reduce((found, file) => found || (0, _glob.glob)(_path.default.resolve(file)).minimatch.match(filePath), false);`

`TypeError: Cannot read properties of undefined (reading 'match')
    at /home/node/app/node_modules/mjml-cli/lib/commands/watchFiles.js:94:123
    at Array.reduce (<anonymous>)
    at FSWatcher.<anonymous> (/home/node/app/node_modules/mjml-cli/lib/commands/watchFiles.js:94:36)
    at FSWatcher.emit (node:events:519:28)
    at FSWatcher.emitWithAll (/home/node/app/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/home/node/app/node_modules/chokidar/index.js:632:8)
    at NodeFsHandler._handleFile (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (/home/node/app/node_modules/chokidar/lib/nodefs-handler.js:637:21)
    at async /home/node/app/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)`

 - MJML Version 4.15.2

It works without errors with a previous version, e.g. 4.14.1

**Comment by iRyusa** [comment]
Can you try to remove completly node modules an reinstall 4.15.2 it might
be because of the glob dependency update

**Comment by Russellmd** [comment]
Already tried, without success.

**Comment by iRyusa** [comment]
Any chance you have a lockfile when you've reinstalled ?

**Comment by Taras-R** [comment]
Same issue. Installed for the first time mjml from npm. 
Latest version used - 4.15.2
Node v.18.12.1
Npm v.8.19.2

`mjml --watch src/**/*.mjml -o test` - `TypeError: Cannot read properties of undefined (reading 'match')`

**Comment by iRyusa** [comment]
4.15.3 should fix this can you all test it ?

**Comment by Taras-R** [comment]
@iRyusa updated mjml version to 4.15.3 - it works now, thank you for such fast feedback.

**Comment by Russellmd** [comment]
> 4.15.3 should fix this can you all test it ?

hi @iRyusa , I can confirm that this specific issue is solved, but now I have another one with included files. I will report it in a separate ticket.

**Comment by iRyusa** [comment]
Ok, if you can provide a repo to reproduce that would be nice debugging the
cli is a bit time consuming and painful
