### ISSUE TITLE
SNYK-JS-INFLIGHT-6095116

### ISSUE THREAD

**Issue by dan753722** [mjmlio/mjml#2826]
Dear MJML maintainers,

https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116

[js-beautify@1.6.14](https://github.com/mjmlio/mjml/blob/1c2f45978bebd8a7e707538f045b3863b0e66384/packages/mjml-cli/package.json#L32) in mjml-cli uses glob@7. Although you've updated glob to v10, our Snyk scanner still detects it as vulnerable.

Could we please bump js-beautify to 1.14.11?

Thank you!

**Comment by iRyusa** [comment]
I'll update it next week

**Comment by boxexchanger** [comment]
+1

**Comment by boxexchanger** [comment]
@iRyusa Hi any updates about it?

**Comment by iRyusa** [comment]
Wanted to push a new version for this, but this should be fixed in 5.x branch for now as js-beautify is entirely removed from the project.
