### ISSUE TITLE
mj social with automatic mode vertical and horizontal

### ISSUE THREAD

**Issue by ilhamdoanggg** [mjmlio/mjml#2829]
i have an issues about vertical and horizontal when open in mobile view 
here the example 

https://mjml.io/try-it-live/pI-AcXW5Yu

please help me

**Comment by iRyusa** [comment]
Can you add more info about your issue please ?

**Comment by ilhamdoanggg** [comment]
when open email in mobile device expected like this
<img width="467" alt="image" src="https://github.com/mjmlio/mjml/assets/9218660/0f01d1dc-5e01-4506-b875-ea87bdc1efe6">


and when open in desktop view expected this
<img width="491" alt="image" src="https://github.com/mjmlio/mjml/assets/9218660/802c4ded-71a3-4d3a-8a79-f9e40231b8f8">

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/avQi-mDW-6 Something like this should work. 
If you want the first social to behave as expected split it into 2 columns and use mj-text for img + text and you should be fine
