### ISSUE TITLE
Support for custom title tags?

### ISSUE THREAD

**Issue by valstu** [mjmlio/mjml#283]
Apparently Android 4.4 is using `<title></title>` tags for push notifications. Also some clients like Outlook might allow you to view email in a browser for better rendering. In those cases title tag would be useful. At the moment I haven't figured out any way to add custom titles for templates.

**Comment by robsonsobral** [comment]
Can't it be part of [`head-attributes`](https://mjml.io/documentation/#mjml-head-attributes)?

```
   <mj-head>
     <mj-attributes>
       <mj-title>My title</mj-title>
     </mj-attributes>
   </mj-head>
```

Or of `mj-head`?

```
   <mj-head>
     <mj-title>My title</mj-title>
   </mj-head>
```

**Comment by iRyusa** [comment]
It will be add into `mj-head` as you mention see #307 ! :)

**Comment by iRyusa** [comment]
Hello `mj-title` is now in MJML 2.3
