### ISSUE TITLE
Can't get keepComments flag to work

### ISSUE THREAD

**Issue by jjbindr** [mjmlio/mjml#2839]
**Describe the bug**
I'm trying to retain comments in the output html and I can't get it to work

**To Reproduce**

I've tried:

mjml templates/admin-invite.mjml -s --config.keepComment=true

mjml templates/admin-invite.mjml -s --config.keepComment true

mjml templates/admin-invite.mjml -s --config.keepComment=1

Also tried putting the flag in .mjmlconfig:
{
  "keepComments": true
}

**Expected behavior**
retains all html comments 

**MJML environment (please complete the following information):**
macos
mjml-core: 4.15.3
mjml-cli: 4.15.3

**Comment by iRyusa** [comment]
Can you maybe share a snipper to reproduce because I don't see any issue on my end

**Comment by jjbindr** [comment]
Hi iRyusa, thanks for the response. 

Attached is the input .mjml and output .html files.

The command used to run is:
` npx mjml templates/admin-invite.mjml -o generated --config.keepComment=true`


[files.zip](https://github.com/mjmlio/mjml/files/14463278/files.zip)

**Comment by jjbindr** [comment]
Thanks for the response. my bad. looking at the documentation closer I see it is plural, not singular keepComments

**Comment by jjbindr** [comment]
The behavior is a little strange though.  It seems to be dependent on where the comments reside in the mjml code.  Not all are getting kept. See attached.

I placed 4 comments only 2 are getting kept.

[files.zip](https://github.com/mjmlio/mjml/files/14463379/files.zip)

Command:
`npx mjml templates/admin-invite.mjml -o generated --config.keepComments=true`

**Comment by iRyusa** [comment]
MJML to HTML wont be transpiled 1-to-1 ex here :
https://mjml.io/try-it-live/W6zfrfYKXg
That's why it behave like that. I know that's not super intuitive as HTML
document dont work like that, but given how MJML document are parsed,
there's no so much to do here
