### ISSUE TITLE
Outlook 2016 doesn't render full-width mj-section

### ISSUE THREAD

**Issue by gtroeno** [mjmlio/mjml#284]
## The MJML:

I've made a template, which has _roughly_ this structure:

```
<mjml>  
    <mj-body>
      <mj-container>

<!-- Header -->
            <mj-section background-color="#f0f0f0" full-width="full-width">
            <mj-column>
            <mj-image src="imgurl" />
            </mj-column>
            </mj-section>

<!-- Body content -->
            <mj-section background-color="#ffffff">
            <mj-column>
            <mj-text>
                <p>Text in paragraph.</p>
            </mj-text>
            <mj-text>
                <p>More text in another paragraph.</p>
            </mj-text>
            </mj-column>
            </mj-section>

<!-- Footer -->
            <mj-section background-color="#1d497d" full-width="full-width">
            <mj-column>
                <mj-text>
                    <p>Footer content</p>
                </mj-text>
            </mj-column>
            </mj-section>

      </mj-container>
  </mj-body>
</mjml>
```

The template contains 3 sections: header, body and footer. The <mj-section> tags of the header and footer contain the _full-with_ attribute and both have a specific background color.
## The problem:

After compiling and testing the full-width sections, I've found them rendering well in most of the mail clients (I was able to test in). Except for **Outlook 2016**, although not sure about the other Outlook versions.

Outlook 2016 renders the full-width sections within the container width, which defaults to 600px.
## Findings & suggestions:

After compiling the generated HTML of the header section starts out like this:

```
    <!--[if mso]>
    <table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;">
      <tr>
        <td>
          <![endif]-->
          <table cellpadding="0" cellspacing="0" style="background:#f0f0f0;width:100%;" border="0">
            <tbody>
              <tr>
                <td>
                  <div style="margin:0 auto;max-width:600px;">
                    <table cellpadding="0" cellspacing="0" style="font-size:0px;width:100%;" align="center" border="0">
                      <tbody>
                        <tr>
                          <td style="text-align:center;vertical-align:top;font-size:0px;padding:20px 0px;">
                            <!--[if mso]>
                            <table border="0" cellpadding="0" cellspacing="0">
                              <tr>
                                <td style="vertical-align:top;width:600px;">
                                  <![endif]-->
                                  <div aria-labelledby="mj-column-per-100" class="mj-column-per-100" style="vertical-align:top;display:inline-block;width:100%;">
                                    <table cellpadding="0" cellspacing="0" width="100%" border="0">
                                      <tbody>
                                        <tr>
                                          <td style="word-break:break-word;font-size:0px;padding:10px 25px;text-align:left;">
                                            <table cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px;" align="left" border="0">
                                              <tbody>
                                                <tr>
                                                  <td style="width:200px;">
                                                    <img alt="" height="auto" src="http://resources.easyads.eu/images/email/marktfeed/logo-marktfeed.png">
```

For demo purposes I stripped some attributes that aren't relevant. 

You can clearly see MJML renders a conditional _[if mso]_ where a _table_ is rendered with both a **width attribute** and an **inline-style** that sets a width of 600px.

If I now manually set this width attribute from '600' to '100%' and to the inline style as well, Outlook 2016 **does** render this section full-width.

So a suggestion would be to let MJML compile widths in _[if mso]_ conditionals, with a value of 100% - **Only** when the mjml-section contains the _full-with_ attribute!

However, my knowledge of MJML and what I've found out here is pretty limited, so I don't know if such a fix would mess up rendering in other Outlook versions or MS mail clients.

**Comment by iRyusa** [comment]
Hello @gtroeno !

Thanks for the issue and thanks for a deep feedback on it ! While reading the MSO conditionnal code I found out what's going on. 

Conditionnal Outlook comment generated from `mj-container` should be inside the table with the 100% width (today we have table 600px > table 100%, it should be table 100% > table 600px). 

But  this will be hard to do, we need to move down the conditionnal comment generated from `mj-container` inside `mj-section` 

I'll try to see what I can do with that

**Comment by gtroeno** [comment]
Hello iRyusa,

No problem, As you've all been doing great work by creating MJML, I'm grateful by helping a hand with this issue.

Ah I see, and what you're explaining makes sense. I've played around with the core, just to workaround the problem - which temporarily works, see further below - and I understand why it's hard to encapsulate the conditional `if-mso` tag from the `mj-container` within the generated `mj-section` table. 

It's because in the base hierarchy `mj-container` is in fact a parent element of an `mj-section` correct? And in a 'full-width' `mj-section` situation, we would like to influence the container within an `mj-section` element, as if it were its child. Which is not the way the MJML-compiler 'looks' at the template when compiling.

For now, I didn't manage to find a solution for it myself, other than in the file mjml/node_modules/mjml-container/lib/index.js to disable (comment out) the lines which replace the classes:

- `.mj-container-outlook-open`
- `.mj-container-outlook-line`
- `.mj-container-outlook-close`

..and then to replace those classes with nothing / empty string. However, that's not THE solution for this issue of course.

Thanks for your feedback and I'll keep following!

**Comment by iRyusa** [comment]
You're 100% correct ! :) That's why I believe that `mj-container` will now stop generate any outlook related conditionnal tag and leave it to the section

**Comment by iRyusa** [comment]
Hi there ! 

It's now ok in MJML4, feel free to test it 👍

**Comment by gtroeno** [comment]
Hi iRyusa, that’s great news and I will definitely test it. Many thanks!
