### ISSUE TITLE
Image width in outlook is overflowing

### ISSUE THREAD

**Issue by BraianPita** [mjmlio/mjml#2840]
**Describe the bug**
Whenever I try to make a new email using an image that is wider than 600px, it overflows and shows on its original size on outlook only. This makes in hard to look at the image unless you open in with a browser.

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>` and include an mj-image element exactly like they do in the documentation (nested inside a mj-section > mj-column > mj-image
2. I have tried with no width, with width="600px", width="100%", height="auto", without height="auto" and nothing fixes it
3. Send the HTML to an email address and view it on outlook.
4. See image sized bigger than the rest of the viewport.

**Expected behavior**
The image should be sized down to fit inside the container column, which for some reason is not happening.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.15.3
 - MJML tool used: MJML App, and npm package does not work either.

**Email sending environment(for rendering issues)**:
 - Odoo Email Marketing  Module

**Affected email clients (for rendering issues):**
 - Email Client: Outlook
 - OS: Windows

**Screenshots**
<img width="507" alt="image" src="https://github.com/mjmlio/mjml/assets/54162188/995f2a37-93ea-4409-aa02-4f43916a05bb">

**Additional context**
I am using the newsletter template as a base (from the MJML app templates).

**Comment by iRyusa** [comment]
Can you try to provide the MJML and test with putsmail.com at least

**Comment by iRyusa** [comment]
Closing for now, feel free to reopen with more details
