### ISSUE TITLE
Issues with rendering in outlook

### ISSUE THREAD

**Issue by kyrillosezzat88** [mjmlio/mjml#2842]
**Describe the bug**
Hi There, we are facing a rendering issue on Outlook, do you know what is the problem? 
This is the code of the part that has an issue :
https://mjml.io/try-it-live/d5Z0tNGNSH

**Screenshots**
1- screenshot from Outlook
![outlook](https://github.com/mjmlio/mjml/assets/54558731/9e40bcbe-0fa8-4249-933a-fe7998e91555)
2- it should be render like this 
![2024-03-06_10-22](https://github.com/mjmlio/mjml/assets/54558731/7864eb06-cdb6-44be-9c16-45146f35433c)

Best Regards

**Comment by iRyusa** [comment]
Hi,

<img width="654" alt="Screenshot 2024-03-06 at 16 30 06" src="https://github.com/mjmlio/mjml/assets/570317/770998cc-2744-4ab9-b6fd-a8855d7d736b">

You should start by looking of errors returned by MJML linter. Multiple elements are not supposed to be used like that so your MJML document is invalid. Even if browser can handle the HTML output from this, it doesn't mean email client will display it properly.

Keep in mind you can't nest column / section like that and a section can't contain more than 100% of content.
