### ISSUE TITLE
"try it live"-Function now not working any more

### ISSUE THREAD

**Issue by kiliandr** [mjmlio/mjml#2844]
We used the "try it live"-function on the website for years, because it was the only tool that worked for us in our company.

No i saw  that there is no support for system shortcuts like strg+a (to select all) in the new version and therefore the tool is now not usable any more. This is very sad because the other MJML-Tools dont work either.

Please restore the system shortcuts in the browser version for select all, copy, paste etc.
And please let users choose which mjml version they want to use!

Edit: I also tried the windows app now (also the VSCodium Plugin together with the NPM mjml which worked even if it definitely was no fun at all bacause i had to switch between VSCodium, Console and Browser to get the effects of "try it live" before).

The scrollbar in the editor of the Windows App gets immediately hidden by the vertical "split bar" as soon as i reach it with my mouse pointer. so i cannot scroll with the mouse pointer pricisely to a position in my (long) code. Please make at least one of your projects work again. And please tell us, if you plan to change everything so that we can find alternatives early!

**Comment by iRyusa** [comment]
Every shortcut works just fine for me, it hasn't been updated for a while now and not really suited to be used as a "tool" but more as a demo/sandbox.

VSCode plugin should suit your need as you can just live preview any change https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml 

Parcel.io also does support MJML out of the box and should suit your need too.

> Please make at least one of your projects work again.
What a great mentality for open source 😄
