### ISSUE TITLE
New Twitter X logo not being rendered with <mj-social-element name="x" href="#">

### ISSUE THREAD

**Issue by mfreilly29** [mjmlio/mjml#2846]
**Describe the bug**
When I look at the documentation [Try it Live page](https://mjml.io/try-it-live/components/social) for adding social icons does not render the new Twitter X logo.
 <mj-social-element name="x" href="https://mjml.io/"> X</mj-social-element>
![image](https://github.com/mjmlio/mjml/assets/89410586/7d320d25-2514-4c32-a47a-70c6bf406abb)

When I add this code to my mjml file and process it, it only removed the src attribute.
-- `<img height="25" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter.png" style="border-radius:50px;display:block;" width="35" />`

++ `<img height="25" style="border-radius:50px;display:block;" width="35" />`

**To Reproduce**

1. Create a file with this MJML code: `<mj-social-element border-radius="50px" background-color="#006C80" name="twitter-x" href="https://twitter.com/boxcast">
          </mj-social-element>`
2. Render it to HTML by doing 'npm run email:process'
3. check HTML output for twitter src

**Expected behavior**
The expected behavior is that the rendered HTML includes the new Twitter X logo for the src. https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter-x.png
`<img height="25" src="https://www.mailjet.com/images/theme/v1/icons/ico-social/twitter-x.png" style="border-radius:50px;display:block;" width="35" />`

**MJML environment (please complete the following information):**
 - OS: macOS
 - MJML Version 4.10.3
 - npm 6.14.13

**Comment by iRyusa** [comment]
`x` icon was added in 4.15, try it live use 4.9 and you seem to use 4.10 so that's normal here.

Just upgrade MJML to 4.15.x and you should be fine
