### ISSUE TITLE
Support DATA variable in href or button

### ISSUE THREAD

**Issue by mehuljariwala** [mjmlio/mjml#2854]
**Describe the bug**
Hello Team, 

I am using mjml template for my email integration in loop. i have one edge case where i have to pass the data variable inside href in a button or a tag but its seems not working i have a tried a lot can you please help me with example how to solve this ? 

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2.  <a
              class="link-a"
              color="white"
              font-family="Inter, Arial"
              target="_blank"
              href="{DATA_VARIABLE:resetUrl}"
              >Reset your password
            </a>
            
            OR 
            
            <mj-button
            font-weight="bold"
            width="250px"
            align="center"
            border-radius="60px"
            background-color="#FE8029"
            color="white"
            font-family="Inter, Arial"
          >
            <a
              class="link-a"
              color="white"
              font-family="Inter, Arial"
              target="_blank"
              href="{DATA_VARIABLE:resetUrl}"
              >Reset your password
            </a>
          </mj-button>
3. Above example both of them not working. 

**Expected behavior**
It should expect the data variable inside tag 

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Screenshots**

**Additional context**

**Comment by iRyusa** [comment]
Hi,
I don't think MJML has something to do with your problem as MJML doesn't have any templating support.
