### ISSUE TITLE
[Feature Request] Allow `<mj-raw>` anywhere

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#286]
Would like to have `<mj-raw>` allowed anywhere.

For example

```
      </mj-container>
        <mj-raw><!-- comment--></mj-raw>
    </mj-body>
</mjml>

```

My aim is to have HTML comment here

```
     <!-- comment-->
   </body>
</html>
```

**Comment by iRyusa** [comment]
Hi !

Due to how react is working we can't implement this yet. However... We might provide a way to change the default `html` container from `.mjmlconfig` in a near futur so you'll be able to add it easily

**Comment by iRyusa** [comment]
This is now OK in MJML4 since mj-container doesn't exists anymore

**Comment by Aylay** [comment]
Hi,

I see that mj-container doesn't exist anymore.
Is there a documentation for MJML 4 please like mjml.io/documentation ?

Thanks

**Comment by ngarnier** [comment]
As said by @iRyusa, it's now ok and as the first beta for MJML 4 is here, I'm closing.
