### ISSUE TITLE
MJML Table Data not rendered in newer Outlook versions using WebView2 (Desktop and Android)

### ISSUE THREAD

**Issue by FixFlare** [mjmlio/mjml#2869]
There seems to be two versions of Outlook in use by Microsoft at the moment. One dependent on the WebView2 which I think is shared with their Android app.

When using this modern version my e-mail template that was working before now no longer renders the table data.

Here is an example that demonstrates the problem.

```mjml
<mjml>
  <mj-head>
    <mj-title>test</mj-title>
    <mj-preview>test</mj-preview>
    <mj-attributes>
      <mj-all font-family="Calibri, Arial"></mj-all>
      <mj-table></mj-table>
      <mj-text font-weight="400" font-size="16px" color="#000000" line-height="24px"></mj-text>
    </mj-attributes>
   
  </mj-head>
  <mj-body background-color="#E7E7E7" width="700px">
      <mj-section  background-color="#000000" padding-bottom="15px" border-radius="10px" >
      <mj-column width="100%">
      </mj-column>
    </mj-section>
    <mj-section padding-top="15px"></mj-section>
     <mj-section background-color="#000000">
      <mj-column width="100%">
      </mj-column>
    </mj-section>
    <mj-wrapper padding-top="0" padding-bottom="0" css-class="body-section">
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px">
        <mj-column width="100%">

  <mj-text>
    <h3>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum: <strong>3</strong>. Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum, lorem ipsum.
      Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum.</h3>
  </mj-text>
<mj-text><p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet dfsfdsfds: <strong>bleggity.blah@dsafsd.com</strong></p>
                                        <p>Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet dfsfdsfds <a href="https://bleggityblah/notes/6y276nghvuxn9e3ve4uc3py/">lorem ipsum</a>. Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum <a href="mailto:bleggity.blah@dfsdsffd.com?subject=RE: lorem ipsum - adfdfsfds@fdsfd.com">lorem ipsum</a>.</p></mj-text>
<mj-text color="#212b35" font-weight="bold" font-size="20px" align="center">lorem ipsum</mj-text>
<mj-table> <table> <colgroup><col/><col/><col/><col/></colgroup> <tr><th>loremipsum</th><th>loremipsum</th><th>loremipsum</th><th>E-loremipsum</th></tr> <tr><td>blehy, blah</td><td>blahp</td><td>blahg</td><td>bloggy.blah@blah.com</td></tr></table> </mj-table>

        </mj-column>
      </mj-section>
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px" padding-top="0">
      </mj-section>
      <mj-section background-color="#ffffff" padding-left="15px" padding-right="15px" padding-top="0">
        <mj-column width="100%">
          <mj-divider border-color="#DFE3E8" border-width="1px" />
        </mj-column>
      </mj-section>
      <mj-section background-color="#ffffff" padding="0 15px 0 15px">
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

When looking at the rendered html it looks like the table gets created with a 0 dimension.

It seems to work fine with the mjml "try it live" feature: [https://mjml.io/try-it-live/LKFi1sfr2V](https://mjml.io/try-it-live/LKFi1sfr2V) but if you then take the resulting HTML code and send it to Outlook you will see the problem.

Interestingly enough, it does not happen with the older Outlook Desktop version (the one without webview)

Outlook Version Desktop:
Microsoft Outlook Version 1.2024.529.200 (Production).
Client Version is 20240524003.09 .
WebView2 Version is 125.0.2535.79

Android Outlook Version:
4.2422.0 

Looks correct in old Desktop Outlook:
![image](https://github.com/SebastianStehle/mjml-net/assets/1587819/5bb3403d-3573-4fa7-91bf-13afa14f3aef)

Table data is missing in Android or Newer Outlook Version based on WebView
![image](https://github.com/SebastianStehle/mjml-net/assets/1587819/1aa24060-0cae-49f9-813e-322cc07bb409)

**Comment by iRyusa** [comment]
I don't have any android phone to test this 😬 

Can you try to send with putsmail to be sure there's nothing altering the HTML first https://putsmail.com/

Then  can you reproduce with a minimal version like https://mjml.io/try-it-live/rwHVx8YeZk

In your MJML you'ved added a `table` inside `mj-table` it would generate a double table in the HTML can you try to remove it too ?

**Comment by iRyusa** [comment]
Hi, any news about that ?

**Comment by FixFlare** [comment]
@iRyusa - Sorry, yesterday was a holiday.

The minimal example doesn't demonstrate the problem unfortunately. The one I provided I already consider pretty minimal - cut down from what was like 3-4 pages.

To be clear, this has been working fine for years - I do not believe there has been a change at MJML but rather at Microsoft where they are starting to rely on html rendering from webview2 across all their newer products/versions.

If you don't have Android to test you can easily see the problem by using edge.

Windows Microsoft Edge Version 126.0.2592.56


Steps to reproduce:

1. In Microsoft Edge Navigate to [https://mjml.io/try-it-live/LKFi1sfr2V](https://mjml.io/try-it-live/LKFi1sfr2V) - Note that the table is **not visible** in the preview view on the right
2. Cut out all the MJML code, preview view goes away.
3. Paste MJML text back, text is properly rendered and table is shown in the preview view on the right



You can also take the rendered HTML from the MJML try-it-live, paste it in a .html file, and open it in Microsoft Edge to see the problem. The table is not shown.




As far as a table within a table, is that not considered valid? Again, it has been working for years like that. It's only with these newer Microsoft versions that we're experiencing this problem.

**Comment by rwatts-bw** [comment]
I'm experiencing the same issue with my clients on Windows 11 using the "New Outlook".

As recent as last Friday, my MJML templates were working as expected. Now they are seeing two column layouts as stacked, as if on desktop they are rendering the mobile version of the email. Emails they've approved of in the past, now are rendering this way as well out of nowhere.

I've sent the email from our email software as well as a nodemailer I maintain, making sure nothings altering the HTML.

I use Litmus for testing and can't replicate this as it seems to be an issue that started this week with some update from Microsoft.

**Comment by iRyusa** [comment]
I'm not sure about your issue @FixFlare because the table is not shown on chrome for me too. It only show when you remove the invalid `table` child inside your `mj-table`

@rwatts-bw might be another issue if you have the outlook version we can take a look.

**Comment by rwatts-bw** [comment]
@iRyusa 
![Screenshot 2024-06-21 115230](https://github.com/mjmlio/mjml/assets/127418874/ba552f45-caf4-44bc-8ccb-c097ddcb0def)

Thanks!

**Comment by iRyusa** [comment]
Yeah on the new outlook for windows I can reproduce only if you put a table
as a child of mj-table. Removing it make the mail work just fine.

**Comment by rwatts-bw** [comment]
I tried with a barebones two column MJML layout and the two columns are still stacking on the new outlook for windows.
`<mjml>

  <mj-head>

    <mj-attributes>
      <mj-text align="center" color="#555" />
      <mj-section background-color="#fff" />
    </mj-attributes>

  </mj-head>

  <mj-body background-color="#eee">
    <mj-section>

      <mj-column>
        <mj-text>
          First column
        </mj-text>
      </mj-column>

      <mj-column>
        <mj-text>
          Second column
        </mj-text>
      </mj-column>

    </mj-section>
  </mj-body>
</mjml>`

which converts to

`<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
  <head>
    <title>
      
    </title>
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
      #outlook a { padding:0; }
      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }
      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }
      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }
      p { display:block;margin:13px 0; }
    </style>
    
    
    
      
        <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet" type="text/css">
        <style type="text/css">
          @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);
        </style>
      

    
    
    <style type="text/css">
      @media only screen and (min-width:480px) {
        .mj-column-per-50 { width:50% !important; max-width: 50%; }
      }
    </style>
    <style media="screen and (min-width:480px)">
      .moz-text-html .mj-column-per-50 { width:50% !important; max-width: 50%; }
    </style>
    
  
    <style type="text/css">
    
    
    </style>
    <style type="text/css">
    
    </style>
    
  </head>
  <body style="word-spacing:normal;background-color:#eeeeee;">
    
    
      <div
         style="background-color:#eeeeee;"
      >
        
      
      
    
      
      <div  style="background:#ffffff;background-color:#ffffff;margin:0px auto;max-width:600px;">
        
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff;background-color:#ffffff;width:100%;"
        >
          <tbody>
            <tr>
              <td
                 style="direction:ltr;font-size:0px;padding:20px 0;text-align:center;"
              >
                
            
      <div
         class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:center;color:#555555;"
      >First column</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          
            
      <div
         class="mj-column-per-50 mj-outlook-group-fix" style="font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;"
      >
        
      <table
         border="0" cellpadding="0" cellspacing="0" role="presentation" style="vertical-align:top;" width="100%"
      >
        <tbody>
          
              <tr>
                <td
                   align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;"
                >
                  
      <div
         style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:center;color:#555555;"
      >Second column</div>
    
                </td>
              </tr>
            
        </tbody>
      </table>
    
      </div>
    
          
              </td>
            </tr>
          </tbody>
        </table>
        
      </div>
    
      
      
    
    
      </div>
    
  </body>
</html>
  `

**Comment by iRyusa** [comment]
Yeah I meant for the original issue with the tables.
The mail displayed in mobile version seem to happen on the web version of
outlook. They might have disabled media queries yet again. Let's open a new
issue for that instead of mixing discussion please.

**Comment by FixFlare** [comment]
When I remove <table> it screws up the formatting of the e-mail for me in old outlook unfortunately. It does work for the new one but that doesn't help me since I have a mix of old/new outlook in my organization.

I've been using this for literally 2 years with the <table> within <mj-table> and it has worked perfectly.

Only since my users have started getting new versions of Outlook on both their desktops as well as their phones am I starting to see this issue crop up.

Here is <table> vs no <table> 

![image](https://github.com/mjmlio/mjml/assets/1587819/041af23a-203a-4a85-ba53-60d1e2063a96)


Users at my organization see this in the top right of their outlook:


![image](https://github.com/mjmlio/mjml/assets/1587819/7e8e2e74-b861-47cb-bba3-3332deb95ea7)


Users who do not have that toggled on use the old outlook and it continues to work fine.

People that have toggled that to "on" get this new version where the table is not displayed.

**Comment by iRyusa** [comment]
I mean putting table into a mj-table directly without no child is just non
valid HTML and it's not MJML fault that the client would misbehave for
that.
Even browsers would just do random stuff with that HTML produced.

On your screenshot the table appear randomly on the bottom left ? I'm
pretty convinced that it try to "correct" the html.
Email client rarely getting updated so yeah, this could still work on a
random engine that is X years old as it won't get updated.

As you said minimal table seems to work fine for you so try to remove the
colgroup at least on your email and the non necessary table to see at least
how it behave.

I don't have any access to your env to reproduce, so here I'm totally
trying to help you blindfolded.

**Comment by FixFlare** [comment]
Not sure I follow what you mean when you say "without no child"?

`<table>` is a child of `<mj-table>`

Nesting tables should be valid HTML, no? Am I misinterpreting the documentation here?

https://documentation.mjml.io/#mj-table

![image](https://github.com/mjmlio/mjml/assets/1587819/352c4b62-419f-4686-b8e7-76675e3a822e)
![image](https://github.com/mjmlio/mjml/assets/1587819/f341193f-4ac8-418e-b813-e9d10a1c0165)


In my last post, the screenshot was removing <table> and just leaving <mj-table> as you suggested which I thought screwed up the format in the old outlook. After reviewing, I may have been missing the `>` on `</mj-table>` when I did that last test - woops.

Now that I corrected that typo, it does seem to work in both the old outlook and new outlook if I remove the `<table>` within `<mj-table>`.


I still do not understand why that is invalid and why I've been happily using that for over 2 years in thousands of e-mails.

I guess the conclusion is Microsoft's webview2 html rendering is less tolerant of this or sanitizes it differently?

**Comment by iRyusa** [comment]
You can't nest a table directly in a table, that's not valid in HTML. You
can in a td but not in a table.

The doc only says that mj-table is a HTML table, you would never do
table>table in a standard HTML document right ?

**Comment by FixFlare** [comment]
No, but I guess I thought of it as benign or pointless rather than invalid - like an unnecessary extra `<div>` or `<span>`

I'm not manually including that though - it's an artifact of PowerShell's ConverTo-HTML function which I use heavily to send pretty tables with MJML which has worked just swell until Microsoft's recent updates.


e.g. 

```powershell
[string](Get-Process | Select-Object ProcessName, Id -First 5 | ConvertTo-Html -Fragment -PreContent '<mj-table>' -PostContent '</mj-table>')
```

but that ends up generating html with the extra `<table>` like so:

```html
<mj-table> <table> <colgroup> ...
```


I've now replaced that with this:

```powershell
[string](Get-Process | Select-Object ProcessName, Id -First 5 | ConvertTo-Html -Fragment) -replace '<table>','<mj-table>' -replace '</table>','</mj-table>'
```

which takes care of the extra <table> and seems to work as mentioned earlier.

I'll have to adjust my e-mails/scripts in a few places but at least I have a solution.

Thanks for the input and suggestions on getting that solved @iRyusa  - much appreciated.
