### ISSUE TITLE
how to add a helper container for an image so it can be centered between elements.

### ISSUE THREAD

**Issue by ITforFF** [mjmlio/mjml#2870]
I have html and css do this but can't figure out how to make mjml do it. Basically I want a grid of cards with the title, img, price and have the whole card be a link to the item. When using mj-raw i can get it to look right in a preview but gmail is completly messed up and outlook just doesnt show the right bg color for the helper that keeps the image center. I will include a screenshot and snippets to help.

This is the html/css to make what I wanted.
`
<mj-raw>
                        <style>
                            .grid-item {
                                background-color: #1b3346;
                                color: inherit;
                                width: 80%;
                                min-width: 120px;
                                height: 38em;
                                padding: 20px;
                                margin-left: 10px;
                                margin-right: 10px;
                                margin-bottom: 10px;
                                margin-top: 10px;
                                text-align: center;
                                border-radius: 10px;
                                box-shadow: rgba(0, 0, 0, 0.25) 0px 14px 28px, rgba(0, 0, 0, 0.22) 0px 10px 10px;
                                background-color: #1B3346;
                                background-image: url("data:image/svg+xml;charset=utf8,%3Csvg data-css-pro-pattern-index='53' data-css-pro-pattern-opacity='40' data-css-pro-pattern-size='10px' data-css-pro-pattern-back-color='%231B3346' data-css-pro-pattern-front-color='%237A7A7A' xmlns='http://www.w3.org/2000/svg' width='4' height='4' viewBox='0 0 4 4'%3E%3Cpath fill='%237A7A7A' fill-opacity='0.4' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'%3E%3C/path%3E%3C/svg%3E");
                                background-position: initial;
                                background-size: initial;
                                background-repeat: initial;
                                position: relative;
                            }
                            .item_name {
                                font-size: 1.3em;
                                height: 150px;
                                margin-top:0px;
                                margin-bottom: -40px;
                            }
                            .price  {
                                font-size: 2em;
                                font-weight: 700;
                                position: static;
                                bottom: 60px;
                                margin-top: 20px;
                            }
                            .value {
                                font-size: 2em;
                                font-weight: 600;
                                position: static;
                                bottom: 30px;
                                text-align: center;
                            }
                            .item_img {
                                height: 240px;
                                vertical-align: middle;
                                align-items: center;
                                white-space: nowrap;
                                background-color: #ffffff;
                                border-radius: 10px;
                            }
                            .helper {
                                display: inline-block;
                                height: 100%;
                                vertical-align: middle;
                            }
                            .item_img img {
                                max-width: 90%;
                                max-height: 80%;
                                border-radius: 10px;
                                padding-top: 30px;
                                margin-right: 5px;
                                align-items: center;
                            }
                            a{
                                color: #ffffff;
                                text-decoration: none;
                            }
                        </style>
                        <div class="grid-item">
                        <a href="https://www.familyfirearms.com/product/tru-tg8432bn-prism-xxxx-32-blk">
                            <div class="item_name">
                                <h2>MAC 1014 12G 18.5in</h2>
                            </div>
                            <div class="item_img">
                                <span class="helper"></span>
                                <img src="https://storage.googleapis.com/msgsndr/3sNS4oka3dqCzinkkmn2/media/66592430c6bcc8013eda9b16.png" alt="Sig Sauer P320 X Ten HGA">
                            </div>
                            <div class="price">Price</div>
                            <div class="value">$900</div>
                        </a>
                        </div>
                    </mj-raw>
`

Here is a picture of the result i want but cant figure out how to make such a thing happen with MJML.
![image](https://github.com/mjmlio/mjml/assets/170741639/8a9fd4eb-b714-4d52-b581-339892e1dd08)

The helper is needed to make a uniform background to then center the differently sized pictures in so it looks uniform and the spacing in the cards stays the same.

**Comment by iRyusa** [comment]
If you go raw then MJML won't really do anything for you.
You can use a 3 column layout with padding/inner-padding and inner
background color to do this in MJML
