### ISSUE TITLE
Outlook 2404 build 17531.20119 not rendering MJML template

### ISSUE THREAD

**Issue by akseltahir** [mjmlio/mjml#2872]
**Describe the bug**
The templates we have written in MJML end up as empty renders on Windows 11, Outlook 2404 build 17531.20119

**To Reproduce**
1. Create a file with any MJML code - I don't want to link our mjml for privacy reasons. I can provide a skeleton with removed sensitive data if necessary. We use a very basic template, nothing fancy
2. Convert it to HTML via the mjml desktop app for MacOS
3. Send the HTML to an email address via <Proprietary java spring service>. The Spring service does not in any way change the html of the email

**Expected behavior**
The email should render properly without any visual bugs, just as it does for virtually any other client apart from Windows 11, Outlook 2404 build 17531.20119

**MJML environment (please complete the following information):**
 - OS: tested on Windows 11
 - MJML Version 4.12.0
 - MJML tool used - MJML App 3.0.4

**Email sending environment(for rendering issues)**:
 - Platform used to send the email - Java Spring implementation

**Affected email clients (for rendering issues):**
 - Email Client Outlook 2404 build 17531.20119
 - OS: Windows 11
 - Browser n/a

**Screenshots**
<img width="1211" alt="Screenshot 2024-06-25 at 15 47 10" src="https://github.com/mjmlio/mjml/assets/58740653/3553aaea-d8c7-4269-b32e-63b8d550e730">

**Comment by iRyusa** [comment]
> The Spring service does not in any way change the html of the email
Can you check if the same html sent with https://putsmail.com/ does the same ?

**Comment by digicase** [comment]
I found the problem for me was Outlook web is stripping out the `<style>` elements from the `<head>` element. I had to duplicate the style elements within the `body` element. See this issue https://github.com/hteumeuleu/email-bugs/issues/141

**Comment by digicase** [comment]
@akseltahir I'm not able to get the Windows app to work. The Mac app Version 16.86.2 (24062313) does not have the same problems as Outlook web app.

**Comment by digicase** [comment]
It looks like your issue could be something else entirely though, but I thought I'd mention the issue as Outlook web seems to have some breaking changes.

**Comment by akseltahir** [comment]
@iRyusa we've tested on postdrop.io and putsmail, both with the same html.
Using Putsmail, the email rendered correctly.
Using postdrop.io, the bug persisted and the email rendered as a blank page. 

I can link the html with removed sensitive company info if necessary

**Comment by iRyusa** [comment]
If it works with putsmail then the HTML is altered in some way at some point we can't really do anything about it.

**Comment by akseltahir** [comment]
Hello, apologies for commenting on a closed issue. Not sure if here is more appropriate or opening a separate one.

Upon further testing with putsmail, we did in fact observe the bug persisting - the initial test wasn't done correctly.

I've traced down the bug to a conditional statement in the MJML generated code.

`    `

The above statement for some reason renders the email completely blank on the older, word-based renderer of Outlook 365. Removing the whole statement fixes the bug.

Moreover, the mj-outlook-group-fix class is only used in with elements which are already defined with an inline style width=100%:

`<div
  class="mj-column-per-100 mj-outlook-group-fix"
  style="
    font-size: 0;
    text-align: left;
    direction: ltr;
    display: inline-block;
    vertical-align: top;
    width: 100%;
  "
>`

So I'm pretty sure the conditional is useless, but also somehow causes the rendering bug. This is all from the generated MJML source, so it might be useful to check into it further.

I'm uploading the mjml and the generated html with obfuscated sensitive data if necessary for debugging:
[email-generated.html.txt](https://github.com/user-attachments/files/16065907/email-generated.html.txt)
[email-mjml.mjml.txt](https://github.com/user-attachments/files/16065908/email-mjml.mjml.txt)

**Comment by iRyusa** [comment]
Here's the screenshot on outlook 365 with the exact same MJML you've used from Email On Acid : 

![image](https://github.com/mjmlio/mjml/assets/570317/085486b6-abf1-4c77-b8eb-1dc245961aed)

I'm not able to reproduce your issue here. Even with your provided HTML I can't reproduce too.
There's a weird formatting applied to your HTML tho try to get the direct output from MJML instead.

**Comment by akseltahir** [comment]
Thanks for the tip. Looks like it was a formatting issue on our end.
