### ISSUE TITLE
MJML Templates not rendering as expected in New Outlook on Windows

### ISSUE THREAD

**Issue by rwatts-bw** [mjmlio/mjml#2873]
**Describe the bug**
When expecting a two column layout on New Outlook on PC. The columns are stacked. Through my testing, this version of Outlook on PC is not rendering the  conditional.

**To Reproduce**
After reports of email templates being stacked I tested this simple two column layout:

![image](https://github.com/mjmlio/mjml/assets/127418874/7d3f6e55-7f3f-485e-b6ce-40ce67ce1c0c)

I then tested these conditionals and only the third rendered, so this version of Outlook is rendering as not MSO similar to Outlook on Mac.

![image](https://github.com/mjmlio/mjml/assets/127418874/122446bc-197a-403f-9d8a-201c80e6080b)

**Expected behavior**
I know this is a recent discovery, but is there a fix in work for the MJML framework? Is there any way to target this version of Outlook I'm not thinking of?

**MJML environment (please complete the following information):**
MJML App

**Email sending environment(for rendering issues)**:
Nodemailer

**Affected email clients (for rendering issues):**
Version information:
![image](https://github.com/mjmlio/mjml/assets/127418874/db0d58f4-dabd-42cc-92d4-88650d93b52e)

**Comment by sven-bs** [comment]
I experience the same issue. If I inspect the rendered HTML in Outlook Web it seems they now add a `x_`  prefix before the classes which lets e.g. the "mj-column-per-50" (which is used for two-col layouts) break.

See screenshot:

<img width="394" alt="mjml_outlook_web_issue" src="https://github.com/mjmlio/mjml/assets/59481399/d6e97bc5-bcdd-4ee3-978e-112b8eccb607">

**Comment by digicase** [comment]
I found the problem for me was Outlook web is stripping out the `<style>` elements from the `<head>` element. I had to duplicate the style elements within the `body` element. See this issue https://github.com/hteumeuleu/email-bugs/issues/141

**Comment by iRyusa** [comment]
Yup seems like we'll have to do that too. If I can find some times, i'll see if I can hotfix both 4.x and 5.x branch thanks for the link @digicase

**Comment by rwatts-bw** [comment]
@digicase That worked for me, thanks!

**Comment by rwatts-bw** [comment]
@digicase That worked for me, thanks!
