### ISSUE TITLE
Outlook web client doesn't render columns

### ISSUE THREAD

**Issue by dpd73** [mjmlio/mjml#2876]
**Describe the bug**
Outlook web client doesn't render columns on Mac
Litmus.com shows the issue...
However, this appears to be an issue for Mac and not Windows outlook web client?!

**To Reproduce**
1. Create a single file, basic layout MJML (this has two simple columns)
2. Send it
3. Observe columns stacked, not side by side

**Expected behavior**
Columns appears side by side

**MJML environment (please complete the following information):**
 - OS: Mac
 - MJML Version 4.12.0
 - MJML App 3.0.4

**Email sending environment(for rendering issues)**:
 - From the App (via Mailjet, I guess)

**Affected email clients (for rendering issues):**
 - Email Client: Outlook.com
 - OS: Mac
 - Browser: Google Chrome

**Screenshots**
![Screenshot 2024-06-26 at 17 42 00](https://github.com/mjmlio/mjml/assets/6959562/8f9c205a-2a36-41a0-b171-5f2f50ce970a)

**Additional context**
This seems to be an intermittent outlook.com thing? Could well be nothing to do with MJML but a change at Microsoft? Putting this here in case any other unfortunate soul encounters the issue or someone else has further insight.

I did see intermittent expected rendering at litmus
![Screenshot 2024-06-26 at 16 46 15](https://github.com/mjmlio/mjml/assets/6959562/c8c03f2f-c0d6-4832-babf-ee06497993e2)

**Comment by dpd73** [comment]
Can someone confirm that this is likely due to lack of media query support in the web app?
https://mjml.io/compatibility/mj-column
(Seems odd that is sometimes gets honoured as per above last screen grab)

**Comment by dpd73** [comment]
Adding the <style> elements to the <body> fixes the issue, as suggested elsewhere.

**Comment by iRyusa** [comment]
Reopening for now as it's still the case

**Comment by iRyusa** [comment]
Closing again (🤡 sorry)

Seems like Microsoft reverted the change 👍 no need to add a fix to MJML for that then 🎉
