### ISSUE TITLE
Try it live does not allow pasting

### ISSUE THREAD

**Issue by rationalthinker1** [mjmlio/mjml#2880]
**Describe the bug**

**To Reproduce**
1. go to https://mjml.io/try-it-live
2. clear up everything and paste this:
```mjml
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>

        <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

        <mj-divider border-color="#F45E43"></mj-divider>

        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior**
it should paste 

**Affected email clients (for rendering issues):**
Google Chrome

**Comment by iRyusa** [comment]
Can't reproduce on my end, are you sure you don't have any extension
installed ?

**Comment by rationalthinker1** [comment]
I've tried in Chrome, and Edge and in incognito mode also. I'm in Windows 11

**Comment by iRyusa** [comment]
I'm not really able to reproduce on my windows machine and in a VM too. Most likely something on your end preventing this.
