### ISSUE TITLE
Replace old not maintained Laravel / PHP package

### ISSUE THREAD

**Issue by EvanSchleret** [mjmlio/mjml#2884]
**Is your feature request related to a problem? Please describe.**
I’m always frustrated when documentation references packages that are no longer maintained. The current package used in the documentation for PHP / Laravel is outdated and no longer maintained, which makes it difficult to use in modern projects.

**Describe the solution you'd like**
I’d like to suggest replacing the current package in the documentation with my package, lara-mjml, which I developed in my free time. [lara-mjml](https://github.com/EvanSchleret/lara-mjml) is simpler and leverages MJML to create responsive email templates efficiently.

**Describe alternatives you've considered**
I considered sticking with the current package or looking for other alternatives, but they either face the same issue of being outdated or are more complicated to use compared to lara-mjml.

**Additional context**
Here is the link to my package: [EvanSchleret/lara-mjml](https://github.com/EvanSchleret/lara-mjml).

Switching to lara-mjml will keep the documentation up-to-date and provide developers with a more straightforward and modern solution for email templating in Laravel projects.

**Comment by iRyusa** [comment]
Doc is open source too so you can list it in here
https://github.com/mjmlio/mjml/blob/master/doc/ports.md

**Comment by iRyusa** [comment]
Merged 👍
