### ISSUE TITLE
Mj-column borders w/ border-radius are not rendering correctly

### ISSUE THREAD

**Issue by jeissler** [mjmlio/mjml#2893]
**Describe the bug**
When setting borders on an mj-column the border radius is not being rendered correctly, it simply shows the borders w/ square corners instead

**To Reproduce**
This can be seen in the 'try it live' editor by adding a column w/ the below code 
```
<mj-column background-color="pink" border-left="2px solid magenta" border-radius="40px">...
```
renders 
<img width="339" alt="Screenshot 2024-08-21 at 10 52 10 AM" src="https://github.com/user-attachments/assets/48956a5b-0eaa-483d-8e39-3f1e1a337b2f">

**Expected behavior**
The border radius property should be being applied to both the background and borders

**Possible solution**
Set border-collapse on the preceding table to 'separate' instead of the default 'collapse' 
```
[class*=mj-column] > table {
    border-collapse: separate;
}
```

**Comment by iRyusa** [comment]
This is a "known" issue but this is used for compatibility issue. If you really need this just apply it as you did.
We won't really fix this as some desktop client misbehave with border-collapse set to separate.
