### ISSUE TITLE
Forwarded email does not retain columns

### ISSUE THREAD

**Issue by esamo** [mjmlio/mjml#2902]
**Describe the bug**
Forwarded email does not retain columns, they change to rows instead.

**To Reproduce**

1. Create a file with this MJML code:

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">1</mj-text>
      </mj-column>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">2</mj-text>
      </mj-column>
      <mj-column>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">3</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

3. Render it to HTML by using https://mjml.io/try-it-live
4. Send the HTML - columns are OK.
5. Forward the message - columns are no more, rows appear instead.

**Expected behavior**
Forwarded message should be consistent with the original and retain columns.

**MJML environment (please complete the following information):**
 - OS: Windows
 - MJML Version 4.9.3
 - MJML tool used https://mjml.io/try-it-live

**Email sending environment(for rendering issues)**:
 - Sending via Debian Apache2 Server with PHP
 - Forwarding via gmail.com

**Affected email clients (for rendering issues):**
 - Email Client gmail.com
 - OS: Windows
 - Browser Google Chrome

**Screenshots**
Original message:
![image](https://github.com/user-attachments/assets/bb757c8f-0c18-4721-9d21-5dce0619709d)

Forwarded message:
![image](https://github.com/user-attachments/assets/3cd9bbae-1e3c-45b9-ba09-6f3615911895)

**Comment by iRyusa** [comment]
Forwarding email alter the HTML, there's nothing we can do about this
