### ISSUE TITLE
Tiny white line below mj-image

### ISSUE THREAD

**Issue by karin-pacholkova** [mjmlio/mjml#2903]
### Discussed in https://github.com/mjmlio/mjml/discussions/2901

<div type='discussions-op-text'>

<sup>Originally posted by **karin-pacholkova** September 11, 2024</sup>
Hi there,
I have two mj-sections. In the first one the background-color is white, in the second one dark blue. In the first mj-section I only have a PNG image, which has a transparent part on the top, but the bottom is all dark blue. In the second mj-section I have the same dark blue color and mj-text. 

When I send myself a test email, then the Apple Mail app on the iPhone XS, or Gmail on Android 11.0 shows a tiny white line below the image. When I changed the background color of the first mj-section from white to dark blue, the white line disappeared. So I assume it's related to the background color of the first mj-section. But unfortunately I can't have the color of the first mj-section the same as the color of the second mj-section. I also tried setting the mj-column in first mj-section to vertical-align="bottom", but it didn't help. 

Here is the code - https://mjml.io/try-it-live/86fve3Elyj

![image](https://github.com/user-attachments/assets/0d03acb0-051f-4b75-85dd-72d51858eaab)

Thank you in advance.

Karin

**Comment by karin-pacholkova** [comment]
Hello,
would you be so kind and tell me what can I do with the code above? 
If I'm doing something wrong or is there some help, please?
Thank you very much in advance for any your idea, thought or help.
Karin

**Comment by iRyusa** [comment]
👋 I'm not sure about this but it might be the browser that have trouble to find a integer value for pixel. Meaning the white line is just a subpixel displayed. Try to set a fixed height to your image it should do the trick

**Comment by karin-pacholkova** [comment]
Sorry to write so late - it helped me. 👍
Thank you VERY MUCH!!! 🤗
