### ISSUE TITLE
npm audit throwing severe vulnerabilities for mjml 4.15.3

### ISSUE THREAD

**Issue by mwhit24** [mjmlio/mjml#2904]
**Describe the bug**
When using mjml 4.15.3, npm audit is throwing severe vulnerabilities for mjml-core.

**To Reproduce**
1. Run npm audit

**Expected behavior**
MJML wouldn't have severe vulnerabilities.

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.15.3
 - MJML tool used MJML NPM Package

**Email sending environment(for rendering issues)**:
 - Sendgrid

**Affected email clients (for rendering issues):**
 - Email Client All
 - OS: All
 - Browser All

**Screenshots**
N/A

**Additional context**
The alpha 5.0.0 works, but breaks all mjml functionality.

**Comment by iRyusa** [comment]
MJML 5 don't break anything it's just now promise based. There's already an open issue about this, stop opening new one please.
