### ISSUE TITLE
Documentation does not mention that mj-column wraps mj-raw differently from other components

### ISSUE THREAD

**Issue by stefanfisk** [mjmlio/mjml#2926]
**Describe the bug**

`<mj-column>` alters the HTML when rendering `<mj-raw>` compared to when rendering other child components. AFAICT this is not documented anywhere and I've lost at least a day of work to trying to figure out why my code broken before I figured it out. (I will admit that it took me WAY longer than it should have to took at the generated HTML 😿).

**To Reproduce**

1. Open https://mjml.io/try-it-live/nBDFlrAqTc
2. Watch the lower half of the template being white instead of red because of `my-table-1` breaking the HTML

**Expected behavior**

My initial expectation was that I should be able to copy another component's HTML markup and just use it inside of `<mj-raw>`.

**MJML environment (please complete the following information):**

https://mjml.io/try-it-live

**Email sending environment(for rendering issues)**:
N/A

**Affected email clients (for rendering issues):**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by iRyusa** [comment]
You can just contribute to the doc as it's just a compilation of `Readme` inside each package. https://github.com/mjmlio/mjml/blob/master/packages/mjml-raw/README.md

`mj-raw` is mostly used for templating stuff or when you know what to do. As said the parser won't touch it so it will be palced "as is".

It's hard to find a balance between a concise doc and covering "all" the pitfall you can encounter during your learning curve.

I'm closing but feel free to open a PR
