### ISSUE TITLE
<mj-section> background-url breaks padding-left in Outlook

### ISSUE THREAD

**Issue by stefanfisk** [mjmlio/mjml#2927]
**Describe the bug**

Combining `background-url` on `<mj-section>` with `padding-left` (either via shorthand or directly) on `<mj-section>` or `<mj-column>` renders without the left padding in Outlook. AFAICT after testing with testi.at and litmus.com this to happen in all Windows version from 2013 up to but not including Outlook for Windows.

**To Reproduce**

1. Open https://mjml.io/try-it-live/1TXyeEYF3O
2. Copy the HTML into whatever service you are using for testing
3. Preview it in an Outlook client on Windows newer than 2013
4. Observe that the left padding is missing

**Expected behavior**

I'd expect the left padding to be there even in Outlook.

**MJML environment (please complete the following information):**

- https://mjml.io/try-it-live/

**Email sending environment(for rendering issues)**:

testi.at and litmus.com.

**Affected email clients (for rendering issues):**

 - Outlook 2013 and newer
 - OS: Windows

**Screenshots**

<img width="652" alt="Screenshot 2024-12-12 at 16 11 50" src="https://github.com/user-attachments/assets/050534a0-0c6d-4d4c-9e95-8400b72b63d9" />

**Additional context**

I really really want Microsoft to kill Outlook with fire...

**Comment by stefanfisk** [comment]
I just did a quick test, and this also seems to happen if you use the `background-url` on `<mj-wrapper>`: https://mjml.io/try-it-live/GIEpinnT0C

**Comment by stefanfisk** [comment]
@iRyusa Could we at least add a note to the documentation? I've lost several hours debugging this issue.

**Comment by iRyusa** [comment]
Feel free to add it, but it will be hard to explain all the known issue for each attribute (there's a high chance it will be missed by user).
