### ISSUE TITLE
[Feature Request] Reverse-ordering of columns

### ISSUE THREAD

**Issue by zrb0529** [mjmlio/mjml#296]
Using a technique similar to what has been implemented here: http://responsiveemailpatterns.com/patterns/layout/source-order-shift.html

I suspect it will be difficult because of the way the entire table must be constructed. Might it be possible though to create a group:

```
<mj-section>
    <mj-column-group shift-direction="standard">
        <mj-column><mj-text /></mj-column>
        <mj-column><mj-text /></mj-column>
    </mj-column-group">

    <mj-column-group shift-direction="reverse">
        <mj-column><mj-text /></mj-column>
        <mj-column><mj-text /></mj-column>
    </mj-column-group">

</mj-section>
```

This would allow the compiler to know which set of HTML etc to use when creating the container table?

**Comment by iRyusa** [comment]
Hello ! 

We're now supporting in MJML 3 `direction="rtl"`on `mj-section`. It will reverse column order in a section when displayed in desktop mode.
