### ISSUE TITLE
How do i change 4 columns on desktop in 2 columns on mobile?

### ISSUE THREAD

**Issue by bkullmanns** [mjmlio/mjml#297]
Hi, i am with a problem in a email. Somebody can help me?
My email has 4 columns in a section. 
The elements are 4 social icons. I separated on 4 columns to let they side by side.
But, on mobile, they stay on vertical, in list.
How do i change that?
I want that divides on 2 blocks, not in a list. Or if i have 5 elements, i want to let 3 on a line and 2 on a second line.

Sorry for my bad english. Im from Brazillian and im learning english yet. haha

**Comment by ngarnier** [comment]
Bom dia Barbara! 

No worries, your english is perfectly understandable. This is not possible yet but will be really soon (probably this week) as we're working right now on a feature that will enable you to do this, have a look at https://github.com/mjmlio/mjml/pull/281 :-)

**Comment by ngarnier** [comment]
Hey @bkullmanns, as promised we released `mj-group` that enables you to do this! Here, you'd wrap your columns like this: 

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-group>
          <mj-column>
            <!-- content -->
          </mj-column>
          <mj-column>
            <!-- content -->
          </mj-column>
        </mj-group>
        <mj-group>
          <mj-column>
            <!-- content -->
          </mj-column>
          <mj-column>
            <!-- content -->
          </mj-column>
        </mj-group>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

You can check the documentation [here](https://mjml.io/documentation/#mjml-group). 

I'm closing the issue, let us know what you think or if you have any issue!
