### ISSUE TITLE
Issue with section with 2 columns and text left and right

### ISSUE THREAD

**Issue by nvassos** [mjmlio/mjml#300]
I have been trying to fix the text underneath the photo to be responsive and correct but I haven't have any success with it yet. Not sure if you have an input. 

[code.mjml.zip](https://github.com/mjmlio/mjml/files/309265/code.mjml.zip)

**Comment by iRyusa** [comment]
Hello @nvassos,

There's a lot of problem in your code right now : 
A section should only contain a

**Comment by iRyusa** [comment]
Hello @nvassos,

There's a lot of problems in your code right now : 
A section should only contain a `mj-group/column`, sometime your putting an `mj-text`, `mj-image` and even sometimes a `mj-section` in a `mj-section`

Can you try to fix it and test it back please ?

Thanks !

**Comment by nvassos** [comment]
so a section should always include a column and/or a group? 

Is this better? 
[code.txt](https://github.com/mjmlio/mjml/files/312169/code.txt)

**Comment by iRyusa** [comment]
This look good! Does it solve your issue ?

**Comment by nvassos** [comment]
It does not. I want the text underneath the picture to be more responsive and not stacking. Is that possible? I am attaching an iphone6s preview using Litmus. 

https://www.dropbox.com/s/qhs0rvlb4m94y9k/Screenshot%202016-06-13%2008.38.05.png?dl=0

**Comment by iRyusa** [comment]
I don't understand what you want to achieve there, can you provide show us what the final render should be ?

**Comment by iRyusa** [comment]
Hi there @nvassos any news on that ?
