### ISSUE TITLE
missing config file docu

### ISSUE THREAD

**Issue by freshfx** [mjmlio/mjml#303]
Hi,

I have a problem on generating a template with the cli using custom components.

I initialized a new component with the cli command `mjml --init-component <name>`.
This command will create a new folder with the component in ES6 style. I used babel to generate an ES5 javascript and move the file to `./components/image-link`.
Now i want to generate a template using the new component. I created a `.mjmlconfig` file in my project root path with this content
```
{
  "packages": [
    "./components/image-link.js"
  ]
}
```

I always get this error message
```
Warning: .mjmlconfig file ./components/image-link.js has an error : Error: Cannot find module './components/image-link.js'
````

Can you please tell me the right way to use custom components with the cli. (A short example/how-to would be awesome)

**Comment by iRyusa** [comment]
Hello @freshfx ,

Can you provide results of this commands : `pwd`, `ls -l`, `node -v` and the code inside `image-link.js`

**Comment by freshfx** [comment]
i'm using Node v6.2.1

here is the content of the image-link.js
https://gist.github.com/freshfx/1de3853390fcf3bbe72dcd057c80b1ea

the project structure
```
project
|-- .babelrc
|-- .mjmlconfig
|-- .nvmrc
|-- package.json
|-- bin
|-- `-- generate
|-- components
|   `-- image-link.js
|-- mails
|   `-- test.mjml
`-- dist
```

in my package.json is a `start` script which execute the `./bin/generate` script.
And this script does `mjml -r ./mails/test.mjml -o ./dist/test.html`
And thats the point i get the error.

**Comment by iRyusa** [comment]
Can you try to set the full path instead of relative to see if it works ?

**Comment by freshfx** [comment]
it works with full path. but it would be much nicer, if the path can be relative too.

**Comment by iRyusa** [comment]
It might be a working directory issue from the process `mjml` mhh i'll add some debug information for further investigation

**Comment by freshfx** [comment]
awesome. thanks.

**Comment by iRyusa** [comment]
2.3 has been released, it should gives you more informations when it happens

**Comment by alex-e-leon** [comment]
@iRyusa I'm having the same issue on v2.3
The error message I'm getting is
```
Warning: .mjmlconfig file ./new-component/src/index.js opened from ~/mjml-dir has an error : Error: Cannot find module './new-component/src/index.js'
```
Replacing the path in .mjmlconfig with an absolute path fixes the issue for me, but also exposes a new error:
```
SyntaxError: Unexpected token import
```

**Comment by iRyusa** [comment]
Does the working directory `new-component` is inside `mjml-dir` ?

I wonder if this is an issue on the `npm` package but not on the `dev` installed version

**Comment by alex-e-leon** [comment]
@iRyusa Yeap, it could be an issue with the published version. `new-component` is inside `mjml-dir`

**Comment by vbraun** [comment]
I have the same issue. Need to use

     NODE_PATH=. mjml mails/test.mjml

to pick up the module.

**Comment by iRyusa** [comment]
Hello there, 

MJML 3 come with a refactor of `.mjmlconfig` it should now parse absolute path correctly ! Feel free to test it and give us some feedback 👍
