### ISSUE TITLE
How to inject my own style into header's style tag?

### ISSUE THREAD

**Issue by rickyngk** [mjmlio/mjml#304]
I'd like to create new responsive component, so I need to define something like '@media (max-width: 500px) ...' in style tag. I have to define it in render(), consequently, it has been repeated in generated html file.

Is there any way to inject it to header's style tag?

**Comment by jitendravyas** [comment]
You can add your styles in HTML output. Afaik MJML does not allow to add style tag. 

You can check if it can help https://github.com/mjmlio/mjml/blob/master/packages/mjml-group/README.md

Share your use case by the way.

**Comment by rickyngk** [comment]
I need it when try to solve https://github.com/mjmlio/mjml/issues/24. In below snippet, I add `style` tag inside `div`. So it is repeated again and again when I use this custom component  

```
      return (
        <MJMLRaw>
          <div className="list-news" style={listStyle}>
            <style>{"\
            .list-news{\
              margin:0 auto;\
            }\
            .list-news .col6{\
              width:50%;\
              float:left;\
              margin:0 auto;\
              text-align:center;\
            }\
            @media (max-width: 500px){\
              .list-news .col6{\
                width:100%!important;\
              }\
            }"}</style>
            <div className="col6" style={itemStyle}>
              <a href={link1} style={linkStyle}>
                <img src={thumb1} style={thumbStyle}/>
                <div style={descStyle} >
                  <p dangerouslySetInnerHTML={desc1}></p>
                </div>
              </a>
            </div>
            <div className="col6" style={itemStyle}>
              <a href={link2} style={linkStyle}>
                <img src={thumb2} style={thumbStyle}/>
                <div style={descStyle} >
                  <p dangerouslySetInnerHTML={desc2}></p>
                </div>
              </a>
            </div>
          </div>
        </MJMLRaw>
      )
```

**Comment by iRyusa** [comment]
Hi @rickyngk 

You can do this with a postRender hook, it will be called once. Why do you wrap your component inside a MJ Raw ?

**Comment by rickyngk** [comment]
Hi @iRyusa 
I've just find a way to solve an issue exactly likes https://github.com/mjmlio/mjml/issues/24
I don't know how to write a good custom components. I try with MJ Raw and it works luckily. Would you plz give me some tips!

**Comment by rickyngk** [comment]
@iRyusa many thanks
