### ISSUE TITLE
[ Can be added ] Prevent IE Edge Meta Tag from Breaking Images in Live Mail

### ISSUE THREAD

**Issue by jitendravyas** [mjmlio/mjml#306]
https://www.emailonacid.com/blog/article/email-development/prevent-ie-edge-meta-tag-from-breaking-images-in-live-mail

**Comment by ngarnier** [comment]
Hey @jitendravyas, thanks for the suggestion, we'll investigate this!

**Comment by iRyusa** [comment]
It will be shipped in the next release 👍

**Comment by iRyusa** [comment]
It's now available in 3.1 👍
