### ISSUE TITLE
mj-location always displaying the default image

### ISSUE THREAD

**Issue by DHDaniel** [mjmlio/mjml#308]
The **mj-location** component, which allows you to set an address which will link to Google Maps, provides a default photo to accompany it. The component has an attribute, **src**, which also allows you to display your own photo.

However, changing the **src** attribute to something else will always end up displaying the default image - it is necessary to go into the compiled HTML file and change it from there in order to add your own custom image.

How to reproduce error:
* Use an **<mj-location>** component and add a custom **src** attribute.
* Compile to MJML and view the result.

It should display your custom image, but it displays the default.

<img width="1229" alt="screen shot 2016-06-19 at 10 42 52 am" src="https://cloud.githubusercontent.com/assets/16171992/16177996/a0990278-360a-11e6-94dc-3db7d340741f.png">
Here, you can see the issue on the online MJML editor using the latest version of Google Chrome.

**Atom version** : 1.8.0
**Language MJML version** :  1.3.0

**Comment by Everus** [comment]
It's typo in the documentation, you should use ```img-src``` attribute.

**Comment by DHDaniel** [comment]
Thanks for the clarification, @Everus

**Comment by ngarnier** [comment]
Thanks for submitting this issue @DHDaniel and thank you @Everus for solving it! We'll update the documentation. 

By the way, have you seen that the [v2](https://github.com/mjmlio/mjml/releases/tag/2.0.0) (now [2.2.0](https://github.com/mjmlio/mjml/releases/tag/2.2.0)) was released? A lot of new features that you will likely enjoy were added :-)

**Comment by DHDaniel** [comment]
Using MJML again, looked at documentation, and apparently it still says "src" instead of "img-src" on the website (https://mjml.io/documentation/#mjml-location). However, it does appear correctly in https://github.com/mjmlio/mjml/tree/master/packages/mjml-location . Could it be added to the website as well, to avoid confusion?

<img width="766" alt="screen shot 2016-07-07 at 9 16 40 am" src="https://cloud.githubusercontent.com/assets/16171992/16654417/afa2069e-4423-11e6-8910-519b4064b3d3.png">

**Comment by ngarnier** [comment]
Hey @DHDaniel, thanks for your message. It'll be updated on the website when we release MJML v2.3.0, very likely next week :-).

**Comment by iRyusa** [comment]
Website will be updated tomorrow, and it has been fixed in the github documentation

**Comment by ashishtilara** [comment]
is `Mj-location` supported in v4+?

I am seeing following while using mj-location, any idea
`Line undefined of undefined (mj-location) — Element mj-location doesn't exist or is not registered`

MJML v4.0.5.

Appreciate any help :)

**Comment by jakob-senzio** [comment]
sad to hear this. it is still listed on your website though > maybe remove it there, too. 

https://mjml.io/components

**Comment by ngarnier** [comment]
As it's very easy to reproduce with a simple mj-image and mj-text, the added value is very weak, which is why we removed it. 

@jakob-senzio the components page is not accessible from the navigation anymore, how did you find it, Google?

**Comment by jakob-senzio** [comment]
yup, found it via google.
