### ISSUE TITLE
Container not centered on outlook.com

### ISSUE THREAD

**Issue by fmonts** [mjmlio/mjml#309]
I can't find how to center the container on outlook.com.

This is how the email should be:

[![1](http://i.imgur.com/wZZABZN.png)](http://i.imgur.com/wZZABZN.png)

And this is how it appears on outlook.com:

[![1](http://i.imgur.com/8qsreSV.png)](http://i.imgur.com/8qsreSV.png)

As you can see, the container is aligned at left instead of centered. I've also tried to add `align="center"` in the body, but without success.
In the other clients I've tried it works well.

Full code:

```
<mjml>
  <mj-body>
    <mj-container width="700" background-color="#eceff4" align="center">
      <mj-section padding-top="0" padding-bottom="24">
      </mj-section>
      <mj-section background-color="#d8e2e7" padding="1">
        <mj-column background-color="white" padding="30">
          <mj-image width="200" src="https://placehold.it/400x200" padding="10px 0 20px 0" />
        </mj-column>
      </mj-section>
      <mj-section background-color="#d8e2e7" padding="1">
        <mj-column background-color="white" padding="30">
          <mj-text font-size="15" padding="30px 30px 16px" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif">
            Dear {{ username }},
          </mj-text>
          <mj-text font-size="15" padding="0 30px 16px" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif">
            Welcome to {{ siteName }}!
          </mj-text>
          <mj-text font-size="15" padding="0 30px 16px" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif">
            To complete the registration, please confirm your email address by clicking the link below.
          </mj-text>
          <mj-text font-size="15" padding="0 30px 6px" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif">
            We may need to send you critical information about our service and it is important that we have an accurate email address.
          </mj-text>
          <mj-button background-color="#00a8ff" color="white" font-size="15" border="none" border-radius="0" align="left" padding="8px 16px 10px" paddint-top="0" padding-left="30" padding-right="30" padding-bottom="16" font-weight="400" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif"
            href="#">
            Confirm E-Mail Adress
          </mj-button>
          <mj-text font-size="15" padding="0 30px 30px 30px" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif">
            — {{ siteName }} Team
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section padding="20px 0 0">
        <mj-column>
          <mj-text padding="0" font-size="15" color="#6b7a85" align="center" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif">
            <a href="{{ siteUrl }}" style="text-decoration: none; color: inherit;">
              <span style="border-bottom: solid 1px #b3bac1">Dashboard</span>
            </a> |
            <a href="{{ settingsUrl }}" style="text-decoration: none; color: inherit;">
              <span style="border-bottom: solid 1px #b3bac1">Email settings</span>
            </a>
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section padding-top="0" padding-bottom="24">
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by Zul3s** [comment]
Hi, 
For align text, you need to use `align="center"` to `<mj-text>`.
Example: 

`<mj-text font-size="15" padding="30px 30px 16px" font-family="Proxima Nova, Arial, Arial, Helvetica, sans-serif" align="center">Dear {{ username }},</mj-text>`

**Comment by ngarnier** [comment]
hey @fmonts, as @Zul3s said, you need to use `align="center"` on the `mj-text`and `mj-button` tags to center the content. I also suggest using [`mj-head` and `mj-attribute`](https://mjml.io/documentation/#mjml-attributes) to specify it only once instead of repeating it on each tag: 

```
  <mj-head>
    <mj-attributes>
      <mj-text align="center" />
    </mj-attributes>
  </mj-head>
```

I'll close the issue as it seems to solve your problem, feel free to reopen if it's not the case.

**Comment by fmonts** [comment]
I don't want to align the content but the whole container. I hope you will understand with this image:

[![1](http://i.imgur.com/sNxAydb.png)](http://i.imgur.com/sNxAydb.png)

**Comment by fmonts** [comment]
@ngarnier I don't know how/I can't reopen it

**Comment by iRyusa** [comment]
Is this version of outlook still available ? I think OWA has now replaced it for everyone ?

**Comment by iRyusa** [comment]
Any news on that ?

**Comment by fmonts** [comment]
I tried 3 ms mail accounts, 2 of them still have that version (one @outlook.com and one @live.it). 

I use my outlook.com account as my primary personal email, with many emails received everyday, and I log in to the webmail almost everyday, so it's not an abandoned one...

**Comment by iRyusa** [comment]
Well I have no access to this version of outlook.com, and only new `outlook.com` is available on Litmus so if anyone have any knowledge to fix this let me know

**Comment by fmonts** [comment]
Some examples of emails correctely centered:

<div style="max-width:700px;background:#d8e2e7;">

PayPal receipt: fixed-width table with align="center"
```
<table align="center" border="0" cellpadding="0" cellspacing="0" style="color:#333333 !important;font-family:arial,helvetica,sans-serif;font-size:12px;" width="600">
```

Linkedin notifications: they use a table with fixed width child of a td with align="center" 
```
<td align="center">
    <table border="0" cellspacing="0" cellpadding="0" style="font-family:Helvetica,Arial,sans-serif;min-width:290px;" width="550" class="ecxresponsive"> 
        ...
    </table>
</td>
```

mjml mails, instead, have a DIV with fixed with and not center-aligned. it works if I replace (in dev tools):
`<div style="max-width:700px;background:#d8e2e7;">`
with
`<table style="max-width:700px;background:#d8e2e7;" align="center">`

**Comment by iRyusa** [comment]
Found out `Outlook.com` doesn't support margin, so that's why it is not centered...

**Comment by iRyusa** [comment]
Well http://www.winbeta.org/news/users-new-outlook-com-end-summer ... this outlook.com version look like to completely disappear soon

**Comment by fmonts** [comment]
Ok, good new then, I close the issue.

**Comment by mklemme** [comment]
Outlook does support margins. For the ones that use word as the rendering engine, it should work with `Margin`. Don't ask me why someone decided to create their own standard but they did. 
More info: https://www.emailonacid.com/blog/article/email-development/outlook.com-does-support-margins
