### ISSUE TITLE
supported clients?

### ISSUE THREAD

**Issue by kukac7** [mjmlio/mjml#31]
outlook?
gmail?
ios?
etc...

thanks!

**Comment by iRyusa** [comment]
Hello @kukac7 

Yes you're right, it should be added on the Readme !

**Comment by kukac7** [comment]
@iRyusa :bow:

**Comment by iRyusa** [comment]
As @lohek mentioned to me, you can find it there: https://mjml.io/faq#email-clients :+1:  if this is ok, you can close the issue :)

**Comment by tagliala** [comment]
Hello, were this information removed from the FAQs?
