### ISSUE TITLE
Outlook Mail Client Text Visible only After Resize

### ISSUE THREAD

**Issue by Tanmayshetty** [mjmlio/mjml#311]
I am having issue with outlook mail client text display.
By default the text in outlook is not getting displayed but after resizing the window to any size, the text becomes visible.
I have added images below for better understanding.

**Screenshots**
By default the text is not displayed :
![imgpsh_fullsize12](https://cloud.githubusercontent.com/assets/8419309/16204318/f25dadb6-373b-11e6-8afe-7f0c51687dc0.png)

But when window is resized to any size the text shows up 
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/8419309/16204384/2d3d8d66-373c-11e6-9957-c8e8a0903772.png)

The email template is based on [Confirmation Email Template](https://mjml.io/try-it-live/templates/confirmation-email)

**MJML Version**
mjml --version
2.2.0

**Email clients the bug is seen on:**
Outlook Mail Client

I have attached the mjml file as a  text file

[welcome.txt](https://github.com/mjmlio/mjml/files/323987/welcome.txt)

Can someone point out how I can solve this issue.?
P.S I cannot ask the users to resize the window.
Thanks

**Comment by lRlevolution** [comment]
Try wrapping the text with a span style and giving the text size an !important tag.

**Comment by Tanmayshetty** [comment]
@lRlevolution I tried with adding display:block !important to all span elements above the text and the issue still exists.

**Comment by ngarnier** [comment]
Hi @Tanmayshetty, thanks for reporting. That's a weird behaviour indeed, we'll investigate to understand what happens.

**Comment by ngarnier** [comment]
Hey @Tanmayshetty, have you had a similar issue lately? I just tried with MJML v3.0.2 and there doesn't seem to have any issue on Outlook Mail so I'm closing.

Feel free to reopen if you see a similar issue happen!
