### ISSUE TITLE
Allow us to set the encoding and charset...

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml#315]
...because some (bad) mail marketing systems... Well, you know.

Thank you!

**Comment by iRyusa** [comment]
Hello @robsonsobral !

You mean meta charset ?

**Comment by robsonsobral** [comment]
Yes, you're right! The encoding should be changed on the MJML App.

Can you, please, add the meta charset?

Thank you for your attention!

**Comment by iRyusa** [comment]
Well it's not an issue with the MJML core itself so I'm closing this one, and update will be on MJML App repo !

**Comment by robsonsobral** [comment]
Not even the meta charset, @iRyusa ?
