### ISSUE TITLE
Stop to encoding `&`

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml#316]
Hi!

The mail marketing system one of my clients use is having problems with query strings on links.

Is it possible to stop encoding `&` as `&amp;` on `href`?

Thank you!

**Comment by iRyusa** [comment]
Hi there, 

Can you share your MJML code + MJML version please ? In 2.2 here `&` aren't encoded inside a href.

**Comment by robsonsobral** [comment]
Sure!

I'm using MJML v2.2.0.

A sample of the code:

```
<mj-section>
	<mj-image href="https://domain.com/ListaProdutos.asp?IDLoja=0000&BuscaNomeRef=True&Digitada=True&Texto=foo&x=0&y=0" src="http://domain.com/news/2016-06-22/banner.jpg" width="600"/>
</mj-section>
<!-- end banner -->
```

**Comment by lRlevolution** [comment]
I've also had this problem. Easiest solution is after the mjml has been outputted to html perform a search a replace for &amp; to &

**Comment by robsonsobral** [comment]
It's what I did too, @lRlevolution .

**Comment by zrb0529** [comment]
Hey @robsonsobral - what system are you using? I have access to Teradata eCircle and Salesforce Marketing Cloud to test on.

**Comment by iRyusa** [comment]
Hello @robsonsobral !

It will be fixed in 2.3 with https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/MJMLRenderer.js#L12

**Comment by robsonsobral** [comment]
@zrb0529 , I've to ask my coworker.

@iRyusa , thank you!

**Comment by iRyusa** [comment]
2.3 has been released and should fix this, please re-open if needed
