### ISSUE TITLE
Button component line-height option

### ISSUE THREAD

**Issue by blackfyre** [mjmlio/mjml#319]
Hi!

I've got some issues with the button component: https://www.dropbox.com/s/cxzrg8i88j02fhh/mjml-button-line-height-error.jpg

Basically in Outlook 2003 / 2017 / 2013 multi line buttons have to much for line height. It doesn't seem to be explicitly set, but an attribute for this would be great :smile:

**Comment by ngarnier** [comment]
Hi @blackfyre, thanks for creating this issue. Indeed multi-lines buttons can be tricky, we'll investigate if we can safely introduce line-height to the button component (I'm pretty confident it won't cause any major issue).

**Comment by blaugueux** [comment]
Cf. https://www.campaignmonitor.com/css/ ```line-height``` seems to be supported across almost every email client

**Comment by eikaramba** [comment]
+1 for this. Also have problems because my button should display a long link that is breaking and now looks quite ugly because of the inner background-color of the a tag. Maybe another option would be to customize the inner background-color. Or set line-height.

**Comment by ngarnier** [comment]
Fixed in 3.3.3: https://github.com/mjmlio/mjml/releases/tag/3.3.3
