### ISSUE TITLE
Modify the default width of the email

### ISSUE THREAD

**Issue by damien-couteillou** [mjmlio/mjml#32]
Hi I was wondering if there is any solution to modify the default width of the email. Because for now it's 600px wide but I want a 550px wide email.

**Comment by iRyusa** [comment]
Hi @damien-couteillou,

At the moment, MJML supports only 600px layout. I think we can add an attribute on mj-body, like: `<mj-body width="550px">`

**Comment by damien-couteillou** [comment]
Ye

**Comment by iRyusa** [comment]
Added in 1.1.0

**Comment by damien-couteillou** [comment]
Thx guys ! Good job on the reactivity !

**Comment by PickRelated** [comment]
Looks like something has been refactored and body width attribute does not work. Is this the case?

**Comment by iRyusa** [comment]
It's now on mj-container

**Comment by PickRelated** [comment]
Ah! Good to know! I could have guessed from mj-container documentation. Thank you!
