### ISSUE TITLE
Columns Absolutely don't work

### ISSUE THREAD

**Issue by yeranuhistdev** [mjmlio/mjml#323]
In your templates you have this https://mjml.io/try-it-live/templates/reactivation-email . Please see the screenshot attached of how this looks on gmail.
![fd4c226b3e](https://cloud.githubusercontent.com/assets/20209625/16459116/c0a0b9c8-3e32-11e6-982b-8fed3efe751b.jpg)
The columns logic that you currently have does not seem to be working at all. Did you check your templates on a real email? I have tried to use a custom template created on my own following all the instructions you have in your documentation for mj-column but this does not work in a real email. Your media ( http://joxi.ru/zANdlYESlPQzam ) is not rendered by emails. I have checked this https://github.com/mjmlio/mjml/issues/312, was not helpful. Please provide a solution or a workaround for this.

**Comment by g0ddish** [comment]
Issue #40 covers this pretty extensively, Gmail for users and for business render differently.

**Comment by iRyusa** [comment]
Hi @yeranuhistdev ,

I'm closing this one because this is an issue with google apps as mention @g0ddish feel free to take a look at a #40
