### ISSUE TITLE
mjml-html tag in website documentation empty

### ISSUE THREAD

**Issue by DHDaniel** [mjmlio/mjml#326]
The `mjml-html` component in the website documentation is empty (https://mjml.io/documentation/#mjml-html), which could be confusing for newcomers.

Image:
<img width="1298" alt="screen shot 2016-07-07 at 2 12 21 pm" src="https://cloud.githubusercontent.com/assets/16171992/16664153/d9db1bb6-444c-11e6-9a7c-3d1aeae5b2b9.png">

https://mjml.io/documentation/#mjml-html

**Comment by ngarnier** [comment]
Hey @DHDaniel, this component is aimed at including HTML directly in your MJML file but it could indeed benefit from a little documentation explaining this more in details. 

We'll improve it, thanks!

**Comment by ngarnier** [comment]
Update on this: we'll deprecate `mj-html` in a future version as it has no real use case. Documentation was updated.

**Comment by ngarnier** [comment]
`mj-html` is deprecated
