### ISSUE TITLE
mj-social: add a cellpadding argument

### ISSUE THREAD

**Issue by blaze33** [mjmlio/mjml#327]
Currently reimplementing an email with MJML, I noticed mj-social generates a table with cellpading fixed to 0.

Wished rendering:
![icons with padding](https://cloud.githubusercontent.com/assets/542233/16681953/183d4162-44f8-11e6-9f67-d9a6bfdaa18b.png)

Available rendering:
![icons without padding](https://cloud.githubusercontent.com/assets/542233/16681963/1fd5011c-44f8-11e6-92df-2ef225653488.png)

Editing https://github.com/mjmlio/mjml/blob/master/packages/mjml-social/src/index.js would be pretty straightforward but I don't know if doing so would cause other rendering issues.

I think a workaround would be to use mj-table instead for now.

**Comment by iRyusa** [comment]
Hi @blaze33 !
I think we should add something like `inner-padding` attributes, thanks for reporting it

**Comment by blaze33** [comment]
Thanks, in the meantime I worked around this issue with a section with 4 fixed-width columns, like this:

```
<mj-section>
  <mj-column width="53px">
    <mj-image width="24px" height="24px" align="center" padding="14px"
      href="link1" src="icon1.png" />
  </mj-column>
  etc...
```

Works well but an `inner-padding` attribute would be nice :)

**Comment by jitendravyas** [comment]
@blaze33 Thanks for raising this point. I had asked for it long time ago #6 https://github.com/mjmlio/mjml/issues/242

**Comment by grebett** [comment]
+1

**Comment by iRyusa** [comment]
Hi ! `inner-padding` has been added into MJML 3 !
