### ISSUE TITLE
Cannot install an MJML fork.

### ISSUE THREAD

**Issue by cookkkie** [mjmlio/mjml#328]
Hi,

I tried `npm install cookkkie/mjml` it installed an mjml-repo but that doesn't seem to work.
`require('mjml')` and `require('mjml-repo')` throw a "Cannot find module" error.

Thanks in advance.

**Comment by blackfyre** [comment]
Did you install it with `npm install https://github.com/cookkkie/mjml.git`?
If so, it should behave as normal, `import {mjml2html} from 'mjml'`.

**Comment by cookkkie** [comment]
@blackfyre 
```
Error: Cannot find module 'mjml'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by blackfyre** [comment]
Ok, but still, how did you install it?

**Comment by iRyusa** [comment]
Hi there,

You can't install your own repo with npm, there's a `install.sh` at the root of the repo that will link everything, use gulp build to compile everything, and there's an `test.js` in `packages/mjml` to "test" if everything is good !

**Comment by iRyusa** [comment]
Hi @blackfyre did you try it ? 

Thanks !

**Comment by blackfyre** [comment]
@iRyusa I don't have any problems with your original setup beside the only open ticket I have :wink:  
Maybe @cookkkie could have solved his problem with your input?

**Comment by iRyusa** [comment]
Oops my bad ! :)

**Comment by Uelb** [comment]
Hi, I'm trying to install a fork of MJML, but I can't find a way to do it... (I want mjml to be in my PATH). I tried npm install Uelb/mjml, and also tried to run the install.sh file, but it did not work. I can successfully run node test.js (in the packages/mjml folder).
I did not want to open a new issue as it seems to be the same, but maybe I should have

**Comment by iRyusa** [comment]
Hi @Uelb 

You can add the content of `npm bin` inside `packages/mjml` directory into your $PATH. However I'm not recommend it because it's not really a good practice.
Note that you'll have to `gulp build` the project at the root folder the first time ( and when you're making some change ).

**Comment by Uelb** [comment]
Don't worry, I just want to try something I did to see if it works the way I expect. I will revert to the normal installation way of mjmlio/master as soon as I test that. I also made a pull request and an issue so as soon as I have an answer, I will revert that.
