### ISSUE TITLE
Creating custom component?

### ISSUE THREAD

**Issue by addorange** [mjmlio/mjml#329]
Hi folks,

I am a little confused how to create a custom component following your documentation. Here is what I did:

1. installed mjml globally by npm install -g mjml
2. created a new directory to hold my email template in ~/mjml
3. created my template like src.mjml and used default components by their tags
4. did mjml -w src.mjml and it rendered perfectly
5. decided to do my custom component by mjml --init-component title within my ~/mjml folder
6. got a new file ~/mjml/title/src/index.js, but documentation expects a file Title.js
7. then tried to integrate the new component by ./title/src/index.js within my ~/mjml/.mjmlconfig
8. and it did not work and could not find the module

This is my corresponding .mjmlconfig

`{
  "packages": [
    "./title/src/index.js"
  ]
}`

What am I missing?

Kind regards,

Christian

**Comment by iRyusa** [comment]
Hi there @addorange,
Can you provide your component please ?
Did you update MJML to 2.3 recently ? It looks like the same error of #303 Can you try with absolute path ? 

Thanks !

**Comment by iRyusa** [comment]
Hi there we've released a tutorial on medium on how to create a component here: https://medium.com/mjml-making-responsive-email-easy/tutorial-creating-your-own-mjml-component-d3a236ab7093#.xmnwrahfy ! Feel free to give us some feedback !

**Comment by farouest** [comment]
Hello, i have an error after creation componant --->MJML Element mj-test doesn't exist or is not registered, how is possible for validation component.
Thanks for your request
