### ISSUE TITLE
Render Error - Unknown prop border on  tag

### ISSUE THREAD

**Issue by simunza** [mjmlio/mjml#332]
I keep getting the following message when I try to render.

Warning: Unknown prop `border` on <img> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in img
    in td
    in tr
    in tbody
    in table
    in Image (created by MJMLElement)
    in td (created by MJMLElement)
    in tr (created by MJMLElement)
    in MJMLElement (created by MJMLElement)
    in tbody
    in table
    in div
    in Column (created by MJMLElement)
    in MJMLElement (created by MJMLElement)
    in td
    in tr
    in tbody
    in table
    in div
    in Section (created by MJMLElement)
    in MJMLElement (created by MJMLElement)
    in div
    in Container (created by MJMLElement)
    in MJMLElement

My code is as follows

`<mjml>
    <mj-head>
        <mj-attributes>
            <mj-class name="green" color="#72b859"/>
            <mj-class name="white" color="#ffffff"/>
            <mj-class name="bigger" font-size="20px"/>
        </mj-attributes>
    </mj-head>
   <mj-body>
     <mj-container background-color="#ebebeb">
      <mj-spacer height="50px"/>
       <mj-section background-url="background.jpg">
         <mj-column>
            <mj-text>
            </mj-text>
         </mj-column>
         <mj-column>
         <mj-image src="logo.png"/>
         <mj-text mj-class="green">
            Some Text
         </mj-text>
         <mj-text mj-class="green bigger">
            Some text
         </mj-text>
         <mj-text mj-class="white">
            Some Text
         </mj-text>
         <mj-text mj-class="white">
            <dl>
                <dt>RSVP - </dt>
                <dd>
                     <a href="mailto: name@company.com" class="white">text name</a><br/>
                     +260 977 503 142<br/><br/>
                     <a href="mailto:name@company.com">text name</a><br/>
                     +260 967 333 421
                </dd>
            </dl>
         </mj-text>
         </mj-column>
       </mj-section>
     </mj-container>
   </mj-body>
 </mjml>`

**Comment by robwise** [comment]
I'm having this problem as well

**Comment by iRyusa** [comment]
Hi there! 
This will be fixed in 2.3.1, sorry about that

**Comment by simunza** [comment]
That’s awesome. 

Thanks.

simunza s. muyangana 

mobile: +260.97.887.1542

twitter: http://www.twitter.com/simunza | linkedin: http://linkedin/in/simunza

"Many of Africa's best and brightest become bureaucrats or NGO workers when they should be scientists or entrepreneurs." - Jennifer Brea

**Comment by iRyusa** [comment]
Hi ! 
2.3.1 has been pushed on npm ! So I'm closing this !

**Comment by simunza** [comment]
Thank you. 


simunza s. muyangana 

mobile: +260.97.887.1542

twitter: http://www.twitter.com/simunza | linkedin: http://linkedin/in/simunza

"Many of Africa's best and brightest become bureaucrats or NGO workers when they should be scientists or entrepreneurs." - Jennifer Brea
