### ISSUE TITLE
mj-list does not support font-weight attributes

### ISSUE THREAD

**Issue by fzembow** [mjmlio/mjml#334]
This seems like an arbitrary restriction - especially since it supports other font attributes like `color` and `font-size`.

**Comment by ngarnier** [comment]
Hey @fzembow, thanks for opening this issue. You are right, `mj-list` is lacking support for `font-weight`. The value of `mj-list` being limited though, we probably won't add any additional attributes to it and we are even considering removing it (while still supporting it not to break any template). It is indeed very easy to reproduce `mj-list`with a simple `mj-text`: 

```
          <mj-text padding-left="0px">
            <ul>
              <li>
                Element #1
              </li>
              <li>
                Element #2
              </li>
            </ul>
          </mj-text>
```

Does it make sense to you?

**Comment by ngarnier** [comment]
`mj-list` is deprecated
