### ISSUE TITLE
[Feature request]: Nested mj-include components

### ISSUE THREAD

**Issue by iainvdw** [mjmlio/mjml#337]
When using mj-include within included .mjml templates, the compiler gives a warning `Warning: Unregistered element: mj-include, skipping it`. I have a default `<mj-social />` configuration I would like to include in each included template, but when I do that the above compiler warning pops up.

Is it already possible to use nested includes? If so, please tell me how :)

**Comment by iRyusa** [comment]
Hello,

It's not available with the current implementation, i'm working on it for 2.4 ! 
Thanks for the feedback

**Comment by iRyusa** [comment]
Nested include is now available in MJML 3 ! Feel free to give some feedback about it
