### ISSUE TITLE
Update docs for creating custom components

### ISSUE THREAD

**Issue by alex-e-leon** [mjmlio/mjml#339]
I decided to give mjml a try for the first time today, and while most of the setup was simple and straightforward (I had a basic template up in under 10 minutes) building custom components turned out to be quite tricky in spite of what the docs say:

>Creating a component is easy!
> *[-- MJML docs](https://mjml.io/documentation/#create-a-component)*

It looks to me like the docs are mostly out of date with changes to how components are created in v2.3.0.

In addition to the docs being out of date, I found that `--init-component` generates components written in es2015 so including a module requires someone to have a custom babel build process to transpile them before they can be used.

I think the docs should include some information about this, as well as a list of babel presets/plugins mjml expects/requires for components to work out of the box (`es2015`, `react`, and `babel-plugin-transform-decorators-legacy` worked for me)

**Comment by iRyusa** [comment]
Hi there!

We're working on a better experience to create components ! Sorry about this

**Comment by alex-e-leon** [comment]
No problem, after working with components a little bit it looks like they're currently mostly for internal use and not ready for public use yet. Keep up the good work though!

**Comment by iRyusa** [comment]
Closing this one, dup of #329
