### ISSUE TITLE
Bulletproof email buttons

### ISSUE THREAD

**Issue by damien-couteillou** [mjmlio/mjml#34]
Bulletproof buttons using the same principle as https://buttons.cm/

Because I want : 
![capture d ecran 2016-02-09 a 16 43 19](https://cloud.githubusercontent.com/assets/6543024/12921190/4c2636d6-cf4c-11e5-8e9d-8c357efce0bd.png)

But on outlook 2010 I got : 
![capture d ecran 2016-02-09 a 16 43 12](https://cloud.githubusercontent.com/assets/6543024/12921207/60954d14-cf4c-11e5-94fd-3f6ee681db77.png)

**Comment by iRyusa** [comment]
Oh nice !

**Comment by Faleij** [comment]
Made a custom component for bulletproof buttons: [mj-bbutton](https://github.com/Faleij/mj-bbutton)
It's a bit hackishly implemented as it barely uses react because of mso-if statements.

**Comment by ngarnier** [comment]
Hey @Faleij, did you keep working on a bulletproof button since [2.0](https://github.com/mjmlio/mjml/releases/tag/2.0.0)? Would be nice to have bulletproof buttons in MJML!

**Comment by Faleij** [comment]
Sorry but I have not kept up with MJML since I last updated that component. Does 2.0 introduce breaking changes?

**Comment by dalefish** [comment]
Not from 1.3 to 2.02, just minor semantic changes. <mjml> and <mj-body>.

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
I'm afraid that we can't support buttons from buttons.cm :

> Can I use bulletproof buttons on top of bulletproof background images? 
> 
> Unfortunately, these buttons can not be placed on top of background images, because Outlook doesn't support nested VML elements. In many cases though, you may be able to code the design up successfully by changing the structure. For instance, if only part of the image needs to be behind text content, you can sometimes slice the image, use a bulletproof background image for only that part of the design, and use bulletproof buttons or inline images (held together by a table structure) for other parts.

Section/Mj-Hero allow users to use background-image and we can't allow outlook users to have a messy render because of the button. We’re working on improving mj-button from the current implementation.

Sorry guys ! I'm closing
