### ISSUE TITLE
[Feature request]: mjml as api service

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#340]
Hi!
I use mjml and python/django by command mjml and pipe-line for pass template and get result.
It is very simple but very slow -- 0.8 - 2 seconds.
https://github.com/liminspace/django-mjml/blob/master/mjml/tools.py#L9

Then I try make tcp-server for keep mjml instance in process and I get better speed -- 0.1-0.2 seconds.
https://github.com/liminspace/django-mjml/blob/master/mjml/node/tcpserver.js

I am not good in node.js, so I propose you make mjml-api-server that other non-node.js services can use it as fast as possible.

**Comment by ngarnier** [comment]
hey @liminspace, thanks for posting this issue. We totally agree with you and are working on it, we're doing our best to deliver a MJML API as fast as possible! 

We'll keep you updated.

**Comment by rogierslag** [comment]
We have implemented this as github.com/inventid/maily

**Comment by ngarnier** [comment]
Hey guys (cc @liminspace, @cheacase, @caymanlad, @ipa1981, @encolpe), cool update for you here! We're opening the beta for the MJML API, here is a short typeform to request access: https://mjml.typeform.com/to/tW2U6K  :-). Have fun!

**Comment by encolpe** [comment]
Very nice and convenient.

**Comment by ngarnier** [comment]
Hello guys, as we released the API in Public Beta today (https://mjml.io/api), I'm closing this! 

Thanks and hope you'll like it :)

**Comment by caymanlad** [comment]
Hi Nicholas,

This is excellent except that it would be excellent if we could download the API and host it internally on our own server. Is that possible?

Tim

**Comment by ngarnier** [comment]
Hey @caymanlad, sorry but we can't expose the internals of the API :(

**Comment by caymanlad** [comment]
Hey @ngarnier, perhaps (in due course) you may reconsider allowing people to download the API and host it internally on their own servers? I work with a lot of companies where they would love to send better styled internal emails and using a cloud hosted API would not be an option for them considering the contents of these emails internal only emails (e.g. password reset for internal application, email notification about changes within an internal application etc.).

**Comment by ngarnier** [comment]
ha ok I see, we'll keep that in mind then. And as they want to host it themselves, running MJML on a NodeJS server themselves is not an option either?

**Comment by caymanlad** [comment]
If the reward for setting up a NodeJS server is that the client will have a better styled email, I suspect a lot of people would be willing to learn about what's required to stand one up.

**Comment by ipa1981** [comment]
Agree with @caymanlad . We use MJML CLI, but we would really consider using MJML service + API to process emails just for much better performance running on localhost. For our client (the bank) processing such emails on 3rd party server is no go due to security policy.

**Comment by ed0906** [comment]
@ngarnier Is the typeform registration working?
I've applied for a key twice and had no email response :(

**Comment by ngarnier** [comment]
Hey Ed,

The typeform is for registering, it's not creating the key automatically.

I'm away from my computer for the weekend but I'll create your key on
Monday :-).

Cheers

**Comment by predragbabic** [comment]
I've applied for open beta, didn't receive email with credentials (I tried to apply twice), should I wait for it or? Is there a problem with open beta registration...

**Comment by ngarnier** [comment]
hey @predragbabic, I just created your account on the API, you should have received them now :)

**Comment by majkoll** [comment]
@ngarnier, I tried to apply for the open beta api but haven't received any email either (as predragbabic). Can you help me out?

**Comment by ed0906** [comment]
@majkoll I had the same issue, they have a Slack channel that you can give them a prod on

https://slack.mjml.io/

**Comment by majkoll** [comment]
Thanks for the info @ed0906. Just joined the channel

**Comment by ngarnier** [comment]
Hey guys, when you fill and submit the form, you're just applying for the beta. We'll then create the credentials manually, so you just have to be a little patient 🙂

**Comment by creativenoobie** [comment]
@ngarnier @iRyusa @robink @loeck @GuillaumeBadi @meriadec @arnaudbreton @epayet

+1 to @caymanlad & @ipa1981.
Hosting API on self-hosted server will promote privacy.
Also, MJML claims to be an open source project, It makes sense to release the API source code.

**Comment by ngarnier** [comment]
wow. I just created your keys @creativenoobie. Please avoid pinging the entire world next time you need help and can't wait, one comment is enough.

MJML is open source, you can see the source code on that very same repo you're commenting, as well as the license. 

About the API source code, you probably wouldn't use it because it includes complexity layers that we need as we provide it as a service (free by the way). However, I doubt you would like to run services and databases to handle credentials management, user management, databases, load balancers, communication between different languages, etc etc.

**Comment by aggarwal-dev** [comment]
@ngarnier Thanks for the keys. btw, I pinged "the entire world" for API source code.

I can see the MJMl source code, but source code related to APIs. And about the doubt you are having, Maybe I will run services? or maybe someone else will? Maybe only one way to find it out?

Anyway, Appreciate your help though. Thanks a ton!
Cheers

**Comment by creativenoobie** [comment]
@ngarnier Thanks for the keys and reply! And by the way, I was pinging "the entire world" for APIs source code.

I can see the MJML source code but I can't find anything related to APIs.

About the doubt you are having,  Maybe I will run services? Maybe someone else will? Only one way to find it out? It's not about complexity when it comes to user's privacy and I do care about privacy (including myself and my users). And I do believe that beautiful design (MJML is a great way to develop stunning emails, I give you that) and privacy can go hand-in-hand.

Anyway, I really appreciate your help and thanks for the keys.

P.S.: I'll keep your point about "pinging the entire world" in mind next time.

**Comment by creativenoobie** [comment]
@ngarnier 

Thanks for the keys.

**Comment by liminspace** [comment]
@ngarnier you can use your own API-service, it is not too difficult do write it by yourself. For example, I use my own solution based on TCP-server and it work very good on production. Code is here https://github.com/liminspace/django-mjml/blob/master/mjml/node/tcpserver.js
You can run several process on different port to balance the load and use random one in your client.

**Comment by anand-gopinath** [comment]
@ngarnier Just got the Keys via mail. Could you give me an example to use it the same on CURL as Postman API request?
![2323](https://user-images.githubusercontent.com/25955939/37697884-82cd3270-2d05-11e8-933f-fada22fbedff.png)

**Comment by ed0906** [comment]
@anand-gopinath See https://mjml.io/api/documentation/

e.g.
`curl -X POST \
  https://api.mjml.io/v1/render \
  -H 'Authorization: Basic XXXXXXX' \
  -d '{
   "mjml": "<mjml><mj-body><mj-container><mj-section><mj-column><mj-text>Hello World!</mj-text></mj-column></mj-section></mj-container></mj-body></mjml>"
}'`

**Comment by jablkopp** [comment]
Hey guys,

I did `mjml-server` npm package that I use in production. It speeded up parsing single email from about 800ms to 5ms. Take a look - maybe it will work for you too. 

github: https://github.com/Siepomaga/mjml-server
npm: https://www.npmjs.com/package/mjml-server

**Comment by danihodovic** [comment]
Another mjml server implementation here: https://github.com/shyim/mjml-server

**Comment by florentdestremau** [comment]
> Hey guys,
> 
> I did `mjml-server` npm package that I use in production. It speeded up parsing single email from about 800ms to 5ms. Take a look - maybe it will work for you too.
> 
> github: https://github.com/Siepomaga/mjml-server
> npm: https://www.npmjs.com/package/mjml-server

this saved me today, I even made a pull request to update some things

**Comment by dubcanada** [comment]
There is a free sponsored mjml api at http://mjml.dev if anyone needs one.

I am the one who maintains it.
