### ISSUE TITLE
Dollar sign (currency) issues

### ISSUE THREAD

**Issue by dangodev** [mjmlio/mjml#341]
When I try to render a string with a dollar sign (e.g.: `$29.00`) inside`<mj-text>`, the `$` bugs it out and it repeats the entire email multiple times. I’m guessing this has something to do with the React parser.

I suggest at least adding this to the docs, as well as a note about how to escape this behavior. I’d also like to know how to take advantage of this; I can see how dynamic text could be very useful. But again, I can’t find anything about this in the docs so right now I’m just plain confused.

**Comment by iRyusa** [comment]
Hello !

Do you have a simple example that reproduce it ? ( already happened here #305 )

I suggest you to use html friendly `$` in the meantime

**Comment by dangodev** [comment]
Ah. I forgot to search closed issues when I tried to see if it was an existing issue or not. I see you had a problem reproducing it. Hopefully this will do it for you: https://gist.github.com/dangodev/c4e66cd4c34eeb20681c20be970ac2b3

On line 61, that entity is a `$`. I had to use that to get this to work.

**Comment by iRyusa** [comment]
We figured out that if `$` is close to a number it duplicate some random nodes... I'll keep testing 👍

**Comment by dangodev** [comment]
Awesome; glad it helped!

**Comment by detj** [comment]
@iRyusa This can be implemented better. Rather than directly replacing `$` characters, why not let the user decide what characters to escape. It can be in compile options.
I stumbled upon this issue a bit differently. I was using the [es6-template-strings](https://www.npmjs.com/package/es6-template-strings) package to dynamically replace variables inside my email string, and because of this change, it would replace all `$` characters to `&#36;` which is not what I want it to do.

**Comment by janedbal** [comment]
I'm facing the issue with **unwanted replacing** too. I want to pass generated html to [latte template engine](https://github.com/nette/latte) where `href="{$link}"` is used for variables and `href="{&#36;link}"` of course doesn't work.

@iRyusa Is there a chance this will be reimplemented in better way?

**Comment by iRyusa** [comment]
@janedbal It will not be an issue because `he` wil re-encode it at the end.

**Comment by detj** [comment]
@iRyusa Sorry, but what is `he` ?

**Comment by iRyusa** [comment]
`he` is an html encoder/decoder https://github.com/mathiasbynens/he We used it just before the final HTML render

**Comment by jaoued** [comment]
Hi,

I have the same problem with dollar sign with **mj-image** component : `<mj-image src="{{ $logoUrl }}" />` where `{{ $url }}` is transformed to `{{ &#36;logoUrl }}`.

With `mj-button` there is no issue.

Regards.

**Comment by Roadirsh** [comment]
Hi,

Same problem, I'm trying to use Laravel Blade function into mjml like @foreach but it's just removed. 

And something like $variable->attribute is transformed by $variable-><![CDATA[attribute. 

 Is there a way to escape some sentence/word/part with by exemple @{{ }} bracket or [[[ ]]] so it is not interpreted by mjml?

Thanks.

**Comment by iRyusa** [comment]
It's an issue with our XML parser and as of today we have no fix for that. See #394 & #410

Best workaround is to use safe chars for variable, and replace them with something like gulp

**Comment by ModernArtisan** [comment]
Still no solution to use it with another template languages like blade?

**Comment by himanxupathak** [comment]
<Link onClick={(event) => (!name || !room) ? event.preventDefault() : null} to={"/chat?name=${name}&room=${room}"} >
                <button className="button mt-20" type="submit">Sgn In</button>
            </Link>

the name and room variable are not working dynamically in the browser
someone help me out please

**Comment by himanxupathak** [comment]
`<Link onClick={(event) => (!name || !room) ? event.preventDefault() : null} to={"/chat?name=${name}&room=${room}"} >
                <button className="button mt-20" type="submit">Sgn In</button>
            </Link>`

**Comment by iRyusa** [comment]
@himanxupathak This is not related in any way to MJML.

**Comment by shulfei** [comment]
We encountered the same problem.
Blade expressions containing mjml tags are stripped by the mjml compiler.

Our solution is to insert the beginning and end of the blade construct into the mj-raw tag. Like:
```
<mj-raw>@if(...)</mj-raw>
...
<mj-raw>@endif</mj-raw>
```

Another solution might be to first obtain all the mjml content with its recursive includes. Then feed it all into the blade. And only then compile the html from the mjml.
