### ISSUE TITLE
HTML entities being replaced by the actual character

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml#343]
Hi!

HMTL entities, like `&eacute;` are being replaced by the actual character they represent. Since MJML doesn't respect file encoding or has a `charset`meta-tag, I have to reconvert the encoding over and over again.

Thank for the app and for the attention.

**Comment by mskec** [comment]
@ngarnier I'd be open to work on this, could someone point me in the right direction?

**Comment by ngarnier** [comment]
Did a few tests and it should be fixed in the latest MJML 4 beta, install with `npm install mjml@next`. 

Would be great if you can check @robsonsobral and @mskec (sorry for not answering you back then 😞 ). 

Feel free to reopen if you can reproduce.
