### ISSUE TITLE
Printer-friendly emails - outputs mobile version rather than desktop

### ISSUE THREAD

**Issue by yodiyo** [mjmlio/mjml#344]
For printing emails (still common with our partners, I'm told):

Expected:
The email would print the desktop version, eg any columns would be inline rather than vertical.

Actual:
The email prints the mobile version, eg any columns are vertical.

As well as my own templates, I have looked and tested a couple of the responsive templates from the website.

**Comment by iRyusa** [comment]
Hi there!

Looks like gmail is stripping most of CSS for "printable" version, i don't know if we can do anything about it

**Comment by yodiyo** [comment]
Thanks for your response. I hope there's a way to do it. Not a simple thing, I know.

**Comment by ngarnier** [comment]
Hey @yodiyo, we can't do much here as Gmail removes the styles. Honestly, it would also add a lot of overhead for an edge-case as printing emails is not that common, so we won't dedicate effort on this, at least for now.
