### ISSUE TITLE
Gaps & stacking in Android Gmail

### ISSUE THREAD

**Issue by zetalevel** [mjmlio/mjml#346]
Forgive me if this has already been posted. In Gmail on Android we see gaps between sections and inability to stack columns. The screenshot of a portion of our E-mail evidences both issues. I hope the problem is with our code and not yours.
![mjml-gmail-android](https://cloud.githubusercontent.com/assets/1233963/17260415/3fb06844-559e-11e6-8a69-f0d1a0b28c56.png)

**Comment by zetalevel** [comment]
`<mjml>
  <mj-head>
    <mj-attributes>
      <mj-class name="hln" line-height="30px" font-size="27px" font-weight="bold" color="#dcb800" />
      <mj-class name="sub" font-size="16px" padding="10px" color="#dcb800" align="center" />
      <mj-class name="whn" font-size="17px" font-weight="bold" color="#dcb800" />
      <mj-class name="std" font-size="15px" color="#fff" />
      <mj-all font-family="Arial" align="center" />
      <mj-image padding="0" />
    </mj-attributes>
  </mj-head>
 
  <mj-body>
    <mj-container background-color="#000">
 
      
      <mj-section background-color="#000">
        <mj-column>
          <mj-text mj-class="std">
            National Science Foundation and the American Association of Community Colleges<br /><span style="font-style: italic">present</span></mj-text>
          <mj-text mj-class="hln">
            Community College Innovation Challenge Finalists' Reception</mj-text>
        </mj-column>
      </mj-section>
 
      
      <mj-section background-color="#000">
        <mj-image src="https://www.nsf.gov/news/newsmedia/ccic2016/img/header_invite.jpg" />
      </mj-section>
 
      
      <mj-section background-color="#000">
        <mj-column>
          <mj-text mj-class="sub">Please join us to celebrate Innovations at the Nexus of Food, Energy and Water</mj-text>
        </mj-column>
      </mj-section>
 
      
      <mj-section background-color="#000">
        <mj-column>
          <mj-text mj-class="whn">When:</mj-text>
         <mj-text mj-class="std">Wednesday<br />June 22 2016<br /> 5:00–7:00 p.m.</mj-text>
        </mj-column>
        <mj-column>
          <mj-text mj-class="whn">Where:</mj-text>
          <mj-text mj-class="std">Hart Senate Office Building - Hart 902</mj-text>
        </mj-column>
        <mj-column>
          <mj-text mj-class="whn">RSVP:</mj-text>
          <mj-text mj-class="std">klaryea@aacc.nche.edu</mj-text>
        </mj-column>
      </mj-section>
             
      <mj-section background-color="#000">
        <mj-column>
          <mj-text mj-class="sub">Come support our community college student teams and their innovations by helping to select a People's Choice Winner!<br /><br />In addition to the technical judging there will be a People's Choice Award where you can vote for the team with
            the most compelling STEM solution by simply filling out a ballot on site. The People's Choice Winner will be announced at the reception.<br /><br />Featuring Community College Innovation Challenge Finalists from:</mj-text>
          <mj-text mj-class="std">Red Rocks Community College, Colorado<br /> Perimeter College at Georgia State University, Georgia<br /> Henry Ford College, Michigan<br />Normandale Community College, Minnesota<br />Forsyth Technical Community College, North Carolina<br />Northeast
            Community College, Nebraska<br />Tulsa Community College, Oklahoma<br /> Bucks County Community College, Pennsylvania<br />Virginia Western Community College, Virginia<br />Northeast Wisconsin Technical College, Wisconsin</mj-text>
        </mj-column>
      </mj-section>
 
      <mj-section background-color="fff">
        <mj-column>
          <mj-image width="100" src="https://www.nsf.gov/news/newsmedia/ccic2016/img/nsf_logo.jpg" /></mj-column>
        <mj-column>
          <mj-image width="255" src="https://www.nsf.gov/news/newsmedia/ccic2016/img/AACC_logo.jpg" /></mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

**Comment by ngarnier** [comment]
hey @zetalevel, it would help to have the whole MJML code you're using. Can you please share it, maybe as a gist?

**Comment by iRyusa** [comment]
I have not the same behaviour as you with given code in Gmail Android on Litmus 
![image](https://cloud.githubusercontent.com/assets/570317/17511607/00f553ec-5e24-11e6-9d9d-c04c4026876c.png)

Are you using a beta version of gmail app or something ?

**Comment by zetalevel** [comment]
OK here's my gist of the MJML: https://gist.github.com/zetalevel/80704d665872fefab14af6a23a3f47a3

Thank you @iRyusa, it's encouraging that it worked in Litmus. I am using Gmail for Android 6.7.128801648.release which appears to be a recent release.

**Comment by iRyusa** [comment]
Mh what is your phone ? And what's resolution too ?

**Comment by zetalevel** [comment]
Phone is Moto G 1280 x 720

**Comment by iRyusa** [comment]
We can't reproduce on a real phone here :/ 

Any chance you're sending your mail through a service that alter the HTML ? Such as inlining style or something?

**Comment by zetalevel** [comment]
The HTML was sent using the Insert method on Outlook. Sending the HTML through other services such as Putsmail and GovDelivery performed the stacking basically correct, but shows only the mobile layout in clients including desktop Outlook and desktop-browser-Gmail.

`<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all font-family="Arial" align="center" font-size="20px" />
    </mj-attributes>
  </mj-head>

  <mj-body>
    <mj-container>

      <mj-section background-color="#aaaaaa">
        <mj-column>
          <mj-text>Tests of MJML</mj-text>
        </mj-column>
      </mj-section>

      <mj-section background-color="#bbbbbb">
        <mj-column>
          <mj-text>This is text in the second section, one column.</mj-text>
        </mj-column>
      </mj-section>

      <mj-section background-color="#cccccc">
        <mj-column>
          <mj-text>
            Third section, first column displays a bear from placebear.com.</mj-text>
        </mj-column>
        <mj-column>
          <mj-image align="center" width="250" src="http://www.placebear.com/g/300/200.jpg" />
        </mj-column>
      </mj-section>

      <mj-section>
        <mj-column background-color="#CCFFD9">
          <mj-text>Section 4 Column 1</mj-text>
        </mj-column>
        <mj-column background-color="#99FFB3">
          <mj-text>Section 4 Column 2</mj-text>
        </mj-column>
        <mj-column background-color="#66FF8C">
          <mj-text>Section 4 Column 3</mj-text>
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>`

**Comment by iRyusa** [comment]
Well outlook certainly alter the email, do you use Google apps Gmail ? Because it's an open issue see #40, Google apps Gmail doesn't support media queries at all, regular Gmail does

**Comment by iRyusa** [comment]
Feel free to reopen if it's not Google apps gmail thanks
