### ISSUE TITLE
Can MJML create a mixed content file?

### ISSUE THREAD

**Issue by magicdude4eva** [mjmlio/mjml#348]
We are currently using Freemarker to generate emails. In short a Freemarker template contains the mail-header, text-mime-part and HTML-mime part. With Freemarker we merge data-variables and then use normal Javamail to send the message.

Ideally I would like to use MJML to generate the HTML portion, but would want to have our templates in a similar format to the below where email-header, text-body and HTML body are within one file.

Since we use close to 300 Freemarker template files, you can appreciate that splitting our current template into multiple files would become a maintenance night-mare.

As far as I understand, nothing can exist outside the <mjml> tag and will be stripped. Do you have any suggestions on how to possibly retain a template-file like the below where we would still be able to generate responsive emails with mjml?

```
[#compress]
Feedback-ID: generic:bidorbuytrans
X-Job: generic-mail
To: [@emailUtilities.formatEmailAddress aEmailAddress=emailrecipient/]
From: [@emailUtilities.formatEmailAddress aEmailAddress=emailsender/]
[#if (bccEmailAddress??)]Bcc: ${bccEmailAddress}[/#if]
Subject: ${mailSubject}
[/#compress]
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="email-boundary"
--email-boundary
Content-Type: text/plain; charset=us-ascii

Hello ${firstName},

[#if (mailTextBody??)]${mailTextBody}[/#if]


--email-boundary
Content-Type: text/html

<mjml>
  <mj-body>
    <mj-container>
....    
Hello ${firstName},

[#if (mailTextBody??)]${mailTextBody}[/#if]
....


    </mj-container>
  </mj-body>
</mjml>

--email-boundary--

```

What I have not shown in the above example are Freemarker imports and macros where we apply certain content sections (the idea here is to use either custom MJML components or Freemarker macros).

**Comment by ngarnier** [comment]
Hey @magicdude4eva, thanks for opening this issue. Unfortunately mjml is designed to ignore what's not in between the `mjml` tags so I can't see an easy option here apart from generating the HTML from MJML separately. 

I don't know Freemarker so I might be completely wrong here but if the email-header and text-part generally have the same form, what I can imagine though is working it the other way around by forking MJML and tweaking the [default container](https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/configs/defaultContainer.js) to include the email-header and text-body before HTML in what's generated by MJML so it complies with your Freemarker templates. What do you think?

**Comment by magicdude4eva** [comment]
Thanks for that. Forking and tweaking the default container certainly sounds like the best option at the moment.

I noticed that another user inquired about a `<ROOT>` wrapping element - is this something which could resolve the issue of having to fork in future?

**Comment by iRyusa** [comment]
Hi @magicdude4eva , following up the discussion.

I think you'll need a task runner like gulp or something to create a specific workflow for your needs.
