### ISSUE TITLE
Responsive font-size?

### ISSUE THREAD

**Issue by Razinsky** [mjmlio/mjml#352]
Hi guys,

I'm crafting my first MJML email today. It works great, there's a real need for this tool 👍 

I was wondering if there was anyway to set up responsive font-size based on media-queries on `<mj-text>` element for instance?

Thanks!

**Comment by ngarnier** [comment]
Hi @Razinsky, 

There's no "MJML" feature allowing that but you should be able to manually add media queries with the help of `mj-raw` in `mj-head`, like this: 
```
 <mjml>
   <mj-head>
       <mj-raw>
         <style>
           <!-- Your styles --> 
         </style>
       </mj-raw>
   </mj-head>
   <mj-body>
    (...)
   </mj-body>
 </mjml
```

Let us know if it works for you!

**Comment by Razinsky** [comment]
Sounds good to me thanks!

On jeu. 08 sept. 2016 at 09:27 Nicolas Garnier

<
mailto:Nicolas Garnier <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi
https://github.com/Razinsky
,

There's no "MJML" feature allowing that but you should be able to manually add media queries with the help of

mj-raw

in

mj-head

, like this:

<mjml> <mj-head> <mj-raw> <style>  </style> </mj-raw> </mj-head> <mj-body> (...) </mj-body> </mjml

Let us know if it works for you!

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/mjmlio/mjml/issues/352#issuecomment-245596707
, or

**Comment by Razinsky** [comment]
So will you guys plan to add support for `mj-raw` in `mj-head`? That would be a nice simple way to tweak final output without having to dive into ugly email HTML code!!

**Comment by iRyusa** [comment]
@Razinsky Already an open issue on that see #82

**Comment by Razinsky** [comment]
Great!

**Comment by iRyusa** [comment]
Hi @Razinsky 

We'll support media queries in 3.3 so I'm closing this issue   for now, feel free to watch https://github.com/mjmlio/mjml/issues/420 for update on this
