### ISSUE TITLE
If I place mj-image inside mj-table, image is not rendering in html?

### ISSUE THREAD

**Issue by sesn** [mjmlio/mjml#353]
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          
          <mj-table>
            <tr>
              <td><mj-image align="right" width="100" src="/assets/img/logo-small.png"></mj-image></td>
              <td><mj-image align="right" width="100" src="/assets/img/logo-small.png"></mj-image></td>
            </tr>
          </mj-table>

          <mj-divider border-style="dotted" border-width="2px"  border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>

**Comment by iRyusa** [comment]
Hi @sesn ,

`Mj-Image` are just allowed inside a `column` not inside `mj-table`. `Mj-table` accepts only `html`elements, so use a regular `img` tag here

**Comment by bassbump** [comment]
This was not clear, should be in documentation

**Comment by ngarnier** [comment]
hey @bassbump, sorry the documentation isn't clear enough. Would it be clearer if it said the following?
> This tag allows you to display a table. It only accepts plain HTML. 

By the way, feel free to send any suggestion to the documentation by submitting a pull request, the documentation is the README.md of each MJML package (for example with mj-table: https://github.com/mjmlio/mjml/blob/master/packages/mjml-table/README.md)

**Comment by bassbump** [comment]
Yep sounds good, submitted pull sorry for the trouble

**Comment by ngarnier** [comment]
No no worries, that's with such feedback that we can improve :).

Thanks a lot for the PR, you rock 👍
