### ISSUE TITLE
Google Fonts auto-detect?

### ISSUE THREAD

**Issue by Razinsky** [mjmlio/mjml#354]
Hey guys,

I just realized that MJML seems to automatically detect Google Fonts and add the right `<link>` and `@import` tags? I was using the `<mj-font>` to add it by myself but now that I look at the rendered HTML I see that the automatically added tag imports all the weights from a font family e.g. `Roboto:300,400,500,700` instead of just `Roboto:400` like I specified in my custom `<mj-font>` tag...

Is there a way to prevent this auto-detection? Because now I have 2 requests to the Google Fonts API and the automatically added one is like 3 times bigger than mine...

Thanks! Again great job!!

**Comment by iRyusa** [comment]
Hi there @Razinsky 

At the moment Roboto is part of default font :/ I'll try to add something to override default font

**Comment by iRyusa** [comment]
Hi @Razinsky just a quick follow up, it will be fix for next release  👍

**Comment by Razinsky** [comment]
Excellent, keep up the good work 😃

**Comment by iRyusa** [comment]
Hi there, you can now override default fonts in MJML 3 !
