### ISSUE TITLE
Columns Layout are broken in Polymail

### ISSUE THREAD

**Issue by Razinsky** [mjmlio/mjml#355]
I don't know if it's a Polymail (https://polymail.io/) or a MJML issue but multi-columns layout just doesn't work in this new viewer. Everything is perfect in Gmail and Apple Mail but Polymail doesn't seem to like `display: inline-block` !

In Apple Mail:
<img width="641" alt="capture d ecran 2016-08-10 a 13 48 15" src="https://cloud.githubusercontent.com/assets/3629808/17564350/2d17e3da-5f01-11e6-8442-1db8ec77752f.png">

In Polymail:
<img width="605" alt="capture d ecran 2016-08-10 a 13 48 34" src="https://cloud.githubusercontent.com/assets/3629808/17564373/300daaa2-5f01-11e6-91d6-f4d147233b56.png">

**Comment by iRyusa** [comment]
Hi there,

Polymail isn't supported by MJML for now, so it will display as mobile mode as a fallback. Polymail doesn't look to support media queries, I added it to #40 .

I close this one, and we'll keep #40 updated
