### ISSUE TITLE
Guidelines for minimizing HTML in rendered output?

### ISSUE THREAD

**Issue by creinhardt** [mjmlio/mjml#356]
I'm having trouble with GMail cutting off any emails I send with templates that I've generated with MJML   (all of them have the 'View Entire Message' link).    I know that GMail cuts things off after 102kb, so i'm trying to figure out where I can reduce the amount of markup in my template.  

I've got around 13 sections each with one column inside of each.  From what I can tell most of the markup is coming from the columns/sections.  
[example-template.zip](https://github.com/mjmlio/mjml/files/416262/example-template.zip)

Does anyone have any recommendations for reducing markup?  If my template has no 50/50 columns (basically all 100% width rows) do I even need to use columns at all?

**Comment by iRyusa** [comment]
Hi there,

There's an option on `mjml` client `-m` or `--min` that should minify the output. Your email should be ok when minified from what i've tested.

**Comment by creinhardt** [comment]
Great, thank you, i'll give that shot.

There's no way to do this from the 'Try It Live' demo, right? https://mjml.io/try-it-live

**Comment by iRyusa** [comment]
There's now way to do this from the try it live sorry, i'm closing it

**Comment by tameroski** [comment]
@creinhardt Got the same issue with Gmail and minifying is not a working solution unfortunately. Did you managed to fix this in any way ? thanks

**Comment by creinhardt** [comment]
Unfortunately I never found a great solution.  I ended up writing my e-mail
templates without MJML.

The markup for one column and 10 or so rows with all of my content ended up
being too much for GMail in most cases.  It's possible I had the template
structured incorrectly in MJML.  From what I remember it looked like there
was a lot of redundant markup, so maybe I was just doing it wrong.



Chris Reinhardt
Digital Services Manager
Newspapers of New England
603-290-1722

**Comment by tameroski** [comment]
Ok, thanks for your answer. 
My template is quiet simple (and below the 102Kb limit) so i didn't understand ... I made A LOT of tests and finally came to the conclusion that GMail is hiding what he find to be a signature, which means **everything below the name of the sender** if it finds it in the body (wherever it is) ...

Nothing to do with MJML by the way ...

**Comment by creinhardt** [comment]
If you're sending subsequent e-mails in the same thread, GMail might be
hiding what it considers to be redundant content, like the signature or
everything after the signature.  Maybe try creating a new thread by
changing the subject of the e-mail you're sending?

Might not be whats happening to you, but i've seen similar behaviour
before...

Chris Reinhardt
Digital Services Manager
Newspapers of New England
603-290-1722

**Comment by tameroski** [comment]
Yea, know that, but i had the issue with every new thread :S

**Comment by dalefish** [comment]
Does sound like a Gmail threading issue rather than an MJML issue.

Kind Regards,

:----------------------------:
Dale McConnell
