### ISSUE TITLE
Space in background-url results in wrong placement on mobile view

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml#358]
This took me some time to figure out...

**Normal behaviour:** Lets assume the newsletter has a width of 600px, the background-image file aswell. Image will be centered, and on mobile view the outer sides left and right are cropped.

But If there is a space in the background-image url, like "http://www.mywebsite.com/images/Folder 123/image.jpg", the background is not cropped left and right, but starts left and is therefore cropped more on the right.

As this is easy to circumvet it doesn't really demand a fix, but it is quite tricky and I'm curious what causes this behaviour

**Comment by iRyusa** [comment]
Hello @janus-reith 

I think it's because url with a space isn't considered valid for css spec, in Chrome inspector mark it as invalid. So maybe browsers are acting weird when you have a space in url. I should test to add a double quote on background-url to see if it works

**Comment by iRyusa** [comment]
Small update here, the most viable option is to encode the space in url with `%20` 

So I'm closing this issue !
