### ISSUE TITLE
Button border issue

### ISSUE THREAD

**Issue by dtrinh100** [mjmlio/mjml#361]
I think this is a bug, but I am not quite sure.

I expected the following codes to produce a border around the button, but instead it produces the border around the text.

`<mj-button background-color="red" color="white" font-size="15px" border-radius="10px" href="#" border="1px solid #FFFFFF">Testing</mj-button>`

The following can be reproduced on the "try live" version as well.

The mjml version that I am currently running is 2.3.2

**Comment by iRyusa** [comment]
Hi there,

It's a known issue introduce in 2.3.1, it will be fix soon in 2.3.3

**Comment by tothandras** [comment]
Hi @iRyusa, when will it be released? :) Having the same issue.

**Comment by iRyusa** [comment]
I think 2.3.3 should be released next tuesday

**Comment by ngarnier** [comment]
Hi @dtrinh100 @tothandras, I'm closing because `2.3.3` brought a fix. Feel free to reopen if you're still experiencing issues.
