### ISSUE TITLE
Feature request: svg support with mjml-image

### ISSUE THREAD

**Issue by Bogdaan** [mjmlio/mjml#362]
Hi all, i found that SVG images does not appear in some programs.

Then i found this article on css-tricks: 
https://css-tricks.com/a-guide-on-svg-support-in-email/

This approach works and may be we can add support of "svg + jpg fallback" in mjml-image?

**Comment by iRyusa** [comment]
Hi @Bogdaan ,

Coming back to this issue, I think this can be achieved by a custom component, but the use-case seems really limited to me. What do you think ?

**Comment by BenGlasser** [comment]
lack of this feature is a deal breaker for me.  web development is using to use svg everywhere.

**Comment by nicksarafa** [comment]
Yeah SVG support cross browser is hideous. If anybody has figured out a viable workaround, please share, but it looks like converting SVGs to image format is the move for the time being

**Comment by evaicash** [comment]
Hi, some updates about that?
Maybe theres a n ew version that support SVG?
thanks!

**Comment by iRyusa** [comment]
Support of svg haven’t got any better as far as I know stick with regular img insteadOn 16 Aug 2024, at 14:58, evaicash ***@***.***> wrote:﻿
Hi, some updates about that?
Maybe theres a n ew version that support SVG?
thanks!
