### ISSUE TITLE
mj-button : no border-bottom available

### ISSUE THREAD

**Issue by Lea-lynx** [mjmlio/mjml#363]
Hello, 
It seems that it's not possible to add a border-bottom on mj-button.
Expected behavior :
![mj-button-expected](https://cloud.githubusercontent.com/assets/11275402/17892659/c102bfb6-6942-11e6-887a-7d6dc0dd840a.png)

Observed behavior :
![mj-button-observed](https://cloud.githubusercontent.com/assets/11275402/17892664/c5fd6598-6942-11e6-9684-f2cb9518e380.png)

MJML version 2.2.0

**Comment by iRyusa** [comment]
Hi there @Lea-lynx 
Only `border` is supported atm, I'm adding it to feature request for `2.4`

**Comment by Lea-lynx** [comment]
Thanks !

**Comment by iRyusa** [comment]
MJML 3 has been released, and border-bottom/left/right/top is now available !
