### ISSUE TITLE
Allow to hide element for mobile display

### ISSUE THREAD

**Issue by Lea-lynx** [mjmlio/mjml#364]
Would be great to have the possibilitie of hiding an element (text or illustration for example), that we want on desktop but not on mobile as `<mj-hide>` or the possibilitie to add it has an `<mj-attribute>` only for mobile purpose.

**Comment by ngarnier** [comment]
Like for https://github.com/mjmlio/mjml/issues/378, the issue is that such a feature would rely heavily on media queries, except if you have something else in mind to achieve it?

**Comment by ngarnier** [comment]
Hello @Lea-lynx, media queries are supported in [v3.3.0 (now in beta)](https://github.com/mjmlio/mjml/releases/tag/3.3.0-beta.3). Feedback welcome! 

Example of implementation: https://mjml.io/try-it-live/HkokV_Due

PS: be careful, media queries are far from being supported in every email clients

**Comment by ngarnier** [comment]
MJML v3.3.0 is out, fixing this issue! It's now easy to achieve this behaviour using media queries. Thanks for submitting, it's a great new feature for MJML.

To install: `npm install mjml`

**Comment by esbeto** [comment]
Is it possible to hide `mj-image` with this feature?

**Comment by alexandraharet** [comment]
... or an entire section? It seems illegal to use id on either section or column elements, is here a known workaround for this?

**Comment by iRyusa** [comment]
In next version 3.3.3, you will be able to add `css-class` to any `mj-element` so you can target it with media queries in `mj-style`

**Comment by vilcuRob** [comment]
Hi @iRyusa,
When is the new 3.3.3 version coming out? 
Thanks.

**Comment by ngarnier** [comment]
hey @vilcuRob, it's going to be released in the coming weeks. We're now trying to get a [fully clickable button](https://github.com/mjmlio/mjml/pull/668#issuecomment-301502350) to work.
