### ISSUE TITLE
mj-column not rendering in Outlook and Gmail desktop when 2 columns side by side

### ISSUE THREAD

**Issue by Lea-lynx** [mjmlio/mjml#365]
`<mj-column>` is rendering `width: 100%;` on columns elements that should be fixed width like 300px or 50% each for exemple. 
Simple exemple test : 
`<mj-section>
			<mj-column width="300px" background-color="#ccc">
				<mj-text>
					Hello there
				</mj-text>
			</mj-column>
			<mj-column width="300px" background-color="#ccc">
				<mj-text>
					Hello there
				</mj-text>
			</mj-column>
		</mj-section>`

Gmail rendering : 
![capture d ecran 2016-08-24 a 14 14 30](https://cloud.githubusercontent.com/assets/11275402/17930176/2aec4d80-6a05-11e6-917b-c487561be13c.png)

Outlook rendering : 
![capture d ecran 2016-08-24 a 14 14 46](https://cloud.githubusercontent.com/assets/11275402/17930184/38c6d1fa-6a05-11e6-941b-b010c7171bea.png)

Yahoo rendering well : 
![capture d ecran 2016-08-24 a 14 14 55](https://cloud.githubusercontent.com/assets/11275402/17930195/416e8b36-6a05-11e6-8b0d-cea55edbe596.png)

**Comment by iRyusa** [comment]
Hello, i'm pretty sure you're using google apps gmail, that's why it doesn't work.

You can follow the discussion here #40

**Comment by Lea-lynx** [comment]
No. For Gmail it is on my business mail (the screenshot is small because of my mails parameters) and Outlook it's just a simple mail that i have create to test. 
I have tested the code of one of your template and the same happened. 

Gmail : 
![capture d ecran 2016-08-24 a 14 51 54](https://cloud.githubusercontent.com/assets/11275402/17931179/58b89b2e-6a0a-11e6-855b-ff03ae5de916.png)


Outlook : 
![capture d ecran 2016-08-24 a 14 52 30](https://cloud.githubusercontent.com/assets/11275402/17931188/68524896-6a0a-11e6-865f-053313c285d5.png)


Yahoo with good render : 
![capture d ecran 2016-08-24 a 14 52 57](https://cloud.githubusercontent.com/assets/11275402/17931192/7737e6ae-6a0a-11e6-835d-66e722e31c2f.png)

**Comment by iRyusa** [comment]
As I mentioned above, gmail for business == google apps gmail. Gmail for business has a terrible css support, so we can't do anything yet. Here's a quick recap of gmail madness https://emails.hteumeuleu.com/trying-to-make-sense-of-gmail-css-support-e88cd7995cea#.bavaibfzc

For outlook it's a known issue, but we can't support both outlook and outlook for mobile. It's a known issue too. See #40 for more information

**Comment by Lea-lynx** [comment]
Ok thanks a lot.
