### ISSUE TITLE
mj-hero: mj-text is not centered within

### ISSUE THREAD

**Issue by brunick** [mjmlio/mjml#366]
I've come across this on my on project and was observing it as well on the try-it-live system, 
if you just start the unedited [Hero-Demo](https://mjml.io/try-it-live/components/hero/), the text is "Go to space" is not centered. 
it does not center if i'm settings mj-hero-content to align="center" or the align tag within mj-text to anything else, not even right was working.
![image](https://cloud.githubusercontent.com/assets/1649407/17934381/1003c198-6a18-11e6-84f6-f9aa1a9d4ec5.png)
MJML version 2.3.1

**Comment by iRyusa** [comment]
Hi there,

Thanks for finding this ! I'll add a fix in next version, but try it live won't be updated within 2 week, sorry about that.

**Comment by brunick** [comment]
well, that's quite ok, 
i'm working with mjml offline on a subsystem, if theres an update for that, that would be fine :D

**Comment by brunick** [comment]
i've just downloaded the mjml app with mjml 2.2.0 - the problem isn't in that version :|

**Comment by iRyusa** [comment]
Yes, some refactor in 2.3 caused it

**Comment by ngarnier** [comment]
Closing this as the fix was released back in version [2.3.3](https://github.com/mjmlio/mjml/releases/tag/2.3.3).
