### ISSUE TITLE
img not terminating

### ISSUE THREAD

**Issue by robcube** [mjmlio/mjml#368]
Was using MJML then when looking in the HTML, the img element doesn't have the proper termination. If you'd look in any generated img, there isn't any "/>" or "></img>". Per README in nodejs\node_modules\mjml\node_modules\mjml-image, it shows it has the proper termination.

Probably a quick fix for anyone.

**Comment by iRyusa** [comment]
Hi @robcube 

`img` is a void-element so `/`can be omitted ( read http://w3c.github.io/html-reference/syntax.html#void-element ). It's perfectly valid from a HTML standpoint

So this : 
```xml
<mj-image href="https://mjml.io" src="http://191n.mj.am/img/191n/3s/xxr.png" alt="Amario logo" align="center" border="none" width="182" padding-left="0" padding-right="0" padding-bottom="0" padding-top="0" />
```

will render as this: 
```html
<img alt="Amario logo" title="" height="auto" src="http://191n.mj.am/img/191n/3s/xxr.png" style="border:none;border-radius:;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="182">
```

**Comment by robcube** [comment]
That's fine -- I can fork it without a problem. I'm using this in an old-school XML/XSLT transform and it's doesn't like the <img.. >. Do you have a recommended way to put this in the index.js code?

**Comment by iRyusa** [comment]
I have honestly no idea how to deal with that, maybe use `dangerouslySetInnerHTML` or  something exist in the JSX world to deal with void elements.

**Comment by aberasarte** [comment]
Sorry for raising this old issue but I'm seeing just the opposite behavior when rendering images. The generated `img` tags are always self-closed.

Looking at the code, I think that this has always been the expected output  https://github.com/mjmlio/mjml/blob/v1.0.0/src/components/Image.js#L62

Am I missing something here? We are applying some additional processing to the generated HTML and the tool we are using for the job, doesn't self-close any void tag. I'm just wondering if leaving those tags opened could be problematic for some email clients.

**Comment by iRyusa** [comment]
No issue with empty tag such as img/input/..., you don't have to worry about any compatibility issue here.

**Comment by aberasarte** [comment]
Great! thanks for the clarification @iRyusa .

Amazing project BTW.
