### ISSUE TITLE
<mj-button> php code in href

### ISSUE THREAD

**Issue by C0mp4ct** [mjmlio/mjml#369]
Hello, we need to put our url from php variable to button href att. If we put php code into href attr of button, it generates CDATA in it. Example:
`<mj-button href="<?= $var['url'] ?>" font-size="16px" font-weight="bold" background-color="#B21B24" inner-padding="16px 45px">BUTTON TEXT</mj-button>`

it returns:
`<a href="<?= $var['url'] ?><![CDATA[" style="display:inline-block;text-decoration:none;background:#B21B24;border-radius:3px;color:#ffffff;font-family:Asap, Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;padding:16px 45px;margin:0px;" target="_blank">BUTTON TEXT]]>`

We hope you can fix it. Thanks!

**Comment by iRyusa** [comment]
Hi @C0mp4ct 

It will not be easy to fix, and to be honest i'm not sure we can fix it. 

We have a regexp to put inner content between CDATA to keep content safe from our XML Parser. Problem is, if you put `>` inside `href` the regexp think you've ended the mj-button and put everything after in CDATA.

The best solution to your use-case is to apply your PHP vars with a pre processor and then pass it to MJML.

**Comment by ngarnier** [comment]
I'm closing this issue as we indeed have no easy way to fix that, sorry @C0mp4ct. I'll second @iRyusa, the best way to do that is to use a preprocessor and change your variables before rendering MJML.
