### ISSUE TITLE
mj-column don't work on outlook 2007, 2010, 2013

### ISSUE THREAD

**Issue by lRlevolution** [mjmlio/mjml#370]
seems like the columns don't stay as intended but instead stay on 1 row. 

![inbox preview](https://cloud.githubusercontent.com/assets/17863572/17980542/a145628c-6ab4-11e6-901c-a6f20bc8ed4c.png)

**Comment by tothandras** [comment]
We are having the same problem, I was trying to solve this with css, but couldn't do it.

**Comment by iRyusa** [comment]
Well it's not really a bug, it's the intended behaviour from the html.
For outlook we're setting a table around section, every column has a `td` so it will inline every column.
Can you provide the MJML related to this screenshot to confirm my expectation ?

**Comment by tothandras** [comment]
Sorry, I thought he meant sections, not columns: #373. :)

**Comment by lRlevolution** [comment]
You're right. What I did was just have 1 section with 6 columns hence why it appeared this way on outlook.
