### ISSUE TITLE
Misplaced sections in Outlook

### ISSUE THREAD

**Issue by tothandras** [mjmlio/mjml#373]
`mjml`:
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-text>
          <h1>Center</h1>
        </mj-text>
      </mj-section>
      <mj-section text-align="left">
        <mj-text>
          <h3>
            Header
          </h3>
        </mj-text>
        <mj-table cellpadding="2" cellspacing="2" table-layout="fixed">
          <tr>
            <th>Head A</th>
            <th>Head B</th>
            <th>Head C</th>
            <th>Head D</th>
          </tr>
          <tr style="text-align: center;">
            <td>A</td>
            <td>B</td>
            <td>C</td>
            <td>D</td>
          </tr>
        </mj-table>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Outlook 2010, 2013 (surprisingly it looks fine in 2011):

![](https://ol2013.capture.litmuscdn.com/cc621b9a-af32-4994-8ea7-a595eb482ff5/results/ol2013-vertical-allowed-1366.png)

In other clients it looks like this:
![](https://chromegoogleinbox.capture.litmuscdn.com/cc621b9a-af32-4994-8ea7-a595eb482ff5/results/chromegoogleinbox-vertical-allowed-1366.png)

**Comment by iRyusa** [comment]
Hi there,

You're missing `column` inside your section, even if it's a single column layout you need `mj-column`

**Comment by tothandras** [comment]
oh thanks, will try :)

**Comment by tothandras** [comment]
perfect! I've missed it, thank you!
