### ISSUE TITLE
Nested sections/columns results a NaNpx and missing width for Outlook

### ISSUE THREAD

**Issue by Scritik** [mjmlio/mjml#374]
Hi guys,

I don't know If I'm doing something wrong but I tried the following code:

```html
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-section>
            <mj-column>
              <mj-text>MJML</mj-text>
            </mj-column>
          </mj-section>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

The result is good except for Outlook, because MJML compiles it to 

```html
<!--[if mso | IE]>
  <table border="0" cellpadding="0" cellspacing="0"><tr><td style="vertical-align:top;width:NaNpx;">
<![endif]-->
```

2 problems:
- The width is NaNpx because the parent doesn't have any specified width.
- The table doesn't have any width at all. It should be 100%.

Have a good weekend!
Emmanuel

**Comment by iRyusa** [comment]
Hi there,

Well it's not really a bug, nesting section in column isn't allowed. 
I'm curious about why you need to nest it ?

**Comment by Scritik** [comment]
Then my guess was right :)

I wanted to wrap the all mail in a section, to have a background and a top padding instead of multiple sections.
I changed to multiple sections but it would be cool to have this feature, no?

Thanks.

**Comment by iRyusa** [comment]
Mhh it looks like multiple section with a background could be a usecase for a `wraper` as mentioned in #255

We've seen a lot of email that would benefit from that i'll reopen the #255
