### ISSUE TITLE
Request mj-container can be more than 600px??

### ISSUE THREAD

**Issue by hellfish2** [mjmlio/mjml#375]
Hi folks,

I wanna use mjml on my responsive email template, but i need the width of mj-container will be over 600px exactly 650px :) any hint to do it?

Thanks

**Comment by dalefish** [comment]
You can set the container width on either the container itself or declare the width in the attributes as below.

`<mjml>

	<mj-head>
	<mj-title>Email Title</mj-title>
    	<mj-attributes>
			<mj-container width="650px" />
     	</mj-attributes>
    </mj-head>

  	<mj-body>

		<mj-container>

			<mj-section>
				<mj-column>
                                        
                                </mj-column>
			</mj-section>
		</mj-container>

	</mj-body>

</mjml>
`
I tend to use these resets too 
`<mj-all padding="0" font-family="Arial" />
<mj-column align="center" vertical-align="middle" />`

**Comment by iRyusa** [comment]
I only edited your answer to add indention +  syntax highlight  but @dalefish is totally right ! 👍

**Comment by dalefish** [comment]
Thanks @iRyusa, it was a hasty reply, much appreciated.

**Comment by mikethehud** [comment]
For future reference, in MJML v4 `mj-container` is replaced by `mj-body` so you'd need to do:

```html
<mj-container width="650px" />
```
