### ISSUE TITLE
Column Alignment issue in Outlook

### ISSUE THREAD

**Issue by lRlevolution** [mjmlio/mjml#376]
So when adding a background image with padding to a section, the child column doesn't align properly in Outlook 2013 and perhaps Outlook 2016 on PC. (see image below)

![outlook issue](https://cloud.githubusercontent.com/assets/17863572/18099935/abbd008e-6e9d-11e6-9489-18c9633f4ffb.png)

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all align="center" />
    </mj-attributes>
  </mj-head>

  <mj-body background-color="#EAECED">

    <mj-container background-color="#EAECED">
      <mj-section padding="20px" background-size="cover" background-repeat="no-repeat" background-color="#76D2CD" background-url="http://hosting-source.bm23.com/35647/public/Promotions/2016_08_16_Promos/bg.jpg">

        <mj-column vertical-align="top" background-color="white">
          <mj-image vertical-align="top" padding-top="20" src="http://hosting-source.bm23.com/35647/public/footer/New_Footer_%2806-16%29/phone-new.png" width="120px"></mj-image>

          <mj-button padding-bottom="20" font-family="Helvetica, sans-serif" font-size="14px" font-weight="500" color="white" background-color="#e3042e" border-radius="4px" href="http://www.#.com">
            Testing 1234
          </mj-button>

        </mj-column>

      </mj-section>
    </mj-container>

  </mj-body>
</mjml>

```

**Comment by lRlevolution** [comment]
I fixed the issue by removing the padding on the section and adding a px width on the column. The only issue now is on mobile view, since the padding on the section is what would reveal the background the column spans to 100% which then removes the visibility of the background.

**Comment by iRyusa** [comment]
I wonder if it's related to #128

**Comment by iRyusa** [comment]
Update here, it's an issue with VML and there's no fix about yet about it. Outlook doesn't like multiple table inside a vml block for unknown reason. I'm closing this one and keep #128 open
