### ISSUE TITLE
Embed video and/or music player

### ISSUE THREAD

**Issue by eotp** [mjmlio/mjml#377]
Hi guys,
great work!

So far I didn´t dive very deeply into the documentation, so maybe I missed something.
Though, for my purposes I need to embed a video (e.g.  YouTube) or even a music player (e.g. from Soundcloud) in my mails.

Is this that possible within the MJML framework?

Thanks.

**Comment by dalefish** [comment]
Video in email is badly supported, for a consistent experience across
clients, an animated gif of the opening frames (with a play button overlaid
for clarity) linked out to the full video works well.

You could embed an HTML5 video using mj-raw but it would break on a lot of
clients.

:----------------------------:
Dale McConnell

**Comment by ngarnier** [comment]
I'm closing this issue for as @dalefish said, there is really little poor support for video in email so there is no `mjml` component dedicated to it. I second Dale on the second point too, if you still want to embed a video, the best would indeed be to embed your video using `mj-raw`.
