### ISSUE TITLE
Text right on desktop, left on mobile

### ISSUE THREAD

**Issue by mdrick** [mjmlio/mjml#378]
Hi,

I would like to know if it's possible to change the text alignement in function of the device ?

For example text align right on desktop and left on mobile ? 
The same for image ? (right on desktop and center on mobile)

Thank you

**Comment by ngarnier** [comment]
Hey @mdrick, it's not possible to achieve this with MJML at the moment.

the issue with such a feature is that it would rely on media queries which are far from being supported everywhere. Except if you're thinking of an alternative method to achieve that without media queries?

**Comment by ngarnier** [comment]
Hello @mdrick, media queries are now supported in [v3.3.0 (now in beta)](https://github.com/mjmlio/mjml/releases/tag/3.3.0-beta.3). Feedback welcome! 

Here's an example of implementation: https://mjml.io/try-it-live/ByORGdDdg

PS: be careful, media queries are far from being supported in every email clients

**Comment by littlbr** [comment]
Hi,

This technique is perfect to hide blocks of text.
It cannot be applied to images or entire columns or sections though.
Any idea how this could be applied to images?

Thanks!

**Comment by ngarnier** [comment]
Hey @littlbr, indeed for images. You can use the same approach as text for sections, it really depends on what you want to achieve. Here's an example: https://mjml.io/try-it-live/HJQpgQ2Fl

```
<mjml>
  <mj-head>
    <mj-style>
      @media all and (max-width: 480px) { 
        *[style*="#999"] { 
          display: none!important; 
        } 
        *[style*="#444"] { 
          background: #88f!important; 
        } 
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container>

      <mj-section background-color="#999">
        <mj-column background-color="#eee">
          <mj-text>Let's make this section disappear!
          </mj-text>
        </mj-column>
      </mj-section>

      <mj-section background-color="#444" padding="10px">
        <mj-column background-color="#eee">
          <mj-text>Let's change the background on this one!
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by littlbr** [comment]
Of course. I feel dumb :)
Thanks @ngarnier !

**Comment by littlbr** [comment]
Only problem is:
Gmail seems to ignore tag[attribute="xxx"] selectors...
Is there an ongoing discussion for or against adding the "class" attribute to mj-column, mj-text, mj-image, ... ?

**Comment by ngarnier** [comment]
No worries! This is something we're thinking of but trickier than it seems: one MJML element doesn't equal only one HTML element.

**Comment by littlbr** [comment]
OK, I get that Thanks.
Maybe something simpler as a specific attribute to hide entire blocks under 480px could be easier to implement?
mobile-hidden="true"

**Comment by ngarnier** [comment]
MJML v3.3.0 is out, fixing this issue! It's now easy to achieve this behaviour using media queries. Thanks for submitting, it's great new feature for MJML.

To install: `npm install mjml`

**Comment by nuthinking** [comment]
Where can I find details about how to handle this?

**Comment by kmcb777** [comment]
Hi @nuthinking, Gmail now supports media queries almost everywhere except on Gmail Android with Non Gmail Account

Here is a small example : 
```
<mjml>
  <mj-head>
    <mj-style>
      @media screen and (min-width: 480px) {
        .aligned div {
        	text-align: left !important;
        }
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text css-class="aligned" align="right">Hello</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
Here the text will be right-aligned on mobile, left on desktop.
First you define the behavior for mobile, and then you use media queries to specify the behavior on desktop (because media queries have better support on desktop)
You give a css-class to your element, and thanks to this you can target the element you want in the media query.
