### ISSUE TITLE
Google inbox and mj-column width attr with

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#380]
Hi.
I have simple mjml:
```
                <mj-section padding-top="0">
                    <mj-column width="30%">
                        <mj-image width="132"
                                  src="image.png"
                                  href="url" padding="20 0"></mj-image>
                    </mj-column>
                    <mj-column width="70%">
                        <mj-text padding="0">
                            <ul>
                                <li>
                                    blablabla
                                </li>
                                <li>
                                     blablabla  blablabla
                                </li>
                            </ul>
                        </mj-text>
                    </mj-column>
                </mj-section>
```

In mail.google.com is ok: http://pix.toile-libre.org/upload/original/1473094382.png
But in inbox.google.com is problem: http://pix.toile-libre.org/upload/original/1473094432.png
Columns are not working with attr `with` in `%`.

If I set `witdh=200` and `width=400` I get the same problem.

In google chrome debug panel I see that:
```<div aria-labelledby="mj-column-per-30" style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;width:100%">```
If I change width:100% to value I need then all are correct.

Please, fix this problem.

**Comment by ngarnier** [comment]
Thanks for opening this issue @liminspace. We're actually aware of Google Inbox rendering the mobile version of MJML emails, unfortunately we can't find any easy fix, we would appreciate some help if you can bring some.

This issue is followed here: https://github.com/mjmlio/mjml/issues/40 so I'll close this one to keep things in one place.
