### ISSUE TITLE
Raw rendering not working when includes are used

### ISSUE THREAD

**Issue by FdezRomero** [mjmlio/mjml#381]
`<mj-raw>` is rendering tags inside the node when it shouldn't, when `<mj-include>` is also used. It may be a related regression from issue #25 .

**Reproduction Steps:**

  1. Create 3 new MJML files:

**`header.mjml`:**
```
<mjml>
  <mj-body>
    <mj-container>
``` 

**`example.mjml`:**
```
<mj-include path="header.mjml" />

<mj-raw>
  <% if (undefined) {} %>
</mj-raw>

<mj-section>
  <mj-column>
    <mj-text>Example</mj-text>
  </mj-column>
</mj-section>

<mj-include path="footer.mjml" />
```

**`footer.mjml`:**
```
    </mj-container>
  </mj-body>
</mjml>
```

  2. Run `mjml -r example.mjml -o example.html`
  3. Check the output at `example.html`

**Expected behavior:**

```
<% if (undefined) {} %>
```

**Observed behavior:**

```
<% if="" (undefined)="" {}="" %="">
```

**MJML version:**

2.3.2 (npm) and 2.3.3 (master branch)

**Comment by ngarnier** [comment]
Hey @FdezRomero, it's actually weird that you can render your MJML as you need the `mjml` and `mj-body` tags in the file you're rendering. 

This is most likely what is causing the issue anyway as I rendered this without any change applied to the conditional:
`header.mjml`
```
<mj-section>
  <mj-column>
    <mj-text>My header</mj-text>
  </mj-column>
</mj-section>
```

`example.mjml` 
```
<mjml>
  <mj-body>
    <mj-container>

      <mj-include path="header.mjml" />

      <mj-raw>
        <% if (undefined) {} %>
      </mj-raw>

      <mj-section>
        <mj-column>
          <mj-text>Example</mj-text>
        </mj-column>
      </mj-section>

      <mj-include path="footer.mjml" />
    </mj-container>
  </mj-body>
</mjml>
```

`footer.mjml`
```
<mj-section>
  <mj-column>
    <mj-text>My footer</mj-text>
  </mj-column>
</mj-section>
```

PS: thanks for making an issue so clear and easy to understand with all the needed details.

**Comment by FdezRomero** [comment]
Oh! This makes a lot of sense 😅  I checked the docs but overlooked that it actually works the other way around. It works as expected now, thanks!
