### ISSUE TITLE
mj-divider not centered on outlook

### ISSUE THREAD

**Issue by Grafikart** [mjmlio/mjml#382]
Dividers works on gmail but when opened online with outlook.com they are aligned to the left

`<mj-divider width="100px" border-color="#033242" border-width="1px">`  
## Screenshots :

**Gmail**

![](https://sc-cdn.scaleengine.net/i/e0a048dea0338a71c59d96daf078c544.png)

**Outlook**

![](https://sc-cdn.scaleengine.net/i/782495d3c62cd140043dfb39016b29961.png)
## Email code

**Gmail renders HTML this way**

```
<td style="word-break:break-word;font-size:0px;padding:10px 25px;border-collapse:collapse">
<p style="font-size:1px;margin:0 auto;border-top:1px solid #033242;width:100px;display:block"></p></td>
```

**Outlook this way**

```
<td style="word-break:break-word;font-size:0px;padding:10px 25px;">
<p style="font-size:1px;border-top:1px solid #033242;width:100px;"></p>
</td>
```

**Comment by ngarnier** [comment]
Thanks @Grafikart. Could you also please join the MJML used?

Cheers!

**Comment by Grafikart** [comment]
```
<mjml>
    <mj-body>
        <mj-container>
            <mj-section>
                <mj-column>
                    <mj-text mj-class="title">STORIES FROM THE FIELD</mj-text>
                    <mj-divider></mj-divider>
                </mj-column>
            </mj-section>
        </mj-container>
    </mj-body>
</mjml>
```

**Comment by tcaddy** [comment]
Can you wrap this content in a `<center>` tag to workaround this issue?  I had some text that wasn't centered in MS Outlook (despite declaring it centered in the `<mj-section>` and `<mj-text>` tags).  Wrapping it in the `<center>` tag fixed the issue in Outlook.

**Comment by iRyusa** [comment]
`Outlook.com` remove margin by default... mhh we have to find another way to align without it..

**Comment by iRyusa** [comment]
Ok we have to replace every `margin` by `Margin` and it will fix this..  cf https://github.com/hteumeuleu/email-bugs/issues/6 Silly outlook

**Comment by Grafikart** [comment]
Nice catch 👍

**Comment by iRyusa** [comment]
Small update here, it will no longer be the case in MJML4. So i'm adding it to the 4.0 milestone instead of 3.3.X

**Comment by ngarnier** [comment]
This should be fixed in the latest MJML 4 beta, install with `npm install mjml@next`.
