### ISSUE TITLE
[Bug] Compiler interpret image attribute when using Elixir Eex templating 

### ISSUE THREAD

**Issue by hdcos** [mjmlio/mjml#383]
Hello,

in our blabla.mjml file we have the following line:
`
<mj-image width="25" src="<%= Advitam.s3_root_url %>/images/illustrations/check.png"></mj-image>`

and it compiles to

`
<img alt="" title="" height="auto" src="<%= Advitam.s3_root_url %><![CDATA[/images/illustrations/check.png"
  .......>
`

The link is destroyed because of the `<![CDATA[` inserted in the source attribute. The compiler should not interpret string attribute. It is really problematic since we inject dynamic variable in our mails.

**Comment by ngarnier** [comment]
Hi @hdcos, this is a recurring issue that we can't easily solve due to how our parser works. See for example https://github.com/mjmlio/mjml/issues/369

Could you apply the dynamic before rendering MJML maybe?

**Comment by hdcos** [comment]
No because that would mean to compile the file for every mail sent.
Nevermind we will change it by hand for now

**Comment by iRyusa** [comment]
Hi @hdcos 

The best way to handle this is to make MJML templates available in an Elixir environment, like https://github.com/kolybasov/mjml-ruby for ruby

**Comment by wibleh** [comment]
Hi @hdcos and @iRyusa - not sure if this helps or not but I've been working on the same/similar issue.

My workaround is to replace the > character in the src/href attribute with another character or combination of character and then replace it back to the > character after MJML has worked it's magic.  My gulp task is:
```
gulp.task('make-emails', function () {
    return gulp.src('./resources/emails/templates/**')
        .pipe(mjml())
        .pipe(rename(function(path){
            path.extname = '.blade.php';
        }))
        .pipe(replace('---', '->'))
        .pipe(gulp.dest('./resources/views/emails/'))
});
```

I run the gulp command to create the blade templates for emails from the MUJML templates which is currently working well, though Im sure I'll have to change the --- replacement at some point!
