### ISSUE TITLE
button text not displayed on older outlook versions

### ISSUE THREAD

**Issue by Uelb** [mjmlio/mjml#385]
Hi,

Thank you for this awesome tool !

## Description : 
When using an mj-button like the one provided here : https://mjml.io/try-it-live/components/button/
The text does not display on some email clients.
To find this bug, I simply pasted the HTML provided by the try it live platform on Litmus, without changing anything. And the text did not display on some clients. (I add this problem on my application too so I was trying to reproduce it with the simple version of the example)

The version I'm using is 2.3.1

### Supported :
- Outlook 2000
- Outlook 2002
- Outlook 2003

### Not supported :
- IBM Notes 9
-  Lotus Notes 8.5

## Possible solution
The text is actually displayed if the property display:inline-block is removed from the a tag of the email. I have not seen any other side effect on my litmus test when removing this property (but I can't be sure what it is supposed to do). I tried to remove the display clause and to play with the attribuets of the mj-button tag and eveything worked fine.

**Comment by Tlapi** [comment]
Works well IMO

**Comment by iRyusa** [comment]
We need to test it with multiple button set ( ghost button, round etc etc ) to see if it doesn't break anything. 
I think the `display: inline-block` is (big maybe) here for multiline button ?

**Comment by Uelb** [comment]
Round button works, I already tested. What is ghost and multiline button ? Do you mean a button where the text is long ?

**Comment by iRyusa** [comment]
Ghost button are like so : `border: 2px solid blue` with `background-color: transparent`.
And for multiline button yes, with a long text or in a small column

**Comment by Uelb** [comment]
Ok, let me perform a litmus test to see how it goes

**Comment by Uelb** [comment]
I put the border in both the td and the a tag

On most browser, I got this (but it does not seem to change anything when I add display:inline-block) : 
![screenshot 2016-09-13 10 16 41](https://cloud.githubusercontent.com/assets/1913426/18466241/37141f3e-799b-11e6-844e-90d01d3ed501.png)

On Gmail App Android and a few others :
![screenshot 2016-09-13 10 17 18](https://cloud.githubusercontent.com/assets/1913426/18466263/49c09a7c-799b-11e6-8215-faafefc997b9.png)

On some old browsers (but it's the same without the display:inline-block) :
![screenshot 2016-09-13 10 17 59](https://cloud.githubusercontent.com/assets/1913426/18466288/64e76cd6-799b-11e6-8719-4d869b21abd9.png)

**Comment by Uelb** [comment]
I have problems with multiline text, but the problem is just different whether I put the style or not...
Problems are on older versions of outlook 
On outlook 2002
With inline-block : 
![screenshot 2016-09-13 10 35 34](https://cloud.githubusercontent.com/assets/1913426/18466873/d6dc26b8-799d-11e6-982b-a89fb110b99a.png)

Without inline-block :
![screenshot 2016-09-13 10 37 37](https://cloud.githubusercontent.com/assets/1913426/18466925/1da60834-799e-11e6-945b-ab2515eb9a59.png)

**Comment by iRyusa** [comment]
Well, it looks ok to remove display `inline-block` but we need to fix how outlook 2003 handle multi line :/

**Comment by Uelb** [comment]
When do you think you will release a new version with #387 ?

**Comment by iRyusa** [comment]
I'm testing these changse with our internal "style guide" with lot of custom button ( radius etc ). 

I don't know if we can push a 2.3.4 because next 2.4/3.0 ( not decided yet ) is almost ready to roll out. 

I'll talk with @ngarnier tomorrow about it. Would be great if we find a real fix for outlook 2003 and above on multiline buttons !

**Comment by ngarnier** [comment]
Hey @Uelb, first thanks a lot for providing all of those details and Litmus tests, appreciate that! 

It seems you're not using the last version of MJML in your tests, it might not change the `inline-block` issue but still important as we fixed the ghost buttons in `2.3.3`: https://github.com/mjmlio/mjml/releases/tag/2.3.3. 

As @iRyusa said, we're focusing the next release https://github.com/mjmlio/mjml/pull/321 but will then review your PR to merge it ASAP. Thanks for submitting it!

**Comment by Uelb** [comment]
Indeed, I used the online version of the demo website for the tests, but I use the latest version available for my project. The new release seems really cool (and I'm also waiting for the border on containers :D). Is there a way to release a fork of it for my personal use, because of the way the project is architectured, I can't reference the github repo as an npm package, and I need a "monkey patch" for the buttons on outlook, so I would like to use my branch for now but don't know how without building everything.

**Comment by iRyusa** [comment]
You can maybe juste rebuild your Button.js and include the absolute path in a `.mjmlconfig` ( relative path are fix in next release but until then use the absolute path )

**Comment by Uelb** [comment]
I found the correct style to display multiline button on every litmus supported client. I added a line-height:100%; and it worked correctly and as expected. I included it in my PR

**Comment by iRyusa** [comment]
That's great ! I'll test it today to merge it so 👍
