### ISSUE TITLE
Change order column, desktop to mobile

### ISSUE THREAD

**Issue by RafaelTF** [mjmlio/mjml#386]
Hi,

I want to change the order column in a section on mobile.

For example if I have two sections with two columns:

Desktop:  
c1  c2 
c3  c4 

mobile:  
c1 
c2
c3
c4  
           
....and I would like to have on mobile this:  
c1
c2
c4
c3

It's possible?
Thanks.

**Comment by dalefish** [comment]
Nothing that's going to be concrete in all email clients but this might be an option for you:

https://litmus.com/community/discussions/1500-using-flexbox-in-an-email

**Comment by iRyusa** [comment]
Hi @RafaelTF 

Someone already proposed that on issue #296 , but we didn't find any solutions that can work for every clients. I'm closing this one, but you can follow the discussion in #296 !
