### ISSUE TITLE
Add support for media queries at Yahoo webmail?

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#389]
Hi,

Yahoo webmail has now support for media queries, kind of. They support ```@media yahoo { .. }```

So if we duplicate columns media query, we get a nice result in Yahoo webmail (not working in IE):
```
<style type="text/css">
    @media only screen and (min-device-width:480px){
      .mj-column-per-50,
      * [aria-labelledby="mj-column-per-50"] {
        width: 50%!important;
      }
    }
    @media yahoo{
      .mj-column-per-50,
      * [aria-labelledby="mj-column-per-50"] {
        width: 50%!important;
      }
    }
  </style>
```

Test: https://www.emailonacid.com/app/acidtest/display/summary/yMu5fo5gaxXuPmFp5Vl7yC4KkhBekNQWcT4tpvOFpeiIM/shared

**Comment by iRyusa** [comment]
I don't know why would we add specific yahoo media queries ? The render is already ok in Yahoo Mail ?

**Comment by Tlapi** [comment]
Its not, it display's mobile version, right?

**Comment by iRyusa** [comment]
Not at all
![screen shot 2016-09-13 at 10 40 44](https://cloud.githubusercontent.com/assets/570317/18467035/9ce0e5ba-799e-11e6-87da-d4779677820b.png)

**Comment by Tlapi** [comment]
My bad, tested with old version.
