### ISSUE TITLE
Responsive Image widths not working in iOS devices

### ISSUE THREAD

**Issue by rgbjay** [mjmlio/mjml#39]
When using the mj-image tag, the responsive sizing isn't working on iOS devices. Example litmus screenshot below:

![screen shot 2016-02-10 at 14 47 50](https://cloud.githubusercontent.com/assets/11628707/12950646/199b32b0-d006-11e5-814c-27228ec3319b.png)

**Comment by iRyusa** [comment]
Ok, it's just a `width: 100%` missing on image I'll check with @hteumeuleu if there's no side effect with it

**Comment by iRyusa** [comment]
It should be ok now with width 100% on `1.1.0`
