### ISSUE TITLE
Line-height issue in older Outlooks

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#390]
This simple example is giving troubles:

```
<mjml>
  <mj-body>
    <mj-container background-color="#c0c9cf" containerWidth="600">
      <mj-section padding="0px" layout="normal" background-color="#ffffff" containerWidth="600">
        <mj-column width="100%" containerWidth="600">
          <mj-text padding="10px 20px 10px 20px" color="#2b729e" font-family="Ubuntu, Helvetica, Arial, sans-serif" align="justify" containerWidth="600">
            <h1>DETSKE IHRISKÁ, WORKOUT IHRISKÁ A</h1>
            <h1>OUTDOOR FITNESS PRE OBCE A MESTÁ</h1> </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Please see the test here: https://www.emailonacid.com/app/acidtest/display/summary/jmJiAdXSTHsrCxLIbsFx0YQTgGDKtJdya9XmR23RHsaBX/shared

Why is there default `line-height: 22px` on mj-text? If I remove it it works more or less ok.

**Comment by Tlapi** [comment]
The same without default ```line-height:22px```

https://www.emailonacid.com/app/acidtest/display/summary/Ec4QOvEqQ81vBNkVsNsPkMtVDmbrEFzgYeLmNebzMnwES/shared

**Comment by iRyusa** [comment]
Well it's a good practice to define a line-height inside `mj-text` because some mail client has some crazy default line height ( ex outlook.com has default 130% ). In your example Outlook 2003 looks totally unreadable

**Comment by Tlapi** [comment]
Well, that i have already fixed with conditional CSS `<!--[if lte mso 11]>` for Outlook 2003 and back.

But as you see in my first test, the text is unreadable in Outlook 2003, 2007, 2010, 2013

**Comment by iRyusa** [comment]
That doesn't look really readable to me ( outlook 2003 in your second link )
![72133_005451](https://cloud.githubusercontent.com/assets/570317/18466839/af006fdc-799d-11e6-9adf-fbacf6e000e8.jpg)

I think keeping the line height is fine just add a line-height into your `h1` and it's fine ?

As mentioned above, setting `line-height` is a better practice than let every client doing what they want

**Comment by Tlapi** [comment]
It is not, i have fixed this in other test:
https://www.emailonacid.com/app/acidtest/display/summary/44F4YgLJLM7gzVKqVHTcWv91EteQ6V3mfzBgh8SAFzb5c/shared

Unfortunatly setting `line-height` on every element manually isn't an option for us as we use WYSIWYG to build mjml-text content.

**Comment by iRyusa** [comment]
There's no way to add default style in your WYSIWYG editor ? Like default line height for every `<hn>` ?

**Comment by ngarnier** [comment]
Hey @Tlapi, I'm super curious because you said you use a WYSIWYG to build `mjml-text` content. I would love to know more about how you do it, could you please shoot me an email at nicolas [at] mjml [dot] io so we can discuss? Thanks!

**Comment by bradbaris** [comment]
I've encountered a very similar issue in Outlook 2013, with the `line-height` being squished and/or cropped at the cap line. You could try going into the compiled HTML and replacing every instance of `mso-line-height-rule:exactly;` with `mso-line-height-rule:single;`

**Comment by iRyusa** [comment]
@bradbaris can you explain the difference between `exactly` & `single` ?

**Comment by bradbaris** [comment]
I just looked at my comment there and realize it makes no sense _at all_.

I must've absentmindedly mixed it up with Word's `line-spacing` property, which has `single` and `exactly`. The only valid values for `mso-line-height-rule` are `exactly` and `at-least` (default). By setting it to nonsense, it defaulted to `at-least` and passed anyway...

**Comment by bradbaris** [comment]
So anyway, as hinted above, the closest workaround would be to make sure all html tags inside of `mj-text` have inlined `line-height` (or whatever styles are needed), since they don't inherit all attrs from `mj-text`.

Another fix is to set the enclosing `mj-text` `line-height` to a unitless `1`. After MJML compiles to HTML, it adds in the `px` unit (which you don't want), so you have to remove the `px` after build. Unitless number for `line-height` changes it to a multiple of the element's font size, so `1` would be actual size, and not 130% or other weirdness.

**Comment by iRyusa** [comment]
Closing this one, 3.1 has been released you can simply set a default line-height to `1` as @bradbaris said !
