### ISSUE TITLE
Please proivde instructions for how to use mjml-repo from git checkout

### ISSUE THREAD

**Issue by dennisschaaf** [mjmlio/mjml#391]
Hi,

I'm trying to do some tweaks in a separate branch, but there is an 'installation.sh' that needs to be executed somehow in order to unbundle the mono repo.

My current attempt 

1. Add git repo to package.json 
`+ "mjml": "https://github.com/mjmlio/mjml.git#xsd",`

2. Install package and dependencies
`npm install`

3. Run install script
`cd node_modules/mjml-repo && ./install.sh`

But this doesn't work, the packages don't get linked to the main project.

**Comment by iRyusa** [comment]
You should just clone the repo instead of adding it inside a package.

Just git clone it,  use `install.sh` and then `gulp build` to build when you've done some changes. 

There's a script you can use to test some MJML inside `packages/mjml` called `test.js`

**Comment by dennisschaaf** [comment]
Ok, so if I want to use it from my repo, how do I install this version to my node application then? 
I cloned and did the install and build process, but now I need to install each of the modules somehow.

1. Clone git repo 
`git clone https://github.com/mjmlio/mjml.git
cd mjml
git checkout xsd`

2. Install module dependencies
`./install.sh`

3. Build the modules
`gulp build`

4. Install the modules to your repository
`?? Should we use npm link here?`

**Comment by iRyusa** [comment]
`install.sh` should do all `npm link` for you. You can just test the `test.js` as mentioned above

**Comment by iRyusa** [comment]
Hi ! 

Is this ok for you @dennisschaaf ?

**Comment by iRyusa** [comment]
Closing this one, for next version i've added some information when running the `install.sh`
