### ISSUE TITLE
[Feature Request] Adding background colors to mj-columns 

### ISSUE THREAD

**Issue by arthurkatz** [mjmlio/mjml#393]
Hi there! 

Adding a background-color attribute to columns would really help (although mj-style should offer a workarround to this problem very soon). 

I'm facing this problem over and over, currently I go in the dirty HTML file and change it manually. 

Best,

**Comment by iRyusa** [comment]
Hello @arthurkatz 

I don't really understand your issue, `mj-container` `mj-section` and `mj-column` already have a `background-color` property ?

**Comment by arthurkatz** [comment]
i don't why I was sure background-colors where not supported on columns. 
sorry my bad
