### ISSUE TITLE
Would you be interested by a mjml-chart chart component ?

### ISSUE THREAD

**Issue by FGRibreau** [mjmlio/mjml#396]
Hello everyone!

A friend of mine ( @wand ) told me of the goods of mjml yesterday night and thus here I am! I'm currently on an online chart generator (just like the old unsupported google image-charts) that could perfectly fit as a [mjml chart component](https://image-charts.com/). 

@iRyusa @lohek would be interested to merge a PR for it?

**Comment by FabioFleitas** [comment]
Just wanted to say that your product looks pretty slick. I'll see how we could potentially use it at my startup.

**Comment by FGRibreau** [comment]
@FabioFleitas thanks! Don't hesitate if you have any bug report or feature requests, we are eager to improve it!

**Comment by ngarnier** [comment]
Hey @FGRibreau, thanks for the kind words! image-charts looks neat, we'd definitely love a PR for a chart component 👍

**Comment by FGRibreau** [comment]
@ngarnier awesome! I'll submit a PR in the following days! :)

**Comment by FGRibreau** [comment]
@ngarnier done!

**Comment by ngarnier** [comment]
hey @FGRibreau, amazing, thanks! Let's keep the discussion on the PR now.
