### ISSUE TITLE
Try It Live Issues

### ISSUE THREAD

**Issue by aarmand** [mjmlio/mjml#397]
I'm going through the "Get Started" https://mjml.io/getting-started/2 materials and the experience doesn't seem be right. Note the screen shot below where I have entered the text from part one. The try-it-live editor is not updating. When I can get it to update by changing a word or two, its super slow. I'm on a Mac El Capitain and using a chrome browser.
![screen shot 2016-09-24 at 10 08 40 am](https://cloud.githubusercontent.com/assets/2370391/18807108/653fb88a-823f-11e6-95cf-ee8bc7b1b572.png)

**Comment by ngarnier** [comment]
Hey @aarmand, nice to see you here :-). 

The getting started focuses on playing with key components and actually strips out parts of the basic structure (see [here](https://mjml.io/documentation/#overview)). Your MJML code is missing the `mjml`, `mj-body` and `mj-container` tags hence the issue you're facing, sorry for the confusion! 

This is the valid structure: 
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>Some Text</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by ngarnier** [comment]
I'm closing this one, feel free to reopen if my answer didn't solve your issue!

**Comment by aarmand** [comment]
Thank you, sir. Will jump back into it.
