### ISSUE TITLE
no way to apply mj-class to standard html

### ISSUE THREAD

**Issue by thepuzzlemaster** [mjmlio/mjml#398]
Unless I'm missing something, there seems to be no way to apply global styles a-la mj-class to any html that is included as part of a different mj component.

i.e.
`<mj-text><a mj-class="link" href="#">Link Text</a></me-text>`

I need to apply the styles inline to the <a> tag because they won't cascade in otherwise. However, it appears that mj-class styles are only applied to mj components and not to any html that was added inside of that component.

It seems like this might be covered by https://github.com/mjmlio/mjml/issues/81, but I want to make sure there's no way to do this currently, and that this would be covered by the above mentioned issue.

**Comment by dalefish** [comment]
You can drop standard CSS classes in to the body with mj-raw within
mj-container

**Comment by thepuzzlemaster** [comment]
Where would those classes be defined? Is there an example of this anywhere linkable? I'm not exactly following how the styles would get applied to the <a> tag here.

Also, just to be clear, my example above assumes the following exists in the `<mj-head>`

````
<mj-head>
  <mj-attributes>
    <mj-class name="link" color="#999999" text-decoration="none" />
  </mj-attributes>
</mj-head>
````

**Comment by dalefish** [comment]
<mjml>
<mj-head>
<mj-title>Email Title</mj-title>
<mj-attributes>
<mj-class name="someclass" ....> 
</mj-attributes>
</mj-head>
<mj-body>
<mj-container>
<mj-raw>
<style type="text/css">
replicate your classes here
.chosen_class{}
</style>
</mj-raw>
<mj-section>
<mj-column>
<mj-text>
<div class="chosen_class">...</div>
</mj-text>
</mj-column>

</mj-section>
</mj-container>
</mj-body>
</mjml>

**Comment by thepuzzlemaster** [comment]
Okay, gotcha. Thanks for the example.

**Comment by iRyusa** [comment]
`mj-class` is design for mj-attribute on mj-element not on HTML elements, as mentioned mj-style come soon and allow you to write plain css in it
