### ISSUE TITLE
Hero height not translating

### ISSUE THREAD

**Issue by dalefish** [mjmlio/mjml#399]
```
<mj-hero
		mode="fluid-height"
        background-width="640px"
        height="366px"
        background-url="header.jpg"
        background-color="#e95625"
        padding-top="30px">
```

Compiles to:

`<v:image xmlns:v="urn:schemas-microsoft-com:vml" croptop="0" cropbottom="0" style="width:480pt;height:0pt;position:absolute;top:0;mso-position-horizontal:center;border:0;z-index:-3;" src="header.jpg" />`

Note the 0pt height, Outlok 2007+ will not show this element with 0 height.

**Comment by iRyusa** [comment]
You need to use `background-height` not `height` cf documentation : 
`The height attribute is required only for the fixed-height mode`

https://mjml.io/documentation/#mjml-hero
