### ISSUE TITLE
I wish I finally would have found a single source for text/html AND text/plain

### ISSUE THREAD

**Issue by pke** [mjmlio/mjml#401]
I was about to invent my own DSL for creating HTML and Text Email from a single source.
Then I got tipped of to mjml. I thought I found it. And you even have invoice items already :)

But then I understood this lib only transpiles to text/html and not to text/plain also.
Would you consider that? I guess since it uses reactjs under the hood its not so easy to compile to text or markdown instead of html.

Anyway. Maybe I could set up a text/plain transpiler on top of the markup you invented here. Anybody think that would be a good idea?

**Comment by ngarnier** [comment]
hey @pke!

Thanks for the suggestion. We've discussed about this before but we think the main role of MJML is to generate responsive HTML and that it would be really difficult to manage a good text conversion within MJML. 

For HTML to text, there are still a few packages on `npm` providing a HTML to text conversion. 

If you want to create a transpiler that would generate text from MJML though, that would be awesome and we would totally feature it!

**Comment by brasilikum** [comment]
I wrote a small bash script to do `mjml -> html -> txt` and it works fine.
https://gist.github.com/brasilikum/3cd515bad5541ca6c76873faf10445c2

You can customise the output a lot:
https://www.npmjs.com/package/html-to-text
