### ISSUE TITLE
Border attribute for mj-section or mj-container

### ISSUE THREAD

**Issue by afdallah-war** [mjmlio/mjml#403]
Hi, I've been using this framework a lot of time and I love this framework so much. 
It is possible to use border attribute to the mj-section / mj-container. I have read the documentation but it said it is not possible. hope it will be added in the next update. Thank you so much

**Comment by dalefish** [comment]
Border on mj-section & mj-column is coming in the next major release 3.0.0.
https://github.com/mjmlio/mjml/pull/321

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
Hi there,

There's already an issue on that so I close this one : #92

I don't know if we can have border on container atm, due to how hard it is to have border on container without breaking the responsive.
