### ISSUE TITLE
Suggestion: configurable alignment for divider

### ISSUE THREAD

**Issue by zauni** [mjmlio/mjml#407]
Hey MJML Team,
first of all: thanks for this awesome framework :) Really great job!

And now the problem: I want to have a 80px wide divider left aligned, which is not possible today. Would it be a good idea to let the margin attribute be configurable? like this

```
<mj-divider margin="0" width="80" />
```

Or could you guide me to the right direction on how to extend the mj-divider component with my own component which has this attribute? I already tried to extend the Divider class and overwrite the getStyles method, but didn't work out as expected. Now I just copied the Divider class and put the margin attribute on it, but this is not so nice solution.

And if I want to make a pull request for the original divider class, what's the best way to support "margin" and "margin-(left|right|top|bottom" attributes at the same time? Is there a utility method for this kind of stuff?

Thanks for your help!

**Comment by ngarnier** [comment]
Hey @zauni, 

Thanks for the feedback and for reporting this issue! Here are 2 workarounds to achieve what you want:

1. Add some padding to force the divider to go left, using `padding-right`
2. Use columns and insert the divider in the left column of your section

Regarding pull-requests to add support for new attributes, here is an example of a similar contribution that could help you: https://github.com/mjmlio/mjml/pull/298 (but here, I don't think we should add `margin` as there is `padding` already).

**Comment by zauni** [comment]
Hi @ngarnier,
thanks for the reply and your 2 suggestions. The first workaround is unfortunately not a good solution on smaller screens (< 600px) because a horizontal scrollbar appears.

example:
```html
<mj-divider border-color="blue" border-width="3px" width="80px" padding-right="495px" />
```

with the following code it is working okay on desktop, but not perfect on mobile (just 32px wide on 320px screen width):
```html
<mj-divider border-color="blue" border-width="3px" width="100%" padding-right="82%" />
```

The column workaround has almost the same problems with the percentage widths, but it is 100% wide on smaller screens.

So maybe an option to switch off the auto margins wouldn't be so bad? :)

**Comment by ngarnier** [comment]
Regarding the columns technique, you have to use `mj-group` (https://mjml.io/documentation/#mjml-group) to prevent the columns from stacking on mobile. 

We'll explore the auto margins, in the meantime let met know if it helps!

**Comment by zauni** [comment]
@ngarnier okay, with the group tag it's better, but also too narrow an small screens:

```html
<mj-section background-color="#fff">
    <mj-group>
        <mj-column width="22%">
            <mj-divider border-color="blue" border-width="3px" padding="0 25px" />
        </mj-column>
        <mj-column width="78%">

        </mj-column>
    </mj-group>
</mj-section>
```

In the meantime I use my own component, which is a copy of the original divider with just the margin turned off. I would make a pull-request, but I have a bug in Outlook 2013 where the divider is centered, even with `margin: 0;`... 🐛 So I have to investigate a bit more.

**Comment by iRyusa** [comment]
Hi there @zauni 

Can you provide a quick screenshot of what you want to achieve with this ? I'll take a look at it

**Comment by zauni** [comment]
Hi @iRyusa, here is the screen:

![mjml-divider-screenshot](https://cloud.githubusercontent.com/assets/663845/19508773/5bf43864-95db-11e6-86ae-f99d8d9f0bb2.png)

My copy of the divider is resetting the margin on the `<p>` and changes the `align` attribute to "left" on the wrapping `<table>`.

**Comment by iRyusa** [comment]
I see ! I'll take a look at it ! Thanks for the screenshot

**Comment by blaugueux** [comment]
👍  for just resetting the margin and changing the parent table align

**Comment by afewremarks** [comment]
@zauni did you get your component working?  I am trying to do the exact same thing.

**Comment by zauni** [comment]
@afewremarks I made a gist of my version of the divider. But beware that this worked for v3.0.2 of MJML, I don't know if it is working in the newest MJML version. Basically it was a copy of the original divider with small additions.
https://gist.github.com/zauni/037782cf3b75037320e6b72b5b1ef6b2

**Comment by afewremarks** [comment]
@zauni thanks for sharing this.  I was having a bit of trouble getting it working...Any way I found a native way to do it if you need it or anyone else does.  I just created a column group one with a 10% width and one with a 90%.  Added a text element with a background color.  then you just have to play with the heights and paddings a little:

`          <mj-section  padding-left="25px" padding-bottom="10" padding-top="0" >
            <mj-group>
                  <mj-column width="10%"  padding-top="0" padding-bottom="0" background-color="#005393">
                    <mj-text height="5px" padding-top="0" padding-bottom="0"></mj-text>
                  </mj-column>
                  <mj-column width="90%" padding-top="0" padding-bottom="0" background-color="#fff">
                  </mj-column>
            </mj-group>
          </mj-section>`

**Comment by vielhuber** [comment]
This does not work inside a column.

Simply use an image. Here is an example for a white colored divider:

```
<mj-image        		src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII="
align="left"
width="50%"
height="1px"
/>

You can generate any color with http://png-pixel.com/

**Comment by bastienrobert** [comment]
I think the simplest way to align left is:
```
<mj-divider mj-class="divider" css-class="divider"/>
```
```
<mj-class name="divider" width="40px" margin="0"/>
```
and 
```
.divider {
  display: inline-block;
}
```

**Comment by dakur** [comment]
I've just ran across this issue as well.
