### ISSUE TITLE
mj-columns losing padding in mobile

### ISSUE THREAD

**Issue by deanorhan** [mjmlio/mjml#408]
I have two columns, one 15% the other 85%, in a mj-group so they'll stick together instead of flowing underneath each other when rendered on mobile. However in the gmail app on Android the padding between the columns seems to go down to zero.

<img width="470" alt="screen shot 2016-10-14 at 11 01 24 am" src="https://cloud.githubusercontent.com/assets/5548298/19381853/d73f9a2c-91fd-11e6-82c6-d3942360e2d0.png">

**Comment by iRyusa** [comment]
Hi there can you provide some code so we can investigate. 
I think there's an overflow from the images, so (maybe) that's why the padding doesn't work as expected

**Comment by deanorhan** [comment]
Here's pretty much what I'm using for that line

	  <mj-section align="left" background-color="#ffffff" padding="5px 0">
        <mj-group>
          <mj-column width="15%">
            <mj-image width="80" src="http://a2.tbn.bidorbuy.co.za/image/fetch/dpr_1.0,f_auto,t_btbnl/https://cdn.shopify.com/s/files/1/0280/5548/products/Brew-Tool-Tamping-Mat-Black-Plain.jpg%3Fv=1443021843" />
          </mj-column>
          
          <mj-column width="85%">
            <mj-text>
              <a style="text-decoration: none;" href="http://www.localhost.co.za/item/228137738/Brew_Tool_Tamping_Mat.html">Brew Tool Tamping Mat</a>
            </mj-text>
            
            <mj-table>
              <tr>
                <td align="left" style="text-align: left; font-size: 14px; color: #939699;">Ends 26 Oct 12:00</td>
                <td align="right" style="text-align: right; font-weight: bold;">R 300</td>
              </tr>
            </mj-table>

          </mj-column>
        </mj-group>
      </mj-section>

**Comment by iRyusa** [comment]
Mhhh, trying it inside the try it live it looks like the padding is bigger than the container, so the image is not rendered at all in my browser with a mobile width.

Your column is set to 15% of the mobile width, that's really really small. Image has a default 10/25px padding so it cannot be displayed. Either add `padding="0"` on your `mj-image` or add some width to the image's column.
