### ISSUE TITLE
Ability to define how column behave in mobile

### ISSUE THREAD

**Issue by rgbjay** [mjmlio/mjml#41]
It would be cool to be able to assign different widths for elements for different breakpoints.

For example if I have three columns on desktop but I want them to be three 1 columns on mobile.

Maybe with m-width and t-width attributes that compile to media queries?

**Comment by iRyusa** [comment]
I may suggest a different approach here, in my opinion in a future we should be able to do this kind of thing:

```xml
<mj-section>
  <mj-group>
    <mj-column width="50%" />
    <mj-column width="50%" />
  </mj-group>
  <mj-group>
    <mj-column width="50%" />
    <mj-column width="50%" />
  </mj-group>
</mj-section>
```

That should render as 2 per 2 on mobile and 4 * 25% column

**Comment by rgbjay** [comment]
Yeah that would work. The ability to have that option, however it is achieved, would be great

**Comment by jsit** [comment]
What about something like this:

```
<mj-section wrap="480px">
  <mj-column />
  <mj-column />
</mj-section>
```

Which would mean that below 480px, the columns would wrap into a single "column"?

@iRyusa's example could then just be:

```
<mj-section wrap="480px">
  <mj-column width="50%" />
  <mj-column width="50%" />
</mj-section>
<mj-section wrap="480px">
  <mj-column width="50%" />
  <mj-column width="50%" />
</mj-section>
```

Other suggestions for the `wrap` attribute: `wrap-at`, `wrap-under`, `single-col`, `break`, `1col`...

Maybe `wrap="mobile"` could re-use a more globally-defined mobile breakpoint.

**Comment by jsit** [comment]
Or would it make more sense to have this as an attribute of the `<mj-column>` elements? E.g.:

```html
<mj-section>
  <mj-div width="50%" lt480-width="100%">
    <mj-column width="50%" lt480-width="100%" />
    <mj-column width="50%" lt480-width="100%" />
  </mj-div>
  <mj-div width="50%" lt480-width="100%">
    <mj-column width="50%" lt480-width="100%" />
    <mj-column width="50%" lt480-width="100%" />
  </mj-div>
</mj-section>
```

**Comment by iRyusa** [comment]
I'm not a big fan of `mj-div`, name is too generic. It will mislead on what the component wants to achieve. 

But I like the idea behind it, I'm still not sure how we can implement it yet

**Comment by jitendravyas** [comment]
Has anyone started working on this feature?

**Comment by ngarnier** [comment]
Hey @jitendravyas, yes, it is actually under development

**Comment by iRyusa** [comment]
Hey there, I have developed `mj-group` you can check it on my PR #281 !

**Comment by ngarnier** [comment]
Hey guys, the amazing #281 has been merged so I'm closing the issue, huge kudos to @iRyusa! 

The documentation is available [here](https://mjml.io/documentation/#mjml-group).

**Comment by AnthonyLai1001** [comment]
still <mj-group> look not working on gmail app, can you check this @ngarnier , thanks 
![photo_2019-03-01_13-42-45](https://user-images.githubusercontent.com/12264291/53621114-0282dd80-3c28-11e9-9ce6-8eaa24699198.jpg)
p/s: outlook, gmail it's ok, but in gmail app not ok.

**Comment by kmcb777** [comment]
Hi @AnthonyLai1001 did you minify the html ? It's needed for gmail app
