### ISSUE TITLE
mjml-social: base-url not applied to custom icons

### ISSUE THREAD

**Issue by blaze33** [mjmlio/mjml#416]
With such a definition:

```
<mj-social
    display="custom-network"
    base-url="http://static.example.com/"
    custom-network-icon="icon.png" />
```

The icon is rendered as `<img alt="custom-network" height="20" src="icon.png">` and not with `src="http://static.example.com/icon.png"` which was my expectation at first.

I'm not sure if this should be considered as an issue because if you naively used base-url for custom icons paths it would break the standard icons if you're not hosting `facebook.png/twitter.png/google-plus.png/pinterest.png/linkedin.png/instagram.png` at the same time.

At first I thought to apply base-url to custom icons at https://github.com/mjmlio/mjml/blob/master/packages/mjml-social/src/index.js#L230:  

```
-      icon: mjAttribute(`${platform}-icon`)
+      icon: mjAttribute('base-url') + mjAttribute(`${platform}-icon`)
```

And update the doc to say you have to host facebook.png/etc. at the base-url otherwise it's broken.

But then you would not be able to provide a full path for a custom icon without having it prefixed by the default base-url (`https://www.mailjet.com/images/theme/v1/icons/ico-social/`) unless you set `base-url=""`.

Sooo:
1. maybe just update the doc to say you have to provide full paths for custom icons and host the standard icons if you ever change `base-url` ?
2. or apply base-url to custom icons and say you must set base-url if you use custom icons (and host facebook.png/etc. once base-url is changed from the default) ?

Also custom network attributes trigger the validator:
`Line 3 (mj-social) — Attributes custom-network-content, custom-network-href, custom-network-icon-color, custom-network-icon are illegal`
But that's another issue.

**Comment by iRyusa** [comment]
Hi @blaze33 !

Yes, base-url is only for default icons. I think we'll have to update to reflect this behaviour.

For validation, we have plans on 3.1 to add some feature on validation that allow wildcards attributes and may be value restriction too ! But that's not for today 😄

**Comment by blaze33** [comment]
Okay, thanks and good luck for the next release !

We use mjml at work at Smart Impulse and it really helped us a lot to have such a good framework available :)

**Comment by iRyusa** [comment]
Doc has been updated so I'm closing this ! 

Doc on website will be up to date soon.
