### ISSUE TITLE
EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file

### ISSUE THREAD

**Issue by Manaus** [mjmlio/mjml#417]
Hello,  
I'm getting this error in transpiling a file thus done: 

    <mjml>
        <mj-text>Hello</mj-text>
    </mjml>

Same replacing `<mjml>` with `<mj-body>`.
This is the command I'm using: `mjml -r index.mjml`. The package version is 3.0.0.

**Comment by dalefish** [comment]
Hi Manaus,

You don't have enough elements.

You need: mjml->mj-body->mj-container->mj-section->mj-column->mj-text

rather than just

mjml->mj-text

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ngarnier** [comment]
Indeed @Manaus, as @dalefish said your markup is missing elements. I'm closing as his answer should fix your issue, feel free to reopen if not the case!
