### ISSUE TITLE
Refactor the MJML CLI to make it independent from MJML 

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml#418]
For a better management of MJML and to avoid installing MJML globally, we'll make the CLI a standalone. This means that, once the refactor is done: 
- `mjml-cli` will be an independent package and generally be installed globally. It will be able to interact with different versions of MJML.
- `mjml`  should be installed locally, in specific folders. This will make it possible to have different versions of MJML on a same machine.

**Comment by FGRibreau** [comment]
> mjml-cli will be an independent package and generally be installed globally. It will be able to interact with different versions of MJML.

Please, also add support to require custom-components with mjml-cli :)

**Comment by iRyusa** [comment]
@FGRibreau It's already available with `.mjmlconfig` !

**Comment by FGRibreau** [comment]
@iRyusa yes, but it must be in the CWD where the binary run. A "--require" option at the CLI level would be more convenient

**Comment by ngarnier** [comment]
Hello, 

Having a global CLI with local dependencies would have led to other issues, so we decided to keep the CLI local as well. However, we now recommend installing MJML locally: https://github.com/mjmlio/mjml#installation
