### ISSUE TITLE
Double units in VML background

### ISSUE THREAD

**Issue by dalefish** [mjmlio/mjml#422]
MJML:
`<mj-section background-color="transparent" background-url="header-bg.jpg">`

Compiled VML:
`<v:rect xmlns:v="urn:schemas-microsoft-com:vml" fill="true" stroke="false" style="width:640pxpx;">`

For some reason the width in the above code has double units: 640**pxpx**

**Comment by iRyusa** [comment]
Hi @dalefish 
Will be fixed in next release !

**Comment by ngarnier** [comment]
This is fixed in 3.1.0, thanks!
