### ISSUE TITLE
mj-column vertical-align default is not top

### ISSUE THREAD

**Issue by quinncomendant** [mjmlio/mjml#425]
The [mjml-column docs](https://github.com/mjmlio/mjml/tree/master/packages/mjml-column) say the default attribute for `vertical-align` is `top` but that's not true. The HTML output on a default usage of `<mj-column>`:

    <table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
      <tbody>
        <tr>
          <td style="word-break:break-word;font-size:0px;padding:0px;" align="left">
            <div style="cursor:auto;color:#000000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;">
              TEST
            </div>
          </td>
        </tr>
      </tbody>
    </table>

When explicitly specifying it with `<mj-column vertical-align="top">`:

    <table role="presentation" cellpadding="0" cellspacing="0" style="vertical-align:top;" width="100%" border="0">
      <tbody>
        <tr>
          <td style="word-break:break-word;font-size:0px;padding:0px;" align="left">
            <div style="cursor:auto;color:#000000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;">
              TEST
            </div>
          </td>
        </tr>
      </tbody>
    </table>

**Comment by iRyusa** [comment]
Hi ! 
Did you update mjml to 3.0.1 ? It should have been fixed in it.

**Comment by quinncomendant** [comment]
$ mjml --version
    3.0.1

**Comment by tomgenoni** [comment]
@quinncomendant Check your styles panel. It's not written into the `style` attr on the element but it is being applied/inherited in the CSS. 

![screen shot 2016-10-21 at 3 29 10 pm](https://cloud.githubusercontent.com/assets/1171072/19613719/275f2fcc-97a3-11e6-8a7d-d31c5c2bb0ac.png)

And that cascades down to the `<td>`.

![screen shot 2016-10-21 at 3 30 04 pm](https://cloud.githubusercontent.com/assets/1171072/19613737/44769b36-97a3-11e6-9cba-42d52ca813f0.png)

That is working for me as of 3.0.1

**Comment by iRyusa** [comment]
@tomgenoni is right, I forgot it's applied by default only on the div. I'm closing this then
