### ISSUE TITLE
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <td>. See MJMLElement > td > Invoice > MJMLElement > tr.

### ISSUE THREAD

**Issue by cmnstmntmn** [mjmlio/mjml#426]
hey, i'm trying the decoumentation example of the invoice

`mjml -w order.mjml -o order.html` i get this output

the version i use is `3.0.1`

---

<img width="645" alt="screen shot 2016-10-23 at 22 08 05" src="https://cloud.githubusercontent.com/assets/2312755/19628749/6e75eb64-996d-11e6-802a-24ce7d78e046.png">

**Comment by ngarnier** [comment]
Thanks for reporting the issue @cmnstmntmn, we'll investigate!

**Comment by cmnstmntmn** [comment]
this is not happening in the Mjml App

**Comment by iRyusa** [comment]
This should be fixed in 3.0.2, sorry about that

**Comment by iRyusa** [comment]
Invoice is now fixed in 3.0.2 🎊 !
