### ISSUE TITLE
Attribute background-position is illegal

### ISSUE THREAD

**Issue by nikmauro** [mjmlio/mjml#428]
The compiler return this notice and the background position not working

#Line 5 (mj-section) — Attribute background-position is illegal

```
<mj-section background-color="#000001" background-position="center center" background-url=".../logo.png"  background-repeat="no-repeat">

**Comment by iRyusa** [comment]
Hi there @nikmauro 

Background-position is not a valid attribute in MJML. As https://www.campaignmonitor.com/css/ state, it's not very well supported, so we don't allow it to `mj-section`
