### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined in validChildren.js

### ISSUE THREAD

**Issue by vbraun** [mjmlio/mjml#429]
I have a self-written plugin that worked with mjml 2.x, but apparently doesn't validate now. That might be ok but the error message is broken, so I don't see where the error is.

~~~~
/home/vbraun/foo/node_modules/mjml-core/node_modules/mjml-validator/lib/rules/validChildren.js:50
    return (0, _ruleError2.default)(ChildComponent.tagName + ' cannot be used inside ' + tagName + ', only inside: ' + ChildComponent.parentTag.join(', '), child);
                                                                                                                                               ^

TypeError: Cannot read property 'join' of undefined
~~~~
This is with mjml version 3.0.1 from npm

**Comment by iRyusa** [comment]
Hi there @vbraun 

Some parameters are now mandatory on a Component to be MJML3 compliant.

- `ParentTag` is an array of tagName that describe in what mj-element your Component can be used. Like `mj-text` can only be found inside a `mj-hero-content` and a `mj-column`.
- `defaultMJMLDefinition` must have every `mjAttribute` that your Component accept. You can set them to `null` if you don't need a default value.
