### ISSUE TITLE
Watch changes crash

### ISSUE THREAD

**Issue by laurent-bientz** [mjmlio/mjml#43]
Hello,

The --watch option seems to crash after some saves on my mjml file.

`> mjml --watch test.mjml --output test.html`

produces:

> Error: [MJMLError] EmptyMJMLError: Null element found in mjmlElementParser at MJMLError.Error (native)
    at new MJMLError (C:\[...]\AppData\Roaming\npm\node_modules\mjml\lib\Error.js:24:85)
    at Object.mjmlElementParser (C:\[...]\AppData\Roaming\npm\node_modules\mjml\lib\documentParser.js:24:13)
    at documentParser (C:\[...]\AppData\Roaming\npm\node_modules\mjml\lib\documentParser.js:65:22)
    at mjml2html (C:\[...]\AppData\Roaming\npm\node_modules\mjml\lib\mjml2html.js:49:52)
    at C:\[...]\AppData\Roaming\npm\node_modules\mjml\lib\cli.js:88:12

No problem with:
`> mjml -r test.mjml --output test.html`

I'm using Node v4.3.0, NPM v2.14.12 & MJML v1.0.3

Thank you

**Comment by GuillaumeBadi** [comment]
Hey @laurent-bientz !

This should be solved by the last release. Can you make sure it works on your side?

Regards,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hey @laurent-bientz !

This is probably when you save the file with an empty body, I will try to make the error appear without crashing for the next release tomorrow!

Regards,
Guillaume

**Comment by patrickfweston** [comment]
@GuillaumeBadi : I believe you're correct about it being empty tags. I can confirm that using `--watch` with the following causes an error:

```
<mj-body>
  <mj-section>
    <mj-column>
      <mj-text align='left'></mj-text>
    </mj-column>
    <mj-column>
      <mj-text align='right'></mj-text>
    </mj-column>
  </mj-section>
</mj-body>
```

However, adding text to the _mj-text_ element fixes the problem and an error is not thrown. The error I'm receiving is different though:

```
Warning: React.renderToStaticMarkup is deprecated. Please use ReactDOMServer.renderToStaticMarkup from require('react-dom/server') instead.
Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.
```

**Comment by laurent-bientz** [comment]
Hello and thank u for your feedback.

I can't test today but to reproduce the glitch, just put some spaces in your file.

For me, it's crashed and no memories about an empty `<mj-body>` or `<mj-text>`.

Btw, i can remember that empty `<mj-text>` also crashed with basic command line (`mjml -r test.mjml --output test.html`), so I don't think it's linked to the same pb, maybe i'm wrong.

I'll check next mon

**Comment by iRyusa** [comment]
Empty `mj-text` is now fixed ! Please reopen if you're still having the issue with `1.2.0`

**Comment by GuillaumeBadi** [comment]
Plus the client won't crash anymore and simply log the error message if any :smile:

**Comment by iRyusa** [comment]
:+1:
