### ISSUE TITLE
MJ-Social custom Icon not working

### ISSUE THREAD

**Issue by dawidvdh** [mjmlio/mjml#432]
Hi

For some reason I can't get the custom social networks working at all.

```
<mj-social 
            display="custom-network" 
            custom-network-icon="https://vodacom-now-blog.s3.amazonaws.com/uploads/image/image/277/facebook.png"
            custom-network-href="http://www.google.com/"
          />
```

any help would be greatly appreciated.

**Comment by ngarnier** [comment]
Hey @dawidvdh, 

By default, `text-mode` is set to true, which means you need to [define a content for your social icon](https://mjml.io/documentation/#mjml-social).
> Note that content is mandatory if text-mode is set to true

You can omit a content by setting `text-mode` to `false`.

Please also add an icon-color (you can set it to `none` if you don't want any.

This MJML code should work:
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-social 
          display="custom-network" 
          text-mode="false"
          custom-network-icon-color="none"
          custom-network-icon="https://vodacom-now-blog.s3.amazonaws.com/uploads/image/image/277/facebook.png" 
          custom-network-href="http://www.google.com/" />
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Let me know if it helps!

**Comment by dawidvdh** [comment]
Awesome that works thanks!

**Comment by kaiusvreo** [comment]
It works with one icon (one social). How can be work with 4 socials? (for example: facebook, youtube, vimeo and linkedin?

If I paste the code twice the icones align vertically and not horizontally

**Comment by ngarnier** [comment]
hey @kaiusvreo, put the different social networks in the same `mj-social` tag and use `mode="horizontal"` to display the icons side by side: https://mjml.io/documentation/#mjml-social

**Comment by kaiusvreo** [comment]
ngarnier, thanks so much for your reply,
I understand how it works, and it works.
I have only one thing to fix, how is possible to change the size of the icon?
My icon is 30x30px but it has the same size of the original icon

https://mjml.io/try-it-live/HkmM46r5x

**Comment by kaiusvreo** [comment]
ngarnier you rock! 
thanks so so so so so much!
it's perfect!

**Comment by Premitium** [comment]
These examples do not work anymore. What's changed?

**Comment by ngarnier** [comment]
The syntax changed in MJML v4 @Premitium https://mjml.io/try-it-live/components/social

**Comment by Premitium** [comment]
These are the regular icons, what about having custom ones?

**Comment by ngarnier** [comment]
https://mjml.io/try-it-live/HJJ9ZeiRz
