### ISSUE TITLE
Template with bare minimum tags doesn't compile

### ISSUE THREAD

**Issue by ptolemybarnes** [mjmlio/mjml#433]
Given a basic template, example.mjml:
```html
<mjml>
  <mj-body>
  </mj-body>
</mjml>
```

From the terminal, run `mjml -r example.mjml`. Blows up with:
```
Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file
    at MJMLError.Error (native)
    at new MJMLError (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/Error.js:26:110)
    at documentParser (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:137:11)
    at MJMLRenderer.parseDocument (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:139:45)
    at new MJMLRenderer (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:127:12)
    at /usr/local/lib/node_modules/mjml/node_modules/mjml-cli/lib/client.js:105:12
```

Add a `<mj-text></mj-text>` inside the body and it works. Using `3.0.1`

**Comment by ngarnier** [comment]
hey @ptolemybarnes, 

The bare minimum MJML template would rather be:
```
<mjml>
  <mj-body>
    <mj-container>
      
    </mj-container>
  </mj-body>
</mjml>
```
`container` is needed as it's responsible for generating the basic HTML container (table and divs) for the body of the email.

**Comment by ptolemybarnes** [comment]
@ngarnier Ah okay, thanks for clarifying. Do you think it's worth updating that error message? I was a little confused by it.

**Comment by ngarnier** [comment]
You're right, it's confusing. We'll update the message to reflect that, thanks!

I'm curious, is there any specific reason you need to render the bare minimum MJML template?

**Comment by ptolemybarnes** [comment]
@ngarnier Not really. I was writing a simple script for validating all the mjml templates in a rails project. I needed an example to work off.

**Comment by ptolemybarnes** [comment]
Just found a few other issues similar to this. I wonder if it would be worth having it such that `<mj-body>` wraps its content in an `<mj-container>` by default, assuming a container is always required. Then the structure of a bare-bones mjml document would be more akin to an html document.

**Comment by ngarnier** [comment]
Hey @ptolemybarnes, I updated the Error, it will be available in the next release so I'm closing. We actually don't want to force `<mj-container>` because you can make a custom component as a container. It is actually more exact to say that the issue with your template was that `body` was empty, rather than missing `container`.

Thanks for reporting!

**Comment by alexjeffburke** [comment]
Hi - aware this issue has been closed, but trying to render the base template given here using the 'mjml2html' method exposed by the `miml-core` package at version 3.1.1 has resulted in the following:
```
Element mj-container doesn\'t exist or is not registered
```
I've dropped the package back to 3.0.2 with the same result. Any idea what might be going on?
Thanks!

**Comment by iRyusa** [comment]
Hi @alexjeffburke `mjml-core` has 0 components registered by default. You have to registered them one by one, or you can simply use the `mjml2html` inside `mjml` package

**Comment by alexjeffburke** [comment]
@iRyusa Apologies for not saying sooner but thank you for the tip - I'm sure I saw a reference to including 'mjml-core' in some documentation around sing the API programmatically so assumed that's what I'd need in this case. Switch to 'mjml' and was able to progress :)
