### ISSUE TITLE
Introduce a "strict" setting?

### ISSUE THREAD

**Issue by robcube** [mjmlio/mjml#435]
Need a way to have "strict" setting for MJML to make sure we have endings on all elements, i.e. `<img>` becomes `<img />`, `<br>` becomes `<br />`, and so on.

It would be great as it can be transformed via XML/XSL parsers. Right now, I'm running it through home-grown parser, adding those back in.

Thanks!

**Comment by ngarnier** [comment]
Hey @robcube, I'm sorry but I don't understand what you mean here. Can you please detail?

**Comment by iRyusa** [comment]
Hi @robcube 

Well, this behaviour is inherited from React & JSX, I don't think there's such settings in both of them.

**Comment by ngarnier** [comment]
Hey @robcube, closing this as we won't be able to provide any update on that, sorry.
