### ISSUE TITLE
Build Documentation Locally

### ISSUE THREAD

**Issue by jaypeedevlin** [mjmlio/mjml#436]
Hi,

Is there a tool for building your documentation locally?  I would like to add the mjml documentation to the [user contributed docs](https://github.com/Kapeli/Dash-User-Contributions) for the documentation browser [Dash](https://kapeli.com/dash).

**Comment by ngarnier** [comment]
Hey Josh, 

Nice, thanks :-). For now the website documentation is not on Github, would it work if I provide you with the static version of the doc or do you need to be able to automatically build it so it can be automatically updated?

**Comment by jaypeedevlin** [comment]
For now, a static version of the doc will help me get it up on Dash.

For a few other docsets that I maintain for Dash, I just watch for new releases via rss, and then build the docs locally > push to Dash.  What we do ongoing is up to you really, Ideally I'd like it to require no manual action on your end, but at the same time if there's a burden in setting it up initially, it might be better the other way!

**Comment by ngarnier** [comment]
Alright as a start I can give you a static version. We should update the website next Tuesday to support MJML v3 and the doc will be up to date, can I share it with you once this is done?

**Comment by jaypeedevlin** [comment]
Of course.

**Comment by ngarnier** [comment]
hey @jaypeedevlin, can you please send me an email to ngarnier@mailjet.com so we can discuss about what you need and I can share a static version with you?

**Comment by jaypeedevlin** [comment]
Sure.
