### ISSUE TITLE
Error when importing mjml2html in React.js

### ISSUE THREAD

**Issue by joehartz** [mjmlio/mjml#438]
Hello,

I'm trying to render mjml inside my React app.

Inside my react app i'm importing:
`import { mjml2html } from 'mjml';`

This is the error I get:

```
Critical dependencies:
79:45-62 the request of a dependency is an expression
 @ ./~/mjml-core/lib/parsers/config.js 79:45-62

```

I am using [react-create-app](https://github.com/facebookincubator/create-react-app) as a boilerplate for the app. Which is already is using  Webpack, Babel and ESLint under the hood.

Is this a side effect of using react-create app? Is there a simple way to tell that dependency I need to install?

PS: Thanks for the great work you guys have put into this!

**Comment by joehartz** [comment]
After taking a closer look the error was a little misleading to me. Apparently It's not a dependency problem but Webpack complaining 'request of a dependency is an expression'? I have not found a workaround yet or solution. 

Reading through [this thread](https://github.com/webpack/webpack/issues/196) I'm still a bit confused why webpack is not happy with importing/requiring mjml.

**Comment by iRyusa** [comment]
I think this might be an issue with the require of .mjmlconfig i'll take a look

**Comment by mmazzarolo** [comment]
FYI I'm having the same issue on `mjml` > 3.0.0. `mjml@2.3.3` works fine though.

**Comment by farhansalam** [comment]
Getting same warning. Any fix for this issue? I am using `mjml: 3.3.0-beta.8`.

**Comment by skoob13** [comment]
Having the same problem on 3.3.0.

**Comment by iRyusa** [comment]
Well little update here, the error comes from webpack build and keeping the project "buildable" for browser is quite a painful job. We're totally open to receive PR on this but we're not gonna take a look at this anytime soon.

So I'm closing this issue for now.

**Comment by ptbrowne** [comment]
For information, if you do not use custom components or custom config, you can use 

```
    exprContextRegExp: /$^/,
    exprContextCritical: false,
```

in your webpack configuration. Source : https://webpack.js.org/configuration/module/#module-contexts

**Comment by AndreasFurster** [comment]
The same problem occurs with a basic Vue installation created with the Vue CLI. https://github.com/vuejs/vue-cli

There also occur some `Cannot find module "fs"` errors

**Comment by kuiperr005** [comment]
Any updates regaring this issue?

**Comment by iRyusa** [comment]
👉 https://github.com/mjmlio/mjml/issues/438#issuecomment-302712905
