### ISSUE TITLE
Speudo elements after/before not working

### ISSUE THREAD

**Issue by WillyPoteloin** [mjmlio/mjml#441]
I have this mjml file and the before speudo element is not add to the span...

```html
<mjml>  
  <mj-head>
    <mj-font name="Ionicons" href="../../../fonts/ionicons/style.css" />
    <mj-style>
      .ion-link {
        color: red;
      }
      .ion-link::before {
          display:block;
          font-family: 'Ionicons'
          content:"\f1fe";
          width: 10px;
          height: 10px;
          background: red;
      }
    </mj-style>
  </mj-head>
  <mjml-body>
    <mj-section background-color="#2d3538">
      <mj-column>
       <mj-text>
             <mj-text align="right">
                <a href="#"><span class="ion-link"></span>Test</a>
             </mj-text>
       </mj-text>
      </mj-column>
    </mj-section>
  </mjml-body>
</mjml>
```

Is it the expected behavior or am i doing something wrong ?

**Comment by dalefish** [comment]
<mj-columns> is not a valid element, use <mj-column> and see if you still
have issues.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by WillyPoteloin** [comment]
Thanks but unfortunately it's just a spelling mistake, in my template i have an <mj-column>, I edit my fisrt post to correct this ;)

**Comment by dalefish** [comment]
Okay, well I don't think you can inline pseudo selectors so you might be
better off adding a <style> block to the main content using an <mj-raw>
tag.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
Hi @WillyPoteloin 

`mj-style` is a simple inlining css tool, so I don't think pseudo element will work... for now. 
With Gmail now supporting `<style>` we'll probably add a way to directly inject `mj-style` content into head.

**Comment by iRyusa** [comment]
`mj-style` no longer inline by default the style so you can try if it works. But as many client doesn't support custom font & pseudo element we can't do anything about this.

Thanks !
