### ISSUE TITLE
Height with MJML text

### ISSUE THREAD

**Issue by JakeHenshall** [mjmlio/mjml#447]
Hi,

Lovely piece of kit, i'm using having a problem with height for the mj-text.

Here's my code:

           <mj-section background-url="background-image.jpg"
                         background-repeat="repeat"
                         padding="0">

             <mj-column width="300" background-color="#435f57">
               <mj-image width="300"
                         src="image1.jpg" />

                           <mj-text font-size="16px" color="#FFFFFF">
                             Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod.</mj-text>
             </mj-column>

             <mj-column width="300" background-color="#435f57">
                 <mj-image width="300"
                           src="image2.jpg" />

                             <mj-text font-size="16px" color="#FFFFFF">
                              Nullam id dolor id nibh ultricies vehicula ut id elit.</mj-text>
             </mj-column>

           </mj-section>

Here is an image with the problem:

<img width="769" alt="screen shot 2016-11-24 at 01 04 04" src="https://cloud.githubusercontent.com/assets/4720782/20583518/90975a1a-b1e2-11e6-8fa3-242dfdc86ebc.png">

Any help would be much appreciated.

Thanks Jake.

**Comment by iRyusa** [comment]
Hi @JakeHenshall 

I take a look at it, and I have no real solution for you in MJML right now. You can add a mj-spacer with the right `height` but it's not really the best way to do it...

But you can do it easily by editing the output HTML like this : https://gist.github.com/iRyusa/144b32e358511c7eb18a06c1ef0fbe33

By adding a div around the `section` and add a `bgcolor` on the `table` for outlook ( see `<!-- START ADD DIV HERE -->` comment )

I think we should add a `wrapped="wrapped"` attribute on `mj-section` or something like that to allow this behaviour, what do you think ?

**Comment by JakeHenshall** [comment]
@iRyusa Yeah that seems like a great solution the wrapped="wrapped" as long as you can add a background-color to it. Are you going to implement something like this -> https://github.com/mjmlio/mjml/pull/444. 

Are you any closer to the nesting sections? I think that the nested section would be the key and make creating email much better. If they gets done I know my company would 100% adopt this and i'm sure would also promote it too. Please let me know if i can be of any assistance. 

Thanks Jake.

**Comment by rogierslag** [comment]
This was fixed in https://github.com/mjmlio/mjml/pull/453

**Comment by ngarnier** [comment]
Indeed, thanks for the contrib @rogierslag!

**Comment by rogierslag** [comment]
Glad I could help :)
