### ISSUE TITLE
Programmatically creating mjml

### ISSUE THREAD

**Issue by HemalR** [mjmlio/mjml#450]
Right, this isn't an issue so much as a request for some advice. Thanks in advance to anybody who takes the time to read! 👍 

## What I am trying to do:
Storing email templates as an array of 'email modules' (as JSON in my database). Then, when it is time to send an email, the program will convert the JSON into mjml, which will then be converted into html, which can then be sent off to Mailjet (or wherever).

### For example (simplified) - an email stored in the db:
```
emailTemplateOne: [
  {type: 'header', value: 'This is a header'}, 
  {type: 'text', value: 'This is some text to be sent'}
]
```

### When it is time to send, this should translate to:

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
	<mj-column>
	  <mj-text>
            <h1>This is a header</h1>
	  </mj-text>
	  <mj-text>
             This is some text to be sent
	  </mj-text>
	</mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

### How I am currently trying (and failing) to do this:
I've using react to generate the mjml similar to this:

```javascript
import React from 'react';
import { mjml2html, elements } from 'mjml';
const { _mjmlBody, _mjmlContainer, _mjmlSection, _mjmlColumn, _mjmlText } = elements;

let createMjml = function (arrayOfComponents) {
  let parsedComponents = arrayOfComponents.map((component) => {
	switch (component.type) {
		case "header":
			return (
				<mj-text>
					<h1>{component.value}</h1>
				</mj-text>
			);
                  case "text":
			return (
				<mj-text>
					{component.value}
				</mj-text>
			);
		default:
			return (<p>Default case fired</p>);
	}
  });

  return (
	<mjml>
		<mj-body>
			<mj-container>
				<mj-section>
					<mj-column>
						{parsedComponents}
					</mj-column>
				</mj-section>
			</mj-container>
		</mj-body>
	</mjml>
  )
};

```

So when it is time to send an email from the database:

```javascript
const createEmailBody = function (arrayOfComponents) {
	console.log(arrayOfComponents); //make sure the right JSON is going in
	let mjmlBody = createMjml(arrayOfComponents); //convert components into mjml
	console.log(mjmlBody); //ensure right mjml coming out
	let htmlOutput = mjml2html(mjmlBody); //convert mjml to html
	console.log(htmlOutput); //ensure right html coming out
	return htmlOutput;
};

let htmlToSend = createEmailBody(/*JSON Object from database goes here*/)
```

## Errors/issues

When creating the mjml, something is going wrong... Not sure what it is or how to fix it. 
* If I hard code the mjml (passing in an mjml string), then works perfectly as expected
* If I wrap the above function with " ` " - and the dynamic bit with ${parsedComponents()} - then, rather than parsing the components I simply get [object, object] within the mjml and html output

Output of the createMjml function below (rather than the mjml, this is what I am getting).
```
{ '$$typeof': Symbol(react.element),
I20161128-13:32:44.851(8)?   type: 'mjml',
I20161128-13:32:44.851(8)?   key: null,
I20161128-13:32:44.851(8)?   ref: null,
I20161128-13:32:44.852(8)?   props: 
I20161128-13:32:44.852(8)?    { children: 
I20161128-13:32:44.852(8)?       { '$$typeof': Symbol(react.element),
I20161128-13:32:44.852(8)?         type: 'mj-body',
I20161128-13:32:44.853(8)?         key: null,
I20161128-13:32:44.853(8)?         ref: null,
I20161128-13:32:44.853(8)?         props: [Object],
I20161128-13:32:44.854(8)?         _owner: null,
I20161128-13:32:44.854(8)?         _store: {} } },
I20161128-13:32:44.854(8)?   _owner: null,
I20161128-13:32:44.855(8)?   _store: {} }
```

# Questions:
1. What are the glaring errors with how I am doing things above?
2. Does anyone have any pointers/code examples on how to programmatically create mjml?

Thanks again - if you've read this far and can help I really appreciate it. End goal is to create an npm package that allows for anyone to drop in a simple email editor with minimalist building blocks for _their_ users to create emails.

**Comment by iRyusa** [comment]
Hi there @HemalR ,

You're passing JSX ( translated to React Element ) to MJML and it doesn't know how to process it.

However there's an undocumented feature that you can use. You can pass JSON to mjml2html and it will work as expected but you can't use any `mj-head` elements. Check https://github.com/mjmlio/mjml/issues/324#issuecomment-230318635 for an example 👍

**Comment by HemalR** [comment]
Trying it out now. Thanks for taking the time to respond!

**Comment by kunKun-tx** [comment]
For anyone who wants to try the json method, be sure to add an additional `mjml `tag outside of `mj-body`

```
console.log(mjml2html({
  'tagName': 'mjml',
  'attributes': {},
  'children': [
    {
      tagName: 'mj-body',
      attributes: {},
      children: [{
        tagName: 'mj-container',
        attributes: {},
        children: [{
          tagName: 'mj-section',
          attributes: {},
          children: [{
            tagName: 'mj-column',
            attributes: {},
            children: [{
              tagName: 'mj-text',
              attributes: {},
              content: 'Youhou \o/'
            }]
          }]
        }]
      }]
    }
  ]
}))
```
