### ISSUE TITLE
Email always display as mobile on Gmail

### ISSUE THREAD

**Issue by bnqtoan** [mjmlio/mjml#454]
After many tries, I used [this demo template](https://mjml.io/try-it-live/templates/proof), in gmail, the template always act like it on mobile.

http://prntscr.com/dctwei

It works fine on mobile device.
Sorry for my bad English.

**Comment by iRyusa** [comment]
Hi there @bnqtoan ,

Are you using a google apps account, or it's a classic gmail email address ?

**Comment by bnqtoan** [comment]
Hi @iRyusa, I'm using classic gmail email address.

**Comment by bnqtoan** [comment]
Another thing is it has desktop version worked well before image load, after I click _Display image_, it's turn into mobile layout.

**Comment by iRyusa** [comment]
Mh weird, how do you send your email ?

**Comment by bnqtoan** [comment]
I'm using mailchimp. It's really weird, I just find out that when I click "Display Image", gmail change the classname. Maybe this is not mjml's problem itself, but I have no idea to deal with it.

**Comment by iRyusa** [comment]
Mailchimp has an issue with the `@import` tag try to remove them from your html and send it back to your gmail or try to use a different service like putsmail.com by litmus

**Comment by bnqtoan** [comment]
I've tried putsmail already, I manually removed `@import` from the beginning. Tested gmail on safari, firefox & chrome but no hope :(

**Comment by iRyusa** [comment]
Can you try to cc the mail to `maxime [at] derniercri.io` when sending it with putsmail please ?

**Comment by bnqtoan** [comment]
I did. Please check it out, thank you!

**Comment by iRyusa** [comment]
Do you directly send the html from https://mjml.io/try-it-live/templates/proof ? I've got a similar mobile display from your email but got the desktop one when sending the HTML from https://mjml.io/try-it-live/templates/proof

**Comment by bnqtoan** [comment]
I copied html from [this](https://mjml.io/try-it-live/templates/proof) http://prntscr.com/dec1aj, and pasted it into putsmail without any modification.

**Comment by bnqtoan** [comment]
Opps, I got things right without check this option http://prntscr.com/dec29a

**Comment by AmilKey** [comment]
I have this issue too
send by mailchimp
![image](https://cloud.githubusercontent.com/assets/1917912/20838040/db9f2836-b8b7-11e6-9341-8fad34d5213f.png)

**Comment by iRyusa** [comment]
@AmilKey @bnqtoan well that's an issue with Mailchimp and not with MJML. Check if you can disable the automatics css inline cf ( http://kb.mailchimp.com/campaigns/ways-to-build/use-the-css-inliner )

**Comment by AmilKey** [comment]
@bnqtoan how did you resolve this issue, I can't find this option in my company?

**Comment by iRyusa** [comment]
The screenshot was from Putsmail @AmilKey 

Did you check this : 
> Check if you can disable the automatics css inline and see if it solve it for you cf ( http://kb.mailchimp.com/campaigns/ways-to-build/use-the-css-inliner )

**Comment by bnqtoan** [comment]
@AmilKey looks like mailchimp change their UI. I didn't see that option too, but you can skip that issue by creating new campaign and send test **from campaign**

**Comment by oldmanwerther** [comment]
I've experienced a similar issue and found that MailChimp adds some interesting erroneous CSS when importing MJML generated code:

`@media only screen and (max-width:480px){
     width:320px {
         width:320px;
     }
 }` 

Removing allowed for Gmail/Outlook to properly render the correct desktop/mobile css.

**Comment by iRyusa** [comment]
Yeah, as mailchimp alter the HTML we can't do anything to prevent this. They try to merge every media queries in a single one I think

**Comment by issambox** [comment]
@oldmanwerther  nice one that's the case, and that solves the problem
