### ISSUE TITLE
<mj-column> padding problems

### ISSUE THREAD

**Issue by laurent-bientz** [mjmlio/mjml#46]
Hi,

I can't set a padding on `<mj-column>`

If i got 3 columns of 33%, the only way to put a padding between columns is to apply this padding on each children of this column.

**What I do (trying to apply a padding on whole col):**
```html
<mj-body background-color="grey">
  
  <mj-section>
    
    <mj-column width="33%" padding="50px">
      <mj-text align="left" color="#EEE" font-family="roboto" align="center">test title lorem ipsum dolor lorem ipsum dolor</mj-text>
      <mj-text align="left" color="#EEE" font-family="roboto" align="center">lorem ipsum dolor sit amet consectetur lorem ipsum </mj-text>
    </mj-column>
    
    <mj-column width="33%" padding="50px">
      <mj-text align="left" color="#EEE" font-family="roboto" align="center">test title lorem ipsum dolor lorem ipsum dolor</mj-text>
      <mj-text align="left" color="#EEE" font-family="roboto" align="center">lorem ipsum dolor sit amet consectetur lorem ipsum </mj-text>
    </mj-column>
    
    <mj-column width="33%" padding="50px">
      <mj-text align="left" color="#EEE" font-family="roboto" align="center">test title lorem ipsum dolor lorem ipsum dolor</mj-text>
      <mj-text align="left" color="#EEE" font-family="roboto" align="center">lorem ipsum dolor sit amet consectetur lorem ipsum </mj-text>
    </mj-column>
    
  </mj-section>
</mj-body>
```

**What I get with padding on `<mj-column>`:**

![padding-col](https://cloud.githubusercontent.com/assets/6093572/12980925/d5896040-d0de-11e5-804e-ca5fd8b29d94.jpg)

**What I get width padding on each children of `<mj-column>` (each `<mj-text>`):**

![padding-child](https://cloud.githubusercontent.com/assets/6093572/12980926/d86c3030-d0de-11e5-87f0-8318f2de3153.jpg)

Padding on `<mj-column>` is not supported? or it's the default padding of `<mj-text>`?

If i put padding-left & padding-right at 0px on each `<mj-text>`, I can see again less padding:

![padding_0](https://cloud.githubusercontent.com/assets/6093572/12981254/2bb9d14c-d0e0-11e5-8a54-5ed1278a071b.jpg)

So I think putting default padding is not a good idea.
If we set a padding on a component with no padding on his children, we've to apply it, what do u think about this approach?

Thank

**Comment by arnaudbreton** [comment]
Hi @laurent-bientz, 

There is actually a typo in our documentation, since `padding` attribute is not supported on column. We will remove it there for now and work on implementing it for real this time (not straightforward to do).

You're right about the padding on the `mj-text` component, you can see the definition in the latest released version [here](https://github.com/mjmlio/mjml/blob/master/src/components/Text.js#L18-L21). 
For now, the only solution we can suggest you is to manually set them to 0. Still, we agree that default value are not optimal and will see to remove them in a future release.

Let us know how this works for you.

**Comment by laurent-bientz** [comment]
Hi @arnaudbreton,

Thank you for the feedback. This solution is working (already what I did).

We'll stay tuned for the next releases, I think that a kind of css reset will be appreciated in our company ;)

Cheers

**Comment by arnaudbreton** [comment]
Great, may we close this issue and follow up once we improved that part in a future releas?

**Comment by laurent-bientz** [comment]
Ofc sry.

**Comment by joeydi** [comment]
> There is actually a typo in our documentation, since padding attribute is not supported on column.

I just wanted to point out that the documentation still show padding as an attribute for mj-column, but it does not do anything. 

Using MJML App v2.8.0

<img width="1605" alt="screen shot 2018-06-25 at 12 36 42 pm" src="https://user-images.githubusercontent.com/173391/41863410-ac92ad50-7874-11e8-861f-7e896621cf6e.png">

**Comment by kmcb777** [comment]
Hi @joeydi , padding should now be supported on mj-column, could you please provide the mjml you used to test this ?
I think the app v2.8 is running on mjml4 and i just tested with a simple example on the try-it-live, and padding was working fine

**Comment by joeydi** [comment]
@kmcb777 It looks like padding works, but padding-xxx does not.

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="center" color="#555" />
      <mj-section background-color="#fff" />
    </mj-attributes>
  </mj-head>
  <mj-body background-color="#eee">
    <mj-section>
      <mj-column padding-top="100px">
        <mj-text>
          First column
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

![screen shot 2018-06-25 at 1 07 49 pm](https://user-images.githubusercontent.com/173391/41864729-ed407608-7878-11e8-9f2b-6c220348756a.png)

**Comment by kmcb777** [comment]
@joeydi ah there was indeed a bug that made `padding-xxx` ignored if no `padding` is specified. This has already been fixed on mjml latest version, so this will be fixed in the next app release.
Thanks anyway for your report 👍
