### ISSUE TITLE
Add styles to the compiled document head

### ISSUE THREAD

**Issue by mklemme** [mjmlio/mjml#462]
Switched from foundation to the latest version of mjml because of the mobile-first approach this framework takes (already solved our outlook & gmail android problems!)

I think the approach for applying styles directly to the component in that context works for email, but we also use ESP customer.io to send the emails. To make this work for me, some styles need to be retained in the head to be applied to the content in the wysiwyg editor (customer.io inlines styles for this content: h1..h6, p, a, hr, etc).

I'm already doing this, but the styles are inlined and not added to the compiled head. 

```html
<mj-style>
  * {
    box-sizing: border-box;
  }
</mj-style>
```

Is there a way to create/import styles and add them to the compiled document head through mjml or do I have to add this manually after it's built?

**Comment by mklemme** [comment]
I see the styles defined here `mjml-core/src/configs/defaultStyle.js`. Should this be where I manually put the styles that I need to be added the head? Doesn't support imports, so this doesn't really feel like a clean way of doing it. Thoughts?

**Comment by mklemme** [comment]
Adding styles to `mjml-core/src/configs/defaultStyle.js` doesn't seem to do anything. Is this intended?

**Comment by iRyusa** [comment]
Hi @mklemme 

So, few things. MjStyle does only support inline yet, but we're thinking about 3 mode for it : inline/in head/ inline+in head, so it will fit your needs perfectly.

About `src` folder it only contains source files. If you want to edit this you can edit the same file inside `lib` folder but I strongly advise you to not do this

**Comment by mklemme** [comment]
Ohh. 👍  That would be awesome. When can we expect this to be released?

I'm not seeing any `lib` folders only `src`. So I need to `npm install` inside each package. I guess a better question is: is there a better way to extend components to add styles and such?

**Comment by iRyusa** [comment]
Just use the install.sh, it will linkg everything to use it in dev mode :) 

And gulp build to build to whole repo ( everytime you have a modification you have to gulp build )

**Comment by ngarnier** [comment]
Hi @mklemme, sorry we didn't update you earlier but this is in beta and available right now (including on the try it live, [example](https://mjml.io/try-it-live/components/head-style))

**Comment by ngarnier** [comment]
MJML v3.3.0 is out, fixing this issue! Thanks again for submitting, definitely a great feature :-).

To install: `npm install mjml`
