### ISSUE TITLE
[question] how to avoid the warning: entity not found:&nbsp;

### ISSUE THREAD

**Issue by robsonpeixoto** [mjmlio/mjml#464]
If I put a `&nbsp;` the compiler always show a warning. How to disable or avoid it?

**Comment by iRyusa** [comment]
Hi @robsonpeixoto can you share an example ?

**Comment by robsonpeixoto** [comment]
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
          &nbsp;&nbsp;
          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Mhh this is not valid from an MJML standpoint if you really want to do this you have to put it inside a `mj-raw`. What do you want to achieve with that ?

**Comment by robsonpeixoto** [comment]
@iRyusa I tried it, but still show the warning.

**Comment by iRyusa** [comment]
Can you paste me the warning ? It doesn't show up on my side

**Comment by robsonpeixoto** [comment]
![image](https://cloud.githubusercontent.com/assets/124390/20971585/c1005aa6-bc70-11e6-8707-8d3f76f780c5.png)

**Comment by robsonpeixoto** [comment]
![image](https://cloud.githubusercontent.com/assets/124390/20971649/fa63e0e2-bc70-11e6-93db-35d53eff7960.png)

A better screenshot

**Comment by iRyusa** [comment]
Oh, you mean inside the try-it-live, it's just a display issue it does the same with every HTML chars.

The code editor assume you're writing some XML, so that's why it says "entity not found"

**Comment by robsonpeixoto** [comment]
Thanks
