### ISSUE TITLE
<mj-hero> Height bug mjml 3.1.1

### ISSUE THREAD

**Issue by renatodeleao** [mjmlio/mjml#465]
The line-height attribute on `<mj-text>` causes `<mj-hero>` to be rendered with a huge non-defined height.

Full bug description and images can be found here:
https://github.com/sighmon/mjml-rails/issues/11

#### TL;DR;
At first I though it was a problem with the gem, but after discussing with the maintainer, we realised that it's a problem with `mjml v3.1.1` itself, since it is working as expected with `v3.0.2`.

Cheers!

**Comment by iRyusa** [comment]
Hi there,
It's a small change in mjml `3.1` that affect this code. `line-height` supports now unitless css notation, so you have to add `px`!

I'll fix the `mj-hero` example, sorry about that :)

**Comment by renatodeleao** [comment]
@iRyusa :facepalm:

Thanks!
