### ISSUE TITLE
Background image issue in hotmail.com

### ISSUE THREAD

**Issue by TylerPottsDev** [mjmlio/mjml#468]
Hi Not sure if this is already been logged but I found that the background image completely breaks in Hotmail.com without fallbacks with this markup.
```xml
<mj-section background-url="http://1.bp.blogspot.com/-TPrfhxbYpDY/Uh3Refzk02I/AAAAAAAALw8/5sUJ0UUGYuw/s1600/New+York+in+The+1960's+-+70's+(2).jpg" background-size="cover" background-repeat="no-repeat">
    <mj-column width="600">
        <mj-text  align="center" color="#f8f8f8" font-size="40" font-family="Helvetica, Arial" font-weight="900" line-height="55px">
            This is Awesome
        </mj-text>
        <mj-button background-color="#00abfa" font-family="Helvetica, Arial" font-weight="700" href="#">
            Promotion
        </mj-button>
    </mj-column>
</mj-section>
```
Let me know if there is a simple fix or if this issue is common. Thanks.

**Comment by iRyusa** [comment]
Hi there @TylerPottsDev 

It looks like MJML doesn't like parenthesis inside url for `background`. Can you try with a reupload here : http://i.imgur.com/COkZvCi.jpg it looks like to work just fine for me.

And don't worry if the text isn't shown inside your button you need a valid url for Outlook

**Comment by TylerPottsDev** [comment]
Thanks @iRyusa I'll give it ago.

**Comment by TylerPottsDev** [comment]
@iRyusa It worked perfectly thank you!
