### ISSUE TITLE
No documentation for mj-list

### ISSUE THREAD

**Issue by Uelb** [mjmlio/mjml#469]
I couldn't find the reference of mj-list documentation here : https://mjml.io/documentation/

I used the github readme of course but it's just a heads up so that you add it whenever you have time.

**Comment by ngarnier** [comment]
Hey @Uelb, thanks for reporting. However, as stated in the [Release 3.1.0](https://github.com/mjmlio/mjml/releases/tag/3.1.0) and on the [package readme](https://github.com/mjmlio/mjml/tree/master/packages/mjml-list), `mj-list` will be deprecated in the next release. 

Cheers!

**Comment by Uelb** [comment]
Oh thank you for answering, I did not notice the message.
