### ISSUE TITLE
validateDOMNesting when using React + Mjml

### ISSUE THREAD

**Issue by renatorib** [mjmlio/mjml#471]
Hi,

I think it's more a problem with React than Mjml itself. But caused indirectly by mjml. I think more people can facing with this same problem.

I have React components that generate pure mjml (using renderToStaticMarkup), so it is parsed with mjml and saved into a file.

Example:
```
EmailConfirmation.jsx
=>
email-confirmation.mjml
=>
email-confirmation.html
```

That's ok. Working. But I have some warning/errors generated by react, because it renders `mj-table > tr`:
```
console.error node_modules/fbjs/lib/warning.js:36
      Warning: validateDOMNesting(...): <tr> cannot appear as a child of <mj-table>. See AddressTable > mj-table > tr.
```

Is there any way to avoid (or disable) `validateDOMNesting` in this cases?

**Comment by iRyusa** [comment]
Hi @renatorib ! 

Can you share the content of this file ?

 Beware that MJML components are not only simple React component, so you'll need to apply post render to the whole document

**Comment by iRyusa** [comment]
Hi @renatorib any news on that ?

**Comment by iRyusa** [comment]
Hi @renatorib , i'm closing this issue for now, feel free to reopen if you can provide more information about the content of" email-confirmation" file

**Comment by renatorib** [comment]
Hello @iRyusa, sorry for delay.

It's about React, not mjml itself.
I use React to render to mjml with `renderToString`, and after, render mjml to html.

```js
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { mjml2html } from 'mjml';

const Email = () => (
  <mj-table>
    <tr>tr as a child of mj-table</tr>
  </mj-table>
);

const mjmlString = ReactDOMServer.renderToStaticMarkup(
  <Email />,
);
/*
console.error node_modules/fbjs/lib/warning.js:36
      Warning: validateDOMNesting(...): <tr> cannot appear as a child of <mj-table>. See Email > mj-table > tr.
*/ 

const html = mjml2html(mjmlString).html;

export default html;
```

**Comment by iRyusa** [comment]
Hey @renatorib 

You need to add a tbody to avoid JSX warning ! Note that we gonna totally drop React from MJML stack in a near future, see : https://medium.com/mjml-making-responsive-email-easy/hey-were-entirely-rebuilding-mjml-from-scratch-announcing-mjml-v4-ae92f83b725b#.xig1gdoc6

**Comment by renatorib** [comment]
Haha, no problem!
Nice, I did not know it was possible to import mjml components directly. 
Thanks!
