### ISSUE TITLE
Styling alt tags for mj-image

### ISSUE THREAD

**Issue by TylerPottsDev** [mjmlio/mjml#472]
Hi, I was thinking you should implement Styled Alt tags - so the ability to add font-size & color ect... to the mj-image tag to style the alt text!

Let me know if this is already in progress or you're going to implement it!

Resource: https://litmus.com/blog/the-ultimate-guide-to-styled-alt-text-in-email

**Comment by dalefish** [comment]
I doubt the support would be wide enough for it to be considered for adding
it as part of the MJML core.

Feel free to prove me wrong though.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by TylerPottsDev** [comment]
Well I believe that styled alt text would be beneficial although it is not very supported it is still a big issue when you have a really nice image but its being blocked and to see styled alt tags may just make the none image design just that slight bit better! 

Here's a link to the support of styled alt tags and it is still pretty supported in webmail clients and some desktop clients. https://litmus.com/blog/the-ultimate-guide-to-styled-alt-text-in-email

**Comment by mattez** [comment]
Hi.
It is IMHO impossible right now in MJML to style ALT attribute. Probably only way is to edit rendered output.(It is mentioned here #577) 
- no unlimited control of _mj-image_ via _mj-class_ . See: https://mjml.io/try-it-live/SkMSGX_ix
- Only parameters accepted are _mj-image_ parametres https://mjml.io/documentation/#mjml-image

So if you want to style _font-size_, _color_, _text-align_ ...which are necessary parameters to define _alt text_  you are doomed.

Related: #577

**Comment by codaha** [comment]
Support is not that small. It wowudl certainly be usefull.

**Comment by iRyusa** [comment]
Hi there, 

Since we're supporting `css-class` you will be able to apply some style to any `img` and styles it. Feel free to test it in current beta !

**Comment by iRyusa** [comment]
As mentioned on my previous comment, css-class now allows that ! So I can close 👍
