### ISSUE TITLE
Outlook 2010 and 2013 do not wrap button text

### ISSUE THREAD

**Issue by travisbrkr1234** [mjmlio/mjml#476]
If you create a button such as: 

```
<mj-button background-color="#c7896f" color="#FFFFFF" font-size="13" align="center" vertical-align="middle" border="none" padding="15px 30px" border-radius="3px" href="https://mjml.io" font-family="Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif"
            padding-left="25" padding-right="25" padding-bottom="10" padding-top="10">
            reallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonTextreallyLongButtonText
          </mj-button>
```
Observe that the button width in outlook 2010 and 2013 is really wide. Even after specifying a width attribute, the button is elongated. This is not the case in outlook 2011 or gmail, etc.

**Comment by iRyusa** [comment]
Hi @travisbrkr1234 

It looks like it's not the only one that ignore word-wrap and I don't think there's much we can do to prevent this behaviour. Do you have any leads about a potential fix ?

**Comment by travisbrkr1234** [comment]
@iRyusa I was able to set a fixed max-width on the button which worked in this case. I am not sure what the optimal fix should be...

**Comment by iRyusa** [comment]
Well, we didn't found anything that looks like word-wrap for Outlook. So I'm afraid there's no fix about this one. 

I'm closing it for now, feel free to reopen if someone has a fix in mind !
