### ISSUE TITLE
Email subscription broken [main site]

### ISSUE THREAD

**Issue by w01fgang** [mjmlio/mjml#477]
I wanted to subscribe to newsletter on the project's site but response is "Oops, something went wrong."
The subscription service responses with code 403 "ForbiddenError: invalid csrf token"

**Comment by ngarnier** [comment]
Hey @w01fgang, thanks a lot for reporting the issue! We're working on it.

**Comment by ngarnier** [comment]
hey @w01fgang, this issue is fixed, you can now subscribe to the newsletter on https://mjml.io/. Sorry for the trouble!
