### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by lemieuxs** [mjmlio/mjml#48]
Hi,

I am building up a newsletter frame, but I am having some issues with the custom components.

I want to create a simple title component to start with. But it doesn't seem to work.

I execute 
`
mjml --init-component title
`
This creates a .js file name Title. Until this point everything works as expected.

From this point if I put a `<mj-title>` component in my template I expect it to be valid and compiled. But instead I get 
`
Error: [MJMLError] UnknownMJMLElement: Could not find element for : mj-title
    at MJMLError.Error (native)
    at new MJMLError (/usr/local/lib/node_modules/mjml/lib/Error.js:24:85)
    at /usr/local/lib/node_modules/mjml/lib/components/decorators/MJMLElement.js:193:21
`
I can't seem to figure out how the new component get's registered with the basic one's.

Thanks

**Comment by GuillaumeBadi** [comment]
Hey @lemieuxs !

At the moment, you will have to use a JS script in order to achieve that.

Your script will need to `import` all your components
``` javascript

import './Title'
import mjml from 'mjml'

/*
...
*/

// And  then compile
mjml.mjml2html(< mjml code >)

```

**Comment by lemieuxs** [comment]
Good thanks.
