### ISSUE TITLE
Add class to element

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml#480]
I would like to use classes in my mjml, that are also transpiled as class in the resulting html.

e.g. `<mj-text class="viewbrowser>` -->  `<div class="viewbrowser>`

Adding a class just to `<mj-section>` would also be sufficient for me.
Use case: The newsletters show a link to a browser view, which is useful if the mail client doesn't display it properly. The browser view should hide this link.
The mailserver detects this by adding a class "viewbrowser" to the element.

This would save me some time of manually editing every newsletter.

**Comment by MatasSim** [comment]
I found a workaround:
```
<mj-text>
  <div class="viewbrowser">
    some html
  </div>
</mj-text>
```

**Comment by ngarnier** [comment]
Hi, there's a discussion going on here: https://github.com/mjmlio/mjml/pull/532. Feel free to comment to give your opinion @janus-reith @matass!
