### ISSUE TITLE
Rendering of Carousel / Padding in Outlook 2016 (365)

### ISSUE THREAD

**Issue by nvassos** [mjmlio/mjml#482]
Hi there, I am testing your carousel component with outlook 2016 and it's not rendering as it should. 

I am testing the exact code snippet that you have on your documentation page. 

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-carousel>
            <mj-carousel-image src="https://www.mailjet.com/wp-content/uploads/2016/11/ecommerce-guide.jpg" />
            <mj-carousel-image src="https://www.mailjet.com/wp-content/uploads/2016/09/3@1x.png" />
            <mj-carousel-image src="https://www.mailjet.com/wp-content/uploads/2016/09/1@1x.png" />
          </mj-carousel>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
https://www.dropbox.com/s/g54z0aqmsqatz80/Screenshot%202016-12-20%2014.35.10.png?dl=0

Do you have any suggestions or I just have to accept it will not work and fall back on single image? 

Also, I just sent a test email within the MJML app using condensed version of padding *padding:20px 10px 20px 20px* and it seems same version of outlook ignores it, when i added each one top/left/right/bottom it worked. 

Update: 

Apparently the issue is on Windows Outlook 2016
https://ol2016.capture.litmuscdn.com/7a697eb2-4f75-46d3-a466-36607b27daea/results/ol2016-vertical-allowed-1366.png

This is litmus outlook 2016 Os x, which seems, even the carousel works
https://ol2015.capture.litmuscdn.com/7a697eb2-4f75-46d3-a466-36607b27daea/results/ol2015-vertical-allowed-1366.png

You guys have any idea?

**Comment by ngarnier** [comment]
Hey @nvassos, thanks for opening this issue and trying out `mj-carousel`. 

The carousel is rendering as it should in Outlook 2016. Unfortunately, as Outlook won't support any interaction needed in the carousel, we just display the first image. If we displayed the other images and the arrows in Outlook, Outlook users wouldn't be able to interact with it, so this is what seems the most decent fallback.

I can't access your images, they must be private to your Litmus account. When I try in Litmus, Outlook 2016 is showing only the first picture:
![](https://puu.sh/sXuZK/abb19360e0.png)

The condensed version of `padding` seems to be working fine for me, here is my test with `padding="10px 100px 10px 10px"`: 
![](https://puu.sh/sXv8K/16b235a00d.png)

I'm closing this issue but feel free to reopen if you feel like I didn't answer your questions!

Cheers

**Comment by arungarunkumar** [comment]
Hi there, I am testing your carousel component in gmail and outlook 2007 am geeting this as output can u plz help me on this.


**Gmail Mail**
![test mjml - responsive edm - arunkumar n krds fr - krds mail - google chrome_2](https://cloud.githubusercontent.com/assets/3403374/21450788/ee79ff9e-c91f-11e6-8c3b-325f0175c53a.jpg)

**Outlook 2007**
![inbox - microsoft outlook_6](https://cloud.githubusercontent.com/assets/3403374/21450802/151b0a44-c920-11e6-84c8-79290a7c487c.jpg)

**Comment by ngarnier** [comment]
Hi @arungarunkumar, can you please share your MJML code?

**Comment by arungarunkumar** [comment]
@ngarnier this is my code
<mj-carousel>
            <mj-carousel-image src="img/1.png" />
            <mj-carousel-image src="img/2.png" />
            <mj-carousel-image src="img/3.png" />
</mj-carousel>

**Comment by arungarunkumar** [comment]
@ngarnier  this is my code
```
<mj-carousel>
            <mj-carousel-image src="img/1.png" />
            <mj-carousel-image src="img/2.png" />
            <mj-carousel-image src="img/3.png" />
</mj-carousel>
```

**Comment by ngarnier** [comment]
@arungarunkumar sorry but as the issue seems different (and this one is resolved), can you please open a different one? 

Please follow those guidelines so we can help you in the most efficient way possible (and share the full code of your template): https://github.com/mjmlio/mjml/blob/master/CONTRIBUTING.md#how-to-submit-a-good-bug-report-or-enhancement.

Cheers!
