### ISSUE TITLE
mjml with react server-side render

### ISSUE THREAD

**Issue by magsout** [mjmlio/mjml#489]
Hi, 

I use mjml to render e-mail server side with React.

I got some bug with outlook.

During the debug, I found some difference between example on your document and the output of my code.

For example here a part of my code (I removed some part not important to explain my bug)

```js
/**
 *
 * Task runner : send email  with a payload
 *
 */

import Job from "./Job"
import React from "react"

import { mjml2html, registerMJElement } from "mjml"

import App from "../components/App"
registerMJElement(App)


class EmailJob extends Job {

  constructor(job, done) {
    super(job, done)
    this.run()
  }

  // sent email
  run() {
    const content = this.getContent()
    console.log(this.getContent())
  }

  getContent() {
    const payload = encodeURIComponent(JSON.stringify(this.payload))

    return mjml2html(`
      <mjml>
        <mj-body>
          <mj-app payload=${payload} />
        </mj-body>
      </mjml>
    `)
  }
}

export default EmailJob

```

and My component `App`

```js
import React, { Component } from "react"

import { MJMLElement } from "mjml-core"
import MjContainer from "mjml-container"
import MjSection from "mjml-section"
import MjText from "mjml-text"
import MjColumn from "mjml-column"

class App extends Component {
  render() {
    const payload = JSON.parse(decodeURIComponent(this.props.mjml.get("attributes").get("payload")))
    const { action, realm } = payload

    return (
        <MjContainer background-color="#f8f3ea">
          <MjSection>
            <MjColumn>
              <MjText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum vitae purus vel condimentum. In hac habitasse platea dictumst. Ut hendrerit volutpat risus. Maecenas sit amet augue at justo sodales vulputate facilisis iaculis quam. Praesent eget est eget ligula vehicula ullamcorper in et lectus. Integer a faucibus libero. Etiam vitae nisl at enim viverra bibendum. Phasellus non lectus sit amet justo laoreet maximus sed congue ante. Nulla tristique rutrum nunc id suscipit. Aliquam tristique consectetur ullamcorper. In cursus lacinia iaculis. Cras ut orci eros. Nunc eu elementum metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porta mattis lacus, vel consectetur enim. </MjText>
            </MjColumn>
          </MjSection>
        </MjContainer>
    )
  }
}

App.tagName = "mj-app"
App.endingTag = false
App.parentTag = ["mj-body"]

export default App
```

Here the ouput for this code https://gist.github.com/magsout/3e4496acf868f5849b9fde1042d96074

If I remove my component App and I run this code:

```js
/**
 *
 * Task runner : send email or sms with a payload
 *
 */

import Job from "./Job"
import React from "react"

import { mjml2html } from "mjml"

class EmailJob extends Job {

  constructor(job, done) {
    super(job, done)
    this.run()
  }

  // sent email
  run() {
    const content = this.getContent()
    console.log(this.getContent())
  }

  getContent() {
    return mjml2html(`
      <mjml>
        <mj-body>
          <mj-container background-color="#f8f3ea">
            <mj-section background-color="#fff">
              <mj-column width="100%">
                <mj-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum vitae purus vel condimentum. In hac habitasse platea dictumst. Ut hendrerit volutpat risus. Maecenas sit amet augue at justo sodales vulputate facilisis iaculis quam. Praesent eget est eget ligula vehicula ullamcorper in et lectus. Integer a faucibus libero. Etiam vitae nisl at enim viverra bibendum. Phasellus non lectus sit amet justo laoreet maximus sed congue ante. Nulla tristique rutrum nunc id suscipit. Aliquam tristique consectetur ullamcorper. In cursus lacinia iaculis. Cras ut orci eros. Nunc eu elementum metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porta mattis lacus, vel consectetur enim. </mj-text>
              </mj-column>
            </mj-section>
          </mj-container>
        </mj-body>
      </mjml>
    `)
  }
}
export default EmailJob

```

Here the output: https://gist.github.com/magsout/a6df7b92d1961611a12022ffeb2908c9

If I make the difference between the two html files, I notice that there are some attribute removed: https://gist.github.com/magsout/672ec709f8d37ba1e7fef028064f0cf3/revisions

I don't know if I'm doing something wrong, or If it's React or anything else. Have you got some idea to help me?

**Comment by ngarnier** [comment]
Hey @magsout, indeed a `MJML` component is different from its `React` component, it's actually a `React` component + a `postRender` which is why you're seeing a difference between the 2 outputs.

You can see the postRender of the `container` component here: https://github.com/mjmlio/mjml/blob/master/packages/mjml-container/src/index.js

**Comment by magsout** [comment]
Thanks @ngarnier . Maybe I missed something but could you explain me how I can reuse mjml component directly with React ? postRender is a local const not expose.

**Comment by iRyusa** [comment]
Hi @magsout I believe this is due to an empty width on `Section`, but it should be inherited from `mj-container` by default .

From what I see, your component miss the `@MJMLElement` decorator, but if it doesn't fix it, it should be a inheritance issue between mj-container <> mj-section, try to set manually a width  to 600 on `mj-container` too.

**Comment by magsout** [comment]
thanks @iRyusa,

so I tried two things:

1) Added decorator `@MJMLElement`

Same html output as  https://gist.github.com/magsout/a6df7b92d1961611a12022ffeb2908c9

2) Added with on "MjSection"  and "MjContainer"

Same html output as  https://gist.github.com/magsout/a6df7b92d1961611a12022ffeb2908c9

Here's my code 

```js
import React, { Component } from "react"
import { MJMLElement } from "mjml-core"

import MjSection from "mjml-section"
import MjText from "mjml-text"
import MjColumn from "mjml-column"
import MjContainer from "mjml-container"

@MJMLElement

class App extends Component {
  render() {
    const payload = JSON.parse(decodeURIComponent(this.props.mjml.get("attributes").get("payload")))
    const { action, realm } = payload
    return (
      <MjContainer background-color="#fff" width="600px">
        <MjSection width="600px">
          <MjColumn>
            <MjText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum vitae purus vel condimentum. In hac habitasse platea dictumst. Ut hendrerit volutpat risus. Maecenas sit amet augue at justo sodales vulputate facilisis iaculis quam. Praesent eget est eget ligula vehicula ullamcorper in et lectus. Integer a faucibus libero. Etiam vitae nisl at enim viverra bibendum. Phasellus non lectus sit amet justo laoreet maximus sed congue ante. Nulla tristique rutrum nunc id suscipit. Aliquam tristique consectetur ullamcorper. In cursus lacinia iaculis. Cras ut orci eros. Nunc eu elementum metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam porta mattis lacus, vel consectetur enim. </MjText>
          </MjColumn>
        </MjSection>
      </MjContainer>
    )
  }
}

App.tagName = "mj-app"
App.endingTag = false
App.parentTag = ["mj-body"]

export default App
```

**Comment by iRyusa** [comment]
Mhh both link you've provided are identical to the last one in the first post, and they look fine to me ?

**Comment by magsout** [comment]
@iRyusa yes but no ;)

Here the big issue: https://gist.github.com/magsout/672ec709f8d37ba1e7fef028064f0cf3/revisions#diff-957f94eb83aab6fee1b9b8fcb76bb7d3L96

`max-width` is removed for container.

**Comment by magsout** [comment]
@iRyusa oups, you're right, wrong link.


The good is https://gist.github.com/magsout/3e4496acf868f5849b9fde1042d96074

and beautify https://gist.github.com/magsout/037d39d81da3e571ec059226c8e047c2

**Comment by magsout** [comment]
@iRyusa I think I get same issue for column. The design is broken on outlook, because there is no width on container, so column are in the same line.

It's seems like   @ngarnier  said, a postRender issue ? I tried to  write container and postRender each Component, but same result as above :(

**Comment by iRyusa** [comment]
I don't think this is a post render issue because you're still using `mjml2html` when rendering it.
It looks like the decorator doesn't do his inheritance job properly. I'll try to investigate on this.

**Comment by magsout** [comment]
@iRyusa hey, sorry for this kind of message, but any news about this issue ?

**Comment by iRyusa** [comment]
I've tried to debug it, but got no luck with it. Components are in a weird state and the decorators fail to build the JSON for some reason... I'm still looking into it, i'll update here when I got some clues of what happens

**Comment by magsout** [comment]
@iRyusa ok thanks 👍

**Comment by iRyusa** [comment]
Fixing this would require to totally rethink the attributes inheritance in MJML 3.X branch.

As we've removed React in MJML4, using MJML component as react component will no longer be doable so I'm closing the issue.
