### ISSUE TITLE
Unsure of how to remove space between columns.

### ISSUE THREAD

**Issue by Hookeo** [mjmlio/mjml#491]
So I'm needing to remove the space between the columns in a section, but cannot figure out how to do that.  I'm needing to have two images touching, with their text blow not.

What I'm needing to achieve:

![screen shot 2017-01-09 at 3 36 16 pm](https://cloud.githubusercontent.com/assets/6879552/21782464/906b43f8-d681-11e6-87b8-0862ae47c43f.png)

What I currently have:
<img width="690" alt="screen shot 2017-01-09 at 3 39 10 pm" src="https://cloud.githubusercontent.com/assets/6879552/21782792/b988046e-d682-11e6-95e1-55a44fdf0f35.png">

I'm pretty new to email template design and MJML, so I apologize if this is a noob question. 

I appreciate any help!  Thank you!

**Comment by dalefish** [comment]
You can use a reset within mj-head, <mj-all padding='0'>, so you know where
you are and build the spacing up as and where you need to.

**Comment by iRyusa** [comment]
HI @Hookeo 

Can you share your MJML code please ? 
It looks like you forgot to set padding to 0 on your MJ-Image as @dalefish mentioned

**Comment by Hookeo** [comment]
@dalefish 
I didn't realize that <mj-all> existed, thank you!  That was very helpful.

@iRyusa 
Thank you as well.  I had been trying to set the padding of the column to 0, not the image.  That also helped with the problem :)
