### ISSUE TITLE
Concatenate attributes from multiple mj-all/mj-component head tags

### ISSUE THREAD

**Issue by martixy** [mjmlio/mjml#495]
For example the `<mj-all />` tag.

I.e. allow this:
```html
<mj-all color="#F00" />
<mj-all font-size="30" />
```
Right now only the last one has an effect. The idea is to have both of them have effect.
This would make using mjml with templating engines that support inheritance easier.
Currently it necessitates a variety of sub-optimal/ugly workarounds.

**Comment by iRyusa** [comment]
Hi @martixy 

I think I can push this change safely for the next 3.2 release

**Comment by martixy** [comment]
Sweet. Looking forward to it. :)

**Comment by iRyusa** [comment]
Hi @martixy 

3.2 has been released and it now merges multiple `mj-all` ! Note that the Try it live is still in 3.1.X so it's only available on NPM right now 👍
