### ISSUE TITLE
General transpilation failure

### ISSUE THREAD

**Issue by martixy** [mjmlio/mjml#498]
On v3.11 I have this mjml:
http://pastebin.com/RDwfvXJk

And results in this:
http://pastebin.com/ZDedSk4t

Problems with it:
a) Nowhere does it import the font specified.
b) Surviving `<mj-raw>` tags.
c) The actual meat of the content is commented out... what gives?

**Comment by ngarnier** [comment]
Hey @martixy, the issue here is that your MJML markup is really invalid. You cannot wrap sections into sections, columns into columns or sections into columns. 

If you're not sure how to achieve a certain layout, feel free to ask.
