### ISSUE TITLE
Validating templates including mj-head fails with TypeError

### ISSUE THREAD

**Issue by csmcanarney** [mjmlio/mjml#499]
Validating templates that make use of the `mj-head` tags fails with a `TypeError`:

```
$ mjml --validate head-attributes.mjml
Error: TypeError: Cannot read property 'container' of undefined
```

I ran into this issue when trying to validate the [head attributes example](https://mjml.io/try-it-live/components/head-attributes):
```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text padding="0" />
      <mj-class name="blue" color="blue" />
      <mj-class name="big" font-size="20px" />
      <mj-all font-family="Arial" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text mj-class="blue big">
            Hello World!
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

It still compiles, but I suspect this might be the reason I'm having trouble uploading some templates to Mailjet. I'm using Node.js 7.3.0 and mjml 3.1.1.

**Comment by iRyusa** [comment]
Hi @csmcanarney 

I think I've found what's going on, I'll fix this in 3.2.1 !

**Comment by ngarnier** [comment]
Missed that you mentioned it @csmcanarney, but you can't use `mj-head` in Mailjet yet. It will be possible once we release v3.3.0 and it's integrated in Mailjet.

**Comment by ngarnier** [comment]
MJML v3.3.0 is out, fixing this issue! Thanks again for reporting. We'll work to support this new version in Mailjet and offer support for head components in the coming weeks.

To install: `npm install mjml`
