### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by martixy** [mjmlio/mjml#500]
My previous issue got closed due to invalid mjml(fair enough), except none of the problems had anything to do with the invalid parts.
So once again, on v3.2.0, there is a general failure of mjml to work properly on numerous accounts:
a) Nowhere does it import the font specified.
b) Surviving `<mj-raw>` tags.
c) The actual meat of the content is commented out.

Before: http://pastebin.com/KGstMk44
After: http://pastebin.com/eDNAW8Lk

**Comment by iRyusa** [comment]
Hi @martixy 

1) Font are being imported only when used, you're using Calibri in your example, and not Roboto.
2) mj-raw is a MJML tag so you can't use it inside `mj-text` that only supports HTML content
3) When removing non-needed `mj-raw` your email looks ok. Here's how it looks on the try it live with those fix : https://mjml.io/try-it-live/r1A7yYqUe

**Comment by martixy** [comment]
1. I forgot to replace that when pasting the test case. And last week I tested with using the font as well, and could not find the font being imported.
2. I seem to have misunderstood how `raw` tags work. Thanks for clarifying.
3. It does indeed.

Thank you very much for your help. :)
