### ISSUE TITLE
3.2.0 outputs file to current dir instead of -o dir

### ISSUE THREAD

**Issue by sighmon** [mjmlio/mjml#501]
When I updated to MJML ```3.2.0``` this morning the output path no longer listens to the directory specified by ```-o file-path/file.html```.

  **Reproduction Steps:**

  1. Move to a different directory to that of the MJML file. ```$ cd ~/Documents```
  2. Run ```$ mjml -r ~/Desktop/input.mjml -o ~/Desktop/output.html```

  **Expected behavior:**

```output.html``` is the folder ```~/Desktop```

  **Observed behavior:**

```output.html``` is in the folder ```~/Documents```

  **MJML version:**

3.2.0 installed globally via ```$ npm install -g mjml@^3.0```

**Comment by iRyusa** [comment]
Hi @sighmon 

It will be fixed in 3.2.1 ! Sorry about that
