### ISSUE TITLE
paths in CLI stop worked

### ISSUE THREAD

**Issue by fico7489** [mjmlio/mjml#505]
This command:
mjml resources/views/emails/layouts/mjml/order.blade.mjml -o resources/views/emails/layouts/order.blade.php
is working in 3.1.1.
but is not working in 3.2.0.
This file "order.blade.php" is not outputed in "resources/views/emails/layouts/" it is outputed in root folder although path is set...

**Comment by iRyusa** [comment]
Hi @fico7489 

We are on this already cf : #501 and we should release the fix soon cf #503  
Sorry about that !

**Comment by iRyusa** [comment]
It should be fixed in 3.2.1 Please try again and tell me if it's ok now :)
