### ISSUE TITLE
Issue using em instead of px

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#506]
Guys  I seem to be having an issue where the padding on any mj tag will not allow me to use  "em"   to set the padding or even height it will only accept "px"  to set the values.

![screen shot 2017-01-19 at 10 45 45 am](https://cloud.githubusercontent.com/assets/25219824/22099575/9d1b4fa2-de34-11e6-8d58-09ff372a6846.png)
![screen shot 2017-01-19 at 10 46 13 am](https://cloud.githubusercontent.com/assets/25219824/22099576/9d454636-de34-11e6-8613-9a06736300c8.png)

Please can you provide me with feed back if there is a solution or possibly add a fix to allow such as it seems to be a bug that you guys have .

**Comment by dalefish** [comment]
https://www.campaignmonitor.com/blog/email-marketing/2011/04/should-i-use-em-or-px-when-coding-for-html-email/

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by magicdude4eva** [comment]
@dalefish do you think a 6 year old article is still relevant now?

**Comment by dalefish** [comment]
Yes, a good portion of the email clients from 6 years ago haven't changed
at all. Outlook 2010 for instance.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by magicdude4eva** [comment]
I think my point is if there is a technical reason why em is not supported (either it is a bug or it is deliberate - it is just confusing that em is supported elsewhere).

**Comment by iRyusa** [comment]
Well, i've checked what happens. The td that receive the padding has a font size of 0, so em will fail here. And I think we should keep the font size to 0 to avoid any whitespacing issue so I dont know if we can fix it

**Comment by magicdude4eva** [comment]
Thanks for considering adding it as a feature request.

**Comment by ngarnier** [comment]
Hey @magicdude4eva, we'll look into it but not sure we'll be able to provide a solution because of: 
- what @iRyusa said, technical reason about the `font-size` set to `0` on the `td` that receives the `padding`
- what @dalefish said, poor support of `em` by email clients. MJML's purpose is to generate emails that render well in every major clients, so introducing an attribute that will very likely lead to issues seems counter-intuitive

**Comment by matthewahillman** [comment]
Id love to see some support for em, even if the main things like paddings and margins stay as PX. I'd love to be able to test and try EM values for my text and headings.

**Comment by iRyusa** [comment]
Support it's still the same, there's no real magic that can happens here :/

**Comment by Jukebox7** [comment]
You can use `vw` and media queries if you want 👍

**Comment by tisdall** [comment]
What if you want to respect the person's custom font size settings for accessibility?

**Comment by iRyusa** [comment]
Technically em is "supported" everywhere
https://www.caniemail.com/features/css-unit-em/ . However, for it to work
within MJML, you'll need to reset everywhere the font-size for each
component to ensure it works as expected : it adds a tons of markup would
need to handle a "base" font-size everywhere.
To be fair you can actually do it yourself by just using smart tweak
mj-style inline, but it should add a lot of unwanted behavior in some
clients I think.
