### ISSUE TITLE
Cannot use mj-include inside mj-head

### ISSUE THREAD

**Issue by vbraun** [mjmlio/mjml#509]
Starting with mjml 3.2.0, using mj-include inside mj-head does not work any more. We have a common <mj-attributes> section for multiple emails, each email including it as in
~~~~
<?xml version="1.0" encoding="utf-8"?>
<mjml>
    <mj-head>
         <mj-include path="common-mj-attributes.mjml" />
    </mj-head>
[...]
~~~~
Build does not error out, but prints the somewhat cryptic 
~~~~
Warning: No handler found for: mj-raw, in mj-head, skipping it
~~~~
message and does not include the attributes. This worked with mjml 3.1.1

**Comment by iRyusa** [comment]
Hi @vbraun 

Because we change how that works in 3.2 ! It's weird that it mention `mj-raw` tho..

So now you can just put your mj-attributes inside a mj-head for you common-mj-attributes.mjml like that : 
```xml
<mjml>
  <mj-head>
    // Every head attributes will be includes in main file
   </mj-head>
</mjml>
```

**Comment by vbraun** [comment]
That didn't work for me either. I debugged this a bit and it seems to be because we use mjml2html() in code to render the mjml. Then, in `includeExternal.js`, the `var filePath = _ref.filePath;` is undefined. Then, a few lines further down, `_path2.default.dirname(filePath || process.cwd()` is the parent directory of where we launch from. So all `path=` arguments are not relative to the current directory, but the parent directory of the current directory (this is most likely not intentional).

The second bug is then that `<mj-include path=...` read errors are not errored out (imho exit with code > 0 would be the right thing to do) but replaced with a `'<mj-raw><!-- mj-include: file not found ' + filePath + ' --></mj-raw>';`. Hence the uninformative `Warning: No handler found for: mj-raw, in mj-head, skipping it`.

If I make the `<mj-include path=...` relative to the parent of the current directory then it works, but that can't be the right way of doing things.

**Comment by iRyusa** [comment]
Wait, how do you compile your file with the cli ? The cli should set filePath for you, that's an option that you can pass to mjml2html & mjmlrenderer too.

Ok so now I get it why'd you get a mj-raw inside mj-head ! I add this to add a comment inside mj-body so you do

**Comment by vbraun** [comment]
Just to clarify, I do not use the cli. I'm using my own script that does `import {mjml2html} from 'mjml'` and then calls `mjml2html` in code.

**Comment by vbraun** [comment]
I made #510 to clarify the parent directory issue

**Comment by iRyusa** [comment]
Oh... I didn't seen the cwd was parsed by default I'll merge your PR !

**Comment by iRyusa** [comment]
3.2.2 has been released with your fix ! So I can close this now

**Comment by IchordeDionysos** [comment]
I'm somehow experiencing the same issue ...
But I'm on v3.3.5 
Node - ./testing.js
```
const fs = require("fs");
const path = require('path');
const mjml = require("mjml");

const verifyEmail = fs.readFileSync(path.join(__dirname, "email_templates", "verifyEmail.mjml"), "utf8");
const html = mjml.mjml2html(verifyEmail);
// OUTPUT
// -- Warning: No handler found for: mj-raw, in mj-head, skipping it
```
./email_template/common-head.mjml
```
<mj-attributes>...</mj-attributes>
<mj-style>...</mj-style>
```
./email_template/verifyEmail.mjml
```
<mjml>
  <mj-head>
    <mj-preview>...</mj-preview>
    <mj-include path="./common-head" />
  </mj-head>
  <mj-body>
    <mj-container>...</mj-container>
  </mj-body>
</mjml>
```

What could be the problem here?
Using the CLI it mostly works, but sometimes the same error occurs also there.
With nodeJS I get the error everytime.

**Comment by IchordeDionysos** [comment]
Running mjml like this, works perfectly fine: `.\node_modules\.bin\mjml .\email_templates\verifyEmail.mjml -o
 .\test.html`

**Comment by IchordeDionysos** [comment]
Ok, did some research and found the problem, going to open a new issue.

**Comment by IchordeDionysos** [comment]
#986
