### ISSUE TITLE
passing variable between partial file with <mj-include> tags

### ISSUE THREAD

**Issue by muhammad-ihsan** [mjmlio/mjml#513]
Hi this projects is very helpful, but could you add the feature like passing variable between the partials file with `<mj-include>` tags. Here is a best example what the [Octobercms](http://octobercms.com/docs/cms/partials#partial-variables) did.

sorry for my bad grammar.

**Comment by ngarnier** [comment]
hi @muhammad-ihsan, thanks for the kind words and don't worry about your English, it's perfectly understandable!

We like to keep duties separated, so we won't commit to add templating in MJML, at least for now. Adding templating would mean a lot of overhead to support variables, loops and conditional statements. Here is how we see it:
- MJML is dedicated to make responsive email easy by generating quality responsive HTML for email
- there are a lot of templating engines out there that can be combined with MJML

However, some members of the community are working on custom components to enable that and we can definitely consider featuring them as community components.
