### ISSUE TITLE
Add ability to specify paddings for mj-wrapper

### ISSUE THREAD

**Issue by lessless** [mjmlio/mjml#516]
Hello,

it will be a good option to be able to specify paddings for `mj-wrapper` element. An example use-case might be a need to have a gap between first content tag and container's upper border:

```
<mjml>
  <mj-body>
    <mj-container padding-top="44px">
      <mj-text>Hello</mj-text>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hi there @lessless 

I think it can be easily done with an empty section or section with column and mj-spacer. 

Suporting padding on mj-container this would make us to add a new `table/tr/td` to support it everywhere and it's too much overhead for a simple padding.

We're working on a mj-wrapper that could solve this more easily too ! cf #520 & #255

**Comment by ngarnier** [comment]
hello @lessless, we're introducing mj-wrapper in v3.3.0 (now in beta) that enables you to do just that, so I'm closing. Feel free to answer here still if you have any feedback! 

Example of implementation: https://mjml.io/try-it-live/HJ_-IOv_g

**Comment by lessless** [comment]
Awesome, looking forward to try!
