### ISSUE TITLE
Examples aren't responsive

### ISSUE THREAD

**Issue by Miserlou** [mjmlio/mjml#52]
Is this rendering correctly?

<img width="1375" alt="screen shot 2016-02-12 at 9 04 19 pm" src="https://cloud.githubusercontent.com/assets/139987/13018830/3c72d262-d1cc-11e5-9796-e2607b414854.png">

**Comment by ngarnier** [comment]
Hey @Miserlou, 

I just tried the Kili template and could not reproduce that bug on any browser (including Firefox). Would you mind trying again and let me know if it's still there on your side?

![](http://puu.sh/n8KaB/99d9b9b48e.png)

Cheers

**Comment by Miserlou** [comment]
No longer borked. Can't explain the error.

Closing.

**Comment by arnaudbreton** [comment]
@Miserlou glad it's solved now! Happy MJML-ing!
