### ISSUE TITLE
The --watch option doesn't work with Homestead

### ISSUE THREAD

**Issue by Bartiff** [mjmlio/mjml#524]
Hi,

I work with Vagrant / Homestead on my Mac.
The --watch option works fine when I edit the file directly on my virtual machine. But the changes made from my physical machine don't seem to be detected.

Have you got some idea to help me?

**Comment by iRyusa** [comment]
Hi @Bartiff 

I'm not really sure that it can be fixed due too how watch works with network shared folder. Dunno if the `usePolling` opiton on Chokidar can solve this...

**Comment by Bartiff** [comment]
Ok thank you for your help.
But I don't see how to use Chokidar with MJML.

**Comment by iRyusa** [comment]
Well Chokidar is what we use to provide the `--watch` option on the cli as you can see here : https://github.com/mjmlio/mjml/blob/master/packages/mjml-cli/src/client.js#L148

But this case is really specific and I don't think the guess system knows when the host is modifying the file so I'm not even sure that this option could help

**Comment by ngarnier** [comment]
Hey @Bartiff, did you have the opportunity to look at this? 

We'd really appreciate your help here. Because it's really an edge case and we don't have much experience with Vagrant/Homestead, we won't be able to solve this ourselves.

**Comment by rogierslag** [comment]
Instead of using the standard shared folders in Vagrant, you might want to use the [NFS folders](https://www.vagrantup.com/docs/synced-folders/nfs.html) instead. We've seen an additional incredible boost in performance when reading lots of small files using this approach (not related to MJML though)

**Comment by iRyusa** [comment]
Well. I'm closing this one for now, but any PR on this is welcome. I think @rogierslag comment is the best way to handle this.
