### ISSUE TITLE
Put different images on desktop or mobile

### ISSUE THREAD

**Issue by hypocrisy87** [mjmlio/mjml#525]
Hi, I need to put different image on desktop and on mobile. No background image, but a <img> tag.

For example, on desktop devices:
`<mj-image padding-bottom="0px" padding-top="0px" padding-left="0px" padding-right="0px" src="http://xxx.it/DESKTOP.jpg" href="http://www.xxx.com" alt=""></mj-image>`

and on MOBILE:
`<mj-image padding-bottom="0px" padding-top="0px" padding-left="0px" padding-right="0px" src="http://xxx.it/MOBILE.jpg" href="http://www.xxx.com" alt=""></mj-image>`

How can I do this?

**Comment by ngarnier** [comment]
hi @hypocrisy87, this requires the use of media queries which is not supported right now. It will be in a future update, as detailed here: https://github.com/mjmlio/mjml/issues/420

For now, the only option is to add your media queries in the HTML output manually. To achieve what you want, you'll probably want to:
- have the desktop image and the mobile image one after the other
- use a different class on each of those images (for example, `.desktop-image` and `.mobile-image`)
- display only the appropriate image depending on the device used, using the `display: none` property. 

Does it help? Be careful with this and make sure to test the result, especially on Outlook which will probably also require conditional comments.

I'm closing as we can't solve this directly but it's related to another issue.

**Comment by hypocrisy87** [comment]
Thank you!

**Comment by sicaboy** [comment]
> hi @hypocrisy87, this requires the use of media queries which is not supported right now. It will be in a future update, as detailed here: #420
> 
> For now, the only option is to add your media queries in the HTML output manually. To achieve what you want, you'll probably want to:
> 
> * have the desktop image and the mobile image one after the other
> * use a different class on each of those images (for example, `.desktop-image` and `.mobile-image`)
> * display only the appropriate image depending on the device used, using the `display: none` property.
> 
> Does it help? Be careful with this and make sure to test the result, especially on Outlook which will probably also require conditional comments.
> 
> I'm closing as we can't solve this directly but it's related to another issue.

This way doesn't work in Lotus clients, Outlook (for Windows) clients, AOL Web mail, Yahoo Web mail.

It looks like those client ignored the CSS.

**Comment by Hodakhosravi** [comment]
are there any updates for this issue?

**Comment by GarryFlemings** [comment]
Have you seen https://github.com/mjmlio/mjml/issues/420#issuecomment-287390404?

Don't be too excited/disappointed. The same person said in 2017, https://github.com/mjmlio/mjml/issues/420#issuecomment-278052112: "be careful, media queries are far from being supported in every email clients".

Media queries are part of the language of the web that email authors wish we could use reliably. His words remain true today: Though was can send media queries in email, we know many email clients (say, desktop Outlooks and others) don't respond to them. :(

That's an aspect of email as we know it, not MJML alone.

Welcome among email authors. This probably frustrates all of us.

**Comment by hitautodestruct** [comment]
According to https://www.caniemail.com/search/?s=%40media
It's safe to say that unless you have a complex use case media queries are supported on all mobile mail platforms.

So, a safe bet would be to go desktop first.

**Comment by GarryFlemings** [comment]
Perhaps we don't interpret the data the same. Perhaps we have different definitions of "safe".

I see full support for about one client in three. That feels low to me.

I see no support for about one client in four. Feels high.

I see spotty support for the remaining clients. Some of those clients (note 1) don't support nested media queries), supporting your point about complex "use case media queries". Other notes are specific and could be hard to keep track of while developing.

You do you; it's fine. Please test a lot to confirm your conclusion! And structure your code on your conclusions from the testing.

I can well understand that the MJML team recommends mobile-first development.

**Comment by hitautodestruct** [comment]
@GarryFlemings Thanks for the advise. I test and confirm my conclusions and I get good results.

Regarding full or partial support it's irrelevant, what matters is if you can "Put different images on desktop or mobile", see title of this issue.
To allow that to happen going desktop first is a viable solution according to those stats.

**Comment by GarryFlemings** [comment]
Glad for your success!

Perhaps you're testing with the likes of Litmus, Email on Acid, or Testi? If your readers use more than a couple of email clients, that type of tool saves time.
