### ISSUE TITLE
Button inner padding - Click area

### ISSUE THREAD

**Issue by carloschneider** [mjmlio/mjml#526]
I'm using the inner-padding property on a button. But the click area is smaller than the size of the button as it can be seen in image. The green area is the background button, and the red area is where is the click.

![image](https://cloud.githubusercontent.com/assets/577143/22391132/8175048e-e4d6-11e6-9eab-276b2a22fd32.png)

**Comment by iRyusa** [comment]
Hi @carloschneider 

This is a known issue but there's nothing we can do about it yet. 

There's an open PR on it #452 but we didn't found any solution to keep mj-button compatible across every clients yet. You an find an open issue about that too at #359 so i'm closing this one !

**Comment by iamwalker** [comment]
Is it possible to put the padding on the <a> tag inside?

**Comment by iRyusa** [comment]
Padding wouldn't be applied on Desktop Outlook, so nope
