### ISSUE TITLE
Carousel Issue on Outlook iPhone SE app

### ISSUE THREAD

**Issue by sgforba** [mjmlio/mjml#529]
#Howdy,

Issue: All three arrows appear on the Outlook Mobile client. This was using the code found here: https://mjml.io/try-it-live/components/carousel 

Client: Outlook 2.9.1 on an iPhone SE 

![outlookcarousel](https://cloud.githubusercontent.com/assets/13650963/22528309/b5995bfc-e8a0-11e6-9f69-fb49c377558a.jpg)

**Comment by tyoung23** [comment]
Any updates re: this issue or when we can expect a resolution?

**Comment by ngarnier** [comment]
@tyoung23 not something we're actively working on at the moment, so we don't have any ETA we can give.

**Comment by iRyusa** [comment]
I'm closing for now feel free to reopen if it's still the case Outlook client has been updated for a while now

**Comment by mikemccarron** [comment]
While i know this issues was reported for Outlook i'm seeing it consistently on Apple Mail iOS14 and MacOS as well as Gmail.

**Comment by iRyusa** [comment]
How did you sent your email ? Just tested on iOS 14 and it works just fine.

Try with https://putsmail.com/

**Comment by mikemccarron** [comment]
Okay, it was likely something on my end. We ended up not needing the carousel so I no longer have a test case to provide. I'll circle back if i run into this issue again.
