### ISSUE TITLE
Increasing Text Size on mobile

### ISSUE THREAD

**Issue by APEWAW** [mjmlio/mjml#530]
Hello, 
How to increase text size only on mobile?
Thank you

**Comment by dalefish** [comment]
This is not supported quite yet, I believe it is due in a future version
though.

For now you'll need to either use HTML (in mj-table or mj-raw etc) and
assign a class to be controlled by a media query or using an MJML component
you'll have to add the class in after render.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by APEWAW** [comment]
Dear Dale, 

Thank you for your prompt and uesful reply.
As suggested, I used a mj-class attribute to apply a media query.

Kind regards
