### ISSUE TITLE
Locked = True | Documentation?

### ISSUE THREAD

**Issue by JeffCleverley** [mjmlio/mjml#535]
In the responsive email templates I am finding:

`<mj-section locked="true" />`

But I can't find any mention in the documentation about a boolean attribute called `locked`.

Am I missing something?

Thx

**Comment by ngarnier** [comment]
Hi @JeffCleverley, you can ignore/remove this attribute. It's coming from Mailjet's drag and drop interface where this attribute is used on the front, and this template was adapted from one used in the platform.

**Comment by JeffCleverley** [comment]
OK understood, thx

**Comment by bassbump** [comment]
Was also confused by this, should be removed from the example templates imo

**Comment by ngarnier** [comment]
hi @bassbump thanks for the feedback, I removed all those attributes that aren't used in MJML. 

I also uploaded all the templates in a [email-templates repo](https://github.com/mjmlio/email-templates), so if you see anything else, feel free to submit an issue there or better yet, submit a pull request 🙌

**Comment by davidsanders** [comment]
hi @ngarnier as a quick update, 'amario' template is still showing this property: https://mjml.io/try-it-live/templates/amario

**Comment by kmcb777** [comment]
Hi @davidsanders thanks for reporting this,
We recently fixed all validation errors in these templates so it will be ok in the next website release 👍
