### ISSUE TITLE
How to send responsive mail from gmail and outlook after generating .html file

### ISSUE THREAD

**Issue by Chandu301** [mjmlio/mjml#536]
Hi Guys,

I have taken a sample responsive mail and tried to send it  but they were receiving mobile version mail only 
.
Can anyone say the steps to insert the html content properly in mail.

Thank you.

**Comment by ngarnier** [comment]
Hi @Chandu301, can you please provide us with more information about your issue? This [template](https://github.com/mjmlio/mjml/blob/master/CONTRIBUTING.md#template-for-submitting-bug-reports) in our `contrubting.md` is a good place to start.

Especially: 
- code you're using
- how you're sending
- which email clients you're seeing the mobile version in

**Comment by Chandu301** [comment]
I used online editor in mjml and copied html content and pasted in a file. Then opened html file in browser and copy pasted in gmail and outlook 2010 ..
In both i was getting mobile version only

**Comment by ngarnier** [comment]
Once again, it's easier to help you if you provide us with more information. It's really hard if not.

Despite being confused, I'll still give it a shot. I understand correctly what you're doing, I think it's showing mobile version because you're in the small Gmail window. If you open the pane, you're seeing the desktop version.
![](https://puu.sh/tR90k/304a2baefd.png)
![](https://puu.sh/tR916/ae734b6854.png)

Anyway, this is not a correct way of sending HTML, Gmail will very likely mess with your HTML code. You should rather use a service such as an email service provider or something like https://putsmail.com/.

**Comment by Chandu301** [comment]
Yeah.....the responsive is working fine when i am sending.  But when the client receive's mail(gmail) its not  becoming responsive(he is able to see mobile version only on desktop also).

**Comment by ngarnier** [comment]
Alright, then this must mean you're using a version of Gmail that didn't receive the update for Gmail to handle responsive styles, you can see more details here: https://litmus.com/blog/gmail-to-support-responsive-email-design

MJML is mobile-first, we think it's a better approach to see a mobile layout on desktop than a desktop layout on mobile (it would be unreadable with a need to zoom in an scroll).

As there's nothing we can do against Gmail not handling responsive styles, I'm closing the issue, sorry for the trouble.

**Comment by kliston** [comment]
If you're sending from Outlook, ContactMonkey works great for importing responsive HTML email templates. They have engineered a solution that solves all the issues with sending HTML email from Outlook. Here's more information on how the tool works https://www.quora.com/What-are-some-free-email-clients-which-allow-me-to-manually-code-and-send-HTML-Email-from-an-Outlook-account/answers/88431938

**Comment by FilzaN** [comment]
If you’re looking for a way to send responsive HTML email templates or newsletters from Gmail without the help of a designer, developer or coding knowledge, you should check out ContactMonkey’s solution for sending HTML emails from Gmail.

They have engineered a way in which you can easily create responsive HTML email templates with their easy to use drag and drop builder and then send straight from your Gmail to your mailing lists.

Here’s a step by step guide on sending HTML from Gmail:
https://www.contactmonkey.com/blog/send-responsive-html-email-gmail

This is really great for internal communicators or internal marketers who want to send and track responsive employee newsletters from Gmail!
