### ISSUE TITLE
Table/grid component

### ISSUE THREAD

**Issue by fabien** [mjmlio/mjml#54]
I've seen this being mentioned on Hacker News, but I'm wondering when it will be ready ;-) I'm about to layout some templates that need this functionality. Thanks!

**Comment by arnaudbreton** [comment]
Hey @fabien, could you help us better understand what kind of layout you're trying to achieve?

For instance, looking at our basic layout, featured in the documentation [here](https://mjml.io/documentation/#2-columns-section), what are you missing?

Sorry if I've missed something obvious here. 
Hope we'll be sort it out shortly!

**Comment by fabien** [comment]
@arnaudbreton I believe a table component was in the works already (I think you said so on HN) - I need something like `<table>` without having it to wrap in `mj-raw` tags, and perhaps with some enhancements.

**Comment by arnaudbreton** [comment]
@fabien do you have an example of what we're trying to achieve? As I told you, this is a known limitation of the engine in its current design to require a `mj-raw` to wrap HTML elements. 

Do you have an example - visual or not - of what you're trying to achieve here? Depending on that, defining a custom component might be the way to go.

**Comment by arnaudbreton** [comment]
@fabien would love to review what you're trying to achieve here! Thanks

**Comment by arnaudbreton** [comment]
@fabien closing this conversation for now. Feel free to re-open once you have more time to share your work with us. Thanks!

**Comment by danilockthar** [comment]
> Hey @fabien, could you help us better understand what kind of layout you're trying to achieve?
> 
> For instance, looking at our basic layout, featured in the documentation [here](https://mjml.io/documentation/#2-columns-section), what are you missing?
> 
> Sorry if I've missed something obvious here. Hope we'll be sort it out shortly!

what if i want to put two more columns inside right column ? right now it cannot be done :(
