### ISSUE TITLE
<mj-include> is not recognised

### ISSUE THREAD

**Issue by hirthb** [mjmlio/mjml#542]
Hello !

I have a set of emails in MJML in 2.2.0. I'm trying to rework some of them in 3.2.0 and use the `<mj-include>` tag, however it doesn't seems to be recognise with the validator or the new atom plugin.

I tried with a simple exemple but I receive the same error.

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-include path="./header" />
    </mj-container>
  </mj-body>
</mjml>
```

```
<mj-section>
  <mj-column>
    <mj-text>This is a header</mj-text>
  </mj-column>
</mj-section>
```

`Line 5 (mj-include) — Element mj-include doesn't exist or is not registered`

I also tried with other release but the error keep coming back.
The only way I can make it work is when I put the `<mj-include>` before the `<mj-body>` but only one file is render.

Thank you.

**Comment by iRyusa** [comment]
Hi there,

I don't really understand, it's only an issue with the atom package or with the cli too ?
The `linter-mjml` doesn't support mj-include, so it's normal

**Comment by hirthb** [comment]
It's an issue with the CLI, the ```mjml --validate main.mjml``` return

```Line 4 (mj-include) — Element mj-include doesn't exist or is not registered```

**Comment by iRyusa** [comment]
Can you provide a ls -l within the folder ?

**Comment by hirthb** [comment]
Sure.
```
➜  Digest git:(master) ✗ ls -l main 
total 8
-rw-r--r-- 1 501 dialout 2774 Feb  8 21:01 digest.mjml
-rw-r--r-- 1 501 dialout  632 Feb  7 23:17 header.mjml
```

**Comment by iRyusa** [comment]
Oh right, validate doesn't replace mj-include so that's fine, can you try to render it and tells me if it renders fine ?

**Comment by hirthb** [comment]
Ok my bad, the rendering does work I thought I was stuck with the `--validate`, but the result is correct.
However since I'm using `gulp mjml` to render my files I have to put the relative path from the root of the project. Is it possible to set the `path=""` from `<mj-include>` relative to the `.mjml` file itself ?

Putting `../partial/header.mjml` instead of `./src/MVB/Bundle/MailerBundle/Resources/views/mjml-3.2.0/Digest/partial/header.mjml`

**Comment by hirthb** [comment]
I fixed that by adding a `process.chdir('./src/MVB/Bundle/MailerBundle/Resources/views/mjml-3.2.0')` to the gulp task. Everything is now working correctly.

Thanks for the help :)

**Comment by iRyusa** [comment]
Oh yeah, it could be easily fix by passing option`filePath` to mjml2html with current file you're compiling

**Comment by techdragon** [comment]
I'm getting this issue when I try and render using the `miml` command line. 
Is it possible that the command line doesn't handle this correctly?

**Comment by ngarnier** [comment]
Hello @techdragon, my bet is that you're missing the closing slash `/` using `<mj-include >` instead of `<mj-include />`.

If I'm wrong, can you please provide:
- the markup of the file you're rendering
- the markup of the file you're including
- the version of MJML you're using
- your folder structure (where is the file you're rendering relatively to the file you're including)
