### ISSUE TITLE
Cannot compile using 3.3.0-beta.3

### ISSUE THREAD

**Issue by gabrieltomescu** [mjmlio/mjml#544]
I installed the latest 3.3.3-beta.3 build since I want to take advantage of the ```mj-wrapper``` element. 

However, it looks like I'm unable to compile any mjml files due a permissions error?

Any help would be appreciated!

![image](https://cloud.githubusercontent.com/assets/1161699/22797879/f40d1a4e-eecd-11e6-8091-8893c89ac03e.png)

**Comment by iRyusa** [comment]
Hi @gabrieltomescu !

You should upgrade your node to at least 6.x ! We'll take a look if we can bring back support to for node 4 /  5 for 3.3 release

**Comment by gabrieltomescu** [comment]
@iRyusa Thanks! That worked.
