### ISSUE TITLE
Outlook.com responsive issue possible solution

### ISSUE THREAD

**Issue by vsalvans** [mjmlio/mjml#547]
Hi,

I've come across an issue with Outlook.com. This webmail doesn't accept media queries so it doesn't support responsive mails.

The rendered mail has something like this:

```
...
<style type="text/css">
  @media only screen and (min-width:480px) {
    .mj-column-per-100 { width:100%!important; }
.mj-column-per-33 { width:33%!important; }
.mj-column-per-40 { width:40%!important; }
.mj-column-per-60 { width:60%!important; }
.mj-column-per-50 { width:50%!important; }
  }
</style>
...
```

This is ignored by Outlook.com and accepted by Gmail webmail and app. If I remove the @media statement it will show a desktop version in Outlook.com but a horrible squizzed version in gmail app. 

My solution is this one:

```
<style type="text/css">

.mj-column-per-100 { width:100%!important; }
.mj-column-per-33 { width:33%!important; }
.mj-column-per-40 { width:40%!important; }
.mj-column-per-60 { width:60%!important; }
.mj-column-per-50 { width:50%!important; }

@media only screen and (max-width:480px) {
  .mj-column-per-100 { width:100%!important; }
  .mj-column-per-33 { width:100%!important; }
  .mj-column-per-40 { width:100%!important; }
  .mj-column-per-60 { width:100%!important; }
  .mj-column-per-50 { width:100%!important; }
}

</style>
```

Now it looks ok in all email clients.

Is it possible to implement this solution for a next version? Or is any way to configurate this in order to change manually the output file?

Thanks!

**Comment by ngarnier** [comment]
Hi @vsalvans, thanks for opening this issue and suggesting a solution. 

Outlook.com doesn't support responsive styles, so it's showing the default layout. This default layout is mobile-first, and we think it's the right approach in email as it's better to show a mobile layout on a desktop than a desktop layout on a mobile device (it'd require to zoom in and scroll horizontally as content becomes unreadable). 

This change would also deeply break the layout, cf in Windows 10 Mail for example:
![](https://puu.sh/u1fa4/f2f7b52af4.png)

We're really open to improvements so thanks again for the suggestion, but here it seems it would really hurt the responsiveness of MJML.

**Comment by vsalvans** [comment]
Thanks for the reply 👍 . I understand what you are saying also I agree, but once again developers have to deal with explanations to non-tech staff and customers that think they can have it all in one piece of code. ;-)

**Comment by ngarnier** [comment]
Agreed, dealing with this as well haha! For me, the non-tech answer is: "Because of how some email clients work, you have to chose: do you prefer to show a mobile-layout on a desktop or a desktop layout on a mobile (which is basically unreadable)?"

**Comment by Mohamedderbel90** [comment]
Bonjour.
J'ai un problème, Outlook ne support pas les media queries .
Est ce que quelqu’un peut m'aider SVP !
