### ISSUE TITLE
Gmail media-queries not working

### ISSUE THREAD

**Issue by ubwhole** [mjmlio/mjml#548]
Hello,

I have two Gmail accounts.  For one account, the email is styled correctly but the other it is not.  I compared the styles and I see the `@media` is missing for the one that is styled incorrectly.  

I have tried Try It Live and it renders correctly for both desktop and mobile.  I used FireFox and the email renders incorrectly.

I can take the generated HTML and modify to specify the width to be 50% on the columns.  What can be done besides modifying the HTML output?

Using:
Chrome 56.0.2924.87
FireFox 51.0.1
mjml 3.2.0

## Good Style
![goodstyle](https://cloud.githubusercontent.com/assets/6104293/22868753/f09ff456-f15e-11e6-8f36-1e87c74bd458.png)

Here is the `@media`
![goodstylewithmedia](https://cloud.githubusercontent.com/assets/6104293/22868937/d5f03a92-f160-11e6-812d-58f5ba915831.png)

## Wrong Style

GMail is asking the user to display image. 
![asktoviewimage](https://cloud.githubusercontent.com/assets/6104293/22868752/f09fcaee-f15e-11e6-8be7-199aa3c2bb76.png)

![wrongstyle](https://cloud.githubusercontent.com/assets/6104293/22868754/f0a0a810-f15e-11e6-9d62-9f4a15efd9ca.png)

## mjml
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section border-top="1px solid black"  border-left="1px solid black" border-right="1px solid black" background-color="#f3f3f3">
        <mj-column>
          <mj-image width="170" src="https://cdn.shopify.com/s/files/1/1347/1869/files/montage3.png?6314390148529060628"></mj-image>
        </mj-column>

        <mj-column>
          <mj-image width="270" src="https://cdn.shopify.com/s/files/1/1347/1869/files/crowFly_grande.png?8031454696433051414"></mj-image>
          <mj-text font-weight="bold" align="justify" font-size="24px" color="#000" font-family="helvetica">It's Your Move</mj-text>
          <mj-text align="justify" font-size="15px" color="#000" font-family="helvetica">Use CrowFly to succeed!</mj-text>

        </mj-column>
      </mj-section>

      <mj-section border-bottom="1px solid black"  border-left="1px solid black" border-right="1px solid black">

        <mj-column>
          <mj-image width="59" src="https://cdn.shopify.com/s/files/1/1347/1869/files/9th_c_trim.png?2969905869815691929"
            href="https://leewayusa.com/pages/current-freshman"></mj-image>

          <mj-button background-color="#1B48AF" border-radius="40px" font-family="helvetica" font-size="18px" padding-top="0" href="https://leewayusa.com/pages/current-sophomore">
            Click Here
          </mj-button>
        </mj-column>

        <mj-column>
          <mj-image width="59" src="https://cdn.shopify.com/s/files/1/1347/1869/files/10th_c_trim.png?2969905869815691929"
            href="https://leewayusa.com/pages/current-freshman"></mj-image>

          <mj-button background-color="#1B48AF" border-radius="40px" font-family="helvetica" font-size="18px" padding-top="0" href="https://leewayusa.com/pages/current-sophomore">
            Click Here
          </mj-button>
        </mj-column>

        <mj-column>
          <mj-image width="59" src="https://cdn.shopify.com/s/files/1/1347/1869/files/11th_c_trim.png?2969905869815691929"
            href="https://leewayusa.com/pages/current-freshman"></mj-image>

          <mj-button background-color="#1B48AF" border-radius="40px" font-family="helvetica" font-size="18px" padding-top="0" href="https://leewayusa.com/pages/current-junior">
            Click Here
          </mj-button>
        </mj-column>

        <mj-column>
          <mj-image width="59" src="https://cdn.shopify.com/s/files/1/1347/1869/files/12th_c_trim.png?2969905869815691929"
            href="https://leewayusa.com/pages/current-freshman"></mj-image>

          <mj-button background-color="#1B48AF" border-radius="40px" font-family="helvetica" font-size="18px" padding-top="0" href="https://leewayusa.com/pages/current-senior">
            Click Here
          </mj-button>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by ngarnier** [comment]
Hi @ubwhole, thanks for a very clear and detailed issue 👍 . 

Unfortunately, we can't do anything, as explained [here](https://github.com/mjmlio/mjml/issues/40#issuecomment-278954474) it means the version of Gmail associated to this account doesn't support responsive styles. 

If you manually set the width to 50% in the HTML, it means the desktop version will be shown in mobile clients that don't support responsive styles, which might not be readable (need to zoom in and scroll horizontally). That's why we're taking a mobile-first approach, as a mobile layout on desktop is far more acceptable than a desktop layout on mobile.

I'm closing it as we can't fix Gmail, sorry for that!

**Comment by ubwhole** [comment]
Hey @ngarnier, glad it was concise and thanks for your reply!

These two accounts belong to the same "G Suite Basic" admin.  How is it configured?  From this [article](https://litmus.com/blog/gmail-to-support-responsive-email-design), it seems it is turned on.
