### ISSUE TITLE
<mj-image> not converting properly when inside <mj-wrapper>

### ISSUE THREAD

**Issue by raonicaselli** [mjmlio/mjml#549]
MJML Version: 3.3.0-beta.4

When trying to use a <mj-image> inside a <mj-wrapper> the width and padding are not converted properly from .mjml to .html

If only width is set, then the value is overridden to a negative value (-15) and if padding is set, the width overrides to 19.
![image](https://cloud.githubusercontent.com/assets/5118276/22897964/cdfbcc14-f20c-11e6-9869-638f1618e712.png)

This is my code in .mjml and below is the html generated:
![image](https://cloud.githubusercontent.com/assets/5118276/22898023/fb2a8928-f20c-11e6-814d-e0293acc9cc3.png)

**Comment by iRyusa** [comment]
Hi @raonicaselli 

Thanks for submitting this issue, can you provide the whole MJML document ? I can't seem to reproduce by myself

**Comment by raonicaselli** [comment]
Sure
[example.mjml.zip](https://github.com/mjmlio/mjml/files/780560/example.mjml.zip)

I put it in a zip file to attach here. The only thing missing is my custom componente <mj-credential> but should work without it.

**Comment by iRyusa** [comment]
When removing the custom component it looks fine on mjml.io and in my own setup too. Maybe something is happening with your custom component. Can you try to remove them to see if it works for you too ?

**Comment by raonicaselli** [comment]
I tried to remove the custom component, but the problem persists. And here it only happens when inside an <mj-wrapper>.

**Comment by iRyusa** [comment]
Looks like to work on the try it live with beta 4 tho, here :  https://mjml.io/try-it-live/B1-TSS7Yg

**Comment by raonicaselli** [comment]
Yup, thats true. Then it must be something inside my setup that is creating this error when converting the mjml. On that note, I did get an error when running npm install to update my mjml version. Perhaps it has something to do with my dependencies in package.json
Based on the file I provided, what would you say is missing from my dependencies:
"dependencies": {
    "lodash": "^4.15.0",
    "mjml": "^3.3.0-beta.4",
    "mjml-column": "^3.3.0-beta.4",
    "mjml-core": "^3.3.0-beta.4",
    "mjml-image": "^3.3.0-beta.4",
    "mjml-section": "^3.3.0-beta.4",
    "mjml-text": "^3.3.0-beta.4",
    "react": "^15.3.1"
  }

Should there be an "mjml-wrapper": "^3.3.0-beta.4"  ?

**Comment by iRyusa** [comment]
It doesn't look like you're missing something, can you test this with beta 6 and tell us if it changes anything for you ?

**Comment by iRyusa** [comment]
Hi @raonicaselli Any news on this ?

**Comment by raonicaselli** [comment]
Hi, yes! I found the problem, my gulpfile is somehow generating the html files wrong when I use npm start. I tried with the mjml build command and the file is generated perfectly. I'm trying to see what is happening to the gulpfile and why only the mj-image inside a mj-wrapper was damaged.
Thanks for the help, you can close this issue!
