### ISSUE TITLE
Add height attribute to mj-button

### ISSUE THREAD

**Issue by fabien** [mjmlio/mjml#55]
In order to make perfect pill-shaped buttons, the height should be either explicit, or the border-radius shoud allow % units.

**Comment by arnaudbreton** [comment]
@fabien thanks for sharing! We'll look into it for a future release. 
Meanwhile, we would love to review a contribution from you :)!

**Comment by iRyusa** [comment]
Hi there, `height` is now available on `mj-button` in MJML3 !
