### ISSUE TITLE
allow including arbitrary css files

### ISSUE THREAD

**Issue by apopiak** [mjmlio/mjml#550]
I don't want to copy and paste my css into the `<mj-style>` tag, but instead use a css file that I can link.
Is this possible today, and if not, will this be added soon?

  **Expected behavior:**

  allow e.g. `<link rel="stylesheet" href="email.css">` or `<mj-link rel="stylesheet" href="email.css">` that will be inlined

  **Observed behavior:**

 need to use `<mj-style>[css here]</mj-style>`

**Comment by iRyusa** [comment]
Hi @apopiak 

Can't you just use a regular `mj-include` with `.mjml.css` inside a mj-style ? This could work easily

**Comment by iRyusa** [comment]
Hi @apopiak 

Did you test this solution ? Does it fit your needs ?

**Comment by apopiak** [comment]
Thanks for following up. I will try the suggestion and get back to you.

**Comment by mratz-immonet** [comment]
had the same issue, tried it like this: 

    <mj-style> 
        <mj-include path="./mjml/snippets/head/styles.mjml.css"/>
    </mj-style>

but that didn't work: 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
ReferenceError: Node is not defined
```

**Comment by iRyusa** [comment]
Hi @mratz-immonet 
Can you give more information about your setup (OS/MJML Version/Node Version) ?

**Comment by mratz-immonet** [comment]
sure: MacOS X / "mjml": "^3.1.1" / 3.9.5

**Comment by iRyusa** [comment]
Can you try to update Node to at least node 6/7 please ?

**Comment by mratz-immonet** [comment]
oh wait i checked npm. node is at 6.2.2

**Comment by iRyusa** [comment]
Your error seems totally unrelated from mj-include, I've already seen that error on the Slack but no chance to reproduce on my side can you prove the full template in https://mjml.io/try-it-live please ?

**Comment by apopiak** [comment]
Alright. I tried your suggestion (sorry for the wait) and it's not working.

```
<mjml>
  <mj-head>
    <mj-style>
      <mj-include path="email.mjml.css" />
    </mj-style>
  </mj-head>
  <mj-body>
    ...
  </mj-body>
</mjml>
```

errors with:

```
>> error processing file code/templates/emails/base.mjml
Fatal error: Node is not defined
```

Which leads me to assume that mjml elements are not supported inside of an `<mj-style>`.

**Comment by apopiak** [comment]
node version: `7.5.0`
mjml version: `3.2.0`

**Comment by apopiak** [comment]
@iRyusa

**Comment by iRyusa** [comment]
Well it looks to be fixed in 3.3 branch, can you try with beta 8 to confirm ?

**Comment by dshastry** [comment]
@iRyusa, I'm trying to accomplish the same thing and not working for me either. I'm using MJML app  2.0.1 released a few days ago by @meriadec running MJML 3.3.2. I tried including the code in <mj-head> and <mj-body> but no go on either.

![image](https://cloud.githubusercontent.com/assets/4194561/25537399/ef8add1c-2c03-11e7-97de-402849cc3575.png)

<mjml>
<mj-head>
    <mj-attributes>
          <mj-text color="#666" font-size="12px" font-family='Arial, sans-serif;' font-weight="normal"/>
          <mj-container background-color="#eaeaea" />
          <mj-section background-color="#fff"/>
      		<mj-button background-color="#aac233" text-transform="uppercase" font-weight="600" font-size="14px" border-radius="10px"/>
    </mj-attributes>
        
    <mj-style> 
      <mj-include path="https://dpp-publicassets.s3.amazonaws.com/emails/css/styles.mjml.css"/>
    </mj-style>
  
  	<mj-style inline="inline">
      a{color:#71b8e4; text-decoration:none;}
      #section-title {text-align:left; color:#2e364d; font-size:14px; font-family:'Arial',sans-serif;}
      h5{color:#666; font-size:14px; margin-bottom:0;}
      h6{color:#2a9dc9; font-size:14px; font-weight:600; margin-bottom:0;}
      #phone{margin-top:0;}
      .action-step{font-size:12px; font-weight:800; color:#333; text-align:center; width:75%; margin-left:auto; margin-right:auto; line-height:12px;}
    </mj-style>
</mj-head>

  <mj-body>
    <mj-container>
      
      <mj-include path="./header.mjml" />
      
      
      <mj-section  padding="0">
      <mj-text>
      	<div>
        	<img width="100%" src="https://dpp-publicassets.s3.amazonaws.com/emails/welcome/leads-header.jpg"/>
        </div>  
      </mj-text>
      </mj-section>

            
      <mj-section padding="0" padding-bottom="35px" padding-top="35px">
      	<mj-text>
          <h1 class="email-title"><strong>All New Cohort Analysis</strong><br/>A fresh new way to look at your collection curves. </h1>
        </mj-text>
        <mj-text>
          <p style="width:65%; margin-left:auto; margin-right:auto; text-align:center; margin-top:20px; line-height:16px">Cohort analysis provides meaningful insights into your fee collection based on vintages of your clients. These reports can be customized and filtered to help you identify revenue trends and shortfalls and forecast future receivables. </p><p class="action-step">Here’s a quick overview of what the sessions will cover</p>
        </mj-text>
      </mj-section>
      
      
      
      <mj-section  padding="0" padding-bottom="75px" padding-left="35px" padding-right="75px" padding-top="25px">
      <mj-text>
      <h5 id="section-title">Hi John,</h5>
      <p>Thanks again for your inquiry. DebtPayPro is one of the most powerful and efficient platforms on the market. We've developed great tools to help your business close more deals, collect payments and market to your clients. We look forward to speaking with you soon. We're here to answer your questions, demo our product and show you any specific functionality tailored to your business needs.</p>

<p><span class="action-step">We’ve assigned you a product specialist who will be in touch shortly with next steps.</span><br/><br/>
Sincerely,<br/>
DebtPayPro
</p>
        
      </mj-text>
      </mj-section>
    
      <mj-include path="./help.mjml" />      
     
    
      <mj-include path="./footer.mjml" /> 

    </mj-container>
  </mj-body>

</mjml>

**Comment by iRyusa** [comment]
Hello @dshastry

We don't support external css, you can only include local files with mj-include

btw this issue looks to be fixed in 3.3.x branch so i'm closing it, feel free to open your own issue !

**Comment by dshastry** [comment]
Ah gotcha. Thanks for clarifying @iRyusa!

**Comment by basmbbl** [comment]
@iRyusa what if I'm using a webfont from myfonts? It needs an:
/* @import must be at top of file, otherwise CSS will not work */
@import url("//hello.myfonts.net/count/XXXXXX");

**Comment by iRyusa** [comment]
You can use mj-font, to import font safely, mj-style, mj-raw in head... there's a lot of working solution

**Comment by basmbbl** [comment]
I see, I tried with mj-raw and it worked. 
I was confused by your remark:

> We don't support external css, you can only include local files with mj-include

**Comment by dilawar-unoiatech** [comment]
<mj-section padding="0px">
            <mj-column>
                <mj-text align="center" padding="0px">
                  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
                </mj-text>
            </mj-column>
        </mj-section>

**Comment by xApep** [comment]
Why is there no documentation how to import custom fonts, that are not part of Google fonts?

**Comment by xApep** [comment]
Yeah, it is so intuitive.

Here is a solution for someone who will face the same problem.

Add this to `<mj-head>`
`<mj-raw>
      <link href="domain.com/fonts.css" rel="stylesheet" type="text/css">
    </mj-raw>`

in .fonts.css define `@font-face`

if you have CORS problem, create .htaccess file where you have fonts.css and add

`<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>`

**Comment by iRyusa** [comment]
Don’t use mj-raw like that or outlook will fallback everything to TimesOn 10 Nov 2023, at 12:34, Andraz ***@***.***> wrote:﻿
Yeah, it is so intuitive.
Here is a solution for someone who will face the same problem.
Add this to <mj-head>
<mj-raw> <link href="domain.com/fonts.css" rel="stylesheet" type="text/css"> </mj-raw>
in .fonts.css define @font-face
if you have CORS problem, create .htaccess file where you have fonts.css and add
<IfModule mod_headers.c> <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css)$"> Header set Access-Control-Allow-Origin "*" </FilesMatch> </IfModule>

**Comment by xApep** [comment]
@iRyusa what do you suggest then?

**Comment by iRyusa** [comment]
```xml
 <mjml>
   <mj-head>
     <mj-font name="Raleway"
       href="domain.com/fonts.css" />
   </mj-head>
   <mj-body>
     <mj-section>
       <mj-column>
         <mj-text font-family="Raleway, Arial">
           Hello World!
         </mj-text>
       </mj-column>
      </mj-section>
   </mj-body>
 </mjml>
```

**Comment by alexindevs** [comment]
Happy new year! I'm facing an issue here, where some of my files aren't getting included. I'm using `<mj-incude>` tags, and only one of the files is getting included. I've been facing this issue for a while, and I don't know what to do.
