### ISSUE TITLE
Respecting container width

### ISSUE THREAD

**Issue by martixy** [mjmlio/mjml#552]
I'm not entirely sure if this is by design, or a bug but mjml will not respect container width.

Say this: https://mjml.io/try-it-live/S1J282xKx

Instead of `width="900px"`, we get max-width(in non-`IE | mso` environments).

If this is by design, nevermind the fact that this subverts some very basic assumptions each developer has, how could I make it respect the width I specify?

**Comment by iRyusa** [comment]
Hi @martixy !

This is completely normal and intended. MJML follows Fluid, hybrid & mobile-first approach as described here : https://www.emailonacid.com/blog/article/email-development/a-fluid-hybrid-design-primer

Keep in mind while using MJML, some attributes __do not__ translate directly into CSS attributes
