### ISSUE TITLE
Image group with fixed with on desktop and mobile

### ISSUE THREAD

**Issue by maxbln** [mjmlio/mjml#553]
Hi,

I'am trying to make a simple thing, but it's not working and I've run out of ideas.

I just want to place 8 images centered, side by side - on mobile, they should break in 2 rows, but keep their distance to each other - still centered.

I am here:
https://mjml.io/try-it-live/H1lN4hgKg

But I want to achive this:
![footer](https://cloud.githubusercontent.com/assets/23459640/22939572/692d5b6c-f2df-11e6-83c1-0719e2b8cd40.png)

What the hell am I doing wrong, this should be no rocket science or?

Hope anybody got an idea - and sorry for posting a question instead of a real issue.

**Comment by iRyusa** [comment]
Hi @maxbln 
I think you should use two `mj-column` with `mj-table` for that, the markup will be way cleaner and you'll have way more control over the generated markup

**Comment by maxbln** [comment]
Hi @iRyusa ,
I also tried this, but the effect on mobile was the same. The fixed width is my problem.

**Comment by ngarnier** [comment]
Not sure about what you want to do exactly @maxbln, but here is a suggestion that might help: https://mjml.io/try-it-live/SJWp_hgFl 

If you want absolute control though, as suggested @iRyusa, you might want to use 2 columns with a table in each.

**Comment by maxbln** [comment]
Hi, thanks for this!
both helped me. @ngarnier suggestion worked fine. But I will try yours @iRyusa also later on, just to learn the difference! I will come back after testing in several browsers/providers.

**Comment by ngarnier** [comment]
Awesome, I'm closing as it seems to have solved your issue but feel free to reopen if you encounter any problem

**Comment by maxbln** [comment]
Hey guys,

@ngarnier your suggestion does not work on iphone, so I tried @iRyusa 's - but with mj-table in mj-column I do not get the right positioning:

https://mjml.io/try-it-live/H1zNKm7Ke

Any idea?

**Comment by ngarnier** [comment]
It should work on iOS, I think it's because you used a version of the HTML that isn't minified. According to the [documentation](https://mjml.io/documentation/#mjml-group): 
>  iOS 9 Issue: If you use a HTML beautifier for MJML output, iOS9 will render your columns inside a mj-group as stacked. On the output HTML, remove the blank space between the two columns inside a mj-group.

**Comment by maxbln** [comment]
Hey @ngarnier - I really tried to find out, what you mean by this.
If I take your suggestion (https://mjml.io/try-it-live/SJWp_hgFl) to litmus, it's looking like this:
![iphone6s-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/23459640/23029623/76f0d4ee-f46b-11e6-879d-46cba6346308.png)

Which blank space in the HTML do you mean?
