### ISSUE TITLE
mjml-font not working

### ISSUE THREAD

**Issue by pmacswebteam** [mjmlio/mjml#554]
I am trying to include Google Fonts into my mjml file, however, it seems as if only the "Raleway" font works.

**Comment by dalefish** [comment]
Can you share your (complete) code?

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by pmacswebteam** [comment]
`<mjml>
  
<mj-head>
  <mj-title>Hello world</mj-title>
  <mj-attributes>
    <mj-all />
    <mj-text font-size="16" />
    <mj-font name="Slabo" href="https://fonts.googleapis.com/css?family=Slabo" />
  </mj-attributes>
</mj-head>

<mj-body>
  <mj-container background-color="#EEE">
    
    
    <mj-section background-color="#036" border-right="15px solid #600">
      <mj-column>
        <mj-image src="http://www.med.upenn.edu/pmacsnewsletter/images/psom_logo_white.png" width="213"/>
      </mj-column>
      <mj-column width="100%">
        <mj-text align="center" font-size="18" color="#39C" font-family="Slabo, sans-serif">
          Penn Medicine Academic Computing Services
        </mj-text>
        <mj-text align="center" font-size="32" color="#FFF" font-family="Slabo, sans-serif">
          Newsletter | Winter 2017
        </mj-text>
      </mj-column>
    </mj-section>
    
    
    <mj-section>
      <mj-image src="http://www.med.upenn.edu/pmacsnewsletter/images/front_image.jpg" width="0"/>
    </mj-section>
    
    
    <mj-section></mj-section>
    
  </mj-container>
  
</mj-body>
</mjml>`

Thanks!

**Comment by iRyusa** [comment]
Hi @pmacswebteam !

Your `mj-font` is inside `mj-attributes` that's why it doesn't work, fix : https://mjml.io/try-it-live/HksYGbftg

**Comment by pmacswebteam** [comment]
Hello, I moved it outside of attributes as you suggested, however, the correct google font still is not being pulled in. It should look like this: https://fonts.google.com/?query=slabo

**Comment by pmacswebteam** [comment]
It does not appear to be working in the example you provided here as well:  https://mjml.io/try-it-live/HksYGbftg

Thanks again for your help!

**Comment by iRyusa** [comment]
Hi @pmacswebteam 

Looks like to work on first paragraph, and working on the 2nd when removing `sans-serif`

**Comment by pmacswebteam** [comment]
Hi, I've attached a screenshot of what I'm seeing 
![screen shot 2017-02-15 at 12 28 49 pm](https://cloud.githubusercontent.com/assets/12412403/22986712/66fd90fa-f37a-11e6-8692-fa71de4f73f3.png)

**Comment by iRyusa** [comment]
Ok, I have a Slabo font on this computer that explain it.

But  `https://fonts.googleapis.com/css?family=Slabo` throw a 400, so that's probably why it doesn't apply on your side

**Comment by pmacswebteam** [comment]
Ah, I see what I was missing. Thanks for your help with this!
