### ISSUE TITLE
Individual product table with fixed width

### ISSUE THREAD

**Issue by maxbln** [mjmlio/mjml#555]
Hi guys,

another question.
I have to develop a prodcutteaser, it is looking like this:
https://mjml.io/try-it-live/HJzuWlzFl

It's ok, but it is not exactly like I want to have it.
Actually I want to keep the width of the image fixed at 110px.
But if I do it like this (https://mjml.io/try-it-live/BJ7dKbGFx), the product image disappears on mobile. Why?

In general, is this the right way I build it? It's looking a bit creepy with the mj-text's and mj-tables in the second column.

Thanks for your feedback!

edit:
My code is not working in iPhone - what is wrong? :/

**Comment by dalefish** [comment]
Problem:

 Column inside a group must have a width in percentage, not in pixel

Source: https://mjml.io/documentation/#mjml-group

Single mj-column containing <mj-table> with a forced fixed width first
column is probably your best way to go if it has to be fixed.




Kind Regards,

:----------------------------:
Dale McConnell

**Comment by maxbln** [comment]
This worked perfect! Thank you - close
