### ISSUE TITLE
 is Inheritance in layout planned ?

### ISSUE THREAD

**Issue by thibaultfriedrich** [mjmlio/mjml#558]
I find mjml very good (more specifically with Atom, it is real happiness). But I would like to know if layout extending is planned for the future like for example in twig:

```
{% extends "base.html" %}
```

I think it would be a great future to add. Otherwise do you have any idea how to do it with the current version ?

Thx

**Comment by ngarnier** [comment]
Hi @thibaultfriedrich, thanks for the kind words and glad you like MJML! 

We think MJML should focus on the hard part of responsive email, that is to say valid HTML which renders well everywhere. This is the task of a templating engine and we think it should remain so. If we started adding that in MJML we'd have to support the features of a templating engine (variables, conditionals, loops...).

I can think of two options: 
- [mj-include](https://mjml.io/documentation/#mj-include), more limited than what you want to do but natively supported in MJML
- use a distinct templating engine that you'll render on your MJML template

Hope it helps!
