### ISSUE TITLE
Allow self hosted social icons

### ISSUE THREAD

**Issue by fabien** [mjmlio/mjml#56]
Although it might not be your intention, any email sent out will 'phone home' to one of your servers. Please allow a `base-url` attribute for `mj-social` tags and include the icons in this repo.

**Comment by arnaudbreton** [comment]
Hey @fabien, you're right, we should allow for such behaviour. We'll make sure we allow for it in a future release! Thanks for sharing.

**Comment by iRyusa** [comment]
Hi @fabien 

We're working to improve `mj-social` this week, I'll add an `base-url` attributes !

**Comment by iRyusa** [comment]
Now added `base-url` in `1.2.0` ! Documentation should be updated today

**Comment by 255kb** [comment]
Hi, 

I tried to use `base-url` in a `mj-social` element with multiple social networks but it seems to change all the networks icons, is there a possibility to set the icon url for each social network, like `facebook-base-url`? Thanks

**Comment by iRyusa** [comment]
Hi @255kb,

I suggest you to do a custom network if it's only for one social network ?

```xml
<mj-social display="fb"
fb-content="Share on a awesome network" 
fb-href="http://awesome-network.com/my-company" 
fb-icon-color="#FF00FF" 
fb-icon="http://myicon.png" />
```

**Comment by 255kb** [comment]
I was very happy with the default behavior of the component and did not want to customize everything but I will probably do this. Thanks for the faster than light reply :)
