### ISSUE TITLE
Height issue / Outlook bug with wrapper

### ISSUE THREAD

**Issue by Toww** [mjmlio/mjml#563]
Hello and first of all thank you for the amazing work, I'm new to MJML and GitHub so if there's anything wrong with this post please let me know I'll correct it and hope it is the good place to ask this.

I am having issues with a column height and am searching for the best solution to do something as follows : 

![exemple-section](https://cloud.githubusercontent.com/assets/25932452/23207083/4cc71226-f8f0-11e6-9d65-0f083c1bd27c.jpg)

As you can see in the picture, I have a light blue color for the background of the page, the background of the mj-container is white, and i would like to have a 30px left and right padding to my section.

The mjml code i use for this section (for now) is the following :

```
<mj-section background-color="#bfbd00">
        <mj-column width="245">
          <mj-image width="255" padding="0" margin="0" align="left" src="the-image.jpg" />
        </mj-column>
        <mj-column width="285" padding="0" border="0">
          <mj-image width="128" height="19" align="left" padding-left="20" padding-top="20" src="title-in-image.png" />
          <mj-text color="white"  padding-left="20" padding-top="20">
            <span style="font-weight:bold;">Subtitle</span><br/>Lorem ipsum dolor sit amet, conse tetur adipiscing elit aliquam non condimentum odio, sit amet sagittis.
          </mj-text>
          <mj-button mj-class="fo-button" href="#" padding-bottom="20">
            READ MORE
          </mj-button>
        </mj-column>
      </mj-section>
```

Everything works pretty well using this, but I can't figure out a way to make the left and right padding to my section and keep it white.

I tried making the section background white and give a  background-color only to the column with text in it (the one on the right) but as I can't give it a proper height, i tried giving a bottom padding to the button to make it the same height as the image, works well on navigators but not in outlook.

I use the MJML app V1.7.0 and figured out that I could use the wrapper in mjml 3.3.0-beta.6, but when I used it seems that there are issues with fixed width columns in Outlook (width are the good ones in navigators but in outlook  gives it 50% width to the two columns).

Do you have any idea how I could do this without a wrapper that has padding-left and padding-right set to 30px for my sections ?

Thank you very much,
Toww

**Comment by Honza-B** [comment]
Hi, try this:

```
<mj-body>
  <mj-container background-color="f5f5f5">
    <mj-section padding="0">
      <mj-column background-color="#ffffff">
        <mj-table padding="20px">
          <tr>
            <td height="200px" width="50%" style="background-color: #999999; text-align: center; vertical-align: middle;">iamge</td>
            <td width="50%" style="background-color: #33f333; text-align: center; vertical-align: middle;">text</td>
          </tr>
        </mj-table>
      </mj-column>
    </mj-section>
  </mj-container>
</mj-body>
```
Hope it helps :)

**Comment by Toww** [comment]
@Honza-B , thank you it works great !

Only issue now, is there any way for the text cell to get over or under the image in mobile view ?

**Comment by Honza-B** [comment]
@Toww there is new try with media queries https://mjml.io/try-it-live/rkLJiXhYe

**Comment by Toww** [comment]
@Honza-B Thank you very much for your help and time, it helps a lot!

**Comment by Renjamin** [comment]
This is incredibly useful.  Thank you.

**Comment by ngarnier** [comment]
Thanks @Honza-B for solving this issue, that's awesome :).

I'm closing as I think it's solved but feel free to reopen if it's not the cas @Toww.

Cheers!
