### ISSUE TITLE
mj-wrapper doesn't exist or is not registered

### ISSUE THREAD

**Issue by auzelac91** [mjmlio/mjml#567]
Hi. I have a strange problem. I'm trying to wrap a section with two columns with mj-wrapper but I get this error: 

> Line 32 (mj-wrapper) - Element mj-wrapper doesn't exist or is not registered

My code is basically this:
```
<mjml>
  <mj-body>
    <mj-container>

32:      <mj-wrapper full-width="full-width" background-color="F2F2F2">
            <mj-section background-color="#FFFFFF" vertical-align="middle">
              <mj-column width="50%" vertical-align="middle"></mj-column>
              <mj-column width="50%" vertical-align="middle"></mj-column>
            </mj-section>
          </mj-wrapper>

    </mj-container>
  </mj-body>
</mjml>
```

Installed MJML version is 3.2.2

Am I missing something?

**Comment by dalefish** [comment]
mj-wrapper is introduced in 3.3 beta, it is not available in 3.2.2

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by auzelac91** [comment]
Well, that's good to know.
Then it wouldn't hurt if it was noted in the documentation on the site.

**Comment by auzelac91** [comment]
@dalefish how can I install the beta?

**Comment by dalefish** [comment]
'npm install -g mjml@beta' for the latest version

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by auzelac91** [comment]
Cool, thanks, it works now.
