### ISSUE TITLE
mj-styling.

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#568]
Hi Guys, 

I need to find out how i can use bullet points with the mj text . Something similar to using list-style:disc; with the mj-text i have tried using the mj-style but that doesnt seem to work .

![screen shot 2017-02-28 at 12 18 19 pm](https://cloud.githubusercontent.com/assets/25219824/23401350/0b227760-fdb0-11e6-92b5-3c07f7276cee.png)

Please can you advise me ?

**Comment by dalefish** [comment]
https://litmus.com/community/discussions/1093-bulletproof-lists-using-ul-and-li

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
Hello @lrae24,

`class` is not supported on any `mj-text` or `mj-*` elements. You have to add your class inside a div within your `mj-text`

**Comment by lrae24** [comment]
So if class is not supported  , i am just asking maybe i dont understand but then why does your very own example use it ??
![screen shot 2017-02-28 at 12 43 54 pm](https://cloud.githubusercontent.com/assets/25219824/23402309/b458f8ba-fdb3-11e6-848a-e10e703f263b.png)

**Comment by dalefish** [comment]
That class is applied to a standard HTML element (<a>) within an mj element.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by lrae24** [comment]
Sorry , i missed that thanks guys.
