### ISSUE TITLE
CSS Agnostic Modules for v4

### ISSUE THREAD

**Issue by davegomez** [mjmlio/mjml#569]
I think it is important to create CSS agnostic modules and let the developer decide if the template is mobile-first or desktop-first, this will give more power on the developer over the design of their templates and the compatibility with the email marketing providers edition tools.

**Comment by iRyusa** [comment]
Hi @davegomez

I believe this is a great idea from a feature standpoint, however it’s going to be a pain from a dev standpoint. Every component will have to be tested for mobile first AND desktop first approaches, and make sure to keep the compatibility  for each feature. This will add a lot of overhead and make components hard to maintain & develop. Our main goal with MJML 4 is to improv the performances while keeping the core of MJML intact (minor visual changes) and provide a better developer experience for custom components creations.
This will also allow you to easily create your own components to override default styles (container/section/column) and apply a desktop-first approach if you need to, and then allow anyone to use them.

**Comment by iRyusa** [comment]
I think we can close this for now. It will be to hard to keep both version compliant & available for both desktop first & mobile first approach.

Best way to do this is to create your own custom components with a desktop-first approach if you want to do so.
