### ISSUE TITLE
does the carousel actually works?

### ISSUE THREAD

**Issue by asdrubalp9** [mjmlio/mjml#575]
I've tried the MJ-carousel  and it doesn't work in roundcube client or the gmail/inbox client
also, webfonts doesn't actually work much on the same clients, is there a way to go around this instead of using safe fonts?

**Comment by iRyusa** [comment]
Hi @asdrubalp9 
There's two question here, can you provide some MJML code ? I think Gmail has a backup strategy with hover mode ?

I don't really understand your question about fonts, some clients doesn't accept them so they fallback with the font-family as normal css

**Comment by iRyusa** [comment]
Hi @asdrubalp9 !

Any update on this ?

**Comment by iRyusa** [comment]
Feel free to reopen if you can provide more feedback about this ! Thanks
