### ISSUE TITLE
Image inside column overflow in multiple column

### ISSUE THREAD

**Issue by cytsunny** [mjmlio/mjml#578]
I have copy and paste the HTML generated in online editor to PHP code and sent through SMTP.

The following is my code:
https://mjml.io/try-it-live/Hyjtys85l

and in Gmail (in Chrome on Windows 10) it looks like:
![image](https://cloud.githubusercontent.com/assets/3927120/23546015/badc0b50-0038-11e7-8d05-af22936ef790.png)

It works fine in Gmail mobile client, but crash in desktop client.

**Comment by ngarnier** [comment]
Hi @cytsunny , oh that's weird, thanks for reporting.

Seems like there's an issue with Gmail on Litmus now, I can't get the images to load (works fine on other email clients) so I can't test.

Can you try to set a width on your image, like `width="200px"` to see what happens?

**Comment by cytsunny** [comment]
![image](https://cloud.githubusercontent.com/assets/3927120/23547985/63f654f0-0040-11e7-9f3c-a916be49d83d.png)

Well, it follows the setting and let the width to be 200px, but at the same time seems that the default margin of mj-text is gone.

And for extra information, according to developer tools of Chrome, the container is 600px and the top single column image is 550px.

**Comment by ngarnier** [comment]
Hey @cytsunny, thanks for the answer.

It appears it's a regression that had been introduced in the beta of v3.3.0, it should be fixed in v3.3.0-beta.8. Can you confirm?

![](https://puu.sh/uyhd8/2c7d3a506d.png)

**Comment by cytsunny** [comment]
I didn't install MJML as I don't have node.js installed in my machine. (I tried but there are some error during installation)  I just use your online editor and copy the HTML generated as a base code. I then further add my PHP code into the generated HTML by myself. If it is not on the online editor yet, sorry I cannot help testing.

**Comment by ngarnier** [comment]
Alright, it's not on the website yet indeed but from my tests it's solved. Maybe you can join the Slack (https://slack.mjml.io/) and I can try to help you on setting up NodeJS :)

**Comment by cytsunny** [comment]
Thanks for your invitation, but I guess I will leave the installation later. I maybe changing my machine soon and may be able to install normally following the official guide on my new machine. 

I trust your testing result and look forward to use the latest version on the online editor. If you want more testing, I may still help testing if you send me the HTML generated.

**Comment by ngarnier** [comment]
MJML v3.3.0 is out, fixing this issue! Thanks again for reporting. 

To install: `npm install mjml`
