### ISSUE TITLE
Displaying *real* full width 

### ISSUE THREAD

**Issue by cemremengu** [mjmlio/mjml#585]
I understand that you are using fluid hybrid email style but, for example, I want to be able create a template to send a report to users (we have an internal enterprise product) with a table with about 10 columns. 

With 600px of max width, this is impossible and I believe it is limiting the capability of MJML for just business/ad type of emails. I understand that it may not look great on mobile but I just wish that the width was customizable.

**Comment by ngarnier** [comment]
Hi @cemremengu, indeed we're using the fluid-hybrid method so the container width is set. However, you can set the container width to anything you want, for example  `<mj-container width="1400px">` and add 10 columns (even if I wouldn't recommend it).

Here's what it would look like: https://litmus.com/builder/documents/1400740/edit#start-test

Does it answer your question?

**Comment by cemremengu** [comment]
@ngarnier The link seems to be broken

**Comment by ngarnier** [comment]
My bad, can you try with: https://litmus.com/checklist/emails/public/a1a8aa1?

**Comment by cemremengu** [comment]
Interesting I remember fiddling with container width and it did not budge then after checking #552 I lost hope.

Now it works as I expected. Thanks for your quick response and great work!

**Comment by john-osullivan** [comment]
Does the fluid-hybrid method imply that there's no way to set the email to simply take 100% of the client's window?

**Comment by ngarnier** [comment]
hey @john-osullivan, indeed the container width needs to be fixed

**Comment by grebebird** [comment]
Seems as though playing with container width again doesn't allow for more than 600px. Am I missing something?

**Comment by ngarnier** [comment]
@grebebird, this is because the iframe used to render the HTML on the try it live is fixed to 600px. However if you take the HTML and open it in your browser, you'll see the container is indeed 900px.
