### ISSUE TITLE
Images were cropped

### ISSUE THREAD

**Issue by maxbln** [mjmlio/mjml#586]
Hi guys,

I got a problem with the following mjml: https://mjml.io/try-it-live/Bk01i2Cqg

Everything looks nice, but in Outlook 2011 and 2016, the images were cropped and the headlines were placed side by side :/
In all other devices/providers it looks perfect.

![outlook-2016_mac](https://cloud.githubusercontent.com/assets/23459640/23748991/427afd96-04c6-11e7-864f-698c9209b024.png)
![outlook-2016_win7](https://cloud.githubusercontent.com/assets/23459640/23748989/427875ee-04c6-11e7-895a-06b2e852ed6b.png)
![ol2010-vertical-allowed-1366](https://cloud.githubusercontent.com/assets/23459640/23748990/4279de66-04c6-11e7-88b1-80934c161808.png)

Where is the error with the mjml?

**Comment by iRyusa** [comment]
Hi @maxbln !

Here's what you've missed : 
- Remember to add `mj-column` even if you only have one in your `mj-section` 
- You should reset the `line-height` on every `td`

So you can see the result here : https://mjml.io/try-it-live/BkCzraR9e and it looks OK on litmus now 👍

**Comment by maxbln** [comment]
Perfect, this worked.
But mj-column doesn't work in sections, where I place mj-hero or mj-divider because it placed a non  controlling padding, see here: https://mjml.io/try-it-live/B1skApR9l - or?

**Comment by iRyusa** [comment]
Well mj-column does live inside section this is how you should use `column`cf https://mjml.io/documentation/#getting-started

`mj-divider` has default padding as mentioned in https://mjml.io/documentation/#mjml-divider , adding `padding="0"`  on `<mj-divider />` solve this

Note that `mj-hero` is like a section, so it shouldn't be inside a `section`

**Comment by iRyusa** [comment]
@maxbln I'm closing this issue for now, as it looks to be solved !
