### ISSUE TITLE
Removing space between columns

### ISSUE THREAD

**Issue by r3gression** [mjmlio/mjml#587]
I have to remove the column spacing on the footer (see attachment), but for the life of can't figure out how to do this. I've tried all padding options, but to no avail.

Layout in question:

![3awxxvx](https://cloud.githubusercontent.com/assets/13783646/23770782/b8f1718c-0514-11e7-8db3-133d8f74d560.jpg)

What I'm trying to achieve:
![newsletter_dersepa](https://cloud.githubusercontent.com/assets/13783646/23770919/59296b14-0515-11e7-9bfe-14c932047590.jpg)

The code: 

`<mjml>
  <mj-head>
    <mj-font name="Roboto Slab" href="https://fonts.googleapis.com/css?family=Roboto+Slab:700" />
  </mj-head>
  <mj-body>
    <mj-container>

      
      <mj-section background-url="file:///Users/onno/Library/Containers/com.apple.mail/Data/Library/Mail%20Downloads/7EC2E357-C476-4BD9-B27B-CC2D2AA82287/Untitled-1.jpg" background-size="120% 100%" background-repeat="no-repeat">
        <mj-column>
          <mj-text font-family="Roboto Slab" font-weight="1000" color="white" font-size="25px">
            <h1 font-size="800px" color="#FFFFFF">NICHT</h1>
            <h1 font-size="800px" color="#FFFFFF">IMMER IST</h1>
            <h1 font-size="800px" color="#FFFFFF">WENIGER</h1>
            <h1 font-size="800px" color="#FFFFFF">MEHR. WIR</h1>
            <h1 font-size="800px" color="#FFFFFF">GLAUBEN</h1>
            <h1 font-size="800px" color="#FFFFFF">MEHR IST</h1>
            <h1 font-size="800px" color="#FFFFFF">MEHR!</h1>
          </mj-text>
        </mj-column>
      </mj-section>

      

      <mj-section background-color="#fcc703">
        <mj-column>
          <mj-image align="left" width="300" height="145" src="http://i.imgur.com/EcvAC9d.png" />
        </mj-column>
      </mj-section>

      
      <mj-section padding-top="0" background-color="#fcc703">

        <mj-column>
          <mj-text padding="0px 0px 0px 0px" font-family="Roboto Slab" font-weight="1000" align="center" font-size="20px" letter-spacing="none">
            <h1 font-size="800px" color="#FFFFFF">Jetzt bis zu 50% sparen.</h1>
            <h1 font-size="800px" color="#FFFFFF">Mit der</h1>
            <h1 font-size="800px" color="#FFFFFF">Deutschland Combo</h1>
            <h1 font-size="800px" color="#FFFFFF">Deluxe!</h1>
            <h1 font-size="800px" color="#FFFFFF">Nur 39,95 &euro;</mj-style></h1>
          </mj-text>
          <mj-button padding-top="50px" padding-bottom="0px" width="250px" height="35px" border-radius="30px" font-family="Helvetica" color="white" font-size="20px">
            JETZT SPIELEN
          </mj-button>
          <mj-text padding="0px 0px 0px 0px" font-family="Roboto Slab" align="center">
            <h1>
            € 25 MIO. EUR
            </h1>
          </mj-text>
        </mj-column>
      </mj-section>
      

      <mj-section padding="0" background-color="#fcc703">
        <mj-column>
          <mj-divider border-style="solid" border-color="#eb8b03" border-width="1px">

          </mj-divider>
        </mj-column>
      </mj-section>
      
      <mj-section padding="0"  background-color="#fcc703">
          <mj-column padding-left="50px">
            <mj-image src="http://i.imgur.com/5pJI2Gz.png" />
          </mj-column>
          <mj-column>
            <mj-image src="http://i.imgur.com/SmjyJt1.png" />
          </mj-column>
          <mj-column>
            <mj-image src="http://i.imgur.com/CFw1ogS.png" />
          </mj-column>
          <mj-column>
            <mj-image src="http://i.imgur.com/W9CnCNo.png" />
          </mj-column>
          <mj-column>
            <mj-image src="http://i.imgur.com/iQYRMEk.png" />
          </mj-column>
      </mj-section>
      
      <mj-section background-color="#fcc703">
          <mj-column>
            <mj-text align="center" color="#eb8b03">
              <p>O LOREM IPSUM TEM VINDO A SER O TEXTO </br> PADAO USADO POR ESTAS INDUSTRIAS DESDE O ANO DE 1500</p>
            </mj-text>
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>`

Thanks in advance.

**Comment by iRyusa** [comment]
Hey @r3gression 

If I understood correctly you're talking about those images on the footer right ? If so, `mj-image` has default padding, so you might want to remove/modify it ? Note that `mj-column` doesn't support padding.

**Comment by r3gression** [comment]
Didn't work, but modifying the compiled version's CSS did the trick.
Thanks for the help though.

**Comment by ngarnier** [comment]
Thanks for the feedback @r3gression, as your problem seems solved I'm closing the issue!
