### ISSUE TITLE
Cheerio.load is not a function

### ISSUE THREAD

**Issue by farhansalam** [mjmlio/mjml#588]
Hi, I am getting while using the `mjml-core` library, I am using webpack to build my system. This error comes after building the project, and I am using the `bundled` code inside another .js file.
```
var $ = cheerio.load('', { decodeEntities: false });
                ^
TypeError: cheerio.load is not a function
```

**Comment by iRyusa** [comment]
Hi @farhansalam 

Thanks for reporting this, but as said in #274 ( https://github.com/mjmlio/mjml/issues/274#issuecomment-275666319 ) supporting browser imply lot of tweaks to make it works on both browser side & NodeJS. As MJML4 is around the corner, we totally stop to patch things to make MJML compatible in the browser.

What I suggest is to keep MJML related stuff away from the browser build, and use either MJML Api or something similar in your project
