### ISSUE TITLE
column not stacking and going to 100% on mobile 

### ISSUE THREAD

**Issue by adamjw3** [mjmlio/mjml#591]
Title says it all really so i just provide my code for the component and a screen shot of what is happening. I have the below code snippet in the other mjml, mj-body, mj-container tags

![screenshot-mjml](https://cloud.githubusercontent.com/assets/367147/23863737/67bbacfa-0808-11e7-820d-85e06cebaf13.jpg)

```xml
<mj-section> 
        <mj-column>
            <mj-image src="http://placehold.it/600x469/000/fff?width=600" href="http://www.syndicut.com" width="600" padding="0 10px 0 0"/>
            <mj-text>
                <span class="heading">Header</span>
                <span class="para">Fermentum est venenatis ex facilisis, quis bibendum lacus faucibus. Pellentesque vulputate auctor libero, ac maximus lacus mollis eget.</span>
            </mj-text>
            <mj-button href="/" align="center">
                Button
            </mj-button>
        </mj-column>
        <mj-column>
            <mj-image src="http://placehold.it/600x469/000/fff?width=600" href="http://www.syndicut.com" width="600" padding="0 0 0 10px"/>
            <mj-text>
                <span class="heading">Header</span>
                <span class="para">Fermentum est venenatis ex facilisis, quis bibendum lacus faucibus. Pellentesque vulputate auctor libero, ac maximus lacus mollis eget.</span>
            </mj-text>
            <mj-button href="/" align="center">
                Button
            </mj-button>
        </mj-column>
    </mj-section>
```

What i want them to do on mobile is stack and have the images 100%

**Comment by ngarnier** [comment]
Columns stack by default so this is what should happen as you can see here: https://mjml.io/try-it-live/B1FiUBVsl. Or did I misunderstand what you want to do?

![](http://g.recordit.co/p2otez7bdF.gif)

**Comment by adamjw3** [comment]
Hi @ngarnier just after i posted on here i tried it in the "try it" and get the the result you have. do you know why i'm not seeing this in my build? i'm using the grunt task if that helps

**Comment by iRyusa** [comment]
Hi @adamjw3 can you share the HTML being rendered ? and how did you test it ?

**Comment by adamjw3** [comment]
Hi @iRyusa I'm just testing it in the browsers (chrome). I've attached the generated html.
[component-content.zip](https://github.com/mjmlio/mjml/files/838892/component-content.zip)

**Comment by iRyusa** [comment]
It works fine on my chrome, your screenshot doesn't look like to be under the mobile breakpoint (480px) can you confirm that ?

**Comment by adamjw3** [comment]
You are correct, haha. think i had too many tabs open. Is one thing, when you do go below 480px my images don't span full width. i've attached a screenshot
![screenshot-mjml](https://cloud.githubusercontent.com/assets/367147/23864844/ae4e61be-080b-11e7-9a94-408dba77ba16.jpg)

**Comment by iRyusa** [comment]
This is a known issue, and atm we didn't find any fix on that. You can see more details here : #263

**Comment by adamjw3** [comment]
@iRyusa how come it works if i put it in the mjml editor https://mjml.io/try-it-live

**Comment by ngarnier** [comment]
The width of `mj-image` is calculated according to the desktop version. To illustrate roughly, the width of the image will be equal to:

- its container width if there is one column
- its container width / 2 if there is two equal columns
- its container width / 3 if the image is contained in a 33% column
- etc

We can't set the width of the image to 100% because of lack of support in Outlook.

The result of the image totally scaling up you're seeing in the try it live is actually a bug introduced in the beta version the try it live is running on, it's fixed in beta.8 (cf https://github.com/mjmlio/mjml/issues/578). 

I'm closing as it's a known issue: https://github.com/mjmlio/mjml/issues/263

**Comment by adamjw3** [comment]
I found a guide on creating your own components. Is it possible to create a custom component to get round this issue?

**Comment by ngarnier** [comment]
hey @adamjw3, you could totally create your own image component and use a different HTML indeed! If you find a nice workaround, feel free to share, we might reintegrate it into MJML :)

**Comment by Rick8rooke** [comment]
Im having this problem with 2 mj-column inside a section. The surrounding table is not set to 100% width so the images do not scale up. Is there a fix for this yet?

```
<mj-section>
    <mj-column>
       <mj-image src="pic.jpg" />
    </mj-column>
    <mj-column>
       <mj-image src="pic.jpg" />
    </mj-column>
</mj-section>
```
