### ISSUE TITLE
Compiling mjml string via command line

### ISSUE THREAD

**Issue by traykovn** [mjmlio/mjml#595]
I want to compile an mjml template from a string in PHP. So, let's say I have a variable `$mjml` that contains an mjml template. I want to achieve this: 

`$html = shell_exec("mjml $mjml");`

I know I can use the API, but I don't want, because the emails can contain sensitive data, which goes to the network back and forth.

Do you plan implementing it? If you have another solution, could you please share it.

Thanks!

**Comment by iRyusa** [comment]
Hi @traykovn 

You could use `stdin` with `-i` option ?

**Comment by traykovn** [comment]
Like this: `$html = system("mjml -i $mjml");`?

**Comment by iRyusa** [comment]
I'm not really a PHP dev, but you could use something like proc_open, http://php.net/manual/fr/function.proc-open.php

**Comment by traykovn** [comment]
Thank you for your answer! I managed to run it, but now I have the following error: 

> Line 6 (mj-wrapper) — Element mj-wrapper doesn't exist or is not registered

I installed mjml like this: `npm install -g mjml`. The current version is 3.2.0. Why mj-wrapper doesn't exist and why should I register it. I googled it but didn't find a solution.

**Comment by iRyusa** [comment]
`mj-wrapper` is a MJML 3.3.X feature, so if you want to install the beta add `@beta` to your npm install cmd

**Comment by traykovn** [comment]
I installed 3.3.0-beta.8. I have the following error:

> TypeError: path must be a string or Buffer
>     at Object.fs.open (fs.js:548:11)
>     at fs.writeFile (fs.js:1200:6)
>     at C:\Users\ntraikov\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-cli\lib\helpers\promesify.js:35:17
>     at C:\Users\ntraikov\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-cli\lib\helpers\promesify.js:34:12
>     at C:\Users\ntraikov\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-cli\lib\client.js:108:35
>     at process._tickCallback (internal/process/next_tick.js:103:7)

I think this is a bug, because my code looks ok.

**Comment by iRyusa** [comment]
Your command might miss a `-s` to tell MJML that you want to redirect the output into the stdout.

**Comment by traykovn** [comment]
It works! I thought only `mjml -i` is enaugh. Thank you very  much!

**Comment by Cool-and-Deadly** [comment]
Wondering if it's possible to compile a mjml template string on the command line like @traykovn suggested. I couldn't find anything in the docs here: https://github.com/mjmlio/mjml/tree/master/packages/mjml-cli

**Comment by iRyusa** [comment]
Just use stdin as mentioned in the doc here ?
