### ISSUE TITLE
(mj-link) — Attribute text-transform is illegal

### ISSUE THREAD

**Issue by mattez** [mjmlio/mjml#596]
This code

`<mj-link href="link" text-transform="none">Link text</mj-link>`

returns error _(mj-link) — Attribute text-transform is illegal_.

Why? Attribute text-transform is legal on _mj-link_. See https://mjml.io/documentation/#mjml-navbar

Node: v7.5.0
mjml: 3.3.0-beta.8

**Comment by ngarnier** [comment]
Hello @mattez, you're right, thanks for reporting. It's a validation error only so the attribute will still work on the component, you can ignore it until we fix it.

**Comment by ngarnier** [comment]
https://github.com/mjmlio/mjml/releases/tag/3.3.3
