### ISSUE TITLE
Please publish npm update for new mj-wrapper

### ISSUE THREAD

**Issue by teddis** [mjmlio/mjml#598]
Hi, MJML noob here, love the project. I'm using mj-wrapper but the latest npm package 3.2.2 doesn't include it. Prefer to use npm instead of importing the project. Release ETA?

**Comment by ngarnier** [comment]
Hi @teddis, glad you love MJML! [3.3.0](https://github.com/mjmlio/mjml/releases) (in which wrapper was introduced) is currently in beta. We'll release it in the next days/at the latter next week. 

In the meantime, you can install the beta with `npm install mjml@beta`

Cheers!
