### ISSUE TITLE
Replace special characters such as `{{`, `}}`, `<%`, `%>`, `$` by a placeholder before compilation to avoid Juice to crash (infinite loop)

### ISSUE THREAD

**Issue by ngarnier** [mjmlio/mjml#601]
This should solve: 
- https://github.com/mjmlio/mjml/issues/487
- https://github.com/mjmlio/mjml/issues/427
- https://github.com/mjmlio/mjml/issues/410

**Comment by iRyusa** [comment]
Will be fix with #607

**Comment by ngarnier** [comment]
It's now fixed!

**Comment by yuniorsk** [comment]
Hi guys, first of all thanks a lot for a great work. I noticed that in #607 dollar sign is not among problematic chars so it's still get escaped.  Do you plan to add it there? Thanks
