### ISSUE TITLE
mj-text is the equivalent of div / Which element for span ? 

### ISSUE THREAD

**Issue by sinsunsan** [mjmlio/mjml#609]
I would like to have an inline equivalent of mj-text that allow to use 
mj-class on inline element for example 

```
<mj-text mj-class="text">
     <mj-text-inline mj-class="black"> My black</mj-text-inline > <mj-text-inline mj-class="blue">& blue title </mj-text-inline >
</mj-text>
```
The equivalent of 
```
<div class="text>
    <span class="black"My Black</span><span class="blue">& blue title</span>
</div>
```

Of course I can add span inside mj-text, but the mj-class do not work on normal elements it seems

**Comment by iRyusa** [comment]
Hi @sinsunsan 
I don't really understand the need of it.

You can just add simple span inside mj-text and use regular class with `mj-style` like that

```xml
<mj-style>
.foo { color: green; }
</mj-style>
<mj-text>
  <span class="foo">Hey !</span>
</mj-text>
```

**Comment by sinsunsan** [comment]
ok, it is because I did not knew mj-style that is more that the css classes actually.

So mj-class add inline style on mj- elements 
and mj-style add inline style on normal html elements ? 

using the class system  that is translated when compiling in html to inline style.
Is this correct ? 

Adding a class on a mj-element won't work 
adding a mj-class on a html eement won't work

**Comment by iRyusa** [comment]
`mj-class` allows you to add `mj-attributes` a MJML element like `mj-text`

`mj-style` no longer inline by default regular css on HTML element, everything define in `mj-style` can be use __only__ with HTML elements. If you want to inline it you can pass `inline="inline"` to mj-style.

**Comment by sinsunsan** [comment]
To better undesrtand, mj-attributes is only for mj element and the only  way  to style them 

<mj-text class="foo">
will not be evaluated ?

mj-text and other mjml elements  
Could be styled only with attributes ? 

What is inside the mj-text.... (span, ul li...) element are up to us and could be styled normally with css styles..
and managed with the mj-style element

**Comment by iRyusa** [comment]
For now, yes. There's a proposal to add `css-class` on any mj-element that should comes with 3.3.2

**Comment by sinsunsan** [comment]
ok thanks :)
