### ISSUE TITLE
Error with generated custom component with ES6 import + decoractors

### ISSUE THREAD

**Issue by epayet** [mjmlio/mjml#61]
When using the template generated by the command `mjml --init-component product`, it generates this:

```javascript
import {
  elements,
  registerElement,
  MJMLColumnElement
} from 'mjml'
```

...

```javascript
@MJMLColumnElement({
  tagName: 'mj-product',
  content: ' ',

  /*
   * These are your default css attributes
   */
  attributes: {
    'color': '#424242',
    'font-family': 'Helvetica',
    'margin-top': '10px'
  }
})
class Product extends Component {
...
}
```

When I do `babel-node Product.js`, I have this error:

```
var Product = (_dec = (0, _mjml.MJMLColumnElement)({
                                                  ^
TypeError: (0 , _mjml.MJMLColumnElement) is not a function
```

The only way I got it to work was to change 

```javascript
import {
  elements,
  registerElement,
  MJMLColumnElement
} from 'mjml'
```

to this

```javascript
import {
  elements,
  registerElement
} from 'mjml'

var MJMLColumnElement = require('mjml').MJMLColumnElement.default
```

I believe this has something to do with the babel decorator plugin and es6 imports, I tried with `transform-decorators-legacy` and `transform-decorators`, same result.

What are your thoughts on this? Thanks

**Comment by arnaudbreton** [comment]
Hi @epayet, thanks for reporting. We'll look into it and come back to you with a solution.

Thanks for your patience!

**Comment by epayet** [comment]
This has been fixed by [this commit](https://github.com/mjmlio/mjml/commit/6a79d95934eaa36c91ff57008c514789b04bba6c).

However, the same rule applies for `MJMLElement`.
Take a look at my [pull-request](https://github.com/mjmlio/mjml/pull/88) to resolve this.
