### ISSUE TITLE
social media icons update

### ISSUE THREAD

**Issue by Fanetteg** [mjmlio/mjml#611]
Hi,
Could it be possible to add the most up-to-date social media icons for mj-social ?

Instagram : https://en.instagram-brand.com/assets
Facebook (seems fine but I'm not sure it's the latest version) : https://en.facebookbrand.com/assets
Pinterest : https://business.pinterest.com/en/brand-guidelines
Twitter : https://brand.twitter.com/

:)

**Comment by ngarnier** [comment]
Makes total sense, thanks for submitting @Fanetteg! Lots going on with MJML v3.3.1, v3.3.2 and v4  but we'll update it in v3.3.3 :)

**Comment by Fanetteg** [comment]
Cool. Thanks for the answer!

**Comment by kukac7** [comment]
do you plan to use your own icons (image)?

**Comment by ngarnier** [comment]
Sorry for the delay on this, it's finally here :-) https://mjml.io/try-it-live/components/social
