### ISSUE TITLE
Any way to use mj-class and mj-style inside custom components?

### ISSUE THREAD

**Issue by PickRelated** [mjmlio/mjml#613]
Hi!
I wonder if I can use styles inside my custom component. I have not found any class to import in my js files.
When using `Raw` to output basic <style> tag, gulp-babel is not happy about css syntax.
Thanks!

P.S. The only way I can think of is as follows:

```javascript
const styles=`
  <style type="text/css">
    .red-text {
      color: red;
    }
  </style>
`;

return (
  <Text>
    { styles }
    <mj-text class="red-text">This text should be red</mj-text>
  </Text>
);
```

However, it produces unwanted `,` on it's output.

**Comment by iRyusa** [comment]
Hello !

It's not available in a custom component, but you can use a post render for this. You can check the code inside mj-column.

**Comment by PickRelated** [comment]
Thank you! I will try that out tomorrow. Looks like it will work.

**Comment by PickRelated** [comment]
Yep, it works for me. Thank you very much!
