### ISSUE TITLE
how to customize mjml-table text based on value 

### ISSUE THREAD

**Issue by xiaomaosusie** [mjmlio/mjml#616]
Hi iRyusa, 

I'm a business analyst. Very excited that MJML helped me build email alerting for business. I mostly used table, wondering how I can use JS to color table texts by value in MJML. Any suggestions or tricks are highly appreciated!! 

Thank you so much,
Susie

**Comment by iRyusa** [comment]
Hi @xiaomaosusie !

Well, you can't use plain JS inside an email, every major clients are stripping it. There are two ways to do:
- You can set some css class with `mj-style` like `red, yellow, green` and apply the css class on your table.
- Or if you're familar with JavaScript, you can develop your own custom component that can do that for you automatically, here's a good start if you chose this path : https://medium.com/mjml-making-responsive-email-easy/tutorial-creating-your-own-mjml-component-d3a236ab7093#.hpsffiq7q

**Comment by xiaomaosusie** [comment]
Hi @iRyusa ,

Thanks for your quick response!! Really helpful!! 
- my tables are automatically generated...applying a class will be manual work...so I'll give up this solution for now.
- This is a great idea. I'd love to work on it...

Thumbs up to you guys!!

Thanks,
Susie
