### ISSUE TITLE
Same MJML-generated HTML results in different view b/w desktop vs. mobile

### ISSUE THREAD

**Issue by xiaomaosusie** [mjmlio/mjml#619]
Hi Team,

I noticed a change. A week ago (on 3/15), I applied some CSS using mj-style. MJML-generated table looked same  b/w desktop (outlook 2016) and mobile (iphone outlook).   Over the week, I made some changes to mj-body and mj-style. When I regenerated email, it applied CSS correctly in either browser or mobile outlook, but lost CSS style in desktop outlook. Do you know what might be causing this? 

iphone mobile version (same if I click destop version to be viewed in browser) 
![image](https://cloud.githubusercontent.com/assets/8771027/24372688/c0742792-12fc-11e7-9d57-afaa4ac7ee5f.png)

but the desktop outlook version is off. shading and text-alignment are gone. 
![image](https://cloud.githubusercontent.com/assets/8771027/24372716/d2e9634c-12fc-11e7-80f3-1aaaf1c6ba47.png)

current MJML template screenshot:
![image](https://cloud.githubusercontent.com/assets/8771027/24372765/0aca62d4-12fd-11e7-8e67-d8e1674fbff8.png)

Thank you so much for diagnosing this issue!

Best,
Susie

**Comment by xiaomaosusie** [comment]
I also noticed the old HTML version actually insert mj-style to each tr/th/tb tag like below:
![image](https://cloud.githubusercontent.com/assets/8771027/24373157/7172abc6-12fe-11e7-9c3d-4684c59d53c0.png)

However, the most recent HTML version leaves mj-style at Header, tr/th/tb doesn't have style attribute:
![image](https://cloud.githubusercontent.com/assets/8771027/24373200/961c4860-12fe-11e7-9df7-292039c61d8e.png)

Shall this cause outlook desktop doesn't apply CSS settings? If yes, is it because that I did something stupid here causing style not applied for tr/tb/th? 

Thanks,
S

**Comment by iRyusa** [comment]
Hello @xiaomaosusie 

We did change something in 3.3, `mj-style` will no longer inline by default. You can set `inline="inline" on `mj-style` to get the old behaviour.

**Comment by xiaomaosusie** [comment]
@iRyusa awesome!! thank you so much!!

Feel free to close out this ticket!

Best,
Susie

**Comment by xiaomaosusie** [comment]
Please hold off closing this ticket..I just tried and it wasn't working...Let me investigate...

Thanks,
Susie

**Comment by iRyusa** [comment]
Can you share the template generated by your template on mjml.io so we can take a look ?

**Comment by xiaomaosusie** [comment]
Hi @iRyusa : it's all set now. It worked beautifully!! Thank you so much!!

Best,
Susie
