### ISSUE TITLE
Out of dated instagram logo

### ISSUE THREAD

**Issue by aliajoudanian** [mjmlio/mjml#621]
Hey guys,
you are using an old version of Instagram logo. Would you please update resource?

I Also attached a new version logo PNG file.

[instagram.zip](https://github.com/mjmlio/mjml/files/874517/instagram.zip)

**Comment by iRyusa** [comment]
Hi @aliajoudanian ! 

Thanks for reporting this ! There's already an issue for that see #611 and it should be fixed for `3.3.3` release.

I'm closing this one !
