### ISSUE TITLE
Could you add mj-class to span ?

### ISSUE THREAD

**Issue by Mijer** [mjmlio/mjml#625]
Hi guys,

We have adopted MJML's tools in our compagny. It helped us so much for all of our emails... we don't have much time to spend into email's development, and MJML is a good solution to solve this issue.

Anyway, after many emails developped with MJML, I noticed that if we could give an mjml-class to span could accelerate even more the time needed.

Do you think it's a possible add ?

Cheers,
Jeremy.

**Comment by ngarnier** [comment]
Hey @Mijer, why not use `mj-style` to add custom css inside and define a real CSS class that you can then use on `span`?

**Comment by Mijer** [comment]
Allright, thanks @ngarnier ! I just tried, and it work well 👍  !
The mjml code is much less messy now :)

**Comment by ngarnier** [comment]
Perfect, happy your code got cleaner 😎 !
