### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open './/'

### ISSUE THREAD

**Issue by sebastienthibaud** [mjmlio/mjml#628]
Hello,

I get the following issue when I try to execute mjml commands :

```
$> mjml source.mjml 
Error: EISDIR: illegal operation on a directory, open './/'
    at Error (native)
```

OS : Mac OS X Sierra 10.12.4
Node v4.1.2
npm v4.4.4
mjml v3.3.0

Thank you in advance.

**Comment by iRyusa** [comment]
Hello, 
Please update your node to >= 6.X, it will fix it

**Comment by sebastienthibaud** [comment]
Thank you very much 👍
