### ISSUE TITLE
Render with max-length 255 charaters for each line

### ISSUE THREAD

**Issue by smatoox** [mjmlio/mjml#629]
Hello,

I'm beginner with MJML and I tried to render an example template and I see in html file (rendered) lines with more than 255 characters.

This limit is still true for emails ?
And how to make config to limit render at 255 characters max each line ?

Thanks a lot.

**Comment by ngarnier** [comment]
Hi @smatoox, 

There is no such limitation in HTML email. This 255 characters limitation can be found on certain clients or proxies, impacting GET requests, but nothing to do with HTML emails.

Therefore I'm closing!
