### ISSUE TITLE
100% width images on mobile

### ISSUE THREAD

**Issue by mike-warning** [mjmlio/mjml#630]
I have 2 column layout with an image in each column.  On Desktops I want space between the images but on mobile (when columns are stacked) I want to the images to be the full width of the column.  

How is this achieved?

**Comment by fusion27** [comment]
@mike-warning Can we please see your MJML?

**Comment by iRyusa** [comment]
Hi @mike-warning 

ATM we don't support full width image with `mj-image`. This is something we're working on for MJML4. We have an open issue on this, see : #263 so I'm closing this one

**Comment by zecka** [comment]
I was looking fot that and it's seems to be done now ! #1323

```html
<mj-image width="300px" src="https://www.online-image-editor.com//styles/2014/images/example_image.png" fluid-on-mobile="true" />
```
