### ISSUE TITLE
Desktop version showing on safari mobile

### ISSUE THREAD

**Issue by sordespilosus** [mjmlio/mjml#631]
Hi all

I create issue, as well Nikolas asked me.

So, I download node.js, install it, install al packages, install plugin for Sublime, edit PATH. Its work ok, mjml file was create, and compiletd markup was output in html file.

Next, i get mjml code from you live preview (https://mjml.io/try-it-live/ryQglRCng), and paste in my mjml file, and do output in html. Open result on mobile device, and result page is not adaptive:

![s70403-175003](https://cloud.githubusercontent.com/assets/7858237/24615139/258f0aea-1896-11e7-8c46-3f0fd24c2648.jpg)

Page just scaling to fit on my mobile device.

But in your  live preview page look like that:

![screenshot-mjml io 2017-04-03 17-52-46](https://cloud.githubusercontent.com/assets/7858237/24615271/802c3dec-1896-11e7-82e1-cb5435d50d66.png)

What i do wrong? Why same code in your preview adaptive, but in my page is not?

Thank you for help and sorry for my english. I never learn it before.

**Comment by fusion27** [comment]
@sordespilosus let's see your MJML

**Comment by iRyusa** [comment]
Hi @sordespilosus !

Thanks for reporting this, it looks to be solved when adding a meta viewport

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

We'll see if it break something on any clients/device to add this

**Comment by sordespilosus** [comment]
@iRyusa, yes, is it! Thanks!

i thought this meta added automatically, and dont cheked compiled html attentively )

now i continue research this))

**Comment by sordespilosus** [comment]
@iRyusa, if i manually paste meta name="viewport" in compiled html, and edited mjml source-file, framework delete this string in html after output. How can i fix, or patched this?

Thanks!

**Comment by iRyusa** [comment]
You can dirty patch it in the `node_modules/mjml-core/lib/configs/defaultContainer.js` and add the meta viewport.

**Comment by sordespilosus** [comment]
@iRyusa thanks!

Its release bug, or i install something wrong?

**Comment by iRyusa** [comment]
It's a bug in current MJML version, should be fix in 3.3.1 👍

**Comment by sordespilosus** [comment]
@iRyusa, thanks! I'll be wait 3.3.1 release)

**Comment by ngarnier** [comment]
Hello, 

Thanks for reporting @sordespilosus, it's now fixed (`npm install mjml` to update).
