### ISSUE TITLE
mj-image inside a mj-text

### ISSUE THREAD

**Issue by seb306bzh** [mjmlio/mjml#632]
Hi Everybody,

I want to insert an image in the text ok my email like this 👍 

`<mjml>
  <mj-body>

    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>text before <mj-image width="30" src="http://www.online-image-editor.com//styles/2014/images/example_image.png" /> and after img</mj-text> 
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

but the image disappears ! why ?
https://mjml.io/try-it-live/rJCJx1epl

How can I do that ?

Thanks

**Comment by iRyusa** [comment]
Hello @seb306bzh ,

You can't nest mj-elements inside `mj-text`. You can only use regular HTML in it, so use `<img>` and it will work fine !

**Comment by seb306bzh** [comment]
Ok was simple ...
Thanks !
