### ISSUE TITLE
Inline images using base64

### ISSUE THREAD

**Issue by codevincedev** [mjmlio/mjml#633]
Hello,
I'm not sure if this is the right place to submit this question. I'm looking for some guidance or opinions about inline images using base64 encoding

```<img src="data:image/jpg;base64,.....'" />```

in emails.

I'm having issues, not related with **MJML**, and I think, based on my search and some info about email clients policies, it's not a good idea.

What do you think?

_PS. Don't hesitate to close this if you think it's not the "appropiate forum" for this._

**Comment by g0ddish** [comment]
Unrelated to MJML this has terrible client support
https://www.campaignmonitor.com/blog/email-marketing/2013/02/embedded-images-in-html-email/

**Comment by codevincedev** [comment]
Yeah, that's one of the places I've landed. The article is a little bit old but I guess it's still valid.
Thanks for your answer.

**Comment by iRyusa** [comment]
Well, you shouldn't doing that. Using base64 image could lead to too large emails and some clients either reject it or crop the email
