### ISSUE TITLE
@media queries not working for responsive images on gmail

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml#635]
I've been trying to show/hide images via media queries. Renders as I want it in the MJML mac/web app and works fine for most clients but fails when opening in Gmail (web/android). Gmail hides image in desktop mode but on device/responsive stacks both images regardless of a display none!important; on the desktop images. MJML Code attached, screenshots attached :

Edit: github doesn't seem to be pasting my mjml code inside the markdown tags. attached as txt

[email.txt](https://github.com/mjmlio/mjml/files/903116/email.txt)

MJML App Previews
![mjml desktop](https://cloud.githubusercontent.com/assets/4194561/24762806/0def66de-1ab5-11e7-9d27-a120eb317213.png)
![mjml mobile](https://cloud.githubusercontent.com/assets/4194561/24762821/1877f044-1ab5-11e7-9ca9-4d2d2fb047b9.png)

Gmail Render
![gmail desktop](https://cloud.githubusercontent.com/assets/4194561/24762836/2775352a-1ab5-11e7-9f21-7ffa60e10dc0.png)
![gmail android](https://cloud.githubusercontent.com/assets/4194561/24762794/0442a68c-1ab5-11e7-9adb-8711fd2834e1.png)

**Comment by iRyusa** [comment]
Hi @dshastry !

Looks like putting your style in `mj-head` works on Litmus ( https://mjml.io/try-it-live/r1nc-1Eae )

Beware `rem` aren't supported everywhere and could probably break in some clients.

![image](https://cloud.githubusercontent.com/assets/570317/24763244/15b285a4-1af1-11e7-8dbb-4ab8cc013aae.png)

**Comment by dshastry** [comment]
Thanks for the quick response @iRyusa! Sorry still a little confused, are you recommending moving all styles into the head? I made that change but still not seeing what you're seeing in litmus. 

Followed your try it live link and it has the same issue in the preview.

Updated code attached with all styles in mj-head and replaced rem values with px. Issue continues to be persistent in real gmail app/web interface but not in MJML previews or litmus

[email.txt](https://github.com/mjmlio/mjml/files/903707/email.txt)

Sidenote: this is my first post here and I just wanted to say thanks for being so helpful! Much appreciated 😃

**Comment by dshastry** [comment]
also on live.com the desktop styles do not display. mobile only view presented and many styles missing. Again, same issue, tests fine on litmus but real browser display is different.

Screenshot attached:
![live](https://cloud.githubusercontent.com/assets/4194561/24771869/e0e5f408-1ad4-11e7-8f12-62c1dca95a30.jpg)

**Comment by dshastry** [comment]
also on live.com the desktop styles do not display. mobile only view presented and many styles missing. Again, same issue, tests fine on litmus but real browser display is different.

Screenshot attached:
![live](https://cloud.githubusercontent.com/assets/4194561/24771918/12ef4954-1ad5-11e7-9936-8810b79fd599.jpg)

**Comment by iRyusa** [comment]
Outlook.com doesn't support media queries so that's normal. You can target it with [owa] selector. And I believe you have the newer version of outlook.com

Dunno why you still have an issue with your gmail app, and I have no android devices so I can't help you more with this. How are you sending your email ? Did you try with putsmail.com ?

**Comment by ngarnier** [comment]
Regarding Gmail, you're probably using Gmail Android app with a POP/IMAP account @dshastry? Have a look at [this recap by Litmus](https://litmus.com/blog/gmail-to-support-responsive-email-design).

Note that the technique you're using is really not safe, as you can't rely on good support for showing/hiding different content on email clients.

**Comment by dshastry** [comment]
Gotcha @ngarnier Thank you both for the feedback. For now I'm defaulting back into using a single image across desktop/mobile. 

But as you can see the MJML Group tag is also breaking and only showing mobile on some desktop clients. Is this because of a lack of client specific tags (eg: OWA) in my code or just a known limitation of the group tag?

**Comment by ngarnier** [comment]
Can you please be more specific about `mj-group` breaking (reference in your code and which clients it's break in) so we can look into what's wrong?

Also, I see a lot of `mj-group` used with only one column inside in your code so I think you might have misunderstood the idea of this component. `mj-group` objective is to prevent columns from stacking on mobile and forcing them to stay side by side. Example: https://mjml.io/try-it-live/components/group

**Comment by iRyusa** [comment]
So I think we did solve everything here. I'm closing this issue, feel free to reopen if needed!
