### ISSUE TITLE
Online editor not showing email larger than 600px even on desktop version

### ISSUE THREAD

**Issue by cytsunny** [mjmlio/mjml#636]
The iframe for desktop preview on online editor is just 600px width. For email wider than 600px, changes is not changed because of this width limit. Should be set to 100% for better preview?

**Comment by maxgironcodes** [comment]
The iframe's width threw me off, as well. If I use the online editor and apply a pink background to mj-container, it looks as though the body is supposed to be white and unaffected. So I was confused when both the body and mj-container were pink in local development.

**Comment by ngarnier** [comment]
The iframe width was extended to 800px

**Comment by cytsunny** [comment]
I wonder if this can be counted as solved?

So when I have a email larger than 800px, the problem will still come back. I would expect an editor that allow infinite width.

But I understand that you may not want to put too much effort into the online editor, as to you it may just be a place for first try and you would expect us to download the real stuff if we like it (which is not true to me at least, I am using it to share the email template to my designer. Instead of teaching her how to install the MJML, a link to online editor is really much easier) I see that you can handle shirking to smaller size very well, so at least set the value to a big number, like 3000px, to handle the common cases?

**Comment by iRyusa** [comment]
Why don't you give a try to the MJML App ? It seems to fit perfectly your need. 

The try it live is just a "demo" editor with limited set of feature.

**Comment by ngarnier** [comment]
Here is what a 600px wide email would look like in a 3000px wide iframe...

![](https://puu.sh/Aa0eH/3209925f9e.png)

I think it's reasonable to consider that most emails aren't wider than 800px.
