### ISSUE TITLE
nested sections for drop shadow

### ISSUE THREAD

**Issue by MrLoh** [mjmlio/mjml#637]
I'm experimenting with creating a drop shadow by nexting tables with `padding="1px"` as suggested [here](https://www.campaignmonitor.com/forums/topic/5421/drop-shadow-whole-email/). But the linter tells me that nested sections or wrappers are not allowed in MJML, is there any proper way to do this?

**Comment by ngarnier** [comment]
Hey @MrLoh, you can wrap sections inside a `mj-wrapper`. I'm not sure to understand your need, can you provide a design of what you're trying to achieve?

**Comment by iRyusa** [comment]
Hey @MrLoh 

I don't think this technique is doable with current section/wrapper implementation. I think you'll have to do a custom `mj-section` to support this behaviour.

**Comment by iRyusa** [comment]
Well @MrLoh I'm closing this one because we can't provide any help on this. If you want to create a drop shadow with this technique you should create a new component for it, so i'm closing this issue 👍
