### ISSUE TITLE
Image width is set to 100px when container is set to 100%

### ISSUE THREAD

**Issue by JstnEdr** [mjmlio/mjml#640]
I'm trying to display a full-width image in my mjml template. I'm able to achieve this if the `mj-container` is set to the default 600px. However, if I set the container `width="100%`, for some reason, the image width is set to 100px. The resulting HTML file seems to suggest the column is being resized to 100px. 

Is this a bug, or am I doing something wrong? 

Here is my code: 
```
<mjml>
  <mj-body>
    <mj-container background-color="#FFF" width="100%">
      <mj-section full-width="full-width" padding="0px">
        <mj-column width="100%">
          <mj-image src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Clint_Eastwood_-_1960s.JPG" alt="Course Navigator" padding="0px"> </mj-image>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hi @JstnEdr  !

As mentioned on the documentation here : https://mjml.io/documentation/#mjml-container we don't support `%` on mj-container. So I'm closing this issue because we won't support `%` for `mj-container`
