### ISSUE TITLE
MJ-social component breaking in outlook/live mail online

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml#642]
MJ social component renders fine on gmail, ios and default mail clients on mac but breaks in outlook/live mail online. 

  **Reproduction Steps:**

Use MJML Social component. Code I used below:

                    <mj-social align="right" padding="5 20" mode="horizontal" border-radius="20px" display="linkedin:url facebook:url twitter:url " linkedin-content="" facebook-content="" twitter-content="" linkedin-icon-color="transparent" facebook-icon-color="transparent" twitter-icon-color="transparent" facebook-href="dpp" google-href="dpp" twitter-href="dpp"/>

  **Expected behavior:**

List of social icons rendered aligned right

  **Observed behavior:**

 Properly rendered in most mail clients except outlook online. Layout breaks and icons randomly stacked vertically

  **Screenshots and GIFs**

Live.com
![image](https://cloud.githubusercontent.com/assets/4194561/25143554/86ca35e6-2430-11e7-8cea-a57def52db8f.png)

Gmail
![image](https://cloud.githubusercontent.com/assets/4194561/25143694/010f343c-2431-11e7-9143-f1ffa503d91d.png)

iPhone
![img_0006](https://cloud.githubusercontent.com/assets/4194561/25143729/22c0de32-2431-11e7-885f-20d39fb6f345.PNG)

  **MJML version:**

3.3.0

  **Email clients the bug is seen on:**

Outlook/Live Mail Online

**Comment by bago** [comment]
Put there real web urls instead of "dpp" and outlook will be more happy.

**Comment by dshastry** [comment]
Ok that seemed to work @bago. Thanks!! 
![image](https://cloud.githubusercontent.com/assets/4194561/25145075/ad8e52e8-2435-11e7-963e-c9b642ce0eeb.png)

But it still seems to be breaking to two lines as opposed to floating on the same line as the logo. Noticed the Outlook conditionals are forcing the logo and the social icons to be width=100%. I'm using columns so I'd assume it would respect the widths defined. Code below:

<mj-section background-color="#2a9dc9" padding="0" padding-top="15px">
        <mj-column width="25%">
          <mj-text><img class="footer-logo" src="https://s3.us-east-2.amazonaws.com/dpp-public-temp/email/logo-white.png" width="100"/></mj-text>
        </mj-column>
        <mj-column width="75%">
                    <mj-social align="right" padding="5 20" mode="horizontal" border-radius="20px" display="linkedin:url facebook:url twitter:url " linkedin-content="" facebook-content="" twitter-content="" linkedin-icon-color="transparent" facebook-icon-color="transparent" twitter-icon-color="transparent" facebook-href="https://www.facebook.com/debtpaypro/" linkedin-href="https://www.linkedin.com/in/debtpaypro/" twitter-href="https://www.twitter.com/debtpaypro/"/>
          
        </mj-column>
      </mj-section>

**Comment by bago** [comment]
Outlook will see the "mobile" version of mjml. You can use mj-group if you want them to be on the same line also on mobile. Otherwise you have to "accept" outlook limits with mjml generated code.

**Comment by iRyusa** [comment]
Hi @dshastry !

As @bago (btw thanks for the awesome support you've provided !) said Outlook will only have the mobile version of the email because we can't differentiate mobile & dekstop Outook.com . You can read more of it here : https://emails.hteumeuleu.com/what-you-need-to-know-about-the-new-outlook-com-8d2c54719398 ! 

Note that you can still target every Outlook.com with OWA selector, then you have to duplicate the content of media query with `[owa]` selector, but mobile version will be shown as desktop on this client.
