### ISSUE TITLE
-- (double dash) in comment error in Thymeleaf

### ISSUE THREAD

**Issue by pglotov** [mjmlio/mjml#644]
`defaultContainer.js` has this part around line [8](https://github.com/mjmlio/mjml/blob/c0b287eeb08ee7bbebea3411640611eefc57b398/packages/mjml-core/src/configs/defaultContainer.js#L8)

```

<title>__title__</title>
  <!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

The middle line generates error as apparently there shouldn't be double dashes in comments. Should this be fixed? If so I can submit a PR.

**Comment by bago** [comment]
How do you propose to FIX this whithout breaking the "reverse conditional comment"?

**Comment by iRyusa** [comment]
Hi there @pglotov 

It allows to fix some image issue on Live mail see https://www.emailonacid.com/blog/article/email-development/prevent-ie-edge-meta-tag-from-breaking-images-in-live-mail and you can see related issue here : #306
