### ISSUE TITLE
inserting opening <div> with <mj-raw>

### ISSUE THREAD

**Issue by pglotov** [mjmlio/mjml#645]
I'm trying to prepare a Thymeleaf template and need to have a conditional div. I'v tried to do

```
<mj-raw>
 <div th:if="${shouldItBeHere}">
</mj-raw>
<mj-section>
 <mj-column>
  <mj-text>It Should</mj-text>
 </mj-column>
</mj-section>
<mj-raw>
 </div>
</mj-raw>
```

But in the resulting html the `div` inside `mj-raw` gets closed with a `</div>` before `<mj-section>` starts. Is it possible to achieve what I'm trying to achieve with `<mj-raw>`?

**Comment by iRyusa** [comment]
Hi @pglotov 

This will no longer be an issue in MJML 4, in the meantime you can use this trick (credit to @dalefish) : 

```xml
<mj-raw>&lt;div&gt;</mj-raw> 
<mj-section>
  <mj-column>
    <mj-text>It Should</mj-text>
  </mj-column>
</mj-section>
<mj-raw>&lt;/div&gt;</mj-raw>
```

**Comment by pglotov** [comment]
That works, thanks a lot!
