### ISSUE TITLE
mj-wrapper and outlook

### ISSUE THREAD

**Issue by janegbert** [mjmlio/mjml#648]
Wrapping multiple `mj-section`'s in an `mj-wrapper` produces an undesirable result in multiple versions of MS Outlook. The `mj-wrapper` width is 600px in Outlook, but the `mj-section` is also 600px. It seems to me that the padding for the wrapper is not taken into account here. Also the width of images inside mj-sections wrapped by mj-wrapper (with padding) should probably be recalculated in MJML.

**Comment by ngarnier** [comment]
Hi @janegbert, I'm having trouble understanding what you mean, maybe you could attach some code and visual elements to illustrate your point?

Wrapping multiple sections and adding a padding on `wrapper` should be working fine, here's a live example: https://mjml.io/try-it-live/components/wrapper

**Comment by janegbert** [comment]
Thanks for the feedback @ngarnier. I'll try again:

Adding padding on the mj-wrapper component results in a too wide newsletter in Outlook.

**Reproduction Steps:**

1. Define to sections and wrap one of them in mj-wrapper
2. Add `padding="24"` to mj-wrapper
3. Test result/HTML in Outlook

**Expected behavior:**

I would expect the wrapper to be 600px wide (MJML default).

**Observed behavior:**

In Outlook the wrapper ends up being 636px wide.

**Screenshots and GIFs**

![The result in Outlook](https://image.ibb.co/gQkcrQ/wrapper.png)

**MJML version:**

v. 3.3.0

**Email clients the bug is seen on:**

Outlook 2013

**Comment by ngarnier** [comment]
Ha, thanks a lot! I edited my answer after rereading your post but you saw it in the meantime. Anyway, thanks a lot for this detailed issue, it makes the problem very clear which is useful for tracking.

**Comment by iRyusa** [comment]
This is now fixed in MJML4 branch

**Comment by ngarnier** [comment]
Should be fixed in the last beta so I'm closing: install with `npm install mjml@next`.
