### ISSUE TITLE
Default MJML styles in head cause Gmail to strip all style blocks

### ISSUE THREAD

**Issue by joeforshaw** [mjmlio/mjml#649]
By default MJML puts the following style block into `<head>`:
```
  <style type="text/css">
    @media only screen and (max-width:480px) {
      @-ms-viewport {
        width: 320px;
      }
      @viewport {
        width: 320px;
      }
    }
  </style>
```

Gmail has recently added partial support for style blocks in head, however it appears nested `@`s will cause all style blocks in head to be removed (see no. 5 in https://www.emailonacid.com/blog/article/email-development/12_things_you_must_know_when_developing_for_gmail_and_gmail_mobile_apps)

More of an FYI, but was also curious to know if there's any possible work around for this other than removing the above style block.

**Comment by ngarnier** [comment]
Hi @joeforshaw, 

Thanks for opening this issue. We're actually putting this style in an isolated `style` at the end of the `head` of the email, so Gmail is not stripping the other styles needed for responsive.

As explained in the article: 
> One way to deal with this is to use multiple style blocks and put the styles that are Gmail safe in the top block.

You can see that a MJML template (here [Racoon](https://mjml.io/try-it-live/templates/racoon)) renders well on Gmail: https://litmus.com/checklist/emails/public/bf208cb#chromegmailnew

I think my answer solves the issue you raised so I'm closing but feel free to answer if you disagree!

**Comment by hansnolte** [comment]
Hi ngarnier,

I have the same problems as joeforshaw.
That's why I tested the racoon template you suggested.

![racoon-gmail](https://user-images.githubusercontent.com/7922627/33797424-c74f76a4-dd07-11e7-980e-fa0461f57c38.jpg)



Has anything changed on Gmail or is it on my client (Thunderbird 52.5.0) and sent via GMX.

Win 7
MJML App v2.7.0
MJML v3.3.3

**Comment by iRyusa** [comment]
Hi 
`sent via GMX.`

You should send it through an esp or something like putsmail. Sending it through a webmail will alter the html

**Comment by hansnolte** [comment]
Hi iRyusa,

many thanks for your fast feedback.
Then I should finally create a Mailjet account.

Thank you for your help
Hans

**Comment by ganlanyuan** [comment]
Hi, 
I encountered the same problem.

When I send through [mailchimp](http://mailchimp.com/) (my business use this service)
 or [thumderbird](https://www.thunderbird.net/en-US/), gmail strips the `<style>` tags in `<head>`, makes the layout broken in Gmail Desktop.

While it's fine when I send it through putsmail or litmus.

I can't persuade my company switch the mail service, what can I do?

**Comment by iRyusa** [comment]
> gmail strips the <style> tags in <head>

Gmail doesn't strip style tags in head for a while now. Try to contact the mailchimp support to see if they have a way to not alter the HTML, it's not really an issue from MJML.

**Comment by ganlanyuan** [comment]
@iRyusa Thanks for your fast response. 
I will reach out to mailchimp to see if they can do this.
