### ISSUE TITLE
Navbar component issue in Outlook 2010 / 2013

### ISSUE THREAD

**Issue by Loac-fr** [mjmlio/mjml#650]
Hello,
after a few days of discovering this great tool, I came across this bug when testing in Litmus.
I tried to recreate it from your try it live example and got the same result :

![navbar](https://cloud.githubusercontent.com/assets/6583342/25346697/a14a727c-2918-11e7-8a49-d1a28a89f386.png)

instead of stacking properly, the links extend outside the container. Here is the correct output (Outlook 2011 & others)

![navbar_2](https://cloud.githubusercontent.com/assets/6583342/25346771/ddb36f70-2918-11e7-9df9-f58920c566f4.png)

and here is the code (copy-pasted from the try it live editor)

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-navbar background-color="#ef6451">
        
        <mj-column >
          <mj-inline-links base-url="https://mjml.io">
            <mj-link href="/gettings-started-onboard" color="#ffffff">Getting started</mj-link>
            <mj-link href="/try-it-live" color="#ffffff">Try it live</mj-link>
            <mj-link href="/templates" color="#ffffff">Templates</mj-link>
            <mj-link href="/components" color="#ffffff">Components</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
          </mj-inline-links>
        </mj-column>
      </mj-navbar>
    </mj-container>
  </mj-body>
</mjml>
```

Do you have something in mind regarding this issue ? I'd really like to make this work with the navbar component as it's working perfectly everywhere else...
Thanks a lot

Loic

**Comment by iRyusa** [comment]
Hi @Loac-fr 

Well this is a limitation of `mj-inline-links` indeed. To know why it happens, you need to understand how it works. 

`mj-inline-links` use `display: inline-block` on `a` element to inline every link. `display: inline-block` isn't supported on Outlook 2013/16/etc so we have to add a `table` within outlook conditionnals.

Problem is, there's no way to know when we have to break the line for outlook, we can't estimate the space taken from each `mj-link` so we can't put a new `tr` in Outlook conditionnals. So I don't think we can fix this, you can add a `</tr><tr>` manually in this HTML (even if it's not the best solution).

**Comment by Loac-fr** [comment]
Thanks for the explanation ! Makes sense.
Is there a way I can add it (the <tr></tr>) inside mjml (between two <mj-link> elements) or do I need to do it after it is compiled ?

**Comment by iRyusa** [comment]
Not the best solution but you can use `mj-raw` between link like this : 

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-navbar background-color="#ef6451">
        
        <mj-column >
          <mj-inline-links base-url="https://mjml.io">
            <mj-link href="/gettings-started-onboard" color="#ffffff">Getting started</mj-link>
            <mj-link href="/try-it-live" color="#ffffff">Try it live</mj-link>
            <mj-link href="/templates" color="#ffffff">Templates</mj-link>
            <mj-link href="/components" color="#ffffff">Components</mj-link>
                    <mj-raw>
              <!--[if gte mso 9]>
                </tr><tr>
              <![endif]-->
            </mj-raw>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
    
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
                    <mj-raw>
              <!--[if gte mso 9]>
                </tr><tr>
              <![endif]-->
            </mj-raw>
            <mj-link href="/documentation" color="#ffffff">Documentation</mj-link>
          </mj-inline-links>
        </mj-column>
      </mj-navbar>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by Loac-fr** [comment]
YES ! Thanks, this worked. Not ideal but thank you very much ! I'm closing the issue :)
