### ISSUE TITLE
What is the tag for image link?

### ISSUE THREAD

**Issue by iwanaga-sakura** [mjmlio/mjml#652]
I've trying to use an image as a link and figuring out the solution but can't find one.
The below is the code I've done.

■This doesn't  works.

```
<mj-inline-links>
    <mj-link href="http://blah">
       <mj-column>
           <mj-image src="banner1_pc.png">
           <mj-image>
       </mj-column>
    </mj-link>
</mj-inline-links>
```

Text works but not the image.
■This works.

```
<mj-inline-links>
    <mj-link href="http://blah">blah
    </mj-link>
</mj-inline-links>
```

**Comment by rogierslag** [comment]
you can just set `href` on `mj-image`

**Comment by iwanaga-sakura** [comment]
Hmm..didn't work.
Just did a workaround.
Thanks though!

```
<mj-inline-links>
    <mj-link href="http://blah">
       <mj-column>
              <img src="sample.png"  />
       </mj-column>
    </mj-link>
</mj-inline-links>
```

**Comment by ngarnier** [comment]
hey @iwanaga-sakura, this is not a correct workaroud. As @rogierslag pointed out, you can use the `href` attribute on `mj-image`. Live demo: https://mjml.io/try-it-live/S1Nt1RTCl
```xml
<mj-image width="100" src="/assets/img/logo-small.png" href="https://mjml.io" />
```

**Comment by iwanaga-sakura** [comment]
Oh wow, it worked!

> mj-inline-links and mj-link are meant to be used inside mj-navbar.
This is why, it wasn't working on mine earlier.

@ngarnier @rogierslag Thanks a lot guys!!
