### ISSUE TITLE
Can't get a well worked group of two or more columns using it inside the custom element

### ISSUE THREAD

**Issue by imeleschenko** [mjmlio/mjml#655]
Hi,

First of all, thanks for the tool. It's awesome!

I just started to dive into it and have a question. Should everything working good if I use "mjml-group" in a custom element?

I've created a github repo here: https://github.com/imeleschenko/mjml-mail.
There're folders in src: the one with custom JSX components and the other one with mjml templates.

I have two templates which should have one same result after parsing to HTML. One of it "with_custom.mjml" includes a custom component "mj-custom-container" (src/components/Container.jsx). The other one "without_custom.mjml" have the same structure, but it isn't include any custom thing.

After some time of researching, I've found that the columns inside of the custom component didn't get a correct class "mj-column-per-50". Seems that it happens because the custom component didn't have any child when it was passed to "parseInstance" in "render" method of MJMLRenderer.

I will appreciate in any advance.

Thanks!

**Comment by iRyusa** [comment]
Hi @imeleschenko 

Thanks for the kind words! 

So, there's a bug when deep nesting component it loose track at some point of his parent. We're aware of that and that's really hard to fix in MJML3. 

So for custom component using existing component that's totally normal that you don't have any children inside it. 
When you define custom component it will not translate to `render` method content. Your `mj-custom-container` for instance, will only serialize as a single node even if it contains many thing inside the `render` method. ParseInstance is here to serialize the XML into a usable JSON object for `MJMLElement` decorator

So how to fix this for now, simply pass every attribute you'd want. So group, column should have a `width` and then it should render fine.

**Comment by imeleschenko** [comment]
@iRyusa thanks for the quick response and the advance!

Passing the attributes covers my case.

I suspect, It should be hard to fix it now. Are you going to fix it in MJML4? I've read that there will be some improvements with custom components in the next version.

**Comment by iRyusa** [comment]
Well MJML4 is a complete rewrite and we're dropping react completely so it should no longer be an issue

**Comment by imeleschenko** [comment]
Great, thanks!
