### ISSUE TITLE
Add box-shadow?

### ISSUE THREAD

**Issue by ShaggyDude** [mjmlio/mjml#656]
Forgive me if this has been asked but why is there no box-shadow?
I don't like to rely on too many images and can do almost everything with straight css.

I'd love to contribute after I learn my way around the codebase.

Thanks!

**Comment by iRyusa** [comment]
Hi @ShaggyDude 

As said on Slack box-shadow isn't supported by most of clients. If you still want to use it, in 3.3.3 you will be able to add `css-class` to any MJML element and apply it in `mj-style`.

**Comment by sicaboy** [comment]
Any solution?

**Comment by kmcb777** [comment]
It's still the same situation, you can use a `css-class` on your element and define the box-shadow in a `mj-style`

**Comment by casank25** [comment]
@iRyusa this still doesn't work. adding `box-shadow` to `css-class` defined in `mj-style` produces no results

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/r1UfEXtOH It does work fine.

**Comment by robkorv** [comment]
This works on mjml v4.4.0 and later. It doesn't work on https://mjml.io/try-it-live because the one runs v4.3.0

```mjml
<mjml>
    <mj-head>
        <mj-style>
            .box-shadow a, .box-shadow p {
                box-shadow: 0 4px 6px hsla(0,0%,46%,0.2), 0 1px 3px hsla(0,0%,46%,0.2);
            }
        </mj-style>
    </mj-head>
    <mj-body>
        <mj-section>
            <mj-column>
                <mj-button css-class="box-shadow">You can't click me!</mj-button>
            </mj-column>
        </mj-section>
        <mj-section>
            <mj-column>
                <mj-button css-class="box-shadow" href="google.com">Visit google</mj-button>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
It does work on the try it live too, it's just hidden in the default background color : https://mjml.io/try-it-live/SkDAvRY_S

**Comment by GregoireGonzalez** [comment]
Correct me if I'm wrong but box-shadow are still not support by many clients 
![image](https://user-images.githubusercontent.com/41725601/166659143-f9ea2cd9-fbce-470b-9d14-b64887e578c9.png)
