### ISSUE TITLE
mj-container width not working

### ISSUE THREAD

**Issue by Fanetteg** [mjmlio/mjml#657]
Hi,
I've read in another issue that you could set the width higher than the 600px default width.
In my case I'd need to go up to 800px, but the mj-container width="800px" doesn't seem to work.
Thanks

**Comment by iRyusa** [comment]
Hi @Fanetteg 
Looks to work fine here : https://mjml.io/try-it-live/rysB1pe1-

Note that the try it live is set to 600px max, so that's why it doesn't expand to 800px but if you check the HTML and open in a browser/clients everything is fine

Can you share some code if it's not ?

**Comment by Fanetteg** [comment]
Oh okay, yeah I was just previewing it with the try it live. :)
It works!
Thanks
