### ISSUE TITLE
<a> link?

### ISSUE THREAD

**Issue by paOol** [mjmlio/mjml#66]
I looked through the documentation and could not find a component for a link.

would you just put it inside the <mj-text> component?

would it be RAW?

I basically want a simple
```
<a href="google.com" target="_blank"> google </a>
```

**Comment by iRyusa** [comment]
Hello @paOol 
You can wrap any tags in `<mj-text>` documentation isn't really crystal clear about it

**Comment by g0ddish** [comment]
Wrapping an anchor tag in mj-text requires you to inline remove text-decoration and color inherit to match the mj-text, is this the intended use?

**Comment by iRyusa** [comment]
@g0ddish Can you open a new issue with all the details ? thanks !

@paOol we've added a notice on the documentation to clarify this !

**Comment by kvnol** [comment]
The `<a>` tag returns the follow error: 

> (a) — Element a doesn't exist or is not registered

**Comment by ngarnier** [comment]
@kvnol `<a>` being an HTML tag, it can only be used where HTML is supported, like inside `mj-text` or `mj-table`, but not inside components such as `mj-section`.

**Comment by kvnol** [comment]
@ngarnier Yes! I Had'nt wrapping the `<a>` tag with the `<mj-text>`. Thank's a lot!

**Comment by benwinding** [comment]
For future readers, this works pretty well
``` html
<mj-text>
  <a href="google.com" target="_blank"> google </a>
</mj-text>
```

**Comment by muratgozel** [comment]
Hi, I'm the future reader and thank you. I think this should be in the docs. I was looking for something like `<mj-link>text link.</mj-link>`.

**Comment by rhazegh** [comment]
This should be in the docs.

**Comment by toto1384** [comment]
Is there any way to wrap a lot of mjml elements inside an \<a\> tag?

**Comment by iRyusa** [comment]
No, because most of old desktop client like outlook doesn't allow to wrap table inside anchor tag.

**Comment by toto1384** [comment]
Ok, thanks for the clarification. I was wondering how the Medium Digest Newsletter did that and it was by wrapping every text element and image element in an anchor tag

**Comment by olefrank** [comment]
How is it possible to re-use css rules from `mj-class` in`<a>`?

Is it possible to do something like this?

Like

<mj-class name="color-text" color="#262626"></mj-class>

...

```
<mj-text>
    <a mj-class="color-text" href="xx">xx</a>
</mj-text>
```

**Comment by iRyusa** [comment]
mj-class are not for css-rule only. Use a css-class instead with mj-style.

**Comment by olefrank** [comment]
> mj-class are not for css-rule only. Use a css-class instead with mj-style.

I tried but can't get mj-style to work.

Copied from MJML docs:

```
    <mj-style inline="inline">
      .blue-text {
        color: blue !important;
      }
    </mj-style>
...

 <mj-text css-class="blue-text">
          <div>
            <a href="mailto:tk.kundeservice@totalkredit.dk">tk.kundeservice@totalkredit.dk</a>
          </div>
</mj-text>
```

Do you know why this is not working?

**Comment by iRyusa** [comment]
You need to target the element properly (add a to the css selector) as default style from mjml take over your css rule hereOn 15 Sep 2022, at 12:55, Ole Frank Jensen ***@***.***> wrote:﻿

mj-class are not for css-rule only. Use a css-class instead with mj-style.

I tried but can't get mj-style to work.
Copied from MJML docs:
    <mj-style inline="inline">
      .blue-text {
        color: blue !important;
      }
    </mj-style>
...

 <mj-text css-class="blue-text">
          <div>
            <a ***@***.******@***.***</a>
          </div>
</mj-text>

Do you know why this is not working?

**Comment by mehuljariwala** [comment]
> For future readers, this works pretty well
> 
> ```
> <mj-text>
>   <a href="google.com" target="_blank"> google </a>
> </mj-text>
> ```

how to use data variable inside href tag
