### ISSUE TITLE
mjml-navbar text-align preserves default center

### ISSUE THREAD

**Issue by CopyJosh** [mjmlio/mjml#661]
The mjml-navbar accepts a text-align attribute -- by default this attribute is "center"

If you open the "try it live" for the mjml-navbar and attempt to adjust the alignment with a text-align="left" or "right", the result keeps the center by default.

"View HTML" lines 142 and 144 as of writing this.

`<div class="mj-inline-links" style="width:100%;text-align:center;">`
`<table role="presentation" border="0" cellpadding="0" cellspacing="0" align="center"> `

**Comment by iRyusa** [comment]
Hi @CopyJosh 

You have to set it on `mj-inline-links` to modify it.

`text-align` on `navbar/section` is only here to handle column behaviour when total width is less than 100% on desktop exemple here : https://mjml.io/try-it-live/Hkm_8dvkZ

**Comment by CopyJosh** [comment]
Ah, I see it now. Sorry, I missed the "align" attribute in that table. 

Thank you, works great now.
