### ISSUE TITLE
mj-text links css

### ISSUE THREAD

**Issue by Fanetteg** [mjmlio/mjml#662]
Hi,
I can't seem to find how the links displayed in mj-text can be styled in mjml. 
They stay purple+underline no matter what I do. 
Tried to find the solution in the documention and here but couldn't.
Thank you

**Comment by ngarnier** [comment]
Hey @Fanetteg, `mj-text` takes raw HTML so you can style the `a` element with inlined HTML attributes or even CSS using `mj-style`. 

Example: https://mjml.io/try-it-live/S1D6pL_yb
```
<mjml>
  <mj-head>
    <mj-style inline="inline">
      .link-nostyle { color: inherit; text-decoration: none }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>

          <mj-text font-size="20px" color="#F45e46" font-family="helvetica">
            <a href="https://mjml.io" class="link-nostyle">Hello World</a>
          </mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

I think it solves your issue so I'm closing but feel free to answer and we'll reopen if it's not the case!

**Comment by SoyDiego** [comment]
Hi, this not working in Outlook or IOs. Someone knows how is the correct code in MJML to blue links in Outlook and IOs. Thanks!

**Comment by Maxime-p** [comment]
Still no fully working answer?

**Comment by maxime-paquatte** [comment]
Hi,
Just adding this here in case it helps anyone stumbling upon this thread in the future.
One way to apply a style to all links in MJML is by using the `mj-html-attributes` component.
Here’s a quick example:

```
<mj-html-attributes>
  <mj-selector path="a">
    <mj-html-attribute name="style">color: red</mj-html-attribute>
  </mj-selector>
</mj-html-attributes>
```

Hope it’s useful

**Comment by iRyusa** [comment]
Please don't do that. Just use mj-style with inline instead.
mj-html-attribute is only for niche templating operation.

**Comment by iRyusa** [comment]
MJML provide some stuff to inline it for you instead of doing manually. The post i've replied too was using an uneffective way to do so.
