### ISSUE TITLE
css-class does not work

### ISSUE THREAD

**Issue by aybmab** [mjmlio/mjml#665]
When compiling, I get the issue: Line 50 (mj-text) — Attribute css-class is illegal

What's the correct way to add a class to an mj component?

**Comment by ngarnier** [comment]
Hey @aybmab, 

`css-class` is mentioned in the documentation but is only available in v3.3.3-beta.1, sorry for that. To install and try it: `npm install mjml@3.3.3-beta.1`

**Comment by nicolas-goudry** [comment]
Hi @ngarnier,

I just tried to use the `css-class` attribute on `mj-column` (as mentioned in docs) with `mjml@3.3.3-beta.1` and I still got the same error message : `Line 91 (mj-column) — Attribute css-class is illegal`

Any ideas or in-depth debugging tools ?

**Comment by iRyusa** [comment]
Hi @nicolas-goudry 

Make sure you've installed the beta.  If so you can ignore the message, we forgot to release a beta version of `mjml-validator` package that whitelist this attribute.

**Comment by nicolas-goudry** [comment]
@iRyusa I checked in `package.json` of mjml folder under `node_modules`, it was the right version.

Anyway, the HTML generated does contain the css class and everything I set, so it’s ok ! Sorry

**Comment by ngarnier** [comment]
I'm closing this issue, as `css-class` does work in the beta. Thanks for reporting the validation issue @nicolas-goudry.

**Comment by kpettinga** [comment]
Loving MJML and thanks for the heads up on this!

Could you try to update the docs? I was banging my head against a wall for some time trying to figure out why this `css-class` wouldn't work.

**Comment by MissFerrety** [comment]
@kpettinga Same here. Glad I also found this issue... after _several_ attempts to re-code it. Would like to see an update to docs or push to master.

**Comment by ngarnier** [comment]
Hi guys, v3.3.3 was just released, install with `npm install mjml`. It's not available in the try it live yet, but will be in the coming days/week. Sorry again for the trouble about the documentation.

cc @kpettinga @MissFerrety
