### ISSUE TITLE
./node_modules/.bin/mjml index.mjml doesn't create index.mjml

### ISSUE THREAD

**Issue by PythonHe** [mjmlio/mjml#669]
I am using a Mac. 

I saw the recommendation of creating a mjml_workspace folder in other issues, so I create a folder in Desktop called MJML, then inside the MJML folder:
1. I installed the package by running this command: `npm init -y && npm install mjml`
2. In the same folder, I run this command: `./node_modules/.bin/mjml index.mjml`
3. It looks like it is doing something behind the scenes, no messages return at all.

Then no new file appears. Am I doing something wrong in here? Where can I find the newly created index.mjml file? 

Thanks in advance.

**Comment by PythonHe** [comment]
I thought the command will create the index.mjml file, but the command is actually used to compile the index.mjml file. What a idiot.

**Comment by Rst0000** [comment]
I lost an hour trying to figured out why the file is not creating and then I saw your issue. Thanks...

BTW Docs should be more specified :/ or `mjml xxx.mjml` should return something like 'File doesn't exist' instead of empty return.
