### ISSUE TITLE
Current social component should be renamed

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#67]
Hi,

IMO current "social component" servers for sharing, therefore it should be renamed to "social share". 

Then there should be new "social follow" component with links to channels like Twitter, Youtube, Website, Pinterest, Instagram, etc....

Would be happy to contribute with "social follow" component.

**Comment by arnaudbreton** [comment]
Hey @Tlapi, get your point. Something we can easily do for a future release, even if we have to be careful since it is not backward compatible as it.

For social follow, that's a great idea, more than happy to review your contribution here!

**Comment by Tlapi** [comment]
Ok, i suggest we could add a attribute to mj-social so that we can set whether it is social follow or social share. If you set it as social follow, url sharer prefixes (like https://www.facebook.com/sharer/sharer.php?u=) will be ignored.

I will make a pull-request for that, feel free to review and comment.

**Comment by Tlapi** [comment]
Please check this pull request: https://github.com/mjmlio/mjml/pull/126

**Comment by iRyusa** [comment]
:+1: on `1.3` by adding `:url` on each social network on `display`
