### ISSUE TITLE
align="center" don't work on yahoo mail

### ISSUE THREAD

**Issue by Hboudra42** [mjmlio/mjml#670]
Hello =),
 i used mjml to template an email and i used the attribute align to center some elements,
it's work on every email client but on yahoo desktop it didn't work .

can someone please help me ?

**Comment by iRyusa** [comment]
Hi @Hboudra42 

Can you provide a code sample to reproduce ? 
You can share the custom url in the try it live here : https://mjml.io/try-it-live

**Comment by Hboudra42** [comment]
it's a button like this
``` mjml
mj-section(align="center")
        mj-button(width="150", href="#{traits}", background-color="#20abe3", style="padding-bottom: 200px", align="center")
          strong(style="color: white; font-weight: bold; font-size: 16px", align="center")
            |Plus d'infos  !
```

**Comment by iRyusa** [comment]
You're missing a column in your section, that should solve it.

**Comment by Hboudra42** [comment]
It's solve the problem thank you answered very quickly

**Comment by iRyusa** [comment]
I'm closing the issue then ! :)
