### ISSUE TITLE
Set arbitrary attribute on a tag in mj-button

### ISSUE THREAD

**Issue by oscar-b** [mjmlio/mjml#671]
For tracking purposes, it would be great to be able to pass through arbitrary attribute and value to the `<a>` link in an mj-button:

```
<a href="https://tracking.domain" data-extra-info="the-big-button"></a>
```

Useful for anyone else? Or better to create my own component for something like that?

**Comment by ngarnier** [comment]
Hey @oscar-b, we can't enable custom attributes in MJML 3 due to the way React works, so I guess a good way to go is indeed with a custom button component in which you'll add this attribute as a valid attribute.

You might also try to omit the `href` in `mj-button` and add an `a` link inside (make sure to test it doesn't break the button compatibility). 
```mjml
<mj-button>
  <a href="https://tracking.domain" data-extra-info="the-big-button">click</a>
</mj-button>
```

Does it help?

**Comment by oscar-b** [comment]
Hm, do you mean the limitation in React passing unknown attributes to elements? I think all data-* are allowed though..

> React supports all data-* and aria-* attributes as well as these attributes:

https://facebook.github.io/react/docs/dom-elements.html

**Comment by ngarnier** [comment]
In your case that would work yes, but allowing custom attributes is a big topic as one MJML element isn't equivalent to a single one HTML element, so we'd have to "guess" where you want the custom attribute to be added (easy in your case, but hard to generalize). 

There's already an [issue about custom attributes](https://github.com/mjmlio/mjml/issues/200) so I'll close this one to keep the discussion in one single place.

Anyway, it's not something we'll work on for MJML 3 (we're now focusing [MJML 4](https://medium.com/mjml-making-responsive-email-easy/hey-were-entirely-rebuilding-mjml-from-scratch-announcing-mjml-v4-ae92f83b725b)) so if you want a quick solution, I'd definitely go with the custom component route (you might be interested in [this tutorial](https://medium.com/mjml-making-responsive-email-easy/tutorial-creating-your-own-mjml-component-d3a236ab7093#.d1ji1oheq)).

Cheers!

**Comment by oscar-b** [comment]
@ngarnier of course, good point. Thanks for all the input!
