### ISSUE TITLE
[Outlook-Android] mj-button link's color is not applied

### ISSUE THREAD

**Issue by zygimantas** [mjmlio/mjml#672]
mjml 3.3.2
mj-button is inside mj-column

```
<mj-button href="http://example" inner-padding="15px 50px">Example 1</mj-button>
<mj-button href="http://example" background-color="#444" inner-padding="15px 50px">Example 2</mj-button>
<mj-button href="http://example" background-color="#444" color="#fff" inner-padding="15px 50px">Example 3</mj-button>
<mj-button href="http://example" background-color="#444" color="#fff" font-size="15" font-family="'Helvetica Neue',Helvetica,Arial,sans-serif" inner-padding="15px 50px">Example 4</mj-button>
<mj-button href="http://example" container-background-color="#444" inner-padding="15px 50px">Example 5</mj-button>
```

**Expected result:**

A button with white text, transparent text background padding and rounded corners (where supported)
Button should be clickable on padding area (not solved with #557 )

**Actual result:**

Windows 10, Outlook 2016 (16.0.7927.1020) 32-bit

![image](https://cloud.githubusercontent.com/assets/102076/25993290/2fc76c60-3712-11e7-9260-99829d4b33fe.png)

Android 7.0.0. Outlook 2.1.203 (should be the latest)

![image](https://cloud.githubusercontent.com/assets/102076/25993466/be5186d2-3712-11e7-9180-06cae493c841.png)

**Comment by iRyusa** [comment]
Hello @zygimantas

Looks like you can't use hexadecimal short-hand color ( 3 digits/letter instead of 6 ). Looks like to work when converting `#444` to `#444444`

**Comment by dalefish** [comment]
A lot of clients don't work with the shorthand, always opt for the
long-form version as a base.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ngarnier** [comment]
+1 on the comments from @iRyusa and @dalefish.

About this point, we're currently testing but it's harder than it seems to have buttons clickable on the padding, working everywhere, and rendering correctly everywhere
> Button should be clickable on padding area (not solved with #557 )

**Comment by zygimantas** [comment]
Hi @iRyusa @dalefish  yes, you are right, after the change to #444444 button size is normal, but few issues are still left:

1. Text color on Android. The text is displayed in blue, as a link. Color property (#ffffff) on button is ignored.
2. Button is not clickable on padding.

**Comment by zygimantas** [comment]
I found this discussion, maybe nothing can be done from the mjml side:
https://litmus.com/community/discussions/5386-outlook-app-on-ios-turns-links-blue

**Comment by zygimantas** [comment]
That was the problem with link colors in mobile outlook: https://litmus.com/community/discussions/6419-outlook-mobile-app-in-android-not-respecting-font-colors

**Comment by iRyusa** [comment]
Mh if it doesn't break anything in any other major emails client I don't mind to remove the color on wrapping td. But we have to test it to make sure color is applied everywhere

**Comment by zygimantas** [comment]
For those who will have the same issue, this is my workaround:

```
<mj-style inline="inline">td a {color: #ffffff !important}</mj-style>
...
<mj-button color="#eeeeee" href="#">Button</mj-button>
<mj-text color="#eeeeee"">
     <a href="#" style="color:#444444 !important">Link</a>
</mj-text>
```

This way I managed to get a button with a white text and a dark link.

**Comment by iRyusa** [comment]
Updating the title to match the real issue

**Comment by zygimantas** [comment]
The change fixed Android Outlook issue, but broke Outlook on Windows. Not on Windows, button text is blue, as a regular link, regardless of "color" attribute on button (mj-attributes)
