### ISSUE TITLE
Creating a component renders unwanted commas

### ISSUE THREAD

**Issue by iammichiel** [mjmlio/mjml#675]
Hi there, 

Thanks for the great work on the project, really like it. However when creating a custom component using the jsx syntax, we have some strange behaviour. 

The following is extracted from the `render` function : 
```
<Column width="50%">
    <Text font-size="14" align="center" padding="0" font-weight="700">
        test
        <a href="tel:0123456789" style={ {color: "#67cfd6"} }>0123456789</a>
        <span style={ {color:"#000000"} }>(appel gratuit)</span>
    </Text>
</Column>
```

This part gets rendered as followed : 
```
test,012345789,(appel gratuit)
```

It seems the mj-text component adds the commas when rendering each element.

**Comment by gabrieltomescu** [comment]
I'm facing the same issue. If you wrap the children inside ```Text``` with a ```div```, the comma disappears. I believe this has something to do with how ```mjContent``` build an array of its children.

**Comment by Laslo89** [comment]
which version of mjml do you use? seems like you have forgotten to say the custom comp which props will get be passed.
something like this:

`const defaultMJMLDefinition = {
    attributes: {
        'background-color': 'blue',
    },
};`

**Comment by iammichiel** [comment]
Hi @Laslo89 

I don't understand your question. How are those attributes relevant to the display of children elements? We are using the 3.3.2 version of MJML.

**Comment by Laslo89** [comment]
Hi @iammichiel  
sry i missunderstand you a bit. Anyways, i ve managed to reproduce this behavior. It should be fixed by wrapping your HTML in on single string. Like this:
```
<Column width="50%">
     <Text font-size="14" align="center" padding="0" font-weight="700">
         {`
             test
             <a href="tel:0123456789" style="color: #67cfd6">0123456789</a>
             <span style="color:#000000">(appel gratuit)</span>
        `}
    </Text>
</Column>
```

**Comment by iRyusa** [comment]
As @gabrieltomescu mention, mjContent doesn't expect an array of content, so toString method is called on an array so that's why you have commas  ex: 

```js
> [1,2,3].toString()
"1,2,3"
```

This behaviour is fixed in MJML4, if someone has time to open a PR on this, this should be easy to fix in MJML3 by checking the type of mjContent

**Comment by etiennemarais** [comment]
@iammichiel @iRyusa Please see ^^ PR? Any comments would be appreciated. It solves the `mj-text` having nested html elements as rendering it with commas.

**Comment by etiennemarais** [comment]
I updated [#778](https://github.com/mjmlio/mjml/pull/778) to do it everywhere. Please can you verify that's what you wanted?
