### ISSUE TITLE
Only mjml -v works

### ISSUE THREAD

**Issue by zabrn** [mjmlio/mjml#677]
I installed mjml locally and try to start it "mjml input.mjml" but nothing happens. I can see the version , but besides that, i cant do anything. I'm using windows and added to system variables. Anyone have a clue what i'm doing wrong? Much thanks for any help.

![ss](https://cloud.githubusercontent.com/assets/9823415/26131844/5e9775dc-3a94-11e7-802e-051c7a481f23.png)

**Comment by iRyusa** [comment]
Hi @zabrn 

Can you provide the content of your `inpux.mjml` file ? Thanks

**Comment by zabrn** [comment]
Hi @iRyusa, it doesnt create any file.

**Comment by ngarnier** [comment]
Hey @zabrn, `mjml index.mjml` doesn't create any file, it's meant to transpile a `.mjml` file into a `.html` file. 

You need to create `input.mjml` yourself, with the `cat` command, with your file editor, or with any other way that suits you best 🙂 . You can find a [boilerplate here](https://mjml.io/try-it-live).

Can you please tell us where you read the instructions that confused you?
