### ISSUE TITLE
Error: URIError: URI malformed when validating mjml file

### ISSUE THREAD

**Issue by quimpg** [mjmlio/mjml#678]
I got this error when I try to validate o render a mjml file.

> URIError: URI malformed
>     at decodeURIComponent (native)
>     at /usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:103:12
>     at /usr/local/lib/node_modules/mjml/node_modules/lodash/mapValues.js:38:34
>     at /usr/local/lib/node_modules/mjml/node_modules/lodash/_createBaseFor.js:17:11
>     at baseForOwn (/usr/local/lib/node_modules/mjml/node_modules/lodash/_baseForOwn.js:13:20)
>     at mapValues (/usr/local/lib/node_modules/mjml/node_modules/lodash/mapValues.js:37:3)
>     at mjmlElementParser (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:102:44)
>     at /usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:116:14
>     at Array.map (native)
>     at mjmlElementParser (/usr/local/lib/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:115:8)

node v4.7.2
mjml 3.3.2

I tried to remove fields with href but the file doesn't validate

<mjml>
  <mj-body>
    <mj-container background-color="#f8f8f8">

      
      <mj-section>
        <mj-column>
          <mj-inline-links align="left" base-url="<%= $urlMain %>">
            <mj-link font-size="28px" text-transform="none" font-family="sans-serif" font-weight="bold" href="?alertCreated" color="#4183c4" padding-left="10%" padding-right="10%">A</mj-link>
          </mj-inline-links>
        </mj-column>
      </mj-section>

      
      <mj-section background-color="#fff">
          <mj-column>
            <mj-text color="#4183c4" font-size="32px" padding-left="10%" font-family="arial,sans-serif" padding-right="10%" padding-top="40px" line-height="34px">
              Nueva alerta creada
            </mj-text>          
            <mj-text color="#333" font-family="arial,sans-serif" font-size="16px" padding-left="10%" padding-right="10%">
              Acabas de activar la alerta que te detallamos a continuación:
              <ul>
              <li>Subasta de <b><%= $tipoBien %></b></li>
              % my $title;
                % if ($municipio eq 'All') {
                  <li>En <b><%= $provincia %></b> provincia</li>
                % } else {
                  % $title = $municipio.', '.$provincia;
                  <li>En <b><%= $municipio %></b>, <b><%= $provincia %></b> provincia</li>
                % }
              <li>Origen <b><%= reverse('sTipoSubasta',$type) %></b></li>
              </ul>
              <p>A partir de ahora recibirás por email las nuevas subastas que se publiquen con estos criterios.</p>
              <p>Recuerda que en cualquier momento puedes eliminar esta alerta si ya no te interesa desde el siguiente enlace.</p>
            </mj-text>
            
            <mj-text color="#ccc" font-size="16px" padding-left="10%" font-family="arial,sans-serif" padding-right="10%" padding-bottom="40px">
              <a href="<%= $urlMain %>/emailAlert/optOut/<%= $iduAlert %>" color="#ccc" text-decoration="underline" style="color:#ccc">Dar de baja esta alerta</a>
            </mj-text>
          </mj-column>
      </mj-section>
	
	<mj-section background-color="#eee">
		<mj-column>
			<mj-text font-size="14px" padding-left="10%" font-family="arial,sans-serif" padding-right="10%" color="#ccc"">
			<a href="#" style="color:#333;text-decoration:none;font-family:arial,sans-serif;font-weight:bold;font-size:20px;">A</a>
			</mj-text>
		</mj-column>
	</mj-section>

    </mj-container>
  </mj-body>
</mjml>

after some try error I found the problem is in this section

```
<mj-column>
  <mj-text font-size="14px" padding-left="10%" font-family="arial,sans-serif" padding-right="10%" color="#ccc"">
    <a href="#" style="color:#333;text-decoration:none;font-family:arial,sans-serif;font-weight:bold;font-size:20px;">A</a>
  </mj-text>
</mj-column>
```

I tried to introduce correct url on href but I got always the same URIError.

After removing the previous code from the mjml  I got this error now

> Error: EISDIR: illegal operation on a directory, open './/'
>     at Error (native)
>

**Comment by ngarnier** [comment]
Hi @quimpg, can you please try to update your NodeJS version? LTS will be fine.

**Comment by quimpg** [comment]
solved! thanks!
