### ISSUE TITLE
Add possibility to set order of social links in social component

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#68]
Would be fine if we will have possibility to set order of links. By now, all links are rendered in default order.

Maybe something like order parameter?

`<mj-social
      order="google|facebook|pinterest" />`

**Comment by iRyusa** [comment]
Hi @Tlapi !

Loving the idea, instead of `<mj-social facebook="true" twitter="true />` it could be `<mj-social display="facebook google twitter" />` What do you think about it?

I am working on `mj-social` atm see PR #65 and I think i'll bring this in `1.2`

**Comment by Tlapi** [comment]
Cool, much better that way!

That will also resolve the other issue i had with declaring what platforms to display as this was not convenient.

Thanks.

**Comment by iRyusa** [comment]
Now in `1.2.0` !
