### ISSUE TITLE
Attribute css-class is illegal

### ISSUE THREAD

**Issue by wallawe** [mjmlio/mjml#684]
**Issue:**

Added `css-class` attribute to the mj-image and mj-text tags, and the result while 'watching' the file was this error message: `(mj-image) — Attribute css-class is illegal`. I also checked the raw HTML to verify that the class wasn't there. 

  **MJML version:**

3.3.2

**Comment by ngarnier** [comment]
Hey @wallawe, `css-class` is available in MJML [v3.3.3-beta.1](https://github.com/mjmlio/mjml/releases/tag/3.3.3-beta.1) only for the moment, sorry for not making it clearer in the documentation.

We'll release a new beta version early next week. As the current beta as some issues that will be fixed in the next release, I suggest you try it when beta.2 is available.

**Comment by Sarah-IFG** [comment]
Hey @ngarnier, I'm using v3.3.3-beta.1 and `css-class` attribute is not working. I have the same error message `(mj-image) — Attribute css-class is illegal`

**Comment by ngarnier** [comment]
@Sarah-IFG `(mj-image) — Attribute css-class is illegal` is just a validation issue, it will be fixed in the next release. Can you check in the HTML if your class is added (by looking with CMD+F for example)?

**Comment by wallawe** [comment]
ok thanks for the prompt response!

**Comment by Sarah-IFG** [comment]
@ngarnier thank you for your response. I didn't know that was only a validation issue. So my class is well added, but not at the good place. I want to add a class on the `<img>`balise, but in the HTML this is added on the first `tr` :

MJML : 
```
<mj-section padding="0 10px 0 25px" background-color="#ffffff" text-align="left">
    <mj-column width="70%"> 
        <mj-image css-class="imgauto" src="/img.jpg" alt="Notre sélection mode"/>
    </mj-column>
</mj-section>
```

HTML :
```
<div class="mj-column-per-70 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;">
<table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
<tbody><tr class="imgauto"><td style="word-wrap:break-word;font-size:0px;padding:0px;" align="center">
<table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px;" align="center" border="0">
<tbody><tr><td style="width:420px;">
<img alt="Notre sélection mode" title="" height="auto" src="img.jpg" style="border:none;border-radius:0px;display:block;font-size:13px;outline:none;text-decoration:none;width:100%;height:auto;" width="420"></td></tr>
</tbody></table></td></tr></tbody></table></div>
```

**Comment by iRyusa** [comment]
Well @Sarah-IFG , `mj-image` doesn't render only as an `img` tag.

So to make everyone happy, we put it at the "root" tag of the component `tr` for any element inside a `mj-column`. You can simply use a quick css selector like `.imgauto img` to achieve this.

**Comment by Sarah-IFG** [comment]
@iRyusa thank you, I didn't think to do that in that way.
