### ISSUE TITLE
Rendering Navbar component in custom component causes Invariant Violation

### ISSUE THREAD

**Issue by dstaley** [mjmlio/mjml#687]
When attempting to create a custom component that wraps the Navbar component, I'm running into an Invariant Error.

```js
import { MJMLElement } from 'mjml-core';
import React, { Component } from 'react';
import Column from 'mjml-column';
import { Navbar, InlineLinks, Link } from 'mjml-navbar';

@MJMLElement
class CustomNavbar extends Component {
    render() {
        return (
            <Navbar>
                <Column>
                    <InlineLinks>
                        <Link href="/one" key="/one">One</Link>
                        <Link href="/two" key="/two">Two</Link>
                        <Link href="/three" key="/three">Three</Link>
                    </InlineLinks>
                </Column>
            </Navbar>
        );
    }
}

CustomNavbar.tagName = 'custom-navbar';
CustomNavbar.parentTag = ['mj-container'];
CustomNavbar.endingTag = false;
CustomNavbar.defaultMJMLDefinition = { content: '' };

export default CustomNavbar;
```

**Reproduction Steps:**

1. `git clone https://github.com/dstaley/mjml-component-boilerplate && cd mjml-component-boilerplate`
2. `npm install`
3. `npm run build`

**Expected behavior:**

A Navbar element with three links is rendered.

**Observed behavior:**

```
Invariant Violation: Element type is invalid: expected a string (for built-in
components) or a class/function (for composite components) but got: undefined.
You likely forgot to export your component from the file it's defined in.
Check the render method of `CustomNavbar`.
```

**MJML version:**
`3.1.1`

**Comment by iRyusa** [comment]
Hi @dstaley  

Can you test to set endingTag to true ?

**Comment by dstaley** [comment]
@iRyusa I can confirm that the issue is still present with `endingTag = true` and mjml v3.3.2. I've updated the linked repo with those changes as well.

**Comment by iRyusa** [comment]
I think this a deep bug in the MJML decorator, and would require a major rework of the decorator.

As mentioned in #489 React will be dropped in MJML4, so i'm closing this one because it won't be fixed.
