### ISSUE TITLE
Attribute css-class is illegal

### ISSUE THREAD

**Issue by elwebdeveloper** [mjmlio/mjml#688]
Compiler throughs the following error:
(mj-section) — Attribute css-class is illegal
(mj-column) — Attribute css-class is illegal

  **Reproduction Steps:**

  1. [First Step]
I add this attribute in:
  <mj-section css-class="some-css-class"></mj-section>
or
  <mj-column css-class="another-css-class"></mj-section>

  2. [Second Step]
Run mjml and get the above messages
 
  **Expected behavior:**
No errors, as documents shows that should be legal ([read here](https://mjml.io/documentation/#mjml-column))

  **Observed behavior:**
It should add the css class as described, no?

  **MJML version:**

  3.3.2

Thank you!

**Comment by ngarnier** [comment]
Hey @elwebdeveloper, thanks for making this issue clear. 

As answered [here](https://github.com/mjmlio/mjml/issues/684), css-class is available in MJML v3.3.3 which is in beta for the moment, sorry for not making it clearer in the documentation.

You can install the beta and use `css-class` with `npm install mjml@3.3.3-beta.3`.
