### ISSUE TITLE
align=center sometimes doesn't work in Windows 10's Mail App

### ISSUE THREAD

**Issue by luisrudge** [mjmlio/mjml#691]
## outlook.com
![image](https://cloud.githubusercontent.com/assets/941075/26530932/94f43dac-43b5-11e7-8a62-f8d8af318363.png)

## gmail
![image](https://cloud.githubusercontent.com/assets/941075/26530942/cefa81aa-43b5-11e7-9cd6-8fe17ae077e3.png)

## Windows 10's Mail App
![image](https://cloud.githubusercontent.com/assets/941075/26530934/ac057a74-43b5-11e7-8d22-f9cce45a4083.png)

Try it here: https://mjml.io/try-it-live/SyIE3YubZ

## mjml code:

```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-all align="center" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text font-weight="100" font-size="48px" line-height="48px" color="#555" mj-class="f-os">
            should be centered
          </mj-text>
          <mj-link href="https://mjml.io" font-weight="100" font-size="48px" line-height="48px" color="#3498db" text-transform="none" padding="0">
            should be centered
          </mj-link>
        </mj-column>
      </mj-section>
      <mj-section background-color="#fff">
        <mj-column>
          <mj-section padding="10px">
            <mj-section background-color="#27ae60" border-radius="10px">
              <mj-link href="https://mjml.io" font-size="25px" line-height="30px" color="#fff" mj-class="f-r" text-transform="none" padding="5px">
                should be centered
              </mj-link>
            </mj-section>
          </mj-section>
          <mj-link href="https://mjml.io" font-weight="100" font-size="35px" color="#3498db" mj-class="f-r" text-transform="none">
            should be centered
          </mj-link>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by luisrudge** [comment]
I tried this and didn't work as well:

```
    <mj-style inline="inline">
      * { text-align: center !important; }
    </mj-style>
```

**Comment by iRyusa** [comment]
Hi @luisrudge 

Well there's some issues in your code and I believe this is why it doesn't work : 

- `mj-link` is only for `inline-links` component, you can read more about `mj-navbar` here: https://mjml.io/documentation/#mjml-navbar
- We don't support nesting `mj-section` inside `mj-column`. ( Even if some people are doing it and have no issue with it see #580 )

I'm closing the issue feel free to reopen if needed

**Comment by ajorquera91** [comment]
Something similar happens to me with my mail.

![image](https://user-images.githubusercontent.com/24572593/26854129-d4bef52e-4ae2-11e7-893b-d1057551c3f4.png)

https://mjml.io/try-it-live/ry_CPiNMb

**Comment by iRyusa** [comment]
Hello @ajorquera91 

It's a separate issue but looks like you more than 100% of content in a section ( column 100% + 88% in the same section ).

**Comment by ajorquera91** [comment]
Hello @iRyusa 

You were right :).

Really thanks.
