### ISSUE TITLE
mj-image, mj-divider rewrite style by class does not work

### ISSUE THREAD

**Issue by vdeapps** [mjmlio/mjml#692]
Hi.

I need divider or image with custom css but neither mj-divider or mj-img does rewrite style with my class.
`<hr>` tag do it.

`<mj-raw><hr class="hr-type5"/></mj-raw> <!-- OK -->`
`<mj-divider class="hr-type5"/> <!-- NOT OK -->`
`<mj-image class="hr-type5"/> <!-- NOT OK -->`

```
.hr-type5{
    border: 0;
    height: 35px;
    text-align: center;
    background-color: #005151;
    background: url("{{ app.settings.baseUrl }}/media/img/hr-5.png") center no-repeat;
    background-size: contain;
  }
```

Can you add this feature.
Thanks.

**Comment by iRyusa** [comment]
Hello @vdeapps 

You can't use any html attributes on mj-element. We're introducing `css-class` to address this in next 3.3.3 release. You can already test it with the beta release with `npm install mjml@beta`.

I'm  closing this issue because it's a dup of #480

**Comment by LukyVj** [comment]
Hello, I have the exact same problem, 5 years later :D 

```html
<mj-divider
      border-color="#CEE1FF"
      border-width="1px"
      css-class="divider"
    ></mj-divider>
```

```css
.divider{display:block;margin: 20px 0px} 
@media (min-width: 480px) {
  .divider{margin: 40px 0px}
}
```

This has no effect and the class isn't applied.

See: <img width="632" alt="Screenshot 2022-07-05 at 17 20 09" src="https://user-images.githubusercontent.com/1630200/177361908-decfe270-100e-40b1-bb75-c812334c89a5.png">
 
Is there any ways to fix that? 

Thanks.

**Comment by LukyVj** [comment]
Thanks for answering. 
But yet doing a `cmd + f` of the class name yields no results? So I'm not sure what's wrong. Also I'm using:  `"mjml": "^4.12.0"`

**Comment by iRyusa** [comment]
![Capture d’écran 2022-07-05 à 18 30 23](https://user-images.githubusercontent.com/570317/177374427-b46ea087-7062-423f-bb9e-2ddb9a4c4266.png)
Works just fine here : https://mjml.io/try-it-live/Hw-yDalBB

**Comment by LukyVj** [comment]
Thanks, so weird, I'm gonna give it an other go! :) :
