### ISSUE TITLE
EM client xml contnet shown

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#696]
In EM client users are seeing the value of:
```
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
```

So they see the number "96" at the beginning of their e-mails.

Any idea why?

**Comment by iRyusa** [comment]
Hi @Tlapi 

It's wrapped into an Outlook comment, and it avoid issues with Outlook high DPI. EM Client isn't in our testing scope, so you might want to contact them to know what happens on their side

**Comment by Tlapi** [comment]
Hi @iRyusa 

ok, I did sent them an e-mail.
