### ISSUE TITLE
Bundle for MJML

### ISSUE THREAD

**Issue by PurpleBabar** [mjmlio/mjml#698]
Hey :p 

Just made a bundle for mjml, i'm writing the doc actually, are you interested in it ?

Cheerz :)

**Comment by meriadec** [comment]
For research purposes, what is a bundle?

**Comment by iRyusa** [comment]
I think it's a symfony bundle right ?

**Comment by PurpleBabar** [comment]
@meriadec : @iRyusa is right :) it's a symfony Bundle :) sorry i wasn't clear :p

**Comment by ngarnier** [comment]
hey @PurpleBabar, great to hear! Definitely something that could belong here: https://mjml.io/community!

Ping us here or on [Slack](https://slack.mjml.io/) when it's ready, thanks a lot! 🙌

**Comment by TomPradat** [comment]
@PurpleBabar is your bundle ready ?

**Comment by PurpleBabar** [comment]
Hi 

Bundle is ready and working, but i may need to rework on documentation as it is pretty basic at the moment.

https://github.com/elephantly/MjmlBundle

Still need to do some ci on it.
