### ISSUE TITLE
Upgrade deprecated fs-promise

### ISSUE THREAD

**Issue by mikelambert** [mjmlio/mjml#700]
Installing mjml triggers the following warning:
`npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support`

This is the file/line in question that needs to be updated:
https://github.com/mjmlio/mjml/blob/master/packages/mjml-cli/package.json#L21

**Comment by ngarnier** [comment]
Released with [3.3.4](https://github.com/mjmlio/mjml/milestone/12).
