### ISSUE TITLE
Support background styles in content tags

### ISSUE THREAD

**Issue by MissFerrety** [mjmlio/mjml#701]
There may be other tags and/or styles that are affected by this, and it may be a conscious choice, but I was unhappily surprised by the fact that `mj-text` and `mj-image` do not support backgrounds. Any `mj-class` attribute applied or explicit `background` attribute set is stripped out in the rendered version. My only option currently is to nest the text-node (or image) inside a `div`, at which point I can't access my `mj-attributes` and have to really mess around with padding and color and anything else that would otherwise already be standardized with the rest of the document.

Possible use-cases: `mj-text` - Callout text in a sidebar (can't nest columns, so can't apply that way); `mj-image` - Custom `.png` icon with variable color

**Comment by iRyusa** [comment]
Hi @MissFerrety 

I'm not sure to understand your need. You can already  apply `container-background-color` on `mj- text` & `mj-image` ( and everything living inside a column ) ex : https://mjml.io/try-it-live/B1Tv2-yzb .

Or you're talking about background image ?

**Comment by MissFerrety** [comment]
Aha, now that is obscure and well-hidden. Why was this relegated to a specific and custom attribute? It would be very nice to be able to use the otherwise standard background attribute or `mj-class` with background style applied.

**Comment by iRyusa** [comment]
Well you can find it on any component on the documentation : https://mjml.io/documentation/#standard-body-components

Background attribute isn't really supported everywhere, so we're sticking to what's most compatible across popular clients.

In 3.3.3 you will be able to set a css-class and do it freely however background image are so badly supported we recommend to stay away from it
