### ISSUE TITLE
mj-font not working with mj-style inline="inline"

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#703]
Hi,

when using `<mj-style inline="inline">` with custom font and then `<mj-font>`, the font isn't iserted into the final render as it is not found in `importFonts.js`

`importFonts.js` does not check mj-style for font appareance.

Check the code:
```
<mjml>
  <mj-head>
    <mj-style inline="inline">
      h1{font-family:Cabin, sans-serif;};
    </mj-style>
    <mj-font name="Cabin" href="https://fonts.googleapis.com/css?family=Cabin" />
  </mj-head>
  <mj-body>
    <mj-container background-color="#FFFFFF">
      <mj-section>
        <mj-column>
          <mj-text>
            <h1>20% off blazers</h1>
          </mj-text>
        </mj-column>
    </mj-container>
  </mj-body>
</mjml>
```

https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/importFonts.js#L26

https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/MJMLRenderer.js#L156

Seems like this problem prevail in `master`

**Comment by Tlapi** [comment]
From my point of view it would be better to remove the check here:
https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/helpers/importFonts.js#L26

I understand that it's better not to include the fonts user does not use in the end, but still, I would let this on the user and get it working with mj-style.

What do you think?

**Comment by iRyusa** [comment]
Hi @Tlapi 

The font check should be applied after inline, we'll take a look at it. The main goal is to avoid non used font declaration in the head.

You can fix it temporarly by adding a font-family inside a mj-text or non inlined mj-style. It's not the best, but at least the font will be imported.

**Comment by iRyusa** [comment]
Editing title for clarity

**Comment by nealoke** [comment]
+1 for this
