### ISSUE TITLE
Add Outlook support for borders on images

### ISSUE THREAD

**Issue by madonkey** [mjmlio/mjml#709]
Currently when a border is added to mj-image, MJML adds the border directly to the img tag. Outlook 2007/2010/2013/2016 doesn't support this, so no border will be shown.

Adding the border to the wrapping td instead will render on Outlook as intended.

Current HTML:
```
<tr>
    <td style="width:250px;"><img alt="" title="" height="auto" src="http://placehold.it/250x250" style="border:#000000 solid 3px;border-radius:0px;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="250"></td>
</tr>
```

Proposed HTML:
```
<tr>
    <td style="width:250px;border:#000000 solid 3px;border-radius:0px;"><img alt="" title="" height="auto" src="http://placehold.it/250x250" style="display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="250"></td>
</tr>
```

**Comment by iRyusa** [comment]
Hi @madonkey 

It could work ! 
But then mixing `border-radius` & `border` will no longer work because of `border-collapse`, I don't know what's the best here..

**Comment by madonkey** [comment]
Hi @iRyusa 

I knew there would be a catch... Yeah, just tested with border radius and it won't work. I suppose the only way this would be a solution is if you had no border radius. Not really ideal.

**Comment by madonkey** [comment]
Adding a wrapping `div` around the `img` could be a possible solution?

You would need to add `border-radius` to both the `img` and `div` though. Probably a lot of bloat for not much gain.

`<tr>
                              <td style="width:250px;"><div style="border:#000000 solid 3px;border-radius:10px;">
                                  <img alt="" title="" height="auto" src="http://placehold.it/250x250" style="display:block;outline:none;text-decoration:none;width:100%;height:auto;border-radius:10px;" width="250"></div></td>
                            </tr>`

**Comment by iRyusa** [comment]
Mhh did you tried in Outlook 2000/2003, if I'm right border on div are totally broken

**Comment by madonkey** [comment]
I tested on 2003 and it renders ok - minus the `border-radius` obviously.

**Comment by kmcb777** [comment]
I made a few tests and this is unfortunately not possible. The `div` would have the border-radius value from the attribute but then the border-radius of the `img` needs to be calculated depending on the border widths, and while it's possible with px values it seems impossible to do when border-radius is in percent, resulting in things like this : 
<img width="165" alt="screen shot 2018-05-25 at 15 32 19" src="https://user-images.githubusercontent.com/8144509/40546976-f0c6aac8-6030-11e8-8599-d092c01d9082.png">
