### ISSUE TITLE
mj-invoice width 100%

### ISSUE THREAD

**Issue by lucased** [mjmlio/mjml#712]
Hi this could be me doing something wrong, when using the invoice component the table doesn't sit at 100% of the width of the container (using the example invoice code). Is there a way to get around this?

Im using version 3.3.3

**Comment by ngarnier** [comment]
Hi @lucased, addingg `width="100%` on `mj-invoice` should do the trick. Can you confirm it's what you need?

**Comment by lucased** [comment]
Hi @ngarnier thanks for the quick response, i did try adding width="100%" but when i build the .mjml file i get the error `Line 24 (mj-invoice) — Attribute width is illegal`

**Comment by ngarnier** [comment]
It's just a validation error but the attribute is passed correctly, you can ignore the warning

**Comment by lucased** [comment]
Great thanks @ngarnier

**Comment by ngarnier** [comment]
Closing as I updated the doc on Github, it will be updated on the website in a future release
