### ISSUE TITLE
Aren't mj-wrapper infinitely nestable?

### ISSUE THREAD

**Issue by lucasnantonio** [mjmlio/mjml#714]
Hi, I'm using wrappers inside other wrappers to organize my code and get shared backgrounds on elements. It's very useful and works fine on the mjml-app preview. Are there any known side-effects of doing this when rendering on different clients?

![image](https://user-images.githubusercontent.com/13240286/27085920-01fb9b84-5027-11e7-8161-60e32e3efe84.png)

**Comment by iRyusa** [comment]
Hi @lucasnantonio 
Can you share some kind of screenshot where wrapper nesting is useful ? Multiple nesting adds complexity and more HTML to the output so you should use it wisely. It's the same thing as nesting section within a column for some people it works, but we're not recommend it

**Comment by lucasnantonio** [comment]
Hi @iRyusa, here's what I'm using it for:

I have an container, an outer wrapper (nº1) with a box-shadow style, and inside it I have some sections wrapped in a gray bg wrapper(nº2). 

This way i can declare the gray bg only once for the wrapper, as well as the border-top and border-bottom lines. Otherwise I'd have to declare these properties in each of the sections.

![slice](https://user-images.githubusercontent.com/13240286/27093004-98422478-503b-11e7-89aa-4990336ad745.png)

**Comment by iRyusa** [comment]
I think this could be way easier with a mj-class for your middle sections. Wrapper would add some non needed overhead that could potentially break something.

I'd agree that it looks useful for border, but this look like an really edgy case to support something like that.

If there's some community interest in this we might take a look at it, but for now I think I can close this one

**Comment by brenramz** [comment]
I think it could be useful :(
