### ISSUE TITLE
Add rel="noopener" with href attribute

### ISSUE THREAD

**Issue by erklat** [mjmlio/mjml#718]
Hi, we have decided to adopt your framework into our company responsive email workflow. However now I see that when we add href attribute to mjml component it adds target="_blank", which is expected behaviour. However exposing window.opener javascript object is not wanted behaviour which is what happens when you use target="_blank" without rel="noopener" attribute and especially since what we are doing are emails and email account is susceptible to phishing attacks.

I don't think that there is single use case scenario where you would want to leave window.opener not nullified.

More on the topic can be read here: https://mathiasbynens.github.io/rel-noopener/

**Comment by iRyusa** [comment]
Hi @erklat 

Most component now support `rel` attribute in 3.3.3 so you can add a noopener if you'd want to !

**Comment by ngarnier** [comment]
As @iRyusa said you can now easily add `rel="noopener"` since v3.3.3 so I'm closing (we won't enforce it by default)
