### ISSUE TITLE
Height of image in Outlook

### ISSUE THREAD

**Issue by Brauwan** [mjmlio/mjml#719]
Hello,

I made a mjml prototype for an email template. The thing is, I have to be able to use it in Outlook. The thing is : outlook just break my code, tear apart my css and deform my image. He use indeed the 100% width but the auto height completely mess up, not respecting proportionnality.

any idea how to fix it ? What are the atribute are you using to settle up your images ?

Thanks,

B.

**Comment by ngarnier** [comment]
Hi, 

I think you [posted this question on OpenClassrooms](https://openclassrooms.com/forum/sujet/responsive-email-envoye-par-outlook?page=1). This is more related to creating an HTML email in Outlook than using MJML, so I'll close the issue and we can keep the discussion on OpenClassrooms. 

Cheers!

**Comment by Brauwan** [comment]
I'd still like to know which attribute you insert in your mj-image to
stabilize your images...

Le 14 juin 2017 17:05, "Nicolas Garnier" <notifications@github.com> a
écrit :

Hi,

I think you posted this question on OpenClassrooms
<https://openclassrooms.com/forum/sujet/responsive-email-envoye-par-outlook?page=1>.
This is more related to creating an HTML email in Outlook than using MJML,
so I'll close the issue and we can keep the discussion on OpenClassrooms.

Cheers!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mjmlio/mjml/issues/719#issuecomment-308460513>, or mute
the thread

**Comment by ngarnier** [comment]
The best option is to set the width of your image only and leave the height so it's automatically adapted and the ratio is respected. By forcing it, you might stretch the image.

Example: https://mjml.io/try-it-live/Byo6PRRf-

**Comment by Brauwan** [comment]
OK, i was not forcing neither width or height. I will try to use a fixed
width but no height value.

Thanks

Le 14 juin 2017 17:36, "Nicolas Garnier" <notifications@github.com> a
écrit :

**Comment by Brauwan** [comment]
Just for you to know, outlook still deform my images, even when fixing the
image width depending on the column width.

**Comment by ngarnier** [comment]
That's strange and not an expected behaviour. Can you please share an example @Brauwan?

**Comment by Brauwan** [comment]
Je t'ai répondu sur open class room (après tout on peut switch en français)

Veux tu un exemple du code ou un screen du visuel du mail ?

Le 15 juin 2017 09:47, "Nicolas Garnier" <notifications@github.com> a
écrit :

**Comment by ngarnier** [comment]
We try to keep things in English here so anyone having the same issue can find an answer 👀 

To be able to help, we need:

- the original MJML code used
- the version of MJML used to convert MJML into HTML
- the result you get versus what you'd like to get (with specifics regarding the email client, ie the version of Outlook you're referring to)

**Comment by faldunate** [comment]
Hello,

I have the same problem using outlook in desktop, apparently only in outlook is not respected the height of the images

@Brauwan Could you get some solution?

**Comment by iRyusa** [comment]
Hi
@faldunate can you share some code please ?
