### ISSUE TITLE
mj-section with margin support

### ISSUE THREAD

**Issue by HLFH** [mjmlio/mjml#720]
Hi,

Let's say I have an email signature and instead of aligning it at center, I want a alignment to the left.
So, instead of a `margin:0px auto`, I should be able to have in HTML a `margin:0px 0px`.

So in MJML:
```mjml
<mj-section margin="0px 0px">
</mj-section>
```
should pe possible to align left the body.

**Comment by ngarnier** [comment]
Hi, 

The `padding` attribute should enable you to do that, example: https://mjml.io/try-it-live/S1T70CAzb

Or do you mean you want the section to be at the far left of the container?

**Comment by HLFH** [comment]
Hi,

> Or do you mean you want the section to be at the far left of the container?

I mean that.

**Comment by ngarnier** [comment]
We're not using margins on the side of the container. Basically, to give you more context, `mj-container` is a fluid-width container made to "contain" your content. It is adapting to the width of the viewports where the email is read on, until a certain max-width: the `width` attribute of `mj-container`. This is one of the principles of the fluid-hybrid method, which we are using in MJML.

What you're asking is a 100% container, which isn't compatible with our approach. As after discussing on the MJML Slack, your need is to create an email signature, the best option is to go with a simple table layout that will do the trick.

I'm closing, hope I answered your questions and feel free to comment if it's not the case or if you have new ones.
