### ISSUE TITLE
Converted MJML not rendering correctly?

### ISSUE THREAD

**Issue by ninetyxtwo** [mjmlio/mjml#723]
Disclaimer, I'm still very new to MJML; so I'm not sure if I'm just missing something or not. Anyways, I use Odoo Enterprise with the Mass Mailer app for email marketing. I think MJML is great and I've created a basic layout with it. However, the problem starts when I convert MJML to HTML and import the code into Odoo.

It seems that Odoo removes everything not found inside the <html>, <head>, and <body> tags of any code once I send out the email for testing so everything comes out as one column in the final product. 

Based on what I've read, I need to run my HTML code through a service like inliner.cm to make all the css show up inline? I did this, but I don't think there were any changes to the codes I made, or even one of the templates available on the mjml site. I copy and paste my "inlined" code into Odoo but the same thing happens. 

Not entirely sure if I'm doing it right. Anyone have any ideas?

**Comment by ngarnier** [comment]
Hi @ninetyxtwo, first, *do not* run the HTML generated by MJML through an inliner. MJML is already inlining the styles to inline, so if anything, this will break styles.

I'm not sure to understand exactly what alterations Odoo is making to the HTML. Maybe it could be worth it to compare the original HTML you import and the HTML after alteration with something like https://www.diffchecker.com/ to see exactly what's happening?

Finally, isn't there any "expert" mode in Odoo to make sure they don't do any modification to the file you import?

**Comment by iRyusa** [comment]
Hi @ninetyxtwo  any news on that ?

**Comment by iRyusa** [comment]
I'm closing this one, feel free to reopen if you can provide more informations !
