### ISSUE TITLE
Pass data inside <mj-include />

### ISSUE THREAD

**Issue by sebmor** [mjmlio/mjml#727]
Would be cool I think if you could

`<mj-include path='./emails/common/header' title='Welcome Email' />`

So I can use the identical header for each template, but with a different title.

**Comment by ngarnier** [comment]
Hey Seb, this has been discussed before and we understand the value of such a feature.

However, it starts with variables, then conditionals, loops... and you end up with reinventing the wheel and building a whole new templating language. There are already a lot of templating languages out there doing the job very well, so we prefer to avoid bundling one in and sticking to responsive email. Yet, you can still use one along with MJML!

**Comment by dzcpy** [comment]
Without a templating language, a lot of important features are implemented very weirdly
