### ISSUE TITLE
Bug: Commenting Out Included Files Doesn't Remove Them From Email

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml#729]
Originally raised [here](https://github.com/mjmlio/mjml-app/issues/160) but posting in this repo as requested by @meriadec 

Tried commenting out an MJML Include block however, the code was not removed in the email even though the block appears to be visually commented out in the editor. Screenshot attached. 

![image](https://user-images.githubusercontent.com/4194561/27495517-ce12b82c-5817-11e7-8ca5-8a47eaaed60b.png)

**Comment by dalefish** [comment]
Not sure if it's the same problem but using the cmd line version there is a
bug where multiple comments in a row will nullify the middle include being
commented out.

I guess it's something to do with the parser, never gave it much thought as
I hadn't seen anyone else with similar, until now.

Try removing the surrounding comments to test the theory.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
Hello @dshastry 

This no longer happens in MJML 4. We'll try to see why it's happening in 3.X branch

**Comment by dshastry** [comment]
Sounds good @iRyusa! Thank you. @dalefish, I tried your method and seems to work for now so I'll tackle that way. Thank you both for the insights
