### ISSUE TITLE
Outlook.com render issue

### ISSUE THREAD

**Issue by ryanstout001** [mjmlio/mjml#73]
Link to testing preview https://www.emailonacid.com/app/acidtest/display/summary/GToyMDR6XGPds9vOte2LXVSInGn1f3Vgfux7DUO7xviAA/shared

First, thank you for creating this. I build emails and double click banners all day and always looking to increase my bandwidth. I would love to implement MJML  but need to be clean in all email clients for our QC process. So I just wanted to share this display check with the community and see if a workaround has been thought up yet. Thanks

**Comment by iRyusa** [comment]
Hey there @ryanstout001 and thanks !

It's because your button `href` is empty. If you set http://mjml.io on both `button` it will render almost ok. 

Currently, outlook.com display a mobile version of the email because of a recent update. I have to see with @hteumeuleu how we can fix it.

**Comment by ryanstout001** [comment]
Thanks @iRyusa , that did the trick sorta. In regards to the mobile display issue. I haven't tested it but heard in the past that in Outlook.com you have to change They changed:

@media only screen and (max-width: 480px) to: @media handheld, only screen and (max-device-width: 480px)

**Comment by acutedeveloper** [comment]
I was going to raise a similar issue. I had performed a test in emailonacid using the demo code. Further testing now has me questioning the outlook.com rendering in EOA.

What I have done is send the test directly to my personal outlook.com account and everything renders as expected.

**EOA test:**
[https://www.emailonacid.com/app/acidtest/display/summary/ALzLk4CgEvPmuNrJ5I4jPrJiXwBHQWDX8PaxxJ25xM2uk/shared](url)

**Direct Outlook.com account:**
![screen shot 2016-02-19 at 09 34 42](https://cloud.githubusercontent.com/assets/2130276/13171691/16efbbde-d6ec-11e5-85cb-0854ffcee559.png)

@ryanstout001 are you able to confirm this? I was going to flag this with EOA.

**Comment by Tlapi** [comment]
@acutedeveloper And this will get a little bit more complicated: https://blogs.office.com/2016/02/17/outlook-com-out-of-preview-and-better-than-ever/
