### ISSUE TITLE
mj-social attribute for adjusting icon's width and height

### ISSUE THREAD

**Issue by maherelaridi** [mjmlio/mjml#730]
Hi!

Is there a way for controlling icon's size without hacking it using images?
Something like this: 
![screenshot 2017-06-23 15 55 23](https://user-images.githubusercontent.com/2089136/27500156-cc5404ae-582c-11e7-88c1-fac5ee75bb1a.png)

It would be really awesome. Thanks!

**Comment by iRyusa** [comment]
Hi @maherelaridi !

Does `icon-size` doesn't work for you ? https://mjml.io/try-it-live/B1WIPRJVZ

**Comment by iRyusa** [comment]
Hi @maherelaridi any news on that or can I close ? :)

**Comment by maherelaridi** [comment]
Hi @iRyusa The `icon-size` cases the social media icon to show pixelated. 

I was able to do this and it worked fine, even though I saw an error saying attributes are illegal.

    <mj-column>
      <mj-text font-size="18" align="center" color="#FFFFFF" letter-spacing="-1">Connect with us!
      </mj-text>
      <mj-social 
                 mode="horizontal" 
                 icon-size="40px"
                 text-mode="false"
                 padding-bottom="20"
                 inner-padding="5"
                 display="facebookc twitterc linkedinc youtubec"
                 facebookc-icon-color="none"
                 facebookc-icon="path-to-icon/icon_fb.png" 
                 twitterc-icon-color="none"
                 twitterc-icon="path-to-icon/icon_tw_2x.png" 
                 linkedinc-icon-color="none"
                 linkedinc-icon="path-to-icon/icon_li_2x.png" 
                 youtubec-icon-color="none"
                 youtubec-icon="http://go.pardot.com/l/218812/2017-06-23/rqg1/218812/40932/icon_yt_2x.png" 
                 facebookc-href="https://www.facebook.com/my-company"
                 twitterc-href="https://twitter.com/my-company"
                 linkedinc-href="https://www.linkedin.com/company-beta/my-company/"
                 youtubec-href="https://www.youtube.com/user/my-company"/>
    </mj-column>
