### ISSUE TITLE
mj-social: Mention `<platform>:{share,url}` syntax for display attribute

### ISSUE THREAD

**Issue by killercup** [mjmlio/mjml#731]
I wanted to add a facebook link to my mail template and the mj-social widget seemed perfect for that. It does, however, generate a "share on facebook" link by prepending `https://www.facebook.com/sharer/sharer.php?u=` to the URL I specify.

By reading [the code](https://github.com/mjmlio/mjml/blob/f57c58d5b58a2731109570d9f6128d935ebf451c/packages/mjml-social/src/index.js#L250-L258) I discovered that the `display` attribute allows values like `display="facebook:url google"`. The `:share` (default)  and `:url` suffixes should be added to the documentation. Or did I miss that section?

**Comment by iRyusa** [comment]
Hi @killercup 
There's a notice on the documentation cf : 

> Note that you can disable default sharing option by adding :url on any social network. Example: <mj-social display="facebook" /> will render https://www.facebook.com/sharer/sharer.php?u=[[facebook-href]] url, and <mj-social display="facebook:url" /> will render [[facebook-href]] url

Just after the try-it-live button https://mjml.io/documentation/#mjml-social

**Comment by killercup** [comment]
Thanks for the super fast reply!

Ohhh, I totally missed that! I apparently only parsed the attributes table, sorry.
