### ISSUE TITLE
Mj-Attribute as separate include file ?

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#732]
Hi there not sure if there was another question or issue like this but is it possible to make your mj-attribute tags in a separate file and use a mj -include to insert it in the head of the mjml itself??

**Comment by iRyusa** [comment]
Hello @lrae24 

Yes, you can either do a partial with a mj-head  and include it anywhere in the file : 

```
<mj-head>
  <mj-attributes>
     <mj-all padding="0" />
  </mj-attributes>
</mj-head>
```

Or just without `mj-head` and mj-include it in your mj-head of your main file: 
```
<mj-attributes>
  <mj-all padding="0" />
</mj-attributes>
```

**Comment by dalefish** [comment]
You already can, save your <mj-head> and contents in a file called
head.mjml, then <mj-include path="./head.mjml" />

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by lrae24** [comment]
Thanks .
