### ISSUE TITLE
mj-button with href on Office365 Outlook webmail

### ISSUE THREAD

**Issue by molocLab** [mjmlio/mjml#733]
Hi!

On Office365 Outlook webmail this code:

```
          <mj-button font-family="Helvetica" background-color="#f45e43" color="white">
            Don't click me!
          </mj-button>
```

works perfectly.

This one:

```
          <mj-button font-family="Helvetica" background-color="#f45e43" color="white" href="#">
            Don't click me!
          </mj-button>
```

doesn't (It breaks layout totally !?).

I think the problem is that the first code generate a <p> tag, the second one an <a>.
Is there some workarounds or Office365 Outlook webmail is not supported?

<mj-button> without href becomes useless....:(

Thanks!

**Comment by molocLab** [comment]
Ok, I've investigated a little bit more.

**The problem is not href but href="#"**.

For testing I'm using href="#" (I don't know yet the url).
I don't know why, but It breaks totally the layout. With a real url all works perfectly.

**Comment by dalefish** [comment]
This is to be expected, it's not a valid href for email

**Comment by bago** [comment]
You can find details on Outlook.com/Office365 behaviour here:
https://mosaico.io/email-client-tricks/outlook-com-office-365-empty-a-style-issue/

**Comment by dalefish** [comment]
Also,
https://emails.hteumeuleu.com/what-you-need-to-know-about-the-new-outlook-com-8d2c54719398

Kind Regards,

:----------------------------:
Dale McConnell
