### ISSUE TITLE
mjml-carousel-image missing "title" attribute

### ISSUE THREAD

**Issue by thechrise** [mjmlio/mjml#734]
MJML Carousel Image is missing the "title" attribute in MJML v.3.3.3 and registered as an illegal attribute in MJML App v.2.4.0.

Also, it would be great if the "title" attribute for each mjml-carousel-image could be displayed as a caption below the hero carousel image when active.

**Comment by thedamianmason** [comment]
This doesn't appear to be fixed. Not in the Desktop application on MacOS anyway.

**Comment by iRyusa** [comment]
I don't think the desktop app has been updated yet to 3.3.4

**Comment by thedamianmason** [comment]
I still shows as an illegal attribute when I use 3.3.5 and 4.0 as the engine.

**Comment by ngarnier** [comment]
@thedamianmason just tried with 3.3.5 and v4 and I didn't get any validation error. Are you using a specific plugin? 

You can also see that the `title` attribute is correctly rendered in the HTML.

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-carousel>
            <mj-carousel-image title="my title" src="https://www.mailjet.com/wp-content/uploads/2016/11/ecommerce-guide.jpg" />
            <mj-carousel-image src="https://www.mailjet.com/wp-content/uploads/2016/09/3@1x.png" />
            <mj-carousel-image src="https://www.mailjet.com/wp-content/uploads/2016/09/1@1x.png" />
          </mj-carousel>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by thedamianmason** [comment]
But the issue is that it does not render before HTML conversion.

**Comment by ngarnier** [comment]
If you try the snippet just above you'll see it is correctly rendered, try this link: https://mjml.io/try-it-live/SylEk-ZLz. 

In the HTML, you can see that the title attribute is correctly rendered.

**Comment by thedamianmason** [comment]
Not showing. 
My Env:
MacOS High Sierra
Opera Web Browser and Chrome Web Browser
