### ISSUE TITLE
MJML Extensions for VSCode

### ISSUE THREAD

**Issue by vikrantnegi** [mjmlio/mjml#736]
Just like Atom plugins, can we have similar extensions for the VScode as well?

**Comment by ngarnier** [comment]
We don't provide any official VSCode package, however you can find a community one here: https://github.com/attilabuti/vscode-mjml. 

I haven't tried it but it looks pretty neat, I would love to know what you think of it!

**Comment by vikrantnegi** [comment]
Ok great. Will let you know how efficient that package works. 
Thanks for your hard work.

**Comment by ngarnier** [comment]
It's a pleasure! I'm closing but let us know what you think of it :)
