### ISSUE TITLE
Left & Right Padding Outlook

### ISSUE THREAD

**Issue by jacobroberts6** [mjmlio/mjml#737]
Hi Guys, 

New to Git and MJML, recently started building all my new templates in MJML and loving how easy it is to use.

I've just built an email with a full width image but in outlook it is adding padding left and right even though I have set it to no padding. Would anyone be able to help? 
![2017-07-05 10_06_17-mjml app](https://user-images.githubusercontent.com/29915532/27857466-b32e1302-6169-11e7-93a8-b96ef181083f.png)
![2017-07-05 10_05_04-inbox - jacob roberts brookson co uk - outlook](https://user-images.githubusercontent.com/29915532/27857465-b32b6da0-6169-11e7-826f-b60c2b9cddec.png)

**Comment by jacobroberts6** [comment]
Code below: 

<mjml>
  <mj-head>
    <mj-attributes>
      <mj-button border-radius="0px">
      </mj-button>
      <mj-all font-family="Roboto, Arial" />
      <mj-text color="#000000" />
      <mj-container background-color="#f2f2f2" />
    </mj-attributes>
    <mj-style>
      #contact{padding-top:10px}
      @media (max-width:480px) {#contact{display:none}#contact-1{display:none}#banner-text{font-size:16px}#footer-number{text-align:left}}
    </mj-style>
    <mj-font name="Roboto" href="https://fonts.googleapis.com/css?family=Roboto" />
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
       <mj-text align="center" font-size="10px"><a style="color:#bbbbbb; text-decoration:none" href="http://$CANTREAD$">View Email Online</a>
        </mj-text>
      </mj-section>
      <mj-wrapper padding="0px" border="solid 2px #eee">
        <mj-section background-color="#fff">
          <mj-column width="50%" align="left">
            <mj-image padding-top="0px" padding-bottom="0px"  align="left" width="150" height="63" src="https://www.brookson.co.uk/globalassets/documents/emails/brookson-one/brookson-one-logo.png" href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">
            </mj-image>
          </mj-column>
          <mj-column width="50%">
            <mj-text padding-top="0px" padding-bottom="0px" align="right">
              <p style="Margin:0px" id="contact">
                <b style="color:#ed520f;">Call:                
                </b> <a style="color:#000000; text-decoration:none" href="tel:08002300213">0800 230 0213</a>          
                
              </p>
            <p id="contact-1" style="Margin:0px">
              <b style="color:#ed520f;">Email:
              </b> <a style="color:#000000; text-decoration:none" href="mailto:friend@brookson.co.uk?bcc=marketing@brookson.co.uk&subject=I'd like to make my 1st referral&body=Hi,%0D%0A%0D%0AI would like to refer a friend to Brookson. Here is their name, contact number and email address.">friend@brookson.co.uk</a>
            </p>
          </mj-text>
        </mj-column>
      </mj-section>
    <mj-section padding="0px" background-color="#fff">
      <mj-column>
        <mj-image width="600" padding="0px"  src="https://www.brooksonone.co.uk/globalassets/documents/raf-2017/raf-june-banner-email.jpg">
        </mj-image>
      </mj-column>
    </mj-section>
    <mj-section padding="10px" background-color="#ed520f">
      <mj-column background-color="#ed520f" >
        <mj-text  align="center" color="white" font-size="18px">
          <span id="banner-text">REFER TODAY FOR YOUR COMPLETE CONTRACTOR PACKAGE
          </span>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff">
      <mj-column>
        <mj-text >
          <p>
            <span style="font-size:20px; color:#000;">Dear @FIRSTNAME@
            </span>
          </p>
          <p>
            We want to ensure you’re always working smartly and that’s why we’re bringing you our latest suite of rewards. So refer a friend and choose from either 12 months Kingsbridge insurance giving you peace of mind, the new iPad which will give you everything you need at your fingertips. 
          </p>
          <p>Looking for something specific? Not to worry, our voucher option gives you access to hundreds of high street stores and last but not least, you can always choose to keep it simple and opt for 2 months free Limited Company Accountancy service.
          </p>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section padding="0px" background-color="#ffffff">
      <mj-column width="33%">
        <mj-image padding="0px" width="160" height="160" src="https://www.brooksonone.co.uk/globalassets/documents/raf-2017/raf-june-insurance.jpg" href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">
        </mj-image>
        <mj-button href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand" padding-bottom="40px" background-color="#000000" font-size="13px" inner-padding="10px" width="160" >12 Months 
          <br> Contractor Insurance
            </mj-button>
          </mj-column>
        <mj-column width="33%">
          <mj-image padding="0px" width="160" height="160" src="https://www.brooksonone.co.uk/globalassets/documents/raf-2017/raf-june-apple.jpg" href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">
          </mj-image>
          <mj-button href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand" padding-bottom="40px" background-color="#000000" font-size="13px" inner-padding="10px" width="160" >Apple 
            <br> iPad
              </mj-button>
            </mj-column>
          <mj-column width="33%">
            <mj-image padding="0px" width="160" height="160" src="https://www.brooksonone.co.uk/globalassets/documents/raf-2017/raf-june-vouchers.jpg" href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">
            </mj-image>
            <mj-button href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand" padding-bottom="40px" background-color="#000000" font-size="13px" inner-padding="10px" width="160" >£200 LOVE2SHOP Vouchers
            </mj-button>
          </mj-column>
          </mj-section>
        <mj-section padding="0px 0px 40px 0px" background-color="#ffffff">
          <mj-column>  
            <mj-text>To get hold of one of our rewards, simply refer a friend or colleague to Brookson and when they join our Limited Company Accountancy service, you will both be rewarded! 
            </mj-text>
          </mj-column>
        </mj-section>
        <mj-section padding="10px" background-color="#888b8d">
          <mj-column >
            <mj-text align="center" color="white" font-size="18px">
              <span id="banner-text">HOW IT WORKS
              </span>
            </mj-text>
          </mj-column>
        </mj-section>
        <mj-section padding="40px 0px 30px 0px" background-color="#ffffff">
          <mj-column>
            <mj-image src="https://www.brooksonone.co.uk/globalassets/documents/raf-2017/raf-june-how.jpg" href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">
            </mj-image>
            <mj-spacer height="30">
            </mj-spacer>
            <mj-button background-color="#ed520f" font-size="16px" href="mailto:friend@brookson.co.uk?bcc=marketing@brookson.co.uk&subject=I'd like to make my 1st referral&body=Hi,%0D%0A%0D%0AI would like to refer a friend to Brookson. Here is their name, contact number and email address.">REFER NOW &nbsp; &nbsp; >
            </mj-button>
          </mj-column>
        </mj-section>
        <mj-section padding="0px 0px 0px 0px" background-color="#ffffff">
          <mj-column width="50%">
            <mj-text font-size="14px" font-weight="bold" align="left"><a style="color:#000000; text-decoration:none" href="http://www.brookson.co.uk/share?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">BROOKSONONE.CO.UK/SHARE</a>
            </mj-text>
          </mj-column>
          <mj-column width="50%">
            <mj-text font-size="14px" font-weight="bold" align="right">
              <p style="Margin:0px" id="footer-number"><a style="color:#000000; text-decoration:none" href="tel:08002300213">0800 230 0213</a>
              </p>
            </mj-text>
          </mj-column>
        </mj-section>
        <mj-section padding="0px 0px" background-color="#ffffff">
          <mj-column width="100%">  
            <mj-divider padding-top="0px" padding-bottom="0px" width="100%" border-width="1px">
            </mj-divider>
          </mj-column>
        </mj-section>
        <mj-section padding="0px 0px 0px 0px" background-color="#ffffff">
          <mj-column width="100%">
            <mj-text font-size="10px" color="#bbbbbb" align="left"><a style="color:#bbbbbb; text-decoration:none" href="https://www.brooksonone.co.uk/recommend-a-friend/customer-tc/?utm_source=RAF&utm_medium=Email&utm_campaign=RAF-June-Rebrand">*Terms & Conditions Apply</a>
            </mj-text>
          </mj-column>
        </mj-section>
      </mj-wrapper>
       <mj-section>
            <mj-text color="#bbbbbb" align="center" font-size="10px">
              <a style="color:#bbbbbb; text-decoration:none" href="http://$unsub$">Unsubscribe
              </a>
            </mj-text>
          </mj-section>
        </mj-container>
      </mj-body>
    </mjml>

**Comment by iRyusa** [comment]
Hi @jacobroberts6 !

You have some padding left & right in some `mj-section` into your `mj-wrapper` so the table width exceed 600px (and this is why you have some empty space ). It should work fine when using padding into your element (like `mj-text`/`mj-image`/ etc etc) instead of `mj-section`

**Comment by jacobroberts6** [comment]
Hi @iRyusa 

I have set all of the `mj-section` to have 0px padding and `mj-imnage` has 0px padding but Outlook is still adding in this padding?

**Comment by iRyusa** [comment]
With some testing I think I got it this time. Issue was with your 3 column images, button had a too large default padding so it breaks the wrapper width as mentioned earlier. Just add a padding="0" on all 3 `mj-button` and it looks fine on litmus now : https://mjml.io/try-it-live/rkf1QE94-

<img width="798" alt="screen shot 2017-07-05 at 11 43 36" src="https://user-images.githubusercontent.com/570317/27858886-3d541e84-6177-11e7-96aa-e941502b4eaa.png">

**Comment by jacobroberts6** [comment]
Thanks @iRyusa! Thats fixed it! Thanks for the help!
