### ISSUE TITLE
mjml-invoice total is always zero

### ISSUE THREAD

**Issue by logankoester** [mjmlio/mjml#739]
I've tried a variety of formats and values, but I can't seem to get the mjml-invoice component to calculate any non-zero total price.

I am using the latest release version, but the issue is also apparent in the try-it-live link in the documentation: https://mjml.io/try-it-live/components/invoice

**Comment by iRyusa** [comment]
Hi @logankoester 

We're sorry about that, we'll fix this with this PR #690 in 3.3.4 !

**Comment by logankoester** [comment]
@iRyusa Great! I searched existing issues but I didn't see that PR, sorry for the dupe & thanks for the quick answer.
