### ISSUE TITLE
Creating a component that extends MJML Wrapper

### ISSUE THREAD

**Issue by 10kc-zack** [mjmlio/mjml#741]
**Issue**
I want to create a component that extends or wraps `mjml-wrapper` and allows me to still render any children passed to it. I've tried my own implementation, but it failed. Is there any way to accomplish this?

Using MJML `v3.3.3`.

**`custom-wrapper.js`**
```js
import Column from 'mjml-column';
import React, { Component } from 'react';
import Section from 'mjml-section';
import Spacer from 'mjml-spacer';
import Wrapper from 'mjml-wrapper';
import { MJMLElement } from 'mjml-core';

const tagName = 'custom-wrapper';
const parentTag = ['mj-container'];
const endingTag = true;
const defaultMJMLDefinition = {
  content: ''
};

@MJMLElement
class CustomWrapper extends Component {
  render() {
    const { mjContent } = this.props;
    return (
      <Wrapper>
        <Section>
          <Column>
            <Spacer />
          </Column>
        </Section>
        {mjContent()}
        <Section>
          <Column>
            <Spacer />
          </Column>
        </Section>
      </Wrapper
    );
  }
}

CustomWrapper.tagName = tagName;
CustomWrapper.parentTag = parentTag;
CustomWrapper.endingTag = endingTag;
CustomWrapper.defaultMJMLDefinition = defaultMJMLDefinition;

export default CustomWrapper;
```

**`my-template.mjml`**
```mjml
<mjml>
  <mj-body>
    <mj-container>
      <custom-wrapper>
        <mj-section>
          <mj-column>
            <mj-text>Another section</mj-text>
          </mj-column>
        </mj-section>
      </custom-wrapper>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hey @10kc-zack !

Can you explain a bit what's failing ?
I think you probably need to pass current props to your wrapper.

**Comment by 10kc-zack** [comment]
@iRyusa The error I'm receiving is
```
ERROR - mjml2html:
TypeError: Cannot read property 'mjml' of undefined
```
I found the stacktrace to point tohttps://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/decorators/MJMLElement.js#L104. I wasn't sure what the solution to this error would be though.

Thanks for the reply!

**Comment by iRyusa** [comment]
Yeah this is exactly the same issue with #489 `mjml` props isn't build properly so component fails to render. 

This is tricky to fix for now, and it is fixed in MJML4. MJML 3's dev is frozen now ( last release should be 3.3.4 with minor fixes ), so I think you'll have to wait for MJML4 sorry about that.

I'm closing because #489 is almost exactly the same issue (same root).
