### ISSUE TITLE
Echoing values

### ISSUE THREAD

**Issue by jgralinski** [mjmlio/mjml#743]
I'm trying to build a re-usable templates and am curious if there is a way to set a single variable near the top of the code and then echo it in multiple places later.  Like list a link variable once up top and echo it in the body in multiple href areas.

similar to a simple php variable and echo

**Comment by iRyusa** [comment]
Hi @jgralinski 

MJML is a markup language so there's no such thing as variable, or conditionnal structure. You could use something like handlebars, mustache or any templating language to do this job.
