### ISSUE TITLE
API Server Down ?

### ISSUE THREAD

**Issue by jsahani** [mjmlio/mjml#744]
Hi Team,

Where can i get the status page for your API ? As right now your server is not responding and we have used it inside our app to generate email templates.

Thanks

**Comment by ngarnier** [comment]
The API is back online, sorry for the inconvenience!

**Comment by jsahani** [comment]
Thanks for the info @ngarnier but i wanna know is it possible to create a failsafe on my own server ? I mean like first my app will hit MJML API but if any in case its down or not responding then another call will hit my own server to render the MJML into HTML ? If this is possible then please tell me how ?

Thanks in advance.
Jatin Sahani

**Comment by SidVal** [comment]
The API is down right now: https://mjml.io/api 😞
