### ISSUE TITLE
Warning: No handler found for: mj-style, in mj-head, skipping it

### ISSUE THREAD

**Issue by ijagbemi2313** [mjmlio/mjml#745]
I get this warning message any time I try to compile using the <mj-style> component

**Comment by Kant1-0** [comment]
Hi @ijagbemi2313 can you share your MJML version and your code ?

**Comment by ijagbemi2313** [comment]
MJML Version: 2.1.1

Code:
```<mjml>
  <mj-head>
    <mj-style>
      @media all and (max-width: 480px) {
        .mobile-view {
          text-align: center !important;
        }
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-container background-color="#f7f7f7"
                  width="550">

      <!-- VIEW ONLINE VERSION -->
      <mj-section padding="0">
        <mj-column>
          <mj-text  mj-class="mobile-view"
                    color="#999999"
                    font-family="Roboto Condensed"
                    font-weight="100"
                    font-size="14"
                    align="right"
                    padding-right="0">
                    <a href="#" target="_blank" style="text-decoration:none; color:#999999;">
                    View the online version <img src="https://i.imgur.com/6togNX0.png" style="width: 6px; padding-left: 10px;">
                    </a>
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>```

I simply want to override right alignment of the td element, [align="right"] without having to touch the compiled HTML file.

**Comment by Kant1-0** [comment]
You will need to migrate to 3.3.3 because mj-style was introducing with the version 3.0.0

**Comment by ijagbemi2313** [comment]
Thanks for your help @Kant1-0 

If you'd kindly oblige, wot the command line for updating to this latest version?

**Comment by meriadec** [comment]
If mjml is installed locally you can `npm install mjml@3.3.3 --save`, if it's installed globally you can `npm install -g mjml@3.3.3` (may require `sudo` if you're on mac/linux)

**Comment by Kant1-0** [comment]
You'r welcome @ijagbemi2313 😉 

Depending which way you use MJML, you'll need to download the new realease app or update with npm : https://mjml.io/download

This command line will update your package locally `npm update mjml --save`

**Comment by ijagbemi2313** [comment]
Wow thanks guys @Kant1-0 & @meriadec ...Works perfectly. Really do appreciate.
