### ISSUE TITLE
Google Webfonts legacy IE Issue

### ISSUE THREAD

**Issue by Quantastical** [mjmlio/mjml#746]
For some silly reason, IE doesn't work well with Google web fonts when loading multiple fonts in the same resource file (see: https://stackoverflow.com/a/10885925/1028949). The solution is load font files separately for IE.

The follow MJML:

```
<mj-font name="Open Sans" 
               href="https://fonts.googleapis.com/css?family=Open+Sans" />
```

Should include IE-specific font stylesheets:

```
<!-- Current output (keep this)
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,700" rel="stylesheet" type="text/css">
<!-- Proposed additions (add the following to the head as well) -->
<!--[if IE]>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400" /> 
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:500" /> 
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:700" />
<![endif]-->
```

I'm proposing to add an IE conditional statement, even though the StackOverflow reference suggests IE 8 and below. I am experiencing the same problem in IE11 and the separated references seems to resolve the issue.

**Comment by iRyusa** [comment]
Hi @Quantastical 

Well I understand the issue, but why won't you insert a new`mj-font` for each weight ? Like this : 

```xml
<mj-font name="Open Sans Light" 
               href="https://fonts.googleapis.com/css?family=Open+Sans:300" />
<mj-font name="Open Sans Regular" 
               href="https://fonts.googleapis.com/css?family=Open+Sans:500" />
...
```

**Comment by Quantastical** [comment]
I didn't think to do that. Thanks for the direction. That's probably better than building in some IE hack. Thanks again.
