### ISSUE TITLE
Dividers duplicated in Outlook

### ISSUE THREAD

**Issue by MissFerrety** [mjmlio/mjml#747]
I have an issue with at least some combinations of PC/Outlook wherein the rendered HTML will output two lines for every `<mj-divider>`. One fellow noticed it only on his PC while other PCs and Mac users had no issue. We were able to replicate it on an old laptop we have around.  It seems that this particular combo listens to both the original HTML _and_ the MSO conditional that gets rendered, leaving these double lines all over the place!

The setup I managed to duplicate it on (let me know if you need more):

> Windows 7 Enterprise, SP1; 64-bit OS
Microsoft Office Professional Plus 2010 (v. 14.0.7182.5000 (32-bit)

**Comment by iRyusa** [comment]
Hi @MissFerrety 

Can you provide more information about it, your MJML version and MJML to reproduce ? Does it happens on litmus as well or email on acid ?

**Comment by Renjaminino** [comment]
Can confirm, it happens on mjml 3.3.3 - happens on the pardot litmus test.

2007-10-13-16 all seem to show doubles, everything else, including outlook.com is fine.

<img width="591" alt="screen shot 2017-07-19 at 11 35 18" src="https://user-images.githubusercontent.com/25082531/28375821-8beec3b4-6c76-11e7-87a3-dce5362d74cc.png">

**Comment by iRyusa** [comment]
Looks fine on Outlook  2007 with default mjml from https://mjml.io/try-it-live
![image](https://user-images.githubusercontent.com/570317/28376064-650d3cb6-6ca9-11e7-99aa-a06522782b57.png)

**Comment by MissFerrety** [comment]
Even just the default sample provided via the Try It Live feature (both the [basic](https://mjml.io/try-it-live) and the [mj-divider](https://mjml.io/try-it-live/components/divider) ones) can make this happen.

I'm using v3.3.3 to render locally.

For the use case, I am sending via Slate.  We have only -just- gotten Litmus, so I will have to get back to you on that if still needed.

**Comment by MissFerrety** [comment]
For those interested, here is my current workaround:

    <mj-section>
        <mj-column>
            <mj-raw><div style="height: 0; border-top: 4px solid #F45E43;" /></mj-raw>
        </mj-column>
    </mj-section>

**Comment by tmalone66** [comment]
I am also working with MissFerrety on this project and when I tried her work around for the line, for some reason they stack on top of each other and make the line thicker instead of going underneath the copy in the <mj-text> line.

Can anyone offer help with this problem?

**Comment by iRyusa** [comment]
> For the use case, I am sending via Slate. We have only -just- gotten Litmus, so I will have to get back to you on that if still needed.

Can you confirm this bug appears on litmus as well, I'm unable to reproduce on it @tmalone66 ? Might be slate altering the HTML ?

**Comment by MissFerrety** [comment]
I haven't refined the workaround yet, as it's meant to be a hotfix so everything doesn't have to go back to the design team. My current solution above relies on the `mj-raw` being contained in its own section/column. @tmalone66 would like to use it in a project where the lines are mostly used in a sidebar, which breaks the "own-section" requirement, as anything in `mj-raw` will render above the rest of the valid MJML in a section, so multiple raws interspersed throughout will all stack at the top of the section.

**Comment by MissFerrety** [comment]
Here's a Litmus I ran with a few testing/solution attempts.

https://litmus.com/checklist/emails/public/b9228ce

**Comment by iRyusa** [comment]
> as anything in mj-raw will render above the rest of the valid MJML in a section, so multiple raws interspersed throughout will all stack at the top of the section. (Should this be its own issue?)

I don't really understand that part can you provide some examples ?

**Comment by MissFerrety** [comment]
@iRyusa 

    <mj-section>
        <mj-column>
            <mj-text>This text should be the first thing on the page, followed by a red line.</mj-text>
            <mj-raw><hr style="border: 1px solid #F00;" /></mj-raw>
            <mj-text>This text should be followed by a blue line.</mj-text>
            <mj-raw><hr style="border: 1px solid #00F;" /></mj-raw>
        </mj-column>
    </mj-section>


![screen shot 2017-07-19 at 1 01 48 pm](https://user-images.githubusercontent.com/12651457/28382067-77f51b54-6c82-11e7-8a52-27a2a33a2689.png)

**Comment by iRyusa** [comment]
This is not a bug from MJML, if you inspect the HTML output, you have now `hr` in a `tbody`. 
Browser just moves the hr out of the tbody. You can add a TR/TD to fix this behaviour in your mj-raw

**Comment by iRyusa** [comment]
Can you try to send the basic divider MJML through a clean service like putsmail.com if it works fine on outlook ?

**Comment by MissFerrety** [comment]
Including a TR/TD still triggers some awkward rendering. It seems that the existence of a raw will forcibly close at least one of the divs/tables it's in, pushing following components into another container.

    <mj-section>
        <mj-column>
            <mj-text>This is the first column. Everything else should be on the right.</mj-text>
        </mj-column>
        <mj-column>

            <mj-text>This text should be the first thing on the page, followed by a red line.</mj-text>

            <mj-raw><tr><td><hr style="border: 1px solid #F00;" /></td></tr></mj-raw>

            <mj-text>This text should be followed by a blue line.</mj-text>

            <mj-raw><tr><td><hr style="border: 1px solid #00F;" /></td></tr></mj-raw>

        </mj-column>
    </mj-section>


![screen shot 2017-07-19 at 2 24 07 pm](https://user-images.githubusercontent.com/12651457/28385511-f5e44cb4-6c8d-11e7-8049-78e46aa63ead.png)

**Comment by MissFerrety** [comment]
@iRyusa Putsmail worked as expected.

**Comment by MissFerrety** [comment]
**UPDATE**
I had been trying to use the most concise and seemingly canonical solution with the least amount of preconceived styling associated with it, hence my previous solution. However, Many variations on it cause certain issues with the flow.  As such, I'll be using this for now:

    <mj-text>
        <div style="border-top: 4px solid #0F0;"></div>
    </mj-text>

**Comment by iRyusa** [comment]
Never seen mj-raw breaking a column like that (you can open a separate issue if needed), mj-raw is more consistent in MJML4 so it will no longer be an issue.
If putsmail work as expected then it comes from your ESP altering the email and there's nothing we can do about it

**Comment by MissFerrety** [comment]
@iRyusa I appreciate that, but it might be worth looking into since it's a highly-ranked standard component that even Litmus has issues with, and at least one other frequently used system does the same thing.  As far as raw goes, I'll see about it tomorrow.

**Comment by iRyusa** [comment]
I am totally unable to reproduce on litmus as mentioned earlier cf https://github.com/mjmlio/mjml/issues/747#issuecomment-316427976

**Comment by iRyusa** [comment]
As said, we're unable to reproduce on a clean ESP with putsmail and litmus, might be your ESP altering something. 

We'll reopen if we find out a way to reproduce it
