### ISSUE TITLE
mj-image works incorrectly when both width and height are set

### ISSUE THREAD

**Issue by ipa1981** [mjmlio/mjml#748]
If both height and width are set for mj-image, it get improportionally resized:

 **Reproduction Steps:**
Example from documentation:

https://mjml.io/try-it-live/BJcwxIAH-

Just add `height="227"` (a proportional height of this particular picture) to `<mj-image>` tag and try switching mobile and desktop versions. Image gets squeed with different height/width proportions.

**Expected behavior**
Proportions should remain the same and image should not be squeezed when both parameters are set.

**Observed behavior:**
A produced code is 

```
<img alt="" title="" 
height="227" src="http://www.online-image-editor.com//styles/2014/images/example_image.png"
style="border:none;border-radius:0px; display:block;font-size:13px;outline:none; 
text-decoration:none;width:100%;height:227px;" width="300">
```
While produced code get correct values for `height` and `width` attributes, the CSS `width` remains 100%. This breaks proportionality of the image.

**MJML version:**
3.3.3

**Comment by dalefish** [comment]
That is expected behavior, if you don't set height, it defaults to auto.

When you set a height explicitly, it will stay at that height.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ipa1981** [comment]
@dalefish and this is exactly the opposite to how `width` behaves. As you see in resulting code the `width` is `auto` even if set.

**Comment by dalefish** [comment]
I was talking about height, not width....

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ipa1981** [comment]
And the issue is about situation when both are set precisely. Not the `height` alone.

**Comment by dalefish** [comment]
Indeed. Remove height and it will stop breaking, just set the width.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ipa1981** [comment]
I'm posting a problem here when you set `height` according the documentation.
For sure I can avoid using `height`, but it is documented feature which doesn't work as expected.
Actually I just found that it fails even `height` is set only. `width` remains in force. 

Just change `width="300"` to `height="300"` and proportions of the image breaks up 
https://mjml.io/try-it-live/r1OgoPRB-

**Comment by dalefish** [comment]
I'm not a part of the MJML team so I'm not going to go down into whether a
'feature' works or not.

However, this seems like a basic misunderstanding about responsive
development. You wouldn't set a fixed height on an object for the web if
you want it to be responsive and maintain aspect ratio. The same goes for
email.

You only need to set a height in MJML if you want it to stay that height,
otherwise it is completely unnecessary.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ipa1981** [comment]
Not every image should be responsive. You have buttons, design elements or something else. This is a W3C standard you expect to work.

Tell me what do you expect if you set `<mj-image src="red-color-gradient.png" width="200" height="200">` ? I would expect a square of red gradient, regardless the screen width, and you?

**Comment by dalefish** [comment]
Yes they should. MJML is a responsive email framework, images are
responsive by default.

If you want it to do something it is not intended to do, you need to hard
code a custom solution.

With that code I would expect a square of 200x200, assuming it would fit
inside a container. if the container is smaller, I would expect a 200h X
whatever width square. As it coded to be.

Fixed aspect ratio images can be done in MJML, just not easily with the
default responsive elements.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by ipa1981** [comment]
OK, I see that it would be hard to implement it to resize proportionally anyway. If it means as expected MJML, let it be. Closing the issue.
Thanks for your time @dalefish
