### ISSUE TITLE
Add target attribute to custom social icon tag

### ISSUE THREAD

**Issue by katart** [mjmlio/mjml#749]
I've created custom social icons within the `mj-social` tag.

The generated code wraps the icon png with an `a` tag, but there is no way to add a `target` attribute. I would like to set a `target="_blank"` to all of these custom links.

Is this possible?

**Comment by iRyusa** [comment]
Hi @katart 

Sorry mj-social won't support target attribute yet , we might consider to add it to MJML 4.

**Comment by ngarnier** [comment]
Now available in 4.0.1
