### ISSUE TITLE
change align based on media query?

### ISSUE THREAD

**Issue by paOol** [mjmlio/mjml#75]
I have some ```<mj-text>``` that should be align="left" on desktop, but I'd like it to be align="center" when it's the mobile view.

is this currently possible?

**Comment by iRyusa** [comment]
Hello @paOol 

I'm afraid that we can't with current MJML version. Do you have any idea on how to implement that feature ?

**Comment by paOol** [comment]
I don't, but I do have an idea of how it should work and that might help you come up with a solution.

it should work like so

```
<mj-text desktop={align="left"} tablet ={align="right"} mobile ={ align="center"} >
```

or

if you look at https://github.com/contra/react-responsive and follow the same idea, 

```
 <MediaQuery maxDeviceWidth={480}>
          <mj-text align="center">You are a mobile phone</mj-text>
  </MediaQuery>

 <MediaQuery maxDeviceWidth={1024}>
          <mj-text align="left">You are a tablet</mj-text>
  </MediaQuery>
```

although that is highly repetitive.

**Comment by iRyusa** [comment]
Well due to lack of support of media queries in most of clients, i believe this wont be possible.
If anyone has a solution feel free to reopen.

**Comment by jitendravyas** [comment]
this is a good idea. it can be possible with mjml, many clients supports media query so it can at least work in them

**Comment by ngarnier** [comment]
I like the idea but as @iRyusa said, most clients don't support media queries. Then, it wouldn't work for the majority of email clients and would break consistency.

For media queries support, see [this post](https://litmus.com/help/email-clients/media-query-support/) by Litmus.
