### ISSUE TITLE
Problem with the width of mjml-column on Outlook

### ISSUE THREAD

**Issue by faldunate** [mjmlio/mjml#750]
Hi Guys!

I've been using MJML in the last moment and all work fine, until I started to test my emails in outlook. Now I have a problem with the width of columns, It's like it does not have a defined width. Also all the columns are centered, even using `align = "left"`

This problem only happens in outlook desktop

This is my code:

`          
<mj-section>
   <mj-group>
        <mj-column width="10%" align="left">
             <mj-text padding="0">
                  <span style="min-width: 30px">#1</span>
                </mj-text>
              </mj-column>
              <mj-column width="30%" align="left">
                <mj-image padding="0" src="http://...." width="45px" border-radius="50%" />
              </mj-column>
              <mj-column width="40%" align="left">
                <mj-text padding="0">
                  <span style="display: block; width: 90px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                    Francisco Aldunate
                  </span>
                </mj-text>
              </mj-column>
              <mj-column width="20%" align="left">
                <mj-text padding="0">
                  <span style="border-radius: 0.3em; display: block; color: white; width: 60px; text-align: center; background-color: #000">300</span>
                </mj-text>
              </mj-column>
            </mj-group>
          </mj-section>`

Anyone have any ideas? Am I doing something wrong?

**Comment by iRyusa** [comment]
Hello @faldunate 
I don't have any issue with outlook desktop with your markup, can you specify the version ?
Can you try to send your email via a service like putsmail.com to see if it's your ESP messing with the HTML ?

Thanks

**Comment by faldunate** [comment]
Thank you for your response @iRyusa

I'm using mjml 3.0.0

I tested with putsmail and doesn't show all columns centered (that is ok), but outlook doesn't respect the width of columns yet.

Here the screenshot of emails:

Outlook:  http://snapnote.io/0xdLD6 (putsmail)
Gmail: http://snapnote.io/01LBQe

**Comment by iRyusa** [comment]
What's this version of outlook ? Can you try to update MJML to 3.3.3, you're missing a lot of fixes & feature, and it could fix your issue

**Comment by faldunate** [comment]
This happens in Outlook 2016 - Windows 7, I tried with Outlook 2016 for Apple and work fine.

Now I updated version of mjml(3.3.3) but the same problem is still happening with Outlook 2016 for windows

**Comment by iRyusa** [comment]
Can you share the whole template so we can investigate ?

**Comment by faldunate** [comment]
Here the whole template

https://codeshare.io/adkjOy

Thank you @iRyusa for your help

**Comment by iRyusa** [comment]
It seems like your nesting a section within a column that might be why you have an issue on outlook.

For this kind of layout you may need to use a simpler approach with a mj-table. Even if you can't use mjml element within a mj-table, it does the job better and way easier than your current implementation : https://mjml.io/try-it-live/SJfwiXlU-

**Comment by faldunate** [comment]
hey @iRyusa Thank you for your help.

Before I was using mj-table but when I used a `img` inside of mj-table it broke the email.

**Comment by iRyusa** [comment]
Never had any issue with img tag, can you share some where it's break ?

**Comment by faldunate** [comment]
hey @iRyusa I could to do that email be shown a little bit better using `mj-table` and `img` inside of table. I have specified the `width` and `height`, but now the image is cut for the middle.

sorry for my english 

http://snapnote.io/08GLwb

**Comment by dalefish** [comment]
That looks like a line height issue, try increasing line-height the at
least the height of the image on the TD containing the image

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by faldunate** [comment]
works the line-height in TD!, I'm very happy for that ahahaha

Thank you a lot for your help @iRyusa @dalefish
