### ISSUE TITLE
MJ-column issue when mobile rendering is used

### ISSUE THREAD

**Issue by Evensier** [mjmlio/mjml#752]
Hello there,

I've been trying to setup a template with some buttons with a text overlay, and I came up with the following code.

        <mj-column width="25%">
          <mj-image width="133px" src="http://static.evensi.com/business-square.png" />
          <mj-text align="center"><h3 class="footer-interest-text-box"><a href="https://twitter.com/RecastAI" style="margin-top: -70px;" class="footer-interest-text">Business</a></h3></mj-text>
        </mj-column>

The css class declared at the top are properly used, but the issue I've experiencing is related the layout once on the mobile view. The 25% width of the column is somewhat ignored and not coded in the final HTML. As a a result of this I have the screen rendering a list of boxes (I've 6 of them as per the above), piled up vertically in a non elegant way.

Anybody that can help me figuring out what's wrong?

Thanks

**Comment by iRyusa** [comment]
Hi @Evensier 

You should take a look at https://mjml.io/documentation/#mjml-group it keeps columns inside  mj-group as inline in mobile

I'm closing this issue, feel free to reopen if it doesn't work for you

**Comment by Evensier** [comment]
I've tried that already, even before posting this issue, but things are getting overlapped with the design above.

**Comment by dalefish** [comment]
mj-table could work for this, if I'm understanding the issue correctly

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment]
You might need to do 2 group of 50/50

mj-group
  mj-column x2 50%
mj-group
  mj-column x2 50%

image could be too wide to allow you 4 column as mobile

**Comment by Evensier** [comment]
Ok sort of getting what I need, although the mj-group doesn't expose any css-class property. Any idea on how to add some style there?

**Comment by iRyusa** [comment]
mj-group does support css-class like every other element in the body

**Comment by Evensier** [comment]
@iRyusa true, but for whatever reason the MJML compiler add some inline style that override the class behaviour. 
Any idea on how to avoid that?

I've created a fiddle here with part of the code I've written. Would love some advice to understand what I'm doing wrong

https://jsfiddle.net/syLdxd1e/

Thanks for the help.
