### ISSUE TITLE
Responsive media queries not applying to MJML components

### ISSUE THREAD

**Issue by zachkrasner** [mjmlio/mjml#753]
Huge fan of MJML, but I'm having trouble adjusting font size for mobile vs desktop. Ideally I'd like to be able to have bigger font size (28px) on mobile vs on desktop(22px) on an **mj-text component**

I'm using Mjmlslim and have tried using a combination of a media query and adding a **css-class** attribute to the mj-text component to no avail:

```
mjml
  mj-head
    mj-style
      |
        .body-text {
          font-size: 22px;
          line-height: 28px;
        }
        @media only screen and (max-width: 480px){
          .body-text {
            font-size: 28px !important;
            line-height: 44px !important;
          }
        }
```

And then in the body:
```
mj-section
  mj-column
    mj-text css-class="body-text"
      This is my body text that hopefully should be responsive
```

I think the final result gets buried in tables and the style isn't being inserted into the email for some reason... Any ideas on how to make responsive css queries with MJML work properly?

**Comment by iRyusa** [comment]
Hi, 
Keep in mind css-class is applied on the `td` not the final div so you have to set a div selector for you MQ

Here's a working example https://mjml.io/try-it-live/Hy5iF7gL-

**Comment by zachkrasner** [comment]
Thank you @iRyusa !

**Comment by zachkrasner** [comment]
@iRyusa I've tried implementing your solution, and while it indeed does work on the MJML browser based editor, I'm having difficulty with it performing in the real world. The email seems to ignore the "max-width: 480px" portion of the media query, always using those defined properties to set the font, even though I've followed your example. Any idea why this might be?

**Comment by Kant1-0** [comment]
@zachkrasner There are some devices / email clients that do not support media query.
