### ISSUE TITLE
Email center rendering blank on Outlook 2013

### ISSUE THREAD

**Issue by pascalicchio** [mjmlio/mjml#754]
Hi there,

Outlook 2013 - and only this version - render my code with blank space between header and footer. I'm using Email on Acid to test. I've reviewed the code already with no success.

https://mjml.io/try-it-live/BkvH_pfUW

Any idea why that's happening?

Thanks

**Comment by Renjaminino** [comment]
Hey there,

Your code doesn't really render any images, so it's difficult for me to tell.  However, Outlook 2013-2016 are messy beasts.  I found a good workaround for those by adding padding="0" on my sections where I do not want to render any gaps or spacing.  I haven't seen any render issues with this on Litmus:

`<mj-section padding="0"></mj-section>`

**Comment by dalefish** [comment]
There's an error on line 46:

<mj-section background-url="IMAGE_URL-align="middle"

should be:

<mj-section background-url="IMAGE_URL" align="middle"

There's also a problem width the closing quote on line 67 for the src
attribute:
<mj-image padding-bottom="20px" padding-top="20px" padding-left="20px"
padding-right="20px" src="IMAGE_URL=""

Not sure if those are the issues in question but without hosted images it's
hard to tell anymore.


Kind Regards,

:----------------------------:
Dale McConnell

**Comment by pascalicchio** [comment]
Thank you for replies.

Yes it has that character missing but it happen when I was changing URL's to show as an example.

My current situation remains the same: Outlook 2013 just ignore the center of the email. I already tested with and without wrapper, already checked if header and footer have same configs comparing to others (the answer is yes) but nothing.

Despite of padding, my code already have padding top and bottom 20px.

Any other idea?

Thanks!

**Comment by pascalicchio** [comment]
This is the workaround on how I manage to fix this:

When I added my last section Outlook 2013 reads it as one single block of information and reduces it, giving a weird result of section above section. What I did was to give padding="0" to the section and add an image spacer.gif in between those last sections.

Not the best or clean thing to do but it works :)

**Note to future updates**: apparently Outlook breaks if the content is too extensive so a way to fix that is to add a <center> right after <body> and closes it before </body>

**Comment by Kant1-0** [comment]
Hi @pascalicchio it seems you fixed the issue yourself. I can close the issue.

By the way you should take care with image with text content because it tends to be unreadable on mobile :)
