### ISSUE TITLE
render text-only?

### ISSUE THREAD

**Issue by brasilikum** [mjmlio/mjml#756]
Providing a text-only version of an Email can influence deliverability. Is there any way to render a text-only version of mjml templates?

**Comment by Kant1-0** [comment]
Hi @brasilikum it was discussed some time ago MJLM is not really made to handle text conversion as there are already existing packages that do the job.

https://github.com/mjmlio/mjml/issues/401#issuecomment-251625107

**Comment by iRyusa** [comment]
I'm closing this one because this is not a feature that we'll implement in MJML as @ngarnier & @Kant1-0 pointed in the #401
