### ISSUE TITLE
Creating two-color backgrounds

### ISSUE THREAD

**Issue by tbolt** [mjmlio/mjml#760]
Is it possible to have the background have a "split color" scheme without using a background-image?

I have attempted several ways but none seem to honor the correct width or the "negative margin" for the content.

Something like this-
![sample](https://user-images.githubusercontent.com/2279260/28724643-b8ed77f2-7388-11e7-8a69-703e65da0071.png)
![sample2](https://user-images.githubusercontent.com/2279260/28724640-b639e810-7388-11e7-8766-3713e2797001.png)

**Comment by Kant1-0** [comment]
It's not really possible, except using a background color + a transparant png img as background

**Comment by tbolt** [comment]
Thanks. I ended up using a background image in CSS. That should work fine.

**Comment by Kant1-0** [comment]
No problem @tbolt ;)
I can close this issue
