### ISSUE TITLE
mj-hero does not show up in outlook 2000 and 2003

### ISSUE THREAD

**Issue by forethoughtde** [mjmlio/mjml#761]
mj-hero does not show up in outlook 2000 and 2003 email client. I know, some of the Outlook email client do not support background-image; Wondering why background-color is not showing?

 ```html
 <mj-hero mode="fluid-height" 
      background-width="600px"  
      background-url="https://cloud.githubusercontent.com/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg" 
      background-color="#2a3448" 
      padding="100px 0px">
      </mj-hero>
```

**Comment by Kant1-0** [comment]
I can't reproduce the bug, can you provide a live snippet ? Outlook 2000 and 2003 render the background image as well.

Although if the image link is wrong, some email clients won't fallback to the background-color and will just render a transparent div.

**Comment by dalefish** [comment]
There is a bug where the background color is not applied in the VML when
background-url is used.

Not sure if it's the same problem here but if it is you can fix it by
manually adding the color="" param to the VML.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by Kant1-0** [comment]
In fact, manually adding background-color after the background attribute seems to fix the issue where image doesn't appear (because link is wrong or image not accessible)

```
<td style="background-repeat:no-repeat;vertical-align:top;background-size:cover;background: url(https://cloud.githubusercontetcom/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg) no-repeat center center / cover;background-color:#2a3448;padding-top:100px;padding-left:0;padding-right:0;padding-bottom:100px;background-position:center center;"
background="https://cloud.githubusercontetcom/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg">
```
^ here using a wrong link

It doesn't work with IBM Notes 9 and Lotus Notes 8.5, but does with Outlook and others

**Comment by forethoughtde** [comment]
Can I know what is VML?

**Comment by iRyusa** [comment]
VML is an "SVG" like markup language for Outlook desktop used mostly for background images in email world because background images aren't supported in plain HTML/CSS in those.

You're missing the `background-height` attributes needed for Outlook. + You might need to add some blank mj-hero-content + empty mj-text. Ex : https://mjml.io/try-it-live/B1s1AaHwZ

Then it shows up fine on litmus !
