### ISSUE TITLE
overriding @media queries

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#763]
Hi Guys  

i wanted to know if there was a way to override a media query .

Currently i am using gulp to process and replace the html content in my freemarker templates and we have a scenario where we have placed border lines in specific places , however  when the screen size changes the layout too we then see the missing border lines.

We thought we could add a media query in a mj-style tag to override the current media queries but seems it does not and what happens is my old styling and the new media query styling show together when the screen size is changed with the layout.

     <mj-style>
       @media only screen and (max-width:480px) {
	.dotw_deal {
	border:0px solid #f00!important;
	border-width: 0 0 1px 0!important;
}
     </mj-style>
![screen shot 2017-08-04 at 3 19 15 pm](https://user-images.githubusercontent.com/25219824/28970333-6b8b6bae-7928-11e7-9f9d-d6197d310677.png)
![screen shot 2017-08-04 at 3 16 40 pm](https://user-images.githubusercontent.com/25219824/28970332-6b8b9ad4-7928-11e7-9762-da1915ac3ff1.png)

thats the code used in hope to override the @media only screen and (max-width:480px)  query.

**Comment by Kant1-0** [comment]
Hi @lrae24 can you send a live snippet so I can see what is going on ?

**Comment by lrae24** [comment]
Kant1-0   please see the updated issue  you can see the mjml code however when we look and at the second screen you see that the output has 2 media queries for the "max-width:480px" and yet i want to override same generated  media query. I hope you can see the 2 media queries the 1 at the top and the other right at the bottom.

**Comment by iRyusa** [comment]
Hi @lrae24 

You can have multiple media queries in multiple style tag, this is not an issue.

**Comment by lrae24** [comment]
I understand that but my issue is how do i override the original media query because i want to overwrite the original styling and replace it not keep both media queries and their styling or added attributes.  You will notice in my style tag example i have a border and the aim is to separate 3 columns vertically  however when the media query is activated for a smaller screen i would like to have the borders changed to be horizontal now as  if they were kept vertical it would look like 1 straight line on 1 side of the display which is what i want to avoid .
![3](https://user-images.githubusercontent.com/25219824/29022129-580f7e34-7b68-11e7-9ede-1415e3d64218.png)
![2](https://user-images.githubusercontent.com/25219824/29022130-5845fab8-7b68-11e7-9e62-2b9717844e17.png)
![1](https://user-images.githubusercontent.com/25219824/29022131-58487b12-7b68-11e7-9acd-e1bbb3901e0b.png)

Image 1 is the desired result for desktop screens and image 2 shows what happens if i keep that design . Image 2 is not ideal for the the smaller mobile screens and this is where my overriding comes in i would like to achieve the result as shown by image 3  on mobile devices only see this is why overriding my media query was an option to look at  so i don't want a duplicate i just want 1 to overwrite the other.

I am not sure if there are other ways to achieve this in mjml , if there are please could you advise me on how it can be done.

**Comment by iRyusa** [comment]
Here you are:  https://mjml.io/try-it-live/rJLX62Sw-

Note that the first media queries that you shown isn't related to any border thing, it's just a small fix for some clients.

**Comment by lrae24** [comment]
Thanks @iRyusa  although seems i have another issue with this so in my column i have a separate mj-table and whats happening is the border is duplicating on the column and the table the column is in the mail so i'm not sure how i would solve that issue now see and the reason for me using a separate mj-table is to have 2 different text on the same line but with different styling on the text itself  see

**Comment by iRyusa** [comment]
You can change the css selector to `.border-override > table` like that : https://mjml.io/try-it-live/HyazOarwb
