### ISSUE TITLE
Layouts Breaking When Forwarded - Outlook for Mac 2017

### ISSUE THREAD

**Issue by sms20** [mjmlio/mjml#764]
We have used the template card (https://mjml.io/try-it-live/templates/card) for a newsletter campaign.

When people forward the newsletter some of the elements break out of the container and appear on the screen at 100% width.

It seems to be an issue with Outlook for Mac (our companies preferred mail client). I've testing in Thunderbird and it seems to forward with out issue.

I believe Outlook for Mac uses WebKit to render email, so it should look OK.

Is this a common / known problem?

**Comment by dalefish** [comment]
Outlook 2017? Not 2016?

Can you share a screenshot of the problem?

**Comment by sms20** [comment]
Version number is showing 15.35:

![image](https://user-images.githubusercontent.com/22502497/28866014-9974e8b2-7769-11e7-9040-99bfd212e7b9.png)

Some screenshots showing the issue:

![screen shot 2017-08-02 at 9 59 14 am](https://user-images.githubusercontent.com/22502497/28865880-44fa5b82-7769-11e7-8cfe-993d208f58e5.png)
![image](https://user-images.githubusercontent.com/22502497/28865888-4f94b5a6-7769-11e7-9218-5ae4409c113a.png)

Thanks.

**Comment by dalefish** [comment]
Hmm, hard to tell what is going on there, it looks very broken.

Can you share the code?  https://mjml.io/try-it-live is the best place to share if you can

**Comment by sms20** [comment]
The sample above uses the code from the card template file:
https://mjml.io/try-it-live/templates/card

Thanks.

**Comment by dalefish** [comment]
Ah, sorry, didn't notice the 'When Forwarded' part of the issue. 

Forwarding a mail will generally break it as styles are stripped and various changes are made to the code by individual emails clients. 

You can get away with simple mails but complex responsive mails are a different matter.

Nothing that can be done about that unfortunately.

**Comment by iRyusa** [comment]
Hi @sms20 

This is a known issue, but there's nothing we can do. When forwarding emails, some pieces of HTML are removed by the clients.

I'm closing this one because we can't do anything about it and it's really client specific
