### ISSUE TITLE
Converting Unicode Characters

### ISSUE THREAD

**Issue by katart** [mjmlio/mjml#765]
The string `<mj-text>Item One &bull; Item Two</mj-text>` is converted to `Item One • Item Two`, but, for some reason, the bullet is missing when the email is deployed. I have to update the rendered HTML file by adding back the `&bull;` character code to get it to display properly.

Would it be better to keep the `&bull;` character code in the rendered HTML or is there a better way to handle this?

**Comment by dalefish** [comment]
You can get around the problem by using &amp;bull (with a closing semicolon
; ).

The initial ampersand gets encoded completing your html.

I think it is being fixed for version 4.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by katart** [comment]
Thanks Dale
