### ISSUE TITLE
Minified output incorrect when font name single-quoted

### ISSUE THREAD

**Issue by ZedNaught** [mjmlio/mjml#766]
Using versions 3.3.2 and 3.3.3. Example input and outputs with minify on/off attached. Relevant sections:

Input:
```<mj-text font-size="20px" color="#F45E43" font-family="'Book Antiqua'">Hello World</mj-text>```

Relevant tag without minification:
```<div class="" style="cursor:auto;color:#F45E43;font-family:'Book Antiqua';font-size:20px;line-height:22px;text-align:left;">Hello World</div>```

Relevant tag with minification:
```<div style="cursor:auto;color:#f45e43;font-family:'line-height:22px;text-align:left">Hello World</div>```

[input.mjml.txt](https://github.com/mjmlio/mjml/files/1195621/input.mjml.txt)
[output_unminified.html.txt](https://github.com/mjmlio/mjml/files/1195620/output_unminified.html.txt)
[output_minified.html.txt](https://github.com/mjmlio/mjml/files/1195619/output_minified.html.txt)

**Comment by forethoughtde** [comment]
Can I know which minification engine do you use?

**Comment by ZedNaught** [comment]
Ah it didn't occur to me to include that. I'm not terribly experienced working with node packages so I may be misunderstanding something, but it looks like we're using the default engine html-minifier (version 3.5.2). 

Strangely, when I manually run html-minifier on the unminified output with the same options used [here](https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/MJMLRenderer.js#L45), the output is similar to the erroneous output but it is correct: [minified_correct.html.txt](https://github.com/mjmlio/mjml/files/1198122/minified_correct.html.txt)

**Comment by iRyusa** [comment]
> Strangely, when I manually run html-minifier on the unminified output with the same options used here, the output is similar to the erroneous output but it is correct: minified_correct.html.txt

I don't really understand this part, you said it's similar, but then the file looks OK ?

Is this an html-minifier bug or mjml related one ?

**Comment by ZedNaught** [comment]
@iRyusa sorry for being unclear. What I mean is that the outputs of the following two procedures:

1. running mjml on an input with minification turned on
2. running mjml on the same input with minification turned off, then manually running that output through html-minifier with the same options that mjml seems to use

are identical except for the style attribute on the "Hello World" div. The output of the first erroneously drops the remainder of the value after the first single-quote as well as the next key-value pair in the style, as seen in the third snippet in my original post:
```html
<div style="cursor:auto;color:#f45e43;font-family:'line-height:22px;text-align:left">Hello World</div>
```

The correct version from procedure 2 for comparison:
```html
<div style="cursor:auto;color:#f45e43;font-family:'Book Antiqua';font-size:20px;line-height:22px;text-align:left">Hello World</div>
```

This leads me to believe it's an issue with mjml itself, perhaps related to character escaping or nested quotes.

**Comment by iRyusa** [comment]
Can you try this again on the 4.0 beta ?

I think it might has been solved with related encoding issue

**Comment by iRyusa** [comment]
I think it should be OK now in 4.0.0-beta.2, feel free to reopen if not !
