### ISSUE TITLE
mj-section width

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#767]
Guys can someone help  me how do i force a specific width in px on a mj-section  to be smaller than my container . I have 3 columns in the section to have it split in 3. I have a container with the width of 640px and want the section to fit in and only have a width of 592px.

 
![screen shot 2017-08-03 at 12 17 50 pm](https://user-images.githubusercontent.com/25219824/28917583-6cc942f8-7846-11e7-8653-58c9ada15787.png)

**Comment by iRyusa** [comment]
Hi @irae24

You can use either `mj-wrapper` with a `padding` or `padding` on a `mj-section` both does the same, the first allows you to keep the padding for multiple sections inside a `mj-wrapper`

Note that mj-image can misbehave on outlook with left/right padding on `section/wrapper`

**Comment by AradhanaChhabra** [comment]
@lrae24 I faced the similar issue. To fix this we can also use `<mj-style>` tag inside `<mj-head>` to create a css class and set the width of section using `css-class` attribute inside `<mj-section>` .  

For Example:

```
<mjml>
  <mj-head>
    <mj-style inline="inline">
          .section-class{
            width: 300px;
           }
    </mj-style>
  </mj-head>
  <mj-body>
       <mj-section css-class="section-class" background-color="red">
             <mj-column background-color="red" width="100%">
                <mj-spacer height="100px"></mj-spacer>
              </mj-column>
       </mj-section>
  </mj-body>
</mjml>
```

**Comment by alfonsrv** [comment]
@AradhanaChhabra's suggestion doesn't work, since it disables all default responsiveness fyi – in case anyone wants to try that.
