### ISSUE TITLE
Modify Social Icons 

### ISSUE THREAD

**Issue by ArtFaks** [mjmlio/mjml#768]
Hi everybody,

It's possible to change social icons like this ?

![social-footer-icons](https://user-images.githubusercontent.com/399591/28919056-15b1c8cc-784c-11e7-8724-c53415260dfe.jpg)

**Comment by Kant1-0** [comment]
Hi @ArtFaks you can change the icons using the `base-url`, providing an online folder - url - for your custom icons. The icons within the folder should be named facebook.png , twitter.png or google.png.

But you can also create custom icon using a custom name like `myfacebook` with a provided `myfacebook-icon` url. Here is a live snipper :

https://mjml.io/try-it-live/Byd0hirPb
