### ISSUE TITLE
Cannot set divider's width

### ISSUE THREAD

**Issue by quangbuule** [mjmlio/mjml#77]
I see the width property but it is not used yet: 
https://github.com/mjmlio/mjml/blob/master/src/components/Divider.js#L17

**Comment by iRyusa** [comment]
Hi @quangbuule ,
I need to test how width is applied on outlook & gmail, but I'm working to bring `width` back on `divider` thanks to report it!

**Comment by iRyusa** [comment]
Now fixed in `1.3` :+1:
