### ISSUE TITLE
Allow styling specific element within a mj-class

### ISSUE THREAD

**Issue by iRyusa** [mjmlio/mjml#773]
It allows you to define sandboxed styles for some elements within a mj-class, ex:

```xml
<mj-head>
    <mj-attrbutes>
        <mj-class name="top-section" background-color="grey">
            <mj-text color="white" font-size="20px"/>
            <mj-column background-color="light-grey"/>
        </mj-class>
    </mj-attributes>
</mj-head>
<mj-body>
    <mj-section mj-class="top-section">
        <mj-column width="50%">
            <mj-text> 
              this text will be white and 20px, column will have a light-grey background
            </mj-text>
        </mj-column>
    </mj-section>
</mj-body>
```

We might need to attach parent-class in mj-attributes to enable it https://github.com/mjmlio/mjml/blob/next-create-component/packages/mjml-core/src/index.js#L120

**Comment by iRyusa** [comment]
We'll ship this in the next alpha for anyone interested in 👍

**Comment by ngarnier** [comment]
The first beta release for MJML 4 is here so I'm closing! You can install it with `npm install mjml@next` to use this feature.
