### ISSUE TITLE
mj-include issue i have 

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#774]
![screen shot 2017-08-11 at 11 48 56 am](https://user-images.githubusercontent.com/25219824/29208629-229f4e5c-7e8b-11e7-8f9d-418a8d8297ba.png)
![screen shot 2017-08-11 at 11 48 43 am](https://user-images.githubusercontent.com/25219824/29208630-22a07642-7e8b-11e7-9648-6ddc51a94dd3.png)

Hi guys ,

I wanted to know if there is a way around this currently i have a mj-include in my mj-head and in my included file i have no root tags or opening and closing head or mjml tags. This worked as my solution however we noticed now that if for example we were to rebuild all our ftl's  using gulp  the build will fail due to the included file not having any root tags is there a way around this to prevent the error in the build process  or does the include file have to have a mjml and mj-container tags? 

Is the include file incorrect if it has no mjml tag or root body or head tags?

**Comment by Kant1-0** [comment]
Hi @lrae24 it's a bug with gulp-mjml and relative path, a fix will be soon released https://github.com/mjmlio/gulp-mjml/issues/27
Your included file is correct as we handle different methode to include file. To temporally fix the issue, you can try with an absolute path.
