### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by ncamacho97** [mjmlio/mjml#777]
is it possible to css gradient on this email temp yeah i know css gradient is bad but im using

**Comment by ngarnier** [comment]
Hey @ncamacho97, technically you can... but be careful with the support from email clients.

MJML template: https://mjml.io/try-it-live/r1NzbBy_b
Litmus test: https://litmus.com/checklist/emails/public/c7402a7

I think your question is answered so I'm closing!
