### ISSUE TITLE
Recovering Trashed Projects

### ISSUE THREAD

**Issue by mjcampagna** [mjmlio/mjml#780]
So, I accidentally killed a project in progress by selecting "Also remove folder and files from disk" while deleting a new project that I had accidentally created in its parent folder. My project files are not in the system trash. Is there any way I can recover the project? Please?

**Comment by ngarnier** [comment]
Hey @mjcampagna, I guess you're using the MJML App, just so you know there's a dedicated repo that you might want to use for future questions/issues related to the app: https://github.com/mjmlio/mjml-app.

About your issue, sorry to hear that! I doubt there's anything we can do but I'll let @meriadec (MJML App's creator and maintainer) confirm or not this statement.

**Comment by meriadec** [comment]
Hello @mjcampagna, I'm sad to confirm that, but when this checkbox is checked, the app remove permanently the files from disk ([see here](https://github.com/mjmlio/mjml-app/blob/f066ac999c9a6a7d9b9e9fcd29522d7c883be3cd/app/actions/projects.js#L54)).

Considering the problem, I think the option may need to be changed to "Move to trash" as it's too dangerous.

**Comment by mjcampagna** [comment]
That's a drag, but thanks for the reply. I agree, it would be much better if the option moved items to the trash, rather than destroying them outright. I'll hope to see it in an app update sometime soon.
