### ISSUE TITLE
Problem with reendering in outlook

### ISSUE THREAD

**Issue by jeffersonegenial** [mjmlio/mjml#786]
I am having problem rendering layout in Outlook.
Below is my code:
<mjml>
  <mj-body>
    <mj-container background-color="#e6e6e6">
      <mj-navbar background-color="#009045">
        <mj-column width="30%">
          <mj-image width="150px" src="https://guiadestri.com.br/site/images/logo80x.png"></mj-image>
        </mj-column>
        <mj-column width="70%">
          <mj-inline-links base-url="" align="right">
            <mj-link href="https://www.facebook.com/guiadestrisorriso" color="#ffffff">
              <img src="../images/mail/icon-fb.png" />
            </mj-link>
            <mj-link href="https://www.instagram.com/guiadestri/" color="#ffffff">
              <img src="../images/mail/icon-insta.png" />
            </mj-link>
          </mj-inline-links>
        </mj-column>
      </mj-navbar>
      
      <mj-section padding="0">
        <mj-column width="100%">
          <mj-image href="https://guiadestri.com.br" src="../images/mail/topo.jpg" alt="Guia Destri" padding="0px"> </mj-image>
        </mj-column>
      </mj-section>
      
      <mj-section padding="15px" background-color='#f2f2f2'>
        <mj-column width="100%">
          <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
            <h3 style="margin: 0;">Olá Dioner, Obrigado pro se cadastrar.</h3>
          </mj-text>
          <mj-text font-family="Tahoma" font-size="14">
            <p style="margin:0;">Você acabou de realizar um cadastro gratuíto, em breve uma operadora entrará em contato para confirmar mais algumas informações, mas não se preocupe, o Guia Destri jamais solicitará documentos pessoais por telefone.</p>
          </mj-text>
          
          <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
            <h3 style="margin: 0;">Que tal dar mais um passo? Anuncie no nosso site!</h3>
          </mj-text>
          <mj-image width="300" src="../images/mail/devices.png" />
        </mj-column>
      </mj-section>
      
      <mj-section padding="15px" background-color='#fff'>
        <mj-column width="100%">
          <mj-text font-family="Tahoma" font-size="14">
            <p style="margin:0;">O Guia Destri tem várias opções de anúncio, com toda certeza uma dela se encaixa perfeitamente ao seu negócio, não prerca essa oportunidade de levar a sua marca mais cliente. Abra novas oportunidades para o seu negócio na Internet!</p>
              <a href="https://guiadestri.com.br/planos" style="color: #0f367c; text-decoration: none;">https://guiadestri.com.br/planos</a>
          </mj-text>
        </mj-column>
      </mj-section>
      
      <mj-section background-color="white" padding="0">
        <mj-column width="100%">
          <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
            <h3 style="margin: 0;">E que tal seu produto, também na internet?</h3>
          </mj-text>
        </mj-column>
        
        <mj-column width="50%">
          <mj-text font-family="Tahoma" font-size="14" align="right">
            <p style="margin:0;">Agora você pode oferecer aos seus clientes seus produtos de forma simples e organizada, no Guia Destri Classificados. A nova ferramenta do Guia Destri que leva seus produtos e serviços ao consumidor final</p>
            <p style="margin:0;"><a href="https://classificados.guiadestri.com.br" style="color: #0f367c; text-decoration: none;">https://classificados.guiadestri.com.br</a></p>
          </mj-text>
        </mj-column>
        
        
        <mj-column width="50%">
          <mj-image width="200px" src="../images/mail/classificados.png" />
        </mj-column>
      </mj-section>
      
      
      <mj-section background-color="white" padding="0">
        <mj-column width="100%">
          <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
            <h3 style="margin: 0;">E vamos muito além disso, conheça outros serviços:</h3>
          </mj-text>
        </mj-column>
        
        
        <mj-column width="30%">
          <mj-image width="100px" src="../images/mail/ads.jpg" />
        </mj-column>
        <mj-column width="70%">
          <mj-text font-family="Tahoma" font-size="14" align="left">
            <p style="margin:0;"><b>Google Adwords:</b> A porta de entrada para anúncios pagos no google, a equipe Guia Destri pode te auxiliar a dar os primeiros passos para anunciar no gigante de buscas</p>
          </mj-text>
        </mj-column>
        
        
        
        <mj-column width="70%">
          <mj-text font-family="Tahoma" font-size="14" align="right">
            <p style="margin:0;"><b>Desenvolvimento de sites:</b> Você sabia que o Guia Destri Constrói sites completos? Utilizamos as mais recentes tecnologias para desenvolver sites com alto padrão visual e técnico. Completamente otimizado para dispositivos móveis.</p>
          </mj-text>
        </mj-column>
        
        <mj-column width="30%">
          <mj-image width="100px" src="../images/mail/dev.jpg" />
        </mj-column>
        
        
        <mj-column width="30%">
          <mj-image width="100px" src="../images/mail/fb-ads.jpg" />
        </mj-column>
        <mj-column width="70%">
          <mj-text font-family="Tahoma" font-size="14" align="left">
            <p style="margin:0;"><b>Facebook Ads:</b> Criamos sua página corporativa do Facebook e montamos anúncios segmentados. O Facebook é uma excelente mídia para atingir novos clientes.</p>
          </mj-text>
        </mj-column>
      </mj-section>
      
      <mj-section background-color="#f2f2f2" padding="15px">
        <mj-column width="100%">
          <mj-text font-family="Tahoma" font-size="14" align="center">
            <p style="margin:0;">Nosso setor de desenvolvimento traz soluções personalizadas com capacidade focada em desenvolvimento e tecnologia. Nossa infraestrutura é própria, portanto sabemos o que estamos fazendo e conseguimos coordenar todos os pontos de necessidade dos clientes, oferecendo um produto personalizado, barateando custos e elevando a satisfação e segurança de todos os envolvidos. Atuamos regionalmente, oferecendo as melhores soluções para nossos parceiros, desenvolvendo qualquer tipo de projeto, sistema ou software e nos destacamos por oferecer soluções flexíveis. Nossa equipe de desenvolvedores, treinados nas melhores escolas do setor, tem as melhores opções para seu negócio, destacando a agilidade nos sistemas e softwares. Um projeto bem desenvolvido acelera a logística interna do seu negócio. Precisa de solucionar um problema? Precisa aperfeiçoar seu negócio? Nós temos a solução. Entre em contato com nossa equipe de desenvolvedores e conheça mais essa opção que o Grupo Destri oferece para alavancar seu negócio.</p>
          </mj-text>
        </mj-column>
      </mj-section>
      <mj-section background-color="white" padding="15px">
        <mj-column width="100%">
          <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
            <h3 style="margin: 0;">Acredite em nós, sabe por quê?</h3>
          </mj-text>
          <mj-text font-family="Tahoma" font-size="14" align="left">
            <p style="margin:0;">O Guia Destri é de fato pioneiro em lista telefônica impressa no norte do Mato Grosso, onde atua desde 1988. Proporciona ao anunciante sempre a melhor opção com bons resultados. Ao usuário praticidade e disponibilidade da lista em sua residência ou empresa, além de exemplares para a área rural e distritos próximos, sendo uma ótima e ampla opção de propaganda anual.</p>
            <p style="margin:0;">A lista telefônica ganha cada vez mais espaço, oferecendo inúmeras vantagens e garantindo a confiança dos mais de 30.000 (trinta mil) usuários em nossa região!</p>
            <p style="margin:0;"> Para acompanhar a evolução das maneiras de comunicar  Guia Destri tem imergido nos meios digitais, primeiro com a lista telefônica online e agora com seu classificado, para que você, empresário alcance seu cliente em qualquer lugar.</p>
          </mj-text>
        </mj-column>
      </mj-section>
      
      <mj-section background-color="white" padding="15px">
        <mj-column width="100%">
          <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
            <h3 style="margin: 0;">Estamos sempre à sua disposição</h3>
          </mj-text>
          <mj-text font-family="Tahoma" font-size="14" align="left">
            <p style="margin:0;">Você pode falar conosco através de nosso email <a href="mailto:atendimento@guiadestri.com.br" style="color: #0f367c; text-decoration: none;">atendimento@guiadestri.com.br</a>, ou ainda pelos fones: 66 3545-9900, 66 99635-9900, 65 99675-9900, um de nossos colaboradores terá um imenso prazer em lhe atender.</p>
          </mj-text>
        </mj-column>
      </mj-section>
      
      
      <mj-section background-color="white" padding="0">
       <mj-column width="50%" background-color="#26388D">
          <mj-image width="218px" href="https://www.facebook.com/guiadestrisorriso" src="../images/mail/bottom-fb.png" />
        </mj-column>
        <mj-column width="50%" background-color="#A9399F">
          <mj-image width="150px" href="https://www.instagram.com/guiadestri/" src="../images/mail/bottom-insta.png" />
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>

**Comment by iRyusa** [comment]
Hi can you be more specific with your issue please ?

**Comment by jeffersonegenial** [comment]
This is the correct
![mjml_certo](https://user-images.githubusercontent.com/3483724/29538913-43604c7c-8674-11e7-8ca1-bb901247a42c.jpg)

**This is the wrong one displayed in Outlook:**
![mjml_erro](https://user-images.githubusercontent.com/3483724/29538932-5fffb4da-8674-11e7-9506-0cf3405b58bb.jpg)

**Comment by iRyusa** [comment]
This is because you have more than 100% of content in a section here : 

```xml
  <mj-section background-color="white" padding="0">
    <mj-column width="100%">
      <mj-text font-size="16px" align="center" font-weight="bold" font-family="Tahoma" color="#626262">
        <h3 style="margin: 0;">E vamos muito além disso, conheça outros serviços:</h3>
      </mj-text>
    </mj-column>
    
    <!-- ROW 1 -->
    <mj-column width="30%">
      <mj-image width="100px" src="../images/mail/ads.jpg" />
    </mj-column>
    <mj-column width="70%">
      <mj-text font-family="Tahoma" font-size="14" align="left">
        <p style="margin:0;"><b>Google Adwords:</b> A porta de entrada para anúncios pagos no google, a equipe Guia Destri pode te auxiliar a dar os primeiros passos para anunciar no gigante de buscas</p>
      </mj-text>
    </mj-column>
    
    <!-- ROW 2 -->
    
    <mj-column width="70%">
      <mj-text font-family="Tahoma" font-size="14" align="right">
        <p style="margin:0;"><b>Desenvolvimento de sites:</b> Você sabia que o Guia Destri Constrói sites completos? Utilizamos as mais recentes tecnologias para desenvolver sites com alto padrão visual e técnico. Completamente otimizado para dispositivos móveis.</p>
      </mj-text>
    </mj-column>
    
    <mj-column width="30%">
      <mj-image width="100px" src="../images/mail/dev.jpg" />
    </mj-column>
    
    <!-- ROW 3 -->
    <mj-column width="30%">
      <mj-image width="100px" src="../images/mail/fb-ads.jpg" />
    </mj-column>
    <mj-column width="70%">
      <mj-text font-family="Tahoma" font-size="14" align="left">
        <p style="margin:0;"><b>Facebook Ads:</b> Criamos sua página corporativa do Facebook e montamos anúncios segmentados. O Facebook é uma excelente mídia para atingir novos clientes.</p>
      </mj-text>
    </mj-column>
  </mj-section>
```
