### ISSUE TITLE
mj-column - must specify a width

### ISSUE THREAD

**Issue by KoalaMontana** [mjmlio/mjml#788]
Hi. I ran into a problem. If you have several columns, then in GMail and Yandex Mail, these columns collapse each other, even in full-screen mode on the desktop.
The solution is to specify the max-width for div elements with classes "mj-column-per-**".

**Comment by ngarnier** [comment]
Hi,

There must be something wrong either in your code sample or the way you tested it. Can you please provide more information, especially the MJML code you used to see this result and how you tested it (if you sent the email, which platform you used).

You can see on [that example created in Litmus](https://litmus.com/checklist/emails/public/3735f3c) that the columns don't collapse in Gmail (Original MJML code: https://mjml.io/try-it-live/SkaJaFtdW)

![](https://puu.sh/xgudi/304af40f46.png)

**Comment by KoalaMontana** [comment]
Example of my template
[template.txt](https://github.com/mjmlio/mjml/files/1241888/template.txt)
And how it's displayed in GMail:
![image](https://user-images.githubusercontent.com/13771483/29564057-e002751c-8748-11e7-8c43-f6206ec0ac21.png)

I have 750px-container, section with paddings and two columns.

**Comment by ngarnier** [comment]
@KoalaMontana how did you send it to your personal Gmail address? Can you please try with https://putsmail.com/?

**Comment by KoalaMontana** [comment]
@ngarnier I and the customer use Mailchimp. I've tried with Putsmail and did not find the problem. Can it be some kind of Mailchimp's bug?

**Comment by ngarnier** [comment]
Yes that's it then, Mailchimp alters the HTML and breaks the style, see this issue for a workaround: #717 (comment)

I'm closing as it's not MJML-related but due to Mailchimp.
