### ISSUE TITLE
Full-width images

### ISSUE THREAD

**Issue by KoalaMontana** [mjmlio/mjml#789]
Hi. I have a problem.
In my mailings there are blocks with images that should be the full width of the template, but there are left/right paddings in Outlook.
What am I doing wrong?
Code:
mj-attributes section
`<mj-class name="content-blocks" padding="10px 20px" />
<mj-class name="no-padding" padding="0" />`

mj-body section
`<mj-section mj-class="content-blocks" background-color="#F0ECE9"></mj-section>
<mj-section>
          <mj-column>
            <mj-image src="line-empty-top.png" mj-class="no-padding" />
          </mj-column>
</mj-section>`

Screenshot:
![image](https://user-images.githubusercontent.com/13771483/29562389-bb65a0fa-8741-11e7-8b7e-4112bf4f23d8.png)

**Comment by iRyusa** [comment]
Hi @KoalaMontana 

You have a padding on your section cf :  `name="content-blocks" padding="10px 20px"`

Remove it to make the image go full-width

**Comment by KoalaMontana** [comment]
@iRyusa paddings were defined for the previous section with class "content-blocks". Section with image don't have any classes or paddings and display incorrect only in Outlook.

**Comment by iRyusa** [comment]
My bad, without indentation it was unclear for me

Can you upload the full snippet on https://mjml.io/try-it-live please ?

**Comment by KoalaMontana** [comment]
@iRyusa thanks for help. 
https://mjml.io/try-it-live/rJFxo5KdW

**Comment by iRyusa** [comment]
I'm unable to reproduce with this snippet as you can see here every outlook are fine https://litmus.com/checklist/emails/public/c3c9c60

**Comment by KoalaMontana** [comment]
Could you try to test this version https://mjml.io/try-it-live/Bkd3FsF_- ?

**Comment by iRyusa** [comment]
Looks to work when removing `mj-wrapper`, I think you can remove it safely because it has no purpose on your design ?

**Comment by iRyusa** [comment]
Hi @KoalaMontana 

Is this good for you now ? 👍

**Comment by KoalaMontana** [comment]
@iRyusa yes, it works. Thank you.
