### ISSUE TITLE
css-class in custom components does not render when inside of a <div> as the component root element

### ISSUE THREAD

**Issue by etiennemarais** [mjmlio/mjml#790]
`css-class` in custom components does not render when inside of a `<div>` as the component root element.

  **Reproduction Steps:**

  1. Create a custom component and add a `<div>` as a root element
  2. Add a couple of mjml `<Table>` parts inside of the div with their own `css-class` attributes
  3. Does not render the css-class for some reason.

  **Expected behavior:**

 I expect that no matter where you specify a mjml component like `<Table>` that it would render the css class, but it's not. For some reason it's ignoring that attribute when in a custom component and a normal div as the element root.

  **Screenshots and GIFs**

![screen shot 2017-08-24 at 10 54 43 am](https://user-images.githubusercontent.com/4479918/29658320-b1be7854-88ba-11e7-8198-60b5d0923d88.png)
![screen shot 2017-08-24 at 10 55 46 am](https://user-images.githubusercontent.com/4479918/29658354-d0247ce4-88ba-11e7-8bd6-621f9fa35971.png)

  **MJML version:**

![screen shot 2017-08-24 at 10 59 03 am](https://user-images.githubusercontent.com/4479918/29658480-463c7814-88bb-11e7-9820-c686c15cdf7e.png)

  **Email clients the bug is seen on:**

N/A This is when I try and run my Nightwatch tests over the html output.
<img width="811" alt="screen shot 2017-08-24 at 11 03 30 am" src="https://user-images.githubusercontent.com/4479918/29658634-ed9cfea8-88bb-11e7-9979-615aaec5ed79.png">

**Comment by iRyusa** [comment]
Hi @etiennemarais 
Well the answer lies into the decorator. Table, Text, Image, every mj-component that live in a Column has a special treatment for css-class as you can see here https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/decorators/MJMLElement.js#L263-L276

Here you should use a regular table, as Mj-Table isn't going to do anything for you

**Comment by etiennemarais** [comment]
Great, Thanks for clearing that up :)
