### ISSUE TITLE
Css transform property is not working

### ISSUE THREAD

**Issue by sinhasagar01** [mjmlio/mjml#791]
`transform="skew(0deg, -7.5deg)" `

Where  can i get the complete list supporting css property in mjml?

**Comment by ngarnier** [comment]
Hey @sinhasagar01, you can see in the documentation the list of MJML attributes for a given MJML element: https://mjml.io/documentation/#standard-body-components

Note that you can use your own custom css (and even inline it automatically) with `mj-style`: https://mjml.io/documentation/#mjml-style
