### ISSUE TITLE
Direct String Input

### ISSUE THREAD

**Issue by davidnestoruk** [mjmlio/mjml#795]
Hi,

Having some issues using MJML via the command line to provide dynamic email templates. Currently using Laravel 5.4, and I read through a previous thread [https://github.com/mjmlio/mjml/issues/595](url) and tried following the Blade -> MJML -> HTML flow, but having trouble.

Tried a variation of code such as: 

`
$html = view('emails.orders.offer', $data)->render();

$mjml = exec("../node_modules/.bin/mjml -s -i '$html'");
`

But I keep getting null in return. Also, if I try to use the command directly in the command line, it just seems to hang, even with simple strings such as `./node_modules/.bin/mjml-cli -s -i "<mjml></mjml>"`

Any suggestions would be helpful! 

Thank you! :)

**Comment by iRyusa** [comment]
Hi

@davidnestoruk `-i` option need an input from `stdin` there's option to directly render a string for the cli.
If you're using it you can prompt any MJML and terminate it with a `ctrl  + D` (see  https://en.wikipedia.org/wiki/End-of-Transmission_character) and then it will output the result .

**Comment by davidnestoruk** [comment]
Hi @iRyusa

Sorry, I may be misunderstanding but still having trouble adding an EOT character. Trying this:

`$html = exec("../node_modules/.bin/mjml -s -i '$mjml \0x04'");` 

But it complains with `exec(): NULL byte detected. Possible attack`

**Comment by iRyusa** [comment]
As I said, you can't send directly a string to the cli, you need to use an stdinput.

I think you can use something like this in PHP http://php.net/manual/fr/function.proc-open.php

**Comment by davidnestoruk** [comment]
Oh, ok - awesome.

I'll look into that! Cheers :)

**Comment by iRyusa** [comment]
👍

**Comment by asahasrabuddhe** [comment]
Hello @davidnestoruk @iRyusa 

This is probably a tad too late but I think I have something that can solve your problem and anyone else who might face this same issue in the future.

https://github.com/asahasrabuddhe/laravel-mjml

Please take a look at this package. This package will seamlessly build MJML views from your blade templates and send them as emails.
