### ISSUE TITLE
API credentials not getting

### ISSUE THREAD

**Issue by AkashMegaravalli** [mjmlio/mjml#796]
Hi ,

 I am using MJML standalone  npm commands so far to convert to html, Now that want to make it independent hence wanted to use APIs,  Did registered on the API and gave my email properly, But still not getting my credentials to access API. Please help.

Thanks,
Akash

**Comment by ngarnier** [comment]
Hello @AkashMegaravalli, you should now have received your API credentials, feel free to comment if it's not the case!

Cheers
