### ISSUE TITLE
How to get errors when rendering from javascript (nodejs) code?

### ISSUE THREAD

**Issue by luixal** [mjmlio/mjml#798]
Hi, I'm having problems while trying to get errors when rendering MJML code.

### **Reproduction Steps:**

```javascript
import mjml from 'mjml';

// the MJML code. Note there's no closing tag for <mj-text>, I'm just forcing that error here:
var mjmlCode = '<mjml>mj-body><mj-text>Easy and Quick</mj-body></mjml>';

try {
  console.log(new mjml.MJMLRenderer(mjmlCode)); // should get an object with errors and html fields
  // also tried this, getting the same result:
  // console.log(mjml.mjml2html(mjmlCode));
} catch(error) {
  console.log(error); // in strict mode, I should get an object with a getErrors and getMessages functions
}
```

### **Expected behaviour:**
According to [this](https://www.npmjs.com/package/mjml-validator) I should get one of this:
* **soft** mode: the renderer should return an object with an `errors` field.
* **strict** mode: the `error` in the catch should contain `getErrors` and `getMessages` functions.

### **Observed behaviour:**
Got the exception raised in both cases (soft and strict), but with no info (not an Error object at all):
```
Error: [MJMLError] ParseError: Error while parsing the file
    at new MJMLError (modules.js?hash=460d1842c52aaca968e2cf7d1f333df7e695d3b3:4204)
    at documentParser (modules.js?hash=460d1842c52aaca968e2cf7d1f333df7e695d3b3:5135)
    at MJMLRenderer.parseDocument (modules.js?hash=460d1842c52aaca968e2cf7d1f333df7e695d3b3:4079)
    at new MJMLRenderer (modules.js?hash=460d1842c52aaca968e2cf7d1f333df7e695d3b3:4068)
    at Object.mjml2html (modules.js?hash=460d1842c52aaca968e2cf7d1f333df7e695d3b3:3780)
    at Object.preview (editor.js:44)
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3051
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1715
    at blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3103
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744)
```

### **MJML version:**
NodeJS: 4.6.2
MJML: 3.3.3

I tried all scenarios I found with no luck on any of them, ¿any idea how can I those errors?

Thanks!

**Comment by iRyusa** [comment]
Hi @luixal 

First i strongly advise you to update your node to a recent one.

I think this is because you have a typo in the string : 
`<mjml>`**<**`mj-body><mj-text>Easy and Quick</mj-body></mjml>`

**Comment by luixal** [comment]
Hi @iRyusa , sure about node version, just tried on **v8.4.0**, same result.

About the typo, that's one kind of error that I should get at the exception, isn't it?

According to `mjml-validator` doc:

> In Javascript, you can provide the level through the options parameters on MJMLRenderer. Ex: new MJMLRenderer(inputMJML, { level: strict }) strict will raise a MJMLValidationError exception. This object has 2 methods:
getErrors returns an array of objects with line, message, tagName as well as a formattedMessage which contains the line, message and tagName concatenated in a sentence.
getMessages returns an array of formattedMessage.
When using soft, no exception will be raised. You can get the errors using the object returned by the render method errors. It is the same object returned by getErrors on strict mode.

Thing is, I know MJML code has errors, I'm expecting the validator to return them.

**Comment by iRyusa** [comment]
Well as stated on my previous reply's edit parsing error is a "critical" error, not a validation error. 

Validation error are raised when some attributes are invalid for an element, invalid nesting, etc. 

Ex: setting a `apple` attribute on `mj-body` or directly set an `mj-text` inside `mj-body`.

**Comment by luixal** [comment]
Ah, ok, didn't know that.

IMHO, it would be interesting to get the number of the line that makes the parser crash :)

Thanks for the info!

**Comment by kuiperr005** [comment]
@iRyusa I agree with @luixal, if the parser crashes you now have to search for a mistake in your markup. Returning the line number should be really nice. Especially on larger templates it's now impossible to debug..

**Comment by iRyusa** [comment]
We don't have this information, that's why it throws a generic error.
