### ISSUE TITLE
mj-image html encodes src

### ISSUE THREAD

**Issue by sylvansecrets** [mjmlio/mjml#800]
Environment: Local Node.js
Language: JS
I called mjml2html on a string of mjml containing the following:
```
<mj-section padding-top="5" padding-bottom="5"  border = "0 none transparent""  border-radius="0px"> 
    <mj-column>
        <mj-image align="center"   src="http://i.imgur.com/4fix7Pc.jpg">
    </mj-column> 
</mj-section>
```

however, the rendered html contains instead of the expected image source, 
```
<img alt="" title="" height="519px" src="http%3A%2F%2Fi.imgur.com%2F4fix7Pc.jpg" style="border:none;border-radius:0px;display:block;font-size:13px;outline:none;text-decoration:none;width:100%;height:519px;" width="550">
```
The conversion of ":" and "/" into their html special char prevents the image from loading correctly (but does leave the correct amount of space)

**Comment by iRyusa** [comment]
Hi @sylvaindumont 

Well there's some typo in your MJML so it should be that :
- `border = "0 none transparent""` has two `"` at the end
-  your mj-image isn't closed  `<m-image ali... >`

**Comment by iRyusa** [comment]
Hi @sylvaindumont any news about that ?

**Comment by iRyusa** [comment]
Well I'm closing it for now, feel free to reopen if needed
