### ISSUE TITLE
overlapping two image, how can we achieve it when no margin supported

### ISSUE THREAD

**Issue by sagarsinha01** [mjmlio/mjml#801]
i want overlap two image one over another just like attached image as margin is not supported in mjml, how to achieve same result. Thanks for help!

![screen shot 2017-09-02 at 3 36 42 pm](https://user-images.githubusercontent.com/29568934/29994772-e8e5e3c6-8ff4-11e7-8420-544c54e3b510.png)

**Comment by iRyusa** [comment]
Hi @sagarsinha01 

Sadly in the email word there's no really bulletproof overlap technique, you can add extra white in your section background to achieve this kind of layout

**Comment by arun-is** [comment]
would something like this work? https://stackoverflow.com/questions/1829541/how-to-put-text-over-an-image-without-absolute-positioning-or-setting-the-image/1829885#1829885

**Comment by vgrafe** [comment]
To achieve this I'd write css classes and add styled elements within mj-raw.

**Comment by AradhanaChhabra** [comment]
I simply added `transform: translate();` in the css class inside `mj-style` for overlapping effect.
