### ISSUE TITLE
how to give a height to a section?

### ISSUE THREAD

**Issue by sagarsinha01** [mjmlio/mjml#802]

**Comment by iRyusa** [comment]
Hi @sagarsinha01 

Well section doesn't support height. However if you need a fixed height you can use mj-hero https://mjml.io/documentation/#mjml-hero if it's for a background related issue.

For content you can play with mj-table height, or mj-text that does support height.

Can you give us a screenshot of what you want to achieve ?

**Comment by sagarsinha01** [comment]
Got it, Thanks man.
