### ISSUE TITLE
mj-include not being included on render

### ISSUE THREAD

**Issue by goodwillhacking** [mjmlio/mjml#807]
Hi,
We have a node app which is using MJML to render and send transactional emails. Below is the basic layout for most of our emails as well as the render function we are using. Unfortunatley the includes are not being honored. We have tried relative and absolute file paths with no luck. Any help would be appreciated.

Node@4.4.7
MJML@3.3.3

SAMPLE
```
  <mj-head>
    <mj-title>User Registration</mj-title>
    <mj-attributes>
      <mj-text align="left" color="#000" font-size="15" />
      <mj-container background-color="#eee" />
    </mj-attributes>

  </mj-head>

  <mj-body>
    <mj-container>

      <mj-include path="./header.mjml" />

      <mj-section background-color="#fff">

 
      </mj-section>
      <mj-include path="./footer.mjml" />
    </mj-container>
  </mj-body>
</mjml>
```

RENDER FUNCTION
```
_render = (path, options, cb) ->
  read path, 'utf8', (err, file) ->
   ¦if err 
   ¦  cb(err)
   ¦else 
   ¦  htmlOutput = MJML.mjml2html Mustache.render file, options
   ¦  cb(null, htmlOutput.html)
```

**Comment by iRyusa** [comment]
hi @goodwillhacking 

You need to pass an extra option "filePath" with actual file you're rendering. So you should extend current `options` to add `filePath: path`

**Comment by goodwillhacking** [comment]
Thank you very very much. That worked.
