### ISSUE TITLE
Cannot use mj-divider in some places 

### ISSUE THREAD

**Issue by ncamacho97** [mjmlio/mjml#809]
So I have some dividers in the mjml and it tell me the have to put the divider in a mj-column like soo 

`<mj-column width="100%">
       
![screenshot from 2017-09-16 11-29-22](https://user-images.githubusercontent.com/23426639/30514103-884cb2f2-9ad4-11e7-869e-2814eaa0bfbf.png)
![screenshot from 2017-09-16 11-30-46](https://user-images.githubusercontent.com/23426639/30514102-884b7d4c-9ad4-11e7-94a4-c14dda34a9e7.png)

 <mj-divider border-color="#EF3E36"></mj-divider>
</mj-column>`

so then I did it as you can see but then when I just the ./node_modules/.bin/mjml index.mjml

**Comment by ncamacho97** [comment]
Then it say mj-column can't be used in mj-container

**Comment by iRyusa** [comment]
Hi @ncamacho97 

Can you share the template you're rendering into the try it live here : https://mjml.io/try-it-live

Thanks

**Comment by ncamacho97** [comment]
`<mjml>
  <mj-head>
    <mj-font name="Varela Round" href="https://fonts.googleapis.com/css?family=Varela+Round" />
  </mj-head>
  <mj-body>
    <mj-container>
      
      <mj-section background-color="#EF3E36" width="200">
        <mj-column>
          <mj-image align="left" width="100" src="" alt="" padding-bottom="0" padding-top="0">
          </mj-image>
        </mj-column>
      </mj-section>
      <mj-section background-url="https://gaytravel-destinations.s3.amazonaws.com/32343/the-bean-chicago-things-to-do__banner-large.jpg" vertical-align="middle" background-size="cover" background-repeat="no-repeat">
        <mj-column width="100%" vertical-align="middle">
          <mj-text align="center" font-size="14" color="#ffffff" padding-bottom="10" padding-top="10">
            <span style="font-size: 30px; line-height: 30px;"></span><br><br><span></span>
          </mj-text>
          <mj-button align="center" background-color="" color="#fff" border-radius="24px" href="https://https://www.swapped.shop" font-family="Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif" padding-bottom="50" padding-top="50">
          </mj-button>
        </mj-column>
      </mj-section>
      <mj-divider border-color="#EF3E36"></mj-divider>
      


      
      <mj-section background-color="#fbfbfb">
        <mj-text align="center" font-style="italic" font-size="20" font-family="Varela Round" color="black"> Account Features</mj-text>
      </mj-section>
      <mj-section background-color="#fbfbfb">

        
        <mj-column>
          <mj-image width="40px" align="center" src="https://s3.us-east-2.amazonaws.com/swapped/address-book.png" />
        </mj-column>

        
        <mj-column>
          <mj-text font-style="italic" font-size="20" font-family='Varela Round' ; color="black">
            Contacts
          </mj-text>
          <mj-text color="black" font-family="Varela Round">
            When you have a account You can add contacts so you can Communicate about listings</mj-text>
        </mj-column>
      </mj-section>
      <mj-column width="100%">
        <mj-divider border-color="#EF3E36"></mj-divider>
      </mj-column>
      
      <mj-section background-color="#fbfbfb">

        
        <mj-column>
          <mj-image width="40px" src="https://s3.us-east-2.amazonaws.com/swapped/file-text2.png" />
        </mj-column>

        
        <mj-column>
          <mj-text font-style="italic" font-size="20" font-family='Varela Round' color="black">
            New listing
          </mj-text>

          <mj-text color="#525252" font-family="Varela Round">
            New listing allows you to post items you want to gift, sell, or trade for free
          </mj-text>

        </mj-column>
      </mj-section>


      
      <mj-section background-color="#fbfbfb "></mj-section>


      <mj-section background-color="#EF3E36">
        <mj-text align="center" color="white" font-size="12px">
          <a href="#" style="color: white">
              Unsubscribe
            </a> from this newsletter
          <br>
          <a style="color:white; text-decoration:none;">&copy; Copyright 2017</a>
          </a>
        </mj-text>
      </mj-section>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

**Comment by ncamacho97** [comment]
<mjml>
  <mj-head>
    <mj-font name="Varela Round" href="https://fonts.googleapis.com/css?family=Varela+Round" />
  </mj-head>
  <mj-body>
    <mj-container>
      
      <mj-section background-color="#EF3E36" width="200">
        <mj-column>
          <mj-image align="left" width="100" src="" alt="" padding-bottom="0" padding-top="0">
          </mj-image>
        </mj-column>
      </mj-section>
      <mj-section background-url="https://gaytravel-destinations.s3.amazonaws.com/32343/the-bean-chicago-things-to-do__banner-large.jpg" vertical-align="middle" background-size="cover" background-repeat="no-repeat">
        <mj-column width="100%" vertical-align="middle">
          <mj-text align="center" font-size="14" color="#ffffff" padding-bottom="10" padding-top="10">
            <span style="font-size: 30px; line-height: 30px;"></span><br><br><span></span>
          </mj-text>
          <mj-button align="center" background-color="" color="#fff" border-radius="24px" href="https://https://www.swapped.shop" font-family="Ubuntu, Helvetica, Arial, sans-serif, Helvetica, Arial, sans-serif" padding-bottom="50" padding-top="50">
          </mj-button>
        </mj-column>
      </mj-section>
      <mj-divider border-color="#EF3E36"></mj-divider>
      


      
      <mj-section background-color="#fbfbfb">
        <mj-text align="center" font-style="italic" font-size="20" font-family="Varela Round" color="black"> Account Features</mj-text>
      </mj-section>
      <mj-section background-color="#fbfbfb">

        
        <mj-column>
          <mj-image width="40px" align="center" src="https://s3.us-east-2.amazonaws.com/swapped/address-book.png" />
        </mj-column>

        
        <mj-column>
          <mj-text font-style="italic" font-size="20" font-family='Varela Round' ; color="black">
            Contacts
          </mj-text>
          <mj-text color="black" font-family="Varela Round">
            When you have a account You can add contacts so you can Communicate about listings</mj-text>
        </mj-column>
      </mj-section>
      <mj-column width="100%">
        <mj-divider border-color="#EF3E36"></mj-divider>
      </mj-column>
      
      <mj-section background-color="#fbfbfb">

        
        <mj-column>
          <mj-image width="40px" src="https://s3.us-east-2.amazonaws.com/swapped/file-text2.png" />
        </mj-column>

        
        <mj-column>
          <mj-text font-style="italic" font-size="20" font-family='Varela Round' color="black">
            New listing
          </mj-text>

          <mj-text color="#525252" font-family="Varela Round">
            New listing allows you to post items you want to gift, sell, or trade for free
          </mj-text>

        </mj-column>
      </mj-section>


      
      <mj-section background-color="#fbfbfb "></mj-section>


      <mj-section background-color="#EF3E36">
        <mj-text align="center" color="white" font-size="12px">
          <a href="#" style="color: white">
              Unsubscribe
            </a> from this newsletter
          <br>
          <a style="color:white; text-decoration:none;">&copy; Copyright 2017</a>
          </a>
        </mj-text>
      </mj-section>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>

**Comment by iRyusa** [comment]
Well, there's many issue with your template.

Every column should bein a mj-section. Mj-text, divider, (content tag) etc should be inside a 
You might need to read https://mjml.io/documentation/#getting-started to understand how column/section works
