### ISSUE TITLE
Install fails looking for mjml-head-preview version 3.3.4

### ISSUE THREAD

**Issue by clokep** [mjmlio/mjml#811]
When trying to install mjml 3.3.4 npm fails:

```
npm ERR! notarget No compatible version found: mjml-head-preview@~3.3.4
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.0.0-alpha.3, 3.3.3, 3.3.3-beta.2
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'mjml'
npm ERR! notarget 
```

Looking at https://www.npmjs.com/package/mjml-head-preview there doesn't seem to be a 3.3.4 version of this, was this not uploaded or is the mjml dependency wrong?

**Comment by iRyusa** [comment]
Hi @clokep 

We got an issue with NPM permission cache atm. So you can bypass it with `npm install mjml@3.3.3`.

I'll keep the issue open (but locked) until this is solved

**Comment by iRyusa** [comment]
Mjml-head-preview 3.3.4 has been finally pushed to NPM ! 
So you can install the 3.3.4 now

**Comment by BartlomiejSkwira** [comment]
@iRyusa I was facing the same issue yesterday, ended up installing a specific-lower version of mjml. I just wonder what happened? care to elaborate?

**Comment by iRyusa** [comment]
We had an issue with ownership of a single package on NPM. NPM has a really long cache on package ownership so we were unable to release the 3.3.4 of that version

**Comment by BartlomiejSkwira** [comment]
Another argument why npm seems to be poorly designed. My team had a different issue with it lately. Kinda sucks

**Comment by iRyusa** [comment]
Well, with the number of package on NPM and simultaneous downloads, I think we can understand their aggressive caching :)

**Comment by BartlomiejSkwira** [comment]
Fair point. In my case there should be a fallback mechanism, I was installing `mjml@^3.0` so basically `3.x.x`, in my opinion, it should try to install `3.3.4` -> exception -> fallback to `3.3.3` this way I wouldn't have broken build issues.
