### ISSUE TITLE
RE: Install fails looking for mjml-head-preview version 3.3.4 #811

### ISSUE THREAD

**Issue by yegortokmakov** [mjmlio/mjml#813]
hi guys,

as that issue is locked from further discussions, I have to create a new one.
Why don't you create a new release of mjml-head-preview 3.3.4 so everyone won't have to make the same change?

@iRyusa 

Cheers
Yegor

**Comment by iRyusa** [comment]
Hi as mentioned in #811 ,

We have an issue with NPM and can't publish the 3.3.4 package because of the ownership on it.
We've mailed the support and trying to get the package published asap.
