### ISSUE TITLE
new CSS features

### ISSUE THREAD

**Issue by cmnstmntmn** [mjmlio/mjml#815]
https://www.campaignmonitor.com/blog/email-marketing/2017/09/all-new-guide-css-support-email/

**Comment by ngarnier** [comment]
hey @cmnstmntmn, not sure what you mean with this.

This article is about the fact that CM updated their page, adding more CSS features in their table of support by email clients. It doesn't mean there was a specific change in email clients that would mean that we can safely add those features. 

If you see specific CSS features that could be added on specific MJML elements, feel free to create a dedicated issue.

Thanks!
