### ISSUE TITLE
Problem with mobile when declaring width in column compondent

### ISSUE THREAD

**Issue by sberthu** [mjmlio/mjml#816]
Hello !
I try to construct a simple gray line centered to the email.
I define 3 columns, first for left padding, middle for the gray line and third for the right padding.
It's ok for Desktop, but for mobile, nothing appears!
I'm looking for the HTML code and discover than the width of each column is < 1%!!
Perhaps the parent width is not taken.
Here is an example of this problem:

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section background-color="#ffffff">
        <mj-group>
          <mj-column width="150" background-color="#FF0000">
            <mj-spacer height="1px" /></mj-column>
          <mj-column width="300" background-color="#00FF00">
            <mj-spacer height="1px" /></mj-column>
          <mj-column width="150" background-color="#0000FF">
            <mj-spacer height="1px" /></mj-column>
        </mj-group>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```` 

like you can see in the HTML code, the width is 0.25% for the first, 0.5% for second and 0.25% again for the third.
In Desktop Mode it works because thes HTML attribute ("width") are override by CSS.
Thank you for your time.
Sylvain Berthu

**Comment by iRyusa** [comment]
Hi @sberthu 

As mj-group is for mobile layout, you can only define column in `%` of the defined width of a group.
That's why it breaks: You should do 25% / 50 % / 25% and then it works fine

**Comment by sberthu** [comment]
hello Maxime,
thank you very much for your quick reply!
I understand that percentage are more powerfull when dealing with
responsive, but some case, you need to fixed width of column specialy when
dealing with pictures.
Here is an example when my designer has add a timeline at the left on the
book topic (with bullets) and I don't see how to avoid to use picture (I
dont't know how to enlarge this one for the mobile rendering any more and
if you have an idea, I take it!!)

Thank for your reply and have a nice day.


[image: Images intégrées 2]


2017-09-22 23:16 GMT+02:00 Maxime Brazeilles <notifications@github.com>:

**Comment by iRyusa** [comment]
Well, in mobile we can't enable `mj-group` to rely on pixel because screen resolution may differs from a device to another.

I can't see your image, you have to upload it on a website like imgur or reply to the issue on the github website

**Comment by sberthu** [comment]
thank for your reply.
Here is the imgur link:https://imgur.com/a/YJuxj



2017-09-25 18:25 GMT+02:00 Maxime Brazeilles <notifications@github.com>:

**Comment by iRyusa** [comment]
Well the design isn't really email-friendly, and not so much idea on how to deal with it. You might want to come on the Slack and ask the community if someone have done something like that

**Comment by sberthu** [comment]
Yes, I understand and I am agree with you.
Thank a lot for your replies and thank you for your beautiful project!!


2017-09-25 18:37 GMT+02:00 Maxime Brazeilles <notifications@github.com>:

**Comment by iRyusa** [comment]
You can find the mjml slack here https://slack.mjml.io/
