### ISSUE TITLE
colums aligning left on mobile

### ISSUE THREAD

**Issue by edtrash** [mjmlio/mjml#818]
Hi! I've been playing with MJML and find it super useful for my work, where I need to create music artists newsletter announcements.

I've created a first draft with a full background (in a full container wrapper), logo, two columns with text and image and button, then a list of dates.

On mobile though, the two colums with pictures get aligned left no matter what I try to fix it. I got it working somehow, once... but can't find out how (shouldn't have done it in the middle of the night...). I have the email test where it worked but even after trying to compare html I can't find the issue.

The list of dates sections are wonky too, and get broken when on mobile, all aligning left. It's got a title section and dates sections that are 33% each.

Here's the code... I'm hoping someone can help out, it's kinda driving me crazy :)
thanks! ed

somehow the code breaks on github so uploaded on pastebin 
https://pastebin.com/nenu7Msf

**Comment by ngarnier** [comment]
Hey @edtrash, I just tried and the images look properly centered: https://mjml.io/try-it-live/HkpF0CUoW. 

Can you maybe share a version of your template with hosted images? It would help to see the issues with the right assets (I had to guess you had a colored background-image with white texts 🤓).

If you're seeing those issues in a specific email client, please specify which (a screenshot would help too). 

About your dates section, I suspect you're seeing this on iOS, you need to minify the output (`mjml -m` with the MJML CLI) like stated in the documentation.

PS: you have set attributes on closing tags, like `line 100` with `</mj-column width="33%">
PPS: I love Petit Biscuit 😄

**Comment by edtrash** [comment]
Hey there! Thanks for your very quick answer. 
Is there any way to take it up directly with you through email? 
The newsletter I'm building has confidential info on it and i'd like to not spill it out on the web :)
And maybe we could continue in French too ! If that's alright shoot me a note at ed@trashbros.net

The mobile email client I'm testing with is Android AquaMail.
I'll try minifying the output right now.

glad you like the music :) thanks !

**Comment by ngarnier** [comment]
My email is ngarnier@mailjet.com but debugging over email won't be easy, can you rather join the community MJML Slack? Then we can chat in private there: https://slack.mjml.io/
