### ISSUE TITLE
API beta?

### ISSUE THREAD

**Issue by peiche** [mjmlio/mjml#819]
About how long does it usually take to get assigned an API key?

**Comment by ngarnier** [comment]
I just created your API Key.

**Comment by creativenoobie** [comment]
@ngarnier 

I'm also waiting for my API keys and I really wish that this process could be automated in order to reduce the waiting period.

**Comment by masatoTokyo** [comment]
Hi @ngarnier, I have sent a API key request twice but haven't got anything yet.
Could you create my API key, please?

**Comment by ngarnier** [comment]
hi @masatoTokyo, done :)
