### ISSUE TITLE
Outlook 2007 , 2010, 2013 (on Windows 7) failure font fallback with Google font

### ISSUE THREAD

**Issue by dhenry-adpear** [mjmlio/mjml#820]
I noticed while using Litmus that Outlook 2007, 2010, 2013 (on Windows 7) is having issues when using a Google Font. Instead of falling back to Helvetica or Arial it renders Times New Roman. At first I thought it was just my personal project. However, after throwing in some of the templates ( 1OnePage) that are located on the MJML site I am realizing that it is inherit with the system. Thought I would share this. Spent most of the day trying to come up with a work around.  Unfortunately I didn't find anything great. Once the Google font is removed Outlook renders fine.

**Comment by ngarnier** [comment]
Hey @dhenry-adpear, this usually happens when you use a Google font composed of several words (like "Open Sans"). Can you share a snippet of MJML showcasing your issue (with the font imported and used).

You might also want to have a look at this fix on Litmus: https://litmus.com/community/discussions/982-outlook-overrides-font-to-times-new-roman#comment-6488

**Comment by dhenry-adpear** [comment]
Hi @ngarnier, 
Thanks for getting back to me. 
So I tried it with multiple different Google fonts such as, "Open Sans," "Montserrat," "Railway," and "Ubuntu" and all yielded the same results. I even boiled down my code so that it was comprised of the following:

```
<mjml>
    <mj-head>
        <mj-font name="Montserrat" href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" />

        <mj-attributes>
            <mj-all font-family="'Montserrat', Helvetica, Arial, sans-serif"/>
        </mj-attributes>
    </mj-head>  
    <mj-body>
        <mj-container> 
            <mj-section > 
                <mj-column > 
                    <mj-text>
                        <h1 class="title">Weekly Report</h1>  
                    </mj-text> 
                </mj-column>  
            </mj-section>
        </mj-container>
    </mj-body>
</mjml>
```

I was able to fix it by incorporating the fix you linked to, however, I had to incorporate more than just the  body, table and td.
```

<!--[if mso]>
  <style type="text/css">
  body, table, td, h1, h2, h3, h4, h5, h6, p, span, strong {font-family: Arial, Helvetica, sans-serif !important;}
  </style>
<![endif]-->
```
Is that something that can be added in on the next build?

Anyways, thanks for the help and MJML!

**Comment by ngarnier** [comment]
Ha, can you try again without the single quotes around the imported font-family?

**Comment by iRyusa** [comment]
It fallback nicely to arial with your first snippet. cf screenshot on litmus + https://mjml.io/try-it-live/SyJ0GVKi-

![image](https://user-images.githubusercontent.com/570317/30918688-8cc43f16-a39f-11e7-9973-89d046319882.png)

**Comment by dhenry-adpear** [comment]
@ngarnier  - I removed the single quotes around Montserrat, however I am still seeing the issue in Litmus for Outlook 2007, 2010, 2013, and 2016 (Windows 7). See attached screen shot.
![mjml](https://user-images.githubusercontent.com/6013004/30920431-cd215478-a358-11e7-844b-c89df6e65cc6.png)

**Comment by ngarnier** [comment]
Interesting, so you're getting different results with the same snippet. How are you sending? If with an ESP, can you please try to send the email with https://putsmail.com/?

**Comment by ngarnier** [comment]
ha, well that's good to know, thanks for sharing the source of the issue!

No worries, and happy you found the solution!
