### ISSUE TITLE
mj-social align not working on Outlook 2007 / 2013 / 2016

### ISSUE THREAD

**Issue by Skinwalker** [mjmlio/mjml#822]
mj-social should be centered by default
This is working in Outlook 2003 - but with higher versions the social block is left aligned

Using MJML v 3.3.3

MJML (from the doc)
```
<mj-social
	display="google facebook"
	google-icon-color="#424242"
	facebook-icon-color="#424242"
	facebook-href="My facebook page"
	google-href="My google+ page" />
```

**Comment by iRyusa** [comment]
Hi @Skinwalker 
I'm unable to reproduce your issue as you can see it's perfectly aligned in Outlook 2013 and so on : 
![image](https://user-images.githubusercontent.com/570317/30958728-4d450006-a43e-11e7-8f07-0ad499acc574.png)
https://mjml.io/try-it-live/ryOSaE5jW

Might be an issue from your side, try to send your email through putsmail.com to see if it fix it. If so your ESP alter the HTML you send and there's nothing we can do about it.

**Comment by Skinwalker** [comment]
Same problem as with #814 
In my Litmus Previews the Social Icons gets left aligned

**Comment by iRyusa** [comment]
Did you check this : https://github.com/mjmlio/mjml/issues/820#issuecomment-332555504 

Because no one is able to reproduce your issue here with almost the same setup

**Comment by Skinwalker** [comment]
Same Problem when sending to litmus through putsmail

**Comment by Skinwalker** [comment]
See my Litmus Test here: https://litmus.com/pub/5267a00

**Comment by Skinwalker** [comment]
Found out that im using MJML Version 3.3.2 (version comes from gulp-mjml)
Can this might be the problem?

**Comment by Skinwalker** [comment]
Problem seems to be this:

```
<!--[if mso | IE]>
      <table role="presentation" border="0" cellpadding="0" cellspacing="0" align="undefined"><tr><td>
      <![endif]-->
```

where the align attribute is "undefined".
If I enter "center" it's working.

Even when ich copy my MJML into your Live Editor the conditional align is "undefined"

Happens also with the vertical-align attribute of the mj-section conditional code

**Comment by iRyusa** [comment]
It shouldn't be an issue, this align should be removed. Can you share the HTML produced from the litmus link ?
