### ISSUE TITLE
Links with <a> or href attribute on mj-image doesn't work - Outlook.com

### ISSUE THREAD

**Issue by JustineCosson** [mjmlio/mjml#827]
Hello everybody,
I have a problem on link integration on Outlook.com

Here is my mjml:

```
<mj-section padding-left="0" padding-right="0">
        		<mj-column>
        			<mj-text align="center" padding="20 0 15 0" container-background-color="#E3E3E3"><a href="google.com" style="color:black;">Read news</a></mj-text>
          			<mj-image src="quot_top.svg" />
          			<mj-text font-size="16" align="center" padding="15 0" container-background-color="#001840" color="white">EDITION DU 1ER SEPTEMBRE 2017</mj-text>
        		</mj-column>
      		</mj-section>
```

The link does not work on Outlook.com.
In the mail, this appears like this:
[google.com]Read news
and the link is not clickable.

In addition, the "href" attribute of the mj-image tag does not work on Outlook.com.
Has anyone ever encountered these problems?

Thank you for your help,

**Comment by iRyusa** [comment]
Hi @JustineCosson 

Well it does, but you need to add an http:// before it. Outlook.com breaks if the link isn't "valid", you can check the problem here https://github.com/hteumeuleu/email-bugs/issues/10

**Comment by JustineCosson** [comment]
Thank you so much for your help !
