### ISSUE TITLE
local background

### ISSUE THREAD

**Issue by knosuhor** [mjmlio/mjml#828]
How is it possible to use local file for background? Can't add style to "mj-section" nor use "background="image.jpg" nor src.

**Comment by rogierslag** [comment]
You basically cant, the file should be accessible from a server somewhere. You might be able to add a file using the file:// approach, but I doubt it will show up in any email client

**Comment by iRyusa** [comment]
Well you can, if you're opening the produced file locally, but as @rogierslag mentioned, at some point you'll need to upload it somewhere.

The attribute you're looking for on `mj-section` is `background-url`. You can find a list of all supported attributes here : https://mjml.io/documentation/#mjml-section
