### ISSUE TITLE
Striped background rows

### ISSUE THREAD

**Issue by Rick8rooke** [mjmlio/mjml#831]
Hi,

I'm having problems creating a layout for my email within MJML and wondered if you could help me?

I have to duplicate a design given to me that has full width rows with different coloured backgrounds. Within each row the content should be max-width 600px. This content could be 2-3 columns and this content should stack in mobile view. The coloured rows should all be full width and the content restricted to 600px width.

I have tried a few ways to do this but cannot seem to replicate the layout as I think I need to nest a table inside your mj tags like this:

```
<mjml>
  <mj-body>
    <mj-container width="100%">
     <mj-wrapper full-width="100%" background-color="grey">
      <mj-section width="600px">
        <mj-column>
          <mj-table>
            <tr style="border-bottom:1px solid #ecedee;text-align:left;padding:15px 0;">
              <th style="padding: 0 15px 0 0;">Year</th>
              <th style="padding: 0 15px;">Language</th>
              <th style="padding: 0 0 0 15px;">Inspired from</th>
            </tr>
            <tr>
              <td style="padding: 0 15px 0 0;">1995</td>
              <td style="padding: 0 15px;">PHP</td>
              <td style="padding: 0 0 0 15px;">C, Shell Unix</td>
            </tr>
            <tr>
              <td style="padding: 0 15px 0 0;">1995</td>
              <td style="padding: 0 15px;">JavaScript</td>
              <td style="padding: 0 0 0 15px;">Scheme, Self</td>
            </tr>
          </mj-table>
        </mj-column>
      </mj-section>
     </mj-wrapper>
    </mj-container>
  </mj-body>

```

I thought it would be as simple as repeating all the code within the ' mj-wrapper tags ' and choosing background colours but its not working though - whats the best way I can set up this simple layout please?

![example](https://user-images.githubusercontent.com/15854447/31347293-ccfa76fe-ad13-11e7-801a-ddea0d2dcad6.jpg)

**Comment by iRyusa** [comment]
Hi @Rick8rooke

You can just use `full-width` attribute on a section no need to nest or add a mj-wrapper:  https://mjml.io/try-it-live/Hk4NwQFhb

As you can see default background color is set with mj-attributes and will fallback to it if not defined.

Note that background doesn't appear as full width on try it live because the viewport is set to 600px, you can watch the result in MJML App/ directly in your browser

**Comment by Rick8rooke** [comment]
Thats a great help, thank you so much :)
