### ISSUE TITLE
Social icons update?

### ISSUE THREAD

**Issue by evforija** [mjmlio/mjml#835]
Hello there! Is there a way to get better social icons that are more up to date with the brand guidelines of each platform, and can be sized larger? Thank you!

**Comment by iRyusa** [comment]
Hi @evforija 

There's many attribute on mj-social to customize it ( icon-size, base-url to custom the icon base url and upload yours, you can override network to create your custom network ) you can read the list of all available attributes here : https://mjml.io/documentation/#mjml-social
