### ISSUE TITLE
Background-image on window 10

### ISSUE THREAD

**Issue by scottin** [mjmlio/mjml#836]
a Workaround is available for background image on  Windows 10 ( Windows Live and Outlook.com ) : https://emailmonks.com/blog/email-coding/background-image-supports-windows-10-mail-app/

**Comment by iRyusa** [comment]
Hi @scottin ,

Well mj-hero already use a similar technique with image and it works just fine : 
![image](https://user-images.githubusercontent.com/570317/31440766-5229f5d8-ae91-11e7-99c3-6b77d1e72f73.png)
But we can't use this on `mj-section` because height will be required.

Thanks for sharing it !

**Comment by wireinet** [comment]
i have a problem with windows 10! Some image are not load!
[http://s008.radikal.ru/i305/1712/82/752bfaa330f6.png](url)

**Comment by ngarnier** [comment]
@wireinet if it's a background-image it's normal, Windows 10 Mail doesn't support them

**Comment by wireinet** [comment]
Thank you for unswer, ngarnier! Dont know this! But how you can explain this? Its hero image! i have two hero images in two different mails! in one - all ok - in picture below - in other - no image background :) 


![2017-12-22_12-25-02](https://user-images.githubusercontent.com/23517333/34292995-043c1c1e-e714-11e7-8760-3a4660a2b6d3.png)

**Comment by ngarnier** [comment]
Would need some code, can't explain anything without the original code 🙄

**Comment by wireinet** [comment]
:) ок. 
This piece of code - not display in windows 10 mail:
![2017-12-22_12-54-49](https://user-images.githubusercontent.com/23517333/34293893-5663455a-e717-11e7-862e-01f3551b775c.png)

This piece of code - very well
![2017-12-22_12-58-09](https://user-images.githubusercontent.com/23517333/34294031-ca364dce-e717-11e7-8dd3-7107bd1a5cfa.png)

Cant understand what is difference for windows 10 mail?
Can you help?

**Comment by ngarnier** [comment]
Can you share this as code snippets so we can try them please?

**Comment by wireinet** [comment]
ofcouse - this is code that is works fine in windows 10!
If you want - i can send you this mail - but give me email, that you can open in windows 10 mail client


 <mj-hero
        mode="fixed-height"
        height="469px"
        background-width="600px"
        background-height="469px"
        background-url="http://ap-com.ru/images/mail/hasten/hero-image.gif"
        background-color="#2a3448"
        padding="100px 0px">
        <mj-hero-content width="100%">
          <mj-text
            padding="20px"
            color="#ffffff"
            font-family="Helvetica"
            align="center"
            font-size="29"
            line-height="32px"
            font-weight="900">
            Enjoy 20% off on our virtual staging and 3D visualization service!
          </mj-text>

        </mj-hero-content>
      </mj-hero>

**Comment by wireinet** [comment]
[new 1.txt](https://github.com/mjmlio/mjml/files/1582177/new.1.txt)

**Comment by cly3** [comment]
Not sure if this is a related issue but I have found that `<mj-hero>` does not render on the Microsoft Outlook (Office Business Platform) V.1711.  

I'm going to guess that it has something to do with the conditional statements.

**Comment by wireinet** [comment]
hm..no sure that this is reason...hero present in both project - one open correct - one is not.
