### ISSUE TITLE
CSS-class illegal v3.3.5

### ISSUE THREAD

**Issue by Omazon** [mjmlio/mjml#838]
I am currently using the latest version (3.3.5) and I have the error (mj-section) - Attribute css-class is illegal, had understood that it only worked in the 3.3.3 version, but this is a superior version, it should not be included? or would it just works exactly in the 3.3.3?. Am I doing something wrong?, help

![imagen](https://user-images.githubusercontent.com/22031788/31512594-c4c66f42-af48-11e7-93dc-f9c735ab60aa.png)

![imagen](https://user-images.githubusercontent.com/22031788/31512613-d293113e-af48-11e7-83c8-37cc67bea903.png)

**Comment by iRyusa** [comment]
Hi @Omazon 
Can you do an `npm list` for me ? That's strange css-class is a whitelisted attribute for every components

**Comment by Omazon** [comment]
Thanks in advance for helping me, and clear that if I do not know if I am doing something wrong. :(

npm list
xxxx_xxxxx@1.0.0 C:\Users\Omar Boza\Documents\Proyectos Omar\Mailchimp\cortes Emailing xxxxxxxxx\email
`-- mjml@3.3.5
  +-- lodash@4.17.4
  +-- mjml-accordion@3.3.5
  | +-- classnames@2.2.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2
  |   +-- create-react-class@15.6.2
  |   | +-- fbjs@0.8.16 deduped
  |   | +-- loose-envify@1.3.1 deduped
  |   | `-- object-assign@4.1.1 deduped
  |   +-- fbjs@0.8.16
  |   | +-- core-js@1.2.7
  |   | +-- isomorphic-fetch@2.2.1
  |   | | +-- node-fetch@1.7.3
  |   | | | +-- encoding@0.1.12
  |   | | | | `-- iconv-lite@0.4.19
  |   | | | `-- is-stream@1.1.0
  |   | | `-- whatwg-fetch@2.0.3
  |   | +-- loose-envify@1.3.1 deduped
  |   | +-- object-assign@4.1.1 deduped
  |   | +-- promise@7.3.1
  |   | | `-- asap@2.0.6
  |   | +-- setimmediate@1.0.5
  |   | `-- ua-parser-js@0.7.14
  |   +-- loose-envify@1.3.1
  |   | `-- js-tokens@3.0.2
  |   +-- object-assign@4.1.1
  |   `-- prop-types@15.6.0
  |     +-- fbjs@0.8.16 deduped
  |     +-- loose-envify@1.3.1 deduped
  |     `-- object-assign@4.1.1 deduped
  +-- mjml-button@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-carousel@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-cli@3.3.5
  | +-- chokidar@1.7.0
  | | +-- anymatch@1.3.2
  | | | +-- micromatch@2.3.11
  | | | | +-- arr-diff@2.0.0
  | | | | | `-- arr-flatten@1.1.0
  | | | | +-- array-unique@0.2.1
  | | | | +-- braces@1.8.5
  | | | | | +-- expand-range@1.8.2
  | | | | | | `-- fill-range@2.2.3
  | | | | | |   +-- is-number@2.1.0
  | | | | | |   | `-- kind-of@3.2.2 deduped
  | | | | | |   +-- isobject@2.1.0
  | | | | | |   | `-- isarray@1.0.0 deduped
  | | | | | |   +-- randomatic@1.1.7
  | | | | | |   | +-- is-number@3.0.0
  | | | | | |   | | `-- kind-of@3.2.2
  | | | | | |   | |   `-- is-buffer@1.1.5 deduped
  | | | | | |   | `-- kind-of@4.0.0
  | | | | | |   |   `-- is-buffer@1.1.5 deduped
  | | | | | |   +-- repeat-element@1.1.2 deduped
  | | | | | |   `-- repeat-string@1.6.1
  | | | | | +-- preserve@0.2.0
  | | | | | `-- repeat-element@1.1.2
  | | | | +-- expand-brackets@0.1.5
  | | | | | `-- is-posix-bracket@0.1.1
  | | | | +-- extglob@0.3.2
  | | | | | `-- is-extglob@1.0.0 deduped
  | | | | +-- filename-regex@2.0.1
  | | | | +-- is-extglob@1.0.0 deduped
  | | | | +-- is-glob@2.0.1 deduped
  | | | | +-- kind-of@3.2.2
  | | | | | `-- is-buffer@1.1.5
  | | | | +-- normalize-path@2.1.1 deduped
  | | | | +-- object.omit@2.0.1
  | | | | | +-- for-own@0.1.5
  | | | | | | `-- for-in@1.0.2
  | | | | | `-- is-extendable@0.1.1
  | | | | +-- parse-glob@3.0.4
  | | | | | +-- glob-base@0.3.0
  | | | | | | +-- glob-parent@2.0.0 deduped
  | | | | | | `-- is-glob@2.0.1 deduped
  | | | | | +-- is-dotfile@1.0.3
  | | | | | +-- is-extglob@1.0.0 deduped
  | | | | | `-- is-glob@2.0.1 deduped
  | | | | `-- regex-cache@0.4.4
  | | | |   `-- is-equal-shallow@0.1.3
  | | | |     `-- is-primitive@2.0.0
  | | | `-- normalize-path@2.1.1
  | | |   `-- remove-trailing-separator@1.1.0
  | | +-- async-each@1.0.1
  | | +-- UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
  | | +-- glob-parent@2.0.0
  | | | `-- is-glob@2.0.1 deduped
  | | +-- inherits@2.0.3
  | | +-- is-binary-path@1.0.1
  | | | `-- binary-extensions@1.10.0
  | | +-- is-glob@2.0.1
  | | | `-- is-extglob@1.0.0
  | | +-- path-is-absolute@1.0.1
  | | `-- readdirp@2.1.0
  | |   +-- graceful-fs@4.1.11
  | |   +-- minimatch@3.0.4 deduped
  | |   +-- readable-stream@2.3.3
  | |   | +-- core-util-is@1.0.2
  | |   | +-- inherits@2.0.3 deduped
  | |   | +-- isarray@1.0.0
  | |   | +-- process-nextick-args@1.0.7
  | |   | +-- safe-buffer@5.1.1
  | |   | +-- string_decoder@1.0.3
  | |   | | `-- safe-buffer@5.1.1 deduped
  | |   | `-- util-deprecate@1.0.2
  | |   `-- set-immediate-shim@1.0.1
  | +-- commander@2.11.0
  | +-- glob@7.1.2
  | | +-- fs.realpath@1.0.0
  | | +-- inflight@1.0.6
  | | | +-- once@1.4.0 deduped
  | | | `-- wrappy@1.0.2
  | | +-- inherits@2.0.3 deduped
  | | +-- minimatch@3.0.4
  | | | `-- brace-expansion@1.1.8
  | | |   +-- balanced-match@1.0.0
  | | |   `-- concat-map@0.0.1
  | | +-- once@1.4.0
  | | | `-- wrappy@1.0.2 deduped
  | | `-- path-is-absolute@1.0.1 deduped
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- mz@2.7.0
  |   +-- any-promise@1.3.0
  |   +-- object-assign@4.1.1 deduped
  |   `-- thenify-all@1.6.0
  |     `-- thenify@3.3.0
  |       `-- any-promise@1.3.0 deduped
  +-- mjml-column@3.3.5
  | +-- classnames@2.2.5 deduped
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-container@3.3.5
  | +-- classnames@2.2.5 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-core@3.3.5
  | +-- cheerio@0.22.0
  | | +-- css-select@1.2.0
  | | | +-- boolbase@1.0.0
  | | | +-- css-what@2.1.0
  | | | +-- domutils@1.5.1
  | | | | +-- dom-serializer@0.1.0 deduped
  | | | | `-- domelementtype@1.3.0 deduped
  | | | `-- nth-check@1.0.1
  | | |   `-- boolbase@1.0.0 deduped
  | | +-- dom-serializer@0.1.0
  | | | +-- domelementtype@1.1.3
  | | | `-- entities@1.1.1 deduped
  | | +-- entities@1.1.1
  | | +-- htmlparser2@3.9.2
  | | | +-- domelementtype@1.3.0
  | | | +-- domhandler@2.4.1
  | | | | `-- domelementtype@1.3.0 deduped
  | | | +-- domutils@1.5.1 deduped
  | | | +-- entities@1.1.1 deduped
  | | | +-- inherits@2.0.3 deduped
  | | | `-- readable-stream@2.3.3 deduped
  | | +-- lodash.assignin@4.2.0
  | | +-- lodash.bind@4.2.1
  | | +-- lodash.defaults@4.2.0
  | | +-- lodash.filter@4.6.0
  | | +-- lodash.flatten@4.4.0
  | | +-- lodash.foreach@4.5.0
  | | +-- lodash.map@4.6.0
  | | +-- lodash.merge@4.6.0
  | | +-- lodash.pick@4.4.0
  | | +-- lodash.reduce@4.6.0
  | | +-- lodash.reject@4.6.0
  | | `-- lodash.some@4.6.0
  | +-- classnames@2.2.5 deduped
  | +-- debug@2.6.9
  | | `-- ms@2.0.0
  | +-- he@1.1.1
  | +-- hoist-non-react-statics@1.2.0
  | +-- html-minifier@3.5.5
  | | +-- camel-case@3.0.0
  | | | +-- no-case@2.3.2
  | | | | `-- lower-case@1.1.4
  | | | `-- upper-case@1.1.3
  | | +-- clean-css@4.1.9
  | | | `-- source-map@0.5.7
  | | +-- commander@2.11.0 deduped
  | | +-- he@1.1.1 deduped
  | | +-- ncname@1.0.0
  | | | `-- xml-char-classes@1.0.0
  | | +-- param-case@2.1.1
  | | | `-- no-case@2.3.2 deduped
  | | +-- relateurl@0.2.7
  | | `-- uglify-js@3.1.3
  | |   +-- commander@2.11.0 deduped
  | |   `-- source-map@0.5.7 deduped
  | +-- immutable@3.8.2
  | +-- jquery@3.2.1
  | +-- js-beautify@1.7.4
  | | +-- config-chain@1.1.11
  | | | +-- ini@1.3.4
  | | | `-- proto-list@1.2.4
  | | +-- editorconfig@0.13.3
  | | | +-- bluebird@3.5.1
  | | | +-- commander@2.11.0 deduped
  | | | +-- lru-cache@3.2.0
  | | | | `-- pseudomap@1.0.2
  | | | +-- semver@5.4.1
  | | | `-- sigmund@1.0.1
  | | +-- mkdirp@0.5.1
  | | | `-- minimist@0.0.8
  | | `-- nopt@3.0.6
  | |   `-- abbrev@1.1.1
  | +-- juice@4.2.0
  | | +-- cheerio@0.22.0 deduped
  | | +-- commander@2.9.0
  | | | `-- graceful-readlink@1.0.1
  | | +-- cross-spawn@5.1.0
  | | | +-- lru-cache@4.1.1
  | | | | +-- pseudomap@1.0.2 deduped
  | | | | `-- yallist@2.1.2
  | | | +-- shebang-command@1.2.0
  | | | | `-- shebang-regex@1.0.0
  | | | `-- which@1.3.0
  | | |   `-- isexe@2.0.0
  | | +-- deep-extend@0.5.0
  | | +-- mensch@0.3.3
  | | +-- slick@1.12.2
  | | `-- web-resource-inliner@4.2.0
  | |   +-- async@2.5.0
  | |   | `-- lodash@4.17.4 deduped
  | |   +-- chalk@1.1.3
  | |   | +-- ansi-styles@2.2.1
  | |   | +-- escape-string-regexp@1.0.5
  | |   | +-- has-ansi@2.0.0
  | |   | | `-- ansi-regex@2.1.1
  | |   | +-- strip-ansi@3.0.1
  | |   | | `-- ansi-regex@2.1.1 deduped
  | |   | `-- supports-color@2.0.0
  | |   +-- datauri@1.0.5
  | |   | +-- image-size@0.3.5
  | |   | +-- mimer@0.2.1
  | |   | `-- semver@5.4.1 deduped
  | |   +-- htmlparser2@3.9.2 deduped
  | |   +-- lodash.unescape@4.0.1
  | |   +-- request@2.83.0
  | |   | +-- aws-sign2@0.7.0
  | |   | +-- aws4@1.6.0
  | |   | +-- caseless@0.12.0
  | |   | +-- combined-stream@1.0.5
  | |   | | `-- delayed-stream@1.0.0
  | |   | +-- extend@3.0.1
  | |   | +-- forever-agent@0.6.1
  | |   | +-- form-data@2.3.1
  | |   | | +-- asynckit@0.4.0
  | |   | | +-- combined-stream@1.0.5 deduped
  | |   | | `-- mime-types@2.1.17 deduped
  | |   | +-- har-validator@5.0.3
  | |   | | +-- ajv@5.2.3
  | |   | | | +-- co@4.6.0
  | |   | | | +-- fast-deep-equal@1.0.0
  | |   | | | +-- json-schema-traverse@0.3.1
  | |   | | | `-- json-stable-stringify@1.0.1
  | |   | | |   `-- jsonify@0.0.0
  | |   | | `-- har-schema@2.0.0
  | |   | +-- hawk@6.0.2
  | |   | | +-- boom@4.3.1
  | |   | | | `-- hoek@4.2.0 deduped
  | |   | | +-- cryptiles@3.1.2
  | |   | | | `-- boom@5.2.0
  | |   | | |   `-- hoek@4.2.0 deduped
  | |   | | +-- hoek@4.2.0
  | |   | | `-- sntp@2.0.2
  | |   | |   `-- hoek@4.2.0 deduped
  | |   | +-- http-signature@1.2.0
  | |   | | +-- assert-plus@1.0.0
  | |   | | +-- jsprim@1.4.1
  | |   | | | +-- assert-plus@1.0.0 deduped
  | |   | | | +-- extsprintf@1.3.0
  | |   | | | +-- json-schema@0.2.3
  | |   | | | `-- verror@1.10.0
  | |   | | |   +-- assert-plus@1.0.0 deduped
  | |   | | |   +-- core-util-is@1.0.2 deduped
  | |   | | |   `-- extsprintf@1.3.0 deduped
  | |   | | `-- sshpk@1.13.1
  | |   | |   +-- asn1@0.2.3
  | |   | |   +-- assert-plus@1.0.0 deduped
  | |   | |   +-- bcrypt-pbkdf@1.0.1
  | |   | |   | `-- tweetnacl@0.14.5 deduped
  | |   | |   +-- dashdash@1.14.1
  | |   | |   | `-- assert-plus@1.0.0 deduped
  | |   | |   +-- ecc-jsbn@0.1.1
  | |   | |   | `-- jsbn@0.1.1 deduped
  | |   | |   +-- getpass@0.1.7
  | |   | |   | `-- assert-plus@1.0.0 deduped
  | |   | |   +-- jsbn@0.1.1
  | |   | |   `-- tweetnacl@0.14.5
  | |   | +-- is-typedarray@1.0.0
  | |   | +-- isstream@0.1.2
  | |   | +-- json-stringify-safe@5.0.1
  | |   | +-- mime-types@2.1.17
  | |   | | `-- mime-db@1.30.0
  | |   | +-- oauth-sign@0.8.2
  | |   | +-- performance-now@2.1.0
  | |   | +-- qs@6.5.1
  | |   | +-- safe-buffer@5.1.1 deduped
  | |   | +-- stringstream@0.0.5
  | |   | +-- tough-cookie@2.3.3
  | |   | | `-- punycode@1.4.1
  | |   | +-- tunnel-agent@0.6.0
  | |   | | `-- safe-buffer@5.1.1 deduped
  | |   | `-- uuid@3.1.0
  | |   +-- valid-data-url@0.1.4
  | |   `-- xtend@4.0.1
  | +-- lodash@4.17.4 deduped
  | +-- mjml-validator@3.3.5
  | | +-- lodash@4.17.4 deduped
  | | `-- warning@3.0.0 deduped
  | +-- react@15.6.2 deduped
  | +-- react-dom@15.6.2
  | | +-- fbjs@0.8.16 deduped
  | | +-- loose-envify@1.3.1 deduped
  | | +-- object-assign@4.1.1 deduped
  | | `-- prop-types@15.6.0 deduped
  | `-- warning@3.0.0
  |   `-- loose-envify@1.3.1 deduped
  +-- mjml-divider@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-group@3.3.5
  | +-- classnames@2.2.5 deduped
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-head-attributes@3.3.5
  | `-- lodash@4.17.4 deduped
  +-- mjml-head-font@3.3.5
  | `-- lodash@4.17.4 deduped
  +-- mjml-head-preview@3.3.5
  +-- mjml-head-style@3.3.5
  +-- mjml-head-title@3.3.5
  +-- mjml-hero@3.3.5
  | +-- classnames@2.2.5 deduped
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-html@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-image@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-invoice@3.3.5
  | +-- he@1.1.1 deduped
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | +-- mjml-table@3.3.5 deduped
  | +-- numeral@2.0.6
  | `-- react@15.6.2 deduped
  +-- mjml-list@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-location@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | +-- mjml-image@3.3.5 deduped
  | +-- mjml-text@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-navbar@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | +-- mjml-section@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-raw@3.3.5
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-section@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-social@3.3.5
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-spacer@3.3.5
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-table@3.3.5
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  +-- mjml-text@3.3.5
  | +-- classnames@2.2.5 deduped
  | +-- lodash@4.17.4 deduped
  | +-- mjml-core@3.3.5 deduped
  | `-- react@15.6.2 deduped
  `-- mjml-wrapper@3.3.5
    +-- lodash@4.17.4 deduped
    +-- mjml-core@3.3.5 deduped
    +-- mjml-section@3.3.5 deduped
    `-- react@15.6.2 deduped

**Comment by iRyusa** [comment]
Local install looks ok, can you ensure you're not using a global older install with `mjml -V`?

**Comment by Omazon** [comment]
Oh my God, I have installed the version 3.3.2, then what I can do to have the latest version?, always use the npm install mjml command in each project.

![imagen](https://user-images.githubusercontent.com/22031788/31517883-88c25c42-af5a-11e7-9482-bac631f124aa.png)

**Comment by iRyusa** [comment]
Well you can either update it globally with `npm install mjml -G` or use the local mjml with `node_modules\.bin\mjml` !

**Comment by Omazon** [comment]
its works :) thanks for all pal
