### ISSUE TITLE
Display inline block feature. Ref: Display image inline block #223

### ISSUE THREAD

**Issue by ijagbemi2313** [mjmlio/mjml#839]
Will like to know if there is a proper support now for displaying mj-image in an inline format.

**Comment by iRyusa** [comment]
Hi @ijagbemi2313 

As described in #223 there's some way to do it in MJML/HTML. But this isn't the purpose of `mj-image`, so you should stick with the `img` inside a `mj-text` or `mj-table` method.

**Comment by fatihdurgut01** [comment]
@iRyusa piece of shit, I need to use all css properties, before april 24. GO FIX THIS SHIT
