### ISSUE TITLE
Google link in social component

### ISSUE THREAD

**Issue by simonwoodhead** [mjmlio/mjml#84]
Setting google="false" does not remove the google link in the social component.

**Comment by arnaudbreton** [comment]
Hey @simonwoodhead thanks for reporting. We'll have a look at it shortly and come back to you once we found what's going wrong here. 

Keep you posted!

**Comment by GuillaumeBadi** [comment]
Hey @simonwoodhead !

The syntax has been replaced by a simplest one : instead of `google="false" facebook="true"`, you can do `display="facebook"`
