### ISSUE TITLE
mj-image not center in sfr.fr with chrome

### ISSUE THREAD

**Issue by BastienOyst** [mjmlio/mjml#841]
Hi,

All the images are on the left side with the email box sfr.fr in chrome browser.

The code: https://mjml.io/try-it-live/SkTsvYN6Z

This is what i get:
![screen](https://user-images.githubusercontent.com/28706634/31707023-461a801e-b3eb-11e7-853c-adc61ae70d46.png)

**Comment by BillyB0y** [comment]
Hello team, any answer ?
Same problem in outlook windows !
Need a FIX plz

**Comment by ngarnier** [comment]
Hello, 

After doing some digging, it seems adding `margin: 0px auto` on the parent `table` of the `img` tag fixes SFR on Chrome. Here is an example using `mj-style` and `css-class`: https://mjml.io/try-it-live/r1maodTZf 

We might need to add this to the default output. 

About Outlook, it's a different issue and it might be related to the actual size of the images being too large (in which case Outlook won't respect the `width` you specify with CSS), can you create another issue and share a template where you have the issue please @BillyB0y?

**Comment by iRyusa** [comment]
I don't think we'll have a proper fix about this one, for unkown reasons SFR is removing the `align` attribute on table
