### ISSUE TITLE
mj-include relative to file?

### ISSUE THREAD

**Issue by ogonkov** [mjmlio/mjml#842]
Seems that `mj-include` is resolved from folder where is build was started.

So, if i have structure like:
```
project
`-- emails
    |-- email-example
    |   |-- _include.mjml
    |   `-- tpl-with-include.mjml
    `-- gulpfile.js
```
If i will use `<mj-include path="./_include.mjml" />`, this will tired to resolve `_include.mjml` inside `emails` folder instead `emails/email-example`.

`gulpfile` example:
```js
import gulp from 'gulp';
import mjml from 'gulp-mjml';

gulp.task('build', function() {
  gulp.src([
    path.normalize(path.join('emails', '**/*.mjml')),
    path.normalize(path.join('!emails', '**/_*.mjml'))
  ])
  .pipe(mjml())
  .pipe(
    gulp.dest(path.normalize('templates'))
  );
});
```

Looks like it should be some kind of `cwd` somewhere? To be honest it's not very obvious, and looks more like API flaw/bug.
Or i just use it wrong?..

**Comment by iRyusa** [comment]
Hi

This is more an `gulp-mjml` issue that has been fixed but the new version hasn't been published on NPM yet. There's a special `filePath` option to pass to let the engine know what's the entry point.

I'll see if I can release `gulp-mjml` today

**Comment by ogonkov** [comment]
@iRyusa thanks! Looking forward for it
