### ISSUE TITLE
Possibility to output inline elements with fluid width

### ISSUE THREAD

**Issue by evenfrost** [mjmlio/mjml#843]
Hi, I'd like to know is there any possibility to output elements (e.g. `mj-button`) in row like you do in common HTML with `inline` and `inline-block` display values. I failed to make it with `mj-column`/`mj-table` elements, but, maybe, `mj-raw` could fit here.

Such thing could be suitable e.g. for labels ([example](https://semantic-ui.com/elements/label.html#groups)).

**Comment by iRyusa** [comment]
Hi @evenfrost 

The best way to do "inline/inline-block" is to play with `mj-table indeed. As you can't put mj-element inside an mj-table you have to tweak the HTML in the mj-table directly.

There's several way to achieve this too, it depends on clients you want to support. Some people having good results by nesting section/column into column but we didn't test it out so it can lead to many issue on clients

You can still share the design you want to achieve, people are very creative in MJML's slack ! Feel free to join us :) https://slack.mjml.io

**Comment by evenfrost** [comment]
Yeah, you could partly do this with table/column, though it would stretch to 100% width of the container and add big gaps between elements. Thanks for reference, Slack seems to be a better place for questions indeed.

**Comment by evenfrost** [comment]
For reference: this should do the trick for now: https://mjml.io/try-it-live/Sk1yhCNpZ.

**Comment by dalefish** [comment]
That padding won't hold in word based outlooks

[image: Inline images 1]

Kind Regards,

:----------------------------:
Dale McConnell
