### ISSUE TITLE
`options` are missing from documentation

### ISSUE THREAD

**Issue by evenfrost** [mjmlio/mjml#845]
Hi,
I've just faced the issue with missing `mj-include` file and noticed a [bunch](https://github.com/mjmlio/mjml/issues/807) [of](https://github.com/mjmlio/mjml/issues/842) [similar](https://github.com/mjmlio/mjml/issues/542) issues, which pointed me to second `options` argument of `mjml2html` method found in source code. It would be great if a list with all available `options` was in [Inside Node.js](https://github.com/mjmlio/mjml#inside-nodejs) section. I believe it could help developers and reduce a number of related issues.

**Comment by iRyusa** [comment]
Hi !

I totally agree with you 👍 
We'll see what we can do for the MJML4 release

**Comment by ngarnier** [comment]
Engine and CLI `options` are now documented in the [readme](https://github.com/mjmlio/mjml#inside-nodejs) so I'm closing!
