### ISSUE TITLE
Office 365 and Outlook.com desktop clients: prevent mj-column fallback to mobile view 

### ISSUE THREAD

**Issue by tolusonaike** [mjmlio/mjml#849]
Is there a way to prevent **mj-column** from falling back to mobile stack-columns on office 365 and outlook desktop clients?

**Comment by tolusonaike** [comment]
After some more research, since office 365 and outlook.com do not support media queries, `.mj-column-per-50` defaults to the in-lined 100% width (as expected for mobile first fallback)  and, for some reason, the 300px width on the parent table is not being respected

![screenshot at oct 21 15-26-18](https://user-images.githubusercontent.com/253270/31855845-fd5e57e8-b678-11e7-8b10-885b4c98fa39.png)

I was able to target this class for only OWA by using 

```
[owa] .owa-responsive-hack {
      width: 50% !important;
}
```
and adding `css-class="owa-responsive-hack"` to responsive columns

**Comment by iRyusa** [comment]
Hi ! 

Those outlook comments are only applied on desktop outlook not on outlook.com/365

I'm closing this issue then :)

**Comment by tolusonaike** [comment]
@iRyusa here are my email on acid results: before and after
![screen shot 2017-10-22 at 8 51 09 am](https://user-images.githubusercontent.com/253270/31862605-6ce62932-b706-11e7-9539-3b8f21397ed7.png)

**Comment by iRyusa** [comment]
Yep ! 

We're aware of that, we're looking to provide a attribute that does the same thing on MJML4, but this is creating a new issue as it will display the desktop version on mobile outlook.com too.

**Comment by tolusonaike** [comment]
@iRyusa i considered the effect on mobile as well and it was a trade-off i was willing to make  (but i am sure outlook mobile probably screws this up more than adding a horizontal scroll!)

BTW, mjml is a life saver!
