### ISSUE TITLE
Can I pass props or a payload?

### ISSUE THREAD

**Issue by sconno05** [mjmlio/mjml#85]
Is it possible to pass a payload or props to my mjml?

`<mj-text color="#EEE" font-size="18px">{orderCount} orders processed today</mj-text>`

paired with something like:

`var htmlOutput = mjml.mjml2html(mjml, {orderCount: 20});`

I have not seen anything in the docs where I can do this.

**Comment by GuillaumeBadi** [comment]
Hey @sconno05 !

This is not a feature we have implemented as Handlebars would already do the job pretty well. You could compile your mjml, then render your handlebars tags with libraries like mu2 for instance
