### ISSUE TITLE
mjml-social instagram icon is cut-off

### ISSUE THREAD

**Issue by mikelambert** [mjmlio/mjml#851]
I'm using `mjml-social`, but it seems the instagram icon is missing its top-half: https://www.mailjet.com/images/theme/v1/icons/ico-social/instagram.png

(I'm not sure where to file a bug on mailjet stuff, but this does seem to be a bug in the `mjml-social` implementation, so I'm reporting it here)

**Comment by ngarnier** [comment]
Hey @mikelambert, the logo isn't cut, it's just transparent on the top half according to the (old) logo. You can see it here: https://mjml.io/try-it-live/HJ96rDkRZ 

However, we need to update the logo for sure (see #611). In the meantime, you can easily add your own social media icon like this: https://mjml.io/try-it-live/HJsvLvJ0W
