### ISSUE TITLE
Carousel render flashing issue

### ISSUE THREAD

**Issue by muxica** [mjmlio/mjml#853]
Hi, I found that if your images are not the same dimensions, the thumbnail hover functionality begins 
rapidly flashing. This is because of a resize that is happening in the carousel image that renders causing the mouse to temporarily not be in the thumbnail box. 

![flashing issue](https://user-images.githubusercontent.com/6655502/31908177-11539c86-b804-11e7-9745-e6cff4f79b13.gif)

**Comment by iRyusa** [comment]
Hi @muxica 

Due to the nature of limited support on webmail (eg no JS/limited css attribute)
 I don't think we can do anything for this, but can you share your carousel so we can take a look if we can fix it ?

**Comment by iRyusa** [comment]
Well I'm closing the issue, as we're limited on MJML side for this, if you can share the mjml we'll reopen to see what we can do
