### ISSUE TITLE
mj-column padding

### ISSUE THREAD

**Issue by vielhuber** [mjmlio/mjml#856]
Hello!

I like resetting the padding for all elements like this:
`<mj-all padding="0" />`
This also removes the padding inside `<mj-column>`.

Officially `<mj-column>` does not support paddings.

What to do if I have a layout where in the left column I have a big image (without padding)
and in the right column I have several elements with a padding around?

**Comment by iRyusa** [comment]
Hi, 

I don't really understand your issue, reseting the padding on all element doesn't prevent you to overide the padding on a single element ?

**Comment by vielhuber** [comment]
Sorry, the tags got stripped out from the original question. Please reread.

**Comment by iRyusa** [comment]
You'll have to manually set a padding in each elements of column, padding in column is a new feature for MJML4 to create gutter around the column cf #160

**Comment by vielhuber** [comment]
Thank you! And thanks for your awesome work.
