### ISSUE TITLE
mjml-include can't trigger Webpack hot reload

### ISSUE THREAD

**Issue by monochrome-yeh** [mjmlio/mjml#857]
Does anyone know how it work on webpack HMR mode?
`mjml-include` file can't trigger hot reload(or full reload) when sub-template get changed.

- Entry `app.js`
```js
import parent from 'parent'
if (module.hot) {
	module.hot.accept();
}

const iframe = document.createElement('iframe')
iframe.srcdoc = parent
document.body.appendChild(iframe)
```

- parent.mjml
```html
<mjml>
  <mj-body>
    <mj-container>
      <mj-include path="child" />
    </mj-container>
  </mj-body>
</mjml>
```

- child.mjml
```html
<mj-section background-color="#ffffff">
<mj-column>
  <mj-text font-style="italic" font-size="20" color="#626262">
    Child
  </mj-text>
</mj-column>
</mj-section>
```

whenever I modify `parent`, it works with HMR, but when I modify `child`, it doesn't work.

**Comment by iRyusa** [comment]
Hi @monochrome-yeh

Well I think you'll need a specific MJML plugin/loader/..? to support mj-include relationship between childs and parent.

**Comment by monochrome-yeh** [comment]
Hello @iRyusa,
yes I've already used https://www.npmjs.com/package/mjml-with-images-loader to solve loader issue.
However, it doesn't work for `ng-include`, I might need to figure out how it works.

Also, I'll try https://www.npmjs.com/package/mjml-loader later.

**Comment by monochrome-yeh** [comment]
it doesn't work either. (https://www.npmjs.com/package/mjml-loader)

**Comment by monochrome-yeh** [comment]
`mjml` will cache file of `ng-include`, both `loaders` have to manually restart `webpack` (refresh couldn't get the newest modification), it's bad to develop.

**Comment by nodkz** [comment]
@monochrome-yeh very strange cause `mjml-with-images-loader` worked with `mj-include` in my app with webpack 3.x. 
https://github.com/nodkz/mjml-with-images-loader/blob/master/index.js#L91

It may not work if you provide an incorrect path for include. In my case, it worked when I provide a relative path from ROOT folder of project. Something like
```
<mj-include path="./src/mailer/_shared/header.mjml" />
```

**Comment by monochrome-yeh** [comment]
@nodkz , good point, I found the issue who cause this situation.

these doesn't work as below:
```html
<mj-include path="src/views/vehicles/child" />
<mj-include path="./src/views/vehicles/child" />
```

this is working as below:
```html
<mj-include path="./src/views/vehicles/child.mjml" />
```

I think the issue that have 2 points need to concern:
- mjml not really work for webpack, so it isn't able to know waht `ext` is.
- the path is from mjml itself after webpack compiled, therefore you couldn't directly to use what file path from webpack structure.

**Comment by monochrome-yeh** [comment]
Also, unfortunately it only works with full-reload, not hot-reload.

**Comment by monochrome-yeh** [comment]
### Update
it's a extended issue,

reload it'll hot-reload first than full-reload again.

hope someone could fix it.

**Comment by iRyusa** [comment]
For mj-include to works you might need to make the plugin pass the filePath option to mjml2html so include will be relative to file.

**Comment by iRyusa** [comment]
So, as MJML webpack loader is a community project, I'm closing the issue because we can't do anything on that, feel free to open an issue on related repositories
