### ISSUE TITLE
max-width property really useful for mj-image?

### ISSUE THREAD

**Issue by epayet** [mjmlio/mjml#86]
mj-image sets by default the css property `max-width` : 

```javascript
getStyles() {
    const { mjAttribute } = this.props

    return _.merge({}, this.constructor.baseStyles, {
      img: {
        border: mjAttribute('border'),
// Here
        maxWidth: this.getContentWidth(),
        height: mjAttribute('height')
      }
    })
  }
```

I have a case where it is much better looking on mobile without this property.

Here is the mobile version, the first image is the MjImage component without max-width, and the second one is the default MjImage component:

![mobile](https://gist.githubusercontent.com/epayet/fa058ac45dd748e5c6e0/raw/1e5d5694857cc2ee7cc45b9772d2b18ab6491df7/mj-image-max-width-mobile2.png)

And here is the desktop version unaffected:

![desktop](https://gist.githubusercontent.com/epayet/fa058ac45dd748e5c6e0/raw/b157c81f27e72ab3e479af5266eba860aaa97a90/mj-image-max-width-desktop.png)

So in my case, I prefer the version without max-width. There is too much white space on the default one. Is this an expected behaviour? Should we have this optional? What are your thoughts on that? thanks

**Comment by iRyusa** [comment]
Hi @epayet,

Did you try to set `padding="0"` on your `mj-image` ? Because `max-width` is computed as such: 
`min(columnWidth/widthAttr) - paddingLeft - paddingRight)` in order to avoid a column overflow.

**Comment by epayet** [comment]
I tried, in the example above, I am using `padding="10px"`, changing it to `padding="0"` just gave me 20px more, but still does not look like I want it to (the first tile) :disappointed: 

Here is what I changed to have the first tile on MjImage:

```javascript
getStyles() {
    const { mjAttribute } = this.props

    // Removed max-width property
    return _.merge({}, this.constructor.baseStyles, {
      img: {
        border: mjAttribute('border'),
        // removed this
        //maxWidth: this.getContentWidth(),
        height: mjAttribute('height')
      }
    })
  }
```

and

```javascript
renderImage() {
    const { mjAttribute } = this.props

    // Changed here
    const img = (
      <img
        alt={mjAttribute('alt')}
        border="0"
        src={mjAttribute('src')}
        style={this.styles.img}
        // instead of width={this.styles.img.maxWidth}
        width={this.getContentWidth()}
        height={this.styles.img.height} />
    )
...
```

**Comment by iRyusa** [comment]
Can you give me the mjml that you use to generate this example ?

I think removing `max-width` can have a side effect on iOS, I believe that's why this it's like this. 

However, I wonder if the bug I had on iOs wasn't related to column unit (`px` rather than `%`)... I have to test it.

**Comment by epayet** [comment]
Here is the code I am using, very simple:

```html
<mj-section padding="0px">
    <mj-column>
        <mj-custom-image src="http://media02.hongkiat.com/keep-calm-designer-posters/keep-calm-and-lorem-ipsum.jpg" padding-left="10px" padding-right="10px"/>
    </mj-column>

    <mj-column>
        <mj-image src="http://media02.hongkiat.com/keep-calm-designer-posters/keep-calm-and-lorem-ipsum.jpg" padding-left="10px" padding-right="10px"/>
    </mj-column>
</mj-section>
```

The `<mj-custom-image/>` being a copy paste from MjImage component with the changes I talked about before. Changing the padding did not affect much the result

**Comment by iRyusa** [comment]
In the next `1.3`, `max-width` will be removed. 

We need to keep an eye on `mj-image` after `1.3` release to see if there's some regressions on it !

Thanks for investigating @epayet !

**Comment by kelvinaero** [comment]
On your example site https://mjml.io/try-it-live/racoon everything looks good, when we copy your template mjml and render on our local machine, the images render with the same value as the % of the columns, but in pixels. What is wrong?
![screen shot 2016-03-16 at 11 25 00 am 3](https://cloud.githubusercontent.com/assets/9321587/13817941/80359770-eb6a-11e5-8d22-cf06d970f501.png)

**Comment by iRyusa** [comment]
Hi !

What version of MJML are you using ?

**Comment by kelvinaero** [comment]
Hello iRyusa the mjml version is 1.2.1

We are also using gulp-mjml 1.0.0

**Comment by kelvinaero** [comment]
Hello. When is your team going to roll 1.3 out?

**Comment by iRyusa** [comment]
@kelvinaero today ;)
Should be ok in `1.3` @epayet feel free to re-open if anything break
