### ISSUE TITLE
Output text email 

### ISSUE THREAD

**Issue by mrcasablr** [mjmlio/mjml#862]
Just discovered this and it makes life easier dealing with email templates
Is it possible to also generate a text only content along with HTML for edge cases where HTML rendering is disabled?

**Comment by ogonkov** [comment]
I think it's up to implementation of MJML templates

We use `html2text` from pip to postprocess generated templates to build text part for Django mailer.

**Comment by iRyusa** [comment]
Hey @mrcasablr 
This has been already discussed (here: https://github.com/mjmlio/mjml/issues/199) and we came to the conclusion that's not the role of mjml as @ogonkov said, there's some lib that can do that work for you
