### ISSUE TITLE
Parse error on '<' exist not in tag part of code

### ISSUE THREAD

**Issue by Satariall** [mjmlio/mjml#863]
At first, big thanks of your working on mjml! It's amazing framework for mails. We opened it now and will use them all our future! It's perfect!

But I got issue when i create a lot of templates with already saved template codes (from IPS4 platform).

Here is some examples.
Good parse:
![good-parse](https://user-images.githubusercontent.com/1109787/32217111-0e73a6d4-be38-11e7-8da4-751d9d28f69a.png)

Parsing error:
![error-parse](https://user-images.githubusercontent.com/1109787/32217155-2aab2dea-be38-11e7-9755-a26eee5e61ab.png)

Thanks for you!

**Comment by Satariall** [comment]
Easy temporary solution - just change varibales order 
![err-fixed](https://user-images.githubusercontent.com/1109787/32217525-4da71434-be39-11e7-9ddd-6710dca605d1.png)

**Comment by iRyusa** [comment]
Hi @Satariall 

I think this is due to the engine think that you're opening a tag. Simple fix for that is to encode the `<` in HTML in `&lt;`

**Comment by Satariall** [comment]
Hi @iRyusa. Thanks for the answer! But i can't change this symbol to &lt;. Because after mjml template generation it will transfer to the second generator part, which do additional logic. Content in { } or {{ }} must be executable for this generator. With &lt; it will be as incorrect part or not compilable text.

I didn't know best solution for fix that situation. I am just notify about that not good thing (and for search for other people). If somebody can dream good way for that - it will be cool. If not.. Ok. We'll just know about that.

Thanks.

**Comment by rogierslag** [comment]
It might be easier to switch the order. First apply the logic to add data and conditionals to the template, and pass the resulting mjml to the cli

**Comment by Satariall** [comment]
@rogierslag in that order we need compile mjml at every time on mail need to send. We send very much mails and that way isn't good. Moreover, we need to install mjml on the server (on each cluster nodes), support, monitore and operate them. Realy hard way. Better way is create in any hand work one time in mjml app and get the result as a template for futher mailings.
Thanks for you care :)

**Comment by rogierslag** [comment]
We had the same problem, and build [maily](https://github.com/inventid/maily) to handle it for us. You can use it as well. I also made some [blogs about it](https://medium.com/@Rogier.Slag/creating-emails-with-the-maily-api-a-how-to-part-1-7f63306a7ad4)

**Comment by iRyusa** [comment]
@Satariall did you tried it because it will be decoded as `<` in the output html ?

**Comment by Satariall** [comment]
@iRyusa i understand you. Thanks. Tried it and yes, you right. Output HTML from MJML App for `&lt;` is decoded `<` symbol. I not tried that before (sorry) because i think mjml must not convert encoded symbols to the real.

**Comment by iRyusa** [comment]
Yes, I think it won't happens anymore in MJML4. So I can close this issue
