### ISSUE TITLE
Change file extension for multiple files with cli

### ISSUE THREAD

**Issue by windows1087** [mjmlio/mjml#866]
I want to parse multiple files with the mjml cli, and rename there extension:

```
mjml ./src/assets/mails/templates/*.mjml -o ./src/assets/mails/compiled/*.blade.php
```

But he gives me this error `Output destination should be a directory instead of a file`. If i change the output to only the folder `./src/assets/mails/compiled` he places me the correct files, but only with `.html`.

**Comment by iRyusa** [comment]
Hi @windows1087 

Can you try to rename your file like this : `.mjml.blade.php` it should remove the `.mjml` in the output if you give a directory

**Comment by windows1087** [comment]
Oh nice, thank you! :)
