### ISSUE TITLE
mj-section interprets every child as column for applying the width

### ISSUE THREAD

**Issue by toyflish** [mjmlio/mjml#868]
I try to have a two row layout with mj-section and two mj-column nested
```
      <mj-section>
        <mj-raw>{% some twig code here %}</mj-raw>
        <mj-column>....</mj-column>
        <mj-raw>{% some twig code here %}</mj-raw>
        <mj-column>....</mj-column>
      </mj-section>
```

but mjml renders out two columns with 25% width, after investigation I found out it renders 33% columns if I remove one mj-raw. Seems mj-section just counts all children to figure out their width and not only mj-columns.

**Comment by iRyusa** [comment]
Hi @toyflish 

Quick fix is to manually set the width of the column. Column auto sizing is based on how many sibling a columns have (here 4) so it will renders as 25%
