### ISSUE TITLE
Components without Javascript - Imports ? 

### ISSUE THREAD

**Issue by techdragon** [mjmlio/mjml#87]
MJML seems great and all, but it kind of defeats the purpose of 'simplifying things'... to suddenly burden myself with writing javascript files, running node... all this stuff... 

Using 'vanilla' MJML is brain dead simple. so why do custom components have to make it twice as complicated? 

Can we get some sort of import mechanism... I like how simple MJML is without having to write my own build toolchain in javascript to use it.

**Comment by epayet** [comment]
I am currently working on a starter kit to simplify these things with a toolchain already done and automated. But I do get your point

**Comment by arnaudbreton** [comment]
Hey @techdragon, thanks for sharing. That's definitely something we'll want to add in a near future. 
If you have a clear idea on how you would like this to be implemented, feel free to describe in more details here so we can kick-off the discussion with other users.

@epayet glad to hear you're working around an MJML toolchain, can't wait to see that in action! Feel free to drop us a line at hi@mjml.io to tell us more.

Cheers

**Comment by techdragon** [comment]
@arnaudbreton I think `<mj-import src='./my-component.js'></mj-import> might be the easiest way to deal with the markup, as for the implementation details under the hood, I'll defer to more knowledgeable react developers on that part.

**Comment by arnaudbreton** [comment]
@techdragon thanks for the feedback. Let push the discussion in #120 to avoid duplicates. Thanks for sharing!
