### ISSUE TITLE
Yargs does not accept type: 'object'

### ISSUE THREAD

**Issue by dhcdata** [mjmlio/mjml#871]
[`mjml-cli/client.js L57-61`](https://github.com/mjmlio/mjml/blob/eebbbbe3f274f430535af7d1082570ce483e6a03/packages/mjml-cli/src/client.js#L57)
```
    c: {
      alias: 'config',
      type: 'object',
      describe: 'Option to pass to mjml-core',
    },
```

type: 'object' is not a valid [`yargs option type`](http://yargs.js.org/docs/#api-optionkey-opt). Must be one of:
```
'array': synonymous for array: true, see array()
'boolean': synonymous for boolean: true, see boolean()
'count': synonymous for count: true, see count()
'number': synonymous for number: true, see number()
'string': synonymous for string: true, see string()
```

Probably need to utilize the [`coerce`](http://yargs.js.org/docs/#api-coercekey-fn) API function. I don't have enough experience with `yargs` to be sure this is the easiest approach.

**Comment by iRyusa** [comment]
Hi @dhcdata 

Oh, right. But there's already an object parser built-in in yargs, so `--config.beautify false` will works as expected. Nice catch

**Comment by dhcdata** [comment]
Thanks, @iRyusa . I wasn't aware of the `--config.beautify` syntax.  Good to know. 

I ran into this with #870 in wanting to pass command line variable to a replacement template. I don't have a real world use case yet, but I imagine using the -`-config.beautify` could get quite hairy with nested objects.
