### ISSUE TITLE
Using mj-spacer outside of mj-column

### ISSUE THREAD

**Issue by sedlar** [mjmlio/mjml#876]
Cli compiler (version 3.3.5) reports warning that mj-spacer can't be used outside mj-column or mj-hero-content. However I haven't found this information anywhere in documentation.
```
Line 22 (mj-spacer) — mj-spacer cannot be used inside mj-container, only inside: mj-column, mj-hero-content
```

It seems there is either redundant warning or incomplete documentation.

Mjml code snippet to reproduce:
```mjml
<mjml>
<mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>test</mj-text>
        </mj-column>
      </mj-section>
      <mj-spacer>
      <mj-section>
        <mj-column>
          <mj-text>test</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hi @sedlar 
As the cli said, yes you shouldn't use mj-spacer outisde of `mj-column, mj-hero-content`.

Well, it's not specified explicitly on the doc but the example clearly shows that it lives inside a `mj-column` like every components `text/button/...` would.

Should we start to list where every component can be used or does the example context is enough ?

Doesn't padding top/bottom on a section would be a better approach in this case ?

**Comment by sedlar** [comment]
@iRyusa 
Given every mj-element is used within mj-column in documentation example, it would be helpful to put a sentence that all elements (possibly list of elements, if it doesn't hold for all) should be used within mj-column. There is probably no need to list it for each element separately.

Actually padding top/bottom doesn't help here, since background color of document is different from section background color (I have stripped the example to contain minimal code to reproduce the issue).

Full mjml template can be found here https://mjml.io/try-it-live/rylwPOe1f

**Comment by iRyusa** [comment]
I'll see then, for compatibility you should add a section with a column. 
We thought it would be clear with example, we'll see what we can do to reflect that in the doc for the MJML 4 release

👍

**Comment by kud** [comment]
I've got a question about that.

Why we should have a `mj-column` when we've got only one "column" there? like for instance I've got:

```
<mj-section>
  <mj-text></mj-text>
</mj-section
```

I did that, it works, but I also see that some components like `mj-divider` without any `mj-column` work but not so well (like missing padding).

`mj-column` seems to be mandatory for some components, even if we have only one column. Is it normal?

**Comment by ngarnier** [comment]
Just consider that you always need a content tag (like `text`, `image`, `button`...) to be inside a `column`, including when you only have one column. It's part of the MJML syntax and structure, as `mj-column` renders HTML markup needed for children elements (that isn't rendered by `mj-section`).

As you said, it might work sometimes and not other times (especially with padding), so avoid any issue by making sure you always put your content inside a `column` tag.

**Comment by iRyusa** [comment]
Well, we want to avoid "magic rules" that you need to remind every time you build a template. s-So to keep it simple, we ensure that the section will behave the same with 1/2/3/4/... columns inside it.

**Comment by ngarnier** [comment]
About the documentation, you're right, it would be helpful to mention explicitly that `mj-column` is always needed. The question is: where? 

As said above in the issue, it would probably be too much to mention it for each component. Maybe as an introduction in https://mjml.io/documentation/#standard-body-components? 

FYI, we also plan to revamp the doc to remove the unnecessary stuff and make it easier to get started with the syntax, so we'll keep that in mind.

Feel free to make any suggestion!

**Comment by ngarnier** [comment]
Taking good note for our doc update and closing.
