### ISSUE TITLE
Stacking columns on mobile

### ISSUE THREAD

**Issue by ketschi-max** [mjmlio/mjml#878]
Hello everyone,

Is it possible to change the stacking order of the columns in the MJML framework. For example I have in my template the following structure:

"image""text"
"text""image"
"image""text"

I would like to structure it on mobile so that it is always "image" first and then "text". Is this possible?

**Comment by iRyusa** [comment]
Hi @ketschi-max 

You can do it with the `direction` attribute on `section`, you can find the usecase here : https://medium.com/mjml-making-responsive-email-easy/mjml-reaches-another-level-with-the-release-of-v3-945d0d988d97#6d77

**Comment by ketschi-max** [comment]
Hi @iRyusa 

Thank you for your quick reply, works like a charm!
