### ISSUE TITLE
Mjml API rest client Java library. 

### ISSUE THREAD

**Issue by atrujillofalcon** [mjmlio/mjml#882]
I would like to contribute to the mjml community by creating a java library to use the mjml API.  I think this is important because the Java developer community is huge.

I created this project in:

[https://github.com/atrujillofalcon/mjml-rest-client](https://github.com/atrujillofalcon/mjml-rest-client)

**Comment by ngarnier** [comment]
Hey @atrujillofalcon, thanks a lot for sharing! 

We'll add it on https://mjml.io/community 

I'm closing the issue and adding this in our todo :)
