### ISSUE TITLE
-bash: mjml: command not found

### ISSUE THREAD

**Issue by ssosina** [mjmlio/mjml#885]
So I'm following the MJML documentation for basic installation. I successfully install.  I run npm list in my project folder and MJML appears there.

However, when I run `mjml -v` the following error appears
`-bash: mjml: command not found`

Terminal output for when I run **which Node**
`/usr/local/bin/node`

Content of my .bashrc is empty at the moment. I previously added `export PATH="$PATH:./node_modules/.bin"` but this made no difference. 

Using a Macbook air, High Sierra and Terminal.

**Comment by iRyusa** [comment]
Hi @ssosina 

Weird, looks like a path issue. If you do a `./node_modules/.bin mjml -V` what does it return ?

**Comment by ssosina** [comment]
Thanks for the quick reply. 

This is what I get
`-bash: ./node_modules/.bin: No such file or directory`

I uninstalled and attempted to reinstall. It doesn't load the node module files into the folder :/

**Comment by iRyusa** [comment]
Well did you done a folder like `workspace` and `npm init` inside it ? 

Then you can do an `npm install mjml` and it should work in this folder.

**Comment by ssosina** [comment]
Thats the first thing I usally do. 

1. Created new folder on desktop t`est-email`
2. Ran `npm init`
3.  Ran `npm install mjml`
4. Ran `npm list` – I can see mjml and all it dependencies.
5. I can node modules folder now
6. Ran `mjml -v` result is `-bash: mjml: command not found`
7. Ran **./node_modules/.bin mjml -V** result is `-bash: ./node_modules/.bin: is a directory`

Do I create .bash_profile or .bashrc on my platform?

**Comment by iRyusa** [comment]
You're missing a `/` in /node_modules/.bin/mjml

Can you `echo $PATH` too to check if the PATH is ok ?

**Comment by ssosina** [comment]
I should have picked up on that. 

Right it shows the version now –
```
Locals-MacBook-Air:test-email user$ ./node_modules/.bin/mjml -V
3.3.5
```
This is what I get when i get echo the path:
```
Locals-MacBook-Air:test-email user$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by iRyusa** [comment]
I think it's a `.bash_profile` in OSX but I'm not 100% sure about it

**Comment by ssosina** [comment]
@iRyusa Hmm. I added it to a bash_profile instead. even tried with bashr yet no difference. 

check this out.
```
Locals-MacBook-Air:test-email user$ mjml -v
-bash: mjml: command not found
Locals-MacBook-Air:test-email user$ ./node_modules/.bin/mjml -V
3.3.5
Locals-MacBook-Air:test-email user$ 
```

**Comment by iRyusa** [comment]
Can you `echo $PATH` again to see if the path is ok

I now advise to follow the `npm-exec` path like this https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules to avoid some kind of nasty package that could replace a common cmd line

**Comment by ssosina** [comment]
Sure – 

```
Locals-Air:test-email user$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:./node_modules/.bin
```

**Comment by iRyusa** [comment]
So 
```
$ pwd
$ ls
$ echo $PATH 
$ mjml -V
```
In order to double check everything ? :)

**Comment by ssosina** [comment]
```
Locals-Air:~ user$ cd desktop
Locals-Air:desktop user$ cd fs-email
Locals-Air:test-email user$ pwd
/Users/user/desktop/test-email
Locals-Air:test-email user$ ls
test.html		index.html	node_modules
test.mjml		index.mjml	package.json
Locals-Air:test-email user$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Locals-Air:test-email user$ mjml -v
-bash: mjml: command not found
Locals-Air:test-email user$ 


```

**Comment by iRyusa** [comment]
Yeah so your $PATH isn't updated, I don't know why it doesn't read your bashrc/bashprofile and there's not really much we can do about this :/ 

Sorry, but I'm closing the issue.

**Comment by TidyIQ** [comment]
Same issue here. Did you ever get this fixed?

**Comment by iRyusa** [comment]
If you've installed it locally just use `npm-exec mjml` or `yarn mjml` it's
now the safest way to use cli binary

**Comment by kostimarko** [comment]
I too had this issue. Running `mjml input.mjml -o output.html` doesn't work.

However, in my `package.json` adding a command like `"compile":"mjml input.mjml -o output.html"` works

**Comment by e10a** [comment]
@kostimarko this worked for me, thanks for this!

> However, in my package.json adding a command like "compile":"mjml input.mjml -o output.html" works

**Comment by sasha150187** [comment]
> I too had this issue. Running `mjml input.mjml -o output.html` doesn't work.
> 
> However, in my `package.json` adding a command like `"compile":"mjml input.mjml -o output.html"` works

Hello, Kosti. Can you tell where exactly you put this command in package.jason ?

**Comment by probablyabear** [comment]
@sasha150187 From what it sounds like, I have a similar setup to @kostimarko. Put the script in the `scripts` section of package.json.

It'd look something like this:


```
// package.json
...
"scripts": {
    "start": // some other script,
    "compile": mjml input.mjml -o output.html
}
...
```

**Comment by iRyusa** [comment]
Newer `npm` comes with `npx`, so you should be able to do `npx mjml` too

**Comment by kostimarko** [comment]
> @sasha150187 From what it sounds like, I have a similar setup to @kostimarko. Put the script in the `scripts` section of package.json.
> 
> It'd look something like this:
> 
> ```
> // package.json
> ...
> "scripts": {
>     "start": // some other script,
>     "compile": mjml input.mjml -o output.html
> }
> ...
> ```

@probablyabear you got to it before me :)
