### ISSUE TITLE
Outlook.com

### ISSUE THREAD

**Issue by NorthstarTech** [mjmlio/mjml#886]
I have the 2 columns including text and image. But it is not responsive on outlook desktop. It should show side by side instead of below each other vertically. How should I fix this? 
Thanks, Here is my code.
‹<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>Content 1
          </mj-text>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff"/>
        </mj-column>
        <mj-column>
          <mj-text>Content 2
          </mj-text>
          <mj-image src="http://placehold.it/350x250/78c5d6/fff"/>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>

**Comment by ngarnier** [comment]
Hey @NorthstarTech, this is a know issue, please have a look at [this comment](https://github.com/mjmlio/mjml/issues/717#issuecomment-308349095) (especially the part about Outlook.com). 

Note that in MJML 4, you have the option to change this behaviour and display the desktop layout on Outlook.com by adding `owa="desktop"` on the `mjml` root tag.
