### ISSUE TITLE
Fallback font

### ISSUE THREAD

**Issue by jojape** [mjmlio/mjml#889]
Hi dear MJML's developers,

I cannot see in the documentation anything related to the fallback font (in case the imported one doesn't work).
I'm editing the html file generated (based on the mjml template) adding a fallback font, but I wouldn't like to modify the html each time.

Thank you 👍

**Comment by iRyusa** [comment]
Hi @jojape 
`font-family` works totally as CSS font-family so you can provide the fallback. `font-family="Helvetica,Arial,..."`
