### ISSUE TITLE
Error : mjml is not a function

### ISSUE THREAD

**Issue by Zalasanjay** [mjmlio/mjml#890]
i am using this module as...

`const mjmlToHtml = require('mjml');
let emailTemplateHtml = mjmlToHtml(MY-MJML-CONTAINING-VARIABLE)`

**Comment by meriadec** [comment]
You have an example [in the README](https://github.com/mjmlio/mjml#inside-nodejs):

```
import { mjml2html } from 'mjml'

const output = mjml2html(YOUR_MJML_CONTAINING_VARIABLE)
```

As you don't use es2015 modules, you may want to do:

```
const { mjml2html } = require('mjml')
```

because you are currently using mjml as mjml2html.
