### ISSUE TITLE
srcset example

### ISSUE THREAD

**Issue by iManu** [mjmlio/mjml#891]
Hi,
Can you provide an example for `srcset` attribute for `mj-image`.
I have tested multiple ways, with no results.

**Comment by iRyusa** [comment]
Hi @iManu 
`srcset` isn't supported everywhere, but it does work like the HTML5 attribute in `img` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-srcset

**Comment by iRyusa** [comment]
Here the "supported" behavior (https://litmus.com/community/discussions/6152-srcset-and-sizes-in-email#comment-10373) described in this pr #716

**Comment by ngarnier** [comment]
About how to use, as @iRyusa said it's the same implementation of the HTML5 attribute in `img`, but here is an example width `320w` and `640w` widths, if you need it: https://mjml.io/try-it-live/HJTAiLEeM

However, as @iRyusa said too, the support is quite limited so it's normal if you don't see it used everywhere (especially in Gmail which removes the attribute).

**Comment by iManu** [comment]
Ha, I understand.
Big thanx !

**Comment by mmelon** [comment]
> About how to use, as @iRyusa said it's the same implementation of the HTML5 attribute in `img`, but here is an example width `320w` and `640w` widths, if you need it: https://mjml.io/try-it-live/HJTAiLEeM
> 
> However, as @iRyusa said too, the support is quite limited so it's normal if you don't see it used everywhere (especially in Gmail which removes the attribute).

what is this example supposed to do? I don't understand how srcset works without the sizes attribute
