### ISSUE TITLE
mj-container background-image/url

### ISSUE THREAD

**Issue by NorthstarTech** [mjmlio/mjml#894]
Want to add the background-image/background-url on mj-container. How should I place it?

**Comment by iRyusa** [comment]
Hi @NorthstarTech 

We don't support "full page" background image on the container. What you can do is add a mj-wrapper on multiple section like that https://mjml.io/try-it-live/B1NTuUYlG

**Comment by MarkSandora** [comment]
HI @iRyusa 
What about adding a link to a background image or an entire section? How would one go about that?

**Comment by kmcb777** [comment]
Hi @MarkSandora i'm not sure what you mean by "adding a link to a background image or an entire section" ?
Do you want to add a background image to a section ? Or a href link on an image ?

**Comment by prakhar625** [comment]
Hi @iRyusa thanks for the tip, on a separate note - how do I set the other style properties for the same background?

I don't want to repeat the image? trying to pass `style="background-repeat:no-repeat;"` as an attribute, but it's not getting applied.

Moreover, the background is semi-transparent, but it's getting applied twice in the DOM, so the effective opacity is double the required value. Can this be fixed anyhow?
