### ISSUE TITLE
mj-hero is missing href attribute

### ISSUE THREAD

**Issue by nickjl** [mjmlio/mjml#895]
Hi,

I think it would be useful for the mj-hero to have the href attribute added to it to make it fully clickable

Thanks

**Comment by iRyusa** [comment]
Hi @nickjl 

Well if we want to keep the support on Outlook Desktop, we can't add `href` into `mj-hero` : it's almost the same issue as fully clickable button, Outlook doesn't support nesting a `table` into an `a`.

Sorry, i'm closing the issue

**Comment by nickjl** [comment]
Hi @iRyusa,

Ahh ok, I understand that, would it not still be worthwhile tho if Outlook just ignores it without causing styling issues?

I've been hard coding around it with mj-raw and it works for all the other clients and then is just ignored on Outlook?

Thanks,
Nick

**Comment by iRyusa** [comment]
Well with `vml` in outlook, we never know.

And if any tag contains another `a` it could totally break the `mj-hero` so it would be hard for us to handle that case

**Comment by nickjl** [comment]
Hi @iRyusa 

Ahh ok, makes sense!

Cheers :)
