### ISSUE TITLE
mj-style in body to add styles to head

### ISSUE THREAD

**Issue by nickjl** [mjmlio/mjml#896]
Hi,

We're working on component based emails and feel it would be extremely useful to be able to add styles to the head (for gmail) from within mj-body (the reverse of how mj-preview works?). Do you think this is something you could please implement if possible?

Thanks,
Nick

**Comment by iRyusa** [comment]
Well component in MJML3 has access to `postRender` with a jquery like syntax (you can look at carousel/column to see how it works)

In MJML4 we're looking to add a function to add style (https://github.com/mjmlio/mjml/issues/880)

Is this what you're looking for ?

**Comment by nickjl** [comment]
Hi @iRyusa,

Yes it is, sorry didn't spot it in there before!

Thanks

**Comment by nickjl** [comment]
Hi @iRyusa, I just reread over this and not quite sure it was what I was looking for actually.

I meant to be able to use mj-style anywhere within mj-body, as it can currently only be used in mj-head.

For the custom component wishlist is that saying to be able to add to the head specifically from the js file instead of using an mj-style in the mjml file?

Cheers

**Comment by iRyusa** [comment]
Hey @nickjl 

Now that head style are supported almost everywhere why would you put an mj style inside a mj-body ?

**Comment by iRyusa** [comment]
Just reposting because I understand what you meant now, but I don't really see the advantage of getting mj-style in a middle of a template rather than grouping everything in the head ?

**Comment by nickjl** [comment]
Hey @iRyusa 

So in terms of our implementation, we use mj-include for the header (incl mj-head) and footer and then Atom with snippets that automatically pull in all the required mjml for any components that we use regularly. (not custom components but combinations of standard mjml ones with certain classes etc)

Each component that is then pulled in may need some slight css changes (hence why the styles for it cant already be in the mj-include within mj-head) and if mj-style could be used within the body, this then allows these style changes to reflect in the header.

Furthermore, this then also allows less technical people to build templates as everything required can be pulled into the template from one line of code and removes the need of having a lot of unnecessary styles in the header file (causing clipping in gmail), as they'd only be added to the head when the component is in the body.

I hope that makes sense?

Cheers

**Comment by iRyusa** [comment]
Well we split the core css of MJML and the mj-style part, so the gmail clipping is not really an issue. 

About the usecase I understand what you want, i'm still not sure if it's a good idea to allow this. 

In mj-include you can include both `mj-head/mj-body` to add some mj-style into the main document. `mj-head` will be append into the main MJML file. I think it's a good compromise between flexibility and keep the body for structural elements only

**Comment by nickjl** [comment]
Hey @iRyusa, ahh yeah I understand the gmail clipping isn't an issue in terms of clashing with the core MJML css, I more meant for when it comes for less technical people to build components we have to have a lot of styles already in the head for incase they want to use a certain component (I'd say we have 15-20 that are regularly used). If it could be added from the body then it removes the need to have these extra styles in the head for if the component is used.

Essentially I think that if it was allowed in the body it allows MJML to easily be set up to allow people with very little understanding of MJML, HTML or CSS to easily build email templates (this is currently what we use it for) and the only problem they all have with it currently is when it comes to needing to add styles into the head from the component, as everything else can be done behind the scenes for them.

What potential problems would be caused by allowing mj-style to be used within the body?

**Comment by iRyusa** [comment]
I think it's more a semantic issue rather than a technical issue. We can do it quite easily in MJML4, but I think it's a matter of consistency over conveniency

**Comment by iRyusa** [comment]
I think it's more a semantic issue rather than a technical issue as we can do it quite easily in MJML4, (consistency over conveniency). 

>  I more meant for when it comes for less technical people to build components we have to have a lot of styles already in the head for incase they want to use a certain component 

It's more a behind the scene issue ?

> If it could be added from the body then it removes the need to have these extra styles in the head for if the component is used.

Well I think the component should add it's own style by itself and shouldn't rely on any input in the template. You can easily know if a component is used in the markup and add styles you need for it ( in MJML3 through post-render, in MJML4 we gonna check it automatically )

I don't think it add __so__ much overhead to do something like this in a mj-included file : 

```
mjml
  mj-head
    mj-style
  mj-body
    // my include
```
From a learning standpoint, I think mixing head and body elements can add a lot of confusion about the goal of mj-head / mj-body

**Comment by nickjl** [comment]
Ahh yeah ok I do see your point in regards to semantics but feel potentially convenience outweighs in the case for ease for say a marketing team.

For me personally it's easy enough to work with that method, and I really love how easy MJML makes it for me to make templates! But it's just the feedback I've had for when people have to make changes to say a colour or url in a style, and then move it up into mj-head, they consistently make mistakes which would be eliminated if it they didnt have to do these changes.

Although saying that, with the addition of adding styles to the head from a custom component. Is that then going to be the case that say a class name could be passed into the component and a variable like color too (class name for if using multiple of same component), that would then go into the head via that method or are the styles for the custom component going to be unchangeable from the mj tag?

**Comment by iRyusa** [comment]
You will be able to push what you want from a component so yeah, if you want to generate a specific style regarding `props` of a component you will be able to do that. Even with props you can already use them as inline style ( I think it's the best way to ensure it will be applied everywhere)

**Comment by nickjl** [comment]
That's cool thanks, yeah I already use it for inline style but we need some things to change dependent on screen size too hence why want to be able to add to classes too.

So am I right in thinking that if I'll be able to push to classes in custom components in MJML 4 then this will essentially have the same effect as if it were mj-style in the body?

Thanks for all your explanations btw, really looking forward to MJML 4!!

**Comment by iRyusa** [comment]
> So am I right in thinking that if I'll be able to push to classes in custom components in MJML 4 then this will essentially have the same effect as if it were mj-style in the body? 

Well correct, then your component will need to generate and push the css he need/want

**Comment by nickjl** [comment]
Ok great thanks.

I guess that'll be the best for me to use instead then if mj-style in the body isn't going to be an option.

Thanks for all your help! :)
