### ISSUE TITLE
borders in mjml

### ISSUE THREAD

**Issue by NorthstarTech** [mjmlio/mjml#897]
Is it possible to add border-top, border-right,border-left properties individually under the decoration heading on mj-section or column. For now it only shows the border-width which gives all sided borders. I want only right or left sided borders. 

Thanks

**Comment by ngarnier** [comment]
Not sure what you mean about "decoration heading"? But those properties are supported as stated in the documentation (https://mjml.io/documentation/#mjml-section).

See this example: https://mjml.io/try-it-live/B1AS-_tlG
