### ISSUE TITLE
Workflow to generate emails

### ISSUE THREAD

**Issue by ptbrowne** [mjmlio/mjml#898]
I discovered `mjml` yesterday and it's been a treat to work with ! Thanks a lot !

To generate my emails from data, I had started with normal HTML and Handlebars so when I switched to `mjml` I kept Handlebars, so my workflow is basically to have Handlebars partials , compile to mjml and then run `mjml2html`.

Now I reckon that since `mjml` is React, I should be able to remove the Handlebars dependency and only rely on JSX and React components instead of Handlebars partials. I was unable to find anything of the sort in the docs, is it the recommended way of doing things ?

**Comment by rogierslag** [comment]
Sounds a lot like the usecase we had as well. As a result we developed https://github.com/inventid/maily

**Comment by iRyusa** [comment]
@ptbrowne

I think you should stick with handlebars, the `React`/`JSX` was only meant for internal stuff. In MJML4, we're totally dropping React from our stack to improve components and speed up the render time.

Note that applying the templating before rendering the mjml (as you do) is the best way to do it 👍

**Comment by ptbrowne** [comment]
> Sounds a lot like the usecase we had as well. As a result we developed https://github.com/inventid/maily

Thanks, I checked it out and it sounded really promising until I saw @iRyusa comment :/

> I think you should stick with handlebars, the React/JSX was only meant for internal stuff. 

OK good that I have that now :)

> Note that applying the templating before rendering the mjml (as you do) is the best way to do it 👍

Why ? I had the impression that if I would run into (hypothetical for now) performance problems, I could do the mjml before the templating (rationale behind being that the Handlebars pass must be faster than the mjml one since it has less things to do).

Thanks you both for you quicks responses !

**Comment by rogierslag** [comment]
> I think you should stick with handlebars, the React/JSX was only meant for internal stuff. In MJML4, we're totally dropping React from our stack to improve components and speed up the render time.

Note that we'd still be able to provide a react interface for maily itself.

**Comment by iRyusa** [comment]
> Why ? I had the impression that if I would run into (hypothetical for now) performance problems, I could do the mjml before the templating (rationale behind being that the Handlebars pass must be faster than the mjml one since it has less things to do).

Well the issue is, if you do some conditional or looping related stuff you could break some internal logic inside MJML component. Like we're compute how many columns you have in a section to set the column width if not defined. And you gonna need to wrap those handlebars conditionnal into a mj-raw, that could lead to break the HTML produced or won't be applied exactly where you'd want to

**Comment by ptbrowne** [comment]
Understood, thanks !
