### ISSUE TITLE
MJ-raw vs MJ-text

### ISSUE THREAD

**Issue by NorthstarTech** [mjmlio/mjml#899]
I am currently using the grapejs editor with the MJML framework. I created a block (within grapejs) to insert raw html within a template. It works best with mj-text. Is there issues later I can run into with mj-text? I know that mj-raw is made for this purpose but it interferes with the drag and drop of the grapejs editor.

**Comment by ngarnier** [comment]
`mj-raw` will basically allow you to add any content anywhere (for example between sections), whereas you're limited by the syntax with `mj-text` (as your content has to been inside a text tag, which is inside a section and a column).

However, if your plan is simply to add custom HTML to have more control on your layout than with MJML tags, `mj-text` will do the job perfectly. `mj-raw` will be more useful to use a templating language for example as you can put it anywhere.

This should answer your question so I'm closing, but feel free to comment if it's still unclear.
