### ISSUE TITLE
Button problem in Outlook.com (Firefox, Chrome, IE)

### ISSUE THREAD

**Issue by jojape** [mjmlio/mjml#901]
Hi there,

Not displaying button text and adding a line below the button.

Expected appearance: https://drive.google.com/open?id=1vb7fNcineCMoUetHNFFvGBLfbOhdbcTV
Appearance (Outlook.com - Desktop): https://drive.google.com/file/d/13g2rbsW1waA_9WG7o7pyrPk-VLucSFLq/view?usp=sharing

      **MJML version:**

      https://mjml.io/try-it-live/B1Qzqb2xf 

      **Email clients the bug is seen on:**

      outlook.com - Desktop

**Comment by nickygb** [comment]
I have the same problem, how did you solve it?
