### ISSUE TITLE
Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file

### ISSUE THREAD

**Issue by Zalasanjay** [mjmlio/mjml#906]
I am getting error while i am converting my mjml template to html

my mjml template is show bellow :

`<mjml><mj-body><mj-container min-height="100px"><mj-section><mj-column><mj-text>RequestType : </mj-text><mj-text id="Requesttype"></mj-text><mj-text>Request : </mj-text><mj-text id="Request"></mj-text><mj-text>Attachment : </mj-text><mj-text id="Attachment"></mj-text><mj-text>From : </mj-text><mj-text id="from"></mj-text><mj-text>Reply : </mj-text><mj-text id="Reply"></mj-text></mj-column></mj-section></mj-container></mj-body></mjml>`

My Code

```
const { mjml2html } = require('mjml')

var mjmlTemplate = "<mjml><mj-body><mj-container min-height="100px"><mj-section><mj-column><mj-text>RequestType : </mj-text><mj-text id="Requesttype"></mj-text><mj-text>Request : </mj-text><mj-text id="Request"></mj-text><mj-text>Attachment : </mj-text><mj-text id="Attachment"></mj-text><mj-text>From : </mj-text><mj-text id="from"></mj-text><mj-text>Reply : </mj-text><mj-text id="Reply"></mj-text></mj-column></mj-section></mj-container></mj-body></mjml>"

var templateHtml = mjml2html(mjmlTemplate)
```

**Comment by ngarnier** [comment]
The issue is that you're using double quotes around your string which is also using doubles quotes. Use backquotes instead: \`.
