### ISSUE TITLE
conditional statements in mj-head doesn't work

### ISSUE THREAD

**Issue by sdjeffal** [mjmlio/mjml#907]
Hello everybody. i need help please.

The conditional statements in mj-head doesn't work:

<mjml>
  <mj-head>
    <mj-attributes>

    <mj-raw>{% if var:brand == "gin" %}</mj-raw>
      <mj-class name="color-primary" color="#22D089"/>
    <mj-raw>{% endif %}</mj-raw>
      
    <mj-raw>{% if var:brand == "epl" %}</mj-raw>
      	<mj-class name="color-primary" color="#0295d3"/>
    <mj-raw>{% endif %}</mj-raw>
      
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container>

      
      <mj-section>
        <mj-column>
          <mj-text mj-class="color-primary">
            Bonjour {{var:name:"dupont"}} {{var:brand}}
          </mj-text>
        </mj-column>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>

Result: The instructions aren't executed, the color-primary is the last called (#0295d3) while the variable brand is gin. Why ?

**Comment by iRyusa** [comment]
Hi @sdjeffal 

Well in that particular case you won't be able to do such thing. Keep in mind that in `mj-head` elements won't transpile to HTML like in `mj-body`. So there's no way for us to know that you will apply it conditionnaly.

Even if we have a proposal for `mj-raw` in `mj-head` (#423) it won't behave as `mj-raw` in `mj-body` so we're still thinking how to reflect this difference.
