### ISSUE TITLE
mjml is not exporting  mjml2html

### ISSUE THREAD

**Issue by ansarizafar** [mjmlio/mjml#913]
mjml is not exporting  mjml2html. Is it a bug?

```
import { mjml2html } from 'mjml'
```

**Comment by iRyusa** [comment]
hi, 

With what’s the version of mjml ?

**Comment by ansarizafar** [comment]
I have installed the latest version  "mjml": "^3.3.5"

**Comment by iRyusa** [comment]
Can you provide more details on the issue any stacktrace, a console.log of the export, node version, Babel ... ?

**Comment by iRyusa** [comment]
Hi any news on that ? @ansarizafar

**Comment by ansarizafar** [comment]
I think it was a backpack-core issue. The issue is resolved. Thanks
