### ISSUE TITLE
renderMJML children

### ISSUE THREAD

**Issue by maxs15** [mjmlio/mjml#914]
I'm trying MJML 4 and I can't render the children of my custom component.
Here is what I'm doing, am I doing something wrong ?
Sorry if I'm missing something, always hard without doc ;) Thanks for the help.

Custom component
```js
class Layout extends BodyComponent {

	render() {
		return this.renderMJML(`
			<mj-section>
				<mj-column>
					${this.renderChildren(this.props.children)}
				</mj-column>
			</mj-section>
		`)
	}

}
```

mjml template:
```js
<mjml>
	<mj-body>
		<layout>
			<mj-text>TEST</mj-text>
		</layout>
	</mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hi @maxs15 

I think this is because mj-column can't receive plain HTML ( this.props.children will already be rendered when passing it into the mj-column ). I think this is something we didn't had in mind when creating this feature. We might need some kind of rawChildren that would allow this kind of thing.

**Comment by maxs15** [comment]
Hey @iRyusa,

Ok I see what's the issue, rawChildren would be a handy property indeed.
I hope you will consider added it in the next release, there's unfortunately lot of things that I can't do without that.

Thanks, and good work on MJML 4 🎉

**Comment by iRyusa** [comment]
ATM you can actually convert your JSON as XML with this snippet : https://jsfiddle.net/jp1nfsk0/ I think it should work fine 👍 Can you try it ?

**Comment by maxs15** [comment]
Awesome it works ! I'm gonna use that for the time being 👍 
You could actually expose such a method in the BodyComponent class (renderRawChildren for instance)

**Comment by iRyusa** [comment]
Yeah I think it will either be exposed as an helper method or as you said on BodyComponent, we'll talk about this 👍

**Comment by iRyusa** [comment]
@kmcb777 Can you add an option on`renderChildren` func to get the raw XML version and allow this for the next beta ?
