### ISSUE TITLE
Inline CSS stopped to work after 3.1.0

### ISSUE THREAD

**Issue by dyorgio** [mjmlio/mjml#915]
Hello guys! very nice lib :),

After update lib version from 3.1.0 to 3.3.5 my mj-style content stopped to be used as "inline css", and stop to be correct rendered on Mail (macOS).

Now my e-mails are build using <style> tags, Is it a new behavior?

```xml
<mjml>
    <mj-head>
        <mj-attributes>
            <mj-all font-family="Open Sans, sans-serif" color="#474747"/>
        </mj-attributes>
        <mj-style>
            .radial-background {
            background-color: #e1e1e1;
            background-image: -webkit-radial-gradient(50% 50%, circle, #f5f5f5, #e1e1e1);
            background-image: radial-gradient( circle at 50% 50%, #f5f5f5, #e1e1e1);
            height: 100%;
            padding-top: 10px;
            padding-bottom: 10px;
            }

            .content-border {
            background: white;
            border-radius: 0px;
            border: 0px;
            -webkit-box-shadow: 0 2px 3px rgba(0, 0, 0, 0.05);
            box-shadow: 0 2px 3px rgba(0, 0, 0, 0.05);
            margin: 0px auto;
            max-width: 600px;
            font: 300 16px/1.55 "Open Sans", sans-serif;
            }
        </mj-style>
    </mj-head>
    <mj-body>
        <mj-container >
            <mj-raw>
                <div class="radial-background">
                    <div class="content-border">
            </mj-raw>
            <!-- Some nice content here -->
            <mj-raw>
                    </div> <!-- Close content-border -->
                </div> <!-- Close radial-background -->
            </mj-raw>
        </mj-container>
    </mj-body>
</mjml>
```

**MJML version:**

3.1.0

**Email clients the bug is seen on:**

Mail (macOS 10.13.1)

**Comment by ngarnier** [comment]
Hey @dyorgio, indeed since v3.3.0, `mj-style` doesn't inline CSS by default so you can also append head styles (to add your own media queries for example). You can still inline styles with the `inline` attribute: `<mj-style inline="inline">`.

See the release note for 3.3.0 https://github.com/mjmlio/mjml/releases/tag/3.3.0

**Comment by dyorgio** [comment]
Tks @ngarnier!

**Comment by dyorgio** [comment]
Is it possible to make e-mail styling work with Mail without css-inline?
I always think that inline css is the more "compatible" way to make it.

**Comment by ngarnier** [comment]
Inlining CSS is the safest way to go indeed, even though more and more clients now support head styles (Gmail used not to but now does, for example). You can try to only rely on head styles, but my opinion is that it's worth going the safe way and inlining as anyway MJML will do it for you.

**Comment by dyorgio** [comment]
@ngarnier Just to stay on 3.1.0 features topic:
In my example I use mj-raw to open some divs and close after in another mj-raw.
Now my divs are closed by lib :(, Can I have the old behavior on 3.3.5?

**Comment by ngarnier** [comment]
Hm that's surprising that it was not autoclosing before... It's something done by React and that we can't really avoid, so unless it's due to an update of React I don't see how it would have not been happening before.

To answer your question, the only way to avoid that in 3.3.5 is to encode the HTML chars like this: `&lt;div&gt;`. This way, the div won't be autoclosed and the characters will be decoded in the output so it will work as you expect.

Note that this hack won't be needed in MJML v4 as this will be fixed (we won't be using React anymore).

**Comment by dyorgio** [comment]
I confirm that ```&lt;div&gt;```works, but inline css stop to works :P.
I will stay on 3.1.0 until v4 is in alpha.
Tks again @ngarnier !

**Comment by ngarnier** [comment]
It's up to you but inline css didn't stop to work, it just works differently as we extended it and added a feature. 

Just adding `inline="inline"` to  `mj-style` will make it work exactly as you expect:
```xml
<mjml>
    <mj-head>
        <mj-attributes>
            <mj-all font-family="Open Sans, sans-serif" color="#474747"/>
        </mj-attributes>
        <mj-style inline="inline">
            .radial-background {
            background-color: #e1e1e1;
            background-image: -webkit-radial-gradient(50% 50%, circle, #f5f5f5, #e1e1e1);
            background-image: radial-gradient( circle at 50% 50%, #f5f5f5, #e1e1e1);
            height: 100%;
            padding-top: 10px;
            padding-bottom: 10px;
            }

            .content-border {
            background: white;
            border-radius: 0px;
            border: 0px;
            -webkit-box-shadow: 0 2px 3px rgba(0, 0, 0, 0.05);
            box-shadow: 0 2px 3px rgba(0, 0, 0, 0.05);
            margin: 0px auto;
            max-width: 600px;
            font: 300 16px/1.55 "Open Sans", sans-serif;
            }
        </mj-style>
    </mj-head>
    <mj-body>
        <mj-container >
            <mj-raw>
                <div class="radial-background">
                    <div class="content-border">
            </mj-raw>
            <!-- Some nice content here -->
            <mj-raw>
                    </div> <!-- Close content-border -->
                </div> <!-- Close radial-background -->
            </mj-raw>
        </mj-container>
    </mj-body>
</mjml>
```

**Comment by dyorgio** [comment]
Hi @ngarnier, this template appears to works if you don't put contents between mj-raw elements.
If you put something there you will see that second mj-raw is ignored (but css inline works).
Than, if you start to use escapes (```&lt;div&gt;```) tags are correctly closed, but I think that mjml stop to recognize it as a valid html to put inline-css. I tested here and don't work if use both "solutions" at same time.

**Comment by ngarnier** [comment]
I see, indeed if you use escapes then the elements won't be detected as HTML elements. I'm not sure what you're trying to do though and feel like you could do what you want way more easily with `css-class`. 

Have a look at this example: https://mjml.io/try-it-live/BJfvGM6WG

If it's not what you're trying to achieve, feel free to share the design you want to have, I'm interested in understanding your need better!

**Comment by dyorgio** [comment]
Omg @ngarnier !
Very nice and elegant solution!
I really don't need to use mj-raw if use mj-wrapper. but I can't get my desired layout yet:
Take a look: https://jsfiddle.net/8q6ajzf3/ (body height 100% is not working in example :( )

**Comment by ngarnier** [comment]
I'm sorry I'm not sure to understand the issue here, is it that the grey background is applied on the whole body instead of just around the white area? 

If so, you should do it more like this: https://mjml.io/try-it-live/By-dbDpZG

However, note that some of the styles you're using will most likely not work in the majority of email clients (radial-background, box-shadow... or even border-radius on Outlook).
