### ISSUE TITLE
sections have margins in Outlook professional plus 2013

### ISSUE THREAD

**Issue by br4nnigan** [mjmlio/mjml#916]
I used the latest mjml version to compile.

here's a simple code example. In the client you can see the vertical borders being interrupted.

    <mjml>
        <mj-body background-color="#ffffff">
            <mj-container background-color="#ffffff" width="800" >

                <mj-section padding="0" border-top="solid 1px #ca9b3c" border-left="solid 1px #ca9b3c" border-right="solid 1px #ca9b3c">
                    <mj-column >
                        <mj-image padding="0" width="800" src="test.png"></mj-image>
                    </mj-column >
                </mj-section>

                <mj-section padding="5% 0" border-left="solid 1px #ca9b3c" border-right="solid 1px #ca9b3c">
                    <mj-column >
                        <mj-image padding-top="40" width="475" src="test.png"></mj-image>
                    </mj-column >
                </mj-section>

                <mj-section></mj-section>
            </mj-container>
        </mj-body>
    </mjml>

**Comment by iRyusa** [comment]
Hi @br4nnigan 

I don't think we can do anything on that, the only fix is to remove few pixels on your full width image, outlook doesn't take the border width in the actual width of the table
