### ISSUE TITLE
mj-section padding issue on outlook 2010

### ISSUE THREAD

**Issue by numito** [mjmlio/mjml#918]
Hello,

If you add 2 sections with a lateral padding of 10px, if the content of the second section is empty then the content width won't be correct, it will be slightly shorter. I have added a screenshot of outlook rendering and gmail rendering as you see the green line is too short on outlook. 
I have corrected the problem by adding a width="800" style="width:800px" attribute to the table:
From:
```
<!--[if mso | IE]>
        <table role="presentation" border="0" cellpadding="0" cellspacing="0" >
            <tr>
                <td style="vertical-align:top;width:800px;">
        <![endif]-->
```
To:

```
<!--[if mso | IE]>
        <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="800" style="width:800px;">
            <tr>
                <td style="vertical-align:top;width:800px;">
        <![endif]-->
```

Original MJML (main-container has a width of 800px). 

```xml
 <mj-section padding="0 10" >
            <mj-column mj-class="block-col">
                <mj-image src="/assets/box1_header.png" padding="0" />
                <mj-text mj-class="perso-msg" css-class="message-fix">
                    Dear Mr T,<br><br>
                    Wish you a very bla bla and bla.<br>
                    Hope you ski, surf etc...<br>
                    See u in January... maybe.
                </mj-text>
                <mj-text mj-class="perso-msg" align="right" css-class="message-fix">
                    <br>
                    Charlie Brown
                </mj-text>
                <mj-image src="/assets/box1_footer.png" padding="0" />
                </mj-column>
            </mj-section>
            <mj-section padding="0 10" >
                <mj-column mj-class="block-col-btm">
                    <mj-spacer height="8px">
                </mj-column>
            </mj-section>
        </mj-container>
```

You will find attached all files.
Best
Numa

**Comment by numito** [comment]
Wrong rendering on outlook
![image003](https://user-images.githubusercontent.com/3371287/33898284-3f1f6a6a-df68-11e7-81a2-eface5960493.png)
Correct rendering on Mail.app
![capture d ecran 2017-12-12 a 18 14 22](https://user-images.githubusercontent.com/3371287/33898340-6545df12-df68-11e7-960e-8f318b878f48.jpg)

**Comment by iRyusa** [comment]
Thanks for reporting that, we'll see if we can add this `width` params in MJML4

**Comment by kmcb777** [comment]
The way `width` and `padding` are handled in v4 have changed, and this seems to be ok now. The rendering for this template is ok on outlook (on email-on-acid).
Now the padding is included in the calculation of the width of the inside `td`.
