### ISSUE TITLE
Add borders to mj-container

### ISSUE THREAD

**Issue by sconno05** [mjmlio/mjml#92]
According to the docs and through some trial and error, it doesn't seem like I can add a border to most components.  I think this would especially useful for mj-body, mj-section, mj-column.  Is there a workaround?

**Comment by Pookiz** [comment]
+1 I would like to know too :+1:

**Comment by Pookiz** [comment]
Thank you !

**Comment by iRyusa** [comment]
Hi there,

I am working on adding border + radius on section/column. Mj-container can receive it only if we add a `max-width` on the generated `div`, and it fails not so gracefully on outlook 2007/10/16 ( see https://litmus.com/builder/21006f6 )

**Comment by iRyusa** [comment]
Quick update here,
`mj-section` and `mj-column` supports border.

We're still investigating for a way to add it to `mj-container` without breaking the responsive or Outlook 20XX render

**Comment by raulsann** [comment]
+1 to border-radius in mj-column, even if it breaks in outlook.

**Comment by iRyusa** [comment]
Well we're stuck with the border-collapse on the table :/

**Comment by ipa1981** [comment]
@iRyusa, I'm trying to put border in mj-section in  "Try It Live", but nothing happens:

The code is simply copy/paste from manual with added border in mj-section
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section border-left="10px" border-color="#F45E43">
        <mj-column>

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Try it live is still in 2.3 please install locally 3.0 :)

**Comment by ipa1981** [comment]
OK, will try other way, Then just for your notice in documentation there is not mention about border so far. )

**Comment by iRyusa** [comment]
Yes whole website is still in MJML 2.3, we'll try to update it asap.

**Comment by iRyusa** [comment]
Well now you can put a `mj-wrapper` with a border and multiple sections inside. I think border on `mj-container` is then no longer needed. I'm closing this one
