### ISSUE TITLE
mj-include doesnt inline css

### ISSUE THREAD

**Issue by justlevine** [mjmlio/mjml#926]
I have a css.mjml file that contains all the common css rules for my various email templates. I include it using:
`<mj-head>
    <mj-include path="css" />
</mj-head>`

And in the css file:
`<mj-head>
    <mj-style>
         .example{color:#212121}
    </mj-style>
    <mj-style inline="inline">
        .example-inline{font-size:14px}
     </mj-style>
</mj-head>`
`
Recently noticed that while the styles display fine in the MJML Windows App (v2.7.1 running MJML 3.3.3), in the html export, none of the styles declared under `mj-style inline="inline" are actually inlined.

Any ideas why?

**Comment by iRyusa** [comment]
Hi @justlevine 

Can you provide the mj-body too, in order to reproduce ? Thanks

**Comment by cly3** [comment]
`<mjml>
  <mj-body>
    <mj-container>

      
      <mj-section background-color="#f0f0f0">
        <mj-column>
          <mj-text font-style="regular" font-size="15" color="#626262" font-family="roboto">
          Firefly Orthoses | Richie Brace – Price Increase
          </mj-text>
        </mj-column>

      </mj-section>


      <mj-section background-color="#ffffff" padding-bottom="20" padding-top="20">
              <mj-column width="100%" vertical-align="top">
                <mj-image src="https://i.imgur.com/HMkqRrN.png?1" alt="Firefly Snow logo" align="center" border="none" width="500" padding-left="10" padding-right="0" padding-bottom="0" padding-top="0">

                </mj-image>
              </mj-column>
            </mj-section>

      
      <mj-section background-color="#fafafa">
        <mj-column width="400">

          <mj-text font-style="italic" font-size="20" font-family="helvetica Neue" color="#fb4f14" line-height="1.4">As you have ordered Richie Brace AFOs from Firefly, we'd like to inform you of an upcoming price increase for this product line. 
          </mj-text>

          <mj-text color=#525252 font-family="helvetica neue" font-size="15">
            This price increase takes effect from XX XXXX 2018
          </mj-text>
        </mj-column>
      </mj-section>

      
      <mj-section background-color="white">

        
        <mj-column column width="45%">
          <mj-image width="500px" src="http://www.fireflyorthoses.com/email-assets/RichieBrace2.jpg">
        </mj-column>

        <mj-column column width="55%">
          <mj-text font-style="regular" font-size="20" font-family="helvetica Neue" align="center">Richie Brace Price Change</mj-text>

          <mj-text padding="0 40 0 30">
                <p>From the above date Richie Brace AFOs will be priced as follows:</p>
            <ul>
              <li>Richie Brace (standard) £260.00<br>
              <li>Little Richie (1 - 12 years) £260.00 <br>
              <li>Richie Brace (shin guard) £305.00 <br>
              <li>Dynamic Assist (w/ Tamarac hinge) £345.00 <br>
            </ul>
          </mj-text>
        </mj-column>          
      </mj-section>

      <mj-section background-color="#f0f0f0">
        <<mj-column>
          <mj-text padding="0 30 0 30">
            The <b>Tamarac hinge</b> is an optional extra for Dynamic Assist versions (this allows Sagittal Plane movement at the Talo-Crural joint, however, attempts to hold the foot approximately 5-10 degrees dorsiflexed).
          </mj-text>
        </mj-column>
      </mj-section>

        <mj-section background-color="#fb4f14">
          <mj-column>
            <mj-text padding="0 30" color="white">Make sure to follow us across our social media platforms to keep up to date on the latest Firefly products, services and news.</mj-text>
          </mj-column>
        </mj-section>
                
      
      <mj-section background-color="#fb4f14">
       
        <mj-column>
          <mj-social display="twitter" url="https://twitter.com/mailjet"/>
        </mj-column>

        <mj-column>
          <mj-social display="instagram" url="https://www.instagram.com/mailjet" />
        </mj-column>

        <mj-column>
          <mj-social display="facebook" url="https://www.facebook.com/mailjet" />
        </mj-column>
      </mj-section>
                
      
                
    </mj-container>
  </mj-body>
</mjml>`

**Comment by cly3** [comment]
<mj-section background-color="#f0f0f0">
    <mj-column>
      <mj-text font-style="regular" font-size="15" color="#626262" font-family="roboto">
      Firefly Orthoses | Richie Brace – Price Increase
      </mj-text>
    </mj-column>

  </mj-section>


  <mj-section background-color="#ffffff" padding-bottom="20" padding-top="20">
          <mj-column width="100%" vertical-align="top">
            <mj-image src="https://i.imgur.com/HMkqRrN.png?1" alt="Firefly Snow logo" align="center" border="none" width="500" padding-left="10" padding-right="0" padding-bottom="0" padding-top="0">

            </mj-image>
          </mj-column>
        </mj-section>

  
  <mj-section background-color="#fafafa">
    <mj-column width="400">

      <mj-text font-style="italic" font-size="20" font-family="helvetica Neue" color="#fb4f14" line-height="1.4">As you have ordered Richie Brace AFOs from Firefly, we'd like to inform you of an upcoming price increase for this product line. 
      </mj-text>

      <mj-text color=#525252 font-family="helvetica neue" font-size="15">
        This price increase takes effect from XX XXXX 2018
      </mj-text>
    </mj-column>
  </mj-section>

  
  <mj-section background-color="white">

    
    <mj-column column width="45%">
      <mj-image width="500px" src="http://www.fireflyorthoses.com/email-assets/RichieBrace2.jpg">
    </mj-column>

    <mj-column column width="55%">
      <mj-text font-style="regular" font-size="20" font-family="helvetica Neue" align="center">Richie Brace Price Change</mj-text>

      <mj-text padding="0 40 0 30">
            <p>From the above date Richie Brace AFOs will be priced as follows:</p>
        <ul>
          <li>Richie Brace (standard) £260.00<br>
          <li>Little Richie (1 - 12 years) £260.00 <br>
          <li>Richie Brace (shin guard) £305.00 <br>
          <li>Dynamic Assist (w/ Tamarac hinge) £345.00 <br>
        </ul>
      </mj-text>
    </mj-column>          
  </mj-section>

  <mj-section background-color="#f0f0f0">
    <<mj-column>
      <mj-text padding="0 30 0 30">
        The <b>Tamarac hinge</b> is an optional extra for Dynamic Assist versions (this allows Sagittal Plane movement at the Talo-Crural joint, however, attempts to hold the foot approximately 5-10 degrees dorsiflexed).
      </mj-text>
    </mj-column>
  </mj-section>

    <mj-section background-color="#fb4f14">
      <mj-column>
        <mj-text padding="0 30" color="white">Make sure to follow us across our social media platforms to keep up to date on the latest Firefly products, services and news.</mj-text>
      </mj-column>
    </mj-section>
            
  
  <mj-section background-color="#fb4f14">
   
    <mj-column>
      <mj-social display="twitter" url="https://twitter.com/mailjet"/>
    </mj-column>

    <mj-column>
      <mj-social display="instagram" url="https://www.instagram.com/mailjet" />
    </mj-column>

    <mj-column>
      <mj-social display="facebook" url="https://www.facebook.com/mailjet" />
    </mj-column>
  </mj-section>
            
  
            
</mj-container>

**Comment by iRyusa** [comment]
@cly3 your MJML doesn't seem related to the issue ?

**Comment by cly3** [comment]
sorry, wrong thread... :(

**Comment by seclace** [comment]
This project very cool, but needs some improvements as I think (see below)
What's wrong: mjml leaves the `@media` queries in output html (tag `head -> style`) which even gmail filters in web client. How could it be inlined in output file?

Yes, I could use some other packages (e.g. [juice](https://github.com/Automattic/juice) or another one), but isn't it supposed to be the default behaviour?
![2017-12-22 12 13 22](https://user-images.githubusercontent.com/13925962/34286215-bf1e3c22-e711-11e7-8679-97333a3f3520.png)
![2017-12-22 12 13 36](https://user-images.githubusercontent.com/13925962/34286216-c180bada-e711-11e7-840a-497f48aa8450.png)

**Comment by ngarnier** [comment]
@seclace, Gmail doesn't filter out the style tag, it has been supporting responsive styles for more than a year now: https://developers.google.com/gmail/design/css.

About the media queries, MJML is mobile-first to ensure the most optimal layout by default, and uses media queries to display the desktop layout. We think mobile-first is best for two reasons: 

- the mobile layout is the most readable (it's easier to read a mobile layout on desktop than a desktop layout on mobile)
- there are more mobile email clients that don't support media queries than desktop email clients

**Comment by iRyusa** [comment]
Hi @justlevine 

Any news on that ?
