### ISSUE TITLE
social media links not working

### ISSUE THREAD

**Issue by cly3** [mjmlio/mjml#927]
I can't link social media icons to the desired network profiles.

REPRODUCTION STEPS

1. [First Step] - using the `<mjml-social>` tag I can display the 3 desired social networks I want;
Twitter,  Facebook and Instagram. See the code below for my Twitter logo:
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-social display="twitter" twitter-href="https://twitter.com/mailjet"/>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

2. [Second Step] The icons are displayed in the email as expected
![screen shot 2017-12-21 at 11 57 10](https://user-images.githubusercontent.com/34556416/34254904-21ccfa9c-e646-11e7-8f14-e8671674f470.png)

However, when they are clicked on they do not bring me to the mailjet twitter profile as expected, but instead I'm brought to:
![screen shot 2017-12-21 at 11 51 11](https://user-images.githubusercontent.com/34556416/34254820-c9d156a8-e645-11e7-83a1-46e1417cb67c.png)

I'm using Google Chrome.

Any help appreciated.

**Comment by mattlub** [comment]
@cly3 try `display="twitter:url"`

This is documented [here](https://github.com/mjmlio/mjml/blob/3.3.x/packages/mjml-social/README.md) but is not correct in the documentation on the website currently...

**Comment by iRyusa** [comment]
Hi @cly3 

As @mattlub said, it's documented here : https://mjml.io/documentation/#mjml-social (in the blue warning)

**Comment by mattlub** [comment]
@iRyusa I think without looking at the blue box, the description in the table is misleading:

attribute | unit | description | default value
-- | -- | -- | --
facebook-href | url | button redirection url | [[SHORT_PERMALINK]]

**Comment by cly3** [comment]
@iRyusa, ah ok I see, but what I'm looking to do is for the social media buttons to direct users to social network profiles? Does that make sense?

**Comment by iRyusa** [comment]
@mattlub Well the component has been refactored in MJML4  to a new syntax with less magic interaction like `:url` 

@cly3 As @mattlub  said, ` <mj-social display="twitter:url" twitter-href="https://twitter.com/mailjet"/>`

**Comment by cly3** [comment]
@mattlub @iRyusa thanks to you both. Problem solved, it's now working as I expect. 
This is my first time using Github, thanks for your help. It was probably a daft question. But you got me there in the end!
