### ISSUE TITLE
Cannot find module "fs" — Can MJML 4 be used in a browser?

### ISSUE THREAD

**Issue by stoplion** [mjmlio/mjml#928]
when using mjml 4 with Webpack and React
adding this line..
`import { mjml2html } from 'mjml';`
produces error: `Cannot find module "fs"`

[Is MJML 4 compatible with browser?](https://github.com/mjmlio/mjml/issues/274)

**Comment by Geczy** [comment]
did you find an answer?

**Comment by apuntovanini** [comment]
@stoplion I'm with @Geczy, did you find an answer?

**Comment by ngarnier** [comment]
Hey @Geczy & @apuntovanini, MJML is not supported browser-side: https://github.com/mjmlio/mjml/issues/438#issuecomment-302712905

**Comment by anand-gopinath** [comment]
@ngarnier  Facing the same issue while importing. I used the previous version (3.3.5) whereas it bundled with 1.5 mb. So now MJML 4 has been released and i want to know weight of the new version as well the the above issue fix.

Thanks in advance

**Comment by ngarnier** [comment]
Still same as above,  MJML is not supporter browser-side.

**Comment by ttonyh** [comment]
Does anyone know the level of effort to make the render function take a promise? I think the best route would be to do what MJML suggests, and handle the MJML processing on the server-side.

**Comment by stevenschlansker** [comment]
In case it's helpful to anyone, we stubbed out `fs` so:
```
module.exports = {
    readFileSync: function(args) {
        if (args == '/.mjmlconfig') {
            return '{"packages":[]}';
        }
        return "";
    }
}
```
and this let us run mjml in Graal.JS

**Comment by iRyusa** [comment]
PR are welcomed, we only require fs for reading an optional .mjmlconfig
file.

**Comment by MrArun005** [comment]
> In case it's helpful to anyone, we stubbed out `fs` so:
> 
> ```
> module.exports = {
>     readFileSync: function(args) {
>         if (args == '/.mjmlconfig') {
>             return '{"packages":[]}';
>         }
>         return "";
>     }
> }
> ```
> 
> and this let us run mjml in Graal.JS. Yes, this is a total hack. But it does indicate that if MJML were a little more careful and only optionally required `fs`, it could probably run in the browser too.

Where i should add this code, in webpack or in somewhere else
