### ISSUE TITLE
Sections having different width

### ISSUE THREAD

**Issue by aybhalala** [mjmlio/mjml#929]
Two MJML sections having different width. Even when inside a wrapper they go out of the wrapper.

**What my code has**

1. A container with background #f7f7f7
2. Two sections with background #fff (One section contains a table)

**Already tried wrapper**
I do not want a full-width section as I want to have different background-color for container and section. I tried setting the sections inside wrapper to have full-width but the wrapper width is set to 600px. I think the issue is because of table.

**Comment by iRyusa** [comment]
Hey! Can you share the Mjml to reproduce ? Thanks

**Comment by aybhalala** [comment]
```
<mj-section background-color="#fff">
         <mj-column>
           <mj-text font-size="25" align="center">New Order Notification</mj-text>
           <mj-text font-size="16">
             <b>Date: {config:date_time}</b>
           </mj-text>
           <mj-text font-size="16">
             Thank you for placing an order}. The following is the summary of your order.
           </mj-text>
           <mj-divider border-width="1px" border-style="dashed" border-color="lightgrey" />
           <mj-text font-size="22" align="center">Order Details</mj-text>
              <b>Order Items:</b>
           </mj-text>
           <mj-table font-size="14">
            <tr style="border-bottom:1px solid #ecedee;text-align:left;padding:15px 0;">
              <th style="padding: 0 15px 0 0;">Product Name</th>
              <th style="padding: 0 15px;">Part #</th>
              <th style="padding: 0 15px;">Unit Price</th>
              <th style="padding: 0 15px;">Qty</th>
              <th style="padding: 0 0 0 15px;">Total</th>
            </tr>
            <tr>
              <td style="padding: 0 15px 0 0;">{order:item_product_name}</td>
              <td style="padding: 0 15px;">{order:item_part_number}</td>
              <td style="padding: 0 15px;">{order:item_price}</td>
              <td style="padding: 0 15px;">{order:item_qty}</td>
              <td style="padding: 0 0 0 15px;">{order:item_total}</td>
            </tr>
          </mj-table>
          <mj-divider border-width="1px" border-style="dashed" border-color="lightgrey" />
         </mj-column>
       </mj-section>
       <mj-section background-color="#fff">
         <mj-column>
           <mj-text font-size="16">
             <b>Billing Address</b><br />
             {order:company}<br />
             {billing:address1}<br />
             {billing:address2}<br />
             {billing:city}, {billing:state} {billing:zipcode}
           </mj-text>
         </mj-column>
       </mj-section>
```

**Comment by aybhalala** [comment]
Hello,
Is this a problem or do I need to change something?

**Comment by ngarnier** [comment]
Indeed it's due to your table, and more specifically to the long text inside the table cells as the cells grow according to it.

If you replace the variables by real content, you'll see your table is correctly stacked: https://mjml.io/try-it-live/B1Fs1NMmf.

PS: you're missing a `mj-text` line 15.

**Comment by iRyusa** [comment]
As @ngarnier said table will expand the mobile layout, what you can do is play with the word-break property on table, but that could make the email unreadable in mobile : so use `mj-table` wisely

**Comment by aybhalala** [comment]
Hello @ngarnier  and @iRyusa ,
Thanks for helping out on the issues. I got a work-around by setting max widths on the td elements and then working with the wraps. Once again thank you for your help and making this platform great.
