### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by willdady** [mjmlio/mjml#930]
Just wondering if there's any plans to add a typescript declaration file to this repo (index.d.ts). I ask as (DefinitelyTyped)[https://github.com/DefinitelyTyped/DefinitelyTyped] also doesn't seem to have a declaration for mjml (`npm install --save-dev @types/mjml`).

**Comment by iRyusa** [comment]
Hi @willdady 

Well we don't use Typescript for MJML, so there's no plan to expose typescript definition. I think PR are welcome but we're not confident keep it up to date

I'm closing the issue, but as said, all PR are welcome

**Comment by aahoughton** [comment]
I just added a basic MJML 4.x type definition to the typescript lib.

**Comment by SoorajChandran** [comment]
@aahoughton  Can you please share the link to find it ?

**Comment by shadeglare** [comment]
> @aahoughton Can you please share the link to find it ?

https://www.npmjs.com/package/@types/mjml

**Comment by MarcARoberge** [comment]
Hey ! is it possible that putting string for the _inp_ variable is wrong ? it is an object no ? Passing a stringify JSON object does not work.

**Comment by iRyusa** [comment]
mjml2html can receive either a string (<mjml>...</mjml>) or an actual
object, no need to stringify it.
