### ISSUE TITLE
section background image

### ISSUE THREAD

**Issue by cly3** [mjmlio/mjml#931]
I'm having an issue with correctly sizing a background image. My background image is always larger than the size of the section. However, event when i've resized the image in photoshop to be 600px wide and link to it, it still appears too large for the section.  

The full image should appear as: 
![top600x171](https://user-images.githubusercontent.com/34556416/34491235-9890c828-efda-11e7-9d29-cc16717f445a.png)

But instead it's appearing as such with the bottom cut off:
![screen shot 2018-01-02 at 16 34 10](https://user-images.githubusercontent.com/34556416/34491310-d58a0262-efda-11e7-8ec8-bfd0f193002f.png)

```
<mjml>
  <mj-body>
    <mj-container>

      <!-- image header -->
      <mj-section background-url="https://i.imgur.com/fgQ7pNW.png"
              background-size="cover"
              background-repeat="no-repeat">

          <mj-text align="center" line-height="#" color="white" font-size="40" font-family="Roboto">February Newsletter</mj-text>


          <mj-button background-color="green" href="www.fireflyorthoses.com">CTA</mj-button>
        </mj-column>

      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
How can I get the full background image to render?

**Comment by ngarnier** [comment]
The section's height is fluid, so as you don't have enough content in the section, the background-image isn't displayed.

Check [this snippet](https://mjml.io/try-it-live/ryuTUEY7z), I also added an example using `mj-hero` that might be useful to you.

PS: you're also missing an opening `mj-column` tag in your section.

**Comment by cly3** [comment]
wow, thanks so much for your help, much appreciated!
