### ISSUE TITLE
Are you kidding ? Cannot set default font for all tag ? 

### ISSUE THREAD

**Issue by KytoSai** [mjmlio/mjml#945]
Are you kidding ? Cannot set default font for all tag ? 
You must set css-class for every tag to change font-family ???

**Comment by dalefish** [comment]
https://www.npmjs.com/package/mjml-head-attributes calm down

**Comment by KytoSai** [comment]
I'm sorry :( !!!! 
Thanks you so much !!!!!!

**Comment by k0pernicus** [comment]
Are you kidding ? Cannot RTFM @KytoSai ???

(Please, *respect* the maintainers and contributors of Open Source projects.
With this kind of issue/comment, you're on the verge of insulting the hard work they do every day to make you happy.
An Open Source projects contributor/maintainer)

**Comment by Rharuow** [comment]
LOL
