### ISSUE TITLE
Full documentation for MJML 4 // mj-container doesn't exist

### ISSUE THREAD

**Issue by Aylay** [mjmlio/mjml#946]
Hi all,

I see that multiple tags don't exist anymore like `mj-container`.
So the validation command don't work and the HTML generation don't continue.

Is there a full documentation of MJML 4 like [mjml.io/documentation](https://mjml.io/documentation) ?

Thanks

**Reproduction Steps:**

1. Put `<mj-container>` in my MJML file
2. `$ mjml -w index.mjml`

**Expected behavior:**

A good HTML file or a full documentation to fix this.

**Observed behavior:**

An error in the terminal output : 
```
/index.mjml - Change detected
[ { line: 3,
    message: 'Attributes name, href are illegal',
    tagName: 'mj-font',
    formattedMessage: 'Line 3 (mj-font) — Attributes name, href are illegal' },
  { line: 12,
    message: 'Element mj-container doesn\'t exist or is not registered',
    tagName: 'mj-container',
    formattedMessage: 'Line 12 (mj-container) — Element mj-container doesn\'t exist or is not registered' },
  { line: 16,
    message: 'Attributes width, src, href, title are illegal',
    tagName: 'mj-image',
    formattedMessage: 'Line 16 (mj-image) — Attributes width, src, href, title are illegal' } ] 'Line 3 (mj-font) — Attributes name, href are illegal' 'Line 12 (mj-container) — Element mj-container doesn\'t exist or is not registered' 'Line 16 (mj-image) — Attributes width, src, href, title are illegal'
/index.mjml - Successfully compiled
```

**MJML version:**

4.0.0-alpha.5

**Comment by iRyusa** [comment]
Hi @Aylay 

ATM the doc is not yet available. There's a lot of breaking change on MJML4 so a lot of doc to update before the release. We should do a pass this week to clean everything up, so the documentation will be available on each package.

Currently you can read about MJML4 on the medium here https://medium.com/mjml-making-responsive-email-easy/the-first-alpha-for-mjml-4-is-here-bde5fbd3f316 

(Note that validation message are still broken on the alpha see #920)

**Comment by ngarnier** [comment]
Also a couple resources that can help you: 
- the list of [breaking changes in the last alpha](https://github.com/mjmlio/mjml/releases/tag/4.0.0-alpha.5): 
- a [migrate package](https://github.com/mjmlio/mjml/tree/migrate-integration/packages/mjml-migrate) to migrate your templates from v3 to v4 (which will be integrated to v4 to ease the transition)

**Comment by Aylay** [comment]
Hi @iRyusa @ngarnier ,

Thanks a lot for the links !
I'm reading the article in Medium, it's really great

_I let you close if you want_

Bye

**Comment by ngarnier** [comment]
We'll leave it open as the doc is indeed not ready yet, it might help others.

**Comment by Aylay** [comment]
Yes good idea @ngarnier  ! 👍

**Comment by ruudboon** [comment]
Thnx. Helpful to have some documentation.

**Comment by ngarnier** [comment]
We've updated the documentation on each readme. So if you need the documentation for the `mj-text` package for example, you'll find it on the [readme of the mj-text package](https://github.com/mjmlio/mjml/blob/next/packages/mjml-text/README.md).

Regarding the list of changes, you can still refer to the Medium article.

We also plan a total revamp of the structure of the documentation on https://mjml.io/documentation for the release. If you have suggestion, feel free to share them here.
