### ISSUE TITLE
Documentation - Basic Layout Example

### ISSUE THREAD

**Issue by louiesolomon** [mjmlio/mjml#95]
Missing 'padding' style in the Company Header example code. Also, the preview image shows the text center aligned, and the 'Try it Live' example has the text left aligned.

**Comment by GuillaumeBadi** [comment]
Hey @louiesolomon !

Yep there is a missing `align="center"` and `padding=30` ! Thanks for discovering the issue!
It will be corrected! :)

**Comment by iRyusa** [comment]
https://mjml.io/try-it-live/basic has been updated, closing ! 

Thanks for reporting
