### ISSUE TITLE
mj-button is adding target=_blank to anchor links

### ISSUE THREAD

**Issue by gavrochelegnou** [mjmlio/mjml#950]
When using mj-button to get a link to another part of the newsletter (anchor link), the generated <a> tag includes a target="_blank" attribute.

It might break the functionnality on some client and definitely breaks it when viewing the web/archive version of the newsletter.

**Reproduction Steps:**

1. Include a link like this  `<mj-button href="#news">News</mj-button>`
2. Include a tag like this somewhere in the mail `<mj-raw><a name="nouveautes"></a></mj-raw>`

**Expected behavior:**

The link should just scroll down to the second section.

**Observed behavior:**

Link is sometimes opened in a new window. Seen in some webmails and in the archived/web version (mailchimp archive etc ...)  of the newsletter.

**Proposed solution**

If the link starts with the character"#", then do not add the target="_blank" attribute.

**Alternative solution**

Adding a "mj-target" attribute.

**Comment by iRyusa** [comment]
Hi @gavrochelegnou 

Well I think most of client doesn't support properly anchor in email ? Like in outlook having something like this would totally break the email layout because href should be a valid link.

**Comment by gavrochelegnou** [comment]
Support for anchors is not that bad : 
https://emaildesign.beefree.io/2016/09/how-to-add-anchor-links-in-email/
And most solutions to compose emails supports it (mailchimp etc ... 
https://kb.mailchimp.com/campaigns/design/add-a-table-of-contents-to-a-campaign )

But whatever the support is for anchor tags, being able to remove/change the target attribute on buttons would be nice.

**Comment by iRyusa** [comment]
Just tested out the anchor and it looks like to works to outlook.com now (only invalid href is removing some content my bad :)

Then we'll see to add a target attribute on mj-button 👍

**Comment by gavrochelegnou** [comment]
Great !
I listed the target attribute as an "alternative" solution, because I don't see any other use case, (i don't imagine mails getting frames/iframes any time soon), and I don't see a use case where a link starting with "#"  would need a target attribute (or anything else than _self). 

That's why i thought that removing the target or setting it to "_self" would be a better solution for any link starting with '#'.

But both solutions can be combined as well.

On the same topic it could be nice to have an `<mjml-anchor name="XYZ" />` tag that generates the `<a name/>` to avoid using the mj-raw :)

Thanks !

**Comment by iRyusa** [comment]
You can already use HTML inside `mj-text` for that, mj-raw would produce non valid html at this time ?

**Comment by gavrochelegnou** [comment]
I currently use  `<mj-raw><a name="nouveautes"></a></mj-raw>` between two `mj-section` and it's working fine. The html output is just `<a name="nouveautes"></a>` as intended.

Puting the anchor inside `<mj-text>` means inside a section / column which is a bad idea for anchors that are often placed before a section. And it is less likely to break the layout on clients if the link is considered invalid.

**Comment by iRyusa** [comment]
As you can see here : https://mjml.io/try-it-live/H1wAC9sVf

The `a` will be in a middle of a table definition that's totally non valid. If the anchor is empty the mj-text won't be displayed anyway ?

**Comment by gavrochelegnou** [comment]
Yes that's why i use it between mj-sections. I think that for anchors it's the most common use case.

But if you need it in the middle of a column then indeed you have to use mj-text but it will add a bunch of useless <div><tr> ...

That's why an mj-anchor component might be a good idea.
It could adapt nicely depending on where it is put.

**Comment by iRyusa** [comment]
Well, you can also do your own component to do that, we have a section to show community components in the doc :) And why not to submit as a PR, people can discuss about the idea.

Imo the current solution is fine, you already have some section/column to your email and it only add an mj-text with some 0 values ( padding/font-size/line-height ) to avoid a side effect.

**Comment by gavrochelegnou** [comment]
Ok i'll have a look
Thanks

**Comment by ngarnier** [comment]
This was released (see https://github.com/mjmlio/mjml/releases/tag/v4.0.2)
