### ISSUE TITLE
Windows 10 Mail background-color support

### ISSUE THREAD

**Issue by rodacato** [mjmlio/mjml#957]
Background color is not working for Windows 10 Mail, this is not a new bug as Mjml 3.3.5 is not working either, and seems this comes from a lack of background color support on Windows 10 Mail.

**Reproduction Steps:**

Convert the following snippet and run it on litmus or a windows 10 mail client.

```
<mjml>
  <mj-body background-color="#ff00ff">
    <mj-section>
      <mj-text>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus sollicitudin enim vel feugiat. Pellentesque a faucibus sapien. 

        Pellentesque cursus ac neque vel faucibus. In leo sapien, iaculis vel cursus quis, malesuada nec ligula. Phasellus gravida nulla at velit imperdiet finibus.
      </mj-text>
    </mj-section>
  </mj-body>
</mjml>
```

**Expected behavior:**

Windows Mail 10 should had the pink-ish color in the background

**Observed behavior:**

From another email campaign with a working background color, seem it is possible to support it by having a table for MSO at full width with the background color property, I managed to make it work as follow:

```
<mjml>
  <mj-body background-color="#ff00ff">
    <mj-raw>
      <!--[if mso | IE]>
        <table
           align="center" border="0" cellpadding="0" cellspacing="0" style="width:100%;background-color: #ff00ff" width="100%"
        >
          <tr>
            <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
        <![endif]-->
    </mj-raw>

    <mj-section>
      <mj-text>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus sollicitudin enim vel feugiat. Pellentesque a faucibus sapien. Nullam volutpat vitae nisi et imperdiet. Nunc vitae ipsum commodo, rutrum nibh ac, pellentesque lorem. Nam semper massa dui, vitae malesuada neque bibendum sit amet. Vivamus quis sapien urna. Morbi vulputate, ligula id ullamcorper vehicula, erat mauris pellentesque sapien, luctus imperdiet nulla risus sed eros. Quisque mollis ante non leo faucibus finibus. Sed sodales sapien hendrerit ipsum consequat, ac faucibus metus porttitor. Vivamus posuere ut augue venenatis bibendum. Donec porttitor porttitor leo, fringilla bibendum mauris imperdiet ut. Fusce eu metus non tellus posuere porta. Curabitur quis maximus ex, sed iaculis odio. Mauris lacinia, tellus id mollis placerat, arcu lacus facilisis ante, ac fringilla felis arcu eget lectus.

        Pellentesque cursus ac neque vel faucibus. In leo sapien, iaculis vel cursus quis, malesuada nec ligula. Phasellus gravida nulla at velit imperdiet finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce ac risus at odio iaculis ultrices vel vitae turpis. Suspendisse porta eleifend quam, a ullamcorper purus lacinia nec. Cras vel lacinia quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      </mj-text>
    </mj-section>

    <mj-raw>
      <!--[if mso | IE]>
          </td>
        </tr>
      </table>
      <![endif]-->
    </mj-raw>
  </mj-body>
</mjml>
```
This may not be the best solution but can give some light to add support for background color on Windows 10 Mail.

**Screenshots and GIFs**

![screen shot 2018-01-19 at 12 54 21 pm](https://user-images.githubusercontent.com/232752/35166574-f075823c-fd17-11e7-81c8-2dffb6f401fb.png)

**MJML version:**

Mjml 4.0.0.alpha5

**Email clients the bug is seen on:**

Windows 10 Mail on Windows 10

**Comment by iRyusa** [comment]
Hi there ! 

Thanks for the fix, did you test your fix into outlook 2000/2003 too? Does it break something else ?

**Comment by rodacato** [comment]
@iRyusa I just ran it on all outlook versions litmus offer, I'm using this fix in production with more mj components without issues, but I only used a few components and I'm still in version 4.0.0.alpha5, so it is hard to say I didn't break anything else.

If you have an email template for regression testing I'm more than happy to run it on litmus and help you to review the output

Here is how they look like right now:
![screen shot 2018-01-23 at 10 54 48 am](https://user-images.githubusercontent.com/232752/35289094-ff2e1ee4-002b-11e8-8d60-f9e49a365451.png)
![screen shot 2018-01-23 at 11 01 48 am](https://user-images.githubusercontent.com/232752/35289408-e08534c2-002c-11e8-9b57-a19d0d1ea16b.png)

**Comment by iRyusa** [comment]
Well the code looks like a `mj-wrapper` full-width and will behave exactly the same I think 🤔 

Did you try it ?

**Comment by rodacato** [comment]
OMG, yeah you were right I just tried that now and look pretty much the same, this is what I used if anyone is interested:

```
<mjml>
  <mj-body background-color="#ff00ff">
    <mj-wrapper background-color="#ff00ff" full-width="full-width">
      <mj-section>
        <mj-text>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean cursus sollicitudin enim vel feugiat. Pellentesque a faucibus sapien. Nullam volutpat vitae nisi et imperdiet. Nunc vitae ipsum commodo, rutrum nibh ac, pellentesque lorem. Nam semper massa dui, vitae malesuada neque bibendum sit amet. Vivamus quis sapien urna. Morbi vulputate, ligula id ullamcorper vehicula, erat mauris pellentesque sapien, luctus imperdiet nulla risus sed eros. Quisque mollis ante non leo faucibus finibus. Sed sodales sapien hendrerit ipsum consequat, ac faucibus metus porttitor. Vivamus posuere ut augue venenatis bibendum. Donec porttitor porttitor leo, fringilla bibendum mauris imperdiet ut. Fusce eu metus non tellus posuere porta. Curabitur quis maximus ex, sed iaculis odio. Mauris lacinia, tellus id mollis placerat, arcu lacus facilisis ante, ac fringilla felis arcu eget lectus.

          Pellentesque cursus ac neque vel faucibus. In leo sapien, iaculis vel cursus quis, malesuada nec ligula. Phasellus gravida nulla at velit imperdiet finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce ac risus at odio iaculis ultrices vel vitae turpis. Suspendisse porta eleifend quam, a ullamcorper purus lacinia nec. Cras vel lacinia quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        </mj-text>
      </mj-section>
    </mj-wrapper>
  </mj-body>
</mjml>
```

way cleaner, thank you @iRyusa, mystery solved.

**Comment by iRyusa** [comment]
I think as Windows 10 Mail has pretty low usage, the wrapper solution is a good trade-off (not adding complexity in the produced html, and if you really need it, then the wrapper is the go-to) 

I'm closing the issue then !
