### ISSUE TITLE
Set default padding to 0

### ISSUE THREAD

**Issue by frenchie4111** [mjmlio/mjml#96]
I am using MJML to style some emails, it is very frustrating to have to set padding="0" on all elements (mj-content, mj-text, mj-image). Why is the padding not defaulted to 0?

**Comment by arnaudbreton** [comment]
Hey @frenchie4111, thanks for sharing feedback.

You should have a look at #79 which provide a solution to provide global attributes definition, avoiding the need of repeating the attribute for every single element. 

> Why is the padding not defaulted to 0?
We made that choice from the beginning to ease the onboarding with MJML and quickly reach a point where templates looks great. Obviously, that's something we'll revisit if it raises too many issues for you guys.

Please let us how #79 looks like to you.

Thanks!
Happy coding with MJML.

**Comment by frenchie4111** [comment]
That's fine. I left my feedback on #79. I am going to close this issue.
