### ISSUE TITLE
mjml-group pixel width not behaving as expected

### ISSUE THREAD

**Issue by mattlub** [mjmlio/mjml#962]
**Desired/expected behavior:**
- behaviour would be similar to setting fixed width on a column

**Observed behavior:**
- Setting any pixel width on an `mjml-group` seems to make the group fill 100% width (on desktop).
- curiously if both groups have widths set to `300px` (equiv. to 50%) then they will display inline
- (using % widths produces expected behaviour)

```html
<mjml>
  <mj-body>
    <mj-container>
      <mj-section border="1px solid black">
        <mj-group width="200px">
          <mj-column>
            <mj-text align="center">
              <p>Write less code, save time and code more efficiently with MJML’s semantic syntax.</p>
            </mj-text>
          </mj-column>
          <mj-column>
            <mj-text align="center">
              <p>Write less code, save time and code more efficiently with MJML’s semantic syntax.</p>
            </mj-text>
          </mj-column>
        </mj-group>
        <mj-group>
          <mj-column>
            <mj-text align="center">
              <h2>Easy and quick</h2>
              <p>Write less code, save time and code more efficiently with MJML’s semantic syntax.</p>
            </mj-text>
          </mj-column>
        </mj-group>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hi @mattlub 

Well, i've found this one while porting mj-group into MJML4, now it's no longer the case. For curious reasons, mj-group was converting `px` to `%` producing a wrong class name for the mj-group. 

I'm closing this issue because it's only affected by MJML3 and there's a workaround to avoid it

**Comment by mattlub** [comment]
@iRyusa ok cool. What's the workaround?

**Comment by iRyusa** [comment]
> (using % widths produces expected behaviour)

As you said :)
