### ISSUE TITLE
mj-divider doesn't render padding if not in mj-column

### ISSUE THREAD

**Issue by kud** [mjmlio/mjml#965]
I want to use `mj-divider` with some padding but the padding isn't rendering if the element isn't in a `mj-column`.

My layout is like that:

```
<mjml>
  <mj-head>
    <mj-title>{% block title %}{% endblock %}</mj-title>
    {% include "../fonts/open-sans.mjml" %}
    {% include "../styles/attributes.mjml" %}
    {% include "../styles/ui.css" %}
    {% include "../styles/layout.css" %}
    {% block css %}{% endblock %}
  </mj-head>

  <mj-body>
    <mj-container css-class="Container">
      <mj-section css-class="Header" padding="0">
        {% block header %}{% endblock %}
      </mj-section>

      <mj-section css-class="Content" padding="0">
        {% block content %}{% endblock %}
      </mj-section>

{...}
```

_please, do not watch nunjucks templating here_ 

If I add an `mj-column` on the `mj-section`, my `mj-divider` will get `padding`. If there's only `mj-section`, it won't. Is it normal?

However, it displays well the grey line.

**Reproduction Steps:**

Add a `mj-divider` only in a `mj-section`, no `mj-column`

**Expected behavior:**

I'd like to see padding on the `mj-divider`

**Observed behavior:**

No padding

**Screenshots and GIFs**

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/655838/35343400-d77a8ffe-012a-11e8-9cae-372dbb9a7efd.png">

**MJML version:**

3.3.5

**Comment by iRyusa** [comment]
Hi, 

Yep this is totally legit, padding attribute is inherited by being placed into a column, content element like divider/text/image/... should live inside a column. It appears as an error when you validate through the cli your MJML.

**Comment by kud** [comment]
I don't get any error here, but probably because I use gulp there.
Well ok, I'll add a mj-column so, even if I've got only one column in my section.

Maybe we should add in the doc the dependance of each component
