### ISSUE TITLE
mjml misses extend/block feature

### ISSUE THREAD

**Issue by kud** [mjmlio/mjml#966]
I often use template engines like jinja2/twig/django and mjml clearly misses feature like `extend` and `block`.

I had to add nunjucks on my project to have this.

**Comment by iRyusa** [comment]
Hi,

As stated multiple times, MJML isn't a templating language so it wouldn't feature such thing. We have a `mj-include` that allow file import ( with both mj-head/mj-body ) You can find a more detailed answer here : #558 by @ngarnier

**Comment by kud** [comment]
Okay I understand. However `mj-include` makes things unclear about what mjml does so.

Maybe a line about that on the doc could be great like what mjml is and is not.

**Comment by Shyam-Chen** [comment]
I use `posthtml-include` instead of `mj-include`, and `posthtml-extend` for `extends` and `block`.

Transpiles: `posthtml` -> `mjml` -> `html`
