### ISSUE TITLE
Open-source live editor?

### ISSUE THREAD

**Issue by fouad** [mjmlio/mjml#97]
Hey there!

This is an awesome project and I'd love to contribute to/self-host the live editor. Would it be possible to open-source the code for that?

Thanks :)
Fouad

**Comment by meriadec** [comment]
Hey! This is already a work in progress, and it will be open sourced soon, after implementing the basics.
Thanks for the input, we'll be happy to have your contribution!

**Comment by codeskyblue** [comment]
+1

**Comment by meriadec** [comment]
Hi guys, we just released a first version of the desktop mjml editor: https://github.com/mjmlio/mjml-app
Still a lot of work to do, it has actually those features:
- create template from scratch / from a preset
- edit with live reloading
- preview in desktop + mobile
- send a test email (with [Mailjet](https://www.mailjet.com/) API keys)
- create a gist from template

Feedbacks are welcome :p

**Comment by codeskyblue** [comment]
nice

**Comment by evstratbg** [comment]
Hi there! Any news about live editor?

**Comment by iRyusa** [comment]
We're not confident about open-source the live editor due to the infrastructure. We've open-sourced the desktop app which can be used as a base for a web editor.

**Comment by evstratbg** [comment]
ok, thank you

**Comment by petrbela** [comment]
For those looking for a wysiwyg live editor, GrapesJS might be a good alternative. https://grapesjs.com/demo-mjml.html
