### ISSUE TITLE
Error thrown when attempting to parse <mj-attributes> via node/grunt

### ISSUE THREAD

**Issue by laurenhamel** [mjmlio/mjml#985]
I've been working on a project that uses [grunt-mjml](https://github.com/smbeiragh/grunt-mjml) to build some email templates, and I'm attempting to upgrade this module to use MJML 4. When passing templates through Grunt, the `mjml` dependency seems to be throwing an error when trying to parse`<mj-attributes>`. However, when using `mjml-cli`, I do not get this error.

**Reproduction Steps:**

1. Include some `<mj-attributes>...</mj-attributes>` in a template.
2. Load the parser in Node.js/Grunt task via `var mjml2html = require ('mjml')`.
3. Attempt to run the template containing `<mj-attributes>` through `mjml2html()`.

**Expected behavior:**

The template should easily parse without throwing errors.

**Observed behavior:**

The `mjml2html` operation returns an object that includes errors, such as `{html: "...", errors: [ true ]}`, and I receive the following error via command line from modified `grunt-mjml`:

```
Fatal error: [
    true
]
```

**MJML version:**

4.0.0-beta.1

**Comment by iRyusa** [comment]
Hi @laurenhamel 

Can you try with the beta 2 if this is still a thing ? Can you provide a git repo to reproduce the issue, it would be easier to debug for us !

Thanks

**Comment by laurenhamel** [comment]
This is the fork of the [grunt-mjml](https://github.com/laurenhamel/grunt-mjml/) repo that I've been working on. I upgraded dependencies to use beta 2 but still no dice. I also recently updated the tests, which I'm noticing is failing with the following error when `<mj-attributes>` is used: `Fatal error: Cannot read property 'handler' of null`

**Comment by iRyusa** [comment]
Thanks a lot ! @kmcb777 will check that 👍

**Comment by kmcb777** [comment]
Hi @laurenhamel 
I made a few tests with your fork, and it seems like the 'Fatal Error' is thrown manually in the gulp task if there has been any validation error.
There was actually a validation bug, resulting in the mj-attributes validation returning 'true' as an error, so thanks for pointing this out.
On the other hand i think `Cannot read property 'handler' of null` has been fixed in beta 2.

**Comment by kmcb777** [comment]
fixed in https://github.com/mjmlio/mjml/commit/f686863ca27b02d3c071478c37f18586cf252dd2

**Comment by kmcb777** [comment]
@laurenhamel for information, it was actually still possible to have the "Cannot read property 'handler'" error when using unrecognized tag in <head> (i got it by putting some mj-class in head but outside of mj-attributes).
Now it will ignore the tag and log a warning instead of crashing.
