### ISSUE TITLE
Container not left aligned in Outlook

### ISSUE THREAD

**Issue by jerrysam** [mjmlio/mjml#988]
I'm creating an Email signature to be used primarily in outlook, and it's not rendering very well. The issue I'm facing is that I can't left-align the output, and it seems now like MJML might just not be built to do this. Is it possible to left align the entire body?

The only hack I've used is to make the container "full width" and then align the contents to the left. However, in Outlook that "100% width" becomes fixed to the screen width in the sender's computer, causing users with a smaller screen to need to scroll left & right in their inbox (not ideal!)

Is it possible to left align the entire body, whilst keeping a max-width on the whole email?

**Full code:**
```
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text align="left" />
      <mj-class name="leftAlign" align="left" text-align="left" style="text-align:left; align:left; margin-left:10px;" />
      <mj-class name="emailWidth" width="320px" style="width: 320px;"/>
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container mj-class="emailWidth leftAlign">
      <mj-section padding="0" mj-class="leftAlign">
      <!-- Header section -->
        <mj-column mj-class="leftAlign">
          <!-- first column -->
          <mj-text font-size="18px" padding="2px" color="#C3002F" font-weight="700">
              <!-- Name -->
              Full Name
          </mj-text>
          <mj-text font-size="16px" padding="2px" font-weight="300">
              <!-- Job Title -->
              Position
          </mj-text>
          <mj-text font-size="14px" color="#C3002F"  padding="12px 2px 0 2px"  font-weight="700">
              Rockpool Investments
          </mj-text>
        </mj-column>
      </mj-section>

      <mj-section padding="8px 0 0 0" mj-class="leftAlign">
      <!-- Information section -->          
          <mj-column mj-class="emailWidth leftAlign">
            <mj-table padding="0 0 10px 0" font-size="12px" mj-class="emailWidth">
              <tr style="height:12px;">
                <td rowspan="3" style="padding: 0 20px 0 0;">
                  <img align="left"  width="60" style="width:60px;height:60px;margin: 0; border: 0; padding: 0; display: block;" src="https://image.ibb.co/kEyndx/Rockpool_Logo.png">
                </td>
                <td style="width: 20px;">
                  <span style="color:#C3002F;font-weight:700;">D</span>
                </td>
                <td style="width: 120px;">
                  Direct Line
                </td>
                <td style="width: 120px;">
                  10 Bressenden Place
                </td>
              </tr>
              <tr style="height:12px;">
                <td style="width: 20px;">
                  <span style="color:#C3002F;font-weight:700;">T</span>
                </td>
                <td style="width: 120px;">
                  Telephone
                </td>
                <td style="width: 120px;">
                  London SW1E 5DH
                </td>
              </tr>
              <tr style="height:12px;">
                <td style="width: 20px;">
                  <span style="color:#C3002F;font-weight:700;">M</span>
                </td>
                <td style="width: 120px;">
                  Mobile
                </td>
                <td style="width: 120px;">
                  rockpool.uk.com
                </td>
              </tr>
            </mj-table>
          </mj-column>
      </mj-section>

      <mj-section padding="10px 0" mj-class="leftAlign">
      <!-- Legal section -->
        <mj-column mj-class="emailWidth leftAlign">
          <mj-text font-size="9px" font-style="italic"  padding="0px" line-height="15px">
            Rockpool Investments LLP is registered in the UK (OC369009) and is authorised and regulated by the Financial Conduct Authority.
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>


```

<img width="1353" alt="screen shot 2018-02-05 at 13 56 09" src="https://user-images.githubusercontent.com/4795545/35808084-a48c3cd6-0a7c-11e8-95a5-677b242bf076.png">

**MJML version:**
version 3.3.5

**Email clients the bug is seen on:**
Sender: Outlook
Recipient: Gmail

**Secondary bugs (bonus points for solving**
1. Table column widths default to 100% in the above (Outlook -> Gmail) case - is there a solution to this?
2. Image dimensions are converted to Inches, and made smaller - is there a way to fix image widths in the HTML pasted into Outlook?
3. Image are attached to the email - is there a way to prevent Outlook from attaching the image separately?
4. This may be solved by solving the Primary bug of this post, but: The italic text at the bottom of the signature in the screenshot attached goes full-width, even though in the code supplied the width is limited, and it should break into two rows - is there a way to force the width attribute to apply in Outlook?

**Comment by ngarnier** [comment]
Indeed, MJML isn't built to do that. MJML's approach is using the fluid-hybrid and mobile-first methods, which requires to have a fixed-width container (where your content will be... contained). 

Does your signature involve a lot of responsive behaviour? Seems like a simple table could do the trick here.

**Comment by jerrysam** [comment]
Thanks @ngarnier - No, I've abandoned the responsive approach, and would be happy if a simple table worked.
How do you suggest structuring it? Just to have the entire signature in one table?

**Comment by ngarnier** [comment]
From your screenshot, I would say:
- the beginning is just text, so just use HTML text/paragraph
- the part where a table is needed, made of 1 row, 3 columns, with each columns being made of 3 rows except the first that is only one row (the logo)
- the end is just text, so just use HTML text/paragraph

I'm closing then!

**Comment by jerrysam** [comment]
Hey @ngarnier - it seems I missed the point with my last comment:
Can you confirm whether it's possible or not to left align this email signature? If so, what attributes to I need to add to my (or your suggested) layout to achieve this?

Here's my implementation of your suggestion (not sure if I got the table setup right): [https://mjml.io/try-it-live/H18lkeLUz]

**Comment by ngarnier** [comment]
I meant: do this with HTML directly, MJML isn't bringing much here. Basically, turn your `mj-text` into `p` and `mj-table` into `HTML`.

**Comment by jerrysam** [comment]
Oh, I see! Ah that's a shame - after all this I'm going Vanilla - feels kinda dumb of me :P

Well, let me leave you with a compliment: I loved your documentation, getting started tutorial, and try-it-live tool. Thanks!
