### ISSUE TITLE
New mj-social in mjml 4 docs

### ISSUE THREAD

**Issue by IchordeDionysos** [mjmlio/mjml#991]
I saw in the mjml release notes for mjml 4, that mj-social has a new structure to use, but here on the doc there is still the old version https://github.com/mjmlio/mjml/blob/next-doc/doc/advanced.md
Shouldn't it use the new way?

**Comment by ngarnier** [comment]
Indeed, you can see the new structure in the documentation for mj-social: https://github.com/mjmlio/mjml/tree/next-doc/packages/mjml-social 

Docs from guides like the one you linked still need to be updated though. Feel free to make a PR!

**Comment by IchordeDionysos** [comment]
https://github.com/mjmlio/mjml/blob/next-doc/doc/basic.md
For completeness that I won't forget it later :)

**Comment by IchordeDionysos** [comment]
Done

**Comment by IchordeDionysos** [comment]
Can be closed, I think
