### ISSUE TITLE
[Feature Request] Prevent default centered layout

### ISSUE THREAD

**Issue by nagman** [mjmlio/mjml#995]
Hi,

It would be nice to prevent the default behavior that displays the email in a 600px wide centered box.
In my case, I need to have a 600px wide left aligned layout.
Because I'm creating an email signature in mjml and it must be aligned with the rest of the email's body.

Is this something achievable with the current version of MJML?

Thanks!

**Comment by ngarnier** [comment]
Hi @nagman, 

Unfortunately that's impossible, as explained on other issues. Have a look for example at https://github.com/mjmlio/mjml/issues/988#issuecomment-363095162.
