### ISSUE TITLE
mjml-raw does not render content

### ISSUE THREAD

**Issue by barkap** [mjmlio/mjml#996]
Hello,

`mjml-raw` component is broken.

**mjml:**
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-raw>
        <p>content</p>
      </mj-raw>
    </mj-container>
  </mj-body>
</mjml>
```

**expected output:**
```
<body>
  <div class="mj-container">
    <p>content</p>
  </div>
</body>
```

**actual output:**
```
<body>
  <div class="mj-container"></div>
</body>
```

The issue can also be observed [here](https://mjml.io/try-it-live/components/raw) (link from the documentation).

MJML v3.3.5 (current online version)

**Comment by dalefish** [comment]
Could be something to do with React. Can you try with the html encoded (&gt
&lt) and see how it goes?

**Comment by ngarnier** [comment]
This issue is fixed in MJML 4 and renders the expected output. We won't fix MJML 3.x.x anymore, so please upgrade with `npm install mjml@next`. 

As stated by @dalefish, encoding the HTML entities should work too.

**Comment by larswittenberg** [comment]
Thanks. The workaround with HTML entities works for me.
MJML version 3.3.5.
