### ISSUE TITLE
Add email icon to mj-social

### ISSUE THREAD

**Issue by maxgironcodes** [mjmlio/mjml#997]
Just discovered the `<mj-social>` tag. It's quick and useful :) I'm building a newsletter where users can send specific articles to others by email. Unfortunately, there isn't an email icon available. I can add it myself in HTML, but I figured there may be others who might need it, too. Could we get an email icon option?

**Comment by ngarnier** [comment]
Hey @maxgironcodes, there's an easy way to add your own custom icon to `mj-social`: look at the second blue highlighted block in the documentation: https://mjml.io/documentation/#mjml-social. 

I think that should enable you to add the icon you wish without having to do it in HTML?

**Comment by maxgironcodes** [comment]
@ngarnier Durhh, somehow I missed that >_< thanks for the quick reply!
