### ISSUE TITLE
Razor with MJML

### ISSUE THREAD

**Issue by Jacorr** [mjmlio/mjml#999]
I try to use Razor with HTML mail templates generated from MJML. Everything works good, but there is some problem in HEAD section, because of rendering tags started with @ char (@media, @viewport), which is restricted for Razor. I get such error like below. 

Is it possible to return doubled @@ for media (Razor can resolve it) or there is special way to cooperate with Razor or such feature is planned for future?

**RazorEngine.Templating.TemplateParsingException : (22:5) - "-" is not valid at the start of a code block.  Only identifiers, keywords, comments, "(" and "{" are valid.**

```
<!--[if !mso]><!-->
<style type="text/css">
  @media only screen and (max-width:480px) {
    @-ms-viewport { width:320px; }
    @viewport { width:320px; }
  }
</style>
```

**Comment by iRyusa** [comment]
Hi @Jacorr 

Sorry about that but I have no idea how we can do that, only solution I would see is to create a post-render task with gulp or something that replace it for you. But I don't think this is the job of MJML here

**Comment by rogierslag** [comment]
You probably want to run Razor over your MJML, and only they export the MJML to HTML

**Comment by graycrow** [comment]
@Jacorr If you solved this issue, could you please let me know how you did it? Thank you.
